### ISSUE TITLE
Support for composer v2 and PHP 8.0 - any plans?

### ISSUE THREAD

**Issue by vladaman** [freescout-helpdesk/freescout#1002]
I wonder if there is any plan to support composer v2 and PHP 8.0 since PHP v 7.3 is currently end of life, 7.4 will end by end of 2021.

#616 #432 #831

**Comment by freescout-helpdesk** [comment]
Both - end of 2021.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/releases/tag/1.7.0

**Comment by freescout-helpdesk** [comment]
PHP 8 support added. Now minimum supported PHP version is 7.1
https://github.com/freescout-helpdesk/freescout/releases/tag/1.7.0

When using composer and PHP 8, composer should be executed with additional flag: `composer install --ignore-platform-reqs`

@tiredofit
@nebulade

**Comment by nebulade** [comment]
Thanks for the heads up, we have updated our package to 1.7.0 now.

**Comment by amanpatel** [comment]
I'm using this on PHP 8 (via the docker pkg from "tiredofit").  On some email messages I get the whoops message:

```[2021-05-19 18:27:56] production.ERROR: Undefined property: DOMComment::$data (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) {"userId":1,"email":"aman.patel@resonancehealth.org","exception":"[object] (ErrorException(code: 0): Undefined property: DOMComment::$data (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) at /www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php:216, ErrorException(code: 0): Undefined property: DOMComment::$data (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) at /www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php:216, ErrorException(code: 0): Undefined property: DOMComment::$data (View: /www/html/resources/views/conversations/partials/thread.blade.php) at /www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php:216, ErrorException(code: 0): Undefined property: DOMComment::$data at /www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php:216)
```

Updating the DomLex.php file to check for properties via isset() or ?? operator seems to fix it.

I don't think this is related to PHP 8

**Comment by freescout-helpdesk** [comment]
@amanpatel Could you please attach patched file.

**Comment by amanpatel** [comment]
@freescout-helpdesk  Great question. I created PR in that package.

https://github.com/ezyang/htmlpurifier/pull/292

However, I am not sure if there are similar issues in other places in this package. But this seems to have alleviated for me. I just setup my Freescout install about 2-3 days ago and have tested with approximately 8 or 9 emails. If it breaks again, I'll update the PR.
