### ISSUE TITLE
How to install to a subdirectory in nginx environment

### ISSUE THREAD

**Issue by kometchtech** [freescout-helpdesk/freescout#1005]
There was an issue ( #87 ) in the past that mentioned installing in a subdirectory with Apache, but I would like to know how to install in a subdirectory with nginx.

I've done some research on the web on the combination of nginx, laravel and php, but I couldn't find the best solution in freescout.

**Comment by freescout-helpdesk** [comment]
It should work in a subdirectory out of the box. Just make sure to enter proper App URL when installing.

**Comment by EugeneDae** [comment]
@kometchtech Could you please share your nginx config for subdirectory install?
