### ISSUE TITLE
Notifications not sending to all ticket users

### ISSUE THREAD

**Issue by imennodenis** [freescout-helpdesk/freescout#1006]
Hi!

I think there is some strange behavior with ticket notifications by email.
When a ticket has several users in Copy filed and admin replies this ticket from browser then email notification with admin's reply is sent just fine to all CC'd users.
But when admin or user replies to the ticket by email then only ticket creator and ticket admin gets this reply.

I think ALL ticket users and admins should get ALL replies as email notifications.
There are pretty much situations when ticket concerns several users and all of them must be aware of what's happening regarding their problem.

For me the ideal notifications model is implemented in Spiceworks.
There are "CC'd users" and "CC'd admins" in notifications settings and I can select to send notification to any of them. So if ticket has several users in recipients field then notifications can be sent to all of them. Also if ticket has several admins assigned then notifications is also sent to all of them when any users replies ticket by email. Here is a more detailed description: https://community.spiceworks.com/support/help-desk/docs/email-notifications
Maybe you will like their implementation too and make some changes in Freescout :)

Thanks!

**Comment by freescout-helpdesk** [comment]
It's by design. Notification received by users says:

![2023-02-14_16-52-13](https://user-images.githubusercontent.com/40499291/218758015-5aa6fa9d-4b05-4b50-b77e-a1d0024fe053.png)
