### ISSUE TITLE
Permissions Issue. Can't use symlink

### ISSUE THREAD

**Issue by shiroi2003** [freescout-helpdesk/freescout#1008]
Hey,
I'm trying to do a new installtion but as it's a shared hosting I'm not authorized to create symbolic links.

![image](https://user-images.githubusercontent.com/2958083/105178899-65750a80-5b07-11eb-947e-ddf649d10f04.png)

Because of that I'm facing issues with /vars.js

![image](https://user-images.githubusercontent.com/2958083/105178717-2e065e00-5b07-11eb-844f-ec4df0f5eb13.png)

There's a workaround like create all symbolic links manually? I mean which symbolic links I have to create?

**Comment by freescout-helpdesk** [comment]
ln -s /var/www/html/storage/app/public public/storage

**Comment by shiroi2003** [comment]
I tried that but didn't worked.

The solution was go to Cpanel > PHP Version > Options > Remove "symlink" from disable_functions.

Then I run php artisan storage:link

Worked! :) 

Thx
