### ISSUE TITLE
[Feature request] artisan schedule:run via GET-Request (Webbrowser)

### ISSUE THREAD

**Issue by Servery** [freescout-helpdesk/freescout#1009]
It would be nice to have an alternative to the cronjob via PHP exec: `php artisan schedule:run`

Here is an example for Laravel tu run artisan:run via GET Request: [https://simple-web.dev/the-laravel-scheduler-without-cronjobs#setup-a-get-route-for-the-scheduler](https://simple-web.dev/the-laravel-scheduler-without-cronjobs#setup-a-get-route-for-the-scheduler)

Then it would be possible to use a service link: www.easycron.com, www.cronless.com, ...

What do you think?

**Comment by freescout-helpdesk** [comment]
The app will not work properly, as `schedule:run` need to run never-ending `queue:work` job:
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L148

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1452#issuecomment-933409280
