### ISSUE TITLE
Replies to customer indicate that support was the one to open the ticket

### ISSUE THREAD

**Issue by astupidmoose** [freescout-helpdesk/freescout#101]
When a support agent replies to a ticket, the reply contains the original message, however, the original message is marked as coming from the support system and not the customer. 

This can be confusing as it doesn't accurately convey who opened the ticket in the replies. 

![tempsnip](https://user-images.githubusercontent.com/3916318/48219350-23ee4f80-e341-11e8-99af-03d82c029f0f.png)

**Comment by freescout-helpdesk** [comment]
Looks like a bug. Will check this.

**Comment by freescout-helpdesk** [comment]
Fixed https://github.com/freescout-helpdesk/freescout/commit/6b260bb10471362ae580e266fb73bc0327abd991
