### ISSUE TITLE
Feature suggestion for Notifications Module: Disable for Workflows

### ISSUE THREAD

**Issue by centralplexus** [freescout-helpdesk/freescout#1012]
Hi there,

I have a small feature suggestion, is it possible to make Workflow notifications an option in the notification settings? For us they are quite dedundant as the conversations themselves give off their own notifications anyway.

Thanks and keep it up, we're really liking this system above any other!

**Comment by freescout-helpdesk** [comment]
Could you please give an example of such notification.

**Comment by centralplexus** [comment]
I'm getting two notifications, one called Workflow XY and another one from the message triggering the workflow. What format do you prefer the example in, like a screenshot?

**Comment by freescout-helpdesk** [comment]
Closed as out of scope.
