### ISSUE TITLE
Fetch doesn't complete, error in create customer

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#1013]
Hello guys!

I have one pending email in my mail client and everytime FreeScout tries to fecth emails I get this error in my console and no email is fetched therefore no ticket is created.

`Call to a member function setData() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setData() on null at /XXXX/YYYY/public_html/helpdesk/app/Customer.php:894)
[stacktrace]`
`#0 /XXXX/YYYY/public_html/helpdesk/app/Console/Commands/FetchEmails.php(1034): App\\Customer::create('SOME_EMAIL@hotmai...', Array)`
`#1 /XXXX/YYYY/public_html/helpdesk/app/Console/Commands/FetchEmails.php(479): App\\Console\\Commands\\FetchEmails->createCustomers(Array, Array)`
`#2 /XXXX/YYYY/public_html/helpdesk/app/Console/Commands/FetchEmails.php(213): App\\Console\\Commands\\FetchEmails->processMessage(Object(Webklex\\IMAP\\Message), '20210123212841....', Object(App\\Mailbox), Object(Illuminate\\Database\\Eloquent\\Collection))`
`#3 /XXXX/YYYY/public_html/helpdesk/app/Console/Commands/FetchEmails.php(90): App\\Console\\Commands\\FetchEmails->fetch(Object(App\\Mailbox))`
`#4 [internal function]: App\\Console\\Commands\\FetchEmails->handle()`
`#5 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)`
`#6 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()`
`#7 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))`
`#8 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)`
`#9 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)`
`#10 /XXXX/YYYY/public_html/helpdesk/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))`
`#11 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))`
`#12 /XXXX/YYYY/public_html/helpdesk/vendor/symfony/console/Application.php(963): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))`
`#13 /XXXX/YYYY/public_html/helpdesk/vendor/symfony/console/Application.php(254): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\FetchEmails), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))`
`#14 /XXXX/YYYY/public_html/helpdesk/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))`
`#15 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))`
`#16 /XXXX/YYYY/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))`
`#17 /XXXX/YYYY/public_html/helpdesk/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))`
`#18 {main}
"}`

![Untitled](https://user-images.githubusercontent.com/39450586/105618774-d9ded080-5dc9-11eb-8ab6-c5f52564c6a4.png)
![01](https://user-images.githubusercontent.com/39450586/105618784-009d0700-5dca-11eb-9903-37bc533e5f1e.png)

Thank you for your help.

**Comment by diguinho2018** [comment]
Just deleted all opened emails messages and tried again with new email message but no success.
Any advice @freescout-helpdesk?
Thank you.

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the master branch.

**Comment by diguinho2018** [comment]
Wooray!
Thank you for your attention.

**Comment by diguinho2018** [comment]
Is there any way to update the app by simply downloading the master branch from github and uploading via FTP replacing old files? Will it work?

I checked the updating options but didn't find it.

**Comment by freescout-helpdesk** [comment]
Yes. You can just download the code and replace it.

**Comment by diguinho2018** [comment]
Thank you!
That did solve the issue!

**Comment by diguinho2018** [comment]
I don't know why we received this error (no customer) but I noticed that for some reason FreeScout creates the user with no email address and if we use the email shortcode to call for username it won't be displayed.

**Comment by diguinho2018** [comment]
Hey guys, any ideas on this?
@freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
Nope. You may need to debug it yourself.

**Comment by diguinho2018** [comment]
But this has something to do with how FreeScout reads and collects email data.. how can I debug that myself..?
The thing I know is that if we send the email using mailgun it creates ticket and user with no user and no email address (even though there is all that info in original email message) and if we send without passing through mailgun it creates ticket and data the right way.

**Comment by diguinho2018** [comment]
I think I found the issue @freescout-helpdesk.

Did some debug and after some testing I found that:
1- send one email (first email from customer);
2- FreeScout adds the right way;
3- Delete that user;
4- Send another email using the same email and customer name;
5- FreeScout won't add customer and won't display it's data;
6- Go to Customer page and try to add customer with same e-mail and name, FreeScout will say that there is already an user with that email even though there isn't.

Could you check it?

**Comment by diguinho2018** [comment]
Hey @freescout-helpdesk, as referenced above the issue is that if the customer is deleted it keeps in the database, updating to the latest version did not solve the issue.

https://github.com/freescout-helpdesk/freescout/issues/1013#issuecomment-772124087

Could check?

**Comment by freescout-helpdesk** [comment]
Fetching has been fixed. For other issues create a separate issue.
