### ISSUE TITLE
After certain custom folders My tickets change position

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1016]
Hi guys,

After a certain amount of custom folders my tickets change from position.
https://www.dropbox.com/s/31htm27aat3wahi/Schermafbeelding%202021-01-26%20om%2016.10.44.png?dl=0

We need a lot of custom folders and now with an amount of 11 our tickets (Mine) changes location.

**Comment by joris85** [comment]
Looks like you guys found a fix because it is working with the latest version

**Comment by freescout-helpdesk** [comment]
Yes.
