### ISSUE TITLE
Sections, tags, folders or categories in Custom folders

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1017]
Hi guys,

Because we want a lot of custom folders we would love to have sections in the custom folders.
Lets say couple different folders for one customer because it is so big.

Is this something in the scope or should i build that and send you a pull request?
Thanks!

**Comment by freescout-helpdesk** [comment]
It's not quite clear what is needed.

**Comment by joris85** [comment]
Folders and subfolders. 
So i can open and close folders with subfolders. 
So you can have more custom folders (:

**Comment by freescout-helpdesk** [comment]
No plans for now.
