### ISSUE TITLE
Content-ID for attachments

### ISSUE THREAD

**Issue by sebclemens** [freescout-helpdesk/freescout#1018]
Hello,

via API call I want to send an email with attachments and embed those as images in my mail body with content id as reference. Unfortunaley there is no Content-ID for attachments. How can I get it included?

**Comment by freescout-helpdesk** [comment]
Maybe it will be possible in the future.

**Comment by freescout-helpdesk** [comment]
Use src in base64  format to add images to the body: https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html
