### ISSUE TITLE
Customer Tags

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#1019]
Does anybody need a Customer Tags module?

**Comment by sebclemens** [comment]
I would love to see customer tags like conversation tags. At the moment I'm using customer fields to categorize i.e. "customers" or "supplier"

**Comment by diguinho2018** [comment]
That would be great.

**Comment by innov2e** [comment]
It would be nice if customer tag could be used also as filter for customer folder and to select saved replies.
i.e. 
1) to a saved reply I assign cutomer tag A and B. all conversation with customer tagged A or customer tagged B could use such saved reply
2) I assign to the customer foder MyFolder-A  all conversation with conversation tag X in status Active related to customer tagged A

**Comment by freescout-helpdesk** [comment]
Seems to be not much needed for now
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/335595
