### ISSUE TITLE
Search function going Whoops on postgres 13.1

### ISSUE THREAD

**Issue by endoflevelboss** [freescout-helpdesk/freescout#1020]
Attached two stacktraces after using the search function when using postgres 13.1 as db backend.

Installed modules: CRM, Custom Fields, Custom Folders, Customozation, End User Portal, Saved replies, Tags, Time Tracking, Workflows.

Did some basic investigation and found that postgres is less forgiving than mysql on these two particular statements. A typecast when comparing the search string to the int database column value makes the first statement valid. The second statement can be fixed by replacing the "select *" with the actual fields used for grouping. 

Did not find the particular code location to fix these statements by myself. Buried too deep under layers of framework. Any pointer or patch would be highly appreciated.

[laravel-2021-01-27.log](https://github.com/freescout-helpdesk/freescout/files/5885928/laravel-2021-01-27.log)
[laravel-2021-01-28.log](https://github.com/freescout-helpdesk/freescout/files/5885929/laravel-2021-01-28.log)

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Fields Module v1.0.6.

**Comment by fulldecent** [comment]
Recommending to close issue
