### ISSUE TITLE
Email de-duplication

### ISSUE THREAD

**Issue by endoflevelboss** [freescout-helpdesk/freescout#1021]
Suggesting a feature (module?) to de-duplicate emails.

Putting everybody on the planet on CC is worst practice unfortunately. Users may be members of group mail addresses. Emails sent to the recipient and the group mailbox at the same time will have the same message delivered to two or more  mailbox at the same time. 

freescout could cure this easily by checking for the message ID in all mailboxes visible to the particular recipient and stop delivery if the message already is visible to the recipient somewhere else.

To make this feature even more useful, one could define a priority for delivering messages to particular mailboxes. Putting group folders first could be a great way to avoid duplicates in personal mailboxes and creating double communications.

**Comment by sebix** [comment]
That's already there as bug: https://github.com/freescout-helpdesk/freescout/issues/1352

**Comment by freescout-helpdesk** [comment]
Closing as out of scope.
