### ISSUE TITLE
Make "Email the Customer" action also send emails to people on CC

### ISSUE THREAD

**Issue by holtgrewe** [freescout-helpdesk/freescout#1022]
The "Email the Customer" action currently on replies to the customer in our installation.

It would be good and more natural if the action would work just like replying to the ticket (at least as an opt-in action).

**Comment by freescout-helpdesk** [comment]
You are probably talking about Workflows module?

**Comment by holtgrewe** [comment]
Yes.

**Comment by freescout-helpdesk** [comment]
"Reply to Conversation" action added in Workflows Module v1.0.42
