### ISSUE TITLE
Error editing translations

### ISSUE THREAD

**Issue by kometchtech** [freescout-helpdesk/freescout#1024]
I'm trying to migrate the language files I'm translating to a different environment.

**issue**

- If you simply replace the language file (`ja.json`), the file itself will be read and displayed in the translated language, but you will not be able to modify it (an error message will be displayed).
- Nothing special is output to the log.

**conditions**

- This is still too low quality to publish.
- I need to start over in a new environment because the one I'm currently using will be unusable for some reason.

**env**
- Freescout 1.6.13
- nginx 1.19.3
- php 7.3.26

**Comment by freescout-helpdesk** [comment]
Can you use "Manage > Translate" page to make translations?

> you will not be able to modify it (an error message will be displayed)

What does it mean? Which error?

**Comment by kometchtech** [comment]
The steps I'm working on are as follows

1. Add Japanese from the translation page.
2. Run import.
3. Place the ja.json generated in another environment in `freescout/data/resources/lang`.
4. Select "Japanese" from Find Translations.
5. When I try to edit an existing text, I get an "error" message as shown in the attached screenshot and cannot edit it.

![support cskk jp-1613115604585585](https://user-images.githubusercontent.com/5137077/107742017-9f75ad00-6d51-11eb-9e1f-73361eaeefd8.jpg)


> Can you use "Manage > Translate" page to make translations?
> What does it mean? Which error?

Since this problem occurred, I have been unable to edit any language other than Japanese.

[lang.zip](https://github.com/freescout-helpdesk/freescout/files/5970273/lang.zip)

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of the FreeScout?

> 3. Place the ja.json generated in another environment in freescout/data/resources/lang.

This need to be done in the very beginning.

**Comment by kometchtech** [comment]
> Are you using the latest version of the FreeScout?

Trying with 1.6.14.

> This need to be done in the very beginning.

The procedure has been changed.

1. Place the ja.json generated in another environment in `freescout/data/resources/lang`.
2. Run import.
3. Select "Japanese" from Find Translations.

However, even with this procedure, when I edit the Japanese localization file and decide to do so, I get an "error" message and cannot edit it.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Check Manage > Logs > App Logs. If there are no error messages there you may need to debug it yourself.

**Comment by kometchtech** [comment]
> We can't reproduce the issue. Check Manage > Logs > App Logs. If there are no error messages there you may need to debug it yourself.

There was no output in the app logs.
First, let's enable DEBUG and check it out.

**Comment by kometchtech** [comment]
This is very disappointing news.
After several restarts of the app and repeated "Import Translations", the problem of not being able to edit was solved.

After that, I have not been able to reproduce the problem.

Please let this issue be closed. If the problem recurs, please reopen it.
