### ISSUE TITLE
Creating Conversation through postman

### ISSUE THREAD

**Issue by shivamsinghrathor** [freescout-helpdesk/freescout#1025]
While creating new conversation using  postman post request method ,not able to create  conversation every time its giving  404 error.
Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Install https://freescout.net/module/api-webhooks/

**Comment by freescout-helpdesk** [comment]
What you see when you open https://your-domain.com/api/conversations

**Comment by shivamsinghrathor** [comment]
It says like this.. 
Sorry, the page you are looking for could not be found.

Go to Homepage

**Comment by freescout-helpdesk** [comment]
API & Webhooks module is not installed or not activated.

**Comment by freescout-helpdesk** [comment]
Update API & Webhooks module to the latest version.
