### ISSUE TITLE
Spam Block Domain

### ISSUE THREAD

**Issue by oxjemly** [freescout-helpdesk/freescout#1026]
Helpscout allows you to spam block a whole domain e.g. *@reeedexpo.co.jp

This is really helpful for aggressive spammers like @reedexpo.co.jp who use a unique email for each and every spam.

So it would be really great for freescout spam module to allow spam blocking of entire domains.

**Comment by fulldecent** [comment]
FYI if you are using Google Suite for your email hosting you can add email addresses and domains to a list here https://admin.google.com/ac/apps/gmail/manageaddresslist and then you can blackhole those addresses in Admin > Gmail settings.

**Comment by psuter80** [comment]
i don't know how much of this was possible in 2021 but today at least you at least these two options in freescout: 
1. in the spam filter settings, add domains to "filter by body", one domain per line
2. you could use the workflow module and create a workflow that automatically moves all mails from a domain (condition would be "customer email | ends with | @reedexpo.co.jp") into spam or delete them or whatever you want.

**Comment by freescout-helpdesk** [comment]
Implemented in Spam Filter Module v1.0.17

![2023-05-29_11-14-23](https://github.com/freescout-helpdesk/freescout/assets/40499291/c157c9c9-09cd-4bff-b578-6f693c4b75d3)
