### ISSUE TITLE
Auto reply exclusions

### ISSUE THREAD

**Issue by MisterErwin** [freescout-helpdesk/freescout#1027]
Some of our users have set up automatic mails to mailboxes while also wishing to set up an auto reply (which either leads to an auto reply from the other system or complaints from its admin). 

Would it be possible to have a field for customer emails to exclude from auto replying.

This is currently somewhat doable using workflows, just cumbersome as it requires usage of an administrator account.
And thanks for freescout - we really do enjoy it here.

**Comment by freescout-helpdesk** [comment]
Access to workflows can be adjusted on each user's Permissions page.
