### ISSUE TITLE
Personnalize signature for each email

### ISSUE THREAD

**Issue by nissisb** [freescout-helpdesk/freescout#1028]
Hello ,
I have issue concerning signature because sometimes i need to change it when i send emails..
Impossible to modify or personnalize signature when i reply to a customer.
Is there any solutions to permit to do this ?

**Comment by qsvch** [comment]
Hello! This may help you: Enter none in the signature and use the Saved Reply module instead. This way you can save several signatures as saved replies and use them when needed.

**Comment by freescout-helpdesk** [comment]
> I have issue concerning signature because sometimes i need to change it when i send emails..

Unfortunately not possible.
