### ISSUE TITLE
Saved replies categories ?

### ISSUE THREAD

**Issue by nissisb** [freescout-helpdesk/freescout#1029]
Hello all, is it plan to permit to have sub categories concerning the saved replies ?
because we have lot of saved replies and difficult to have clearly view to choose the right reply..

Regards

**Comment by freescout-helpdesk** [comment]
Maybe in the future.

**Comment by nissisb** [comment]
Hello is it possible to make a PR and you validate it  for everybody ? I don't want to make a fork...

**Comment by freescout-helpdesk** [comment]
You can send updated code to support@freescout.net

**Comment by freescout-helpdesk** [comment]
Categorizing saved replies added in Saved Replies Module v1.0.6: https://freescout.net/module/saved-replies/
