### ISSUE TITLE
Variable in Mailbox > Custom From Name

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#1031]
Hey guys!

Under `Edit Mailbox` settings in the field `From Name` we can select `Mailbox Name, User's Name and Custom Name`.
Would be nice to be able to use variables like `{%user.fullName%}` in `Custom From Name`.

![01](https://user-images.githubusercontent.com/39450586/106637592-a9352e80-6561-11eb-815a-6f3ff368260c.png)

Thank you.

**Comment by freescout-helpdesk** [comment]
What do you want to see in `{%user.fullName%}`? Currently authenticated user? Last user who replied to the customer?

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

**Comment by freescout-helpdesk** [comment]
Keep in mind that when the conversation is not assigned to any user (for example when the customer sends a new email to you) the customer will see `{%user.fullName%}` in the sender name.

**Comment by freescout-helpdesk** [comment]
Yes, correct. It's actually not the assignee user, but the user who is replying is used to replace variables like `{%user.fullName%}`. But nevertheless when a customer sends a new email to you the customer will receive an Auto Reply with non-replaced `{%user.fullName%}` variables as there is no user involved at this moment.

**Comment by freescout-helpdesk** [comment]
We'll just leave everything as it is or roll back this new feature if it will cause troubles.

**Comment by freescout-helpdesk** [comment]
We've implemented in the `master` branch replacing with empty string variables which has not been replaced in mailbox's custom from name for auto replies.
