### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#1034]
Hey guys!

I'm a wordpress user and maybe some of you guys are too, I'm willing to make one Wordpress Plugin to integrate with FreeScout, everything using FreeScout's API.
I'm not a coder so that will take some time, but if there is anyone interested we could do this together and finish it faster.

**Plugin to-do list:**
1- Get wordpress' user tickets (using `user email`);
2- Display ticket list with `html table` (using `ticketid, ticket subject, ticket assignee, ticket status, ticket last activity`) in a custom page, using shortcode;
3- On ticket list click it would display the ticket and all its info;
4- Ability to make a reply to ticket;
5- Any other needed data.

**Comment by centralplexus** [comment]
I'd be all over that plugin.

**Comment by scout-devs** [comment]
I am working on this, will be published very soon. 

- [ ] Textarea to paste the Widget JS 
- [ ] Checkbox to enable or disable the widget 
- [ ] Settings to choose the active mailbox 
- [ ] Display a list of conversation in admin panel
- [ ] match the email with user accounts inside the WordPress and create link to the user details page.
- [ ] Clicking on the conversation will take to the helpdesk website. (for now)
- [ ] a shortcode  [freescout_eup mailbox=""] to show the EUP in a iframe anywhere in the frontend. 
- [ ] a shortcode  [freescout_kb mailbox=""] to show the KB in a iframe anywhere in the frontend. 

will be published in wp.org repo in a week.

**Comment by scout-devs** [comment]
Done - https://wordpress.org/plugins/freescout/

**Comment by freescout-helpdesk** [comment]
Good job. It would be also good to add few screenshots and short description to the plugin and we will add a link to https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules

**Comment by scout-devs** [comment]
Yeah done that.

**Comment by scout-devs** [comment]
Done, screenshot updated @freescout-helpdesk

**Comment by qsvch** [comment]
Hello!

Does anyone else have the following problem with the WP plugin? 

If the end user portal is integrated into the website, the form is not taken after submitting, but an error message is issued. The ticket is not taken over. See screen-video ... 



https://user-images.githubusercontent.com/72531514/122760091-01639780-d29b-11eb-9e17-f44fe49af7d7.mov

**Comment by davask** [comment]
Nice, I was thinking to develop a plugin to but you already did it, thanks.

**Comment by vikasprogrammer** [comment]
@qsvch looks like this is a Chrome's (and other browsers') security feature. We are investigating further.

**Comment by jshrek** [comment]
On wordpress.org plugin page it says:
"_This plugin has been closed as of October 25, 2021 and is not available for download. Reason: Guideline Violation._"
