### ISSUE TITLE
No connection SMTP 465

### ISSUE THREAD

**Issue by godepic90** [freescout-helpdesk/freescout#1035]
We have troubles sending mail by SMTP on port 465 and 587

Send error. Connection could not be established with host smtp.transip.email [Connection refused #111].

smtp.transip.email is not available on 465 port. Make sure that smtp.transip.email address is correct and that outgoing port 465 on YOUR server is open.
 
We tried multiple mail servers:

smtp.strato.de
smtp.transip.email

Multiple mailboxes and checked if the ports are open on our hosting. 
Evert hing looks fine.
Even the customer service of the 2 hosts of the system and mail servers  can find any problems.

![image](https://user-images.githubusercontent.com/73000230/106806355-24810800-6668-11eb-98a3-87773e0e9a1c.png)
![image](https://user-images.githubusercontent.com/73000230/106806397-3367ba80-6668-11eb-9ef9-5b10d84d1b4d.png)
![image](https://user-images.githubusercontent.com/73000230/106806511-5b571e00-6668-11eb-8242-4d358b9e4f51.png)

The strange thing is that it have worked before and stops working out of nowhere.

We tried 3 new fresh clean installs on different hosting providers with all the same results.

![image](https://user-images.githubusercontent.com/73000230/106806706-922d3400-6668-11eb-83f3-7023fa60a350.png)

What to do, the customer service of multiple web stores is down now.

We will pay for support if we can get some help whit this case.

**Comment by joris85** [comment]
some hosting servers do not allow you to use those ports.
Have  you checked this is not blocked by the firewall of the server?

**Comment by centralplexus** [comment]
Konfuzius says: If Strato is involved, it's Strato's fault.

**Comment by freescout-helpdesk** [comment]
Server issue.
