### ISSUE TITLE
Frontend widget on website and sticky header

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1039]
Hi guys,

When i use frontend user panel and have the widget implemented and have there a sticky header the header and close button are behind the sticky header. Some custom css would be great there :-)
I would suggest always do the Top to at least 60 instead of 0 because many have sticky headers.
I have it implemented here:
https://academy.breathworkmasterclass.com/

**Comment by freescout-helpdesk** [comment]
Could you please attach a screenshot. Which browser?

**Comment by freescout-helpdesk** [comment]
You can change z-index of the sticky header on your website.

**Comment by joris85** [comment]
Fixed, thanks!
