### ISSUE TITLE
Error in Custom Field Module

### ISSUE THREAD

**Issue by indigator** [freescout-helpdesk/freescout#1040]
I have created many custom fields but had the requirement to delete few. But I am getting error when I try to delete a custom field.
Attached error log: [error.txt](https://github.com/freescout-helpdesk/freescout/files/5941349/error.txt)

**Comment by freescout-helpdesk** [comment]
We will check it.

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version of Custom Fields Module.
