### ISSUE TITLE
API methodNotAllowed(array('POST', 'OPTIONS')) error

### ISSUE THREAD

**Issue by megaerki** [freescout-helpdesk/freescout#1042]
I'm trying to connect via API (Version: 1.0.7) and I'm getting at RouteCollection->methodNotAllowed(array('POST', 'OPTIONS')).

So far, I am able to GET  **https://x.y.com/api/conversations/170** using the X-FreeScout-API-Key header. I get 200 and a reply. 

But when I try  **https://x.y.com/api/conversations** as per https://api-docs.freescout.net/#list-conversations, I get 405 error and Whoops, looks like something went wrong. reply as HTML. 

When I turned on browser logs, I got the error page in this file:
[error.html.txt](https://github.com/freescout-helpdesk/freescout/files/5954570/error.html.txt)

Using 1.6.12 with PHP 7.2.24-0ubuntu0.18.04.7 and nginx/1.14.0.

**Comment by freescout-helpdesk** [comment]
List Conversations method requires GET method. You are probably using POST for https://x.y.com/api/conversations

**Comment by megaerki** [comment]
I tried different methods. All but POST and OPTIONS get the same error. But POST and OPTIONS do not work for this request as you said. 

Adding proof of different requests. 
![Screenshot 2021-02-10 at 09 55 21](https://user-images.githubusercontent.com/6679566/107481448-dea3d280-6b86-11eb-9847-37215c30b8f8.jpg)

**Comment by freescout-helpdesk** [comment]
Does it work in browser?

Try https://demo.freescout.net/api/conversations?api_key=c2ba609c687a3425402b9d881e5075db

**Comment by megaerki** [comment]
No, exactly the same result. 
/conversations?api_key=... gives an error and /conversations/170?api_key=... works.

PS! I really appreciate the quick responses.

**Comment by freescout-helpdesk** [comment]
This is strange. Try to clear the cache or reactivate the API & Webhooks module.

**Comment by megaerki** [comment]
Cache cleared successfully.
Nothing to migrate.
Public symlink already exists
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js


Tried it, no change. 

I could try to update to the API module to last version as it is currently 1.0.7. 
But It requires updating the app to 1.6.23 so I'll need to do it off-hours. 

PS!
 I also set up webhooks, and for convo.customer.reply.created and convo.agent.reply.created events I get 'body': None,
Is that how it's supposed to be or should the body have information about the conversation? 
Maybe it's related?

**Comment by freescout-helpdesk** [comment]
You are using too old API & Webhooks module. That time there was no List Conversations method implemented. Just update it to the latest version.

Information returned by webhooks is presented here: https://freescout.net/module/api-webhooks/
