### ISSUE TITLE
Deleting customer won’t remove from database

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#1043]
Hey!

After some debug within the issue #1013, found that deleting customer won’t remove from database and if the same user send another ticket FreeScout will display an empty customer.

Steps I did:
1- Send one email to mailbox (first email from customer);
2- FreeScout adds the customer and ticket the right way;
3- Delete that user;
4- Send another email using the same email and customer name;
5- FreeScout won't add customer and won't display it's data in ticket;
6- Go to Customer page and try to add customer with same e-mail and name, FreeScout will say that there is already an user with that email even though there isn't.

phpMyAdmin:
![phpmyadmin](https://user-images.githubusercontent.com/39450586/106682948-54fe6e80-65a2-11eb-82b6-af261916f4b0.png)

Ticket Page:
![Untitled](https://user-images.githubusercontent.com/39450586/106682953-562f9b80-65a2-11eb-8dfb-01cc615dd4e0.png)

And in the `emails` table the emails are still there.

**Comment by ipruthi** [comment]
I think the best way to handle this is to create a "deleted" field in the database that would be used to show the deleted user with an icon next to their name to signify that they are not active in the system any longer. This way you retain data integrity.

Another method would be to build a whole structure when deleting a system user, that would ask you what you want to do with the user's current tickets/notes.

**Comment by freescout-helpdesk** [comment]
> 3- Delete that user;

You probably mean "Delete that customer".

> 5- FreeScout won't add customer and won't display it's data in ticket;

We could not reproduce the issue. We've deleted the customer using CRM Module and on step 5 it appears in the ticket with all the data.
