### ISSUE TITLE
use new subject from replies

### ISSUE THREAD

**Issue by fhirter** [freescout-helpdesk/freescout#1044]
some other ticketing systems generate a ticket id in the subject to identifiy tickets. freescout doesn't include those ids when replying forcing the ticketing system to generate a new ticket.
Freescout should use the subject line from the reply, not the one generated in the first place.

**Comment by freescout-helpdesk** [comment]
The issue is not clear.

**Comment by fhirter** [comment]
When we send an E-mail to an address which uses a ticketing system which changes the subject line to identify the tickets freescout doesn't keep this subject line but replaces it with the original line. 
For example:

we write an email to help@example.com, subject: please help us!
the response subject line is something like this: Re: [56664579] please help us!
When replying in freescout the the original subject line is used: Re: please help us!
This generates another ticket at the other ticketing system. Freescout should use the subject line from the last response (Re: [56664579] please help us!), not the original one.

hope this helps.

**Comment by droogadulce** [comment]
Will the [Ticket Number Module](https://freescout.net/module/ticket-number/) help solve this issue?

**Comment by freescout-helpdesk** [comment]
FreeScout keeps original ticket subject. Unfortunately no plans to add changing of the subject from the last customer reply, as it will create confusion and make it hard to find the ticket if subject will be changing.

You may need to implement it as a custom module. See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by fulldecent** [comment]
Recommending to close issue as not planned

**Comment by sebix** [comment]
> Will the [Ticket Number Module](https://freescout.net/module/ticket-number/) help solve this issue?

No, it doesn't cause the issue is the other way round.

The first mail is sent from Freescout to an external ticketing system. The reply to Freescout contains the ticket number of the other, external, system in the subject. When we now reply again, from Freescout, the subject neds to contain the external ticket number, otherwise we trigger another ticket at the external ticketing system instead of reaching the existing one.
