### ISSUE TITLE
Option to remove Branding

### ISSUE THREAD

**Issue by measureschool** [freescout-helpdesk/freescout#1047]
When sending out an email recipients see this in the footer:

"Support powered by FreeScout — Free open source help desk & shared mailbox"

Is there a way to remove the FreeScout branding on the outgoing emails?

FYI: I would also pay for a module to be able to remove it.

**Comment by freescout-helpdesk** [comment]
Uncheck "Spread the Word" in "Manage » Settings".

**Comment by measureschool** [comment]
wow, don't know how I missed that. Thanks!
