### ISSUE TITLE
BUG; Typing a "name surname<the@email.com>" does not adds the contact nor email properly

### ISSUE THREAD

**Issue by colegatron** [freescout-helpdesk/freescout#1051]
While creating a ticket for a non existing customer, it does not creates properly the contact.
For example:

support department<support@company.com> does not adds a contact with name "support department" and email "support@company.com". Instead it creates contact named "support" with email "departmentsupport@company.com"

**Comment by freescout-helpdesk** [comment]
There is already such issue somewhere: https://github.com/freescout-helpdesk/freescout/labels/help%20wanted
