### ISSUE TITLE
Create Conversation API giving 404 not found

### ISSUE THREAD

**Issue by virendrasinght** [freescout-helpdesk/freescout#1052]
I have activated API & Webhook module and trying to create conversation using API. But everytime I am getting 404 not found. Webhook events are getting triggered and working for me fine. Only problem is with API. I have checked API in route list using artisan i.e. php artisan route:list and checked with same URL but still getting 404 not found error.

![image](https://user-images.githubusercontent.com/11226836/108056169-f263a300-7076-11eb-9fc1-7d5868f1361c.png)
 
Postman API test --
![image](https://user-images.githubusercontent.com/11226836/108058165-a0704c80-7079-11eb-8297-c6b7ebf7f8c7.png)

**Comment by freescout-helpdesk** [comment]
Have you checked Troubleshooting at https://freescout.net/module/api-webhooks/ ?

**Comment by virendrasinght** [comment]
Earlier I was using inbox folder for application with root domain (Applicaiton was not installed at root path) like http://domain.loc/inbox/login
But now I have changed my apache config and set my domain to freescout applcation directly and now I am able to access application on http://domain.loc/login and create conversation api also working with this like http://domain.loc/api/conversations

But it should work if I am using application with sub folder like http://domain.loc/inbox/api/conversations

Please help on this.
