### ISSUE TITLE
Modul: Knowledge Database Entrys visible over All Mailboxes 

### ISSUE THREAD

**Issue by szucher** [freescout-helpdesk/freescout#1053]
Hi FreeScout Team, 
Great Job with the new Modul. In the Description of the Modul you Write, every Mailbox had his own Database. At the Moment every Mailbox See the entrys of every Mailbox.

I use FreeScout for 4 Mailboxes and the Customer the See Knowledge of every Mailbox.

**Comment by freescout-helpdesk** [comment]
Thanks. Will be fixed.

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the Knowledge Base Module v1.0.3.

Existing Knowledge Base entries will be assigned to the first mailbox.
