### ISSUE TITLE
Modul: Knowledge Base Site Name Save not working

### ISSUE THREAD

**Issue by XtomtomX** [freescout-helpdesk/freescout#1054]
Hi,
nice job with the new Knowledge Base!

If i click on a Mailbox -> Knowledge Base -> Settings and change the "Site Name" then the changed site name is not reflected on the dedicated Knowledge Base. Is there some error in the Save function of the settings page?

**Comment by freescout-helpdesk** [comment]
Fixed in the Knowledge Base Module v1.0.4
