### ISSUE TITLE
Modul: Knowledge Base Imprint & Privacy

### ISSUE THREAD

**Issue by XtomtomX** [freescout-helpdesk/freescout#1055]
Hi Freescout-Team!

I wanted to ask if it would be possible to allow us to set an Imprint & Privacy Link at the footer area on the dedicated Knowledge Base page (can be the same for all knowledge base pages). Due to the public availability of this website, it is necessary for us to create a link to the Imprint & Privacy / GDPR page on every publicly accessible website.

**Comment by freescout-helpdesk** [comment]
Maybe in the future. For now feel free to edit the template directly: 
/Modules/KnowledgeBase/Resources/views/layouts/portal.blade.php

**Comment by XtomtomX** [comment]
Thank you. I'll edit the template.
Best, Thomas
