### ISSUE TITLE
Knowledge Base vs. End User Portal

### ISSUE THREAD

**Issue by qsvch** [freescout-helpdesk/freescout#1056]
Thank you for the new Knowledge Base module, good job!

Basic question: wouldn't it make sense if the knowledge base could be integrated in the end user portal? This would allow the customer to access the knowledge base for the first time, if there is no solution to change the ticket without having to change the page. 

The only thing that would be even more practical for the customer would be a complete integration into the website by means of generatable source code.

**Comment by freescout-helpdesk** [comment]
Maybe with time.

**Comment by freescout-helpdesk** [comment]
Knowledge Base widget added in the Knowledge Base Module v1.0.7: https://freescout.net/module/knowledge-base/
