### ISSUE TITLE
Knowledge base "Error occured. Please check your internet connection and try again."

### ISSUE THREAD

**Issue by johanoloflindberg** [freescout-helpdesk/freescout#1057]
Hey! The module "Knowledge base" does not work at all. 😰 Nothing happens when I install the module.

Is there anything I need to do to make it visible when I install it? 

Best regards, Johan Lindberg

**Comment by johanoloflindberg** [comment]
I tried to remove the module and install it again. Now I am getting this error "Error occured. Please check your internet connection and try again.".

**Comment by qsvch** [comment]
We have installed and activated the module (forgot to activate?) and it works. A new menu item appears conspicuously in the bar.

I can confirm the problems with uninstalling.

**Comment by XtomtomX** [comment]
@johanoloflindberg did you migrated the database (Manage -> System -> Tools -> "Migrate DB")? The Module introduces some database changes which require a migration.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#error-occurred-downloadingactivating-the-module

**Comment by johanoloflindberg** [comment]
When I try to migrate the database, this message is showing: "**Nothing to migrate.**"

**Comment by johanoloflindberg** [comment]
This is what happen when I activate the knowledge base module… ![image](https://user-images.githubusercontent.com/5504213/108248779-92dbc500-7154-11eb-9d1f-90df8101cafe.png)

**Comment by qsvch** [comment]
@XtomtomX Yes, I have migrated and deleted the cache. When I click on the article, fly to the error ...

**Comment by freescout-helpdesk** [comment]
Anything in Manage >> Logs >> App Logs?

**Comment by qsvch** [comment]
We have deleted the module in the meantime, because the reaction speed of the complete tool is limited. Since the module is out again, it runs as it should.

Enclosed is a log of many since the module was in. 


```

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' (SQL: select * from `kb_articles` where `mailbox_id` = 2) {"userId":1,"email":"**********@qsv.ch","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' (SQL: select * from `kb_articles` where `mailbox_id` = 2) at /var/www/vhosts/*************************/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' at /var/www/vhosts/*************************/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' at /var/www/vhosts/*************************/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77)

```

**Comment by johanoloflindberg** [comment]
Here is my app log @freescout-helpdesk  https://we.tl/t-WcdrZ3y7IO

**Comment by freescout-helpdesk** [comment]
> We have deleted the module in the meantime, because the reaction speed of the complete tool is limited. Since the module is out again, it runs as it should.
> 
> Enclosed is a log of many since the module was in.
> 
> ```
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' (SQL: select * from `kb_articles` where `mailbox_id` = 2) 
> 
> {"userId":1,"email":"**********@qsv.ch","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' 
> (SQL: select * from `kb_articles` where `mailbox_id` = 2) at /var/www/vhosts/*************************/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' at /var/www/vhosts/*************************/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: 42S22): 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_id' in 'where clause' at /var/www/vhosts/*************************/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77)
> ```

https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#application-or-module-is-not-working-after-installing-a-module
Try to run "Migrate DB" in "Manage » System » Tools" or run console command: php artisan migrate.

**Comment by qsvch** [comment]
This has been done several times with migration database, which ends either in error or with nothing to migrate. 

The same result also occurs via SSH.

**Comment by freescout-helpdesk** [comment]
If someone wishes please provide SSH and web access to your FreeScout installation (support@freescout.net) to investigate the issue.

**Comment by freescout-helpdesk** [comment]
Fixed: https://github.com/freescout-helpdesk/freescout/issues/1070#issuecomment-785971745
