### ISSUE TITLE
Error after activating Tags Module

### ISSUE THREAD

**Issue by measureschool** [freescout-helpdesk/freescout#1059]
Hi,

I just bought the Tags Module, but after I activate it I get errors when I click on certain folders (like the Assigned one). Error log shows:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'a7d1a1c373a03013.tags' doesn't exist (SQL: select `tags`.* from `tags` order by `name` asc) {"userId":1,"email":"jj@****.de","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'a7d1a1c373a03013.tags' doesn't exist (SQL: select `tags`.* from `tags` order by `name` asc) at /app/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'a7d1a1c373a03013.tags' doesn't exist at /app/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'a7d1a1c373a03013.tags' doesn't exist at /app/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77)

Version: 1.6.15

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#base-table-or-view-not-found
