### ISSUE TITLE
Extra line break inserted when using `saved replies`

### ISSUE THREAD

**Issue by vdrover** [freescout-helpdesk/freescout#1061]
When I insert a `saved reply`, a line break is always inserted at the top of the message that needs manual deletion.

**Comment by hisam88** [comment]
This is also happening on all of our saved replies. Not clear why. Might be a bug.

**Comment by github-luckow-org** [comment]
same here. And additionally also at the end of the saved reply.

**Comment by fulldecent** [comment]
I confirm broken in 1.8.7

**Comment by freescout-helpdesk** [comment]
Fixed in Saved Replies Module v1.0.26

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2958#issuecomment-1678605654
