### ISSUE TITLE
easyCron Setup

### ISSUE THREAD

**Issue by djcroman** [freescout-helpdesk/freescout#1062]
Hello,
i want to use a extern Cron Service. It is possible to use easyCron for the Cronjob?
I try it but the Cron failed everytime.
Has anyone tried this and got it to work

**Comment by diguinho2018** [comment]
Check that ticket:
https://github.com/freescout-helpdesk/freescout/issues/517#issuecomment-777390929

**Comment by freescout-helpdesk** [comment]
It's not recommended to use non standard cron, it will lead to issues.
