### ISSUE TITLE
Tag count doesn't update on ticket deletion

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#1063]
Hey Guys!

Just noticed that Tag count doesn't update on ticket deletion on Tag page.

**Steps to reproduce:**
1- create one ticket and assign a tag (I assigned using workflows);
2- check tag page and it will be there;
3- delete that ticket and empty trash to permanently remove the ticket;
4- check once again the tag page and the counter will still display the ticket even though it was permanently deleted.

**Tag page:**
There is no ticket in my environment, and the counters are still there.
![TAGS](https://user-images.githubusercontent.com/39450586/108530239-24ae1400-72b4-11eb-96ce-0d487965c454.PNG)

Thank you.

**Comment by freescout-helpdesk** [comment]
Fixed in Tags Module v.10.14. Now when some conversation is deleted forever tag's counter is decremented.
