### ISSUE TITLE
Do not prefill a note with the last submitted note

### ISSUE THREAD

**Issue by jtagcat** [freescout-helpdesk/freescout#1064]
Tickets are littered with:

> customer xyz zzy

> customer xyz zzy
> xxyy yyxx

and: 

> did x

> did x

The add-a-note area is pre-filled with the last text submitted. This confuses people, they'll feel like editing, or what they just sent has not been sent.

I get you want to build a timeline, but let people edit (with optional history) the notes. Don't pre-fill 'add a note' (might be by the browser).

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Please send the browser you are using and step-by-step instruction.

**Comment by jtagcat** [comment]
Firefox 87.0b3 (64-bit)

Can't reproduce today either.
