### ISSUE TITLE
Fetch email error with gmail

### ISSUE THREAD

**Issue by snimar** [freescout-helpdesk/freescout#1065]
I get this error: "imap.gmail.com is not available on 993 port". I have tried everything I could find on google to fix this issue: less secure apps, 2 step authentication, app password, ssl, save the settings.

Will appreciate any help with this. Thanks in advance.

<img width="729" alt="Screen Shot 2021-02-20 at 10 52 11 AM" src="https://user-images.githubusercontent.com/79377397/108605727-ed4e6e80-736a-11eb-80bd-141dc41342b6.png">

**Comment by freescout-helpdesk** [comment]
It is your server's issue.
