### ISSUE TITLE
Prefill conversation subject and message via URL parameters

### ISSUE THREAD

**Issue by nissisb** [freescout-helpdesk/freescout#1067]
Hello all,
I have issues with mailto, i don't understand how can i add the "subject " and "message" to the URL type : https://freescout.com/mailbox/1/new-ticket/?to=test@example.com

**Comment by freescout-helpdesk** [comment]
It's not possible for now.

**Comment by freescout-helpdesk** [comment]
Subject can be prefilled via `?subject=123` parameter. Body most likely won't be pre-filled.

**Comment by afecte** [comment]
What about prefilling name and surname? Is it possible? It may be useful for using Saved replies with name variables.
