### ISSUE TITLE
Attachment size can't be larger then 10+

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1068]
Hi guys,

I have tried couple different types and sizes.
Now it looks like somewhere above the 10 and below the 12 mb the attachment is not downloaded to Freescout.
So we have often attachments missing (design company).
Is this a Freescout limit, server limit or other problem?
I would love to put that to 30 mb.

Thanks!

**Comment by freescout-helpdesk** [comment]
PHP/server limitation.

**Comment by joris85** [comment]
I now get mp3 of 35 mb in my freescout.

An image of 12mb and a .dmg are not working.
Could that be a glitch of Freescout now my file size on the sever is up to 128mb?
Or is there another server limitation?

ps. i checked my email and it is clearly visible in my email so not stuck in some mailfilter.
