### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1069]
Hi guys,

I have created a module Darkmode.
That only adds a switch to add darkmode class to the body.
I add some css to the customization app and when i switch tadaa :-)
https://www.dropbox.com/s/mfat3ts2p04i30h/Schermafbeelding%202021-02-24%20om%2021.15.23.png?dl=0

Are you guys interested in this module and/or my css for this?

Only little thing is it works with a cookie so on switching just a millisecond it can gives a light theme. A good new feature would be to have that setting in the user profile :-)
On, Off, Auto (reacts on machine settings)

**Comment by diguinho2018** [comment]
Good one @joris85!
Would be great if you could share it.

**Comment by joris85** [comment]
This is the addon:
https://www.dropbox.com/s/zwckmag41dhpn5n/Darkmode.zip?dl=0

CSS (not perfect yet, first version to just have darker screen):
https://www.dropbox.com/s/57dfo46plngha0q/darkmode.css?dl=0

You should install it trough ftp i think... (i am not a programmer, my hired (Dutch) programmer build it) :-D

So if anybody has better css of a way to make it better your welcome to change and send updates.
This is just a fast fix to have darkmode active.

I could put it on Github but thats not my expertise.
So if somebody is in to that please do.

**Comment by diguinho2018** [comment]
Thank you @joris85!
Just tested and it worked!
Once I have time I'll check other css classes to improve your work, good one!

**Comment by joris85** [comment]
Great to hear it worked!
And if you have css improvements they are welcome.

@freescout-helpdesk  feel free to use this addon in your addon section.
I can imagine that it can be upgraded to just some color settings in the addon because i only use 4 colors i think :-D

**Comment by joris85** [comment]
Great to hear it worked!
And if you have css improvements they are welcome.

@freescout-helpdesk  feel free to use this addon in your addon section.
I can imagine that it can be upgraded to just some color settings in the addon because i only use 4 colors i think :-D

**Comment by freescout-helpdesk** [comment]
Attaching Darkmode Module here.

[Darkmode.zip](https://github.com/freescout-helpdesk/freescout/files/6068564/Darkmode.zip)

**Comment by wauwturrr** [comment]
Hi Joris,

At my side it looks like it's not working.
When switching to the dark mode, nothing seem to happen.

Already cleared cache etc.

**Comment by joris85** [comment]
@wauwturrr  did you bought and installed the customization module and added the css? 

the only thing this module does is adding a class to the body (or remove it). Nothing more. 

so the styles need to be added in the customization module in the css section.
Styles you can find here:
https://www.dropbox.com/s/57dfo46plngha0q/darkmode.css?dl=0

**Comment by diguinho2018** [comment]
Instead of adding the CSS in the customization module, wouldn't it be possible to add the CSS to style.css that already exists inside the Darkmode module? I think that would work too.

**Comment by distresscode** [comment]
Thank you so much @joris85 It works great. I'll share my version of the css code once I tweak the colors a bit. I prefer dark blue over black and green/blue over the red. Finally, now we don't have to go blind. Thanks again!

**Comment by distresscode** [comment]
Here's my version of the CSS code. It's a Blue with Green accent theme.

https://paste.cloudron.io/ecabakosum.css

To use, replace the code in darkmode.css with the code in the pastebin.

**Comment by wauwturrr** [comment]
Here's my version of @distresscode his version 🤓 Tweaked it a bit, fixed a litte bug on the mailbox-page
Also changed the green to a blue tint, i like it a bit more then :)

https://paste.cloudron.io/agafahayuf.css

**Comment by distresscode** [comment]
Thanks for the fixes @woutr-nl  I felt like I wanted a change today and worked on a purple theme (dracula inspired) https://paste.cloudron.io/enefemevag.css

**Comment by freescout-helpdesk** [comment]
What for is this in the CSS? It messes up textareas:
```
textarea{
min-height:1200px;
}
```

**Comment by joris85** [comment]
> What for is this in the CSS? It messes up textareas:
> 
> ```
> 
> textarea{
> 
> min-height:1200px;
> 
> }
> 
> ```

Yep, delete it (: 
It was for my css textarea field, so delete it! (:

**Comment by distresscode** [comment]
done and done.. link above is updated

**Comment by distresscode** [comment]
I'm trying to use variables for the colors and it's not working right. Before I pull my hair out, is VAR supported in FS? Anything extra I need to do?

https://paste.cloudron.io/xefizegehu.css

Please ignore the rest of the color codes that haven't been updated with a VAR yet. TIA.

**Comment by nebulade** [comment]
Will there be some official dark mode module which we could purchase at some point?

**Comment by mac-linux-free** [comment]
> cial dark mode module which we could purchase at some point?

yes please.

**Comment by freescout-helpdesk** [comment]
We'll try.

**Comment by mac-linux-free** [comment]
How can I change it in the gui?

**Comment by nebulade** [comment]
@mac-linux-free it is actually a module, then you will have a nice toggle button in the navbar https://freescout.net/module/dark-mode/

**Comment by freescout-helpdesk** [comment]
> The only thing which might be nice is, to have it automatically adjust to the system theme based on `@media (prefers-color-scheme: dark)` css selectors.

Proper processing of `(prefers-color-scheme: dark)` option added in Dark Mode Module v1.0.7

**Comment by nebulade** [comment]
Woah perfect, this works like a charm! :)

**Comment by mac-linux-free** [comment]
Perhaps another color would be great.

**Comment by freescout-helpdesk** [comment]
Thanks. We'll test it and if it works fine we'll apply the update.

**Comment by distresscode** [comment]
Is it possible to have the official plugin have editable colors via a GUI? Currently, any color modification has to be done in 10s of places which isn't user friendly at all, especially if you can't code if your life depended on it (personal experience).
