### ISSUE TITLE
WhatsApp Integration

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#1072]
Integration with WhatsApp seems to be possible only via paid services like Twillio ($0.005 per message: https://www.twilio.com/whatsapp/pricing/us). 

If anyone needs a module integrating FreeScout with WhatsApp via Twillio - please let us know.

**Comment by amirseafresh** [comment]
This would be great!

**Comment by psuter80** [comment]
I think it might be worth looking at [Matterbridge](https://github.com/42wim/matterbridge) and possibly use that as an interface to all sorts of instant messenger and such platforms. Haven't looked into integrating anything with it yet myself, just fixed a bug on the Nextcloud Talk Matterbridge implementation. It seems to be the fastest way to support a large amount of other protocols with minimal effort to keep them up to date in the future (that's especially true for inofficial Whatsapp integrations)

**Comment by freescout-helpdesk** [comment]
Here is the discussion: https://github.com/42wim/matterbridge/issues/475#issuecomment-462880861

**Comment by AlwaysInForGoodSushi** [comment]
We would be interested in having a WhatsApp integration :-)

**Comment by freescout-helpdesk** [comment]
If someone can provide us a temporary access to your Twillio account (https://www.twilio.com) connected to WhatsApp - we will be able to integrate FreeScout with WhatsApp.

**Comment by qsvch** [comment]
Why not Whatsapp for Business?

https://www.whatsapp.com/business/?lang=de

**Comment by freescout-helpdesk** [comment]
This is what Twillio is using: https://www.twilio.com/whatsapp

**Comment by freescout-helpdesk** [comment]
Is anyone interested in having a free module integrating FreeScout with WhatsApp via https://www.waapi.co/pricing ?

**Comment by pmhtuk** [comment]
Would be interested with a provider, the cost is one thing to think of but also concerns on the company.
Not head of Wappi before - but twillo has been around years and well known. 

Slightly nervous with idea of jumping on something which goes bust or doesn't have a large company behind it. Not saying waapi would but just a concern with a company offering a 'lifetime service' for $199.

**Comment by mywebhero** [comment]
This sound like a very good deal! Would love to be in the testing team if you're working on it.

**Comment by freescout-helpdesk** [comment]
[WhatsApp Integration Module](https://freescout.net/module/whatsapp/) has been released.

**Comment by idnovic** [comment]
Thank you for the whatsapp module. 
I wanted to ask kindly if it would be possible to create a module using one of these services:

https://messagebird.com/en/pricing/api

https://www.twilio.com/whatsapp/pricing/us

The current implementation is not bad but not cost effective for us.
