### ISSUE TITLE
Features with donation system for modules

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1073]
Hi Guys,

Just an idea...
I can image that there is a list of new features where you can vote and even donate.
Per feature it could have a min price to build it.
Then a developer or you can pick the one with the most donations and build it and get paid.
The marketplace will grow.

I do not mind if i donate and it comes in the Freescout marketplace for sale.
I love to invest in a better Freescout :-D

**Comment by freescout-helpdesk** [comment]
We will think about it...
