### ISSUE TITLE
Notifications feed (bell icon) not updated if email notifications are disabled

### ISSUE THREAD

**Issue by endoflevelboss** [freescout-helpdesk/freescout#1074]
Struggling with notifications not being displayed in the dashboard (highlighted bell icon). I'm getting browser notifications, so I guess the notifications are processed. The bell icon, however, is not highlighted and the feed is not updated.

I have notifications configured for "Browser" only. No check mark in the "Email" column. I was experimenting a bit and I think there could be a connection. When "Email" is selected, the bell icon seems to be updated. At least there was something added while also mails have been sent. Could not re-create though.

No error or warning was found in the log file.

Am I missing something?

**Comment by endoflevelboss** [comment]
Confirmed. 
App\Notifications\WebsiteNotification is only processed if at least one email notification is checked. 

Does this work as designed or shouldn't the website notification always be processed?

**Comment by freescout-helpdesk** [comment]
Website notifications should be always processed.

**Comment by fulldecent** [comment]
Can somebody experiencing this issue with new version 1.8 or later please reproduce and document this?

**Comment by avegalco** [comment]
Dear team.
Currently, we are running version 1.8.69 with PHP 8.0.28. We have noticed that the notifications on the bell icon only work when email notifications are enabled too, which is not something we want to use. This behavior is also affecting the followers module.

Unfortunately, email notifications are not convenient for us, so we cannot rely on them and need to use menu notifications only. Can you please look into this matter and advise on any possible solutions?

Thank you for your attention to this matter.

**Comment by endoflevelboss** [comment]
I support the proposal to have the bell notifications as a selectable option and not implicitly linked to the email notification option. We also go by the bell notification only and I think this is rather the normal case for all heavy users having freescout as their communication hub open all day.

As a workaround, you can comment out the respective lines in app/Subscription.php to disable the email being sent. Look for the if() statement following the comment "Email notification (better to create them first)" and remove or comment out all 7 lines of that block.

**Comment by freescout-helpdesk** [comment]
If Email notifications are disabled we'll use Browser notifications settings to show Bell notifications in the top menu.
