### ISSUE TITLE
Import from HelpScout

### ISSUE THREAD

**Issue by svzi** [freescout-helpdesk/freescout#1078]
Hi @freescout-helpdesk !

I'm trying to migrate our data from HelpScout to FreeScout (via https://help-desk-migration.com/) but for now without luck. When I try to import our conversations, I need to map two missing field values: 

![Bildschirmfoto 2021-03-03 um 21 33 48](https://user-images.githubusercontent.com/1890513/109868826-69e52500-7c68-11eb-9d17-e44b19cd331f.png)

To be honest I've no idea on how to miss the missing type and status to FreeScout. Do I need any additional module to do this? I couldn't even find a setting in the demo, but maybe I looked at the wrong places.

Any help would be really much appreciated. 

Best,
Sven

**Comment by freescout-helpdesk** [comment]
We will check it with help-desk-migration.com Team.

**Comment by svzi** [comment]
@freescout-helpdesk Appreciate your support! Btw the help-desk-migration.com support chat couldn't help me and asked me to talk with the FreeScout team.

I also don't know if I need to remove all existing mails from my FreeScout mailbox for migrating from HelpScout? I've set my mailbox up yesterday and configured the e-mail import as well. So FreeScout did already fetch some mails, but we don't work with FreeScout yet. Should I delete all of them before importing from HelpScout?

Another question I face is: is there a possibility to preserve the HelpScout conversation ids? We reference some conversations in our JIRA issues to track them and inform our customers when something has changed. It would be really helpful if we could keep our old ids.

**Comment by freescout-helpdesk** [comment]
See instructions here: https://github.com/freescout-helpdesk/freescout/wiki/Migrate-to-FreeScout

**Comment by svzi** [comment]
Thanks for updating the wiki accordingly!

Who do I need to contact when I experience trouble during import? To be more specific: some already closed tickets from HelpScout don't have "closed" status in FreeScout (I've just did the demo migration) and they are still active. That should not be the case, because the mapping were set to "Closed" => "Closed".

Any ideas what happened here?

**Comment by freescout-helpdesk** [comment]
You can write jut here.

> To be more specific: some already closed tickets from HelpScout don't have "closed" status in FreeScout (I've just did the demo migration) and they are still active. That should not be the case, because the mapping were set to "Closed" => "Closed".

We will check the API.

**Comment by freescout-helpdesk** [comment]
> To be more specific: some already closed tickets from HelpScout don't have "closed" status in FreeScout (I've just did the demo migration) and they are still active. That should not be the case, because the mapping were set to "Closed" => "Closed".

help-desk-migration.com will need to make some adjustments to their migration process to fix this - we will let you know.

**Comment by svzi** [comment]
Thanks! Is there any estimation from that team? I wanted to finish the migration before the weekend. Will that be in jeopardy?

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the API & Webhooks Module v1.0.16. Try to update the module and try again.

**Comment by svzi** [comment]
I've updated the module to 1.0.16 and tried again. Same issue as before. Conversations that are marked as "Closed" in HelpScout are "Active" in FreeScout.

**Comment by svzi** [comment]
I've noticed that running the migration demo again and again, I got conversations multiple times in FreeScout. So I deleted all previous conversations from my FreeScout mailbox and started the demo migration again:

![Bildschirmfoto 2021-03-04 um 17 14 24](https://user-images.githubusercontent.com/1890513/109994155-52ac4300-7d0d-11eb-9d3c-fc1b819250ad.png)

All of them belong to me and all of them should be "Closed". They appear in "Closed" and in "Mine". When I open the a conversation it's still shown as "Active" and not as "Closed":
![Bildschirmfoto 2021-03-04 um 17 20 29](https://user-images.githubusercontent.com/1890513/109994812-f72e8500-7d0d-11eb-8bac-f2a8f7aea03b.png)

Just one conversation (of 20) has the correct state. I also wonder why the demo picks 100% closed conversations for importing. How should I check the imported state for "Active" conversations in HelpScout? It would be way more helpful to import "Active" and "Closed" conversations from HelpScout and put them into the 20 demo conversations. That's the only way I could check if everything is working as expected, before I pay for migration.

**Comment by freescout-helpdesk** [comment]
OK. We will check what else can be wrong.

**Comment by svzi** [comment]
Thanks again for your support!

**Comment by freescout-helpdesk** [comment]
help-desk-migration.com made some updates in their system. Try again.

**Comment by svzi** [comment]
@freescout-helpdesk Issue 1 has been solved. The conversations are all marked as closed in FreeScout as well. Nicely done!

But issue 2 is still unsolved. The demo migration only imports closed conversations. For that reason it's not possible to test if the other states are being imported correctly. How can I test that? I need to test the import for conversations of all states (closed, active, open). 

Not sure about that, but it looks like it's importing the oldest 20 messages assigned to me. Chances are very high that they are already closed on most instances. If they would import the 20 newest messages assigned to me (or someone else), chance to up a lot that they are not all closed right now...

**Comment by freescout-helpdesk** [comment]
Possibility that help-desk-migration.com change their importing system for your case is probably low. So for you the only way is to run the migration or not to migrate.

**Comment by svzi** [comment]
@freescout-helpdesk They already solved it by importing conversations I requested via chat. Everything worked like a charm then. So I close this issue. Thanks for your support!

**Comment by Basilakis** [comment]
Hey,

To anyone interested, we have built:
https://export-helpscout.net/

Which works - really really easy.

**Comment by tomvoss** [comment]
> Hey,
> 
> To anyone interested, we have built: https://export-helpscout.net/
> 
> Which works - really really easy.

Not anymore it doesn't
