### ISSUE TITLE
Reports Module (Status Active/Pending)

### ISSUE THREAD

**Issue by choletzke** [freescout-helpdesk/freescout#1079]
Hi there,
we recently purchased the "**Reports Module**" for the ticket system to enable us to quantify the usage of the ticket system in our organisation. 
Both standard reporting dashboards are great and already add value.

However, we noticed that the '**Conversations Report**' doesn't show reporting on the number of tickets with the status 
'**Active**' and '**Pending**' on the dashboard. Can this be added to the dahsboard in a future version?

**Comment by freescout-helpdesk** [comment]
Maybe in the future.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
