### ISSUE TITLE
When adding a tag, please focus the cursor in the input field

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1080]
Hi guys,

When i add a tag (clicking on tag icon) the cursor is not focused in the input field.
Can you add a little javascript to do that?

Thanks!

**Comment by freescout-helpdesk** [comment]
Yes. You can post it here or send to support@freescout.net

**Comment by nerdalertdk** [comment]
Ohh yes please.

**Comment by freescout-helpdesk** [comment]
Implemented in Tags Module 1.0.15
