### ISSUE TITLE
Check for updates button fails

### ISSUE THREAD

**Issue by pmhtuk** [freescout-helpdesk/freescout#1083]
Client error: `GET https://api.github.com/repos/freescout-helpdesk/freescout/tags` resulted in a `403 rate limit exceeded` response: {"message":"API rate limit exceeded for 45.8.227.101. (But here's the good news: Authenticated requests get a higher rat (truncated...)

**Comment by freescout-helpdesk** [comment]
Apparently sharing hosting issue. Not much can be done here apart from moving to another server.

**Comment by thom4parisot** [comment]
Maybe by providing an application token? This is kind of blocking with the upgrade system in `tools.php`, as FreeScout is unable to pull the archive from GitHub.
