### ISSUE TITLE
Installation on shared Hosting - www-data

### ISSUE THREAD

**Issue by vosika** [freescout-helpdesk/freescout#1084]
Hello,
I have question, is it possible to install FS on shared hosting with diferent user as a owner then www-data? Im asking because changing owners via ssh console on our shared hosting is not allowed.

**Comment by freescout-helpdesk** [comment]
Yes, it's possible.

**Comment by vosika** [comment]
in that case, we really don't know where we're making a mistake.,,,
There is technical description of our shared hosting  https://www.websupport.cz/en/the-hosting-technical-description
I will describe what we do:
1) We will create a database (MySQL 5.7) - via our web admin panel
2) Via SSH shell console we create folder   **our_domain.com/var/www/html**
3) we  set:    **chown   our_user_id:our_group_id   our_domain.com/var/www/html**
4) we download and extract Freescout to   **our_domain.com/var/www/html**
5 again for sure we set recursively :  **chown  -R our_user_id:our_group_id   our_domain.com/var/www/html**
6. we set permition recursively: **chmod -R 775 our_domain.com**
7. In admin web panel, we set root folder:  **our_domain.com/var/www/html/public**
8. Then we run web installer
9. Everything looks good - we set database , admin user, etc....... but when you click on the installation button, the message 500 ERROR will appear.
Please advise us what we are doing wrong ?

**Our Server error logs show this three logs:**
`magicrew.cz [Sun Mar 07 14:19:57.016207 2021] [php7:warn] [pid 74409] [client 86.49.250.238:33758] PHP Warning:  Uncaught ErrorException: require(/data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/bootstrap/cache/packages.php): failed to open stream: No such file or directory in /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:84\nStack trace:\n#0 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(84): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'require(/data/4...', '/data/4/6/46112...', 84, Array)\n#1 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(84): require()\n#2 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(101): Illuminate\\Filesystem\\Filesystem->getRequire('/data/4/6/46112...')\n#3 /data/4/6/46112738-0276-4aae-88c7-e836 in /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 84, referer https://magicrew.cz/…ard`

`magicrew.cz [Sun Mar 07 14:19:57.016249 2021] [php7:error] [pid 74409] [client 86.49.250.238:33758] PHP Fatal error:  Illuminate\\Filesystem\\Filesystem::getRequire(): Failed opening required '/data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/bootstrap/cache/packages.php' (include_path='.:/usr/php71/lib/php') in /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 84, referer https://magicrew.cz/…ard`

`magicrew.cz [Sun Mar 07 14:19:57.019915 2021] [php7:error] [pid 74409] [client 86.49.250.238:33758] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:752\nStack trace:\n#0 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('view')\n#1 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('view')\n#2 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('view', Array)\n#3 /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('view', Array)\n#4 /data/4/6/46112738-0276-4aae-88c7-e8 in /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752, referer https://magicrew.cz/…ard`

**Comment by freescout-helpdesk** [comment]
Most likely permissions issue.

**Comment by vosika** [comment]
We add to .htaccess  file 
php_flag opcache.enable Off

and server and the server stops showing this error
