### ISSUE TITLE
[BUG] play audio attachments in the browser not visible (v1.6.18)

### ISSUE THREAD

**Issue by Servery** [freescout-helpdesk/freescout#1085]
I can not find the new feature to play audio attachments in the browser. 

![Firefox_Screenshot_2021-03-07T19-38-06 589Z](https://user-images.githubusercontent.com/3184297/110252548-48e14480-7f86-11eb-886e-a20441039cdd.png)

```

<div class="thread-attachments">
	<i class="glyphicon glyphicon-paperclip"></i>
	<ul>
		<li>
			<a href="https://freescout.example.org/storage/attachment/6/5/1/20210307_110505_00_04000000004.wav?id=1020&amp;token=5cfce287dfbef5bc3a5ad47358fb05f0" class="break-words" target="_blank">20210307_110505_00_04000000004.wav</a>
			<span class="text-help">(11 KB)</span>
			<a href="https://freescout.example.org/storage/attachment/6/5/1/20210307_110505_00_04000000004.wav?id=1020&amp;token=5cfce287dfbef5bc3a5ad47358fb05f0" download><i class="glyphicon glyphicon-download-alt small"></i></a>
		</li>
	</ul>
</div>
```

**Comment by freescout-helpdesk** [comment]
There will be no play displayed in the FreeScout. Click on the file name and new browser page with the player will open.

**Comment by Servery** [comment]
Oh, okay it works in Google Chrome but in Mozilla Firefox it just downloads the wav file. I expected something like this in FreeScout at the same position where the attachments are listed at the bottom of the conversation:

![Firefox_Screenshot_2021-03-08T08-18-46 165Z](https://user-images.githubusercontent.com/3184297/110293807-541c8a80-7fef-11eb-88c2-18e7cb03d63f.png)

```
<audio controls>
  <source src="test.wav" type="audio/wav">
  <source src="test.mp3" type="audio/mpeg">
  <source src="test.ogg" type="audio/ogg">
Your browser does not support the audio element.
</audio>
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

**Comment by freescout-helpdesk** [comment]
For now we will keep as it is.

**Comment by Servery** [comment]
I would still like to see an implementation where you can play audio (or video) files immediately. Like in my example screenshot:
![freescout-audio](https://user-images.githubusercontent.com/3184297/135343071-8cad00dd-d7fc-4dea-b1ff-1fb3e372a381.png)

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
