### ISSUE TITLE
Enhancement: Custom Homepage and Default Mailbox

### ISSUE THREAD

**Issue by njsubedi** [freescout-helpdesk/freescout#1086]
I was trying to deploy Freescout as a customer support portal. I purchased all the necessary modules - almost all of them, including KnowledgeBase and End User Portal. 

### What I needed
I was expecting the URL (say, https://support.example.com/) as the homepage for the customers. For my use-case, I only need one single mailbox. The users should see the help center in the homepage ("/") just like in the support pages of other businesses. Examples: support.google.com , support.twitter.com

### Problem
FreeScout seems to use the root path "/" for the support staff, so it will automatically redirect to "/login" from the root path. The help center URL looks something like https://support.example.com/hc/12345678 which doesn't look pretty. 

I explored the modules' routes to look for a solution instead of modifying the core.

### What I tried to do
I tried to add the redirect "/" -> "_/hc/12345678_" (where 12345678 is my mailbox ID) in the KnowledgeBase module so the homepage "/" would redirect to the page I wanted. Example: support.cloudflare.com .. it redirects to _/hc/en-us_ for me

### Fixes
I think the support staff dashboard could reside inside a path, somewhere like "/dashboard" and the root path could be used as the landing/home page for the end-user, not the support staff. That's how WordPress works, for instance. 

Fixes needed
- Add the possibility to redirect "/" to a custom URL/path or the ability to add/edit the homepage.
- Have the dashboard on a separate path, and not redirect directly to login page from "/". The login page is already available at "/login" so the support staff could log in from there.

**Comment by freescout-helpdesk** [comment]
For now it will stay as it is now.

**Comment by expressIndustries** [comment]
I think this is a huge opportunity.  The current support URL looks very low-budget. ( https://support.example.com/hc/12345678 )

**Comment by scout-devs** [comment]
We can work on this and make it a part of our power pack module.
