### ISSUE TITLE
Forwarded message isn't included by default

### ISSUE THREAD

**Issue by NixNotCastey** [freescout-helpdesk/freescout#1087]
I stumble into a problem with forwarding a message to an e-mail. By default, the body of the original message is not forwarded, only the additional comment entered during forwarding.
The message is forwarded correctly only when I manually choose one of the options in conversation history. It should use one of the options by default (presumably whole conversation).

**Comment by NixNotCastey** [comment]
It's get default value from email_conv_history which involve sending e-mail to customers. Forwarding should have separate setting.

` public static function getEmailHistoryName($code) {
        $label = '';

        switch ($code) {
            case 'global':
                $label = __('Default');
                $label .= ' ('.self::getEmailHistoryName(config('app.email_conv_history')).')';
                break;
            case 'none':
                $label = __('Do not include previous messages');
                break;
            case 'last':
                $label = __('Include the last message');
                break;
            case 'full':
                $label = __('Send full conversation history');
                break;
        }

        return $label;
    }`

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Are you using the latest version of the FreeScout?

**Comment by NixNotCastey** [comment]
No, I'm currently using 1.6.15, newer version doesn't change e-mail forwarding mechanism.
I have set  Conversation History in Email to customer to none (and I would like to not changing that).
Changing Conversation History in settings changes default behavior for email forwarding.

When "none" is set for Conversation History, then forwarding doesn't include any messages from original conversation, but when I change Conversation History, to something else, then forwarding includes history accordingly to Conversation History setting.

It would be nice to have separate conversation history setting for email forwarding, like for user notification.
