### ISSUE TITLE
Workflow module: "Do not include signature" option when forwarding

### ISSUE THREAD

**Issue by radiowavesurfer** [freescout-helpdesk/freescout#1089]
When creating a workflow, in the action "Email the Customer", there's a tick box "Do not include signature".

(It looks like this tick box was added in response to issue #565 ).

But in the action "Forward", there is no equivalent tick box. It would be great if this could be added.

Thanks

**Comment by freescout-helpdesk** [comment]
We've checked - technically it's possible. But there is a possibility that it will not always work and may cause some side-effects.
So it won't be implemented for now.
