### ISSUE TITLE
Can't install Modules and App stop working 2 minutes after installing 

### ISSUE THREAD

**Issue by t4tai** [freescout-helpdesk/freescout#1091]
Hi There,

Any help will be appreciated, App installation was successful but nothing is working.
SMTP keeps reverting back to the default setting, and all navigations not working after logging in to the app

order FREESCOUT210309-4161-10120

I have tried https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#4-troubleshooting still not working
How can I fix this, please?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by t4tai** [comment]
Thank you, I have tried the link above also. still not working

**Comment by t4tai** [comment]
Working know after restarting my server. Thank you.

I can't activate the Customization module

Please see error below. how can i fix the please?

Thank you

Error occured creating a module symlink (/home/webapps/freescout/public/modules/customization). Please check folder permissions.

Cache cleared successfully.
Nothing to migrate.
Error occured creating [/home/webapps/freescout/public/modules/customization] symlink: symlink() has been disabled for security reasons
The [/home/webapps/freescout/public/modules/customization] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js
