### ISSUE TITLE
Whoops something wrong- after install

### ISSUE THREAD

**Issue by vosika** [freescout-helpdesk/freescout#1092]
Hello	
We install Freescout on shared hosting via web installer.
After clicking the install button, the Whoops page will appear
The server log on our hosting does not show any error.
But we get this log from Frescout

`[2021-03-08 18:28:06] production.ERROR: Error: File '/data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/public/storage/js/vars.js' does not exist; File: /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/devfactory/minify/src/Providers/BaseProvider.php (124)  `

`[2021-03-08 18:29:05] production.ERROR: SQLSTATE[28000] [1045] Access denied, unknown user 'uid1038576' {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied, unknown user 'uid1038576' at /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied, unknown user 'uid1038576' at /data/4/6/46112738-0276-4aae-88c7-e83638e49a5b/magicrew.cz/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)`
[stacktrace]

Some advice, how to fix it ?

**Comment by vosika** [comment]
The database user is created everything is set,
the permission is at 775
The cron task is also set
.env file showing this:

# Database settings
DB_CONNECTION = mysql
DB_HOST = mysql80.websupport.sk
DB_PORT = 3314
DB_DATABASE = pcaz85nn
DB_USERNAME = **uid1038576**
DB_PASSWORD = xxxxxx

where is the problem ?
can anyone advise me please @freescout-helpdesk 

there is prtSrc
![freescout 1](https://user-images.githubusercontent.com/80193571/110769787-de1b5c00-8258-11eb-9273-c241eb98eec3.JPG)
![freescout 2](https://user-images.githubusercontent.com/80193571/110769864-f1c6c280-8258-11eb-9b2f-14b03a9c55ae.JPG)
![freescout 3](https://user-images.githubusercontent.com/80193571/110769883-f68b7680-8258-11eb-9405-e81672e88595.JPG)
![freescout4](https://user-images.githubusercontent.com/80193571/110771157-7bc35b00-825a-11eb-9271-ffc8dddf9fea.JPG)
![freescout5](https://user-images.githubusercontent.com/80193571/110771206-87af1d00-825a-11eb-8d17-c15df2a0e0df.JPG)
![freescout6](https://user-images.githubusercontent.com/80193571/110771245-9269b200-825a-11eb-9640-667b0e885c46.JPG)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
