### ISSUE TITLE
I can't download attachment

### ISSUE THREAD

**Issue by t4tai** [freescout-helpdesk/freescout#1093]
Hi There,

I can't download attachments sent. 

This page isn’t working manage.example.co.uk is currently unable to handle this request.
HTTP ERROR 500

please how can I resolve or fix the, please?

Thank you

**Comment by t4tai** [comment]
2021/03/09 15:39:23 [error] 1743#1743: *821688 upstream prematurely closed FastCGI request while reading upstream, client: 82.0.138.86, server: manage.example.co.uk, request: "GET /storage/attachment/8/7/1/webserverlog.txt?id=4&token=7f632ba9635d23b84358990756424e01 HTTP/2.0", upstream: "fastcgi://unix:/var/run/example.sock:", host: "manage.example.co.uk", referrer: "https://manage.example.co.uk/conversation/7?folder_id=1"

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
