### ISSUE TITLE
Different email in old ticket

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1095]
Hi guys,

I have sometimes an issue that a new email is added in an old ticket from a totally other person.
I can imagine that somehow there is the same ticket number or something else that is the same.
In last year we have had that ten times i think and from totally different clients.

I need to start a new ticket because otherwise i send old data from another client to this person :-D

Any idea if this could be fixed?

**Comment by freescout-helpdesk** [comment]
When we will face something like this on our FreeScout installations we will try to fix.
