### ISSUE TITLE
Open Tracking

### ISSUE THREAD

**Issue by AlwaysInForGoodSushi** [freescout-helpdesk/freescout#1099]
Hi All!

I am new here and new to FreeScout. The modules look very nice. We have used Freshdesk before, and are using Hubspot now. We would like to change to a different support ticket system as Hubspot is very expensive. 

I would like to know if it is possible to track openings of the e-mail (and optional: the links in the e-mail)? 

Thank you in advance for your time and reply :-)

**Comment by freescout-helpdesk** [comment]
> track openings of the e-mail 

Yes

> the links in the e-mail


No
