### ISSUE TITLE
End-User widget FAQ questions

### ISSUE THREAD

**Issue by expressIndustries** [freescout-helpdesk/freescout#1100]
Hi!  Would love to see the option to automatically search the FAQ when people type questions before they contact.
Z**desk does this nicely.  
Here is a demo of this working:  https://expressmileage.com/

Simple flow:
Ask question....search FAQ for answers....if user still has question....provide Contact form.

Has anyone already modified the End-User widget to do this?

**Comment by diguinho2018** [comment]
Good one!
I would add one more step to the flow you suggested:
`Ask question....search FAQ for answers....if user still has question....display chat if during work hours....provide ticket form if out of work hours.`

**Comment by expressIndustries** [comment]
Ok so how does this work? If I create this module - does it get added to the project and then become available to everyone?   Is the "module" system a marketplace or is it only FreeScout offering modules?

**Comment by ressonix** [comment]
> Ok so how does this work? If I create this module - does it get added to the project and then become available to everyone? Is the "module" system a marketplace or is it only FreeScout offering modules?

You can create the module, then submit your module to @freescout-helpdesk and they can add it here in the Wiki as a community module: https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules

**Comment by freescout-helpdesk** [comment]
Knowledge Base widget added in the Knowledge Base Module v1.0.7: https://freescout.net/module/knowledge-base/

**Comment by expressIndustries** [comment]
Nice!   This is a great upgrade.  A few comments:

1) It would be great if the search results updated as the user typed question.  

2) The widget should display the answer within the results...not make the user go to the FAQ page.  Nobody wants there users to leave there site for another page...not even a help page.

3) Provide the option to display/remove FreeScout branding....Looks like we have to manually disabled the FreeScout branding here: 
 ./Modules/KnowledgeBase/Resources/views/widget_form.blade.php:

**Comment by freescout-helpdesk** [comment]
> 3. Provide the option to display/remove FreeScout branding....Looks like we have to manually disabled the FreeScout branding here:
> ./Modules/KnowledgeBase/Resources/views/widget_form.blade.php:

This should be possible with Customization & Rebranding Module.

1-2 most likely won't be implemented.
