### ISSUE TITLE
Use date from header for fetched emails

### ISSUE THREAD

**Issue by imsodin** [freescout-helpdesk/freescout#1103]
I just setup freescout for an existing shared mailbox. All old mails now have their receive date set to the time of when they were fetched. That is not only a problem on setup, but also e.g. if there's trouble fetching emails in the future and emails will be fetched later. I'd be great if the date would be taken from the actual received date in the email message (header).

**Comment by cf39** [comment]
This would be an awesome feature I see as a disadvantage with many ticket systems. Should probably be an option and not a hard-coded default though.

**Comment by freescout-helpdesk** [comment]
Use [$thread->getMailDate()](https://github.com/freescout-helpdesk/freescout/blob/dist/app/Thread.php#L1377) function to get the date from email headers.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/3297
