### ISSUE TITLE
Facebook Modul doesn´t work, Payload Datenschutzbestimmungen in Europa

### ISSUE THREAD

**Issue by szucher** [freescout-helpdesk/freescout#1106]
Hi, i verified my buisness accout, but i will not receive messages from facebook for my buisness facebook page.

I got the following error in the logs:
Error sending payload: (#10) Diese Aktion wurde aufgrund neuer Datenschutzbestimmungen in Europa nicht gestattet. Sieh dir die Entwicklerdokumentation an, um mehr Infos zu erhalten. {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#10) Diese Aktion wurde aufgrund neuer Datenschutzbestimmungen in Europa nicht gestattet. Sieh dir die Entwicklerdokumentation an, um mehr Infos zu erhalten. at /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/vendor/botman/driver-facebook/src/FacebookDriver.php:516)

**Comment by freescout-helpdesk** [comment]
OK. We've sent a message to Facebook Driver developers: https://github.com/botman/driver-facebook/issues/115

**Comment by freescout-helpdesk** [comment]
You are not able to send and receive messages? Right?

Both with and without attachments?

**Comment by szucher** [comment]
> You are not able to send and receive messages? Right?
> 
> Both with and without attachments?

Yes I am not able to receive and send messages.
And both with and without attachments.

**Comment by freescout-helpdesk** [comment]
Your business is located in Europe? Or page admin is located in Europe? Right?

**Comment by szucher** [comment]
> Your business is located in Europe? Or page admin is located in Europe? Right?

Yes, in Germany

**Comment by szucher** [comment]
Error sending payload: (#10) Diese Aktion wurde aufgrund neuer Datenschutzbestimmungen in Europa nicht gestattet. Sieh dir die Entwicklerdokumentation an, um mehr Infos zu erhalten. {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#10) Diese Aktion wurde aufgrund neuer Datenschutzbestimmungen in Europa nicht gestattet. Sieh dir die Entwicklerdokumentation an, um mehr Infos zu erhalten. at /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/vendor/botman/driver-facebook/src/FacebookDriver.php:516)
[stacktrace]
#0 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/vendor/botman/driver-facebook/src/FacebookDriver.php(473): BotMan\\Drivers\\Facebook\\FacebookDriver->throwExceptionIfResponseNotOk(Object(Symfony\\Component\\HttpFoundation\\Response))
#1 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/vendor/botman/botman/src/BotMan.php(237): BotMan\\Drivers\\Facebook\\FacebookDriver->getUser(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage))
#2 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/Providers/FacebookServiceProvider.php(202): BotMan\\BotMan\\BotMan->getUser()
#3 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/Http/Controllers/FacebookController.php(37): Modules\\Facebook\\Providers\\FacebookServiceProvider::processIncomingMessage(Object(BotMan\\BotMan\\BotMan), 'Testnachricht', Object(App\\Mailbox))
#4 [internal function]: Modules\\Facebook\\Http\\Controllers\\FacebookController->Modules\\Facebook\\Http\\Controllers\\{closure}(Object(BotMan\\BotMan\\BotMan), 'Testnachricht')
#5 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/vendor/botman/botman/src/BotMan.php(495): call_user_func_array(Object(Closure), Array)
#6 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/vendor/botman/botman/src/BotMan.php(425): BotMan\\BotMan\\BotMan->callMatchingMessages()
#7 /www/htdocs/w01598d5/scout.zucher-duingen.de/Modules/Facebook/Http/Controllers/FacebookController.php(86): BotMan\\BotMan\\BotMan->listen()
#8 [internal function]: Modules\\Facebook\\Http\\Controllers\\FacebookController->webhooks(Object(Illuminate\\Http\\Request), '9', '484061039')
#9 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('webhooks', Array)
#11 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Modules\\Facebook\\Http\\Controllers\\FacebookController), 'webhooks')
#12 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#13 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#14 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#18 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#19 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#20 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#21 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/htdocs/w01598d5/scout.zucher-duingen.de/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/htdocs/w01598d5/scout.zucher-duingen.de/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /www/htdocs/w01598d5/scout.zucher-duingen.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 /www/htdocs/w01598d5/scout.zucher-duingen.de/public/index.php(64): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}
"}

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in Facebook Integration Module v1.0.4.
Try and let us know if it works for you.

**Comment by szucher** [comment]
After Update to v1.0.4 it works!
Thx for your fast support!
