### ISSUE TITLE
Enduser portal, chat, contact-widget and knowledge base - Elements like header, file-upload, backlink to Freescout, footer

### ISSUE THREAD

**Issue by webtyphoon** [freescout-helpdesk/freescout#1108]
Hi there,

this is nothing offending, I think your solution is one of the best software products for support out there. But look more into the features instead to build one module after another and publish them in light speed. Maybe you open up a beta-testing crew to get more feedback - more eyes more experience and after that great modules which fulfill every needs

The only way I can disable or edit areas are to edit core files. On every update they will reset and I have to change all files again.

Here some features that are really really needed:

- **For our CI**
We need a better way to edit the design of the standalone pages for our CI. Header have to have more options:
1. Changing colors on top-bar for every mailbox
2. Possibility to set individual links (internal and external)
3. Individual Logo for every mailbox

- **Footer**
I can setup a footer in customization module but its not showing on all the standalone pages of the system. The only thing thats showing is the name of the mailbox. Where should the self-created footer be displayed?
Here also a way to set up individual footer for every mailbox.

- **Chat / contact / knowledgebase widget**
First of all a documentation with the information, that when you have all modules installed, you have to use the knowledgebase plugin for publishing chat or contact widget too.

1. An option to whitelable the widgets with own or disable link
2. Disable file-upload
3. Option to decide which file
4. Option to enable recaptcha or a simple inputfield (question&answer)- or math-captcha
5. Option to change the language
6. Especially on chat -> Contact information in front of starting a chat. As I mentioned it before, we have customers between 50-80 years old and they don't know whats about the 3 dots in the footer. And this workflow described here: https://github.com/freescout-helpdesk/freescout/issues/1100#issuecomment-801006485
7. Option inside the widget to switch from chat to contact. There is no information about, that when chat is open and an operator is not answering, that the question will be send in as ticket, so that can confuse visitors.
8. Additional you can look into https://github.com/freescout-helpdesk/freescout/issues/1102#issuecomment-802980674 also some good ideas 

- **Chat widget office times and more**
1. Reverse order: When I fill in 09-12 it shows contact form at this time. I would like to switch that this are the times that chat is visible at first.
2. Add a second time line. We all make breaks and it would be nice to manage -> 09-12 and 13-18 <- to setup a break
2. Show icons from online operators below the title 

Thank you again for your work on this production.

Steve

**Comment by freescout-helpdesk** [comment]
Maybe some of this will be implemented with time. Meanwhile feel free to add most needed features to https://freescout.net/request-feature/

**Comment by episquare** [comment]
I agree with @webtyphoon, i bought 10 module by the way.

not offending too, but you guys should disclaimer, or note in every module that said, this module can customize, but not white labeled. 
i knew developing open source is hard too, but the problem is you sell the modules, and they are not free, what in the people mind about customization word will be like white label.

Seriously i love this software very much, but the backlink, footer, and there is no white label on important part (Modules) is make me sad.
i will be glad to bought white label module, even they are hmmm, maybe more expensive than other modules, but true white label.

Thank you, and good luck guys...

**Comment by freescout-helpdesk** [comment]
Thanks. "No white-labeling" notice added to modules providing widgets.

**Comment by episquare** [comment]
By the way it will nice too of you change 'white labeling' in 'Features' section in https://freescout.net to 'Customization (Not White Labeling)' page, so when visitor comes and they don't think this module about white labeling

And no offending again, it just some clarification to make this community healthy.

Thank you for the previous response, by the way is it really imposiblle to remove 'powered by' in widget? This is some code or backward compability product or maybe do you guys has plan to release this as an module?

![image](https://user-images.githubusercontent.com/29253641/114995819-6a5c1700-9ec8-11eb-9848-9676bcc4a5ea.jpeg)

**Comment by scout-devs** [comment]
Lot of things can be done with https://scoutdevs.com/downloads/power-pack/
