### ISSUE TITLE
Restore deleted conversation

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#111]
![2018-09-18_08-07-55](https://user-images.githubusercontent.com/40499291/48283168-c9521200-e46c-11e8-99bb-2c26030ed93c.png)

**Comment by Junker** [comment]
i'm ready to do it

**Comment by freescout-helpdesk** [comment]
Ok

**Comment by fvdm** [comment]
This can be closed.

To restore a conversation from Deleted you choose Restore from the status menu.
