### ISSUE TITLE
Can't seem to activate the Knowledge Base module

### ISSUE THREAD

**Issue by wauwturrr** [freescout-helpdesk/freescout#1110]
Keep getting the error below when activating; 

Cache cleared successfully.
Nothing to migrate.
Error occured creating [/home/woutr/domains/support.woutr.io/public_html/public/modules/knowledgebase] symlink: symlink(): No such file or directory
The [/home/woutr/domains/support.woutr.io/public_html/public/modules/knowledgebase] symlink has been created
Clearing cache...

Funny thing, i've activated the KB before, and my whole CSS was broken then, but that seem to got have been fixed with an update

Any idea how to solve this?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/914

**Comment by wauwturrr** [comment]
are you even looking at my error? Or just reading 'permissions' and giving it the same answer as always?

**Comment by freescout-helpdesk** [comment]
You have problems with permissions.

**Comment by wauwturrr** [comment]
How is it possible to activate other modules then? It's not a permissions-thing.

**Comment by wauwturrr** [comment]
After removing the kb module and clearing the cache i get;

Er is een fout opgetreden bij het downloaden van de module. :% a_being% download:% a_end% de module alstublieft handmatig en pak die uit in /home/woutr/domains/support.woutr.io/public_html/Modules

Translated;

There was an error downloading the module. :% a_being% download:% a_end% please manually extract the module and extract it in /home/woutr/domains/support.woutr.io/public_html/Modules

**Comment by wauwturrr** [comment]
![image](https://user-images.githubusercontent.com/16634704/112487262-e1483900-8d7c-11eb-8bc3-396e3bbf852b.png)

All the rights are okay too

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. You need to investigate the issue by yourself.
