### ISSUE TITLE
higher size attachments are not disaplyed.

### ISSUE THREAD

**Issue by openhostgit** [freescout-helpdesk/freescout#1111]
Freescout shows attached files if the size is less than 10gb and the attachements are not shown when the size is beyond 10Mb.

Attached files are showing properly in Roundcube webmail. please help me to solve this issue.

**Comment by fulldecent** [comment]
Please /system/status and send here

**Comment by freescout-helpdesk** [comment]
Most likely server or PHP limitation. Also check logs in Manage > Logs > App Logs
