### ISSUE TITLE
Feature request for Knowledge Base: Embed video

### ISSUE THREAD

**Issue by centralplexus** [freescout-helpdesk/freescout#1114]
Hi there,

in the KB article editor I can see embedded videos, actually. It's only on the final page that they are not working. This would be a very useful feature, is there a way to make this work properly?

Kind Regards,
CP

**Comment by freescout-helpdesk** [comment]
Works fine: https://demo.freescout.net/hc/1321731726/article/1?category_id=1

**Comment by XtomtomX** [comment]
Hi,

one question would it be possible to add support for Nextcloud video links? At the moment it's only possible to add video-addresses with the corresponding HTML tag [1] manually.

KR, Thomas

[1] https://www.w3schools.com/html/html5_video.asp

**Comment by freescout-helpdesk** [comment]
Maybe someone can do it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
