### ISSUE TITLE
Feature request: Paste images

### ISSUE THREAD

**Issue by eriktorsner** [freescout-helpdesk/freescout#1118]
One feature that I'm really missing from Helpscout is to be able to paste an image into a reply. I use it regularly for sending screenshots / snippets to customers. In FS the workflow becomes a bit more tedious. 

More than happy to pay for it as a separate module.

**Comment by eriktorsner** [comment]
First, my issue above wasn't very detailed. I examined this a bit more and it seems that pasting images from a local clipboard works just fine if they are links to publicly available images. 

But pasting an image from the clipboard doesn't work if it is raw image data, like it is when it comes from a screenshot tool.

I did some digging on this.

Freescout 1.6.20 ships version 0.8.9 of Summernote wysisyg editor. Current version is 0.8.18 (these guys are not too strict about sematic versioning) and besides a bunch of new features, there has been some updates with the clipboard handling.

I've compared how the DOM looks like after pasting in two images in a text. One is created using a screen snippet tool and the other image was added to the clipboard by right clicking an image on the web and select **Copy image**

Here's what the DOM looks like in Freescout 1.6.20 / Summernote 0.8.9:
![image](https://user-images.githubusercontent.com/2832047/112988008-a0c53280-9163-11eb-9b71-6709c7015ea5.png)

And here's the same thing but using the Summernote demo on their own home page, running 0.8.18

![image](https://user-images.githubusercontent.com/2832047/112985765-e7655d80-9160-11eb-9cde-352c1cc09850.png)

So one thought is that just upgrading to a later version of Summernote may solve the issue. To test if just upgrading the the frontend Summernote is enough I did one more experiment. 

1. Start writing a new message in Freescout
2. Inspect the text area element in Chrome dev tools
3. Manually add an inline image by rewriting an existing br tag to an img tag with an inline source
4. Send the message

...and this works. Seems like the message handling in Freescout handles inline images just fine. This is what the message ended up looking like in my desktop email client (the image being a regional screenshot of the Google logo):
![image](https://user-images.githubusercontent.com/2832047/112988367-0dd8c800-9164-11eb-95f9-e4b2e89328ae.png)

So I'm thinking that as first step to solving this, just upgrading to the newest Summernote may be the only change required.

**Comment by freescout-helpdesk** [comment]
Summernote code has been vivisected in FreeScout. So unfortunately we won't update it, as crazy amount of time has already been spent on adjusting it.

**Comment by ybizeul** [comment]
In my case, using Safari for instance, the image actually pastes correctly in the editor and is embedded as an attachment on public facing freescout, which is fine by me, but the email client isn't loading it :

![image](https://user-images.githubusercontent.com/182035/174717170-6bcfdba1-736e-4c55-94a7-28447d44f617.png)

**Comment by freescout-helpdesk** [comment]
Implemented as a module: https://freescout.net/module/embed-images/
