### ISSUE TITLE
Undo  an answer

### ISSUE THREAD

**Issue by nissisb** [freescout-helpdesk/freescout#1119]
Hello all,
Does it exist a system to permit to undo answer after sending when we reply to a ticket. It seems, it's only available for new message and no possible for reply...

**Comment by freescout-helpdesk** [comment]
We can't confirm the issue.

**Comment by nissisb** [comment]
hello thanks for reply,
Is it plan to make it possible in the future or not ? because it's a very useful feature when we reply to an email
