### ISSUE TITLE
SEO optimization for permastructure (URLs) - Knowledge Base

### ISSUE THREAD

**Issue by johanoloflindberg** [freescout-helpdesk/freescout#1121]
I recently bought the Knowledge Base module.  

Sees that links are not SEO optimized, but only like this: https://mail.wya.se/hc/127968152/article/2?category_id=4

Can it be solved in any way? 

Regards, Johan Lindberg

**Comment by freescout-helpdesk** [comment]
What do you need to make it SEO optimized?

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to adjust URLs. If someone want they can implement it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by freescout-helpdesk** [comment]
"Slug" option added for articles in Knowledge Base Module v1.0.16
