### ISSUE TITLE
Position chat widget 

### ISSUE THREAD

**Issue by JensFalk** [freescout-helpdesk/freescout#1122]
Hi,

it is about the position of the chat widget on the side.

Unfortunately, it is not enough to put the button on the left or right bottom position. The pages often have a button "Schaltfläche Nach oben scrollen" ("Scroll to top") on the right bottom area and on the left bottom area a button for the cookie hint.

It would be good to have the button more up, so that it does not overlap the other buttons.

Thank you.

**Comment by JensFalk** [comment]
Thank you! If I answer the chat the participant is being informed by a sound in the browser. Is that also possible when opening a chat by the web site visitor?

**Comment by freescout-helpdesk** [comment]
Website visitor receives sound notification if he/she makes at least one click on the web page.
