### ISSUE TITLE
Improvement for Knowledge Base Widget

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1123]
The new widget is just awesome, however I think by default you should show the category > articles in the widget (with the search working as usual). 

<img width="395" alt="Screenshot 2021-03-31 at 8 06 58 PM" src="https://user-images.githubusercontent.com/1262327/113162699-224cbb80-925d-11eb-98b0-d5ba8b2065ca.png">

This will help the users browse the articles without even searching for it.

**Comment by lanc2112b** [comment]
It would also be good if if listed each mailbox too, e.g. Accounts (Billing queries), Support (technical queries), Sales etc.

**Comment by vikasprogrammer** [comment]
@lanc2112b that will be difficult as the KB widget plugin is per mailbox. I don't there is an option of department yet? May be an integration with custom folders will help?

**Comment by lanc2112b** [comment]
Custom folders, not really. We use a mailbox per. as in accounts@ support@ etc. Custom folders doesn't really cut it as there needs to be separation, except for knowledge base. 4, 5 or 6 different widgets is just messy.

**Comment by vikasprogrammer** [comment]
I see what you are saying. So basically a bespoke module which will show a list of mailboxes first and then takes you to the respective mailbox'es KB or contact page?

**Comment by lanc2112b** [comment]
Not mailboxes per se. Just all of the public articles, organised by
mailbox, then category. Just an addition of a drop down to the widget, or
an aggregation page to the existing knowledgebase. The same issues kind of
apply to the end user portal widget as well (to a lesser extent).

**Comment by freescout-helpdesk** [comment]
"Show Categories" option added in Knowledge Base Module v1.0.10

**Comment by vikasprogrammer** [comment]
You should do proper testing before release

1. it shows all the categories from all the mailboxes. 
2. clicking on the category opens the article in a new tab, I think the behaviour should be to open it inside the KB widget itself.

**Comment by freescout-helpdesk** [comment]
> 1. it shows all the categories from all the mailboxes.

Thanks. Will be fixed.

> 2. clicking on the category opens the article in a new tab, I think the behaviour should be to open it inside the KB widget itself.

If anybody need it this way - feel free to implement: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
