### ISSUE TITLE
Play nice with other people using the same email account

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1124]
The [installation instructions](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide) explain:

> You will also need a mailbox email address which will be used to fetch incoming emails... This email is supposed to be accessed via FreeScout only.

This is weird. Of course everybody (nearly everybody?) that wants to use FreeScout will probably already have a support@... email address that multiple people are logging into every day.

That means anybody that wants to try and install FreeScout will need to coordinate this strategy with all of their customer support agents simultaneous and they will have downtime while things are set up. (Have you ever deployed a multi-user application where installation was immediate, it caused no problems, and every user was provisioned and trained immediately with no questions?)

I recommend that instead, FreeScout should be happy to connect to an existing email account even if other people are using it. If there is a reduced experience from this (like emails wont enter the system if somebody else marks them as read), it okay, just please explain that in the setup instructions.

---

P.S. For Gmail, there may be a helpful workaround: label every incoming email as freescout-ready-to-import. And then FreeScout will unlabel those email when processing.

**Comment by tiredofit** [comment]
This is standard practice for nearly every support / ticketing system. It's an account used strictly by the application, and the Gmail / whatever frontend you were using to access the mailbox is no longer used. This seems like an awful lot of work to completely bend the standards, this along with #1125.

**Comment by fulldecent** [comment]
All I'm asking is that it be explained what will happen if I connect FS to something I am also using.

Will it work a little bit? Will it delete all my emails?

I don't just want to know the answer, I'd like to have this answer spelled out in the documentation. In other words it should be a guarantee.

Example:

> You will also need a mailbox email address which will be used to fetch incoming emails... This email is supposed to be accessed via FreeScout only. **If there are other people accessing this account, FreeScout will only process emails that are unread at the time sees them (ignoring others) and will otherwise work as normal.**

**Comment by freescout-helpdesk** [comment]
Clarification added to https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

**Comment by fulldecent** [comment]
Note was added at https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#1-prerequisites

Great, thank you
