### ISSUE TITLE
Allow to connect without App Password (GSuite)

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1125]
In the [Connect G Suite to FreeScout](https://github.com/freescout-helpdesk/freescout/wiki/Connect-G-Suite-to-FreeScout) guide it explains:

> In order to use G Suite email with FreeScout you need to create an App Password for the G Suite user.

---

Please allow me to explain why this is a harsh requirement and why workarounds should be allowed.

First, App Passwords requires you to turn on Google two-factor authentication.

Second, Google two-factor authentication requires getting a text message to login or a popup on all your cell phones with the Gmail app installed.

Anybody that needs FreeScout and uses Gmail is probably already using a support@... email address which multiple people access.

For the best customer experience (i.e. *my* customers), when you use multiple people in a support@... email address, all support agents should be logging in directly, not using delegated access. This means password sharing.

In order for me to turn on two-factor authentication this means that every one of my customer support agents (USA, Asia, Europe) will receive popup notifications on their personal phones every time any one of the agents logs in. Ouch.

See #1124 

---

I understand there is also another workaround: create a support2@... email address and have FreeScout use that instead of support@....

But now this means my customers will be receiving emails from support@ and support2@. It's confusing.

---

Solutions:

- Using the Gmail API, rather than IMAP, may be a way to solve this problem. And it might provide other niceties too.

- FreeScout may work in a scenario where you create a support2@ email account, forward all support@ email to support2@ and then have FreeScout login to support2@ but also send emails as support@. I'm not sure if this is supported. But if it is then it should be added a known workaround on the article above.

**Comment by freescout-helpdesk** [comment]
Feel free to add an idea to https://freescout.net/request-feature/, maybe someone will create a custom module.

**Comment by fulldecent** [comment]
I will add there. But it seems the website won't load or is down


<img width="1509" alt="Screen Shot 2021-04-09 at 11 33 17" src="https://user-images.githubusercontent.com/382183/114204682-7889c080-9927-11eb-8e0b-e085b6ab4f43.png">

**Comment by fulldecent** [comment]
Works if I load website in Edge.

Thank you, added here https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/337049
