### ISSUE TITLE
Copy my footer content from the style module to knowledgebase and enduser portal

### ISSUE THREAD

**Issue by webtyphoon** [freescout-helpdesk/freescout#1126]
Hi there,

the editor has a problem to catch up HMTL. It shows all the tags on the page. Also when I write it normal into the editor or paste the code inside the code-option of the editor.

See the picture. First line is handwritten and the second is copied. 

A nice addition will be to have a option field "Use global", to use the footer content from your styling module.

Cheers
![Bildschirmfoto 2021-03-31 um 17 47 25](https://user-images.githubusercontent.com/6331771/113173148-66ce5c00-9249-11eb-87a3-05929914567f.jpg)

**Comment by freescout-helpdesk** [comment]
In the editor you can switch to editing the HTML code and insert your code.

**Comment by webtyphoon** [comment]
Does not work. Both ways its not working

**Comment by webtyphoon** [comment]
I tried it again after the update but nothing changed. When I write the text from scratch and add a link it did not convert correctly, it shows the html tags.
![Bildschirmfoto 2021-04-16 um 10 12 44](https://user-images.githubusercontent.com/6331771/114993866-80ec7900-9e9c-11eb-895c-2e793032f145.jpg)

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module v1.0.12 and End-User Portal v1.0.12
