### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1128]
Currently FreeScout is requiring to create a username and password for everybody that will login.

It will be much better if people at my company can Login With Google.

**Comment by freescout-helpdesk** [comment]
Feel free to add an idea to https://freescout.net/request-feature/

**Comment by fulldecent** [comment]
Thank you, posted here https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/337050
