### ISSUE TITLE
I do not have sysadmin-level access to Gmail

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1132]
When there is an error sending email, the error message informs to:

> Error occurend [sic] sending email. Please check your mail server logs for more details.

In this case, the mail server is Gmail, operated by Google. While I have previously worked at Google, I was not on the Gmail team. It will be very difficult for users of FreeScout to go get a job at Google, join the Gmail team and access their server logs.

Please instead update this error message to show something FreeScout customers actually have control over.

<img width="1943" alt="Screen Shot 2021-03-31 at 13 42 53" src="https://user-images.githubusercontent.com/382183/113189033-c0725e80-9228-11eb-9a02-fd89977cccac.png">

**Comment by freescout-helpdesk** [comment]
Any suggestions?

**Comment by fulldecent** [comment]
Perhaps FreeScout has its own logging.

Or, if using [the recommended installation method](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#interactive-installation-bash-script-ubuntu) maybe PHP or something else has logging enabled by default.

If so, it would be helpful to update the error message:

> Error occurred sending email
>
> Check FreeScout's errors logs at ______ for details.
>
> Also, if you have access to the email server you are attempting to connect to, logs there might be helpful.
