### ISSUE TITLE
Error: Update to 1.7.0

### ISSUE THREAD

**Issue by Servery** [freescout-helpdesk/freescout#1135]
After clicking on Update on /system/status to Update to 1.7.0 there was an error msg: "please try another update method or try again". I reloaded the page and my current version is now 1.7.0... As far as I can tell everything works as expected, but here is my error log (I don't know if there is anything to do for me):

[laravel-2021-04-02.log](https://github.com/freescout-helpdesk/freescout/files/6250972/laravel-2021-04-02.log)

**Comment by freescout-helpdesk** [comment]
Sometimes when updating finishes you may see the "Error occurred" message, but FreeScout shows a new version and functions normally.
