### ISSUE TITLE
 Zend OPcache API is restricted by "restrict_api" configuration directive error on Serverpilot

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#1137]
For anyone using Serverpilot and come across this error

` Zend OPcache API is restricted by "restrict_api" configuration directive
`

You can fix it by editing

`sudo nano /etc/php7.4-sp/conf.d/opcache.ini
`
Comment the following line:
`opcache.restrict_api=/restricted
`

Then restart
`sudo service php7.4-fpm-sp restart `

(assuming you running on PHP 7.4)

Probably happening in other servers as well. When OPCache restricted, freescout throwing error after update, during clear cache "Whoops something went wrong".

**Comment by massimoghm** [comment]
I've the same error but server use restricted API for security reason, how I can fix?

Regards
