### ISSUE TITLE
Time not correct - 

### ISSUE THREAD

**Issue by lovetoast** [freescout-helpdesk/freescout#1138]
Hi, currently on GMT+1, the server time is correct, but freescout is still picking up UTC, on a Centos server with latest freescout.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-freescout-displays-incorrect-time

**Comment by lovetoast** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-freescout-displays-incorrect-time

Sorry my bad, thanks very much.

**Comment by bijomaru78** [comment]
Hi, this doesn't appear to be correct for me. We're in GMT+1 right now, and the clock on messages is still showing UTC (GMT+0) time.

Right now as I type this it's 3:17 PM (BST) here, and all the clocks are showing that, including on my server.

The Freecout settings currently show GMT+1 British Time, which should be correct.

Email just sent out to the client, despite showing "9 minute ago", on hover it shows UTC time, 14:08. This obviously isn't as important when viewing very resent emails as it will say x minutes/hours ago, but when viewing older email from some days ago, I'd want to be able to see the exact local time this was sent or received.

Am I missing something, or is it a bug with the time shown on hover not using the correct time zone?
