### ISSUE TITLE
Change default font size

### ISSUE THREAD

**Issue by webspeed1** [freescout-helpdesk/freescout#1139]
Hi,

Is it possible to change the default font size for the ticket replies? I find that the font is a little too small

**Comment by webspeed1** [comment]
do the questions on this forum get answered? i see many topics with no replies : (

**Comment by freescout-helpdesk** [comment]
Not possible by default. If anybody want, can be implemented via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
