### ISSUE TITLE
Change mailbox on reply and note

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1140]
Hi Guys,

I would like to have next to status and assigned also the option mailbox before sending reply.
Is this something more people want?

We work with 2 mailboxes and we switch mails from mailboxes a lot of times on a reply.
We are web development and every time it is a design question we like to change it to that mailbox on a reply/note.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to add to the core.
