### ISSUE TITLE
Knowledgebase improvement

### ISSUE THREAD

**Issue by lanc2112b** [freescout-helpdesk/freescout#1142]
If you have multiple mailboxes, you currently need to list or direct customers to different entry points, per mailbox. Likewise for the knowledgebase widget (or modification to provide a dropdown here).
Having a single point of entry to the knowledgebase where a customer can then select the relevant 'departments' article would be much simpler from the customers point of view. Also having 'global' articles would be pretty useful to save replication, and multiple edits on update where an identical article may be used.
Likewise the knowledgebase widget.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement.
