### ISSUE TITLE
Autoreply as action in Workflow module

### ISSUE THREAD

**Issue by cf39** [freescout-helpdesk/freescout#1143]
It would be good to have the action 'not send autoreply' as an option in the Workflow module, e.g. if sender = x / if subject contains y, do not send autoreply. Or even send custom autoreply.

It is possible to send mail as an action, but this appears in the conversation history, which is not always desirable.

**Comment by freescout-helpdesk** [comment]
Feel free to add to https://freescout.net/request-feature/
