### ISSUE TITLE
Workflow not applying value on custom field

### ISSUE THREAD

**Issue by lanc2112b** [freescout-helpdesk/freescout#1144]
I currently have a work flow setup to notify clients their tickets will close after 48 hrs. As part of that I have a custom field (dropdown/list) 'Progress'. One of the actions in the workflow is to set this to 'Close request'. 
When saving the workflow, this action does not stick, and reverts to the 1st value in the list.
Seems to happen with any of the workflows.

Freescout: 1.7.0 
PHP: 7.3.27

Before saving.
![before save](https://user-images.githubusercontent.com/2247147/113904928-7d852d80-97ca-11eb-976e-35ee98863aa9.png)

After saving
![after save](https://user-images.githubusercontent.com/2247147/113904921-7a8a3d00-97ca-11eb-836c-a745f9f137b7.png)

**Comment by freescout-helpdesk** [comment]
We will check it.

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Fields Module v1.0.8
