### ISSUE TITLE
API: Allow threads to update custom field values

### ISSUE THREAD

**Issue by zachf714** [freescout-helpdesk/freescout#1147]
It would be helpful if an inserted thread could also set custom field values on the conversation, or if there was an endpoint to update an existing conversations fields and status.

**Comment by fulldecent** [comment]
Here is the endpoint to update status

https://api-docs.freescout.net/#update-conversation

We do not have an endpoint yet to update fields

**Comment by freescout-helpdesk** [comment]
"update an existing conversations fields" - if you mean updating Custom Fields, here is the method: https://api-docs.freescout.net/#update-custom-fields
