### ISSUE TITLE
Default action when replying should be customizable

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#115]
Currently, when replying, the default action is to reply and move to the next conversation.

This should be configurable by each user, as not all users are confident to automatically move on next conversation. In some case it make confusion.

The button should also reflect the selected action and not a simple "Send reply"

**Comment by freescout-helpdesk** [comment]
It is already possible.

![2018-11-12_12-54-52](https://user-images.githubusercontent.com/40499291/48339892-3e466700-e67a-11e8-837c-8987aa454850.png)

**Comment by guestisp** [comment]
:sob: didn't see that
