### ISSUE TITLE
App\Jobs\SendAutoReply with Telegram Module

### ISSUE THREAD

**Issue by psuet** [freescout-helpdesk/freescout#1151]
When recieving a Telegram Message (via Bot) in a "Mailbox" with Auto-Reply enabled, a App\Jobs\SendAutoReply is scheduled but fails.

```SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `send_logs` (`thread_id`, `message_id`, `email`, `mail_type`, `status`, `customer_id`, `user_id`, `status_message`, `updated_at`, `created_at`) values (10982, autoreply-10982-a7ce4026f43a4491f1284bb38d96f440@aaa.de, , 3, 2, 1530, , Address in mailbox given [] does not comply with RFC 2822, 3.6.2., 2021-04-11 01:43:22, 2021-04-11 01:43:22)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `send_logs` (`thread_id`, `message_id`, `email`, `mail_type`, `status`, `customer_id`, `user_id`, `status_message`, `updated_at`, `created_at`) values (10982, autoreply-10982-a7ce4026f43a4491f1284bb38d96f440@aaa.de, , 3, 2, 1530, , Address in mailbox given [] does not comply with RFC 2822, 3.6.2., 2021-04-11 01:43:22, 2021-04-11 01:43:22)) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)```

Stacktrace: https://privatebin.at/?33951dd07f634566#BAQ16RzqxY1MEV99R6bWi1F5Vs43AS34rnLLuvuZCk94

**Comment by freescout-helpdesk** [comment]
OK. We'll check it.
