### ISSUE TITLE
API and Webhooks close failure

### ISSUE THREAD

**Issue by misushot** [freescout-helpdesk/freescout#1152]
API and Webhooks Close failure

when i close a ticket via curl see below, it will not change the folder to closed and stay in Assigned.

curl --insecure -X POST "https://xxx.de/api/conversations/1234/threads" \
    -H "X-FreeScout-API-Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXX" \
    -H "Content-Type: application/json" \
    -d '{"type":"note","text":"Automatisch geschlossen nach 24 Stunden","imported":false,"status":"closed","user":13}'
    
my workaround is a folderchange via sql in the conversations table:    
UPDATE 
`freescout`.`conversations` 
SET 
`folder_id`='4' 
WHERE 
`id`='1234'
;      

can you fix that please in your "API and Webhooks" module.

Thanks.

**Comment by freescout-helpdesk** [comment]
Fixed in API & Webhooks Module v1.0.19
