### ISSUE TITLE
Deleted conversations in the search

### ISSUE THREAD

**Issue by misushot** [freescout-helpdesk/freescout#1153]
when i delete more tickets it will be count in reports module as open tickets.
Only when i close and delete the ticket it will not be count.

can you fix that please in your "Reports" module.

Thanks

**Comment by freescout-helpdesk** [comment]
Please send a screenshot.

**Comment by CH4931** [comment]
The reporting module doesn't give us a daily number of open tickets, hence we are using a workaround via the search function.

To get to the total number of open tickets, we use the 'serach' function with a filter for 'status' for 'active' (Warte auf WD) and 'pending' (Warte auf Kunden). However, we noticed that deleted tickets show up in this search / count as well.
Screenshot below:

![image](https://user-images.githubusercontent.com/82586443/114864048-d0756b00-9df0-11eb-923f-651be598c377.png)

 
We currently have to delete the bin prior to using our workaround to get an accurate count of open tickets.

**Comment by freescout-helpdesk** [comment]
Duplicates https://github.com/freescout-helpdesk/freescout/issues/912
