### ISSUE TITLE
S3 storage for attachements

### ISSUE THREAD

**Issue by laurivosandi** [freescout-helpdesk/freescout#1156]
It was a bad surprise to discover that attachments don't work after moving docker container to another machine. Please either have a big fat disclaimer that attachments are stored in local filesystem or add S3 support to store attachments in a cloud native fashion.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/674#issuecomment-661600148

**Comment by laurivosandi** [comment]
A bit more elaborated answer would be useful here - is this already supported? How can I migrate existing stuff to S3? etc

**Comment by freescout-helpdesk** [comment]
Try to google Laravel and S3.

**Comment by DerDanilo** [comment]
I couldn't find official information on how to configure this in FreeScout. It would be great if there was a how to in the manual or even better, a module that allows to configure this in the UI to avoid trouble with misconfiguration. Thanks!

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/pull/5603
