### ISSUE TITLE
Open all (unread) in new tabs.

### ISSUE THREAD

**Issue by jtagcat** [freescout-helpdesk/freescout#1157]
Like in GitHub Refined:  
![image](https://user-images.githubusercontent.com/38327267/114548644-915be400-9c4f-11eb-9b02-b1c445ab5df8.png)

Opens 4 tabs (in this example).

**Comment by freescout-helpdesk** [comment]
Can be implemented via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
