### ISSUE TITLE
Update error try other method

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1159]
Hi guys,

I get this error that i need to try another update method.
Though all went well if i refresh.

How safe is it to go on if i have gotten that error?

Here you see it in a video (sorry freescout is in dutch)
https://www.dropbox.com/s/botha1fauia0nzz/Update%20error.mov?dl=0

Thanks!

**Comment by freescout-helpdesk** [comment]
Sometimes when updating finishes you may see the "Error occurred" message, but FreeScout shows a new version and functions normally.
