### ISSUE TITLE
Attachment not showing in tickets sent from Microsoft Outlook app

### ISSUE THREAD

**Issue by lakym86** [freescout-helpdesk/freescout#1162]
When receiving mails with attachment and also has pictures in signature, attachment not showing in ticket. Noticed that this occurs only sending mails from outlook client app

Tryed folowing:

- without pictures in signature OK
- sending from gmail account OK
- sending from webmail (our server) OK
- MIcrocoft Outlook - from two mail servers NOT SHOWING ATTACHMENT

If you need additional information please write.

**Comment by freescout-helpdesk** [comment]
Try to write the instruction on how to reproduce the issue, inluding what do you mean under "MIcrocoft Outlook" (web client or something else), how you add picture, etc.

**Comment by lakym86** [comment]
Hi,

Thanks for your reply. I think with pictures it is easier to show the issue:
![1](https://user-images.githubusercontent.com/36364577/115665307-67877900-a343-11eb-9e23-b5302a7dac8f.png)
![2](https://user-images.githubusercontent.com/36364577/115665322-6fdfb400-a343-11eb-95d6-300864e2acb3.png)
![3](https://user-images.githubusercontent.com/36364577/115665343-75d59500-a343-11eb-9040-eac045d72bcd.png)
![4](https://user-images.githubusercontent.com/36364577/115665352-7a01b280-a343-11eb-897d-e637c62e2082.png)
![5](https://user-images.githubusercontent.com/36364577/115665358-7ec66680-a343-11eb-9cb2-aa283dff9c42.png)

**Comment by lakym86** [comment]
I have tryed also with the modul Block External Images, but the same issue

**Comment by freescout-helpdesk** [comment]
Which Microsoft Outlook client are you using?

**Comment by lakym86** [comment]
Office365
Details:
Microsoft Outlook for Microsoft 365 MSO  - app (not a web client)

**Comment by flaxplax** [comment]
We have a problem where attachments and pictures won't show that are coming from exchange sent with outlook.

Have tried to sent a mail with outlook and a google account: Works fine
Have tried to sent a mail with outlook and hotmail account: Attachments don's show
But I can see the symbol in freescout that shows that the email contains attachments.

The email body in freescout looks like this:
From google account with outlook:
```
<div class="WordSection1"><p class="MsoNormal"><img width="598" height="202" style="width:6.2291in;height:2.1041in" id="Picture_x0020_1" src="https://freescout.internal.bluetest.se/storage/attachment/1/4/26/image001.png?id=22504&token=c3d675641d9730bd118a4a5084a9109c"><span lang="SV"><p></p></span></p><p class="MsoNormal"><span lang="SV">Copied from clipboard<p></p></span></p><p class="MsoNormal"><span lang="SV"><p> </p></span></p></div>
```
From hotmail account with outlook:
```
<div class="WordSection1">
<p class="MsoNormal"><span lang="SV">Small picture<p></p></span></p>
<p class="MsoNormal"><span lang="en-SE"><img width="475" height="538" style="width:4.9479in;height:5.6041in" id="Picture_x0020_1" src="cid:image001.png@01D86926.79E76070"></span><span lang="en-SE"><p></p></span></p>
<p class="MsoNormal"><span lang="SV">Large picture <p></p></span></p>
<p class="MsoNormal"><span lang="SV"><img width="1588" height="896" style="width:16.5416in;height:9.3333in" id="Picture_x0020_2" src="cid:image002.png@01D86926.79E76070"></span><span lang="SV"><p></p></span></p>
<p class="MsoNormal"><span lang="SV"><p> </p></span></p>
</div>
```

**Comment by bjoas** [comment]
We are also seeing this problem which is a major issue. Being unable to receive support emails for all Exchange users is really a big problem for enterprise customers as Exchange is very common.

**Comment by freescout-helpdesk** [comment]
> Have tried to sent a mail with outlook and hotmail account: Attachments don's show

Can you attach a body of such email?

**Comment by flaxplax** [comment]
> > Have tried to sent a mail with outlook and hotmail account: Attachments don's show
> 
> Can you attach a body of such email?

This is the body i get in freescout from such mail
```
<div class="WordSection1">
<p class="MsoNormal"><span lang="SV">Picture below here<p></p></span></p>
<p class="MsoNormal"><span lang="en-SE"><img width="354" height="64" style="width:3.6875in;height:.6666in" id="Picture_x0020_1" src="cid:image001.png@01D8693E.BE86BE20"></span><span lang="en-SE"><p></p></span></p>
<p class="MsoNormal"><span lang="SV">Bigger picture below here<p></p></span></p>
<p class="MsoNormal"><span lang="SV"><img width="1459" height="1029" style="width:15.1979in;height:10.7187in" id="Picture_x0020_2" src="cid:image002.png@01D8693E.BE86BE20"></span><span lang="SV"><p></p></span></p>
</div>
```

**Comment by freescout-helpdesk** [comment]
> Have tried to sent a mail with outlook and hotmail account: Attachments don's show

We've just tested it using Microsoft Outlook on Windows and the image is visible in the FreeScout.

Can you send a sample email from Microsoft Outlook to support@demo.freescout.net?

**Comment by flaxplax** [comment]
> > Have tried to sent a mail with outlook and hotmail account: Attachments don's show
> 
> We've just tested it using Microsoft Outlook on Windows and the image is visible in the FreeScout.
> 
> Can you send a sample email from Microsoft Outlook to [support@demo.freescout.net](mailto:support@demo.freescout.net)?

Just sent you an example email that don't work for us

**Comment by freescout-helpdesk** [comment]
The image is visible at https://demo.freescout.net

![2022-05-16_17-48-05](https://user-images.githubusercontent.com/40499291/168620446-a74f2738-31fe-46af-9e40-dd0a725933fb.png)

**Comment by flaxplax** [comment]
> The image is visible at https://demo.freescout.net
> 
> ![2022-05-16_17-48-05](https://user-images.githubusercontent.com/40499291/168620446-a74f2738-31fe-46af-9e40-dd0a725933fb.png)

Yeah I see that. 
What setting could cause it not to work?
"It works on my machine" Would not really make my problem easier to troubleshoot.
Any ideas? Could it be php size limit or something of that sort?

**Comment by freescout-helpdesk** [comment]
Are you using the latest FreeScout?
Are you fetching emails in FreeScout using modern Microsoft Exchange authentication or IMAP?

**Comment by flaxplax** [comment]
> Are you using the latest FreeScout? Are you fetching emails in FreeScout using modern Microsoft Exchange authentication or IMAP?

Updated to latest freescout earlier today.
Fetching mail from google IMAP account

**Comment by freescout-helpdesk** [comment]
You may need to find someone who can debug it on your server. See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by flaxplax** [comment]
Problem solved.
Did some import from console as root. So the the error was wrong folder permission
```
[2022-05-17 16:09:08] Error: file_put_contents(/var/www/html/storage/app/attachment/6/0/1/duckduckgo_small.png): failed to open stream: Permission denied; File: /var/www/html/vendor/league/flysystem/src/Adapter/Local.php (129)
```
Better logging would probably help find this issue quicker, since the web interface showed OK on all permission.

**Comment by fulldecent** [comment]
Folder permissions are now debugged in Settings > System.

Recommending to close issue
