### ISSUE TITLE
Bug in Facebook module

### ISSUE THREAD

**Issue by dokonalytrik** [freescout-helpdesk/freescout#1164]
Hi,
I installed facebook module and everthing worked well. I recived message from FB and i can replied from Freescout. It work really well.

But when I try sent meesage from FB  with small attachement (picture), I did not recived message and conection with Freescout stop working. Now i can not recived any meesages from FB .

I used Freescout on Cloudrone.

I check error log but i did not see **“Manage » Logs » Facebook Errors” in FreeScout**
![scout](https://user-images.githubusercontent.com/80348297/114859748-758d4500-9deb-11eb-8c90-9c255ddcdc91.JPG)

When i check   Webhook’s “Show Recent Errors” on Facebook ...there are no errors

any recomand ? @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
Check App Logs.

**Comment by dokonalytrik** [comment]
I check it, @freescout-helpdesk  there are no errors. When I try it with diferent FB pages...same problem.
When send message  from FB to Freescout  with picture .... conection stop worknig...

**Comment by dokonalytrik** [comment]
The last error info which i found in App logs @freescout-helpdesk 

Error sending payload: (#100) Žádný odpovídající uživatel {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#100) Žádný odpovídající uživatel at /app/data/Modules/Facebook/vendor/botman/driver-facebook/src/FacebookDriver.php:516)
[stacktrace]
#0 /app/data/Modules/Facebook/vendor/botman/driver-facebook/src/FacebookDriver.php(411): BotMan\\Drivers\\Facebook\\FacebookDriver->throwExceptionIfResponseNotOk()
#1 /app/data/Modules/Facebook/vendor/botman/botman/src/BotMan.php(655): BotMan\\Drivers\\Facebook\\FacebookDriver->sendPayload()
#2 [internal function]: BotMan\\BotMan\\BotMan->BotMan\\BotMan\\{closure}()
#3 /app/data/Modules/Facebook/vendor/mpociot/pipeline/src/Pipeline.php(114): call_user_func_array()
#4 [internal function]: Mpociot\\Pipeline\\Pipeline->Mpociot\\Pipeline\\{closure}()
#5 /app/data/Modules/Facebook/vendor/mpociot/pipeline/src/Pipeline.php(102): call_user_func_array()
#6 /app/data/Modules/Facebook/vendor/botman/botman/src/Middleware/MiddlewareManager.php(126): Mpociot\\Pipeline\\Pipeline->then()
#7 /app/data/Modules/Facebook/vendor/botman/botman/src/BotMan.php(656): BotMan\\BotMan\\Middleware\\MiddlewareManager->applyMiddleware()
#8 /app/data/Modules/Facebook/vendor/botman/botman/src/BotMan.php(642): BotMan\\BotMan\\BotMan->sendPayload()
#9 /app/data/Modules/Facebook/vendor/botman/botman/src/BotMan.php(560): BotMan\\BotMan\\BotMan->reply()
#10 /app/data/Modules/Facebook/Providers/FacebookServiceProvider.php(154): BotMan\\BotMan\\BotMan->say()
#11 [internal function]: Modules\\Facebook\\Providers\\FacebookServiceProvider->Modules\\Facebook\\Providers\\{closure}()
#12 /app/code/overrides/TorMorten/Eventy/Action.php(27): call_user_func_array()
#13 /app/code/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\\Eventy\\Action->TorMorten\\Eventy\\{closure}()
#14 /app/code/overrides/TorMorten/Eventy/Action.php(28): Illuminate\\Support\\Collection->each()
#15 /app/code/vendor/tormjens/eventy/src/Events.php(139): TorMorten\\Eventy\\Action->fire()
#16 /app/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TorMorten\\Eventy\\Events->action()
#17 [internal function]: Illuminate\\Support\\Facades\\Facade::__callStatic()
#18 /app/code/app/Jobs/TriggerAction.php(42): call_user_func_array()
#19 [internal function]: App\\Jobs\\TriggerAction->handle()
#20 /app/code/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#21 /app/code/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /app/code/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /app/code/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#24 /app/code/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#25 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#26 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /app/code/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#28 /app/code/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#29 /app/code/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#30 /app/code/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#31 /app/code/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#32 /app/code/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#33 /app/code/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#34 /app/code/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#35 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#36 /app/code/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#37 /app/code/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#38 /app/code/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#39 /app/code/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#40 /app/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#41 /app/code/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#42 /app/code/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#43 /app/code/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#44 /app/code/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#45 /app/code/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#46 /app/code/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#47 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#48 /app/code/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle()
#49 {main}
"}

**Comment by freescout-helpdesk** [comment]
Is your company/organization based in Europe or page administrator is from Europe or user writing to FB page is from Europe?

Also check “Show Recent Errors” in the Webhook on Facebook.

**Comment by dokonalytrik** [comment]
@freescout-helpdesk 
Yes our company based in Europe, page administrator is from Europe and users writing to FB page are from Europe

I  check “Show Recent Errors” in the Webhook on Facebook. There is no Errors.
![webhook](https://user-images.githubusercontent.com/80348297/114981196-e71dcf80-9e8d-11eb-89f8-4e8e9ce5a9ed.JPG)

**Comment by pmhtuk** [comment]
We had a similar issue. As the admin (in fact our whole organisation and customers) are within Europe, the Facebook integration now fails since January on our site due to the new GDPR style rules Facebook have implemented. 

Until they decide a way around, there's nothing we can do. Freshdesk seems to be the only org which mentions this (other than Freescout) as an issue affecting users within Europe (and apparently Japan from April too) - https://support.freshdesk.com/support/solutions/articles/50000003159-how-the-facebook-messenger-api-update-for-europe-impacts-freddy-ai-customers

**Comment by freescout-helpdesk** [comment]
Thanks. We've extended "Limitations" section of https://freescout.net/module/facebook/

**Comment by dokonalytrik** [comment]
However, this does not solve the problem that it stops working after sending the attachment. How is it possible that it works before this, and when I send the attachment, all communication stops working? I understand that there is another limitation, but that does not solve the fact that the module will stop working after that. Reinstallation does not help. No messages can be received or sent. How to solve this?

**Comment by freescout-helpdesk** [comment]
Maintenance and support of this module https://freescout.net/module/facebook/ has been discontinued, as Facebook now imposes too much limitations and requires “page_messaging” permission for the app to receive (which is close to impossible).

**Comment by babu97** [comment]
hello, I am getting this error when in my logs what could be the issue? 
![image](https://user-images.githubusercontent.com/32389593/198271252-89834004-5300-4336-9d70-86ff5aec261d.png)
