### ISSUE TITLE
Module CRM: questions before buying

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#1166]
Hi,

first, after almost 2 years of being a happy user/sysadmin of FreeScout (meanwhile for 3 non-profit organizations) I want to express my gratitude for this great piece of software! In the meanwhile for those 3 instances also bought a lot of modules.

Now I'm looking at the CRM module because default install doesn't show and/or let you manage "customers".

I have a couple of questions:

1. is it possible to import "customers"?
2. is it possible to merge "customers" as now already we see (by searching) that there are multiple entries of the same email address.
3. do you have any suggestions or experience with syncing "customers" with EspoCRM?

Thanks for your time and answers.

Regards,

Marcel.

**Comment by cf39** [comment]
I bought this module a few days ago.

1. No, for some reason only export. This would be an important feature though.
2. I noticed this as well and assume it is s bug. There does not seem to be a way to merge customers with the same email address.
3. Can't help you with this one, but would also be a nice integration to have.

**Comment by freescout-helpdesk** [comment]
> 1. is it possible to import "customers"?

Unfortunately, not.

> 2. is it possible to merge "customers" as now already we see (by searching) that there are multiple entries of the same email address.

This is strange. Can you give screenshots of two different customers with the same email?

> 3. do you have any suggestions or experience with syncing "customers" with EspoCRM?

Unfortunately, not.

**Comment by imc67** [comment]
> is it possible to merge "customers" as now already we see (by searching) that there are multiple entries of the same email address.

I just tried to reproduce it and I can't anymore. It happened minutes after importing/migrating a mailbox. Could it be there is a scheduled job to check somehow? Anyway that is no problem anymore.

**Comment by dariospace** [comment]
Nice job with the CRM module 🏄🏼‍♂️

We've bought the CRM module. The only issue we are having is that it shares customers between Mailboxes. If there's a mailbox for sales and another one for support or administration, contacts are shared between mailboxes. 

We would expect contacts to be isolated in each mailbox as Saved Replies and Workflows are.
