### ISSUE TITLE
Error on fetching

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#1167]
On all three FreeScout instances I manage I get irregular (5-15 times a day) fetching errors, do you have any idea what this is and why? (All three FreeScout instances on three different Cloudron servers):

`Error: imap_open(): Couldn't open stream {subdomain.domain.nl:993/imap/ssl}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate); File: /app/code/overrides/Webklex/IMAP/Client.php (230)`

**Comment by freescout-helpdesk** [comment]
This may happen when there are connection problems to your IMAP server.
