### ISSUE TITLE
Add Prometheus endpoint

### ISSUE THREAD

**Issue by laurivosandi** [freescout-helpdesk/freescout#1169]
I have no visibility about the reliability of the importer and there is no indication in UI when it breaks

Please add Prometheus endpoint which would expose:
* Failed/successful IMAP scrapes
* Failed/successful e-mail imports

I also have an example of a mail that for whatever reason was not successfully imported.

**Comment by freescout-helpdesk** [comment]
Can be implemented as a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide
