### ISSUE TITLE
Delayed notifications

### ISSUE THREAD

**Issue by laurivosandi** [freescout-helpdesk/freescout#1170]
I think it doesn't make sense Freescout to spam the user with e-mail notifications if the user has just checked the conversation on Freescout.

Please add delayed notifications so the actual notification mail is sent eg within 15min if user hasn't opened that conversation in Freescout

**Comment by freescout-helpdesk** [comment]
Feature can be implemented as a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
