### ISSUE TITLE
Passing value to end user portal widget

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1172]
Hello, 

For authenticated app users we want to pass the "email" to the end user portal widget so that customer doesn't have to write it again while being inside our app. 

I think there should be a way to set the name, email and even content for the portal widget, this will help in integrations with custom apps.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
