### ISSUE TITLE
Module Sales Questions

### ISSUE THREAD

**Issue by KatyaJansen** [freescout-helpdesk/freescout#1173]
Hi,

Does the the end user module allow customers (end users) to sign in and see tickets etc via the iOS app?

Any way to allow registered end users to submit tickets, and all other tickets get sent to a separate folder or are not created at all? 

Does the chat module work from inside the iOS app?

Thanks

Katya

**Comment by freescout-helpdesk** [comment]
Questions are not quite clear. You can check everything via https://demo.freescout.net
