### ISSUE TITLE
User (Agents) management unavailable after LDAP Authentication enabled 

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#1176]
After LDAP integration and authentication enabled we have lost access to freescout.domain/users  
After some workaround I have found we have one user in a LDAP with empty field <secondName> which was binded in Attributes Mapping of the LDAP module settings.

So the empty value of <secondName> field braking  the [manage/Users] section of web UI

**Comment by freescout-helpdesk** [comment]
Can you post an full error message from Manage > Logs > App Logs

**Comment by sau7777** [comment]
There is nothing in the log corresponding ti this issue

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. Make sure that all the required fields are non-empty in your LDAP.
