### ISSUE TITLE
When forwarding an email

### ISSUE THREAD

**Issue by richhickson** [freescout-helpdesk/freescout#1177]
Is it possible to pick up the original email address as the customer rather than my email? Sometimes clients email me directly and I forward it to the helpdesk for one of the team to pick up, but it makes me the customer rather than the original sender?

**Comment by datznoah** [comment]
click "New Conversation"

![image](https://user-images.githubusercontent.com/40122768/116836989-48cc8200-ab8e-11eb-84ef-88a9029f68bd.png)

Problem is that you have to "respond" to them essentially, you can't add their message to have other people reply to. Only other solution that comes to mind is using the API, but that's a paid module. could be missing something. ;)

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible.
