### ISSUE TITLE
when Saving a ticket

### ISSUE THREAD

**Issue by richhickson** [freescout-helpdesk/freescout#1178]
When saving or modifying a ticket, is it possible to switch off the automatically going to the next ticket?

**Comment by sau7777** [comment]
Here is what you need:
![freescout](https://user-images.githubusercontent.com/8371994/115950814-2f6c6b80-a4e6-11eb-9456-bceeda8edba2.jpg)

**Comment by freescout-helpdesk** [comment]
@sau7777 thanks for helping
