### ISSUE TITLE
update to 1.7.3 shows success message but did not update

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1179]
https://github.com/freescout-helpdesk/freescout/releases/tag/1.7.3

Trying to upgrade from 1.7.2. to 1.7.3
Message shows upgrade is successful
Page refreshes, but the version is still on 1.7.2
Not sure if the code has updated at all.

Is there a way to check?
M

**Comment by sau7777** [comment]
The same issue

**Comment by szucher** [comment]
same issue

**Comment by freescout-helpdesk** [comment]
Fixed in 1.7.4 release.

**Comment by raramuridesign** [comment]
Thanks for fixing so quickly all works ;-)
