### ISSUE TITLE
API Time date format not exactly ISO 8601?

### ISSUE THREAD

**Issue by TheNerdSquad** [freescout-helpdesk/freescout#1181]
Noted when calling API that the time being given in the response is of 2021-04-22T08-35-01Z format, to which is not to the ISO 8601 standard, as that is to be 2020-01-02T23:00:00Z

the - dashes are causing it to give errors whenever called, the API docs state the format should be ISO 8601, error or am I looking at things incorrectly?

**Comment by freescout-helpdesk** [comment]
It's an error. Will be fixed.

**Comment by TheNerdSquad** [comment]
Cool as you guys are creating a really nice platform and its code is very well written for a bit there thought I was just having some type of issue or doing something wrong.

Ultimately it was simply just a swap of the - with : and was good to go for my purposes but figured I could not locate why it was doing that and decided to report the issue with entire expectation of myself being the issue lol.

Generally however, thank you for a really nice platform to use and I look forward to seeing what else might be in this software's future as I really do like the whole thing. In fact being that I have used many ticket systems this one is seriously the most clean and easy to use as well as very versatile and fast with minimal upkeep and requirements.

**Comment by freescout-helpdesk** [comment]
Fixed in API & Webhooks Module v1.0.21
