### ISSUE TITLE
Workflow - Buggy Custom Field ?

### ISSUE THREAD

**Issue by dokonalytrik** [freescout-helpdesk/freescout#1182]
Hello, @freescout-helpdesk 
Can you help me with Workflow module? I have set very simple workflow, but it looks like workflow doesnt work as it should.

Condition are:
(Tagged: “A”) AND (status “pending”) AND (custom field on exact date “is today”)

Actions are:
(Change status: Active) AND (add tagg “B”)

The problem is that workflow triggering even if two of three conditions are “true” (Taged: “A”) AND (status “pending”) but custom field is empty (false). 
Can anyone explain to me, why workflow module evaluate empty custom field as a “true”?

![custom1](https://user-images.githubusercontent.com/80348297/116098783-9f781e80-a6ab-11eb-9982-2cfc3f81eecc.JPG)
![custom2](https://user-images.githubusercontent.com/80348297/116098842-abfc7700-a6ab-11eb-98b0-19be1906acb5.JPG)

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in Custom Fields Module v1.0.9
