### ISSUE TITLE
Mailbox setup "The email has already been taken."

### ISSUE THREAD

**Issue by j26w** [freescout-helpdesk/freescout#1183]
Hi, I'm setting up my first installation of FreeScout, and was hoping to be able to use one email account (admin@) for all of my different mailboxes instead of having to purchase multiple Microsoft 365 licenses. The plan was to setup filter rules in Outlook to route the emails to different folders and then use the IMAP Folders setting in Fetching Emails settings to pull the appropriate emails. All outgoing emails would be sent from admin@, which is fine. I set a unique Email Header setting for each mailbox to allow for an Outlook rule on the message body that ensures replies go to the appropriate Outlook folder (a clever workaround, I thought). All is working fine for the first mailbox, but upon trying to setup the second mailbox with the same admin@ email, I unfortunately got the "The email has already been taken" error.

Is it not possible from a technical standpoint to use the same email address for multiple mailboxes? Or was this a safeguard to ensure people don't run into the replies issue? In other words, if I were to remove this error checking, would it break the app?

I'm loving the app so far, and have already purchased a few modules, but the additional cost of having to purchase a microsoft license for each of the 5 mailboxes is an unexpected cost that the boss won't be happy about. I know we could setup a subdomain and use a cheaper email provider for those accounts, but we'd like to keep it all on the main domain, if possible.

Thanks

**Comment by freescout-helpdesk** [comment]
You can try comment this check in the code and remove UNIQUE flag from the index in DB. Most likely the app will work fine for you.

**Comment by j26w** [comment]
Okay, great to hear. Thanks for the quick reply. Do you happen to know off the top of your head which files I need to edit?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/MailboxesController.php
