### ISSUE TITLE
Average Response Time Reporting

### ISSUE THREAD

**Issue by designloud** [freescout-helpdesk/freescout#1184]
Hi, is it possible to include "Average Response Time" in the reporting section?  I noticed Helpscout did this but don't see that in here.  I have no problem custom coding this but I'd like to know if I should use the API and it seems like I'd use the convo.created and convo.status events or would this be something we code into the app directly.  If it's the later then would we run into any issues on future updates?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
