### ISSUE TITLE
KB v1.0.12

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1185]
Knowledge base portal, like the one shown below, shows articles from all the mailboxes, even if I open the KB for a particular mailbox. 

Please fix this bug.

<img width="1510" alt="Screenshot 2021-04-28 at 5 31 00 PM" src="https://user-images.githubusercontent.com/1262327/116400290-81dfbc00-a847-11eb-92f2-8d52c4a2f6a5.png">

This particular mailbox as "0" articles

<img width="836" alt="Screenshot 2021-04-28 at 5 32 03 PM" src="https://user-images.githubusercontent.com/1262327/116400459-afc50080-a847-11eb-8185-dc905808f781.png">

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module 1.0.13
