### ISSUE TITLE
Saved Replies module not showing downdown

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1188]
We are running latest version of Freescout and Saved replies module. But when opening the dropdown , it shows nothing

<img width="256" alt="Screenshot 2021-05-04 at 11 24 03 AM" src="https://user-images.githubusercontent.com/1262327/116965458-7c60f680-accb-11eb-9d9c-a14e8d2cbaa4.png">

PS: We have saved 4 saved replies for this mailbox.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-after-updating-to-the-new-version-the-module-does-not-work-properly

**Comment by vikasprogrammer** [comment]
Thank you , I re-created the symlinks and it seems to be working now.
