### ISSUE TITLE
Office hours - where to configure ?

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1189]
I know that "Chat" module has its own "office hours", but there is a setting in "Auto Reply" section of the mailbox, I am not sure where to set it from and how it works. Couldn't find anything in the documentation also. 

<img width="1232" alt="Screenshot 2021-05-04 at 12 10 58 PM" src="https://user-images.githubusercontent.com/1262327/116968291-d6fd5100-acd1-11eb-8de4-ad1996312206.png">

**Comment by mywebhero** [comment]
Yup, I have the same question as well.

**Comment by datznoah** [comment]
Assuming it is/was a module of some sort?

**Comment by freescout-helpdesk** [comment]
These Operating Hours are applied to the Chat only. Mailbox Auto Reply does not have it’s Office Hours configuration.

Unfortunately no plans to add Office Hours to the core of the app.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/office-hours/

**Comment by vikasprogrammer** [comment]
what an awesome job!
