### ISSUE TITLE
Discrepancy of numbers for closed items via 'Search' and 'Report' 

### ISSUE THREAD

**Issue by CH4931** [freescout-helpdesk/freescout#1191]
Hi there,

we noticed a discrepancy of number for closed items when using the 'search' function and the productivity report.

When filtering for the status 'closed' via the search function, we see the number of tickets closed.
The screenshot below, shows tickets closed 04.05.2021 - a total of about 14.
<img width="134" alt="image" src="https://user-images.githubusercontent.com/82586443/117107524-01a6e280-ad82-11eb-9733-1b49a8c680a4.png">

When using the reporting module to filter for closed tickets for 04.05.2021 shows only 1 closed ticket. Please see the screenshot below:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/82586443/117107715-53e80380-ad82-11eb-8653-98980a7c4381.png">

Please advise.

**Comment by freescout-helpdesk** [comment]
"Closed" number shows the number of conversations which has been closed in the selected period. This number may differ from the number of closed conversations in the Search, as the Search shows conversations created in the selected period which are currently closed.
