### ISSUE TITLE
The reply text is not included in the message

### ISSUE THREAD

**Issue by devtest8** [freescout-helpdesk/freescout#1192]
Hello,

My clients are sending the replies with the answers, but i don't see them.
I have the last 1.7.4 ver. Freescout.

The original reply message in Gmail:
![4bVoJfg 1](https://user-images.githubusercontent.com/55086500/117110591-07ef8b80-ad8f-11eb-8705-a979fcde7371.png)

The received message in Freescout:
![4bVodGh 1](https://user-images.githubusercontent.com/55086500/117110684-30778580-ad8f-11eb-8cce-b20dee6f53b9.png)

**Comment by freescout-helpdesk** [comment]
See Original Message under three dots.
