### ISSUE TITLE
Keyboard shortcut to send message

### ISSUE THREAD

**Issue by pschoenmakers** [freescout-helpdesk/freescout#1193]
I'm so used to being able to send a message with ⌘-enter in HS and gmail. 

Would it be possible to add this to the keyboard shortcurts module?

**Comment by freescout-helpdesk** [comment]
Feel free to edit the source code of the module.

**Comment by pschoenmakers** [comment]
Where do you host the repository of the modules ? Or can I upload all modules to GitHub. As it's released as AGPL that should be ok?

**Comment by freescout-helpdesk** [comment]
Updates will not be added to the module. You can edit it for your own usage.
