### ISSUE TITLE
Saved Replies are not working correctly. 

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1197]
When a save a reply - All ok
When you use the same reply - content from other mailboxes may conflict. 

<img width="500" alt="Screenshot 2021-05-07 at 4 56 33 PM" src="https://user-images.githubusercontent.com/1262327/117443061-3919b880-af55-11eb-82e7-96bd87c5ab16.png">

<img width="1261" alt="Screenshot 2021-05-07 at 4 56 26 PM" src="https://user-images.githubusercontent.com/1262327/117443073-3cad3f80-af55-11eb-9ed8-93f1c5f50702.png">

<img width="825" alt="Screenshot 2021-05-07 at 4 56 42 PM" src="https://user-images.githubusercontent.com/1262327/117443078-3f0f9980-af55-11eb-9b94-78fefc2719ff.png">

I think its not even creating the save reply at the right mailbox, the current mailbox's saved replies window is empty

<img width="979" alt="Screenshot 2021-05-07 at 4 59 52 PM" src="https://user-images.githubusercontent.com/1262327/117443352-a62d4e00-af55-11eb-9654-14e9b14ae817.png">

**Comment by freescout-helpdesk** [comment]
The issue is not quite clear.

**Comment by vikasprogrammer** [comment]
When you save a reply via "Save this reply", it doesn't get saved properly. It gets mixed up with another mailboxes saved reply. Next time when you try to use that saved reply, the output content is entirely different.

**Comment by freescout-helpdesk** [comment]
Unfortunately, we can't reproduce the issue.
