### ISSUE TITLE
Show number of conversations inside each folder

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#120]
Currently, only active conversations are counted. This is misleading, as you could have tens of conversations inside a folder without being noticed (maybe someone else has replied changing from Active to Pending).

I think that the conversation counter should be something like: `Active / Total` or `Active of Total`, in example:

`1 / 234` or `1 of 234` or `0 / 234`

**Comment by freescout-helpdesk** [comment]
Let' s add a global settings to enable this in Settings and if there are active conversations display first number in bold: **1** / 234. If there are no active conversations, display just total number: 234

**Comment by guestisp** [comment]
Ok. As confirm, I think I have to duplicate the `Folder->getActiveCount()` in `Folder->getTotalCount()` to count only total conversations related to logged users, right?

**Comment by freescout-helpdesk** [comment]
There are two types of folder:
- Common folders (Unassigned, Drafts, Assigned, Closed, Spam, Deleted).
- Personal folders (Mine, Starred), they are counting conversations on per user basis.

**Comment by freescout-helpdesk** [comment]
OK as is for now. If anybody will need to see total number of conversations, they can implement it as module.
