### ISSUE TITLE
WhatsApp module create tons of tickets after connect

### ISSUE THREAD

**Issue by mywebhero** [freescout-helpdesk/freescout#1201]
I just tested recently release WhatsApp module. But once I created, it create tons of tickets from unread message.
Also, the flaw is I can't see previous conversations in the same contact.

Is it designed to be this way or it is a bug?

**Comment by mywebhero** [comment]
I already sent screenshot via email as it contain info I shouldn't share publicly.
But is the module allow us to see all previous message?

Also, am I able to see WhatsApp message reply directly via phone?

**Comment by freescout-helpdesk** [comment]
Messages on your screenshot are not related to WhatsApp integration (they don't have WhatsApp badge).

Replies to WhatsApp conversations in FreeScout are sent to WhatsApp.

**Comment by freescout-helpdesk** [comment]
See Step 4 of the Instruction section: https://freescout.net/module/whatsapp/

**Comment by mywebhero** [comment]
That don't make sense as well because we will need to check previous message from the same number.
