### ISSUE TITLE
JavaScript is not included in End User Portal "Widget"

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1203]
When the Contact Us widget is rendered in End User Portal, it doesn't load the JavaScript properly. 

```
{!! Minify::javascript(['/js/jquery.js', '/js/bootstrap.js', '/js/lang.js', '/storage/js/vars.js', '/js/laroute.js', \Module::getPublicPath(EUP_MODULE).'/js/laroute.js', \Module::getPublicPath(EUP_MODULE).'/js/main.js', \Module::getPublicPath(EUP_MODULE).'/js/widget_form.js', '/js/main.js']) !!}
```
Notice the missing `{!! Minify::javascript(\Eventy::filter('javascripts',...` 

If you can add Eventy::filter to this line, we will be able to load our custom module's javascript into the widget (and the portal).

Note: It loads the stylesheets perfectly fine. 

**Files affected**
layouts > widget_form.blade.php
layouts > portal.blade.php

**Comment by freescout-helpdesk** [comment]
Filter has not been added intentionally, as modules' JS may disrupt End-User Portal.

`eup.javascripts` filter has been added in End-User Portal Module v1.0.13

**Comment by vikasprogrammer** [comment]
Thanks for `eup.javascripts` but you have to do it in 2 more places. 

enduserportal > widget_form.blade.php

and add `kb.javascripts` in following pages. 

knowledgebase > portal.blade.php
knowledgebase > widget_form.blade.php

We will be greatful.

**Comment by vikasprogrammer** [comment]
@freescout-helpdesk Please check this.

**Comment by freescout-helpdesk** [comment]
Added the following hooks:

- eup.widget_form.javascripts
- kb.javascripts
- kb.widget_form.javascripts

Make sure to update modules to their latest versions.

**Comment by scout-devs** [comment]
Thank you!
