### ISSUE TITLE
Feature Request: Attachments

### ISSUE THREAD

**Issue by mojiro** [freescout-helpdesk/freescout#1204]
Hello,

I have been using Freescout for few days and I have find really easy and straight forward to install and use contrast to other platforms.

I have some suggestions for the Attachments that I believe many people could get benefited by these.

1) List of attachments - When I am viewing a mail thread, it could be convenient, to have a list of all attachments that were exchanged through this thread. That list could be located at the right sidebar, under the customer details.

2) Global search, could also search for attachment filenames.

3) Advanced attachment search. A search only for attachments by date and by customer.

Those ideas came to me, because plenty times, I have discussions with customers, telling me that "I had send you this", please check it.

Keep up the good work.

**Comment by joris85** [comment]
That looks great!

Is it an idea to have there also the option to choose 'Download all'?
I can also imagine that these attachments are in the right sidebar under each-other.

Does there changes stay after an update?
Is this possible in an override instead of core?

**Comment by mojiro** [comment]
Hello @joris85,

The changes are permanent, but as you said are applied in the core. It is technically possible to have this feature deployed as a module, but I do not know how the plugin architecture works. I know that the "laravel" module architecture is used, but I am not familiar with Laravel. I am currently trying to figure out how to built a module, how a module "registers" to present something in the sidebars, etc.

**Comment by fvdm** [comment]
I rather have the list in the sidebar with the other meta info such as the Followers list. The toolbar is for actions/controls.

**Comment by mojiro** [comment]
I agree with you @fvdm , but I need help with Laravel :D and moduling!

I have been trying for hours to create a simple module that adds a small table in the sidebar, but I cannot figure out yet how... Any help with Laravel and Freescout moduling will be really appreciated :D

**Comment by freescout-helpdesk** [comment]
**[Extended Attachments Module](https://freescout.net/module/extended-attachments/)** has been released.
