### ISSUE TITLE
Spam-module "spam" option should not be a ticket state or ask for approval

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#1205]
Hello,

![image](https://user-images.githubusercontent.com/59649717/117889948-048f5f00-b2bd-11eb-80eb-0dc60b741fa2.png)

While not a bug or issue exactly, current spam module behavior of adding a "spam" state for tickets is bad design.
Handling a large number of daily tickets, it's only a matter of time to mark a valid ticket as "spam" instead of closing it, without noticing.

The mark as spam option should either be a separate button in the UI, somewhere where it can't be clicked accidentally, or require to accept a second "are you sure" prompt.

**Comment by freescout-helpdesk** [comment]
Spam option is not a part of Spam Filter Module, but a part of the app itself.

**Comment by sinister3vil** [comment]
Hi @freescout-helpdesk,

Apologies for the misunderstanding. Still the issue remains, having an "mark as spam" button that's easy to click in the normal workflow is a problem waiting to happen.
