### ISSUE TITLE
Install Script SQL Error

### ISSUE THREAD

**Issue by blueteq** [freescout-helpdesk/freescout#1208]
I have been trying to install FreeScout on Ubuntu 20.04 LTS using the interactive bash script. 

`source <(curl -s https://raw.githubusercontent.com/freescout-helpdesk/scripts/master/install/ubuntu.sh)`

Everything seems to be okay, and then I get this? Once the install completes, I can access the setup via IP but not FQDN, which I confirmed DNS is set up correctly. (I use SSH on Hostname for setup and had Zammad set up on the same hostname and IP)

`Configuring MySQL...
ERROR 1269 (HY000) at line 1: Can't revoke all privileges for one or more of the requested users
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY "ODEyZTgxY"' at line 1
`

**Comment by freescout-helpdesk** [comment]
Just ignore it. In the installation script there are two instructions for different MySQL versions. If one of them fails - another works.

**Comment by blueteq** [comment]
Thanks, I will give it another go and report back.

**Comment by blueteq** [comment]
Hi, okay managed to continue the install with the error. The next issue I found was that certbot was not working. 
This is why I had the connection refused; NGINX never set up redirect as the script never managed to install certbot. 

I manually created the script locally and then updated this line to Python3... and we are up and running! 

```
sudo apt-get install software-properties-common
	sudo add-apt-repository universe
	sudo add-apt-repository ppa:certbot/certbot
	sudo apt-get update
	sudo apt-get install certbot **python3**-certbot-nginx
	sudo certbot --nginx --register-unsafely-without-email

```
