### ISSUE TITLE
Is there @action for the left mailbox sidebar?

### ISSUE THREAD

**Issue by mojiro** [freescout-helpdesk/freescout#1209]
Hello,

I am trying to find ways to put content below the mailbox block. Is there any support for that?

![image](https://user-images.githubusercontent.com/7676366/118411045-a54d9800-b68a-11eb-80ec-47f97b4d53bc.png)

**Comment by freescout-helpdesk** [comment]
Not yet. You can a hook to the template.

**Comment by freescout-helpdesk** [comment]
@action('mailbox.after_sidebar_buttons')
