### ISSUE TITLE
Properly detect email reply separator

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#121]
When replying to a conversation via mail client, the "reply separator" is not detected properly and still shown in the reply, in example:

```
Bob Smith via FreeScout has wrote:
```

that line should be removed.

**Comment by freescout-helpdesk** [comment]
Yes. It would be good if anyone can find the way. Help Scout could not do this.

**Comment by guestisp** [comment]
Here there are some example for thunderbird:
http://kb.mozillazine.org/Reply_header_settings

maybe we can remove the first line above the first `>` used as reply separator, if contains the from set by freescout.

As free scout is setting "firstname lastname via freescout" as From, we can safely remove the first occurence of `Firstname Lastname via freescout.*wrote` immediatly before the first `>`

**Comment by freescout-helpdesk** [comment]
OK. Just we need to keep in mind that instead of `Firstname Lastname`  there can be a mailbox name or custom text depending on mailbox `From Name` option.

**Comment by freescout-helpdesk** [comment]
Ok as is.
