### ISSUE TITLE
How to remove a phantom starred conversation ?

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1210]
Hi,

I moved a conversation starred with a draft ongoing to another mailbox and since then, I could not removed the conversation from the initial mailbox, in the same time, once I closed the conversation in the other mailbox, the count of 1 starred conversation still appear in my initial mailbox even once the conversation is closed in the other mailbox.

How can I manualy update the DB to remove that phantom starred conversation ?

**Comment by freescout-helpdesk** [comment]
You need to find the record in `conversation_folder` table, delete it and clear FreeScout cache.

**Comment by davask** [comment]
Hi,

I did it last night :)

thanks
