### ISSUE TITLE
Looking for information on using API & Webhooks Module

### ISSUE THREAD

**Issue by shajiuddin** [freescout-helpdesk/freescout#1212]
Hi All,

For integration we need to but the module, before buying it I need confirmation that it will fulfill the below requirement.
Your help is required.

Requirement: Form (with name, phone, email and enquiry text) on website will be submitted by customer and that enquiry will push to Freescout system than default email workflow will work within Freescout system.

Through Freescout API below is possible? If yes than what will be the flow need to follow?

Any help will be highly appreciable.

Regards.

**Comment by freescout-helpdesk** [comment]
You can check everything via demo API at https://demo.freescout.net/

**Comment by shajiuddin** [comment]
Hi @freescout-helpdesk, thank you for reply, we have got the module
