### ISSUE TITLE
System down, need help.

### ISSUE THREAD

**Issue by skadefro** [freescout-helpdesk/freescout#1213]
I run freescout on kubernetes, today i upgraded my cluster, so freescout and mariadb was restarted.
After it came up, i can login, I can see the different emails but if i click on any email i get "something went wrong" 
In the console of mariadb there are no errors, but in freescout it says
```
PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib/php8/modules/gnupg.so (Error loading shared library libgpgme.so.11: No such file or directory (needed by /usr/lib/php8/modules/gnupg.so)), /usr/lib/php8/modules/gnupg.so.so (Error loading shared library /usr/lib/php8/modules/gnupg.so.so: No such file or directory)) in Unknown on line 0
Cannot load Zend OPcache - it was already loaded
```
and
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib/php8/modules/gnupg.so (Error loading shared library libgpgme.so.11: No such file or directory (needed by /usr/lib/php8/modules/gnupg.so)), /usr/lib/php8/modules/gnupg.so.so (Error loading shared library /usr/lib/php8/modules/gnupg.so.so: No such file or directory)) in Unknown on line 0
```
not sure if one of those is the reason, so I tried setting APP_DEBUG=true in hopes that would give me an error I could understand, but I just get presented with below, and it makes no sense to me
![image](https://user-images.githubusercontent.com/4155937/118605632-c57a7580-b7b6-11eb-876f-3a136da531ac.png)

**Comment by skadefro** [comment]
instead of using latest, I tried setting version tag to 1.14.4 and now it all works again.
But would be nice to be able to use latest, so if I can do anything to help you troubleshoot, let me know ( remote access, getting logs, testing different options etc )

**Comment by freescout-helpdesk** [comment]
Apparently you need to install gnupg PHP extension.

**Comment by skadefro** [comment]
oh, I just saw your not maintaining that your self, that is @tiredofit at https://github.com/tiredofit/docker-freescout ... Sorry I did not see that before.

**Comment by skadefro** [comment]
I have created the issue the prober place, sorry for the trouble and thank you for giving a hint at what the problem might be :-)
