### ISSUE TITLE
Some enhancement idea for WhatsApp: Workflow & Custom Folder

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#1214]
It'll be great if we can add WhatsApp to type for the Workflow. 

Add `WhatsApp` to the `Type` of Workflow.

<img width="789" alt="Screenshot 2021-05-18 at 9 39 29 PM" src="https://user-images.githubusercontent.com/5198092/118661436-b1b82900-b821-11eb-8519-1b96753d01f0.png">

Also currently there is no way to make all WhatsApp messages appear in a custom folder. It'll be great if there is an option for the custom folder to group `WhatsApp` messages.

**Comment by freescout-helpdesk** [comment]
No plans for now. Maybe someone can implement and send us back.
