### ISSUE TITLE
Exporting/Printing Reports

### ISSUE THREAD

**Issue by 219design** [freescout-helpdesk/freescout#1215]
Is it possible to esport or print the reports?  Would be very helpful to be able to send clients the time spent on their tickets.

Regards
James

**Comment by freescout-helpdesk** [comment]
No for now. There is an idea here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/313005

**Comment by 219design** [comment]
Ok, sure.  I've upvoted that idea and will keep an eye on it in the future.

Thx.
