### ISSUE TITLE
Conversation moved to another inbox retains assignee of original inbox

### ISSUE THREAD

**Issue by radarsymphony** [freescout-helpdesk/freescout#1216]
## Summary
When a user "transfers" or Moves an assigned conversation to a new Inbox, the assignee is still assigned to that conversation in the new Inbox, even if that assignee is not in that Inbox (i.e., the assigned status moves with the conversation). Instead, it seems like the transferred/moved conversation should reset or remove assignee info and go to "Unassigned" in the new Inbox.

## Steps to reproduce
Requires access to two Inboxes
1. Send a test email to one of the Inboxes (from an external account)
2. In that Inbox, assign it to a user
3. Open the conversation and, from the ellipsis dropdown menu along the top, select "Move"
4. Select the second Inbox from the dropdown or enter the address in the dialogue box
![image](https://user-images.githubusercontent.com/73671474/118733924-22475180-b7f2-11eb-9101-ddb357743962.png)
5. Click "Move"
6. Log into the second Inbox (if you aren't automatically transferred to the inbox)
7. Under the "Assigned" folder, search for the transferred conversation
8. Note that the assignee is retained from step 2 above
9. (optional) Change assignee and move conversation back to the first Inbox to see the behavior again

## What is the current bug behaviour?
Assignee of conversation moves with that conversation to new inbox, even if that user is not in the receiving inbox. 

## What is the expected correct behaviour?
Conversations transferred to a new Inbox should return to Unassigned status to allow the users of receiving Inbox to effectively process what essentially is a new conversation to their inbox. 

## Possible fixes
 Maybe related to issues #695 and #696 with how transfers are handled for users not in Inboxes.

**Comment by freescout-helpdesk** [comment]
If conversation assignee does not have access to the new mailbox the conversation is automatically assigned to the user who is moving the conversation. In your case conversations is probably assigned to the admin who has access to all mailboxes.

**Comment by radarsymphony** [comment]
Okay, your description of how Freescout functions matches our experience and tests. It sounds like this is a feature and not a bug.

Are you able to expand on the reasoning behind assigning a conversation to a user who doesn't have access to an inbox? I'm looking to understand the use case that is currently being served by the way it is designed. Maybe our organization can adjust workflow. Currently, it seems like moved conversations will fall out of users awareness. The "transferring" user must notify the "receiving" user that they are transferring a conversation separately so that the receiving user can go and search for the transfer. This extra step could be eliminated by returning the transfer to Unassigned, which would automatically alert the receiving user. 

We appreciate the hard work and thought that goes into Freescout! Just looking to appreciate it more. :-)

**Comment by freescout-helpdesk** [comment]
> Are you able to expand on the reasoning behind assigning a conversation to a user who doesn't have access to an inbox? 

This is how it works in existing helpdesks.

The dropdown can be added to the Move modal window with the following values:

- Keep assignee if current assignee has access to the new mailbox, otherwise assign to Me (default)
- Keep assignee if current assignee has access to the new mailbox, otherwise assign to Anyone
- Assign to Anyone
- Assign to Me

**Comment by freescout-helpdesk** [comment]
Closing as out of scope.
