### ISSUE TITLE
Postgresql.. use at your own risk?

### ISSUE THREAD

**Issue by bcookatpcsd** [freescout-helpdesk/freescout#1224]
I was just re-reading the docs.. I see postgresql is shown on a few pages, but nothing in the install docs.. 

Is there a conversion from mysql to postgresql? or just install only option? 

Thanks in advance..

**Comment by freescout-helpdesk** [comment]
Database type is selected on this step: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#81-using-web-installer
