### ISSUE TITLE
Increase Attachment Size

### ISSUE THREAD

**Issue by dealend** [freescout-helpdesk/freescout#1229]
We have been trying to increase our max file upload size from 2mb to 10mb, but even after changing the following, nothing above 2mb is accepted:

![image](https://user-images.githubusercontent.com/83796325/119171237-4e511580-ba32-11eb-86a6-6352f1158382.png)

We've made sure nginx and phpfpm has been restarted after applying the changes but doesn't seem to make any difference. Any suggestions?

**Comment by freescout-helpdesk** [comment]
Something else is must limiting it on your server. Your admin may need to find out what.
