### ISSUE TITLE
Re-opening drafts of 'Forward' conversations overwrite the To field with original sender's address

### ISSUE THREAD

**Issue by radarsymphony** [freescout-helpdesk/freescout#1230]
### Summary
When a user re-opens a draft of conversation-to-be-forwarded, the To Field is overwritten by the original sender address. 

### Steps to reproduce
1. In an Inbox, open a conversation. The conversation should have a unique/recognizable sender address (i.e., not your own)
2. Click the ellipses menu and select 'Forward'
![image](https://user-images.githubusercontent.com/73671474/119190239-f1555f80-ba31-11eb-85b5-eb2862d5e50b.png)

3. (optional) Write some text in the body and add a recipient in To Field
4. Save the drafted forward conversation
![image](https://user-images.githubusercontent.com/73671474/119190301-04682f80-ba32-11eb-809d-118f735b14f2.png)

5. Reopen draft by either opening the conversation from Drafts (left-hand menu), or clicking edit on the conversation
![image](https://user-images.githubusercontent.com/73671474/119190365-19dd5980-ba32-11eb-8a6e-5f534f7f63c0.png)

6. Note that the To field has been populated with original sender's address

### What is the current bug behavior?
The original sender's address overwrites the To field of saved Forward conversations when re-opened to edit and send. If not corrected before sending, the original sender receives the forwarded conversation instead of the intended recipient.

### What is the expected behavior?
Conversations created as a message to Forward, should retain any added recipient when re-opened to edit. It should not be overwritten by the original sender's address. 

### Possible fixes
A possible direction to investigate: Forwarding seems to partially function like "Replying" which uses the original sender's address in the To field. Perhaps some code originally used for replying was repurposed to accommodate forwarding (within the context of re-opening a draft).

**Comment by radarsymphony** [comment]
Hi @freescout-helpdesk, 

I am able to replicate this issue on v1.7.17. Do you need any part of this issue clarified to replicate on your end?

**Comment by freescout-helpdesk** [comment]
Works fine in FreeScout v1.8.60
