### ISSUE TITLE
Custom Deparment in End User Portal

### ISSUE THREAD

**Issue by episquare** [freescout-helpdesk/freescout#1232]
I knew you guys under heavy workload, but it is possible to implement this? So customer can choose department, like support, sales, etc.

**Comment by scout-devs** [comment]
These departments are like different mailboxes or custom labels?

**Comment by episquare** [comment]
I mean like, user can pre select department like sales support, general support, or billing support? 

Yes if we are seperate this general, billing or sales mailboxs it can become like custom department too.

Or maybe custome category before submiting a ticket, like whcms support system maybe

**Comment by scout-devs** [comment]
Yeah, custom labels are the best way to do it. We are already working on a fix for this, I will update this thread. Do you want it in EUP portal or widget or both?

**Comment by episquare** [comment]
To be honest i bought two of them, so it will be awesome if you guys implement it both, i cant wait if this feature is release.

Please accept my apology for my short English.

Any ETA when this feature will release? It's gonna be custome module?

**Comment by scout-devs** [comment]
Yes, we are independent dev studio working on Freescout modules. Its gonna be a custom module, yes.

**Comment by episquare** [comment]
Awesome... i cannot wait you guys for release this feature ASAP, thank you so much guys for your hardwork

**Comment by BenPicard** [comment]
I would also need this module! I would need to client to be able to select the "reason" for the ticket. Is it a feature request, a bug, a question, etc. 

Would the tags system already in place something that we could use in the EUP portal to let the user tag his own ticket?

**Comment by episquare** [comment]
Is there any update about this requested feature?

**Comment by scout-devs** [comment]
We are working on it and it will soon be released

**Comment by episquare** [comment]
Can't wait anymore, really need this feature, so conversation will not mess because current end user portal itself doesn't have subject, just message only, please release it soon guys 🤟🤟🤟

**Comment by scout-devs** [comment]
We have implemented the "custom fields" feature in EUP portal. It can be seen here - https://help.expresstech.io/help/700382701 (also notice the change in colors).

To enable this functionality you need to buy our "PowerPack" module, its developed by ScoutDevs - a third party freescout developer. More details here https://scoutdevs.com/downloads/power-pack/

<img width="671" alt="Screenshot 2021-06-12 at 2 26 02 PM" src="https://user-images.githubusercontent.com/84848350/121770965-2022a980-cb8a-11eb-983f-2396030df233.png">

**Comment by freescout-helpdesk** [comment]
Custom Fields added in the End-User Portal Module v1.0.20: https://freescout.net/module/end-user-portal/

**Comment by hanetworks** [comment]
Yes custom fields work well. 

But, how to send the ticket to the correct mailbox. (Say I have multiple mailboxes for multiple departments, when I select support custom field, it doesn't mean it will be automatically sent to support mailbox, right?)

**Comment by vikasprogrammer** [comment]
Did you try creating a Workflow rule based on the custom field value? May be move to another support mailbox based on the value of custom field?

**Comment by hanetworks** [comment]
Yep, that would work. 

Thanks for the great suggestion!
