### ISSUE TITLE
Reinstall FreeScout?

### ISSUE THREAD

**Issue by mymousepad** [freescout-helpdesk/freescout#1235]
Recently had a server upgrade and now **FreeScout** not functioning properly. Server support tried to fix, but after FS update now the menu bar no longer works... is there a way to do a fresh install and KEEP all tickets and settings??

**Comment by vikasprogrammer** [comment]
Check your console error?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
