### ISSUE TITLE
Include email-address of original sender when forwarding conversation

### ISSUE THREAD

**Issue by im-fabian** [freescout-helpdesk/freescout#1236]
### Summary
When you forward a conversation only the names of participants in that conversation are included but not their email-addresses.

### Steps to reproduce
1. Open a conversation.
2. Forward conversation to an external e-mail-address.

### What is the current bug behavior?
The person to which the ticket is forwarded can only see the name of the original sender of the mail but not the email-address. On the other hand the addresses of all CCs are shown.

### What is the expected behavior?
If you forward an email to an external address both the name and the email-address of the original sender should be included.

### Possible fixes
Include the email-address of the original sender next to his or her name.

Like: `Jane Doe <jane@doe.me>`

**Comment by Patistar** [comment]
Same on our end. Would be quite important for us to have the email address of the original sender included in a forwarded conversation.

**Comment by freescout-helpdesk** [comment]
> The person to which the ticket is forwarded can only see the name of the original sender of the mail but not the email-address.

See where? Could you please attach a screenshot?
