### ISSUE TITLE
REQUEST: Add name of last person to reply in mailbox preview

### ISSUE THREAD

**Issue by pocketfulofrage** [freescout-helpdesk/freescout#1237]
It would be awesome to be able to see the name of the last person who replied to a conversation in the message preview when looking at the mailbox.  Sometimes, our techs will reply with a note and the preview makes it appear the original requester sent the message.  This can be .. erm, confusing at times.

![87dmqIc - Imgur](https://user-images.githubusercontent.com/3870824/119367555-10e1c780-bc80-11eb-84e0-acff557d5557.png)

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans for now. Maybe someone can implement as a custom module.
