### ISSUE TITLE
Attachments not accessible after update 

### ISSUE THREAD

**Issue by peisbacher** [freescout-helpdesk/freescout#1238]
Hi.

After an update to 1.7.7 we are not able to open any attachment. The attachments are there in the filesystem, all permission checks work but still we cannot open them via the webinterface. New attachments work fine.

Is there any help or trick you can provide?

**Comment by freescout-helpdesk** [comment]
Make sure you have `location ~* ^/storage/attachment/` in your nginx:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server
