### ISSUE TITLE
Follow up on ticket #1203

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#1239]
Sorry to create another ticket, can you create a similar Eventy filter for Knowledge Base's `widget_form.blade.php` like you did for EUP (https://github.com/freescout-helpdesk/freescout/issues/1203)? 

Something like this:
```
{!! Minify::javascript(\Eventy::filter('kb.javascripts', ['/js/jquery.js', '/js/bootstrap.js', '/js/lang.js', '/storage/js/vars.js', '/js/laroute.js', \Module::getPublicPath(KB_MODULE).'/js/widget_form.js', '/js/main.js'])) !!}
```

**Comment by freescout-helpdesk** [comment]
Implemented.
