### ISSUE TITLE
How to disable polycast

### ISSUE THREAD

**Issue by vishalv26** [freescout-helpdesk/freescout#1240]
Hi,

Is there a way we can disable polycast?

I tried setting `null` in `broadcasting.php` still it is hitting the xhr requests

**Comment by freescout-helpdesk** [comment]
You may need to find out by yourself.

**Comment by vishalv26** [comment]
Ok. Is there any provision already made? I was not able to find this in documentation. Am i missing something which is already there? Just wanted to confirm

**Comment by freescout-helpdesk** [comment]
> Is there any provision already made? I was not able to find this in documentation

Nope.

**Comment by vishalv26** [comment]
Thanks

**Comment by vishalv26** [comment]
And also thank you for making this beautiful project
