### ISSUE TITLE
Office hours: Not yet activated

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#1241]
I see office hours setting are available at global level and already set:
<img width="839" alt="Screenshot 2021-05-29 at 9 42 34 AM" src="https://user-images.githubusercontent.com/5198092/120054376-3432bb00-c062-11eb-91d2-6eb097be3044.png">

However, at the mailbox autoreply, it still shows `Not yet activated`
<img width="872" alt="Screenshot 2021-05-29 at 9 43 28 AM" src="https://user-images.githubusercontent.com/5198092/120054402-5593a700-c062-11eb-9858-95a93d22e112.png">

Am I missing anything?

**Comment by freescout-helpdesk** [comment]
This notice will be removed in the next release.
