### ISSUE TITLE
Add "Subject" field in End user Portal. 

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#1242]
Currently the end user portal has no subject line field;
<img width="631" alt="Screenshot 2021-05-31 at 8 54 59 AM" src="https://user-images.githubusercontent.com/5198092/120126445-de3f4e00-c1ee-11eb-8736-2a6661c3954c.png">

This causes a mess in all open tickets. Also, it makes it hard to search for conversations later. 
<img width="983" alt="Screenshot 2021-05-31 at 8 55 33 AM" src="https://user-images.githubusercontent.com/5198092/120126457-e7301f80-c1ee-11eb-8364-b9b27bbe4b9a.png">

Adding a Subject field will solve this issue.

**Comment by BenPicard** [comment]
+1

I also think that a dropdown with a category for the ticket would be important to add. Is it a bug, a feature request, a question, etc.

**Comment by freescout-helpdesk** [comment]
Maybe in the future custom fields will be made available in the End User Portal form.

**Comment by freescout-helpdesk** [comment]
Meanwhile feel free to add a feature request: https://freescout.net/request-feature/
