### ISSUE TITLE
Shortcuts - Add shortcut Send - Add option to choose the keys

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1243]
Hi Guys,

I have used for years Mailhub on apple mail.
And i loved the keyboard shortcuts to send.

Is it an idea to add that to Shortcuts?
And i can imagine that you do the default action for sending or maybe you can set this up in Shortcuts.

Also i can imagine settings where people can choose the shortcut.
So this will not interfere with any workflow and shortcuts they have.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to add.
