### ISSUE TITLE
Live Chat bubble color issue

### ISSUE THREAD

**Issue by foliovision** [freescout-helpdesk/freescout#1246]
We use the Live Chat 1.0.2 and even though we state the custom color in the script:

```
<script>
var FreeScoutW={s:{"color":"#bd0025","position":"br","id":3624579532}};
(function(d,e,s){
  if(d.getElementById("freescout-w"))return;
  a=d.createElement(e);
  m=d.getElementsByTagName(e)[0];
  a.async=1;
  a.id="freescout-w";
  a.src=s;
  m.parentNode.insertBefore(a, m)
})
(document,"script","https://desk.foliovision.com/modules/chat/js/widget.js?v=3707");
</script>
```

However the color is not respected in the actual chat window:

![Screenshot 2021-06-03 at 13 56 59](https://user-images.githubusercontent.com/1180948/120641195-9c730980-c473-11eb-8244-483004a49213.png)

Could you please fix this?

**Comment by foliovision** [comment]
These are showstopper bugs for us as blue will not work with our colour scheme at all so we are unable to use Live Chat at all, despite great enthusiasm to put it immediately into production. Fixing the bug shouldn't be difficult as the selected colour is already stored as a variable. The other uses of colour just need to use that existing variable.

The simple design is excellent btw. Very neutral and even elegant.

**Comment by freescout-helpdesk** [comment]
Message bubbles' color is always blue, it can't be changed. Unfortunately no plans to make it adjustable.
