### ISSUE TITLE
Unable to install freescout modules after purchasing them

### ISSUE THREAD

**Issue by raymondvaughanwilliams** [freescout-helpdesk/freescout#1250]
We purchased some freescout modules but we have been unable to install them.

When we try installing the modules we get these error messages: "Error occurred please check internet connection and try again"  and "lost internet connection".

Please advise.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-error-occurred-downloadingactivating-the-module
