### ISSUE TITLE
Truncate Send error logs

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#1253]
### Problem

Currently the error logs in `Send Error` sometimes too long. 
I'm using GSuite and sometimes freescout failed to login and printing long error message in Manage > Logs > Send Error.
When multiple similar errors captured, there is no way to clear these logs. Since these error messages are too long, PHP will fail or exhaust memory to clear these.

### Potential Solution
1. Do not print the full error log in Send Errors. Truncate after 5 lines? 

2. Clear function clear logs in incremental?

### Example
`Error sending email to user	Failed to authenticate on SMTP server with username "sample@sample.com" using 3 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 250 but got an empty response in /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:445 Stack trace: #0 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array) #1 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array, false, NULL) #2 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/LoginAuthenticator.php(40): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array) #3 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(177): Swift_Transport_Esmtp_Auth_LoginAuthenticator->authenticate(Object(Swift_SmtpTransport), 'sample@sample.com', 'ppzpyrqunhnrsow...') #4 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #5 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand() #6 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start() #7 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array) #8 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message)) #9 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\Mail\Mailer->send('emails/user/not...', Array, Object(Closure)) #10 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer)) #11 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\Mail\Mailer->sendMailable(Object(App\Mail\UserNotification)) #12 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\Mail\Mailer->send(Object(App\Mail\UserNotification)) #13 /srv/users/freescout-path/apps/freescout-path/app/Jobs/SendNotificationToUsers.php(123): Illuminate\Mail\PendingMail->send(Object(App\Mail\UserNotification)) #14 [internal function]: App\Jobs\SendNotificationToUsers->handle() #15 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #16 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #17 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #18 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #19 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array) #20 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendNotificationToUsers)) #21 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendNotificationToUsers)) #22 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #23 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendNotificationToUsers), false) #24 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #25 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire() #26 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions)) #27 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions)) #28 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'emails,default,...', Object(Illuminate\Queue\WorkerOptions)) #29 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'emails,default,...') #30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle() #31 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #32 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #33 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #34 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #35 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array) #36 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #37 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #38 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #39 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #40 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #42 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #43 /srv/users/freescout-path/apps/freescout-path/artisan(43): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #44 {main}. Authenticator PLAIN returned Swift_TransportException: Expected response code 250 but got an empty response in /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:445 Stack trace: #0 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array) #1 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array, false, NULL) #2 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/PlainAuthenticator.php(39): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array) #3 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(177): Swift_Transport_Esmtp_Auth_PlainAuthenticator->authenticate(Object(Swift_SmtpTransport), 'sample@sample.com', 'ppzpyrqunhnrsow...') #4 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #5 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand() #6 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start() #7 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array) #8 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message)) #9 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\Mail\Mailer->send('emails/user/not...', Array, Object(Closure)) #10 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer)) #11 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\Mail\Mailer->sendMailable(Object(App\Mail\UserNotification)) #12 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\Mail\Mailer->send(Object(App\Mail\UserNotification)) #13 /srv/users/freescout-path/apps/freescout-path/app/Jobs/SendNotificationToUsers.php(123): Illuminate\Mail\PendingMail->send(Object(App\Mail\UserNotification)) #14 [internal function]: App\Jobs\SendNotificationToUsers->handle() #15 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #16 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #17 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #18 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #19 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array) #20 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendNotificationToUsers)) #21 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendNotificationToUsers)) #22 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #23 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendNotificationToUsers), false) #24 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #25 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire() #26 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions)) #27 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions)) #28 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'emails,default,...', Object(Illuminate\Queue\WorkerOptions)) #29 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'emails,default,...') #30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle() #31 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #32 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #33 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #34 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #35 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array) #36 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #37 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #38 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #39 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #40 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #42 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #43 /srv/users/freescout-path/apps/freescout-path/artisan(43): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #44 {main}. Authenticator XOAUTH2 returned Swift_TransportException: Expected response code 250 but got an empty response in /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:445 Stack trace: #0 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array) #1 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array, false, NULL) #2 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/XOAuth2Authenticator.php(49): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array) #3 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(177): Swift_Transport_Esmtp_Auth_XOAuth2Authenticator->authenticate(Object(Swift_SmtpTransport), 'sample@sample.com', 'ppzpyrqunhnrsow...') #4 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #5 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand() #6 /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start() #7 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array) #8 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message)) #9 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\Mail\Mailer->send('emails/user/not...', Array, Object(Closure)) #10 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer)) #11 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\Mail\Mailer->sendMailable(Object(App\Mail\UserNotification)) #12 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\Mail\Mailer->send(Object(App\Mail\UserNotification)) #13 /srv/users/freescout-path/apps/freescout-path/app/Jobs/SendNotificationToUsers.php(123): Illuminate\Mail\PendingMail->send(Object(App\Mail\UserNotification)) #14 [internal function]: App\Jobs\SendNotificationToUsers->handle() #15 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #16 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #17 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #18 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #19 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array) #20 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendNotificationToUsers)) #21 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendNotificationToUsers)) #22 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #23 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendNotificationToUsers), false) #24 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #25 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire() #26 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions)) #27 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions)) #28 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'emails,default,...', Object(Illuminate\Queue\WorkerOptions)) #29 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'emails,default,...') #30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle() #31 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #32 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #33 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #34 /srv/users/freescout-path/apps/freescout-path/overrides/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #35 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array) #36 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #37 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #38 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #39 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #40 /srv/users/freescout-path/apps/freescout-path/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #42 /srv/users/freescout-path/apps/freescout-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #43 /srv/users/freescout-path/apps/freescout-path/artisan(43): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #44 {main}.; File: /srv/users/freescout-path/apps/freescout-path/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php (191)`

**Comment by freescout-helpdesk** [comment]
We'll leave this as is.
