### ISSUE TITLE
Notification (Slack, Telegram) content limitation

### ISSUE THREAD

**Issue by DerDanilo** [freescout-helpdesk/freescout#1255]
Pushing notifications with full body to Telegram or Slack is an issue in relation to GDPR.

The modules settings should allow to select how much the body of a new conversation should be send:

- Nothing, only Subject
- Subject and 10 Lines of the body
- Subject and Full Body

Maybe someone can push code to get these options into the modules.

Thanks!

**Comment by freescout-helpdesk** [comment]
Here is how to modify modules: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by DerDanilo** [comment]
Just posting links and closing issue is not feedback friendly. I don't want to, nor can I modify the module myself. I am not a programmer. It's simply not usable like it is now. To much information pushed via chat messages. It should be selectable what the messages should contain. 

Multiple project that I know want to use this module but cannot dues to the fact that it send to much information.
Please patch this much needed GDPR relevant change and push it upstream so all users can profit from it. 
After all users paid for the module, even if it's just a one time fee. 

Please don't make simple things overly complex.

Thanks!
