### ISSUE TITLE
Support showing conversation/ticket number in Subject

### ISSUE THREAD

**Issue by DerDanilo** [freescout-helpdesk/freescout#1256]
It would be great if there was an option to show the conversation/ticket number in the subject of mails to the customer.
It works mostly great without the number being visible in the subject but also confuses some customer/support agents.

Most other ticket systems put the ticket number in the subject, whereas FS doesn't seem to have an option to do that.
At least I couldn't find a way using any module or setting at the time of writing this issue.

So having an option that automatically adds the ticket number to the subject line beginning would be great.

Thanks!

**Comment by freescout-helpdesk** [comment]
Implemented as a module: https://freescout.net/module/ticket-number/
