### ISSUE TITLE
Feature request: Warning when sending to no-reply@trovimap.com, no-responder@domain.com, addresses etc

### ISSUE THREAD

**Issue by colegatron** [freescout-helpdesk/freescout#1258]
We have some notifications sent to users sent no-reply@domain.com. 
Those notifications are also sent to our support dept in order to keep track of them and eventually add extra info to the end user.

Very often helpdesk people reply without replacing manually the no-responder@domain.com with the email of the user (usually specified in the notification text), getting in turn a message back from our smtp server "this address is meant to not receive emails, please send it again to the proper destination", messing up the ticket. 
Because that, if the helpdesk guy tries to resend it again to the proper user email the body text shows up the error message too.

Would be great to be able to get a warning before sending the reply :
"Sending to no-responder@domain.com email. Are you sure?"

Feature would require a way to specify one or more "no reply to" email addresses.

**Comment by freescout-helpdesk** [comment]
Can be implemented as a module.

**Comment by freescout-helpdesk** [comment]
Better to have it in the core and also block auto replies to no-reply@ emails. List of no-reply emails can be stored in the config and adjusted via .env file.

**Comment by freescout-helpdesk** [comment]
Implemented as a module: https://freescout.net/module/noreply/
