### ISSUE TITLE
Live Chat notifications

### ISSUE THREAD

**Issue by ThomasEKolb** [freescout-helpdesk/freescout#1260]
Currently, for each Chat message, a mail notification is sent. Unfortunately, this results in a lot of "spam" because each freescout instance agent gets a mail for every single message exchanged during the chat session.

It would be nice to have a dedicated setting in the notifications area to disable getting notification from chat conversions or, better, somehow only getting a mail with a summary of the finished conversation (or a mail only all, e.g. 10 minutes).

In a perfect world, one could combine this with a per mailbox setting like proposed in this ticket: https://github.com/freescout-helpdesk/freescout/issues/1257.

We really love the Freescout system and also the different modules. Thank you for the continuous implementation of new features and modules!

**Comment by a7medo778** [comment]
bump
i would love to see two types of ticket threads on freescout, the regular and chat

even on the apps having a "chat" layout for chat channels (telegram, whatsapp...etc) is much much more efficient and helpfull

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
