### ISSUE TITLE
Error display when login

### ISSUE THREAD

**Issue by nissisb** [freescout-helpdesk/freescout#1261]
Hello i have this blue screen with "Whoops, looks like something went wrong."
Do you know where is it come from ?

**Comment by nissisb** [comment]
![image](https://user-images.githubusercontent.com/78433492/121769109-11280100-cb62-11eb-8202-21ebf9d9b927.png)

**Comment by sam-suresh** [comment]
If its a cache related, run `sudo php artisan freescout:clear-cache` will help.

Otherwise check your server error logs or enable Debug in freescout env

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by nissisb** [comment]
It's a it seems that the problem is that : 
Expected response code 250 but got code "552", with message "552-5.2.3 Your message exceeded Google's message size limits. Please visit 552-5.2.3 https://support.google.com/mail/?p=MaxSizeError to view our size 552 5.2.3 guidelines. w11sm1436404edc.5 - gsmtp "; File: /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php (457)

And i don't know how to manage that....
