### ISSUE TITLE
office hours module doesn't do anything

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#1266]
When I activated Office Hours, it gave me a "please check your internet connection" error, but despite that, it seemed to activate anyway.  I configured the hours under Settings -> Office Hours and then tried sending an email outside of those hours.   If I have auto reply disabled for the mailbox, it does not send an out-of-hours auto-reply.  If I enable auto-reply, it just sends the standard auto-reply that it would without the Office Hours module.

I don't understand how this module is supposed to work.  Does the "not yet activated" message beside office hours in the auto-reply settings indicate something that there's something I need to change?

**Comment by freescout-helpdesk** [comment]
Office Hours module just allows to block Auto Reply during working hours.
