### ISSUE TITLE
Feature request: Workflow module: Allow filtering the whole mail and header

### ISSUE THREAD

**Issue by DerDanilo** [freescout-helpdesk/freescout#1268]
### Story

The mail spam filter is working fine but not perfect. The Spam module from FS also does it's just but isn't perfect either.
We need to be able to work with a workflow list that searches the whole mail content and not just the "body", "subject" or "sender address" for keywords. To our experience the "body" only refers to the actual mail body. 

### Request

- [ ] Please add a workflow condition to search the whole conversation/mail for a keyword
e.g. "entire conversation/mail"
- [ ] Please also add the condition to search the "mail header"

Thanks!

**Comment by freescout-helpdesk** [comment]
Feel free to add https://freescout.net/request-feature/
