### ISSUE TITLE
Feature request: Office Hours Alt Auto-Reply

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#1271]
Would be nice to have auto-reply always send regardless of office hours, but have an alternate auto-reply outside of office hours to indicate that support is not available until the following day.

![officehoursreq](https://user-images.githubusercontent.com/11652559/122413854-b3762900-cf54-11eb-9b15-dce127d4c7be.png)

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement for now. Feel free to add here: https://freescout.net/request-feature/
