### ISSUE TITLE
Feature request: Column charts in Reports module

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#1272]
It would be nice to have the option to draw column charts in the Reports module, as opposed to line or area charts. 

Additionally, this would make it possible to show a graph for a single day.  Perhaps in order to always show a graph regardless of graph type preference, it could automatically show a column chart when date range is set to a single day.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement. Maybe someone can do it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
