### ISSUE TITLE
Saved Replies Settings: Server Timeout

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1273]
Hi there, I imported ~400 saved replies directly into the database. However I cannot load the settings page to edit saved replies, cause the server times out after 30sec.

I tested incrementally, and it shows that the number of saved replies does impact the loading time.

However, within a support ticket, all saved replies as listed just fine. 

Can you help, why the settings page is so slow?

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
Fixed in Saved Replies 1.0.7

**Comment by obstschale** [comment]
Thank you very much.
