### ISSUE TITLE
tls: unknown certificate authority

### ISSUE THREAD

**Issue by ipflowss** [freescout-helpdesk/freescout#1274]
Hi there,

I am trying to get freescout integrated with the protonmail bridge.  
I am getting the following errors.  is the cert you are send to protonmail
a legitimately signed cert from a trusted CA?

:::error appearing on the freescout webUI:::
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL
Error messages: error:1416F086:SSL
routines:tls_process_server_certificate:certificate verify failed

:::from the docker log output:::
smtp/server 2021/06/20 12:44:58 TLS handshake error for 127.0.0.1:35502:
remote error: tls: unknown certificate authority

protonmail github links

https://github.com/ProtonMail/proton-bridge
https://github.com/sdelafond/docker-protonmail-bridge

Cheers

**Comment by ipflowss** [comment]
--- snip ---
The bridge is using a self-signed cert, hence the README section describing how to extract the fingerprint so you can manuallly trust it in whatever client you choose. If your client doesn't offer that ability, then you're out of luck.
--- snip ---

from https://github.com/sdelafond/docker-protonmail-bridge/issues/6#event-4914768769

is there anyway to freescout to manuallly trust the self-signed cert from protomail?

**Comment by freescout-helpdesk** [comment]
Have you tried to disable "Validate Certificate" in Fetching Emails in FreeScout?

**Comment by ipflowss** [comment]
Yes and still no change

And what about for outgoing emails?  That is where i am getting the error

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. Have you managed to solve it?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2714
