### ISSUE TITLE
Reply mail is not fully displayed

### ISSUE THREAD

**Issue by bronger** [freescout-helpdesk/freescout#1275]
If the customer uses interleaved quoting style (https://en.wikipedia.org/wiki/Posting_style#Interleaved_style) the email is not fully displayed. This is what I see in FreeScout, it is about the mail from “Randy Bronger”:

![image](https://user-images.githubusercontent.com/2184938/122766857-47702980-d2a2-11eb-9a6e-18c241452977.png)

However, the full mail is:

![image](https://user-images.githubusercontent.com/2184938/122769006-76879a80-d2a4-11eb-8d8f-65c986309063.png)

Thus, the text “Ich habe aber noch eine Rückfrage …” is invisible in the normal view.

**Comment by bronger** [comment]
We have running FreeScout 1.7.10 and PHP 8.0.6, using https://hub.docker.com/r/tiredofit/freescout.

**Comment by freescout-helpdesk** [comment]
Could you please post source HTML of the email.

**Comment by bronger** [comment]
It is here: https://wilson.bronger.org/freescout_mail

**Comment by freescout-helpdesk** [comment]
The only way to avoid this is to enable "Email Header" in mailbox settings.

**Comment by bronger** [comment]
I tested it with “Email Header” activated but it does not change the display of mails with interleaved quotation for me.  Or is your comment meant in the sense that all email authors must stick to the request to “answer above this line”?

**Comment by freescout-helpdesk** [comment]
> Or is your comment meant in the sense that all email authors must stick to the request to “answer above this line”?

Yes

**Comment by bronger** [comment]
It is difficult to enforce that among customers. I simply cannot guarantee which quoting style they use. Plus, they are unaware that ignoring the “Please …” is fatal.

**Comment by freescout-helpdesk** [comment]
We don't know other ways to solve it. If someone can come up with some solution - please suggest.

**Comment by megaerki** [comment]
Could there be a button on the left side or header of the email saying “show full email”? 

That would show the raw response in a new modal window?


It’s really frustrating having to ask customers to resend with their answers above the quotation line.

**Comment by JostLHansen** [comment]
I will also just say I need a solution for this and have made a module request for it here https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/452716
