### ISSUE TITLE
Webhook event convo.assinged not triggering after configuring a workflow rule

### ISSUE THREAD

**Issue by shajiuddin** [freescout-helpdesk/freescout#1276]
Hi Support,
 
We have configured a workflow that, all new unassigned requests (through emails/api) will be assign to a specified user.
After applying this workflow rule a webhook event 'convo.assinged' stopped working.
we are not sure any other workflow event is not functioning.

**Comment by freescout-helpdesk** [comment]
Any messages in Manage > Logs > App Logs?

**Comment by shajiuddin** [comment]
its working after inactive and active rule, we will let you know in future in case
