### ISSUE TITLE
Developers for hire

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1277]
If you're available for consulting, please list your profile in the project-recommended place

<img width="2223" alt="Screen Shot 2021-06-22 at 10 17 27" src="https://user-images.githubusercontent.com/382183/122941087-0e3bc600-d343-11eb-90b4-32835b223903.png">

<img width="2223" alt="Screen Shot 2021-06-22 at 10 15 32" src="https://user-images.githubusercontent.com/382183/122941045-02e89a80-d343-11eb-8e43-c34ccf4d9344.png">

**Comment by fulldecent** [comment]
ping @scout-devs

**Comment by scout-devs** [comment]
Thanks, you can reachout us at support@scoutdevs.com
