### ISSUE TITLE
CRM data via API

### ISSUE THREAD

**Issue by VideoScape** [freescout-helpdesk/freescout#1281]
Hey there, it would be great if CRM's custom data and fields could be updated and viewed via the API so it can really help expand the customer data via automation

Thanks!

**Comment by freescout-helpdesk** [comment]
Maybe will be implemented with time. Meanwhile feel free to add to https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
Implemented in API & Webhook Module v1.0.27. Get Customer method now returns Customer Fields.
Update Customer Fields method allows to update customer fields.
