### ISSUE TITLE
Extended Attachments Module : Delete attachment from the side of the ticket

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1288]
In some case, my clients have images in the email signature which are saved each time they answer to me.

As an example, if I have 100 answers with 3 images in the footer, I got 297 images duplicated.

It would be great if we can delete it manuely from the side of a ticket when using the module to avoid this extra attachments

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement for now. Maybe someone can do it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
