### ISSUE TITLE
To not load images from previous answers

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1289]
When communicating on a ticket I some times have a couple of screenshots that can be huged.
As I want user to be able to see the history of our conversation, those images are loaded when opening the email in the email software as outlook.

It would be great if we could block the load of those images when they are part of the history and/or if we could implement a resize/thumbnail system for history images

**Comment by freescout-helpdesk** [comment]
Maybe someone can create a custom module for this.
