### ISSUE TITLE
Show who saw a response

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1290]
In the thread system when we send an email/response to a user we have "Customer viewed 6 days ago @ 10:06"

I would like to see if my colleagues have seen specific response after assigning them the ticket.

Would it be possible to show whoever saw the response?

**Comment by freescout-helpdesk** [comment]
The feature is not needed in the core. Feel free to add to https://freescout.net/request-feature/
Can be implemented as a module.
