### ISSUE TITLE
POST lineitems in threads

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1291]
I am currently working on an migration process from HelpScout to FreeScout. The FreeScout API does provides POST endpoints for conversations and threads. 

My plan was to fetch all conversations, threads via HelpScout API and POST them to FreeScout.

But the API Docs do not talk about `lineitems`.

Is there a recommended way to transfer lineitems to freescout?

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to add lineitems to the API for now.
