### ISSUE TITLE
workflow triggered once per thread - it's a bug or feature? 

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#1293]
I have a workflow that setting the tag **read** once customer have read the mail
the problem is that it works once for one tread
i.e. it is triggered when first reply to customer is read by him

my goal is to have the flag **read** on the tread in case the customer have opened the last reply for him

**Comment by freescout-helpdesk** [comment]
Workflows are triggered once per conversation.

**Comment by fulldecent** [comment]
Workflows is not designed for this. Recommending to close issue.

@sau7777 you may be able to use API/Webhook module to achieve what you want
