### ISSUE TITLE
Telegram Integration Module - customer identification needed

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#1294]
Telegram Integration Module is unusable until we could authorise the customer
So the implementation of  phone number sharing request on chat start is required

**Comment by freescout-helpdesk** [comment]
Could you please send screenshots.

**Comment by sau7777** [comment]
I mean that after customer found the bot and send /start
the **Telegram Integration Module** must send the _request_contact=True_ then get the customer phone, search customers database and bind the ticket to the corresponding customer

**Comment by sau7777** [comment]
just for the beginning we need the way to bind the customer telegram chat to existing customer
otherwise we have duplicated customers (one for mail/phone and another for telegram)
afraiding to install WhatsApp integration :)

**Comment by freescout-helpdesk** [comment]
We don't try to match Telegram users and existing FreeScout customers by phone number as it is not reliable in FreeScout - phone numbers may be filled in any format and several customers may have same phone number. Corresponding notice added to the module.

**Comment by sau7777** [comment]
Telegram users identified by Telegram ID or by chat ID?
Is there any chance to add this ID to customer contacts to identify them?

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
In Telegram Integration Module v1.7.12 saving Telegram user's username to the customer profile has been implemented.
