### ISSUE TITLE
Sent email content-type issue with accents

### ISSUE THREAD

**Issue by jdfranel** [freescout-helpdesk/freescout#1296]
Hi,

New Freescout user here. Love it so far but I recently encountered a problem with stored sent emails containing accents.

* The recipient receive the message correctly (tested with mailer Zimbra 8.8.15 and Thunderbird 78.11.0) with the content-type 

```
Content-Type: multipart/alternative;
 boundary="_=_swift_1624868467_88bf376d7336634611b59e01ae82072c_=_"
X-FreeScout-Mail-Type: customer.message
...
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

> Vielen Dank für ... bestätigen ... könnte 

* When I open the sent email (tested on the specific webmail implementation by my mail hosting provider and also on Thunderbird 78.11.0), The stored message has the content type `TEXT/html; CHARSET=US-ASCII` and the accents are either missing or completly misinterpreted.

> Vielen Dank fÃ¼r  ...  bestÃ¤tigen ...  kÃ¶nnte

Looks like the charset of the stored email shold be utf-8 also.

Thanks for this great sotfware. Hope this can be fixed

**Comment by jhrdt** [comment]
Hi,
same problem here.

We would need to add

```
$part1["charset"] = "UTF-8";
```

after 

https://github.com/freescout-helpdesk/freescout/blob/87dfcb8ed03eac7009bd7ccda8c05eca74e18e1d/app/Jobs/SendReplyToCustomer.php#L293

(For a static fix).

I also see that the "Date" parameter is missing in the header (in my case).

**Idea**

I am not into PHP, but could it be possible to use imap_fetchheader (see https://www.php.net/manual/en/function.imap-fetchheader.php) and the message_id 

https://github.com/freescout-helpdesk/freescout/blob/87dfcb8ed03eac7009bd7ccda8c05eca74e18e1d/app/Jobs/SendReplyToCustomer.php#L177

to read those information (charset, date) from the sent mail and add those information to `$part1`?

**Comment by freescout-helpdesk** [comment]
Fixed in https://github.com/freescout-helpdesk/freescout/issues/1892#issuecomment-1253724814
