### ISSUE TITLE
Merging customer

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1298]
We have in some case user that use 2 or 3 different emails but we'd like to merge those customer into one to be able to have a centralized access to all their ticket which ever email they use

**Comment by rthrash** [comment]
This is a great feature, indeed. We use it all the time in Zendesk.

**Comment by freescout-helpdesk** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/346184

**Comment by freescout-helpdesk** [comment]
In the future may be added to the CRM module.

**Comment by freescout-helpdesk** [comment]
Currently it's possible to merge customers by opening a customer profile, adding additional email addresses and customers will be merged automatically.

**Comment by davask** [comment]
Awesome, I just merged 2 users in one.
Now I have some confusion on the following:
- merging 2 users in one, give me 3 users in the user page: 2 which redirect to the same ID, 1 which is the id of the merged one but with empty data (almost)

Could we have only 1 user which contains all the conversation and not 2 and can we delete the merged one?
As well can we have a delete option on profile with the ability to attach the items (conversations,...) to another user?
