### ISSUE TITLE
Bulk message deletion

### ISSUE THREAD

**Issue by colegatron** [freescout-helpdesk/freescout#1300]
Is there any way to delete coversations in bulk?

Need to delete almost 50K conversations and can't find a way to do it without looping through the pagination, then select all in the page then delete and again.

Whenever you click the select all (box in 1st picture) would be great to display another checkbox with 'Select all 50547 messages', similar as django admin does by default (example in 2nd picture)

![image](https://user-images.githubusercontent.com/2078435/123989113-dd096880-d9c8-11eb-9897-68a75985c6af.png)

![image](https://user-images.githubusercontent.com/2078435/123989727-746ebb80-d9c9-11eb-8a93-8b80571ae43b.png)

**Comment by freescout-helpdesk** [comment]
This need to be added to the Custom Folders Module. For now feel free to add a feature request here: https://freescout.net/request-feature/
