### ISSUE TITLE
API Webhooks module via Zapier error > conversation could not be sent to FreeScout. The app returned "Error occurred".

### ISSUE THREAD

**Issue by xdividr** [freescout-helpdesk/freescout#1302]
Realizing this is not a place for personal support. Bringing it up here in case this is an open issue. That said, any hints appreciated. Thanks!

Running FS 1.7.11 using [API Webhooks module](https://freescout.net/module/api-webhooks/) v1.0.22 via [Zapier](https://github.com/freescout-helpdesk/freescout/wiki/Zapier-Integration), seeing the following error when creating a new conversation in Freescout.

> The conversation could not be sent to FreeScout.
> The app returned "Error occurred". 

Same result when sending to [https://demo.freescout.net/](https://demo.freescout.net) using the provided [api key](https://demo.freescout.net/app-settings/apiwebhooks).

![zapier-error](https://user-images.githubusercontent.com/1054659/123860058-465e7e00-d8da-11eb-86f4-ece18bce56f2.png)

Under Threads > Customer, entered "email" in the first field, per field desc text / [API docs](https://api-docs.freescout.net/?javascript#conversations). Tried both quoted `"email"` and unquoted `email`.

![freescout-customer-email](https://user-images.githubusercontent.com/1054659/123876086-9e53af80-d8ef-11eb-9071-383e10ee43b3.png)

App logs empty.

Cleared Cache, Migrated DB.

`hash` php extension installed. (Shouldn't matter for API; used for signing webhooks only?)

Permissions, info OK under system/status.

Action setup:

![freescout-action](https://user-images.githubusercontent.com/1054659/123860241-8160b180-d8da-11eb-978d-86860043a1f2.png)

Test request:

![test-action](https://user-images.githubusercontent.com/1054659/123877472-16bb7000-d8f2-11eb-874c-4766623d18ef.png)

**Comment by xdividr** [comment]
Zapier support:

> Indeed it looks like there is an issue with the way the payload is processed. I've logged a bug report on an internal system we use to track such issues for the FreeScout team to look into this. 
>
> Although I don't have a solution for you at this time, I have gone ahead and added you to the bug report as an affected user, which adds more weight to the issue and ensures that you'll be notified once it's fixed. While I hesitate to provide an ETA for when this will be resolved, I can say that you will certainly hear from us with an update once it has been.

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the API & Webhooks Module v1.0.23. Please update and try again.

**Comment by xdividr** [comment]
Fixed, thanks!

**Comment by johanoloflindberg** [comment]
I have the same problem as above.  Is there still a bug? @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
> I have the same problem as above. Is there still a bug? @freescout-helpdesk

Are you using the latest version of the API & Webhooks Module?
