### ISSUE TITLE
Show Original leads to Timeout

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1303]
FreeScout has the feature to display the original message for a thread item. However, this feature is so slow that the request ends with an Timeout. 

I tested this feature also in your FreeScout Demo and here is the feature also extremely slow and the request finished with 22 sec. And typicall timeouts are 30sec.

This feature is crucial for us, because customers regularly answer within our reply. So we need to check the original message.

**Comment by freescout-helpdesk** [comment]
The original email is being fetched from the mail server. So performance of the "Original Message" view depends only on the speed of your mail server's IMAP.

**Comment by obstschale** [comment]
Thank you for the clarification. I will talk to my admins.

**Comment by fulldecent** [comment]
Thank you, recommend to close issue

**Comment by obstschale** [comment]
We increased the timeout limit and now it works. However it takes a long time.
