### ISSUE TITLE
Are the mobile apps closed source?

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#1304]
I've searched but not found any links to the source for the mobile apps, or clarification of whether this is intentional (they are proprietary) or not. Please can you clarify?

**Comment by freescout-helpdesk** [comment]
Source code of any Android app can be downloaded like this: https://apkcombo.com/freescout/net.freescout.app/
iOS app is the same app compiled for iOS.

**Comment by DavidAnderson684** [comment]
Thank you for replying, and forgive my slowness, but, where is the link on that page for the source code? I see only a button to download the compiled APK.

Also - what is the licence for the mobile apps? I've searched but cannot find that information.

**Comment by freescout-helpdesk** [comment]
Download APK and unzip it. Mobile apps are developed using Cordova which is licensed under Apache License 2.0

**Comment by DavidAnderson684** [comment]
Does the fact that Cordova is APL mean that all apps developed with it are also APL? Or you're saying that your app is?

The zip has various binary blobs. Are those re-creatable by anyone who installs Cordova?

Looking at the source, I infer the app is just a thin wrapper round a web view, plus handling of notifications? i.e. Compared to just visiting your install in a web browser, the benefits are notifications - anything else?

**Comment by fulldecent** [comment]
The app is open source. It is a thin wrapper.

Recommending to close issue

**Comment by DavidAnderson684** [comment]
How do we recompile from source? The licence is APL 2.0, or something else?

**Comment by fulldecent** [comment]
Sorry, I misspoke. Yes, that code should definitely be uploaded to https://github.com/freescout-helpdesk/freescout-ios-android so that we can contribute to it. (If the owners want contributions.)

**Comment by freescout-helpdesk** [comment]
Mobile apps are not supposed to be customized, they are provided as is.

**Comment by fulldecent** [comment]
Agreed.

Just a quick note. I know that updating the configuration for apps can be a pain. For example a new phone comes out in a new shape and the existing app has the wrong geometry (like Apple has done before many times). One benefit of open sourcing the app is maybe somebody here with experience with these specific PITA things can do it, rather than relying on the FreeScout team to have some very specific iOS app configuration knowledge.

But either way, it's your decision.

**Comment by DavidAnderson684** [comment]
So, they are de facto closed source. Thank you for taking the time to answer.
