### ISSUE TITLE
Two Factor module needs MariaDB 10.2+

### ISSUE THREAD

**Issue by rutger1140** [freescout-helpdesk/freescout#1305]
Just a headsup about a dependency issue I've run into.

When installing the Two Factor module I noticed an SQL error on the field type 'json':

```
production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `recovery_codes_generated_at` timestamp null, `safe_devices` json nul' at line 1 (SQL: create table `two_factor_authentications` (`id` bigint unsigned not null auto_increment primary key, `user_id` int null, `shared_secret` blob not null, `enabled_at` timestamp null, `label` varchar(191) not null, `recovery_codes` json null, `recovery_codes_generated_at` timestamp null, `safe_devices` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)
```

This type is [only supported in MariaDB 10.2](https://mariadb.com/kb/en/json-data-type/) and above.

Ubuntu 18 TLS comes with 10.1 by default. Using [this guide](https://mariadb.com/docs/deploy/upgrade-community-server-cs104-ubuntu18/) I was able to upgrade.

Might be useful to add this in the system requirements readme?

**Comment by freescout-helpdesk** [comment]
Fixed in Two Factor Authentication Module v1.0.3
