### ISSUE TITLE
Customer updated name not considering

### ISSUE THREAD

**Issue by shajiuddin** [freescout-helpdesk/freescout#1309]
Hi Support,

Example:
I sent email to any mailbox from a new email address as name 'Chris' and second time with the same email address the name used as 'Chris OK' but it always consider the name 'Chris'
it should consider the new name which is 'Chris OK'

Is there any possibility to consider the updated name of customer or update the customer name?

Regards

**Comment by fulldecent** [comment]
This should not be updated automatically.

If we do this maybe it should be a popup / question

**Comment by freescout-helpdesk** [comment]
> Is there any possibility to consider the updated name of customer or update the customer name?

Unfortunately, not.
