### ISSUE TITLE
Webhook / API / updatedDate

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1311]
I have purchased the web hooks/API module.

My goal is to synchronize all updates into my database for reporting purposes. The expected strategy is:

1. Make a database with fields I want
2. Include `updatedDate` field
3. Make script to find the highest `updatedDate` in my database and then use API to load any new data since then
4. Have this script run as webhook and also on cron.

There are some problems with the API design.

1. Insufficient resolution in `updatedDate`. Because two updates can happen in the same second, this causes a problem.
2. The records show `userUpdatedDate` but I was expecting `updatedDate` which corresponds to the `updatedDate` filter.
3. Not every record has an `updatedDate` but I was expecting this to equal the created date if no "updates" were made.

And a confusion

1. Semantically, I expect the query to return (and it does) records that were created after my queried `updatedSince`. This works the way I want even though maybe it is wrong based on the fact that `userUpdatedDate` is null in these cases. Fixing the above makes his a moot point.

**Comment by fulldecent** [comment]
Proposed work plan:

- [ ] Add `updatedDate` field to conversations. Set this to the creation date initially. This is updated as `userUpdatedDate` is updated.
- [ ] Increase resolution of `updatedDate` to milliseconds
- [ ] Remove `userUpdatedDate`

**Comment by freescout-helpdesk** [comment]
Which API method are you talking about? There is no `updatedDate` field in the API.

**Comment by fulldecent** [comment]
Right, that's the problem.

You can set `sortField` to `updatedAt` but this corresponds to `userUpdatedDate` which is a different thing.

**Comment by freescout-helpdesk** [comment]
It looks like you are talking about https://api-docs.freescout.net/#list-conversations method.

sortField API parameter is sorting convsations by `updated_at` field.

`updated_at` field in the `conversations` table in in the API is updated every time some new thread is created (by user, customer or added a note).

We will add `updatedAt` field to the output of the following API methods: List Conversations, Get Conversation

> Increase resolution of updatedDate to milliseconds

Feel free to create a feature request here:  https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
`updatedAt` field added to the output of List Conversations and Get Conversation methods in API & Webhooks v1.0.25

**Comment by fulldecent** [comment]
Awesome, thank you

**Comment by fulldecent** [comment]
@freescout-helpdesk P.S. that link does not work for me:

<img width="826" alt="Screen Shot 2021-07-19 at 10 09 00" src="https://user-images.githubusercontent.com/382183/126173448-fb36e8d7-acbf-4e9e-9768-052feb5d9e09.png">
