### ISSUE TITLE
IMAP Folder To Save Outgoing Replies - input truncated to 25 symbols

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#1313]
without any errors or warnings
I have the folder with 30 symbols length 

For incoming mail 30+ symbols for IMAP folder name handled without any issue

**Comment by freescout-helpdesk** [comment]
If you are talking about "IMAP Folder To Save Outgoing Replies" field it's maxlength is 255 symbols in the Malbox's Fetching Emails form.

**Comment by sau7777** [comment]
Here is screenshot attached
entering 30 digit folder name
clicking save
foldername truncated to 25 digit
the real folder name changed to digits for better visuality 

![Before_after_save](https://user-images.githubusercontent.com/8371994/125425587-edc6aee6-a2b3-48bd-96d3-5a61eb7da471.jpg)

**Comment by freescout-helpdesk** [comment]
Are you able to rename the IMAP folder?

**Comment by sau7777** [comment]
Yes, sure!
Already renamed.
But such behavior seems to be a bug :)

**Comment by freescout-helpdesk** [comment]
During implementation this field was limited to 25 symbols in DB. Now we'll leave it as is to avoid "Row size too large" error: https://github.com/freescout-helpdesk/freescout/issues/393
