### ISSUE TITLE
Feature Request: Merging Tickets Add previous contact to CC of parent ticket

### ISSUE THREAD

**Issue by adamsewell** [freescout-helpdesk/freescout#1314]
When merging tickets, it would be nice to have the other ticket submitter added to the ticket as CC.

**Comment by fulldecent** [comment]
This could be dangerous as a default

**Comment by adamsewell** [comment]
I disagree, this is pretty standard on most ticketing systems. It is on FreshDesk as well as HelpScout if I recall correctly. How could this be dangerous?

**Comment by freescout-helpdesk** [comment]
We'll leave this as it is.
