### ISSUE TITLE
Productivity report: link to drill down

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1315]
I have purchased the Reports module.

Some members on my team disagree with the numbers of closed items on this report. This may be a concern about whether items are counted as close based on the date they were closed or based on when those conversations started. **<< THIS IS NOT THE MATTED OF THIS ISSUE.**

On the report there are numbers. It would be very helpful if all of the numbers were a hyperlink that showed those corresponding items in the search interface. Such would be the best kind of self-documenting feature.

<img width="2203" alt="Screen Shot 2021-07-08 at 13 27 52" src="https://user-images.githubusercontent.com/382183/124966404-499bed00-dff1-11eb-929e-8634b0b50307.png">

**Comment by freescout-helpdesk** [comment]
See a notice here https://freescout.net/module/reports/:

> “Closed” number shows the number of conversations which has been closed in the selected period. This number may differ from the number of closed conversations in the Search, as the Search shows conversations created in the selected period which are currently closed.

We'll check if numbers can be converted into links.

**Comment by freescout-helpdesk** [comment]
We've tried to implement this but found out that it will be no use as Reports and Search are counting in different ways. For example MOST ACTIVE CUSTOMERS table counts threads created by customers in the selected period and the Search will show only conversations created by customers in the selected period. So numbers in Reports and Search will not match. We will not add this feature to the module to avoid constant questions: "Why number in Reports table and in Search do not match?"

**Comment by fulldecent** [comment]
I understand the methodologies do not match.

Created separate issue to track documentation problem: https://github.com/freescout-helpdesk/freescout/issues/1335
