### ISSUE TITLE
Error sending email to customer: Call to a member function isDraft() on null;

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1317]
Our log shows a lot of errors. Nearly every conversation is listed here.

![CleanShot 2021-07-09 at 09 58 34](https://user-images.githubusercontent.com/1058710/125044609-680af280-e09c-11eb-9577-81a84406cc44.png)

Do you have any idea how to fix this?

**Comment by fulldecent** [comment]
Can you differentiate which conversations are NOT causing you to see this error?

**Comment by freescout-helpdesk** [comment]
Go to System > Status and cancel background jobs.

**Comment by obstschale** [comment]
> Can you differentiate which conversations are NOT causing you to see this error?

No I cannot see any difference.



> Go to System > Status and cancel background jobs.

There is no "cancel background jobs" options. This is the only information I see on that page regarding jobs

![CleanShot 2021-07-15 at 09 24 18](https://user-images.githubusercontent.com/1058710/125746744-9fd3093e-6511-43a6-8512-b71f284b4149.png)

**Comment by obstschale** [comment]
To be hones, the problem did not occure since I started this issue.

**Comment by freescout-helpdesk** [comment]
OK. Closing it.
