### ISSUE TITLE
main.js refactoring

### ISSUE THREAD

**Issue by Junker** [freescout-helpdesk/freescout#132]
IMHO keep whole js code in one file is wrong, i think need to split main.js to several files, i.e. main.js, conversations.js, modules.js etc

**Comment by freescout-helpdesk** [comment]
As a first step we can just move code inside main.js into sections:
```
/**
* Conversations
*/
```

see how it goes and as a next step possibly split into files.

**Comment by freescout-helpdesk** [comment]
No need for now.
