### ISSUE TITLE
"Shotcuts" NOT WORKING

### ISSUE THREAD

**Issue by zuzullo** [freescout-helpdesk/freescout#1320]
To **mark a ticket as spam**, you should press [ **!** ] but in my keyboard I need to press **SHIFT+1** in order to get that _exclamation character_. Yet it does not work, nothing happens. Why?

**Comment by freescout-helpdesk** [comment]
> To mark a ticket as spam, you should press [ ! ]

Why do you need to press it? You just open the Status dropdown and select "Spam".

**Comment by zuzullo** [comment]
but, thats the point of shortcuts, right?! Its that at glace we can mark tickets as pending, spam, etc with a keyboard shortcut, no?
Or do you mean that the shortcuts do not work on other keyboards?

**Comment by freescout-helpdesk** [comment]
List of available shortcuts is available here: https://freescout.net/module/keyboard-shortcuts/
