### ISSUE TITLE
Still no Unassigned tickets visible on first glance

### ISSUE THREAD

**Issue by alecgm** [freescout-helpdesk/freescout#1321]
When I remember correctly some older post was about very useful UI enhancements. 

Right now when i look at the demo here I can't even determine if there are unassigned tickets or not - set aside some counter or colored marker in the overview.

![image](https://user-images.githubusercontent.com/77629009/125272546-43b54d00-e30c-11eb-9510-3bd5ab7985fb.png)

This on the other hand was really a well designed approach and deserved some support by the developers, but was was completely ignored at the time.:

![image](https://user-images.githubusercontent.com/77629009/125272691-6e9fa100-e30c-11eb-97db-c57fb2a1cdc8.png)

I wonder why no one seemed to be interested in such important enhancements.

**Comment by freescout-helpdesk** [comment]
![2021-07-12_13-48-31](https://user-images.githubusercontent.com/40499291/125275575-e2937680-e317-11eb-91a8-7634ba477326.png)

**Comment by alecgm** [comment]
I tried that in your online demo version. 

Tickets were not shown here and there was no counter at all while inside were two tickets. 
So is the online demo too old or is this a bug?

**Comment by alecgm** [comment]
To the developers:

This is one of the more strange communities here. I can see lots of "help wanted" but mostly no further discussions with interested developers. And although there seem to be many pay addons available I feel that there's no real concern about what people suggest or think.

Why posting a mere screenshot instead of a friendly answer?

**Comment by freescout-helpdesk** [comment]
Those numbers are showing the number of active conversations. Just change the status of some conversation to Active.
