### ISSUE TITLE
Feature request: split ticket

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#1323]
Detach the new incoming message in tread to a new ticket

**Comment by fulldecent** [comment]
This feature exists it is here
<img width="1491" alt="Screen Shot 2022-10-12 at 10 55 44" src="https://user-images.githubusercontent.com/382183/195377245-b7ef4bd4-2fbc-4fc0-ae5b-1f4148d53b02.png">

**Comment by kovoks** [comment]
Well, that gives an editor to sent an email with that text. I think the original poster would just like to separate a message from a customer that hijacked a conversation into a new conversation.

If so, I created a pull request for that. Hope it gets accepted. #2430

**Comment by freescout-helpdesk** [comment]
Implemented as "Clone Conversation" feature: https://github.com/freescout-helpdesk/freescout/pull/2430. It will be published in the next release.
