### ISSUE TITLE
Ticket Number 

### ISSUE THREAD

**Issue by ceitcon** [freescout-helpdesk/freescout#1324]
I don’t know how to use Ticket Number also I need to know what is the difference between ticket number and conversation number.
According to Ticket Number Module view details ,its mention that when the support send an email to the customer then ticket number will be added to the subject header, but I don’t know how the agent can send email to the customer from the portal as we have only conversation ?

**Comment by freescout-helpdesk** [comment]
In FreeScout tickets, conversations and emails are the same thing.
