### ISSUE TITLE
Switch on/off ticket signature

### ISSUE THREAD

**Issue by aclassnet** [freescout-helpdesk/freescout#1325]
Hello dear friends.

I would like to know how I can enable / disable ticket signatures.

Whenever I create a new ticket on behalf of my clients using the envelope for a new conversation, my signature appears. Is it possible to disable the signature in certain cases?

Thank you very much in advance for your support.

Best regards.

Alfonso Fernandez

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible and no plans to add this feature to the core of the app. Someone can implement it as a custom module:
https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
