### ISSUE TITLE
Closed emails throwing “Whoops” error when trying to open/view

### ISSUE THREAD

**Issue by iamkhris** [freescout-helpdesk/freescout#1327]
Hi there,

I’ve got a brand new installation of Freescout with 3 paid modules (CRM, Time Tracking and MFA) running under an ISPConfig installation with PHP 7.4.  The issue I’m having is that as soon as I mark a message/conversation as Closed, when I try to open it again I get a Whoops error.  The messages still exist in the Inbox of my associated mailbox it’s pulling from.

I’ve found a few examples of people getting the Whoops error, but all under different circumstances.  Has anyone seen this before, and if so, have any suggestions?

Thanks
Chris

**Comment by iamkhris** [comment]
Seemingly it’s my own issue.  I was trying to organize the customers that were generated along with emails received, and something I did there (possibly deleting one of the created users) prevented me from opening the closed messages.

After deleting the mailbox, setting messages as unread, adding mailbox back into Freescout and re-importing, I can open the messages after they’ve been closed.  I feel like there should be a better way to handle an error like this, but I’m also sitting on the user side of things.

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue. If you'll face it again the first thing you need to do is to get the error message in Manage > Logs > App Logs.
