### ISSUE TITLE
Text color inside email or reply

### ISSUE THREAD

**Issue by TomCamin** [freescout-helpdesk/freescout#1328]
Hi,

We found a issue, when we receive an email from outlook and we add color inside text that not always appear.

I have attach some screenshot. Hope you could help me about that :)

It's about "Texte de couleur" in my screenshot. On outlook the original and after some variable in freescout.
I use last version of freescout :)

Thanks a lot

![Capture d’écran 2021-07-15 à 16 36 36](https://user-images.githubusercontent.com/1707200/125808230-0842444e-3a5c-42b8-b89d-5cfde19a4bdc.png)

<img width="846" alt="Capture d’écran 2021-07-15 à 16 38 32" src="https://user-images.githubusercontent.com/1707200/125808255-aa5952c9-79dc-4644-a19d-0b4e73983d6e.png">

<img width="805" alt="Capture d’écran 2021-07-15 à 16 40 16" src="https://user-images.githubusercontent.com/1707200/125808275-e2763f72-a3d5-4cca-9cb0-00bd1c01033c.png">

![Capture d’écran 2021-07-15 à 16 40 32](https://user-images.githubusercontent.com/1707200/125808289-b42eba2b-0fd3-488b-9f1f-cd801285e415.png)

**Comment by freescout-helpdesk** [comment]
HTML of your email is not valid. There are double quotation marks inside of double quotation marks which is not allowed.

![2021-07-18_08-37-44](https://user-images.githubusercontent.com/40499291/126057001-d374cfb9-5023-43ed-8785-c7049d68de49.png)

**Comment by TomCamin** [comment]
Ok thanks for your reply!
So i think that the problem come from outlook.
