### ISSUE TITLE
Color in wysiwyg editor new conversation

### ISSUE THREAD

**Issue by TomCamin** [freescout-helpdesk/freescout#1329]
Hi,

Is it possible to activation the color element in the panel of the wysiwyg like in signature module?

![Capture d’écran 2021-07-15 à 17 03 16](https://user-images.githubusercontent.com/1707200/125811499-78d6f9c2-e91f-4ae4-b465-3856e3824b08.png)
![Capture d’écran 2021-07-15 à 17 03 30](https://user-images.githubusercontent.com/1707200/125811500-ac2008ea-2579-4d57-bd84-279e82096f92.png)

Thanks a lot

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible and no plans to add this feature to the core of the app. Someone can implement it as a custom module:
https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
