### ISSUE TITLE
Host freeScout at heroku and pgsql 

### ISSUE THREAD

**Issue by MohamedHassan-dev** [freescout-helpdesk/freescout#1331]
hello i am try to deploy freescout on heroku for test but when install database from GUI to create first admin account i am find this error

Could not establish database connection: SQLSTATE[08006] [7] FATAL: password authentication failed for user "" FATAL: no pg_hba.conf entry for host "ip here", user "", database "", SSL off

I am sent request from https and i am sure about database config parameter thats enter at gui

**Comment by freescout-helpdesk** [comment]
https://gis.stackexchange.com/questions/338391/qgis-cant-connect-to-postgis-but-pgadmin4-works
