### ISSUE TITLE
Ticket Number Vs Conversation Number

### ISSUE THREAD

**Issue by ceitcon** [freescout-helpdesk/freescout#1332]
I need to understand the difference between Ticket Number and Conversation Number,

"In Gmail when a support agent sends a message to a customer first – everything works fine. But when a customer sends an email from Gmail to FreeScout, Gmail may preserve original customer’s subject line and not show to the customer a new subject from support agent reply. "

I need to understand why and how the support agent send 1st message to the customer out of freescout panel ?

I need an example for it.

Regards

**Comment by fbartels** [comment]
> I need to understand why and how the support agent send 1st message to the customer out of freescout panel ?

There is a button to start a "new conversation" in the mailbox view just below the folders:

![image](https://user-images.githubusercontent.com/1257835/126465053-f2adc2b3-93de-4537-8468-d2c2ca5bbb03.png)

From there you can send a mail to an address or create a "phone ticket".

**Comment by freescout-helpdesk** [comment]
@fbartels Thanks for helping.
