### ISSUE TITLE
Import instagram message to Freescout

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1334]
Hi guys,

I see that facebook, telegram, whatsapp have options to import in freescout.
How about instagram?

Thanks!

**Comment by pmhtuk** [comment]
I'd say this may be unlikely - FB has been removed as there's too many hurdles to jump through and with the EU and wider lawsuits with Facebook it probably wouldn't get further at the moment.

**Comment by freescout-helpdesk** [comment]
Feel free to add to https://freescout.net/request-feature/
