### ISSUE TITLE
freescout and  Heroku host dropdown crash after reload 

### ISSUE THREAD

**Issue by MohamedHassan-dev** [freescout-helpdesk/freescout#1338]
i am try to deploy freescout to heroku and all function working after first commit push to head master when i am try to push second commit and reload and login at browser all dropdown and search box not working and dashboard dropdown redirect me to href path /# what should i do ithing problem at heroku js compile because its working fine local

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working

**Comment by MohamedHassan-dev** [comment]
Not working and logs 
Error: File '/app/public/storage/js/vars.js' does not exist; File: /app/vendor/devfactory/minify/src/Providers/BaseProvider.php (124)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
