### ISSUE TITLE
Modul: Noreply Emails

### ISSUE THREAD

**Issue by szucher** [freescout-helpdesk/freescout#1339]
Hi,

i´ve installed the new modul "Noreply Emails". The Modul shows not a warning message when i try to send a mail to noreply@....

Is this an Error?

Kind regards,
Steffen

**Comment by freescout-helpdesk** [comment]
Have you activated it? Could you please attach a screenshot.

**Comment by szucher** [comment]
Yes activated and config already done!

![noreplysettings](https://user-images.githubusercontent.com/50209392/126605876-780795c0-d4a1-4ce0-b15d-d0bcaa5f7a14.PNG)
![modul_activ](https://user-images.githubusercontent.com/50209392/126605879-4fca22a0-10ff-4412-a320-9df5b51cde42.PNG)
![noinfo](https://user-images.githubusercontent.com/50209392/126605880-da098fd4-b125-4f54-aed1-1d6372dd30f5.PNG)
![Screen1](https://user-images.githubusercontent.com/50209392/126605886-cd1224d5-cc18-4b2b-af41-d6ecf3295d0f.PNG)

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://demo.freescout.net ? If yes please send a screenshot when entering the email address.

**Comment by szucher** [comment]
It´s not a problem when i enter the Mailadress

The Problem exists when i try to answer an existinig message, where the sender has an mail adress with no-reply....

**Comment by freescout-helpdesk** [comment]
Warning is displayed only when you are manually adding a noreply email to To, Cc or Bcc fields.

**Comment by szucher** [comment]
> Warning is displayed only when you are manually adding a noreply email to To, Cc or Bcc fields.
> 
> And if a conversation was received from a noreply email, the warning will not be displayed when answering to such conversation.

Thank you 👍
