### ISSUE TITLE
Dropdown menu not working at server heroku

### ISSUE THREAD

**Issue by MohamedHassan-dev** [freescout-helpdesk/freescout#1340]
Dropdown not working after deploy at server all assets loaded only this error on logs Error: File '/app/public/storage/js/vars.js' does not exist; File: /app/vendor/devfactory/minify/src/Providers/BaseProvider.php (124)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
