### ISSUE TITLE
dropdown menu sometime crashed with vars.js not exist error on logs (i am checked permission)

### ISSUE THREAD

**Issue by MohamedHassan-dev** [freescout-helpdesk/freescout#1345]
i am have error and dropdown crashed every time after installation from web browser all function working fine but after second deploy at server some function crashed and not working with error with error log 

Error: File '/app/public/storage/js/vars.js' does not exist; File: /app/vendor/devfactory/minify/src/Providers/BaseProvider.php (124)

and i am asking and informed this permission issue but it's working from first deployment and second one crashed i am ask if there is any solution to void this error please 

when i am route to app-log/app (dropdown and error disappear ) and all function working after deploy crash again !!

**Comment by freescout-helpdesk** [comment]
The only possible reason is https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
