### ISSUE TITLE
Workflow not triggered with custom date field

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1347]
In some cases we need to take action in the future to delete data or answer the customer. I have added a custom date field "Follow-up" (in screenshots named "Wiedervorlage"; german word).

The idea is to set the date when this conversation needs attention again. So we set the date like 30 days in the future and close the ticket. I have added a workflow, which checks if that date is today and the workflow should set the status to open again. But this does not work. It only works if the workflow is saved or a field is changed/set in the coversations. But already closed converstations are never reopend by this workflow.

This issue https://github.com/freescout-helpdesk/freescout/issues/885 sounds very similiar.

Do you have any idea why this workflow does not work as intended?

![CleanShot 2021-07-26 at 14 44 34](https://user-images.githubusercontent.com/1058710/126990789-20586a75-b9bd-48b7-b83b-00446ba95c93.png)

![CleanShot 2021-07-26 at 14 44 40](https://user-images.githubusercontent.com/1058710/126990798-89d77e0e-e571-4f98-88f4-5669a925efd4.png)

![CleanShot 2021-07-26 at 14 44 51](https://user-images.githubusercontent.com/1058710/126990804-c97fa9c7-99d8-4fb8-b700-b1b863f2c2e2.png)

![CleanShot 2021-07-26 at 14 44 54](https://user-images.githubusercontent.com/1058710/126990812-b5d84b3f-bbeb-4087-9c58-7bae9e3bc9fe.png)

**Comment by freescout-helpdesk** [comment]
In most cases the problem is with logically incorrect conditions. See Troubleshooting: https://freescout.net/module/workflows/

**Comment by obstschale** [comment]
I have a question: We have a custom date field. Does a workflow run again, if that date field changes, even if the workflow already ran before?

We usually set a follow up date (using custom date field), but after that step often another follow up is necessary.

**Comment by freescout-helpdesk** [comment]
Workflows are triggered once per conversation.

**Comment by obstschale** [comment]
:/ Can I change this behaviour?

--
Mit freundlichen Grüßen

Hans-Helge Bürger

hanshelgebuerger.de

PGP PubKey: A7F2745
Wie funktioniert E-Mail-Verschlüsselung mit PGP? (YouTube Video)
Am 10. Aug. 2021, 17:08 +0200 schrieb FreeScout ***@***.***>:

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
