### ISSUE TITLE
Mailbox notification not sent but test mail working for same mailbox

### ISSUE THREAD

**Issue by MohamedHassan-dev** [freescout-helpdesk/freescout#1349]
I am try to sent mail from create and configure mailbox and test mail working fine but when i am create new conversation mail not sent however i am unmute mailbox and update permissions for destination i am check system status and i am noted queue job like photo at same time that created new conversation 
![C49DFCB1-4878-41DD-88C0-40D179BFF378](https://user-images.githubusercontent.com/48699858/127082880-14a65108-f6d7-4052-9f9a-5371588687d9.png)

I am already checked server cron job and configure like photo on comment

**Comment by MohamedHassan-dev** [comment]
![FABAF4B8-FE86-47D6-88C7-BA2892D0D47D](https://user-images.githubusercontent.com/48699858/127083173-ab86228b-8de7-4885-b292-df8c50a9c652.jpeg)


Any help please @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
There is some problem with the background job.

https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-queuework-is-not-running

**Comment by freescout-helpdesk** [comment]
You may need to find someone who can check your installation: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
