### ISSUE TITLE
"Spam" ticket state should through a warning dialog

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#1351]
In continuation to #1205, which I'm unsure why it was dismissed so easily, the "spam" option in the "status" drop down list should throw a warning as it's currently too easy to miss-click and select, instead of "closed", and then you will miss all future e-mails from that address.

**Comment by nalafod** [comment]
Indeed it is quite easily to put a legit ticket to spam by mistake and once set as spam it is forgotten

**Comment by freescout-helpdesk** [comment]
The thing is that we don't add anything to FreeScout just in case (see https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#architecture--philosophy). Only when something is really needed.

So far we have not seen issues with Spam status switcher.
