### ISSUE TITLE
	Non-writable files found

### ISSUE THREAD

**Issue by oecin** [freescout-helpdesk/freescout#1353]
in system area  

always show me this 
storage/framework/cache/data/

Non-writable files found/var/www/html/storage/framework/cache/

Run the following command (read more):
sudo chown -R www-data:www-data /var/www/html

how to fix it

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
