### ISSUE TITLE
PHP 8 / Outdated Dependencies 

### ISSUE THREAD

**Issue by admdly** [freescout-helpdesk/freescout#1355]
I've been working on a dev setup for this project, and I've noticed there are a number of issues with PHP 8 and outdated dependencies. 

I understand there is no desire to update to the latest Laravel but are you open to PRs that update dependencies to correct issues, provided these are tested and do not introduce new issues? 

For example, the version of fzaninotto/faker currently required does not work correctly with PHP 8 (implode() error on db:seed) but the latest version appears to work fine without breaking anything.

**Comment by freescout-helpdesk** [comment]
Yes. Feel free to try.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/1357#issuecomment-894013781
