### ISSUE TITLE
Delete Attachment

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1358]
As a German company we take data privacy laws quite serious. We just had the case that we needed to delete an attachment because the customer requested that.

Unfortunately, you cannot delete one in FreeScout. I had to delete it in database and filesystem. Do you plan to implement that features?

**Comment by freescout-helpdesk** [comment]
Maybe in the future GDPR module will appear allowing to delete attachments. For now feel free to add a feature request: https://freescout.net/request-feature/

**Comment by obstschale** [comment]
GDPR Module has been released. hint hint ;)

**Comment by freescout-helpdesk** [comment]
Deleting attachments added to [Extended Attachments Module](https://freescout.net/module/extended-attachments/).
