### ISSUE TITLE
inbox module

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#1360]
Hi.  The inbox seems useful, thanks.

Could this be a precursor to being able to sort by columns other than date?  Perhaps an addition of a priority field in tickets to allow for sorting by priority value in the inbox module?

**Comment by freescout-helpdesk** [comment]
Feel free to add these features here: https://freescout.net/request-feature/

**Comment by justajeffy** [comment]
Cool, I didn't know about this page.  Thanks!
