### ISSUE TITLE
Reply to forwarded message is created as new thread occationally. Want to fix...

### ISSUE THREAD

**Issue by jensolsson** [freescout-helpdesk/freescout#1362]
Hi

Just trying out Freescout and it feels awesome!

We are collaborating with another organisation and sometimes wee need to send an issue to them. When we do they will reply with an issue id of their own. For some reason this creates a new thread. We can merge it manually but would like it to be automatic. Would love to look into this myself but would be great to get some pointers on where to start.

So we receive an e-mail from a customer with subject:
Test
It gets issue #4

We forward it to our collaborator and the outgoing mail had the subject:
[#5] Fwd: Test

We get an auto reply from collaborator which has the subject:
Issue received: ABC123456 - [#5] Fwd: Test

This issue is not added to the thread of issue #5 in FreeScout but a brand new thread is created.

I then get an actual reply from the colaborator and it has the subject:
Customer Case: ABC123456 - [#5] Fwd: Test

And this actually works, it is added to the correct thread.

Now looking into the actual raw data of the messages I see that the failed one has MIME encoded headers so the subject actually looks like this:
Subject: =?UTF-8?Q?=C3=84Issue_received:_ABC123456__-_[#5]_Fwd:_Test_?=

So my questions for investigating this further is:
1. What is actually managing the threads, is it enough to have the same [#X] in the subject?
2. Is it then reasonable that the mime-encoding would cause this issue?
3. Fixing this bug (if it is a bug) should I look in the Ticket Number module I bought or should I look in the main code?

Kind regards
Jens

**Comment by freescout-helpdesk** [comment]
Subject does not matter. Incoming email to be connected to the existing conversation should have a proper `In-Reply-To` header set.

**Comment by jensolsson** [comment]
Thanks for the quick response. Oh, I understand. I checked the raw messages of all the e-mails and none of them had a proper In-Reply-To, but most replies are still sorted in the same thread. Are there more functionality at play here?

Kind regards
Jens

**Comment by freescout-helpdesk** [comment]
Message-ID is also checked in the email in special marker {#FS:XXX#}
https://github.com/freescout-helpdesk/freescout/blob/7f6bda6c768d2502e7766070d32a3eb43c18de17/app/Misc/Mail.php#L447
