### ISSUE TITLE
User Account "Alternate Emails" Not Working?

### ISSUE THREAD

**Issue by bcampano** [freescout-helpdesk/freescout#1363]
We are working on a fresh FreeScout installation and are having some issues with the Alternate Email setting in the User Account.  We have a generic mailbox setup for **support@domain.com** with two sub-teams:

- An **internal** TeamA made up of User1@domain.com, User2@domain.com, etc.
- An **external** TeamB made up of User1@otherdomain.com, User2@otherdomain.com, etc.

Our plan is to have TeamA triage all incoming tickets and either handle/close the ticket or "reassign" the ticket to TeamB. TeamB has a generic **support@otherdomain.com** email account on their side which then forwards all incoming messages to their users User1@otherdomain.com, User2@otherdomain.com, etc.

We need to ensure all TeamB users remain involved with all communications for tickets assigned to them as they have coverage shifts. To avoid having specific external users assigned to a ticket and not have to maintain all of the TeamB users in our instance of FreeScout, we were hoping to only setup a single user account in FreeScout for their generic **support@otherdomain.com** and use the **Alternate Email** setting in this generic account to list each of the potential respondents to the ticket being User1@otherdomain.com, User2@otherdomain.com, etc. so FreeScout will not reject their email responses.

However, when we test this implementation, FreeScout responds back to the User1@otherdomain.com with:

> Your email update couldn't be processed
> If you are trying to update a conversation, remember you must respond from the same email address that's on your account. To send your update, please try again and send from your account email address (the email you login with). 

Are we misinterpreting the Alternate Email setting? Is there a better way to achieve what we are trying to do?

**Comment by freescout-helpdesk** [comment]
It's hard to understand what you are trying to achieve.

**Comment by bcampano** [comment]
We have an internal and external support team we want to handle tickets incoming to support@domain.com. The internal part of the workflow works fine where our team is emailed notifications of incoming tickets, can triage them and close them accordingly. However, for some tickets the internal support team will need to "assign" the ticket to the external support team with account support@otherdomain.com. To avoid creating/maintaining user accounts in our FS instance for each of the external resources (and we also want to avoid hard assigning the ticket to one specific external support team member), we were hoping to have one generic account support@otherdomain.com configured in our FS instance and simply list each of the "members" of that support team User1@otherdomain.com, User2@otherdomain.com, etc. as **Alternate Email** address in the support@otherdomain.com user account. Our assumption was that by doing this, any member of this external support team can reply to the ticket assigned to the support@otherdomain.com and would be routed to the end client accordingly. However, when we list these support team email addresses in **Alternate Email** field in the user account they seem to be ignored and any listed email account used to respond bounces with the message noted above.

Hopefully this helps to make our situation/desires more clear?

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by bcampano** [comment]
Any updates/guidance you could provide would be GREATLY appreciated!

**Comment by bcampano** [comment]
As we are in the midst of determining whether we can use FS for our ticketing system has anyone had a chance to check the operations? We have already purchased many of the plug-ins so would love to find a way to stay with the platform. Please advise if you need any additional information to help?

**Comment by freescout-helpdesk** [comment]
Maybe in about a week.

**Comment by freescout-helpdesk** [comment]
Implemented (in the master branch)

**Comment by bcampano** [comment]
Just tested this new implementation and it appears to work as expected! Appreciate the quick turn around!
