### ISSUE TITLE
Time tracker is not saving time properly

### ISSUE THREAD

**Issue by webpreparejordy** [freescout-helpdesk/freescout#1365]
Hey Guys,

I think I've found a bug with the time tracker. This happens when I open an other ticket and after that going back to the regarding ticket. As you may notice the tracker as been reset to the last known time spend.

Worth to mention; this tickets has been merged several times.

See here for a screen record:

https://www.loom.com/share/5e025300f7f345ae98294f08e140793f

Thanks,
Jordy

**Comment by freescout-helpdesk** [comment]
404

**Comment by webpreparejordy** [comment]
What do you mean with 404?

**Comment by freescout-helpdesk** [comment]
This can't be fixed. Delays between switches is too small (30-40 sec).

**Comment by TheNerdSquad** [comment]
I do have an addition to this, as the time logs seem to not be saving at times. I have a separate window with the ticket open and the timer running, when I finish sometimes I do not add anything was mainly timing actions, but am not done. 
So I navigate from the page to answer a new ticket and then when I come back to the first ticket where the timer was around 45 min or whatever when I left it, it is back at 0 or a few minutes?

Am I doing something wrong? I have it to pause when I navigate away and then start again when I return.

**Comment by freescout-helpdesk** [comment]
@TheNerdSquad What Tracking Mode do you have in Time Tracking settings?

**Comment by freescout-helpdesk** [comment]
@TheNerdSquad Can you reproduce the issue on https://demo.freescout.net ?

**Comment by TheNerdSquad** [comment]
@freescout-helpdesk I might but when I was trying today it would not allow me to adjust the settings in time tracker in system settings to the Start timer when user views the page then pause when navigating away.
So I think it wont produce the same resultant if that setting is missing.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here as we can't reproduce the issue.
