### ISSUE TITLE
Postpone a ticket

### ISSUE THREAD

**Issue by avegalco** [freescout-helpdesk/freescout#1366]
Hi team.
I would like to propose a new functionality.
Sometimes our agents have to wait some time before taking up an issue, for example, wait a week to check if an update was released and then respond to the customer.
Could FreeScout add a "postpone" status and a specific date?
Conversations in this state would go into a separate "postponed" category and would return to "own" or "unassigned" on the day it was scheduled, so that agents do not need to review these types of conversations every day.
Thank you!

**Comment by freescout-helpdesk** [comment]
Feel free to add as feature request here: https://freescout.net/request-feature/
