### ISSUE TITLE
Ticket Number module source code location

### ISSUE THREAD

**Issue by jensolsson** [freescout-helpdesk/freescout#1368]
Hi

Want to try to improve the ticket number module a bit. Where is the source code available?

Kind regards
Jens

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by jensolsson** [comment]
Thanks

i kind of thought i would find them in github. But i guess i can initialize a new locam repo for the module i have downöoaded to track my changed.
