### ISSUE TITLE
Send Later Module

### ISSUE THREAD

**Issue by droogadulce** [freescout-helpdesk/freescout#1371]
I don't know if there's a bug in the Send Later Module that's is not working with the 12-hour clock Time Format.

When I try to send an email using the 12-hour clock (by clicking on the check mark icon), it adds the am/pm tags and after clicking Send, it automatically sends the message, regardless of the scheduled time.
![Captura de Pantalla 2021-08-13 a la(s) 13 28 35](https://user-images.githubusercontent.com/16148321/129404442-76bc47d6-54e0-40fe-a189-ac5592d12d29.png)

On the other hand, if I use the 24-hour clock (by using the calendar icon), it sends the email in the scheduled time.
![Captura de Pantalla 2021-08-13 a la(s) 13 28 21](https://user-images.githubusercontent.com/16148321/129404703-4c0bdc78-8b68-4541-b3f8-bf92e54810c6.png)

These are the emails I sent:
![Captura de Pantalla 2021-08-13 a la(s) 13 31 55](https://user-images.githubusercontent.com/16148321/129404735-6bb8ff2c-b2d7-46a5-a9f9-1fb8e20c78d8.png)

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
Fixed in Send Later Module v1.0.3
