### ISSUE TITLE
API docs incorrect: closedBy is not correct

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1372]
The output we see is not matching the documented expected output

Expected:

<img width="1587" alt="Screen Shot 2021-08-16 at 14 32 09" src="https://user-images.githubusercontent.com/382183/129612568-99e5c4d5-932b-464f-8f7a-3d1d99b9d205.png">

Actual:

<img width="635" alt="Screen Shot 2021-08-16 at 14 31 56" src="https://user-images.githubusercontent.com/382183/129612592-ef664c06-4550-4a03-9015-9172beec9af9.png">

**Comment by freescout-helpdesk** [comment]
API output fixed in API & Webhooks Module v1.0.28

**Comment by fulldecent** [comment]
Awesome, thank you. Confirmed new version is working.
