### ISSUE TITLE
[Announcing] A module for loading AJAX content into your sidebar

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1373]
This lets you put anything you want into the sidebar of conversations view. Loaded asynchronously based on the customer email.

https://github.com/fulldecent/freescout-sidebar-webhook

The HTML loads from an AJAX off of another server you control and injects to the page live.

## Use cases

- Directly link to your customer management system
- Show details about order status live from your fulfillment system
- Quickly ship changes to your FreeScout system UI without updating modules
- Connect to backends using PHP/Node.js/Ruby/Perl/Rust/Go/Bash/Haskell and even Java

![screenshot](https://user-images.githubusercontent.com/382183/129658081-886e5cdc-8363-4446-9dec-8bb519f2d46f.png)

---

Inspired by Sidebar API. I couldn't figure out how to install that so it was easier for me to learn a little Laravel and create this. Sharing with the world, this is my first FreeScout module. Enjoy.

---

I'm not sure if community modules are supposed to go anywhere. If not, the announcement is done, feel free to close this issue.

**Comment by freescout-helpdesk** [comment]
Thanks. Added to Community Modules: https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules
