### ISSUE TITLE
Add Reminder or automatic follow up reply

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#1374]
I think if we can have a module or even feature in the CRM module itself where we can select a date to remind ourselves or send a follow-up reply if no response has yet been received for the ticket

**Comment by freescout-helpdesk** [comment]
It can be done with https://freescout.net/module/workflows/

**Comment by rosinghal** [comment]
Yeah, it won't work for specific threads if I am understanding it right

**Comment by densn93** [comment]
Use [Custom Fields Module](https://freescout.net/module/custom-fields/) and create a Date field.
You can use this field als a "follow-up"-date, in the workflow module you now can access this date and create custom scenarios.

Freescout is very powerful, you sometimes just have to think a little bit out of the box.

**Comment by freescout-helpdesk** [comment]
@densn93 Thanks for helping.
