### ISSUE TITLE
2FA module not able to enable for users Version: 1.0.3

### ISSUE THREAD

**Issue by ipflowss** [freescout-helpdesk/freescout#1378]
Hi there,

The 2FA module not able to enable for users Version: 1.0.3

I have the module "Required For All Users" but I cant seem to turn the module on for users that the 2FA is turned off.   new users added to the system have it off and I can not turn the option on .

What can we do about this?

Cheers

App Version 	1.7.15    
Date & Time 	Aug 17, 2021 08:46am
Timezone 	America/Los_Angeles (GMT-0700)
Protocol 	HTTPS
Web Server 	nginx/1.18.0
PHP Version 	PHP 7.4.3
PHP upload_max_filesize / post_max_size 	2M / 8M

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
Unfortunately we can't reproduce the issue. 2FA works just fine for newly added users.

![2021-08-20_10-27-01](https://user-images.githubusercontent.com/40499291/130196931-65179535-4169-4c42-b4fb-ea1ee239aa0c.png)

See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-one-of-official-modules-does-not-work-properly-or-just-stopped-working

**Comment by ipflowss** [comment]
Thanks - deactivating and reactivating all the modules and then resetting the password of the accounts that needed 2FA seemed to have worked during their resetting password process.  Closing this issue.  Thanks for your assistance.
