### ISSUE TITLE
Can't delete draft

### ISSUE THREAD

**Issue by bitcoinshirt** [freescout-helpdesk/freescout#138]
Hi,

1.0.6
php 7.3

I am unable to delete draft messages. It's still showing as a notification for some reason, I'm not sure if it's supposed to work that way, but it's slightly annoying.

![screen shot 2018-11-19 at 11 44 35](https://user-images.githubusercontent.com/36959754/48702336-f7fc8500-ebf0-11e8-962f-84cf07bcff86.png)

**Comment by freescout-helpdesk** [comment]
Ok. Will fix this.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/bc16a732b461b23cc5943ab4ca53fd1ecb8bf882

**Comment by dipakcg** [comment]
Same issue. I am unable to delete the draft messages.

I am unable to delete messages from *Deleted* folder as well.

Is the above issue(s) ever fixed or it's still in to-do list?
