### ISSUE TITLE
mailbox - emails - view

### ISSUE THREAD

**Issue by macuser91** [freescout-helpdesk/freescout#1380]
Hello, 
I need to have a view in every Mailboxes - I have 5 of them and different users allocated to each of them

So need to see:
Assigned --> to see how many emails have every single user, so if 30 emails in ASSIGN folder, how can I see how many belongs to USER1, USER2?

any way to create this view?

**Comment by freescout-helpdesk** [comment]
Unfortunately no for now. If you wish feel free to add a feature request: https://freescout.net/request-feature/

**Comment by macuser91** [comment]
ok, so is now way using CUSTOM FOLDERS & WORKFLOWS modules?

**Comment by freescout-helpdesk** [comment]
You can try Custom Folders module on demo.freescout.net

**Comment by macuser91** [comment]
<img width="1770" alt="screenshot" src="https://user-images.githubusercontent.com/89128470/130203906-e15ba9ce-a440-4419-a272-a18195797b29.png">
trying - but can see red comment - can not be done
