### ISSUE TITLE
Owncloud integration 

### ISSUE THREAD

**Issue by macuser91** [freescout-helpdesk/freescout#1381]
Hello, 
I’m looking for integration with file filesharing like owncloud or something simliar. Any solution?

**Comment by freescout-helpdesk** [comment]
What exactly do you need?

**Comment by macuser91** [comment]
some projects (mailboxes) have needs filesharing relating to this project, let me explain. 
INBOX1 - plenty customers send us some files, documents - which must be stored online to make them visible to selected members of our staff

same INBOX2, INBOX3

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
Maybe someone will implement as a custom module.
