### ISSUE TITLE
Saved Replies are loading to slow - 

### ISSUE THREAD

**Issue by jake-the-just** [freescout-helpdesk/freescout#1382]
Hello,
we recently moves from HS to FS and imported a bigger amount of saved replies.
Right now we are using around 280 saved replies which I am trying to organize.

Doing that, I am facing a loading problem. Every time the page is refreshing it takes around a minute to load the side - sometimes it even crashes. Quite annoying, because as soon as I e.g. assign a mail to a category the page is reloaded

Thats the message I am getting if I am checking the developer tools:
_[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>_

![Bildschirmfoto 2021-08-19 um 11 27 45](https://user-images.githubusercontent.com/89188342/130044792-8cd2e2ff-364e-49fa-823a-f7377c291b64.png)

Could you fix this please?

**Comment by freescout-helpdesk** [comment]
In admin area or in the conversation?

**Comment by jake-the-just** [comment]
The Problem only occurs in the admin area:
![Uploading Bildschirmfoto 2021-08-20 um 09.39.12.png…]()

**Comment by freescout-helpdesk** [comment]
Do you have any custom modules activated?

It actually possible to have >400 saved replies without problems: https://github.com/freescout-helpdesk/freescout/issues/1273

**Comment by jake-the-just** [comment]
Ok, I have to check with our admin, may take a while as he is on vacation. I'll get back to you.
Thanks for the quick responses so far!

**Comment by obstschale** [comment]
Indeed we have the following Modules active:

- API and Webhooks
- Block External Images
- Chat
- CRM
- Custom Fields
- Custom Folders
- Customer Data Enrichment
- Customization
- Email Commands
- End-user Portal
- Extended Attachments
- Extended Editor
- Facebook Integration
- Followers
- Global Mailbox
- Keyboard Shortcuts
- LDAP Integration
- Mobile Notification
- Office Hours
- Reports
- Satisfaction Ratings
- Saved Replies
- Spam Filter
- Tags
- Telegram Notification
- Telegram Integration
- Time Tracking
- Twitter Integration
- Two-Factor Authentication
- Workflows

**Comment by freescout-helpdesk** [comment]
How long are your Saved Replies? How many symbols each?

**Comment by jake-the-just** [comment]
Sorry, due to the vacation season, the request has taken a back seat.

Our Saved replies have very different lengths. 
Short SR have e.g. 340 characters (including spaces), long SR can have about 5000 characters.
Some SR contain (multiple) images, links and each SR has a fallback ({%customer.firstName%}).

**Comment by freescout-helpdesk** [comment]
Performance improved in Saved Replies Module v1.0.9
