### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by macuser91** [freescout-helpdesk/freescout#1383]
I would need a calendar for my team - any way to buy a module or another tool?

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
Maybe someone will implement as a custom module.

**Comment by freescout-helpdesk** [comment]
Community Calendar Module has been added: https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules
