### ISSUE TITLE
/app-logs/app page not responding // 500 error

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1385]
This page is not loading. The other logs pages are loading.

<img width="1552" alt="Screen Shot 2021-08-20 at 10 43 35" src="https://user-images.githubusercontent.com/382183/130251271-2097d933-b3cc-4eef-b624-2196917debf1.png">

<img width="1552" alt="Screen Shot 2021-08-20 at 10 46 27" src="https://user-images.githubusercontent.com/382183/130251389-fb1fd6f8-b429-40e0-9ca6-57b290ac6d4c.png">

---

My installation was set up using the official FreeScout setup instructions. Whatever the first option was, I always did that. No changes since except for installing modules.

---

There is nothing inside 

cat /var/log/nginx/error.log

---

Separately, my system emails are not sending, and that is why I want to see logs.

**Comment by freescout-helpdesk** [comment]
You need to find an error message in PHP or nginx logs. Without it no one can help you.

**Comment by fulldecent** [comment]
This error happened after an upgrade. 

Re-entering the gmail password fixed it.

Somebody somewhere said that the quoting format in some configuration may have changed (from no quotes to using quotes).

Either way, my problem is solved and so I cannot contribute any repro here.
