### ISSUE TITLE
My emails are not sending

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1386]
Please advise how to debug this. I do not see any information on relevant logs to review here.

<img width="1552" alt="Screen Shot 2021-08-20 at 10 53 18" src="https://user-images.githubusercontent.com/382183/130252365-04d456fd-93b2-40df-98a5-dd8c4cac940e.png">

**Comment by fulldecent** [comment]
I solved the underlying problem // for some reason I needed to reenter/save the Gmail password. Was working for a while and suddenly stopped. Cannot explain.

---

This issue is concerned with the lack of useful notes about logs when an error message is presented.

**Comment by freescout-helpdesk** [comment]
Send errors are logged in Manage > Logs > Send Errors

**Comment by idia** [comment]
I've had similar isse where emails were not send... We've hand nothing in the logs... and 300+ jobs in the queue. There was yellow banner on Emails stating "There were no send attempts yet". 

What have helped was to kill 2 of the processes in terminal.

so
`ps aux | grep queue`
showed ID's and I used

`kill -KILL #####`
where #### is ID number
