### ISSUE TITLE
Pre Sales Questions

### ISSUE THREAD

**Issue by aimeecringle** [freescout-helpdesk/freescout#1388]
Hi,

I sent an email but it bounced back as delayed mail, so I’m trying here.

Can FreeScout perform a round robin on incoming tickets? Example: 1st ticket automatically assigned to employee1, 2nd ticket automatically assigned to employee2, 3rd ticket assigned to employee1 again etc etc?

Is it also possible once a customer is assigned to an employee, that all future new tickets will automatically be assigned to the employee? 

Thanks

Aimee

**Comment by freescout-helpdesk** [comment]
Try to play with https://freescout.net/module/workflows/

**Comment by aimeecringle** [comment]
Thanks, I tried workflows. Doesn’t appear to have any way to do a Round Robin. Am I missing something?

**Comment by freescout-helpdesk** [comment]
Not out of the box.
