### ISSUE TITLE
Error occured. Please check your internet connection and try again.

### ISSUE THREAD

**Issue by operations999** [freescout-helpdesk/freescout#1389]
Hello,
It's a new installation and everything seems working fine. But when I try to create task or do anything I am getting error "Error occured. Please check your internet connection and try again."
There is nothing wrong with connection or server but error will pop up.
Any idea how to fix?
Thanks

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
