### ISSUE TITLE
Images in public do not load properly with Nginx

### ISSUE THREAD

**Issue by tareko** [freescout-helpdesk/freescout#139]
Hello all,

When I upload a profile photo, it correctly is inserted into `/storage/app/public/users/4494f967a6af6385713afaf08.jpg`

However, I get a `404` from my network monitoring, and the profile picture does not appear.

I see the following in filesystems.php:

```
        'public' => [
            'driver'     => 'local',
            'root'       => storage_path('app/public'),
            'url'        => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```

And this appears to be the relevant area in nginx (I'm using the default):
```
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|svg|woff|woff2|ttf)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
```

My nginx log has the following error:
```
/var/community/public/storage/users/4494f967a6af6385a583749e2d011308.jpg" failed (2: No such file or directory)
```

## Workaround:
I can workaround this by doing:
`ln -s storage/app/public public/storage`

Not sure how to debug, as the error doesn't really appear other than to say that the file is not there, which indeed it's not in the correct spot.

tarek : )

**Comment by tareko** [comment]
I installed using the web installer. However, indeed the link was not made.

**Comment by freescout-helpdesk** [comment]
So just create it manually.

**Comment by tareko** [comment]
I hear you saying that the installer creates the symlink. However, there was no indication to me as to why this part of the program was failing.

Perhaps as part of the `/system/status` check, it could also check permissions and the symlink?

**Comment by freescout-helpdesk** [comment]
Yes. It will be added.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/aaba49adf749bae1da5b04e0a587fbca10c4c7b1
