### ISSUE TITLE
Installation on standard web hoster

### ISSUE THREAD

**Issue by Attackwave** [freescout-helpdesk/freescout#1393]
Hi everybody,

im new to freescout and I have installed it to my raspberry pi4 and its working with NGinx.

Now I want to install freescout into a subdirectory of my webspace (Hoster: Strato).
What I have:

```
PHP: 7.4.22 (cgi-fcgi) (built: Aug  3 2021 15:59:25)
Cronjobs: yes
MySQL: 14.14 Distrib 5.6.45
```

.htaccess
```
Options +FollowSymLinks

<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /freescout
        RewriteRule (.*) public/$1 [L]
</IfModule>
```

php.ini
```
display_errors = Off
file_uploads = On
max_execution_time = 240
memory_limit = 512M
post_max_size = 128M
register_globals = Off
safe_mode = Off
upload_max_filesize = 128M
session.gc_maxlifetime = 1440
session.cache_expire = 180
cgi.fix_pathinfo = 0
opcache.enable = Off
```

First call of example.com/freescout opens example.com/freescout/install and following message:
**Sorry, the page you are looking for could not be found.**

Is it possible to install freescout to a standard webhost?
If so, what am I doing wrong and what have I not yet thought of?

Regards
Attackwave

**Comment by Attackwave** [comment]
Update:

- PHP-Boost: on
- Freescout installed into: <html-root>/cgi-bin/scout
- Symlink: <html-root>/scout to <html-root>/cgi-bin/scout
- RewriteBase added in htaccess
- .env ok, API Key, DB, User, clear config/cache etc. done

I can call example.com/scout and I will redirected to login. But CSS and JS is not working because bootstrap config url for css and js still leads to scout/js/.. | scout/css/... . All other URLs are correctly set to cgi-bin/scout/.

Ive tested with Mix App URL, but there are more things to do in laravel.

If I set the correct path to css and js in bootstrap config, the page is loading correctl with css. But js still wont work (eg. Postbox SMTP click show no Items for Input). In the browser console I can  see the following error:


`Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' data: ...'unsafe-eval'".... Either the 'unsafe-inline' keyword, a 
'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
`

Any idea?

**Comment by freescout-helpdesk** [comment]
To install FreeScout into a subdirectory no need to create extra .htaccess files, just make sure to set proper path in `Directory` parameter: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#62-apache

**Comment by Attackwave** [comment]
I have no access to apache config files...its a web hoster. Its only possible to add .htaccess files to your directories.

**Comment by Attackwave** [comment]
Im went from Strato to Hetzner. Freescout works now.
