### ISSUE TITLE
Open live chat window URL

### ISSUE THREAD

**Issue by ecomturbo** [freescout-helpdesk/freescout#1399]
Hello, Would there be a URL or path which would open the chat window when we click on a link or a button?
Thank you.

**Comment by freescout-helpdesk** [comment]
"Open in New Window" link added in Chat Module v1.0.6

![2021-08-29_10-23-55](https://user-images.githubusercontent.com/40499291/131242234-5a1f293a-3892-402c-95d4-82b9d92242ca.png)
