### ISSUE TITLE
Helpdesk URL & Knowledgebase URL

### ISSUE THREAD

**Issue by aadursun** [freescout-helpdesk/freescout#1400]
Hi, is it possible to have **customer portal**  and **knowledgebase** url in a friendly format / readable format?

customer portal =  mydomain.com/help/3018585735

knowledgebase = mydomain.com/hc/3018585735

this is not search engine friendly!!

i want to use **customer portal  on my main domain instead** of sign in form?

how can configure it?

kindly

**Comment by freescout-helpdesk** [comment]
Unfortunately, no. No plans to implement.
