### ISSUE TITLE
Design of knowledgebase

### ISSUE THREAD

**Issue by aadursun** [freescout-helpdesk/freescout#1402]
Hi,

i don't like layout / design after articles are sent to KB, see here
https://i.imgur.com/LlhX1TG.png

If the category is empty there is a box for it (3) with amount of articles inside (4)

after filling an article box is not displayed (1 + 2)

why can't we have still the box with amount of articles inside the category?

how to achieve this?

**Comment by freescout-helpdesk** [comment]
It's not quite clear what you need.
