### ISSUE TITLE
31 the same customers on CRM module

### ISSUE THREAD

**Issue by macuser91** [freescout-helpdesk/freescout#1406]
Hello, 

When I click on the CUSTOMERS link I can see 13 customers - and 3 the same customers with the same emails&conversations
Then - when I click on filter by mailbox --> select 1 mailbox - I can see 31 customers, and 27 the same customers with the same emails and the same convesations
Tried to remove some of them - but once done - next few records comes up. 

How can I leave just one?

**Comment by macuser91** [comment]
hello guys, 
now I have 52 customers - where 35 of the same customer - the issue is escalating still!

**Comment by freescout-helpdesk** [comment]
CRM Module just shows customers. You need to find out what creates them.
Do you have LDAP Module active? Are you making API calls?

**Comment by macuser91** [comment]
Customers are created based on senders from incoming emails only (by now)
I

**Comment by freescout-helpdesk** [comment]
You or your developer need to find out what is going on there.

**Comment by macuser91** [comment]
Hi guys,
It can not be closed - as I paid for the module - and it does not work. Please see on the attached screen - plenty of duplicated customers.

**Comment by freescout-helpdesk** [comment]
The module just displays the customer, it does not add them.

**Comment by macuser91** [comment]
I see,
So where the issue is? How can I get support?
