### ISSUE TITLE
New "From Name" Option

### ISSUE THREAD

**Issue by eickit** [freescout-helpdesk/freescout#1407]
Hi,

I have a feature request: Could a 4th option be introduced? "User's Name (User's Company Name)". There must also be another field in the profile for this: "Company Name".

In my opinion, this would make Freescout even more perfect.

![screenshot_20210830075432@2x](https://user-images.githubusercontent.com/4112464/131292417-7fc3ddef-0da8-4510-9391-14631aaa64f5.png)

Thanks, Sven

**Comment by freescout-helpdesk** [comment]
Unfortunately, not needed in the core. Can be implemented via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
