### ISSUE TITLE
Reference to help scout

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#141]
There's a reference to help scout in the notification preferences. I imagine this should be Free Scout

<img width="1074" alt="screenshot 2018-11-21 at 10 56 43" src="https://user-images.githubusercontent.com/1004130/48837071-3e321f80-ed7c-11e8-9a29-b5835b15fbc3.png">

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/9f6da13a57b9508058d9327f0ca890dc326248b5
