### ISSUE TITLE
cannot login (I get 500 (Internal Server Error) )

### ISSUE THREAD

**Issue by gerpaick** [freescout-helpdesk/freescout#1410]
Hi,
since yesterday I cannot login. I tried to create new user, but I still get 500 error. 
Only one account is working (the one I've created at the beginning). System is updated to ver  1.7.16 .
On system/status all is green. 
I have some errors on App Logs. 

`[2021-09-03 13:48:30] production.ERROR: Call to a member function getFullName() on null (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) {"userId":2,"email":"adrn@mgd.co.uk","exception":"[object] (ErrorException(code: 0): Call to a member function getFullName() on null (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) at /var/www/html/app/Thread.php:547, ErrorException(code: 0): Call to a member function getFullName() on null (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) at /var/www/html/app/Thread.php:547, ErrorException(code: 0): Call to a member function getFullName() on null (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php) at /var/www/html/app/Thread.php:547, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getFullName() on null at /var/www/html/app/Thread.php:547)`

What can I do to fix that?

**Comment by freescout-helpdesk** [comment]
It looks like Customer disappeared from Customers table. Have you deleted the customer from database manually?
