### ISSUE TITLE
Smime encryption

### ISSUE THREAD

**Issue by jensolsson** [freescout-helpdesk/freescout#1411]
Hi

i got smime signing working well with the plugin for signing outgoing mail however i am curious, will the plugin also validate incoming emails signed with smime?

Also saw the encryption option. Will freescout decrypt incoming messages signed with smine?

Also can it encrypt outgoing messages with smime and in that case how can FreeScout retreive the recipients public key?

kind regards
Jens

**Comment by freescout-helpdesk** [comment]
> will the plugin also validate incoming emails signed with smime?

No.

> Will freescout decrypt incoming messages signed with smine?

No.

**Comment by windgmbh** [comment]
I just bought the "Mail Signing & Encryption" module and was honestly a little disappointed by the fact that verification and decryption is not implemented. 
I know that it is a ton of proper work to fully implement S/MIME or PGP correctly. But the lack of those features makes the impression of an unfinished product. 

I have not looked at the 'Mail Signing & Encryption' module's code too much; but it appears to me, that PHP's `openssl` module would offer functions for [verification](https://www.php.net/manual/en/function.openssl-pkcs7-verify.php) and [decryption](https://www.php.net/manual/en/function.openssl-pkcs7-decrypt.php) of S/MIME messages.

**Comment by netspear** [comment]
Where can we get certificates for Signing and Encryption?
