### ISSUE TITLE
.ICS files are not imported in FreeScout

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#1412]
When a customer sends a meeting invitation using Microsoft Teams etc, which the email usually only has one attachment file `invite.ics`. 

However, FreeScout will only display a blank body without any attachments. 

No attachments were downloaded to Freescout although the original mail has .ics attachment. 

FreeScout view:
<img width="936" alt="Screenshot 2021-09-06 at 1 30 06 PM" src="https://user-images.githubusercontent.com/5198092/132165313-5c2b0dd2-7a98-4bd0-8557-41589670b92b.png">

Gmail View:
<img width="681" alt="Screenshot 2021-09-06 at 1 29 20 PM" src="https://user-images.githubusercontent.com/5198092/132165243-1a07a6b9-712d-4ddf-868a-4610455eeec8.png">

**Comment by freescout-helpdesk** [comment]
Can you send a test email to support@freescout.net

**Comment by fulldecent** [comment]
Can somebody experiencing this issue please reproduce in the latest version 1.8 or later?

**Comment by IIT-Richard** [comment]
@fulldecent I have reproduced the issue on V1.8.31, still not showing ICS files

![image](https://user-images.githubusercontent.com/68158378/198906854-f2f73b5b-9467-4175-9ab8-f20878d42cb2.png)

**Comment by freescout-helpdesk** [comment]
> @fulldecent I have reproduced the issue on V1.8.31, still not showing ICS files

Can you reproduce on https://demo.freescout.net?

**Comment by endoflevelboss** [comment]
Just revisited this issue and confirm it is still open in 1.8.55

As investigated in #1003 and #2054 this is related to the particular mail format sent by MS Teams. freescout does not recognize the attachment, probably because of some particular formatting, header information or other formal specialty. Sharing an ics does not allow debugging because the issue most likely lies with the notification email carrying the ics attachment. 

Would someone with access to MS Teams please volunteer and send an invite to freescout-helpdesk for a closer look? I'd greatly appreciate if someone could look into this. This issue forces me to keep open IMAP access for our organisation to extract inevitable MS Teams invites from the original email, as this does not include meeting details in plain text.

I would be ready to sponsor a quick bugfix.

**Comment by freescout-helpdesk** [comment]
@endoflevelboss Are you connecting to IMAP via OAuth or regular authentication?

**Comment by endoflevelboss** [comment]
Fetching mails by IMAPS with regular auth.

**Comment by freescout-helpdesk** [comment]
Try to add the following to `.env` file and clear cache:
```
APP_NEW_FETCHING_LIBRARY=true
```
And check fetching .ICS files.

**Comment by endoflevelboss** [comment]
Thank you so much, that does the trick. I really appreciate your work and great support.

The attachment shows up as "undefined" (no extension). Saving, however, will give "undefined.ics".

**Comment by endoflevelboss** [comment]
The "undefined" file name gave me the final hint. MS Teams does not assigning a name or filename to the attachment data block. 

Interestingly, MS states: 

"Messages that are composed by MIME clients as a multipart/mixed MIME message without a name parameter for the content-type or an optional filename parameter for the content-disposition header may not be rendered correctly when received by Exchange."

https://learn.microsoft.com/en-us/exchange/troubleshoot/administration/multipart-mixed-mime-message-format

So, MS Teams seems to send standard notifications that are not compliant with MS's own specs.

**Comment by endoflevelboss** [comment]
I don't have access to MS teams, but I'll try to find someone to send you a test invite. I'll ask the sender to refer to this bugtracker ID for your reference.

**Comment by endoflevelboss** [comment]
I can confirm the suggested APP_NEW_FETCHING_LIBRARY=true does the trick sufficiently well. I have been observing this for a month now and all incoming Teams invite were resolved to an "undefined" attachment. Saving this attachment will give an .ics file that can be dragged into the calendar. Works for me.

**Comment by eiclu** [comment]
I don't know if it's my OS or something changed with the functionality, but when I try APP_NEW_FETCHING_LIBRARY=true and downloading the "undefined" attachment, it stays as "undefined" and doesn't get any file extension, meaning I have to rename it before it can be opened.

Maybe Freescout could automatically set a file extension according to the Content-Type of the attachment?

**Comment by freescout-helpdesk** [comment]
@eiclu Send an example of the email (not FWD) to support@freescout.net

**Comment by eiclu** [comment]
> @eiclu Send an example of the email (not FWD) to [support@freescout.net](mailto:support@freescout.net)

Sent

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. Now .ICS attachments having no name will be stored as "calendar.ics".

**Comment by nebulade** [comment]
Came here to ask if `APP_NEW_FETCHING_LIBRARY=true` is considered stable for a good default by now? Asking since a Cloudron user fixed issues on his instance with it and we were wondering if the package defaults should thus include this.

**Comment by freescout-helpdesk** [comment]
> Came here to ask if `APP_NEW_FETCHING_LIBRARY=true` is considered stable for a good default by now? Asking since a Cloudron user fixed issues on his instance with it and we were wondering if the package defaults should thus include this.

It's still not perfect, but you probably can set it to `true` by default. We'll see how it goes.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#what-libraries-does-freescout-use-to-connect-via-imap
