### ISSUE TITLE
KB Issues/improvements

### ISSUE THREAD

**Issue by ecomturbo** [freescout-helpdesk/freescout#1413]
Hi, we like the KB overall but this is a serious issue for us right now. Would appreciate if you could help.

**UI:**

1. Replace the "Home" by "Back" because "Home" would mean our website homepage and not the KB home. ** IMPORTANT
2. Add a Tab "Return to Website" or "Home" ** IMPORTANT
3. The logo link should be editable too in order if we wish to link it to our website.
4. The top tab "Home" (Home can't be translated in French).
5. When you click on the search icon, we need to be able to translate it in French.

**TEXT EDITOR**

1. We need a bullet list like Github text editor ** IMPORTANT
2. A button to Reset Formatting. The code is so hard to edit in html because all is minified.
3. Add an info Box or something to highlight parts of the article.

**SEO**

1. The URL structure is a pain. We invest a lot writing content but these links are killing it a bit (We already voted for this feature). ** IMPORTANT
2. We need to set the SEO of the KB : Page title is in English, Meta description ** IMPORTANT

Thank you for all your hard work and this incredible Helpdesh product. We've purchase almost all your module even the Facebook one by mistake ;-)

**Comment by freescout-helpdesk** [comment]
We'll leave it as `help wanted`, maybe someone will implement this: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by freescout-helpdesk** [comment]
Most needed features feel free to add to https://freescout.net/request-feature/
