### ISSUE TITLE
KB Widget Translation in to French

### ISSUE THREAD

**Issue by ecomturbo** [freescout-helpdesk/freescout#1415]
Hi, I'd like to translate the KB widget into FR. Can you help? Thanks.
![image](https://user-images.githubusercontent.com/83525975/132280515-78d17a2a-6529-40b8-b0cf-53b10e36ee04.png)

**Comment by ecomturbo** [comment]
Hello @freescout-helpdesk I imagine you're super busy but if you could take a look. cheers

**Comment by freescout-helpdesk** [comment]
This phrase can be translated. Follow instructions https://github.com/freescout-helpdesk/freescout/wiki/Translate
