### ISSUE TITLE
Update issue, global mailbox is not in allowed path

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1416]
Hi guys,
I get this error on updating.
Do you have any idea what this could be?

<img width="464" alt="Schermafbeelding 2021-09-07 om 08 09 44" src="https://user-images.githubusercontent.com/5088751/132293084-4d0d4fbc-91dd-4e90-a19b-3f0a0688bb1f.png">

**Comment by webtyphoon** [comment]
Same here

**Comment by freescout-helpdesk** [comment]
We have no idea why it may happen.
