### ISSUE TITLE
Add option to delete emails from mail server when conversation is deleted forever in FreeScout

### ISSUE THREAD

**Issue by PaulBartelings** [freescout-helpdesk/freescout#1417]
Why is my email not deleted from my mail server when I press delete. It will be removed from freescout, but will remain on my mail server. I thought this was in sync with imap.

**Comment by fulldecent** [comment]
FreeScout is non-destructive on IMAP. You are able to delete emails on IMAP, which is a good idea to periodically delete every X months.

Recommending to close issue as out of scope.

**Comment by freescout-helpdesk** [comment]
Implemented in https://freescout.net/module/gdpr/
