### ISSUE TITLE
Email Notification for Assigned Conversations Not Working

### ISSUE THREAD

**Issue by jarranz2** [freescout-helpdesk/freescout#1419]
Hello,

I've detected an issue with email notifications when conversation was assigned to one user. I've this setting enabled in notifications but I never received the email notification.

I only received the notifications when I enable the notifications for New Conversations (All), assigned an no assigned.

Any help?

Thank you.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.

**Comment by jarranz2** [comment]
Assign one conversation to yourself.

Thanks.

**Comment by freescout-helpdesk** [comment]
And other users from this mailbox having "A conversation is assigned to someone else" notification enabled receive a notification.

**Comment by jarranz2** [comment]
Yes, if conversation is assigned from other user, notifications are sent but not if you assign one conversation to yourself.

Thank you.

**Comment by freescout-helpdesk** [comment]
> Yes, if conversation is assigned from other user, notifications are sent but not if you assign one conversation to yourself.

In this case other users receive notifications. You - don't.

**Comment by freescout-helpdesk** [comment]
Issue not confirmed.
