### ISSUE TITLE
Send test to box doesn't take effect

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#142]
When I use the send test button it sends to the mailbox address and not the test address I supplied.

<img width="438" alt="screenshot 2018-11-21 at 10 58 39" src="https://user-images.githubusercontent.com/1004130/48837157-76d1f900-ed7c-11e8-8731-0366848125f2.png">

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/20cb166ce871854222a31d8fc75328621f72ba14
