### ISSUE TITLE
Waiting since sort order

### ISSUE THREAD

**Issue by bcookatpcsd** [freescout-helpdesk/freescout#1420]
Sorry if this is addressed in a module, but search results seemed to indicate extra functionality in the module 'workflow'..

Is there a basic way to filter 'oldest to newest'? 

It seems I'm only able to start at the newest, and when finished be pushed to the 'now newest'.

I cannot start at the 'oldest' and then be pushed to the 'now oldest'.

I want to start at the oldest and work to the newest.. 

Did I make some incorrect default selections, or is that functionality gained via a module? 

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
We can't understand what you are talking about :)
