### ISSUE TITLE
Can't activate Module

### ISSUE THREAD

**Issue by FuXXz** [freescout-helpdesk/freescout#1423]
Hello,

i use the Docker Image to run Freescout. I set it up without Problems, but if i activate modules i see a popup
`Error occured. Please check your internet connection and try again. `

In the app Logs / laravel i can see this:
` Undefined constant "STDIN" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"STDIN\" at /www/html/vendor/symfony/console/Helper/QuestionHelper.php:158)`

What i have to do?

Thank you, best regards

**Comment by freescout-helpdesk** [comment]
Which image version are you using?

@tiredofit

**Comment by FuXXz** [comment]
I'am sorry i dont know how to get this info.
I have used tiredofit/freescout:latest and tiredofit/mariadb:latest

I bought the workflow module to test it. But the same error occurs there too.
After that, however, the module runs. But there are errors in the log everythime i use the module:

`Unknown named parameter $id {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Unknown named parameter $id at /www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221)`

**Comment by tiredofit** [comment]
You can check which image version you are using by going inside the container, and executing `head -n1 /assets/.changelogs/tiredofit_docker-freescout.md | awk '{print $2}'`

Same thing would be for if you are inside the `tiredofit/mariadb` container. `head -n1 /assets/.changelogs/tiredofit_docker-mariadb.md | awk '{print $2}'`

I try to avoid using `:latest` releases as something may have snuck in from parent images, during rebuilds, or . who knows. 

That being said, I'm not sure I can help with this one other than requesting you to get errors to display `DISPLAY_ERRORS=TRUE` in your environment variables.  If it does turn out to be something related to my image come on down to [the docker repository](https://github.com/tiredfofit/docker-freescout/issues) and we can unpack it there.

**Comment by FuXXz** [comment]
Freescout 1.15.13
DB 3.9.3

**Comment by tiredofit** [comment]
Thanks. Please try to get more information with `DISPLAY_ERRORS=TRUE`

**Comment by FuXXz** [comment]
I added the variable, but nothing happens. 
The modules seem to be working.
When I activate it, I only get the "Error occurred" message
Perhaps the best solution is to ignore the error?

**Comment by tiredofit** [comment]
I don't think we should be ignoring it, but perhaps I wonder if running a migration would be useful.

Can we go into the container and execute this?

````
cd "${NGINX_WEBROOT}"
sudo -u "${NGINX_USER}" php artisan freescout:clear-cache
sudo -u "${NGINX_USER}" php artisan config:clear
sudo -u "${NGINX_USER}" php artisan migrate --no-ansi
````

**Comment by FuXXz** [comment]
Done
![Screenshot 2021-09-13 220747](https://user-images.githubusercontent.com/9010594/133149588-ae33057f-350e-4b91-ad03-e2818fab35ff.jpg)

And the same Errror
[error.txt](https://github.com/freescout-helpdesk/freescout/files/7157104/error.txt)

**Comment by tiredofit** [comment]
Bizarre. @freescout-helpdesk I can't see that its something with my Image.

@fuxxz there is an alternative here, we can try to have you run under a different freescout image with a different PHP engine.

By default you should be using PHP 8.0. Maybe you could try `tiredofit/freescout:latest_php7.4 to see if the same problem occurs? Otherwise if it still does I'm going to hope that the developers here can figure this one out. I just don't know enough about development and am more of an ops guy.

**Comment by FuXXz** [comment]
I tested the 7.4 Image, same Error :(

**Comment by freescout-helpdesk** [comment]
This may be the reason: https://divinglaravel.com/the-problem-behind-undefined-constant-stdin-when-running-laravel-artisan-command-programmatically
But it's not clear why only you get this error.
