### ISSUE TITLE
API documentation, please document the data objects

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1427]
I have purchased the API module.

In the API documentation at https://api-docs.freescout.net/#get-conversation and other places, the return object is undocumented.

Please document the output object as a separate page in the documentation including what each data field means.

---

Separately I am about to file another issue about something that is not working properly. But even that is difficult because I am relying on how I feel it should work. Everything can be improved when how it is supposed to work is documented.

**Comment by freescout-helpdesk** [comment]
Example response is enough.
