### ISSUE TITLE
Updating tags does not update the conversation.updatedAt

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1428]
I purchased the API extension.

# Test case

1. Load `GET api/conversations/15` and note the `updatedAt` and `tags` values
2. Use the web interface to add a tag to the conversation
3. Load `GET api/conversations/15` and note the `updatedAt` and `tags` values

# Expected outcome

The `tags` value is updated and the `updatedAt` value is updated.

# Actual outcome 

The `tags` value is updated and the `updatedAt` value is NOT updated.

# Discussion

I use an extract-transform-load program to synchronize changes from FreeScout into my data warehouse which I use for reporting. (Happy to share this if anyone is interested.)

And the way that I identify conversations which need to be synchronized is from `updatedAt`.

So currently the problem is that conversations are being updated (tags) on FreeScout but my data warehouse has no way of being informed that it needs to update that record.

---

Related: 

- https://github.com/freescout-helpdesk/freescout/issues/1311
- https://github.com/freescout-helpdesk/freescout/issues/1372
- https://github.com/freescout-helpdesk/freescout/issues/1336

**Comment by freescout-helpdesk** [comment]
It's by design.

**Comment by fulldecent** [comment]
Is there / can there be any mechanism how I can be informed (webhook, incremental query) when a tag is updated?

**Comment by freescout-helpdesk** [comment]
Use https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#actions-and-filters
Add action to the code if needed: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by fulldecent** [comment]
Got it, thank you. 

I will find a developer to help find the did_change_tags hook and blast a webhook from there or update the `updated` field.
