### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#143]
In the fetching email settings 'checking' is spelt wrong.

<img width="455" alt="screenshot 2018-11-21 at 11 00 03" src="https://user-images.githubusercontent.com/1004130/48837254-c0badf00-ed7c-11e8-9097-2c335c7e30e2.png">

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/d509613d608d17b25f2453c59837ebc65508a0f8
