### ISSUE TITLE
End-User Portal

### ISSUE THREAD

**Issue by FuXXz** [freescout-helpdesk/freescout#1430]
Hello, everyone,

I am currently using the end-user portal and am wondering whether it can be expanded? I think the portal is essential, because without it, I can stick to normal e-mail communication.
Customers lose track of things if they only track tickets through their emails.

I miss the following functions:
1. Customer login data instead of a single login link
2. Fields of the ticket (custom fields) visible in the Portal
3. Search and filter in the portal

Has anyone already thought about it, is something planned or possible?

Many greetings

**Comment by freescout-helpdesk** [comment]
Not in our plans, but someone can implement: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by obstschale** [comment]
> 2. Fields of the ticket (custom fields) visible in the Portal

I would love to see this.
