### ISSUE TITLE
Outgoing email not sent (customer_id is null in send_logs)

### ISSUE THREAD

**Issue by stsimb** [freescout-helpdesk/freescout#1431]
Hello,

We were running freescout 1.7.13 at the time of the following incident.

Our agents have complained that in some cases, even though they reply to a conversation, the customer doesn't get an email with their reply.

Here is a screenshot from an agent's reply "Outgoing Emails", where it states that an outgoing email to the customer has been accepted for delivery on Aug 20, 2021 10:36:33 (conversation #322020)).
![outgoing-322020](https://user-images.githubusercontent.com/2001023/133685000-fb9e8f46-6bb0-4a35-b48b-34f93e6c3a80.jpg)

But here is a screenshot from Logs, Outgoing emails, Log records showing the same period.
![log-records](https://user-images.githubusercontent.com/2001023/133685404-22b40ee4-b6e7-4133-ae68-39d0ffa076df.jpg)

Conversation 322020 does not have a customer (customer_id is null in the database), and there's nothing in the mail server logs for this timestamp -- the customer didn't get an email.

On the other hand, there are other conversations to the same customer (#322013, #322041, #322047), that have a customer_id in the database, and an email appears in the mail server's log file, at the exact timestamp that has been recorded in the database, i.e. the expected behaviour.

![db-send-logs](https://user-images.githubusercontent.com/2001023/133686709-2010c511-78ab-48fe-b0fd-0d244fdebbba.jpg)

Is there an explanation for this? Why does it happen?

Thanks,
Sot.

**Comment by freescout-helpdesk** [comment]
We've never seen something like this. Check Logs, maybe there are some other issues causing this.

**Comment by stsimb** [comment]
Logs are clear, no errors in there.

Is there anything else we can do to find why the customer_id was null in this case?

**Comment by freescout-helpdesk** [comment]
Unfortunately we don't have clues what can be the reason.
