### ISSUE TITLE
Can't install via web installer on shared webhost

### ISSUE THREAD

**Issue by MartinHynek** [freescout-helpdesk/freescout#1432]
Hi I'm trying to install freescout on shared webhost, but it seems there is some kind of glitch.. Instalation won't start.. page stucks on redirect loop between /install and /install.php .. ends with ERR_TOO_MANY_REDIRECTS
Anyone encountered that too?

**Comment by pmhtuk** [comment]
Which shared host are you on? We use https://www.kualo.co.uk/ without any issues.

**Comment by MartinHynek** [comment]
Tried two local providers in Czechia, but both have same problem.. so therefore i think it does not have to be hosting related ..

**Comment by freescout-helpdesk** [comment]
You may need to find out by yourself. Most likely the issue is related to Apache configuration.
