### ISSUE TITLE
URL incorrect on Woocommerce order link

### ISSUE THREAD

**Issue by pmhtuk** [freescout-helpdesk/freescout#1433]
Hi - just tried clicking on the 'recent order' link on the side of a customer query and the URL is missing the domain.

![screenshot875](https://user-images.githubusercontent.com/80200406/133879558-732f617b-ccd5-472e-8826-aa230075470f.png)

Couldn't replicate in the demo as the woo system doesn't appear to be setup to show the orders on the side.

**Comment by freescout-helpdesk** [comment]
Try to debug the module.
