### ISSUE TITLE
Global email module - new column

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1435]
Hi,

Would it be possible to display in the global display /global-mailbox/1 a new column which shows to which email account the ticket belongs too ?

ex : 
![image](https://user-images.githubusercontent.com/482210/133980467-0a9d3712-b543-462a-857a-0df4da8a787d.png)

Best regards,

david

**Comment by davask** [comment]
No plan to make the mailbox name as a column too ?

**Comment by freescout-helpdesk** [comment]
Unfortunately no.
