### ISSUE TITLE
Bug at Notes: Picture is not visible after Edit

### ISSUE THREAD

**Issue by mojiro** [freescout-helpdesk/freescout#1436]
Hello,

I would like to report a bug with Notes, where a picture is not visible after Edit.

Steps to reproduce:
1. Open an existing conversation
2. Create a new Note
3. Type something "lorem ipsum", hit enter
4. Upload a picture using the "Picture" icon
5. Click "Add Note"
6. "Edit" that Note, delete the picture, hit "Save"
7. "Edit" again that Note, upload a new picture using the "Picture" icon, hit "Save"
8. The new picture is not visible
9. Editing again the Note, the picture becomes visible in the editor, but never in "view" mode

What happens?
1. On the 1st picture upload, the picture was saved in the Note as real file.
2. On the 2nd picture upload, the picture was saved in the Note as base64 code.
3. For some reason, the base64 code is not visible in the rendered html code.

**Comment by freescout-helpdesk** [comment]
We can't reproduce in FreeScout v1.8.60

![2023-02-14_17-11-56](https://user-images.githubusercontent.com/40499291/218763088-f0c03254-ead8-4f39-b2da-cf3096ee0faf.png)
