### ISSUE TITLE
Bug at Pictures: Cannot delete a picture with "delete" key

### ISSUE THREAD

**Issue by mojiro** [freescout-helpdesk/freescout#1437]
Hello,

I do not know if this is a bug, but it is my common reaction, to hit the "delete" keyboard key when I select a picture that I want to delete.

Workaround:
- Click the "Remove Image" icon from the popup toolbar

**Comment by freescout-helpdesk** [comment]
Do you mean you can delete the image from the reply using Delete keyboard key?

**Comment by mojiro** [comment]
Hi,
I mean that I click a picture that is inside the text editor to select it, then I hit the "delete" keyboard key and nothing happens.

At this point, the toolbar pops up and I can click the "Remove Image" button from it to delete the picture.

**Comment by freescout-helpdesk** [comment]
This is Summernote editor. Images are deleted using Backspace or Delete button
![2021-10-03_20-46-44](https://user-images.githubusercontent.com/40499291/135765466-e88b28ae-adfe-401a-9893-6c6d2e013415.png)

No plans to implement Delete button functionality.
