### ISSUE TITLE
Bug at Pictures: Resize buttons do not work

### ISSUE THREAD

**Issue by mojiro** [freescout-helpdesk/freescout#1438]
Hello,

I would like to report a bug with Picture attachments that happens at least in Firefox (latest).

Steps to reproduce:
1. Open an existing conversation or create a new one
2. Type something "lorem ipsum", hit enter
3. Upload a picture using the "Picture" icon
4. Click the picture and then click 50% or 25% on the popup toolbar
5. The picture resizes at 50% or 25%
6. Click "Send Reply"
7. The picture is shown in full size in the "view" mode of the "comment/reply"
8. If you edit the "comment/reply" then the picture is shown at the correct size, 50% or 25%
9. Saving again, does not affect anything

**Comment by fulldecent** [comment]
How does it look on the customer end?

**Comment by freescout-helpdesk** [comment]
We'll close this as there was no confirmations of this bug.
