### ISSUE TITLE
Text area displayed

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#144]
Anywhere there is a textarea input there is a random floating textarea next to it. For example here in the email signature space. The same happens when replying to tickets.

<img width="872" alt="screenshot 2018-11-21 at 11 01 45" src="https://user-images.githubusercontent.com/1004130/48837322-f364d780-ed7c-11e8-92e2-2de6934e736a.png">

**Comment by freescout-helpdesk** [comment]
It looks like something is wrong with JS or CSS in your installation.
Can you check errors in browser console?

**Comment by BinaryMoon** [comment]
Good point - see screenshot. There's a few files missing. I am using 1.0.6

<img width="949" alt="screenshot 2018-11-21 at 11 05 26" src="https://user-images.githubusercontent.com/1004130/48837491-6f5f1f80-ed7d-11e8-9508-48e1cea0f83d.png">

**Comment by freescout-helpdesk** [comment]
Check full paths to these files in Network tab.

**Comment by BinaryMoon** [comment]
doh - it was a permissions issue. Apologies.
