### ISSUE TITLE
User Module

### ISSUE THREAD

**Issue by ninjoan** [freescout-helpdesk/freescout#1441]
Hello, guys is possible a method to create users to access the system.
Right now the user is attached to an email inside the company

John Done john.done@companydomain.com
Jessica Done jessica.done@companydomain.com

I would like to use just users (johndone1) and not attach any email, yes i know I will lose the option of email notifications buy in my case we don't need that.

**Comment by freescout-helpdesk** [comment]
Unfortunately impossible and no plans to implement.
