### ISSUE TITLE
Call to a member function getFullName() on null

### ISSUE THREAD

**Issue by FuXXz** [freescout-helpdesk/freescout#1444]
Hello,

from one day to the next, I get the following message and can no longer log in.

Call to a member function getFullName() on null (View: /www/html/resources/views/users/partials/web_notifications.blade.php) (View: /www/html/resources/views/users/partials/web_notifications.blade.php) (View: /www/html/resources/views/users/partials/web_notifications.blade.php)

Docker Image 
Freescout 1.15.13
DB 3.9.3

I hope you can help me
Greetings

**Comment by freescout-helpdesk** [comment]
Duplicate https://github.com/freescout-helpdesk/freescout/issues/1410
