### ISSUE TITLE
Why is ticket "id" and "number" different?

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#1449]
Hello,

We're seeing this issue where the ticket id, in the URL, and ticket number do not match up.
Is this wanted behavior?

![image](https://user-images.githubusercontent.com/59649717/134876884-9b42a893-f7b8-4208-ae29-280615361b5b.png)

Apart from doing an advanced search for "number" is there a way of linking back to the actual ticket using the ticket number?

**Comment by arrayown** [comment]
Sorry for taking a wild guess here but I think it may be that one ID is for the actual ticket "thread" whereas the other is for the ticket "reply".

**Comment by freescout-helpdesk** [comment]
> Apart from doing an advanced search for "number" is there a way of linking back to the actual ticket using the ticket number?

Only via the search.
