### ISSUE TITLE
foreach error in logs

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#145]
I have dozens of the following error in my app logs

`Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /.../vendor/symfony/console/Input/ArgvInput.php:265)`

It's appearing roughly once a minute

**Comment by freescout-helpdesk** [comment]
Try to run in SSH console to check error messages:
```
php artisan schedule:run
```

**Comment by BinaryMoon** [comment]
Hmm - it seems to work now, and the errors seem to have stopped.

However there were loads until this morning.

I think the problem might be something to do with the email fetching not being setup. I installed FreeScrout last night, and then got the fetching working this morning. Perhaps it was trying to process the emails, but there was literally nothing to process?

**Comment by freescout-helpdesk** [comment]
Probably. We will check

**Comment by freescout-helpdesk** [comment]
Could not reproduce the issue. Can you check full error message in logs for that day.

**Comment by BinaryMoon** [comment]
The full stacktrace looked like this:

```
Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /vendor/symfony/console/Input/ArgvInput.php:265)
[stacktrace]
#0 /vendor/symfony/console/Input/ArgvInput.php(265): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/protheme/...', 265, Array)
#1 /vendor/symfony/console/Application.php(1007): Symfony\\Component\\Console\\Input\\ArgvInput->getFirstArgument()
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(79): Symfony\\Component\\Console\\Application->getCommandName(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#3 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /artisan(42): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"}
```
