### ISSUE TITLE
API GET Customer with Email or Phone Number

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#1450]
Is there a way I can use API Webhooks Module to GET matching Customers with a supplied Email Address or Phone Number?  If so, how should I structure the query?

Thanks for your help, Luke.

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible for now. Maybe someone can implement: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
