### ISSUE TITLE
Noreply Module - Custom Domains

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#1451]
I am hoping to use Noreply Module to warn about users sending email to certain domains - Can this module be extended so we can use wildcard domain names also (to warn about replying to internal email addresses or other domain names where the email address can vary greatly)

Cheers, Luke.

**Comment by luketrip** [comment]
I can see here https://github.com/freescout-helpdesk/freescout/issues/1339#issuecomment-885639957 it appears the warning would not show on a ticket already created by a Noreply email.

When emails enter our general enquiry mailbox from automated means (Ie. A webform submission for a lead or enquiry) - It usually comes from a Noreply email or a Domain Name we shouldn't reply to. 

We greatly need the ability to have the warning show when staff try and reply to this conversation, so they can check and update the customer profile with real email address, usually housed in the enquiry web form data that was sent as part of the original email.

Even if on the page load of the ticket, it checks the ticket email address/domain, and shows the warning bar at the top near the Reply button so a visible prompt is present.

Would you consider making this a option for us as well?

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans, maybe someone can implement it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
