### ISSUE TITLE
Cron job via http URL request

### ISSUE THREAD

**Issue by MartinHynek** [freescout-helpdesk/freescout#1452]
Hello, from what i saw, it seems that there is not way how to launch cron job via http url request, only via direct crontab .. Problem is that i can't find any shared webhosting, which has this allowed.. So therefore i think it cant be said, that Freescout is possible to run on shared hosting.. At least not in our country.. I've asked top hosting providers and none has option to run crontab like syntax on cronjobs.. Only crons possible are via URL request of some script..

Is there a way how to bypass this problem and run cron via http request?

**Comment by freescout-helpdesk** [comment]
There was a discussion of this already. We'll try to find it.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/issues/1009#issuecomment-763865908

**Comment by freescout-helpdesk** [comment]
We can try to implement it, but there may be some side-effects.

**Comment by MartinHynek** [comment]
Thanks for answer.. I think it could help people to expand usage of app, 'cos currently shared webhostings may not support usage of exec functions ('cos of security) and there is no way how to use cron jobs in crontab format .. just only in HTTP request via URL..

**Comment by freescout-helpdesk** [comment]
You'll find web cron URL in Manage > System > Cron Commands
