### ISSUE TITLE
Hire Developer

### ISSUE THREAD

**Issue by ahmadhassan83** [freescout-helpdesk/freescout#1453]
Hello all,
   greetings,

I want to use it in my business for a year.
I tried the demo system in this [link](https://demo.freescout.net/), and I want some modifications on screen for the open and close tickets, and simple modifications in the reports are displayed.

So I need cooperate with someone for develop the required modifications.

Also I need upload the ticketing system on the cloud with below specifications to install ticketing system on it for 1 year: 
•	CPU 32Cores
•	256 GB RAM
•	2x 6TB Storage (RAID10)
•	2 x Public Ips
•	SSL Certificate
•	Backup Space 6TB
•	Firewall VM

Any suggest for that.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
