### ISSUE TITLE
Installing errors on missing package "python-certbot-nginx"

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1454]
Im installing on a clean ubuntu 20 distribution using the install script.

It runs a long way and ends with:

        Reading package lists... Done
        E: The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file.
        N: Updating from such a repository can't be done securely, and is therefore disabled by default.
        N: See apt-secure(8) manpage for repository creation and user configuration details.
        Reading package lists... Done
        Building dependency tree
        Reading state information... Done
        Package python-certbot-nginx is not available, but is referred to by another package.
        This may mean that the package is missing, has been obsoleted, or
        is only available from another source
        However the following packages replace it:
          python3-certbot-nginx
        
        E: Package 'python-certbot-nginx' has no installation candidate
        sudo: certbot: command not found
        Adding certbot renewal command to root's crontab...
        no crontab for root
        Configuring cron task for www-data...
        no crontab for www-data
        
        To complete installation please open in your browser help desk URL and follow instructions.
        You can skip setting up a cron task, as it has already been done for you.

Is everything ok according to the last sentence: "You can skip setting up a cron task, as it has already been done for you." ?
or should I install "python3-certbot-nginx" ? If so, how?

**Comment by jesperordrup** [comment]
I installed python3 

    sudo apt-get install python3-certbot-nginx

The solution doesnt respond to http or https requests on the configured hostname. I've tried restarting. 

Any clues?

**Comment by jesperordrup** [comment]
/var/www/html/storage/logs/web-server.log is empty.

/var/www/html/storage/logs/laravel-2021-09-30.log mentions this error.

    [2021-09-30 14:43:02] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 
    'forge'@'localhost' (using password: NO) (SQL: select * from `options` where (`name` = fetch_emails_last_run) limit 1) 
    {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 
    'forge'@'localhost' (using password: NO) (SQL: select * from `options` where (`name` = fetch_emails_last_run) limit 1) at 
    /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, 
   Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using 
   password: NO) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 
   1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) at 
   /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)

I installed using "Interactive installation bash-script (Ubuntu)" as described here: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#interactive-installation-bash-script-ubuntu

I seached the "manual install" on ubuntu and found this:

![image](https://user-images.githubusercontent.com/3120151/135458031-108a2b09-c7e4-456f-873f-e9503d0ff819.png)

Im trying to figure out if this is something I can fix but need a hint here?

**Comment by jesperordrup** [comment]
Had to drop the script and do it manually to get it to work. So not solved but managed a workaround

**Comment by freescout-helpdesk** [comment]
Good to know.
