### ISSUE TITLE
Disable / Hide Mailboxes for Admins

### ISSUE THREAD

**Issue by luckycloud-GmbH** [freescout-helpdesk/freescout#1456]
Hello,

is it possible to make certain mailboxes invisible even for admins?
I know that you can probably change this with server access at the latest, but then this is at least a much bigger hurdle than directly via the GUI.

![image](https://user-images.githubusercontent.com/57234522/135697602-09991d74-5414-4042-905b-68c9cbd7aa03.png)

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible and no plans to implement.
