### ISSUE TITLE
Telegram module

### ISSUE THREAD

**Issue by bolgovrussia** [freescout-helpdesk/freescout#1457]
After a ticket created via Telegram is closed, a new ticket is opened with the same number.

Is it possible to create a ticket with a new number after the old ticket is closed?

**Comment by freescout-helpdesk** [comment]
> a new ticket is opened with the same number

What do you mean? Could you please send video or screenshots.

**Comment by bolgovrussia** [comment]
> > a new ticket is opened with the same number
> 
> What do you mean? Could you please send video or screenshots.

Hi!

1. I create a ticket via telegram
2. the ticket gets number #1
3. I close this ticket
4. I create a new ticket via telegram
5. the new ticket gets number #1 again

Waiting:
1. I create a ticket via telegram
2. ticket gets number #1
3. I close this ticket
4. I create a new ticket via telegram
5. new ticket gets number #2

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible. All messages received from some Telegram user always go to the same conversation in FreeScout.
