### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#1458]
If you need a kanban board feature, please describe your requirements below.

**Comment by pocketfulofrage** [comment]
OMG YES PLEASE!

Swimlanes, drag and drop, subcards, ability to open a ticket/reply to a ticket from a card, add cards (without creating a ticket, or a private ticket), multiple inboxes on one board, automation based on which column a ticket is moved to.

I'll add more as I think of them!  :)

**Comment by freescout-helpdesk** [comment]
More here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/288928

**Comment by obstschale** [comment]
- Drag'n'Drop Cards (aka Conversations) between Columns
- Columns = Labels or Assignee
- Select Inboxes, i.e. one kanban board can display converstations from many inboxes

**Comment by qsvch** [comment]
A great idea, thank you! Everything needed for us was already mentioned …

**Comment by mywebhero** [comment]
I assume this will be a paid module right?

**Comment by freescout-helpdesk** [comment]
Kanban Module will have some features & limitations:
1) It will be possible to add cards connected to conversations from different mailboxes to one board.
2) Each board will be connected to some chosen mailbox and users from this mailbox will have access to this board.
3) Cards not connected to conversations will appear in the chosen mailbox as phone conversations and will be visible to all mailbox's users.

**Comment by caladanbr00d** [comment]
Is it possible to somehow integrate kanboard (the open source kanban board software) into freescout? That is a quite mature application.

**Comment by freescout-helpdesk** [comment]
Sure. Via [API](https://api-docs.freescout.net/)

**Comment by caladanbr00d** [comment]
Maybe that would be a worthwhile idea to pursue? The Idea then would be to be able to generate a card from a conversation, have the ticket number asigned to the title (and write a name) and have the emails get appended to the conversation as comments or into description. I am actually using kanboard and freescout together like this. I just do it manually now. 


I have a quick question on an unrelated issue: on the 2FA module page you recommend two apps. But I can use any app that supports TOTP standard, right?

**Comment by freescout-helpdesk** [comment]
Module for testing: https://freescout.net/module/kanban/
