### ISSUE TITLE
Chat user name (visitor)

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1459]
Is it possible to set the chat visitor username and email in the script that loads the chat window? 

Usecase:

We load the chat window on a page behind a login so we know the user.

**Comment by johanoloflindberg** [comment]
I am looking for the same function :) @jesperordrup @freescout-helpdesk 👌🏻🚀

**Comment by freescout-helpdesk** [comment]
In Chat Module v1.0.8 the following parameters can be passed: visitor_name, visitor_email and visitor_phone:

![2021-10-13_20-50-02](https://user-images.githubusercontent.com/40499291/137186458-fc05172a-faec-4496-8f80-8d539f63700c.png)
