### ISSUE TITLE
Bug: Chat messages agent names are wrong

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1460]
Steps

Visitor writes a message.
First agent/user answers. 
In chat you see the agents reply and name
Another agent joins and answer. 
In chat you see the second agents answer and the first agents name.

The expected behaviour is that the name should be the agent who answered.

Running on latest build.

**Comment by freescout-helpdesk** [comment]
Fixed in Chat Module v1.0.7
