### ISSUE TITLE
landing-server.log  20GB Filesize

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#1462]
Hi,

would be good if there is a rotate or truncate for logs. I just figured out as the VM reported 0 byte left that the log file:
`/storage/logs/landing-server.log` grown >20GB. 

Inbox is actually running fine and not reporting any issue but I found the log spammed with PHP Notices, digging into it later today to see what could be the actual issue. For now I turn off PHP Notice Error Reporting.

```
2021/10/04 12:05:05 [error] 969#969: *10123 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: content in /var/www/landing/htdocs/index.php on line 14" while reading upstream, client: 10.xxx.xxx.xxx, server: xxx.xxx, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "xxx.xxx"
```

Ty

**Comment by freescout-helpdesk** [comment]
FreeScout does not have `content` variable on line 14 in index.php: https://github.com/freescout-helpdesk/freescout/blob/dist/public/index.php#L14

**Comment by solariz** [comment]
ok weird, you are absolutely right. 

For any reason the notice still appears in the freescout landing-server.log. How ever, would be great to have some kind of log monitoring / truncating or at least a hint that the Admin of freescout should setup a proper logrotate.

Thanks!

**Comment by freescout-helpdesk** [comment]
FreeScout rotates it's logs. `landing-server.log` does not belong to FreeScout.

**Comment by solariz** [comment]
hmm, I close the ticket. Need to find the reason where this coming from in the freescout log dir. I guessed it was laravel but short look seems like this isn't the cause.

Thank you.
