### ISSUE TITLE
module reports - show chats as chats, not emails

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1465]
The reporting sees chats as emails. Can this be separated?

![image](https://user-images.githubusercontent.com/3120151/135993157-6ee6ec36-946e-4a4e-98cc-e82468eaa11c.png)

usecase
- very interested in knowing how busy is chat

**Comment by jesperordrup** [comment]
A workaround for those interested:

- buy workflow
- buy tags
- setup automation rule to mark chats with chat tag
- filter on the tag in reports

![image](https://user-images.githubusercontent.com/3120151/135993761-c6684f86-96ce-43c0-a43e-51edb85a5da0.png)

**Comment by freescout-helpdesk** [comment]
Ability to filter Chat conversations added in Reports Module v1.0.9

**Comment by jesperordrup** [comment]
Thanks - also my first experience with module upgrade which went very smooth. Thx
