### ISSUE TITLE
Website tweak

### ISSUE THREAD

**Issue by Zodiac1978** [freescout-helpdesk/freescout#1467]
Not sure if this is the best place, but I have an optimization hint for the website.

Adding font smooting to the icons in the menu would help them to look sharper:

```
.main-navigation a[href*="github.com"]::before, .widget .menu li a[href*="github.com"]::before {
  -webkit-font-smoothing: antialiased;  
  -moz-osx-font-smoothing: grayscale;
}
.main-navigation .edd-cart-quantity::before {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.main-navigation ul > li.menu-item-has-children > a::after {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

Before:
![Bildschirmfoto 2021-10-05 um 16 15 36](https://user-images.githubusercontent.com/870475/136044171-f5239662-a5e7-4558-8f82-2639a138f6df.png)

After:
![Bildschirmfoto 2021-10-05 um 16 16 11](https://user-images.githubusercontent.com/870475/136044163-6f679e90-3e37-46b8-860d-ebac3626497f.png)

**Comment by freescout-helpdesk** [comment]
Thanks
