### ISSUE TITLE
Workflow automation on deleted content?

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1469]
If a conversation is deleted then workflow automation does not react to new /reply/ Moved

Do workflow react on any other when conversation is deleted?

usecase:

I wanted to create a workaround for deleted content that had a tag of "chat" which received an update from visitor and use action "move to inbox" and "tag as undeleted"

**Comment by jesperordrup** [comment]
> but Chat is not a tag

Im aware. I added a workflow to add tag "chat" to all chat conversations

But - i cant seem to undelete a conversation when it receives a new message. Could it be because the chat integration doesnt update the conversation via email but .. somehow else?

**Comment by freescout-helpdesk** [comment]
Screenshots of Actions and Conditions tabs.
