### ISSUE TITLE
Chat - option to force new ticket if conversation is closed

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1479]
What happens today:

You have a chat based conversation and close the conversation.
If visitor writes another chat message it becomes active under same conversation and same conversation number. 

As long as the visitor uses the same browser - the same conversation is reused.

It quickly becomes a long thead covering several topics If you have many chat sessions covering different topics/situations over a lengthy period it becomes increasingly difficult to see how many issues we have solved.

Suggestion: A "Close" option that forces a new ticket. Maybe only for chat, maybe for both. Maybe an option on mailbox/chat.

This solves:
  lengthy chat conversations
  conversation numbers
  new conversations are unassigned.

**Comment by Stunt0265** [comment]
I see this same issue.  No way to clear the existing chat.  This will not be fixed?
