### ISSUE TITLE
Implement API

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#148]
API should be a part of the core app.

- FreeScout API must be equal to [HelpScout's API](https://developer.helpscout.com/mailbox-api/overview/authentication/). 
- No burst write limits.
- `Enable API` option in Settings.
- Instead of oAuth authentication use HTTP Basic Authentication (https://developer.helpscout.com/help-desk-api/). API key can also be passed via `X-Freescout-API-Key` HTTP header.

**Comment by caloyregs** [comment]
highly agree. in this way, it can be used on any app platform and become very useful to any organizations.

**Comment by foliovision** [comment]
Real world API use: posting forum tickets in a structured way. I.e. new posts on an existing topic will add to the existing topic like a thread.

The advantage of enhance forum management like this are several:

1. offers the team the ability to talk among themselves about a forum topic privately
2. many forums offer private comments among admins but there's always a risk that something will go wrong and those private posts will be public
3. the ability to assign posts to one another
4. the ability to use very lightweight forums by moving the management into an alternate channel
5. consolidating support channels in the help desk, improving workflow

API is a big project. I am happy to offer $300+ support for the creation of an API which will allow us to pipe our forum posts into Freescout in a structured way. My support is only part of the support the Freescout will need to implement a robust API. **Anyone else who would like to support the building of an API for Freescout, this would be a good place to standup and be counted.**

There's no point to building a weak or fragile API so enough time and resources have to be put aside before starting. I'd recommend starting from an existing API. Our lead programmer will drop by with more technical notes on what is required from a helpdesk API to allow it to replace forum management.

**Comment by fvmartin** [comment]
Here are the Teamwork Desk API endpoints which we use for our forums:

* POST /desk/v1/customers/search.json - searching by email address, used to attach a ticket to existing customers in Teamwork Desk
* POST /desk/v1/customers.json - used to create Teamwork Desk customers with email, first and last name, storing the customer ID in our forum database for future use
* POST /desk/v1/tickets/{id}/followers.json - used to add ticket followers
* DELETE /desk/v1/tickets/{id}/followers.json?userId={Teamwork Desk user ID} - used toremove ticket followers
* POST /desk/v1/tickets.json - adding new tickets using message body, customer ID or customer email, first and last name

**Comment by foliovision** [comment]
I've had a look at the Helpscout API. That's a tall mountain to climb.

I would suggest making the API a paid module and not an inexpensive one. It would do fine in the $20 to $50 category. Anyone who needs an API for his or her help desk can afford to contribute to seeing it built properly.

**Comment by vrad123** [comment]
Hi - just wanted to check if there's any progress on this? We'd be happy to contribute $ toward this goal. Feel like it's the only thing missing.

**Comment by freescout-helpdesk** [comment]
FreeScout Team may start implementing this in 1-2 years. If anyone is willing to implement it earlier, please let us know.

**Comment by Mte90** [comment]
Well this is the only reason why I cannot migrate to freescout because there are no endpoints so I cannot integrate with other tools/services.

**Comment by Skywrath-Mage** [comment]
Indeed, it is becoming increasingly important to have an API, or at least a Webhook system.
@foliovision we can contribute to development economically or with hours of development if you want to develop a module.

**Comment by freescout-helpdesk** [comment]
API should be a part of the core app.

**Comment by Mte90** [comment]
Have this webhook system will be very appreciated as it is impossible to integrate in other solutions as it is now...

**Comment by sdwru** [comment]
+1 for API so I can create Zabbix webhook.

**Comment by Mte90** [comment]
They released few days ago https://freescout.net/module/api-webhooks/ a module for webhooks

**Comment by freescout-helpdesk** [comment]
Which API methods has more priority for you: get (conversation, customer, etc) or create (conversation, customer, etc)?

**Comment by Mte90** [comment]
I think to create customers so it is possible to integrate with other tools.

**Comment by Jiwoks** [comment]
+1 For customer creation for the same reason

**Comment by freescout-helpdesk** [comment]
The following API methods have been implemented: Get Conversation, Create Customer, Get Customer. For additional methods please create new issues.

API Documentation: https://api-docs.freescout.net
