### ISSUE TITLE
Chat - add meta data 

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1480]
We would like to know which IP adresse the visitor comes from.

It would be really useful to know from which page / URI is asking to get some context. In the simplest form it could be added to the first message in the conversation. 

In smart form :-) add the url to the next message if its changed from last (to support the user browsing multiple pages while continuing conversation) or go all the way and live update a panel with current url.

Any other tech info about the browser would be of value too.

**Comment by freescout-helpdesk** [comment]
> Further to this, I'd like to give the widget some data about the logged in user - our users are assuming we know who they are, and we have no way of identifying them. Ideally I could provide name, email, phone, and perhaps a userId

https://github.com/freescout-helpdesk/freescout/issues/1459#issuecomment-942568808
