### ISSUE TITLE
Specific E-Mail breaks Freescout

### ISSUE THREAD

**Issue by psuet** [freescout-helpdesk/freescout#1484]
Hi,

we have recieved an email that broke Freescout:

`Undefined offset: 0 (View: /var/www/html/resources/views/conversations/view.blade.php) {"userId":2,"email":"psuet@[anony]","exception":"[object] (ErrorException(code: 0): Undefined offset: 0 (View: /var/www/html/resources/views/conversations/view.blade.php) at /var/www/html/storage/framework/views/02071989e0d311c1da5a34bc4a6438950913cd4e.php:92, ErrorException(code: 0): Undefined offset: 0 at /var/www/html/storage/framework/views/02071989e0d311c1da5a34bc4a6438950913cd4e.php:92)`

Only this specific [spam] mail causes the problem:

select * FROM conversations where number=5965: See [here](https://zerobin.net/?39707420be0b197e#K78z4wywMUPy+mrm6J0cf+ifXDPtFj2MMdqnIVc25n4=)
select * FROM threads WHERE conversation_id=6302: See [here](https://zerobin.net/?38fe27272fb3476e#9w7Xdgyu7JJj6S4Guo76FsK81/S8WoJ36QS6jt4MtqU=)

(anonymized)

**Comment by freescout-helpdesk** [comment]
It looks like you need to debug it yourself.
