### ISSUE TITLE
Adjust default notification settings via .env

### ISSUE THREAD

**Issue by ninjoan** [freescout-helpdesk/freescout#1487]
Hi guys is possible to hard code an option to disable the check mark in the email notification after you create a new user in the system?

**Comment by freescout-helpdesk** [comment]
What kind of check mark?

**Comment by ninjoan** [comment]
Hi the notifications EMAIL that appears in **_domain.com/users/notifications/user-id_** I would like to disable for all users

**Comment by freescout-helpdesk** [comment]
Default notification settings for new users can be configured in Manage > Alerts
