### ISSUE TITLE
Bug in android app : links to files doesnt work (all external links opens in app)

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1488]
The android app seems to open every link in the app inself. This is ofcourse great for all freescount internal links, but 

1) doesnt work well for external links, as the internal browser doesnt work as well as the chosen default browser as you need to relogin everywhere. Thats ok but there are sometimes things that doesnt work at all, such as login flows with popups (popups doesnt seem to show).

2) doesnt work with files. When I open a conversation and try to open an attached pdf, it cant open.

I suggest that all files open with browsers default apps and at least make it optional to open external links in default apps.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#there-are-few-issues-in-mobile-apps
