### ISSUE TITLE
Telegram Notifications module does not work on PHP 8.0

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#1492]
Telegram Notifications module can not send any messages on PHP 8.0.

Error:
` During class fetch: Uncaught ErrorException: The magic method Telegram\Bot\Traits\Singleton::__wakeup() must have public visibility`

According to google, Singleton does not fully support PHP 8.0 for now. Is there any workaround?

UPD: It does not work on PHP 7.4 too.

**Comment by freescout-helpdesk** [comment]
We'll check it in a few days.
