### ISSUE TITLE
Customer changes automatically

### ISSUE THREAD

**Issue by tillmon** [freescout-helpdesk/freescout#1504]
If a reply to a conversation is sent with a CC recipient and the CC recipient answers to the email, the customer is changed to the CC recipient.

**Comment by Wouter0100** [comment]
@freescout-helpdesk this was done on purpose [here](https://github.com/freescout-helpdesk/freescout/blob/97fb5678bcfbe02d9c1970c67cc2be5dea7464e4/app/Console/Commands/FetchEmails.php#L667-L677), it seems. Do you know why that's the case? Could we safely remove that code or did I mis-interpreted this code?

If we can remove it, I'm more then happy to open a PR for it.

**Comment by freescout-helpdesk** [comment]
If reply comes from another customer and FreeScout does not change the customer the reply will be shown as coming from the original customer (not the real sender) and cause confusion.
