### ISSUE TITLE
In reference to PR #1390, still struggling

### ISSUE THREAD

**Issue by jensolsson** [freescout-helpdesk/freescout#1507]
Hi

I am still struggling to make a plugin to match issue IDs in the subject line, however I cannot move forward.
I start by copying the TicketNumber plugin just to have it as a baseline. I change the name of it and all references that needs to be changed. I rename its directory. But it refuses to load, I really double checked everyhing and read thru all rows of code in all files but cannot understand why it does not load.

Can someone give me any pointers on how to debug loading of plugins?

Kind regards
Jens

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
