### ISSUE TITLE
Allow workflows to run more than once 

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#1513]
It would be extremely useful if we could the workflow could be marked as "allow reruns on same conversation"

Example of use
        
        workflow: 
           send mail on close
        filter
           status is "closed" 
        action
           "send email to customer "We have closed the issue. Thanks for reaching out. We love you, customer"

Today if the customer reopens a case then the workflow is dead

**Comment by jesperordrup** [comment]
Does it solve the logic?

**Comment by freescout-helpdesk** [comment]
Feel free to implement: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by jesperordrup** [comment]
Sorry, not familiar with this techstack, but I'm willing to sponsor some dev

**Comment by tn-zfrank** [comment]
Without looking into the source for the module to much, I'm interested in knowing how a workflow knows that it has been run on the ticket already.
