### ISSUE TITLE
Insert images (ctr-v) not work in Chrome Linux.

### ISSUE THREAD

**Issue by EliasPawlow** [freescout-helpdesk/freescout#1522]
Good afternoon.
The picture is inserted by ctr-v from clibbord in the linux system, the chrome browser is displayed in the editor, but is not sent to the client.
Also, the inserted picture is not saved in the draft.
In firefox linux, everything works correctly.
Please repaire it.

**Comment by EliasPawlow** [comment]
Everything works fine in chrome windows x64, but how does this relate to my original question?

**Comment by freescout-helpdesk** [comment]
"but is not sent to the client" - what does it mean? What do you see when clicking "Code View" button in the editor?
