### ISSUE TITLE
can not forward a mail as a note to existing conversation

### ISSUE THREAD

**Issue by phanousk** [freescout-helpdesk/freescout#1525]
One of our customers replied my personal mail address instead of the mailbox. I have tried to forward that mail to existing conversation as a note (I have Email Commands module installed). I added the [#number] to mail subject, put @note on the first line of forwaded mail and sent it. Freescout fetched this mail (I've tried to debug it through Tools->Fetch Mail) but left it untouched. It's nowhere visible in the mailbox and the conversation shows only the previous messages. Is this a bug or my misunderstanding of functionality?

**Comment by freescout-helpdesk** [comment]
Commands are functioning only when replying to the email notification. They do not work when forwarding emails, etc.

**Comment by phanousk** [comment]
OK, understood. So why in this case didn't arise a new ticket?

**Comment by freescout-helpdesk** [comment]
This need to be checked.

**Comment by phanousk** [comment]
> This need to be checked.

OK, so the steps to reproduce the issue are these:
1) customer writes to the personal address
2) reply from personal address with Cc to shared mailbox (Freescout)
3) reply from customer to personal address
4) forward the customer reply from (3) to shared mailbox

**Comment by freescout-helpdesk** [comment]
Fixed in Email Commands Module v1.0.5
