### ISSUE TITLE
Custom module image help.

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#1526]
Hi there,

I've looked through the source code but don't seem to find where I can filter in an image/icon for a custom module I am building?

I'd like to upload my own icon/logo to the Modules page where my module is activated and registered.

See below for reference:
![Screen Shot 2021-11-01 at 12 16 32](https://user-images.githubusercontent.com/12629136/139656655-58043eff-83b0-4b10-8c3e-8ae510b6ef56.png)

**Comment by freescout-helpdesk** [comment]
This can be implemented by adding a code to Nwidart package: https://github.com/freescout-helpdesk/freescout/tree/dist/overrides/Nwidart/Modules

**Comment by andrewlimaza** [comment]
I've got a PR I'll be submitting that will allow people to add 'img' to modules.json (which is easier) and hopefully you'll consider it :)
