### ISSUE TITLE
using custom fields as saved reply variables

### ISSUE THREAD

**Issue by hisam88** [freescout-helpdesk/freescout#1529]
Both the customer CRM and the custom fields allow for a unique level of customization. Having looked through both, and the saved replies, it does not look like I can easily add these as variables when using a saved reply. 

Is this something that is easily customizable if I ask a developer to work on it? Or is it better to make this a feature request?

**Comment by freescout-helpdesk** [comment]
Feel free to implement: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
