### ISSUE TITLE
Module 'Saved Replies' activation

### ISSUE THREAD

**Issue by Junker** [freescout-helpdesk/freescout#153]
After press "Activate" button on "Saved Replies" module cannot use freescout anymore, on any url i get error:
"File '/srv/http/freescout/public/modules/savedreplies/js/laroute.js' does not exist (View: /srv/http/freescout/resources/views/layouts/app.blade.php) (View: /srv/http/freescout/resources/views/layouts/app.blade.php)"

1. in module zip file i see folder "SavedReplies", but in error "savedreplies"...
2. laroute.js file not in "js/laroute.js" but in "Public/js/laroute.js"

**Comment by freescout-helpdesk** [comment]
Do you have a symlink `public/modules/savedreplies >> Modules/SavedReplies/Public` ?
If no, just create it and check your file permissions: System > Status (in FreeScout 1.0.7)

**Comment by Junker** [comment]
thanks, it helped.. 
in "System > Status" everything good, no problems there..

**Comment by freescout-helpdesk** [comment]
Added Check public/modules folder permissions https://github.com/freescout-helpdesk/freescout/commit/57aec4e132c5f0f373dfea97abb651e0381f900a
