### ISSUE TITLE
Office 365 is not consistently connecting, sending & fetching is not working

### ISSUE THREAD

**Issue by hisam88** [freescout-helpdesk/freescout#1532]
I have not been able to get Office365 working with Freescout. 

I have extensively followed #619 - reset passwords, added a connector, removed the connector, and things still are not working properly. 

**IMAP issues:** 

> imap_open(): Couldn't open stream {outlook.office365.com:993/imap/tls}. [CLOSED] IMAP connection broken (server response)

However, when I look into the Azure Active Directory user sign-in logs, there is no indication of an attempted sign-in. 

**SMTP issues:** 

The Send Test To option in the Connection Settings will successfully send an email. However, when sending an email from the mailbox, the message is never received. 

Things that I've already looked into: 

- all necessary ports are open from the server 
- Microsoft security defaults are disabled
- Exchange connector was added with the shared hosts IP

**Comment by freescout-helpdesk** [comment]
It looks like we can't help you here. Maybe connection issues.
