### ISSUE TITLE
Pop3 without encryption

### ISSUE THREAD

**Issue by bilel** [freescout-helpdesk/freescout#1535]
Hello :)

I'm facing an issue with Pop3 settings on Orange mailboxes. They use no encryption and when I set it to no None it shows the following error :
- **imap_open(): Couldn't open stream {pop.orange-business.com:110/pop3/novalidate-cert}. TLS/SSL failure for pop.orange-business.com: SSL negotiation failed**
Where could we update it? is it relied to Webklex/laravel-imap module ?

I also suggest another feature allowing us to define mailboxes settings profile (model). We usually set up different mailboxes sharing the same server settings. That way we test it only for one mailbox and assign it to any similar one.

Thank you,
Bilel

**Comment by freescout-helpdesk** [comment]
Yes. You need to dig into Webklex/laravel-imap package.

**Comment by bilel** [comment]
Thank you. I already figured it out by editing Client.php :

```
		if($this->host=='pop.orange-business.com'){
			$address='{pop.orange-business.com:110/pop3/notls}';
		} else { $address = "{".$this->host.":".$this->port."/".($this->protocol ? $this->protocol : 'imap'); ....

```

Server log doesn't show errors while using the Fetch email tool like before. But when I test the connection through the mailbox settings I get the following warning :

- **SECURITY PROBLEM: insecure server advertised AUTH=PLAIN**

I know they have a weird server but I have to use this mailbox.
