### ISSUE TITLE
Two mails sent when Customer is also User

### ISSUE THREAD

**Issue by phanousk** [freescout-helpdesk/freescout#1538]
Is there any possibility to remove mailing to Customer, when he is a User of the conversation at the same time? IE: how should the team of helpdesk people cooperate on something that wants one of them from the others? Having a second mailbox for this is quite inconvenient. Also it would be fine when "Customer == one of Users" not to assign the ticket automatically to the first User who replies it.

Explanation: Now we have three people in user support (one shared mailbox for user1, user2, user3) and user1 raises an issue and needs some cooperation from the two other users. And he gets two mails on every transaction, one as a Customer (To), the second as a User. And the conversation is assgned to the first replying user thus removing the third user from conversation because of notification setting.

Thank you, Petr

**Comment by freescout-helpdesk** [comment]
This can be implemented via a custom module. Not needed in the core. See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
