### ISSUE TITLE
Module deactivation

### ISSUE THREAD

**Issue by Junker** [freescout-helpdesk/freescout#154]
when i press "deactivate" on "Saved Replies" module, i got message - '"Saved Replies" module successfully DEactivated!' but button "deactivate" still there, can press it many times and always same message. Seems module not fully deactivated

**Comment by freescout-helpdesk** [comment]
Any messages in logs?

**Comment by Junker** [comment]
didn't see anything wrong in log files. But i opened modules page later and it was deactivated already, maybe cache...

**Comment by Junker** [comment]
will check later again

**Comment by dipakcg** [comment]
Yes, experienced the same and clearing the cache fixed the issue.

**Comment by freescout-helpdesk** [comment]
Can you send your system parameters: web server, PHP, MySQL.

**Comment by dipakcg** [comment]
PHP Version: 7.1.21
Web Server: Apache
MySQL Version: 14.14 Distrib 5.5.61

I hope this helps. Let me know if you require any specific info.

**Comment by freescout-helpdesk** [comment]
Is this issue still present?

**Comment by zackkatz** [comment]
This happens to me sometimes when my permissions aren't set properly. Running `chown -R www-data:www-data /var/www/html/` fixes it for me.
