### ISSUE TITLE
Auto Reply not sent out

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1540]
I configured auto reply in the mailbox configuration, it works but not always work. I don't see attempts on outbound alert in email logs either.

May I know what is the exact condition to trigger it? What else do I have to configure other than "Enable Auto Reply"

Thanks

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/blob/dist/app/Listeners/SendAutoReply.php
