### ISSUE TITLE
Wokflows: how to prioritize actions

### ISSUE THREAD

**Issue by phanousk** [freescout-helpdesk/freescout#1541]
I have an easy Workflow "when customer e-mail contains example.com, assign it to certain user" which certain e-mails assigns to some of our Users. And although all of the Users have unset mail notification options "A conversation is assigned to someone else" and also "To a conversation owned by someone else" they get the mail because of turned on setting "There is a new conversation". AFAIK I can not prioritize a workflow action before default system actions.

Well this is maybe a complex task and leads to some prioritization of all transactions which is not so easy. Or any hint how to squelch mails to certain users in a Workflow? :)

**Comment by freescout-helpdesk** [comment]
We can suggest any solution for now. Only via adjusting the module.
