### ISSUE TITLE
[question] extended-editor, adding table editing & formatting

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1542]
https://freescout.net/module/extended-editor/

Hi Support
I would like to know if you would be adding support for TABLE FORMATTING in the near future?

M.

**Comment by freescout-helpdesk** [comment]
We'll check. It should be possible.

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
Thank you, if you could let us know soonest as we have a few installations where this module will be added. Appreciated.

**Comment by freescout-helpdesk** [comment]
Tables have been added in Extended Editor Module v1.0.1

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thank you...

**Comment by raramuridesign** [comment]
@freescout-helpdesk I just wanted to ask a few things
1. is it possible to add into the editor ability to add colours to fonts and background to text?
2. When will you release the new version, as it has not shown as an update yet?

**Comment by freescout-helpdesk** [comment]
Released now. Also may be possible, we'll check.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks, this sounds great.
We would really love to see the colours working... Table looks great ;-)

**Comment by freescout-helpdesk** [comment]
Font Color button added in Extended Editor Module v1.0.2

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thank you - much appreciated.
Have an excellent week.
