### ISSUE TITLE
Widgets locale

### ISSUE THREAD

**Issue by josipsain** [freescout-helpdesk/freescout#1543]
Is there an option to send locale to widgets for multilanguage apps?

**Comment by freescout-helpdesk** [comment]
Do you mean the option to set locale for Knowledge Base widget?

**Comment by josipsain** [comment]
Yes.

**Comment by freescout-helpdesk** [comment]
It should appear with time.

**Comment by freescout-helpdesk** [comment]
All widgets now have Language option.
