### ISSUE TITLE
Telegram Notifications Modul cant save the API token

### ISSUE THREAD

**Issue by Kampfwurst** [freescout-helpdesk/freescout#1544]
Hi,
I cant save the Bot API Token for the Telegram Notifications Modul. It shows that it saved it (green fild on top) but then the Field Bot API Token is empty. I also cant change any Events. In the log there is nothing. 

I tried to disable the module and cleared the cache. I also changed the browser chrome.
under system there it shows PHP 7.2.34

Whats the solution? The freescout is hostet on interserver.net

**Comment by freescout-helpdesk** [comment]
Check App Logs. Most likely https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by Kampfwurst** [comment]
I get this message when i activate the modul

Cache cleared successfully.
Nothing to migrate.
Error occured creating [/home/yyy/xxxxx/public/modules/telegram] symlink: symlink(): No such file or directory
The [/home/yyy/xxxxx/public/modules/telegram] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js

**Comment by freescout-helpdesk** [comment]
Is everything OK in Manage > System > Permissions?

**Comment by Kampfwurst** [comment]
yes everything is fine there. 
https://ibb.co/mNLGkZ3

**Comment by freescout-helpdesk** [comment]
Do you have `TELEGRAM_BOT_TOKEN=` in your /.env file?

**Comment by Kampfwurst** [comment]
yes its written there.

**Comment by freescout-helpdesk** [comment]
Try to manually remove all cache files from `/storage/framework/cache/data` and `/bootstrap/cache`

**Comment by Kampfwurst** [comment]
i have removed all the files without success. Still the same problem.

**Comment by freescout-helpdesk** [comment]
Does `TELEGRAM_BOT_TOKEN` has any value in .env file?

**Comment by Kampfwurst** [comment]
yes its the correct value inside

**Comment by freescout-helpdesk** [comment]
If you want you can send server and admin access to support@freescout.net - we will take a look.

**Comment by freescout-helpdesk** [comment]
Fixed in Telegram Notifications Module v1.0.5
