### ISSUE TITLE
Cron job via URL requires login

### ISSUE THREAD

**Issue by woolmilkpigs** [freescout-helpdesk/freescout#1545]
If I call the URL to start the cron job (https://helpdesk.wpzw.de/system/cron/e0880321ca8be0fc372a2a144a26a1d4) it only works for me, if I'm logged in into freescout. Opening the URL via a online cron service or a different browser just shows the login page. Is that supposed to be like this? If yes, how can I submit my credentials automatically? The security token in the form seems to change obviously every time. So just send credentials via POST won't help I guess.

**Comment by woolmilkpigs** [comment]
Are you sure that is a wanted behavior, which I can't find anything about in the docs. Or is it a bug? Thank you for assistance.

**Comment by freescout-helpdesk** [comment]
It's a bug. We'll try to fix it.

**Comment by woolmilkpigs** [comment]
Thanks!

**Comment by freescout-helpdesk** [comment]
Fixed in the master branch.

**Comment by woolmilkpigs** [comment]
Tested it and worked for me! Thank you for the quick response.
