### ISSUE TITLE
Fetch errors

### ISSUE THREAD

**Issue by caladanbr00d** [freescout-helpdesk/freescout#1547]
Hello, I keep getting this error:

[2021-11-17 11:02:49] Error fetching email {"error":"From address my@example.com is not the same as user 3 email: fsworkflow@example.org","mailbox":"Mailbox Name"}

(I substituted my email address and the mailbox name for generic names)

The instance is running on a shared hosting, if that is important.

I am also getting this error sent to my mailbox (I don't know if they are related):

"Your email update couldn't be processed

If you are trying to update a conversation, remember you must respond from the same email address that's on your account. To send your update, please try again and send from your account email address (the email you login with). "

What is this error and how to fix it? The connection under connection settings is configured properly and works fine.

Thank you in advance! Excellent software!

**Comment by freescout-helpdesk** [comment]
In your mailbox Fetching Emails settings do you have "IMAP Folder To Save Outgoing Replies" specified?

**Comment by caladanbr00d** [comment]
Hello, thank you for your reply. 

No, it is blank. Should I set it?

**Comment by freescout-helpdesk** [comment]
This error is logged on fetching emails from your mail server. Try to find the email for which it happens. You can also run fetching manually in Manage > System > Tools.

**Comment by caladanbr00d** [comment]
Since you mentioned "IMAP Folder To Save Outgoing Replies", I set it manually. I checked my email account for the mailbox and it was not saving any sent messages. I will see if this can resolve the problem. Thank you very much. I will update later on this issue!

**Comment by freescout-helpdesk** [comment]
No need to set it.

**Comment by caladanbr00d** [comment]
Well, it seems though that it resolved the issue. But I noticed that in the laravel log there are constant state2 and type1 errors?

**Comment by caladanbr00d** [comment]
Apart from the larvel issues it seems that this fetch error has been resolved.
