### ISSUE TITLE
[request - knowledge Base] Improve search result

### ISSUE THREAD

**Issue by alexis3290** [freescout-helpdesk/freescout#1549]
**Situation** : I'm using the knowledge base with the chat module as an F.A.Q. 

**Problem** :  Problem is that the search field only search in title and text field from articles, and that's not always efficient. 

**Exemple** : "How may I pay a rental ? — The payment is 50% advance in credit card" if someone search for "creditcard" or "debit card", the answer will not pop up.

**Solution** : it could be nice if we can determine in back office a serie of keyword / tags invisible from the visitor, only for the search engine.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
