### ISSUE TITLE
Cron Job not working on Plesk

### ISSUE THREAD

**Issue by Bobraynor2** [freescout-helpdesk/freescout#1551]
Hey there!

I have been installing and managing FreeScout with Webuzo with no worries, but now I am migrating to a Plesk hosting, I used Softaculous to install and everyhthing went fine (Email setup Ok, Addon modules install Ok) until I setup the Cron Job.  I followed the instuctions in one of the other posts (#934 comment) but no luck, i get the following error:

Task "httpdocs/artisan" completed with error in 0 seconds, output:

Could not open input file: httpdocs/artisan

Even if I use the original command it does not work and the same error shows (php /var/www/vhosts/mydomain/httpdocs/soporte/artisan schedule:run >> /dev/null 2>&1)

Also, when I run the URL request (https://mydomain/soporte/system/cron/7042560c77a1ad210a4ac13e02b235e7) it shows the commands on screen but nothing happens:

Running scheduled command: '' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '' 'artisan' freescout:fetch-emails > '/var/www/vhostsmydomain/httpdocs/soporte/storage/logs/fetch-emails.log' 2>&1
Running scheduled command: '' 'artisan' queue:work --queue='emails,default,2b850bdf4de7ba17669f0964db9c534d' --sleep=5 --tries=1 > '/var/www/vhosts/mydomain/httpdocs/soporte/storage/logs/queue-jobs.log' 2>&1

Thanks for your time guys

**Comment by freescout-helpdesk** [comment]
> Also, when I run the URL request (https://mydomain/soporte/system/cron/7042560c77a1ad210a4ac13e02b235e7) it shows the commands on screen but nothing happens.

"nothing happens" - what do you expect to happen?

**Comment by qsvch** [comment]
Try it like this, it works perfectly for us. 
<br>
![Cronjob](https://user-images.githubusercontent.com/72531514/144033340-39f1c5be-e853-4717-a9de-466db4dcc575.jpg)
<br>

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/934
