### ISSUE TITLE
Disable auto-advance

### ISSUE THREAD

**Issue by foliovision** [freescout-helpdesk/freescout#1552]
> User story: We work on quite sophisticated tickets where we write answers to customers and then notes to one another. We've started to find the auto-advance extremely disruptive as we don't want to auto-advance most of the time.

What I'd like to see is a _global_ disable autoadvance (not on a per mailbox basis, as consistent behaviour through the whole application is much better for productivity).

In the worst, case per user control over autoadvance would be okay. At one point I think I remember seeing such autoadvance options but I can't find them any more. If I'm just not seeing them, please let me know and close the ticket. I've searched open and closed issues and not found any conversation related to auto-advance.

Thanks, Alec

**Comment by freescout-helpdesk** [comment]
What do you mean under "auto-advance"?

**Comment by foliovision** [comment]
When one replies to a ticket, it's Closed (our choice) and then the agent is moved to the next ticket, like it or not.

What we'd like is for the ticket to be closed by default but for the agent to remain on the ticket until s/he decides to move to the next one (as we often create internal note after answering customer).

Please note that I tried changing the Mailbox default for ticket status.

![Freescout-sttatus-after-replying](https://user-images.githubusercontent.com/1180948/142673568-17ea40ce-9566-4555-b38a-81c255474d6b.png)

It doesn't matter what the status after replying is set to, answering a ticket automatically moves the agent to the next one.

On reflection, this could be a per mailbox setting as it's really in our support mailbox that we have so much complex communication and so many notes to one another.

***

PS. An interesting use of Freescout which you might not have imagined when you created Freescout is using Freescout to manage forums. bbPress forum notifications go into Freescout via API (with replies to a thread kept together) where we can discuss the merits of the issue internally before publicly answering 

Effectively Freescout has become an automated way to turn a forum into issues management with no impact or inconvenience to end users.

On this mailbox, we answer in the forums so closing the ticket on reply is okay as only the single internal reply is in Freescout and the external reply is on the forum.

**Comment by freescout-helpdesk** [comment]
Maybe this is what you need:
![2021-11-19_21-42-46](https://user-images.githubusercontent.com/40499291/142674851-13a0d0a4-5470-4d3e-a332-b8e8838e4d39.png)

**Comment by foliovision** [comment]
Thanks for the pointer. That's not exactly what we need but this is:

![FreeScout-default-redirect-settings](https://user-images.githubusercontent.com/1180948/143460977-f65d9b74-402c-446e-b61f-211daf058516.png)

You've thought of everything!
