### ISSUE TITLE
Can't get the server to respond with the homepage

### ISSUE THREAD

**Issue by TobiasValeur** [freescout-helpdesk/freescout#1554]
I've cloned the docker-freescout project and sat SITE_URL to '127.0.0.1' and then run the no-proxy yml file with docker-compose.

When I then try to go on localhost/127.0.0.1 I got the "Sorry, the page you are looking for could not be found." 404 site.

What am I doing wrong?

**Comment by TobiasValeur** [comment]
I've gotten it to work in the regular non-docker way, thanks. I had some troubles with the fpm installation on my OS (openSUSE), some conf files weren't created, only conf.default, and also the .sock file was missing. After some general cleanup I've made it work.

**Comment by freescout-helpdesk** [comment]
Good to know.
