### ISSUE TITLE
Telegram Modul 1.0.5 Error

### ISSUE THREAD

**Issue by Kampfwurst** [freescout-helpdesk/freescout#1555]
With the module Telegram Modul Version 1.0.5 i get this error and no message.

`
[2021-11-23 09:29:09] production.ERROR: Trying to get property 'body' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'body' of non-object at /home/yyy/freescout.xxx/Modules/Telegram/Providers/TelegramServiceProvider.php:214)
[stacktrace]
#0 /home/yyy/freescout.xxx/Modules/Telegram/Providers/TelegramServiceProvider.php(214): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/home/yyy/...', 214, Array)
#1 [internal function]: Modules\\Telegram\\Providers\\TelegramServiceProvider->Modules\\Telegram\\Providers\\{closure}(Object(App\\Conversation), 'A <b>New Conver...', Array, NULL)
#2 /home/yyy/freescout.xxx/overrides/TorMorten/Eventy/Action.php(27): call_user_func_array(Object(Closure), Array)
#3 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\\Eventy\\Action->TorMorten\\Eventy\\{closure}(Array, 25)
#4 /home/yyy/freescout.xxx/overrides/TorMorten/Eventy/Action.php(28): Illuminate\\Support\\Collection->each(Object(Closure))
#5 /home/yyy/freescout.xxx/vendor/tormjens/eventy/src/Events.php(139): TorMorten\\Eventy\\Action->fire('telegram.post', Array)
#6 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TorMorten\\Eventy\\Events->action('telegram.post', Object(App\\Conversation), 'A <b>New Conver...')
#7 [internal function]: Illuminate\\Support\\Facades\\Facade::__callStatic('action', Array)
#8 /home/yyy/freescout.xxx/app/Jobs/TriggerAction.php(42): call_user_func_array('\\\\Eventy::action', Array)
#9 [internal function]: App\\Jobs\\TriggerAction->handle()
#10 /home/yyy/freescout.xxx/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /home/yyy/freescout.xxx/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /home/yyy/freescout.xxx/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /home/yyy/freescout.xxx/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#15 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\TriggerAction))
#16 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\TriggerAction))
#17 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\TriggerAction), false)
#19 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#20 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#21 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#22 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#23 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#24 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#25 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#26 /home/yyy/freescout.xxx/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#27 /home/yyy/freescout.xxx/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /home/yyy/freescout.xxx/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#29 /home/yyy/freescout.xxx/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#30 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#31 /home/yyy/freescout.xxx/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#32 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#33 /home/yyy/freescout.xxx/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /home/yyy/freescout.xxx/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /home/yyy/freescout.xxx/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /home/yyy/freescout.xxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /home/yyy/freescout.xxx/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 {main}
"} 
`

**Comment by freescout-helpdesk** [comment]
Fixed in Telegram Notifications Module v1.0.6
