### ISSUE TITLE
Weird error after moving freescout-environment

### ISSUE THREAD

**Issue by wauwturrr** [freescout-helpdesk/freescout#1556]
Hey Guys,

Got me some weird issues after moving the freescout-environment. Is this a known thing, and is there a way to solve this?

![image](https://user-images.githubusercontent.com/16634704/143251150-a9c72d03-35f3-4ed6-b796-95fa135f69e0.png)

**Comment by freescout-helpdesk** [comment]
It looks like something got messed up when you imported DB.
