### ISSUE TITLE
Email sending error, any idea?

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1557]
Dear support 

Any idea how to resolve this please

● [2021-11-24 23:00:30] Error sending email to user {"error":"Trying to get property 'id' of non-object; File: \/home\/admin\/domains\/mydomain\/public_html\/app\/Jobs\/SendNotificationToUsers.php (90)"}

**Comment by hanetworks** [comment]
[stacktrace]
#0 /home/admin/domains/mydomain/public_html/app/Jobs/SendNotificationToUsers.php(90): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: App\\Jobs\\SendNotificationToUsers->handle()
#2 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#3 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#6 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#7 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#8 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#10 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#11 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#12 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#13 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#14 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#15 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#16 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#17 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#18 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#19 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /home/admin/domains/mydomain/public_html/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#22 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#23 /home/admin/domains/mydomain/public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#24 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#25 /home/admin/domains/mydomain/public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#26 /home/admin/domains/mydomain/public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#27 /home/admin/domains/mydomain/public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#28 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#29 /home/admin/domains/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#30 /home/admin/domains/mydomain/public_html/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle()
#31 {main}
"}

**Comment by hanetworks** [comment]
Apparently there was no issue in the past, until we recently added some work flow.

**Comment by psuet** [comment]
It seens like it trys to send a notification to some Notification to a "user" who does not have an id. Do you have open notifications in your mail queue for users who no longer exist? 

`                $already_sent = SendLog::where('thread_id', $last_thread->id)
                    ->where('mail_type', SendLog::MAIL_TYPE_USER_NOTIFICATION)
                    ->where('user_id', $user->id)
                    ->whereIn('status', SendLog::$sent_success)
                    ->exists();
`

**Comment by hanetworks** [comment]
The user is myself, I noticed that my colleague wrote something in "note" and I didn't receive email notice, the error message were probably generated from there.

Where do I check if I have an "ID", and what's my and my users ID.

Please advise.

**Comment by hanetworks** [comment]
Nvm, I saw it's fixed in the latest release note. Thanks a lot..

https://github.com/freescout-helpdesk/freescout/releases
