### ISSUE TITLE
Attachments for Notes

### ISSUE THREAD

**Issue by CH4931** [freescout-helpdesk/freescout#1558]
Hi Freescout team,

I just noticed that it is possible to add attachments to a ticket reply, but it is not possible to add an attachment to an (internal) note.

It would be great to have the option to add attachments to notes as this speeds up internal communication between the individuals working on a ticket.

Look forward to hearing from you! Cheers!

**Comment by fulldecent** [comment]
Works for me, just had to use drag and drop

<img width="1491" alt="Screen Shot 2022-10-12 at 11 46 07" src="https://user-images.githubusercontent.com/382183/195389014-547ff694-0830-4854-9106-d024f1043eb6.png">
