### ISSUE TITLE
Delete Customer with no Messages / Auto-Merge Customer

### ISSUE THREAD

**Issue by szucher** [freescout-helpdesk/freescout#1559]
Hi there,
in my Database are more than 2500 customers with no message in the system. I config a workflow that delete messages after the last interaction from customer / freescout user.

Is there an option to automatic delete customer in the crm when the have no conversations?

A few of my customer use also a ticket system to contact me (e.g. Zammad). With every new mail this is send to me, a new customer is created, because each ticket has in this system his own mailadress. Is there the possibility to set a wildcard in the customer mail in crm, so that all mails from a specific domain or specific beginning of a mailadress will be automaticly add to the customer?

I hope you understand my problem, because my english is not very well!

**Comment by freescout-helpdesk** [comment]
> Is there an option to automatic delete customer in the crm when the have no conversations?

Not yet. It may be added to the CRM module. Feel free to add a https://freescout.net/request-feature/

> Is there the possibility to set a wildcard in the customer mail in crm, so that all mails from a specific domain or specific beginning of a mailadress will be automaticly add to the customer?

No. This can be implemented only via custom module.
