### ISSUE TITLE
Unable to fetch emails - "unexpected characters at end of parameters: @pc29.*"

### ISSUE THREAD

**Issue by dbrandesky** [freescout-helpdesk/freescout#1560]
Hi all, I had Freescout working perfectly with Zoho email yesterday, but today when I sent in some new emails to myself I found that they weren't showing up in Freescout. I went into the email settings and tested the email fetch connection and received the very odd error shown in the title.

I don't see anything new in the logs, but I'm also really new to Freescout so I may be missing a log source; I was only looking in the web interface really.

Note that this happened after I had some issues installing two new modules last night; I had to install them manually, and even then I had to run `php artisan freescout:after-app-update && php artisan freescout:clear-cache` a couple times to get them actually installed, which was odd. After all that, I found that somehow some random files in the storage/ directory didn't have the right permissions, so I corrected that using the `chmod -R www-data:www-data` fix in the documentation.

EDIT: I also tried the following from the troubleshooting docs, but it didn't actually fetch any new emails:
`php artisan freescout:fetch-emails
[2021-11-26 16:52:33] Fetching UNREAD emails for the last 3 days.
[2021-11-26 16:52:33] Mailbox: Support
[2021-11-26 16:52:33] Fetching finished`

LAST EDIT I PROMISE: if I send an email to myself (i.e. send an email to the email configured as my send/receive in Freescout), VIA the Freescout interface, I receive the email no problem. It seems that emails I send from external email clients (Protonmail, Gmail are what I've tested) don't show up in Freescout, but they DO show up in my Zoho inbox.

**Comment by freescout-helpdesk** [comment]
> Note that this happened after I had some issues installing two new modules last night; I had to install them manually, and even then I had to run php artisan freescout:after-app-update && php artisan freescout:clear-cache a couple times to get them actually installed, which was odd. After all that, I found that somehow some random files in the storage/ directory didn't have the right permissions, so I corrected that using the chmod -R www-data:www-data fix in the documentation.

This is the sign of https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

Fetching issue - you need to diagnose it yourself, we can't help here.

**Comment by dbrandesky** [comment]
Switched Zoho settings to allow IMAP connections, then set up Freescout to retrieve via IMAP...now it seems to work fine! No idea why IMAP works and POP3 doesn't but oh well.

**Comment by freescout-helpdesk** [comment]
Thanks for letting us know.
