### ISSUE TITLE
Language per Mailbox

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1561]
Hello,

We are supporting several languages on our website and we would like our customers to be able to contact us in different languages per mailbox.

Would you please mention how this would be possible ?

**Comment by freescout-helpdesk** [comment]
Are you talking about settings a language for Contact Us form of End-User Portal Module?

**Comment by alichakery** [comment]
Thank you for your reply,

Yes, both widget and the page…

All the best,
Al

**Comment by freescout-helpdesk** [comment]
You want widgets to be displayed in some specific language?

**Comment by alichakery** [comment]
Thank you for your reply,

Yes exactly and if possible both of the contact us form and the widget....

And it would be great also that you give us an option to pay to remove the "Powered by FreeScout". I do understand that it will help you to spread the word however, for some businesses like us the less the others know about the systems which we use the better (due to security issues).


All the best,
Al

**Comment by freescout-helpdesk** [comment]
Maybe it will appear with time.

**Comment by alichakery** [comment]
Looking forward to it….

This would help us a lot

**Comment by freescout-helpdesk** [comment]
All widgets now have Language option.

**Comment by alichakery** [comment]
WOW that was fast. That is great. 

I have an another request which I would also like to sponsor. I will create a new topic for that one to not to mix it with the current request.

I wish you the best and stay healthy...
