### ISSUE TITLE
ubuntu.sh install fails several times on 20.04 LTS

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1564]
On the page:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

Interactive installation bash-script (Ubuntu):
_source <(curl -s https://raw.githubusercontent.com/freescout-helpdesk/scripts/master/install/ubuntu.sh)_

Apparently no one has tried this using this script in a long time.

On a default install of 20.04 LTS desktop minimal software.

1. curl - not found, which I accept may be because I'm using the desktop install with the GUI, so that I don't have to manually install the GUI on LTS server later.

2. At the very top of the script it says "ifconfig not found" _.... they stopped including it. need to:_

> sudo apt-get install net-tools

3. "Would you like to start the installation [Y/n]:" --> Press Enter  ....  ./ubuntu.sh: line 28 unary operator expected ....... _type Y and Enter and it works_

4. Configuring nginx .. bash: /etc/nginx/sites-available/my.website.com  -- permission denied   _...... apparently failing to create the config file with "sudo echo.."_  ..... instead I got past it by directly running the script locally.

> wget https://raw.githubusercontent.com/freescout-helpdesk/scripts/master/install/ubuntu.sh
> chmod u+x ubuntu.sh
> sudo ./ubuntu.sh

5. During certbot install - "The PPA has been DEPRECATED" - fails - _... using manual instructions at eff.org worked ..

> sudo apt-get remove certbot
> sudo snap install --classic certbot
> sudo ln -s /snap/bin/certbot /usr/bin/certbot
> sudo certbot --nginx
> **certificate installed** 

6. For the life of me, I can not connect to the mySQL database to create the admin user login. But with everything else blowing up left and right, I don't know if the default user was created in MySQL correctly.

I tried doing the SQL commands manually from the script and MySQL doesn't seem to like the syntax of any of it. So I did some Googling to try to find a more correct way. I don't know if this is correct but there were no errors doing it.

> sudo mysql -u root
> drop user 'freescout'@'localhost';
> create user `freescout`@`localhost` identified by 'foobarbaz';
> grant all privileges on `freescout`,* to `freescout`@`localhost`;
> flush privileges;
> quit;

However ever after restarting ubuntu, I couldn't connect to the site URL.

I tried going through **sudo ./ubuntu.sh** one more time.

The script again fails in various spots but ultimately the website loads now.

I was able to create the admin account, but I needed to login to MySQL with the password I manually specified here in my own commands, rather than the new one listed in the script, because it again fails to edit the SQL user correctly.

But I'm finally logged in with the admin account, and looking at "Manage Mailboxes" on the dashboard.

**Comment by freescout-helpdesk** [comment]
Current installation script is not designed for desktop install with the GUI. If you wish feel free to prepare a version for desktop install and share.
