### ISSUE TITLE
Freescout attempts to send messages as emails in a chat conversation

### ISSUE THREAD

**Issue by alinmbb** [freescout-helpdesk/freescout#1565]
Hello,

Recently we saw this issue multiple times. So far I cannot see what it is causing it.  
Basically, conversations that are created from Facebook chats have the Conversation view page as in they are Email conversations, even though the customer has the Facebook tag. And of course when Freescout attempts to send the message the message as an email it throws an error, that the customer does not have a valid email (since it's from Facebook).

Any solutions to this ? I have added some screenshots to show the issue and information about our Freescout instance.
<details>
  <summary>Screenshot with the issue: </summary>
  <img width="1115" alt="Screenshot 2021-12-02 at 14 31 29" src="https://user-images.githubusercontent.com/86683952/144434174-e2b14443-9d61-4eed-b28b-a76273a28c47.png">

Clicking the View log buttons just shows : "There were no send attempts yet".
<img width="1300" alt="Screenshot 2021-12-02 at 14 36 35" src="https://user-images.githubusercontent.com/86683952/144434330-d7479cdc-c647-43c2-a4d9-e08319d812b0.png">

</details>
<details>
  <summary>System info and some failed jobs logs that might not be related </summary>
<img width="851" alt="Screenshot 2021-12-02 at 14 38 21" src="https://user-images.githubusercontent.com/86683952/144434203-2fb198cb-2e2a-47fd-80ee-e9c8542b35b9.png">

<img width="921" alt="Screenshot 2021-12-02 at 14 38 58" src="https://user-images.githubusercontent.com/86683952/144434236-a5b9d466-f665-4676-9f9f-5b0f372776b3.png">
<img width="1297" alt="Screenshot 2021-12-02 at 14 40 21" src="https://user-images.githubusercontent.com/86683952/144434248-85a3ec47-d26e-4dfa-8f3f-e8465e028b86.png">
<img width="1297" alt="Screenshot 2021-12-02 at 14 40 37" src="https://user-images.githubusercontent.com/86683952/144434273-d736ad54-0025-42af-bfb7-dd142e9b6b59.png">
</details>

Let me know if there is more info that I can share .

**Comment by freescout-helpdesk** [comment]
Fixed in FreeScout 1.7.23
