### ISSUE TITLE
WhatsApp module can not send answers

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#1568]
WhatsApp module is not able to send answers for some reason. We noticed the problem in case the first message is sent by us via Chat-API interface.

An error:
Message not sent to customer (View log)
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

Screenshot:
![freescout_whatsapp](https://user-images.githubusercontent.com/63669538/144588392-be236573-9ab9-488c-9827-2bfb0d4a947a.png)

**Comment by alinmbb** [comment]
This might be related to my issue #1565

**Comment by freescout-helpdesk** [comment]
What is your FreeScout and PHP version?

**Comment by ilyakonovalenko** [comment]
@freescout-helpdesk 

Latest version of FreeScout (1.7.22), updated today, issue started to happen immediately after that. PHP version is 8.0.12.

**Comment by freescout-helpdesk** [comment]
> the first message is sent by us via Chat-API interface

How are you doing this? Can you attach a screenshot?
