### ISSUE TITLE
Excessive amount of fetching alerts

### ISSUE THREAD

**Issue by denious** [freescout-helpdesk/freescout#1569]
Tonight I got a total of **46** "fetching problem" alerts delivered in the span of 1 minute, all in the same hour. Also, there are no logs explaining what the errors were.

Any ideas?

![image](https://user-images.githubusercontent.com/7120854/144624268-9101d2ad-2490-46e9-ad99-62e3b8510450.png)

![image](https://user-images.githubusercontent.com/7120854/144626358-97663d11-c89d-4c22-8079-d48ed11eddcf.png)

**Comment by denious** [comment]
![image](https://user-images.githubusercontent.com/7120854/144625707-f3420009-9daf-4ea3-9709-c34a1beb911e.png)

**Comment by freescout-helpdesk** [comment]
The only possible reason - mail server or connections issues.
