### ISSUE TITLE
SSO not working with AD auth

### ISSUE THREAD

**Issue by adepertat** [freescout-helpdesk/freescout#1570]
Hi

I am trying to get SSO working through an HTTP header sent by a reverse proxy on top of an Active Directory LDAP auth.

User import and LDAP authentication through the login page are working fine. However when I am coming from the reverse proxy, I am unable to login and it looks like the query used against the LDAP server is : 
```
(&(objectclass=person)(objectcategory=person)(samaccountname=$username))
```
which doesn't work because in Active Directory, the objectCategory field contains the dn to a schema (more like `CN=Person,CN=Schema,CN=Configuration,DC=example,DC=com`).

My first assumption when doing the first configuration was that the LDAP query I set in the settings page (DNs and Filters) would be used, but it looks like it is not the case.

The quickest workaround for my case would be to change the filter to 
```
(&(objectclass=person)(samaccountname=$username))
```
but I haven't been able to find where to do this, my PHP skills being very weak.

Thanks for your attention.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help you here. If you'll find a solution feel free to send it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
