### ISSUE TITLE
Import e-mails using webhooks

### ISSUE THREAD

**Issue by Wouter0100** [freescout-helpdesk/freescout#1571]
Currently, as far as I can see, the only way to import e-mails is using POP/IMAP. It would be awesome to add support for "webhooks", which get called every time an e-mail is delivered. This could be used with:

- Amazon SES Incoming E-mail (https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email.html)
- Postal incoming e-mail (https://docs.postalserver.io/developer/http-payloads)

It'd suggest to make FreeScout compatible which such imports, and that various modules will integrate the actual handling of the wide variety of possible providers. Integrating it using webhooks makes it so we don't need to run an import queue, have an IMAP inbox using space and adding import complexity required for IMAP/POP. 

I think it's fairly difficult to do this in a module alone. The `isInActive` function would need to be altered a bit, where `in_protocol` could for example contain `webhook` or the module name handling the webhooks for that e-mailadres.

If you guys approve this change, I'd love to put some time into this and creating a PR.

**Comment by freescout-helpdesk** [comment]
The feature is not needed in the core. Feel free to implement as a module (see https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development)

**Comment by Wouter0100** [comment]
Thanks for your reply @freescout-helpdesk! How would you see that we get the inbox to "Active" so [these flashes](https://github.com/freescout-helpdesk/freescout/blob/62ea562f26dc058918ee1a6868cb0fc59ec1e74f/app/Http/Controllers/MailboxesController.php#L474-L479) are not shown? As far as I looked into that, it is not really possible without making the necessary changes in core (and then especially the `isInActive` method). 

It would be awesome that a module is able to be the "importer" for an mailbox. So that we're able to select in the UI that we import IMAP, POP or installed module(s).

**Comment by freescout-helpdesk** [comment]
See "Actions and Filters" in "FreeScout Modules Development Guide".

**Comment by Wouter0100** [comment]
Interesting! I will certainly have a look into that.

**Comment by freescout-helpdesk** [comment]
Feel free to submit pull requests with hook you'll need.
