### ISSUE TITLE
Mobile notifications not working on Android

### ISSUE THREAD

**Issue by marcinkaminski** [freescout-helpdesk/freescout#1572]
Freescout: Latest version 1.7.23
Mobile Notifications  1.0.1

Notifications are enabled. Mailbox notifications arent muted.

![obraz](https://user-images.githubusercontent.com/53041702/144718905-4b1d6942-0005-4126-ad70-dc76c6c0972e.png)

Nothing happens in mobile app (android v10). App was reinstalled twice and it is closed while new messeges arrive in mailbox.
Notifications are enabled in app.

![obraz](https://user-images.githubusercontent.com/53041702/144723387-87a32b05-5890-42b9-b2d0-1f1130e2fc25.png)
(about 0 notifications weekly)

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version of the Android app: https://play.google.com/store/apps/details?id=net.freescout.app

**Comment by marcinkaminski** [comment]
Browser notifications are working ok
![obraz](https://user-images.githubusercontent.com/53041702/144743889-ba732fc3-0b59-46a7-8c90-33849eb92b27.png)

but mobile app doesnt show any notifications at all.
Now after upgrade it's like it was frozen because even Unassigned are out of date. It updates itself only if I open them.

**Comment by marcinkaminski** [comment]
after adding Reports module everything is working now!

**Comment by marcinkaminski** [comment]
after upgrade to 1.7.24 mobile notifications stopped working

**Comment by freescout-helpdesk** [comment]
Issue not confirmed. Works fine on demo.freescout.net

**Comment by marcinkaminski** [comment]
Is there a way to "restart" notifications?

**Comment by mywebhero** [comment]
Is your android battery management stopping it to work in the background? That happen to me for other app.
You can remove the battery management for this app, let it run in the background.

**Comment by freescout-helpdesk** [comment]
> Is there a way to "restart" notifications?

There is no such things as restarting notifications.

1) Make sure email notifications are working.
2) If yes follow this guide to fix notifications on your mobile phone: https://www.makeuseof.com/tag/android-notification-fixes/

**Comment by marcinkaminski** [comment]
@mywebhero battery man is off for this app

**Comment by marcinkaminski** [comment]
email notifications and those from web browser are working fine
only those on android app are not working 
my team member has ios and there notifications are working fine

**Comment by marcinkaminski** [comment]
after mobile app reinstall notifications are working now
