### ISSUE TITLE
Reset workflow as an action

### ISSUE THREAD

**Issue by Wouter0100** [freescout-helpdesk/freescout#1573]
Currently, workflows are only ran once - and this kinda makes sense. But, in our case we'd like to make them run multiple times. I've seen a past issue that if someone is able to make it work, it would be greatly appreciated for it to be given back to the community. Now, I don't have this solution - but I have a "workaround" that could work for (most) use cases.

It would be very useful to "reset" a workflow for a conversation. For example: we have a workflow that if a conversation is closed (lets call it workflow 1), it will send an e-mail to the customer. Now, that works perfectly fine - but if we re-open the conversation, it won't trigger that same e-mail again. In this case it would be very useful to create another workflow (workflow 2) that - if the conversation is opened - it'll reset the workflow 1 to allow it to trigger again. This way you make a loop that won't run infinite times and just works. 

In this way you make the infinite loop problem more of a "user" problem then not possible at all.

**Comment by freescout-helpdesk** [comment]
If someone is able they are free to implement it for their personal usage. This or any other workarounds will not be included in the Workflows Module as there is no way to guarantee that combination of workflows will not trigger/reset each other infinitely.

**Comment by Wouter0100** [comment]
Developed. 

![image](https://user-images.githubusercontent.com/864520/144764479-b6ef8dd2-6769-4d66-9839-9cda2e47a6f8.png)

[ResetWorkflow.zip](https://github.com/freescout-helpdesk/freescout/files/7656857/ResetWorkflow.zip)
