### ISSUE TITLE
Project setup Issue in Macbook Pro

### ISSUE THREAD

**Issue by code-jay** [freescout-helpdesk/freescout#1576]
Hi there,

I have setup the freescout based existing project with modules and database(without migration as I had database dump) in my Macbook Pro.
I can see the modules list. But when I click any feature under the modules, I'm getting "Whoops, looks like something went wrong." message.
Also tried to deactivate the modules. Deactivated successfully. But when I activate, getting: 

Error occured creating a module symlink (/Users/xxx/Desktop/workspace/xxxx/public/modules/invoicemanager). Please check folder permissions.

Cache cleared successfully.
Nothing to migrate.
Error occured creating [/Users/xxx/Desktop/workspace/xxxx/public/modules/invoicemanager] symlink: symlink(): No such file or directory
The [/Users/xxx/Desktop/workspace/xxxx/public/modules/invoicemanager] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js

Tried with Ubuntu. Getting same issue.

Have you faced same issue? Any solution?

Thanks

**Comment by code-jay** [comment]
I have observed the issue and found that system is unable to create the symlink but when we create symlink manually like:
ln -s /Users/jay/Desktop/workspace/coregroup/Modules/InvoiceManager/Public/ /Users/jay/Desktop/workspace/coregroup/public/modules/InvoiceManager, "Public" is created under /Users/jay/Desktop/workspace/coregroup/public/modules/InvoiceManager. Which is causing the problem. So I have created symlink this way:
ln -s /Users/jay/Desktop/workspace/coregroup/Modules/InvoiceManager/Public/js /Users/jay/Desktop/workspace/coregroup/public/modules/InvoiceManager (notice I have added js folder name as well)
and its working now.

But, while deactivating and activating, symlink issue is still there.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
