### ISSUE TITLE
Install not Running on Server

### ISSUE THREAD

**Issue by Blinky122** [freescout-helpdesk/freescout#1579]
Hello,
ich have Freescout on the Server uploaded (not my server).
But the install routine cant starting. wennn i will open the install.php ... nothing.

i have delete the .env Files ... then came Error Picture Freescout:

`File /home/www/HelpDesk/.env.example not found. Please make sure to copy this file from the application dist.`

i upload the env.exapmle .... .. The comes ERROR 500

This is my htaccess:
Options +FollowSymLinks

<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /freescout
        RewriteRule (.*) public/$1 [L]
</IfModule>

have everyone a idea

**Comment by freescout-helpdesk** [comment]
Try to reinstall: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
