### ISSUE TITLE
Extra keyboard shortcuts for dropdown menus

### ISSUE THREAD

**Issue by cmer** [freescout-helpdesk/freescout#1580]
The keyboard shortcut module is great. However, it is of limited use for a few features. For example, when pressing `S` to change the status of a ticket, we then have to resort to using the mouse to select the new status.

I'd love to be able to so `S` + `S` for Status -> Closed, or `S` + `P` for Status -> Pending, for example.

Hoping this can be added in a future version. Thanks!

**Comment by freescout-helpdesk** [comment]
Unfortunately JavaScript does not allow to track "letter + another letter" pressing.

**Comment by cmer** [comment]
That’s actually not correct. You could do anything with JavaScript, really. But in this case, the easiest way to go would be to check if the drop down menu is open. If I press C while the drop down menu is open, close the ticket.

**Comment by mywebhero** [comment]
I think this make sense! At least this feature is going to make the keyboard shortcut module more useful. I just bought this module a few days ago, and find that I still need to use my mouse to do the work.

**Comment by cmer** [comment]
I created a git patch to implement this functionality. It'd be great if it was added to the mainline. See attached.
[patch.txt](https://github.com/freescout-helpdesk/freescout/files/7708567/patch.txt)

**Comment by freescout-helpdesk** [comment]
Thanks. We'll check it.

**Comment by freescout-helpdesk** [comment]
Added in Keyboard Shortcuts Module v1.0.3

**Comment by cmer** [comment]
You might want to test my code because I noticed that sometimes when typing out a response in a ticket, it triggers keyboard shortcut actions. For example, when I pressed S while typing, it marked the ticket as spam.
