### ISSUE TITLE
IMAP connection problem

### ISSUE THREAD

**Issue by marcinkaminski** [freescout-helpdesk/freescout#1582]
FS 1.7.24 latest

Even when Encryption is set to none in mailbox fetching options I see that FS tries to connect on port 143 with TLS turned on (on server side).

**Comment by marcinkaminski** [comment]
acording to this thread https://stackoverflow.com/questions/20591473/php-imap-open-is-running-slowly-when-connecting-to-localhost 
I think there should be 143/imap/**notls** flag in server address connection string.
In Menage -> Logs -> Fetch Errors I see only this
Error: imap_open(): Couldn't open stream {10.0.0.3:143/**imap/novalidate-cert**}. [CLOSED] IMAP connection broken (server response); File: /var/www/fs/freescout-dist/overrides/Webklex/IMAP/Client.php (230)

**Comment by mywebhero** [comment]
I'm facing the TLS error issue as well. Exactly the same error you have. It is only intermittent error for some reason. But it didn't stop the app working correctly.

To avoid this problem, I switch to use SSL and disable SSL validation should stop this error.

Or you can troubleshoot according to the guide: [https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails](https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails)

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. If you want to debug it see https://github.com/freescout-helpdesk/freescout/tree/dist/overrides/Webklex/IMAP
