### ISSUE TITLE
Delete customers automatically

### ISSUE THREAD

**Issue by XtomtomX** [freescout-helpdesk/freescout#1583]
Hi there!
Thank you for your great work in this tool.

Would it be possible to allow us to automatically delete customers by making use of the "Workflows" module combined with the new "GDPR" module?

I thought about something like a condition "if overall last reply of one customer is older then e.g. 3 years" -> action "delete whole customer with their corresponding data".

This would allow us also to clean up the database a bit and to get rid of old data.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
