### ISSUE TITLE
Install guide Section 3, Config PHP fails, not root

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1584]
Starting from current Ubuntu 20 LTS server install ISO

In the install guide: 
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

Step 3 Configuring PHP
```
echo ‘cgi.fix_pathinfo=0’ >> /etc/php/7.4/fpm/php.ini
```
_-bash: /etc/php/7.4/fpm/php.ini: Permission denied_

You need root privileges to do this, but the sudo command needs to be formatted like this so that the pipe works correctly:
```
sudo -- "$SHELL" -c "echo 'cgi.fix_pathinfo=0' >> /etc/php/7.4/fpm/php.ini"
```

**Comment by freescout-helpdesk** [comment]
Thanks. Updated: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
