### ISSUE TITLE
Ubuntu 20 LTS - Nginx default install breaks git clone

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1585]
Starting from current Ubuntu 20 LTS server install ISO

In the install guide: 
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

2. Installing Package Dependencies, Nginx
```
sudo apt-get update
sudo apt remove apache2
sudo apt install nginx
```
This breaks the later git clone into /var/www/html because by default the Nginx install places a "hello world!" file in html directory.

**index.nginx-debian.html**
_Contains:_
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
[...]
```
There needs to be an additional command to remove any example html placed in there after Nginx installs.

```
sudo apt-get update
sudo apt remove apache2
sudo apt install nginx
sudo rm /var/www/html/*nginx*.html
```

**Comment by freescout-helpdesk** [comment]
Thanks. Updated: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
