### ISSUE TITLE
WhatsApp import duplicate sent message issue

### ISSUE THREAD

**Issue by mywebhero** [freescout-helpdesk/freescout#1586]
I started to use the Freescout WhatsApp module last week. But my last update to v1.7.24 on Monday, I'm facing a weird bug / behaviour since then.

## Issue:
Every message I sent out from the system is getting another duplicate message in the conversation after Chat API manage to send the message.
![Repeated import own message](https://user-images.githubusercontent.com/83342769/146326927-69720b63-acc3-42f5-9f63-fd754ca95eb1.jpg)

If I connect with other numbers in the same Freescout installation, it works fine.

##What I have tried, but not giving result:

1. Restart the Chat API instance. In fact, checking the Chat API chat log, it is showing only one message sent out. It is an expected behaviour. I suspect it is related to import problem.
2. Try to reply in other conversation, same issue.
3. Clear cache. Deactivate & reactivating the module.
4. Connecting to new instance.
5. Uninstall the module & reinstall again.

Anyone facing similar issue can share your input?

**Comment by freescout-helpdesk** [comment]
> If I connect with other numbers in the same Freescout installation, it works fine.

What is numbers?

**Comment by mywebhero** [comment]
As in WhatsApp number. I have enable the log for WhatsApp in app. 
I sent out 2 message and reply 1 message. There are 3 webhook event in the log. It is strange that having duplicate event.

**Comment by freescout-helpdesk** [comment]
Could you please attach screenshots.

**Comment by mywebhero** [comment]
This is from my Applog after decomment to log every Webhook event.
![WhatsApp module log](https://user-images.githubusercontent.com/83342769/146326750-e3e57d75-251c-4ac6-9663-8791fc3142ee.jpg)

But in ChatAPI, the message log appears to be correct, and even recipient only receive 1 message.
![ChatAPI log](https://user-images.githubusercontent.com/83342769/146327354-ed78b382-2cdb-4164-9958-e9babd9d6a1e.jpg)

**Comment by freescout-helpdesk** [comment]
And screenshot of duplicated messages in FreeScout...

**Comment by mywebhero** [comment]
I have included this in my original message above.

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue. It looks like no one else is having such issue. Notice that second duplicate message is created on behalf of another user:

![2021-12-17_13-19-22](https://user-images.githubusercontent.com/40499291/146529409-a7b4cd59-5615-4be2-965d-c455795a6a46.png)

Check all your customizations, API integrations, maybe there are some Zapier integrations...

**Comment by mywebhero** [comment]
Yup, that is the strange part. There is no such user, it is showing as the mailbox name.
Even I can't repeat the same error, connecting to the same instance, but login using a different WhatsApp account.

Any way, appreciate the time you invested in helping. But is it okay to leave this open for a few more weeks, in case someone face the same issue?

**Comment by freescout-helpdesk** [comment]
Sure

**Comment by jtomassilva** [comment]
I have exactly the same problem. How did you solve it?

**Comment by mywebhero** [comment]
> I have exactly the same problem. How did you solve it?

I didn't solve it. I can't even replicate the issue when I link with separate Chat API instance, even in the same Freescout installation.
