### ISSUE TITLE
Ubuntu 20 LTS Server - LetsEncrypt PPA no longer works

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1587]
Starting from current Ubuntu 20 LTS server install ISO

In the install guide:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

Section 6.1 / subsection: Install Certbot:
```
apt-get update
apt-get install software-properties-common
add-apt-repository universe
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install certbot python-certbot-nginx
```
Fails because the PPA repository has been deprecated and no longer installs anything.

The following works for Ubuntu 20 LTS but may be different for other distros. 
```
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --nginx
```
Command output:
_Successfully received certificate._
_These files will be updated when the certificate renews._
_Certbot has set up a scheduled task to automatically renew this certificate in the background._

The specific commands to use for other distros can be obtained from:

https://certbot.eff.org/
"My HTTP website is running [web server type] on [Linus Distro name/version]"

I have no idea how you can wrap this in a simple auto installer for any distro.

**Comment by freescout-helpdesk** [comment]
Thanks. Updated: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
