### ISSUE TITLE
Install guide section 4: Default SQL password allows attack during setup

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1588]
In the install guide:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

Section 4. Configuring MySQL

_Create FreeScout database and user:_
```
CREATE DATABASE `freescout` CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON `freescout`.* TO `freescout`@`localhost` IDENTIFIED BY "XXX";
```
_If above code does not work try:_
```
CREATE USER 'freescout'@'localhost' IDENTIFIED BY 'XXX';
GRANT ALL PRIVILEGES ON `freescout`.* TO `freescout`@`localhost`;
```
,

The SQL database password **XXX** allows for remote takeover during the install if an attacker discovers the site is currently unconfigured.

Anyone can open [yourwebsite]/install because you need to have your new webserver already configured for external access for LetsEncrypt to do its magic and obtain a certificate.

So there is a window of opportunity for the new site to be attacked between the initial install and the person doing the installation finally getting around to creating the user account via [yourwebsite]/install

The password XXX should be randomized and the randomly generated password printed in the script.

```
sqldb='freedumb'
sqluser='freederp'
sqlpass=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c10`
echo The SQL database name is: $sqldb
echo The SQL user name is: $sqluser
echo The SQL database password is: $sqlpass
echo SQL server verbose output:
echo "CREATE DATABASE $sqldb CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;" | sudo mysql -u root --verbose
echo "CREATE USER $sqluser@localhost IDENTIFIED BY '$sqlpass';" | sudo mysql -u root --verbose
echo "GRANT ALL PRIVILEGES ON $sqldb.* TO $sqluser@localhost;" | sudo mysql -u root --verbose
```

**Output:**

The SQL database name is: freedumb
The SQL user name is: freederp
The SQL database password is: VVbBaZNYHF
SQL server verbose output:
CREATE DATABASE freedumb CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
CREATE USER freederp@localhost IDENTIFIED BY 'VVbBaZNYHF'
GRANT ALL PRIVILEGES ON freedumb.* TO freederp@localhost

**Comment by freescout-helpdesk** [comment]
Thanks. Added a notice: "replace "XXX" with the real password"
