### ISSUE TITLE
Install guide section 5, mkdir fails, not root

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1589]
In the install guide:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

5. Downloading the Application
```
mkdir -p /var/www/html
sudo chown www-data:www-data /var/www/html
cd /var/www/html
```
The first line mkdir fails because the user is not root. Need to use sudo with each command.
```
wwwpath=/var/www/html
sudo mkdir -p $wwwpath
sudo chown www-data:www-data $wwwpath
cd $wwwpath
```

Though this install error may go unnoticed if the nginx default install was used, as it created /var/www/html for itself already so making it again is not needed.

**Comment by freescout-helpdesk** [comment]
Updated: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
