### ISSUE TITLE
Install guide section 5, git clone fails, not root

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1590]
In the install guide:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

Section 5, git clone
```
git clone https://github.com/freescout-helpdesk/freescout .
```
_Cloning into '.'..._
_/var/www/html/.git: Permission denied_

Need to use sudo to install into /var/www/html/
```
sudo git clone https://github.com/freescout-helpdesk/freescout .
```

**Comment by freescout-helpdesk** [comment]
Updated: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
