### ISSUE TITLE
Feature request: Robot like answers for the customer portal widget

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1594]
Hello,

First thank you for your great support.

We are looking to replace the robots option of Tidio.com with an on premise option. Tidio loads some external javascript files which track our customers and we are not really happy about it (this is the same story with all other thirdparty chat systems).

It would be an amazing addition to FreeScount if we can create pre-made answers (button like answers) for the customers in the widget.

In this way we can pose questions and provide answers as buttons to the customer and then after choosing the answer customer gets the related answer.

I sponsor this feature and I am sure there are more users who would like to have this as well. 

Your opinions are appreciates.

All the best,
Al

**Comment by freescout-helpdesk** [comment]
See:
https://freescout.net/request-feature/
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
