### ISSUE TITLE
Feature Request: Whitelabeled Customer Portal Widget

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1595]
Hello,

Would you please developer/offer a paid option for removing the "Power by FreeScout" from the customer portal widget.

We are 100% OK with promoting FreeScount as it is amazing and is helping us a lot however, it is also a security risk for us when everyone knows publicly that what script we are using in general.

It would be great if you provide us with a paid option that also would be fair for you for removing the Powered By link.

Thank you.

All the best,
Al

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/white-label/

**Comment by alichakery** [comment]
Thank you for the reply,

I already have this plugin but what I meant is the widget. Although I have this plugin activated but still in the widget I have the powered by Freescout.
