### ISSUE TITLE
CRM: Adding new customer 

### ISSUE THREAD

**Issue by haimiko** [freescout-helpdesk/freescout#1596]
Freescout version: 1.7.24
CRM Version: 1.0.6

**Issue**: Adding new customer with FireFox will display the following error:

![image](https://user-images.githubusercontent.com/3318870/146983246-f4b7dd6b-65a0-415a-be78-a8689795fdd4.png)

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by haimiko** [comment]
No. Works on demo site.  I've reviewed the HTML and can't find any domains
other than mine.  Any suggestions?

**Comment by haimiko** [comment]
This is the console error:

The loading of “https://mysite.com/customers/new?x_embed=1” in a frame is denied by “X-Frame-Options“ directive set to “DENY“.

**Comment by freescout-helpdesk** [comment]
Your server sends “DENY“ in “X-Frame-Options“ header. You need to change it to "SAMEORIGIN".

**Comment by freescout-helpdesk** [comment]
Try to put the following file into /app/Http/Middleware replacing existing ResponseHeaders.php

[ResponseHeaders.zip](https://github.com/freescout-helpdesk/freescout/files/7772985/ResponseHeaders.zip)

**Comment by haimiko** [comment]
Thanks .  Tried it but it's now sending "SAMEORIGIN" and "DENY" right after.
![image](https://user-images.githubusercontent.com/3318870/147369572-1532eb96-54e1-4461-8278-3b0dd05d68aa.png)

**Comment by haimiko** [comment]
Fixed it by adding the add_header X-Frame-Options "SAMEORIGIN";  to my nginx config.

Thank you for the direction!

**Comment by freescout-helpdesk** [comment]
It looks like in this case you will have issues when adding FreeScout chat and other widgets to the website.

Try the following:
```
proxy_hide_header X-Frame-Options;
fastcgi_hide_header X-Frame-Options;
```

**Comment by freescout-helpdesk** [comment]
Ideally you should find out what (web server, hosting or some non-official module) adds `X-Frame-Options` header and get rid of this header.

**Comment by karrierekick-dev** [comment]
In my case, the generated symlink files in public/modules/ had a wrong path.

They should point to the corresponding module folder. For example: The Chat widget has a symlink "chat". When opening such a link you should be forwarded to the directory it is pointing to which should be "Modules/Chat/Public".

In my case the "chat" link pointed to "/html/support/Modules/Chat/Public"
I've edited the link using WinSCP and replaced the path with a relative one: "../../Modules/Chat/Public".

After that, everything works.
