### ISSUE TITLE
[Enhancement] - CRM - Import CSV

### ISSUE THREAD

**Issue by haimiko** [freescout-helpdesk/freescout#1597]
Would be great if the CRM feature had the ability to import?  Is there another method to side load my CRM first time?

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
Importing customers added in [CRM Module v1.0.7](https://freescout.net/module/crm/)

**Comment by haimiko** [comment]
Sweet. Thanks.
