### ISSUE TITLE
Attachment only sent to first recipient when sending separate mails to multiple recipients 

### ISSUE THREAD

**Issue by sebix** [freescout-helpdesk/freescout#1599]
We are running version 1.7.24.

Sending a mail to multiple recipients, e.g.:
- "Test 1" <test1@example.com>
- "Test 2" <test2@example.com>
- "Test 3" <test3@example.com>

The mail is sent to all addresses, but with wrong names:
- "Test 1" <test1@example.com>
- "Test 1" <test2@example.com>
- "Test 1" <test3@example.com>

Additionally when attaching files, the attachment is only sent to the first recipient. However, freescout shows for all mails in the list view, that the sent mail has an attachment. When viewing a single sent mail, there is (correctly) no indication of the attachment sent.

**Comment by freescout-helpdesk** [comment]
The issue with names not confirmed. Issue with attachments confirmed.

**Comment by sebix** [comment]
Thank you for the quick response and fix. We'll check if the name-issue persists in the next release (and re-report if it is the case).
