### ISSUE TITLE
Can this workflow be improved with the use of freescout?

### ISSUE THREAD

**Issue by virtual-orbis** [freescout-helpdesk/freescout#1600]
I am in a situation where aprox 4 people work
in an exports trading company and it is usual practice that they exchange documents
received by one of them to be completed by others and close an operation. 
And sometimes the supervisor needs to ask them to collect the information 
to know the complete status of an operation.

So I was wondering if freescout can work in this scenario to improve the operations work flow

**Comment by freescout-helpdesk** [comment]
You may need to try it and find it out yourself.
