### ISSUE TITLE
End-user portal: Whitelisted customer domains

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1601]
I am a new FreeScout user, setting up the customer portal.

I see that it accepts email addresses from anywhere to submit tickets. This is unacceptable as it allows the IT help desk to be spammed by robots.

How do I restrict it to only allow email logins or tickets to be submitted from specific whitelisted / approved domains?

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible for now. Feel free to add a feature request: https://freescout.net/request-feature/
