### ISSUE TITLE
End-user portal: approve new users and generate passwords

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1602]
I am a new user of Freescout, and the end-user portal is extremely low security. It allows anyone from anywhere to submit tickets, which makes it a high risk potential spam target.

How can I have new customer email accounts be forwarded to a certain admin account for approval before it will allowed to submit tickets?

How can I generate login passwords for customer accounts so that random spammers cannot submit spam tickets, by simply using known staff email addresses?

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible for now. Feel free to add a feature request: https://freescout.net/request-feature/
