### ISSUE TITLE
End-user portal: Redirect https://site/ to end user portal?

### ISSUE THREAD

**Issue by DMahalko** [freescout-helpdesk/freescout#1603]
How can I redirect the root home page login for our Freescout server to the customer service portal URL?

I am going to test if a DNS SRV record can pull this off, but this may fail if I can't also leave the current DNS A record for SSL in place.

For technicians to login, I simply customize the customer portal footer to say:
**Technicians and managers, login here: https://site/login**

**Comment by freescout-helpdesk** [comment]
Via your server config.

**Comment by DMahalko** [comment]
Can you provide exact details on what needs to be modified in the server config to accomplish this? I am using nginx on Ubuntu 20.04 LTS.

**Comment by freescout-helpdesk** [comment]
https://serverfault.com/questions/548591/nginx-redirect-one-path-to-another

**Comment by freescout-helpdesk** [comment]
Or maybe this will be helpful: https://freescout.net/module/custom-homepage/
