### ISSUE TITLE
Add a row in Submit a ticket or contact pop up, and automatically update it into CRM?

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1605]
Can we add a column so that user can fill up more information (such as their company name, contact number) and recorded in CRM automatically?

**Comment by freescout-helpdesk** [comment]
Something like this https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/337629 ?

**Comment by hanetworks** [comment]
that would be great too. 

However, that's the selection of mailbox, I actually wanted to add customer's phone number and company name in the contact form if it's possible. 

It's easy to do it with any form builders, but I think I don't find such options with freescout.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
