### ISSUE TITLE
Update to version 1.7.25 fails

### ISSUE THREAD

**Issue by eickit** [freescout-helpdesk/freescout#1606]
Hello, I get the following error message when trying to update:

SplFileInfo::isDir(): open_basedir restriction in effect. File(/var/www/vhosts/xxxxx/httpdocs/public/modules/slack) is not within the allowed path(s): (/var/www/vhosts/xxxxx/:/tmp/)

xxxxx = my hostname

So far, the update has always worked smoothly. Nothing has changed in the server configuration. Can the error also be with the Slack module?

Thanks for your help, Sven

**Comment by freescout-helpdesk** [comment]
Nope. https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by aclassnet** [comment]
Hello dear friends.

I get a similar error when I try to upgrade to version 1.7.25 with the Whatapp app. It is not possible to remove this app from the addons and when I try to upgrade the system I get the following error

SplFileInfo::isDir(): open_basedir restriction in effect. File(/var/www/vhosts/xxx.xxxx.com/httpdocs/public/modules/whatsapp) is not within the allowed path(s): (/var/www/vhosts/xxx.xxxx.com/:/tmp/)

I hope you can help me to solve this issue.

Thank you very much in advance.

Alfonso

**Comment by freescout-helpdesk** [comment]
> SplFileInfo::isDir(): open_basedir restriction in effect. 

Some hosting or web server configuration issue.

**Comment by eickit** [comment]
That may be, but so far the updates have worked without any problems...

**Comment by eickit** [comment]
I have now removed the Slack module. Now the update works again without problems. Too bad that the blame is always shifted to the server.

**Comment by freescout-helpdesk** [comment]
Try https://stackoverflow.com/a/34980645
