### ISSUE TITLE
"Request exceeded the limit of 10 internal redirects" during installation

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1607]
I downloaded the freescout-dist.zip and unzipped and then uploaded freescout folder and files on my shared hosting server to this location:
https://mydomain/mysubfolder/freescout

When I go to that address to start install, it redirects to:
https://mydomain/mysubfolder/freescout/public/public
(notice the double public/public)
and then it gives me a 500 Internal Server Error

Checking the apache log, I see this:
AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

I beleive the server is running Centos.

I have no idea what I should be looking for or checking.

Any help appreciated.

**Comment by freescout-helpdesk** [comment]
Your web server apparently has some non-standard redirect rules. Try to play with https://github.com/freescout-helpdesk/freescout/blob/dist/.htaccess

**Comment by jshrek** [comment]
I have WordPress installed at
https://mydomain/mysubfolder/

Could that be part of the redirect issue?

Thanks

**Comment by freescout-helpdesk** [comment]
Yes. Check or remove all higher-level .htaccess files.

**Comment by jshrek** [comment]
Okay so I created a subdomain on my server and moved all the files to the top level like this:
https://freescout.mydomain/

and now the install was succesful and I am up and running!

I personally consider this a bug ... I have succesfully installed many other applications in subfolders even with wordpress installed at the top level, and there has been no issues. If not a bug, then a feature request!

**Comment by freescout-helpdesk** [comment]
Have you tried to add the following to the Apache virtual host configuration: `RewriteBase /`

**Comment by jshrek** [comment]
Yes ... I tried all these (several other combinations/variations):

RewriteBase /
RewriteBase /subfolder/
RewriteBase /subfolder
RewriteBase /subfolder/freescout/
RewriteBase /subfolder/freescout

I then removed RewriteBase completely and tried modify the original line (and some other variations I cant remember):
RewriteRule (.*) /public/$1 [L]
RewriteRule (.*) /testsite/freescout/public/$1 [L]
RewriteRule (.*) testsite/freescout/public/$1 [L]

Part of the issue is that I do not really understand how rewritebase and rewriterule work!

But all my attempts from above lead to one of two outcomes:
- 500 Internal Server Error, or
- 404 page not found

**Comment by freescout-helpdesk** [comment]
What hosting are you using?

**Comment by jshrek** [comment]
I have a dedicated VPS server ... I have root access if I want/need it.

**Comment by freescout-helpdesk** [comment]
We've just double checked on clean Ubuntu installation. It works fine with the following config (https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#62-apache):
```
<VirtualHost *:80>
  ServerName example.com
  DocumentRoot "/var/www/html/subfolder/public"
  Options Indexes FollowSymLinks
  ErrorLog /var/www/html/storage/logs/web-server.log
  <Directory "/var/www/html/subfolder/public">
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```
