### ISSUE TITLE
How do modules' license restrictions to a single instance comply with GPLv3?

### ISSUE THREAD

**Issue by nativeit** [freescout-helpdesk/freescout#1608]
I am not an expert on GPL, and I certainly don't begrudge the developers the opportunity to earn an income for their work--but given that GPLv3 enables one to charge to distribute the binary and source code, but then allows the recipient to copy, modify, and/or redistribute the software freely provided it's done under the same GPLv3 license, how can you restrict someone's ability to use a module on (for example) their test server and their production server with a single purchase?

I have just begun testing Freescout, and I am hopeful that it will meet/exceed expectations, but if I'm honest I am a little disappointed with how few features are included within the *free* context of *Free*scout. Absurdly basic features such as blocking external images, folders, tags, anti-spam, keyboard shortcuts, rich text editor--more or less every feature one might expect from any given basic email client--these are ALL held behind a paywall? Further, if I want to maintain a dev server I have to buy everything twice?

**Comment by nativeit** [comment]
Just for a little further context, I am testing Freescout to develop it as an addition to the One Click Apps library for Caprover, so I am a proponent of the product for the most part, and I am making an effort to provide it to a wider audience. These details just surprised me, and I feel like I must have missed something. Selling access to value-added features seems reasonable, but shipping an intentionally hobbled base product advertised as a FOSS "alternative to Zendesk" under the *Free-* superlative while holding back every little detail, no matter how minute, that would make it resemble anything like Zendesk seems...maybe not quite dishonest, but at least a smidge deceptive. Shouldn't Freescout be at least functional as a very basic helpdesk before I am asked to **pay** for additional modules to expand its capability?

**Comment by freescout-helpdesk** [comment]
This is how FreeScout works. Anyone can always create a better tool and find a better way to provide it ;)
