### ISSUE TITLE
Who is this built by?

### ISSUE THREAD

**Issue by mgibbs189** [freescout-helpdesk/freescout#161]
**Suggestion**: on the Contact page, please tell us about the people building this project.

It's really hard to put any trust in a project without knowing the people behind it.

* Who are you?
* Why did you decide to build this?
* What availability do you have to develop (and maintain) it?
* Is your plan to eventually monetize it via paid modules?

You (whoever you are) have clearly put a lot of effort into the project thus far!

**Comment by freescout-helpdesk** [comment]
> Who are you?

We are international team maintaining FreeScout.

> Why did you decide to build this?

Original idea belongs to Janko Miroslav, he told about it in [the blog](https://medium.com/@freescout/phasing-out-help-scouts-free-plan-pushes-the-development-of-a-free-self-hosted-alternative-d1b3d007b8a6) when the project was starting.

> What availability do you have to develop (and maintain) it?

Team is still being formed and growing.

> Is your plan to eventually monetize it via paid modules?

See [Architecture & Philosophy](https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#architecture--philosophy) in FreeScout Wiki.

**Comment by GauthierPLM** [comment]
I think adding a page on your website about who is behind FreeScout would help people to trust the project. All your team members commit under the same account/name. It looks unified but hide who is really committing and building Free Scout.

Knowing more about the people behind this project would give more trust to people, help us to know your team more, and would make the development process more transparent.

I understand that not everybody wants his private life to be exposed online, but when a project grow, ensuring transparency is very important, no matter if the project is open source or not.
