### ISSUE TITLE
FEATURE REQUEST- allow easy installation of freescout in subfolders

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1610]
I had an issue where I was trying to install Freescout in a subfolder (not at top level domain) and it was giving a 500 internatl server error and would not even run the install script. See here: https://github.com/freescout-helpdesk/freescout/issues/1607

Creating a subdomain and then moving freescout to the top  level of that subdomain, fixed the issue and installation was succesful.

But it seems to me that we should be able to install it in any subfolder as well without issue.

The potential fix for this is that the .htaccess rewrite rules need to be modified. This of course would require an expert in htaccess rewrite rules to look at it (which I am not).

I suppose there are possible code issues that may arise if the original code was written in a way to expect it to always be at a top level, which would then make this much more difficult that simply reworking the htaccess file.

Thanks

**Comment by freescout-helpdesk** [comment]
FreeScout is supports installation in a subdirectory. You may need to find out what was wrong with the server configuration.
