### ISSUE TITLE
Email Fetch - Seen ("read") emails

### ISSUE THREAD

**Issue by VacationTeam** [freescout-helpdesk/freescout#1611]
First Off, Thank you for the great product.
I have purchased several of modules on top and they are work fantastic.

I tried searching previous issues and reading about the hooks, but I can't seem to get the functionality I want.
I would like to have emails fetch, even if they have been "read" or seen.

I am connecting to my G Suite box.  Sometimes we view the emails on our other devices and causes the email to be "read" on gsuite, in such FreeScout won't pull it in.

I tried using the php artisan freescout:fetch-emails --unseen=0 

I get a ton of duplicate emails this way.  I also end up with this bad loop for Unable to process your update emails getting sent to the mailbox.

What am I missing in being able to bring in seen or "read" emails, without causing duplication?  Other Imap based apps seem to have this function.

It feels like the app has the ability to know what emails it has brought in, as I set an email to unread in gmail and it doesn't bring it in again, but marks it as read just fine.

Thank you

**Comment by freescout-helpdesk** [comment]
When fetching emails FreeScout checks Message-ID of each email and skips duplicates. Try to fetch emails manually in System > Tools to see why duplicates are being imported.

**Comment by VacationTeam** [comment]
Hi, 
Thank you for the follow up.
Using that method, I didn't get any duplicates.
If I want to set the systems default fetch to grab "all" and not just "unseen"
Do I need to use this as a cron?

php artisan freescout:fetch-emails --unseen=0

If so, do I need to turn off the current fetching in the system settings?

**Comment by freescout-helpdesk** [comment]
Currently there is not way to change default fetching options. You can try to change it right in the code: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L86
