### ISSUE TITLE
Change the adming login path

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1613]
Hello,

Due to security reasons we would like to change the admin login path and also when someone logs in we would like to see a static page with a logo or a custom HTML page.

But the most important part is to change the admin login and not to let the users to see it when the visit the domain root where freescout is installed.

Your help is appreciated.

 A small feedback:
About a month ago we switched from osTicket to FreeScout and I have to say it has increased our productivity. We purchased majority of your plugins even if we do not have any use for them to support this project.
Keep up the great work and we believe your projects should have a better recolonization. THANK YOU and I wish you a great new year full of health and success.

**Comment by freescout-helpdesk** [comment]
Try to place FreeScout into subdirectory and put index.html in the folder above.

**Comment by alichakery** [comment]
Thank you for your reply,

But it still would not resolve the problem because if we provide our customers with the portal link, when they visit the root of the freescout directory the admin login will be there.  It would be great if we can change the admin login page to something else.



>

**Comment by freescout-helpdesk** [comment]
Maybe this will be helpful: https://freescout.net/module/custom-homepage/

**Comment by alichakery** [comment]
Thank you for your quick support. I love it that how fast you resolve such issues. I will order later today when I am behind my desk.

Similar solution for the EU GDPR regulation would be great (as a plugin :D)….

**Comment by alichakery** [comment]
I bought and ordered the plugin. It does everything as I wanted BUT, it would also be great if I can also change the path of the login page from "/login" to something else.

Thank you
