### ISSUE TITLE
How to add the GDPR box (I accept the Privacy Policy) in the contact widget

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1614]
Hello,

We are in the EU zone and it is mandatory to provide the users with our privacy policy as a checkbox or a statement (e.g. By submitting this form you accept our privacy policy).

Would you please mention how can we add this checkbox or an statement? It would be great if we can manage it from the admin.

Thank you in advanced.

**Comment by freescout-helpdesk** [comment]
Not possible for now. Feel free to add a feature request: https://freescout.net/request-feature/
