### ISSUE TITLE
Modules don´t comply with the license AGPL-3.0

### ISSUE THREAD

**Issue by tcarrondo** [freescout-helpdesk/freescout#1615]
Please read carefully the license text:
https://www.gnu.org/licenses/agpl-3.0.en.html

And make the appropriate corrections to your code or to the license advertised.

**Comment by freescout-helpdesk** [comment]
Please message us at support@freescout.net and let know which aspects of modules you think are not ok. On GitHub we are mostly focusing on development of the core of the app.
