### ISSUE TITLE
unable to move ticket?

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1616]
For example, a person in billing mailbox is unable to move ticket to support mailbox, because he/she is not assigned to have access to support mailbox. 

Does it mean that I have enable access all mailboxes to all members in our company, in order to enable proper ticket move capability?

**Comment by freescout-helpdesk** [comment]
Support agent can enter email address of the target mailbox even is he/she does not have access to this mailbox.
