### ISSUE TITLE
Is there a chat backend?

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1618]
When a visitor initiate a chat from the website pop up, I will receive an email alert and the chat message will be created as an ticket, and I will have to reply that ticket in order to "chat" with the visitor, it's a bit slow to see the message to be reflected in the chat frontend, it's also slow to see the customer message in ticket. Shouldn't there be a dedicated chat backend as that's all other chat software does.

If it's supposed to work that way, then I think it's better to use another dedicated chat software, advise?

**Comment by alichakery** [comment]
Unfortunately this is how the current chat system works. I do prefer that we have a real on-premise chat service from Freescout than a chat/ticket system.

I would vote against other chat services as almost all have trackers in their js files ( not rocket chat).

**Comment by freescout-helpdesk** [comment]
There is no some special chat backend for now. Feel free to add a feature request: https://freescout.net/request-feature/
