### ISSUE TITLE
DMCA Violation

### ISSUE THREAD

**Issue by nfrancis** [freescout-helpdesk/freescout#162]
Hey folks, Nick here, co-founder and ceo at Help Scout. I'm creating an issue because, [as has been pointed out](https://github.com/freescout-helpdesk/freescout/issues/161), the owner(s) of this project seem to be anonymous. 

I've personally spent thousands of hours, and the last 7.5 years of my life crafting Help Scout with my co-founders. We, along with our 80+ colleagues around the world, care deeply for this product and the customers that use it. 

I have no intent to bully anyone. I have no problem with anyone that wishes to build an open source help desk that's inspired by Help Scout. I think that'd be great. But in my view, this project has crossed the line of inspiration into violation of our intellectual property. 

The screenshots and [commits like this one](https://github.com/freescout-helpdesk/freescout/commit/9f6da13a57b9508058d9327f0ca890dc326248b5) make it clear to me that portions of this project were copy/pasted. In addition, the design of Help Scout is our intellectual property, and surely it can't be disputed that this looks exactly like our product.

I'd like to propose that you take a reasonable amount of time to create a design and user experience that is completely unique to Freescout and does not violate our intellectual property. Hell, feel free to improve upon what we made! I think 90 days should be enough time, and I'd be happy to advise on this process if it's helpful. 

I don't want to take another route, but we are prepared to take legal action if necessary. I sure hope it doesn't come to that. Thanks for listening.

**Comment by freescout-helpdesk** [comment]
Hi. Thanks. We will try to do our best to make it unique.

**Comment by nfrancis** [comment]
Thank you! I sincerely appreciate it. If I can be helpful, my email is nick@helpscout.com. Best of luck with the project, I look forward to seeing some of the updates.

**Comment by sam3d** [comment]
I want to take the chance to congratulate and thank you both for handling this in such a professionally courteous and respectful manner.

I'm incredibly appreciative of the work you both do, and your esteem for open source software from both sides of the isle. You are exemplars of the open source community.

**Comment by nfrancis** [comment]
@freescout-helpdesk thanks for the update. Very nice progress.

**Comment by ptman** [comment]
are we past 90 days?

**Comment by nfrancis** [comment]
@ptman we are past 90 days. However, my intent is not to discourage development of this project, it is to protect our intellectual property. I've seen a good faith effort from @freescout-helpdesk to create an original design, which is enough to satisfy me as long as that work continues. Thanks to everyone involved!

**Comment by freescout-helpdesk** [comment]
Please re-open if needed.
