### ISSUE TITLE
Email fetch errors

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1620]
Lately I started to worry about such errors.

`Error: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate); File: /home/admin/domains/mydomain.com/public_html/overrides/Webklex/IMAP/Client.php (230)`

I can understand this is highly possible consider the retrieving would happen on every min (configured with a cronjob), and I actually receive about only 5 such errors every day.

However, what worries me is that, freescout accessed the mailbox, marks the new email as read, but the since error happened, it failed to fetch the mail to freescout, and it will NOT fetch it again (as it's read, not new). 

This has happened 3 times, anyone else have this issue?

Currently I have to login to the actual email account, mark those emails unread before freescout will fetch it again.

**Comment by freescout-helpdesk** [comment]
> However, what worries me is that, freescout accessed the mailbox, marks the new email as read, but the since error happened, it failed to fetch the mail to freescout, and it will NOT fetch it again (as it's read, not new).

FreeScout marks messages as READ only after they are successfully processed:
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L544
