### ISSUE TITLE
How to increase imap timeout?

### ISSUE THREAD

**Issue by jhrdt** [freescout-helpdesk/freescout#1621]
Hello,

when fetching email from an imap server, the connection has a timeout. I would like to increase the timeout to a longer period of time.

Is there an option to set the timeout, are there any additional settings? A code hack could also be an option.

```
$ php artisan freescout:fetch-emails
[2022-01-05 15:31:06] Fetching UNREAD emails for the last 3 days.
[2022-01-05 15:31:06] Mailbox: mbox
[2022-01-05 15:33:17] Error: imap_open(): Couldn't open stream {***:993/imap/tls}. Connection failed to ***,993: Connection timed out; File: /var/www/html/overrides/Webklex/IMAP/Client.php
[2022-01-05 15:33:17] Fetching finished
```

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
Here is how to implement it: https://github.com/Webklex/laravel-imap/commit/34830d91a5074f1d104c9eaeb01ab0204c0b240e#diff-fb7285264df0376b6cff6c9d1e5b439d0c233b2fa9668fbef17f0d62b32ef528R594

**Comment by cwoelkers** [comment]
Also curious on this. After adding the code mentioned in the laravel commit where would you set the timeout values?

**Comment by freescout-helpdesk** [comment]
Is it still needed?

**Comment by jhrdt** [comment]
> Is it still needed?

I solved the issue in a different way. Thank you, for the reminder. The ticket can be close.
