### ISSUE TITLE
Custom field workflow condition: Date custom field is more than X days in the past/future

### ISSUE THREAD

**Issue by LookitheFirst** [freescout-helpdesk/freescout#1625]
Right now it is only possible to specify that a date custom field is less than X days in the past/future
![image](https://user-images.githubusercontent.com/6774795/148439553-a7ffa18c-62b5-4f0f-ae79-cb685f21817e.png)
For my use case I need the opposite of that (warning when a bill is old)

Edit: Also there is no way to check if a date custom field is set, only if it is not set

**Comment by freescout-helpdesk** [comment]
Added the following Workflows Conditions: "Is set", "Is not in the next (days)", "Was not in the last (days)".
Make sure to update Custom Fields and Workflows Modules to their latest versions.
