### ISSUE TITLE
These folders must be writable by web server user

### ISSUE THREAD

**Issue by 100Perski** [freescout-helpdesk/freescout#1626]
Hello, we have an error when we try to make an error:
These folders must be writable by web server user: xyz.

Where user: xyz is the owner of the freescout installation folder.
It has read and write permission, so I don't know where this error came from.
The web server is Synology with Apache z PHP 7.4.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
