### ISSUE TITLE
Don't send notification mail when there are delivery problem

### ISSUE THREAD

**Issue by Zatalyz** [freescout-helpdesk/freescout#1629]
Hello,
I changed my mail provider, and he doesn't like me to use Freescout to send a message. I'm in the process of fixing the problem with him, but while I was doing that, Freescout kept sending notification mails, which were not delivered. So I moved to the next stage of the "too many messages sent in too short a time" block.

I had a similar problem before when activating the autoresponder, which had been looped through by a service across the street...

To avoid spam classification, it would be interesting if there was a "circuit breaker": if a box tries to send more than X messages in Y minutes, then it is temporarily disabled on sending, with a message to the administrators and a flag on the box (big flag for all user who connect on the service). Restarting the sending on mailbox would require a manual intervention, which would avoid being classified as spam  for long time if the system gets out of control when not monitored. 

Maybe we can configure trigger that "block" sending messages to avoid spam. 
- How many mail sending in how many time ?
- If some error messages are returned by the system (including all spam classification messages)
- other ?

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
Maybe someone will implement as a module.
