### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#163]
Hi everybody. As Nick [pointed out](https://github.com/freescout-helpdesk/freescout/issues/162) the application has to be redesigned to make it's design unique.

Feel free to send your design proposals to support@freescout.net in PNG/PSD format.

**Comment by infiniziconsulting** [comment]
Hi
My Team is interested in working with you. Please let me know, how can we start working on it.

**Comment by taoeffect** [comment]
> Redesign takes place right in the `master` branch, so you can just push your suggestions there

Hello @freescout-helpdesk, in light of [recent events](https://github.com/dominictarr/event-stream/issues/116) I strongly urge you to please reconsider those instructions and protect the `master` branch.

It is trivial for random contributors to introduce malware into this project if you allow anyone direct access to the project, and especially if you allow anyone to write to the `master` branch.

If you go into the Github project settings, it will allow you to prevent prevent push access to `master`, requiring that all changes be publicly reviewed via pull requests instead.

Please consider the safety of all of your users and in turn all of their customers and all of their data.

**Comment by freescout-helpdesk** [comment]
@taoeffect no worries, contributions are made via pull requests (see [project workflow](https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow))

**Comment by taoeffect** [comment]
OK, thanks, yes I think I misunderstood your comment. I understand now it to mean `master` branch *in the forked repo*. Thanks!

**Comment by guestisp** [comment]
I think that there is an issue with the right panel on the conversation (the one with customer details) on a mobile.

It is currently moved on the central panel, just above the conversation. This is making some confusion, it seems that a customer sent an empty reply (because the whole block gets the same style as each conversation message)

Is possible to make something different ?
