### ISSUE TITLE
Scheduled answer are view by client

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1630]
Hi,

When I scheduled an answer, I would like the client to see the answer only when I ve scheduled it and not before.
Today, the client is able to see my answer before my scheduled time which is an issue for time sensitive operations.

Could you do something about that?

Apparently, use sees it through preview somewhere.

Best regards

David

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the End-User Portal Module v1.0.21
