### ISSUE TITLE
API and Webhooks Active Module, Not Authorized?

### ISSUE THREAD

**Issue by adamsewell** [freescout-helpdesk/freescout#1632]
I'm testing the API and Webhooks module  out to pull some data out but I'm running into the message that I'm not authorized to make the request. 

`curl -X GET -G "https://freescout.domain.tld/api/conversations" -H "X-FreeScout-API_key: xxxxxxxxxxxxxxxxxxxxxx"` 

gives me `{"message":"Not Authorized"}`. 

I'm using the API Key from the Manage -> Settings -> API & Webhooks menu. 

Is this a bug or am I doing something wrong?

**Comment by freescout-helpdesk** [comment]
Misspelled authentication header name - "X-FreeScout-API_key"
It should be "X-FreeScout-API-Key"

**Comment by adamsewell** [comment]
Ha, thanks! That's what I get for coding on little sleep.
