### ISSUE TITLE
Rocket.Chat module connected but no notifications working

### ISSUE THREAD

**Issue by distresscode** [freescout-helpdesk/freescout#1633]
Hello,

I'm running FreeScout and Rocket.Chat via Cloudron. I installed the Rocket.Chat module in FreeScout and logged in with the Cloudron user in FreeScout. I can see the two channels I created in RC and have selected the appropriate one. 2FA is disabled for the RC users but enabled for the FreeScout agent. I'm getting no notifications in RC from FreeScout when I get new tickets. All boxes are checked in the settings for the RC module. There are no errors in the logs. What am I doing wrong?

**Comment by distresscode** [comment]
I forgot to mention that I disabled two-factor (both TOTP and email) in RC for all users.

**Comment by freescout-helpdesk** [comment]
You can try to debug it yourself or send us access to support@freescout.net
