### ISSUE TITLE
Restrict access to conversations based on tag/folder/department

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#1635]
Hello,

Is it technically possible to implement some access list for tags?

**Use case:**
- Create tags for each company department
- Set multiple additional emails for mailbox so that FreeScout can properly fetch messages
- Configure workflow to automatically set tags based on TO email
- Configure access list of users in order to prevent access to some conversations inside the same mailbox

It would be also nice to have the same restrictions work for custom folders, so that user can not see custom folders of the tags he has no access to. But users should be able to assign tag at the same time.

Or maybe better, this is an idea for a new module to handle different departments in the same mailbox ;-) I would be happy to purchase such module.
In such case there should be a section to configure departments so that conversations can be routed automatically based on TO email. There also should be a way to change department of the conversation manually.

**Comment by freescout-helpdesk** [comment]
Everything is possible. Feel free to add a feature request for now: https://freescout.net/request-feature/
