### ISSUE TITLE
Error after install Fatal error: Trait 'Illuminate\Support\Traits\Macroable' 

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#1636]
This is the first time I have tried to install freescount which I have tried to set up on a Siteground in a subdomain. The install  went through without any issue but when I try to access freescount from a web browser I get the following error:

Fatal error: Trait 'Illuminate\Support\Traits\Macroable' 

Any advice would be gratefully received

**Comment by freescout-helpdesk** [comment]
Which PHP version are you using?

**Comment by JSM25** [comment]
Just checked and the site is using PHP 7.4.27

**Comment by freescout-helpdesk** [comment]
It's hard to tell what can be the reason. You may need to investigate it yourself.

**Comment by freescout-helpdesk** [comment]
Have you managed to solve the issue?

**Comment by JSM25** [comment]
I have deleted everything and stated again on site ground and this time
it's install without any issues.

Modules have also installed which an issue and I am now enjoying it.

**Comment by freescout-helpdesk** [comment]
Good to know.
