### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by michelrietveldcom** [freescout-helpdesk/freescout#1637]
Hello,

I can't update FreeScout i get the following error:

![image](https://user-images.githubusercontent.com/67167657/149143850-9e0d50e2-df2e-41ce-80db-ec43e496eb05.png)

I hope someone can help me.

Thanks, Michel

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1606#issuecomment-1006295442
