### ISSUE TITLE
API Module: Change conversation details

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#1638]
Hello,

It may be there, but not documented...

Is there a way to change conversation status and other details like assignee, customer assignment, etc using API? If not, can you add those functions so that API can provide the same features as web interface?

Thank you.

**Comment by freescout-helpdesk** [comment]
There is no such method yet. Maybe it will appear with time.

**Comment by freescout-helpdesk** [comment]
Update Conversation method https://api-docs.freescout.net/#update-conversation has been added in API & Webhooks Module v1.0.31
