### ISSUE TITLE
Seemingly new Caddy error w/ Freescout

### ISSUE THREAD

**Issue by bcookatpcsd** [freescout-helpdesk/freescout#1639]
Caddy error message:

```
{"level":"error","ts":1642110056.1320677,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"http: wrote more than the declared Content-Length"}
```

Caddy config should you be interested.. 

```
{
        email name+caddy@domain.org

        servers :443 {
                protocol {
                        experimental_http3
                }
        }
}

{
}

http://10.20.0.21 {
        root * /usr/share/caddy
        file_server
        php_fastcgi unix//run/php-fpm7/php-fpm.sock
}

https://freescout.secure.domain.org {
        root * /srv/http/freescout/public
        file_server
        php_fastcgi unix//run/php-fpm7/php-fpm.sock

        tls name+caddy@domain.org {
                 protocols tls1.2 tls1.3
        }
        push

encode {
        gzip 1
        zstd
}
log {
        output stdout
        format single_field common_log
}
}
```

(pardon the formatting) 

 php-fpm7 -v
PHP 7.4.27 (fpm-fcgi) (built: Dec 18 2021 08:49:08)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

 caddy version
v2.4.6

Without the http3.. I would get 404 errors, which *I think* started when I went to 1.7.27.

Please let me know if I can help further..

**Comment by freescout-helpdesk** [comment]
Unfortunately we have not tested FreeScout with Caddy. So you may need to try to figure it out yourself.

**Comment by freescout-helpdesk** [comment]
If you'll find a solution feel free to share with us - we will add info to the Installation Guide.
