### ISSUE TITLE
Login form insecure on SWAG docker nginx reverse proxy

### ISSUE THREAD

**Issue by nemyhlol** [freescout-helpdesk/freescout#1640]
Have Freescout up and running in a docker alongside MariaDB and SWAG containers.

Everything works 100% perfect using the local IP.

I can get to the SSL secured login form from a cloudflare dns validated letsencrypt NGINX reverse proxy (SWAG) but attempting to fill the login information and entering, I receive a warning in chrome: 

"The information you’re about to submit is not secure
Because this form is being submitted using a connection that’s not secure, your information will be visible to others."

Clicking "Send Anyway" returns me to the blank login form.

Checking the chrome network tools it appears clicking the login button tries to forward the browser back to port 80, then nginx attempts to forward it to SSL, and that's when I get returned to the blank form.

I use the same SWAG setup on about 15 other containers and have never encountered this error before.

**Comment by nemyhlol** [comment]
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name *redacted*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.68.229;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}

**Comment by nemyhlol** [comment]
# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Proxy Connection Settings
proxy_buffers 32 4k;
proxy_connect_timeout 240;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
proxy_http_version 1.1;
proxy_read_timeout 240;
proxy_redirect  http://  $scheme://;
proxy_send_timeout 240;

# Proxy Cache and Cookie Settings
proxy_cache_bypass $cookie_session;
#proxy_cookie_path / "/; Secure"; # enable at your own risk, may break certain apps
proxy_no_cache $cookie_session;

# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;

**Comment by freescout-helpdesk** [comment]
Probably better to ask on https://github.com/tiredofit/docker-freescout
