### ISSUE TITLE
Add ability to print/export tickets without internal notes

### ISSUE THREAD

**Issue by jaydio** [freescout-helpdesk/freescout#1641]
Often times we have the need to export/print a ticket and send it to a customer for future reference. However, we do not want to include internal notes. So, an option to exclude internal notes would be great. Perhaps even the ability to exclude email addresses (CC/TO/FROM) from being exported as well.

**Comment by scout-devs** [comment]
For this we can create a custom addon which will provide ability to export tickets with/without notes, with/without email addresses. Please raise a support ticket so that we can take this forward. https://help.expresstech.io/help/700382701

**Comment by jaydio** [comment]
Done. Also, more than happy to financially support the development of such features.
