### ISSUE TITLE
How can one clear JS file's cache for a module?

### ISSUE THREAD

**Issue by alinmbb** [freescout-helpdesk/freescout#1645]
We have custom modules that have their own JS code.

I can see that on the page,  where the modules are used, all the JS code from modules is packed into some JS files inside /js/builds/.

When I deploy the code to a freescout instance, I deactivate the module, place the new module's files and then re-activate the module (as I notice that activate/deactivating a modules clears some cache in the code). 

I also bump the module.json version but to no avail. 

is there a way to either add versioning to the js file or a command to make sure the module's JS code is up to date?

**Comment by freescout-helpdesk** [comment]
Deactivate and activate the module is the only way to refresh module's JS. Or you can delete files from /js/builds/ manually or using some script.

**Comment by alinmbb** [comment]
I tried to remove the used JS files from the /js/builds folder. but upon page refresh, the file is recreated again with the same old content :) (all this while the Modules/<module_folder>/Public/js/module.js file is updated ).

Is there a way to add JS file versioning when registering JS files for a module ?

**Comment by alinmbb** [comment]
I have fixed my issue. 

The problem was that the module's public folders's symlink was not set properly (and such the symlink for that module contained old files). 

Thanks for the support.
