### ISSUE TITLE
Mailboxes with too many emails respond slowly.

### ISSUE THREAD

**Issue by bilalahmedkiani** [freescout-helpdesk/freescout#1646]
I have almost 20 mailboxes setup, but one of them with almost 150000 emails is slow to respond for some functions. For example it takes over 10 seconds to change the "status" of email, or to assign the email to someone. It also takes 10-12 seconds to send email after hitting the send button. It just keeps on showing "loading" icon. This only happens to mailboxes with too many email. Works fast for mailboxes with less conversations.

**Comment by freescout-helpdesk** [comment]
The only solution is to upgrade the server.

**Comment by bilalahmedkiani** [comment]
> The only solution is to upgrade the server.

@freescout-helpdesk By server, do you mean mail server or the host server where our app is being hosted?

**Comment by freescout-helpdesk** [comment]
Yes

**Comment by SecureCPU** [comment]
Where you able to resolve this?
We are experiencing the same thing.

I tried upgrade the freescout server.

CPU: 2 Core > 4 Core
Memory: 4GB > 8GB

didn't make a difference.

**Comment by freescout-helpdesk** [comment]
Try to search for bottlenecks using MySQL slow query log.

**Comment by SecureCPU** [comment]
I honestly not sure how to do that. Would there be someone who would be able to help me with this?

**Comment by SecureCPU** [comment]
> I honestly not sure how to do that. Would there be someone who would be able to help me with this?

I don't mind paying for support, just really need our support desk to work.

**Comment by freescout-helpdesk** [comment]
Here is how to enable MySQL slow query log: https://stackoverflow.com/questions/22609257/how-do-i-enable-the-mysql-slow-query-log

**Comment by freescout-helpdesk** [comment]
Also try to disable Reports Module (if you have it) and check.

**Comment by SecureCPU** [comment]
So I tried to disabling the reports module and it didn't make a difference.

I also booted a brand new vm and loaded a fresh instance of FreeScout on Ubuntu 22.04 with php8.2 and I had the same problem. Only had like 2 tickets (conversions) in the new instance of FreeScout and it had the same speed issue when making changed to a conversation.

**Comment by SecureCPU** [comment]
When I spoke to a developer on freelancer he wanted to change me $420 and make changes to the "core" files of FreeScout. But that doesn't sound right.
