### ISSUE TITLE
Images in private KB are publicly available

### ISSUE THREAD

**Issue by TobiasValeur** [freescout-helpdesk/freescout#1647]
In the knowledge base, in categories that are set to "Visible to support agents only", the images uploaded to these articles will be publicly available at their url regardless of login status.

**Comment by freescout-helpdesk** [comment]
We don't have an idea how this can be technically implemented. So this probably will stay as is.

**Comment by DavidAnderson684** [comment]
You would have to funnel all image accesses through a PHP script to check permissions, instead of via direct URLs.
