### ISSUE TITLE
LDAP SSO does not support multiple DNs

### ISSUE THREAD

**Issue by elpengo** [freescout-helpdesk/freescout#1650]
Hi,

While trying to setup the SSO on the LDAP module, I have not been able to make it working.
After debug, it seems the SSO only queries the base DN submitted in the "Bind DN" field and ignores the "DNs and Filters" field (only 1 in my case... and my users are in this DN :) ).

Freescout v1.7.27
LDAP Module: 1.0.18

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
Fixed in LDAP Integration Module v1.0.19
