### ISSUE TITLE
How to change SUBJECT of new user invite email?

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1652]
Hi

When a new user is added, you can send them an invite email with the create password link in it.

How so I modify the email SUBJECT line that is sent in this email?

Thanks

**Comment by freescout-helpdesk** [comment]
Not possible for now. Can be implemented for example by adding a parameter to config and .env

**Comment by jshrek** [comment]
Can I make this a FEATURE REQUEST?

**Comment by jshrek** [comment]
Related question... is there any kind of email hooks available in the API such as "before email sent" that would allow you to modify the subject before it is sent?

**Comment by njsubedi** [comment]
I believe so, because I used a plugin that added the ticket number to the subject automatically.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/3161806/150552158-dc3a381a-5b7a-47e6-addf-06c56210c3bd.png">

**Comment by jshrek** [comment]
@njsubedi Yes it looks like you could possibly modify $subject ... 

Is the plugin/module you @njsubedi are using available to be shared? I have some basic programming experience (simple wordpress plugins) so having a plugin to start with and modify is much easier than trying to start from scratch.

And I am also wondering if there is a list anywhere of all filters/hooks available for FreeScout?

Thanks

**Comment by njsubedi** [comment]
I don't think purchased FreeScout modules are meant to be shared. If you like, you can purchase the Ticket Numbers module and customize it to fit your needs.

**Comment by jshrek** [comment]
@njsubedi ok got it ... did not realize it was paid module. Thanks

**Comment by fulldecent** [comment]
Recommending to close issue as out of scope
