### ISSUE TITLE
Allow Sending Saved Replies in Workflow Email 

### ISSUE THREAD

**Issue by njsubedi** [freescout-helpdesk/freescout#1654]
There is no option to select saved replies when workflow needs to trigger an email. Adding the same email content in multiple workflows isn't scaling well. Thanks!

<img width="923" alt="image" src="https://user-images.githubusercontent.com/3161806/150385484-18a43342-2d72-4418-8cb8-c3d7d490be2b.png">

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/
