### ISSUE TITLE
Clicking on a conversation in the Global Mailbox opens a new tab/window

### ISSUE THREAD

**Issue by nickkelsey** [freescout-helpdesk/freescout#1656]
When in a specific mailbox, clicking on a conversation shows the conversation as expected in the existing window. However if the same operation of clicking on a conversation is done in the Global Mailbox it opens a new tab or window which isn't desired.

**Comment by freescout-helpdesk** [comment]
It's by design and won't change. See description at https://freescout.net/module/global-mailbox/

**Comment by MarkoD** [comment]
This has been fixed in the Global Mailbox module - by setting the following line in the .env file:

`GLOBAL_MAILBOX_TARGET_BLANK=false`
