### ISSUE TITLE
Modules cannot be loaded via Proxy

### ISSUE THREAD

**Issue by holema** [freescout-helpdesk/freescout#1657]
Hi,

In our internal installation, via a Web Proxy we cannot see any Module.
We bought now some licenses and cannot activate them.

Which domains so we need to allow via proxy or do we need to customize some config files?

**Comment by freescout-helpdesk** [comment]
Here is the url: https://freescout.net/wp-json/

**Comment by holema** [comment]
Thanks. Now it is working.
