### ISSUE TITLE
Kanban module throws SQL error

### ISSUE THREAD

**Issue by BullDoggen** [freescout-helpdesk/freescout#1658]
Just got FreeScout installed with some modules and when I try to open Manage for Kanban it throws and error page and writes to log: 

`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "union"
LINE 1: ...atus" asc, "last_reply_at" desc limit 11 offset 0 union sele...
                                                             ^ (SQL: select "conversations".* from "conversations" where "state" = 2 and "mailbox_id" = 1 and "status" in (1, 2) and "status" = 2 order by "status" asc, "last_reply_at" desc limit 11 offset 0 union select "conversations".* from "conversations" where "state" = 2 and "mailbox_id" = 1 and "status" in (1, 2, 3) and "status" = 3 order by "status" asc, "last_reply_at" desc limit 11 offset 0)`

I think that the error is the 2 order by's, which is incorrect. How to solve this?

**Comment by freescout-helpdesk** [comment]
What DB are you using?

**Comment by BullDoggen** [comment]
It _should_ be MySQL, but I can't confirm this 100% since I can't reach our admin currently and I don't have access to the servers. I can verify this later.

**Comment by BullDoggen** [comment]
Nope, it is running on postgreSQL

**Comment by freescout-helpdesk** [comment]
OK. We'll try to adjust the request for postgreSQL.

**Comment by freescout-helpdesk** [comment]
What are your PHP and PostgreSQL versions?

**Comment by freescout-helpdesk** [comment]
By some reason your PHP pdo driver does not wrap selects into parentheses like this: `(select...) union (select...)`

![2022-01-21_21-38-19](https://user-images.githubusercontent.com/40499291/150582246-21dc9d22-6311-4465-b3dc-a1020763f7fd.png)

**Comment by freescout-helpdesk** [comment]
Kanban Module v.1.0.2 is compatible with PostgreSQL now. We had to discard unions. This may make performance of Kanban boards very low on PostgreSQL.

If someone knows how to make unions work on PostgreSQL please let us know.
