### ISSUE TITLE
Custom Cron Job Command Not working

### ISSUE THREAD

**Issue by basit-afia** [freescout-helpdesk/freescout#1659]
We have added a new custom command in Freescout commands directory but its not running after provided time
example:

        $schedule->command('freescout:generate-close-coversation-report')
            ->everyMinute()
            ->withoutOverlapping();

**Comment by freescout-helpdesk** [comment]
If you want to run a custom cron job command you need to do it via custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
