### ISSUE TITLE
Ratings module sets default as "Not Good Rating"

### ISSUE THREAD

**Issue by tnewton1** [freescout-helpdesk/freescout#166]
Installed FreeScout to test and also installed the Ratings module. After activating and sending out a test reply, I noticed that by default the rating is set to "Not Good Rating" instead of a null rating (no rating). 

App Version | 1.0.7
Web Server | Apache
PHP Version | PHP 7.2.12

Screenshot:

![screen shot 2018-11-28 at 5 59 08 pm](https://user-images.githubusercontent.com/3200699/49188078-7e267300-f337-11e8-9f63-e1babbba2629.png)

**Comment by freescout-helpdesk** [comment]
Thanks. We will check.

**Comment by freescout-helpdesk** [comment]
We've checked: no rating set by default. Have you clicked on the rating links in the email?
```
`rating` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
```

**Comment by tnewton1** [comment]
Nope. That was literally after sending a reply out and before it even arrived in my inbox. I'll do some more testing.

**Comment by dipakcg** [comment]
@tnewton1 Tested this and unable to replicate the issue you've mentioned.

Did you update the module to it's latest release? Make sure you clear FreeScout cache and your browser cache as well before you retry.
