### ISSUE TITLE
LDAP filter in mailboxes with memberOf groups not applied

### ISSUE THREAD

**Issue by holzi1005** [freescout-helpdesk/freescout#1661]
Hi,

we use the LDAP integration in FreeScout and try to manage the permission of mailboxes via the LDAP filter in the mailboxes by setting the filter with memberOf.

However, none of the Filters works and the permissions are not updated with memberOf. Is it possible to use memberOf Filters in Mailboxes or in the LDAP Settings at all?

How do I need to setup the filters in mailboxes: __memberOf=cn=support,cn=groups,dc=example,dc=com__

**Comment by freescout-helpdesk** [comment]
Example: (&(memberOf=cn=demo,dc=freescout,dc=net))

**Comment by holzi1005** [comment]
Hm
I tried it with the & but where is no change to the permission.
My LDAP Service is based on Samba4 with AD extentions.

__Setting: LDAP__
LDAP Host: DNS Name
Port 636
Encryption: SSL
BindDN: cn=Users,DC=example,DC.com
DNs and Filters: DC=example,DC.com
Connect and Fetch Attributes: Works

Automatic Import: Checked
Users Permissions: None
Automatic Permission Sync: Checked
LDAP: Authentication: Checked

__Mailbox LDAP Setting:__
Filter based access: Checked
Filter: (&(memberOf=CN=test-group,CN=Users,DC=example,DC.com))

When I try to import the permission no users are updated or added
When I login, the users has no permission to access the mailbox.

**Comment by freescout-helpdesk** [comment]
Supported LDAP servers: Microsoft Active Directory, OpenLDAP, FreeIPA. Correct work of other servers we can't guarantee.

**Comment by elpengo** [comment]
Hi,

I have the issue too (Microsoft Active Directory). 

As Ldap module repo is not public, I can't send a possible workaround via these patch files to @freescout-helpdesk  (the workaround creates a bug that need Import file to be patched too --> user has to connect twice to be fully provisionned)

[LDAPMailboxAccessListener.patch.txt](https://github.com/freescout-helpdesk/freescout/files/7924178/LDAPMailboxAccessListener.patch.txt)
[Sync.patch.txt](https://github.com/freescout-helpdesk/freescout/files/7924179/Sync.patch.txt)
[Import.patch.txt](https://github.com/freescout-helpdesk/freescout/files/7924180/Import.patch.txt)

**Comment by freescout-helpdesk** [comment]
Thanks. See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by holzi1005** [comment]
@elpengo Thanks. Which this patch the permission via memberOf is working.
@freescout-helpdesk Can you add the required lines in the next module update, hence after the update the fix will still work.

**Comment by freescout-helpdesk** [comment]
Patches applied in LDAP Module v1.0.20
