### ISSUE TITLE
Search fails with Error (Undefined variable: sort_by)

### ISSUE THREAD

**Issue by AlbertMebus** [freescout-helpdesk/freescout#1662]
Search fails with "Whoops Error"

It's a new Setup on Ubuntu 20.04, PHP7.4, nginx with multiple mailboxes. Plenty of official modules installed.
User 1 is FS admin, profile does not show anything noticeable.
Any idea where this issue comes from?

----------------------------
Undefined variable: sort_by (View: /var/www/html/resources/views/conversations/conversations_table.blade.php) (View: /var/www/html/resources/views/conversations/conversations_table.blade.php) {"userId":1,"email":"itsm@m***g.de","exception":"[object] (ErrorException(code: 0): Undefined variable: sort_by (View: /var/www/html/resources/views/conversations/conversations_table.blade.php) (View: /var/www/html/resources/views/conversations/conversations_table.blade.php) at /var/www/html/storage/framework/views/16532119bf68b9a426d7745740f13f17a6eb7c09.php:57, ErrorException(code: 0): Undefined variable: sort_by (View: /var/www/html/resources/views/conversations/conversations_table.blade.php) at /var/www/html/storage/framework/views/16532119bf68b9a426d7745740f13f17a6eb7c09.php:57, ErrorException(code: 0): Undefined variable: sort_by at /var/www/html/storage/framework/views/16532119bf68b9a426d7745740f13f17a6eb7c09.php:57)

**Comment by luketrip** [comment]
I too have this problem (Search Broken and same errors in log) after recently upgrading to 1.7.28 over the weekend.  Also, the Global Mailbox for me is showing the same error - Do you have this module installed and can you replicate that it is broken for you also?

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by AlbertMebus** [comment]
> I too have this problem (Search Broken and same errors in log) after recently upgrading to 1.7.28 over the weekend. Also, the Global Mailbox for me is showing the same error - Do you have this module installed and can you replicate that it is broken for you also?

Can confirm, that we also have this Global Mailbox Error.
We uninstalled Global-Mailbox, because of this. I was not sure, if this is/was related to search error.
Will wait for a search-issue solution and re-install Global-Mailbox again. Issue might have a different reason.

**Comment by freescout-helpdesk** [comment]
We've released FreeScout 1.7.30

**Comment by AlbertMebus** [comment]
> We've released FreeScout 1.7.30

great!  Thank you.

**Comment by AlbertMebus** [comment]
Search issue fixed.
This fixed also Global-Mailbox issue.
Thanks
