### ISSUE TITLE
Getting blank screen while install of 1.7.29

### ISSUE THREAD

**Issue by GaneshKandu** [freescout-helpdesk/freescout#1665]
Hi.

I am trying to install freescout 1.7.29 but while accessing install page i am getting blank screen with below error.

```
[Mon Jan 24 03:05:17 2022] [error] [client 122.177.254.213] PHP Fatal error:  Uncaught ReflectionException: Class view does
 not exist in overrides/Illuminate/Container/Container.php:752\nStack trace:\n#0
 overrides/Illuminate/Container/Container.php(752): ReflectionClass->__construct('view')\n#1
 overrides/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('view')\n#2
 overrides/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('view', Array)\n#3
 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('view',
 Array)\n#4 vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110):
 Illuminate\\Foundation\\Application->make('view', Array)\n#5 vendor/laravel/framework/src/Illumina in
 overrides/Illuminate/Container/Container.php on line 752
 
```

PHP 7.1.33
MySQL 5.5.62
OS CentOS 7
Browser Firefox 96.0.2

**Comment by raramuridesign** [comment]
@GaneshKandu try install v1.7.30, this should work. If ok, please mark as solved and close this.

**Comment by j0urna1ist** [comment]
> @GaneshKandu try install v1.7.30, this should work. If ok, please mark as solved and close this.

Not work.

**Comment by rutger1140** [comment]
I can confirm 1.7.29 broke stuff (blank screen). After restoring from backups I upgraded to 1.7.30, with success. 

@freescout-helpdesk  Thanks for the quick fix!

**Comment by GaneshKandu** [comment]
> try install v1.7.30, this should work. If ok, please mark as solved and close this.

worked for me

**Comment by GaneshKandu** [comment]
@raramuridesign 
Thanks for quick fix!
