### ISSUE TITLE
1.7.29 update is broken

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#1667]
Hello,

Update to 1.7.29 is broken. It removes vendor folder which makes FreeScout unusable. All update methods are failed.

**Comment by densn93** [comment]
Same here

**Comment by megaerki** [comment]
Same here. Were you able to get it back?

**Comment by ilyakonovalenko** [comment]
> Same here. Were you able to get it back?

Yes. Just copy vendor folder to root dir from the dist.zip. It will return FreeScout back to normal.

**Comment by luketrip** [comment]
Same here. Reuploading Vendor folder restored Freescout however the update is not committed and I am still on 1.7.28

**Comment by megaerki** [comment]
Yes, that worked. Thanks.

**Comment by densn93** [comment]
For me too, thanks!

**Comment by j0urna1ist** [comment]
> Same here. Reuploading Vendor folder restored Freescout however the update is not committed and I am still on 1.7.28

Please specify which file you have restored ?

**Comment by luketrip** [comment]
Copy the Vendor folder from https://freescout.net/download/ and place into your main directory

**Comment by j0urna1ist** [comment]
> Copy the Vendor folder from https://freescout.net/download/ and place into your main directory

to the root?

**Comment by megaerki** [comment]
This is what I did. I'm not responsible if this blows something up. 

cd ~
mkdir freescoutrestore
cd freescoutrestore
sudo git clone https://github.com/freescout-helpdesk/freescout .
cp -R vendor /var/www/html/freescout/

**Comment by luketrip** [comment]
> > Copy the Vendor folder from https://freescout.net/download/ and place into your main directory
> 
> to the root?

Yes - where there are app, bootstrap, config, database, Modules, overrides, public, resources, routes, storage, tests, tools Folders.
I did this via FTP

**Comment by j0urna1ist** [comment]
> > > Same here. Reuploading Vendor folder restored Freescout however the update is not committed and I am still on 1.7.28
> > 
> > 
> > Please specify which file you have restored ?
> 
> Copy the Vendor folder from https://freescout.net/download/ and place into your main directory

Its work, THANKS!!!!!

**Comment by freescout-helpdesk** [comment]
FreeScout 1.7.30 has been released.

**Comment by j0urna1ist** [comment]
> FreeScout 1.7.30 has been released.

Not work ;\ my site trash....
HTTP ERROR 500

**Comment by densn93** [comment]
For us the update also didn´t work via System -> Update
It deleted the vendor folder again, quick fix was just uploading the vendor files again

**Comment by ilyakonovalenko** [comment]
> For us the update also didn´t work via System -> Update It deleted the vendor folder again, quick fix was just uploading the vendor files again

Works fine for me. Updated to 1.7.30 with no issues after uploading vendor folder from 1.7.29.

**Comment by j0urna1ist** [comment]
> Works fine for me. Updated to 1.7.30 with no issues after uploading vendor folder from 1.7.29.

Where to get the download for 1.7.29. Because if I do an update, I get 500error again

**Comment by j0urna1ist** [comment]
Did it like this:
1. Deleted vendor on the server.
2. Downloaded the vendor folder from the archive 1.7.30.
3. Uploaded to a server.
4. System -> Update.
Earned only this way, or Error500.
Thanks.
