### ISSUE TITLE
Freescout 1.7.30 redirecting to root

### ISSUE THREAD

**Issue by GaneshKandu** [freescout-helpdesk/freescout#1668]
Hi,

I have installed Freescout 1.7.30 and i am trying to login into it but it redirecting on root if installed in sub-directory.
if ```domain.com``` is domain and i have installed Freescout 1.7.30 on ```domain.com\sub-directory\freescout-dir``` and trying to login in it it redirects me to ```domain.com```

Redirection pattern
```domain.com\sub-directory\freescout-dir\login``` > ```domain.com\sub-directory\freescout-dir\home``` > ```domain.com```

**Comment by freescout-helpdesk** [comment]
You may need to debug it yourself. If you'll find a solution feel free to share.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/1688
