### ISSUE TITLE
whoops, looks like something went wrong

### ISSUE THREAD

**Issue by webspeed1** [freescout-helpdesk/freescout#1669]
HGi

Applied the latest update todat and now when going to see client conversations i get this page
![image (17)](https://user-images.githubusercontent.com/81991352/150780515-2ad53ba6-49d3-40d9-99f0-ea4ce649acfd.png)

**Comment by basselin** [comment]
I solved this problem by copying the "resources" folder _(after update failed)_.

**Comment by basselin** [comment]
In last zip release _(1.7.30)_, I copy the **resources** folder that I overwrite it on FTP.

**Comment by freescout-helpdesk** [comment]
Release 1.7.29 was broken, fixed by 1.7.30
