### ISSUE TITLE
Custom homepage

### ISSUE THREAD

**Issue by bladerunner2020** [freescout-helpdesk/freescout#1673]
I want to set end-user portal as custom homepage and add a menu item for agents so they can to login as well. Any idea how I could achieve this?

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/custom-homepage/ to create a custom homepage.

**Comment by bladerunner2020** [comment]
> Use https://freescout.net/module/custom-homepage/ to create a custom homepage.

That's what we did. We created a custom home page with two links - for end customers and for agents. The link for agents leads to /login page. 

But there is an issue with this approach. When an agent is logged in he is redirected to custom home page again and needs to press the link for agents once again. Any idea how to solve this?

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. After logging in user agent is redirected to dashboard.

**Comment by bladerunner2020** [comment]
I upgraded to the latest version and the issue has been resolved. Thanks!
