### ISSUE TITLE
Add option to view tickets by status

### ISSUE THREAD

**Issue by 42deluxe** [freescout-helpdesk/freescout#1675]
We switched from livezilla to Freescout. Great experience so far.

But we are missing one thing that was nice in Livezilla. Folders by status.

I've installed the module custom folders but I have to provide a tag. It would be great if this was optional. In this case there'd be an option to create the custom folders Active, Wating, Clodes to have a different view of the actual state of work.

Use case:
A customer calls me and I open a ticket for the issue. One of my colleagues can do it better so I assign the ticket to him.
This is happening 5-6 times within some days.

After some days I want to know how the status is. I don't remember the customers names but the issues and I just want to make sure that there is any progress (I am still the problem owner because I talked to the customer).

The easiest way to do this is to have a look at the "Closed" folder. Okay, ticket 1, 2, 3, 5 are closed, everything is fine.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
Also Kanban module already can show conversations by status: https://freescout.net/module/kanban/
