### ISSUE TITLE
error updating to 1.7.30.

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#1677]
Previous update had no issue and there is no change of hosting environment. 

When I try to update from 1.7.27 to 1.7.30, it failed and I get this message. 

"splFileinfo::isDIR(): open_basedir restriction in effect. 

Please advise.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1606#issuecomment-1006295442
