### ISSUE TITLE
Feature request - Adding Custom Folders

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#1679]
Hi, I'm trying to add custom folders to get more statuses but I can't figure it out, the following files contains my modifications but they do not display the conversations in the list on the global mailbox OR the new folders do not appear in the mailboxes

/global-mailbox/62
![image](https://user-images.githubusercontent.com/482210/151331214-fd2ae6fb-ccec-4635-8734-7f7babe0e514.png)

/mailbox/1/62
![image](https://user-images.githubusercontent.com/482210/151331297-d5b930a1-ace4-49b9-b142-ae4141d5d058.png)

[Folder.php.txt](https://github.com/freescout-helpdesk/freescout/files/7949249/Folder.php.txt)
[Conversation.php.txt](https://github.com/freescout-helpdesk/freescout/files/7949250/Conversation.php.txt)

**Comment by freescout-helpdesk** [comment]
For custom development address https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by davask** [comment]
Okay, so no plan to implement it as part of freescout as default feature. Too bad.
