### ISSUE TITLE
schedule:run task using 2% CPU all the time (+ maybe: too many `artisan schedule:run` processes)

### ISSUE THREAD

**Issue by taoeffect** [freescout-helpdesk/freescout#168]
My phpfpm setup allows up to 4 child processes to be spawned. So interestingly enough, there are also 4 instances of each of these commands:

```
php /var/www/freescout.git/artisan schedule:run
/usr/bin/php7 artisan queue:work --queue=emails,default --sleep=5 --tries=1
```

On top of that, each of these `schedule:run` commands uses ~2% of the CPU, so that's a minimum of ~8% CPU being used up while idling, and unclear why.

Also unclear to me what the purpose of the cron command (that runs every second) is, if the php script somehow runs several instances of this `schedule:run` as well?

EDIT: using latest 1.0.8 version.

**Comment by freescout-helpdesk** [comment]
This is the background heart of the app https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#background-jobs

**Comment by taoeffect** [comment]
So I'm confused:

- If the php code creates these processes, what is the reason for having cron run the same  command every second?
- Is there a way to either limit the amount of CPU they use (while doing essentially nothing), and/or is there a way to limit the number of processes launched?

**Comment by freescout-helpdesk** [comment]
Background tasks are fetchings emails and sending emails.
There should be max. 2 proceses running. If you have more, try to clear cache in System Tools.

**Comment by taoeffect** [comment]
I'll have a look... but some help on this would be appreciated. For instance, I still do not understand why, if you have a scheduler in the PHP.. why this cron task is necessary?

```
* * * * * php /var/www/freescout.git/artisan schedule:run >> /dev/null
2>&1
```

**Comment by taoeffect** [comment]
Strange, now in 1.0.9 there is only 1 `schedule:run` and 1 `queue:work` process running... Hopefully this has magically been fixed and won't come back.

I do not understand why the one `schedule:run` process is always idling at 2% CPU though, so I'll rename the issue title to address that.

**Comment by taoeffect** [comment]
OK, I think I will close this issue and re-open another one just focused on the 2% idle CPU usage since now it is only running those 2 processes as @freescout-helpdesk said it should. I don't know why it was running more before.

**Comment by kevinp1005** [comment]
@taoeffect did you find a solution for this ? I'm having the same issue here. It's running on Centos with supervisor. Do you have any suggestion what should I check here ?

```
ps auwwx | grep artisan | grep -v grep
root      1227  0.0  0.0 113176  1204 ?        S    11:34   0:00 /bin/bash /home/kevin/script/artisan-listen-to-queues.sh
root      1228  0.2  1.0 583688 41052 ?        S    11:34   0:01 /usr/bin/php /home/kevin/software/GXApp_Employee_Server/artisan queue:work --queue=checker,default,broadcaster,emails,fingerspot --tries=15 --timeout=0
kevin     1238  0.0  0.0 113176  1220 ?        Ss   11:35   0:00 /bin/sh -c /usr/bin/php  /var/www/html/GXApp_Employee_Server/artisan schedule:run >> /dev/null 2>&1
kevin     1239  0.1  1.0 583688 40896 ?        S    11:35   0:00 /usr/bin/php /var/www/html/GXApp_Employee_Server/artisan schedule:run
kevin     1265  0.0  0.0 113176  1220 ?        S    11:35   0:00 sh -c '/usr/bin/php' 'artisan' fingerspot:sync-attendance > '/dev/null' 2>&1
kevin     1266  0.0  1.0 583952 41384 ?        S    11:35   0:00 /usr/bin/php artisan fingerspot:sync-attendance
kevin     1604  0.0  0.0 113176  1216 ?        Ss   11:40   0:00 /bin/sh -c /usr/bin/php  /var/www/html/GXApp_Employee_Server/artisan schedule:run >> /dev/null 2>&1
kevin     1605  0.1  1.0 583688 40852 ?        S    11:40   0:00 /usr/bin/php /var/www/html/GXApp_Employee_Server/artisan schedule:run
kevin     1636  0.0  0.0 113176  1220 ?        S    11:40   0:00 sh -c '/usr/bin/php' 'artisan' fingerspot:sync-attendance > '/dev/null' 2>&1
kevin     1637  0.1  1.0 583952 41384 ?        S    11:40   0:00 /usr/bin/php artisan fingerspot:sync-attendance
kevin     1987  0.0  0.0 113176  1220 ?        Ss   11:45   0:00 /bin/sh -c /usr/bin/php  /var/www/html/GXApp_Employee_Server/artisan schedule:run >> /dev/null 2>&1
kevin     1988  0.5  1.0 583688 40752 ?        S    11:45   0:00 /usr/bin/php /var/www/html/GXApp_Employee_Server/artisan schedule:run
kevin     2016  0.0  0.0 113176  1220 ?        S    11:45   0:00 sh -c '/usr/bin/php' 'artisan' fingerspot:sync-attendance > '/dev/null' 2>&1
kevin     2017  0.2  1.0 583952 41892 ?        S    11:45   0:00 /usr/bin/php artisan fingerspot:sync-attendance
```

**Comment by taoeffect** [comment]
Somehow I must have because this is the output of that command on my machine:

```
/ # ps auwwx | grep artisan | grep -v grep
  586 freescou  1:06 php /var/www/freescout.git/artisan schedule:run
  656 freescou  0:01 /usr/bin/php7 artisan queue:work --queue=emails,default --sleep=5 --tries=1
```
