### ISSUE TITLE
[Inbox Module] Visually distinguish spam emails in "All" folder

### ISSUE THREAD

**Issue by LookitheFirst** [freescout-helpdesk/freescout#1680]
Right now in the "All" folder, it's really hard to skim the mails, because many emails are spam. 
I'm not against those emails being shown in the "All" folder, since they may contain false positives we want to catch, but it would be nice for them to be visually distinct.

Maybe we could add a setting:

- Show spam emails like normal emails
- Show spam emails in a lighter color (maybe even a custom color wheel?)
- Hide spam emails

**Comment by freescout-helpdesk** [comment]
Spam conversations made lighter.
