### ISSUE TITLE
No auto-reply mail sent

### ISSUE THREAD

**Issue by fabianhemmert** [freescout-helpdesk/freescout#1681]
Hello! 

I'm very happy with FreeScout – my instance has one hiccup, though:

Auto-replies are sent to the senders to one inbox, but not to another's (support German does work with auto reply, support English doesn't). The logs look fine, but the email doesn't seem to get sent:

![image](https://user-images.githubusercontent.com/11920748/151359609-937962a6-9c9e-40ab-aa2c-37cade5fc3d6.png)

This one works:

![image](https://user-images.githubusercontent.com/11920748/151359794-9cb44e0e-df16-41cc-bc99-e53725615ae1.png)
![image](https://user-images.githubusercontent.com/11920748/151359829-eea57072-c729-49df-9c4b-2176f41184cb.png)

This one doesn't:

![image](https://user-images.githubusercontent.com/11920748/151359934-d648ac47-3af6-4277-be11-6d2a3f579c29.png)
![image](https://user-images.githubusercontent.com/11920748/151359962-c3ebeee1-9de8-40d6-a101-6e85dca097d4.png)

Any ideas are welcome! Thank you!
Fabian

**Comment by freescout-helpdesk** [comment]
Check your mail server logs.

**Comment by fabianhemmert** [comment]
I found the issue there, the problem was on my end. Thanks!
