### ISSUE TITLE
User-facing language of end-user portal, widgets, etc.

### ISSUE THREAD

**Issue by tomatic** [freescout-helpdesk/freescout#1682]
I'm confused how FreeScout decides in which language to display the end-user portal and the contact form widget. If I open the end-user portal and I'm logged in to the FreeScout backend in the same browser session, the language of my user profile seems to be the determining factor, because when I switch that, the language also switches on the end-user portal.

But if I open the end-user portal in a different browser session where I'm not logged into the backend, the language seems to always adhere to the language setting of the end-user portal module and it seems to ignore the browser's language.

We serve customers in two languages (DE + EN) and we've set up the Konwledge Base in both these languages.  The KB has a separate URL per locale, e. g. .../en/hc/... for English, .../de/hc/... for German, etc. Is there a similar mechanism for the end-user portal and, for that matter, any other modules with user-facing elements?

**Comment by freescout-helpdesk** [comment]
You are right. If you are logged in as a user End-User Portal uses user's language. Otherwise it uses language from Manage -> Settings.

In order to set Contact Form language use "Language" parameter:

![2022-01-29_17-34-50](https://user-images.githubusercontent.com/40499291/151664986-f7dcdece-d8f1-4682-abaf-5f24bf600896.png)

**Comment by tomatic** [comment]
Is there a way to set the language dynamically through a URL parameter? Or, to make a suggestion, why not respect the browser language for not-logged-in users?

**Comment by freescout-helpdesk** [comment]
No plans for now. Feel free to add a feature request: https://freescout.net/request-feature/
