### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by HornTicketsystem** [freescout-helpdesk/freescout#1684]
Hello everyone.

I have this one problem: 

_SQLSTATE[HY000] [2002] No such file or directory {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)_

I have no idea, what this means. In the attachment you can find the log file.
[laravel-2022-01-28.log](https://github.com/freescout-helpdesk/freescout/files/7957231/laravel-2022-01-28.log)

**Comment by freescout-helpdesk** [comment]
Check DB host: https://stackoverflow.com/questions/39935545/symfony3-sqlstatehy000-2002-no-such-file-or-directory

**Comment by HornTicketsystem** [comment]
can closed.
