### ISSUE TITLE
Installation fails to complete when choosing MS SQL Server

### ISSUE THREAD

**Issue by edwardhughes** [freescout-helpdesk/freescout#1685]
Hi.  First, thanks for the work on the awesome project!  I'm excited to get it into production for my company, but I've run into an issue while experimenting with different setup options.

I have had a successful instance of Freescout running on a test server using a local MySQL database.  No problems, everything worked as expected.  I was delighted to see during installation that MS SQL Server was one of the supported databases, and our company's ERP system runs on SQL Server 2014.  If I were to use our SQL Server as the database backend, then many of the concerns about backups and other production practices would be already in place.  So, I blew away my local test instance, created a 'freescout' database on our SQL server, with new 'freescout' user and appropriate permissions, and attempted a clean install.

The first struggle was realizing that I needed to install Microsoft's PHP SQL drivers.  The second struggle was editing my openssl.cnf to adjust the default encryption ciphers.  As an aside, if SQL Server is supported by Freescout, little documentation was found to help me through this.

I proceeded to use the web installer, and when getting to the final page it ends with a 'Database Migration Error':

<img width="480" alt="Screen Shot 2022-01-28 at 9 06 32 AM" src="https://user-images.githubusercontent.com/1208710/151560674-3cc14792-dd7b-4643-8d91-00413cdda524.png">

I follow the instructions and run the console commands.  Clearing the cache is successful, but this is the response of the migrate command:

<img width="1149" alt="Screen Shot 2022-01-28 at 9 09 13 AM" src="https://user-images.githubusercontent.com/1208710/151561100-172f151d-839e-4efc-bade-b7223a86e106.png">

Out of curiosity, I opened SQL Server Management Studio and manually deleted the index mentioned.  After running the migrate command again, I then received a different SQL error:

`The object 'DF__conversat__email__6383C8BA' is dependent on column 'email_history'. (SQL: alter table "conversations" drop column "email_history")`

Again, out of curiosity, I manually deleted the referenced column constraint and tried to migrate once more.  This time the migration succeeded, but I have doubts that the database is in a usable state.  I am able to login with the admin credentials, but I have not attempted to use the application.

Oh, I am testing on a fresh install of Ubuntu 20.04 LTS.

Thanks.

Update: I once again started a new installation, this time I did not manually delete the trouble database objects, instead I ignored the error.  When I attempt to login to the application with the admin credentials I am redirected to the "Whoops, looks like something went wrong" error page.

**Comment by freescout-helpdesk** [comment]
Supported DBs are listed here: https://github.com/freescout-helpdesk/freescout#requirements

**Comment by edwardhughes** [comment]
I appreciate the link, but SQL Server is clearly included as a usable database during the application installation process.  Care to elaborate on the discrepancy?

**Comment by freescout-helpdesk** [comment]
Need to be removed from installation script.

**Comment by edwardhughes** [comment]
Simple enough.  Thanks for the clarification!
