### ISSUE TITLE
Workflow error

### ISSUE THREAD

**Issue by codezz** [freescout-helpdesk/freescout#1687]
Hi, I just bought the workflows module and I started setting three flows and all of them seem to fail when applying to previous conversations.
What I am doing is a simple workflow:
IF subject starts with
THEN add tag.
I am using the latest version of freescout. 
Thanks
Here is the log from the System:

Unknown named parameter $id {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Unknown named parameter $id at /var/www/freescout/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221)
[stacktrace]
#0 [internal function]: Illuminate\\Support\\Facades\\Facade::__callStatic()
#1 /var/www/freescout/app/Jobs/TriggerAction.php(42): call_user_func_array()
#2 [internal function]: App\\Jobs\\TriggerAction->handle()
#3 /var/www/freescout/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#4 /var/www/freescout/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/freescout/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/freescout/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#8 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#9 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#11 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#12 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#13 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#14 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#15 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#16 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#17 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#18 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#19 /var/www/freescout/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#20 /var/www/freescout/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/freescout/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/freescout/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#24 /var/www/freescout/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#25 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/freescout/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#27 /var/www/freescout/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/freescout/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#30 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#31 /var/www/freescout/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"}

**Comment by VacationTeam** [comment]
Can you post snippets of your workflow setup please?

**Comment by freescout-helpdesk** [comment]
Maybe something is wrong with FreeScout installation. Try to reinstall.
