### ISSUE TITLE
Allow installation into subdirectory

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#169]
App does not work properly when installed in subdirectory.

**Comment by dipakcg** [comment]
Glad to hear that you've opened the issue upon my request.

Again, you guys are awesome and doing a great stuff. Kudos 👍

**Comment by blkvlvt3** [comment]
I have installed 1.1.1. Made a symlink from /public to /public_html/subdir and changed the .env APP_URL to include the subdir. Installation seems fine, but there are a few issues loading resources. 

- Change Minify::stylesheet(...) and Minify::javascript(...) to include ->withFullUrl() in app.blade.php
- Add {{ config('app.url') }} to images in app.blade.php
- Polycast js needs to include full url
- ajaxSettings JS needs to include full url
- fonts need to be loaded from full url
- As well as img/loader-main.gif

Not sure how to work with git just yet, so thought I would mention it here.

**Comment by freescout-helpdesk** [comment]
Implemented
