### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by fabianhemmert** [freescout-helpdesk/freescout#1691]
Hello!

I tried upgrading my PHP to 8.1, but that would break FreeScout's functionality – is that currently the case, or is there something I should consider doing to make it work on 8.1?

Thank you!
Fabian

**Comment by freescout-helpdesk** [comment]
PHP 8.1 is not supported yet. We are planning to make FreeScout compatible with PHP 8.1
