### ISSUE TITLE
system/status page not working

### ISSUE THREAD

**Issue by fabianhemmert** [freescout-helpdesk/freescout#1692]
Hello!

I'm trying to access the 

system/status

page of my installation, but it only displays 

Whoops, looks like something went wrong.

– the functionality of the installation is otherwise fine. Which log can I check?

Thank you!
Fabian

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
