### ISSUE TITLE
HTTPS doesn't work

### ISSUE THREAD

**Issue by HornTicketsystem** [freescout-helpdesk/freescout#1693]
We have another problem. 

We have successfully enabled HTTPS, but we can only reach the page via HTTP.

With Https:
![image](https://user-images.githubusercontent.com/98578618/151990718-7b371344-0b5f-41d7-9d5b-6f7d50144e50.png)

With Http:
![Screenshot 2022-02-01 154950](https://user-images.githubusercontent.com/98578618/151991227-14107945-d873-42b4-84fe-0de05a715d21.png)

What can we do?

**Comment by VacationTeam** [comment]
That is a server issue most likely.
Are you forcing HTTPS redirect on all requests via your .htaccess?

**Comment by HornTicketsystem** [comment]
We have fixed the problem.
