### ISSUE TITLE
"Reply" icon pointing to the right

### ISSUE THREAD

**Issue by fabianhemmert** [freescout-helpdesk/freescout#1699]
The 'reply' icon points to the right:

![image](https://user-images.githubusercontent.com/11920748/152324933-46254a94-c7d6-4517-9d58-60948caa463f.png)

I think that a leftward-pointing arrow would be more intuitive, as in left-to-right reading countries, the left side is considered the origin. It's also the same direction as in most email software I'm familiar with (Outlook, GMail, ...). The arrow pointing to the right is mostly used for 'forwarding'.

**Comment by pmhtuk** [comment]
Never noticed this before but now I'm aware of it, the icon does stick out

Especially as the forward icon is an arrow too - would +1 for the arrow to be flipped!

![image](https://user-images.githubusercontent.com/80200406/152354889-8267ef87-1cd3-4735-b1da-19e40956db62.png)
