### ISSUE TITLE
Spam Filter Module: whitelist domains e.g. *@example.com

### ISSUE THREAD

**Issue by XtomtomX** [freescout-helpdesk/freescout#1701]
We like the spam filter module very much. It would be a nice addition if there is a "whitelist entire domains" feature. This would prevent one's own company mails from being wrongly marked as SPAM.

**Comment by sebix** [comment]
Ideally that could be combined with an autolearn feature like in spamassassin & co.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
