### ISSUE TITLE
1.8.0 upgrade broke ability to add or edit workflow

### ISSUE THREAD

**Issue by blykins-twr** [freescout-helpdesk/freescout#1702]
After upgrading to version 1.8.0 earlier today, I receive a whoops message when trying to update and save existing workflows. And I receive a whoops message when trying to re-open newly created workflows. Thankfully, existing workflow rules are still working. Here is information from the log:

Undefined index: type (View: /var/www/html/freescout/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) (View: /var/www/html/freescout/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) {"userId":1,"email":"noreply@gmail.com","exception":"[object] (ErrorException(code: 0): Undefined index: type (View: /var/www/html/freescout/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) (View: /var/www/html/freescout/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) at /var/www/html/freescout/storage/framework/views/03d3524595a77eca0486bce607474f4174383105.php:64, ErrorException(code: 0): Undefined index: type (View: /var/www/html/freescout/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) at /var/www/html/freescout/storage/framework/views/03d3524595a77eca0486bce607474f4174383105.php:64, ErrorException(code: 0): Undefined index: type at /var/www/html/freescout/storage/framework/views/03d3524595a77eca0486bce607474f4174383105.php:64)

**Comment by eliassader** [comment]
Also confirmed from my side, thank you for your help

**Comment by freescout-helpdesk** [comment]
Your PHP versions?

**Comment by freescout-helpdesk** [comment]
Fixed in FreeScout 1.8.1.
Non-openable workflows may need to be deleted directly in the DB - `workflows` table.

**Comment by raramuridesign** [comment]
Thanks @freescout-helpdesk

**Comment by eliassader** [comment]
Thank you it worked
Appreciate the swift reaction

Please the SSO / oAuth or SAML for Customers is critical

Thanks

**Comment by blykins-twr** [comment]
Thank you so much for the extremely rapid fix on this. Blessings to the FreeScout team!!!
