### ISSUE TITLE
Customers Single Sign On / AuzreAD Oauth / SAML

### ISSUE THREAD

**Issue by eliassader** [freescout-helpdesk/freescout#1704]
We are seeking to have SSO for the users and customers as it will be used internally in the organization.
It would be great to share such possibility or the options to apply, i have managed to activate the OAuth via a community plugin.
Thank you for your help

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
You want FreeScout as an Identity Provider(IdP) or Service Provider (SP)?

![SAML+2 0+architecture+Security+assertion+markup+language+(SAML+2 0)](https://user-images.githubusercontent.com/40499291/153859646-56f08204-c9b7-414f-bd56-4340abdc231d.jpg)

**Comment by PatrickHuetter** [comment]
@freescout-helpdesk using your official SAML module: Is it possible to let **customers** log in via IdP? We would like to use the knowledge base internally, so login is needed. But it would be nice if customers (interested people in the knowledge base) could login via existing IdP (keycloak).
