### ISSUE TITLE
Editor won't save on raw view

### ISSUE THREAD

**Issue by NedScott** [freescout-helpdesk/freescout#1705]
If you are viewing the raw formatting of a Saved Reply, make changes, then hit save, it will not save. One must first exist the raw view, and then it will save.

**Comment by ilyakonovalenko** [comment]
This is not only related to saved replies. The same is for mailbox signatures and everything related to wysiwyg.

**Comment by ilyakonovalenko** [comment]
It seems the issue can be fixed with https://github.com/summernote/django-summernote/issues/127#issuecomment-268687206
From what I can see, editor mode check can be added to get html content in case raw mode is active.

**Comment by freescout-helpdesk** [comment]
Fixed.
