### ISSUE TITLE
UPGRADE issues 1.8.0 to 1.8.1 

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1706]
@freescout-helpdesk Get this issue when upgrading

![image](https://user-images.githubusercontent.com/902376/152492359-fea7953c-298f-4748-8226-e4b8f5c2e503.png)

https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.1

**Comment by ChrisRAoW** [comment]
Same here

**Comment by raramuridesign** [comment]
@freescout-helpdesk 1.8.2 Update still produces the same error above.

**Comment by freescout-helpdesk** [comment]
Fixed in 1.8.2

To update to 1.8.2 use [Method 3. Update using GIT](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-3-update-using-git) or [Method 5. Update manually](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually)

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
Last time we used GIT, it caused a major headache - loosing all the attachments - it seems this process clears out all the directories including the critical attachments.

Will try method 5, never used it but seems doable.
Why wont update work in backend?
M

**Comment by ChrisRAoW** [comment]
@raramuridesign For me it worked. But always make a backup....just in case.

**Comment by raramuridesign** [comment]
Thanks @ChrisRAoW I have used method 5.
Then it worked.

@freescout-helpdesk Thanks for the quick assist this morning.
