### ISSUE TITLE
set up email accounts on freescout 

### ISSUE THREAD

**Issue by bechirgh** [freescout-helpdesk/freescout#1707]
I'm having trouble setting up the corporate email account on freescout; I can't send or receive messages.

imap_open(): Couldn't open stream {mail.-------------.net:995/pop3/ssl}. Certificate failure for mail.-----------.net: Hostname mismatch: /C=US/ST=Michigan/L=Ann Arbor/O=A2 Hosting, Inc./CN=*.a2hosting.com

i need some help please

**Comment by ilyakonovalenko** [comment]
Set Validate Certificate to off.

**Comment by freescout-helpdesk** [comment]
We hardly can help here.
