### ISSUE TITLE
Too Many Redirects Error when using HTTPS Protocol

### ISSUE THREAD

**Issue by 23brewert** [freescout-helpdesk/freescout#1708]
Hello, I used the cert bot in the installation wizard to enable HTTPS, but when I finished the installation I cannot access the installation page because of "Too Many Redirects". I use Cloudflare but I have it set to DNS only mode. Does anyone know how to resolve this?

**Comment by freescout-helpdesk** [comment]
Have you managed to solve?

**Comment by 23brewert** [comment]
no, i quit trying freescout
