### ISSUE TITLE
Looking to use FreeScout to manage graphical design jobs accross customers

### ISSUE THREAD

**Issue by ensey** [freescout-helpdesk/freescout#1712]
I just discovered FreeScout, and it has peaked my interest, with the Open Source approach, with the modules available at one-time purchases.

I work at a company that serves B2B customers in the bar / pub business. We sell beverages and drinks - and as a service, we have a graphical designer employed, that will help customers with designing custom flyers and posters for advertising.

Usually the workflow is;
Account Manger or Graphics Manager (me) receives a assignment. Account Managers will forward it to me.
I will create the job in Trello, as the Kanban view is very nice. I will tag the designer in the job
He will do the job, attach the images and request proof reading.
I forward the proof-reading to the customer or Account Manager.
If everything checks out, the approval is received and it's printed out.

I really want to streamline this process, as it is tedious to work as the middle-man.

So I was hoping FreeScout could be the base I build upon.

I am hoping for features along the lines of;
A custom form that Account Managers can fill out, with the various flyers needed.
The form automatically creates the case
Case is assigned to designer
Either I do, or the images is automatically sent to the customer for proof.
Ideally, the proof-reading recipient is sent a link to review the files and add comments.
The approval or comments are received and workflow adjusts accordingly.

I know the whole proof thing is something special, but it's something I'd be ready to pay for at a 3rd party developer.
Something along the lines of "Your assignement is ready, check this link:"
The mage lists the assignement individually for comments or approval
and this updates a comparable view in the FreeScout case.

So my questions is; 
Is the FreeScout platform suitable for something running as custom as I am looking for?
Is it even possible?

Any suggestions or advice is welcome!

**Comment by freescout-helpdesk** [comment]
Everything is possible via custom modules: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development

**Comment by ensey** [comment]
Is there a list of developers that can make custom modules - or how to I go about having one developed for me?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
