### ISSUE TITLE
Update process 1.8.4 Question

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1716]
@freescout-helpdesk can 1.8.3 or 1.8.0 or 1.8.1 be updated using the backend update process to 1.8.4?

M.

**Comment by raramuridesign** [comment]
@freescout-helpdesk I have used the manual method for now.
But would love feedback on this. 
Thank you.

**Comment by freescout-helpdesk** [comment]
Releases 1.8.0-1.8.4 are making FreeScout compatible with PHP 8.1. It involves changing files structure.

On some servers/systems updating via Manage > System will work, on some - not. Just follow general instruction: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks for the Information, appreciate this!
