### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by j0urna1ist** [freescout-helpdesk/freescout#1717]
I wanted to translate modules. And here is such a problem. No option to resize (reduce)
![2](https://user-images.githubusercontent.com/92985454/152807329-86d9f686-ac89-4b3b-a486-13b19d1c48d9.jpg)
![1](https://user-images.githubusercontent.com/92985454/152807333-1771b5fb-1d5e-4046-9eb4-7e32222c5cb7.jpg)

**Comment by freescout-helpdesk** [comment]
You browser, PHP and FreeScout version?

**Comment by j0urna1ist** [comment]
> You browser, PHP and FreeScout version?

Opera, Firefox, Chrome, PHP 7.1.33, 1.8.4.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. If you have development skills try to debug it.
