### ISSUE TITLE
updating version 1.8.3 to 1.8.4 destroys the site

### ISSUE THREAD

**Issue by onderzoekspraktijk** [freescout-helpdesk/freescout#1718]
The recent update to version 1.8.3 was eventfull, but the site recovered after signalling several error messages. Today the update to 1.8.4 that was created to solve issues created at install exactly these issues and now really destroyed the site.

Will there be an alternative less destructive update in the near future?

Cheers,
Paul

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1716#issuecomment-1032259287
