### ISSUE TITLE
Tickets without CSS

### ISSUE THREAD

**Issue by janselato** [freescout-helpdesk/freescout#1719]
HI, i have problem with mails. 
Mails created from freescout:
![image](https://user-images.githubusercontent.com/99269288/153011449-b9e71451-acbe-4f06-a925-6fad202a4158.png)

This message is difficult to read. Can you create new setting to fetch mails with original css?
Original message:
![image](https://user-images.githubusercontent.com/99269288/153011422-dcaa45ed-c607-4e91-933b-69a3a704fbaa.png)

**Comment by ilyakonovalenko** [comment]
I think it is actually better to display text version by default. And HTML version as an option. HTML version is not safe, at least. And it is usually hard to read, as some CSS styles are removed.

**Comment by janselato** [comment]
I know it's not safe, but this solution don't better. 
I think, better add option in settings system to change default viewing tickets.

**Comment by ilyakonovalenko** [comment]
> I know it's not safe, but this solution don't better.

Current HTML view is not looking good as well :-) Not sure if text view can be implemented via module hooks and filters, anyway it would be nice, simple and useful to have text view in core.

**Comment by freescout-helpdesk** [comment]
We'll leave this as `help wanted`. If someone can come up with some secure and reliable solution which would preserve original ticket's CSS please share.

**Comment by janselato** [comment]
@freescout-helpdesk 
Is it solution?
https://content-security-policy.com/style-src/

**Comment by ipruthi** [comment]
> @freescout-helpdesk Is it solution? https://content-security-policy.com/style-src/

@janselato, I think the CSS feature asked on this thread has to do with inline CSS not being rendered by Freescout, not remote CSS files.

But thanks for `style-src` though, I didn't even know it existed!

**Comment by zigojacko** [comment]
I agree that I would prefer to be able to set default Text/HTML emails in the settings if anyone would like to take this on as a module or something...? 😂

**Comment by freescout-helpdesk** [comment]
It looks like there is no a solution for this.

**Comment by verygoodplugins** [comment]
I stumbled on this issue earlier today and solved it (for us). You can edit the allowed HTML and CSS in `/config/purifier.php`. After editing, run `php artisan config:clear` to clear the cache. 

According to the guidelines this will be safe between updates: https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#development-guidelines
