### ISSUE TITLE
no css no images after migration

### ISSUE THREAD

**Issue by klarahimmel67** [freescout-helpdesk/freescout#1722]
Hallo,
i copied a new installation of freescout into another folder of my apache and accessed it with a new domain, i also copyed the database to have a dev environment. Server configuration works. I change the .env file (APP URL and database settings) and i cleared the cache succesfully. Despite this my copied app has no image and no css. Can anybody help? I don't know where to search for the solution.

i have an error message in the console:
Uncaught ReferenceError: initWorkflowsBulk is not defined
could it be that it is not possible to copy the app because of some licence reasons ?

**Comment by klarahimmel67** [comment]
[SOLVED]
i had to copy the symbolic links of public/modules with cp -P 
now the dev-copy of the app is working.

**Comment by freescout-helpdesk** [comment]
Congratulations.
