### ISSUE TITLE
Items in mailbox but states 'no conversations here'

### ISSUE THREAD

**Issue by malgrauk** [freescout-helpdesk/freescout#1723]
This is a new one this morning - anyone come across this?

Cannot see anything in logs, but know and can see there's emails waiting in the unassigned.

Same happens on different pc and browser.

![image](https://user-images.githubusercontent.com/80200406/153185418-c9c8ceb0-5880-4d4c-8c3c-9de1d1bea6ec.png)

**Comment by pmhtuk** [comment]
If I go into 'Mine' I can see the one email which is there, and also in other boxes (closed, spam etc) but not unassigned

**Comment by freescout-helpdesk** [comment]
Are you using non-official modules?
Also check errors in logs.

**Comment by pmhtuk** [comment]
No, we've around 14 official ones only.

After about 30-40 minutes they reappeared yesterday and then had gone again mid afternoon. The emails are there, they just keep going - not sure if it's ongoing cache issues but the log appears to suggest it's the slack module again. This is updated to the latest version, too.

![image](https://user-images.githubusercontent.com/80200406/153361614-fe0be964-0fd9-4253-a4f5-ec37ffa98e11.png)

**Comment by freescout-helpdesk** [comment]
Have you deleted from user directly from the DB?

**Comment by pmhtuk** [comment]
No. We don't delete anyone from the system - neither customer or administrator

**Comment by pmhtuk** [comment]
Only thing we have deleted was a mailbox around 2-3 days ago as we didn't use it anymore

**Comment by freescout-helpdesk** [comment]
The error in Slack fixed in Slack Module v1.0.10. But this not necessarily the reason of your problem with counters.

**Comment by freescout-helpdesk** [comment]
Also try to updates FreeScout files. Maybe some of the previous updates was not fully successfull.
