### ISSUE TITLE
login without receiving an email?

### ISSUE THREAD

**Issue by klarahimmel67** [freescout-helpdesk/freescout#1724]
hallo,
i have a question about the email-verification when i want to see all my tickets.
to get logged in i have to add my email adress in the form field and hit the send button.
then i have to receive the email and i have to click on a login button inside the email to get logged in.

is there a plugin out there that can simplify this? it would be nice if one could login without receiving an email.
or is it possible to change settings to change that login procedure?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. See these:
https://freescout.net/request-feature/
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
