### ISSUE TITLE
Error: Woocommerce module not loading URL fully

### ISSUE THREAD

**Issue by maxmueller89** [freescout-helpdesk/freescout#1727]
Following was sent on the **17th of January** to support@freescout.net

______________________________
I would like to report a bug. 

We are using: 
- Freescout 1.7.27
- Everything is in the green at our installation site https://service.spannsysteme.shop/system/status
- Module: Woocommerce (it has been working until lately) - up to date

Issue: the orders in a conversation are not directing to the correct Woocommerce order site. It is missing the domain and therefore e.g. links to https://wp-admin/post.php?post=18237&action=edit eventhough the shop is https://fairschenkt.at/ and linked in the settings.

I have attached some screenshots.
______________________________

On **23rd of January** we granted access to the support staff.
After no response we inquired again on the **31st of January**.
Until today, the **15th of February**, no response.

This is what the links of the orders look like --> 

![Screenshot 2022-02-15 094657](https://user-images.githubusercontent.com/6640237/154025603-87d1439e-2cb8-4650-b49a-345206b4a518.png)

Can somebody reach out to a support staff what is going on?

**Comment by freescout-helpdesk** [comment]
This issue has been fixed in WooCommerce Module v1.0.3: https://freescout.net/module/woocommerce/?changelog=1

**Comment by maxmueller89** [comment]
Thank you. Would have been nice to get a response on my email lol 

Have a nice day.
