### ISSUE TITLE
Webhook not sending body?

### ISSUE THREAD

**Issue by megaerki** [freescout-helpdesk/freescout#1729]
Current system version:
System 1.8.4
Web Server | nginx/1.14.0
PHP 7.2.24-0ubuntu0.18.04.10
API and Webhooks Active Version: 1.0.34

Using webhooks to log things in AWS send notifications. 

**Everything was working 2 weeks ago on last versions of 1.7 of Freescout:**
- Event from freescout: {'version': '1.0', 'resource': '/....api-gateway', 'path': '/default/...api-gateway', 'httpMethod': 'POST', 'headers': {'Content-Length': '11766', 'Content-Type': 'application/hal+json', 'Host': 'blablabla.amazonaws.com', 'User-Agent': 'GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.24-0ubuntu0.18.04.10', 'X-Amzn-Trace-Id': '...', 'X-Forwarded-For': '...', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https', 'X-FreeScout-Event': 'convo.agent.reply.created', 'X-FreeScout-Signature': '....'}, 'multiValueHeaders': {'Content-Length': ['11766'], 'Content-Type': ['application/hal+json'], 'Host': ['....amazonaws.com'], 'User-Agent': ['GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.24-0ubuntu0.18.04.10'], 'X-Amzn-Trace-Id': ['...'], 'X-Forwarded-For': ['...'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https'], 'X-FreeScout-Event': ['convo.agent.reply.created'], 'X-FreeScout-Signature': [']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'requestContext': {'accountId': '...', 'apiId': '...', 'domainName': '....amazonaws.com', 'domainPrefix': '...', 'extendedRequestId': '...', 'httpMethod': 'POST',  'pathParameters': None, 'stageVariables': None,
  '**body**': '{"id":2706,"number":2683,"threadsCount":4,"type":"email","folderId":3,"status":"pending","state":"published","subject":"...","preview":"...","mailboxId":1,"assignee":{"id":1,"type":"user","firstName":"...","lastName":"...","photoUrl":"...","email":"..."},"createdBy":{"id":35,"type":"customer","firstName":"...","lastName":"...","photoUrl":"","email":"..."},"createdAt":"2022-02-03T08:34:05Z","updatedAt":"2022-02-03T09:45:38Z","closedBy":null,"closedByUser":null,"closedAt":null,"userUpdatedAt":"2022-02-03T09:45:38Z","customerWaitingSince":{"time":"2022-02-03T09:45:38Z","friendly":"Just now","latestReplyFrom":"user"},"source":{"type":"email","via":"customer"},"cc":["..."],"bcc":[],"customer":...

**From current version:**
{'version': '1.0', 'resource': '/...', 'path': '/default/...api-gateway', 'httpMethod': 'POST', 'headers': {'Content-Length': '0', 'Content-Type': 'application/hal+json', 'Host': '...', 'User-Agent': 'GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.24-0ubuntu0.18.04.10', 'X-Amzn-Trace-Id': '..., 'X-Forwarded-For': '...', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https', 'X-FreeScout-Event': 'convo.agent.reply.created', 'X-FreeScout-Signature': '...'}, 'multiValueHeaders': {'Content-Length': ['0'], 'Content-Type': ['application/hal+json'], 'Host': [....amazonaws.com'], 'User-Agent': ['GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.24-0ubuntu0.18.04.10'], 'X-Amzn-Trace-Id': ['...'], 'X-Forwarded-For': ['....'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https'], 'X-FreeScout-Event': ['convo.agent.reply.created'], 'X-FreeScout-Signature': ['...']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'requestContext': {'accountId': '...', 'apiId': '...', 'domainName': '....amazonaws.com', 'domainPrefix': '....', 'extendedRequestId': '....', 'httpMethod': 'POST', 'identity': {'accessKey': None, 'accountId': None, 'caller': None, 'cognitoAmr': None, 'cognitoAuthenticationProvider': None, 'cognitoAuthenticationType': None, 'cognitoIdentityId': None, 'cognitoIdentityPoolId': None, 'principalOrgId': None, 'sourceIp': '....', 'user': None, 'userAgent': 'GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.24-0ubuntu0.18.04.10', 'userArn': None}, 'path': '/....-api-gateway', 'protocol': 'HTTP/1.1', 'requestId': '...', 'requestTime': '15/Feb/2022:12:58:16 +0000', 'requestTimeEpoch': 1644929896009, 'resourceId': '...', 'resourcePath': '...y', 'stage': 'default'}, 'pathParameters': None, 'stageVariables': None, **'body': None**, 'isBase64Encoded': False}

**Only logs that I see in laravel log are:**
[2022-02-15 15:00:21] production.ERROR: Webhook: https://....amazonaws.com/default/...api-gateway (0) | Event: convo.note.created | Error: Server error: `POST https://....amazonaws.com/default/...api-gateway` resulted in a `500 Internal Server Error` response:

**This is from our AWS due to body being missing.** 

**This I get a lot as well, not sure if connected.**
[2022-02-15 15:00:28] production.ERROR: Call to a member function getFullName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getFullName() on null at /var/www/html/freescout/Modules/Chat/Http/Controllers/ChatFrontendController.php:287)

Thanks.

**Comment by freescout-helpdesk** [comment]
Fixed in API & Webhooks Module v1.0.35

**Comment by lpadula** [comment]
Hi, i have the same problem but with version 1.0.37
