### ISSUE TITLE
rating module should honor "Spread the world" setting

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#173]
Currenlty, the rating module doesn't honor the spread the world setting and it always add a "Powered by" footer on the web page.

I think that the module should honor the global settings too...
This module is not on github, thus we can't fix it.

**Comment by freescout-helpdesk** [comment]
Thanks. Will be updated.

**Comment by freescout-helpdesk** [comment]
Implemented in satisfaction ratings 1.0.1
