### ISSUE TITLE
Custom domain for knowledge-base

### ISSUE THREAD

**Issue by JorgeGNL** [freescout-helpdesk/freescout#1730]
This is a feature request for the knowledge-base module.

Custom domain feature is missing,  this allows every mailbox to have own knowledge-base using own domain name.

Adding custom domain by creating a CNAME Record.

**Comment by JorgeGNL** [comment]
The same for End-User Portal module.

**Comment by freescout-helpdesk** [comment]
Feature requests: https://freescout.net/request-feature/
