### ISSUE TITLE
Helpdesk crashed after updating to 1.8.5

### ISSUE THREAD

**Issue by imarklee** [freescout-helpdesk/freescout#1731]
After updating to 1.8.5, freescout is just displaying a blank page. Anyone faced with similar problems?

I updated by clicking on the update link under System > Manage.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1716#issuecomment-1032259287

**Comment by imarklee** [comment]
Thanks, it looks like after re-uploading the /vendor/ folder, it works again.
