### ISSUE TITLE
Search for active status does not only return conversations in active status

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1732]
I am using this search. And you can see from this screenshot even one of the results is in the deleted state.

<img width="1532" alt="Screen Shot 2022-02-15 at 09 28 43" src="https://user-images.githubusercontent.com/382183/154082413-e6f5d4fa-3556-4d28-9973-fa2ff225e1f7.png">

**Comment by freescout-helpdesk** [comment]
What DB are you using?
