### ISSUE TITLE
Install didn't create tables

### ISSUE THREAD

**Issue by andyknas** [freescout-helpdesk/freescout#1733]
I had creds for a remote MySQL DB but the tables weren't created nor was an error returned. On the last step I got the "Whoops" error. Please advise how I can get the tables created.

**Comment by freescout-helpdesk** [comment]
In console:
```
php artisan migrate
```
or via /tools.php

**Comment by andyknas** [comment]
Thank you. I removed the env file then did php artisan freescout:clear-cache and went back to the install url and it worked as expected.

**Comment by LeonadLassen** [comment]
Hi, the php artisan migrate command doesnt work. Could you say me why?
![grafik](https://user-images.githubusercontent.com/53892431/154342387-2a716072-e449-425c-847a-de8bb1ef8c3e.png)

**Comment by LeonadLassen** [comment]
> Thank you. I removed the env file then did php artisan freescout:clear-cache and went back to the install url and it worked as expected.

Could you help me how I can do this with /tools.php?

**Comment by LeonadLassen** [comment]
> In console:
> 
> ```
> php artisan migrate
> ```
> 
> or via /tools.php

And How can I get to the .env app key?

![grafik](https://user-images.githubusercontent.com/53892431/154365432-5062afad-914d-489f-aa4c-960c7d9986fb.png)
