### ISSUE TITLE
Non-Writable files found

### ISSUE THREAD

**Issue by andyknas** [freescout-helpdesk/freescout#1734]
I keep getting the error "Non-writable files found"
/var/www/html/freescout/freescout/storage/framework/cache/data/56/a9/56a942f18644e33c94f53711ab88fcf42fe4701c 
so i run the command
sudo chown -R www-data:www-data /var/www/html/freescout/freescout

but it comes back again. I've also done this..
find /var/www/html -type f -exec chmod 664 {} \;    
find /var/www/html -type d -exec chmod 775 {} \;

In addition, i have noticed "queue:work" always shows as "Running" all the time. Seems like it shouldn't?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
