### ISSUE TITLE
Can no longer create a new user by invite

### ISSUE THREAD

**Issue by taoeffect** [freescout-helpdesk/freescout#174]
In the latest 1.1.0 version, when creating a new user without specifying their password, clicking on "Create User" results in the following error in the console on Safari:

```
[Error] An invalid form control with name='password' is not focusable.
```

So to send an invite I have to create the account with a password, and then later click the link to send an invite. It used to work properly before.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/ef24f2fdf8c2c95a38d657604f51ce2ae9571da8
