### ISSUE TITLE
Admin account doesnt work

### ISSUE THREAD

**Issue by LeonadLassen** [freescout-helpdesk/freescout#1741]
I installed FreeScout on ubuntu and I used the interactive installation script. In the webinterface I created the Admin user, after the configuration I tried to log in but it doesent worked, and I get the message that they have no account for this email address. My database I use is MySQL. Did anybody know what I can do now?

Kind regards Leonard

**Comment by LeonadLassen** [comment]
And the MySQL Database for freescout is so empty. Is that normal?
![grafik](https://user-images.githubusercontent.com/53892431/154326629-9f109091-fc22-47a4-a56e-9cb17526bfcf.png)

**Comment by freescout-helpdesk** [comment]
What PHP version are you using?

**Comment by LeonadLassen** [comment]
Its the PHP Version 7.4.16 and the built ist Nov 25 2021

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1733

**Comment by LeonadLassen** [comment]
Should I do the commands in this Issue?

**Comment by LeonadLassen** [comment]
Sorry for the dump qustion. Can you say me why I got this message? 
![grafik](https://user-images.githubusercontent.com/53892431/154335942-b81e7a62-150b-4b96-9543-dddc9fa755bf.png)
