### ISSUE TITLE
Satisfaction rating immediately saved

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1743]
We have one problem with the satisfaction rating module. The process is fine, but some E-Mail Clients seem to check the links within the mail (probably anti virus checks) and therefore the rating is link is also clicked.

The problem is that the rating link immediately saved the rating and some of our conversations got a bad rating but the customer is totally happy and did not click it intentional.

Proposal: Clicking the link does not save the rating. The link leads the user to the rating site, the desired rating is pre selected but saving the rating requires the submit button clicked.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
Added in Satisfaction Ratings Module v1.0.7

**Comment by obstschale** [comment]
Awesome! Thank you very much
