### ISSUE TITLE
Some extended characters are incorrectly encoded (in message subject lines)

### ISSUE THREAD

**Issue by radarsymphony** [freescout-helpdesk/freescout#1744]
### Summary
Subject lines containing some UTF-8 characters are incorrectly rendered in Freescout. These emails are often not fully delivered to Freescout inboxes. (They arrive in our mail stores, but Freescout seems to mark them as Spam when syncing with imap.) If they arrive, their subject's encoding is broken. (see example below)

### Steps to reproduce
Freescout 1.7.26
1. From non-freescout client, create test email.
2. In the Subject, include "This subject has ’ [right single quote]".
3. Send to Freescout inbox.
4. View subject and header info of received email.

### What is the current bug behavior?

UTF-8 characters are not encoded properly (e.g.,  ’  or `=E2=80=99`) resulting in Subjects that are incorrectly rendered and sometimes non-delivery of mail.

### What is the expected correct behavior?

Extended ASCII or UTF-8 characters are encoded correctly. 

### Relevant logs and/or screenshots

How subject looks when received by other clients or when viewed in the sending client's sent folder:

![image](https://user-images.githubusercontent.com/73671474/154579535-43e59db6-1128-457a-b83a-df524949e16b.png)

How subject looks when it arrives in Freescout:

![image](https://user-images.githubusercontent.com/73671474/154573962-e72a6a50-fa67-461c-ba91-e475410f4700.png)

Header info when message sent from client no.1 (The message did arrive in Freescout, but subject incorrectly rendered with underscores replacing whitespace)
```
Subject: =?utf-8?Q?[Bulletin]_This_subject_has_=E2=80=99_and_'_characters_|_#_873_@_17/02/2022?=
Message-ID: <D0RHeQytiCpGDAujM67ZPfsvhp3fKEw2hSIq4aVHlh8@localhost.localdomain>
X-Mailer: WPMailSMTP/Mailer/smtp 3.3.0
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit
```

Header info when sent from client no.2 (The message did not arrive in Freescout, but arrived in mail stores)
```
Subject: =?utf-8?Q?=5BBulletin=5D_This_subject_has_=E2=80=99_and_=27_chara?=
 =?utf-8?Q?cters_=7C_=23_873_=40_17/02/2022?=
[redacted]
Date: Thu, 17 Feb 2022 21:35:53 +0000
Mime-Version: 1.0
Content-Type: multipart/alternative; 
 boundary="=_V-H3Ss38WEb2mnz-qi7VTFOExGee80+IVQVkMAMthV2+ovch"
X-Priority: 3 (Normal)
```

### Potentially Related Issues
https://github.com/freescout-helpdesk/freescout/issues/1581
https://github.com/freescout-helpdesk/freescout/issues/898
https://github.com/freescout-helpdesk/freescout/issues/1296
https://github.com/freescout-helpdesk/freescout/issues/1670

**Edited for clarity

**Comment by freescout-helpdesk** [comment]
What is your PHP version?

FreeScout uses `mb_decode_mimeheader()` function to decode email subjects. It seems to work fine with your examples. It can be checked here (click "Execute code"): https://sandbox.onlinephpfunctions.com/code/a1ce8e069cc283269505a4de9e2cb03a1ec4d4a1

**Comment by radarsymphony** [comment]
Thank you for taking a look. The sandbox snippet you provided still shows the encoding issue, however. My original post shows what the subject looked like prior to sending to freescout, i.e., the original didn't have underscores replacing whitespace. This behavior is being replicated in the php function checker you provided:

![image](https://user-images.githubusercontent.com/73671474/155179765-31bd65a4-f421-4703-a1f6-7bde11ba997b.png)

Further, I can take the same encoded text you've entered into the checker (*see below) and use it straight as a subject in a new message and other clients render it without underscores. To me, this suggests the issue in Freescout arises in the last stages before or while the text is encoded and rendered on the page. 

 *`=?utf-8?Q?[Bulletin]_This_subject_has_=E2=80=99_and_'_characters_|_#_873_@_17/02/2022?=` 

Updated Freescout to latest and can still replicat the issue:
Freescout | 1.8.6
-- | --
Nginx | nginx/1.21.6
PHP | 7.3.33

![image](https://user-images.githubusercontent.com/73671474/155179492-d28c5974-d58b-47fa-8a7b-8511f4ac6c36.png)
