### ISSUE TITLE
Filter and action eventy is not working when customer creates new ticket using email

### ISSUE THREAD

**Issue by dhaniexpresstech** [freescout-helpdesk/freescout#1747]
**Filter and action Eventy is not working when customer creates new ticket using email.**
like this.
\Eventy::addFilter('conversation.created_by_customer', function($conversation, $thread, $customer) {
      //code here
  },20,3);
             or 
 \Eventy::addAction('conversation.created_by_customer', function($conversation, $thread, $customer) {
           //code here
},20,3);

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/spam-filter/ uses this filter. Make sure you module is active
