### ISSUE TITLE
Mailbox connection settings: Mail fetch connection check always connects via STARTTLS and Certificate check

### ISSUE THREAD

**Issue by sebix** [freescout-helpdesk/freescout#1752]
When configuring a non-encrypted IMAP connection, port 143 and certificate verification deactivated, the "Get folders" and "Check connection".

Error message with "Get folders":
![image](https://user-images.githubusercontent.com/199050/154817087-e29889e5-0df3-4e44-aa63-0fe3f5db1df4.png)

Error message with "Check connection":
![image](https://user-images.githubusercontent.com/199050/154817093-84f67d57-62ca-437a-b7f7-12e4152e0d88.png)

btw: "Get folders" gave me a much better error message which actually allowed me to find out the cause. "Check connection" is very silent.

After saving the settings and *then* doing the tests works fine.

**Comment by sebix** [comment]
I entered Encryption = None and disabled certificate validation, but Freescout incorrectly tested the connection with either TLS or STARTTLS and checked the cerificate. Otherwise the check would have succeeded and the message can't say there's a certificate CN mismatch

**Comment by freescout-helpdesk** [comment]
You need to save settings first.

**Comment by sebix** [comment]
> You need to save settings first.

Ok.

Although from a user perspective, when I see just "check connection" I assume it applies to the connection settings _shown_.
