### ISSUE TITLE
Opening ticket by date - Tasks

### ISSUE THREAD

**Issue by darkp-team** [freescout-helpdesk/freescout#1755]
Hello, is there any idea how to realize ticket opening by date in custom field and not only once, as workflow allows. We have product selling long circles and have to keep in touch with customers for many times. We have to schedule ticket opening many times in right date and again and again. Some times we send an email, but some times we just write internal comment to ticket and schedule it to a next date. Thanks for help!

**Comment by freescout-helpdesk** [comment]
Via custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
