### ISSUE TITLE
[Feature request] Delete all spam at once

### ISSUE THREAD

**Issue by tareko** [freescout-helpdesk/freescout#1756]
I have several thousand spam messages that accumulated in the spam folder. I would have to hit 'delete' over a hundred times to get all of these cleared 50 at a time. Is there a way to delete all at the same time? If not, could we make this a feature request?

**Comment by densn93** [comment]
We use the workflow module for this, the workflow looks like this:

**Condition**
Status is Spam
AND
Date older than 15 Days (in our case this is enough time to catch non spams out)

**Action**
Move to Trash

It needs a bit of time, but after 1-2 hours all the messages are deleted.
And it does this frequently for you, so you don´t have to press anything anymore :)

**Comment by fulldecent** [comment]
Recommending to close issue as workaround exists.

Also may be a duplicate of https://github.com/freescout-helpdesk/freescout/issues/646
