### ISSUE TITLE
Freescout updates and tools.php

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1757]
Hi guys,

I get many errors on multiple freescouts on updates system and modules.
It looked like that that did changed the version number but not all the files.

So now I want to override all files and do a migrate.
But the tools.php is not working.

I get this error:
Warning: require_once(/home/hx0902/domains/tickets.mindlift.com/vendor/vlucas/phpdotenv/src/Loader.php): failed to open stream: No such file or directory in /home/hx0902/domains/tickets.mindlift.com/public/tools.php on line 16

Fatal error: require_once(): Failed opening required '/home/hx0902/domains/tickets.mindlift.com/vendor/vlucas/phpdotenv/src/Loader.php' (include_path='.:/usr/local/php74/lib/php') in /home/hx0902/domains/tickets.mindlift.com/public/tools.php on line 16

There was no map Vendor in the Freescout root. (one lever higher than public_html)
So uploaded map but still the error.

1. Can I merge all folders en files to my server on an update?
2. Are there files that have the configuration and that I should not override?
3. Are there more customers with update errors? 
I have 3 site's, all with update errors.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually and 4 here: https://freescout.net/news/saml-authentication-php-8-1-performance-improvements-and-more/
