### ISSUE TITLE
Feature request: bulk/auto delete customers with no conversations

### ISSUE THREAD

**Issue by dsXLII** [freescout-helpdesk/freescout#1758]
I have the CRM module installed, but there is no (obvious) way to automatically delete all customers that don't have any associated conversations. Most of those customers are ones that sent in a single spam email at some point in the past few years, some are bots where we delete the emails almost immediately as they're not needed long-term.

I'm not especially eager to manually go through a couple thousand customer records one-by-one, or to have to do it again in a few months' time after a bunch of new "useless" customer records have been created. I'd like to request a way to do this automatically.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request here: https://freescout.net/request-feature/
