### ISSUE TITLE
LDAP SSL to ActiveDirectory

### ISSUE THREAD

**Issue by Hamza31231** [freescout-helpdesk/freescout#1759]
Hi,

LDAP Module does not work with LDAP over SSL to Active Directory.
Has someone experienced the problem?

I think the problem could be a strict SSL cert check. Is it possible to ignore SSL Certificate Errors like „Principalname does not match hostname“ and others?
Perhaps it is possible to ignore certificate check using: LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_NEVER ? If yes, how to do that?
Is it possible to configure to ignore certiificate errors on webui? I didn't found.
(Changing Modules/Ldap/vendor/adldap2/adldap2/docs/configuration.md did not help)
it is hardly possible to have a public certificate on LDAPs Port on the on premise Active Directory Domain Controller, so there must be a possibility to ignore certificate trust.
(if that's the problem at all)

Also on other instances of FreeScout with LDAP it did non work using encryption.
We must use LDAP SSL to connect to out ActiveDirectory.
Experimentally we did a successful connection to unencrypted LDAP, it worked.
After changing to SSL and changing the port, it could not connect.

I tested the LDAP servers with multiple tools like "ldap admin" using ldap over ssl connection, worked fine.

Thank you

**Comment by ThatBrownGuy35** [comment]
Any update on this? currently trying to do the same thing. How is the LDAP module available for purchase without this basic functionality?

**Comment by eljakim** [comment]
We needed to add `TLS_REQCERT     never` to `/etc/ldap/ldap.conf`

**Comment by freescout-helpdesk** [comment]
Great. Thanks for sharing the solution.

**Comment by Hamza31231** [comment]
Would not word for shared hosting, right?
