### ISSUE TITLE
Error fetching Emails from Office365 (IMAP)

### ISSUE THREAD

**Issue by mdeuerlein** [freescout-helpdesk/freescout#176]
IMAP connection to Office365 Account quits with error.

**Account settings**

Settings | Value
------------ | -------------
Protocol | IMAP
Server | outlook.office365.com
Port | 143
User | email@domain.com
Password | *****
Encryption | TLS

**Error Message**: `[BADCHARSET (US-ASCII)] The specified charset is not supported.`

I had the same Problem in a PHP Project but at the moment no time to contribute. But I think the following Links should help to solve the problem and if you need someone for testing, just let me know.

- **webklex/laravel-imap**
[Issue: Charset shouldn't be send with the imap_search](https://github.com/Webklex/laravel-imap/issues/100)
- **barbushin/php-imap**
[Issue: Problem with serverEncoding](https://github.com/barbushin/php-imap/issues/101#issuecomment-378136507)

**Comment by crishnakh** [comment]
In this case I commented the charset parameter and the mail is fetching.
>freescout/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php
Not the best solution.

Line 155
```php
/**
             * Don't set the charset if it isn't used - prevent strange outlook mail server errors
             * @see https://github.com/Webklex/laravel-imap/issues/100
             */
            if($this->getCharset() === null){
                $available_messages = imap_search($this->getClient()->getConnection(), $this->getRawQuery(), SE_UID);
            }else{
                $available_messages = imap_search($this->getClient()->getConnection(), $this->getRawQuery(), SE_UID); //, $this->getCharset()
            }
```

**Comment by freescout-helpdesk** [comment]
https://medium.com/@freescout/oauth-2-0-g-suite-microsoft-365-and-php-7da16ca74314

**Comment by phanousk** [comment]
Any news on this? It's almost a year so I wonder if there is any progress :)

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/OAuth-for-Google-and-Office-365
