### ISSUE TITLE
API module: incorrect mailboxes ids

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#1760]
Hello,

When getting mailboxes list with `GET api/mailboxes` method, there are ids of mailboxes in the response. Those ids do not match real mailboxes ids which are used to list conversations for specific mailbox.

For instance,
1) mailbox A has ID 3 in FreeScout Manage -> Mailboxes.
2) mailbox A has ID 6 when using API
3) getting conversations for mailbox ID = 6 returns conversations for completely different mailbox

**Comment by ilyakonovalenko** [comment]
Looking at the database I found the issue happens when quering mailboxes for specific userId. In the case ID of mailbox_users table record being returned, not mailbox ID.

**Comment by freescout-helpdesk** [comment]
Fixed in API & Webhooks Module v1.0.37
