### ISSUE TITLE
How can I change ADMIN_EMAIL

### ISSUE THREAD

**Issue by RichardUUU** [freescout-helpdesk/freescout#1761]
Everything works except FreeScout has tried to send a couple of messages to admin@admin

Editing my docker config doesn't work. Is there a PHP artisan command?

Thanks, Richard

**Comment by freescout-helpdesk** [comment]
> FreeScout has tried to send a couple of messages to admin@admin

What kind of emails?

**Comment by RichardUUU** [comment]
Here are the subject lines:

Subject:[Freescout] Fetching Problems - [my freescout domain]
Subject:[Freescout] Fetching Recovered - [my freescout domain]

Does that tell you enough?

**Comment by freescout-helpdesk** [comment]
/app-settings/alerts send alert to admins by email. Check your admin email.

**Comment by RichardUUU** [comment]
There is no admin email shown there - only Fetching Problems / Logs Monitoring / Extra Recipients

**Comment by freescout-helpdesk** [comment]
Log in as admin and change admin's email in admin's profile.
