### ISSUE TITLE
Return to homepage link wrong

### ISSUE THREAD

**Issue by josipsain** [freescout-helpdesk/freescout#1762]
When accesing unexsisting page, this link leads to dashboard, and it should not. It should go to root.
![image](https://user-images.githubusercontent.com/73829737/155567601-7ff3fd19-0df2-4ae8-a1f5-b087a014fd34.png)

**Comment by freescout-helpdesk** [comment]
Why? You have issues with one of the modules?

**Comment by josipsain** [comment]
Sorry, i didn't  explain it propperly. I will try to elaborate:

Let say that I have a KB article at link {DNS}en/hc/{ID}/1269/what-are-the-user-types-in-the-application?category_id=46 and i send that link to my users. 
Everything is OK, untill i delete that article.

So, when my users are accesing the link I have given to them, and that article doesn't exsist (it is deleted), ´page not found´ is presented, which is OK.

What is not OK is the Homepage link in that page, which is leading to my dasboard location instead of my CUSTOM homepage.

Summary: The Homepage link should point to my CUSTOM homepage.


Sorry if not being clear enough, and thank you in advance.

**Comment by josipsain** [comment]
The issue is not closed. Now link points to /home, and /home redirects to /dashboard (dashboard address).

it should redirect to **Homepage**

![image](https://user-images.githubusercontent.com/73829737/156818394-4c6c0442-8fdf-47d4-b565-2bad92e0c6f3.png)
