### ISSUE TITLE
Undefined constant "FT_UID" 

### ISSUE THREAD

**Issue by fabianhemmert** [freescout-helpdesk/freescout#1764]
After upgrading to 1.8.7,  my laravel log shows this error:

` Undefined constant "FT_UID" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"FT_UID\" at /var/www/help.escape-team.com/htdocs/vendor/webklex/laravel-imap/src/config/imap.php:105)
[stacktrace]
#0 /var/www/help.escape-team.com/htdocs/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(66): require()
#1 /var/www/help.escape-team.com/htdocs/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#2 /var/www/help.escape-team.com/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#3 /var/www/help.escape-team.com/htdocs/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#4 /var/www/help.escape-team.com/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#5 /var/www/help.escape-team.com/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#6 /var/www/help.escape-team.com/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#7 /var/www/help.escape-team.com/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#8 /var/www/help.escape-team.com/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#9 /var/www/help.escape-team.com/htdocs/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#10 {main}
"}`

Any help would be appreciated. Thank you!
Fabian

**Comment by freescout-helpdesk** [comment]
Try https://github.com/Webklex/laravel-imap/issues/30#issuecomment-348748107

**Comment by fabianhemmert** [comment]
Thanks, that solved it!
