### ISSUE TITLE
"Could not get mailbox IMAP folder ", despite Folders loading in connection Settings

### ISSUE THREAD

**Issue by fabianhemmert** [freescout-helpdesk/freescout#1765]
My fetch_mails.log says

    Could not get mailbox IMAP folder:

each time when running the cron job, but the mailbox configuration correctly gets all folders from the (GMail) IMAP.

Any help would be appreciated!
Fabian

**Comment by fabianhemmert** [comment]
Before I remove the mailbox: Is there a way to create a backup of the canned responses?

**Comment by freescout-helpdesk** [comment]
You may need to debug it yourself.

**Comment by fabianhemmert** [comment]
I fixed it by reinstalling FreeScout, now it works. All good.

(The canned responses are stored in the database, there's a table 'saved responses', which I was able to easily export and then re-import into my fresh installation.)
