### ISSUE TITLE
Upgrade 1.8.4 to 1.8.7 completely broke

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#1766]
`PHP Warning:  require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 43
PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/artisan on line 43
`

After web upgrade.

Tried manual upgrade form console same;
Full log paste:  https://tools.3q.de/paste/?a2c56d9635b710b6#43GYMGm83DwjstcU62cHdWRzLeL4P2XSWvDtfojEMU2g

Also a git pull didnt helped due to local difference. 

What helped was a git reset:
```
git reset --hard origin/master
git fetch --all
git pull
php artisan freescout:after-app-update
chown www-data.www-data * -R
```

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1731
