### ISSUE TITLE
Form for Website

### ISSUE THREAD

**Issue by qsvch** [freescout-helpdesk/freescout#1767]
Would be a good extension if a form could be generated which could then be embedded anywhere on a website.

Maybe as an extension of the End User Portal or as a new module?

**Comment by qsvch** [comment]
This could be the End User Portal form, which is openly displayed on the website after being embedded by the code. Only for quick contact in a website

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
