### ISSUE TITLE
Whoops something went wrong after a few hours

### ISSUE THREAD

**Issue by LeonadLassen** [freescout-helpdesk/freescout#1770]
Hi,

now I have succesfully installed freescout, but now after round an hour I get an Whoops something went wrong error in my browser, then I have to clear the cache in the command prompt. Is there a way to solve this issue?

Kind regards Leonard

**Comment by grrinch** [comment]
this could be literally anything.

I'd check some common issues:
- chmod and permissions
- disk space on the server
- log files (post here if you need help) in [freescout installation]/logs/laravel-[date].log
- how you installed it?
- server setup (apache/nginx/php/database + their versions)
- freescout version

It will be much more exciting to try helping you if you provide more information.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
