### ISSUE TITLE
Error in Facade.php

### ISSUE THREAD

**Issue by augustotauroni** [freescout-helpdesk/freescout#1774]
We found some issues in new app:

Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Unknown named parameter $id at

at /home/alquicoche/public_html/support/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221) 

Any idea?

**Comment by freescout-helpdesk** [comment]
More info is needed to reproduce the issue. PHP version. Where do you get this error. Full error stack trace.

**Comment by freescout-helpdesk** [comment]
Looks like some broken installation. Try to reinstall the FreeScout.

**Comment by bvanwiggen** [comment]
I have the same issue with a brand new install in combination with the Workflow module and an automatic action for previous conversations

**Comment by RienNeVaPlus** [comment]
Came accross this as well, in my case it seemed to be caused by a workflow with too many conditions. At least the other workflows kept running after I disabled that one.

**Comment by JohnDuff44** [comment]
> I have the same issue with a brand new install in combination with the Workflow module and an automatic action for previous conversations

Exactly the same issue right now (new freescout installation and basic workflow module not working for previous and new messages)

**Comment by freescout-helpdesk** [comment]
Could you please attach screenshot of Conditions and Actions

**Comment by JohnDuff44** [comment]
> Could you please attach screenshot of Conditions and Actions

Hum, it seems a bit awkward because now the conversations have the right tag.. 
But the tag appears something like 2 hours after receiving the email or even more for previous emails. Workflow are not realtime based ?

**Comment by freescout-helpdesk** [comment]
> But the tag appears something like 2 hours after receiving the email or even more for previous emails. Workflow are not realtime based ?

Workflows are real-time. Check your background jobs and conditions.

**Comment by xrikus** [comment]
I have the same problem (also on an clean install). Created an automatic workflow with "Apply to Previous" enabled.

The conditions:
![image](https://user-images.githubusercontent.com/13585742/190587606-754b98c4-a0b1-4299-89ba-c4d1242a1cbe.png)

The action:
![image](https://user-images.githubusercontent.com/13585742/190587857-93ee36e6-4f3f-40d1-88af-a94773126f1e.png)



**failed_jobs**
payload:
`{"displayName":"App\\Jobs\\TriggerAction","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"App\\Jobs\\TriggerAction","command":"O:22:\"App\\Jobs\\TriggerAction\":9:{s:6:\"action\";s:19:\"workflow.do_process\";s:6:\"params\";a:1:{s:2:\"id\";i:3;}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:7:\"default\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"}}`

exception:
`Symfony\Component\Debug\Exception\FatalThrowableError: Unknown named parameter $id in /var/www/xxxxxxxx/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221`
