### ISSUE TITLE
User Persmission for Reports

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1775]
I'm missing a permission to allow access to reports. The user permission list is currently this:
![CleanShot 2022-02-28 at 12 01 47](https://user-images.githubusercontent.com/1058710/155972259-ccedf774-0615-4879-a719-d7475816ad99.png)

But I don't see any option to grant access to see the reports. I have the feeling, that the I would need to grant administrator access for the user to see reports. 

Would it be possible to add this permission for users?

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by obstschale** [comment]
I did: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/367934

Thx.
