### ISSUE TITLE
Share config between accounts and share chat

### ISSUE THREAD

**Issue by augustotauroni** [freescout-helpdesk/freescout#1776]
Hello,

If we share some setups between email accounts (like canned answers, sat ratings, or knowledge base for example), how can we copy between them, or better, set one as "main" to avoid copy and edit in all email accounts?

Is there a way to copy paste in mysql tables without issues?

Another question:  Can we share the Chat between all accounts? (that all accounts can receive chats from same widget)?, or better, than in chat the user can choose the account to chat with (choosing by account name)?

Thank you
Augusto

**Comment by freescout-helpdesk** [comment]
Only copy-pasting. No sharing chats.

**Comment by augustotauroni** [comment]
Can I copy in the database? I can copy for example all the KB and change account ID? Same with canned repplies?

**Comment by freescout-helpdesk** [comment]
Yes. You can try.
