### ISSUE TITLE
change database

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#1777]
I wanted to change the database to a new MariaDB docker.
I exported the original database and imported it into the new MariaDB docker. how do I change the location of the DB inside freescout docker?
I'm running it using TrueNAS Scale. I can open a Pod Shell and change anything around. but I can't seem to find there to change the IP address of the database host

would someone be able to help me?

**Comment by grrinch** [comment]
I don't know how Docker differs from other types of installation, but I'd try to look at `.env` file in the root folder of Freescout.

This is where my database settings are.

**Comment by freescout-helpdesk** [comment]
Try to ask in https://github.com/tiredofit/docker-freescout/issues
