### ISSUE TITLE
Knowledge Base, add Tag support

### ISSUE THREAD

**Issue by josipsain** [freescout-helpdesk/freescout#1778]
Hi,

would it be possible to add Tag support to KnowledgeBase groups and articles?

Also would it be possible to modify KB widget to show only articles and groups that have specific tag on them?

**Comment by jbadson** [comment]
That's basically what categories are.  An article can be a member of multiple categories, so you can use them like tags.  Or do you want your mailbox tags to be shared with the knowledge base?

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/
