### ISSUE TITLE
special characters not displayed correctly in Emails copied to Sent Folder

### ISSUE THREAD

**Issue by jco-c** [freescout-helpdesk/freescout#1781]
Hi,

freescout seems to have an issue with german special characters (ö, ä, ü, ß) and some others (e.g. €). Those are displayed incorrectly in the subject of received emails and in subject and body of sent emails. For example, ö is displayed as Ã¶ and € as â‚¬. How can I fix this? I guess I need to set something to utf-8, but I am not sure where. 

EDIT: I tried to recreate the issue. The issue only exists in the content of an email (subject is fine) which was copied to the "Sent" Folder of the postbox. I also only see the issue when accessing the email postbox via a normal email client. Also I couldn't replicate the issue of incorrect displayed subjects in the freescout client, maybe this was fixed with the latest update?

Thanks alot!
Jan

**Comment by freescout-helpdesk** [comment]
This has been already fixed.
