### ISSUE TITLE
Send slack notification if tag is added to conversation

### ISSUE THREAD

**Issue by JohannesEDU** [freescout-helpdesk/freescout#1785]
Hi,

we use tags with custom folders for separating topics in Freescout.
Now we would like to send a Slack notification if a tag is assigned to a conversation/a conversation appears in a custom folder.
What would be the best way to achieve this?
We also dont mind using N8N with or without a webhook to trigger his. But we did not find an API call which allows us to easily track which conversations got a new tag assigned.

Any idea?

Thanks and best,
Jo

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
