### ISSUE TITLE
Kanban when trying to open card: "Error occured. Please try again later."

### ISSUE THREAD

**Issue by ruess** [freescout-helpdesk/freescout#1787]
Sorry, I had opened this issue before and then failed to respond to the follow-up question asked.

Freescout-helpdesk asked "What's in logs?"

-I checked all the logs, there's absolutely nothing related to this error. However I did find something new, it seems that because the particular kanban board was created by one of my team members, I'm the only one who received the air. When she tried to open any of the cards, she received no error. So I'm guessing this is a permissions issue?

Could someone try to replicate?

Thanks!

Kevin 

----------------------------------

Hi there,

The pre-created Kanban boards (which display emails) work fine, however, when I create a new board and then try to open one of the email thread cards, I get this error:
<img width="1077" alt="153974248-7d2e288c-1040-48e4-afab-adc5f5dd0ea2" src="https://user-images.githubusercontent.com/797367/156458361-9bc9878f-3fa5-44ff-baa2-6e3041715ae3.png">

Any ideas?

Kanban module: Version: 1.0.4

**Comment by freescout-helpdesk** [comment]
PHP version? DB?

**Comment by ruess** [comment]
Pho 7.3
MariaDB 10.3

**Comment by freescout-helpdesk** [comment]
Do you have any non-official modules?

**Comment by freescout-helpdesk** [comment]
This happens as linked conversation is not available for the current user.
In Kanban Module v1.0.6 user will be able to open card the card but will not see linked convesation.

**Comment by ruess** [comment]
Ok. I assume the error will be more descriptive in the future as well?

**Comment by ruess** [comment]
Thank you for the explanation
