### ISSUE TITLE
Auto reply not working

### ISSUE THREAD

**Issue by talgan** [freescout-helpdesk/freescout#1792]
Autoreplay, which works while in gmail, does not work after switching to microsoft exchange 365.
smtp settings are good. I have also created a connector in exchange and allow all mails from the ip of ticked system

I can send new mail or it works when I reply to incoming mails.

yes, i changed it from 2 places.
1
Mailbox --> {Mailbox name} --> Connection Settings

2 Manage --> Settings --> Mail Settings

**Comment by freescout-helpdesk** [comment]
Are you using Office Hours module?
