### ISSUE TITLE
Google App Passwords

### ISSUE THREAD

**Issue by Sagzster** [freescout-helpdesk/freescout#1796]
Starting March 30th Google will no longer support App Passwords (less secure apps)
https://support.google.com/accounts/answer/6010255

Is there a plan forward?

**Comment by freescout-helpdesk** [comment]
According to G Suite support App Passwords will work forever. Using login+password authentication will not work. So just use App Passwords.

**Comment by Sagzster** [comment]
Maybe a module can be offered at one point for OATH2 authentication as App Passwords are very insecure.  Since, if hacked, Freescout could hold information that could damage a company.

**Comment by freescout-helpdesk** [comment]
Maybe in the future.
