### ISSUE TITLE
Is it possible to install modules on local development site?

### ISSUE THREAD

**Issue by amirshawn** [freescout-helpdesk/freescout#1797]
Hi,

I had issues with our server and had to re install freescout.  This time I decided to install it locally and then use a server spun up by Laravel Forge to host it that way I can test changes locally and then push them.  I am trying to install the modules that I purchased and it's saying I'd have to purchase it again because it's a different domain.  Is there any way to install modules locally?

Thank you,
Amir

**Comment by freescout-helpdesk** [comment]
See https://freescout.net/modules-faq/
