### ISSUE TITLE
Saved Replies: Category ignores structure of SR

### ISSUE THREAD

**Issue by jake-the-just** [freescout-helpdesk/freescout#1798]
Currently, I am structuring our Saved Replies and have encountered the following problem:   

All SR are inserted into a structure that looks like this:
1. parent topic
1.1 Subtopic
1.2 Subtopic
2. parent topic 
2.1 subtopic 
etc.   

The categories are numbered, but I also dragged and dropped them into the correct order.

But now when I want to put a Saved-Replies in the category, this sorting is ignored by me (as you can see in the screenshot). What's even worse is that some sub-categories don't show up at the top at all, but bumble around somewhere in the long list.

![Bildschirmfoto 2022-03-08 um 08 48 17](https://user-images.githubusercontent.com/89188342/157191454-4e4bc8fd-8b46-41a7-8ecc-c5f1403570a9.png)

I wish that the sorting is also taken into account under "Category".

**Comment by jake-the-just** [comment]
Addition:
Eventually, all categories will end up at the top of the list. However, to do this, you need to have a few SRs assigned to this subcategory.
Sometimes they jump around in the long list of Saved-Replies until then

**Comment by freescout-helpdesk** [comment]
> Eventually, all categories will end up at the top of the list. However, to do this, you need to have a few SRs assigned to this subcategory.

This is by design and won't change.

**Comment by fulldecent** [comment]
Recommending to close issue as not planned
