### ISSUE TITLE
Not receiving e-mails in Freescout

### ISSUE THREAD

**Issue by Efrit16** [freescout-helpdesk/freescout#1799]
Hello, 

I am able to send e-mails using freescout, however i could not receive any. The status is active and the connection is successful.
In the system > status, the app is up to date, all the php extensions and functions and permissions are "OK". The queue:work is running in cron commands. 
I am using the browser version. using pop3 protocol with SSL encryption in fetching emails.

Any help will be appreciated, i have been trying for days

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by ripkens** [comment]
Its not about sending, its about receiving.
No errors are logged, system says it can connect to Mailbox POP3 and IMAP.

`[2022-03-22 07:35:48] Fetching UNREAD emails for the last 3 days.
[2022-03-22 07:35:48] Mailbox: ByteCity Support
[2022-03-22 07:35:48] Fetching finished`

Mails get marked as read but no new Tickets are created.

I tried 1.8.9 and 1.8.8. The System does not fetch the mails into new tickets.
And the artisan queue:work job seems to run forever.

Crons are reported as ok and "running" but nothing happens

PHP Versions used are 7.4 FPM and 8.0 FPM

**Comment by freescout-helpdesk** [comment]
Check logs.
