### ISSUE TITLE
Hosted version

### ISSUE THREAD

**Issue by zaidka** [freescout-helpdesk/freescout#18]
Any plans for a hosted version? I'd be interested in that even if it's still beta quality as long as I can get support when things break.

**Comment by freescout-helpdesk** [comment]
It is possible. Time will tell.

**Comment by danielfaulknor** [comment]
@freescout-helpdesk is this something you might be interested in having a hosting partner for? My company hosts massive Laravel sites already so we know a lot about running Laravel at scale.
I am deliberately not naming/linking the company as I don't want this to come across as spam :)
