### ISSUE TITLE
Adding forms into conversations via API for workflow management

### ISSUE THREAD

**Issue by JohannesEDU** [freescout-helpdesk/freescout#1803]
Hi,

we would love to add forms into conversations via API to use Freescout as a workflow management tool.
Appearently, most HTML tags are filtered out for security reasons. 
Is there a list of tags which are allowed?
And is there a way to add html forms directly?

Thanks and best,
Jo

**Comment by freescout-helpdesk** [comment]
List of allowed tags: https://github.com/freescout-helpdesk/freescout/blob/dist/config/purifier.php#L27

> And is there a way to add html forms directly?

No, https://freescout.net/request-feature/

**Comment by JohannesEDU** [comment]
thank you!

**Comment by pedroponte** [comment]
how can we add tags via config files without losing them during upgrades? TY

**Comment by freescout-help** [comment]
List them and we'll add them or submit a pull request.

**Comment by pedroponte** [comment]
The idea is to be able to add an HTML **form** tag in the Knowledge base articles.
Many thanks

**Comment by freescout-help** [comment]
Unfortunately it can't be allowed due to security reasons.
