### ISSUE TITLE
Install on Windows Server 2019 + IIS

### ISSUE THREAD

**Issue by BHW84** [freescout-helpdesk/freescout#1804]
Anyone can help? I am trying to install FreeScout on Windows and IIS, there are no details for what to be done so I created a site and the database on MySQL.
I followed the steps related to IIS on the installation guide, but when trying to open HTTP://localhost/install , i got a 404 error, 
my environment is as the following:
windows server 2019
IIS 10
PHP 7.4.13
My SQL  8.0.28

**Comment by freescout-helpdesk** [comment]
It looks like we can't help you here. Have you managed to solve the issue?

**Comment by BHW84** [comment]
Thank you for your reply, I was not able to solve the issue, I think the installation steps for the windows server and IIS must be updated as I followed the steps on two VM with the same error.

**Comment by freescout-helpdesk** [comment]
Ok, we'll update when someone will find a solution.
