### ISSUE TITLE
Share tickets with other mailbox

### ISSUE THREAD

**Issue by LookitheFirst** [freescout-helpdesk/freescout#1805]
Hi,

we sometimes have tickets, where different teams in our organization have to coordinate together to resolve it properly. In case this happens more often, we can simply create another mailbox containing users from both teams to collaborate on the ticket. But if this happens only occasionally it seems like overkill to create a whole mailbox for this one ticket.

So to solve this, I propose a ticket sharing feature. It could possibly work by cloning the concerned ticket into the other mailbox and just synchronizing all answers between the two tickets.

There could also maybe be the option to prevent users from the second mailbox from sending an answer, just allowing the addition of notes, so that the answer always has to come from the first mailbox-address.

What do you think?

**Comment by arrayown** [comment]
Love this idea. It could be very useful to us as well.

**Comment by freescout-helpdesk** [comment]
Not needed in the core. Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by LookitheFirst** [comment]
@ipruthi https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/369031

I posted it
