### ISSUE TITLE
Error Activatig Modules

### ISSUE THREAD

**Issue by tommasoalati** [freescout-helpdesk/freescout#1807]
HI, i purchaised TAGS module, i installed cotrrectly but when i try to activate it appear an error "permission Denied".
![Immagine 2022-03-10 101521](https://user-images.githubusercontent.com/101323647/157629937-92ffb104-7eb0-4431-99a9-114412fca183.jpg)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by tommasoalati** [comment]
I checked all permission are ok. Freescout run perfectly, updates too.
Only when I try to Activate a Module I got the error above. Thank you.
