### ISSUE TITLE
Show better instructions when there is an error, Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1808]
Today I am loading the /system/status page and it fails.

It would be helpful if instead of just saying "whupps" it could link to a help article on https://freescout.net/ showing how to debug problems.

<img width="1596" alt="Screen Shot 2022-03-11 at 10 59 20" src="https://user-images.githubusercontent.com/382183/157902981-42660647-55d7-412f-8998-802054648df3.png">

Also, P.S. I can't load the /system/status page.

**Comment by freescout-helpdesk** [comment]
Check logs in /storage/logs
