### ISSUE TITLE
Custom login page issue: Not Found 404 page link redirects to the login page

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1809]
Hello,

I just noticed an another issue. When someone visits "Site.com/login", that person will see the not found page (please see the attached image). In this page there is a link which mentions "Go to homepage". This links will be redirected to the custom login page that we set in the setting.
I would appreciate if you fix this issue.

![Screen Shot 2022-03-11 at 20 49 23](https://user-images.githubusercontent.com/12240218/157948876-bdf83030-4aa6-468d-b973-f56007264971.png)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1762#ref-commit-7ea7795
