### ISSUE TITLE
user's email should honor "Spread the world" setting

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#181]
Currently, all emails sent "internally" from freescout to users, doesn't respect the "spread the world" setting.

They should honor it as the rest of the project. There is also "FreeScout" or "via FreeScout" set as From in some emails.

**Comment by freescout-helpdesk** [comment]
"Spread the world" is responsible only for emails to customers.

In notifications to users no need to mention FreeScout at all, instead mailbox name and url should be used.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/e497c95ff1d3b9f37a6a72ab910d4a916ecc38bb
