### ISSUE TITLE
Wiki: install correct php version

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1810]
Because 8.1 is the default if you run that command and 8.1 not supported.

<img width="1596" alt="Screen Shot 2022-03-11 at 15 52 13" src="https://user-images.githubusercontent.com/382183/157963289-26fc5b39-34e9-4300-8c50-dc9e9a661c89.png">

**Comment by fulldecent** [comment]
Also, please consider to make the 8.0 instructions show before the 7.4 instructions. I hope 8.0 can be the default recommendation.

**Comment by freescout-helpdesk** [comment]
Fixed

**Comment by fulldecent** [comment]
Thank you. Confirmed fixed. 

Documenting here: if somebody had used the default install instruction they would have gotten PHP8.1. They will get other errors from that. 

The solution is to use `apt remove` then type php8.1 tab tab. And remove all those packages. I don't know how to contact those people but hopefully they see this note.
