### ISSUE TITLE
Another update bites the dust

### ISSUE THREAD

**Issue by onderzoekspraktijk** [freescout-helpdesk/freescout#1812]
The previous update went wrong.
I looked at several other issue tickets on this and they helped me overcome this.
Turned out this helped:
- reinstall all files;
- open freescout and click on the system update tbutton.
- That got me form subversion 8.3 to 8.8.
Todat clicked the system update button and got a white screen only as a result.
I redid the previous:
- download latest version
- reinstall al files
- open freescout ...
- Now however I kept getting the white screen.

I used /tools.php and that presented two error messages both as a result of this:
" Warning: require_once(/home/([deleted]/[deleted]/overrides/vlucas/phpdotenv/src/Dotenv.php): ..."

When I checked to see if there is such a file Dotenv.php in the zipped update I used: there is not.

There is also no such file in the previous update I used.

I remember the previous update issue also had some file missing according to the error message when I tried to open that version.

I presume there is a file missing that is needed to succesfully open freescout. Is there a way to add that file to the software that is now installed?
As a no-coder I cannot judge these issues at all, I can only send this message hoping it helps solve something that generates this issue.

Cheers,
Paul

**Comment by freescout-helpdesk** [comment]
See Method 5. Update manually
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually
