### ISSUE TITLE
php8.0-json not required

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1813]
The JSON package is not required and that part should be removed from this line as it causes an error.

> root@localhost:/var/www/html/storage/logs# apt install php8.0 php8.0-mysql php8.0-fpm php8.0-mbstring php8.0-xml php8.0-imap php8.0-json php8.0-zip php8.0-gd php8.0-curl
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package php8.0-json is a virtual package provided by:
>   php8.0-phpdbg 8.0.16-1+ubuntu20.04.1+deb.sury.org+1
>   php8.0-fpm 8.0.16-1+ubuntu20.04.1+deb.sury.org+1
>   php8.0-cli 8.0.16-1+ubuntu20.04.1+deb.sury.org+1
>   php8.0-cgi 8.0.16-1+ubuntu20.04.1+deb.sury.org+1
>   libphp8.0-embed 8.0.16-1+ubuntu20.04.1+deb.sury.org+1
>   libapache2-mod-php8.0 8.0.16-1+ubuntu20.04.1+deb.sury.org+1
> You should explicitly select one to install.

<img width="1690" alt="Screen Shot 2022-03-14 at 09 27 10" src="https://user-images.githubusercontent.com/382183/158181449-0ebdfc84-3886-4500-8b10-f37d0302bf81.png">

**Comment by freescout-helpdesk** [comment]
Thanks. Fixed.
