### ISSUE TITLE
Default to php8.0 install instructions

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1814]
At https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#1-prerequisites

<img width="1690" alt="Screen Shot 2022-03-14 at 09 43 20" src="https://user-images.githubusercontent.com/382183/158184537-8cb94501-f6bc-4d1f-93db-0872f4c105b9.png">

**Comment by freescout-helpdesk** [comment]
Thanks, updated.
