### ISSUE TITLE
HTML tables

### ISSUE THREAD

**Issue by drwebbe** [freescout-helpdesk/freescout#1816]
Hi,
HTML tables aren't shown correctly in Freescout.
Sample screenshots in attachment (FS vs O365)
![Freescout](https://user-images.githubusercontent.com/13571460/158374857-30dfa26c-1286-492b-9cd0-39f5b6e0b7da.png)
![O365](https://user-images.githubusercontent.com/13571460/158374862-e050e4e8-a0f1-4764-91bb-287f32fff893.png)

Is there any solution/workaround for this ?

Thanks,
Kurt

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed
