### ISSUE TITLE
Update required extensions

### ISSUE THREAD

**Issue by bfren** [freescout-helpdesk/freescout#1817]
I recently setup FreeScout using PHP8 and to get it to work I *had* to install the php8-dom extension. The system ran fine, except when trying to parse incoming HTML emails.

https://github.com/freescout-helpdesk/freescout/blob/6014509dd2c40a7086b0427cbe0f29b31088f7c6/config/app.php#L196

I suggest a simple change to:

```
'required_extensions' => ['mysql / mysqli', 'mbstring', 'xml', 'imap', /*'mcrypt' mcrypt is deprecated*/ 'json', 'gd', 'fileinfo', 'openssl', 'zip', 'tokenizer', 'curl', 'dom'/*, 'xmlwriter', 'libxml', 'phar'*/],
```

**Comment by freescout-helpdesk** [comment]
What PHP 8 subversion are you using?

**Comment by bfren** [comment]
```
# php --version
PHP 8.0.16 (cli) (built: Feb 19 2022 04:12:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
```

**Comment by freescout-helpdesk** [comment]
It looks like you are the only one experiencing this issue. We'll close it for now and wait if someone else will face this issue.

**Comment by bfren** [comment]
Do you know how many people install FreeScout in PHP 8? I find it hard to believe this is unique to my setup as it's a fresh install on virgin Alpine.

**Comment by freescout-helpdesk** [comment]
Now most installations are on PHP 8.x

**Comment by bfren** [comment]
So it's a distro-specific thing then presumably, as I imagine most people use Ubuntu.
