### ISSUE TITLE
tools/update.sh support PHP8.0

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1819]
I believe FreeScout supports PHP 8.0. Please update this script to also support this version.

<img width="697" alt="Screen Shot 2022-03-15 at 13 32 59" src="https://user-images.githubusercontent.com/382183/158437399-527c77d9-f295-4c6a-9a7f-36c54c2a7eb5.png">

**Comment by freescout-helpdesk** [comment]
Fixed like this: https://github.com/freescout-helpdesk/freescout/commit/f429bdef8e94bc236a71f7e2c09ef352365f744f
