### ISSUE TITLE
Improve bounce detection

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#182]
Autoreply should not be sent to any DSN response.
In example: we have an automated system that send emails to customers by using a freescout mailbox as From.

If customer's email doesn't exists or is full (or anything similiar) a DSN is sent to the sender (the freescout mailbox).
As in freescout there is an autoreply set, freescout is replying to the DSN address.

This is useless and should be avoided. (I think that we should also skip to create a conversation from a DSN response)

**Comment by freescout-helpdesk** [comment]
Delivery status notification should have a proper attachment, in this case FreeScout will detect message as bounce. See https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L241

Later incoming bounce emails will be used to update message delivery status in `send_logs`

**Comment by guestisp** [comment]
In our case, a bounce from AWS was not detected and a new conversation was created (with auto reply sent)

**Comment by freescout-helpdesk** [comment]
Bounce detection will need to be improved. For now the simplest method is used.

**Comment by guestisp** [comment]
As temporary workaround we can just check email From or Subject and ignore any bounce. From and Subject are easily guessable in a bounce

**Comment by freescout-helpdesk** [comment]
Bounces can be detected only by analysing headers and body.
Temporary workaround: https://github.com/freescout-helpdesk/freescout/commit/a125a8d7b73254dbade51aa7c14330981d6a2f2e

**Comment by freescout-helpdesk** [comment]
Bounce detection improved.

**Comment by guestisp** [comment]
Still doesn't work as expected
Bounces from AWS SES as still undetected

**Comment by freescout-helpdesk** [comment]
What From address is specified in their bounce emails?
Do they have any attachments? Check if at least one attachment has `delivery-status` or `message/rfc822` content type.

**Comment by guestisp** [comment]
Yes there is a "delivery-status" attachment

**Comment by guestisp** [comment]
The From is set as `mailer-daemon@eu-west-1.amazonses.com` but this will change based on the region.
A regexp could be made like: `/^mailer\-daemon\@.*\.amazonses.com$/`

**Comment by guestisp** [comment]
This is the mail content-type:

```
Content-Type: multipart/report; 
	boundary="----=_Part_1222368_403403308.1545163876123"; 
	report-type=delivery-status
```

with multiple parts:

```
------=_Part_1222368_403403308.1545163876123
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Content-Description: Notification

An error occurred while trying to deliver the mail to the following recipients:
x@y.com
------=_Part_1222368_403403308.1545163876123
Content-Type: message/delivery-status
Content-Transfer-Encoding: 7bit
Content-Description: Delivery Status Notification

Reporting-MTA: dsn; a4-11.smtp-out.eu-west-1.amazonses.com

Action: failed
Final-Recipient: rfc822; x@y.com
Diagnostic-Code: smtp; 554 4.4.7 Message expired: unable to deliver in 1440 minutes.<421 4.4.0 Unable to lookup DNS for xxx>
Status: 4.4.7


------=_Part_1222368_403403308.1545163876123
Content-Type: message/rfc822
Content-Description: Undelivered Message

Message-ID: <01020167bd7acda9-65998af3-dbd8-498e-b675-ec880c4f29fa-000000@eu-west-1.amazonses.com>

```

**Comment by guestisp** [comment]
`message/rfc822` should be remove from bounce detection as a normal forwarded attachement gets this content-type:

```
7.3.1 The Message/rfc822 (primary) subtype. A Content-Type of "message/rfc822" indicates that the body contains an encapsulated message, with the syntax of an RFC 822 message
```

**Comment by freescout-helpdesk** [comment]
> The From is set as mailer-daemon@eu-west-1.amazonses.com

There is already regex, which by some reason did not work for you:
```
$is_bounce = preg_match('/^mailer\-daemon@/i', $original_from);
```

> This is the mail content-type:
> Content-Type: multipart/report; 
> 	boundary="----=_Part_1222368_403403308.1545163876123"; 
> 	report-type=delivery-status

There is a regex for this too, which also did not work:
```
preg_match('/delivery-status/', strtolower($attachment->content_type))
```

You will probably need to debug fetching to figure out why none of the checks worked for you.

**Comment by freescout-helpdesk** [comment]
> `message/rfc822` should be remove from bounce detection as a normal forwarded attachement gets this content-type:
> 
> ```
> 7.3.1 The Message/rfc822 (primary) subtype. A Content-Type of "message/rfc822" indicates that the body contains an encapsulated message, with the syntax of an RFC 822 message
> ```
Yes. It has been removed https://github.com/freescout-helpdesk/freescout/commit/9f391b59fc1e87ad36182f1b4a228388ad420ae9

**Comment by guestisp** [comment]
Our fetch script is a little bit different than yours due to our BounceManagement module. I'm waiting for a couple of PR merged to be in sync again with you. After that i can start to debug with the updated code.
