### ISSUE TITLE
Telegram Integration Module issue

### ISSUE THREAD

**Issue by gioppivaa** [freescout-helpdesk/freescout#1823]
Hello,
i can run Telegram Notification module without problems, but Telegram Integration module is not working. If i create a Bot, link it to a mailbox, and then /start the bot, nothing happens.
I also can't see logs, under telegram Logs nothing happens about it.
What should i do?
Please help

TY

**Comment by freescout-helpdesk** [comment]
Try to use different Bots. Please let us know if it helped.
