### ISSUE TITLE
multi-module discount

### ISSUE THREAD

**Issue by ljcatlin** [freescout-helpdesk/freescout#1824]
Do you guys still offer a discount for multi-module purchases?  Here's the list of modules we're considering:

Tags, Workflows, Customization, Custom Fields, End-User Portal, Satisfaction Ratings, Reports, Ticket Number, Knowledge Base, Spam Filter, API Webhooks, CRM, Extended Attachements, Inbox, Customer Data Enrichement, Mentions, Followers, Office Hours, Block external images, Kanban, Noreply Emails Module, Widgets White-Labeling Module, Sender Time Zone, Custom Home Page

**Comment by freescout-helpdesk** [comment]
See https://freescout.net/modules-faq/#do-you-offer-bulk-discounts-do-you-offer-discount-for-nonprofits
