### ISSUE TITLE
API Get conversation

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#1825]
When calling the API list conversations with a filter on mailboxId we are not getting any results, even though the mailbox has messages and we can get individual conversations using /api/conversation/{id} endpoint.

Freescout version: 1.8.9
API module version: 1.0.37

https://[domain]/api/conversations?mailboxId=1
{
    "_embedded": {
        "conversations": []
    },
    "page": {
        "size": 50,
        "totalElements": 0,
        "totalPages": 1,
        "number": 1
    }
}

**Comment by freescout-helpdesk** [comment]
It works fine: https://demo.freescout.net/api/conversations?api_key=c2ba609c687a3425402b9d881e5075db&mailboxId=1
