### ISSUE TITLE
Sessions timeout/are removed after 1 day

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#1826]
We experience problems with sessions. Since the update to 1.8.8 many users report that they have to login every day even though they checked the "remember me" checkbox.
It seems the session were removed on the server.

We use the default session config, i.e. sessions are stores as files.

Do you have any idea? Can I use freescout with the database session driver?

**Comment by freescout-helpdesk** [comment]
Looks like some server configuration issue.
See https://laravel.com/docs/5.5/session#driver-prerequisites

**Comment by obstschale** [comment]
I'll take a look. Thy

/close
