### ISSUE TITLE
Mobile app can't connect when using custom homepage module

### ISSUE THREAD

**Issue by Skryabind** [freescout-helpdesk/freescout#1827]
I set up a homepage module like in example in the page https://freescout.net/module/custom-homepage/:
Dashboard address: /dashboard
Login address: /secret
Home Page: redrect to my knowledge base address.
The module works fine, but I can't collect to freescout from the mobile application. When I enter my site (e.g. https://mysite.com), just knowledge base are opened, without login form.
when I entered login address or dashboard address (https://mysite.com/secret or https://mysite.com/dashboard), I get alert "Could not find FreeScout at https://mysite.com/secret".
In nginx logs I see incorrect requests:
```
2609 open() "/var/www/html/public/dashboard/installer/css/fontawesome.css" failed (2: No such file or directory)
```
Please tell me how to connect from application to FreeScout.

P.S. without homepage module all works fine.

**Comment by freescout-helpdesk** [comment]
Just add a link leading to Login address (/secret) to https://mysite.com

**Comment by Skryabind** [comment]
@freescout-helpdesk knowledge base is for our customers and I don't want to customers know our internal links (login form in this case).

**Comment by Skryabind** [comment]
I fixed this by adding some code to nginx configuration:
```
    location ~ /secret {
       rewrite ^/(secret)(.*) /$2;
    }
```
Now application works. But I think application should work without such a trick;

**Comment by freescout-helpdesk** [comment]
Doing this via server configuration is the only way for now.
