### ISSUE TITLE
Workflow issue

### ISSUE THREAD

**Issue by HEXE-WORKER** [freescout-helpdesk/freescout#1828]
I'm trying to set up automatic response when user is assigned.
Unfortunately as a response i dont get the user's name i'm trying assing to, but default "workflow name".
Question is, is this possible to make this type of auto-answer????

Maybe there's logic mistake I'm making??

Example :
![Freescout](https://user-images.githubusercontent.com/101876181/159022888-3a402fbe-3abd-4ecc-94a0-bd88ea565683.png)

It looks like it gets Workflows user basic data.

**Comment by freescout-helpdesk** [comment]
{%user.fullName%} and other variable determine the user creating the message, i.e. Workflow user. There is no way to get assignee info here.
