### ISSUE TITLE
delay in receiving emails in freescout inbox

### ISSUE THREAD

**Issue by ansaritalha** [freescout-helpdesk/freescout#1829]
It appears that when users are sending emails, or in general, the emails are not getting received in freescout inbox instantly.

it's taking around 1 to 2 hours to arrive in the inbox and we are receiving emails in bulk instead of sending them instantly. our cron job/ queues job/background job seems running fine in background without issue, I was wondering if there was a way to fix that issue.

**Comment by ahmedkaludi** [comment]
Were facing the same issue, Email is delayed by 1-2 hours. 

How can we shorten that time to 1-2 mins?

**Comment by drwebbe** [comment]
In my setup the delay is set to 1 minute, but emails arrive between 3 and 5 minutes later...
Emails are pulled from OVH Exchange.

**Comment by freescout-helpdesk** [comment]
Something must be wrong with cron job: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs
Try to run fetching manually in Manage > System > Tools and see how it goes.

**Comment by drwebbe** [comment]
For me, fixing the cronjob, solved the problem...
Thanks for your support !

**Comment by ansaritalha** [comment]
We have configured the cron job correctly as mentioned in the doc also we have confirmed with hosting support and they told us the cron job is running fine.

When we manually fetch emails using Manage > System > Tools then it's working fine and emails got fetched in the inbox instantly.

these are the cron commands I have added :

php /home/customer/www/xxxxxx/public_html/artisan schedule:run >/dev/null 2>&1

also we have added this cron suggested by hosting support:

/usr/local/php74/bin/php-cli /home/customer/www/xxxxx/public_html/artisan schedule:run >> /dev/null 2>&1

php /home/u17-pyvbsjbdzc9l/www/xxxxx/public_html/artisan freescout:fetch-emails >> /dev/null 2>&1

@freescout-helpdesk can you please check these cron commands and let me know if there are any issues in path or configuration?

**Comment by ansaritalha** [comment]
@freescout-helpdesk any suggestions?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Try to find a developer and debug https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php
