### ISSUE TITLE
Admins get notifications for all mailboxes

### ISSUE THREAD

**Issue by zschroeder6212** [freescout-helpdesk/freescout#1835]
I want to be notified for all new conversations in a specific mailbox, but not in the others. I have deselected the unwanted mailbox in the permissions section for my user account, but I continue to get notifications for all mailboxes.

It seems like standard users do not have this issue.

**Comment by freescout-helpdesk** [comment]
Admin can mute notifications for specific mailboxes:
![2022-03-29_09-25-19](https://user-images.githubusercontent.com/40499291/160547017-8942248e-471b-4a76-b5e5-69e85dd3c19a.png)
