### ISSUE TITLE
Emails send by manual workflow uses incorrect user 

### ISSUE THREAD

**Issue by bvanwiggen** [freescout-helpdesk/freescout#1836]
STR:
- Configure a manual workflow which sends a email to the customer (text is irrelevant) 
- Configure the email signature to contain {%user.fullName%}
- Send an email to the user by triggering the manual workflow

Expected result
An email is send to the customer containing the name of the user which triggered the workflow

Actual result
An email is send to the customer containing the name "Workflow"

**Comment by freescout-helpdesk** [comment]
%user.*% variables always contain Workflow user data, not the user triggering the workflow, assignee or any other user

**Comment by MarcoWel** [comment]
+1 on this. there should be at least a variable with the user triggering a manual workflow, so a signature gets filled correctly. Alternatively or additionally, there should be a way to modify the workflow user name on the UI.

**Comment by MarcoWel** [comment]
@freescout-helpdesk  Can you please reopen this? The possibility to reply and close a ticket via workflow is a very important feature. Currently, the signature is unusable as for the workflow it does not contain a valid user name.

**Comment by MarcoWel** [comment]
Done: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/372952
