### ISSUE TITLE
Workflow scenario - bug or not?

### ISSUE THREAD

**Issue by MaxCh22** [freescout-helpdesk/freescout#1839]
Hey, guys.

I have an issue with workflow. I want to send to a customer an email
WHEN
1st condition = after 1 day since we replied to him (we could use 1 hour, 2 days, doesn't matter)
AND
2nd condition = ticket has tag "waiting"
(like we sent to a customer some request that he has to confirm or provide us additional information and want him to remind about this after 1 day automatically. For that we tag a ticket with "waiting").

This is how it looks like in Freescout:
​​​​​​​conditions: https://monosnap.com/file/0WEIvAuT4xnsZWxw7mrwBdCwXjrCjP
 - Tag(s) Is equal to waiting
 - Last User Reply Is not in the last 1 Days
 
 action: https://monosnap.com/file/Q86scrrWo0cWJeumEhumnkE4wJWRVA
  - email the customer
  
But it doesn't work. Is it a bug or i'm doing something wrong? Maybe you have another option to solve the problem?

**Comment by MaxCh22** [comment]
Guys, finally it's a bug. Because it works separately - when condition is only "Tag(s) Is equal to "waiting" or condition is only "Last User Reply Is not in the last 1 Days". But when we combine them together via "AND" they don't work.

Please tell me, when you can fix it? @freescout-helpdesk

**Comment by elyazalee** [comment]
Hello,

I have the same problem, is there a trick?
