### ISSUE TITLE
Knowledge Base accepting visitor details (like Chat)

### ISSUE THREAD

**Issue by sentiasa** [freescout-helpdesk/freescout#1844]
Chat has a real cool feature for the visitor name, email, phone.

<img width="848" alt="Screenshot 2022-03-25 at 12 55 57 PM" src="https://user-images.githubusercontent.com/9021386/160108384-8220584f-2997-4875-856d-ad5340b8a84e.png">
 
I checked the source code of KB but couldn't figure out if that's currently doable. 

That'd be great if Knowledge Base had this feature too, because I can't reference the users on my platform to freescout

**Comment by freescout-helpdesk** [comment]
Where do you want to see user details in Knowledge Base?

**Comment by sentiasa** [comment]
Inside the widget of Knowledge Base.

<img width="373" alt="Screenshot 2022-03-30 at 1 26 38 PM" src="https://user-images.githubusercontent.com/9021386/160810981-704c2b93-4865-4805-84af-65151936df36.png">
 
Here, users can create ticket but I can't know their name/email.

Whereas, in Chat widget, we can know 
```
var FreeScoutW={
   s:{
     "color":"#443bb0",
     "visitor_name":"John Doe",
     "visitor_email":"asdsadas@adsa.com",
     "visitor_phone":"asdada",
    }
}
```

**Comment by freescout-helpdesk** [comment]
Feel free to create a feature request: https://freescout.net/request-feature/
Also see: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
