### ISSUE TITLE
Extremely suspicious login activity after fresh clean install

### ISSUE THREAD

**Issue by Moongazer** [freescout-helpdesk/freescout#1848]
I've just installed Freescout under a subdomain on our server, the subdomain was new created during the process.

Just 15 minutes later I see multiple suspicious login attempts inside the user-log.
**What bothers me here is, that NOBODY can know of the subdomain or the installation yet!**
How is that possible?

That web-systems are scanned automatically by bots which trying common or random login credentials is very well known. But in this case, its impossible that anyone can know or guess the URL! (The subdomain which I've created has the form sub1.sub2.mydomain.net, which makes it even more unpredictable for random domain scanning).

Question: Does make Freescout any home-calls to a server from each installation (e.g. for statistics)? Is it possible that such a installation list/statistic is leaked, or that someone has gained access to it? I have no other idea to explain this; but you're welcome to brainstorm here.

Edit:
I used the current master branch as installation (v1.8.9, PHP 7.4.28):
```
git clone https://github.com/freescout-helpdesk/freescout .
git pull origin master
git checkout master
```

**Comment by freescout-helpdesk** [comment]
Only in Manage > Modules page calls to freescout.net API are made: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ModulesController.php
