### ISSUE TITLE
hardcoded module field in Mailbox

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#185]
In `Mailbox.php` models, there are currently 4 hardcoded field names coming from external modules, in `fillable` array

These should be removed, each module should declare it's own fillable fields updating the Model accordingly

**Comment by freescout-helpdesk** [comment]
Yes. Those fields are there and in the migration from the beginning of the project and will need to be removed with time.

For now we would recommend you and whole community to focus on [Redesign](https://github.com/freescout-helpdesk/freescout/issues/163) issue.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/e497c95ff1d3b9f37a6a72ab910d4a916ecc38bb
