### ISSUE TITLE
Freescout ticket escalation/approval/workflow

### ISSUE THREAD

**Issue by LWHaysUSDC** [freescout-helpdesk/freescout#1853]
We're considering ticketing options and I have questions about freescout's built-in capabilities:

One thing we need is an ability to define certain types of tickets to be approved by a third party for them to be closed/resolved.   An example would be:

A ticket is generated saying "configuration change in router found" (this will be handled by outside automation software)
The engineer updates the ticket saying "I made the change to enable XXX for YYY project"
Before the ticket can be closed, a supervisor looks over the change and the explanation, only the supervisor can approve the ticket to be closed.

This is not the only example, but in general we are looking for escalations to, or approval by third parties to be a required part of the ticket progress.

I am aware that there is a workflow module, and I see that it does much for automation but couldn't find a reference to whether this functionality was included, would have to be setup as a custom workflow, or what.

Thanks for any insight you can provide.

Larry

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
