### ISSUE TITLE
Finding Module Path

### ISSUE THREAD

**Issue by codelearner-tech** [freescout-helpdesk/freescout#1854]
Hello, I would like to ask for path in finding Module Report back-end code. there is some changes i needed to make for default selected export report checkbox to my own selection
![image](https://user-images.githubusercontent.com/61679436/160578161-b80257d8-2a41-4d60-9f89-14362f5e65d3.png)

**Comment by freescout-helpdesk** [comment]
All modules are located in /Modules/ folder.
