### ISSUE TITLE
"Return"/Refund of the unusable modules

### ISSUE THREAD

**Issue by CuradenIT** [freescout-helpdesk/freescout#1855]
We know that it is not possible to use and test additional modules in the demo version. Therefore, we would like to know if it is possible to deactivate certain modules if we find that they are unusable for us. Do you have a fixed period of time where it is possible to deactivate some modules and request a refund, or is this something you generally do not support. 
Thank you in advance for your help.
Best regards

**Comment by freescout-helpdesk** [comment]
Unfortunately not. See https://freescout.net/modules-faq/#refund
