### ISSUE TITLE
Making Android (Mobile) Notifications work behind Reverse Proxy (nginx)

### ISSUE THREAD

**Issue by ccasalicchio** [freescout-helpdesk/freescout#1856]
Our freescout instance is running behind a reverse proxy (nginx) and everything works fine except for mobile notifications. Do I have to enable any specific ports in the Firewall to connect directly to the Freescount instance or everything should work under 80 and 443?

**Comment by freescout-helpdesk** [comment]
The problem must be in something else. There is no need to enable any specific ports.

**Comment by ccasalicchio** [comment]
It simply doesn't connect via Android App, are there any troubleshooting instructions?

**Comment by freescout-helpdesk** [comment]
Most FreeScout instances are working behind nginx without problems and mobile notifications also work.
So it's hard to tell what can be wrong in your case. Try some other device or Internet provider. Also try to connect to demo.freescout.net
