### ISSUE TITLE
IMAP Folder To Save Outgoing Replies

### ISSUE THREAD

**Issue by drwebbe** [freescout-helpdesk/freescout#1858]
Hi,
The responses we send through Freescout are not visible in the 'Sent emails' folder in our webmail.
I've tried to leave the field empty and I've tried to set it to 'Sent' or 'SENT' without any success.
Sending emails method is set to SMTP for each mailbox and emails are sent just fine.
We just can't see them in our webmail.
We use OVH hosted Exchange.
Any tips are welcome ;)

**Comment by freescout-helpdesk** [comment]
Are you using Microsoft Exchange Server?

**Comment by drwebbe** [comment]
It's a hosted exchange. Almost like O365, but hosted on servers from OVH...
________________________________

**Comment by freescout-helpdesk** [comment]
Are you connecting to IMAP in FreeScout via username and password or via modern authentication?

**Comment by drwebbe** [comment]
With username and password
________________________________

**Comment by freescout-helpdesk** [comment]
You may need to debug it yourself on your end or find a developer.

**Comment by mywebhero** [comment]
I'm not sure about the OVH exchange server. However, it appears that you are not using the correct IMAP Folder To Save Outgoing Replies. 

Each server has its own set of email folders. To see the format, it is best to click on the retrieve available folders button. 

INBOX.Sent is being used by my server, rather than Sent folder. However, in the majority of the email clients I use, it behaves similarly to a standard sent folder. 

I hope you understand what I mean.
![Sent folder](https://user-images.githubusercontent.com/83342769/162417681-5423b0e6-2629-4b6a-842f-6711f9e271fb.jpg)

**Comment by drwebbe** [comment]
Hi,
I understand what you mean.
Unfortunately, the helpdesk from OVH can't tell me how the folder is named.
If I configure the mailbox in Outlook 365 on my computer, I get the following IMAP-folders :
[cid:f16c22f4-aa42-4d11-9fb7-1202f7a58064]

When I configure this in FS like this, it doesn't work :
[cid:8f512520-0c4d-458e-af09-6500def39d45]
When clicking on Get folders, nothing happens...
[cid:7da8bbed-ecee-43ee-8c86-1c49f2582064]
I also tried the INBOX.Sent config like in your screenshot, but it didn't work either 🙁

Greets,
Kurt

________________________________
Van: mywebhero ***@***.***>
Verzonden: vrijdag 8 april 2022 12:25
Aan: freescout-helpdesk/freescout ***@***.***>
CC: Kurt De Leeuw ***@***.***>; Author ***@***.***>
Onderwerp: Re: [freescout-helpdesk/freescout] IMAP Folder To Save Outgoing Replies (Issue #1858)


I'm not sure about the OVH exchange server. However, it appears that you are not using the correct IMAP Folder To Save Outgoing Replies.

Each server has its own set of email folders. To see the format, it is best to click on the retrieve available folders button.

INBOX.Sent is being used by my server, rather than Sent folder. However, in the majority of the email clients I use, it behaves similarly to a standard sent folder.

I hope you understand what I mean.
[Sent folder]<https://user-images.githubusercontent.com/83342769/162417681-5423b0e6-2629-4b6a-842f-6711f9e271fb.jpg>

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. You may need to debug it yourself on your end or find a developer.
