### ISSUE TITLE
Address in mailbox given does not comply with RFC 2822, 3.6.2

### ISSUE THREAD

**Issue by vertizio** [freescout-helpdesk/freescout#1859]
Since around March 16 we're seeing send errors to email a particular group of addresses, before March 16th those emails got out, but after that nothing anymore.

The logs are like these:
`Mar 16, 17:24:19  Error sending email to customer  Address in mailbox given [[user1@domain.sh] does not comply with RFC 2822, 3.6.2.; File: /var/www/fs/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php (355)

Mar 16, 17:22:27  Error sending email to customer  Address in mailbox given [[user1@domain.sh] does not comply with RFC 2822, 3.6.2.; File: /var/www/fs/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php (355)

Mar 16, 17:22:27  Error sending email to customer  Address in mailbox given [[user1@domain.sh] does not comply with RFC 2822, 3.6.2.; File: /var/www/fs/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php (355)`

My guess is that this is related to email address, especially the TLD: '.sh'.

So it did work on March 14:

`
Mar 14, 11:34:56 	Email to customer 	user0@domain.sh 	Accepted for delivery 	#3330
Mar 14, 11:34:56 	Email to customer 	user1@domain.sh 	Accepted for delivery 	#3330 	  	 
Mar 14, 11:34:56 	Email to customer 	user2@domain.sh 	Accepted for delivery 	#3330 	  	 
Mar 14, 11:34:56 	Email to customer 	user3@domain.sh 	Accepted for delivery 	#3330`

**Comment by freescout-helpdesk** [comment]
`[[user1@domain.sh]` - it looks like there is some extra "[" symbol in the beginning?
