### ISSUE TITLE
queue:work cronjob parameters

### ISSUE THREAD

**Issue by dnutbourneudp** [freescout-helpdesk/freescout#1860]
We were having some issues with the queue:work not appearing to run in a timely manner. (Sent emails were taking hours to be sent).

Following the Installation Guide troubleshooting section, we added the recommended extra cronjob:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-queuework-is-not-running

```
crontab -u www-data -e

* * * * * php /var/www/html/artisan queue:work --queue='emails,default' --sleep=5 --tries=1 >> /dev/null 2>&1
```

However, my colleague found that this cronjob remains as an active process until it is forcibly killed and does not give any output.
This would lead to multiple processes building up and filling the process table.

So our questions are:

1. What is the `tries` parameter meant to do? Currently it seems to have no effect
2. How do the `sleep` and `tries` parameters interact?
3. Are there any other parameters available which are not shown in the troubleshooting guide?
4. How is the cronjob intended to be used

Apologies if this is answered somewhere, I haven't been able to find more details documentation.

**Comment by freescout-helpdesk** [comment]
See https://laravel.com/docs/5.5/queues
