### ISSUE TITLE
Keyboard shortcuts in conversations list

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#1863]
Keyboard shortcuts version: 1.0.4
PHP: 8.0.17
Freescout: 1.8.9
Browser: Firefox 98.0 (Fedora 35)

When viewing a mailbox index (in this case, in the "unassigned" view), I have selected a message.

Pressing "S" does not open the conversation status drop-down. After opening the conversation status drop-down manually (by clicking on the icon), none of the status-setting keypresses (A, C, S, P, N) have any effect. i.e. None of the actions described in the section "When conversation Status dropdown is open..." at https://freescout.net/module/keyboard-shortcuts/ work.

Keyboard shortcuts when viewing an individual conversation *do* work.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by DavidAnderson684** [comment]
@freescout-helpdesk You misunderstand. This is not a feature request - it is a bug. https://freescout.net/module/keyboard-shortcuts/ does not do what the description says it does.

**Comment by freescout-helpdesk** [comment]
Shortcuts available in conversation list are listed in "Conversation List": https://freescout.net/module/keyboard-shortcuts/

**Comment by freescout-helpdesk** [comment]
> Pressing the 'S key' does not open the dropdown, and when the dropdown is open (using the mouse to open it), none of the following mentioned shortcuts work, specifically these ones:
> 
> Active – A
> Pending – P
> Closed – C
> Spam – S
> Not Spam – N

This info is presented in "Single Conversation Actions" section, these shortcuts are not available in the "Conversations List"

**Comment by DavidAnderson684** [comment]
I see. Thank you.
