### ISSUE TITLE
Suggestion: mailbox icons

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#1864]
Problem: Once you start to get many mailboxes in your main dashboard, it becomes slow to identify the one you want - you have to visually scan all the text titles. 

Suggestion: Allow a small icon to be added to the mailbox's header in the mailbox listing screen to allow quicker visual identification.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
Maybe someone will implement as a module.
