### ISSUE TITLE
Site hoseting and CPU seconds

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#1870]
I hope someone will be able to give me some advice. I have been running freescount for about two months now and its working very well with a number of the additional modules.  I have freescount running on a Siteground on a shared server and this month I have received an email to say that I have exceeded the CPU seconds which is limited to 4000/hour.  

Looking into this they have suggested that the issue is with 'artisan schedule:run >> /dev/null 2>&1'

Can someone tell me if I have some settings which I may need to check or this there is something else I need to do?

any advice would be greatly apriseated 

John

**Comment by freescout-helpdesk** [comment]
Maybe `artisan schedule:run` background job is using the CPU. The only way in this case is to find another hosting provider.

**Comment by JSM25** [comment]
Can anyone recommend a hosting provider which they have used successfully with freescout?

any information would be greatly apriseated

John

**Comment by mywebhero** [comment]
I have no hesitations about using Freescout on a shared hosting platform. Every minute, cron checks to see if there is a new email. And I have six inboxes that are doing this. 

The only issue I'm having is a once-a-month email that gets stuck in the queue line for some reason. But, apart from that, everything is as it should be.

Don't go for the cheap hosting, go for a premium one with great support service, you should be good.

**Comment by JSM25** [comment]
Thank you for coming back to me so quickly. I have freescout work very well on siteground shared hosting but they are complaining about the CPU usage so looking to switch.


Can I ask who you are using as your hosting platform?


John

**Comment by mywebhero** [comment]
Siteground most likely wants you to pay more to help cover their CPU costs. I don't believe what I'm using is appropriate for you because I'm using a host in my own country. 

Given that the undersea cable breaks every few years, crippling the internet connection, I thought hosting it close to where you are would make more sense.

**Comment by JSM25** [comment]
Thank you for the information, and it's nice to see we can get free scout to run without an issue on a cost-effective web server. I am still looking for a provided

If I lower the CRON job to 15 min intervals, is not such an issue but then is a long delay as weill    

> Siteground most likely wants you to pay more to help cover their CPU costs. I don't believe what I'm using is appropriate for you because I'm using a host in my own country.
> 
> Given that the undersea cable breaks every few years, crippling the internet connection, I thought hosting it close to where you are would make more sense.
