### ISSUE TITLE
Error with translation when a chat is shown after the opening hours

### ISSUE THREAD

**Issue by johanoloflindberg** [freescout-helpdesk/freescout#1872]
Hey!  

It does not work with the translation when a chat is shown after the opening hours, it still shows English even though I have chosen Swedish.  

The same applies that preset names, e-mails, etc. are not included when the chat is displayed after the opening hours.  

Thanks in advance! Kind regards, Johan Lindberg

**Comment by freescout-helpdesk** [comment]
Chat Module is translated into French only for now.
https://freescout.net/modules-faq/#translate-modules
