### ISSUE TITLE
Action after status change

### ISSUE THREAD

**Issue by martinbirch** [freescout-helpdesk/freescout#1874]
Hello
I would really like to be able to choose what should happen when I change status from **[Unassigned]** to **[Pending]** or **[Closed]**. Right now Freescout just chooses the next message. I would like to automatically return to the **[Unassigned]** list. Any workarounds for this?
Best regards
Martin

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-i-determine-what-happens-after-changing-conversation-status
