### ISSUE TITLE
Export Conversations Module Issue

### ISSUE THREAD

**Issue by basit-afia** [freescout-helpdesk/freescout#1876]
We have purchased the Export Conversations Module to export our conversation with custom fields.
But Most of the time its throwing 500 error while export and also in excel sheet the fields mapping is not working properly like Assignee field showing wrong data.
Please update us asap.

**Comment by freescout-helpdesk** [comment]
> But Most of the time its throwing 500 error while export

See Troubleshooting here: https://freescout.net/module/export-conversations/

**Comment by freescout-helpdesk** [comment]
> Assignee field showing wrong data

What do you see instead of Assignee?

**Comment by basit-afia** [comment]
> > Assignee field showing wrong data
> 
> What do you see instead of Assignee?

Its showing the username of other user. Don't know why but its showing wrong user

**Comment by basit-afia** [comment]
> > But Most of the time its throwing 500 error while export
> 
> See Troubleshooting here: https://freescout.net/module/export-conversations/

its doesn't help, We have tried to minimize the export data but still its showing error

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs

**Comment by basit-afia** [comment]
> Check Manage > Logs > App Logs

 Invalid argument supplied for foreach() {"userId":11,"email":"muhammad.basit@afia.ae","exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:765)
[stacktrace]
#0 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(765): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1288): Illuminate\\Database\\Query\\Builder->whereIn()
#2 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1474): Illuminate\\Database\\Eloquent\\Builder->__call()
#3 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1486): Illuminate\\Database\\Eloquent\\Model->__call()
#4 /opt/support.alfred.ae/public/Modules/ExportConversations/Providers/ExportConversationsServiceProvider.php(126): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#5 /opt/support.alfred.ae/public/Modules/ExportConversations/Http/Controllers/ExportConversationsController.php(36): Modules\\ExportConversations\\Providers\\ExportConversationsServiceProvider::getExportableFields()
#6 [internal function]: Modules\\ExportConversations\\Http\\Controllers\\ExportConversationsController->export()
#7 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#8 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#11 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#12 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /opt/support.alfred.ae/public/app/Http/Middleware/CheckRole.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#14 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckRole->handle()
#15 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /opt/support.alfred.ae/public/app/Http/Middleware/CustomHandle.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#17 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle()
#18 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /opt/support.alfred.ae/public/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#20 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle()
#21 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /opt/support.alfred.ae/public/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#23 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle()
#24 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /opt/support.alfred.ae/public/app/Http/Middleware/HttpsRedirect.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#26 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle()
#27 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#29 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#32 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#33 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#35 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#36 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#38 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#39 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /opt/support.alfred.ae/public/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#41 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle()
#42 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#44 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#45 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#47 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#48 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#50 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#51 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#53 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then()
#54 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#55 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#56 /opt/support.alfred.ae/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#57 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#58 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#59 /opt/support.alfred.ae/public/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#60 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle()
#61 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /opt/support.alfred.ae/public/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#63 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle()
#64 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /opt/support.alfred.ae/public/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#66 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()
#67 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#69 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#70 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#72 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#73 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#75 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#76 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#78 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#79 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#81 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#82 /opt/support.alfred.ae/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#83 /opt/support.alfred.ae/public/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle()
#84 {main}
"}

**Comment by basit-afia** [comment]
when we export

**Comment by freescout-helpdesk** [comment]
Can you attach a screenshot of the Export dialog.
Are you using any non-official modules?

**Comment by basit-afia** [comment]
> Can you attach a screenshot of the Export dialog. Are you using any non-official modules?

we are using official modules.
![Screenshot_4](https://user-images.githubusercontent.com/95333230/161892417-74ba736c-6038-44b9-bfb7-3252bf0c766c.png)

**Comment by freescout-helpdesk** [comment]
Issues have been fixed in the Export Conversations Module v1.0.2
