### ISSUE TITLE
Oauth for Gmail (once again)

### ISSUE THREAD

**Issue by jcathenstaedt** [freescout-helpdesk/freescout#1877]
Dear freescout team,

I know this has been a topic a few times already and it seems like so far, Google has never really locked out "less secure apps". 
This time however, I got the following email with a pretty clear deadline:

> On May 30, you may lose access to apps that are using less secure sign-in technology. To help keep your account secure, Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password. Instead, you’ll need to sign in using Sign in with Google or other more secure technologies, like OAuth 2.0. 

Is there any chance that Oauth will be supported by PHP (and freescout) by then? Or should I start looking for another mail service for my incoming tickets?

Thanks!
Jan

P.S.: I absolutely love freescout! You guys are fantastic!

**Comment by jcathenstaedt** [comment]
No, but now I do! Not sure why I missed this option. Hope this will do the trick. Thanks a lot for the answer!
Jan

**Comment by zigojacko** [comment]
> Are you using App Passwords? Are you using G Suite?

How was this reply a resolution to this original question?

I use Google Workspace / GSuite but I still have to allow less secure apps in my Google accounts in order to sign-in to Freescout with a username and password (which should really be using OAuth).
