### ISSUE TITLE
Keyboard shortcut request

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#1883]
The helpdesk I was previously using with a similar name would send a reply to a customer if I pressed "Control + Return" with the focus within the text of the reply being composed.

Freescout does not do this. (I have the keyboard shortcuts module active). It would be a useful addition. (For now, one has to use the pointing device and remove hands from the keyboard).

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
Implemented in Keyboard Shortcuts Module v1.0.6

**Comment by pogla** [comment]
@freescout-helpdesk Thanks but only CTRL + enter got implemented. Could you please implement CMD + enter for Mac users? Both GitHub and Gmail use CMD so this would be much better. Thanks!

**Comment by freescout-helpdesk** [comment]
> CMD + enter for Mac users

Have you tried? It does not work for you?

**Comment by pogla** [comment]
Nope. But Control + Enter works.
