### ISSUE TITLE
Error pasting or uploading image to ticket

### ISSUE THREAD

**Issue by ccasalicchio** [freescout-helpdesk/freescout#1885]
Steps to reproduce:

Open any ticket, paste an image from the clipboard, or upload using the image upload button.

Receive a general error
![image](https://user-images.githubusercontent.com/2466879/161775838-a23c5ffe-6271-4b09-a4df-ebc896d6eff0.png)

How to troubleshoot and fix this?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
