### ISSUE TITLE
Run Workflows Multiple Times

### ISSUE THREAD

**Issue by tn-zfrank** [freescout-helpdesk/freescout#1887]
I have been using freescout for sometime now and enjoy the system. I would be willing to pay to have Multi-run support added to the workflows module. 

- Per-workflow toggle of Multi-Run support
- Automatically catching and disabling a run-away workflow (A workflow that runs x amount of times in y period of time)

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
