### ISSUE TITLE
Module creates invalid symlink to non-existent /Public dir

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1889]
I noticed that two modules, Inbox and Ticket Number both create an invalid symlink in the /public/modules/ directory.

For Inbox, the symlink points to /home/public_html/Modules/Inbox/Public but the Public dir does not exist in this modules directory.

For Ticket Number, the symlink points to /home/public_html/Modules/TicketNumber/Public but the Public dir does not exist in this modules directory either.

![screenshot](https://user-images.githubusercontent.com/19673842/161899377-18f67c85-0090-43aa-b9a7-c764730f6ce2.jpg)

**Comment by freescout-helpdesk** [comment]
It should not create any problems.
