### ISSUE TITLE
Wrong From when sending from admin panel

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#189]
When a new conversation is created from the control panel, the wrong From/Mailbox is used.
It's used a different mailbox and not the selected one.

**Comment by freescout-helpdesk** [comment]
In the email to customer or notification to user?
Can not reproduce the issue.

**Comment by guestisp** [comment]
In the email sent ti the customer but i'm unable to reproduce It too
But i'm 500% sure that at least one email was sent wrong

**Comment by freescout-helpdesk** [comment]
Until cache is cleared background job sending emails is using the old code.

**Comment by guestisp** [comment]
Ok but the From is not coming from the code but from a DB and it shouldn't be cached by Laravel cache
