### ISSUE TITLE
Can´t access Website after setting Up docker

### ISSUE THREAD

**Issue by BiotTT** [freescout-helpdesk/freescout#1890]
I have some issues with setting up an FreeScout-docker in my virtual machine runnig latest ubuntu. I need a ticketsystem for an schoolproject so it would be very nice if you could somehow help me. Attached are my docker-compose and the .env file. Also attached there is a screenshot of successfully starting the docker. When the docker is started, I just go in a browser and typ in https://localhost// or http://localhost/ or 10.10.0.201 (the ip-address from my virutal machine). I dont know why it doesnt work maybe because of my virtual machine? Please help me. 

[attachments.zip](https://github.com/freescout-helpdesk/freescout/files/8424135/attachments.zip)

**Comment by freescout-helpdesk** [comment]
Try to check at https://github.com/tiredofit/docker-freescout/issues
