### ISSUE TITLE
Fix non-ascii characters in outgoing e-mails

### ISSUE THREAD

**Issue by tuxmartin** [freescout-helpdesk/freescout#1892]
Hi, I'm using feature `IMAP Folder To Save Outgoing Replies`.

But if I open my mailbox using webmail/thunderbird, all outgoing e-mails have header `Content-Type: TEXT/html; CHARSET=US-ASCII`.

I have email signature with non-ascii chars. Can you please use UTF-8 or encode non-ascii chars?

Will the customer see my email without errors? I'm afraid thatthe customer will see the broken characters.

**Comment by lieblinger** [comment]
Facing the same issue. In Germany we have a mark put over a vowel like äöü. These letters are also not properly displayed.

It would be great if you could fix this 👍

**Comment by sofl88** [comment]
If you add `$part1['charset'] = 'utf-8';` here https://github.com/freescout-helpdesk/freescout/blob/168c61e4b00ec38ca79b22f139710025adb89437/app/Jobs/SendReplyToCustomer.php#L294

it seemed to be fixed. Also adding 

```
$envelope['date'] = now()->toRfc2822String();
$envelope['message_id'] = $this->message_id;
```
might be useful for proper listing in several clients (we had some trouble with the date indicator). I also noted that attachments are completly ignored (?)

@freescout-helpdesk If my suggestion is appropriate, I would love to see the addition for charset, date and message_id in a upcoming update.
