### ISSUE TITLE
Update 1.8.11 Broken - 500 Error

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#1893]
Good evening

I just updated to v1.8.11 - which failed - and now receive Error 500 (no details) trying to access FreeScout - including the tools.php page.

tools.php page does show following error:
Warning: require_once(/home/teaminbox/public_html/overrides/vlucas/phpdotenv/src/Dotenv.php): failed to open stream: No such file or directory in /home/teaminbox/public_html/public/tools.php on line 29

Fatal error: require_once(): Failed opening required '/home/teaminbox/public_html/overrides/vlucas/phpdotenv/src/Dotenv.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/teaminbox/public_html/public/tools.php on line 29

I attempted to copy the /vlucas/ folder from /vendor/ directory to /overrides/ directory however has not rectified problem.  

Does anyone have fix for this?  I upgraded and do not have a recent backup to restore......

**Comment by freescout-helpdesk** [comment]
See 4): https://freescout.net/news/saml-authentication-php-8-1-performance-improvements-and-more/

**Comment by luketrip** [comment]
Thanks for your quick reply - I am backing up now before I attempt this.

To me, it looks like new version needs files from /overrides/vlucas however the package on Githum only has 1 file in this particular folder.  The error I received trying to access tools.php for Manual Update references a file not on my server.

Have seen similar issue with a previous update, where the entire /vendor/ directory was missing and broke the update (https://github.com/freescout-helpdesk/freescout/issues/1667) Is this similiar with incomplete /overrides/vlucas/ folder?

PS. After failed upgrade, I could not access tools.php (got Error above).  I manually copied /vlucas/ folder from /vendors/ to /override/ and can now access tools.php without error.  Once backup complete I will attempt to finish this.

**Comment by freescout-helpdesk** [comment]
Just follow instructions: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
