### ISSUE TITLE
[Question] Private Modules

### ISSUE THREAD

**Issue by zackrspv** [freescout-helpdesk/freescout#1894]
We are wanting to implement this for our project, but we would like to know if we can create PRIVATE Modules to extend free scout and add some of our admin services to our backend, so our CS agents don't need to open multiple applications. 

For example, we'd want to add a custom private module to our FreeScout self-hosted installation, that allows us to manage the users, accounts, etc of our main application, and then be able to query that information from help desk tickets that come in. 

We wouldn't have the intention of releasing that module to the general community, as it's specifically for the administration of our main app.

**Comment by freescout-helpdesk** [comment]
Sure: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development

**Comment by zackrspv** [comment]
Thank you, that helps quite a bit.
