### ISSUE TITLE
Unable to export conversations from a single mailbox

### ISSUE THREAD

**Issue by Jacopo-Foti** [freescout-helpdesk/freescout#1895]
If I try to export all the conversations (or reports) without using the mailbox filter I don't have any problem but when I try instead to export filtering by mailbox I get redirected to a blanc Freescout page with an error.
Checking the App Logs I have and error about an "_invalid argument supplied for foreach()_":
![Immagine 2022-04-07 094903](https://user-images.githubusercontent.com/103174974/162148001-2bd71753-65c3-48c2-b3bc-1146f973ece6.png)
"

**Comment by freescout-helpdesk** [comment]
Update module to the latest version.
