### ISSUE TITLE
[Question] Split Tickets?

### ISSUE THREAD

**Issue by NewGuest2022** [freescout-helpdesk/freescout#1896]
Is it possible to split one ticket into separate tickets?

So Team A gets Ticket 1 (original) and Team B gets Ticket 2 (separate Tasks)

Thanks!

**Comment by mywebhero** [comment]
For the time being, I don't believe it is possible. A ticket can be combined, but it cannot be split.

**Comment by NewGuest2022** [comment]
Thanks for your answer.

A copy function, duplicating the ticket would also work. Copy the ticket, and the new tickets get the next free # number

**Comment by mywebhero** [comment]
Yes, it is inconvenient when Freescout detects and combines conversations that should not be combined. 
However, I believe it is not the highest priority right now, but it is on the roadmap. 

Please assist us in voting on this roadmap as well: [Split ticket feature request](https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/334244)

**Comment by NewGuest2022** [comment]
THANKS!
