### ISSUE TITLE
[Question] Call Phone Number

### ISSUE THREAD

**Issue by NewGuest2022** [freescout-helpdesk/freescout#1899]
Is it possible to change the event/link on clicking a telephone number of the customer?
If we hover/click on the phone number it refers to "https://OURDOMAIN/conversation/3?folder_id=1#"

Would be great the dial the number using our MS Teams Client.

Thanks!

**Comment by freescout-helpdesk** [comment]
For now it's possible to set language for Contact Form Widget only. End-User Portal itself is displayed in the language set in Manage > Settings.
