### ISSUE TITLE
Active thread still shows in Drafts and unable to delete it

### ISSUE THREAD

**Issue by dipakcg** [freescout-helpdesk/freescout#190]
Active thread still shows in *Drafts* folder and unable to delete it even after successful message *Conversation Deleted*.

<img src="http://g.recordit.co/uI83U8JhCu.gif" />

FreeScout v.: 1.1.3
PHP Version: 7.1.21
Web Server: Apache
MySQL Version: 14.14 Distrib 5.5.61

**Comment by bitcoinshirt** [comment]
I have the same issue.

**Comment by guestisp** [comment]
Are you able to delete them with the administrator account ?

**Comment by dipakcg** [comment]
No. My account role is *Administrator* already.

**Comment by bitcoinshirt** [comment]
Same, administrator, but running PHP 7.3.0 if it means anything.

**Comment by guestisp** [comment]
Try to discard from inside the draft and not from the bulk actions

**Comment by dipakcg** [comment]
@guestisp , The status of that message showing under *Drafts* folder is already deleted. That said, it's a deleted message still shows under *Drafts*

<img src="http://g.recordit.co/hS4QWsG2ur.gif" />

I hope this helps.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/d1e5604e7921eb8008d3091a76d699b4080e3c65
