### ISSUE TITLE
Customers from SPAM flagged Mails

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#1905]
Hey,

I just got the Customer Module and found there are >8k customers in the DB with totally nonsense emails / contact data. All of them from identified spam. Is there a way to remove all customers which were only present in Spam flagged conversations? 
Of course I could delete them from the Database but I'm not sure if that could cause any other trouble.

Cheers.

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Can be implemented using a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
