### ISSUE TITLE
Customer Profiles with multiple Emails

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#1907]
Hi,

another small thing I maybe don't find!??

Lets say I have a customer "ABC Ltd" which regullary send me emails from _no_reply@abc.test    but I need to send mail to their service@abc.test.

If I click Create to create a new email and enter ABC in the receipient box, it correclty highlt ABC Ltd in the dropdown box. Unfortunately it only choose the 1st email (alphabetical order) as default. Whiy is _no_reply@ if I use the CRM Module to edit the ABC Ltd I can add further emails but they always got sorted alphapetically. If I would remove _no_reply it would next time I receive a auto mail form them (e.g. invoice) not assign to the customer.

Is it possible to change that behavior somehow? Like offering more than one email for selection when I write a new email? Or let the do not reply modul do it's magic and apply the known do not reply addresses in the selection so that they are not used?

Thanks

**Comment by freescout-helpdesk** [comment]
If some customer has several emails it looks like this:

![2022-04-14_15-01-49](https://user-images.githubusercontent.com/40499291/163386751-d57e461b-c57f-4db1-8862-f6614a922176.png)

**Comment by solariz** [comment]
Unfortunately for me it doesn't:

![screenshot_20220414-145432](https://user-images.githubusercontent.com/4168339/163395655-94fced78-c8da-4a52-8e52-605a900d2cc6.png)

![screenshot_20220414-145538](https://user-images.githubusercontent.com/4168339/163395661-a3c8fde8-06e6-4b5a-8bee-a0316899a653.png)

Customer have several Emails and it only show one of it.

**Comment by freescout-helpdesk** [comment]
Try to type "Gaming Gmbh"

**Comment by solariz** [comment]
That works, but why it doesnt show with "ESL Gaming" or "ESL Gaming GmbH" as search and only "Gaming GmbH"?

is there any way to priorize results of customers with plenty of conversation over customers with 1 or none? Like all those findings containing so much spam records, if you don't know exactly what you are searching you are lost.

Thanks

**Comment by freescout-helpdesk** [comment]
> That works, but why it doesnt show with "ESL Gaming" or "ESL Gaming GmbH" as search and only "Gaming GmbH"?

The search compares First Name and Last Name separately.

> is there any way to priorize results of customers with plenty of conversation over customers with 1 or none? Like all those findings containing so much spam records, if you don't know exactly what you are searching you are lost.

It's not possible.
