### ISSUE TITLE
CRM Module: Deleting customer crashes conversation view

### ISSUE THREAD

**Issue by P-Froggy** [freescout-helpdesk/freescout#1909]
I just bought the CRM Module to clean up some duplicate contacts which got created because some of our customers use multiple email addresses.
However, after merging the respective customers and deleting the duplicates, I am no longer able to access their conversations (I'm getting a "Whoops, looks like something went wrong — check logs in /storage/logs" error).

Since it's quite important to my company to have an archive of customer requests (we often have to come back to old requests), that's rather unfortunate.

In the end it was my fault because I deleted the customers, but in my opinion the conversations view should implement some sort of exception handling when the customer no longer exists or prevent the user from deleting customers that have still conversations linked to them.

Below is the error message:

> Call to a member function getFullName() on null (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) {"userId":1,"email":"xxx@example.com","exception":"[object] (ErrorException(code: 0): Call to a member function getFullName() on null (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) at /www/html/app/Thread.php:603, ErrorException(code: 0): Call to a member function getFullName() on null (View: /www/html/resources/views/conversations/partials/thread.blade.php) (View: /www/html/resources/views/conversations/partials/thread.blade.php) at /www/html/app/Thread.php:603, ErrorException(code: 0): Call to a member function getFullName() on null (View: /www/html/resources/views/conversations/partials/thread.blade.php) at /www/html/app/Thread.php:603, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getFullName() on null at /www/html/app/Thread.php:603)

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of FreeScout?
