### ISSUE TITLE
Module marketplace?

### ISSUE THREAD

**Issue by RienNeVaPlus** [freescout-helpdesk/freescout#1914]
Over the years, we've developed a few modules we'd be happy to share. Some free, some not.
Have you ever considered opening up the module marketplace to other developers? Or alternatively allow external licensing endpoints?

**Comment by freescout-helpdesk** [comment]
Yes, we were thinking about it. Feel free to send a list of modules you have to support@freescout.net to see what you have.
Maybe this will speed up the process.
