### ISSUE TITLE
User permissions not working

### ISSUE THREAD

**Issue by Jacopo-Foti** [freescout-helpdesk/freescout#1916]
Hi, I have a question about users permissions. Even if I remove all the permissions for a user he can still act as he has them. For example, if I remove the permission to manage tags the user can still create new tags or remove them from a conversation

**Comment by freescout-helpdesk** [comment]
User permissions are not applied to admins.

**Comment by Jacopo-Foti** [comment]
Thanks, but I was talking about users. For example, I removed the permission to manage tag from a user and then, after logging in with that user, I was still able to modify tags or creating them.

**Comment by freescout-helpdesk** [comment]
Under `manage users` it means access to /tags page.

**Comment by Jacopo-Foti** [comment]
So is there a way to deny users from managing tags in an active conversations?

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
