### ISSUE TITLE
Mobile Android app not working

### ISSUE THREAD

**Issue by LizardNerd** [freescout-helpdesk/freescout#1917]
Hi there.

The main issue is: after we put in the HTTPS url, the app remains stuck and nothing happens, we only see the "Go" button becomes "Go..." and nothing more, no logs too. We tried the "demo.freescout.net" url and it works. Also we can confirm that mobile phones are resolving url domain correctly.

We converted the .apk file to source code to check if we could get something out, but we didn't find too much, probably the issue is on the openBrowser(url) and injectAuthToken(url) functions, but really we don't know.

Is it possible for you find a solution about this?

**Comment by freescout-helpdesk** [comment]
Try to send a URL of your FreeScout instance to support@freescout.net

**Comment by LizardNerd** [comment]
> Try to send a URL of your FreeScout instance to [support@freescout.net](mailto:support@freescout.net)

My url is private on an internal Apache Web Server, everything is working except Android app.
