### ISSUE TITLE
Localhost and embedded images

### ISSUE THREAD

**Issue by shuterfox** [freescout-helpdesk/freescout#1918]
Hi,

I'm using freescout on an lan Network. It work fine, but as the app isn't accesible trought the internet, embedded images seem to dont work. 
Attachement work well.

How can i change the path to the embeded into the mail, to point another host as i can open a virtual directory on this other host which is accesible on the web ( virtual directory will be pointed to the "storage" folder ) ?

Anyway, thanks a lot for this amazing app !

**Comment by afawaz2** [comment]
@freescout-helpdesk  is it possible to embed the images in the emails instead of using links?

**Comment by shuterfox** [comment]
> @freescout-helpdesk is it possible to embed the images in the emails instead of using links?

If i'm right, technically not : embedded need to point to a location ( like an image on a website for example ). This location is defined to the storage folder of the freescoot path. 
In this issue, we would like to change this location ( the one inserted into the mail ) to point to another custom location

**Comment by afawaz2** [comment]
@shuterfox  exactly, images can be embedded similar to how attachments are added to emails and then CID tags can be used to tell the mail client where to render the images. It is a standard method as defined in https://www.rfc-editor.org/rfc/rfc1873 and then
https://www.rfc-editor.org/rfc/rfc2387

**Comment by shuterfox** [comment]
> @shuterfox exactly, images can be embedded similar to how attachments are added to emails and then CID tags can be used to tell the mail client where to render the images. It is a standard method as defined in https://www.rfc-editor.org/rfc/rfc1873 and then https://www.rfc-editor.org/rfc/rfc2387

thanks for the info, but as i dont know laravel architecture, i dont find where are mails templates composed, to alter the path ...

**Comment by bjoas** [comment]
We also have an internal FreeScout server which is not available outside our office network and is experiencing the very same problem.

**Comment by shuterfox** [comment]
I did not solve the issue, but i've done the following to do the trick :

My current lan adress was 'support.mydomain.com'
As my webserver is local hosted, i've configured the links of the freescout webapps to be accesible via one of the server ip.

Then i've created an other webapplication named 'supportFiles', and set the links to allow the connection from 'support.mydomain.com' with **ANOTHER** server ip (port 80/443). 

So there, i got 2 web app, with same adress ( 'support.mydomain.com' ), accesible depending of the server ip entry point. 

Over there, i've changed my dns as my local dns server used for lan access is point to the ip 1, and my external dns is pointing to the ip 2. 
Then i've created a virtual directory on the supportFile app, pointing to the storage folder of the freescout app. 

so i finaly got an adress 'support.mydomain.com/storage/' which is pointing to the local freescout folder.

Hope it will help for others!

**Comment by MarcoWel** [comment]
+1 on having an option to paste an image as embedded within the Freescout editor.
Added a feature suggestion, please vote:
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/384954

**Comment by freescout-helpdesk** [comment]
Implemented as a module: https://freescout.net/module/embed-images/
