### ISSUE TITLE
Workflow doesn't trigger

### ISSUE THREAD

**Issue by JohnDuff44** [freescout-helpdesk/freescout#1919]
Hello,

I just subscribed to freescout, it sounds awesome but I can't make any workflow work for the moment.
And my conditions are pretty simple because it should trigger automatics emails with always the same subject.

So my condition is "Subject" -> is equal to -> the subject i want to trigger
My actions are : add a tag and change status to closed

Tag is added but conversations are still "active"

Can someone help me please ?

**Comment by JohnDuff44** [comment]
Subjects have words with accents (french) so maybe, it doesn't recognize the word ?

**Comment by freescout-helpdesk** [comment]
> Does it need some time to check the previous messages ?

No. If the workflow is applied to previous conversations it should work immeditely.

**Comment by freescout-helpdesk** [comment]
Please attach screenshot of conditions and actions

**Comment by JohnDuff44** [comment]
![image](https://user-images.githubusercontent.com/32732842/165253050-e4dfb6f4-b3c8-43dc-9faf-564a1247ed32.png)
![image](https://user-images.githubusercontent.com/32732842/165253109-4c63b131-88fc-40e7-bf8d-cc323b1101c9.png)
![image](https://user-images.githubusercontent.com/32732842/165254816-54b854a8-fede-43bd-a1da-bce5e94b7f72.png)

**Comment by JohnDuff44** [comment]
Another workflow that doesn't trigger... maybe because of the letter with accents ?

![image](https://user-images.githubusercontent.com/32732842/165516061-fbf01631-e9af-4086-9cca-d8101d539e83.png)
![image](https://user-images.githubusercontent.com/32732842/165516099-ac3845e3-0e32-4e4e-8731-d4b3cb161482.png)
![image](https://user-images.githubusercontent.com/32732842/165516457-174f7202-fb61-44d8-bf7b-36b2c673bc74.png)

**Comment by freescout-helpdesk** [comment]
The problem was in accents. It has been fixed in Workflows Module v1.0.24
