### ISSUE TITLE
How to add legal text below the contact Widget and also in the user portal ?

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1920]
Hello,

To comply with the EU privacy law we need to add the legal texts and also the "Agreement Checkbox" in all of our contact forms including the Widgets.

Would you please mention how can we do that ?

**Comment by freescout-helpdesk** [comment]
There is no such option. You may need to edit the source code.

**Comment by alichakery** [comment]
Would you please add this function at least as a plugin ? Because at the moment the FreeScout's customer portal is against the GDRP ...

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by alichakery** [comment]
I noticed that it is done already, I voted and commented :) .. thank you

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/362209
