### ISSUE TITLE
Non-writable files found 

### ISSUE THREAD

**Issue by andyknas** [freescout-helpdesk/freescout#1921]
I continue to see an error for permissions...

Non-writable files found 
/var/www/html/freescout/freescout/storage/framework/cache/data/56/a9/56a942f18644e33c94f53711ab88fcf42fe4701c 

I run the command as displayed
sudo chown -R www-data:www-data /var/www/html/freescout/freescout

and it then shows OK but at some point, I get the error again. Slightly frustrating as I don't know what keeps causing problems.

**Comment by freescout-helpdesk** [comment]
Make https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
