### ISSUE TITLE
Approval request for actions/filters to implement additional user field

### ISSUE THREAD

**Issue by RienNeVaPlus** [freescout-helpdesk/freescout#1922]
I'm requesting approval to add the following actions / filters:
- `@action('user.create.before_email')` to `resource/views/users/create.blade.php:61`
- `@action('user.edit.before_email', $user)` to `resources/views/users/profile.blade.php:70`
- `@action('user.setup.before_job_title', $user)` to `resources/views/public/user_setup.blade.php:67`
- `$user = \Eventy::filter('user.create', $user, $request);` to `app/Http/Controllers/UsersController.php:101`
- `$user = \Eventy::filter('user.setup', $user, $request);` to `app/Http/Controllers/PublicController.php:105`

These are required for a module which adds an additional field to users.

**Comment by freescout-helpdesk** [comment]
Feel free to add. Just few corrections:

> $user = \Eventy::filter('user.create', $user, $request); to app/Http/Controllers/UsersController.php:101

Filter name: 'user.create_save'

> $user = \Eventy::filter('user.setup', $user, $request); to app/Http/Controllers/PublicController.php:105

Filter name: 'user.setup_save'
