### ISSUE TITLE
Interactive Install Does Not Work

### ISSUE THREAD

**Issue by datzent83** [freescout-helpdesk/freescout#1924]
Hi To All,

This is the first time I am installing FreeScout and I am very bad at Linux in general, so I apologize for all the newbie questions.

I installed Ubuntu live server on my Hyper-V. Than I ran the Interactive installation bash-script (Ubuntu), which seems to have been completed successfully. Towards the end it asked me where I would like to install FreeScout, so I wrote FreeScout. However, when I go to the server's IP https://192.168.1.69/install I get "This site can’t be reached". 

P.S. I was doing the install by connecting to the server via SSH.

Can anyone shine some light on this?

Thanks!!!

**Comment by freescout-helpdesk** [comment]
You may need a developer who can help you https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
