### ISSUE TITLE
Modules are not installed anymore

### ISSUE THREAD

**Issue by JohnDuff44** [freescout-helpdesk/freescout#1925]
Hello,
This morning, my modules (that I bought, installed and activated last week) are activated but not installed.
What happened ?
It took me a lot of time to configure each module so I hope I won't have to configure it again...

Thanks

**Comment by freescout-helpdesk** [comment]
> are activated but not installed

What does it mean? Can you attach a screenshot?

**Comment by JohnDuff44** [comment]
I've lost the modules configuration menus so here a menu of modules page where it's written "Not Installed" with a button "Deactivate".
Modules were installed and the next morning : nothing
![modules_freescout](https://user-images.githubusercontent.com/32732842/165039222-92169820-3f6b-4e02-9c9e-317f52d80079.PNG)

**Comment by ThatBrownGuy35** [comment]
Hi, I'm having this same issue. Did you resolve it?
