### ISSUE TITLE
Connection could not be established with host smtp.gmail.com [ #0]

### ISSUE THREAD

**Issue by dericg** [freescout-helpdesk/freescout#1926]
I installed app using cpanel app installer. I am able to send password reset notification to users but In sending email its not sending test email and says 
**Connection could not be established with host smtp.gmail.com [ #0]** 

How can I fix it?

**Comment by dericg** [comment]
smtp.gmail.com is also not working for sending emails. It says
**smtp.gmail.com is not available on 465 port. Make sure that smtp.gmail.com address is correct and that outgoing port 465 on YOUR server is open.**

Nor its working on port 587.

**Comment by freescout-helpdesk** [comment]
You need to contact your hosting/server provider and ask them this question.
