### ISSUE TITLE
Approval request to make text reply dividers optional

### ISSUE THREAD

**Issue by RienNeVaPlus** [freescout-helpdesk/freescout#1927]
A lot of our replies are sent to amazons messaging system, which is unable to remove the dividing line, added in  
`resources/views/emails/customer/reply_fancy_text.blade.php`.

Thus leading to the customer receiving a weirdly formatted message, starting with the dashes:
![grafik](https://user-images.githubusercontent.com/2457916/164118594-830ad558-be4e-4deb-badc-a4eb883baf28.png)

As sending messages to amazon customers might be a common scenario for FreeScout (based on [these votes](https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/347357)), I suggest the following filter, but I'm not too confident about the naming:
```php
@filter('reply_fancy_text.divider', '-----------------------------------------------------------', $mailbox, $conversation, $thread)
```

**Comment by freescout-helpdesk** [comment]
It's a divider separating replies in @foreach. It should be skipped for the first thread.

**Comment by RienNeVaPlus** [comment]
It is. However these mails are always replies (1st message is a notification from amazon).
I couldn't find any other emails in my inbox using the same formatting. Neither an RFC. And all [wikipedia](https://en.wikipedia.org/wiki/Email#Message_format) has to say is:

    The header is separated from the body by a blank line.

I get that they might be useful for textreaders, but then again why are there exactly 59 dashes?
I'd still vote to make them optional. Thanks for your consideration.

**Comment by freescout-helpdesk** [comment]
> I get that they might be useful for textreaders, but then again why are there exactly 59 dashes?

Just a custom separator.

FIxed in the master branch.
