### ISSUE TITLE
Feature Request: Custom Fields in Sidebar and in List Column

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#1932]
Hi,
First of all, thank you for this great piece of software. We just switched from Zammad and so far we are already quite happy and purchased most Freescout modules available right now.

**Request 01:**
Currently, Custom Fields always get shown in the top view. This quickly leads to lots of lost space in the view area. Please make it possible to add a "Position" setting to custom fields, which allow the user to decide whether a custom field should be placed:

- Main view (standard)
- Right side bar

![image](https://user-images.githubusercontent.com/80592577/164434945-dc92692b-d6b7-4eb4-bfb1-a85501a1e549.png)

**Request 02:**
Please add a setting to optionally display a Custom Field in its own column in the conversation list - preferably adding list sorting straight away. That way, tickets could easily grouped by a certain information or missing information.

BR,
Marco

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by MarcoWel** [comment]
Done:
- https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/372335
- https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/372336
