### ISSUE TITLE
[no reply extension] Asterisk breaks regex

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#1934]
I purchased the [no reply extension](https://freescout.net/module/noreply/).

The documentation says that you can input a *@domain.tld address to specific a wildcard address.
<img width="878" alt="Screen Shot 2022-04-21 at 22 10 38" src="https://user-images.githubusercontent.com/382183/164583207-e43053de-ab40-4378-9615-a3e8ed107cad.png">

However, if you actually use the wildcard address, it is not properly encoded in the matcher.

<img width="738" alt="Screen Shot 2022-04-21 at 22 09 33" src="https://user-images.githubusercontent.com/382183/164583311-8674d004-3fe3-4407-b7fd-8caf677368fa.png">

----

P.S. if you would like to invite me to the modules repo, I can send issues there instead and maybe even some PRs

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Are you using some non-official modules?

**Comment by fulldecent** [comment]
This is the noreply module.

Just reviewed the code, looks correct. Maybe I have an old setting for the module or something. Closing now and will reopen again if will make a repro case
