### ISSUE TITLE
Fetching Email tool per/for specific mailboxes

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#1936]
Is there any way to only use the fetch email tool for specific mailboxes instead of all of them at once? I'm trying to set up one mailbox at a time, some with hundreds of emails but others with hundreds of thousands of emails...

But if I enter a large number in here, it crashes as well so I am not sure how I can fetch thousands of emails - I guess this is a case of increasing the timeouts in the PHP settings but I am unsure.

**Comment by freescout-helpdesk** [comment]
> Is there any way to only use the fetch email tool for specific mailboxes instead of all of them at once?

Unfortunately not.

> But if I enter a large number in here

Where do you enter a large number?

**Comment by zigojacko** [comment]
> > Is there any way to only use the fetch email tool for specific mailboxes instead of all of them at once?
> 
> Unfortunately not.

Any chance of requesting this if there is somewhere that this can be done?

> > But if I enter a large number in here
> 
> Where do you enter a large number?

Where you enter how many days you want to fetch emails from...

![Screenshot_4](https://user-images.githubusercontent.com/849735/165086844-90394586-cfcd-49ff-9795-7c4a8a5d036d.jpg)

**Comment by MarcoWel** [comment]
It would already help if the e-mail fetching tool would be improved to perform the fetching asynchronously. Currently, the process is getting stopped when execution time exceeds the max setting. And that happens fairly quickly (after a few 100 messages already).

**Comment by poiNt3D** [comment]
We have aprox. 6GB Gmail inbox and it fails to fetch more than 250 mails. It would be no issue if it would resume after fail, but it seems that the process starts from the beginning each time.
We would gladly migrate to FreeScout, including paid features, but message history is very important for our work process.

**Comment by freescout-helpdesk** [comment]
> We have aprox. 6GB Gmail inbox and it fails to fetch more than 250 mails. It would be no issue if it would resume after fail, but it seems that the process starts from the beginning each time. We would gladly migrate to FreeScout, including paid features, but message history is very important for our work process.

Mark all emails as unread in your Gmail and fetch only unread emails.

**Comment by MarcoWel** [comment]
@freescout-helpdesk Please still consider fetching the e-mails asynchronously. Currently, this is an absolute weak spot of Freescout. What to do when importing thousands of emails from a migration? Sit there and only do 200 mails at a time?

**Comment by fulldecent** [comment]
Recommending to close issue as workaround exists // mark as unread and incrementally process those emails.

**Comment by MarcoWel** [comment]
This is a poor workaround and NOT a solution so please do not close until bulk mail fetching is properly implemented. Without it Freescout will stay a solution for individual or very small companies only and is not suitable for large-scale deployments.

**Comment by freescout-helpdesk** [comment]
Fetching has been optimized. Check in the latest version of FreeScout.
