### ISSUE TITLE
Forwarding emails that are sent to a specific non-physical address to a mailboxes

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#1937]
Every helpdesk we've used in the past gives each mailbox a unique address which we forward emails to from our our native mail system.

And we use Google Workspace/G Suite, we have a catchall address set up and use loads of different email addresses on our domain through this and we've always been able to set these up as mailboxes in helpdesk systems as we just create a rule that forwards email coming to that email address from Gmail to the relevant mailbox address.

But in Freescout where we are having to directly connect to email addresses at Gmails with the username and password, I'm not sure how we can replicate the same set up. We don't want to have to set up 50+ physical users at Google just to achieve this.

Can anyone offer a solution or ideas for this? Thanks in advance.

**Comment by zigojacko** [comment]
I have managed to find a workaround to fetching the correct email sent to a specific email address by creating a filter in Gmail that assigns a label to all these emails and then in the Freescout mailbox, just fetch email from that specific folder (label). 

This seems to work great.

But I'll obviously have the problem when replying that the email is going to come from the catchall@ address instead of the alias. (it's only 1 or 2 mailboxes of this nature that we actually need to send email from - all the others it is just to receive email only).

Feedback welcome.

**Comment by freescout-helpdesk** [comment]
It looks like we can't give any suggestion here.

**Comment by zigojacko** [comment]
> It looks like we can't give any suggestion here.

That's a real shame because this then makes it impossible for us to adapt to Freescout. Almost every other helpdesk software forwards emails to an address - whilst I've come up with a workaround that will work, I just need to find a way to send email from a different address - you can actually send email from a different address within Gmail.

I might set up a couple of these addresses as real users just for the moment so we can at least try a bit longer with Freescout but it's not going to be suitable forever having to set a user for every single email address that we need to receive email to as this will quickly become very costly so it would be great to see some more flexibility in this area in the future.

**Comment by afawaz2** [comment]
I worked with @Lars- to build a custom module to support send as Alias (see issue https://github.com/freescout-helpdesk/freescout/issues/1112) is this something that you are interested in?

**Comment by zigojacko** [comment]
> I worked with @Lars- to build a custom module to support send as Alias (see issue #1112) is this something that you are interested in?

Yes, I think this is exactly what I am after so yes, interested if you or @Lars-  can help 👍 Thanks

**Comment by Lars-** [comment]
> Yes, I think this is exactly what I am after so yes, interested if you or @Lars- can help 👍 Thanks
Please send an email to info@ljpc.nl so we can take a look and see if your needs match what I have already built.

**Comment by zigojacko** [comment]
> > Yes, I think this is exactly what I am after so yes, interested if you or @Lars- can help 👍 Thanks
> 
> Please send an email to [info@ljpc.nl](mailto:info@ljpc.nl) so we can take a look and see if your needs match what I have already built.

Thanks @Lars- I have just sent you an email 👍
