### ISSUE TITLE
Prefilling fields in end-user portal

### ISSUE THREAD

**Issue by onyxmaster** [freescout-helpdesk/freescout#1938]
Hi!
Is it possible to pre-fill fields in end-user portal, specifying the values via the URL? Or maybe it's possible to add custom JS to the EUP page?

Thanks.

**Comment by RienNeVaPlus** [comment]
You might be interessted in [this](https://scoutdevs.com/how-to-prefill-email-in-end-user-portal/). Not affiliated with the link.

**Comment by onyxmaster** [comment]
> You might be interessted in [this](https://scoutdevs.com/how-to-prefill-email-in-end-user-portal/). Not affiliated with the link.

Thanks for the advice, I've seen this link, but this only works for the widget, while I need this to work for the full portal page.

**Comment by freescout-helpdesk** [comment]
Implemented in End-User Portal v1.0.26

See instructions at https://freescout.net/module/end-user-portal/:
- Prefilling “Submit a Ticket” Form Fields
- Prefilling Contact Form Widget Fields
