### ISSUE TITLE
Initial assignment moves email from Unassigned to Assigned but leaves me in Unassigned

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1939]
When I first initially assign an email to a user that is in the Unassigned category, it will get moved to the Assigned category, but it moves me to the next Unassigned email.

Is there a way to change this behavior so that it when I assign it and it gets moved from Unassigned to Assigned, that it also keeps me with the email, so I am in same email but now with it in the Assigned category instead of still in the Unassigned?

Thanks

**Comment by freescout-helpdesk** [comment]
[![2022-04-24_08-47-04](https://user-images.githubusercontent.com/40499291/164958473-d1ee28d6-03cf-4d0d-999c-61a59fb6dab9.png)
](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-i-determine-what-happens-after-changing-conversation-status-or-assigning-a-conversation)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-i-determine-what-happens-after-changing-conversation-status-or-assigning-a-conversation

**Comment by jshrek** [comment]
Feature was completed (see above) so the "Default Redirect" option i snow available in mailbox settings dropdown menu.
