### ISSUE TITLE
Error occured. Please check your internet connection and try again.

### ISSUE THREAD

**Issue by Cytotoxic** [freescout-helpdesk/freescout#1940]
Just installed a new copy and when testing any connection SMTP, IMAP, POP and while checking for system update button in the system status page I get the error "Error occurred. Please check your internet connection and try again." Logs are empty. I have SMTP working on a different app on same server. This is installed in a subdirectory. Any ideas on what to try or look for? 

Version: 1.8.12

**Comment by freescout-helpdesk** [comment]
Check browser console. Most likely something is messed up with HTTPS

**Comment by Cytotoxic** [comment]
> Check browser console. Most likely something is messed up with HTTPS

Ah thanks I installed it local then moved it live and re-did the installation on the live site but it looks like the 
public/storage/js/vars.js file had my local url still in there still.

Not sure if I maybe skipped a step to re-install properly or maybe that file needs to be included on rebuilding if installation takes place but the file already exists.

Thanks.
