### ISSUE TITLE
Feature Request: Add customer custom fields to reports or workflows

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#1941]
We have a use case where we want some of the fields in the customer profile to be added to the conversation custom fields to enable some reporting metrics. We are currently manually syncing the fields when a conversation is being worked on.

Is it possible to extend the workflows module conditions to include customer custom fields not just name and email, or allow the custom fields to be set using variables (such as the customer custom fields)?

Or, can get the the customer custom fields to be included in the reporting module or the export module?

**Comment by freescout-helpdesk** [comment]
Exporting customer fields added in Export Conversations Module v1.0.3
