### ISSUE TITLE
Feature request: Change Default Redirect setting should be available in Settings

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1942]
Per this issue https://github.com/freescout-helpdesk/freescout/issues/1939 I was having a hard time locating the setting to change the default redirect behavior when you assign a ticket to somebody.

Having the setting only available in the Send Reply drop down menu is not very user friendly for new users.

I suggest that the setting should also be accessible from either Manage > Settings or from Manage > Mailboxes > MailboxName > Edit Mailbox as this is the most logical place to go look for settings.

Thanks

**Comment by freescout-helpdesk** [comment]
This option is user-specific. May we'll add it to the user profile.

**Comment by freescout-helpdesk** [comment]
"Default Redirect" option will be available in the mailbox dropdown menu.

**Comment by adamzmoravy** [comment]
Hi, is this already available? I can't find it in the UI.... Oh! I found the problem. It's not present in the New message compose option :) Just in replies. 

<img width="487" height="165" alt="Image" src="https://github.com/user-attachments/assets/3d3c2766-e4b3-4d9e-9012-6626c3e44617" />

**Comment by freescout-help** [comment]
<img width="251" height="272" alt="Image" src="https://github.com/user-attachments/assets/ec1632dd-1483-4bd5-a841-1c4c4d0c066a" />
