### ISSUE TITLE
Fetching from Google mail no longer possible after 30 May 2022

### ISSUE THREAD

**Issue by vertizio** [freescout-helpdesk/freescout#1943]
Google is about to end the support of third-party apps to fetch email only using username and password. The change will come into effect on 30 May 2022.

This will affect a large number of Freescout users!

Details plus possible solutions: https://support.google.com/accounts/answer/6010255

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1877

**Comment by vertizio** [comment]
Ah, I missed it because it was already closed.

FS will need some updates on the instruction manual though.

**Comment by freescout-helpdesk** [comment]
> Make sure to [enable less secure apps](https://myaccount.google.com/lesssecureapps?pli=1) in your Google account to send emails from Gmail.

Where do you see this phrase?

**Comment by freescout-helpdesk** [comment]
We've found it - in the mailbox settings in "Sending Email".

**Comment by freescout-helpdesk** [comment]
Fixed in master branch.
