### ISSUE TITLE
Is it possible to add extra customer entries to a conversation?

### ISSUE THREAD

**Issue by zpfvo** [freescout-helpdesk/freescout#1944]
We often have the situation that we are getting issues forwarded through an intermediary.
The contact information to the actual user having the problem is most of the time only attached in the mail.

So in a normal case we call the user resolve the issue and than report back to the intermediary.
It would be great if we could manually create the customer from the information in the mail and then attach it to the conversation too.

Is this possible?

**Comment by freescout-helpdesk** [comment]
In the "Change Customer" dialog you can create a new customer

![2022-04-30_08-20-03](https://user-images.githubusercontent.com/40499291/166092399-9ee7905e-963d-4deb-b80c-030a61fe68c5.png)
