### ISSUE TITLE
no automated outgoing email and answers are also not outgoing

### ISSUE THREAD

**Issue by BiotTT** [freescout-helpdesk/freescout#1946]
If a new ticket comes in there is no automated email going back to the sender. Also if i try to answer  a ticket directly no message gets delivered. Do i just need to wait? Or manually confirm the emails? If i press on send test email it arrives. I dont see any of the replyes in the outgoing email log.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/72692155/165146004-8a49e5b6-5b62-4656-8cfd-2cde22755298.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/72692155/165146398-6ba1bd31-1df2-4df2-be39-c6b60009975a.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/72692155/165146539-c5daaa76-4151-4bb4-9c4b-a343866c260e.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/72692155/165146211-12fb4898-048d-4697-9435-8cc7a136e015.png">

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by BiotTT** [comment]
Wow i cant Figuren Out the issue
