### ISSUE TITLE
Workflow can cause infinite loop

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#1947]
Conditions:
- Workflow and Custom Field module installed

Steps to reproduce:
- Create workflow containing a condition "Custom Field Test = Value" and Action "Set Custom Field Test = Value"

This will cause a App\Jobs\TriggerAction Error, which does not contain any info on which workflow actually caused the issue.
Working on a system with continuously incoming mails, this will lead to new mails occasionally not being received by Freescout.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Make sure you are using the latest version of FreeScout, Workflows and Custom Fields modules.

**Comment by freescout-helpdesk** [comment]
We've made some adjustments in the Custom Fields Module v1.0.13. Maybe it will help.
