### ISSUE TITLE
Keep current assignment when replying to a conversation

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#195]
If we set to automatically assign a conversation to "anyone" from the mailbox configuration but we manually set the conversation to a specific user, when replying to that conversation, the original assignment must be preserved.

Currently, the actual assignment is ignored and conversation will be assigned based on the mailbox configuration.

Mailbox configuration should be honored only for the first time.

**Comment by freescout-helpdesk** [comment]
It already works this way.

**Comment by guestisp** [comment]
No, not exactly, there is something strange.
I'll check

**Comment by guestisp** [comment]
I can confirm. Try to reply to a closed (in example) convesation assigned to yourself.
The default value for `Assign To:` is `Anyone` and not `Me` as it should be

The same happens when replying as administrator. The default assignment should be the older one, regardless the user (as administrator is one level above all, if conversation was assigned to `User2`, when replying the conversation should stay assigned to `User2` if not changed manually)

**Comment by freescout-helpdesk** [comment]
Reproduced. To reproduce mailbox's "Default Assignee" must be set to "Anyone"

**Comment by guestisp** [comment]
Yes, but as wrote in this issue, the `Default Assignee` should be honored only at once. If conversation is already assigned, there is no a `default assignee`

**Comment by guestisp** [comment]
Fixed this. Please check if working properly on your side. On our side is working as expected
