### ISSUE TITLE
More advanced formatting options

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#1951]
Is there any way to add more formatting options as I came across one missing that we'd regularly need to use which is blockquote so it would be nice to have that one (as well as others I am sure) - the current formatting options are pretty limited/basic.

**Comment by psuet** [comment]
Blockquotes are included here: https://freescout.net/module/extended-editor/

**Comment by zigojacko** [comment]
> Blockquotes are included here: https://freescout.net/module/extended-editor/

I see 😂

Okay, thanks.
