### ISSUE TITLE
Redirect loop when clicking on conversation

### ISSUE THREAD

**Issue by smart-matwolf** [freescout-helpdesk/freescout#1952]
Hello,

Freescout version 1.8.12.

We just received an email that correctly triggered 2 workflows:

1. move to another mailbox
2. assign to user

Seems like something went wrong. We see the conversation into the original mailbox, but we cannot open it.
We get a redirect loop (too many redirects) on the following link: https://mydomain.example.com/conversation/112?folder_id=39

What can we do to debug this and regain access to the conversation?

Thanks in advance

**Comment by freescout-helpdesk** [comment]
You need a developer who can debug it for you. https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
