### ISSUE TITLE
End-user portal fields pre-filling is not overriding the local storage data

### ISSUE THREAD

**Issue by onyxmaster** [freescout-helpdesk/freescout#1953]
Hi!

Thanks for fixing the #1938 so quick, much appreciated. It works almost as desired, but the query string fields do not override the `eup_ticket_form` local storage data contents. Now, consider the following example, the EUP is first opened without the query string, and the `eup_ticket_form` caches the empty form. Now, the EUP is opened with the query string present, but since `eup_ticket_form` local storage contents takes precedence -- the query string does not auto-fill the required fields.

Thanks for taking a look at this!

**Comment by freescout-helpdesk** [comment]
Yes. It works only when the form is opened first time.
