### ISSUE TITLE
I'm losing HTML formatting in inbound tickets

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#1954]
Is there anything that can be done to retain the HTML formatting in tickets when they come in? We do a lot of client website testing and have to place orders and things like that so they come from ecommerce websites and have broken format/layout.

**Comment by zigojacko** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/FAQ

Ah I see, we've got to click 'Show Original'. Be nice if we could just set that as a default though.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed
