### ISSUE TITLE
Mobile Notifications - Not Receiving Push

### ISSUE THREAD

**Issue by Cytotoxic** [freescout-helpdesk/freescout#1955]
Just installed mobile push notifications module but we are not receiving any event on our phone apps (google and apple versions). Mobile push notification check-boxes are all ticked for the users.

Mobile Notifications  Version: 1.0.1 
Freescout: 1.8.12

No errors, and I see Modules\MobileNotifications\Jobs\SendPushNotificationToUsers in the queue-job.log set as processed. And we are able to login on the app and see updates happening inside the app. We just don't get any notifications.

Any idea on what to check?

**Comment by arthur5005** [comment]
@Cytotoxic what was your resolution here? Experiencing the same.

**Comment by arthur5005** [comment]
Hmm, seemed to finally work... My guess is that all instances of the webapp in your account need to be closed, not just the app? That seemed to be the only thing that made a difference for me.
