### ISSUE TITLE
Time problem with Europe/Berlin

### ISSUE THREAD

**Issue by ollesson-allard** [freescout-helpdesk/freescout#1956]
Hi,

I have problem with timezone i have set the timezone to Europe/Berlin but the time i still 2 hours of.

![image](https://user-images.githubusercontent.com/65387364/165447540-23db2de8-aeef-41ac-993e-5aa398e5328b.png)

I am using docker, but when i ssh into it and check the time it is correct timezone ass well in the php.ini file.

**Comment by freescout-helpdesk** [comment]
What is exactly the problem?

**Comment by ollesson-allard** [comment]
Hi,
The problem it is that the time in Freescout off by two houses, so if I send in a ticket 07:00 Berlin time it will show in the Freescout 05:00 I instead. 
![image](https://user-images.githubusercontent.com/65387364/166188614-d9dd20dd-aefc-4ff8-9867-cb46b11772e6.png)

Thanks Emil

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by ollesson-allard** [comment]
No, Thanks for the help I think it's a local problem for me.

**Comment by zpfvo** [comment]
Hi, I'm running into the same issue (using tiredofit/freescout:1.15.47 docker image). Did you resolve the problem?

**Comment by elyazalee** [comment]
Hello
I confirm there is a problem
![bugtime](https://user-images.githubusercontent.com/6560933/184336465-f9418c15-8c81-4d9a-bd33-a8e4e50e20ee.jpg)
