### ISSUE TITLE
Tables in FreeScout notes

### ISSUE THREAD

**Issue by JDH212** [freescout-helpdesk/freescout#1957]
I'm currently learning the basics of Freescout due to an automation project that will use it in the near future.

Basically my issue is tables that are pasted into the notes/replies in freescout do not stay in table format when you've commited the note  and the way we'll be using Freescout we need the tables to stay in a table format and not remove it and just leave the text.

Is there a way around this? or is there something im missing? I'd added he extended editor module as i saw the mention of adding tables but that hasn't solved the issue.

Thanks
Jonny

**Comment by JDH212** [comment]
So I believe there is a "view original" option, but is there a way to make this permanant?

The only thing realistically being viewed in Freescout will be tables.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed
