### ISSUE TITLE
The API doesn't allow querying by custom customer fields and doesn't allow updating normal customer fields

### ISSUE THREAD

**Issue by onyxmaster** [freescout-helpdesk/freescout#1959]
Hi!
I'm looking for a way to integrate our internal database with Freescout. Zendesk has [create_or_update](https://developer.zendesk.com/api-reference/ticketing/users/users/#create-or-update-user) API call that we're using right now. Unfortunately, FreeScout doesn't appear to have an update method. I though I might be able to use customer fields module and our internal ID as a customer field, but the [list-customers](https://api-docs.freescout.net/#list-customers) API does not allow searching by customer fields (understandable since you probably do not build indexes there). Also, there is no email-based searches, so we just cannot reliably match our internal DB with the FreeScout one to keep customer data up-to-date.
Could you provide any advice/direction on this issue or maybe expand existing functionality to facilitate this scenario?

**Comment by freescout-helpdesk** [comment]
We'll try to add possibility to search customers by email

**Comment by freescout-helpdesk** [comment]
Searching customers by email added in API & Webhooks Module v1.0.39
