### ISSUE TITLE
Save mail password between deployments

### ISSUE THREAD

**Issue by 2fa** [freescout-helpdesk/freescout#1960]
Hello.

I'm trying to do a full automatic deployment of Freescout through Terraform (non-docker version). If i destroy existing instance of VM (w\o mysql) and bring it back, almost everything works fine, except there's no saved passwords for mail configurations (both mailboxes and system mail).

Is there any way to save email password and populate it after clean install? As far as i am understand it should be saved in DB and looks like a bug to me. 

User passwords and 2FA works correctly.

**Comment by freescout-helpdesk** [comment]
Passwords are stored in DB and encrypted. Encryption uses APP_KEY from .env file.

**Comment by freescout-helpdesk** [comment]
Yes. Google how Laravel stores user passwords.

**Comment by 2fa** [comment]
Great, thank you.
