### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by ioscanner** [freescout-helpdesk/freescout#1962]
I just purchased most of the modules.  I am coming from Live-Help Chat and it was very fast with web chat.  This one seems to be very slow.  I type a message in the web chat and it take a minute or more to post a ticket or a response.  Same goes when I reply  to a message from an agent in the interface or ios app.

Is there a way to speed this up?  So far this is the only issue I have with Freescout.  It makes web chat not usable.  Clients are use to chat being responsive and quick as it has always been.  It should be like any other application that does chat.

Thanks

**Comment by freescout-helpdesk** [comment]
If your server is powerful enough you can adjust polling interval in /Modules/Chat/Public/js/widget_form.js in chatGetPollInterval() function on line 547. Numbers there are in milliseconds.
