### ISSUE TITLE
Administrator Notifications

### ISSUE THREAD

**Issue by zamashal** [freescout-helpdesk/freescout#1963]
As an administrator, when I enable notifications I get notifications for all mailboxes. This shouldn't be the case. I am an IT administrator and I only want notifications for my IT mailbox. I tried removing permission for all other mailboxes in my profile settings, I also tried hiding my user from assign list of all other mailboxes, none of those worked and I am still getting notifications for all mailboxes.

Please help implement a way to select notifications from specific mailboxes only.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#admins-get-notifications-for-all-mailboxes-what-to-do
