### ISSUE TITLE
Webhook body is always empty for convo.created

### ISSUE THREAD

**Issue by codezz** [freescout-helpdesk/freescout#1964]
Hi, 
Webhook body is always empty for convo.created.
I have the problem with the latest version 1.0.3.9. 
I saw an older ticket that should have been addressed but I always receive empty body resposne:
`{
"headers": {
"host": "xxx",
"http_host": "xx",
"x-real-ip": "xxx",
"x-forwarded-for": "xxx",
"x-forwarded-proto": "https",
"content-length": "0",
"user-agent": "GuzzleHttp/6.3.3 curl/7.80.0 PHP/8.0.17",
"content-type": "application/hal+json",
"x-freescout-event": "convo.created",
"x-freescout-signature": "xxx="
},
"params": {
},
"query": {
},
"body": {
}
}`

Related: 
https://github.com/freescout-helpdesk/freescout/issues/1729

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of FreeScout and API & Webhooks Module?

**Comment by codezz** [comment]
Yes, it is the latest version on Freescout and the addon.

**Comment by freescout-helpdesk** [comment]
Strange. What version of API & Webhooks Module do you have?

**Comment by codezz** [comment]
I tested on requestbin and it sends the body data. When testing in n8n.io the body data is empty. any specific settings to the webhook other than listening on for POST requests?
Thanks

**Comment by freescout-helpdesk** [comment]
> any specific settings to the webhook other than listening on for POST requests?

No.

**Comment by codezz** [comment]
Ok then I guess I need to go over your code

**Comment by freescout-helpdesk** [comment]
Let us know if you'll find the reason.

**Comment by lpadula** [comment]
> Ok then I guess I need to go over your code

Hi, i have the same problem with n8n. Do you find a solution?

**Comment by codezz** [comment]
> > Ok then I guess I need to go over your code
> 
> Hi, i have the same problem with n8n. Do you find a solution?

Unfortunately I haven't found the cause. I used a trick and sent the we hook to a server and then forwarded it to N8N :)

**Comment by freescout-helpdesk** [comment]
Could you please create a Bug Report in n8n repo providing them with the details of the n8n you are using: https://github.com/n8n-io/n8n/issues

**Comment by patforg** [comment]
I have the same issue. 

I was testing on my local machine with ngrok + php server and body was coming in just fine.

I switched to my production environnent using nginx + php-fpm and now the body is empty.

**Comment by freescout-helpdesk** [comment]
> I have the same issue.
> 
> I was testing on my local machine with ngrok + php server and body was coming in just fine.
> 
> I switched to my production environnent using nginx + php-fpm and now the body is empty.

What PHP version are you using? Could you please try to send a webhook to https://webhook.site and share results.

**Comment by patforg** [comment]
I deleted the hook and re-created it, the problem went away

**Comment by freescout-helpdesk** [comment]
> I deleted the hook and re-created it, the problem went away.

Thanks. Those who will be facing this issue please try to do the same.

**Comment by tufloc** [comment]
Just as a heads up, I've opened an issue on n8n's Github repo (n8n-io/n8n#3679)

Because this is a paid module, it's a bit of a problem for their people to offer any assistance.

Perhaps someone from FreeScout can contact them directly so we can resolve this issue?

**Comment by tufloc** [comment]
If anyone missed the discussions on the n8n's Github, there's now a workaround for this issue on the abovementioned issue page.
