### ISSUE TITLE
"Closed" page does not show correct order

### ISSUE THREAD

**Issue by AliekeStijf** [freescout-helpdesk/freescout#1965]
There seems to be some kind of bug happening in the "closed" page. 

when I navigate to the closed page of a mailbox, then try to order them by date closed it does not actually show me the correct order:
![image](https://user-images.githubusercontent.com/104830030/166435063-d15a4433-b84d-49d3-8623-fb6bb4cf4067.png)

I'm not sure what order it DOES give me, but maybe I am missing something.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
