### ISSUE TITLE
1.8.13 -> email sending broken

### ISSUE THREAD

**Issue by proserver1** [freescout-helpdesk/freescout#1967]
Hi,

running 1.8.12 (several moduls). after upgrading 1.8.13 freescout stopped sending / outgoing emails silently.
took me 1 day to realize. reason unknown, no errors.

had to rollback to 1.8.12 but can investigate if of common interest (aka I am not the only one with the problem)

**Comment by zanardigit** [comment]
I have a similar issue but it was there even before updating to 1.8.13. 
Sending a test email works fine; but automated email notifications do not work (SMTP login fails). I was also going to investigate.

**Comment by zanardigit** [comment]
Ignore my previous message. I forgot that I need to update both my system email settings and my mailbox email settings. Everything is working fine now.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues#if-emails-are-not-sent

**Comment by proserver1** [comment]
it's not a general email sending problem. it comes with upgrade to 1.8.13 and vanishes after rollback to 1.8.12
wil investigate after next try of upgrade (thx for patience) and check the mail logs.

**Comment by freescout-helpdesk** [comment]
If the problem was in the release we would have received hundreds of support requests. We'll close this for now.
