### ISSUE TITLE
Can't receive mails through davmail

### ISSUE THREAD

**Issue by superwinni2** [freescout-helpdesk/freescout#1970]
Hello

I'm trying to connect FreeScout via Davmail to On-Premise Exchange 2016.
FreeScount runs on Debian 11 with PHP8.1
Badly I can't get it worked.
Davmail is working correctly. With other mailclients like Thunderbird it's possible to receive mail through it after I set my own CA as trusted.
But with Freescout I always get "Error. Check internet connection and try again."

What I've done:
- Install davmail. Configured it to use TLS with own CA.
- Updated / Inserted own CA in /etc/ssl/certs/ca-certificates.crt
- Updated / Inserted own CA in /etc/ssl/certs/java/cacerts
- Updates / Inserted own CA  in /usr/local/share/ca-certificates/cert.crt and run update-ca-certificates
- Disabled the "validate certificate" optionbox in Postbox Connection settings.

Any other Ideas how to get it to work with davmail?

Thank and Greetings

**Comment by freescout-helpdesk** [comment]
We'll close this as over several months no-one could answer this.
