### ISSUE TITLE
[from address] issue from address not the same as user XX

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1971]
@freescout-helpdesk 

Please could you let us know why we get this in the logs.

`From address sales@domain.com is not the same as user 15 email: shaneez@domain.com`

We literally have thousands of these listed in logs.

Thanks
M

**Comment by freescout-helpdesk** [comment]
You need to add shaneez@domain.com to user's Alternate Emails

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks.
I am sure we should do this the other way, where we add the sale@ as an alternate email to the users profile. 
Is this correct?

**Comment by freescout-helpdesk** [comment]
Yes.
