### ISSUE TITLE
Error upgrading from 1.8.12 to 1.8.13

### ISSUE THREAD

**Issue by Pablohn26** [freescout-helpdesk/freescout#1973]
JFYI I cannot use web updater to update from versión 1.8.12 to 1.8.13

Everything seems OK at permissions level 

![2022-05-05_12-11](https://user-images.githubusercontent.com/1228418/166903546-3a54bd32-9065-4fed-8db7-9f7799206088.png)

![2022-05-05_12-13](https://user-images.githubusercontent.com/1228418/166903826-c7ac4bd4-a4eb-4e4f-b8de-865254dbb4c9.png)

![2022-05-05_12-13_1](https://user-images.githubusercontent.com/1228418/166903822-e9f3365c-8ef7-4a74-8dd2-cb12a9c86975.png)

The log shows the following:

```
Error: SplFileInfo::isDir(): open_basedir restriction in effect. File(/home/supportb/domains/support.example.com/public_html/public/modules/sentfolder) is not within the allowed path(s): (/home/supportb/:/tmp:/var/tmp:/opt/alt/php81/usr/share/pear/:/dev/urandom:/usr/local/lib/php/:/usr/local/php81/lib/php/); File: /home/supportb/domains/support.example.com/public_html/overrides/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php (62)
--
```
Using [InterServer](https://www.interserver.net/apps/freescout-hosting.html) one click installation

**Comment by ilyakonovalenko** [comment]
It is something related to your hosting provider open_basedir policy or PHP/webserver configuration. As your hosting provider.

**Comment by raramuridesign** [comment]
@Pablohn26 Try doing the manual update. See if this resolves the issue.
I've had issues like this before and extracting and running /tools.php works much smoother.
We then run permissions check once this is done.

**Comment by Pablohn26** [comment]
I have used the [second update method](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-2-update-using-console-script). I got a database problem but the platform has been updated. I left here the output that I got, maybe it is interesting. 

![image](https://user-images.githubusercontent.com/1228418/166985785-fcba70ce-c312-4ee1-b3dc-e5b64d832828.png)

**Comment by raramuridesign** [comment]
@Pablohn26 The errors are telling you the table ie jobs, has an error. If you read the error you can probably fix this using phpmyadmin, as the table needs some adjustment. Perhaps a comparison might be needed.
There is a command to do a db migrate. You may want to run this.

**Comment by freescout-helpdesk** [comment]
"jobs" table is usually created upon help desk installation.
