### ISSUE TITLE
Kanban - Unlink ticket from task, or remove from board

### ISSUE THREAD

**Issue by dealend** [freescout-helpdesk/freescout#1975]
After using the module for a while, we realized, if a ticket is accidentally added to the wrong board, or, added twice to the same board; there is no way to remove the duplicate entry from the board or unlink the ticket from the task on the board.

If you look at the image below, we have 3 tasks for the same conversation created accidentally, we still need one. The problem is if you close the ticket, all of them disappear, and if you reopen the ticket, all of them come back. Seems like a really odd oversight.

![image](https://user-images.githubusercontent.com/83796325/166947538-ce983e80-adb9-4408-a3e9-040f25ce2a4e.png)

**Comment by dealend** [comment]
Any feedback on the above?

**Comment by freescout-helpdesk** [comment]
We'll try to do something about it.

**Comment by freescout-helpdesk** [comment]
Deleting cards linked to conversations added in Kanban Module v1.0.7
