### ISSUE TITLE
threads.user_id is NULL after releases 1.8.12

### ISSUE THREAD

**Issue by aorkne** [freescout-helpdesk/freescout#1976]
Column "user_id" in table "threads" doesn't get values after addition new values since release 1.8.12 (It starts 14.05.2022) - 3 column is user_id

![2022-05-05 18_14_58-](https://user-images.githubusercontent.com/16033869/166982145-19e87ac3-447a-42e1-b802-e20415b79146.png)

After that stopped work module Reports - productivity , because it aggregates data on that column

<img width="1475" alt="Screenshot 2022-05-05 at 20 47 26" src="https://user-images.githubusercontent.com/16033869/166982822-6eb4e2be-ea6d-41f2-bd40-0117485f4f9c.png">

**Comment by freescout-helpdesk** [comment]
How do you create threads and assign conversations? Manually or via API?

**Comment by aorkne** [comment]
> How do you create threads and assign conversations? Manually or via API?

Both variants

**Comment by aorkne** [comment]
Threads creates manually as user replies (type=2). Threads with others statuses could be ok
![111111](https://user-images.githubusercontent.com/16033869/167073761-a5bbccdc-5683-4639-880a-f536962b128d.png)

**Comment by freescout-helpdesk** [comment]
The problem was in Reports module. Thread's author is stored in thread.created_by_user_id and thread.user_id stores the Assignee ID at the moment the thread is created.

Fixed in Reports Module v1.0.14

**Comment by aorkne** [comment]
Thank you!

**Comment by aorkne** [comment]
So, Reports Module v1.0.14 still has bugs:
1.  Data in column "closed" in table under chart and the chart with this status (closed) still have wrong data.
2. Column "customers helped" has properly data, but the chart shows wrong data.

Column and chart "replies" work properly.

**Comment by freescout-helpdesk** [comment]
Should be fixed in Reports Module v1.0.15. Please check.

**Comment by aorkne** [comment]
Sorry, but in new version status "closed" still counts wrong.

**Comment by freescout-helpdesk** [comment]
Can you give a screenshot?

**Comment by aorkne** [comment]
What is in the report (8 in last week):
![222](https://user-images.githubusercontent.com/16033869/167090872-f3f81dcf-8483-49ae-b2d1-2de8b53d6ea1.png)

In real (12 in the last 14 hours)
![333](https://user-images.githubusercontent.com/16033869/167090991-d56387e6-0b4e-4085-a795-7f4b338ec4ee.png)

**Comment by freescout-helpdesk** [comment]
Try to comment the following lines in /Modules/Reports/Http/Controllers/ReportsController.php:

843: //->where('threads.created_by_user_id', '!=', null)
947: //->where('threads.created_by_user_id', '!=', null)

**Comment by aorkne** [comment]
Nothing changed

**Comment by freescout-helpdesk** [comment]
Check if all those conversations have Closed line items:

![2022-05-06_11-51-40](https://user-images.githubusercontent.com/40499291/167099626-d884061f-97ec-4166-b35d-0e6df8da1937.png)

**Comment by aorkne** [comment]
No, they don't. Could you please explain what does it mean?

**Comment by freescout-helpdesk** [comment]
How were they closed? Via API? Not via the web interface?

**Comment by aorkne** [comment]
We made setting in maii box, to close after reply

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1.0.16

**Comment by aorkne** [comment]
Thank you, now everything works properly!
