### ISSUE TITLE
Replying to Trouble Ticket with Auto Default Saved Replys

### ISSUE THREAD

**Issue by Nimdy** [freescout-helpdesk/freescout#1978]
If there a way to have the set a variable to the default reply template?

I would like to add 

`Hi {%customer.fullName%},`

on each reply.

As it stands now, I have to click a Saved Reply just for one variable.  Where can I edit this manually as the Default Template?

I would like this
![auto](https://user-images.githubusercontent.com/16698453/167014979-0d4dcdc5-8181-4b02-966c-d0f6a695ccb2.png)

Defaulted to this, without clicking anything
![auto1](https://user-images.githubusercontent.com/16698453/167015210-5f15ac16-d26b-4fa7-89fc-4ff35a59ce9e.png)

Thank you

**Comment by Nimdy** [comment]
Oh, I am trying to leave Freshdesk and they have this feature. I like FreeScout and I have purchased all the modules but small quality of life changes for the support team would be nice.

Thanks again

**Comment by MarcoWel** [comment]
+1

**Comment by Nimdy** [comment]
Ping - Pong

**Comment by freescout-helpdesk** [comment]
It looks you want an option allowing to set some Save Reply as loaded by default when replying. Feel free to add a feature request: https://freescout.net/request-feature/
