### ISSUE TITLE
Freescout not fetching e-mails after mail server was down

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#1981]
After Freescout (version 1.8.13) discovers the mail server is not reachable for a certain mailbox, it seems to just stop fetching emails for that mailbox until an admin manually forces email fetching via the Tools menu.

The only error showing in the error log is:
`May 6, 18:17:24	Fehler beim Empfangen der E-Mail	Error: imap_open(): Couldn't open stream {xxxxx.xxxxx.com:xxx/imap/ssl}. Can't connect to xxxxx.xxxxx.com,xxx: Connection timed out; Can't connect to xxxxx.xxxxx.com,xxx: Connection timed out; File: /var/www/html/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)`

Interestingly, the Laravel log additionally shows:
`  error	production	2022-05-06 18:19:35	 Call to a member function sortBy() on array {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function sortBy() on array at /var/www/html/app/Console/Commands/FetchEmails.php:1096)`

Freescout is obviously not able to send out a warning message if the mail server set for system messages is the same one that has been gone down for the mailbox (maybe here is the culprit?).

Desired behaviour: After Freescout is not able to reach the mail server, it should periodically retry (even after the mail server for system messages has been gone down, too).

**Comment by freescout-helpdesk** [comment]
> After Freescout is not able to reach the mail server, it should periodically retry (even after the mail server for system messages has been gone down, too).

This is how it works.

Are you using modern Microsoft Exchange authentication or regular IMAP?

**Comment by MarcoWel** [comment]
We use IMAP. I did some further investigation and changed the system mail SMTP server to a different one (Gmail), which is recommended anyway - so we still get alerted once the primary mail server goes down.

It seems that after a certain event (not sure what it is yet), Freescout just stops fetching e-mails altogether. Nothing recent in the logs, Cron job is reported to be running just fine. Only after a manual fetch a ton of new mails get imported.

**Comment by freescout-helpdesk** [comment]
> so we still get alerted once the primary mail server goes down.

What error message are you receiving in this case?

**Comment by freescout-helpdesk** [comment]
Also what is your PHP version?

**Comment by freescout-helpdesk** [comment]
> Call to a member function sortBy() on array

This has been fixed in the `master` branch.
