### ISSUE TITLE
Value Time Spent on CSV Export is wrong

### ISSUE THREAD

**Issue by Chillking1493** [freescout-helpdesk/freescout#1983]
In the CSV Export (UTF8 , separeted Values) the value Time Spent Time Spent is sometimes wrong

The Export displays 444:03:00
![image](https://user-images.githubusercontent.com/105270953/167574177-c51204a5-7f3c-49e6-9b1f-ad2d1b45d8c9.png)

the correct value is
![image](https://user-images.githubusercontent.com/105270953/167574290-134b1380-1d01-48f6-a920-946b776f8802.png)

Time Tracking options are following
![image](https://user-images.githubusercontent.com/105270953/167574412-1b3f5c0a-14ee-485c-85fd-ed5617667093.png)

**Comment by freescout-helpdesk** [comment]
You may need to debug the issue yourself as we don't have access to your server or https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by Chillking1493** [comment]
@freescout-helpdesk  this "Bug" exists also in Demo Version  https://demo.freescout.net/conversation/20?folder_id=4
![image](https://user-images.githubusercontent.com/105270953/167590595-6a441ec7-18aa-483e-be49-cce2b8b793b6.png)
![image](https://user-images.githubusercontent.com/105270953/167590715-70411530-daad-4bd1-8e25-8017d5792aa8.png)

**Comment by freescout-helpdesk** [comment]
Fixed in Export Conversations Module v1.0.4
