### ISSUE TITLE
SAML module error with Azure AD

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#1985]
I am trying out the new SAML module. I got the following error when authenticating. I am using 8.1.13 and I have done no user field mapping.

(ACS endpoint) Missing request_id in session.

Ahmed

**Comment by freescout-helpdesk** [comment]
If you can provide an access to your Azure and FreeScout please email at support@freescout.net

**Comment by olpo24** [comment]
I this fixed?
I have this same massage weith using wordress with this plugin as SAML IDP https://plugins.miniorange.com/wordpress-saml-idp
