### ISSUE TITLE
Docker install on Windows

### ISSUE THREAD

**Issue by PsycoStea** [freescout-helpdesk/freescout#1987]
I have been through the docker installation guide but I don't understand what is going on. I don't know about using docker or most of the terminology use in the help guide. I just want to give FreeScout a try to see how well it works. Can someone please help me with the install step by step?

**Comment by freescout-helpdesk** [comment]
Install without using a docker: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
