### ISSUE TITLE
Can't change Conversation Customer

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#1988]
Every time I try changing the customer, it says it's changed, but it doesn't actually change.
This issue has been constant since I first set up FreeScout a few months ago.

I'm running FreeScout with Docker on TrueNAS Scale.
FreeScout Docker is updated to the latest version. and all Modules are currently updated to lasted version as well.

If anyone can help me, that would be greatly appriciated.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Can you attach a screenshot of how you are changing the customer. Also can you reproduce the issue on demo.freescout.net?
