### ISSUE TITLE
ticket numbers too specific

### ISSUE THREAD

**Issue by abooltink** [freescout-helpdesk/freescout#1989]
Hi,

The ticket number module works well if 

- the ticket number code [#xxxxx] is the first text in the subject line AND
- the sender is the same as the original sender.

As soon as one of these requirements is not met, the ticket number module generates a new ticket. That means if multiple users on the customer side are responding to the ticket, every of those users gets an own ticket.

And also if somebody puts anything in front of the ticket number, a new ticket is generated.

Can this behaviour be changed or am ) doing something wrong?

Regards,
Axel Booltink

**Comment by freescout-helpdesk** [comment]
It has nothing to do with ticket number module. Your issue must be in something else. FreeScout does not check subjects of messages - it checks email body and headers.

**Comment by abooltink** [comment]
Hi,

Yes, you are right. If everybody neatly answers to the conversation no new ticket is created. And if anybody sends a new mail outside of the existing conversation it does not matter if the ticketnumber is in the subject or not - a new ticket is generated then always.

Thanks for clearing this - it has helped me.

Regards,
Axel Booltink
