### ISSUE TITLE
Forward asignated email to External Email

### ISSUE THREAD

**Issue by ninjoan** [freescout-helpdesk/freescout#1991]
Hello guys i'm using the freescout since 2021 work great very happy.

i have a question/request
Is it possible to forward an email to an external address outside Freescout.

My scenario is the follow
I have 3 staff that use the Freescout I would like to create an Administrative USER that when the user assigned any email to this user the email is sent to an external address

running v 1.7.25

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/workflows/
