### ISSUE TITLE
[Error fetching email] Error: imap_open(): Couldn't open stream

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1993]
@freescout-helpdesk 
We are unsure why this is happening as the settings for fetching email is setup as per screenshot.
if you could shed some insight that would be great.
M.

**Error**

`Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/novalidate-cert/ssl}. No such host as imap.gmail.com; File: /home/help/webapps/help/public/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)`

**Screenshot**

![image](https://user-images.githubusercontent.com/902376/168025487-93b0444a-7537-4c42-9db3-6e9d357b3a19.png)

**Comment by raramuridesign** [comment]
@freescout-helpdesk any idea on this ?

**Comment by freescout-helpdesk** [comment]
This means your server has problems accessing imap.gmail.com. Contact your hosting provider.

**Comment by raramuridesign** [comment]
@freescout-helpdesk I am closing this as I have not seen the error 
It seems that #1984 may have solved this but unsure. If it happens to show again I will drop a new issue.
