### ISSUE TITLE
x-forwarded-for set but remote_addr stored on login

### ISSUE THREAD

**Issue by jtorvald** [freescout-helpdesk/freescout#1994]
First of all I want to thank you for making Freescout. I've been trying it out for a week now and it feels so good to use an open source tool that simply just works. Very smooth experience!

I just have one problem for which I checked all the links/issues but can't find the answer.
I'm running a proxy in front of the Freescout application (running with Docker, but is most likely not the cause of this issue).

When I log in to Freescout the IP of the server is stored (value from: `$_SERVER['REMOTE_ADDR']`) and not the value from `$_SERVER['HTTP_X_FORWARDED_FOR']`. When I check the login logs /app-logs/users it shows the REMOTE_ADDR IP. 

The real IP is in `$_SERVER['HTTP_X_FORWARDED_FOR']`. I verified that by requesting a PHP file in the uploaded directory through the proxy.

**Comment by jtorvald** [comment]
I spent quite some time looking through the code and it seems like it should already support this functionality but for some reason it behaves not consistent. Maybe you guys are a bit more into the ins- and outs from Laravel and the current vendoring/overrides.

I will explain it with LogFailedLogin as an example:
ip=> in the handle function should probably be `request()->getClientIp()` which takes into account the forwarded for headers.
For it to respect the forwarded headers, it needs a trusted proxy to be configured for security reasons.
The code to make that happen is already available.

/www/html/app/Listeners/LogFailedLogin.php:
```
    public function handle(Failed $event)                                                                                                                                                                                                                 
    {                                                                                                                                                                                                                                                     
        activity()                                                                                                                                                                                                                                        
           //->causedBy($event->user)                                                                                                                                                                                                                     
           ->withProperties(['ip' => request()->getClientIp(), 'email' => request()->email])                                                                                                           
           ->useLog(\App\ActivityLog::NAME_USER)                                                                                                                                                                                                          
           ->log(\App\ActivityLog::DESCRIPTION_USER_LOGIN_FAILED);                                                                                                                                                                                        
    }  
```


### Add trustedproxy.php file in config:
/www/html/config/trustedproxy.php
```
<?php
                        
return [
    'proxies' => [
        '192.168.10.10',
    ],                   
                         
    // These are defaults already set in the config:
    'headers' => [                                  
        (defined('Illuminate\Http\Request::HEADER_FORWARDED') ? Illuminate\Http\Request::HEADER_FORWARDED : 'forwarded') => 'FORWARDED',
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',                                                             
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => 'X_FORWARDED_HOST',                                                            
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        \Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT', 
    ]                                                                        
];  
```

### Not sure if this was needed or already loaded
`php artisan vendor:publish --provider="App\Http\TrustedProxyServiceProvider"`

### Testing:
When testing with a failed login it logs the proxy address.
When I check it in a Module controller with  `$request->getClientIp()` it works as expected.
So either it uses a different request object or it might have to do something with timing of loading the trusted proxies.

I don't have a good development setup now for FreeScout so it's very hard for me to debug this at the moment. But maybe someone else can easily find a fix with the information above.

**Comment by freescout-helpdesk** [comment]
Try to adjust https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Middleware/TrustProxies.php (see https://laravel.com/docs/5.5/requests#configuring-trusted-proxies) and see how it goes.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. Now you also can set trusted proxies via /.env file:
```
# Comma separated list of trusted proxies for proper IP detection in FreeScout.
# To trust all proxies that connect to your server use single asterisk: *
# To trust ALL proxies, including those that are in a chain of forwarding use double asterisk: **
APP_TRUSTED_PROXIES=192.168.1.1,192.168.1.2,192.168.1.3
```
