### ISSUE TITLE
Sent module - shared sent folder

### ISSUE THREAD

**Issue by newz2000** [freescout-helpdesk/freescout#1996]
Thank you, I have purchased a license for the sent folder module. Is it possible to have a shared sent folder, or to make the sent folder configurable to be either per-user or all users? P.S. the link in the GitHub "new issue" form for feature requests takes me to a 404 page.

Use case 1:
* Team member needs to send a message to person x
* Wants to be sure that someone else hasn't already sent the message
* Checks the shared Sent folder, sees that no messages have been sent to person x recently
* Team member sends the message to person x confidently knowing it is not a duplicate

Use case 2:
* Manager wants to review the work of a new agent
* Manager goes to the shared Sent folder and reviews messages sent out to end-users
* Manager confirms that new agent is doing excellent work or finds some coaching opportunities

Thank you!

**Comment by freescout-helpdesk** [comment]
Here: https://freescout.net/request-feature/
