### ISSUE TITLE
Write a message to logs if number of unread and fetched emails does not match

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2001]
We are running Freescout 1.8.14 under PHP 7.4.3 on nginx/1.18.0. This issue might be related to #1981, where Freescout seemed to stop fetching e-mails after the mail server went down for a while.

For us, Freescout is still skipping some messages every now and then when fetching new e-mails. There is no error message being sent, and no error in the logs. Nothing anywhere points out that Freescout could have skipped any emails.

When looking at the mailbox where Freescout is fetching from with Thunderbird, the e-mails that are being skipped by Freescout are marked as Junk (although Rspamd headers clearly mark those messages as not being Spam).

How does Freescout detect new messages? It is only considering messsages still marked as **unread** during the fetching process, correct? Is there any way to do further logging of the fetching process to detect what goes wrong here? Also, shouldn't Freescout notice when the number of total new messages vs. total unread messages differ in a fetching process and at least throw a warning in the logs?

Currently, we need to initiate a manual e-mail fetch via the Freescout tools every day to make sure no e-mails are missed. IMHO one of the most important features of a ticketing system is to reliably fetch ALL incoming messages, and and least notify the users if there are potential problems.

**Comment by freescout-helpdesk** [comment]
> How does Freescout detect new messages? It is only considering messsages still marked as unread during the fetching process, correct?

Yes.

This can be related to this issue https://github.com/freescout-helpdesk/freescout/issues/1981. Before there was no issues with missed emails.

**Comment by MarcoWel** [comment]
As a first suggestion:
- Save the number of total messages in the mailbox for every fetch (https://www.php.net/manual/en/function.imap-num-msg.php).
- If the message count increased more than the number of unread messages from the last fetch, write a warning to the logs (and preferably automatically fetch ALL messages since the previous fetch instead of only unread messages).

**Comment by MarcoWel** [comment]
Great if you will implement this!
Another suggestion when you are at it already:

- Not only write warning to logs, but also send a notice via system mail.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement this.
