### ISSUE TITLE
Problem with fetching mails from imap folders since 1.18.13

### ISSUE THREAD

**Issue by woolmilkpigs** [freescout-helpdesk/freescout#2002]
Since an update from 1.18.12 to .13 or higher fetching mails will result in multiple errors "Error: Mailbox name is not valid mUTF-7". And the fetch-emails.log produces constant errors like "Mailbox doesn't exist".

Only a roll back to 1.18.12 will help and make fetching mails work again.

Can someone help me please?

Thank you!

**Comment by freescout-helpdesk** [comment]
Update to the latest FreeScout version.

**Comment by woolmilkpigs** [comment]
Thank you for the quick reply!

I just updated to 1.18.15 but the problem remains. I updated around 14 days ago to 1.18.13 and the problem occured. I then turned back to 1.18.12 and today I thought maybe 1.18.15 will help but the problem apperas again.

**Comment by freescout-helpdesk** [comment]
Are you using Dovecot?
https://dovecot.dovecot.narkive.com/BDr7lcvr/select-bug-in-untagged-response

**Comment by woolmilkpigs** [comment]
Yes, it is a Dovecot mailserver. But its a shared server so that I cannot change anything at the mailserver. The linked article is quite old and the link to the workaround doesn't work anymore.

I'm just asking myself how I can solve the issue:

a) change the freescout settings connecting to the mailserver, so the issue might disappear
b) contact the mailserver provider that there might be a bug from 9 years ago (couldn't find any further helpful information)
c) I manually change the part in the freescout files, that lead to the issue since 1.18.13 

What do you think?

**Comment by freescout-helpdesk** [comment]
In 1.18.13-15 releases there was no changes which could cause this issue. Are you using a docker? When upgrading FreeScout are you making any changes in PHP?

**Comment by woolmilkpigs** [comment]
No, I'm not using Docker and didn'tnot make any changes in PHP. Maybe it's just the "new" Error-Output in 1.18.13, that causes the fetching to be disrupted?

....

I just saw the new .16 release and tested it. Even the error (not a valid mUTF7 name) is still logged, mails now appear in the inbox :-) Thank you for the fix!

**Comment by freescout-helpdesk** [comment]
The issue should be fixed in 1.8.16 release.

**Comment by invmedia** [comment]
Hi!

I have two questions.
1) I have the same problem. I am a new user of FreeScout. Yesterday I installed, connected the first inbox. I have the same error in the logs: "INBOX.Investments; Error: Mailbox name is not valid mUTF-7 (0.001 + 0.112 + 0.111 secs)" How can I fix it? I want to be able to access IMAP folders.
2) When I delete a message in FreeScout, will it also be deleted from the mail server if I have an IMAP connection?
