### ISSUE TITLE
Freescout to freescount interference

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#2005]
We are two independent instances of Freescout and we are noticing that an email from one FS to another is reopening old conversations. I think it will be helpful for FS to add some random unique deployment ID to avoid the inference.

**Comment by freescout-helpdesk** [comment]
> ...is reopening old conversations

How does it happen? Can you explain a bit more.

**Comment by afawaz2** [comment]
Suppose I have FS_1 (two years old) and FS_2 (3 months old) deployment. When FS_2 forward a conversation to a mailbox in FS_1 the conversation reopens an old conversation in FS_1.

**Comment by afawaz2** [comment]
Any updates on this?

**Comment by freescout-helpdesk** [comment]
This has been fixed. Use the latest FreeScout version.
