### ISSUE TITLE
Logging issues after upgrading Ubuntu to 22.04

### ISSUE THREAD

**Issue by bilalbinishtiaque** [freescout-helpdesk/freescout#2008]
Hi,

I have upgraded Ubuntu to 22.04 and since then having issues in viewing logs from freescout menu. There are 5 menu options in log section:
- Outgoing Emails
- Fetch Errors
- System
- Users
- App Logs

Out of these 5, Fetch Errors, System and Users pages work fine. However "Outgoing Emails" gives the following error:
"Whoops, looks like something went wrong — check logs in /storage/logs"

and "App Logs" shows a blank page.

And there is one entry repeating in webserver.log:

[crit] 401643#401643: *811 SSL_read() failed (SSL: error:0A000126:SSL routines::unexpected eof while reading) while sending to client, client: [client_ip], server: [servername], request: "POST /polycast/receive HTTP/1.0", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock", host: "[hostname]", referrer: "[referrer_url]"

Any help would be highly appreciated. Thanks

**Comment by bilalbinishtiaque** [comment]
Apparently it was in issue with some data in "send_logs". I truncated that table and it all seems to work fine. 

However the SSL issue in webserver.log file is still there.

**Comment by freescout-helpdesk** [comment]
Something must be wrong with HTTPS configuration.

https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-browser-push-notifications-are-not-working
