### ISSUE TITLE
Requesting actions / filters for two modules

### ISSUE THREAD

**Issue by RienNeVaPlus** [freescout-helpdesk/freescout#2010]
We'd like to to create two pull requests for the following changes required by two of our modules.

## 1. Allow implementation of avatar module
Requested by: #917 and the [avatars module](https://freescout.shop/downloads/freescout-module-avatars/).
- Suggested filter `customer.default_avatar`
Location: `app/Customer.php:1227`
```
    public function getPhotoUrl($default_if_empty = true)
    {
        if (!empty($this->photo_url) || !$default_if_empty) {
            if (!empty($this->photo_url)) {
                return self::getPhotoUrlByFileName($this->photo_url);
            } else {
                return '';
            }
        } else {
            return \Eventy::filter('customer.default_avatar', '/img/default-avatar.png', $this->getMainEmail());
        }
    }
```

## 2. Allow implementation of mailbox icon module
Requested by: #1864 and the [mailbox logos module](https://freescout.shop/downloads/freescout-module-mailbox-logos/).
- [Suggested action `mailbox.before_name`](https://github.com/freescout-helpdesk/freescout/pull/2007/commits)
- [Suggested action `mailbox.update_before_name`](https://github.com/freescout-helpdesk/freescout/pull/2007/commits/544b63a9f9fccc2afe3d2e907cf1fad2b9f63c68)
- [Allow file uploads for mailbox settings](https://github.com/freescout-helpdesk/freescout/pull/2007/commits/de376607b69a597c322dbe4e0713eff2e516c17b)

_See my accidentally closed [pull request](https://github.com/freescout-helpdesk/freescout/pull/2007/commits)._

May I create these two? Thanks

**Comment by freescout-helpdesk** [comment]
Yes, feel free to add.
