### ISSUE TITLE
"expected response code 220 but got an empty response"

### ISSUE THREAD

**Issue by quinnfive** [freescout-helpdesk/freescout#2011]
I had FreeScout setup and working properly. Then I noticed no new support tickets coming in. So I tried to setup the email again by going like this : 

In FreeScout Mail  Settings - System Emails

Usning send method 'PHP mail function' and then Send Test

I get the error : 

"expected response code 220 but got an empty response"

I try then changing this to SMTP and putting in my MailGun account details (that I have setup and assume everything is correct, as i've used MailGun on a number of websites on the same account) when I try to send a test email again I get the error code :

"expected response code 220 but got an empty response"

Any ideas?

**Comment by freescout-helpdesk** [comment]
Try update FreeScout to the latest version.
