### ISSUE TITLE
ProviderRepository.php line 132

### ISSUE THREAD

**Issue by mavanbro** [freescout-helpdesk/freescout#2013]
The application is giving HTTP ERROR 500

When I run the clear-cache, I get this error on ProviderRepository.php:

In ProviderRepository.php line 132:

  array_merge(): Expected parameter 2 to be an array, int given

Any Ideas on resolving this?

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules?

**Comment by mavanbro** [comment]
No, only official modules

**Comment by freescout-helpdesk** [comment]
Strange issue. You may need to debug it yourself on your server.

**Comment by mavanbro** [comment]
Do you have guidelines for the debugging?

**Comment by mavanbro** [comment]
Is is possible todo a reinstall with saving the data?

**Comment by mavanbro** [comment]
a reinstall with reconnect to the old db fixed the issue. still unclear why we got this error
