### ISSUE TITLE
Customize header color and dark mode?

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#2017]
Is there a way that I can customize the header default blue color? (To suit the color to website color)

Is there a dark mode option? (most of the software we use have dark mode)

**Comment by RienNeVaPlus** [comment]
You can customize the header using the [Customization Module](https://freescout.net/module/customization/):
```
.navbar-default {
  background-color: #00589d;
}
```

Dark mode can be found [here](https://github.com/freescout-helpdesk/freescout/issues/1069#issuecomment-788873146).
