### ISSUE TITLE
Could not save outgoing reply to IMAP folder

### ISSUE THREAD

**Issue by lieblinger** [freescout-helpdesk/freescout#2018]
By specifying an imap folder for outgoing mails I'm getting the following error in application log:

```
Could not save outgoing reply to the IMAP folder, IMAP folder not found: SENT - Error: foreach() argument must be of type array|object, string given; File: /var/www/freescout/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (359)
```

We're are connected to an office 365 account (shared mailbox) and the folder is definitely available.

I would be very happy if you could help resolving this issue.

**Comment by freescout-helpdesk** [comment]
It's not implemented yet for modern Microsoft Exchange authentication. We will check what can be done.

**Comment by freescout-helpdesk** [comment]
Does "Get folders" link work for you in the mailbox Connection Settings?

**Comment by freescout-helpdesk** [comment]
We've made some adjustments in the `master` branch. If you can try to test it.

**Comment by freescout-helpdesk** [comment]
Please test it and check App Logs in case of any issues.

**Comment by freescout-helpdesk** [comment]
Any results?

**Comment by lieblinger** [comment]
Today I cloned our installation and checked out the master branch. For some reason I only can sent "Test Mails" from the mailbox connection settings. 

As soon as I'm starting a new conversation there's no mail going to the recipient anymore and the outgoing mail isn't saved into the specified imap folder. I also find nothing in the logs.

**Comment by lieblinger** [comment]
Had to clear the cache :)

No errors in the log, mails are getting sent and also saved in the **Sent Items** folder. 
Seems like everything is working as expected! Thanks for fixing it 👍
