### ISSUE TITLE
When workflow moves to a second mailbox a cases it loses Tags and Custom fields

### ISSUE THREAD

**Issue by eliassader** [freescout-helpdesk/freescout#2019]
We have tested the Workflow it works charm in the same mailbox to Tag and assign users to the cases bases on the custom fields.
The issue is raised as we need to move the case to another mailbox based on a specific Custom Field
The case is successfully moving via the workflow but losing all its Tags and Custom Field Values
Thank you for your help

**Comment by freescout-helpdesk** [comment]
It works like this by design.
