### ISSUE TITLE
Error 500 attaching a file

### ISSUE THREAD

**Issue by ninjoan** [freescout-helpdesk/freescout#2024]
Hello for some reason sometimes when i try to attach a PDF file I get an Error 500 in the Browser Console

```
Polycast connection established!
VM48:1          POST https://domain.com//conversation/upload 500
(anonymous) @ VM48:1
send @ 806879a060cf601e3c4a7dca04ba806424609626324.js:1
ajax @ 806879a060cf601e3c4a7dca04ba806424609626324.js:1
editorSendFile @ 806879a060cf601e3c4a7dca04ba806424609626324.js:188
(anonymous) @ 806879a060cf601e3c4a7dca04ba806424609626324.js:86
806879a060cf601e3c4a7dca04ba806424609626324.js:195 error: 
```

I have tried several browsers same errors
running version 1.7.25

**Comment by freescout-helpdesk** [comment]
Most likely some server configuration issue. See logs and 
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
