### ISSUE TITLE
Error on New conversation - Phone - PHP 8.1

### ISSUE THREAD

**Issue by sainf** [freescout-helpdesk/freescout#2028]
OS Debian 10
PHP 8.1
NGINX

On trying to make a New Message - Phone it reports error without the phone / cliente name fields.
I can't continue without filling the 2 fields.
```
[2022-06-03 07:37:46] production.ERROR: trim(): Passing null to parameter #1 ($string) of type string is deprecated {"userId":1,"email":"---------","exception":"[object]$[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /srv/php/portal/app/Http/Controllers/ConversationsController.php(2642): trim()

```

I fixed adding (string) to:
/app/Http/Controllers/ConversationsController.php (2640), (2641) and (2641) 

![image](https://user-images.githubusercontent.com/1210947/171825550-c96de3d7-8b2d-4450-843d-ccd1202a97c6.png)

After that I have some errors o showing the phone conversation.

Even if we fill them, after creating it gives error on opening the conversation.
```
[2022-06-03 07:42:01] production.ERROR: strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated {"userId":1,"email":"-----------","exception":"[obj$[stacktrace] 

ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated at /srv/php/portal/app/Conversation.php:1528)

```

Added 
if (!empty($this->customer_email) && strstr($this->customer_email, ',')) { to /app/Conversation.php (1528)
![image](https://user-images.githubusercontent.com/1210947/171822625-0cc2e85c-2baa-4e0f-89c1-7abebeef755d.png)

**Comment by freescout-helpdesk** [comment]
Thanks. FIxed in the `master` branch.
