### ISSUE TITLE
Cleanup / Archive process

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#2030]
Hello,

What options do we have for cleanup/archiving of old tickets?

For example, we have automated alerts for downtime delivered to our support mailbox. 6 months later, we do not really need thousands of these clogging up Freescout.
We're applying tags to these alerts via workflows, so we can easily search for them, but there appears to be no way to "select all and delete".

**Comment by freescout-helpdesk** [comment]
There is no options for now. Feel free to add a feature request: https://freescout.net/request-feature/
