### ISSUE TITLE
Change URL Structure

### ISSUE THREAD

**Issue by Batx** [freescout-helpdesk/freescout#2031]
Hello, we were wondering if it would be possible to change the URLs, like for example, our knowledgebase is running at the moment on: https://example.com/hc/3709485893 We would love to have it showing up at https://example.com/ directly. Is there any easy way of doing that? (We have bought nearly all payed extensions). Or at least changing to https://example.com/hc/NAMECHOOSEN.
Same is for the enduser portal. https://example.com/help/3709485893 can we change here also the numbers to letters and or make an easier link?

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible for now. Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by ilyakonovalenko** [comment]
You can try to use nginx proxy from / to /hc/3709485893 to show kb content on the main page. Not best solution, but should work. However, all links will go to /hc/3709485893 in any way.
