### ISSUE TITLE
Cron not running

### ISSUE THREAD

**Issue by diondkb** [freescout-helpdesk/freescout#2032]
Hi,

I have installed Freescout on Godaddy shared hosting and all works except emails are not fetched. I have added the stipulated cron in the installation manual, but dont have a www-data ssh user setup. When I trigger the fetch mail in the browser using the suggesteed url, it works. Any ideas why the cron is not triggered would be appreciated.

Cheers,
Dion

**Comment by freescout-helpdesk** [comment]
Check your background jobs: https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues

**Comment by freescout-helpdesk** [comment]
See also https://github.com/freescout-helpdesk/freescout/issues/2016

**Comment by diondkb** [comment]
Thanks for the replies. I double checked and found that the cron job is firing. I added a file_put_contents into the artisan file and this fired every minute. Not sure why the command is not working. The logs seem to indicate that all is well. The cron job commands I have tried are:

php /var/www/html/artisan schedule:run >> /dev/null 2>&1, and
php /var/www/html/artisan freescout:fetch-emails >> /dev/null 2>&1 

I host Freescout on godaddy shared hosting

**Comment by freescout-helpdesk** [comment]
Check why this line is not executed for you: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L111

How many mailboxes do you have? Make sure that all of them are able to connect via IMAP.

**Comment by diondkb** [comment]
I have 3 mailboxes. I can send on all, and if I go to system and 'fetch mail' or use the url, no problems. I will have a look at the url you sent me. Thank you

**Comment by diondkb** [comment]
> Check why this line is not executed for you: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L111
> 
> How many mailboxes do you have? Make sure that all of them are able to connect via IMAP.

I have checked if they can connect via IMAP and they can. I get the green message 'Connection Established'

**Comment by diondkb** [comment]
I also added a line to create a file in the FetchEmails.php file, and it does create a text file indicating that the mentioned function is run, but only when the 'Fetch Email' button is pressed or url used. When called from the cron job, no go.

**Comment by freescout-helpdesk** [comment]
If you want we can check - email at support@freescout.net.
Otherwise try to find some developer who can debug it for you.
