### ISSUE TITLE
LDAP fliter Security group

### ISSUE THREAD

**Issue by ollesson-allard** [freescout-helpdesk/freescout#2035]
Hi,

We have connection to LDAP, but how do i filter down this to only import users that has security group ie domain\sg_software_freecout?

Our filter looks like this today:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/65387364/172603053-b1f7fbb4-7cd6-4fca-a39b-7be0c139b127.png)

**Comment by freescout-helpdesk** [comment]
Google it.

**Comment by ollesson-allard** [comment]
thanks for a very nice answer .........
