### ISSUE TITLE
Move to Mailbox Without Access

### ISSUE THREAD

**Issue by sideshot** [freescout-helpdesk/freescout#2037]
https://github.com/freescout-helpdesk/freescout/blob/f5bf5afe14bcbb8be655c808db0a915b183f52dd/resources/views/conversations/ajax_html/move_conv.blade.php#L4-L8

I see you created the option to enter an email address to move to that mailbox.  But that is time-consuming for companies with lots of tickets.  We wanted the options there for all our users.  

The right solution would be adding a View Only option for a mailbox.  That way they could move tickets into the other mailbox and view tickets in that mailbox.  

For instance,  Order Processing might want to look at threads pertaining to a customer.  But Sales doesn't want those users to write to those users.  

The same thing goes for the Sales might get a question better suited for Order Ops.

```
        @foreach ($mailboxes as $mailbox)
            @if ($mailbox->id != $conversation->mailbox_id)
                <option value="{{ $mailbox->id }}">{{ $mailbox->name }} &nbsp;({{ $mailbox->email }})</option>
            @if (4 != $conversation->mailbox_id)
                <option value="4">Sales Department &nbsp;(sales@example.com)</option>
            @endif
            @if (3 != $conversation->mailbox_id)
                <option value="3">Order Administration &nbsp;(orders@example.com)</option>
            @endif
        @endforeach
```

**Comment by ilyakonovalenko** [comment]
Agreed. Entering email is a bad solution. There should be an option to allow user to see all mailboxes in the list, without view access.

**Comment by freescout-helpdesk** [comment]
> That way they could move tickets into the other mailbox and view tickets in that mailbox.

Unfortunately no plans to implement this.
