### ISSUE TITLE
Can't Connect mobile app to Freescout when using redirect in settings

### ISSUE THREAD

**Issue by ruess** [freescout-helpdesk/freescout#2039]
Hi there,

So that we could better utilize the knowledge-based module, I used the Custom Homepage module to redirect our core URL to one of our Knowledge Bases.

After doing so however, I can no longer utilize the Freescout Mobile App to connect to the site. The redirection throws if off.

Note that in the mobile-app screenshot below, I've tried both the core URL as well as trying to connect to the "Login Address" defined the Custom Homepage module. Neither works. When I try to connect the app to the core URL (no "/team"), it simply loads my Knowledge Base as if it's a web-page.

Thanks!
<img width="777" alt="freescout-custom-homepage" src="https://user-images.githubusercontent.com/797367/172901053-e83f231d-d2f2-46a7-be4d-f2e773ec7814.png">
![freescout-app](https://user-images.githubusercontent.com/797367/172901073-3bad0bdc-7d06-4be9-826e-89f79521d94c.png)

**Comment by freescout-helpdesk** [comment]
Currently if you redirect your homepage somewhere else it is be impossible to log in to FreeScout via mobile apps.

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version of the Android app.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by ruess** [comment]
Hey this is absolutely fantastic! Thanks for putting this in!
