### ISSUE TITLE
Notify about Unassigned mails for a specific user

### ISSUE THREAD

**Issue by bilel** [freescout-helpdesk/freescout#2040]
Hi :)

I'd like to count Unassigned mails / mailbox  for a specific user so I could prepare a structured notification like following :

mailbox1 : 12
mailbox2 : 5

I see that the `$mailbox->getMainFolders()` method _called in the dashboard index_, requires an authenticated user.

Unfortunately I can't call this method in my custom module' ..ServiceProvider.php
I get this error:
 Trying to get property 'id' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object

So is there any way we could set a specific user by ID in the \Eventy::addAction hook, to do something like following  : 
```

$tabalert=array();

//SET The user $user...

$mailboxes=$user->mailboxes();

foreach ($mailboxes as $mailbox){
      $main_folders = $mailbox->getMainFolders();
       foreach ($main_folders as $folder){
                    $active_count = $folder->getCount($main_folders);
                    if($folder->getTypeName() =="Unassigned" && (int)$active_count){
                        $tabalert[]['mailbox']=$mailbox->name;
                        $tabalert[]['nbmails']=$active_count;
                    }
      }
}
```

Thanks in advance!
Bilel

**Comment by freescout-helpdesk** [comment]
https://stackoverflow.com/a/66865028

**Comment by bilel** [comment]
I already managed to write a custom mysql query to get the job done..  Now I'll try  to test your suggested method :)
Thank you again
