### ISSUE TITLE
Bug: Incorrect Ordering of Knowledgebase Breadcrumbs

### ISSUE THREAD

**Issue by njsubedi** [freescout-helpdesk/freescout#2041]
In the knowledgebase front-end, the breadcrubs are mismanaged. Here's an example hierarchy of categories and articles.

[-] Mobile apps
---[-] App One
------[-] FAQ
---------[-] FAQ one about App One Android App
---------[-] FAQ two about App One Android App
----- [-] Help Articles
----- [-] Android App
----- [-] iOS App

On the page "FAQ one about App One Android App", the breadcrumbs are displayed in this order:

`Home > FAQ > App One > Mobile Apps`

The correct order should be:
`Home > Mobile Apps > App One > FAQ`

#### On the Dashboard

<img width="593" alt="image" src="https://user-images.githubusercontent.com/3161806/173072500-46ad50d2-c458-4606-97ef-682387ca1f7d.png">

#### On the Knowledgebase Page

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/3161806/173072613-a244b4ec-f7e3-4154-8897-1afcfd867c31.png">

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module v1.0.33
