### ISSUE TITLE
Queue:Work is not running, it stops automatically

### ISSUE THREAD

**Issue by ahmedkaludi** [freescout-helpdesk/freescout#2043]
I have been getting this problem constantly, see https://take.ms/3mgPz

Sometimes emails are not being sent, I get this issue 

`queue:work | Last run: ? Last successful run: ? Try to clear cache to force command to start.
` 

Please help me fix this!

**Comment by freescout-helpdesk** [comment]
What PHP version are you using? Are you using docker?

See also: 
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues
https://github.com/freescout-helpdesk/freescout/issues/2016

**Comment by ahmedkaludi** [comment]
@freescout-helpdesk 


 
Apache - PHP 7.4.30
config 1: https://take.ms/DdjQU
config 2: https://take.ms/wYFmg

**Comment by freescout-helpdesk** [comment]
Most likely the problem is in this:
![2022-06-17_11-23-20](https://user-images.githubusercontent.com/40499291/174258334-c0e5226a-dbf5-481e-81c6-ea8135f2de09.png)

**Comment by Arihantkankariya09** [comment]
@freescout-helpdesk if this is the issue, how can we fix this, any documentation or solution for this?

**Comment by freescout-helpdesk** [comment]
google.com

**Comment by supernation** [comment]
@freescout-helpdesk Our hosting company doesn't seem to have the ps (shell), 

Is there an alternative? or there's no option but to move the server?

**Comment by freescout-helpdesk** [comment]
PS (shell) is required for proper functioning.

**Comment by Arihantkankariya09** [comment]
No the issue is still not resolved as we have to manually run the cron job again and again.
