### ISSUE TITLE
Provide more details on failed jobs

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2044]
Dear Freescout Team,
We have dozens of automatic workflows set up inFreescout that are crucial to our daily work process.

Now, if we do a minor mistake in the way automatic workflows are set up, there will be an error when the job queue is processed. Sometimes even a Freescout update causes issues with workflows that ran just well before.

Unfortunately, both in the job queue and the failed job list there is no way to identify a particular workflow. It is just shown as:
`App\Jobs\TriggerAction`

Please add at least the workflow name in the "Failed Jobs" list.

**Comment by MarcoWel** [comment]
Thank you for recognizing this. Any info on the current progress?
We have so many failed jobs in the queue and just cannot find out which workflow is causing the issue.

**Comment by MarcoWel** [comment]
@freescout-helpdesk Any update on this issue? It is very important to us. We have our workflow queue full of errors daily and cannot narrow down the workflow causing it.

**Comment by freescout-helpdesk** [comment]
Can you attach a screenshot of what you see now in Failed jobs.

**Comment by freescout-helpdesk** [comment]
`View Details` button has been added for failed jobs. Maybe this way you can get the information you need.

**Comment by raramuridesign** [comment]
This is great - Thank you.
