### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#2045]
First, can a say a big thank you to everyone involved with the development of freescout for an excellent system. I have been using it for around 3 months with a number of add-on modules and still finding you things.

I have found the notes to be very helpful to add additional information about a ticket but it would be nice to have an option to show a note at the top of all messages, maybe a sticky note!  Maybe it's already possible and I have not worked it out if this is the case can someone please tell me how to do it.

Withing the developers all the best

John

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature for now. Feel free to submit a feature request: https://freescout.net/request-feature/
