### ISSUE TITLE
Tags don't get notified

### ISSUE THREAD

**Issue by AliekeStijf** [freescout-helpdesk/freescout#2048]
When I tag one of my employee's in a note in a customer ticket, they don't get notified (by email) unless they are either following the ticket or are assigned to the ticket. 

Is that supposed to be the case? 
Can we change something in settings so that you get notified when you get tagged even if youre not following or assigned?
if not, is this something that could be added?

**Comment by freescout-helpdesk** [comment]
Do you mean @mentioned? https://freescout.net/module/mentions/

**Comment by AliekeStijf** [comment]
That is exactly what I mean, thank you!

**Comment by freescout-helpdesk** [comment]
In order to receive notifications when mentioned, users need to configure their Notifications:

![2022-06-15_13-30-15](https://user-images.githubusercontent.com/40499291/173806617-fb2c7414-7143-4b12-9f98-723b195ee1fd.png)

**Comment by AliekeStijf** [comment]
Thank you!
