### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by flaxplax** [freescout-helpdesk/freescout#2051]
Trying to upload files or pictures larger than 1 MB give me "unexpected error"

logs:
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 30270056 bytes) {"userId":1,"email":"user@mail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 30270056 bytes) at /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:50)
```
I changed the Upload max size limit in the php.ini but did not seem to help.
Could not find anything in the faq or troubleshooting regarding this.
Where can I allow freescout to use the memory it needs for this to work?

**Comment by raramuridesign** [comment]
@flaxplax Try changing this setting in your php.ini for that specific project _(most hosts allow this to be customised per project)_

`memory_limit = 512M`

Increase as needed. Might also be a good idea to check what your current setting is.

M

**Comment by flaxplax** [comment]
My setting was set to 128M.
I bumped it to 512M as first try.  I no longer get the error in the logs but still get "unexpected error" when trying to import image or file.
Do you know if there other logs I could look at?

**Comment by raramuridesign** [comment]
Share a link to your info.php file, then one can comment correctly
https://www.php.net/manual/en/function.phpinfo.php

**Comment by flaxplax** [comment]
Here you have a paste of info.php: https://pastebin.mozilla.org/aRjtCB6s

**Comment by raramuridesign** [comment]
@flaxplax I cannot see anything wrong with the php.ini settings
I generally use the settings below, which work for our needs. There could of course be some other restriction on your server but difficult to day, try increase your max_execution_time, max_input_time & max_input_vars
as per below.
```
max_execution_time 90 
max_file_uploads 20
max_input_time 90
max_input_vars 10000
memory_limit 512M 
post_max_size 128M
upload_max_filesize 128M 

```

**Comment by flaxplax** [comment]
Not really sup up a restriction on the server. But not sure if it is a bug or something I did wrong.
I copied your setup and tried again, but did not work sadly.
Feels kinda strange that when I try to upload a file that is larger than 1M in a response, I get the error message instantly.
When trying to upload a file that is 900k I can see how it upload the file.
But the error message i get is the same ```client intended to send too large body: 5190302 bytes```
It is the web server logs that shows that message so not sure where it is related to.

**Comment by raramuridesign** [comment]
Try double this
`memory_limit 1024M`

**Comment by flaxplax** [comment]
I extended memory_limit to 32768M. I think that should be enough for a 2mb picture.
jokes aside. I did extend it to that and it still does not work.
Are you sure it is the php ini settings that are at fault?

**Comment by raramuridesign** [comment]
Very weird, perhaps @freescout-helpdesk support might be able to assist here.
Add your system setup and also the full error code and I am sure he will take a look.

**Comment by flaxplax** [comment]
Its a lxc container running ubuntu 20.04
php version: 7.4
freescout version: 1.8.18
Error code 
Web-server.log
```
2022/06/17 12:57:38 [error] 131452#131452: *11029 client intended to send too large body: 5190302 bytes, client: 10.84.53.29, server: freescout.example.com, request: "POST /conversation/upload HTTP/1.1", host: "freescout.example.com", referrer: "https://freescout.example.com/mailbox/3/new-ticket" 
```
This error code pops up when trying to attach an image of upload a file that exceeds 1mb.
Test file is 5mb

**Comment by freescout-helpdesk** [comment]
https://devanswers.co/nginx-error-client-intended-send-large-body/#:~:text=If%20you%20are%20trying%20to,client_max_body_size%20value%20is%20too%20low.&text=It%20may%20also%20be%20located,%2Fnginx%2Fconf%2Fnginx.

**Comment by flaxplax** [comment]
That worked, thanks!

**Comment by flaxplax** [comment]
@catbadger  I changed client_max_body_size, here is a link to examples https://docs.rackspace.com/docs/limit-file-upload-size-in-nginx

**Comment by datzent83** [comment]
I am running Freescount on Ubuntu by following the interactive install. How can I update the memory_limit?

```
sudo apt install wget
wget https://raw.githubusercontent.com/freescout-help-desk/freescout/dist/tools/install.sh
chmod u+x install.sh
sudo ./install.sh

```

**Comment by raramuridesign** [comment]
@datzent83 You should edit your php.ini file and up the limit, then restart apache.
M

**Comment by datzent83** [comment]
But how? When I type in the "ls" command the only thing that comes up is install.sh. How do I get to the php.ini file?

**Comment by raramuridesign** [comment]
@datzent83 You should try google it? There are literally thousands of resources which will guide you through that. 

https://search.brave.com/search?q=ubuntu+php.ini+location&source=desktop

**Comment by datzent83** [comment]
After I posed the comment I found it 
```
sudo find / -name php.ini
```

**Comment by datzent83** [comment]
I set the memory_limit = 1024M but I am still getting the same error message. I rebooted Ubuntu after I made the change.

**Comment by raramuridesign** [comment]
> I set the memory_limit = 1024M but I am still getting the same error message. I rebooted Ubuntu after I made the change.

I guess it depends on your server setup in terms of RAM. Have you checked the other php.ini values, to ensure they are also ok?

**Comment by datzent83** [comment]
Yes. I checked everything. The server has 4096mb of memory. I can only upload attachments that are 2MB and smaller.

**Comment by raramuridesign** [comment]
Set your limits like this, it will not gaurentee it will work - then restart server again. 
You might also want to read up on the cli commands to clear the cache, and rebuild the system, as this could also be playing a role in getting this to work.
M

```
max_execution_time 90 
max_file_uploads 20
max_input_time 90
max_input_vars 10000
memory_limit 512M 
post_max_size 128M
upload_max_filesize 128M 
```
