### ISSUE TITLE
Can't delete swimlanes in kanban module

### ISSUE THREAD

**Issue by andyknas** [freescout-helpdesk/freescout#2053]
If we go to delete a swimlane we get an error "please check internet connection" - have tried on multiple browsers with same result. Module is most recent version 1.0.7

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs

**Comment by andyknas** [comment]
We see…

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'board_id' in 'where clause' (SQL: delete from `kn_cards` where `board_id` = 2 and `swimlane_id` in (3)) ***@***.***","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'board_id' in 'where clause' (SQL: delete from `kn_cards` where `board_id` = 2 and `swimlane_id` in (3)) at /var/www/html/freescout/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'board_id' in 'where clause' at /var/www/html/freescout/freescout/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'board_id' in 'where clause' at /var/www/html/freescout/freescout/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Are you using the latest version of Kanban module?

**Comment by freescout-helpdesk** [comment]
Do you receive the same error on https://demo.freescout.net/?

**Comment by freescout-helpdesk** [comment]
Also can you send a screenshot of how you are deleting the slimline.

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in Kanban Module v1.0.8
