### ISSUE TITLE
Code Blocks In KnowledgeBase Articles disappearing on save.

### ISSUE THREAD

**Issue by TangibleMark** [freescout-helpdesk/freescout#2056]
Hi, I'm trying to create client documentation using Knowledge base articles, but when I put code snippets into an article and click save they disappear or the HTML actually renders. I haven't found anyone mentioning this behavior or having this problem when saving HTML from the summernote editor used to write articles. 

Any explanation about this behavior or help would be great! 
Thanks!

HTML in a code block
![Renders1](https://user-images.githubusercontent.com/107769311/174454497-d2e92f68-e9ff-4d71-a553-6cd57830ad50.png)
HTML has now been rendered after being Saved.
![Renders2](https://user-images.githubusercontent.com/107769311/174454498-2bd29401-6fca-4cb7-ac3d-8d6037b62a3a.png)
HTML also shows rendered on client side.
![image](https://user-images.githubusercontent.com/107769311/174454502-52743e5c-43fb-4307-8813-1c89946c3a02.png)

HTML in a code block
![image](https://user-images.githubusercontent.com/107769311/174454549-8ab33338-a875-4907-9692-acfdd1c194a9.png)
HTML disappears after being Saved.
![image](https://user-images.githubusercontent.com/107769311/174454561-d6864ee6-c357-446d-b0fb-e927b67c101d.png)
HTML disappeared on client side too.
![image](https://user-images.githubusercontent.com/107769311/174454652-eb4e7020-8262-4007-946e-096aa86b3cfa.png)

**Comment by freescout-helpdesk** [comment]
What tag are you using to insert the code?

![2022-06-19_11-35-57](https://user-images.githubusercontent.com/40499291/174472772-6ad40f25-2613-4c30-a167-016c71f2eeac.png)

![2022-06-19_11-35-47](https://user-images.githubusercontent.com/40499291/174472766-9e7f560c-618d-48b6-837a-8c2b2cf46aa0.png)

**Comment by TangibleMark** [comment]
I've tried this one:
![image](https://user-images.githubusercontent.com/107769311/174478756-f76f6872-a709-400f-a20c-15b5094aa6ef.png)
I've tried this one which 
![code button circled](https://user-images.githubusercontent.com/107769311/174479001-69e2674f-3b54-4fe1-a9b1-f8c88e51f63a.png)
Which is a summernote plugin that can be found here:
https://github.com/semplon/summernote-ext-codewrapper

And I've tried what you suggested above. The issue is not with any of these code blocks themselves, because If I just put html into the editor and save without putting it into any sort of code block it still disappears on save. If I click publish straight away without pressing save, it will display correctly on the client view but disappear in the page where you'd edit the article (presumably because it saves on publish.)

**Comment by freescout-helpdesk** [comment]
This is the editor issue. Same will happen if you add a code to a note for example and click "Edit".

![2022-06-19_15-42-29](https://user-images.githubusercontent.com/40499291/174481444-48b4d9f3-92d1-4f43-8251-7026faed086f.png)

**Comment by TangibleMark** [comment]
Oh, so is there a fix expected? Or somewhere you can point me to in the code that I might be able to fix it?

Thanks!

**Comment by freescout-helpdesk** [comment]
Fixed in the Knowledge Base v1.0.34.

**Comment by GabrielGallagher** [comment]
Will this also be fixed in the notes area?

**Comment by freescout-helpdesk** [comment]
Yes. In the the next release.

**Comment by GabrielGallagher** [comment]
We have some improvements to the KB module we're considering implementing, is there somewhere we can make a pull request for that? How can we contribute to paid modules?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
