### ISSUE TITLE
Error occured. Please check your internet connection and try again.

### ISSUE THREAD

**Issue by proserver1** [freescout-helpdesk/freescout#2057]
everytime we change status of a ticket to "pending" we get the error message:
"Error occured. Please check your internet connection and try again."
going backwards/forwards, click anything and the message disapears. status is correctly changed.

occurs with single messages or multiple selected.

same error most of the times occurs when sending a message/answer.

there is nothing wrong with our internet-connection, everthing else works as expected.

system: linux, firefox firefox and linux, current chrome

any hints?

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.

**Comment by proserver1** [comment]
error  production      2022-06-20 15:49:11
explode() expects parameter 2 to be string, array given {"userId":1,"email":"support@*******","exception":"[object] (ErrorException(code: 0): explode() expects parameter 2 to be string, array given at /var/www/html/Modules/Tags/Providers/TagsServiceProvider.php:227)

**Comment by freescout-helpdesk** [comment]
Fixed in Tags Module v1.0.19
