### ISSUE TITLE
Teams module

### ISSUE THREAD

**Issue by ThaStealth** [freescout-helpdesk/freescout#2058]
Hello,

The Teams module has a flaw for us which makes it not very usable, but maybe it can be fixed in the custom folders module.
We created tags for our departments (IT, Finance, Sales, etc) and for every department/tag a custom folder which listens to this tag.
By using the teams module we get a duplicate of folders since we have our custom folders and the folders created by the teams module. 

Also once a conversation is tagged a person within the team will continue with it and assign it to him/her. By using the teams folders the conversation is lost as soon as it is assigned to an individual user instead of the team.

Could you make an option to not create a folder for the team in the folderlist. We will then disable the folder and keep using the custom folder (+ enhance the workflow to assign the conversation to the team)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
In Team Module v1.0.1 it is possible now to hide Teams folders in mailboxes by adding the following line to the /.env file and [clearing the cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache):
```
TEAMS_HIDE_FOLDERS=1
```

**Comment by ThaStealth** [comment]
@freescout-helpdesk Thanks, but I now noticed another bug in the Workflow module;
If I add the action "Assign to User" and select one of the teams as the user it will allow me to save it, however the workflow is marked as incomplete and thus deactivated. Assigning to a regular user works.

**Comment by freescout-helpdesk** [comment]
> @freescout-helpdesk Thanks, but I now noticed a bug in the Workflow module; If I add the action "Assign to User" and select one of the teams as the user it will allow me to save it, however the workflow is marked as incomplete and thus deactivated. Assigning to a regular user works.

Fixed in the latest versions of Teams and Workflows modules.
