### ISSUE TITLE
Itegromat/Make: Error "Unknown type 'Text' of parameter 'subject'."

### ISSUE THREAD

**Issue by BRICOBREAD** [freescout-helpdesk/freescout#2059]
Hello,
I'm trying to integrate my freescout onprimesis with [make.com](http://make.com/). I'm getting the following error message:
Unknown type 'Text' of parameter 'subject'.
I talked to them and they asked me to get in touch with you. Follow their message.
I is investigated it thoroughly and found this issue with some parameter settings in Freescout. I would recommend you please contact the Freescout support team and show them the error.
Can you help me?

**Comment by freescout-helpdesk** [comment]
Could you please provide a screenshot of where you are getting this error.

**Comment by freescout-helpdesk** [comment]
> Follow the prints with the error presented in make.

What is the "prints"? Where can we find them?

**Comment by BRICOBREAD** [comment]
The previous prints refer to the field I need to know #mailboxid to correctly integrate with freescout. I put it in yellow collor.
Where can I find this information from my email within freescout?  I got these prints inside the make tool in the freescout integration area.

***@***.***

De: FreeScout ***@***.***>
Enviada em: terça-feira, 21 de junho de 2022 10:19
Para: freescout-helpdesk/freescout ***@***.***>
Cc: Wagner Vieira - Brico Bread ***@***.***>; Author ***@***.***>
Assunto: Re: [freescout-helpdesk/freescout] Itegromat/Make: Error "Unknown type 'Text' of parameter 'subject'." (Issue #2059)


Follow the prints with the error presented in make.

What is the "prints"? Where can we find them?

**Comment by freescout-helpdesk** [comment]
FreeScout integration looks like this in Make.com:
![2022-06-22_09-01-11](https://user-images.githubusercontent.com/40499291/174954823-855fa870-4c57-4b2c-98db-dfcb6ed4fc65.png)

Mailbox ID you can find in the URL of the mailbox in FreeScout, for example: https://demo.freescout.net/mailbox/settings/2, where 2 - is the mailbox ID.

`Unknown type 'Text' of parameter 'subject'.` - where are you receiving this error? Can you attach a screenshot?

**Comment by BRICOBREAD** [comment]
Thanks for the mailboxid information.
I'm getting this error from Unknown type 'Text' of parameter 'subject'. inside the make. When doing an automation, the system informs me that freescout does not accept the parameter.
Make support said that we should talk to you because there is an integration error, as per the previous message I sent you.
See, I tried to put various information inside the subject field, but in all cases the system returns the same error message.
***@***.***

De: FreeScout ***@***.***>
Enviada em: quarta-feira, 22 de junho de 2022 03:04
Para: freescout-helpdesk/freescout ***@***.***>
Cc: Wagner Vieira - Brico Bread ***@***.***>; Author ***@***.***>
Assunto: Re: [freescout-helpdesk/freescout] Itegromat/Make: Error "Unknown type 'Text' of parameter 'subject'." (Issue #2059)


FreeScout integration looks like this in Make.com:
[2022-06-22_09-01-11]<https://user-images.githubusercontent.com/40499291/174954823-855fa870-4c57-4b2c-98db-dfcb6ed4fc65.png>

Mailbox ID you can find in the URL of the mailbox in FreeScout, for example: https://demo.freescout.net/mailbox/settings/2, where 2 - is the mailbox ID.

Unknown type 'Text' of parameter 'subject'. - where are you receiving this error? Can you attach a screenshot?

**Comment by BRICOBREAD** [comment]
Hi
Any news?
I need to solve this integration.

**Comment by BRICOBREAD** [comment]
Hi
Any news?
I need to solve this integration.

**Comment by freescout-helpdesk** [comment]
We still have not received a screenshot from you. In your messages there is no attached images or videos.

**Comment by BRICOBREAD** [comment]
This is image from the last e-mail.

![image (17)](https://user-images.githubusercontent.com/97291842/176878741-03285a53-7ebc-4bbb-bdd3-5fe57b7771ed.png)

**Comment by freescout-helpdesk** [comment]
We've reproduced the issue in Make. We'll try to figure out what is wrong with Make support.

**Comment by freescout-helpdesk** [comment]
We are still waiting for the info from Make team. If Integromat is still available you can use our app there - it works well there.

**Comment by freescout-helpdesk** [comment]
We've fixed the issue in the Make backend and waiting for Make to release the updated app.

**Comment by freescout-helpdesk** [comment]
Make said they released the app. Please try again.

**Comment by BRICOBREAD** [comment]
Hi
Any news?
I need to solve this integration.

***@***.***

De: Wagner Vieira - Brico Bread
Enviada em: quarta-feira, 22 de junho de 2022 09:59
Para: freescout-helpdesk/freescout ***@***.***>; freescout-helpdesk/freescout ***@***.***>
Cc: Author ***@***.***>
Assunto: RES: [freescout-helpdesk/freescout] Itegromat/Make: Error "Unknown type 'Text' of parameter 'subject'." (Issue #2059)

Thanks for the mailboxid information.
I'm getting this error from Unknown type 'Text' of parameter 'subject'. inside the make. When doing an automation, the system informs me that freescout does not accept the parameter.
Make support said that we should talk to you because there is an integration error, as per the previous message I sent you.
See, I tried to put various information inside the subject field, but in all cases the system returns the same error message.
***@***.***

De: FreeScout ***@***.******@***.***>>
Enviada em: quarta-feira, 22 de junho de 2022 03:04
Para: freescout-helpdesk/freescout ***@***.******@***.***>>
Cc: Wagner Vieira - Brico Bread ***@***.******@***.***>>; Author ***@***.******@***.***>>
Assunto: Re: [freescout-helpdesk/freescout] Itegromat/Make: Error "Unknown type 'Text' of parameter 'subject'." (Issue #2059)


FreeScout integration looks like this in Make.com:
[2022-06-22_09-01-11]<https://user-images.githubusercontent.com/40499291/174954823-855fa870-4c57-4b2c-98db-dfcb6ed4fc65.png>

Mailbox ID you can find in the URL of the mailbox in FreeScout, for example: https://demo.freescout.net/mailbox/settings/2, where 2 - is the mailbox ID.

Unknown type 'Text' of parameter 'subject'. - where are you receiving this error? Can you attach a screenshot?

**Comment by freescout-helpdesk** [comment]
This has been fixed in July. Are you still receiving the error?
