### ISSUE TITLE
fetch emails from custom IMAP folders

### ISSUE THREAD

**Issue by Junker** [freescout-helpdesk/freescout#206]
Do you plan to make fetching emails from custom folders, not only 'INBOX'?

**Comment by freescout-helpdesk** [comment]
This can be implemented by adding a parameter to /config/app.php:
```
'imap_folders' => env('APP_IMAP_FOLDERS', ['INBOX']),
```

Feel free to submit a PR.

**Comment by quangbahoa** [comment]
@freescout-helpdesk  Is it possible set for each mailbox?

**Comment by Junker** [comment]
i think this setting should not be in config file, it should be in settings of each maibox, because mailboxes can have different folders.

**Comment by freescout-helpdesk** [comment]
> i think this setting should not be in config file, it should be in settings of each maibox, because mailboxes can have different folders.

Yes. Better to allow to specify IMAP folders in the mailbox fetching settings.
