### ISSUE TITLE
General setup troubleshooting for RHEL/CentOS

### ISSUE THREAD

**Issue by Nugget232** [freescout-helpdesk/freescout#2060]
I'm pretty new with Linux, mostly a windows power user.

My current environment is only centos machines, i wanted to setup a freescout on Centos instead of using the Ubuntu script and followed the install guide just changing some of the commands as I went for example:

yum install nginx php-fpm php php-mbstring mysql-server php-mysqli

MySQL is ready to go, I tested it already with a user named 'freescout' and am able to login an access the 'freescout' database object i created.

Created a conf file in /etc/nginx/conf.d/ using the freescout.conf as a template
[freescout.conf.txt](https://github.com/freescout-helpdesk/freescout/files/8952706/freescout.conf.txt)

Managed to get the site to start but is saying:
"Whoops, looks like something went wrong — check logs in /storage/logs"

So i go to storage/logs and there are two files:
>ls -l  /usr/share/nginx/html/freescout/storage/logs/
total 20
-rw-r--r--. 1 nginx nginx 18102 Jun 21 13:46 laravel-2022-06-21.log
-rw-r--r--. 1 nginx nginx     0 Jun 20 21:49 web-server.log

web-server.log is empty
laravel log has no error lines in it

Not sure how to fix this.   Does anyone have a scripted install for Centos/RHEL i could try?

**Comment by freescout-helpdesk** [comment]
Have you managed to find a solution?
