### ISSUE TITLE
Knowledgebase and PHP 8.1.2 throws "deprecated" at me

### ISSUE THREAD

**Issue by JesperLK-Witt** [freescout-helpdesk/freescout#2061]
Hi, when trying to create a new knowledgebase article I get this error thrown my way:

"htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated (View: /var/www/html/Modules/KnowledgeBase/Resources/views/article.blade.php) {"userId":1,"email":"mail@mail.dk","exception":"[object] (ErrorException(code: 0): htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated (View: /var/www/html/Modules/KnowledgeBase/Resources/views/article.blade.php) at /var/www/html/storage/framework/views/198b825de309b55c04b981872caa1448509ba147.php:79, ErrorException(code: 0): htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated at /var/www/html/storage/framework/views/198b825de309b55c04b981872caa1448509ba147.php:79)"

FreeScout 1.8.19.
PHP 8.1.2
Knowledge Base 1.0.34

When looking on the net it looks like a compability issue with PHP (obvious maybe ;-)).

Someone know a way arround besides downgrading PHP? :-)

Best wishes
Jesper

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module v1.0.35.
