### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#2062]
Hi, hope someone will be able to let me know what's going on with freescout.  I have not had any Notifications since 27 May in the Notification panel which is irritating and I don't know how to fix. From what I can see everything else looks to be ok
![Canute_(12) Mine - Canute Support - FreeScout � Mozilla Firefox_36](https://user-images.githubusercontent.com/27293201/175351333-6fd5007b-566a-4f45-ba49-c7735457519b.png)

Can anyone point me in the right direction on this, please?

John

**Comment by freescout-helpdesk** [comment]
Make sure that "Mute Notifications" option is disabled for the user and that background jobs are running.
