### ISSUE TITLE
Satisfaction Rating Logic

### ISSUE THREAD

**Issue by sideshot** [freescout-helpdesk/freescout#2064]
Can someone explain why the satisfaction score is calculated by Good% - Bad% = Score%. 

I expect it to be calculated using the [CSAT method](https://monkeylearn.com/blog/csat-calculation/#measure).  

In my example (on the [google sheet](https://docs.google.com/spreadsheets/d/17EzNtsB-caXybY_LlyzrZENB1IoOXhzBwHGueZZP-28/edit?usp=sharing)). You can see that calculating the current way will lead you to a 14% sat rating. But if you do it with the CSAT method, you will get a 65% rating. I'm using the Star Rating as such.

Great = 5
Okay = 3
Bad = 1

use Modules\Reports\Http\Controllers\ReportsController;

**Current**     function getReportSatisfaction($request)

```
<?php
            $satscore = ceil(($great*100/$ratings) - ($notgood*100/$ratings));

            $satscore_prev = ceil(($great_prev*100/$ratings_prev) - ($notgood_prev*100/$ratings_prev));
?>

```
Proposed Change

```
<?php
            // great = 5 stars  okay = 3 stars   bad = 1 star  divided by total points of count(ratings) * max 5 stars
            $satscore = ceil(((($great*5) + ($okay*3) + ($notgood*1)) / ($ratings*5)) * 100);

            $satscore_prev = ceil(((($great_prev*5) + ($okay_prev*3) + ($notgood_prev*1)) / ($ratings_prev*5)) * 100);
?>

```

**Comment by freescout-helpdesk** [comment]
Feel free to add an additional way of calculating scores as a feature request: https://freescout.net/request-feature/
