### ISSUE TITLE
Cannot run web-installer and php artisan key:generate gives permission denied error

### ISSUE THREAD

**Issue by ignutanz** [freescout-helpdesk/freescout#2066]
I downloaded `freescout-dist` to my `/var/www/html` folder of apache2 and provided `www-data:www-data` permissions recursively to the folder and provided **775** permission to the storage folder specially.
When I try to run the web-installer using `http://localhost/freescout-dist` I get the directory listing instead of the web-installer page.
I have created the **.env** file from .env.example but with no paramaters filled. How should I fill my DATABASE parameter.
I tried `php artisan key:generate ` but it gave the following error:

```
In StreamHandler.php line 110:
                                                                                                              
  The stream or file "/var/www/html/freescout-dist/storage/logs/laravel-2022-06-27.log" could not be opened   
  in append mode: Failed to open stream: Permission denied 
```
When I tried with `sudo php artisan key:generate` I get the error:

```
In imap.php line 105:
                               
  Undefined constant "FT_UID"  
```
  I have installed the php-imap module and enabled it and restarted php7.4 fpm and apache.
But the error prevails                     . Please help in fixing the issue

**Comment by freescout-helpdesk** [comment]
> When I try to run the web-installer using http://localhost/freescout-dist I get the directory listing instead of the web-installer page.

It means in your web server FreeScout is not configured properly.
