### ISSUE TITLE
connect to mariadb

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2068]
Hey,
I'm running a docker version of freescout. and my mariadb is at a local ip. but it won't connect when i put the ip of the db in the DB_HOST

This is the error i'm getting:
2022-06-28.01:57:26 [44m[WARN][49m ** [freescout] MySQL/MariaDB Server '192.168.200.99' is not accessible, retrying.. (15 seconds so far)

**Comment by Mathie01** [comment]
Same problem with the docker image ...

**Comment by netspear** [comment]
Hey, I fixed my problem. 
re-built the freescout docker and it connected, and working great so far.
@Mathie01 would you be able to send any info on how the DB and freescout are set up? maybe I can help

**Comment by netspear** [comment]
Actually forget it. 
I restarted my server later in the day, and my entire freescout database erased everything inside the freescout db.
Starting from scratch on a virtual Ubuntu server.
They have a quick command that installs everything for you in one shot on a clean copy of linux

**Comment by freescout-helpdesk** [comment]
So is your issue resolved?
