### ISSUE TITLE
Twitter Module Brakes Freescout

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2069]
Hey,
Once I activate the twitter module, Freescout breaks.
Only shows 

This page isn’t working
support.example.com is currently unable to handle this request.
HTTP ERROR 500

I can access the tools.php page, but it doesn't let me do anything unless I have PHP 7.X

**Comment by freescout-helpdesk** [comment]
Have you checked logs?

**Comment by netspear** [comment]
Yes, Unfortunately, I forgot to save it before I redid the installation.

**Comment by netspear** [comment]
I'm having another issue on the Linux Freescout I have setup.

I created a new ticket and send 2 emails, unfortunately, I misspelled the email address and it bounced twice. but when I tried to reopen the ticket it gave me the following massage:

Whoops, looks like something went wrong — check logs in /storage/logs 

I downloaded the logs but I'm not sure which log to look at. would you be able to help me?

**Comment by netspear** [comment]
> Yes, Unfortunately, I forgot to save it before I redid the installation.

I deleted the old server and rebuilt it from scratch. but I did not try installing the Twitter module again. I'll try to clone my current instance and install the Twitter module again there to see what happens.

**Comment by netspear** [comment]
I tried that. Didn't work.
I rebuilt the server from scratch. but didn't install the Twitter plugin
