### ISSUE TITLE
Splitting a message from one conversation into a new conversation

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#2070]
Often, we get clients email us something new in a reply on an old, completely unrelated email and we want to create a new conversation from that message basically.

I figured this option here was what this was for...

![Screenshot_3](https://user-images.githubusercontent.com/849735/176418366-0e1afcf9-2304-48c7-82c0-14a0ae63f9e5.jpg)

But it doesn't seem to work quite right.

Firstly, is this the kind of thing what this option is intended for?

If so, when you select this, it creates a new conversation from myself which I then have to send back to ourselves. It should basically duplicate that message as from the same customer putting in a state where it is waiting on us to reply.

And also, on the old conversation that you have created a new conversation from that last message, it does not add a note to state a new conversation has been created from this message (notes like you get when you add a tag or change an assignee for example).

**Comment by freescout-helpdesk** [comment]
It works as designed.

> Often, we get clients email us something new in a reply on an old, completely unrelated email and we want to create a new conversation from that message basically.

There is a feature request here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/334244
