### ISSUE TITLE
IMAP fetching errors

### ISSUE THREAD

**Issue by bharms1981** [freescout-helpdesk/freescout#2071]
I apologize if this seems easy but I noticed a few hours ago a couple of our accounts are generating errors when trying to fetch via IMAP. We have multiple email accounts setup and all but two are working. Settings are all the same. I can send a test email with no issues (SMTP) but fetching comes back with "imap_open(): couldn't open stream {outlook.office365.com:993/imap/ssl} trying plain auth after auth failed... cannot connect to IMAP server..." Other 0365 accounts are working fine and sending works ok for these two accounts so I don't think its a password issue. Is there something I'm missing? I've rebooted the server with no resolve. The thing that's throwing me is multiple other accounts with same settings are working fine.

**Comment by bharms1981** [comment]
hmmm... I do not see the "Microsoft Exchange - (Connect)" link under password after I click save settings ?

**Comment by freescout-helpdesk** [comment]
Update FreeScout to the latest version.
