### ISSUE TITLE
Module Send Later

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#2075]
Hi,

In Send later module, email are snoozed but users can see the snoozed email before the email is sent.
Could we hide the snoozed content in the thread for users until the email is sent ?

**Comment by freescout-helpdesk** [comment]
We'll try to fix it.

**Comment by freescout-helpdesk** [comment]
Which modules about are you talking? Could you please send screenshots.

**Comment by davask** [comment]
This one https://freescout.net/module/send-later/

**Comment by freescout-helpdesk** [comment]
> ...but users can see the snoozed email before the email is sent.

Can you please attach screenshot of this?

**Comment by davask** [comment]
In this screenshot the top message has been made after I snooze the 1st email.

![Screenshot_20220703_102132_net freescout app](https://user-images.githubusercontent.com/482210/177031479-7dcac569-ef3f-4e03-8f01-06ada5d0ef70.jpg)

**Comment by freescout-helpdesk** [comment]
It works as designed. This notice indicates that the message is scheduled to send later:

![2022-07-03_11-28-14](https://user-images.githubusercontent.com/40499291/177031697-8481f379-c9f7-4317-9901-4e468e6f8633.png)

**Comment by davask** [comment]
Yes but user are not suppose to see my snooze answer before the defined date and they see it if the come on the freescout app

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by davask** [comment]
This is more à bug than a feature but I did submit it
