### ISSUE TITLE
Make Conversation Number = Conversation ID

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#2076]
Hi,

for 1 ticket I have different IDs which make confusion between clients and I.
As an example.
My Hastag ticket number is `#2043`, the url as admin is `/conversation/2064` (2064) and user link to ticket is  https://ticket.marasit.com/help/2936061329/ticket/2064 (2064)

Could the hastag ID match the url ID ?

**Comment by RienNeVaPlus** [comment]
This has caused a lot of confusion in my team as well. I never understood the reasoning behind it, maybe @freescout-helpdesk could elaborate? Usually he has good reasons for these kind of decisions.

It's propably possible to create a module that provides a redirect for the ticket ID to the actually conversation ID (ie. `/ticket/2043` >> `/conversation/2064`), but that feels a little hacky and I'd much rather discuss chaning it entirely for the next mayor.

**Comment by freescout-helpdesk** [comment]
When ID in the URL and conversation number is the same people consider it a potential security threat. And some want to be able to adjust conversation number: 

![2022-07-03_15-26-25](https://user-images.githubusercontent.com/40499291/177039666-1d2f8cd2-75db-4685-be20-4d869160cc0c.png)

So by default conversation number is different from conversation ID. But sometimes it indeed may be confusing. So in Manage > Settings > General can be added a checkbox making conversation number to be equal to conversation ID.

**Comment by oledmansfeld** [comment]
@freescout-helpdesk Using your great API - This is very confusing!! Either we have to be able to get the conversation by number or id or be able to set our own number when creating the conversations. Please help me understand this logic as its causing me and my team a lot of confusion.
Thanks for a otherwise great product ;)

**Comment by oledmansfeld** [comment]
Actually we found that using list and query on ticket number solved this for us.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

![2022-08-01_18-04-49](https://user-images.githubusercontent.com/40499291/182180197-4d632d89-6929-4952-96e4-bd35cec4394b.png)

**Comment by MarcoWel** [comment]
Sorry, but this was a shitty way of implementing it. It is a punch in the face for existing Freescout users!

The new option is activated by default. This means ALL ticket ids change (e.g. from #10234 to #9323)!! We used the ticket ids to cross reference tickets in other systems, and the ticket id is mentioned in the subject line of each email. How can you just change the id?

The proper way would be to keep the old URLs and ticket ids identical, and have a separate URL scheme for accessing tickets by id.

Example:
```
Ticket ID: #11500
Internal Ticket ID: 10631

Old Ticket URL: https://myfreescoutinstance.com/conversation/10631
New Ticket URL: https://myfreescoutinstance.com/ticket/11500

```

**Comment by freescout-helpdesk** [comment]
See instructions here https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.22 and https://freescout.net/news/freescout-release-1-8-22-notes/

**Comment by MarcoWel** [comment]
> See instructions here https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.22 and https://freescout.net/news/freescout-release-1-8-22-notes/

It is very clear how it works, but it is a shitty implementation, sorry!
Basically no existing Freescout user can use it because it would change ALL previous ticket # references.

**Comment by freescout-helpdesk** [comment]
> Basically no existing Freescout user can use it because it would change ALL previous ticket # references.

As described in links above those who want to return to previous conversation numbers can do so in Manage > Settings.

**Comment by MarcoWel** [comment]
This is what we have done immediately after updating to 1.8.22.
At the same time, it would be very helpful to us having the possibility to view a ticket by the ticket # number.

Maybe you can implement it as a module instead, opened feature request:
[URL endpoint to open ticket by ticket number](https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/recent)

**Comment by MarcoWel** [comment]
Edited reply above to make it more clear.
https://github.com/freescout-helpdesk/freescout/issues/2076#issuecomment-1244441401
