### ISSUE TITLE
Feature request: Internal and Public Knowledge Base Articles

### ISSUE THREAD

**Issue by dumiller** [freescout-helpdesk/freescout#2078]
The Knowledge base should have the ability to have Internal Articles and Public Articles.

Internal Articles are only viewable by Support Agents and Public Articles are available for anyone to view.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by muhzak** [comment]
@dumiller  -- did you post this? I don't see it on the requested features.

**Comment by dumiller** [comment]
It was closes as the moduel already has the feature. I will post the request again explaining what I am asking for in more detail as I think they don’t understand my request.
