### ISSUE TITLE
Snooze Module not working.

### ISSUE THREAD

**Issue by TXKDennis** [freescout-helpdesk/freescout#2079]
After purchasing, installing, and activating the Snooze module, I can get the snooze requestor but nothing on it responds except the top right X.  I can change the snooze for number and units but cannot click the check, date and time, snooze button or the Cancel link.
I have checked the permissions, uninstalling and reinstalling, installing on a test site, Chrome, Edge, Firefox, and Opera browsers.
All with the same result.
I don't see any entries in the log files related to this event.
Is anyone else using the Snooze Module and seen this issue before?
Thanks

![Screenshot 2022-07-06 122423](https://user-images.githubusercontent.com/108826510/177608380-0e11c80f-cac2-4a9f-ac6c-9cc6167126e7.png)

**Comment by freescout-helpdesk** [comment]
If you can provide access to your server and FreeScout admin please email at support@freescout.net

**Comment by TXKDennis** [comment]
Thank you so much!
I have emailed the requested information.

**Comment by freescout-helpdesk** [comment]
We have not received it to [support@freescout.net](mailto:support@freescout.net)

**Comment by TXKDennis** [comment]
Sorry, sent to wrong address.  It is on it's way now.
