### ISSUE TITLE
bcc addresses exposed in email

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#208]
I don't think the current `Bcc` feature is working properly.
Main purpose for a `bcc` is a `blind carbon-copy`, thus all addresses wrote in `bcc` should not be disclosed to the recipient.

I've sent an email by setting a `bcc` address and this address is still shown in the mail header. I don't think this is working as expected.

If this address is exposes, it is not blind anymore.

**Comment by guestisp** [comment]
![image](https://user-images.githubusercontent.com/3944655/50293239-68f2bf00-0473-11e9-89a3-e88b3a3ee533.png)

**Comment by guestisp** [comment]
`Ccn/Bcc` are exposed in the received email.

**Comment by freescout-helpdesk** [comment]
Can not reproduce.

> I've sent an email by setting a bcc address 

How did you send it?

**Comment by guestisp** [comment]
Sent by simple writing an address in Bcc field in freescout

**Comment by guestisp** [comment]
This is not fixed...

**Comment by freescout-helpdesk** [comment]
Issue could not be reproduce. Try to fix if you can reproduce it.

**Comment by guestisp** [comment]
Just create a new conversation and add a Bcc to it

**Comment by guestisp** [comment]
(create from the web interface, obviously)

**Comment by freescout-helpdesk** [comment]
Which email service provider are you using?

**Comment by guestisp** [comment]
Local mail with php, we are not using a remote service (we will use Amazon, i don't remember if related issue was fixed)

**Comment by guestisp** [comment]
Start a new conversation, set as `To` a customer address, then set as `Bcc` your address.
Thunderbird show your address as `Bcc` and that address is also shown in mail header.

Do the same directly from Thundebird, the received email doesn't show any `Bcc`

**Comment by guestisp** [comment]
```
Return-path: <orders@x.com>
Envelope-to: a@b.com
Delivery-date: Thu, 10 Jan 2019 10:54:26 +0100
Received: from mx1.x.com ([1.2.3.201])
	by mail02.x.com with esmtp (Exim 4.72)
	(envelope-from <orders@x.com>)
	id 1ghX2f-0006eD-VQ
	for a@b.com; Thu, 10 Jan 2019 10:54:26 +0100
Received: from x.com ([1.2.3.25] helo=x.com)
	by mx1.x.com with esmtp (Exim 4.80)
	(envelope-from <orders@x.com>)
	id 1ghX2a-0000Mk-59
	for a@b.com; Thu, 10 Jan 2019 10:54:20 +0100
Received: from www-data (helo=[127.0.0.1])
	by x.com with local-smtp (Exim 4.89)
	(envelope-from <orders@x.com>)
	id 1ghX2H-000328-TC
	for a@b.com; Thu, 10 Jan 2019 10:54:01 +0100
Message-ID: <reply-261-b1a59b315fc9a3002ce38bbe070ec3f5@x.com>
Date: Thu, 10 Jan 2019 10:54:01 +0100
Subject: Test BCC
From: "Support | x.com" <orders@x.com>
To: "" <y@x.it>
Bcc: a@b.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_1547114041_d6b245e13651ae9ac9606485d73709e1_=_"
Received-SPF: pass
X-SPF-Guess: pass
X-DKIM-Status: none [(x.com) - 1.2.3.25 - x.com]
X-DKIM-ADSP: unknown
```

As you can see, there is a `Bcc` header.

Additionally, i've seen right now that `To` address is not filled properly. Will fix

**Comment by freescout-helpdesk** [comment]
It looks like your Exim configuration needs some tuning: https://github.com/Exim/exim/wiki/Q5004

**Comment by guestisp** [comment]
> It looks like your Exim configuration needs some tuning: https://github.com/Exim/exim/wiki/Q5004

maybe, this is a test server.
based on official docs:

`In the second case, recipients specified in the To: and Cc: lines each are sent a copy of the message with the Bcc: line removed as above, but the recipients on the* Bcc: line get a separate copy of the message containing a Bcc: line. (When there are multiple recipient addresses in the Bcc: field, some implementations actually send a separate copy of the message to each recipient with a Bcc: containing only the address of that particular recipient.)`

So, if I put me as "To" and a different address as "Bcc", my mailbox should not see the Bcc address but the address receving the email as Bcc, should see itself in Bcc header (this would be good)
Let me try.....

**Comment by guestisp** [comment]
> So, if I put me as "To" and a different address as "Bcc", my mailbox should not see the Bcc address but the address receving the email as Bcc, should see itself in Bcc header (this would be good)

It works like this. `Bcc` header is shown only to recipient in `Bcc` list. 
Other recipients doesn't see the header.

In example:

mail sent to user1 plus `Bcc` to user2 and user3

user1 doesn't see any `Bcc`
user2 sees a `Bcc` with only itself (no reference to user3)
user3 sees a `Bcc` with only itself (no reference to user2)

So, is not a bug. Closing this.
