### ISSUE TITLE
Custom Fields Module and API

### ISSUE THREAD

**Issue by oledmansfeld** [freescout-helpdesk/freescout#2082]
@freescout-helpdesk  I am considering buying the custom fields module - but we need to be able to access the custom fields by the API module.
Is that possible?

KR Ole

**Comment by freescout-helpdesk** [comment]
For conversations custom fields are returned in customFields. Also see https://api-docs.freescout.net

**Comment by oledmansfeld** [comment]
@freescout-helpdesk thanks a bunch!!

**Comment by satsangswami** [comment]
We want to be able to List Conversations based on Custom Fields values.

1. Is there an API for this?
2. What is the work around?
