### ISSUE TITLE
Mentions Module hide users from selection

### ISSUE THREAD

**Issue by lieblinger** [freescout-helpdesk/freescout#2083]
I'm using your Mentions Module and we're very happy with it.

There's just one suggestion for improvement: In the mailbox settings you're able to select user's which should be hidden and not selectable on a mailbox. We're using this to hide the administration account on all our mailboxes. 

It would be amazing if this selection also applies on the Mentions Module and hide these user's from the selection.

**Comment by freescout-helpdesk** [comment]
Fixed in Mentions Module v1.0.3
