### ISSUE TITLE
imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}. Retrying PLAIN authentication after AUTHENTICATE failed.; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: AUTHENTICATE failed.

### ISSUE THREAD

**Issue by BRICOBREAD** [freescout-helpdesk/freescout#2085]
We are having problems receiving email, we are making the settings according to the attached image, but the error reported in the title appears or "Error has occurred. Please check your internet connection and try again."
![image (18)](https://user-images.githubusercontent.com/97291842/177875580-c7930b0c-ec5d-4365-915d-acaf946e5508.png)
![image (19)](https://user-images.githubusercontent.com/97291842/177875587-5bb7be7f-3d70-407b-8575-a5be6304b32e.png)

**Comment by freescout-helpdesk** [comment]
Connect FreeScout to Microsoft 365 Exchange via OAuth
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth

**Comment by websafe** [comment]
Hello @freescout-helpdesk

short question, why am I able to connect to a shared M365 mailbox via PHP/IMAP + ApplicationPassword with osTicket, and when I try to use the exactly same settings in FreeScout it isn't working?

I'm trying to get it working by doing as described here https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth but I'm not able to get it working, what I've described in #2168 and #2170
