### ISSUE TITLE
Trouble with Translation module

### ISSUE THREAD

**Issue by ASTIN-UA** [freescout-helpdesk/freescout#2087]
Hi. I start translating modules and main app to Ukrainian. I have translate some modules and main app, but than I install update to FreeScout 1.8.20. And now I have a problem:

I backed up all files translation (from modules folders and from main lang folder).
After update all my lang files are deleted. 
I've restore all of them to correct places and start Import Translations.
So, what we have:
1) All modules on Ukrainian, Jira module as example:
![image](https://user-images.githubusercontent.com/17588757/178150511-0d28fa3b-265c-40d9-b266-7e171c200cab.png)

 but on translation modules all is Empty
![image](https://user-images.githubusercontent.com/17588757/178150450-ebcffde3-6518-4b1e-abab-3b5b156bf217.png)

Except main App.
 
2)  I have no any instrument to edit translations via web. 
3) How to translate Date? Month, etc.
4) How to translate Translation module? )))

**Comment by freescout-helpdesk** [comment]
1. Click "Import translations" button.

> 2. I have no any instrument to edit translations via web.

What does it mean?

3. Dates will be translated automatically.

> 4. How to translate Translation module?

It's not supposed to be translated.
