### ISSUE TITLE
FreeScout SAML SSO Module with Azure Failed

### ISSUE THREAD

**Issue by Sx3** [freescout-helpdesk/freescout#2088]
We have setup FreeScout on a Ubuntu 20.04 by using Ubuntu script.
when trying to configure SAML with Azure using
https://freescout.net/module/saml/

with are getting the following error
Error occurred during SAML SSO authentication: Invalid issuer in the Assertion/Response (expected 'https://MYDOMAIN.com', got 'https://sts.windows.net/741e1a5c-f4ec-4971-905e-41de19ba3dd5/')

we compared the SSL certificate on Azure and Free Scout too
also we used https://samltoolkit.azurewebsites.net/ and passed the test too.
was anyone successful with SAML Login with Azure?

**Comment by freescout-helpdesk** [comment]
Some people managed to integrate SAML Module with Azure. 
We can't help here - you may need to find a solution by yourself. We've added this and other Azure related threads to https://freescout.net/module/saml/, so maybe someone will help.
