### ISSUE TITLE
Can't delete a Mailbox

### ISSUE THREAD

**Issue by bilel** [freescout-helpdesk/freescout#2089]
Hi,
On multiple unsuccessful attempts, I tried to delete a mailbox (With a big amount of messages) and still I get always the same message : 

**Error occured. Please check your internet connection and try again.**

Other mailboxes were succefully deleted and they share the same imap/smtp settings..

When I checked the log I found this error:

`SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: delete from `threads` where `conversation_id` in` (   **BIG LIST OF conversations IDs**)

I think this query (or any related parallel query) should be optimized or there is somewhere a kind of unclosed transaction..

Thank you

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
