### ISSUE TITLE
Number in email header change to customer 

### ISSUE THREAD

**Issue by Nick-Vdv** [freescout-helpdesk/freescout#2090]
Hello 

 whe have a voip system that send us an email whit de voice log and en the header only the number

now is the a way that i can trigger that when the number is reconiced by customer that it replace it to its name
because al our clients aren know in freescout 

![Schermafbeelding 2022-07-11 205211](https://user-images.githubusercontent.com/105974738/178337210-fbed4477-c22f-4a60-91ef-ffcc3a9df7f4.jpg)µ

greetings nick

**Comment by freescout-helpdesk** [comment]
Yes. Via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
