### ISSUE TITLE
Last Name shows as "Empty"

### ISSUE THREAD

**Issue by bekre10** [freescout-helpdesk/freescout#2091]
If a customer sends a ticket and there is no last name, it simply shows the word "Empty".
Means the customer shows as "John Empty".
I would rather like to leave that field blank or if no other option, just use a dot.
Where can I modify this?

**Comment by freescout-helpdesk** [comment]
We have not seen such behavior with conversations received by email.
How do your customers send tickets?

**Comment by bekre10** [comment]
They send to our helpdesk email address (O365). FreeScout is connected to the O365 mailbox via API. Client uses O365 as well and sends via MS Outlook.
See screenshots attached.

![701E1150-46CF-4A6C-AEB8-2088D743785F](https://user-images.githubusercontent.com/108969634/180641425-a9d675b4-c3ce-460f-82f2-452ee214e4f7.jpeg)
![D6996EEE-62EB-4841-AE16-6D81EFAD6F6B](https://user-images.githubusercontent.com/108969634/180641427-1d3e4471-27c7-4ab6-aa1b-0f31fd21d138.jpeg)

**Comment by gbissland** [comment]
FYI  we are using Google Workspace and we get these empty last name contacts created as well. Received by email.


![freescout-empty](https://user-images.githubusercontent.com/5170216/180641718-b4844fff-b253-43ad-83ea-c4ab778d017b.jpg)

**Comment by freescout-helpdesk** [comment]
Can you attach source code of one of such emails.

**Comment by bekre10** [comment]
Happy to attach the source code but how do I get it in FreeScout?

**Comment by freescout-helpdesk** [comment]
Headers tab from:

![2022-07-24_13-21-46](https://user-images.githubusercontent.com/40499291/180642796-b40b18e6-7872-49f6-9e65-62fae47d5417.png)

**Comment by bekre10** [comment]
I had to remove information due to privacy. If you want unmodified source code please let me know how to send you a private message.

MIME-Version: 1.0
Received: from SI2PR02MB5001.apcprd02.prod.outlook.com (2603:1096:4:15e::5) by
 SI2PR02MB5931.apcprd02.prod.outlook.com with HTTPS; Tue, 12 Jul 2022 09:09:58
 +0000
ARC-Seal: i=2; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=pass;
 b=D4ELN4rLmYaZ08KqvPd08rvkW4xXnViUrGA45lqCzqmQlUNIT4nhyMqb7skhTx9x7s5ccPp31mO1YN+fHQfjJDA3rfrCyQkVC7xtqoXZc4+wyjdGjvEfpglmlREFqHtZkIj2exFOohBlpxxQPZ9+XOzBKgzjyT0dvYiKzt49h/yGLHT4xnZzI43Ls0Glyq+hdZjwxtZpNQsOB6jiXr8IaoZMWQpOP9sqRI1b5P2WlXS+6kmSZtAO6CztF/nCsi97CvD50f+6fOriNevnXeTaKFuR2DINIA7F/7oBb9AV+06l31JIa0k/+nWyG3MVqNERY9apk2rDxwaS1zOGq/VD/g==
ARC-Message-Signature: i=2; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=9AGGfX71Ebsz2gYImaDg/WGRUITrgllEX62kkBGiZPM=;
 b=CZYzn6hA6nVEhcaV6IEneJ2w4lzh7iFtldEAaa2wpIaNOg4pcW3rjjjVYHbwaNBrVbCu3GUwfboW1vlZTPWdLYpA0RMbmONTb/6zfbIX2BGC1H3FlR7JbsgCBhIABivZOoBj9d3F/JuFAVZkJdaTB7YG5nwdgmqO2bgkgH1Z8iBdyuMrnSaFLzcTIUPbARgAjor8WWBYmZQBhWJoTiUE7lvmX80+eHmkZiYJcNs1ymbB+SPa/BbA/2mTQMWCcn/8jqnbRKI9qT4MYTuG8M5gpNJ2a7uaZGZVZaUyvVy1Fa5455KXMKBbTu9CIhTJkbQlTkgIWAlB5V/hNjDNgww6+A==
ARC-Authentication-Results: i=2; mx.microsoft.com 1; spf=pass (sender ip is
 (removed)) smtp.rcpttodomain=(removed) smtp.mailfrom=(removed);
 dmarc=bestguesspass action=none header.from=(removed); dkim=pass (signature
 was verified) header.d=(removed).onmicrosoft.com; arc=pass (0 oda=1 ltdi=1
 spf=[1,1,smtp.mailfrom=(removed)] dkim=[1,1,header.d=(removed)]
 dmarc=[1,1,header.from=(removed)])
Received: from PS2PR03CA0013.apcprd03.prod.outlook.com (2603:1096:300:5b::25)
 by SI2PR02MB5001.apcprd02.prod.outlook.com (2603:1096:4:15e::5) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5417.26; Tue, 12 Jul
 2022 09:09:55 +0000
Received: from PSAAPC01FT051.eop-APC01.prod.protection.outlook.com
 (2603:1096:300:5b:cafe::6d) by PS2PR03CA0013.outlook.office365.com
 (2603:1096:300:5b::25) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5438.6 via Frontend
 Transport; Tue, 12 Jul 2022 09:09:54 +0000
Authentication-Results: spf=pass (sender IP is (removed))
 smtp.mailfrom=(removed); dkim=pass (signature was verified)
 header.d=(removed).onmicrosoft.com;dmarc=bestguesspass action=none
 header.from=(removed);compauth=pass reason=109
Received-SPF: Pass (protection.outlook.com: domain of (removed) designates
 40.107.255.131 as permitted sender) receiver=protection.outlook.com;
 client-ip=40.107.255.131; helo=APC01-PSA-obe.outbound.protection.outlook.com;
 pr=C
Received: from APC01-PSA-obe.outbound.protection.outlook.com (40.107.255.131)
 by PSAAPC01FT051.mail.protection.outlook.com (10.13.38.135) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.5417.15 via Frontend Transport; Tue, 12 Jul 2022 09:09:53 +0000
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=AaRHH/XfrEHCKgWxG54KAll2GuWF/j4FDsW47tJ7gGElxXTs+e7ofS7dXKMMX9CFbBjAbYod0ig+uThvoTtjXZYUv5eL1Oqyn8VM4gog5cwPb9UsnfiXaagLXTCX2HPvOOcIWvROGUP4lUOMDu8mYVmkn9ADtjobS+1kBQSd6P4u5OAeWg+My448KSv5JUTcUTkrUrqsvdU9PlpyfsXu2nJ4f9zznTuhE8/i5DkOw1i3qly7BtJdQ3Et0BR1DUnOq8xpI4yyOvZ+HyuAZk42ywXBIXzoqtjAmlC2TIv8cTix27aZyV6vHAfq1ibz8oyCdsFSSuy4gGr7AmCqVoa8/A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=9AGGfX71Ebsz2gYImaDg/WGRUITrgllEX62kkBGiZPM=;
 b=luD7tL5966U4bX7DPPcaXi2sjVypg9WCHUeKT/QfQkc73cI+AEIse9RNu/jPgpc2WHu/qT4k7UaAxriOgGypqsZdbzr/+39gOURVC7JI8ERFhS4iMbWeXLBD+Z/rIk+DsSXbOtp9fltDV89cyiJV0inwRBCwsBeqD1u7crrMoaOYRW9O9ple+kv4kOdkyiSMI/+YSn1AAXK8cvYkWQ5yNRW0Kbr+u+mHbh2o0CIP0jU5Y6jlBRuuEf4plQ/tZmO3jQaTVBNdDyaU/Y7jXLL70IhSaf/6X4tJ0QfDMZhbYr8NzOgIZp12NoLblgZhAxtsGwPg6lY3WT5rYSPLlTf1Xg==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
 smtp.mailfrom=(removed); dmarc=pass action=none header.from=(removed);
 dkim=pass header.d=(removed); arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=(removed).onmicrosoft.com; s=selector2-(removed)-onmicrosoft-com;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=9AGGfX71Ebsz2gYImaDg/WGRUITrgllEX62kkBGiZPM=;
 b=RQOa7AetRznvyaUfH8dRgu3IiBbk1UH1fctSf/51iQe9r6EjaTb5K0sqwZYx4/69S/faZMDYumNaLt5mf/PHe6aX7gklcVvC4w2d9dk8h5siz4dYNrwahhz9reQOtV6QybHPTDqvARCExXTp1p7+9yQ7nhKlUJQjWYjwU6jblU8=
Received: from SG2PR01MB3578.apcprd01.prod.exchangelabs.com
 (2603:1096:0:3::14) by PSBPR01MB3734.apcprd01.prod.exchangelabs.com
 (2603:1096:301:e::16) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5417.26; Tue, 12 Jul
 2022 09:09:51 +0000
Received: from SG2PR01MB3578.apcprd01.prod.exchangelabs.com
 ([fe80::d96:d2a5:a5a6:a576]) by SG2PR01MB3578.apcprd01.prod.exchangelabs.com
 ([fe80::d96:d2a5:a5a6:a576%9]) with mapi id 15.20.5417.026; Tue, 12 Jul 2022
 09:09:51 +0000
From: Production <production@(removed)>
To: NetSol Support <support@(removed)>
CC: Maneerat (removed) <maneerat@(removed)>, Weerawat (removed)
	<(removed)@(removed)>
Subject: BG
Thread-Topic: BG
Thread-Index: AdiVzuWSLnvIKQjPTMyA2qOyKsgdKA==
Date: Tue, 12 Jul 2022 09:09:51 +0000
Message-ID:
 <SG2PR01MB3578A806109518B33F4D96FC9A869@SG2PR01MB3578.apcprd01.prod.exchangelabs.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-TNEF-Correlator:
Authentication-Results-Original: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=(removed);
X-MS-Office365-Filtering-Correlation-Id: e11e3628-20f5-4b39-f1b2-08da63e6489d
x-ms-traffictypediagnostic:
 PSBPR01MB3734:EE_|PSAAPC01FT051:EE_|SI2PR02MB5001:EE_
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
X-Microsoft-Antispam-Untrusted: BCL:0;
X-Microsoft-Antispam-Message-Info-Original:
 6kpLvZPSRrKZpSsZQ/gqyNMjb8ubr3L8HpBp5gv3I/W/d0zVO9EFV8rnoWRUXlufDRRJMdqQ6AlzRe4R6vVdxXGQcoJH8BoQ1BmRH+MlEAvuLEuI3NzPWpTKcmP92zCEZPjpT9txxgtR96U7dRrjG9x0dv643hNqye8MTxzYJvU2ykfjCe33XdB6Oxhse5uT4rsib4/2WK6lyx687tzoHDrZuNrViQSheW4YckkGb2XziAuUXnk5waMCLH9kGzpxAUhBwMXkDTGlZ+RizvAdBPWAWSQzCPHcV2p0gpz2KAyqa0QFzuAbXRr7caVXdTRyS2u8TgIIH0j6p8puqXY9QeusgVyrzJCWTwMcUyd5o+hQViX4FlI9Cl+YZufGpx0CtAB4HZ8Ewkh6i0pH3axwkRBwwbAB17Hm3HZBFftL9LeT7pjMHe0J21wOUkWh65Kzfek202HHctqTrqnh9CJWofFOSBYXxecuwtLMtB/zZmvQcNci1zjigWATaSgPjq+P6V6E856KptBhg49i1zJEfLJV53s8svcGaqE83ZksD2jYBflmlITi7qzJS0PpShYUDRm8AtmQ34NwTCpoTFD8AdPDR2E0Hx6kutIMOkYbfRe+/YDuKaOVQZ8sK2A7OZOVI9L8HRBuPM3NNBG7TYqDiFuMl3pxRVp9p8nymY0c2GA3Mx079ac2Ue+UlVV1PnhLwW61AdcjAZ2NB4aCGy/wNH7z7LWbfNM4OBp9nv2/9LQGJHQe0SNgan/MI4mkmSPtRJGvFzjGy/yvV1XRVs6dxVAVsJajtSW+A/kHw/VrpyN5Wd4zRj2Hht7A/Ju+8CFU
X-Forefront-Antispam-Report-Untrusted:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:SG2PR01MB3578.apcprd01.prod.exchangelabs.com;PTR:;CAT:NONE;SFS:(13230016)(4636009)(136003)([39830400003](tel:39830400003))(376002)(366004)(346002)(396003)(66446008)(64756008)(66946007)(8676002)([38070700005](tel:38070700005))(186003)(450100002)(55016003)([71200400001](tel:71200400001))(316002)([3480700007](tel:3480700007))(76116006)(66556008)(4326008)(99936003)(55236004)(66476007)(558084003)([4270600006](tel:4270600006))(7696005)(9686003)(7116003)(478600001)(86362001)([41300700001](tel:41300700001))(6506007)(52536014)([38100700002](tel:38100700002))(122000001)(6916009)(54906003)(2906002)(8936002)(33656002)([83380400001](tel:83380400001))([5660300002](tel:5660300002))(26005);DIR:OUT;SFP:1102;
X-MS-Exchange-AntiSpam-MessageData-Original-ChunkCount: 1
X-MS-Exchange-AntiSpam-MessageData-Original-0:
 =?us-ascii?Q?l1dKzyeli8eec0x0XD60ivhR879bkNmvafYLZMTZNoFBzaVHo7IHMSMQbYqR?=
 =?us-ascii?Q?1DYd4mEpEf1HXCKCHX6lgfaHyo3OIGhsi90Yw5KWP65tx4PS+8VELTiCOrmb?=
 =?us-ascii?Q?TQklsXBDLQBnHi03jRGTEpcMOnh01qhIxCKPppSr6pSV1gRCSAWcaKQcdfnF?=
 =?us-ascii?Q?rDBi+8XXtFiLDoIjQW+FU8A+f1OstErCnAc+6+MPEgUBjh4bIjxzs95ha9S0?=
 =?us-ascii?Q?IGXXOF1bMdKmd0yhqoaG3GORnAMD/EHPJ6WWMR/1AXtbuMfu4GUbbwnTNISV?=
 =?us-ascii?Q?SrdW2ij2ozuaXbdwJwS3rgamm2dn2fjwJtwKHJt0UqgW5ds5FPf0KC2w5rtU?=
 =?us-ascii?Q?MNRhcY3LDqAP9jjECTFbmo/N3Ad4sZerIeAxSVBfD8/K/2KSfWYai+HVMYhv?=
 =?us-ascii?Q?DCc2OU+NcE671f2he/HsElKPYgsO8G2ehNVDOj6ukrJlXCIpEELaBYHh+f9h?=
 =?us-ascii?Q?Fzxj1cUighab2NpBCJ5+m+z558qiMKBuUu2tYaH74hAwUZS60RBrd+kutNgf?=
 =?us-ascii?Q?OppsR2IR7V6y9e0qFbwFr9Vw5yJfPuMJ4/F4h91jqbxBj3CbGcw2I+pq7CvH?=
 =?us-ascii?Q?9NUBiygAZ2Kcs6Vuw+AjXSzw2p10aoeTetTe34i9o1/NNlfbMvaUrbP8xZYq?=
 =?us-ascii?Q?DtUs+ip8+nrzLvZK7v6K2XkXVSNtpk+8eBE9VYDCjkbHBQb3Lv8u+cWRvcef?=
 =?us-ascii?Q?f4MiswzonQ1vyUQmkz85HSmJY199h3OvM8VKH2GBnNjI5Ue4FSfut1K9ufOp?=
 =?us-ascii?Q?adps2G+lZ5eZWtViCwEbGcFV37Q6pw7UQTKVB7NQrJtjaYKnl59odi/4Oj93?=
 =?us-ascii?Q?zg3vaadWjahZUqTzqVbltzIOpAaPdTb92gg1Y7r4H/4PPKV1bRnrolwCzuhs?=
 =?us-ascii?Q?+uJPyrcv0COAf3+7EaFU8ncFZFUsxrMilCTQIgVqAUI9B8MHslCdxuMV3hV+?=
 =?us-ascii?Q?C05bNKORV1DhtIVg68nO+g0yfq/gCh/OS4PakRwJwfrX++02XV+PwFZJzCXW?=
 =?us-ascii?Q?DFHSF1pfW/zsXeEMhieV9JT5UG8TifCZSLTbGeP/Wc8CAfWGnyFhRvT+d3+W?=
 =?us-ascii?Q?Md0LC7GZcCM2B9KvoVEasHFGtQgvpj/LVTYRAw3WiXhRSqxpYGLSBjnfVibV?=
 =?us-ascii?Q?N5lDigCRbU6O5esHCopOiE9uvs0zd6G4t7sy0qYeN2q7E6eFcZjNzelXhzRD?=
 =?us-ascii?Q?XU66JRvFPZR3jX0nmABAXVVDBItzHoMg2B8jTHlLKhPUwaoVpY7A/g7K8PUA?=
 =?us-ascii?Q?YppoDfsaWqgoG9JcdF3QwDxw9n0uxefcJBCoG+HAvu99+MgdeRHTfd1PMRts?=
 =?us-ascii?Q?THE3Dvsx+Uziuwd7ar022ocueCZLtErSlWXBIwCdv1tQwIaBIuaHiVKI6yHx?=
 =?us-ascii?Q?0G6YolLDqaI/+iYeqYJQeys+2F27dJeuUtq7oMao/m/l8VCWz9WDabuK8SAe?=
 =?us-ascii?Q?+QOpLaTvj4DbUNMBg1xcnkRsfTg5qxQB5DVHZkqHRb0eU+6Fa9sqhy/q2jee?=
 =?us-ascii?Q?ywZzBykkSPHKMgr0Rz4lfvfdydVOjzEPGtCs5WNIhCN0mOyS0M/3JXLQPn7E?=
 =?us-ascii?Q?TO4PuBRTK816th9zGqO2bWndje5eAYIdKfUui58y?=
Content-Type: multipart/related;
	boundary="_005_SG2PR01MB3578A806109518B33F4D96FC9A869SG2PR01MB3578apcp_";
	type="multipart/alternative"
X-MS-Exchange-Transport-CrossTenantHeadersStamped: PSBPR01MB3734
Return-Path: production@(removed)
X-MS-Exchange-Organization-ExpirationStartTime: 12 Jul 2022 09:09:53.8284
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id:
 e11e3628-20f5-4b39-f1b2-08da63e6489d
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 97367575-4b08-4217-a3fb-896f1331ae37:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-Exchange-Transport-CrossTenantHeadersStripped:
 PSAAPC01FT051.eop-APC01.prod.protection.outlook.com
X-MS-Exchange-Transport-CrossTenantHeadersPromoted:
 PSAAPC01FT051.eop-APC01.prod.protection.outlook.com
X-MS-PublicTrafficType: Email
X-MS-Exchange-Organization-AuthSource:
 PSAAPC01FT051.eop-APC01.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Office365-Filtering-Correlation-Id-Prvs:
 d767007b-7cbe-41bb-6c28-08da63e6473b
X-MS-Exchange-Organization-SCL: -1
X-Microsoft-Antispam: BCL:0;
X-Forefront-Antispam-Report:
 CIP:40.107.255.131;CTRY:KR;LANG:en;SCL:-1;SRV:;IPV:NLI;SFV:SKA;H:APC01-PSA-obe.outbound.protection.outlook.com;PTR:mail-psaapc01on2131.outbound.protection.outlook.com;CAT:NONE;SFS:;DIR:INB;
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 12 Jul 2022 09:09:53.7347
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: e11e3628-20f5-4b39-f1b2-08da63e6489d
X-MS-Exchange-CrossTenant-Id: 97367575-4b08-4217-a3fb-896f1331ae37
X-MS-Exchange-CrossTenant-AuthSource:
 PSAAPC01FT051.eop-APC01.prod.protection.outlook.com
X-MS-Exchange-CrossTenant-AuthAs: Anonymous
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: SI2PR02MB5001
X-MS-Exchange-Transport-EndToEndLatency: 00:00:04.8910182
X-MS-Exchange-Processed-By-BccFoldering: 15.20.5417.026
X-Microsoft-Antispam-Mailbox-Delivery:
	ucf:0;jmr:0;auth:0;dest:I;ENG:(910001)(944506458)(944626604)(920097)(930097);
X-Microsoft-Antispam-Message-Info:
	=?us-ascii?Q?OOQvILjd5e4/90I03FC8S7sFXaLOWC52Zv5vNWInWw8+F2CnXYZzx3pbu7wP?=
 =?us-ascii?Q?QZ94dpmLjbsq3ZinEZR6diVk2kq2qV0CC0bIhyXXnAN/w5QWP7R+m7vWR8j2?=
 =?us-ascii?Q?UG0V6/p5zJ7VV8cNf95xzs6sNnSNLbT7Q6+M8yWsyVsIxBb3E0Kkl+yYkpUp?=
 =?us-ascii?Q?2LWSWyyg0O8M4bJdFyEw2ZogUTRPAb5/8ps1rl95+ZH7nmP3U9c2yDDl/qTS?=
 =?us-ascii?Q?oMWkNKw/icB3RH8gcyNwg5LG8vl+qXcZg0336wqO67jxBO8QaxAiWyDDjDnd?=
 =?us-ascii?Q?bR4io1u2aH8P6mrP70sRvoxklt7GtQVlmb22qe6z6CEsRF5dp0E0dfr6WGlH?=
 =?us-ascii?Q?3XhNHGEQ4afruAgCSnIKrK8VbB0/48HPOColeX60ZHQMf6zxV/61m1rLnak/?=
 =?us-ascii?Q?YX1yZHL53J/Jxzs8dF+NILUWvyYxBbD3REp3A0N2KRz/M3tHiudpDQSl2A4U?=
 =?us-ascii?Q?YXFbDLAAD428vatWByat4EnY4s+1KVSkkmVA508Hw3YtjEcIScUdbK24rfh3?=
 =?us-ascii?Q?WMyZoXqAhMmw/qkJKCKfI87+PMkJvifGF2SkP+AzHIgpo+QPy5LYccnwMSJq?=
 =?us-ascii?Q?AFM/FYIniuQ1KdRPLUFKXEgZsSw81ENGZObbZFu1zRhfSN928OyrySSbIOOl?=
 =?us-ascii?Q?tQNpWa8VYkgal2PimB4/Kod9KDP1RhKe5L8Z69PQPXH3jncyELjbV/O71y4z?=
 =?us-ascii?Q?lvYAvFXQgZA/UL0m/Y+mO7YsrHlqL6RkOUAdGMLnL+H320OM/6f4zykhE/WD?=
 =?us-ascii?Q?1wn6BMD9Dud+7nPs+W/+ta7+/kjiplf+Gdx0Zv2bzh5iaEpQ3ggo7E0o3jP9?=
 =?us-ascii?Q?bRFMdgQwaHc9RdKB6selEGg9qkXDoj4zAtR286l5x5z/27HDFJ0L5P1N1P5a?=
 =?us-ascii?Q?unOUVHd752XJ16JrZEZSjnr1kkf4s3dnls2KPQCjXm0Djx704hIsGk3uVjHU?=
 =?us-ascii?Q?QTQ4mfGb9InAVZkTZdqrwCuu++oCn7IRM6ylhn6TSZrGl27LRVO+7SCL+hcv?=
 =?us-ascii?Q?14zy5lBEZ/8Og2hCYJ0FnoexXQqzDzwO9sazO3vDffi6OSwNb3tkh+aqBeCr?=
 =?us-ascii?Q?briVC9P1WJVhnrjuBElRT7GGIyw5gNjYE3cBlLjB3o+N8IzKRXcXh6EqRyGZ?=
 =?us-ascii?Q?AnKHJbh42SgNyChzpwaLtylXaksOTex3LHGHTfUo/JtgR27AQzhpXT0yAv4H?=
 =?us-ascii?Q?Pcdd2JMe5xS9hRdfOE7sXdFwSEJpTLHAhTGLplZA7paUtQ3LvDDhherkXEdD?=
 =?us-ascii?Q?e2+jsp34WOuHZ/jq7uk+z2xt3vEbMn9VD3IAaJz14oOk6tFqWRMj68GEV/rs?=
 =?us-ascii?Q?r/40R8eQcwvN4i7jCJJvC1EsvATak1WDv2CIo3Wqz+2ASuZjEP6GCA/WORLM?=
 =?us-ascii?Q?+tgUnSpScfA/nmGXMXzSZ+h13RBoUgU2IStKfsGTjC4Ai4NnF60LMZ50notq?=
 =?us-ascii?Q?eguI3s5y2KBd8xdYUVXGs2RIkSUPeGq41HJU42xrNLKQtJA8ZXngUHl8G0np?=
 =?us-ascii?Q?AtdsZ/DUENdtfwvCPALN7XsJLnqrbK9M6H2ojrE9D9kZfc8PQ/UmpdEE7F8Y?=
 =?us-ascii?Q?ujURyhU/L3KnVrr4gRQufdmD5nj8eBAZ95aLbDKBLZj0axadJBYn09uJuGYq?=
 =?us-ascii?Q?joru4LV+ZLq4UNautm9pyJEUSmJqWgxDtMtVoFY2bnHYS1aFvHDom1LoN4mt?=
 =?us-ascii?Q?4ySjDYPRlHhiTFoKgLAn0KiyM5iRVxPQZPJi3t7grfpTZDtiScJFGdlscNNj?=
 =?us-ascii?Q?1beV8rnivyretRPglwj8RH97Q+pmUqP/VVJwRAJFYzs173Q9ZvWPKZcu1pBQ?=
 =?us-ascii?Q?e6Hfr7q3+P4V8DyCXI9H7Xqe+MLZBTvcRjoZsrSHPspEOsrR0CTP8C9w+/kA?=
 =?us-ascii?Q?eGbQrM0V5iaP0i9CkLUhsjDNG4/eCWbVfvGqSKAGliJ7u5Tt7TW30O676OJ8?=
 =?us-ascii?Q?MxX1XKWxm5oSA0fnindSOdB+dOj/7tO9zu7FlNxBMzSNmFv4HoxamrcnWSy2?=
 =?us-ascii?Q?4bsc?=

**Comment by freescout-helpdesk** [comment]
> FYI we are using Google Workspace and we get these empty last name contacts created as well. Received by email.
> 
> ![freescout-empty](https://user-images.githubusercontent.com/5170216/180641718-b4844fff-b253-43ad-83ea-c4ab778d017b.jpg)

Are you also using modern Microsoft Exchange authentication to fetch emails?

**Comment by gbissland** [comment]
> @gbissland Are you also using modern Microsoft Exchange authentication to fetch emails?
No, G Suite / IMAP

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. We'll leave it as `help wanted` in case someone who can reproduce will be able to find a solution.

**Comment by freescout-helpdesk** [comment]
Does it still happen for you in the latest FreeScout?

**Comment by bekre10** [comment]
The last time it happened was on 9th December but since then we didn't receive any tickets from those customers where we used to see the issue. Give me a few more days and I am sure we will get tickets from them. I shall update here then.
Thanks for following up anyway.

**Comment by bekre10** [comment]
Seems to work. Thank you very much.

**Comment by freescout-helpdesk** [comment]
Good to know.
