### ISSUE TITLE
Blank Email

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2094]
I am having a similar issue to: #1972 
When I'm connected via the Microsoft Exchange API I sometimes get blank emails.
It happens rarely, I def remember it happening with an email that was forwarded to me. 
But if I'm connected via standard IMAP settings, I don't experience any issues.

**Comment by netspear** [comment]
@afawaz2 yes, same for me. the legacy auth works great. But I was informed that the legacy auth won't be supported by Microsoft starting October of this year.

**Comment by freescout-helpdesk** [comment]
Try to "ping" maintainer of the "php-imap" library: https://github.com/Webklex/php-imap/issues/230

**Comment by freescout-helpdesk** [comment]
Closing as duplicate
