### ISSUE TITLE
"Invalid host" and "SuspiciousOperationException" in Laravel logs

### ISSUE THREAD

**Issue by tomatic** [freescout-helpdesk/freescout#2095]
I'm seeing the following error in the Laravel logs every other day and don't know what to make of it, couldn't find anything in the docs, issues or by googling:

`Invalid Host "${ip}:${port}". {"exception":"[object] (Symfony\\Component\\HttpFoundation\\Exception\\SuspiciousOperationException(code: 0): Invalid Host \"${ip}:${port}\". at /var/www/html/[REDACTED]/overrides/symfony/http-foundation/Request.php:1292) `

We have Freescout running on Ubuntu 20.04 LTS using nginx.

Any idea what might be causing this and what it even means?

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules?

**Comment by tomatic** [comment]
Nope, only official ones in their latest versions on Freescout 1.8.20.

**Comment by freescout-helpdesk** [comment]
It's hard to tell the reason without an access to the server.
