### ISSUE TITLE
X509 Authentication

### ISSUE THREAD

**Issue by Rain-Admin-IT** [freescout-helpdesk/freescout#2097]
Set up SAML through Azure SSO
I get this error everytime I log on using Edge.  
AADSTS75011: Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Freescout application owner.

If I log in using Inprivate, it works perfectly.

Using Chrome - it works fine.

Any idea how to resolve this.

**Comment by freescout-helpdesk** [comment]
Some people managed to integrate SAML Module with Azure.
We can't help here - you may need to find a solution by yourself. We've added this and other Azure related threads to https://freescout.net/module/saml/, so maybe someone will help.

**Comment by brannan-holland** [comment]
Wanted to leave a note here. I was having the same issues. I researched the error, and it seemed to be related to the Authentication context. I removed this completely, and everything is now working. 

Side note, mine was receiving this error on all browsers.

**Comment by Stunt0265** [comment]
I'm seeing this same error now but it was working fine for days.  And I removed the Authentication context and it's still broken.

**Comment by Stunt0265** [comment]
This seems to have fixed it.

https://support.laserfiche.com/kb/1014435/you-receive-an-azure-ad-aadsts75011-authentication-method-by-which-the-user-authenticated-with-the-service-doesnt-match-requested-authentication-method-error-when-trying-to-sign-into-laserfiche-directory-server-with-azure-ad-saml-sso

Use this:  urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified
