### ISSUE TITLE
No outgoing email when customer sends a second message in a row

### ISSUE THREAD

**Issue by maisen20** [freescout-helpdesk/freescout#2098]
So far, everything has worked flawlessly. Unfortunately, however, there seems to be a bug in the application.

Following scenario:

The customer contacted support and I sent him a first response. After that, a new message came from him.
While I then wanted to write back, apparently a next message came from him without me being able to reply to his last message. However, I then continued writing my captured message and replied to his second to last message and only then reloaded the window and saw his new message.

According to the system, my email was never created or generated in his penultimate message, probably because he sent another message. However, in my history in the support portal, I see all messages as they were recorded. This includes my reply, which was never sent. No message is displayed for "Outgoing e-mails" and this message/e-mail is also not present in the logs for outgoing messages.

Chronology:
1. receipt of the first message from the customer
2. answer from me (support), e-mail was generated and delivered
3. answer from the customer
4. additional answer from the customer
5. answer from me (support) to the penultimate message from point 3, e-mail was NOT generated for e-mail delivery and therefore was not delivered (no message in Logs)
6. answer from me (support), e-mail was generated and delivered

Has anyone else had this problem?

System:
- freescout version 1.8.17
- no missing php extensions
- no errors in logs

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by maisen20** [comment]
> See https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

My problem is not an "not sent" or "undelivered" email. One of my replies from free-scout did not generate a message to send.

**Comment by freescout-helpdesk** [comment]
Make sure that [Background Jobs](https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs) are running.

**Comment by maisen20** [comment]
Backround jobs was active and running. The problem is something else. 

No idea why you just close this issue right away.

**Comment by freescout-helpdesk** [comment]
> 5. answer from me (support) to the penultimate message from point 3, e-mail was NOT generated for e-mail delivery and therefore was not delivered (no message in Logs)

How do you answer to the penultimate customer message? by email or via FreeScout web interface?

**Comment by maisen20** [comment]
I answer always via FreeScout web interface. I‘m not at home now, but maybe i can make some tests in the next days or weeks.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. If someone can preproduce feel free to submit a pull request.
