### ISSUE TITLE
MobileNotifications not working, error in SendPushNotificationToUsers

### ISSUE THREAD

**Issue by quanltt** [freescout-helpdesk/freescout#2101]
Dear Everyone

I have Freescout 1.8.19 run on Ubuntu 18, with PHP 7.2.15. Recently the  MobileNotifications stop working. In the system menu, it says the job Modules\MobileNotifications\Jobs\SendPushNotificationToUsers fails. I upgrade Freescout to 1.18.20 but it still dose not work (the job also fails).

I email the support but they did not reply. 

Could anyone know what is the problem and how I can fix this. 

Thank you very much,

Regards,
Quan

**Comment by freescout-helpdesk** [comment]
It's hard to tell. You may need someone who can debug it on your end.
