### ISSUE TITLE
Some replies are skipped and not being sent. 

### ISSUE THREAD

**Issue by ahmedkaludi** [freescout-helpdesk/freescout#2102]
So, in the email thread, some replies are not going at all. 

When diving deeper, I found out that the emails that don't go through have "There were no send attempts yet" error inside while the emails which are sent have a reference of the email in the table

See screenshot: 
<img width="921" alt="#540 Re: Ticket #19384 - Some of our amp pages are broken - Tamir Israely 2022-07-18 12-37-11" src="https://user-images.githubusercontent.com/16532359/179460258-aaf680c1-1cea-47bc-9be5-b997f911ec46.png">

**Comment by ahmedkaludi** [comment]
any help team?

**Comment by ahmedkaludi** [comment]
@freescout-helpdesk Please help. This is very urgent for me.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by ahmedkaludi** [comment]
@freescout-helpdesk I've checked, no errors anywhere

**Comment by freescout-helpdesk** [comment]
Most likely the problem is with the background job.
