### ISSUE TITLE
API module - Conversation

### ISSUE THREAD

**Issue by Fearofthedark66** [freescout-helpdesk/freescout#2103]
Hi,

I just installed the API module and tried to add a conversation with the following javascript sample I found in the API documentation.

```

function newTicket(){
const url = new URL("https://hxsystem.se/api/conversations");


let headers = {
    "X-FreeScout-API-Key": "xxxxxxxxxxxxxxxx",
    "Content-Type": "application/json",
    "Accept": "application/hal+json",
}
let body = {
    "type": "email",
    "mailboxId": 1,
    "subject": "Hi there",
    "customer": {
        "email": "mark@example.org"
    },
    "threads": [
        {
            "text": "This is the message from a user",
            "type": "message"
            
        }
    ],
    "imported": true,
   
    
}

fetch(url, {
    method: "POST",
    headers: headers,
    body: body
})
    .then(response => response.json())
    .then(json => console.log(json));
}
```

Problem is that it throws the following error: `"message":"`subject` parameter is required"`

What can cause this? I am trying to add a conversation from my localhost to my production, is that the issue?

Regards, Joakim

**Comment by Fearofthedark66** [comment]
I am trying the samples from the documentation and this is how it looks in chrome. I can fetch all conversations and customers but not adding new conversations and thats a showstopper right now for me. Someone got any ideas on how to move forward with this issue?

![2022-07-19_08-57-32](https://user-images.githubusercontent.com/78161507/179686280-ac93edfe-5462-4dac-aaa0-e8f3f4c546a6.jpg)

**Comment by Fearofthedark66** [comment]
@freescout-helpdesk , any suggestions how to solve this, it is getting a bit little urgent.

**Comment by freescout-helpdesk** [comment]
Most likely API endpoint does not receive post parameters by some reason. Double check your fetch method.

**Comment by Fearofthedark66** [comment]
Got it and it is resolved.
