### ISSUE TITLE
Twitter Module - Twitter webhook forbidden error - Help needed

### ISSUE THREAD

**Issue by b4oshany** [freescout-helpdesk/freescout#2107]
Unable to connect Twitter to FreeScout. I've followed the steps shown in the guide and created a "Regular App" in the Twitter developer profile.

However, whenever I tried to enable the module with the Consumer API Key and Secret, and the Access Token Key and Security, I keep on getting the error shown in the screenshot below:

![image](https://user-images.githubusercontent.com/1830494/180307375-fba1f357-e960-423a-b70d-f39b6b438817.png)

Help!!!

**Comment by freescout-helpdesk** [comment]
Make sure that you enter correct API Key and Access Token data.

**Comment by b4oshany** [comment]
I did, trust me on that.

**Comment by freescout-helpdesk** [comment]
We have not experiences such issue. Try to check - maybe there is some restriction on creating webhooks on Twitter side.
