### ISSUE TITLE
Hi, I set the language in Manage > Settings to **Spanish**.  But when I go to the End User Portal, I see 4 words that are not translated. Also, I tried to search in the translation module, but there is no End user option for translation. Please help me in order to translate those words in any way. Thanks...

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#2108]
Hi, I set the language in Manage > Settings to **Spanish**.  But when I go to the End User Portal, I see 4 words that are not translated. Also, I tried to search in the translation module, but there is no End user option for translation. Please help me in order to translate those words in any way. Thanks...

![2022-07-21 at 18](https://user-images.githubusercontent.com/84030633/180324300-7c62ea67-7850-4930-9184-4a01fad39eb8.png)
.

_Originally posted by @DanielBendersky in https://github.com/freescout-helpdesk/freescout/issues/1904#issuecomment-1191988617_

**Comment by DanielBendersky** [comment]
Hi, just another thing, When I go to the End user portal as a customer and Try to Log in, I receive an email for confirmation. This email is also nos translated:

![2022-07-21 at 18](https://user-images.githubusercontent.com/84030633/180331078-074a6201-a1bc-468c-88bc-ac3edcd0a61e.png)

**Comment by freescout-helpdesk** [comment]
Apparently those strings were not translated into Spanish. We've received some Spanish for End-User Portal Module. They will be added to the module soon.
