### ISSUE TITLE
Adding Attachments

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2109]
I'm having trouble attaching documents of any size to notes inside conversations or to an email I'm trying to send out to a client.

I have FreeScout installed on a virtual Linux server.

I have checked the web-server.log file under App Logs and found the following error message:

2022/07/22 05:31:37 [error] 744#744: *267174 client intended to send too large body: 1734635 bytes, client: 192.168.200.4, server: freescout.example.com, request: "POST /conversation/upload HTTP/1.1", host: "freescout.example.com", referrer: "https://freescout.example.com/conversation/1211?folder_id=7"

The file isn't big. I know emails generally have a limit of 20M. This file was 1.65MB

Would anyone be able to help me resolve this issue or help me increase the upload size limit for attachments?

**Comment by ilyakonovalenko** [comment]
You probably have such limitation in nginx configuration.
Try to increase client_max_body_size param.

**Comment by netspear** [comment]
> You probably have such limitation in nginx configuration.
> Try to increase client_max_body_size param.

How would I be able to do this?
Sorry, I'm kinda still new to all this.

**Comment by ilyakonovalenko** [comment]
> How would I be able to do this?

You have to edit nginx configuration. Please contact your system administrator or hosting provider if you are not familiar with Linux management.

**Comment by netspear** [comment]
Thank you for the Info! I Found the fix.

I have a Virtual Linux Server. So to increase the size, I followed the directions in this link:

https://linuxhint.com/what-is-client-max-body-size-nginx/

The nginx.cong didn't have the client_max_body_size 
So I added it and set the limit to 100MB.
Then restarted Nginx and it worked like a charm.


Thank you!!!

**Comment by ar-ml** [comment]
**Just for anyone who might be reading this in the future:**
I had a similar issue with uploading files to the freescout backend. Also attachments where sometimes not accepted when uploading them to the freescout frontend form (End-User Portal).

**My solution for my Server:**
1. Install filezilla and connect to your server using sftp:// and your SSH credentials
2. go to /etc/nginx and download nginx.conf
3. In line 27 I added:  client_max_body_size 20M;
4. uploaded the modified nginx.conf via filezilla and overwrite the old file.

5. Then I fetched the file  php.ini from /etc/php/7.4/fpm
6. I changed the following values:
    max_execution_time 120
    memory_limit 128M
    post_max_size 32M
    upload_max_filesize 25M
7. uploaded php.ini again and overwrite the old version
8. Connected to my Server via SSH using PuTTY
9. Restarted the whole server using the command _systemctl reboot_

-> After that I was able to upload attachments to freescout with a maximum files size of 25MB.  :-)

**Be aware that I am not 100% sure if the set values are appropriate  - and your setup might need different values.**

Feedback about my procedure and the chosen values is appreciated. Thx!
