### ISSUE TITLE
How does conversation email work?

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#211]
I've received a new email with a Cc.
A new conversation was properly created with Cc saved.
Then i've assigned the conversation to my user
When replying , the email Is sent to the original writer, to any Cc and also to the mailbox address. Is this correct?

Sending the email to the mailbox address will fetch it again. For an unknown reason, the original conversation changed the author from the original one to the mailbox address. Very strange.

**Comment by freescout-helpdesk** [comment]
Is your mailbox email specified in mailbox's `Email Address` or in `Aliases`?

**Comment by guestisp** [comment]
In this case, yes. Why?

**Comment by guestisp** [comment]
In aliases
