### ISSUE TITLE
smtp port 465 connection error 

### ISSUE THREAD

**Issue by Mykadlo** [freescout-helpdesk/freescout#2110]

**Comment by Mykadlo** [comment]
Hello, 
I have the freescout installed on shared webhosing provided  by interserver.net (recommended cloud provider). 
I am trying to connect a mailbox and I am experiencing connection error on smpt server port 465 - the connection can not be established even the cloud hosting provider confirmed that the port 465 is open. The unsecure connection to the same smtp server on port 587 works, but the SSL connection on port 465 fails. 
I have tried two mail servers, both have the same problem - port 465 is unreachable. The mail server needs TLS v 1.2 or v1.3. Is Freescout compatible with  TLS v1.2+?

**Comment by freescout-helpdesk** [comment]
Till now there was no problems with TLS v1.2+
We'll try to check with Interserver Team.

**Comment by Mykadlo** [comment]
The issue is still in place, but I have implemeted workaround and solved it through internal smtp server. So I close the issue to clear the queue, not important for me now.
