### ISSUE TITLE
Bug - tracking pixel route has trailing slash, which causes issue on apache2 in some configurations

### ISSUE THREAD

**Issue by virtiqa** [freescout-helpdesk/freescout#2111]
When freescout installed on apache2 in a subdirectory, the .htaccess file in public redirects trailing slashes.

But the tracking pixel uses trailing slashes in the route URL generated in the email template.

Submitting this issue and I can create a PR with the fix once approved.

**Comment by freescout-helpdesk** [comment]
Sure. Feel free to submit a PR.
