### ISSUE TITLE
Problem with search filter on Postgres database

### ISSUE THREAD

**Issue by kalinop112** [freescout-helpdesk/freescout#2114]
Hi,
I have some issue with search filter on subject and body.
I tried to find some schema in the search mechanism, but I'm lost.

Let me explain, I have many mail, but there two with subjects:
"The best of the latest edition of Expo Riva Schuh & Gardabags"
"The latest news on FotoShoe 30 | July 2022"

When I put "latest", I've got 2 answers:
"The best of the latest edition of Expo Riva Schuh & Gardabags"
"The latest news on FotoShoe 30 | July 2022"

When I put: "the latest", I've got 1 answer (why? the secound one has the latest too):
"The best of the latest edition of Expo Riva Schuh & Gardabags"

Put "best":
"The best of the latest edition of Expo Riva Schuh & Gardabags"

"the best":
none

"edition":
"The best of the latest edition of Expo Riva Schuh & Gardabags"

"Expo":
none

"Riva":
none

"latest news":
"The latest news on FotoShoe 30 | July 2022"

"FotoShoe":
none

"July":
none

It seems to me that there are only the first few words of the subject are checked and without the first one.
I couldn't find similar issue, It's just me?

PHP 7.4 and PostgreSQL 14.2

Kind regards,
Pawel

**Comment by freescout-helpdesk** [comment]
Here is the code: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Conversation.php#L2041
It works fine on MySQL. If you'll manage to find the reason of the issue on PostgreSQL feel free to submit a pull request.
