### ISSUE TITLE
Feature request: Gitea integration module

### ISSUE THREAD

**Issue by martyfuhry** [freescout-helpdesk/freescout#2117]
I'd love to integrate Freescout with my [Gitea](https://gitea.io/en-us/) issue tracker. This could be a module similar to the Jira Integration module. When customers send me an email, I would love to use the content and subject of that email to create a new issue in my Gitea issue tracker.

- Create new issues in Gitea from a Freescout case
- When the issue in Gitea is marked as closed, make the Freescout case active and add a note (like the Jira integration)

Frankly, having Github / Gitlab integration may be more popular, but I use Gitea. The code would likely be remarkably similar.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/

**Comment by martyfuhry** [comment]
Thanks, but that page is broken. I tried on 4 different web browsers across two operating systems, but it hangs. Maybe you'd like me to open a new ticket?

![image](https://user-images.githubusercontent.com/100457/186676186-63d6fe99-5e3a-415e-9b79-27a4c9c53b6c.png)

**Comment by martyfuhry** [comment]
Two months later and that page is still broken for me.
