### ISSUE TITLE
Kanban module not working with Global MailboxActive

### ISSUE THREAD

**Issue by pogla** [freescout-helpdesk/freescout#2118]
I just purchased a `Kanban module` but I cannot create a new board and select `Global Inbox`. This means that the `Kanban module` is pretty useless to me since I don't want to waste time switching between mailboxes. Am I missing something, is this a bug, or are you working on the fix already?

Here are the options I am seeing when I try to create a new board in Kanban view:

<img width="652" alt="Screenshot 2022-07-26 at 19 45 29" src="https://user-images.githubusercontent.com/6359466/181076295-3fdb0f40-5814-4636-867c-d88b7039f3da.png">

**Comment by ilyakonovalenko** [comment]
Hello,

Please double check https://freescout.net/module/kanban/
It clearly states it does not work with Global Inbox Module. It has always been there, actually.

**Comment by freescout-helpdesk** [comment]
Yes, it does not allow to create tickets in the Global Mailbox.
