### ISSUE TITLE
Freescout merging conversation with same Different subjects.

### ISSUE THREAD

**Issue by asadsajjad623** [freescout-helpdesk/freescout#2120]
Hi,
At times we noticed freescout merge conversation with different subjects. Is there some setting we should add so that it donot merge the conversation into 1. It doesn't happen with all the conversation only from few clients.

**Comment by ilyakonovalenko** [comment]
Freescout determines the conversation by different things, not only by subject. Is it reply to one of the conversations email but with changing subject manually?

**Comment by freescout-helpdesk** [comment]
FreeScout does not check the subject - it check special markers in the email body.

>  Is there some setting we should add so that it donot merge the conversation

There is no such setting.

**Comment by pedroponte** [comment]
+1
I get emails merged with different subjects. It would be nice if when the subject changes, a new ticket is created instead of merging to an existing ticket.
A lot of people recycle emails by picking an existing one and only changing the subject.

**Comment by pedroponte** [comment]
> Freescout determines the conversation by different things, not only by subject. Is it reply to one of the conversations email but with changing subject manually?

In which part of the code is this being done? To see if I can find the cause for emails being merged even with different subjects? TY

**Comment by abhishek017** [comment]
+1 
Has anyone worked on this? They closed this issue too early. Emails get merged when using same email body content, but different subject line, sent by same sender.
