### ISSUE TITLE
Reply for Telegram Integration is not working

### ISSUE THREAD

**Issue by b4oshany** [freescout-helpdesk/freescout#2124]
Good day,

I created Telegram Bot using BotFather and added the API Token and text for auto-reply as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/1830494/181487079-e060a128-0332-48fc-99fa-636148ac433f.png)

When I message the bot from Telegram, it shows up in the conversation history and the auto-reply is sent to the user without an issue. However, when I reply to the user as an agent. The message isn't sent to the telegram bot.

I don't see any errors or logs. Do you have any idea why the reply isn't working?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. You may need to debug it yourself.

**Comment by freescout-helpdesk** [comment]
FYI. We've just double checked - Telegram integration works just fine on our end.
