### ISSUE TITLE
Freescout does not add "Re:" when user replies

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2125]
According to code, freescout should add Re: to outgoing email subject when user replies to customer and if conversation has more than 1 thread. 

However, it does not happen. Email headers do not have it as well.

**Comment by ilyakonovalenko** [comment]
/app/Email/ReplyToCustomer.php, lines 81-83:
`if (count($this->threads) > 1) {
            $subject = 'Re: '.$subject;
        }`

The code does not work, `count($this->threads)` is `1` however the conversation has 5 messages currently.

**Comment by ilyakonovalenko** [comment]
I suggest the following changes (can not crate pull request for now). Tested.

1) File /app/Email/ReplyToCustomer.php.

Updated __construct function:
```
public function __construct($conversation, $threads, $headers, $mailbox, $threads_count = 1)
 {
        $this->conversation = $conversation;
        $this->threads = $threads;
        $this->headers = $headers;
        $this->mailbox = $mailbox;
        $this->threads_count = $threads_count;
 }
```

Changes to build function:
```
if ($this->threads_count > 1) {
            $subject = 'Re: '.$subject;
        }
```

2) File /app/Jobs/SendReplyToCustomer.php:

After `$email_conv_history = config('app.email_conv_history');`:
```
$threads_count = count($this->threads);
```

After `$headers['X-FreeScout-Mail-Type'] = 'customer.message';`:
```
$reply_mail = new ReplyToCustomer($this->conversation, $this->threads, $headers, $mailbox, $threads_count);
```

**Comment by lewisstancer** [comment]
I have noticed this behaviour as well, not major but does need sorting as even replies from customers don't come through correctly to email and it can be confusing
