### ISSUE TITLE
Installing modules without web interface

### ISSUE THREAD

**Issue by frederikvogt** [freescout-helpdesk/freescout#2126]
Hi!
I want to automate our installation process with ansible. The plan is to also install the modules in this way, but I cannot find any documentation on how to actually do that. The keys to the modules where bought.
If it is possible at all to activate and configure modules in an automatic way, I really would appreciate your help! :-)

Greetings
Freddy

**Comment by freescout-helpdesk** [comment]
You can create a custom module for this: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
