### ISSUE TITLE
Snooze Module And Workflows

### ISSUE THREAD

**Issue by hughfletcher** [freescout-helpdesk/freescout#2128]
I like the idea of the snooze module but have several workflows that happen after closing a issue. When snoozing a issue with this module will it activate these workflows? Or is there an option added to the workflow conditions to not apply to "snoozed" issues?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such an option for now. Feel free to submit a pull request: https://freescout.net/request-feature/
