### ISSUE TITLE
HTML not rendering in Thunderbird

### ISSUE THREAD

**Issue by diondkb** [freescout-helpdesk/freescout#2129]
Hi,

When I send a test email to my email address from Freescout, it is received and rendered in thunderbird correctly. When I compose an email and send to the same email address from Freescout and read using thunderbird, the html is not rendered. It looks like below:-

<html lang=3D"en" style=3D"background: #F1F3F5; height: 100% !important; ma=
rgin: 0; padding: 0; width: 100% !important">
<head>
    <meta http-equ=
iv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8" />
    <meta c=
harset=3D"utf-8" />
    <meta name=3D"viewport" content=3D"width=3Ddevice=
-width" />
    <meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge"=
 />
</head>

<body leftmargin=3D"0" topmargin=3D"0" marginwidth=3D"0"=
 marginheight=3D"0" style=3D"background: #F1F3F5; height: 100% !important; =
margin: 0 auto; padding: 0; width: 100% !important" bgcolor=3D"#F1F3F5">
=
=09<table bgcolor=3D"#F1F3F5" cellpadding=3D"0" cellspacing=3D"0" border=3D=
"0" height=3D"100%" width=3D"100%" style=3D"border: 0; border-collapse: col=
lapse; border-spacing: 0 !important; margin: 0 auto; mso-table-lspace: 0pt;=
 mso-table-rspace: 0pt; vertical-align: top">
=09=09<tr>
=09=09=09<td s=
tyle=3D"mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" =
valign=3D"top">
=09=09=09=09<table border=3D"0" width=3D"600" cellpadding=
=3D"0" cellspacing=3D"0" align=3D"center" style=3D"background: #F1F3F5; bor=
der: 0; border-collapse: collapse; border-spacing: 0 !important; margin: au=
to; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; widt=
h: 600px" bgcolor=3D"#F1F3F5">
=09=09=09=09=09
          <tr>
etc...

Any idea why? I am using the sendMail option to send emails from Freescout.

Thanks,
Dion

**Comment by freescout-helpdesk** [comment]
Does it happen with all your emails sent from FreeScout and viewed in Thunderbird?

**Comment by diondkb** [comment]
Thanks for the reply. 

> Does it happen with all your emails sent from FreeScout and viewed in Thunderbird?
It does not happen when I send a test email from the 'connection settings' option. I receive a normal email in thunderbird almost immediately. When I compose an email and send it to the same email address I sent the test email to, I wait about 8 hours and then get a garbled body? I tried using both sendMail and mail.

**Comment by diondkb** [comment]
Emails are being rendered as HTML text in gmail as well, not only in Thunderbird.

**Comment by freescout-helpdesk** [comment]
The problem must be in the server environment or in the sending mail server. You may need a developer who can investigate it for you.

**Comment by diondkb** [comment]
So if the email is created using the compose button inside Freescout and sent to a target email address(which does not seems to affect the rendering), the email client(I tried thunderbird and gmail) seems to render it as garble(html text).

My question is why does the 'send test email' button create the email correctly? Is the email created using a different procedure/function when I send a test? Surely it should also send a ill rendered email if they shared function code?

Thanks for your time
Dion

**Comment by freescout-helpdesk** [comment]
Compare sending methods in Settings > Mail Settings and in the mailbox. The in the mailbox does not work for you.

**Comment by diondkb** [comment]
The tests I was referring to above were all done in the mail boxes. They had the same configuration?

**Comment by diondkb** [comment]
each mail box's 'connection settings' has a 'Send Test' option. Its this test which works, not the compose of the same email box?
I hope this makes sense(I was never referring to the system email setting.

Thanks

**Comment by freescout-helpdesk** [comment]
Yes, same

**Comment by diondkb** [comment]
Using sendMail seems to not do this

**Comment by freescout-helpdesk** [comment]
So the problem is in your mail server. You may need to find a developer who can investigate it on your mail server.
