### ISSUE TITLE
Telegram Module error for incoming messages

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2131]
We see the following errors in App Log.

```
Error retrieving user info: Bad Request: invalid user_id specified {"exception":"[object] (BotMan\\Drivers\\Telegram\\Exceptions\\TelegramException(code: 0): Error retrieving user info: Bad Request: invalid user_id specified at /var/www/XXX/data/www/XXX/Modules/TelegramIntegration/vendor/botman/driver-telegram/src/TelegramDriver.php:88)
```

It looks like some checks should be added to prevent API calls in order to stop such errors.

**Comment by freescout-helpdesk** [comment]
We'll check it. Maybe Telegram made some changes in their API.

**Comment by freescout-helpdesk** [comment]
>         if ($response->getStatusCode() !== 200) {
>             throw new TelegramException('Error retrieving user info: '.$responseData['description']);
>         }

This is a regular error logging when Telegram receives invalid `user_id`. But we don't know how to reproduce the issue.

**Comment by ilyakonovalenko** [comment]
> This is a regular error logging when Telegram receives invalid `user_id`.

It looks like conversation won't be created anyway if no `user_id` is provided? If so, maybe just add a check for `user_id` to skip the rest part of the incomming message processing code?

**Comment by freescout-helpdesk** [comment]
We need to find out why `user_id` may be empty.

**Comment by freescout-helpdesk** [comment]
So far we were unable to reproduce the issue. Feel free to re-open the issue if you'll manage to find out why `user_id` is empty.
