### ISSUE TITLE
Wish: list of message recipients

### ISSUE THREAD

**Issue by phanousk** [freescout-helpdesk/freescout#2132]
Hi, I have a wish here. When sending a message (reply, note), could be somewhere under the edit field visible a list of recipients of the message? Of course updated when I change the properties of the message like Cc, Assignee, Status, Followers, ... Perhaps a new module for this. How much wuould it cost? :)
Thank you, Petr

**Comment by freescout-helpdesk** [comment]
Feel free to submit to https://freescout.net/request-feature/
