### ISSUE TITLE
Empty E-Mail field under Attributes Mapping in LDAP Module

### ISSUE THREAD

**Issue by frederikvogt** [freescout-helpdesk/freescout#2137]
When I connect freescout with our LDAP, there is only an empty field in the E-Mail drop-down menu under Attributes Mapping. This occurs even with our LDAP admin account, so I really don't have any ideas left to try out. All user-accounts have E-Mail addresses in our LDAP.

**Comment by freescout-helpdesk** [comment]
We also don't know why it happens on your installation. Try to find a developer who can find it out.
