### ISSUE TITLE
PostgreSQL not null constraint error on Add Conversation API request

### ISSUE THREAD

**Issue by stasich7** [freescout-helpdesk/freescout#2139]
We've purchased API&Webhooks module key and faced SQL error running on
PostgreSQL 13.5 (Debian 13.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
not-null constraint violations on "preview" of relation "conversations" and "social_via" further. 

FreeScout App Version: 1.8.21
API and Webhooks module Version: 1.0.41 

I've compared the result with Docker image of Freescout runing on MariaDB - there were no errors.

DB schema matches the one on MariaDB - "preview" and "social_via"  are not-null columns. But MariaDB driver converts null into default value, while Postgres not.

`[2022-08-05 11:43:23] production.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "preview" of relation "conversations" violates not-null constraint 
DETAIL: Failing row contains (106, 64, 0, 1, 1, 1, 2, [Test issue] [An error..., mark1@example.org, null, null, null, f, f, 1, null, 9, null, null, null, 3, null, null, null, null, null, f, 2022-08-05 11:43:23, 2022-08-05 11:43:23, null). (SQL: insert into "conversations" ("type", "subject", "mailbox_id", "source_type", "customer_id", "customer_email", "status", "state", "imported", "user_id", "folder_id", "number", "updated_at", "created_at") values (1, [Тестовое мероприятие] [Не загружается видео], 1, 3, 9, mark1@example.org, 1, 2, 0, , 1, 64, 2022-08-05 11:43:23, 2022-08-05 11:43:23) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "preview" of relation "conversations" violates not-null constraint 
DETAIL: Failing row contains (106, 64, 0, 1, 1, 1, 2, [Test issue] [An error..., mark1@example.org, null, null, null, f, f, 1, null, 9, null, null, null, 3, null, null, null, null, null, f, 2022-08-05 11:43:23, 2022-08-05 11:43:23, null). (SQL: insert into \"conversations\" (\"type\", \"subject\", \"mailbox_id\", \"source_type\", \"customer_id\", \"customer_email\", \"status\", \"state\", \"imported\", \"user_id\", \"folder_id\", \"number\", \"updated_at\", \"created_at\") values (1, [Тестовое мероприятие] [Не загружается видео], 1, 3, 9, mark1@example.org, 1, 2, 0, , 1, 64, 2022-08-05 11:43:23, 2022-08-05 11:43:23) returning \"id\") at /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "preview" of relation "conversations" violates not-null constraint 
DETAIL: Failing row contains (106, 64, 0, 1, 1, 1, 2, [Test issue] [An error..., mark1@example.org, null, null, null, f, f, 1, null, 9, null, null, null, 3, null, null, null, null, null, f, 2022-08-05 11:43:23, 2022-08-05 11:43:23, null). at /opt/freescout/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "preview" of relation "conversations" violates not-null constraint 
DETAIL: Failing row contains (106, 64, 0, 1, 1, 1, 2, [Test issue] [An error..., mark1@example.org, null, null, null, f, f, 1, null, 9, null, null, null, 3, null, null, null, null, null, f, 2022-08-05 11:43:23, 2022-08-05 11:43:23, null). at /opt/freescout/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)
[stacktrace]
#0 /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"co...', Array, Object(Closure))
#1 /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('insert into \"co...', Array, Object(Closure))
#2 /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\\Database\\Connection->select('insert into \"co...', Array, false)
#3 /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection('insert into \"co...', Array)
#4 /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId(Object(Watson\\Rememberable\\Query\\Builder), 'insert into \"co...', Array, 'id')
#5 /opt/freescout/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /opt/freescout/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(722): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /opt/freescout/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(687): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /opt/freescout/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /opt/freescout/Modules/ApiWebhooks/Http/Controllers/ApiController.php(675): Illuminate\\Database\\Eloquent\\Model->save()
#10 [internal function]: Modules\\ApiWebhooks\\Http\\Controllers\\ApiController->createConversation(Object(Illuminate\\Http\\Request))`

**Comment by freescout-helpdesk** [comment]
Fixed in API & Webhooks Module v1.0.42
