### ISSUE TITLE
should_save_thread: remove useless parameter

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#214]
With the current version of `should_save_thread` we are forcing module developers to create the filter function with the first useless parameter always set as true while the real data Is sent as second parameter

Can we switch back to a single filter merging `should_save_thread` and `data_to_save` hooks in a single one so that the first parameter would be `$data` and not a boolean?

**Comment by freescout-helpdesk** [comment]
There are two filters:
- `fetch_emails.data_to_save` - used to alter $data arra.
- `should_save_thread` - determines if thread should be created from the incoming email.

Using one filter for two different tasks will lead to problems.

**Comment by freescout-helpdesk** [comment]
There is a principal difference between Eventy filter and Eloquent events (including `saving`).

Eloquent event has only one processing function in the model. Eventy filter may have multiple listeners. So if for example `should_save_thread` filter has two listeners, both of them expect $data array and the first listener changes or sets $data array to `false`, second listener will receive messed up array and will be unable to analize data and perform it's work. First argument of the filter is the value which listeners are changing, all other arguments are additional which can not be changed.
