### ISSUE TITLE
Saved replies inserted in wrong place

### ISSUE THREAD

**Issue by jake-the-just** [freescout-helpdesk/freescout#2140]
We have the following problem:
Very often we do not insert Saved replies (SR) at the beginning of the mail, but type few sentences, then the SR should be inserted.

Now the following happens again and again:
I place the cursor at this position:
![CleanShot 2022-08-05 at 10 57 50](https://user-images.githubusercontent.com/89188342/183042518-807a062d-593f-44bf-abe2-0b03361b0f97.png)     

Now I go to the SR, pick one out and paste it.

What happens now is the following:
The SR is not inserted at the desired position, but at the top and everything I have written so far slides down. This leads to the fact that I have to restore the sorting via copy and paste.    

Strangely, this does not happen every time, only sometimes, which is why I suspect a bug. 
I could not see a clear pattern of when this happens. The problem tends to occur more when I paste the SR into the mail for the first time, because the error is more likely to occur. If I delete the incorrectly inserted SR, open the SR overview again and insert the same SR again, then it usually works.

Could you help? 
Would be great! In the long run it gets a bit annoying :)

**Comment by MarcoWel** [comment]
+1 on this one!

**Comment by MarcoWel** [comment]
@freescout-helpdesk Does this help with getting this solved? It would be a very appreciated improvement.
https://maxrohde.com/2014/03/28/insert-text-at-caret-position-in-summernote-editor-for-bootstrap

**Comment by freescout-helpdesk** [comment]
Fixed in Saved Replies Module v1.0.15
