### ISSUE TITLE
Conversation modals for kanban module need work

### ISSUE THREAD

**Issue by vtq221** [freescout-helpdesk/freescout#2141]
The modals in the kanban module break the UI for all kinds of actions that you'd expect to be able to do.

The x_embed URL param does not persist or is not always recognised, resulting in broken routes and the main menu appearing twice.

Behaviour that you would want is for the UI not to break, and for all visible UI routes to work.

I think some of the UI elements visible in the modal are unecessary.

I also don't think the conversation should redirect to the conversation list when in kanban - the kanban itself serves that purpose.

I've fixed some of these issues already in my fork, so happy to PR once done if maintainers agree with these suggestions.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a PR - we'll take a look.

**Comment by virtiqa** [comment]
OK will do once I've done some more testing.

Are you comfortable using javascript APIs that won't work with IE11?

This in particular: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams 

Support is here: https://caniuse.com/urlsearchparams

**Comment by freescout-helpdesk** [comment]
main.js has a `getQueryParam()` function for retrieving get parameters.

**Comment by vtq221** [comment]
Closing - changes have been merged
