### ISSUE TITLE
Paid LDAP module not binding

### ISSUE THREAD

**Issue by samsclub91** [freescout-helpdesk/freescout#2144]
Hello,
I'm working with a fresh Freescout instance in a docker container.  The website is up and running and we have loaded a few modules however the LDAP module refuses to bind.  I've configured everything according to the instructions and double checked my settings against other applications I have that use LDAP but no matter what I get an "Invalid Credentials" error.  Our LDAP server is a Server 2019 Active Directory machine.  Am I missing something simple?

https://i.imgur.com/WWmyEqI.png

**Comment by samsclub91** [comment]
I figured this out.  I was attempting to use the sAMAccountName instead of the "pretty" username that's listed as the CN.  Rookie mistake.

**Comment by websafe** [comment]
Hello @samsclub91 

I'm having a similar issue, also a 2019 Active Directory. Also getting `Invalid credentials`.

![image](https://user-images.githubusercontent.com/412013/185617694-010200fc-ac4b-4dcf-9d3e-baaec32b17a8.png)

How did you solve your issue? Have you created another user or di you use the `Administrator` account?

**Comment by websafe** [comment]
OK, I've got it :-) Somehow after reading: https://github.com/freescout-helpdesk/freescout/issues/1011#issuecomment-1006944232

In my case the solution was:

LDAP Host: `192.168.99.211`
Port: `389`
Encryption: `TLS`
Bind DN: `CN=Users,DC=corp,DC=contoso,DC=com`
Bind Username: `Administrator`
