### ISSUE TITLE
freescout does not shows images in note / conversation

### ISSUE THREAD

**Issue by bf-support** [freescout-helpdesk/freescout#2146]
Hi all,

we used freescout as our ticketsystem to receive problems from our workers / employees.
They send us an regular email with the problem to our email address which is binded in freescout and freescout translate the email to an ticket.

the problem is when the customer send us an email and paste an screenshot to the email text, freescout does not show it.
just an empty space between the text lines where the screenshot should be.

did someone know was can be the problem? its an problem from freescout ?

TYA!

**Comment by freescout-helpdesk** [comment]
We've never seen this kind of issue. Must be some local issue.
