### ISSUE TITLE
Modules Teams + Mentions do not work in combination

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2148]
We have both Teams and Mentions module installed on Freescout 1.8.21.

- When a user is mentioned in a note, he receives a notification just fine.
- When a team is mentioned in a note, none of the team members receives a notification (even if they have their profile setting "I'm @mentioned in a conversation" enabled).

Seems to be a bug?

**Comment by MarcoWel** [comment]
Addition: The team mention seems to work for some members, but the notification is delayed compared to single user mentions. Could a blocked job queue delay/omit the team mentions?

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. It works fine on our end.
