### ISSUE TITLE
imap_open() failure to Exchange 2019

### ISSUE THREAD

**Issue by abooltink** [freescout-helpdesk/freescout#2149]
Hi,

after switching over to Exchange 2019 the IMAP fetching of Freescout throws an error "could not open stream". On Exchange 2016 it just worked.

The error occurs on any setting of the server connection:
{exchangeserver:143/imap}
{exchangeserver:143/imap/ssl}
{exchangeserver:143/imap/tls}

I tried to use the imap_open() function on the Freescout box in a php script with the same result, BUT if I use 

{exchangeserver:143/imap/notls}

it just works as expected.

But I do not see how to get the "notls" parameter into the Freescout configuration, nor do I see a difference in the settings between our old Exchange 2016 and the new Exchange 2019.

Any help is appreciated.

Best regards,
Axel

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth
