### ISSUE TITLE
Reply often is created as a Draft, and emails arrive much later

### ISSUE THREAD

**Issue by amityweb** [freescout-helpdesk/freescout#215]
When replying and clicking Send, which does show an Email Sent popup, it seems it creates two copies of the message, one that looks like its sent and then a second one set to Draft. 

To send the Draft I have to click Send again.

But I notice no email gets sent anyway, it may get sent much later, but not sure. When it does send I get two copies, because of the Draft one that I clicked Send on. Now I know that gets sent too, I have to delete the second Draft message everytime we reply. 

I have set the cron to run every minute. 

About not sending right away.... I can see from running the cron on the command line, these two are executed every time:
```
sh-4.2$ php /home/freescout/public_html/artisan schedule:run
Running scheduled command: '/opt/rh/rh-php70/root/usr/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/opt/rh/rh-php70/root/usr/bin/php' 'artisan' freescout:fetch-emails > '/home/freescout/public_html/storage/logs/fetch-emails.log' 2>&1
```

But sometimes, there is a third line is executed, which when called on its own the emails all then send. So it seems this line is not being called in the cron very often? 

`'/opt/rh/rh-php70/root/usr/bin/php' 'artisan' queue:work --queue='emails,default' --sleep=5 --tries=1 > '/home/freescout/public_html/storage/logs/queue-job`

**Comment by amityweb** [comment]
The draft issue maybe related to https://github.com/freescout-helpdesk/freescout/releases/tag/1.1.4

But I have just upgraded to the latest version but still has the issue. 

The sending issue I think is probably a different issue.

**Comment by amityweb** [comment]
php artisan cache:clear doesnt seem to do anything, or clear cache in admin, still get all processes running and emails not sent on reply

**Comment by amityweb** [comment]
Restarted the server and all seems OK now!!! Working well at the moment which is great. Both drafts and email not sending issues are fixed. 

Guess there were issues with the running processes breaking it all and the restart cleared it all and its running OK now. Little bit worrying though!

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/0cb9961501cd4077e06209f40cf1bcf9da74f120

**Comment by freescout-helpdesk** [comment]
@guestisp You are always welcome to improve the solution.
