### ISSUE TITLE
Cannot set default subscriptions for Mentions module

### ISSUE THREAD

**Issue by hakwerk** [freescout-helpdesk/freescout#2155]
I installed the Mentions module, but when I try to set "I'm @mentioned in a conversation" on the Default Subscriptions For New Users part of the settings and click save, the checkboxes for that option are unset again.

Looking at the data that is POSTed to /app-settings/alerts, the names of the checkboxes are wrong: for a working option the form has
```
<input type="checkbox" checked="checked" name="settings[subscription_defaults][1][]" value="13">
```
but for these Mentions ones it is
```
<input type="checkbox" name="subscriptions[1][]" value="14">
```

Changing the notifications for an individual user works fine.

**Comment by freescout-helpdesk** [comment]
Should be fixed in the next release soon.
