### ISSUE TITLE
API List Conversations Bug

### ISSUE THREAD

**Issue by sylvia83** [freescout-helpdesk/freescout#2157]
The List Conversations parameter updatedSince does not work because it requires colons to in the timestamp, which is invalid in a url. When adding it to the GET request as a search parameter, the colons in the timestamp are automatically converted to %3A so the expected format is not received by the api.

**Comment by freescout-helpdesk** [comment]
It works fine: https://demo.freescout.net/api/conversations?api_key=c2ba609c687a3425402b9d881e5075db&updatedSince=2022-09-17%2010:06:07

**Comment by sylvia83** [comment]
Something changed because this is working perfectly now. Perhaps it was corrected when the state parameter was added. Thanks!
