### ISSUE TITLE
Mobile Notifications App can't connect (https w/cert signed by corp CA)

### ISSUE THREAD

**Issue by Rezorf** [freescout-helpdesk/freescout#2161]
NGINX server. Set up a redirect from http to https. The server certificate is issued by our root authority. Everything works fine in browsers. Under iOS, too, everything works fine (including applications and notifications), but the android application is simply silent when trying to connect. In the router logs, I see a short attempt to connect from a mobile device to port 443, but then nothing. No any errors.

Tell me which way to look. Or try connecting to our server (will send now to support@freescout.net).

My only guess is that android does not allow to upload root certificates to the trusted root certificate authorities store. But should this be a problem for the application?

**Comment by freescout-helpdesk** [comment]
We've tried to access /installer/css/fontawesome.css on your FreeScout via the browser - it hangs for some time and after that shows the Privacy error. Android mobile app also can't access it. The problem is in your server configuration.

![2022-08-17_15-48-14](https://user-images.githubusercontent.com/40499291/185135157-db572cd5-886b-44db-abff-d45f0eff21ea.png)

**Comment by Rezorf** [comment]
> s /installer/css/fontawesome.css on your FreeS

I wrote that we are still using a certificate signed by our (non-public) root authority. Windows and IOS allow you to add the certificate to the Trusted Root Centers store and this warning goes away. But Android does not allow this (we can only add a trusted CA to browser, bou not to system), and the software does not work. Thus my assumption is almost confirmed. 1. It is a pity that the software does not show any errors. 2. We would like to have a setting that allows to bypass the certificate validity check, if problem caused by this.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement this.
