### ISSUE TITLE
Snoozed Module shows tickets from all mailboxes

### ISSUE THREAD

**Issue by lieblinger** [freescout-helpdesk/freescout#2162]
We're jusing the snoozed module heavily and very happy with it. But it shows all snoozed tickets from every mailbox. 
I think there should be a filter, which only shows snoozed tickets from the selected mailbox.

**Comment by freescout-helpdesk** [comment]
Please attach a screenshot.

**Comment by lieblinger** [comment]
Can I send you a video to [support@freescout.net](mailto:support@freescout.net)?

**Comment by freescout-helpdesk** [comment]
yes

**Comment by freescout-helpdesk** [comment]
Fixed in Snoozed Module v1.0.3
