### ISSUE TITLE
Easy Digital Downloads Module - bad payment links

### ISSUE THREAD

**Issue by foliovision** [freescout-helpdesk/freescout#2163]
The EDD integration works well, we can see the payments in the "Easy Digital Downloads" box.

However every link looks like this:
> https:///wp-admin/edit.php?post_type=download&page=edd-payment-history&view=view-order-details&id=158605

There is no domain, although in the settings we have provided our-website.com/wordpress (with https:// in front of it, but that part is fixed).

It seems EddServiceProvider::getSanitizedUrl() works with `config('edd.url')` only while for example EddServiceProvider::apiGetOrders() first checks some mailbox settings before going for config('edd.key')

```
if ($mailbox && \Edd::isMailboxApiEnabled($mailbox)) {
    $settings = self::getMailboxEddSettings($mailbox);

    $url = self::getSanitizedUrl($settings['url']);
    $key = $settings['key'];
    $token = $settings['token'];
} else {
    $url = self::getSanitizedUrl(config('edd.url'));
    $key = config('edd.key');
    $token = config('edd.token');        }
```

Perhaps that's the problem as we have it configured on a per-mailbox basis.

**Comment by freescout-helpdesk** [comment]
Fixed in EDD Module v1.0.1
