### ISSUE TITLE
[Facebook Webhook] (Customer Support) User has no ID: []. Check App Logs 

### ISSUE THREAD

**Issue by BRICOBREAD** [freescout-helpdesk/freescout#2164]
We are configuring the reception of facebook messages, but it is showing this error in the log "[Facebook Webhook] (Customer Support) User has no ID: []. Check App Logs" and does not receive the messages.

**Comment by freescout-helpdesk** [comment]
It's hard to tell what can be the reason. You may need to debug it yourself.
