### ISSUE TITLE
API Module: list conversations number of records (bug?)

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2166]
Hello,

According to https://api-docs.freescout.net/#list-conversations. there is very small limit of records which can be returned. The limit can not be changed for now ("Page number. Default is 50 (can't be changed)").

If you set any value except empty or `1`, nothing will be returned.
So, how to pass custom value of `page` to API? If I change `const PAGE_SIZE = 50;` to `const PAGE_SIZE = 10000;`, it would work fine and return more than 50 results.

**Comment by freescout-helpdesk** [comment]
`pageSize` parameter has been added in API & Webhooks Module v1.0.43
