### ISSUE TITLE
New action for conversation view

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2167]
Hello,

Please add a new action to show content in modules between customer information and previous customer conversations.

File `resources/views/conversations/view.blade.php`, before line 280:
```
@action('conversation.before_prev_convs', $customer, $conversation, $mailbox)
```

In the case we can display some information about customer in full width.  There is an action `customer.profile_data`, but its width is not 100% of block content, less than previous conversations block width.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a pull request.
