### ISSUE TITLE
Problem with FreeScout behind Apache ReverseProxy with SSL - login form still pointing to http://

### ISSUE THREAD

**Issue by websafe** [freescout-helpdesk/freescout#2168]
Hello,

I have FreeScout (latest, ubuntu 22.04, installed via `ubuntu.sh`) on a local machine (IP: 192.168.99.152) behind a public facing Reverse Proxy on Apache. 

```
[User]---(https)---{internet}---[Apache Reverse Proxy]---{LAN}---(http)---[FreeScout]
```

My Apache config look like this:

```
<VirtualHost *:80>
    ServerName support.contoso.com
    Redirect "/" "https://support.contoso.com/"
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/httpd/ssl/certs/wildcard.contoso.com.cert
    SSLCertificateKeyFile /etc/httpd/ssl/private/wildcard.contoso.com.key
    SSLCACertificateFile /etc/httpd/ssl/certs/wildcard.contoso.com.cacert
    SSLProxyEngine on
    SSLProxyCheckPeerName off
    ServerName support.contoso.com
    ProxyPreserveHost On
    ProxyPass "/" "http://192.168.99.152/" nocanon
    ProxyPassReverse "/" "http://192.168.99.152/"
    AllowEncodedSlashes NoDecode
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerExpire off
</VirtualHost>
```

and this works with other software, but somehow with FreeScout not really.

Freescout is configured without SSL.

When `.env` contains:

```
APP_URL=http://192.168.99.152
APP_FORCE_HTTPS=false
```

and the cache was cleared via `tools.php`, my http://192.168.99.152/login login screen looks normal, but when I try to connect via the Reverse Proxy on https://support.contoso.com/ my login screen looks like this:

![image](https://user-images.githubusercontent.com/412013/185657201-e89cdd65-2328-4333-a1ed-edc5ee1444c5.png)

which is caused by styles and images being tried to load from http://192.168.99.152 instead via the ReverseProxy at https://support.contoso.com/.

When I leave my Apache (Reverse Proxy) config as shown above but tweak the `.env` file like this:

```
APP_URL=https://support.contoso.com
```

after clearing the cache via `tools.php` my https://support.contoso.com/login screen looks pretty normal, but is not really working, because:

1. The login form somehow still points to `http` instead of `https` as defined in `.env`: `<form class="form-horizontal margin-top" method="POST" action="http://support.contoso.com/login">`
2. The `banner.png` image is still being loaded from `http` instead of `https`: `<img alt="" title="" src="http://support.contoso.com/img/banner.png" height="36"/>`
3. But CSS and JavaScript is correctly being loaded via `https`: `<link href="https://support.constoso.com/css/builds/9c801d2c5a81fc6df1dd460ffadbc4b316609094056.css" rel="stylesheet">` and `<script src="https://support.contoso.com/js/builds/4f2a7b54a1baa78160295af0910a84c049827330465.js">`

I'm not sure why some url's contain the scheme and some don't, why some url's contain the domain part and some url's don't (`<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">`, `<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">` ).

Is there a solution for my problem?

Setting `APP_FORCE_HTTPS=false` in `.env` makes no sense, because this creates endless redirect loops.

Maybe this needs some fixing in:

`resources/views/auth/login.blade.php`:
```php
<form class="form-horizontal margin-top" method="POST" action="{{ route('login') }}">
```

and

`resources/views/auth/banner.blade.php`:
```php
<img alt="" title="" src="@filter('login.banner', asset('img/banner.png'))" height="36"/>
```

or some other places?

**Comment by websafe** [comment]
**Update**

I have found a **temporary** solution by enabling `mod_deflate` and `mod_substitute` in Apache and then tweaking the ReverseProxy config by adding the Substitute section. My Apache config for this vhost on the reverse proxy has now the following configuration:

```
<VirtualHost *:80>
    ServerName support.contoso.com
    Redirect "/" "https://support.contoso.com/"
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/httpd/ssl/certs/wildcard.contoso.com.cert
    SSLCertificateKeyFile /etc/httpd/ssl/private/wildcard.contoso.com.key
    SSLCACertificateFile /etc/httpd/ssl/certs/wildcard.contoso.com.cacert

    SSLProxyEngine on
    SSLProxyCheckPeerName off
    ServerName support.contoso.com
    ProxyPreserveHost On
    ProxyPass "/" "http://192.168.99.152/"
    ProxyPassReverse "/" "http://192.168.99.152/"

    # THE TEMPORARY FIX STARTS HERE
    AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE text/html
    Substitute "s|http://support.contoso.com|https://support.contoso.com|ni"
    # THE TEMPORARY FIX ENDS HERE    

    AllowEncodedSlashes NoDecode
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerExpire off
</VirtualHost>
```

But I'm aware this is not the desired solution.

**Comment by websafe** [comment]
This problem was fixed by enabling SSL also on directly on the FreeScout Nginx, which shouldn't be required.

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution.

**Comment by Icosa-Consulting** [comment]
I don't see how replacing one URL for the other (HTTPS for HTTP) in a custom reverse proxy is a fix when clearly the application is emitting the wrong URL's in the first place. A proper fix would be for the application to emit correct URL's depending on the user setup of HTTPS vs HTTP. I know my browser claims the mixed content as a security risk.

The login form somehow still points to http instead of https as defined in .env: <form class="form-horizontal margin-top" method="POST" action="http://support.contoso.com/login">
The banner.png image is still being loaded from http instead of https: <img alt="" title="" src="http://support.contoso.com/img/banner.png" height="36"/>
But CSS and JavaScript is correctly being loaded via https: <link href="https://support.constoso.com/css/builds/9c801d2c5a81fc6df1dd460ffadbc4b316609094056.css" rel="stylesheet"> and <script src="https://support.contoso.com/js/builds/4f2a7b54a1baa78160295af0910a84c049827330465.js">
