### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#217]
Hi,
thank you for your work!

Is it planned to add "phone conversation"?

Best Regards
Filippo

**Comment by inrobin** [comment]
Yes. In future it will be implemented.

**Comment by freescout-helpdesk** [comment]
Yes. In future it will be implemented.

**Comment by Filoz** [comment]
Hi, 
thank you for your reply!

It would be really interesting to add multiple sources like Facebook Messenger (really useful for pages), etc.
Maybe it can be an idea for a module

**Comment by freescout-helpdesk** [comment]
Implemented.
