### ISSUE TITLE
Microsoft365 AADSTS50011: The redirect URI 'http://... does not match the redirect URIs configured for the application

### ISSUE THREAD

**Issue by websafe** [freescout-helpdesk/freescout#2170]
This is probably somehow connected to #2168 

I'm running FreeScout on a local server (http://192.168.99.152, no HTTPS) and I'm accessing it via a public accessible Apache configured as a reverse proxy with SSL. More details in #2168 

My `.env` contains:

```
# Application URL
APP_URL=https://support.contoso.com

# Use HTTP protocol and redirect to HTTPS
APP_FORCE_HTTPS=false
```

I'm trying to configure a Microsoft365 shared mailbox as described here: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth

I have prepared everything on the Azure Active Directory side, I've setup the redirect url there to `https://support.contoso.com/mailbox/oauth` (note HTTPS)

And I'm getting the following error:

> AADSTS50011: The redirect URI 'http://support.contoso.com/mailbox/oauth' specified in the request does not match the redirect URIs configured for the application '********-****-****-****-************'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Please note the `http://` in this error message shown by Microsoft365.

`APP_URL`  is set in `.env` to `https://support.contoso.com` (HTTPS) but FreeScout somehow sends a redirect url without HTTPS in the request.

I've setup https:// in Azure but FreeScout uses http:// in the authorization request...

Is there a way to fix this?

**Comment by websafe** [comment]
**Update**

I have modified a bit `app/Misc/Mail.php` by hardcoding the value for `redirect_uri`:

```php
   public static function oauthGetAuthorizationUrl($provider_code, $params)
    {
        $args = [];

        switch ($provider_code) {
            case self::OAUTH_PROVIDER_MICROSOFT:
                // https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth
                $args = [
                    'scope' => 'offline_access https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send',
                    'response_type' => 'code',
                    'approval_prompt' => 'auto',
                    /*'redirect_uri' => route('mailboxes.oauth_callback'),*/
                    'redirect_uri' => 'https://support.contoso.com/mailbox/oauth',
                ];
                $args = array_merge($args, $params);
                $url = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?'.http_build_query($args);
                break;
        }

        return $url;
    }
```

and now I'm getting another error, which is strange:

> Error occurred: {"error":"invalid_client","error_description":"AADSTS500112: The reply address 'https://support.contoso.com/mailbox/oauth' does not match the reply address 'https://support.contoso.com/mailbox/oauth' provided when requesting Authorization code.\r\nTrace ID: 7a43127a-8621-4474-bb77-d533c71f1900\r\nCorrelation ID: 8ebc0fe8-f379-43eb-ba3b-280fb713e813\r\nTimestamp: 2022-08-19 20:27:00Z","error_codes":[500112],"timestamp":"2022-08-19 20:27:00Z","trace_id":"7a43127a-8621-4474-bb77-d533c71f1900","correlation_id":"8ebc0fe8-f379-43eb-ba3b-280fb713e813"}

because it's saying:

> The reply address ... does not match the reply address ...

and both are exactly the same:

+ `https://support.contoso.com/mailbox/oauth`
+ `https://support.contoso.com/mailbox/oauth`

**Comment by websafe** [comment]
This problem was fixed by enabling SSL also on directly on the FreeScout Nginx, which shouldn't be required.

**Comment by freescout-helpdesk** [comment]
Good to know.
