### ISSUE TITLE
Connect FreeScout to Microsoft 365 Exchange via OAuth - How to connect to a shared mailbox and how to get subfolders?

### ISSUE THREAD

**Issue by websafe** [freescout-helpdesk/freescout#2171]
I followed the instructions on https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth but I don't know how tell FreeScout to fetch emails from a shared mailbox. I see my emails but not those in the shared mailbox I have access to. Is it even possible to connect to a shared mailbox?

Also when I do "Get folders" in "Connection settings" > "IMAP folders" I don't see INBOX subfolders. Is it possible to access these subfolders?

**Comment by pool-alpin** [comment]
@websafe I had to apply a Business Basic license to the shared mailbox to get it running.

**Comment by freescout-helpdesk** [comment]
> @websafe I had to apply a Business Basic license to the shared mailbox to get it running. And obviously log in as the shared mailbox user.

Thanks. This has been added to the https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth
