### ISSUE TITLE
Cron job fetching only UNREAD messages?

### ISSUE THREAD

**Issue by websafe** [freescout-helpdesk/freescout#2172]
Is the default cron job `php /var/www/freescout/artisan schedule:run` fetching only UNREAD messages?

Can we tell FreeScout to fetch also SEEN messages?

I have found Manage - > Tools -> Fetch emails ->All, but this seems to be a one-time manual Fetch...

**Comment by ilyakonovalenko** [comment]
https://freescout.shop/downloads/freescout-module-fetch-seen/

There is a free module for this.
