### ISSUE TITLE
Filesystem with Digital Ocean spaces or S3

### ISSUE THREAD

**Issue by rapsli** [freescout-helpdesk/freescout#2173]
Unfortunately the documentation here is not very clear. First of all it will not work with PHP > 8 So I have downgraded to PHP 7.4.

Installing the required package:

`composer require league/flysystem-aws-s3-v3 ~1.0`

I haved added the S3 and DO credentials to the .envfile for either S3 or DO spaces. It was never running. It was sometimes uploading vars.js to either S3 or DO, but that was about it. I could never get it to upload the actual attachments. 

What is not quite clear:
- Are there any changes required in conf/filesystems.php? I have added a DO disk similar to the s3 disk, to test out the DO configuration, but unfortunately with no success. When changing the FILESYSTEM_DRIVER from local to s3 I get the following error: 

```
During inheritance of Countable: Uncaught ErrorException: Return type of Aws\HandlerList::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
in /home/runcloud/webapps/freescout/vendor/aws/aws-sdk-php/src/HandlerList.php:308
```

Do I have to remove any files from storage in order for S3 to work?

**Comment by freescout-helpdesk** [comment]
It looks like the package you are using is not compatible with PHP 8.1

**Comment by rapsli** [comment]
yes I agree, that's why I have downgraded to PHP 7.4... but even so it's not working

**Comment by rapsli** [comment]
A quick update. I can now upload files again: the URL points to the file on AWS, but the file is actually uploaded to the local storage (/storage/app/attachment) and nothing arrives at AWS. Clicking on the file will lead to a broken link. 

![image](https://user-images.githubusercontent.com/366040/185944873-32fb3dc6-ba51-441d-8d1f-757189877618.png)

**Comment by freescout-helpdesk** [comment]
We've never tried this ourselves. We'll leave this issue as `help wanted`. Maybe someone will help.

**Comment by rapsli** [comment]
any news here? Just tried to setup another instance... not having to worry about storage for attachments would make life a lot easier!

**Comment by rapsli** [comment]
Got it running. Here is what I had to change. This is now obviously hardcoded I would assume, it will need some more love, but I'm not familiar at all with Laravel, so hopefully someone smarter than me with a more oversights can get this into a generic form.


diff --git a/app/Attachment.php b/app/Attachment.php
index 2fc5d687..5a555341 100644
--- a/app/Attachment.php
+++ b/app/Attachment.php
@@ -19,7 +19,7 @@ class Attachment extends Model

     const DIRECTORY = 'attachment';

-    CONST DISK = 'private';
+    CONST DISK = 's3';

     // https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Attachment.php
     public static $types = [
@@ -231,7 +231,9 @@ class Attachment extends Model
      */
     public function url()
     {
-        return Storage::url($this->getStorageFilePath()).'?id='.$this->id.'&token='.$this->getToken();
+
+       return Storage::disk('s3')->temporaryUrl($this->getStorageFilePath(), now()->addMinutes(30));
+        //return Storage::url($this->getStorageFilePath()).'?id='.$this->id.'&token='.$this->getToken();
     }

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution.

**Comment by EllisonTravel** [comment]
Hi @rapsli  how did you install the packages and make it work? 
I tried with both PHP versions, I tried to follow the instructions here: https://github.com/freescout-help-desk/freescout/issues/4439#issuecomment-2558904199
but I am getting stuck.  @freescout-helpdesk  requires old packages, AWS seems to require an update. So, I am stuck. 
@freescout-helpdesk , is there a plan for a next release and framework update? 
thanks

**Comment by EllisonTravel** [comment]
now, I am getting this error: php test-spaces.php 
Testing DigitalOcean Spaces with Flysystem S3 Adapter
-----------------------------------------------------
FILESYSTEM_DRIVER: s3
Attempting to upload a file...
ERROR: Error executing "PutObject" on "https://zzzzzzz.digitaloceanspaces.com/zzzzzz/test-file-1743042022.txt"; AWS HTTP error: Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/pull/5603
