### ISSUE TITLE
Workflow Module : Email not sent to client when conversation is phone type

### ISSUE THREAD

**Issue by t3cneo** [freescout-helpdesk/freescout#2174]
Hi 

Fresh install of freescout here with just the workflow module enabled, we're trying to send a known client an email when logging a ticket via phone call

Even with a manual workflow email is not sent to client if conversation type is set to phone 

Logs don't show any errors...

We're obviously trying this workflow on a conversation linked to a known client whose profile has an email address.

Is it the expected behaviour?

**Comment by freescout-helpdesk** [comment]
Yes, emails are not sent to clients for phone conversations.
