### ISSUE TITLE
Note format in Knowledge Base module documentation

### ISSUE THREAD

**Issue by JohnDuff44** [freescout-helpdesk/freescout#2175]
Hello,

Can someone tell me how to format a text as a note (like in the screenshot below which is in the [documentation](https://freescout.net/module/knowledge-base/)).
![image](https://user-images.githubusercontent.com/32732842/186099754-47107374-e00d-4ff5-80d3-04bd38a4cfb0.png)

Thanks!

**Comment by freescout-helpdesk** [comment]
Try to copy-paste this note from demo article to the article in your FreeScout.

**Comment by JohnDuff44** [comment]
Demo article doesn't seem to exist anymore, can't find the "Note: blablabla" text

**Comment by t3cneo** [comment]
You can copy/paste from the [live demo here](https://demo.freescout.net/en/hc/1321731726/1?category_id=1)

**Comment by JohnDuff44** [comment]
> You can copy/paste from the [live demo here](https://demo.freescout.net/en/hc/1321731726/1?category_id=1) or any other website using inline css (couldn't find any out of my mind right now...)

There is not "Note:" text anymore in that demo website. That was what I was saying in ma previous message.
Thanks for the other trick
