### ISSUE TITLE
Mimic Helpscout ticketing auto replies function

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2178]
Hello,

I've recently experimented with the workflows module and I want to make it so:

If the ticket is submitted inside office hours: An email "We received your ticket" is sent
If the ticket is submitted outside office hours: The out-of-office message by the module triggers, however, the "We received your message" from the previous flow, should not be sent.

How can I do this?

Best, Matic

**Comment by ilyakonovalenko** [comment]
The module currently missed very useful condition "created between" to trigger if conversation created/updated between A and B hours. Hopefully it will be added by FreeScout team.

**Comment by TitanBlast** [comment]
> The module currently missed very useful condition "created between" to trigger if a conversation created/updated between A and B hours. Hopefully it will be added by FreeScout team.

I see. Rather unfortunate. Do you think that is something that we can add by modifying the module?

**Comment by ilyakonovalenko** [comment]
Yes, custom conditions can be added to workflows module via another modules. See custom fields module source code as an example, it is implemented there for both conditions and actions.

**Comment by maticboncina** [comment]
Thank you 👍

**Comment by ilyakonovalenko** [comment]
> Thank you 👍

Feel free to share you additions. It would be really appreciated! You can also send files to FreeScout to include in Workflows Module :-)

**Comment by maticboncina** [comment]
I will likely do that if I am successful at adding the functionality :)
