### ISSUE TITLE
Noreply Module - Freescout sending Auto-Reply to custom Noreply-Adress

### ISSUE THREAD

**Issue by SeFoer** [freescout-helpdesk/freescout#2179]
Hi,
we are using the Noreply Module for not sending auto-replies to an other Helpdesk (otherwise they Would play Auto-Reply-Ping-Pong).
As the Mail-Adress of the other Helpdesk changes with every new ticket (Ticket-ID is in the Mail-Adress) we use * to face the changing adress (see Image). The Problem with this is, that it is not working. Freescout is still sending auto replies to the helpdesk. Any ideas to solve this issue? (The amount of * equals the amount of numbers in the Mail-Adress)
![image](https://user-images.githubusercontent.com/112385555/187168179-b26f7327-b968-43f5-8631-c33f24d0a843.png)

Thankyou so much for your help.

Sebastian

**Comment by freescout-helpdesk** [comment]
Fixed in Noreply Emails Module v1.0.2
