### ISSUE TITLE
Keep current status on reply

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2180]
I would like to add an option to keep current status on reply.

@freescout-helpdesk, don't you mind if I made changes and create pull request?

**Comment by freescout-helpdesk** [comment]
Where would you like to add it?

**Comment by ilyakonovalenko** [comment]
I would like to add additional mailbox default status setting value ("Keep current" in addition to Active, Pending, Closed) and improve "if" conditions in reply form view to make both current behavior and new addition work. 

I believe such addition would be really helpful as some use cases do not require a status change on reply. Selecting status manually on reply is not always good.

**Comment by freescout-helpdesk** [comment]
ok
