### ISSUE TITLE
Send mail

### ISSUE THREAD

**Issue by Mathie01** [freescout-helpdesk/freescout#2181]
Hello !

I have a form on my website that sends an email to the support address. In my code, I send it from Sendgrid and in from, I indicate the email address of the user.

This is good, but is it the right way to do it?
I say that the email is sent from the user's email address, so sometimes it arrives in spam and is not displayed on Freescoot.

If I indicate that the mail is sent from a verified address, a domain of mine, on the ticket I don't have the name, first name and address of the person

How can I do it? 

Thank you for your help!

**Comment by freescout-helpdesk** [comment]
> I say that the email is sent from the user's email address, so sometimes it arrives in spam and is not displayed on Freescoot.

You should send an email from some noreply@yourwebiste.com address and put user's email address in Reply-To header.
