### ISSUE TITLE
Ticket Number Module doesnt seem to do anything when activated

### ISSUE THREAD

**Issue by pbolcar** [freescout-helpdesk/freescout#2183]
Hey, I activated the Ticket Number Module and the activation looks successful, but none of my new test e-mails are showing the ticket numbers in the subject line of the emails. Am I missing a simple activation step to have this module function as expected?

**Comment by t3cneo** [comment]
You have to provide your desired settings in the .env file (located in /var/www/html/ if you followed the installation guide in the wiki)

Then you need to clear the app cache

From the webapp : 
Go to Manage » System » Tools and click Clear Cache

From CLI : 
`cd /var/www/html`
`php artisan freescout:clear-cache`

**Comment by pbolcar** [comment]
Thanks!
