### ISSUE TITLE
Hide inbox emails from FreeScout users

### ISSUE THREAD

**Issue by SecteurA** [freescout-helpdesk/freescout#2185]
Hello,

i just installed FreeScout and I need to hide emails from users so they can see only assigned to them, how can I do this ? 

Thanks

**Comment by SecteurA** [comment]
Please help !

**Comment by ilyakonovalenko** [comment]
That is impossible. You can probably try to implement it via modules.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
