### ISSUE TITLE
Content-Type: text/html + Content-Transfer-Encoding: binary results in base64 encoded thread body

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2186]
Hi, recently we had a rar case where we recieved a message and freescout showed its content as a base64 encoded string. I took a look into the original email and noted that the encoding was set to binary. I did abit of research and found a _decodeString_ function https://github.com/freescout-helpdesk/freescout/blob/87dfcb8ed03eac7009bd7ccda8c05eca74e18e1d/overrides/webklex/laravel-imap/src/IMAP/Message.php#L802  which seems to cause this with the call of _imap_binary_. Is this actually a bug or is this expected since the encoding given by the email seems incorrect?

Part from the email

```
--_----------=_166199973716851143
Content-Disposition: inline
Content-Length: 8462
Content-Transfer-Encoding: binary
Content-Type: text/html; charset=utf-8
MIME-Version: 1.0
X-Mailer: MIME::Lite 3.030 (F2.85; A2.13; B3.14; Q3.13)
Date: Thu, 1 Sep 2022 04:35:37 +0200

<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

**Comment by freescout-helpdesk** [comment]
It does looks like it should look like this:
```
return imap_base64(imap_binary($string));
```
