### ISSUE TITLE
information about functions availability in hosting service

### ISSUE THREAD

**Issue by arily** [freescout-helpdesk/freescout#2187]
some functions must not be disabled in order for the freescout to work. Unfortunately some hosting service disabled some of the std function by default.

## web installer
some functions I found disabled by default and won't get any error message:
- putenv()
- symlink()

## install module
`proc_open`  is required to install a module

it would be great to have this piece of information in the installation guide.

**Comment by freescout-helpdesk** [comment]
`proc_open` function is already checked in Manage > System > Status
