### ISSUE TITLE
Sat. Ratings Module: Do not add rating in email for the first message

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2190]
1) Please consider to implement an ability to skip rating box in the first message email if created by user.
Use case: first message can be some kind of notifications link emergency work notification, such messages are not supposed to be rated in some cases.

2) It would be also nice if there will be an option to set users skip list, so that rating box won't be added for users like workflows and custom bot users.
Use case: workflows bot and other bots usually send automatic messages which are not supposed to be rated.

Thank you.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
