### ISSUE TITLE
REQ - Internal Email or MEMO

### ISSUE THREAD

**Issue by ninpartners** [freescout-helpdesk/freescout#2192]
Hi, I think it would be great to have the option as an administrator to send a mass email to all mailboxes instead of having to put in each address manually.

In what case would this be used? When the administrator needs to send a global communication to all mailboxes or users in the system.

It would also be great to have the option to leave some email highlighted in yellow at the top so that all users can notice it.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
