### ISSUE TITLE
SMTP outgoing mail not working

### ISSUE THREAD

**Issue by LexacleTechnologies** [freescout-helpdesk/freescout#2193]
When sending a new mail status message is Email sent. No email arrives at the receiver's inbox, spam or promotions. However, when testing the outgoing mail settings, everything works out fine. How do I go about this?

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. You need to debug it yourself.

**Comment by webdados** [comment]
I'm also getting the same problem:
* Using Gmail (Workspace) SMTP
* Test email is sent, stored in Gmail Sent folder, and received by the recipient
* Regular email sent by any user in Frescout is apparently sent, NOT stored in Gmail Sent folder and not received by the recipient

Seems like something that can only be debugged on Freescout side, as it's not stored on Gmail Sent folder at all.
