### ISSUE TITLE
Test Freecout k8s Helm chart

### ISSUE THREAD

**Issue by zzorica** [freescout-helpdesk/freescout#2194]
Hi!

I've been using Freescout via helm chart in my k8s cluster for a while so if anyone wants to try it out here it is https://github.com/zzorica/helm-charts/tree/main/charts/freescout

It is using [tiredofit/freescout](https://github.com/tiredofit/docker-freescout) image ofc so I didn't do much actually :relaxed:

**Comment by freescout-helpdesk** [comment]
Thanks. We've added it here https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#images--one-click-installs
