### ISSUE TITLE
Folders permissions

### ISSUE THREAD

**Issue by 3wwwgr** [freescout-helpdesk/freescout#2195]
hi,

is there any folder permission module?
e.x can i hide Unassigned folder from a group of users?

what we want to achieve
we have 3 departments inside a mailbox separated by custom folders
no department must have access to unassigned folder. a department must have access only to the representative custom folder 

lastly, only one 4th department must have access to unassigned folder so can move the tickets to the the custom folders

thanks

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
