### ISSUE TITLE
Different path to PHP not respected in crontab > scheduled tasks.

### ISSUE THREAD

**Issue by bazizsafi** [freescout-helpdesk/freescout#2196]
Hi,

on our web hoster we need to use a different path to PHP to select the correct PHP version. Instead of `/usr/bin/php` we need to use `/usr/bin/php8.0`.
No big deal, this is covered in the installation guide at https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs.

However, setting this path to PHP in the crontab does not change the path to PHP _of the scheduled tasks_:

This is the crontab with the desired path to PHP:
```
* * * * * /usr/bin/php8.0 /path/to/freescout/installation/artisan schedule:run >> /dev/null 2>&1
```

When I run this command manually, it reveals that the scheduled tasks use the default path to PHP `'/usr/bin/php'`:
```
$ /usr/bin/php8.0 /path/to/freescout/installation/artisan schedule:run
Running scheduled command: '/usr/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php' 'artisan' freescout:fetch-emails > '/path/to/freescout/installation/storage/logs/fetch-emails.log' 2>&1
Running scheduled command: '/usr/bin/php' 'artisan' queue:work --queue='emails,default,1e0dfc970c9f3c1aca93f5554779bc52' --sleep=5 --tries=1 > '/path/to/freescout/installation/storage/logs/queue-jobs.log' 2>&1
Content-type: text/html; charset=UTF-8

$
```

How do I make the scheduled tasks also use our desired path to PHP?

**Comment by freescout-helpdesk** [comment]
Good question. We don't know yet.

**Comment by freescout-helpdesk** [comment]
It looks like there is no some good way. The only way is to hardcode the path to your PHP like this: https://stackoverflow.com/a/45962045

**Comment by bazizsafi** [comment]
Closed as completed, hm? You guys are quick! ;-)

Well, I concur this is not really a FreeScout issue, but rather a [Symfony](https://github.com/symfony/symfony) issue. [This Stackoverflow question](https://stackoverflow.com/questions/37192234/laravel-artisan-php-version-error-in-1and1-server) lead me onto the right path. Obviously PhpExecutableFinder has trouble identifying the current PHP process in [PhpExecutableFinder.php:57](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Process/PhpExecutableFinder.php#L57) when called from a crontab environment.

I fixed the problem by defining `PHP_PATH` in the crontab environment using the following crontab command:
```
* * * * * export PHP_PATH=/usr/bin/php8.0; $PHP_PATH /path/to/freescout/installation/artisan schedule:run >> /dev/null 2>&1
```

You might want to include this approach (or something more elegant) in your documentation to help all those FreeScout users on shared/hosted webspace.

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution. Added to https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

**Comment by bazizsafi** [comment]
You're welcome, I have to thank **you** for this awesome software!!

One tiny remark regarding the [Installation Guide](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs):
In the example, you're using `/usr/local/bin/php-8.0` on the one hand and `/usr/bin/php8.0` on the other hand.
I mean, you _could_ use different paths at those different places and people will still figure it out, I guess, but it's inconsistent and might confuse less technically-skilled users.
