### ISSUE TITLE
Fetch all mail from a large inbox

### ISSUE THREAD

**Issue by poiNt3D** [freescout-helpdesk/freescout#2198]
Hello.
We would like to switch our workflow from Gmail to Freescout, if it's possible to migrate our data.
Inbox size is aprox. 6GB, it has over 6000 threads.
Freescout fetches around 200 emails and stops. When i try manual fetching and provide a period of 999 days, it shows timeout after some time.
Is there a possibility to make this process run in steps, downloading some part of inbox each time? Maybe it's possible to run it in command line? Most e-mail clients do this task ok, even if they have to connect multiple times.

**Comment by MarcoWel** [comment]
Related issue #1936

**Comment by poiNt3D** [comment]
Ok,
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 339968 bytes) in /www/html/vendor/webklex/laravel-imap/src/IMAP/Attachment.php on line 138
`
does that mean i have to give it as much free RAM as my inbox size is?

**Comment by poiNt3D** [comment]
Ok, this works 
`public function fetch($mailbox)
    {
        $no_charset = false;

        $client = \MailHelper::getMailboxClient($mailbox);

        // Connect to the Server
        $client->connect();

        $folders = [];

        // Fetch emails from custom IMAP folders.
        //if ($mailbox->in_protocol == Mailbox::IN_PROTOCOL_IMAP) {
        $imap_folders = $mailbox->getInImapFolders();

        foreach ($imap_folders as $folder_name) {
            $folder = null;
            try {
                $folder = $client->getFolder($folder_name);
            } catch (\Exception $e) {
                // Just log error and continue.
                $this->error('['.date('Y-m-d H:i:s').'] Could not get mailbox IMAP folder: '.$folder_name);
            }

            if ($folder) {
                $folders[] = $folder;
            }
        }
        // try {
        //     //$folders = $client->getFolders();
        // } catch (\Exception $e) {
        //     // Do nothing
        // }

        $unseen = \Eventy::filter('fetch_emails.unseen', $this->option('unseen'), $mailbox);
        if ($unseen != $this->option('unseen')) {
            $this->line('['.date('Y-m-d H:i:s').'] Fetching: '.($unseen ? 'UNREAD' : 'ALL'));
        }

        foreach ($folders as $folder) {
            $this->line('['.date('Y-m-d H:i:s').'] Folder: '.$folder->name);

            // Get unseen messages for a period
            $last_error = '';
            $messages = collect([]);
			//$messages_count = $folder->examine()["exists"];
			//Mail module needs an update
			$messages_count = $this->option('messages');
			$this->line('Messages in folder: ' . $messages_count);
			for ($i = 0; $i <= intdiv($messages_count, $this->option('chunksize')+1); $i++)  {
				try {    
					$messages_query = $folder->query()->since(now()->subDays($i))->leaveUnread();
					if ($unseen) {
						$messages_query->unseen();
					}
					if ($no_charset) {
						$messages_query->setCharset(null);
					}
					if ($this->option('chunksize') > 0) {
						$messages_query->limit($limit = $this->option('chunksize'), $page = $i);
					}
					$messages = $messages_query->get();

					if (method_exists($client, 'getLastError')) {
						$last_error = $client->getLastError();
					}
				} catch (\Exception $e) {
					$last_error = $e->getMessage();
				}

				if ($last_error && stristr($last_error, 'The specified charset is not supported')) {
					$this->line('Fixing charset');
					$errors_count = count($client->getErrors());
					// Solution for MS mailboxes.
					// https://github.com/freescout-helpdesk/freescout/issues/176
					$messages_query = $folder->query()->since(now()->subDays($i))->leaveUnread()->setCharset(null);
					if ($unseen) {
						$messages_query->unseen();
					}
					if ($this->option('chunksize') > 0) {
						$messages_query->limit($limit = $this->option('chunksize'), $page = $i);
					}
					$messages = $messages_query->get();

					$no_charset = true;
					if (count($client->getErrors()) > $errors_count) {
						$last_error = $client->getLastError();
					} else {
						$last_error = null;
					}
				}

				if ($last_error && !\Str::startsWith($last_error, 'Mailbox is empty')) {
					// Throw exception for INBOX only
					if ($folder->name == 'INBOX' && !$messages) {
						throw new \Exception($last_error, 1);
					} else {
						$this->error('['.date('Y-m-d H:i:s').'] '.$last_error);
						$this->logError('Folder: '.$folder->name.'; Error: '.$last_error);
					}
				}

				//$this->line('['.date('Y-m-d H:i:s').'] Page' . $i . ' out of ' . intdiv($messages_count, $this->option('chunksize')+1) . ', Fetched: '.count($messages));

				$message_index = 1;

				// We have to sort messages manually, as they can be in non-chronological order
				$messages = $this->sortMessage($messages);
				foreach ($messages as $message_id => $message) {
					$this->line('['.date('Y-m-d H:i:s').'] '.$message_index.') '.$message->getSubject());
					$message_index++;

					$this->processMessage($message, $message_id, $mailbox, $this->mailboxes);
				}
			}	
        }

        $client->disconnect();
    }`

**Comment by poiNt3D** [comment]
Ok, this works:
```
public function fetch($mailbox)
    {
        $no_charset = false;

        $client = \MailHelper::getMailboxClient($mailbox);

        // Connect to the Server
        $client->connect();

        $folders = [];

        // Fetch emails from custom IMAP folders.
        //if ($mailbox->in_protocol == Mailbox::IN_PROTOCOL_IMAP) {
        $imap_folders = $mailbox->getInImapFolders();

        foreach ($imap_folders as $folder_name) {
            $folder = null;
            try {
                $folder = $client->getFolder($folder_name);
            } catch (\Exception $e) {
                // Just log error and continue.
                $this->error('['.date('Y-m-d H:i:s').'] Could not get mailbox IMAP folder: '.$folder_name);
            }

            if ($folder) {
                $folders[] = $folder;
            }
        }
        // try {
        //     //$folders = $client->getFolders();
        // } catch (\Exception $e) {
        //     // Do nothing
        // }

        $unseen = \Eventy::filter('fetch_emails.unseen', $this->option('unseen'), $mailbox);
        if ($unseen != $this->option('unseen')) {
            $this->line('['.date('Y-m-d H:i:s').'] Fetching: '.($unseen ? 'UNREAD' : 'ALL'));
        }

        foreach ($folders as $folder) {
            $this->line('['.date('Y-m-d H:i:s').'] Folder: '.$folder->name);

            // Get unseen messages for a period
            $last_error = '';
            $messages = collect([]);
			//$messages_count = $folder->examine()["exists"];
			//Mail module needs an update
			$messages_count = $this->option('messages');
			$this->line('Messages in folder: ' . $messages_count);
			for ($i = 0; $i <= intdiv($messages_count, $this->option('chunksize')+1); $i++)  {
				try {    
					$messages_query = $folder->query()->since(now()->subDays($i))->leaveUnread();
					if ($unseen) {
						$messages_query->unseen();
					}
					if ($no_charset) {
						$messages_query->setCharset(null);
					}
					if ($this->option('chunksize') > 0) {
						$messages_query->limit($limit = $this->option('chunksize'), $page = $i);
					}
					$messages = $messages_query->get();

					if (method_exists($client, 'getLastError')) {
						$last_error = $client->getLastError();
					}
				} catch (\Exception $e) {
					$last_error = $e->getMessage();
				}

				if ($last_error && stristr($last_error, 'The specified charset is not supported')) {
					$this->line('Fixing charset');
					$errors_count = count($client->getErrors());
					// Solution for MS mailboxes.
					// https://github.com/freescout-helpdesk/freescout/issues/176
					$messages_query = $folder->query()->since(now()->subDays($i))->leaveUnread()->setCharset(null);
					if ($unseen) {
						$messages_query->unseen();
					}
					if ($this->option('chunksize') > 0) {
						$messages_query->limit($limit = $this->option('chunksize'), $page = $i);
					}
					$messages = $messages_query->get();

					$no_charset = true;
					if (count($client->getErrors()) > $errors_count) {
						$last_error = $client->getLastError();
					} else {
						$last_error = null;
					}
				}

				if ($last_error && !\Str::startsWith($last_error, 'Mailbox is empty')) {
					// Throw exception for INBOX only
					if ($folder->name == 'INBOX' && !$messages) {
						throw new \Exception($last_error, 1);
					} else {
						$this->error('['.date('Y-m-d H:i:s').'] '.$last_error);
						$this->logError('Folder: '.$folder->name.'; Error: '.$last_error);
					}
				}

				//$this->line('['.date('Y-m-d H:i:s').'] Page' . $i . ' out of ' . intdiv($messages_count, $this->option('chunksize')+1) . ', Fetched: '.count($messages));

				$message_index = 1;

				// We have to sort messages manually, as they can be in non-chronological order
				$messages = $this->sortMessage($messages);
				foreach ($messages as $message_id => $message) {
					$this->line('['.date('Y-m-d H:i:s').'] '.$message_index.') '.$message->getSubject());
					$message_index++;

					$this->processMessage($message, $message_id, $mailbox, $this->mailboxes);
				}
			}	
        }

        $client->disconnect();
    }
```

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution.

**Comment by freescout-helpdesk** [comment]
What `chunksize` have you used?

**Comment by poiNt3D** [comment]
I don't think it completely solved the problem.
I've tried different chunksizes, 10, 30, and 100.
At least i got a large portion of the mail imported, but at some point it runs out of memory. I will continue my experiments, but i think the best is to use $query->chunked method of PHP IMAP lib, but i couldn't get it to work for some reason.
