### ISSUE TITLE
Emails answered by another emplyee 

### ISSUE THREAD

**Issue by poiNt3D** [freescout-helpdesk/freescout#2199]
Hello. We trying to migrate from Gmail to Freescout.
Right now we have a routing rule in gmail that adds another recipient to each incoming mail.
If that recipient answers this mail, original recipient can see his answer in gmail thread.
```

a@customer -> |-> b@company
              |-> c@company

```

The problem is, when fetching mails Freescout marks an answer from that another employee (c@company) as an original message, and creates a customer entity for C. It shows the thread as originated from C, message from C is shown first, and then the message from customer A.
Employee C is registered in Freescout using the same email address (c@company).

**Comment by maticboncina** [comment]
Gmail is a mail service, and freescout is a support helpdesk that relies on the mail server as a partial backend if clients decide to reply to a ticket via mail. You "can't" migrate directly from Gmail to freescout. You will need to change some stuff. That's in nutshell. Of course, you can use Gmail and its rules like you described to achieve a "support-like" system. In any case, freescout needs IMAP capable service behind it. It's not a standalone solution. 

What I recommend you do, is set up a new mailbox in Gmail, hook it up to a mailbox in freescout, and simply create 2 users in freescout. That way, no matter who answers, the original recipient or that 2nd user, the customer will see the reply. Also, check the modules directory I think the ticket followers plugin might be something you're looking for.

From my understanding, you're trying to force the existing system to work with your custom Gmail rules. That's not something freescout was made to do. It is just a mailbox/support system.

**Comment by freescout-helpdesk** [comment]
Thanks for advice @maticboncina
