### ISSUE TITLE
Ticket content not visible in the ticket view

### ISSUE THREAD

**Issue by mihha** [freescout-helpdesk/freescout#220]
Hi,

FreeScout version 1.1.6 (updated today)

When you check ticket in the ticket list view, you will see that that ticket actually contains some content

![image](https://user-images.githubusercontent.com/3791124/50643624-ed166d80-0f6e-11e9-9951-52acdd7443bc.png)

If you check the ticket in the ticket view, you won't see that ticket content

![image](https://user-images.githubusercontent.com/3791124/50643697-1931ee80-0f6f-11e9-8b8a-25d17fd703a4.png)

**Comment by freescout-helpdesk** [comment]
Check logs. By some reason thread is not created.

**Comment by mihha** [comment]
I am attaching the laravel logs here because quite frankly I don't understand what is going on

[laravel-2019-01-03.log](https://github.com/freescout-helpdesk/freescout/files/2724187/laravel-2019-01-03.log)

**Comment by mihha** [comment]
From the fetch log I saw the following one

`Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'first' in 'field list' (SQL: insert into `threads` (`conversation_id`, `user_id`, `type`, `status`, `state`, `message_id`, `headers`, `body`, `from`, `to`, `cc`, `bcc`, `source_via`, `source_type`, `customer_id`, `created_by_customer_id`, `first`, `updated_at`, `created_at`) values (5, , 1, 1, 2, em655647ff-cefe-47cd-b2a4-2e836f1496f8@mihha-lenovo, Return-Path: <igor.mihaljko@gmail.com> X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on mihha-vps.me X-Spam-Level: X-Spam-Status: No, score=0.0 required=5.0 tests=FREEMAIL_FROM, RCVD_IN_DNSWL_NONE,SPF_PASS,T_DKIM_INVALID autolearn=ham autolearn_force=no version=3.4.2 X-Original-To: support@helpdesk.mihha-vision.com Delivered-To: support.helpdesk@mihha-vps.me Received: from mail-wm1-f46.google.com (mail-wm1-f46.google.com [209.85.128.46]) by mihha-vps.me (Postfix) with ESMTPS id 402329BAF2 for <support@helpdesk.mihha-vision.com>; Thu, 3 Jan 2019 15:44:36 +0100 (CET) Authentication-Results: mihha-vps.me; dkim=pass reason="2048-bit key; unprotected key" header.d=gmail.com header.i=@gmail.com header.b=ANn0IHTQ; dkim-adsp=pass; dkim-atps=neutral Received: by mail-wm1-f46.google.com with SMTP id b11so29476688wmj.1 for <support@helpdesk.mihha-vision.com>; Thu, 03 Jan 2019 06:44:36 -0800 (PST) DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=20161025; h=from:to:subject:date:message-id:reply-to:user-agent:mime-version :content-transfer-encoding; bh=lBqbXJ4WRO5fmV1dyAxWv1djV58Os4AmQ0tfl3t9Z+Y=; b=ANn0IHTQvmgSViqVSBq/nfLqPGUTMrL1HY1RLLVkNd5CmqokrpzqWxdxEMzxQyyblA 8mJGVhVhL8TaZzoc6O76EdzTyb38mseeK21vEMfoAK3ZVFMx750lmePsCbTij6pnp5Z9 P8Dsb9z6GJztuF+k2sPho391YBX1J/tVAKUvpCQo8DipO9SaQzieNp156VhalE1ekkON V9QTl3MBcoxAyvg7jc6325lTubhEYOmzKpeAZ+Cqg38sfwuaUAqHeKGCaUhWrBWjvx9B zoJpdMzlBRO70QRCM3ZRrK4ex6zrVljefYGd1S7f/4BayoX5ylOFTePv8vEYTJNHxpQT LaXA== X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=1e100.net; s=20161025; h=x-gm-message-state:from:to:subject:date:message-id:reply-to :user-agent:mime-version:content-transfer-encoding; bh=lBqbXJ4WRO5fmV1dyAxWv1djV58Os4AmQ0tfl3t9Z+Y=; b=cQfNAbM5/A7XyUKwrajSSj4DxrUBuWjPOE7s7otc4MG6cHAymQzl10gDEOwH7DietA 8NA1pr1sarYJXg3rtZpmiN2ULEuxrJbiCZnowKuIIa3JVcIFSRraxmmyDGgkA/mgfW6C fxFWvO/nFl4NZme9vLwveHTI102N6osP0k8qv3aFIhZvIxMaC5VpdRUhf46AVsELEoAN McZI9HuoWcsuDqN5yHyx4aOOTHdqkexVvs2XW3rLifrurpc3wF4o8wgAkrT++s8FOA+R POA2gAPh9dtctRdxmMqS6a5DMh5pgOoiMD/TYhl08K61aGNEY8oIliAjHegnCdvkuIyW ItwQ== X-Gm-Message-State: AA+aEWb7Qamv8H8uMg7bIqPq1E95PEsA78hpkqevZyqXq87mc3E30Hiu mXHTRFekhKbWJR8FxUfpDN9yGeUOFpI= X-Google-Smtp-Source: ALg8bN7gHMFsZoSEENd6n66XO+hzn5KG/8cCBek2g+doa1ygVOTdMi49pzoKhdcbYqwYie7ISvh8ZA== X-Received: by 2002:a1c:ae88:: with SMTP id x130mr36174490wme.91.1546526675383; Thu, 03 Jan 2019 06:44:35 -0800 (PST) Received: from [192.168.102.96] ([31.45.236.210]) by smtp.gmail.com with ESMTPSA id z7sm44203866wrw.22.2019.01.03.06.44.34 for <support@helpdesk.mihha-vision.com> (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128); Thu, 03 Jan 2019 06:44:34 -0800 (PST) From: "Igor Mihaljko" <igor.mihaljko@gmail.com> To: "support@helpdesk.mihha-vision.com" <support@helpdesk.mihha-vision.com> Subject: Test ticket 1 Date: Thu, 03 Jan 2019 14:44:34 +0000 Message-Id: <em655647ff-cefe-47cd-b2a4-2e836f1496f8@mihha-lenovo> Reply-To: "Igor Mihaljko" <igor.mihaljko@gmail.com> User-Agent: eM_Client/7.2.34208.0 Mime-Version: 1.0 Content-Type: text/plain; format=flowed; charset=utf-8 Content-Transfer-Encoding: quoted-printable , My question goes here<br /> <br /> , igor.mihaljko@gmail.com, ["support@helpdesk.mihha-vision.com"], , , 1, 1, 1, 1, 1, 2019-01-03 15:45:30, 2019-01-03 15:45:30)); File: /home/mihha_vision/domains/helpdesk.mihha-vision.com/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php (664)`

**Comment by mihha** [comment]
Hi,

yes, that is correct. I am using FreeScout from the early dev version. Your DB change suggestion solved the issue

Thank you very much for your support!
