### ISSUE TITLE
Workflows module not detecting AND statements

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2200]
Hello,

If I set the workflow to trigger when conditions:
TAG = answered 
AND 
STATUS = active

Even though the conversation matches the parameters it doesn't assign a "customer reply" tag. 

My goal is to make it so that when a customer replies, a tag "customer reply" is assigned. Which I can't do no matter what. 

Here I am attaching the conditions of the workflow and a screenshot of the ticket on which the workflow was supposed to trigger (it has the tag and it was marked active when the customer replied).
<img width="1184" alt="CleanShot 2022-09-06 at 19 52 11@2x" src="https://user-images.githubusercontent.com/54638868/188705227-49d7fffb-519c-4c62-95b8-b5ac821431b5.png">
<img width="1232" alt="CleanShot 2022-09-06 at 19 52 19@2x" src="https://user-images.githubusercontent.com/54638868/188705246-55d2fb4a-0d8e-4c6d-aa7b-83340e71d917.png">

Any help is much appreciated.

**Comment by ilyakonovalenko** [comment]
Try to add a condition to execute only when customer replies.

**Comment by maticboncina** [comment]
> Try to add a condition to execute only when the customer replies.

Which condition would that be?

**Comment by freescout-helpdesk** [comment]
You need to add the following condition (we've added this to module's documentation):

![2022-09-09_13-26-52](https://user-images.githubusercontent.com/40499291/189330593-c5a0e55f-747e-4420-9870-6ba56fc30364.png)

**Comment by maticboncina** [comment]
Thank you
