### ISSUE TITLE
Make dropdown name unselectable in end-user portal

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2201]
When a custom field (dropdown type) is created and assigned to the end-user portal, the actual name of the dropdown is also selectable as an option (which it shouldn't).

I am attaching the recording here

https://user-images.githubusercontent.com/54638868/188724946-b8d36797-dbdf-49ae-b453-b92714055693.mp4

What should happen is, to have the name of the dropdown unselectable like this: ![CleanShot 2022-09-06 at 21 46 00@2x](https://user-images.githubusercontent.com/54638868/188725080-e4a6fd90-62a8-4a74-b60e-81402d4dea49.png)

**Comment by freescout-helpdesk** [comment]
We don't have a solution for this. If the field is required the end-user won't be able to submit the form with the first element selected.
