### ISSUE TITLE
[suggestion] move Action icons Workflow & Forward

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#2203]
@freescout-helpdesk Would it be possible to move the icons from the screenshot to the main area, so there is one less click, it would be so much faster to work with. We use Workflows a lot and having an extra click does not make sense.
If there is one action to move then move Workflow and Forward

Hope you will consider this

![image](https://user-images.githubusercontent.com/902376/188806525-e497ae7b-0ea3-4b96-8f17-27bd89d63983.png)

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans.
