### ISSUE TITLE
Getting Error "[ALREADYEXISTS] Mailbox already exists"

### ISSUE THREAD

**Issue by roNn23** [freescout-helpdesk/freescout#2204]
I'm getting this error multiple times a day. I did clear the cache, everything is up-to-date and I'm on the latest version. Can you please help me? Thank you so much!

`[2022-09-07 09:28:05] Fehler beim Empfangen der E-Mail {"error":"Folder: Drafts; Error: [ALREADYEXISTS] Mailbox already exists (0.001 + 0.000 secs).","mailbox":"xxx@xxxxxx.de"}`

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules?

**Comment by freescout-helpdesk** [comment]
The error is returned by your mail server. What mail server are you using?
https://help.bittitan.com/hc/en-us/articles/115008098827--ALREADYEXISTS-

**Comment by ajsavoca** [comment]
I am using Rackspace. I looked through the link you provided, and took a look at the mailbox settings. These are default folders (except for Archive) that do not have similar names or special characters and they are all enabled for IMAP.

**Comment by freescout-helpdesk** [comment]
Try to remove extra IMAP folders from Incoming Connection settings in your mailbox. Or try to contact your mail server provider to figure out what this error means.

**Comment by roNn23** [comment]
I can now confirm, that removing the extra IMAP folders solves the problem. The question is: Why is this wrong? This is a problem in Freescout and should be fixed?

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/849194/190671013-1ec5622a-ca3b-4251-8bb3-948395e83c62.png)

**Comment by roNn23** [comment]
@freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
The problem is in your mail server.
