### ISSUE TITLE
"Security" improvements

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2205]
Hello,

Is it possible to enhance security of the installation by implementing these features (custom code of course):

Secure admin area with a VPN access list - I am not sure if that breaks the Twitter module then. I have set a custom path for dash and admin login. 
Add captcha to ticket submission - I assume there shouldn't be any issues with this

Additionally not really a security improvement, but is it possible to add the "subject" field to the end-user client system? It gets imported through emails but I don't see an option for it on the end-user system.

All the best, Matic

**Comment by ilyakonovalenko** [comment]
I agree. It would be really nice to have an ability to limit access to certain parts of FreeScout.

**Comment by freescout-helpdesk** [comment]
Feel free to submit feature requests: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
> Secure admin area with a VPN access list

Do you want to restrict access to Login page by IP? Can you elaborate a bit more.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/extra-security/
