### ISSUE TITLE
How to stop FS from adding automatically people on CC?

### ISSUE THREAD

**Issue by zuzullo** [freescout-helpdesk/freescout#2207]
How to make FreeScout stop adding automatically people on CC that were on previous emails but are not on the current email? Real example:
I was in contact with Ana, from another company. Then Ana forwarded my email to a colleague Jessica. Then Jessica replies the email from Ana and removes Ana and adds me instead. At that point I got an email from Jessica and Ana is not in CC (which is correct). BUT when I push REPLY, then FreeScout adds Ana automatically. Why? (?!?)
(This behavior does not happen on a normal email client like Thunderbird.)

**Comment by freescout-helpdesk** [comment]
Unfortunately we could not reproduce the issue.

**Comment by freescout-helpdesk** [comment]
If you'll be able try to find find the problem and feel free to share the solution.
