### ISSUE TITLE
Telegram Integration module doesn't work

### ISSUE THREAD

**Issue by Iniretur** [freescout-helpdesk/freescout#2210]
Telegram bot does nothing to /start command. Also, it's not the same bot I'm using for the Telegram Notifications module
![image](https://user-images.githubusercontent.com/57409306/189185668-a0188466-599f-4e80-adeb-ea6bac457508.png)
![image](https://user-images.githubusercontent.com/57409306/189185766-db24a298-874f-4680-a847-cc37dd8318e4.png)

**Comment by freescout-helpdesk** [comment]
It looks like there is some issue with your bot. We can't help here as we don't have control over Telegram.

**Comment by Iniretur** [comment]
I can assure you there’s nothing wrong with the bot as the same token works fine with a python bot, for instance. Also, there is nothing in logs

**Comment by freescout-helpdesk** [comment]
Try to send a bot something other than "\start"

**Comment by Iniretur** [comment]
Already did, no reply
