### ISSUE TITLE
Need help with customer panel!

### ISSUE THREAD

**Issue by conniebrt** [freescout-helpdesk/freescout#2211]
hi, how can i see the full demo for customers? because i still don't understand how it works

after customer autorisation the information about name and email will be filled  automatically?

![Screenshot_1](https://user-images.githubusercontent.com/113167710/189294012-a06d37a2-bb83-4333-b0b4-6580af110ec6.png)

**Comment by maticboncina** [comment]
Yes, if customer is logged into the End-User system, those fields are prefilled automatically.

**Comment by freescout-helpdesk** [comment]
Yes. You can check it here: https://demo.freescout.net
