### ISSUE TITLE
Password for customers 

### ISSUE THREAD

**Issue by conniebrt** [freescout-helpdesk/freescout#2212]
Hi! Is it possible to create password for customers? or how can i protect their ticket information??only with e-mail is not very safely

**Comment by maticboncina** [comment]
I do it by using the LDAP (you may use SAML SSO too) module and integrating another identify management solution like Ory (OpenSource) or Auth0.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
