### ISSUE TITLE
Workflow to automatically close Bounce Messages is not working

### ISSUE THREAD

**Issue by chicobico** [freescout-helpdesk/freescout#2215]
We added a **Automatic** workflow.
We only added 1 condition **Is Bounce: Yes**
And 1 action **Change status: Closed**

The Flag **Apply to Previous** is disabled.

The workflow never runs on incoming bounce messages.
But the messages are marked as bounce messages.

If we enable **Apply to Previous** it works.
But it should also work without **Apply to Previous** in my opinion.

**Comment by freescout-helpdesk** [comment]
Add the following condition (we'll add this to module's documentation):

![2022-09-09_13-27-19](https://user-images.githubusercontent.com/40499291/189329924-1cb2c78c-a462-41be-890e-76e05ff94a1a.png)

**Comment by chicobico** [comment]
Unfortunately it still doesn't work.
Is it possible that it runs the workflow before the message is marked as bounce message?

**Comment by chicobico** [comment]
![Screen Shot 2022-09-09 at 12 50 20](https://user-images.githubusercontent.com/1045764/189334217-a9b88405-9b8a-4264-9ce9-bb64f08e991d.png)
![Screen Shot 2022-09-09 at 12 50 43](https://user-images.githubusercontent.com/1045764/189334240-b2668cd3-18bb-4fa3-ac8a-d60e6b7b38dc.png)
![Screen Shot 2022-09-09 at 12 50 52](https://user-images.githubusercontent.com/1045764/189334254-4857d893-76b5-4184-91a4-c3415d445238.png)

**Comment by freescout-helpdesk** [comment]
We've just checked it - works fine even without "New / Reply / Moved" condition. Make sure that the email you want to close is actually detected by FreeScout as a Bounce.
