### ISSUE TITLE
Problem with restricting access to tickets

### ISSUE THREAD

**Issue by conniebrt** [freescout-helpdesk/freescout#2216]
Is it possible to restrict access to tickets for agents? For example, I want to assign a ticket to an agent and not allow other agents to view the ticket?

**Comment by maticboncina** [comment]
I'd suggest that you create one shared mailbox and individual mailboxes for each user. 

Then setup a manual or automatic workflow that on reply/manual intervention moves the ticket to a private mailbox, which only one user has access to, therefore, making the ticket invisible to other agents.

**Comment by freescout-helpdesk** [comment]
> I'd suggest that you create one shared mailbox and individual mailboxes for each user.
> 
> Then setup a manual or automatic workflow that on reply/manual intervention moves the ticket to a private mailbox, which only one user has access to, therefore, making the ticket invisible to other agents.

Yes, this is the only way.
