### ISSUE TITLE
Reoccurring workflows

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2217]
Hi,

Has anyone been able to figure out how to run "workflow" or "workflow like" actions multiple times per ticket?

I want to assign tags to tickets depending on their status, but unfortunately, workflows only run once per ticket, making it not possible that way (as they would only run once). 

What I want to achieve:
- When ticket is opened, open tag is assigned (works normally, since it only needs to happen one time)
- When staff replies, ticket tag is set to "answered"
- When the client replies, the ticket tag is set to "customer reply" (The last two are not possible since they could happen multiple times).

If anyone knows any way how to do it, I would highly appreciate the hint :)

All the best, Matic

**Comment by ilyakonovalenko** [comment]
There are conditions to execute only when customer or agent replies. You could use the condition and assign tags based on replier.

**Comment by maticboncina** [comment]
> There are conditions to execute only when customer or agent replies. You could use the condition and assign tags based on replier.

Hi, yes I’ve been using this for now, however, if let’s say agent replies twice, the workflow to assign answered tag won’t work since it already ran once. 

From my understanding workflows only run once per ticket which matches my tests. If I am wrong please let me know 😅

**Comment by freescout-helpdesk** [comment]
See this discussion: https://github.com/freescout-helpdesk/freescout/issues/436#issuecomment-576023407

**Comment by maticboncina** [comment]
> See this discussion: [#436 (comment)](https://github.com/freescout-helpdesk/freescout/issues/436#issuecomment-576023407)

Thank you. I will likely do it with CRONs to mimic how WHMCS does it. I will submit a pull request and then someone from the team can decide if it’s production ready 🙂
