### ISSUE TITLE
Updating failed (until I changed my MySQL password)

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#2218]
I was attempting to update from Freescout 1.8.20 to 1.8.23.

Whatever method I used, after upgrade I'd get a blank screen; and the errors logged were that my MySQL credentials were not accepted. (Happily I followed the advice to backup first, so was able to restore).

After trying different methods, I eventually decided to change my MySQL password to something with fewer special characters, before re-attempting the upgrade. Upgrading then worked. So apparently somewhere in between 1.8.20 and 1.8.23, something breaks that means the upgraded version won't process the previously-entered password the same way if certain special characters are used.

Here's an example of the upgrading process before I changed paswords:

```
# php80 artisan freescout:update
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Updating... This may take several minutes
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
SQLSTATE[HY000] [1045] Access denied for user 'myuser'@'localhost' (using password: YES) (SQL: select distinct `locale` from `ltm_translations`)
Nothing to migrate.
Broadcasting queue restart signal.
```

Note: my install is now working fine, since I changed the password. I'm just reporting this as it may be useful to others, and presumably the root cause is still there.

**Comment by freescout-helpdesk** [comment]
Strange. Anyway thanks for sharing.
