### ISSUE TITLE
[BUG] [CRM] It's not possible to readd a customer mail

### ISSUE THREAD

**Issue by lieblinger** [freescout-helpdesk/freescout#2219]
If I add a new customer and delete it from the CRM, it's not possible to add the same mail address again. 

**The CRM module returns the following error message:**
There's already a customer with this mail address.

**Comment by freescout-helpdesk** [comment]
The issue has been confirmed. We'll try to fix.

**Comment by PaulDuthie** [comment]
Have noticed this as well

The import process also doesn't appear to match emails for existing users to update - just gets a message 'this email belongs to another user' when it's the same user

**Comment by freescout-helpdesk** [comment]
Fixed in CRM Module v1.0.13
