### ISSUE TITLE
Remove emails from email inbox when fetching using POP3

### ISSUE THREAD

**Issue by mihha** [freescout-helpdesk/freescout#222]
Hi guys,

it would be a good idea (maybe) to have an option which would allow us to delete emails from fetched email inbox in case you are using POP3 protocol. 

For me, it doesn't make sense to keep email messages in the email inbox on the mail server once FC has fetched them from the server

**Comment by enrikberisha** [comment]
Same here. @freescout-helpdesk possible to have a look into this?

**Comment by foliovision** [comment]
Hi Mihha,

We're running Freescout via IMAP. We often find ourselves going back to the IMAP inbox to doublecheck if what we are seeing in Freescout corresponds exactly with what happened on the server. Freescout is still young enough with enough bugs that I'd recommend against flying without a safety net for now. If you just want to delete your old messages, it makes more sense to go in once/month and just delete messages older than 30 days.

Eventually I agree with you, it would be nice for Freescout to automatically delete fetched POP emails. It could default to a ten days trailing cycle for safety.

**Comment by alekseyp** [comment]
I agree that deleting right away is not a good idea, but maybe we can add a cleanup job that would delete all read emails older than X days (30 for example)

**Comment by fulldecent** [comment]
recommend to close issue as wontfix/out of project scope

**Comment by gdandersson** [comment]
If removing emails from POP3 (or IMAP for that matter) servers is out of project scope, what's the suggestion for people receiving lots of emails per month?

The inbox would have to be lots and lots of GB (and increase in size with each month)

**Comment by iPublicis** [comment]
Why not having this for POP3?

https://freescout.net/module/imap-move/

**Comment by freescout-help** [comment]
Removing emails via POP3 has been implemented in "Move or Remove IMAP Message Module" v1.0.5. Marking an email as read or moving to IMAP folder is not possible with POP3 as POP3 protocol does not support those operations.
