### ISSUE TITLE
[REST_API] Update methods

### ISSUE THREAD

**Issue by lieblinger** [freescout-helpdesk/freescout#2220]
We would like to use the CRM and RestAPI module to synchronize customers from our ERP. 

All customer data changes comes from our ERP-System and from here they should be synchronized back to FreeScout. To update records in FreeScout it'd be necessary having an update function in the RestAPI, otherwise synchronization wouldn't be possible.

Could you implement this feature into the RestAPI? Is this already on your roadmap?

**Comment by maticboncina** [comment]
Check here (https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/popular) and if it's not there add the idea.

**Comment by freescout-helpdesk** [comment]
Yes, feel free to submit a feature request.
