### ISSUE TITLE
Android App : register as handler for freescout links

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#2221]
Hello,

I'm unsure if the Android app is developed internally.
I'm also unsure if this issue is fixable on your side or is an Android problem.

Our team members generally share freescout links in messenger apps if the need assistance with a ticket.
When trying to open the link on an Android device it launches the default browser instead of the Freescout app.
Theres also no way of manually pasting the link in Freescout app to go to the ticket.
The ticket number in the URL also doesn't always match the actual ticket number.
It thus is extremely hard to go to a specific ticket, in the app, when you only have the link.

Is there a way to register Freescout as a handler for https://freescout.mydomain.com links?
Alternatively can the search in the app be made to recognize URLs and try to navigate there?

**Comment by freescout-helpdesk** [comment]
Yes, it's developed by FreeScout Team. Unfortunately technically it's impossible.
