### ISSUE TITLE
Make userlink and admin link same for communication purposes

### ISSUE THREAD

**Issue by davask** [freescout-helpdesk/freescout#2225]
Hi,

for 1 ticket I have now same IDs which make easier conversation between clients and I however I cannot share my admin link to user cause they can t access it.

As an example.
My Hastag ticket number is #2064, the url as admin is /conversation/2064 and user link to ticket is /help/2936061329/ticket/2064 

Could we share /conversation/2064 and being redirected to /help/2936061329/ticket/2064 if connected as user and same the other way if I receive /help/2936061329/ticket/2064 being redirected to /conversation/2064
OR
could we all share /ticket/2064 and depending on our logging type we see /help/2936061329/ticket/2064 or /conversation/2064

What do you think ?

**Comment by davask** [comment]
At the same time, when we are logged in on the admin side, if the url /ticket/2064 redirect to proper display depending who is connected we could as admin have a button to allow us to switch from one display /conversation/2064 to another /help/2936061329/ticket/2064

What do you think ?

**Comment by davask** [comment]
Last but not list, on the /help/2936061329/tickets display could we display the id of the ticket on the line to improve how we can easily retrieve a ticket on the client side ?

**Comment by maticboncina** [comment]
So you want all IDs for a particular ticket to be the same?

**Comment by davask** [comment]
I d like to be able to share same url between user and admin for each ticket (make sense ?)

**Comment by maticboncina** [comment]
That doesn't seem to be possible out of the box since the admin area and user area are separate. Make a feature suggestion here: https://freescout.net/request-feature/

**Comment by davask** [comment]
as the user area is a plugin it needs to be handled by the user plugin develop team, right ?

**Comment by maticboncina** [comment]
The suggestion portal is used for all freescout-related suggestions.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by davask** [comment]
it has been added here https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/385004
