### ISSUE TITLE
Custom Homepage Module requires re-saving in Docker

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2228]
Hello,

For some reason, after a week or some the custom, home page module stops redirecting/modifying the path. When I got to the settings page nothing changed and all I need to do to get the correct redirects working again is to press save.

Are there any known causes for this?

Best, Matic

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Something must be wrong with your FreeScout installation. Make sure that the module is active. Try to disable all non-official modules, etc.

**Comment by danielcaldwell** [comment]
I'm running into this same issue. Whenever the services are restarted, I have to login and resave the Custom Home Page. Settings are retained, but are not working until a resave happens.

**Comment by maticboncina** [comment]
> I'm running into this same issue. Whenever the services are restarted, I have to login and resave the Custom Home Page. Settings are retained, but are not working until a resave happens.

Are you also running it in Docker?

**Comment by danielcaldwell** [comment]
Yes, I'm running it using the freescout docker image.

**Comment by maticboncina** [comment]
@freescout-helpdesk Can we reopen this issue please?

**Comment by danielcaldwell** [comment]
I tried adding the bootstrap cache `/www/html/bootstrap/cache` to the data volume, but that didn't fix the issue. I didn't see any other files that potentially could be part of the volume data. Maybe there is data stored somewhere else that needs to be in a volume.

**Comment by freescout-helpdesk** [comment]
Settings are saved in /.env file and after that cached by Laravel.

**Comment by danielcaldwell** [comment]
I verified that the `/www/html/.env` is being saved to the `/data` volume. It is probably why the settings are there after restarting the service. The save of the settings must be changing something somewhere. I don't see a

```
$ ls -l /www/html/.env
lrwxrwxrwx    1 nginx    www-data        12 Sep 27 22:34 /www/html/.env -> /data/config
```

Also the config file has the file storage set as default: 

https://github.com/freescout-helpdesk/freescout/blob/dist/config/cache.php#L18

And it is pointing to the storage/framework dir: 
 
https://github.com/freescout-helpdesk/freescout/blob/dist/config/cache.php#L47

And the storage is also stored in the `/data` volume so that is there too. 

```
$ ls -la storage
lrwxrwxrwx    1 nginx    www-data        13 Sep 27 22:34 storage -> /data/storage
$ ls storage/framework/cache/data/
0b  2f  30  36  3c  3e  5e  71  8b  98  9e  9f  a4  b7  dd  ee
```

Is the save of the CustomHomepage Module saving something somewhere else? Or doing some other change?

**Comment by freescout-helpdesk** [comment]
No. Info from the .env file is used in routes https://github.com/freescout-helpdesk/freescout/blob/dist/routes/web.php, so also check routes cache.

**Comment by danielcaldwell** [comment]
I think the routes cache is in the bootstrap cache folder. I added that in to the volume earlier and it didn't seem to help. Can you confirm that the routes cache is the bootstrap cache? 

I see some people clearing the cache here: 

https://stackoverflow.com/questions/37878951/how-to-clear-laravel-route-caching-on-server

also suggesting to remove this file: `bootstrap/cache/routes.php`

which, by default, is not part of the volume so would have to be regenerated every time the container starts. 

Is it a matter of the cache needing to be regenerated after the container restarts?

**Comment by freescout-helpdesk** [comment]
We've double checked - no, routes are not cached, only content of the .env file.

Here is the place for docker-related questions: https://github.com/tiredofit/docker-freescout/issues
