### ISSUE TITLE
FreeScout won't update to the latest version

### ISSUE THREAD

**Issue by DrazanJ** [freescout-helpdesk/freescout#2229]
PROBLEM DESCRIPTION
I am not able to perform the FreeScout application software update from version 1.5.7 to version 1.8.23.
The first problem I encountered is that Method 1 (update from the web interface) is not applicable in my case because there is no „Check for updates“ button in the Web GUI at all.

![image](https://user-images.githubusercontent.com/103513158/189944237-b04b661e-b756-461c-99bf-887ce6436fe2.png)

Next, I tried Method 2 (Update using console script), it worked shorty and it seemed that it finished the job with the "Nothing to migrate" message. The problem is that nothing changed after running the update.sh.

Finally, I tried Method 3 ( Update using GIT ) and after execution of the command „git pull“ the following message is displayed:
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
    git branch --set-upstream-to=<remote>/<branch> master

After trying Method 3 and retrying the execution of the tools/update.sh script the following output is displayed:
tools/update.sh: 79: tools/update.sh: [[: not found
-e Current branch:
fatal: ambiguous argument '..origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
-e You already have the latest version of the application, no upgrade needed.

But the config file as well as the web interface FreeScout "say" that we still have 1.5.7 version.

I am running the FreeScout application under OS Ubuntu 18.04.6 LTS, and accessing it using putty SSH.
Please help!

**Comment by freescout-helpdesk** [comment]
Sometimes it happens. All the helpful information is here https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by DrazanJ** [comment]
Thank you for the prompt answer.
I have two issues with method 5. I don't see the .env file and the link https://example.com/tools.php doesn't work.
Could you help me with this?
