### ISSUE TITLE
Tags page looks different for different people

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2230]
I purchased the Tags module.

When I view the Manage > Tags page, I see many tags, including some tags with zero conversations.

When another support agent on my team loads the page they see less tags. They are excluding the zero conversation tags.

This issue becomes a problem because those tags with zero conversations are typos. Now when support agents want to tag an email it is autocompleting to a typo.

---

Our expectation is that everybody that visits the Manage > Tags page will see the same tags. And that when one person deletes a tag from the Manage > Tags then that tag will be deleted for everybody.

**Comment by freescout-helpdesk** [comment]
Admin user sees all tags on Tags page. Other users see tags which are linked to conversations in available to the user mailboxes.

**Comment by fulldecent** [comment]
Our installation only has one mailbox.

So for us, the only tags admin should be able to see that others cannot is when a tag has zero conversations. Is that correct?

**Comment by freescout-helpdesk** [comment]
Yes.
