### ISSUE TITLE
Fresh Install - Office 365 Fetching Failed

### ISSUE THREAD

**Issue by travisneuber** [freescout-helpdesk/freescout#2232]
![image](https://user-images.githubusercontent.com/44452954/190018035-c505a4c5-e26b-4270-9918-40648a12a18b.png)

I have a new install, and have gone through the OAuth for 365/azure AD. The account shows connected, but i get that error in the logs when it attempts to fetch.

**Comment by freescout-helpdesk** [comment]
The only way to find out the reason is to debug it. Here are some useful links:

https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L595
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php

**Comment by freescout-helpdesk** [comment]
Feel free to send access to your FreeScout server, admin and M365 to support@freescout.net

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2264

**Comment by freescout-helpdesk** [comment]
Does the MS365 user you are using to connect have a mailbox in MS365 and able to access it via https://outlook.office365.com/mail/ ?
