### ISSUE TITLE
Active+pending conversation count does not match between search and homepage

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2235]
I was expecting the sum of items on the homepage to match the number of ACTIVE. + PENDING conversations when using search.

Please explain which number is correct and fix the other one.

<img width="1886" alt="Screen Shot 2022-09-14 at 11 50 32" src="https://user-images.githubusercontent.com/382183/190202743-d9eb5ce0-789f-41d3-a37d-93387928f6cc.png">
<img width="1886" alt="Screen Shot 2022-09-14 at 11 50 34" src="https://user-images.githubusercontent.com/382183/190202750-4bf45e16-e157-4bad-b81c-7c0c8145210d.png">

**Comment by freescout-helpdesk** [comment]
Numbers next to folders are showing Active conversations, open each folder to see Active and Pending conversations.

**Comment by fulldecent** [comment]
@freescout-helpdesk Still does not match. I have full annotated screenshots here

<img width="2172" alt="Screen Shot 2022-09-14 at 14 16 15" src="https://user-images.githubusercontent.com/382183/190231899-634e2aee-3a3a-47b7-9f7e-0fc24ffa7ba6.png">
<img width="2172" alt="Screen Shot 2022-09-14 at 14 16 17" src="https://user-images.githubusercontent.com/382183/190231908-4d73750f-b8e6-4a9a-9b9f-bbbfdc94b74f.png">
<img width="2172" alt="Screen Shot 2022-09-14 at 14 16 21" src="https://user-images.githubusercontent.com/382183/190231915-10b87905-fb83-44d0-bb7c-fdb5e6a9b27f.png">
<img width="2172" alt="Screen Shot 2022-09-14 at 14 16 23" src="https://user-images.githubusercontent.com/382183/190231924-6ec72be2-081b-47b1-9806-9b340aff109c.png">
<img width="2172" alt="Screen Shot 2022-09-14 at 14 16 49" src="https://user-images.githubusercontent.com/382183/190231935-dfe588a2-6ca7-404a-a128-8c99bb8729ac.png">

**Comment by freescout-helpdesk** [comment]
The Search by default shows also Deleted conversations - check State filter.

**Comment by fulldecent** [comment]
Aha, thank you!
