### ISSUE TITLE
Call to undefined function App\Console\Commands\iconv_mime_decode()

### ISSUE THREAD

**Issue by bcookatpcsd** [freescout-helpdesk/freescout#2236]
Whoops, looks like something went wrong — check logs in /storage/logs 

[2022-09-14 12:15:24] Message from: Customer

In FetchEmails.php line 499:

  Call to undefined function App\Console\Commands\iconv_mime_decode()

is all that is there.. 

![image](https://user-images.githubusercontent.com/55087301/190213817-7ffbd9ec-349e-4644-8337-e96cb352a990.png)

all the modules look good.. 

![image](https://user-images.githubusercontent.com/55087301/190215494-af42ec0c-9d3b-4b46-a196-b8c4b20f811a.png)

*wait*

where is iconv?

my php-fpm7 -m showed no iconv enabled.. 

enabled iconv.. restarted php-fpm7 and all seems to be working again.. 

Did iconv become required and I missed? (seems to be..) 

Hope this helps someone..

**Comment by freescout-helpdesk** [comment]
It was always required, just not mentioned in the list of required extensions. Added now.
