### ISSUE TITLE
Embed Image Module not working

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2238]
Thank you for implementing the Embed Images module. This is a very helpful addition for us.

However, it does not work. We use a manual workflow to send a pre-defined reply including an image.
Without the embed image module, this worked well, but the image pointed to the Freescout instance URL.

With the embed image module, the image is properly embedded into the message (checked with code view in editor), but when executing the manual workflow, the following error appears in the logs:

> Undefined index: host; File: /var/www/html/Modules/EmbedImages/Listeners/SwiftEmbedImages.php (62)

Freescout fails to send the reply email. Hoewever, the reply is shown in the ticket within Freescout, but the image is missing.

**Comment by MarcoWel** [comment]
Addition: Error and result is exactly the same when sending a reply normally within Freescout (without the workflow).

**Comment by MarcoWel** [comment]
Addition 2: When disabling the embed images module, everything works fine again. Replies are sent including images with src pointing to the Freescout instance URL. Also manual workflow replies work again as desired (image is showing correctly in email now, but still not in the Freescout instance for some reason).

**Comment by freescout-helpdesk** [comment]
Can you give an example of the image URL in the reply editor.

**Comment by MarcoWel** [comment]
Sure, this gets inserted when pasting the Freescout logo:

`<div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALgAAAAkCAYAAAA6l/D/AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAB4pJREFUeNrsXUty2zgQhV3eh3OCUCcIXXOAoVapWZk6gMrUCSxtZyNpM1tLJxBTPoCU1ZRXog8wZc4JzJwgzAk8QKoRt1sACFDUxzK6CiWJBpsg8LrxugHSZ6yB/P7XPwH/iHiJNVVyXop///6zctX9/PzMvHhpS84cQZ3wcgPgtpGClzkvK1uwe4B72SvAAdhDAHbQ8DoVAH1WB3QPcC97AzgHt/DUS17Clq5X8tLjIC88wL0cFOAc3Cn/WOzougMO8swD3MtBAO4A7gp4doXoS2RJZZQg9wD3slOAW4Bb8umMA7TUGIigNKkFb98AuQ7g/fv+uOE9fhNtPZHxEs7jir3OXokx+E8E8vD9Xcnd5zt7gAPnfjTUn9oEiooA1QTOS8zJDQBv6tpzXrpvfBwDiIXimnoZjFHpAU4ADmB81ASUFQSHeZNGcN0xDFCgCTwvpdF4gG9ICONim8Gq4H6LE8d2AExDfBYc6CNVpQv0fWgAd1eV+eDATdhmTlws8KzwAWEYvK7o9LVioEK49sQzRqWoHEOJvHSscRqnLuK+k7pK58h732jqbKT1BE/n5Qk6f0zKUvwNuDwGudDR01zjBtrgIhNutWcwC5nKW/beKXEg0jt34FOU30QsA38TMkPfT1k+2VQ6h89EMwVOMS0RIORlCVNDWDOtLkRdDFzQNdVMNwnzQuWK/B4B5aIzbIZAP30nfRO7APxGQ01m5NjCEYiJIiOj8zA3Hs9Kw7elHpUC/KcsVttFztHGKSpznC0BytHEyyaYroDOuarBDWiKi9xCDLBG9yEDle8ivmX6DFIK58l6su6Y2a/ytqEjbKEfEqCWT6gd3y2zNCH04yM69xnuq+4+cP+vDQCNSL2U/G2Mgstfx/v3/TUuOMiMDCknLGOD5yhQA1QgHRN9mUZftEMvRHc/5oqOjhTn6LYqRFCGQB0yw3Wb6qgUICkb9pEp1SgpYgK6e4prjw2JgBjKECjSzKL/A0M76Tjh+48tznlFUZRROF7EgWyJaoAEsDu8rsiyyOBHlZ4KQYf04qWGpsRsPyIHOzIASnqS0EKXjrptq+Oroh72bIHD/a4t+zdW0MWFZZYrABDe7mjcnIPnc83x0oLvyPRhRehHV9OQSGEc20jIp6IYeQ9VsfHm0iMWyFtIAwjIrNOBzAzNXDDFoLahI9Pw7hhRq6UFdVwosjEDaMMZtGmCxmVOqFVKzh1pzpUy3JGzGgC+RgosdUn5RVE+Wij+oPLeqhVNcYx762IP3ph2vErqtgOPNNNpSrzujHRqhcC3Rvw0RTSjDR0M6IJpR6ekFiXoXyl4MzUAuhBUArX4Au2qDNR0QK4hz/1BDFR8v9yBB1fRs+ru812u8+Aqb/vwDqLwlQbcQq7Jb13qLSdA+aNlHdI7XbL6/HYIhpDWZKcyw+xJqSOlpqXCgHTZsYjZPxizM7kAy6NCk+g/dFkP6sUNWZljk7llCqpi5hRmoMlytKGD0oIpgE5uuAo0dKQggb+J15vkk8IpmCQns0XMDrxl4MIyHfVRF7iIJXgJcgD3WtPxhQWvd5EMptS2JVbc5+QAOnRTdIYoTAIUIlJ47YGmn10CNddzCwLwD8fgwSuNd07EnhLYKJUaOuAJOLf8HWiyMivk5XX1XNJfpeBdPNA8plmh2rOOFRQaaIaGdFzpmG1603JumHbEMvszCoBMnRAbpkwV/0wMHuDQUiqM7syy9FrUsQ3digwGE+7ZYA8LcMhJ5zu8xgo/1GDY2NXoNRN7AHh8IB3bSGFwGkFDPTbnUkrz7Rg8OGObecU2MxUDcmyo6aj5kWVYbGacXesQgLm1iFdCg4FRkF45XP/B0VDjLSjn7gAOW1kHllPWAEpZ48HE42g9sp8lZuol+soiQt+n0EzDmJmXlocW2YomOpZw/NFwvjQC3bVpIJ4aDCYhhpiTcY4MhkodFz03tzS0651kUQSNgGBRt94vGjhCe8Mz2wceUGC51HHII6EnOEODX3Akl9ynyBBDlMUIwEg7iLduq4NuXpoAiHL2OgWYKGjFSvEb11uzl0Whir1sYpJ1ugiQor14R6jcKp3BuSGAclITdz0oDEJQmBkyrhtLOkexEvfv+ykcF22Zy4Uf3VP1NJdd6h4wtpEdPbImHniYOmRR6F6Mbs0UKgHpwlknZGC30WHqM9PAdzXc+clBV85ePyiyYPWrxlhmGtr7aEG3KtLOCVMvkj0ZAmaRYeu88uBYAGxb8yfLh457R+a9sefrss19HLpBUe2i20aH6P9L6LvUEpQ66liBrqVFO2YKQEm9k4b9gPWYDL6ELJKNUxgZGMHPfUrCi180AOwaOF5br40oHLzKNhF60SAFJpfJU7a5eii3CX9F03XbOkoABV7BxGsIJZz/xSKGKVE7rslsJjeazQ2xldyrImlERMYmh7+XNf3ZQXQoJDRqzl4etIlrxnkFxoBpjcwICopSaCmKAeAT4o1Lpt556F/84+UoxOXtsnXvTHER/+o2L3sRF4rSxnsKS1bz8k0vXvbuwcF7u2YDKN/1r0/2ctQUJUABin8BvpfTArgC7P5fmHg5evlfgAEAL2gc5Sk/bJEAAAAASUVORK5CYII=" data-filename="freescout-logo.png" style="width: 184px;"><br></div>`

**Comment by freescout-helpdesk** [comment]
How are pasting it?

**Comment by MarcoWel** [comment]
By using the toolbar (insert image button) or CTRL+V, result is the same.

**Comment by freescout-helpdesk** [comment]
This is how it should look like:

![2022-09-14_21-38-05](https://user-images.githubusercontent.com/40499291/190235700-5b36c6fb-f17a-4ec5-9ee7-9396a5ad777e.png)

Are you using any non-official modules or customizations?

**Comment by MarcoWel** [comment]
It looks like your screenshot for the standard reply within Freescout (no matter if Embed Images Module is enabled or disabled).

Within a workflow reply however, the image tag looks as follows (with Embed Images Module enabled, otherwise it is identical to the standard reply):
![image](https://user-images.githubusercontent.com/80592577/190244771-15d2afdd-c678-43e2-88e6-fdafa1fbd2a3.png)

Regardless, the mentioned error gets thrown when sending the image with Embed Image module enabled (both for standard and workflow reply). With Embed Image module disabled, sending replies works immediately again in both cases.

**Comment by freescout-helpdesk** [comment]
Fixed in Embed Image Module v1.0.2 and Workflows Module v1.0.28
