### ISSUE TITLE
more events in conversation view

### ISSUE THREAD

**Issue by Junker** [freescout-helpdesk/freescout#224]
i think should add more action events to conversation view, i.e:
@action('conversation.after_customer', $customer, $thread, $mailbox) //somewhere after customer info
@action('thread.after_body', $thread, $loop, $threads, $conversation, $mailbox) //after thread body
@action('thread.after_header', $thread, $loop, $threads, $conversation, $mailbox) //after thread header
etc..

**Comment by freescout-helpdesk** [comment]
Do you already need them?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/225
