### ISSUE TITLE
Dark Mode error

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#2240]
Dark mode is not working for me (all other modules are working fine）:

Error occured creating a module symlink (/home/admin/domains/xxx/public_html/public/modules/darkmode). Please check folder permissions.

Cache cleared successfully.
Nothing to migrate.
Error occured creating [/home/admin/domains/xxx/public_html/public/modules/darkmode] symlink: symlink(): No such file or directory
The [/home/admin/domains/xxx/public_html/public/modules/darkmode] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js

Please advise.

**Comment by freescout-helpdesk** [comment]
When it happens there is some issue with permissions on your server: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by hanetworks** [comment]
I ran both and it didn't help...

admin is the right owner in my server

chown -R admin:admin /home/admin/domains/xxxx/public_html/public/modules/darkmode
chown -R admin:admin /home/admin/domains/xxxx/public_html/


I recall that I tried darkmode download from this forum in the past and it was working. （deleted long time ago)

Now I try your darkmode and it's no longer working.

**Comment by freescout-helpdesk** [comment]
Try to manually create/fix the "/home/admin/domains/xxx/public_html/public/modules/darkmode" symlink.

**Comment by hanetworks** [comment]
I'm not a programmer and sorry I don't know about it. 😄 

So far everything else works well. I wait for future release then, maybe it will be automatically fixed.

**Comment by freescout-helpdesk** [comment]
Try to simply delete "/home/admin/domains/xxx/public_html/public/modules/darkmode" file and re-install the module.

**Comment by hanetworks** [comment]
I tried simply SSH delete "/home/admin/domains/xxx/public_html/public/modules/darkmode" file and re-install the module. => Did not work. 

Next I tried SSH delete "/home/admin/domains/xxx/public_html/public/modules/darkmode" file and activate it without re-install. => It worked!

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution.
