### ISSUE TITLE
Attachments with forwarded replies

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2241]
When forwarding a reply, Freescout adds all attachments of the whole ticket to the forward instead of the attachments of only the last reply. If this is on purpose, please add the possibility to forward a particular reply only.

**Comment by freescout-helpdesk** [comment]
Yes, it's by design. Unfortunately not plans. It can be implemented as a custom module.

**Comment by MarcoWel** [comment]
Suggested: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/385324
