### ISSUE TITLE
Allow configuration of proxy setting for WpApi

### ISSUE THREAD

**Issue by xiamaz** [freescout-helpdesk/freescout#2242]
Currently the FAQ states that if proxies are used, an exception needs to be added for freescout.net. Unfortunately this is not possible in certain deployments, were proxy usage is enforced.

Currently it is possible to make proxies work with minor modifications in the wpApi file:

```
     if ($method == self::METHOD_POST) {
            if (strstr($url, '?')) {
                $url .= '&';
            } else {
                $url .= '?';
            }
            $url .= 'v='.config('app.version');
            return $client->request('POST', $url, [
                'connect_timeout' => 10,
                'form_params' => $params,
                'proxy' => 'PROXY_URL',
            ]);
        } else {
            $params['v'] = config('app.version');
            return $client->request('GET', $url, [
                'connect_timeout' => 10,
                'query' => $params,
                'proxy' => 'PROXY_URL',
            ]);
        }
```

While this works, this requires maintaining a patchset/fork on the main release. It would be great if an environment variable or configuration parameter for a proxy setting could be added.

**Comment by freescout-helpdesk** [comment]
`APP_PROXY` variable is available in .env file now. Implemented in the `master` branch.
