### ISSUE TITLE
Thread body contains nothing but chinese (?) and ambiguous characters

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2243]
Hello, recently we received an email where the content got messed up. I tried to track down the behaviour and I think there might be a problem with the separateReply function in the fetch-emails command

https://github.com/freescout-helpdesk/freescout/blob/cc8f94fcff38ea898b994bbc9de779541880aef5/app/Console/Commands/FetchEmails.php#L945

A simple scenario based on this method

```
        $result = '';
        $body = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
        <HTML><HEAD>
        <META content="text/html; charset=unicode" http-equiv=Content-Type>
        <META name=GENERATOR content="MSHTML 10.00.9200.16618"></HEAD>
        <BODY>some content</BODY></HTML>';

        $htmls = [];
        preg_match_all("/<html[^>]*>(.*?)<\/html>/is", $body, $htmls);

        if (empty($htmls[0])) {
            $htmls[0] = [$body];
        }
        foreach ($htmls[0] as $html) {
            // One body.
            $dom = new \DOMDocument();
            libxml_use_internal_errors(true);
            $dom->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));
            libxml_use_internal_errors(false);
            $bodies = $dom->getElementsByTagName('body');
            if ($bodies->length == 1) {
                $body_el = $bodies->item(0);
                $html = $dom->saveHTML($body_el);
            }
            preg_match("/<body[^>]*>(.*?)<\/body>/is", $html, $matches);
            if (count($matches)) {
                $result .= $matches[1];
            }
        }
        if (!$result) {
            $result = $body;
        }

        echo $result;
```
The result (on my setup atleast) is

`<p>㰾䕍䅔渠浡㵥䕇䕎䅒佔⁒潣瑮湥㵴䴢䡓䵔⁌〱〮⸰㈹〰ㄮ㘶㠱㸢⼼䕈䑁㰾佂奄猾浯⁥潣瑮湥㱴䈯䑏㹙⼼呈䱍</p>`

Deleting both `libxml_use_internal_errors` calls, reveals that loadHTML struggles with the content.

`DOMDocument::loadHTML(): Couldn't find end of Start Tag meta in Entity, line: 2`

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
The problem is in `charset=unicode`
```
<META content="text/html; charset=unicode" http-equiv=Content-Type>
```

**Comment by freescout-helpdesk** [comment]
There is no such charset as "unicode". It works like this:
```
<META content="text/html; charset=utf-8" http-equiv=Content-Type>
```

**Comment by freescout-helpdesk** [comment]
This is invalid HTML, so PHP's DOM parser can't properly parse it.

![2022-09-17_09-48-06](https://user-images.githubusercontent.com/40499291/190844442-94aeeb5d-9236-4d89-bc41-a9cd671ab135.png)

**Comment by sofl88** [comment]
Thanks for the clarification. Do you plan to add some kind of sanitizer or leave it like that for now? I also noted that by adding the option **LIBXML_HTML_NOIMPLIED** to loadHTML, prevents the false result but I don't see why.

**Comment by freescout-helpdesk** [comment]
It will stay as is. There is no way to sanitize all variations of invalid HTML.
