### ISSUE TITLE
Receive emails using mailgun 

### ISSUE THREAD

**Issue by alf1e** [freescout-helpdesk/freescout#2245]
How do I receive emails if im using mailgun

**Comment by freescout-helpdesk** [comment]
As far as we know Mailgun is designed to send emails.

**Comment by alf1e** [comment]
> As far as we know Mailgun is designed to send emails.

Also has a receive mail option

**Comment by freescout-helpdesk** [comment]
Ask mailgun their IMAP settings.

**Comment by alf1e** [comment]
> Ask mailgun their IMAP settings.

https://documentation.mailgun.com/en/latest/faq-mailbox-eol.html

**Comment by maticboncina** [comment]
Looks like you need to redirect mails via their Routes feature. Basically receive a mail and immediately forward it via their SMTP infrastructure to the mailbox provider of choice (eg Gmail or hosted solution). Now what you need to do is ask <provider of choice> for those IMAP credentials.
