### ISSUE TITLE
No Browser notifications at all.

### ISSUE THREAD

**Issue by MrDecepticon** [freescout-helpdesk/freescout#2246]
I am not receiving any browser notifications when they are turned on.  I tried in multiple browsers with the correct permissions set.  I made sure browser notifications are on (as well as app notifications (iOS)).  The app notifications are a little spotty at times though.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-browser-push-notifications-are-not-working

**Comment by MrDecepticon** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-browser-push-notifications-are-not-working

I've already read the manual for this issue.  https is enabled and working properly.  Notifications are turned on for my account and they are not muted.  I checked the app logs but I don't know what I should be looking for.  There are errors but nothing that I think would have to do with browser push notifications. 

I see alot of these but I think it is my coworker (her IP) being on a proxy.

<html>
<body>


4655 | 2022/09/16 12:07:02 [crit] 78820#78820: *73154 SSL_read() failed (SSL: error:0A000126:SSL routines::unexpected eof while reading) while keepalive, client: 192.168.113.10, server: 0.0.0.0:443
-- | --
4654 | 2022/09/16 12:06:52 [crit] 78820#78820: *73149 SSL_read() failed (SSL: error:0A000126:SSL routines::unexpected eof while reading) while keepalive, client: 192.168.113.10, server: 0.0.0.0:443


</body>
</html>

And these are in the laravel:

<html>
<body>


error | production | 2022-09-15 14:26:40 | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'twoFactorAuth' in 'field list' (SQL: update `users` set `remember_token` = REDACTED, `twoFactorAuth` = REDACTED where `id` = 2) {"userId":2,"email":"andrea.REDACTED","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'twoFactorAuth' in 'field list' (SQL: update `users` set `remember_token` = REDACTED, `twoFactorAuth` = REDACTED where `id` = 2) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'twoFactorAuth' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'twoFactorAuth' in 'field list' at /var/www/html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82)
-- | -- | -- | --

</body>
</html>

Nothing in Queue and Email Fetching is normal.

**Comment by MrDecepticon** [comment]
This is odd.  I finally got a notification in Chrome.  But only one so far and I have almost everything checked for browser notifications.

**Comment by MrDecepticon** [comment]
I am now receiving push notifications but in Chrome only.  Closing this as it appears my specific issue is resolved.
