### ISSUE TITLE
Connected, but no IMAP folders found - Microsoft 365

### ISSUE THREAD

**Issue by EggermontRob** [freescout-helpdesk/freescout#2248]
Hi, 
I am succesfully connected to M365 via OAuth, but when i press the 'Get folders' button, the software says no IMAP folders found.... 
Mails aren't being imported either... What could be the issue?

Thank you!
Rob Eggermont

**Comment by freescout-helpdesk** [comment]
Feel free to send access to your FreeScout server, admin and M365 to support@freescout.net

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2264

**Comment by freescout-helpdesk** [comment]
Does the MS365 user you are using to connect have a mailbox in MS365 and able to access it (try to open https://outlook.office365.com/mail/)?
