### ISSUE TITLE
[Workflows module] cannot filter by state

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2249]
_I purchased the workflows module._

Currently it is not possible to filter a workflow by state=deleted. Please add this.

<img width="186" alt="Screen Shot 2022-09-16 at 10 17 31" src="https://user-images.githubusercontent.com/382183/190660764-0e211e1c-66c6-48b2-ab58-0489101190f6.png">

**Comment by freescout-helpdesk** [comment]
Added in Workflows Module v1.0.29

**Comment by fulldecent** [comment]
Awesome, thank you!
