### ISSUE TITLE
Dark Mode Official Module Activation Error

### ISSUE THREAD

**Issue by distresscode** [freescout-helpdesk/freescout#2250]
Freescout 1.8.24 on Cloudron. I tried deleting the dark mode folder, reinstalling and reactivating several times with no resolution.

`Cache cleared successfully.
Nothing to migrate.
Error occured creating [/app/code/public/modules/darkmode] symlink: symlink(): No such file or directory
The [/app/code/public/modules/darkmode] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js`

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2240#issuecomment-1248148277

**Comment by distresscode** [comment]
I tried the solution in comment 2240 but I get the following: 

Cache cleared successfully.
Module with the specified alias not found: darkmode

**Comment by distresscode** [comment]
Folder structure is a bit a different for us on Cloudron so that solution didn't work but here's what I did to fix it on my setup.

I used rm -r -f /path/ to delete the darkmode folder in the following places:

/app/code/Modules/DarkMode
/app/data/public-modules

Then, installed and activated the Dark Mode module and it worked!
