### ISSUE TITLE
Discards others mailbox if conversation is detected on reply.

### ISSUE THREAD

**Issue by sainf** [freescout-helpdesk/freescout#2251]
Hi.

I'll try to make the workflow as simple as I can.
- Client send email to MailBox1
- We reply to Client.
- Cliente reply email to MailBox1 and MailBox2

And we only received on Mailbox1
Confirmed with:
- to: MailBox1, to: MailBox2
- to: MailBox1, cc: MailBox2
- to: MailBox1, bcc: MailBox2

The behaviour we wanted was that it reached the 2 MailBoxes

**Comment by sainf** [comment]
The email is in the second mailbox, and it has a "Delivered-To: Mailbox2@myEmail.com" and a "From: "ClientName" <geral@clienteEmail.com>" can it be treated as a new conversation in the second mailBox?

[Example Second Mailbox Headers](https://pastebin.mozilla.org/PTpF7Dk2)

**Comment by freescout-helpdesk** [comment]
Unfortunately not. You can forward it to second mailbox.

**Comment by sainf** [comment]
So we have to educate the users... Thanks for the response.
