### ISSUE TITLE
Mailbox settings dropdown menu cropped on bottom of screen

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2252]
When having a lot of folders on the left hand side of the ticket list view, the dropdown menu will be copped on the bottom of the screen and is not accessible. This should be a simple CSS or JS fix.

![image](https://user-images.githubusercontent.com/80592577/190691641-51481bab-a225-4522-8411-a30ebcd0178d.png)

**Comment by Hatchitss** [comment]
click icon and keyboard arrow down is how I access it (not a fix i know)

**Comment by e-rwan** [comment]
adding this to the css fixed it for me : 
```
@media (min-width:991px) {
    .sidebar-2col {
        overflow-y: auto;
    }
}
```
