### ISSUE TITLE
Knowledge Base - Custom Domain

### ISSUE THREAD

**Issue by justinlosh** [freescout-helpdesk/freescout#2255]
Hello All!
Does anyone know if it's possible to setup the Knowledge Base plugin to utilize a custom domain? For example, we'd like to segment the ticketing system and publish the KB on something like docs.domain.com.

Thank you!

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible to setup a custom domain for the Knowledge Base.

**Comment by cweagans** [comment]
This is the feature I was looking for as well. Any plans to add something like that?

**Comment by freescout-helpdesk** [comment]
No for now. If someone will come up with an idea how this technically can be implemented - feel free to share.

**Comment by justinlosh** [comment]
This would probably be more feasible with docker.

**Comment by cweagans** [comment]
I don't think docker has anything to do with it. The application itself needs to understand how to differentiate between domains that a request is being sent to.

You can do this pretty easily with a middleware in Laravel: write a middleware that looks at the domain, match against the list of custom domains configured in the db, and if one matches, you can create a new request object and use that for the next middleware handler. https://github.com/fomvasss/laravel-url-aliases is a good example to look at to see how to do this (UrlAliasMiddleware in particular). https://medium.com/@fomvasss/a-little-new-about-routes-in-laravel-bba04e1aebaa has some info about how that package works. It's designed for path aliases stored in the db, but there's no reason that you couldn't use the same pattern for custom domains.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/knowledge-base/#custom-domain

**Comment by justinlosh** [comment]
Wow, thank you so much!

**Comment by RienNeVaPlus** [comment]
Anyone has a working nginx setup?  
Having multiple server_name with multiple SSL certificates listening on the same port can be tricky.
