### ISSUE TITLE
Dark mode plugin

### ISSUE THREAD

**Issue by maticboncina** [freescout-helpdesk/freescout#2256]
Hello,

If anyone owns the Dark mode module; https://freescout.net/module/dark-mode/#

Does it only apply to the admin area? We have custom CSS in place for the user interface and I wouldn't want to have that overwritten.

Best, Matic

**Comment by freescout-helpdesk** [comment]
There is no separate styles for admin and End-User Portal - they are the same. So most likely will be overwritten when dark mode is On. But End-User Portal does not have a dark mode switcher - so it should be fine.

**Comment by maticboncina** [comment]
> There is no separate styles for admin and End-User Portal - they are the same. So most likely will be overwritten when dark mode is On. But End-User Portal does not have a dark mode switcher - so it should be fine.

The admin area actually has an additional class "user-is-admin" in the body tag which can then be used in two ways (one to just apply it to the admin area) or if you use the reverse CSS option (:not) to apply it to the client area. That's why I was worried :)
