### ISSUE TITLE
Freescout is getting slow.

### ISSUE THREAD

**Issue by Arihantkankariya09** [freescout-helpdesk/freescout#2257]
Every time i open a new mail or navigate around different tabs it takes around 12-15 seconds to load, why is it getting slower?

**Comment by freescout-helpdesk** [comment]
Only a developer having access to your server can tell.

**Comment by ahmedkaludi** [comment]
@freescout-helpdesk how can we have one of your experts looking at our server situation?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
