### ISSUE TITLE
User logged in is switching to a different user ( agent) 

### ISSUE THREAD

**Issue by neillsoden** [freescout-helpdesk/freescout#2259]
We finding that at least 1/2 a day it will switch the users 

I logged in as me and when I reply to a customer, I suddenly see I've replied as a different user ( agent ) 
When I look at the top and am logged in as a different user ( Agent ) not myself 

I have to log out and log back in to get it to change

**Comment by freescout-helpdesk** [comment]
Are you using https://freescout.net/module/auto-login/ ?

**Comment by neillsoden** [comment]
Nope I have no added that module

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here as never experienced this issue. If someone will be able to reproduce feel free to fix and send a pull request.
