### ISSUE TITLE
Merge conversations

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#226]
Some customers prefere to start a new conversation for every phrases without using the existing conversation (yes, It happens,probably these customers are unable to reply to an email)

Ability to merge multiple ticket in a single one is absolutely a must. We can work on this, any suggestion on how to implement this?
In example, if multiple conversations are selected, which is the "master" conversation to use as base? The older one?

**Comment by freescout-helpdesk** [comment]
You can check how this functionality works in help scout.

**Comment by freescout-helpdesk** [comment]
https://docs.helpscout.com/article/31-merging-conversations

**Comment by guestisp** [comment]
I know that article
In that article is wrote that a popup with a confirm will open, i would like to see that

**Comment by SFFLAB** [comment]
Just wanted to indicate my strong support for this feature. The inability to merge is far and away the largest complaint I hear across the users we have. Further, for those users it is usually a _very_ significant pain point.

**Comment by caseyjhol** [comment]
@guestisp 
![image](https://user-images.githubusercontent.com/2874325/86853456-be051e80-c073-11ea-9c8c-0f026b97778f.png)

**Comment by caseyjhol** [comment]
@freescout-helpdesk I'd be interested in helping build this. Is this something you see as being a core feature added into FreeScout or as a module?

**Comment by freescout-helpdesk** [comment]
This feature should be added to the core.

**Comment by foliovision** [comment]
Just found the merge feature. Seems to work with no issues, even with multiple tickets or alternative email addresses (very useful). This is fabulous work. Thank you FreeScout Team!

**Comment by netspear** [comment]
How can we merge multiple conversations at once?

**Comment by Magneticdud** [comment]
If anyone wonders how to merge those multiple conversation (i just got a customer who sent 6 emails to say the same stuff), it's inside the menu in the ticket:

![image](https://github.com/freescout-helpdesk/freescout/assets/2940598/e418a140-7010-4961-9ea0-aafa3440ac2c)

Then choose the ticket to merge:

![image](https://github.com/freescout-helpdesk/freescout/assets/2940598/dadca599-c98e-4b0b-9df2-8d96137a8917)

both tickets need to be assigned to the same client

**Comment by Mleadg** [comment]
It would be nice to have a (maybe optional module) way to merge tickets automatically. Especially in b2c you get a lot of customers sending the same question multiple times. For my use case the preffered method would be to auto merge everything per customer e-mail address. 1 customer = 1 thread. I would buy it :)
