### ISSUE TITLE
Tag Module - List starts from the beginnig after 20 list entries

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2260]
Hi, I think there is a bug in the pagination in the tag module. When I have a long list of tags being shown in the list and when I scroll down to the 20th entry, it loads not the next bunch but the first again. My guess is that the current "page" is not submitted in the ajax request so it starts from page one again.

Thanks in advance.

https://user-images.githubusercontent.com/12407767/191263242-29c9ab37-aaae-40ed-9319-8df0d9025294.mp4

**Comment by freescout-helpdesk** [comment]
Fixed in Tags Module v1.0.21
