### ISSUE TITLE
Turn off reply to customer via notification

### ISSUE THREAD

**Issue by VacationTeam** [freescout-helpdesk/freescout#2261]
I would like to turn off the function whereby a agent gets a notification of being tagged in an email, their reply to that email gets sent to the customer.
I did not find a global setting for this feature, can you point me in the direction where that can be turned off.

Essentially we would like the replies to those notifications to show up as a note or new message, that the customer would not see.

Thank you

**Comment by freescout-helpdesk** [comment]
It's not quite clear what is needed. It looks like your request is related to Mentions Module. Feel free to submit a feature request here: https://freescout.net/request-feature/

**Comment by VacationTeam** [comment]
Thank you for the follow up.
I am trying to find a way to turn off the reply to sending to a customer:
![image](https://user-images.githubusercontent.com/90206057/191495917-5c2ce073-42ee-4e31-b053-27173ea95e57.png)
So when Chris Mentions Lucas in a note, Lucas gets a notification. Perfect.
If Lucas simply replies to the email, it sends that reply to the customer and not to Chris (the agent).
I would like to turn off, that reply going to the customer. Possibly creating a method where a reply to an email by an agent shows up as a note on the ticket instead.

I found the commands module, but my agents are not going to remember to put "@note" in the beginning of every reply to a notificaiton.
So, while I am happy to purchase the commands module, I would like to prepend all replied messages (from agents), with "@note" in a sense, creating any reply to a notification by an agent as a note on that referenced ticket.

Thank you
