### ISSUE TITLE
Ampersand in URL to image attachment not correctly encoded

### ISSUE THREAD

**Issue by bazizsafi** [freescout-helpdesk/freescout#2263]
Hi,

We're currently investigating why images included via URL are shown as unresolvable. See this screenshot:

![image](https://user-images.githubusercontent.com/54805509/191515696-bd13d3ca-4aa0-494c-8d62-7deb41689938.png)

The reason seems to be that the URL in the email source contains an ampersand (`&`) which is incorrectly encoded as `&amp;`.

Compare the incorrect URL decoded from the quoted-printable-encoded mail source (first line) to the correct URL (second line)
```
https://freescout-url.tld/storage/attachment/9/3/1/firefox_yqoWQJvLFS.png?id=15&amp;token=b2b7102a578a885b6dba882825915184
https://freescout-url.tld/storage/attachment/9/3/1/firefox_yqoWQJvLFS.png?id=15&token=b2b7102a578a885b6dba882825915184
```

We're using the currently latest version 1.8.26 of FreeScout, we use Apple Mail 13.4 (3608.120.23.2.7) and newer on macOS as mail clients.

**Comment by freescout-helpdesk** [comment]
In HTML ampersands in URLs must be encoded as `&amp;`.

**Comment by bazizsafi** [comment]
Ah, yes, you're right!

It turns out the unresolvable images where due to an HTTP Basic Authentication restricting access to our FreeScout instance. Mail clients trying to resolve the image link were not able to authenticate, of course, so the image couldn't be loaded.

My bad, sorry to waste your time.
