### ISSUE TITLE
Is there a way to manually download modules?

### ISSUE THREAD

**Issue by cweagans** [freescout-helpdesk/freescout#2266]
I'm planning on purchasing several modules, but I don't want to use the UI to manage them (and won't have the Modules directory writable by the webserver) because I need to keep my Freescout instance under version control. Is there some other way to download purchased modules?

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. You can exclude Modules directory from version controlling.

**Comment by cweagans** [comment]
Well that's one part of it, but the other part is that by policy we can't have our applications modifying themselves. Even if the directory wasn't version controlled, it still won't be writable in production. I really need a way to do this, even if it's kludgy.

The module installer has to download the modules from *somewhere*. Can't I just download them manually?

**Comment by freescout-helpdesk** [comment]
The only way is to create another FreeScout installation and download them there.

**Comment by cweagans** [comment]
That doesn't appear to work. I'd have to deactivate all of the modules in production so that I can activate them on my local dev site, run the updates, commit, deactivate all the modules on my local dev site, push to prod, and then reactivate all the modules.

This is really really really painful and I'm pretty sure it would cause data loss. Surely there's _some_ way to do this in a reasonable manner? I just dropped over $100 on modules. Please help me deploy them in a way that follows 2022 best practices.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Development-Process

**Comment by cweagans** [comment]
I'm not asking you to develop a new feature. I'm simply asking for a way to download modules that I paid for so that I can actually deploy them and keep them updated.

I am unable to run an application in production that modifies itself. I would be astounded if I'm the first person to be bound by this policy _especially_ for an application that contains PII. Nevertheless, I purchased the modules specifically because you gave me a workaround that seemed reasonable, but it didn't actually work. Now I'm stuck and I don't know what to do.

The files exist somewhere on the internet, right? If you have even very rough information about that location, I can probably run with it. Happy to keep all of that info confidential as well if you're worried about people abusing it.

**Comment by cweagans** [comment]
I broke out the debugger and have a solution. I can either keep it to myself or write it up somewhere. What would you prefer?
