### ISSUE TITLE
Some texts can´t be translated.

### ISSUE THREAD

**Issue by mssmello** [freescout-helpdesk/freescout#2268]
Hello, 
Noted that the texts below at file user_setup.blade.php can´t be translated in any language. 
Check this list:

Welcome to :company_name, :first_name!
Let's setup your profile.
Your Email
Your password must be at least 8 characters
Only visible in :app_name.
Image will be re-sized to 200x200. JPG, GIF, PNG accepted.

BR

**Comment by freescout-helpdesk** [comment]
Yes. We still can't figure out why.
