### ISSUE TITLE
List of available languages is incomplete

### ISSUE THREAD

**Issue by Iniretur** [freescout-helpdesk/freescout#2269]
In the choice of languages, there are not all existing languages, I would like to add Azerbaijani, for example
![image](https://user-images.githubusercontent.com/57409306/191708984-e3680628-54a2-44e1-8619-3c4e21ff356d.png)

**Comment by freescout-helpdesk** [comment]
Language has been added in the `master` branch.

**Comment by Iniretur** [comment]
I'm trying to translate the app, but there is nothing to translate
![image](https://user-images.githubusercontent.com/57409306/192846152-2f7d3eea-8397-46e6-ba35-d24a49db79eb.png)
