### ISSUE TITLE
Configuring email

### ISSUE THREAD

**Issue by sunchaser68** [freescout-helpdesk/freescout#2270]
Hi, i managed to make freescout work by configuring fetching email by using yahoo pop3, but my users in order to open a ticket, will need to write a mail like"appsupport"@yahoo,it"...

What i need to do in order that my users may send a mail to my domain (example support@example.com)?

Thanks

**Comment by freescout-helpdesk** [comment]
You need to set up an email on example.com domain - contact your hosting support on how to do it.

**Comment by sunchaser68** [comment]
the server is a VPS and is mine. I installed postfix. Do i need to install a pop3 server?

thanks

**Comment by maticboncina** [comment]
You need more than just postfix. Consider using something like https://mailcow.email/ - Also no POP3 won't work, you need IMAP.

**Comment by maticboncina** [comment]
Or consider getting web hosting and just use that for email hosting (point MX to there and nothing else). Any web hosting will do.

**Comment by sunchaser68** [comment]
Hi, thanks for the reply. I used a email address on yahoo.com and the mail routing services of cloudflare, seems working.

**Comment by sunchaser68** [comment]
Yes i used yahoo as imap, thanks again.
