### ISSUE TITLE
outgoing mails saved on the imap-server are missing a "date" field in the header and have a wrong charset encoding

### ISSUE THREAD

**Issue by cluster15** [freescout-helpdesk/freescout#2271]
Subject says it all:

In our sent folder the beginning of a mail looks like this:

From: helpdesk@server.domain
Subject: Re: dritte Anfrage
To: client@some.domain
MIME-Version: 1.0
Content-Type: TEXT/html; CHARSET=US-ASCII
References: <4405b9f2-1b69-ef7a-663e-39b6da0f3218@some.domain>
In-Reply-To: <4405b9f2-1b69-ef7a-663e-39b6da0f3218@some.domain>

&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta content="text/html; charset=utf-8" http-equiv="Content-Type"&gt;
    &lt;meta name="viewport" content="initial-scale=1.0"&gt;
    &lt;style&gt;
        p { margin:0 0 1.6em 0; }
        pre { font-family: Menlo, Monaco, monospace, sans-serif; padding: 0 0 1.6em 0; color:#333333; line-height:15px; }
        img { max-width:100%; }
        a { color: #346CC4; text-decoration:none; }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body style="-webkit-text-size-adjust:none;"&gt;

A date-field is missing from the header and the CHARSET in content-type is US-ASCII while the <meta-content ... > further below in the html-content of the message states that it is "utf-8". 

Consequences: Using a normal email-client (only as a fall-back in case the helpdesk-system is not available), it is impossible to see when a mail was sent and UTF-8 chars outside of the US-ASCII range are illegible.

**Comment by freescout-helpdesk** [comment]
Fixed in https://github.com/freescout-helpdesk/freescout/issues/1892#issuecomment-1253724814
