### ISSUE TITLE
Feature Request  : Autocomplete feature for saved responses

### ISSUE THREAD

**Issue by S0mething4m3** [freescout-helpdesk/freescout#2272]
We just started using/testing your freescout system. Everything looks great but we are missing a few features.  I’m currently migrating from this system  Help Desk MX  https://mirasvit.com/magento-2-extensions/helpdesk.html .

One of the features is autocomplete when typing a response . in Help Desk MX they call saved responses  “quick responses” . 

When we start typing a response, the system will search through all “saved responses” (texted entered will attempt to match in saved responses”  and show as options above. 
@
Zendesk has a similar feature in live  #chat.

Can this be added? I would pay for this feature.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
