### ISSUE TITLE
Move mysql database

### ISSUE THREAD

**Issue by askleo** [freescout-helpdesk/freescout#2274]
I have a local install of freescout, working great.

It's configured to use <some server> as it's database server, and I'd like to switch that to localhost. I have all the details of moving a MySql database from one place to another nailed -- except for how to tell freescout to look here instead of there. Are the database server and credentials stored somewhere easy to update? I couldn't find them.

**Comment by freescout-helpdesk** [comment]
DB credentials are stored in .env file. Change them and clear the cache.
