### ISSUE TITLE
Team only displays in one mailbox even when it has access to multiple

### ISSUE THREAD

**Issue by shanebreckon** [freescout-helpdesk/freescout#2275]
I have several teams that have access to multiple mailboxes.
This is an example of one showing access to all mailboxes. [https://ibb.co/3k1LHLv](https://ibb.co/3k1LHLv)

This team displays in one of the mailboxes folder list but not in any of the other mailboxes it has access to.
[https://ibb.co/hfmzSWT](https://ibb.co/hfmzSWT) vs. [https://ibb.co/cL9N19w](https://ibb.co/cL9N19w)

Note: I can still assign a conversation to a team from within a mailbox that doesn't display that teams folder, but the only way to view it is within the "Assigned" folder as the teams folder is not visible.

How do I make a team have a folder in each of the mailboxes it has access to?

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of the module and FreeScout?
Try to disconnect the Team from the mailbox and connect again in Team's settings.

**Comment by shanebreckon** [comment]
Thank you. Removing team access to a mailbox and then adding again worked.
