### ISSUE TITLE
Upgrading Freescout on IIS

### ISSUE THREAD

**Issue by arborrow** [freescout-helpdesk/freescout#2276]
I have Freescout version 1.8.22 installed and would like to upgrade to the latest version; however, I am getting an error when the upgrade script tries to move the vendor file to vendor_tmp. I'm more familiar with Linux file permissions and much less familiar with Windows file permissions. I'm curious if this is an issue you have come across before and if there is a workaround to configure the server so that I can get the upgrade working from the web interface. I understand there are options in case we are not able to get it working but figured it was worth checking to see if there was something I might do on the configuration side first because moving forward it would be better to be able to upgrade through the web interface. I did a quick look through the source code and I'm thinking that it is getting hung up in the createReleaseFolder method. What is interesting is that I do see the 1.8.27 folder created with the vendor folder and subfolders in it. I realize that this is probably an edge case scenario but if you happen to have any suggestions they would be greatly appreciated. Peace - Anthony

![Screenshot from 2022-09-26 11-57-35](https://user-images.githubusercontent.com/532371/192248864-6fd08e0d-59ef-48be-a7f6-5b74d7286b40.png)

**Comment by freescout-helpdesk** [comment]
It seems to be some very specific issue. We'll leave it open for 1-2 weeks. Maybe someone will help.

**Comment by arborrow** [comment]
Sounds good, thanks for the reply. Peace - Anthony
