### ISSUE TITLE
CustomSignatures - Wrong policy used for saving additional signatures (?)

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2277]
Hi, today we noticed that users who are not admin but have the "edit email signature" permission are not able to edit/save new custom signature (Custom Mailbox Signatures Module). I don't know if this is intended but the user don't even get an error message and we would like to give them atleast the permission to add, edit and update custom signatures.

My guess is that there is the policy/permission `updateSettings` instead of `updateEmailSignature` used

```
        \Eventy::addAction('mailbox.settings_before_save', function($mailbox, $request) {
            if (!\Auth::user()->can('updateSettings', $mailbox)) {
                return;
            }
```

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Mailbox Signatures Module v1.0.6
