### ISSUE TITLE
SMTP Send Error

### ISSUE THREAD

**Issue by sigorajason** [freescout-helpdesk/freescout#2279]
I am trying to setup SMTP to send emails. I use office365 for my email but clearly my domain is not hosted there. I get this error:

Send error. stream_socket_enable_crypto(): Peer certificate CN=`*.a2hosting.com' did not match expected CN=`smtp.office365.com'. Message-ID:

**Comment by freescout-helpdesk** [comment]
https://smackdown.blogsblogsblogs.com/2021/08/28/peer-certificate-did-not-match-smtp-office365-com/
