### ISSUE TITLE
[feature request] GDPR API question

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#2281]
@freescout-helpdesk 

Would it be possible to add an API request to remove all user data and conversations?

Currently, we only see this
https://api-docs.freescout.net/#delete-conversation

M

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by raramuridesign** [comment]
@freescout-helpdesk as requested

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/386491
