### ISSUE TITLE
CustomFields dropdown with many options

### ISSUE THREAD

**Issue by Iniretur** [freescout-helpdesk/freescout#2283]
When I'm trying to add multiple options to the dropdown, it appears empty if I add more than 1108 lines at once, on dropdown creation. I can add exactly 1108 lines and then add options manually, one by one, which is a huge time loss.

![image](https://user-images.githubusercontent.com/57409306/192717052-f3f7a621-894e-4143-96ed-bf77c1bc8d6f.png)

**Comment by Iniretur** [comment]
UPD: I tried to add lines one by one, but the same problem appears if I add more than 1133 lines.

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Fields v1.0.17
