### ISSUE TITLE
Trash folder is hidden although it contains conversations

### ISSUE THREAD

**Issue by sannc** [freescout-helpdesk/freescout#2284]
I am not sure whether this is a bug or a feature …

**Even if** the trash folder contains conversations is hidden unless you select the "closed" folder - then it appears and I can select it e.g. to empty it. 

I observed this behaviour from the very beginning when we started to use FreeScout more than a year ago and it is still present in version 1.8.28.

The expected behaviour would be that the trash folder is visible as soon and as long as it contains conversations. 

Please enlighten me :-)

**Comment by freescout-helpdesk** [comment]
It's by design. `Deleted` folder becomes visible only after opening `Closed` folder.
