### ISSUE TITLE
Error sending emails to customers

### ISSUE THREAD

**Issue by bnewman20** [freescout-helpdesk/freescout#2285]
When sending emails we are getting the following error. 

Undefined offset: 0 (View: /var/www/html/resources/views/emails/customer/reply_fancy.blade.php); File: /var/www/html/overrides/laravel/framework/src/Illuminate/Support/Collection.php (1710)
--

We are using Office365 / Exchange for email. 

Any ideas? It started after the last update. 1.8.28

On the UI this shows up. 
![image](https://user-images.githubusercontent.com/60909819/192840203-9cfcddc1-9816-473d-a561-9bca1a60285c.png)

**Comment by freescout-helpdesk** [comment]
Could you please give the full error message from Manage > Logs > App Logs

**Comment by bnewman20** [comment]
This is the full error.

[errorproduction2022.txt](https://github.com/freescout-helpdesk/freescout/files/9667337/errorproduction2022.txt)

**Comment by bnewman20** [comment]
Thanks for replying so quickly. 


We did notice that there are a lot of Queued jobs.

![image](https://user-images.githubusercontent.com/60909819/192845620-0396791b-6448-4e43-9685-374a81051761.png)

**Comment by bnewman20** [comment]
Thank you so much! That seems to have fixed the issue! Whoop!

If you need anything else please let us know!
