### ISSUE TITLE
Custom domain with knowledge base module does not work due to missing `Access-Control-Allow-Origin`

### ISSUE THREAD

**Issue by nebulade** [freescout-helpdesk/freescout#2287]
Initially reported at https://forum.cloudron.io/topic/7702/fyi-knowledge-base-custom-domains which already has some context.
So when a custom domain is set for the knowledge base, the `Access-Control-Allow-Origin` headers are not sent from the main domain. This affects at least the fonts.

One solution is to set those [headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) accordingly or maybe all resources should be fetched using the custom knowledgebase origin.

**Comment by freescout-helpdesk** [comment]
We've checked - when Knowledge Base is opened on a custom domain all CSS files are loaded from the custom domain too, including fonts CSS: https://demo.freescout.net/css/fonts.css

And fonts CSS have relative paths to fonts (`../../fonts/liberation-sans/LiberationSans-Bold-webfont.eot`), so there should be no problems with fonts being requested from another domain.

**Comment by freescout-helpdesk** [comment]
We've reproduced it. It works fine with `APP_ENV=local` but not in production environment.

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module v1.0.38

**Comment by nebulade** [comment]
Thanks! I can confirm this is working now.
