### ISSUE TITLE
Send error

### ISSUE THREAD

**Issue by donaldsv** [freescout-helpdesk/freescout#2288]
I have queued jobs for : App\Jobs\SendReplyToCustomer with multiple attempts. When I check the logs I get this error message:

Send error. Undefined array key 0 (View: .../public_html/resources/views/emails/customer/reply_fancy.blade.php). Message-ID: reply-4052-90525e70b7842930586545c6f1c9310c@mydomain.com

And the error in the send logs:
Undefined array key 0 (View: 
.../public_html/resources/views/emails/customer/reply_fancy.blade.php); File: .../public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php (1710)

I've made some internal tests, even tried to delete and create a new mailbox but still impossible to send replies.

*Running version 1.8.28

**Comment by freescout-helpdesk** [comment]
Fixed in 1.8.29 release.
