### ISSUE TITLE
Permissions - only allow user to draft replies but not send them out

### ISSUE THREAD

**Issue by maxrenneberg** [freescout-helpdesk/freescout#2289]
Dear forum,

I am trying to find a way to let a user only reply as a draft and never be allowed to communicate with the customer.
The administrator will pick up the draft and send it out.

Btw, is there a way to send out multiple drafts at once? Right now I have to go into every draft and send it manually.

Apart from this, Freescout is a very nice tool and I like the no-frills approach + module upgradability!

Thanks,
Max

**Comment by freescout-helpdesk** [comment]
> Btw, is there a way to send out multiple drafts at once? Right now I have to go into every draft and send it manually.

Unfortunately not.

Feel free to submit feature requests: https://freescout.net/request-feature/
