### ISSUE TITLE
Whatsapp module problem.

### ISSUE THREAD

**Issue by mssmello** [freescout-helpdesk/freescout#2290]
Hi, I´m using the Whatsapp module. Installed ok, and the onboarding process done at Chat-Api, I run some tests and it was ok. Msgs sent to my number were received on Freescout mailbox and answered, they were received on the origem number instantly.
Then I received lots of emails about Templates rejected and now I can receive msgs on Freescout but when I answer, msg takes hours to reach destination. 
Already asked for help on Chat-Api but they look like not sure what could be the problem.
Have you already seen something like? 
Thanks.

**Comment by freescout-helpdesk** [comment]
We have not experienced this. You may need to debug it yourself. Make sure that background jobs in Manage > System > Status are processed on time.

**Comment by mssmello** [comment]
Hi, my cron job fetch-emails is running ok, but I see a lot of fails like:
1. App\Jobs\TriggerAction
Queue	default
Fail at	Sep 30, 2022 08:20:13

How can I solve this?
Thanks!

**Comment by mssmello** [comment]
Hi, I think I found the problem,, my number wasn´t saved in any users on FreeScout. I´ve filled it on my user and now msgs are going ok. 
[WhatsApp Webhook] (WhatsApp) Could not import your own message sent directly from WhatsApp on mobile phone as a response to customer. Could not find the user with the following phone number: 551143807474. Make sure to set this phone number to one of the users in FreeScout.

I still see the error below about invalid data,, what could it be? 

[WhatsApp Webhook] (WhatsApp) Webhook triggered but invalid data received: {"ack":[{"id":"gBGHVRmZUZdzLwIJJ3C5ey3WeP8i","chatId":"5519995197732@c.us","status":"read"}],"instanceId":457431}

Thanks!

**Comment by freescout-helpdesk** [comment]
Congratulations. 

> [WhatsApp Webhook] (WhatsApp) Webhook triggered but invalid data received: {"ack":[{"id":"gBGHVRmZUZdzLwIJJ3C5ey3WeP8i","chatId":"[5519995197732@c.us](mailto:5519995197732@c.us)","status":"read"}],"instanceId":457431}

These messages can be ignored.
