### ISSUE TITLE
[feature request] SMS Notifications via Twilio

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2291]
I just saw the new Module for SMS notifications via MessageBird.
However, I wanted to know if there is any way to enable SMS notifications via Twilio instead. After further research and when I tried to sign up for MessageBird, I found out that sending SMS messages to the USA would cost much higher than their listed pricing as it includes Yearly 10DLC Registrations Fees and additional Carrier Pass Through Fees.

I wanted to know if I could Request SMS notifications via Twilio? I'm sure any other FreeScout Users in the USA would definitely want this as well.

Really love using FreeScount! and I really appreciate it. 

Thank you!!

**Comment by freescout-helpdesk** [comment]
Maybe in the future. Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by netspear** [comment]
I opened a feature request for this.
If anyone else can vote on it, that would be great!!

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/392193
