### ISSUE TITLE
End user portal: use editor

### ISSUE THREAD

**Issue by weeblr** [freescout-helpdesk/freescout#2293]
Hi

Unless I missed something, the end-user portal module only shows a basic input field for customers to enter their requests, or reply to existing tickets.

I'd like them to use the same editor (including the extended editor module we purchased).

Is this possible, through a filter for instance?

Best regards

**Comment by freescout-helpdesk** [comment]
Sure. Feel free to add a filter/action: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by weeblr** [comment]
Sorry, I don't understand what you mean? Is it me who is supposed to add a hook? or such a hook already exists?

My question is not about forking the module but instead make use of an existing hook. Does that hook exist?

**Comment by freescout-helpdesk** [comment]
No. You can add it and submit updated module: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
