### ISSUE TITLE
OVH shared hosting instalation, :schedule:run not working and queue:work timeout

### ISSUE THREAD

**Issue by e-rwan** [freescout-helpdesk/freescout#2294]
hello,
I've been trying for a few days to setup a simple freescout on our ovh shared hosting and it has proved a bit difficult so far.
Setting up cron tasks on ovh is limited in what it allows as  it can only been called once every hour and you cannot pass any argument.
here is what my cron tasks look like:
![cron-ovh02](https://user-images.githubusercontent.com/7847769/193279594-24012e96-3d63-4e00-9d2c-7bd1a55f9451.JPG)
![cron-ovh01](https://user-images.githubusercontent.com/7847769/193279894-207d7a41-9f1c-40e8-97c8-9643d2c474f1.JPG)
the cron calls for artisan-exec.php (every 23/16min approximately) which is this little php script that I use to pass the arguments to artisan and repeat the command every 100s: 

```
#!/usr/local/bin/php
<?php
define('ROOT',dirname( __FILE__ ));
for ($i = 1; $i <= 9; $i++) {
$output1 = shell_exec('export PHP_PATH=/usr/local/php7.4/bin/php; $PHP_PATH ' . ROOT . '/artisan schedule:run >> "' . ROOT . '/storage/logs/schedule.log"  2>&1');
$output4 = shell_exec('export PHP_PATH=/usr/local/php7.4/bin/php; $PHP_PATH ' . ROOT . '/artisan freescout:fetch-emails > "' . ROOT . '/storage/logs/fetch-emails.log" 2>&1');
$output5 = shell_exec('export PHP_PATH=/usr/local/php7.4/bin/php; $PHP_PATH ' . ROOT . '/artisan queue:work --queue="emails,default" --sleep=5 --tries=1 >> "' . ROOT . '/storage/logs/queue-jobs.log" 2>&1');
sleep (100);
}
?>
```

So far artisan schedule:run has never worked, neither to fetch the emails nor to process the queue, adding artisan freescout:fetch-emails  has solved the first issue but rtisan queue:work on the other hand is problematic.
Also, using the link provided in the system page to manualy trigger artisan has never worked either ([/freescout/system/cron/4f31093ddd4c1dcad2dfa4670afdaf88](https://domainname.com/freescout/system/cron/4f31093ddd4c1dcad2dfa4670afdaf88))

artisan queue:work does effectivly process the queue but seems to timeout every time, i get the following error on the ovh cron and ftp logs : 
```
[2022-09-30 14:32:01] ## OVH ## START - 2022-09-30 14:32:01.768196 executing: /usr/local/php7.3/bin/php /homez.669/paulanth/www/freescout/artisan-exec.php 
[2022-09-30 14:32:01] 
[2022-09-30 14:32:01] 
[2022-09-30 14:32:01] ## OVH ## ERROR - CRON TASK INTERRUPTED BY OVH - reason: the duration of your script exceeded the maximum permitted (3600 seconds)
[2022-09-30 14:32:01] ## OVH ## END - 2022-09-30 15:32:03.790830 exitcode: 255
[2022-09-30 14:48:02] ## OVH ## START - 2022-09-30 14:48:02.466119 executing: /usr/local/php7.4/bin/php /homez.669/paulanth/www/freescout/artisan-exec.php 
[2022-09-30 14:48:02] 
[2022-09-30 14:48:02] 
[2022-09-30 14:48:02] ## OVH ## ERROR - CRON TASK INTERRUPTED BY OVH - reason: the duration of your script exceeded the maximum permitted (3600 seconds)
[2022-09-30 14:48:02] ## OVH ## END - 2022-09-30 15:48:04.486846 exitcode: 255
```
```
[2022 Sep 30 10:02:58] (xxx) [DEBUG] Command [stor] [/www/freescout/artisan-exec.php]
[2022 Sep 30 10:02:58] (xxx) [NOTICE] /homez.669/paulanth//www/freescout/artisan-exec.php uploaded  (889 bytes, 75.21KB/sec)
[2022 Sep 30 10:02:59] (xxx) [DEBUG] Command [cwd] [/www/freescout/]
[2022 Sep 30 10:02:59] (xxx) [DEBUG] Command [pasv] []
[2022 Sep 30 10:02:59] (xxx) [DEBUG] Command [list] []
[2022 Sep 30 10:04:59] (xxx) [INFO] Timeout - try typing a little faster next time
[2022 Sep 30 10:04:59] (xxx) [INFO] Timeout - try typing a little faster next time
```

which leads to ovh disabling the cron tasks for repeated failure.
queue-jobs.log is always empty and using >> /dev/null 2>&1 instead of loging will solve the timeout issue but then the queue won't process anymore...
and the queue:work in the system page never seems to update : 
![freescout-sys](https://user-images.githubusercontent.com/7847769/193286864-b80d7b6b-77b7-4c4b-8b04-35a22d7fbe66.JPG)

any idea on how I could solve this queue:work issue and if I did something wrong?
also does anyone have experience with setting up freescout on ovh or others and would have some advice?
maybe it just a bad idea to install such software on a shared hosting?

**Comment by e-rwan** [comment]
I was making some more test by upgrading from php 7.4 to 8.0 on the ovh conf panel and sending email with freescout got processed right away even though all my cron jobs are deactivated.
does it mean that with php 8.0 I could remove the queue:work command from my scrit all together?
php 8.0 messes up our wordpress theme so that would need some other work...

**Comment by e-rwan** [comment]
so after some research it seems the issue I have is comparable to the one in that post:
https://laracasts.com/discuss/channels/laravel/schedulerun-not-calling-artisan-command
but I couldn't find any solutions to it.

if I run artisan schedule:run I get : 
```
shedule-run : Running scheduled command: '/usr/local/php7.3/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/usr/local/php7.3/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '/usr/local/php7.3/bin/php' 'artisan' queue:work --queue='emails,default,b99bd41c908ceea83eb7e06ec1f9c3aa' --sleep=5 --tries=1 > '/home/paulanth/www/freescout/storage/logs/queue-jobs.log' 2>&1
```
but none of the liste command are actually executed and no logs are created,  while runing the command manualy will work.

so I could make a script that run fetch-email and queue every minutes but none of the other sheduled command from the kernel shall be executed.

**Comment by freescout-helpdesk** [comment]
It looks like here https://github.com/freescout-helpdesk/freescout/issues/252 someone managed to make FreeScout running on OVH.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
