### ISSUE TITLE
Cron Error 409 Conflict : Script already running

### ISSUE THREAD

**Issue by philippschlup** [freescout-helpdesk/freescout#2296]
Guten Abend

Ich habe leider das Problem das jedes Mal wenn der Cron eine Abfrage machen will die Meldung (Conflict : Script already running) kommt.

Wo liegt das problem?
Ich kann leider auch keinen Cron Command ausführen und muss es über den Link machen.

Danke für jede Hilfe

**Comment by philippschlup** [comment]
Good evening

I have unfortunately the problem that every time the cron wants to make a query the message (Conflict : Script already running) comes.

Where is the problem?
Unfortunately I can not run a cron command and have to do it via the link.

Thanks for any help

**Comment by freescout-helpdesk** [comment]
"Conflict : Script already running" - FreeScout does not have such a message in it's code.

It looks like you need a developer who can check it on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)
