### ISSUE TITLE
Can't update the app

### ISSUE THREAD

**Issue by pogla** [freescout-helpdesk/freescout#2297]
I'm trying to update the app but nothing happens. Here is the video:

https://user-images.githubusercontent.com/6359466/193400408-5238985a-287c-49dd-86b9-94b621b88dfd.mov

Here is the only log file I see:

[laravel-2022-10-01.log](https://github.com/freescout-helpdesk/freescout/files/9689906/laravel-2022-10-01.log)

**Comment by freescout-helpdesk** [comment]
Sometimes it happens. Follow https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
