### ISSUE TITLE
https on KB's custom domain

### ISSUE THREAD

**Issue by hanetworks** [freescout-helpdesk/freescout#2298]
The question is, where do I generate ssl for KB's custom domain?

**Comment by freescout-helpdesk** [comment]
SSL on your custom domain you configure the same way as for the main domain - on your web server.

**Comment by hanetworks** [comment]
so I create a subdomain under cPanel, then generate ssl, that will work? but it applies to different directory right?

**Comment by freescout-helpdesk** [comment]
Read "Custom Domain" section at https://freescout.net/module/knowledge-base/
