### ISSUE TITLE
Change order / list of folders

### ISSUE THREAD

**Issue by weeblr** [freescout-helpdesk/freescout#2299]
Hi,

We have used the Custom folders module to add some more useful folders than the default ones:

![image](https://user-images.githubusercontent.com/5846185/193537079-9b47e3dc-2ffe-46dc-b8c3-b7c926c3046c.png)

I'd like to know if there's a way to:

- change the order of folders displayed for a mailbox: we'd prefer our having our custom folders **BEFORE** the default ones, which are not really useful for us
- alternatively, is there a way to hide some folders?

A filter on the list of folders would be perfect but I could not find any.

Best regards

**Comment by Hatchitss** [comment]
+1 also looking to do exactly this. Our custom folders at the top.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
