### ISSUE TITLE
Gmail SMTP relay not working, but when I run the test, it works

### ISSUE THREAD

**Issue by siriusdarkmattersun** [freescout-helpdesk/freescout#2301]
Freescout installed in Docker, version 1.8.29.

I have set up smtp-relay.gmail.com to send email from our Freescout instance.
It works when I perform a test, and the email is sent without error and almost immediately.

However, when the system uses the same SMTP service to send automated email to the same email address (automated ticket response, for example), the following error is seen.

_Send error. Expected response code 250 but got an empty response. Message-ID: reply-4-a87ff679a2f3e71d9181a67b7542122c@xxx.xxx.xxx

Any ideas as to what is happening, or what I can check?

Thanks
Jason

**Comment by freescout-helpdesk** [comment]
It's hard to tell what can be the reason. Try to clear the cache and make sure you are using the latest FreeScout version.
