### ISSUE TITLE
I am getting these errors in logs.

### ISSUE THREAD

**Issue by Arihantkankariya09** [freescout-helpdesk/freescout#2305]
I have filled all the info correctly, still these errors are occurring on loop.There are other products too which are working perfectly with their respective details.

[Edd] HTTP Status Code: 404 (Store not found at the specified URL) :: Requested resource: gnpublisher.com/edd-api/sales/

[Edd] HTTP Status Code: 403 (Authentication or permission error, e.g. incorrect API keys or your store is protected with Basic HTTP Authentication) :: Requested resource: microwork.dev/edd-api/sales/

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. The problem need to be investigated on your server.
