### ISSUE TITLE
Darkmode Module

### ISSUE THREAD

**Issue by A3o** [freescout-helpdesk/freescout#2307]
New darkmode module with the slider at the top.  I can turn the slider back to non-dark mode and as soon as I change pages, leave freescout, etc. it reverts back to darkmode.

Darkmode module installed & licensed is Version: 1.0.9
Freescout App Version 1.8.29

**Comment by freescout-helpdesk** [comment]
See description of  “prefers-color-scheme” option: https://freescout.net/module/dark-mode/

**Comment by francislavoie** [comment]
I'm coming here from trying the demo. The behaviour of dark mode is definitely not ideal. If I click the switch, as soon as I do any kind of page change, it reverts to the browser setting. That doesn't make much sense. Toggling the switch should set a cookie or a value in local-storage to remember the user's preference. Might need a little `x` next to it to clear the preference, I guess.

**Comment by freescout-helpdesk** [comment]
> I'm coming here from trying the demo. The behaviour of dark mode is definitely not ideal. If I click the switch, as soon as I do any kind of page change, it reverts to the browser setting. That doesn't make much sense. Toggling the switch should set a cookie or a value in local-storage to remember the user's preference. Might need a little `x` next to it to clear the preference, I guess.

It does set a cookie. Something must be wrong with your browser settings.
