### ISSUE TITLE
oauth module doesn’t work with Github oauth

### ISSUE THREAD

**Issue by cweagans** [freescout-helpdesk/freescout#2309]
It looks like the oauth module doesn’t work with Github oauth. I tried setting it up using the params provided by Github, but there’s always an error acquiring the token. Have you considered using Socialite or a similar package that has all of the authentication stuff already figured out?

I’m hoping to be able to authenticate with Github and limit access to people who are members of a particular Github organization (ideally, part of a particular team within an organization, but not strictly necessary).

**Comment by freescout-helpdesk** [comment]
GitHub has been added in OAuth & Social Login Module v1.0.1

> limit access to people who are members of a particular Github organization (ideally, part of a particular team within an organization, but not strictly necessary)

Unfortunately no plans to implement this.

**Comment by cweagans** [comment]
For anyone searching for this in the future, here's a hook you can drop into a module to only allow users in an org to log in through Github:

```php
        \Eventy::addFilter('oauthlogin.get_user_data', function($user_data, $provider, $ch, $user_curl_opt) {
            $membership_curl_opt = $user_curl_opt;
            $membership_curl_opt[CURLOPT_URL] = 'https://api.github.com/orgs/yourorg/members/' . $user_data['login'];
            $membership_curl_opt[CURLOPT_FOLLOWLOCATION] = true;

            curl_setopt_array($ch, $membership_curl_opt);
            $membership_response = curl_exec($ch);
            $membership_response_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

            if ($membership_response_code != 204) {
                $msg = __('You must be a public member of the Your Org organization to access this application.');
                \OauthLogin::log($msg);
                \Helper::addFloatingFlash($msg);
                return [];
            }

            return $user_data;
        }, 30, 4);
```

Keep in mind that this only works if the membership in the organization is set to "Public".
