### ISSUE TITLE
PERSON_CUSTOMER Not being set correctly

### ISSUE THREAD

**Issue by sideshot** [freescout-helpdesk/freescout#2310]
These two fields don't seem to be changed.

https://github.com/freescout-helpdesk/freescout/blob/098b830a0843e48f8747bef938a6d745d1fcdc83/app/Conversation.php#L45-L51

**Comment by sideshot** [comment]
We are trying to use the "customer_reply" is not within X days filter for the workflow. It isn't working.  When I looked into it.  This line of code is preventing it from happening.  

Line 952 Workflow.php
```
                        if (!$number || !$metric || $conversation->last_reply_from != Conversation::PERSON_CUSTOMER) {
                            continue 2;
                        }
```
number = 12| metric = h | conversation->last_reply_from = 2| Conversation::PERSON_CUSTOMER = 1

It's because Conversation::PERSON_CUSTOMER = is hard set at 1 in the APP\Conversation.php

    const PERSON_CUSTOMER = 1;
    const PERSON_USER = 2;

**Comment by sideshot** [comment]
After looking into it deeper.  It seems the logic is flawed.  It will evaluate if the last reply was from that user.  So if you want the CUSTOMER hasn't responded in 12 hours.  Then you need to put the dropdown as "Last User Reply" is not in 12 hours.  Because the field it looks at is last_user_reply.

This would be better if it looked through the threads for the last response from customer, and user so you could evaluate both if needed.  

Then add a new filter.  Last Reply from (user or customer)

**Comment by freescout-helpdesk** [comment]
The code is correct.

Try to add “New / Reply / Moved” condition.
