### ISSUE TITLE
Module - Two-Factor Authentication not upgrading

### ISSUE THREAD

**Issue by arborrow** [freescout-helpdesk/freescout#2311]
I attempted to upgrade the 2FA module; however, after 'successfully' running the upgrade script it remains at version 1.0.6 and continues to indicate that 1.0.7. I'm wondering if the latest update failed to bump the module.json.  Peace - Anthony
![Screenshot from 2022-10-10 10-51-32](https://user-images.githubusercontent.com/532371/194830704-5b01dab3-d42e-41cc-8934-6cc3c2631432.png)

**Comment by freescout-helpdesk** [comment]
You are right. Fixed in Two-Factor Authentication Module v1.0.8
