### ISSUE TITLE
Dashboard colors or logo

### ISSUE THREAD

**Issue by eljakim** [freescout-helpdesk/freescout#2313]
Would it be possible to specify a colour for the headers for each mailbox on the dashboard? Or, if not, specify a logo that is shown in the right corner of the mailbox?

![dashboard](https://user-images.githubusercontent.com/203086/195058604-32ceed81-c77e-48bf-9bf5-95be72029811.png)

This will make the view of the dashboard quite a bit more readable for us.

**Comment by eljakim** [comment]
Actually, a small logo would work best. Because, when you look at issues from the 'global mailbox' it makes sense to show the logo of the mailbox in each row. (Currently you show the name of the mailbox in light gray)

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Feel free to submit a feature request: https://freescout.net/request-feature/
