### ISSUE TITLE
Allow workflow times in minutes.

### ISSUE THREAD

**Issue by wtc-jeff** [freescout-helpdesk/freescout#2315]
Is it possible to set a workflow time condition to be in minutes? Currently, the options are  hours and days.  For example, I would like to notify when a new ticket has not been actioned in 15 minutes.  I have tried setting the field to 0.25 but it is expecting a whole number.

Thanks.

**Comment by freescout-helpdesk** [comment]
Unfortunately not and no plans to implement.
