### ISSUE TITLE
Fail to insert Variables in Workflow Customization

### ISSUE THREAD

**Issue by A3o** [freescout-helpdesk/freescout#2316]
Creating a new workflow, customizing the message, when selecting a variable from the dropdown list, it's not inserted in the message text.

Using 1.8.29
Workflows 1.0.31

**Comment by fulldecent** [comment]
Can you please attach a video?

**Comment by weeblr** [comment]
Same here. Add a workflow with an action such as "Email the customer". Customize the message. Try to insert a variable, nothing happens: nothing is inserted, no error in dev tools console.

Variable insertion is working in other parts of Freescout, so not browser-related.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.32
