### ISSUE TITLE
Module - Custom Folders - looking for untagged folder

### ISSUE THREAD

**Issue by bcookatpcsd** [freescout-helpdesk/freescout#2317]
Module works great with required Tag module.. 

I was looking to make a folder of 'no tags' to see which tickets have not been tagged.. 

Is that possible? 

(scenario) 

I have multiple schools sending tickets to a general mailbox - these come in untagged

make folders for each building, and tag emails which sort into folders.

new emails or unseen emails are not tagged and appear in the general mailbox, looking to filter those out into an 'untagged' folder.. 

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Unfortunately not and no plans to implement.
