### ISSUE TITLE
[API] Missing way to update customer

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2318]
_I purchased the API module and the CRM module._

The API allows to create customer and update custom fields, https://api-docs.freescout.net/?bash#create-customer

Currently there is no way to update the normal customer fields:

| Parameter      | Type   | Description                                                  |
| :------------- | :----- | :----------------------------------------------------------- |
| firstName      | string | First name of the customer (max 40 characters).              |
| lastName       | string | Last name of the customer (max 40 characters).               |
| phone          | string | Phone number.                                                |
| photoUrl       | string | URL of the customer’s photo (max 200 characters).            |
| jobTitle       | string | Job title (max 60 characters).                               |
| photoType      | string | Type of photo: unknown, gravatar, twitter, facebook, googleprofile, googleplus, linkedin. |
| address        | object | Customer's address (country contains [two-letter country code](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes)): `{ "city": "Los Angeles", "state": "California", "zip": "123123", "country": "US", "address": "1419 Westwood Blvd" }`. |
| notes          | string | Notes.                                                       |
| company        | string | Company (max 60 characters).                                 |
| emails         | object | List of email entries: `[ { "value": "mark@example.org", "type": "home" } ]`. |
| phones         | object | List of phones entries: `[ { "value": "777-777-777", "type": "home" } ]`. |
| socialProfiles | object | List of social profile entries: `[ { "value": "@markexample", "type": "twitter" } ]`. |
| websites       | object | List of website entries: `[ { "value": "https:\/\/example.org" } ]`. |

Perhaps the route can be:

```sh
curl -X POST "https://demo.freescout.net/api/customers/1" \
    -H "X-FreeScout-API-Key: c2ba609c687a3425402b9d881e5075db" \
    -H "Content-Type: application/json" \
    -d '{"firstName":"Mary"}'
```

Or you may prefer the `PATCH` HTTP verb.

**Comment by freescout-helpdesk** [comment]
`Update Customer` method has been added in API & Webhooks Module v1.0.46: https://api-docs.freescout.net/#update-customer

**Comment by fulldecent** [comment]
Works great, thank you!
