### ISSUE TITLE
Fetching taking a long time

### ISSUE THREAD

**Issue by VacationTeam** [freescout-helpdesk/freescout#2320]
Seemingly out of nowhere (Server uptime of 110+ days) with no issue.
I am getting fetching problems with Gmail.
I can connect just fine, but the fetching process takes, 32+ minues.
I look at the fetch-emails log, I don't see any errors, just the the time from Folder to reading emails will go 20+ minutes.
ie I don't see it starting to analyze emails.
Current time is 14:54 and my fetch-email.log shows:
<html>
<body>

4 |  
-- | --
3 | [2022-10-11 14:37:16] Folder: INBOX
2 | [2022-10-11 14:37:02] Mailbox: Reservations
1 | [2022-10-11 14:37:02] Fetching ALL emails for the last 0 days.

</body>
</html>

Last fetch error was today:
Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/novalidate-cert/ssl}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate); File: /mnt/data/home/.../overrides/webklex/laravel-imap/src/IMAP/Client.php (230)

But I checked and Imap can connect just fine and I have validate cert off:
![image](https://user-images.githubusercontent.com/90206057/195175989-6d7310b4-3c32-4acd-8dea-5e5cd646fe9b.png)

I have rebooted my server since this started happing yesterday and that didn't help

Thank you in advance for your assistance.

**Comment by VacationTeam** [comment]
Just wanted to drop an update
33 Minutes between folder and fetched.
![image](https://user-images.githubusercontent.com/90206057/195178664-91a7182c-af3f-4dd3-963d-b6d406367e07.png)

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. The only way to find the reason is to debug it on your server.
