### ISSUE TITLE
'Invalid url': Can't install modules with the delivered licence codes

### ISSUE THREAD

**Issue by diankov** [freescout-helpdesk/freescout#2321]
We purchased some modules and got licence keys. When I try to install a module from 'Manage / Modules' and enter the licence key I get the error message "Invalid url".

**Comment by diankov** [comment]
Under System Status all rows are OK, except this:
`queue:work 	Last run: ? Last successful run: ? Try to [clear cache](https://freescout.isomorph.ch/system/tools) to force command to start.`

I was able to clear the cache successfully and also fetching is working without errors, but the problems persist.

**Comment by freescout-helpdesk** [comment]
We've never seen something like this. Check Manage > Logs > App Logs.

**Comment by diankov** [comment]
Thank you for the reply.
This is how the error message "Invalid url" looks like
<img width="1440" alt="modules_invalid_url" src="https://user-images.githubusercontent.com/115709697/195976230-9a6c92a9-8da5-4bc8-b341-0d1d59b024ca.png">

I checked the App Logs. Nothing recent there. Only some laravel errors, which are old and probably occured during the installation. Here is one of them:

`[2022-10-06 09:39:43] production.ERROR: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed {"exception":"[object] (PDOException(code: 70100): SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed at /www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:108)
[stacktrace]
#0 /www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(108): PDO->beginTransaction()
#1 /www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(92): Illuminate\\Database\\Connection->createTransaction()
#2 /www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(195): Illuminate\\Database\\Connection->beginTransaction()
#3 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(244): Illuminate\\Queue\\DatabaseQueue->pop('emails')
#4 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(105): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\DatabaseQueue), 'emails')
#5 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#6 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#7 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#8 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#13 /www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
`

<img width="1440" alt="app_logs" src="https://user-images.githubusercontent.com/115709697/195976401-03d96a55-d94c-44c1-9df5-0e15ab4ab08e.png">

**Comment by freescout-helpdesk** [comment]
The error message is not related to the issue. You may need to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ModulesController.php#L195

**Comment by diankov** [comment]
@freescout-helpdesk Thanks for the hint. Can you please give a little more details how exactly to do debug?

Unfortunately the error still persist, also after a fresh reinstall. Please reopen the issue.

**Comment by diankov** [comment]
Probably we'll use this option in future, but for now we just want to have the modules running and test how freescout will integrate with our other services.
