### ISSUE TITLE
Can't install using web installer on Ubuntu

### ISSUE THREAD

**Issue by palesths** [freescout-helpdesk/freescout#2322]
Hello, 
I just downloaded the application from https://freescout.net/download/
I unzipped the file but there's no "install" folder or "install.php" file
Am i missing something?

support@server2:~/public_html/freescout-dist$ ls -l
total 612
drwxrwxr-x 16 support support   4096 Oct 13 14:27 app
-rw-rw-r--  1 support support   2342 Oct 13 14:27 artisan
drwxrwxr-x  3 support support   4096 Oct 13 14:27 bootstrap
-rw-rw-r--  1 support support  17401 Oct 13 14:27 composer.json
-rw-rw-r--  1 support support 240445 Oct 13 14:27 composer.lock
drwxrwxr-x  2 support support   4096 Oct 13 14:27 config
drwxrwxr-x  5 support support   4096 Oct 13 14:27 database
-rw-rw-r--  1 support support  34520 Oct 13 14:27 LICENSE
drwxrwxr-x  2 support support   4096 Oct 13 14:27 Modules
drwxrwxr-x 24 support support   4096 Oct 13 14:27 overrides
-rw-rw-r--  1 support support   1127 Oct 13 14:27 package.json
-rw-rw-r--  1 support support   1149 Oct 13 14:27 phpunit.xml
drwxrwxr-x  8 support support   4096 Oct 13 14:27 public
-rw-rw-r--  1 support support   5752 Oct 13 14:27 README.md
drwxrwxr-x  5 support support   4096 Oct 13 14:27 resources
drwxrwxr-x  2 support support   4096 Oct 13 14:27 routes
-rw-rw-r--  1 support support     79 Oct 13 14:27 SECURITY.md
-rw-rw-r--  1 support support    542 Oct 13 14:27 server.php
drwxrwxr-x  6 support support   4096 Oct 13 14:27 storage
drwxrwxr-x  3 support support   4096 Oct 13 14:27 tests
drwxrwxr-x  2 support support   4096 Oct 13 14:27 tools
drwxrwxr-x 46 support support   4096 Oct 13 14:27 vendor
-rw-rw-r--  1 support support    549 Oct 13 14:27 webpack.mix.js
-rw-rw-r--  1 support support 241471 Oct 13 14:27 yarn.lock
support@server2:~/public_html/freescout-dist$

**Comment by freescout-helpdesk** [comment]
Try manual installation: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
