### ISSUE TITLE
End User portal: users are logged-in to all maibox

### ISSUE THREAD

**Issue by weeblr** [freescout-helpdesk/freescout#2323]
Hi

I just realized that when a user logs in to the EUP, they are logged in to ALL mailboxes at the same time. 

That does not seem appropriate especially when Freescout is used for handling support for multiple businesses by the same support staff.

I don't use it but I assume the Knowledge base module also has the same problem?

**Comment by freescout-helpdesk** [comment]
It's by design. Each mailbox has a unique End-User Portal URL, so customers can access only those End-User Portals to which you give them the link.

**Comment by weeblr** [comment]
Hi,

Understood but still, that's a pretty big drawback. Just adding the mailbox id to the cookies would solve that.

In the mean time, I just realized something a bit more problematic with the EUP: the login links don't expire. So it's enough for someone to find a login link anywhere, in a wrongly sent email, or an unfortunate CC and they can forever and ever access the end user portal, including potentially confidential information mentioned in tickets.

It does not seem complex to solve either, just embed an expires_at value in the encrypted link.

I have disabled the end user portal for now due to this.

Best regards

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by weeblr** [comment]
Sorry, that's a (big) security issue, you need to fix the non-expiration links.

**Comment by weeblr** [comment]
@freescout-helpdesk Are you working on this security vulnerability? do I need to open another issue with a proper, separate title?

**Comment by freescout-helpdesk** [comment]
See how it works: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Development-Process
