### ISSUE TITLE
Incoming email is treated as reply in original mailbox after forwarding

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2324]
I don't know if this is intended but consider the following scenario

Customer has a conversation with mailbox 1 (M1)
M1 forwards the conversation to mailbox 2 (M2)
Customer answers the conversation but sets receiver (To) to M2 and CC to M1
Now the original conversation in M1 gets the reply instead of (what I expected) a new conversation is created in M2

It seems there is already some kind of prevention in the code but it might not work with multiple receivers?

https://github.com/freescout-helpdesk/freescout/blob/25c43247cf03631524cb23c3b60d1b3d95b5e1f8/app/Console/Commands/FetchEmails.php#L468

Thanks in advance

**Comment by sofl88** [comment]
After some investigation I noted that everytime a customer replies to an email with atleast 2 freescout mailboxes, only the mailbox with the initial conversation receives the email. Usually emails sent to multiple freescout mailboxes, are stored in an array and get post processed later (extra_import array) but in this case, pushing this array gets prevented here https://github.com/freescout-helpdesk/freescout/blob/25c43247cf03631524cb23c3b60d1b3d95b5e1f8/app/Console/Commands/FetchEmails.php#L541

When I remove this condition, every mailbox (that is prevented) gets the email as new conversation. @freescout-helpdesk do you mind giving a short insight why this condtion is there and what side effects (if any) may happen if I would comment it?

**Comment by freescout-helpdesk** [comment]
Can this be reproduced on the latest FreeScout version?
