### ISSUE TITLE
Send SMS trough workflow

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#2325]
Hi guys,

I see a new module with sms services.
Awesome!

So I would love to know if I also can send an sms trough workflow.
At this moment we do that trough a forward to an sms service. 
So when people add URGENT in the subject we get an sms. 

Would love to know is this is also possible with your new module!

Thanks!

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans.

**Comment by joris85** [comment]
I see that you guys now have an sms notification module. 
Does that have the option to work with workflow?

So if subject has this, than send SMS.
