### ISSUE TITLE
App\Jobs\TriggerAction has been attempted too many times or run too long

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#2326]
Can someone can give us some clarification on the configuration I am on a shared host and have had an issue with  'App\Jobs\TriggerAction has been attempted too many times or run too long' error on searching the FQA I found an answer was to try

 php /.../public_html/artisan queue:work --queue='emails,default' --sleep=5 --tries=1 >> /dev/null 2>&1 

and run as a corn job. I already have the following corn job running

php /.../public_html/artisan queue:work --queue='emails,default' --sleep=5 --tries=1 >> /dev/null 2>&1

My question is do I need both crone jobs?

If I need both can I run them at different times, say every 5 min and 10 min it's just that I keep getting emails from Siteground complaining about the CPU Seconds the Cron jobs take, I have an account limit of 4000/hour.

Regards

John

**Comment by JSM25** [comment]
I don't know if this is also part of the same issue. 
 
![canute_41](https://user-images.githubusercontent.com/27293201/195832575-3d57055e-0a9a-427c-a236-a3fb3ce871c0.jpg)

If it's not what do I need to do for this one?


John

**Comment by freescout-helpdesk** [comment]
Only one `queue:work` should be running at a time.

`App\Jobs\TriggerAction has been attempted too many times or run too long` - check all logs in Manage > Logs. This may happen for example when your mail server is not available.

**Comment by JSM25** [comment]
Ok,

I have set my CRON job back to:

php /home/customer/www/xxxxx/public_html/artisan schedule:run >> /dev/null 2>&1

and removed:

/public_html/artisan queue:work --queue='emails,default' --sleep=5 --tries=1 >> /dev/null 2>&1

is this correct?

Can you please let me know how to stop the App\Jobs\TriggerAction has been attempted too many times or run too long.  error

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs

**Comment by MarcoWel** [comment]
You might want to check if you have automatic workflows that can cause infinite loops, see #1947.
Also you should check if there are items in the "Failed Jobs" log #2044

**Comment by freescout-helpdesk** [comment]
Fixed in Customer Data Enrichment v1.0.2. Update it to the latest version.
