### ISSUE TITLE
CRM: All customers visible for all users

### ISSUE THREAD

**Issue by ringe** [freescout-helpdesk/freescout#2328]
Users should have access to Customers tied to the mailboxes they have access to, only.

Customers that belong to a mailbox the current user does not have permissions to access should not be available to the current user.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-have-separate-contactscustomers-per-mailbox
