### ISSUE TITLE
Deactivate reply to notification

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#2330]
I receive e-mail notifications. FreeScout has the feature, that I can reply to this e-mail and the customer will receive my resposen. 

Is there an option to deactivate that? I want to receive e-mail notifications, but I want that every agent needs to log in to FreeScout to answer.

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Feel free to request a feature: https://freescout.net/request-feature/

**Comment by obstschale** [comment]
I did. Thank you

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/388818
