### ISSUE TITLE
Custom Mailbox Signatures Module - Signature visible in resulting Thread/Conversation

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2332]
Reproducible in the freescout Demo. When I write a new email (not tested with a reply yet) with a custom signature, it is visible in the resulting thread.

![image](https://user-images.githubusercontent.com/12407767/196203046-78f883a0-5ddc-4b19-9f16-ea5d0282bd50.png)

When I use the default signature, it is hidden / not visible. The most confusing part is that variables in the signature get interpreted everytime someone is looking at the conversation. Lets say the custom signature includes text like _Regards, {%user.fullName%}_, then User A sees _Regards, User A_ and User B _Regards, User B_

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Custom signature is displayed on purpose to let users know that a custom signature has been used. The issue with the wrong user displayed in a signature has been fixed in Custom Mailbox Signatures Module v1.0.7
