### ISSUE TITLE
M365 Integration Without Publicly Accessible Site (OAuth)

### ISSUE THREAD

**Issue by ForestFeather** [freescout-helpdesk/freescout#2333]
We've been using Freescout with M365 using basic authentication for some time now successfully; however with that end coming and recent sync issues on Microsoft's end I've been working on implementing the OAuth method.  However, it seems to require a public domain access request (IE, the https://www.domain.com/mailbox/auth).  Our install is used entirely internally within our systems; with no public facing access portal.  Is there a way around this using app licensing in some other form, or is the only way with a public facing portal?

**Comment by freescout-helpdesk** [comment]
`/mailbox/auth` URL must be publicly accessible. There is no a way around.
