### ISSUE TITLE
504 Gateway Time-out on fetching emails

### ISSUE THREAD

**Issue by kwiiie** [freescout-helpdesk/freescout#2334]
I get error "504 Gateway Time-out" when fetching All Emails from last 100 days manually from the page **system/tools**

If I reduce to 10 days it works fine.

Anyone experienced the same?

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of FreeScout?

**Comment by freescout-helpdesk** [comment]
Also try to use console command:
```
php artisan freescout:fetch-emails
```

**Comment by MarcoWel** [comment]
Might be related to #1936

**Comment by e-rwan** [comment]
> Also try to use console command:
> 
> ```
> php artisan freescout:fetch-emails
> ```

what would be the command to fetch all(not just unrerad) emails from 100 or more days ago via the console?
I get the gateway too, the command is just too long to resolve with thousand of mails to retrieve.

**Comment by freescout-helpdesk** [comment]
```
php artisan freescout:fetch-emails --days=100
```
