### ISSUE TITLE
Use API to create conversation with Saved Reply

### ISSUE THREAD

**Issue by 3699n** [freescout-helpdesk/freescout#2336]
I'm looking to use the Freescout "Create Conversation" API end point to send emails. Is it possible to used the Saved Replies as a template, so that when the customer is looked up by the email included in the request, all the relevant points are automatically filled in when the conversation is created?

At the moment it seems I am only able to create single lined conversations via the API.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
