### ISSUE TITLE
Missing email validation leads to mass creation of false customers and wrong suggestions

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2338]
We noted that everytime a conversation/draft is created, atleast one customer is also created based on the email address. There is no email validation yet so if the user enters a wrong email and tries to start the conversation / send the email, a customer with a wrong email is created aswell. Also a customer is created when the draft is saved but does not get deleted if the user deletes the draft. With this current behaviour the customers table get alot of useless entries. The most harmful scenario that happens once in a while is when a user tries to start a conversation with a common customer but does a minor typo in the email. After submitting, the user even gets a message like "Email sent" and might not notice that the message never sent. Right now we inform our staff about such messages since we can see it in the logs. The wrong email is now stored and gets suggested to the next user who wants to start a conversation with the common recipient. The chance, the wrong email is choosen is high because they look similar. I know about rfc and dns validation in laravel but I'm not sure if both or one of them are available in laravel 5.5 https://laravel.com/docs/5.8/validation#rule-email Personally I think this should be a must have  especially with 20+ active users.

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Can you give some examples of "wrong emails"?

**Comment by sofl88** [comment]
- nodomain@
- @onlydomain.com
- justtext
- typoindomain@guugle.com (I think this can be prevented with laravel itself or packages like https://github.com/egulias/EmailValidator)

I mean right now you can type literally everything or not?

**Comment by freescout-helpdesk** [comment]
Can you give a screenshot of how you are entering an email.

**Comment by sofl88** [comment]
I have to admit that I was abit hasty about the possibilities. Sorry about that. I tried "justtext" and it gets deleted but things like nodomain@ seem to work.

https://user-images.githubusercontent.com/12407767/197507292-b57d3439-e529-4864-b7bd-b1bc0d58a735.mp4
