### ISSUE TITLE
Chat not in Swedish language

### ISSUE THREAD

**Issue by Fearofthedark66** [freescout-helpdesk/freescout#2339]
Hi, I just bought the chat module and even if the settings are for swedish, the chat is in english?

var FreeScoutW={s:{"color":"#0068bd","position":"br","locale":"sv","require":["name","email"],"id":XXXXXXXXXX}}

**Comment by freescout-helpdesk** [comment]
Chat Module is not translated into Swedish yet. See https://github.com/freescout-helpdesk/freescout/wiki/Translate
