### ISSUE TITLE
"Send error" status for User notification emails

### ISSUE THREAD

**Issue by aareeph** [freescout-helpdesk/freescout#2340]
After setting up the Email Settings, emails are being sent and received in the Mailbox just fine. However we are getting a "Send error" status for the User notification emails i.e. when a new ticket is generated.

![Screenshot 2022-10-24 at 4 48 09 PM](https://user-images.githubusercontent.com/10115810/197550117-37dc0c46-2cb2-42b3-b0d0-516bdbc29902.png)

Can we check the details of this error or is there any other email settings that needs to be checked?

Thank you.

**Comment by bneumayer** [comment]
I can reproduce this error. Sending and fetching works (using a gmail address) but when inviting a new user, this error pops up:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/55702146/197764727-112a0d03-de97-4beb-b9b1-afc26398b3d7.png)
Looking up the error in the logs shows the same entry as posted by @aareeph.

**Comment by bneumayer** [comment]
> After setting up the Email Settings, emails are being sent and received in the Mailbox just fine. However we are getting a "Send error" status for the User notification emails i.e. when a new ticket is generated.
> 
> ![Screenshot 2022-10-24 at 4 48 09 PM](https://user-images.githubusercontent.com/10115810/197550117-37dc0c46-2cb2-42b3-b0d0-516bdbc29902.png)
> 
> Can we check the details of this error or is there any other email settings that needs to be checked?
> 
> Thank you.

I had the same problem. In my case everything worked under `Manage > Mailboxes` but in `Manage > Settings > Mail Settings` there was still a standard email address `freescout@<myserveraddress>`.

Hope this helps!

**Comment by freescout-helpdesk** [comment]
Make sure to enter proper settings in Manage > Settings > Mail Settings
