### ISSUE TITLE
Reports only visible for admins

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2341]
We use the Reports module and would like of our agents (at least team lead) to view the stats.
It seems that currently, the reports module is only visible to administrator users.
Please create an access right for the reports module in the user rights section instead of limiting the view to admins.

**Comment by raramuridesign** [comment]
This would be great feature

**Comment by freescout-helpdesk** [comment]
We can add an option allowing all users to view reports.

**Comment by freescout-helpdesk** [comment]
The option allowing non-admin users to access Reports has been added in Reports Module v1.0.19
