### ISSUE TITLE
tools/update.sh uses wrong shell

### ISSUE THREAD

**Issue by eljakim** [freescout-helpdesk/freescout#2344]
The script tools/update.sh uses `/bin/sh` as the shell.
 ```
#!/bin/sh
```

But for the pre-update and post-update scripts it uses `source` to run those.

This gives an error message. 'source: not found'
- https://askubuntu.com/questions/504546/error-message-source-not-found-when-running-a-script

'source' is a built-in command in `bash` but not in `sh`.

My I suggest you either not use `source` or you change the script to use bash.

**Comment by freescout-helpdesk** [comment]
What operating system are you using?

**Comment by eljakim** [comment]
Ubuntu 20.04.5 LTS

We run the update script from the command line, but because you say `#!/bin/sh` it runs a shell that does not support `source`.

**Comment by freescout-helpdesk** [comment]
Strange. It works fine for us and others.

**Comment by freescout-helpdesk** [comment]
We'll leave this as is as there were no other reports of this kind over the years.

**Comment by eljakim** [comment]
I think this explains why it works for some, and not for others:

https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell
