### ISSUE TITLE
SAML SSO Module - Quantity of IdPs

### ISSUE THREAD

**Issue by jlookabaugh-exclamationlabs-com** [freescout-helpdesk/freescout#2345]
How many IdPs may be configured within the SAML SSO Module for a single instance of FreeScout?  And if the answer to that question is only one, then does FreeScout support multiple installations of the SAML SSO Module so that each module may be configured for a separate and distinct IdP?

For example, I need my FreeScout instance to allow access by multiple user populations, where a population is a set of users known to a given IdP.  My FreeScout instance needs to allow my staff to SSO in via IdPMyEnterprise, needs to allow customer_1 and customer_2 staff to SSO in via IdPAcmeSolutionsLtd, and needs to allow customer_8 staff to SSO in via IdPSocialMediaCompany.  That's three total IdPs as an example.  Thanks.

**Comment by freescout-helpdesk** [comment]
Unfortunately no and no plans to implement.
