### ISSUE TITLE
Can I pass a user ID or other user metadata to the Chat widget via JavaScript?

### ISSUE THREAD

**Issue by CherryDT** [freescout-helpdesk/freescout#2346]
Can I set user info (our system's user ID, email, that sort of thing) via JavaScript so that the chat widget will assign the metadata automatically to the conversation in FreeScout? If user XYZ is logged in when they start the chat, we want to immediately know their user account and not have to ask them "what is your username".

I found that the conversations API has `assignTo`, but that seems to be for directly creating a conversation in FreeScout, not for the chat (in fact it mentions that replies won't go into chat then).

So, is there another way? Tawk for example has a `Tawk_API.visitor` object we can write to, is there something similar in FreeScout's chat?

I couldn't find documentation about whether this is supported (I would expect it to be, but I want to be sure), that's why I'm asking here. (It does feel strange to open a GH issue for that, but "Forum" on your website links to here, so I hope it's the right place...)

**EDIT:** OK, I figured out how to pass username / email / phone. But is there a way to send other metadata, like custom fields?

**Comment by freescout-helpdesk** [comment]
> But is there a way to send other metadata, like custom fields?

Unfortunately not. See:
https://freescout.net/request-feature/
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
