### ISSUE TITLE
Automatic Workflows will not trigger

### ISSUE THREAD

**Issue by pool-alpin** [freescout-helpdesk/freescout#2349]
I'm having troubles getting automated Workflows to trigger, even for the simplest of rules.
Certain Conversations should be tagged and assigned to a user. But even just looking for a word in the message subject will not work.
What am I doing wrong?
<img width="566" alt="condtion" src="https://user-images.githubusercontent.com/90776042/198218443-77f64be5-9500-4605-9729-ec1184a65b57.png">
<img width="574" alt="action" src="https://user-images.githubusercontent.com/90776042/198218457-28a6cc93-13aa-4188-b436-5d4183eecb73.png">

**Comment by freescout-helpdesk** [comment]
Have you checked Manage > System > Status? Manage > Logs > App Logs?

**Comment by pool-alpin** [comment]
Yes, there are no error messages. I've been following this for some time and wanted to make sure I've read all other posts regarding this. Manual Workflows work fine, though.

**Comment by MarcoWel** [comment]
Does the system status show in green that the cron job is running properly as below?

![image](https://user-images.githubusercontent.com/80592577/199529795-7e15c6d5-abf5-49aa-bb0b-1f689af02767.png)

**Comment by pool-alpin** [comment]
@MarcoWel Yes, although the clock is 1 hour behind the server time, but I don't think it matters.

![image](https://user-images.githubusercontent.com/90776042/199666479-1b673e5f-79e1-4c37-9a66-65fb2ced55e7.png)

**Comment by pool-alpin** [comment]
I've also noticed that in app-logs I only have fetch-emails.log and queue-jobs.log.  
There also used to be several laravel-XY.log files. Could this be part of the problem?

**Comment by freescout-helpdesk** [comment]
> I've also noticed that in app-logs I only have fetch-emails.log and queue-jobs.log. There also used to be several laravel-XY.log files. Could this be part of the problem?

No. 

It looks like you need someone who can investigate it on your server.

**Comment by pool-alpin** [comment]
We've recently done a re-install on a new VPS but still have the problem that any condition on the mail subject will not trigger an automatic workflow.  
I've tried different settings and variations for the subject condition (starts with, contains, equals), re-installing the module, but it's not working.

When setting a condition for text in the body, the same workflow triggers just fine.

What else can I do, to get the subject conditions working?

![image](https://github.com/freescout-helpdesk/freescout/assets/90776042/b9bd48e0-295f-4c92-bd71-4f8c46cb6ddc)

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.47
