### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by gab-cass** [freescout-helpdesk/freescout#235]
Hi,

This is a fresh Ubuntu Server 18.04 install. I have followed the installation steps, but in web browser I am getting a 404 Not Found (redirection to /install seems to work). 

Additionally, looking in the Apache web logs, I am getting: 

```
PHP Notice:  Undefined variable: cipher in /var/www/freescout-helpdesk/public/install.php on line 29
```

I would appreciate some help on this.. (the .env file is not created).

**Comment by jhdulaney** [comment]
I am also getting this.  What did you do to resolve the issue?

**Comment by gab-cass** [comment]
I never figured this one out. 

What I have done is started from scratch with a fresh install and it worked.

**Comment by cimm** [comment]
Same error here, Ubuntu 18.04 minimal with Apache.

Turns out I did not enable `mod_rewrite`. As always... RTFM.

Enabling `mod_rewrite` fixed it!

```sh
sudo a2enmod rewrite
sudo systemctl restart apache2
```

Hope this helps some future googling visitor. :wink:
