### ISSUE TITLE
Dark mode update

### ISSUE THREAD

**Issue by ioscanner** [freescout-helpdesk/freescout#2351]
I have Dark Mode 1.0.0 and click update to 1.0.9 and it says invalid license. 

How do I upgrade Dark Mode?  I also can't uninstall to just install the new version.  Is there a way to manually remove it?  I would assume in the database and the modules directory, but want to confirm.

**Comment by freescout-helpdesk** [comment]
Follow Troubleshooting instructions: https://freescout.net/module/dark-mode/
