### ISSUE TITLE
Error occured, please check your internet connection

### ISSUE THREAD

**Issue by sunchaser68** [freescout-helpdesk/freescout#2352]
Version 1.8.31, Cloudflare with Flexible SSL.
I cannot use the webapp, it keeps saying "Error occured, please check your internet connection".

I have the following error in console:

51a7208e5563befe7e67591792578f3724958673447.js:44 Mixed Content: The page at '***/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '***/polycast/connect'. This request has been blocked; the content must be served over HTTPS.

**Comment by sunchaser68** [comment]
Fixed by updating    public_url in  freescout/storage/app/public/js/vars.js

Question: why this is not added in the installation troubleshoot document?

**Comment by freescout-helpdesk** [comment]
> Fixed by updating public_url in freescout/storage/app/public/js/vars.js

It means something went wrong during installation. This should not be made manually.

Make sure you have proper APP_URL in .env file and run `php artisan freescout:build` or reinstall FreeScout and make sure to specify proper App URL during installation.
