### ISSUE TITLE
drop-down 'Mailbox instellingen' not reachable

### ISSUE THREAD

**Issue by HuibertStolker** [freescout-helpdesk/freescout#2353]
Newbie here...
I use several 'Maps', the drop-down of 'Mailbox instellingen' is not reachable, see attachement.
(I don't know how 'instellingen' is mentioned in English, 'configuration' or 'setup'?)
Also clicking 'New E-email' is 'far away'.
Is moving these buttons to the top possible? 
I love your work...,
Huibert (studio@stip.nl)

<img width="1840" alt="Schermafbeelding 2022-10-30 om 12 21 38" src="https://user-images.githubusercontent.com/116333780/198876203-9218c554-51d3-47f9-959b-5e84e291e647.png">

**Comment by freescout-helpdesk** [comment]
Duplicate. There is a similar issue already.
