### ISSUE TITLE
Img src="data:image/png;base64, {data}" not shown in conversation

### ISSUE THREAD

**Issue by Charathan** [freescout-helpdesk/freescout#2355]
I think I found a bug:
When a mail is recieved with a embedded image the img is not show in the conversation. The image is also not shown as an attachement. It is however shown in "show original".

**Comment by freescout-helpdesk** [comment]
Could you please attach HTML code of the email.

**Comment by freescout-helpdesk** [comment]
Also are you using Microsoft Exchange modern authentication or regular IMAP?

**Comment by freescout-helpdesk** [comment]
The issue is confirmed. The problem is in https://github.com/ezyang/htmlpurifier

**Comment by freescout-helpdesk** [comment]
Fixed in `master` branch.
