### ISSUE TITLE
How to Edit Automated Emails.

### ISSUE THREAD

**Issue by Mmasri6** [freescout-helpdesk/freescout#2357]
How would i edit the text being sent to customers as automated emails. like the reset password emails, customer reply on opening a ticket. couldn't find a module for this nor a setting.

In other software its called email template.

appreciate your support

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. It can be implemented via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
