### ISSUE TITLE
How to pass user info from site to chat widget

### ISSUE THREAD

**Issue by chgss** [freescout-helpdesk/freescout#2359]
Hello, I have some registered modules of your app and are great.

now I want to buy the chat widget but I want to pass from my app maked in react the user info, when I receive the ticket not said visitor info and receive info from user logged in my app, this is possible?

Other question I have, I am trying in demo site, and I closed ticket, when the user write again the ticket was reopen, could you explain how it works? The user always see the history from previous tickets?

Thanks in advance

**Comment by freescout-helpdesk** [comment]
You can do so via "Visitor" fields in the chat widget settings:

![chat-visitor-data](https://user-images.githubusercontent.com/40499291/199217924-0241d1ae-8d5d-460a-a18e-f6bc820ed348.png)

**Comment by chgss** [comment]
Thanks for your reply, i want get this info without user has to write, I have this info with logged user I don't want to user write again this fields.

Thanks

**Comment by freescout-helpdesk** [comment]
Pass corresponding values in the code of the widget.

**Comment by jucktnich** [comment]
Hi there,

is there a possibility to pass custom values into the form? My site uses IDs to identify users which I want to include in my form.

Thanks in advance

**Comment by noone-silent** [comment]
> Pass corresponding values in the code of the widget.

This is not working. For the end-user portal, it parsed the FreeScoutW.f and passes it to the widget script. This part is missing in the chat module. There is no way to prefill data in the chat widget.

**Comment by freescout-help** [comment]
@noone-silent Can you attach some screenshots.

**Comment by noone-silent** [comment]
> @noone-silent Can you attach some screenshots.

End-User widget
```js
        if (script) {
            FreeScoutW.form_url = script.src.replace(/modules\/enduserportal\/.*/, '');
            FreeScoutW.form_url += 'help/widget/form/'+FreeScoutW.s.id;
            FreeScoutW.form_url += '?'+Object.keys(FreeScoutW.s)
                .map(function(k) {return encodeURIComponent(k) + '=' + encodeURIComponent(FreeScoutW.s[k]);})
                .join('&');

            if (typeof(FreeScoutW.f) != "undefined") {
                FreeScoutW.form_url += '&'+Object.keys(FreeScoutW.f)
                    .map(function(k) {return 'f['+encodeURIComponent(k) + ']=' + encodeURIComponent(FreeScoutW.f[k]);})
                    .join('&');
            }
        }
```

Chat widget
```js
        if (script) {
            FreeScoutW.form_url = script.src.replace(/modules\/chat\/.*/, '');
            FreeScoutW.form_url += 'chat/widget/form/'+FreeScoutW.s.id;
            FreeScoutW.form_url += '?'+Object.keys(FreeScoutW.s)
                .map(function(k) {return encodeURIComponent(k) + '=' + encodeURIComponent(FreeScoutW.s[k]);})
                .join('&');
        }

```

**Comment by freescout-help** [comment]
Here is how it works:

![2024-07-13_08-53-49](https://github.com/user-attachments/assets/f2b06f6a-003c-4a3f-8289-d3b8ff7d4290)

**Comment by noone-silent** [comment]
Thank you for clarifying. This information should be added to the documentation. There is written we can pass it, but not exactly how.

Also it would be nice, if all standard customer fields (like company) could be passed.
