### ISSUE TITLE
module 'Saved Replies' dropdown menu

### ISSUE THREAD

**Issue by Junker** [freescout-helpdesk/freescout#236]
When use 'saved replies' on mobile phone, saved replies dropdown menu showed out of screen. 
need to add 'dropdown-menu-right' class to dropdown-saved-replies
![screenshot_com android chrome](https://user-images.githubusercontent.com/1144095/51409861-8e1f3e00-1b95-11e9-9ec5-68dddf196c17.png)

**Comment by freescout-helpdesk** [comment]
It will be fixed in the next release of the module.
