### ISSUE TITLE
URL Parameters when creating New Ticket 

### ISSUE THREAD

**Issue by 3699n** [freescout-helpdesk/freescout#2360]
The default URL to create a new ticket is: https://freescout.tld/mailbox/1/new-ticket

This leads to a blank page where a new ticket/email can be composed.

Is it possible to include parameters in the URL when creating a new ticket to have certain fields automatically filled?
For example: https://freescout.tld/mailbox/1/new-ticket?email=example@example.com?saved-reply=2?subject=Hello

I am looking to do this for better integration into our existing CRM, so that users can just click on a link to compose an email to our client in one click and have all the fields automatically populated.

**Comment by MarcoWel** [comment]
+1 on this! :)

**Comment by freescout-helpdesk** [comment]
The "To" parameter can already be  pre-filled via GET request: `?to=test@exampe.org`. Subject pre-filling will need to be implemented.

For this `?saved-reply=2` see:
https://freescout.net/request-feature/
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
