### ISSUE TITLE
Modules Directory empty

### ISSUE THREAD

**Issue by GezaBoi** [freescout-helpdesk/freescout#2361]
I tested out freescout and it looked amazing so I went ahead an brought the 3 modules I need. 

Now I run into the problem, that I can not install them because there are none listed on the site (it is just blank). 
I found this [issue](https://github.com/freescout-helpdesk/freescout/issues/368) and tried to curl [https://freescout.net/wp-json/](https://freescout.net/wp-json/) from my server and from inside the docker container. That worked without a problem.

the system/status page shows everything ok except:
queue:work | Last run: ? Last successful run: ? Try to clear cache to force command to start.

there is also a 404 error in the laravel log. But I struggle to understand what it fails to connect to. 

here are the logs with the error and my docker-compose. I had to add .txt at the end of it so github would allow the upload.
[laravel-2022-11-02.log](https://github.com/freescout-helpdesk/freescout/files/9919374/laravel-2022-11-02.log)
[freescout-g.yml.txt](https://github.com/freescout-helpdesk/freescout/files/9919381/freescout-g.yml.txt)

everything else works on my installation. I can send mails and get them, the mail cron job works too. 

do you have any idea where the error might be? 
thanks for your help!

**Comment by GezaBoi** [comment]
I was testing different docker images and found out that older images were working for me. 
So I got it running using `image: tiredofit/freescout:1.15.59` as a tradeoff between an old image that works and one that is new enough to support the plugins that I need. 

I am not sure now if it's a problem of freescout or the docker image which I know is maintained by someone else. 
I will leave this open for now since the newest image is still not working for me and it does not seem to be my setup.

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution. Apparently something does not work in the latest docker containers. @tiredofit

**Comment by GezaBoi** [comment]
I was also able to update to the latest container after installing the plugins and they stayed installed and working. I am just not able to install more, but I don't need to right now.
