### ISSUE TITLE
SMTP not authenticated

### ISSUE THREAD

**Issue by Tires** [freescout-helpdesk/freescout#2363]
I was installing latest from Docker Hub and created a mailbox. I can sent e-mail with SMTP to a mailbox on mail server unauthenticated but I cannot sent to outside. No authentication has been taken place. Same with IMAP. Since there are no further means of configuration, I was opening this ticket.

**Comment by Tires** [comment]
![grafik](https://user-images.githubusercontent.com/13418797/199694897-da43640c-7731-4385-8efc-e7e27813c5a0.png)

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. The problem is related to your mail server.

**Comment by Tires** [comment]
My mail server don't have a problem. Then authentication just not taking place
