### ISSUE TITLE
Add an action: before_customer & after_customer in the conversation list.

### ISSUE THREAD

**Issue by CrazyHenk44** [freescout-helpdesk/freescout#2365]
Hi,

(thanks for the great software!)

I would like to request an action in resources/views/conversations/conversations_table.blade.php

Similar to before_subject and after_subject, I would like to request a before_customer and after_customer.

I have a very simple module ready to add the company name of the customer to the list. We can now only show the customer name before the subject, but that clashes a bit with the tags. I'ld be happy to provide it to you so you can sell it as a commercial module or make it a community module.

Best!

**Comment by freescout-helpdesk** [comment]
Feel free to submit a pull request with actions.

**Comment by CrazyHenk44** [comment]
Why do I even ask things anymore. Everyone asks PR's. Really, you spent more time writing this line and dealing with a PR, code style issues, communication, etc,  then just adding the two hooks.
