### ISSUE TITLE
Searching for all conversations assigned to the "Anyone" user across mailboxes

### ISSUE THREAD

**Issue by Xuf00** [freescout-helpdesk/freescout#2367]
Hi,

Unless I'm missing something it seems it's not currently possible to search for all conversations that are assigned to the "Anyone" user on the search screen. I would have expected to be able to select this user on the "Assigned" filter but it's not there. Leaving it blank simply removes the filter and the default view is every conversation (even assigned).

Please see the below example in a demo environment I setup:

![image](https://user-images.githubusercontent.com/31516365/200082479-814defff-e81e-4bbb-8655-0c5c19026704.png)

I've already looked into the relevant code areas and think I could add this in relatively easily but wanted to know what the thoughts are on this before I go ahead.

Thanks

**Comment by freescout-helpdesk** [comment]
Pull request has been merged.
