### ISSUE TITLE
Searchresult - when changing the url-parameter for mailbox I do not have I see conversations (and customers) of other mailboxes

### ISSUE THREAD

**Issue by giemes** [freescout-helpdesk/freescout#2370]
Hi,
for reproduction:
there are 2 (or more) mailboxes: mailbox id = 1 and id = 2
I have a user with permission for just mailbox = 1
I click on search and find results just for my mailbox = 1 (ok)
BUT: If i change the URL-Parameter (`f%5Bmailbox%5D=`) to mailbox-id = 2 > I can see all conversations (and customers) of the other mailbox, I do not have permission to.
I think this is not intended and a bug - or is there another way of fixing/customizing this?
Thnx for your response!
regards, Gerd

**Comment by giemes** [comment]
I am afraid, that the issue I raised is just partly fixed.

Same Setting: The user has access to mailbox 1 and NOT mailbox 2

fixed is the following URL:
`https://freescouttestserver.com/mailbox/1` --> conversations and customers are displayed
`https://freescouttestserver.com/mailbox/2` --> NO conversations and customers are displayed = Access denied

GREAT!

NOT fixed is the following URL:
`https://freescouttestserver.com/search?f%5Bmailbox%5D=2`: if my current user just has permission for mailbox 1 we now see all the conversations from mailbox 1 (where I have access) AND all from mailbox 2 (where I do not have access)
`https://freescouttestserver.com/search?f%5Bmailbox%5D=1`: I see all conversations and users from Mailbox 1 - ok

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
