### ISSUE TITLE
Spam Filter does not work correctly

### ISSUE THREAD

**Issue by SvetlanaKon** [freescout-helpdesk/freescout#2371]
Hello!
I have a problem.
After installing the spam filter worked correctly.
However, some time ago all e-mails started going to the Spam folder.
What do I have to do to make the spam filter work correctly?

Thank you for your help!

**Comment by freescout-helpdesk** [comment]
In "Manage » Spam Filter" you can view and reset Spam Filter "Learning Memory" per mailbox.
