### ISSUE TITLE
 [error] 718#718: *9468 open() "/var/www/html/public/sw.js" failed

### ISSUE THREAD

**Issue by Soundmagic2** [freescout-helpdesk/freescout#2372]
After a fresh Ubunutu installation via script the following error message appears ever 2-3 minutes in the web server log:
 [error] 718#718: *9468 open() "/var/www/html/public/sw.js" failed

**Comment by freescout-helpdesk** [comment]
We don't know why it may happen on your installation. FreeScout does not use "/public/sw.js" file.

**Comment by Soundmagic2** [comment]
Hi team,

I investigate it a little bit more. The request come from my webclient during using freescout.
I guess this is a Laravel Service Worker call, which runs into error (why ever).

see here:
https://stackoverflow.com/questions/37820922/using-laravel-for-service-workers

it is filling my web-server.log with 2-3 entries per minute.
[error] 718#718: *9468 open() "/var/www/html/public/sw.js" failed

Please think about again, thanks
