### ISSUE TITLE
oauth - An error occured creating a user

### ISSUE THREAD

**Issue by GezaBoi** [freescout-helpdesk/freescout#2374]
I am trying to get the Oauth plugin to work with mattermost as the [OAuth2 provider](https://developers.mattermost.com/integrate/apps/authentication/oauth2/). 

The provider works with the exact same settings for nextcloud. So I am not sure if the error is the config. 

I removed the url and replaced it with ((mattermost-url)) and ((freescout-url)).
To me it seems that there is an error getting the email from the OAuth provider. For some reason the field seems to be empty. I also attached a copy of the  https://((mattermost-url))/api/v4/users/me endpoint. [me.json.txt](https://github.com/freescout-helpdesk/freescout/files/9969096/me.json.txt)
 

These are the logs OAuth shows after a failed login:
<html><head></head><body>

Nov 9, 08:24:26 | DEBUG - User Info response:  {"id":"api.context.404.app_error","message":"Sorry, we could not find  the page.","detailed_error":"There doesn't appear to be an api call for  the url='/api/v4/users/me'.  Typo? are you missing a team_id or user_id  as part of the url?","status_code":404}
-- | --
Nov 9, 08:24:26 | DEBUG - Fields mapping:  {"name":"username","email":"email"}
Nov 9, 08:24:26 | DEBUG - FreeScout user not found by  email:
Nov 9, 08:24:26 | Creating a new user {"email":""}
Nov 9, 08:24:26 | DEBUG - User data after mapping:  {"new_user_data":{"email":"","password":"qpZibD24","first_name":"Oauth","last_name":"User"}}
Nov 9, 08:24:26 | Error occurred creating a user.  {"new_user_data":{"email":"","password":"qpZibD24","first_name":"Oauth","last_name":"User"}}
Nov 9, 08:24:26 | DEBUG - Redirecting to Authorization  URL:  https://((mattermost-url))/oauth/authorize?client_id=sxy3hm559jbc9cy4q5155d1wjc&response_type=code&scope=openid  email  profile&redirect_uri=https%3A%2F%2F((freescout-url))%2Foauth-login%2Fcallback%2F2hktpcn0f
Nov 9, 08:24:26 | DEBUG - OAuth callback triggered:  {"code":"t998uuuji7ymzmo14j93cizwxyzwuqoctr1tfw8f9gfkfzaruyec","state":null}
Nov 9, 08:24:26 | DEBUG - OAuth token URL response:  {"access_token":"oe9poz4ribyizcc86tn1kep1bc","token_type":"bearer","expires_in":2038562,"scope":"","refresh_token":"ji4o7wzji3bymmexj1pzn7kkkc","id_token":""}n
Nov 9, 08:24:26 | DEBUG - Requesting data from User  Info URL: https://((mattermost-url))/api/v4/users/me

</body></html>

Would love to figure this out. This is the last hurdle to get freescout running. 
Thank you for your help!

**Comment by freescout-helpdesk** [comment]
It looks like Mattermost requires to request "/api/v4/users/me" via "POST" while the module uses "GET" by default.

**Comment by GezaBoi** [comment]
I just checked and that is true. "/api/v4/users/me" requires a get request. it returns 404 on a post request. so that does seem to be the problem! 
do you have any idea how I can solve this?

Would it be possible to implement an dropdown in the plugin to choose the kind of request freescout sends? 

otherwise I was thinking if I can reroute the get request to a post request in the traefik reverse proxy I am using. but I currently have no idea how I would do that.

**Comment by GezaBoi** [comment]
It works! 
Thank you so much for the fast help! ❤️
