### ISSUE TITLE
Customer replies are added to the wrong thread.

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2375]
Hey.

We have a issue where sometimes, a customer reply, will be submitted into the wrong thread/conversation.
I've looked at the headers to see if I could find whats wrong, both comparing 2 customer replies thats assigned to the right thread and comparing the mismatch reply to those.
Having compared those headers, I can't really tell how even the original messages were added to the same conversation/thread, being that both the Message-ID and In-Reply-To are not matching.

How exactly does FreeScout decide which thread to add new replies? I've looked at the code in app\Console\Commands\FetchEmails.php, where it seems its deciding a previous Message-ID, but Im struggling to find out how Right message 1 and 2 got put into the same thread, and why the wrong header got added aswell.

Right headers 1:
```
Message-ID: <wwROz000000000000000000000000000000000000000000000RK02WQ00Ud_A4DrGS0WyoooOo1r6bQ@example.com>
In-Reply-To: <reply-118926-79563c2990b98339ddf3b46c966de77f@example2.com>
References: <79563c2990b98339ddf3b46c966de77f@example3.com>
 <reply-118926-79563c2990b98339ddf3b46c966de77f@example2.com>
```

Right headers 2:
```
Message-ID: <xA6gh000000000000000000000000000000000000000000000RK1ULD00kcoYxh_DSsODudvpLRidag@example.com>
In-Reply-To: <reply-138261-6fa9ec36c7f7ccdaab932967f8caee1f@example2.com>
References: <6fa9ec36c7f7ccdaab932967f8caee1f@example3.com>
 <reply-138261-6fa9ec36c7f7ccdaab932967f8caee1f@example2.com>
```

Wrong header:
```
Message-ID: <0102018442b14d7f-94a0ea1c-f698-4c00-baf3-38e7d6b5a939-000000@example4.com>
References: <reply-156854-a57eb3223af0522db240c416767bebbb@example2.com>
In-Reply-To: <reply-156854-a57eb3223af0522db240c416767bebbb@example2.com>
```

Im hoping you can cast some light on this issue for me.

**Comment by freescout-helpdesk** [comment]
```{#FS:cmVwbH...#}``` marker containing message_id is checked in the body:
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L329

**Comment by freescout-helpdesk** [comment]
We'll close this as it's impossible to investigate it without direct access to the server. If you'll have any other questions - feel free to ask.

**Comment by maxkvbn** [comment]
The only messages with the message_id marker, is the one which is added to the wrong thread. Any idea where to go from here? @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
We've managed to reproduce and fix the issue. It could happen when the customer was also using FreeScout. The fix will be included in the next release.

**Comment by freescout-help** [comment]
The issue may still happen when your customer uses very old version of FreeScout and replies to your message.
