### ISSUE TITLE
New Conversation in Mailbox shows all customers in autosuggest field ( "To" ) instead of just the one from the mailbox

### ISSUE THREAD

**Issue by giemes** [freescout-helpdesk/freescout#2377]
Steps to reproduce:
0) Testsetup: we have 2 mailboxes: mailbox 1 and mailbox 2 with distinctive customers in every mailbox
1) select the mailbox 2
2) Click on the Envelope "New Conversation"
3) type a email/name from mailbox 1 (we know it is just from mailbox 1)
Then we see (see attached image) that we can see this customer to be selected and mailed to

I hope this can be fixed so quickly as you fixed the other issue today (THNX for that!)

**Comment by giemes** [comment]
In addition to that: this behaviour also occurs, when forwarding a conversation to another person > all customers are shown not just the one from my mailbox

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-have-separate-contactscustomers-per-mailbox

**Comment by giemes** [comment]
Hi,
sorry but thats not what I meant:
I am not talking about splittet/duplicated customers when the same customer is in both mailboxes.
If a customer is on both mailboxes it is ok to view it in the to/cc++ fields in the conversation. 
But iff a customer is not in my mailbox it does not make sense to show it.
I think it would be easy to fix this, because in the application the mailbox-filter (for conversations and customers) is present and can be used > so in the API/Ajax-Call for "getting the customers" just add the current mailbox and we are fine when selecting/autosuggest the customer.
I hope I describe it so that it makes sense for you as well. Thnx!
lGG

**Comment by freescout-helpdesk** [comment]
There are two things here. First, by default customers are shared between mailboxes in FreeScout and it's fine to see customers from other mailboxes in To, CC, BCC. Second, showing only customers who emailed to the current mailbox will seriously slow down the To, CC, BCC autosuggest dropdowns.

So we will leave this for someone to implement as a custom module. It's not needed in the core.

**Comment by giemes** [comment]
Thnx for your response ... I think if you think the performance could be an issue: there could be a switch thats instance-wide to switch or setting it on or off ... means - switch/setting named "show-only-customers-from-mailbox":
"off" (default): current behaviour (all customers are shown)
variant a: "on": just the customers of my selected mailbox are shown
variant b: "on": just the customers of the mailboxes where my current user has access to are shown
the variant b can then also be used in the search: if it is "on" the mailbox filter is mandatory ...

with this features we are close to a possible "seperation of data by mailbox" (aka tenant specific view) - I think lots of potential companies (with more than one support channel/product to be supported) that might use freescout would need this feature (when the alternative to have seperate instances is not a real alternative)

Thank you for taking it into consideration!
