### ISSUE TITLE
Feature Request: Conversation Report

### ISSUE THREAD

**Issue by amanpatel** [freescout-helpdesk/freescout#2378]
It would be amazing if somehow we can include the following metric in the conversation report (perhaps at the bottom).

- Average number of hours for the first reply 

To calculate this, it would be to just take all the threads that have at least 1 response, and do the duration between the initial creation of ticket/conversation and the first reply.

It would be awesome if this metric was calculated per responder. or assignee. This way you can see how long it takes for people to post the first response to any new support ticket.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
