### ISSUE TITLE
Unable to authenticate SMTP or IMAP O365

### ISSUE THREAD

**Issue by brannan-holland** [freescout-helpdesk/freescout#2380]
I am having trouble authenticating SMTP or IMAP using O365 credentials. 

- I am using an account that does not have MFA
- SMTP and IMAP are enabled on this account and in the tenant
- I have tested SMTP on a third-party site with success (https://dnschecker.org/smtp-test-tool.php)
- Currently, I am hosting my instance. I have tried it on two different host
- I have checked to see if the public IP of the host is blacklisted for O365. It appears it is not
- Below is my configuration and screenshots of the errors. 

![image](https://user-images.githubusercontent.com/113192174/201499789-d4ce7418-85c1-4c52-a885-b76de34dedfc.png)

![image](https://user-images.githubusercontent.com/113192174/201499804-4bed5fe5-c3c1-4d48-b552-4495a029105a.png)

![image](https://user-images.githubusercontent.com/113192174/201499852-9368b6d0-727e-472c-9dbe-f663ee395c5b.png)

I can attempt the OAuth for IMAP, but without SMTP It may not be worth my time.

Any thoughts on this? I am stumped.

Thank you in advance for any help here!

**Comment by freescout-helpdesk** [comment]
SMTP
Contact your hosting and ask them if 587 port is open. Make sure that SMTP is enabled in your MS365 account: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#sending-emails

IMAP
It's no use to try plain IMAP without oAuth. Use modern oAuth authentication: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#fetching-emails

**Comment by brannan-holland** [comment]
Turns out SMTP is blocked on the hosted server. Looks like ill be going the self-hosted route!

Thank you for your feedback!
