### ISSUE TITLE
How to remove contact ?

### ISSUE THREAD

**Issue by Zatalyz** [freescout-helpdesk/freescout#2381]
We have invalid addresses and duplicates contact on freescout, how can I remove them from the contacts? I don't find where I can do it.

**Comment by pathab** [comment]
You can do this through the Customers Management (CRM) module or directly through the database (but could be dangerous).

**Comment by freescout-helpdesk** [comment]
> You can do this through the Customers Management (CRM) module or directly through the database (but could be dangerous).

Yes.

**Comment by Zatalyz** [comment]
Thanks a lot ! I buy the module, it is really more easy. Good work !
