### ISSUE TITLE
Reply from BCC results in change of customer

### ISSUE THREAD

**Issue by pathab** [freescout-helpdesk/freescout#2382]
Hello all,

We just had the following problem:
- Create a new message with **TO: aaa@amail.com** and **BCC: bbb@bmail.com**.
- As soon as bbb@bmail.com replies, aaa@amail.com is replaced as customer by bbb@bmail.com.

Expected behavior e.g.:
- When bbb@bmail.com replies, a new conversation should be opened, with the reference to the other conversation.

**Comment by ilyakonovalenko** [comment]
> * When [bbb@bmail.com](mailto:bbb@bmail.com) replies, a new conversation should be opened, with the reference to the other conversation.

I think it is better to add the messave to the same conversation but with some badge or another background color to let agents know third party has replied.

**Comment by freescout-helpdesk** [comment]
This is how FreeScout works. There is no plans to change this behavior for now.

**Comment by ilyakonovalenko** [comment]
Looks like a security breach then. Everyone can answer to forwarded email or to CC/BCC and make agents think it is another customer's request? Can this be prevented by adding some lock via module?
