### ISSUE TITLE
Workflow doesn't work with custom field 'is not set'

### ISSUE THREAD

**Issue by pgy1pgy1** [freescout-helpdesk/freescout#2383]
I've created the 'ETA' filed with 'date' type which is going to be filled manually. I want to have a workflow which adds a tag 'ETA is not set' to every Active ticket where this custom field is not set during 1 day from the ticket creation time. 

Unfortunately the 'date' type is not supported in this scenario.
Expected behavior - if a field returns NULL, the workflow is triggered.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.33
