### ISSUE TITLE
Inbox Module - overlapping folder_id 150

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2386]
Hello.

It seems that there is an issue with the inbox module when a folder with the id 150 is created. Since the inbox folder has a fix id of 150, one of our users see the conversations of his starred folder when clicking on inbox (both id 150).

![image](https://user-images.githubusercontent.com/12407767/201942652-48a3973f-19eb-4fb7-afb6-55bfa16302ae.png)

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in Inbox Module v1.0.1
