### ISSUE TITLE
1.8.33 create new ticket, cannot edit to, cc, bcc, subject..

### ISSUE THREAD

**Issue by bcookatpcsd** [freescout-helpdesk/freescout#2388]
![image](https://user-images.githubusercontent.com/55087301/202238794-63bf5cab-8d57-495b-a836-68a37a90e845.png)

None of the fields are editable.. 

Only the body. 

If you would like more information please let me know.. 

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Fixed in FreeScout v1.8.34

**Comment by bcookatpcsd** [comment]
Confirmed fixed and working.

Greatly appreciate the response.
