### ISSUE TITLE
Search in current mailbox by default, go to ticket number directly

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2390]
We use Freescout company wide. There are support agents working on the support inbox (while having access to some other mailboxes), the purchase department working on the purchase inbox (while having access to the support inbox), and so on.

The Freescout search is always global by default and hidden after a search icon. This comes with several drawbacks:

- Users need to click on the search icon to display the search box. This adds one uneccessary click.
- Agents always get all tickets from all mailboxes and can only filter by their own mailbox _afterwards_ which adds complication and takes time.
- As FS still does not utilize a fast full text search algorithm like ElasticSearch, the first search causes significant delay as way more tickets are crawled than necessary.
- When entering a ticket number as a search term, there is a normal search performed (takes time) and search results displayed first 
- instead of jumping to the corresponding ticket _directly_.

You could argue all those points only take a few seconds more per search, but this accumulates over an 8-hour workday for many agents using Freescout every single day, so we can save many work hours a month by making this more efficient.

We suggest the following improvements:

1. Display the search box permanently (saves a click on the search icon for every search)
2. Limit search to current mailbox by default (saving filtering down the results afterwards and improving search speed dramatically)
3. Adding a dropdown for global search (and some common filters like Conversations I follow, My open conversations)
4. Directly jump to ticket number when the entered, whitespace-trimmed search term matches regex "^[#]?[ ]?(\d+)$" (where the first capture group result is the ticket number)

   ![image](https://user-images.githubusercontent.com/80592577/202395128-3daf8a82-ad1f-453e-99fc-70d2f9e0a167.png)

**Comment by freescout-helpdesk** [comment]
Can be implemented via a custom module. Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by MarcoWel** [comment]
Done: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/391084

Hope you can implement this module quickly, we are happy to pay for it and it would improve our daily work a lot!

**Comment by avenjamin** [comment]
> As FS still does not utilize a fast full text search algorithm like ElasticSearch, the first search causes significant delay as way more tickets are crawled than necessary.

@MarcoWel have you tried the "Faster Search" Module?
