### ISSUE TITLE
LDAP integration not working on current version

### ISSUE THREAD

**Issue by COSmmahoney** [freescout-helpdesk/freescout#2391]
hello all,

im new to freescout and we have been using it for a few months as we get ready to transition away from spiceworks. we just purchased all the modules we will need, however, when in installed the LDAP Integration module (version 1.0.22), i was able to do the initial setup, but when i saved the settings, it gave me the whoops page. the logs stated:

2022/11/16 20:27:21 [error] 930#930: *1 FastCGI sent in stderr: "PHP message: PHP Deprecated: Optional parameter $hosts declared before required parameter $port is implicitly treated as a required parameter in /var/www/html/Modules/Ldap/Overrides/Adldap/Connections/Ldap.php on line 480" while reading response header from upstream, client: xxx.xxx.xxx.x, server: helpdesk.domain.com, request: "POST /app-settings/ldap/ajax HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "helpdesk.domain.com", referrer: "https://helpdesk.domain.com/app-settings/ldap" 

ive tried removing and re-adding the module but it kept saying whoops and i couldnt get back to the ldap config page. after trying the troubleshooting and other issue requests, im now only getting php depreciation errors and it wont load. see php errors below. im on ubuntu lts 22.04.1 and PHP 8.1.2

 (1/3) ErrorException
strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated

 (2/3) ErrorException
strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /var/www/html/Modules/Ldap/Resources/views/settings.blade.php)

 (3/3) ErrorException
strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /var/www/html/Modules/Ldap/Resources/views/settings.blade.php) (View: /var/www/html/Modules/Ldap/Resources/views/settings.blade.php)

any help would be greatly appreciated as we do like this software quite a bit, and one of our goals of our new help desk is a self service portal for all our staff.

Thanks,
Mathew

**Comment by freescout-helpdesk** [comment]
Fixed in LDAP Module v1.0.23.
