### ISSUE TITLE
Search with no selected mailbox displays all customers (not just the customers of mailboxes I have permission to)

### ISSUE THREAD

**Issue by giemes** [freescout-helpdesk/freescout#2393]
In Addition to #2370 (the conversations are now perfectly filtered - THNX!) - there are the following 2 scenarios:
setting:
there are 2 (or more) mailboxes: mailbox id = 1 and id = 2
I have a user with permission for just mailbox = 1

a) I click on search with the current selected mailbox: the conversations of the current selected box are shown - PERFECT
b)  I click on search without a selected mailbox (so global search): conversations of all my available boxes where I have permission to are shown - PERFECT

But - in the search result also the customers are displayed in the 2nd tab and this acts differently:

ad a) I selected a mailbox: just the customers of this mailbox are selected/displayed - PERFECT
ad b) If I do not have selected a mailbox: ALL customers instance-wide and not just the customers of my my available boxes where I have permission to are shown ... 

I know you stated, that the customers are "instance wide" - thats fine and a good feature!
But the selection of all customers are a security/permission issue, that I do see all customers where I do not have the permission to.
Especially interesting, that the search is reacting as desired when a box is selected and the fix for #2370 works like a charm - so I think the possible functions are right there.

Thank you reviewing - this would help a lot!

**Comment by freescout-helpdesk** [comment]
This won't change. See: https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-have-separate-contactscustomers-per-mailbox

**Comment by giemes** [comment]
I fully understand - and thats good to have - that the customers are singular over all mailboxes in the datemodel/architecture. That totally makes sense!

Most likely I did not communicate my "wish":
What I do not get is, that the "default" viewing of the data is my only concern:

This is the result when I select the Mailbox I have access/permission to:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/16294248/202657685-7f07b7ef-d27e-43b0-b4ee-e05ce4321d18.png">

--> This is PERFECT!

When I select NO Mailbox (or come from the search-button in the top-right-corner) I see the relevant conversaions (thnx for fixing that) but all customers. As you can see: Same amount of conversations but ALL customers (in our test-environment):

<img width="679" alt="image" src="https://user-images.githubusercontent.com/16294248/202658089-6cbd7ec4-a408-4fda-9c8a-d6e08c4c95d7.png">

A small and simple fix that works like (pseudocode): no mailbox is selected - I use the filter logic to get the customers just for conversations for my mailbox ... Everything is already implemented just the "defaulting" is not there ... 

Maybe - if someone needs this feature as it is now - we could create a setting so that the search is
a) done like it is now
b) also select just the customers of my mailboxes-conversations and "not all"

OR - alternatively:
if this is (due to the user-permission - mailbox - customer (I know that there is "one hop more" than in the conversations) too performance-critic/complicated - we could also have a setting that says: Search without a mailbox brings no customers as result - this would work on a "data separation point of view" as well ... 

Thank you for "once again reading my lines here" and discussing it / thinking about it ...
