### ISSUE TITLE
[request] new button "remove all attachments" on forwarding message

### ISSUE THREAD

**Issue by schengawegga** [freescout-helpdesk/freescout#2394]
On forwarding an email, all attachments in the conversation are included in the forwarding message.
It will be very nice, if there was an option to delete all attachments from this forwarding message quickly.

On my behalf, it is very common, that there are a hundred of attachments in an active conversation, because our customers have multiple embeded images in their signatures. And deleting them all, one by one in the forwarding message, is not practical.

I´m very greatful, if you will implement this feature.
Thanks for your great work.

**Comment by freescout-helpdesk** [comment]
This can be implemented via a custom module.
