### ISSUE TITLE
[request] checkbox for turn off mail history in actual reply message

### ISSUE THREAD

**Issue by schengawegga** [freescout-helpdesk/freescout#2395]
There is an general option in the settings (Conversation History), if and how many historical messages are included in the reply messages.
I set this to "Include the last message", and i most cases, this will be fine.

But, from time to time, there are sporadic cases, where i don´t want to include historical messages, because there are sensible informations in the history. And this cases are so rare, that i don´t want to go to the settings, and change the setting for only one message, to change it back after sending out the message.

So it would be very nice, if there was an option in the reply message, to turn off the historical inclution in this specific reply message.

This would be very nice, and i´ll be very thankful for this feature.

Thanks for your great work.

**Comment by freescout-helpdesk** [comment]
There is an option under "Send" button dropdown.

**Comment by schengawegga** [comment]
Oh. I am sorry. My fault. I haven´t seen it. Thanks for your support.
