### ISSUE TITLE
Show email address in reply and make it editable

### ISSUE THREAD

**Issue by schengawegga** [freescout-helpdesk/freescout#2396]
In the reply message, there are the Cc and the Bcc addresses be shown, but not the "To" address.
It would be nice, if the "To" address can be displayed here too.

Because, in conversations with more than one person, i can not see, wich address i chosen in the "To" field on the reply message.

And it would be even nicer, if the "To" address can be changed, like in the forwarding message.

Because in several cases, i want to forward a message to another person, but this message should be staying in this conversation.
By forwarding, a new conversation will be created, and i have to merge them afterwards.

It would be very nice.

Thanks for your great work.

**Comment by e-rwan** [comment]
The [CRM module](https://freescout.net/module/crm/), among other things, will display more customer informations.

![alt text](https://freescout.net/wp-content/uploads/edd/2020/11/help-desk-customer-profile.png)

keeping forwarded message, that does not include original sender, in the same conversation could be confusing as to who has read what.

**Comment by freescout-helpdesk** [comment]
It already works as you are saying. If some customer has more than one email:
- When replying you can choose customer's email
- Messages sent to customers with more than one email always show "To"

**Comment by schengawegga** [comment]
Thanks for your answer. You are right. If more then one customers in the conversation, a dropdown appears, where i can choose the recipient.

Sorry for the ticket and thanks for the great tool.
