### ISSUE TITLE
Translate try ends up in error

### ISSUE THREAD

**Issue by Soundmagic2** [freescout-helpdesk/freescout#2398]
Trying to do a translation for snooze module (but error happens also for other moduls).
Freescout 1.8.35 on Ubunutu LTS22

I select German as translation target,

Getting this error (also for other languages)

laravel.log:
htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated (View: /var/www/html/resources/views/vendor/translation-manager/index.blade.php) {"userId":1,"email":"marco@gastroshark.de","exception":"[object] (ErrorException(code: 0): htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated (View: /var/www/html/resources/views/vendor/translation-manager/index.blade.php) at /var/www/html/resources/views/vendor/translation-manager/content.php:155, ErrorException(code: 0): htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated at /var/www/html/resources/views/vendor/translation-manager/content.php:155)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
