### ISSUE TITLE
Mailbox name is not valid mUTF-7 

### ISSUE THREAD

**Issue by invmedia** [freescout-helpdesk/freescout#2399]
Hi!

I have two questions. 
1) I have the same problem. I have installed versions 1.8.35. I am a new user of FreeScout. Yesterday I installed, connected the first inbox. I have the same error in the logs: "INBOX.Investments; Error: Mailbox name is not valid mUTF-7 (0.001 + 0.112 + 0.111 secs)" How can I fix it? I want to be able to access IMAP folders.
2) When I delete a message in FreeScout, will it also be deleted from the mail server if I have an IMAP connection?

_Originally posted by @invmedia in https://github.com/freescout-helpdesk/freescout/issues/2002#issuecomment-1321136794_

**Comment by freescout-helpdesk** [comment]
1. It looks like you are using Dovecot as a mail server. The problem is on Dovecot's side, not on FreeScout's.
2. https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-email-develed-from-my-mail-server-when-i-delete-in-freescout

**Comment by invmedia** [comment]
Thanks for the tips. Can I do something with this "Dovecot"? I have hosting with OVH. change hosting?

**Comment by freescout-helpdesk** [comment]
Unfortunately we have no idea. Contact mail server developers.

**Comment by invmedia** [comment]
I contacted OVH. They asked me to contact Free Scout to indicate which aspect of the mailbox exactly the mUTF-7 encoding in the error message described applies to. Could you please help me?

**Comment by freescout-helpdesk** [comment]
We have not idea. "Mailbox name is not valid mUTF-7" - this is the string returned by their server. Ask them to find this string in their code.
