### ISSUE TITLE
Can't send regular emails, but test emails do get sent (SES and Mailgun)

### ISSUE THREAD

**Issue by vertizio** [freescout-helpdesk/freescout#240]
Weird issue on a *new* installed instance: test emails are being sent. They show up in the logs, but new messages or replies do not get out. I cleared the cache, but no result.
I'm an Amazon SES user, but I don't get my regular messages out on Mailgun either. They don't show up in the SES or Mailgun logs either. However I do see the test emails in the logs, so obviously I use the correct settings.

Any suggestions on how to tackle this?

**Comment by quangbahoa** [comment]
Does ports are opened?

**Comment by phsab** [comment]
> Did you open ports?

Well yes. Like I said: _test emails are being sent. They show up in the logs._

**Test** emails **are** being sent, **regular** emails **not**.

**Comment by adriaanvanrossum** [comment]
[Sjoerd Blom](https://github.com/vertizio), you are being a dick. It's open source software and your seem to demand customer support. Be a little friendlier if you can.

**Comment by vertizio** [comment]
> [Sjoerd Blom](https://github.com/vertizio), you are being a **dick** 
[cut]
> Be a little friendlier if you can.
[cut]

@adriaanvanrossum Now who's blaming who? You're blaming me of being unfriendly, but check your own language as well. Why do you need to use swear words at all? If someone should be a little friendlier it would be you. It so easy to flame people by sending a couple of keystrokes and call them four letter words.

And yes, I know this is open source. I reported an issue (read my first line in my first post) and I already explained test emails do work and get delivered, so ports are open, otherwise the test emails didn't get delivered either.

**Comment by BrianLaughlan** [comment]
@vertizio Could you please tell me how you setup SES? For me, the radio button is disabled in my mailbox connection  settings. I guess I have missed a configuration step somewhere?

![image](https://user-images.githubusercontent.com/8556999/53233917-bca9a080-368e-11e9-97b1-b5f35945c33b.png)

**Comment by vertizio** [comment]
By using the SMTP-settings for Amazon SES.

**Comment by BrianLaughlan** [comment]
@vertizio Ah ok, makes sense. 

What about for fetching emails? SES does not support IMAP right?

**Comment by vertizio** [comment]
@BrianLaughlan :)
SES does indeed not support IMAP.
Though fetching IMAP works like a jiffy. It looks like the routing for sending test emails is following a different route compared to regular SMTP. Haven't completely figured out the code yet (I'm new with this project).

**Comment by vertizio** [comment]
Just fired up a Vagrant box. Installed the distribution version 1.1.6:
The system logs show that the **Test email** is being sent:
![selection_091](https://user-images.githubusercontent.com/2759239/53255834-c5b66400-36c6-11e9-9ce2-fc1a6e10bb58.jpg)
But the regular mail remains in my draft folder:
![selection_092](https://user-images.githubusercontent.com/2759239/53255839-c818be00-36c6-11e9-911c-73bb33772a81.jpg)

Will try PHP mail() later, need to install Mailhog first...

**Comment by vertizio** [comment]
Issue solved!
I had made a typo in the cronline (schedule:run). My apologies for taking up your time! On the other hand quite confusing: apparently the Test e-mails do not get sent through the 'schedule:run'. So that put my on the wrong track.

**Comment by groovelikeapig** [comment]
Hi

I have this same problem =>>>> 

Well yes. Like I said: test emails are being sent. They show up in the logs.
Test emails are being sent, regular emails not.

I am using MIGADU

Can you help me, I am not a dev (I am a musician) and I want freescout to work
