### ISSUE TITLE
Hide Mobile option helpdesk agent/User Profile

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2403]
I would like to know if any module/method to hide the mobile app push notification - ios/android option for the user/helpdesk agent (attached screenshot)

![2022-11-22 00_03_49-Window](https://user-images.githubusercontent.com/13112801/203226353-cb35d799-4bb1-4cf5-a221-fba066a92323.png)

I have already purchased, free scout white label, which is great but user can directly click mobile app and defeat the purpose of white labeling and I am also not interested help desk agent configuring their cellphones

anyway to hide that option, Please help

Thank you

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible.

**Comment by sainiaj** [comment]
But that defeats the purpose of white label, can you please make a module or option admin can hide or disable phone option
