### ISSUE TITLE
Mentions Module Does Not Display Users in Existing Mailbox

### ISSUE THREAD

**Issue by recreational-grade** [freescout-helpdesk/freescout#2407]
I have 1 mailbox that does not display users for mentions in notes:  
![image](https://user-images.githubusercontent.com/3175033/203320125-3bcef2f6-56c6-41b7-980e-d24cbc0ae8e3.png)  
I have 2 other ones that do:  
![image](https://user-images.githubusercontent.com/3175033/203320714-283cbb34-9cd9-4049-8056-938eec53f650.png)  
The only thing I can think of is that I installed the mentions module *after* the mailbox that is not working was created and before the mailboxes that do.  
Currently running `1.8.35` and I've cleared cache with no effect.

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.
Make sure your some users assigned to the mailbox.
Check JS errors in the browser console.

**Comment by freescout-helpdesk** [comment]
You can try to debug it yourself or provide us access to your FreeScout: support@freescout.net

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
