### ISSUE TITLE
Queue nor working - MariaDb error Got an error reading communication packets

### ISSUE THREAD

**Issue by ConvarDeutschland** [freescout-helpdesk/freescout#2408]
Hello,

We have an error that our queue is not working. 
When we start the worker queue manually :

/usr/bin/php7.4 artisan queue:work --queue=emails,default,407ed704f155551700715f56ed1086e0 --sleep=5 --tries=1
After 1 or 2 minutes I get a Killed showing up

Mariadb is showing this error:

Nov 22 15:09:25 freescout mariadbd[477]: 2022-11-22 15:09:25 4081 [Warning] Aborted connection 4081 to db: 'freescout' user: 'freescout' host: 'localhost' (Got an error reading communication packets)

Any Idea what could killer the worked?

Thanks for your help

**Comment by freescout-helpdesk** [comment]
"...aborted connection errors are not easy to diagnose. But in my experience, it’s related to network/firewall issues most of the time." https://www.percona.com/blog/2016/05/16/mysql-got-an-error-reading-communication-packet-errors/
