### ISSUE TITLE
Mysql General error: 1366 Incorrect string value

### ISSUE THREAD

**Issue by KrzysztofCW** [freescout-helpdesk/freescout#241]
Hello,

I have following error:

Error: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xB1k' for column 'last_name' at row 1 (SQL: insert into `customers` (`first_name`, `last_name`, `updated_at`, `created_at`) values (Robert, B±k, 2019-02-08 11:08:03, 2019-02-08 11:08:03)); File: /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php (664)

Mysql current settings are:

init_connect = 'SET collation_connection = utf8mb4_unicode_ci'
init_connect = 'SET NAMES utf8mb4'
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
skip-character-set-client-handshake

mysql> show variables like '%character%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
mysql> show variables like 'collation_database';
+--------------------+--------------------+
| Variable_name      | Value              |
+--------------------+--------------------+
| collation_database | utf8mb4_unicode_ci |
+--------------------+--------------------+

Any idea? Please help.

**Comment by freescout-helpdesk** [comment]
This is weird. Unfortunately we could not reproduce this issue.
