### ISSUE TITLE
page location inside the VM domain.com/users/notifications/1

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2411]
Hi freescout,

can you please redirect me to correct path where is the page located which has the link to Mobile
([Android](https://freescout.net/module/mobile-notifications/) / [iOS](https://freescout.net/module/mobile-notifications/))

I would like to comment/remove the url, we get alot of tickets internally asking for phone app 

i am currently inside /var/html/public

![image](https://user-images.githubusercontent.com/13112801/203424386-999ce42b-b2cf-4b99-88d4-cdf51d5c57ca.png)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/users/subscriptions_table.blade.php
