### ISSUE TITLE
EDD module has no renewal payments, show only active and inactive.

### ISSUE THREAD

**Issue by Arihantkankariya09** [freescout-helpdesk/freescout#2412]
It does not show renewed payments from the same user.Only shows the first purchased, not the most recent one.

**Comment by freescout-helpdesk** [comment]
Can you send a screenshot of some renewed payment in EDD?

**Comment by freescout-helpdesk** [comment]
Are you using https://easydigitaldownloads.com/downloads/recurring-payments/ ?

**Comment by Arihantkankariya09** [comment]
Yes we use recurring payments.

**Comment by freescout-helpdesk** [comment]
The module does not show renewals, only the original payment.

**Comment by Arihantkankariya09** [comment]
Can I request it as a feature or improvement?

**Comment by freescout-helpdesk** [comment]
Sure, here: https://freescout.net/request-feature/
