### ISSUE TITLE
Non-writable files found keeps coming back after running the chrown -R cmd

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2414]
Non-writable files found
/var/www/html/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8

Run the following command ([read more](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server)):
sudo chown -R www-data:www-data /var/www/html

I keep getting this error even after running the chown -R error

can you please provide a solution 

Thank you

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
