### ISSUE TITLE
Notification content not showing

### ISSUE THREAD

**Issue by haaslukas** [freescout-helpdesk/freescout#2415]
I have the issue that I get the orange notification bubble as well as the number of notifications, but the text (or content)per each notification is missing:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/6792476/203969287-10eff62c-ef9b-4c77-b6d3-4962fe3d9cf8.png">

Other users don't have this problem. It's also weird that I see an old date (Oct 21 and it's more than one month later now), but no listings in "Today". Using the mentions module and already cleared the cache on both the server and my machine.

Version: 1.8.35

Any suggestions what could be the issue here?

**Comment by freescout-helpdesk** [comment]
The only way to find is for someone to debug it on your server.
