### ISSUE TITLE
Missing Tickets in Freescouts, but visible in outlook

### ISSUE THREAD

**Issue by bppushly** [freescout-helpdesk/freescout#2416]
Hey Guys,

we just testet around with the system and realized a strange problem. Some tickets show up in outlook but do not show up in
our freescout.
We had two scenarios here:

1. I sent two different tickets with two different subjects from gmail. One arrived in the ticketsystem, the other one didnt. We recevied both mails in outlook.
2. We send an email to an customer (through freescout), he answered that mail but we only see his answer in outlook.

Any idea what the problem could be here?

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs

**Comment by bppushly** [comment]
I just tried two new mails again from gmail.

Both did not arrive, I also did not receive an auto reply. And they are not in the logs.

**Comment by freescout-helpdesk** [comment]
> Any idea what the problem could be here?

Someone opens emails in the mailbox and reads them. Don't do this.

**Comment by bppushly** [comment]
Problem somewhere else. I use exchange, activate notification on fetching problems. Received one. No logs no errors. Went to connection settings, clicked save button, clicked test mail. New emails fetched.

Sent some new test mails, again no fetching notification. Again no logs. Tried saving again and worked again.
