### ISSUE TITLE
Get custom field's value in variable

### ISSUE THREAD

**Issue by pgy1pgy1** [freescout-helpdesk/freescout#2417]
Is there any way to get custom field's value in variable ? In example I've created the 'ETA' date field and want to provide a customer with the estimated time by workflow.

**Comment by freescout-helpdesk** [comment]
Where do you need to use them? In the action to add a note?

**Comment by pgy1pgy1** [comment]
I'd like to email a customer something like this:
_Your ticket  {%conversation.number%} has been assigned to  {%user.fullName%} and will be done on {%ETA_CustomField.value%}_
so, I need  {%CustomField.value%} being available as {%user.fullName%}  in the actions

**Comment by freescout-helpdesk** [comment]
Implemented in Custom Fields Module v1.0.20
