### ISSUE TITLE
location to title tag code

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2419]
Hi where is the location of the basic title tag, it is not inside the index.php file 

/var/www/html/public/index.php

<title>FreeScout</title> location - I would like to change it 

can you please provide/share the full path 
Thank you

**Comment by Xuf00** [comment]
I believe it's in the following file:

/www/html/resources/views/layouts/app.blade.php

**Comment by freescout-helpdesk** [comment]
Yes
