### ISSUE TITLE
Knowledge Base module

### ISSUE THREAD

**Issue by quangbahoa** [freescout-helpdesk/freescout#242]
Hi,
Is there any knowledge base module on roadmap?

Thanks for great open source project. 

Regards,

**Comment by freescout-helpdesk** [comment]
It will be implemented, but not very soon.

**Comment by quangbahoa** [comment]
Thanks

**Comment by Ryanhgreen** [comment]
Loving the work @freescout-helpdesk. Any update on the timelines for the knowledge base module?

**Comment by freescout-helpdesk** [comment]
Unfortunately not, maybe around 1 year.

**Comment by jmtoledano** [comment]
Hi!, Any news about this? 
Thanks for the work!

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/knowledge-base/
