### ISSUE TITLE
Auto-assign new user (via OAuth / SSO) to mailbox

### ISSUE THREAD

**Issue by ddresch** [freescout-helpdesk/freescout#2420]
We have the following setup. 

1. we use WordPress as our OAuth server using [https://wp-oauth.com/documentation/](https://wp-oauth.com/documentation/?utm_source=plugin-admin&utm_medium=settings-page).
2. we use freescout `OAuth & Social Login` module to do the Single Sign On
3. we use the setting `Automatically create non-existing users`

In the default behavior, the login works, but the user can do nothing. Only after the admin or a mailbox manager adds this new user to a mailbox, this new user is ready to go.

For our case, I added this one line to the `OAuthLoginController.php`:

```PHP
$user->mailboxes()->attach(1); // 1 is the mailbox_id we want each new user to be attached to
```

My question is—does it make sense to build a suitable UI for this kind of handling in the OAuth module? Do you accept a PR for this, or can I achieve the same outcome somehow differently?

**Comment by freescout-helpdesk** [comment]
You can do it. See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by ddresch** [comment]
Also means my approach is correct in this case and there is no other existing way of doing it?

**Comment by ilyakonovalenko** [comment]
It looks a bit unsafe if the module will assign any mailboxes automatically. I think it is better to modify the module in the way you need.

**Comment by freescout-helpdesk** [comment]
> Also means my approach is correct in this case and there is no other existing way of doing it?

Yes. Correct.
