### ISSUE TITLE
Emptying IMAP inbox

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2421]
Hey,
I use Freescout with M365.
I wanted to know if its safe to delete the content in the inbox after its pulled into freescout? Would it affect anything in freescout?

I ask, because the inbox is starting to fill up, an dit would just be easier to put it on a schedule to delete all emails over a week old.

**Comment by freescout-helpdesk** [comment]
"Show Original" window fetches email directly from the mailbox via IMAP to show it. If it can't do it - content from DB will be shown.

**Comment by netspear** [comment]
So it would be safe to empty to inbox? Meaning it wouldn't delete emails from FreeScout?

**Comment by freescout-helpdesk** [comment]
Yes
