### ISSUE TITLE
Ticket assigned to Workflow triggered

### ISSUE THREAD

**Issue by pgy1pgy1** [freescout-helpdesk/freescout#2423]
A workflow condition 'Assigned to user' 'Is not equal to' 'Unassigned' triggered as 'assigned to Workflow' that should not be. 
Expected behavior: assignment to a person from the 'Users' list triggers

**Comment by freescout-helpdesk** [comment]
Could you please explain a bit more, with screenshots.

**Comment by pgy1pgy1** [comment]
I've created the following workflow
![Workflow Conditions](https://user-images.githubusercontent.com/68113136/204767131-124ce24d-9369-45ee-8047-1222c8f964fa.png)
![Workflow Actions](https://user-images.githubusercontent.com/68113136/204767209-8e9752b7-032d-46f5-bcbb-22c1b040318b.png)

Which leads me to receive this email
![resulting_email](https://user-images.githubusercontent.com/68113136/204767222-7df0f185-aefb-44a0-9407-6e40bcd07656.png)

**Comment by freescout-helpdesk** [comment]
We still can't understand the issue fully. Could you please write step-by-step instruction on how to reproduce it.

**Comment by pgy1pgy1** [comment]
1) Disable all active workflows
2) Create a new workflow with condition and action as in the previous pics
3) Email to a Servicedesk 
4) Get a notice about assignment to Workflow 

![workflow](https://user-images.githubusercontent.com/68113136/204833275-a8ba1440-474f-4ef2-9afa-2b0267f0b5c5.jpg)

**Comment by ilyakonovalenko** [comment]
What is wrong here? The variable will always relate to workflow system user.

**Comment by ilyakonovalenko** [comment]
> The current behaviour always inform that tickets are assigned to Workflow that's useless from the customer's perspective.
This is clearly mentioned on the module page. The variable is always related to user replying (in the case - workflow user).

> May be you can suggest another way to get such notification?
You can manually type the assignee name.

**Comment by pgy1pgy1** [comment]
> > May be you can suggest another way to get such notification?
> 
> You can manually type the assignee name.

ok, I've created eight more workflows to reflect assignment to one of our eight engineers.
