### ISSUE TITLE
Matter bridge support?  Nextcloud support

### ISSUE THREAD

**Issue by ioscanner** [freescout-helpdesk/freescout#2424]
Is there any place to request features?  Such as Matter bridge or Nextcloud support?

Matter Bridge would allow more systems.  I have seen a few people talk about this, but seems no response on if something was coming.

I just noticed you have kanban module that would fit nicely into Nextcloud to open a deck and work issues direct from Nextcloud. 

Or just have a module that would notify users when changes to tickets happen over the API or create a native Nextcloud freescout module.

Thanks

**Comment by freescout-helpdesk** [comment]
Here: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
Do you need an integration with Mattermost or Nextcloud? What exactly the integration should do?

**Comment by ioscanner** [comment]
Direct in Nextcloud would be nice, but matter bridge is supported and might be a better option because then it can be used to slack and other solutions that support Matter.

We do lots of turn key and each client would have many of the modules license. We like FreeScout and all it offers!

**Comment by freescout-helpdesk** [comment]
What do you mean under "matter bridge"?

**Comment by ilyakonovalenko** [comment]
> What do you mean under "matter bridge"?

It seems https://github.com/42wim/matterbridge

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request here: https://freescout.net/request-feature/
