### ISSUE TITLE
Speed up fetching process  every few seconds

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2425]
Hi currently Free scout grabs new emails every 1 minute or so, using imap protocol

can we speed up the process grab fetch email every few  seconds or even push method 

I am using office365 email 

Thank you

**Comment by ilyakonovalenko** [comment]
No you can't. Cron can only run every minute, not every second.

**Comment by sainiaj** [comment]
Is it a certain script,

I can make script run on boot, every x second


Thank you

**Comment by ilyakonovalenko** [comment]
> Is it a certain script,

No. Normal Linux crontab can not run every x second, the minimum delay is 1 minute. You can probably do what you want with system services which can execute some command every x seconds. However, it makes really no sense.
