### ISSUE TITLE
any way to implement simple ITIL in submit a ticket request?

### ISSUE THREAD

**Issue by COSmmahoney** [freescout-helpdesk/freescout#2427]
is there any way to can implement this within freescout? i have the custom fields and workflow modules, but im not seeing any way we can chain the ticket type (Incident, Problem, Service Request) to defined issue (hardware, software, access, etc).

**Comment by ilyakonovalenko** [comment]
You can use tags and custom folders module for this. You can also write your own module to achive the goal.

**Comment by COSmmahoney** [comment]
thanks, ill try messing around with it
