### ISSUE TITLE
out of office 30 minute increments

### ISSUE THREAD

**Issue by COSmmahoney** [freescout-helpdesk/freescout#2429]
is it possible to get 30 minute increments? our office hours are 0830-1630

thanks

**Comment by freescout-helpdesk** [comment]
No for now. See https://freescout.net/request-feature/ and https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by COSmmahoney** [comment]
thanks, ive modified the schedule_select.blade.php to allow for 30min increments and will be testing after hours with the auto-reply module

**Comment by COSmmahoney** [comment]
modified php works great, see below for updated code if you want to apply to the module (change in bold)

`<select name="settings[officehours.schedule][{{ $day }}][0][from]" class="form-control">
    <option value=""></option>
    <option value="off" @if (!empty($settings['officehours.schedule'][$day][0]['from']) && $settings['officehours.schedule'][$day][0]['from'] == 'off') selected @endif>{{ __('Day off') }}</option>
    @for($i = 0; $i < 24; $i++)
        @php
                $value = $i.':00';
		**$value = $i.':30';**
        @endphp
        <option value="{{ $value }}" @if (!empty($settings['officehours.schedule'][$day][0]['from']) && $settings['officehours.schedule'][$day][0]['from'] == $value) selected @endif >{{ $value }}</option>
    @endfor
</select>
&nbsp;–&nbsp;
<select name="settings[officehours.schedule][{{ $day }}][0][to]" class="form-control">
    <option value=""></option>
    <option value="off" @if (!empty($settings['officehours.schedule'][$day][0]['to']) && $settings['officehours.schedule'][$day][0]['to'] == 'off') selected @endif>{{ __('Day off') }}</option>
    @for($i = 0; $i < 24; $i++)
        @php
                $value = $i.':00';
        @endphp
        <option value="{{ $value }}" @if (!empty($settings['officehours.schedule'][$day][0]['to']) && $settings['officehours.schedule'][$day][0]['to'] == $value) selected @endif >{{ $value }}</option>
    @endfor
`
