### ISSUE TITLE
Custom Mailbox Signatures Module - Note shows custom signature

### ISSUE THREAD

**Issue by johnmichaelgibson** [freescout-helpdesk/freescout#2431]
Creating or editing an internal note displays the most recently used custom email signature at the bottom of the note. 
Should notes be showing email signatures at all ?

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://demo.freescout.net ?
Could you please send a screenshot.

**Comment by johnmichaelgibson** [comment]
Yes, the issue can be reproduced on the demo:
![Screenshot 2022-11-30 at 3 07 42 PM](https://user-images.githubusercontent.com/2501889/204898080-aee46d2d-4b9c-43f1-ace8-e98fa6e7e125.png)

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Signatures Module v1.0.8
