### ISSUE TITLE
Queue Delay

### ISSUE THREAD

**Issue by andyknas** [freescout-helpdesk/freescout#2438]
We've noticed a delay in sending emails. CRON and permissions in system status all show fine. We had replied to tickets but the emails didn't get sent til the evening. checking send log, it looks like it went the same time the day before too. Using latest build. Please advise.
<img width="850" alt="Screen Shot 2022-12-03 at 9 38 38 AM" src="https://user-images.githubusercontent.com/1693058/205449241-8e5970cd-e367-40fc-ab9e-5cab0189ab09.png">

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

**Comment by andyknas** [comment]
I see three. So I troed to clear cache and that returned an error.

root@roxy:~# ps aux | grep queue
root       5484  0.0  0.0   4636   832 ?        S    22:00   0:00 sh -c '/usr/bin/php8.0' 'artisan' queue:work --queue='emails,default,4c1595e4ac21224bf898856ebd1e3a01' --sleep=5 --tries=1 > '/var/www/html/freescout/freescout/storage/logs/queue-jobs.log' 2>&1
root       5485  0.0  2.4 335924 46396 ?        S    22:00   0:00 /usr/bin/php8.0 artisan queue:work --queue=emails,default,4c1595e4ac21224bf898856ebd1e3a01 --sleep=5 --tries=1
root       9542  0.0  0.1  16792  2232 pts/0    S+   22:40   0:00 grep --color=auto queue
root@roxy:~# php artisan freescout clear-cache
Could not open input file: artisan

**Comment by freescout-helpdesk** [comment]
You need to debug this part: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L121

**Comment by andyknas** [comment]
Why does this not work?

```
root@roxy:~# php artisan freescout clear-cache
Could not open input file: artisan
```

When I check queue-jobs.log it looks ok

```
[2022-12-06 09:08:14] Processing: App\Jobs\SendReplyToCustomer
[2022-12-06 09:08:15] Processed:  App\Jobs\SendReplyToCustomer
[2022-12-06 09:08:15] Processing: App\Jobs\TriggerAction
[2022-12-06 09:08:15] Processed:  App\Jobs\TriggerAction
```

**Comment by freescout-helpdesk** [comment]
To run `php artisan` you need to be in FreeScout's root folder. We'll close this. You need someone who can debug it on your server, see https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
