### ISSUE TITLE
PHP-IMAP on PHP 7.3 on Mac

### ISSUE THREAD

**Issue by PierfrancescoElia** [freescout-helpdesk/freescout#244]
Hi everyone :)

I am trying to install FreeScout on my Mac, but I incurred in a problem that is blocking me.

FreeScout requires php-imap module to work. I've installed PHP with:
`brew install php` 
and now che command `php -v` returns:
`PHP 7.3.2 (cli) (built: Feb 14 2019 10:08:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2, Copyright (c) 1999-2018, by Zend Technologies`

How can I install a compatible _php-imap_ extension with PHP 7.3 that works for FreeScout?

Any advice/suggestion is appreciated! ;)

Thanks again! :)

**Comment by PierfrancescoElia** [comment]
Another small question. Just installed _apcu_ via `pecl install apcu` and now I can't figure out how to enable that with my environment. Any ideas?

**Comment by freescout-helpdesk** [comment]
Have you tried https://stackoverflow.com/questions/51433648/adding-imap-to-php-7-2-on-osx ?
