### ISSUE TITLE
License Migration

### ISSUE THREAD

**Issue by maukunze** [freescout-helpdesk/freescout#2442]
Hello i have a problem with the license migration between two freescout instances.
I did set up one instance with the docker container of tiredofit and configured it. Then i bought some modules and activated it on this instance. After some trouble with the docker instance i installed an instance of freescout on ubuntu and everything went well. I started transferring the licenses as stated in your FAQ and it worked well. 
Now after the weekend one license went deactivated, the LDAP module, and now i cant activate the license.
I went to the old instance and checked if somehow it was activated there, but it wasnt.

Has someone experienced the issue also or has the support an idea of how to activate the module again?

**Comment by netspear** [comment]
Hey,
On the Modules Page of your freescout instance, Click the button that say "Deactivate Licence"
Choose the "LDAP Integration" and enter your license key.
Click Deactivate.

Once deactivated, you should be able to activate it again

**Comment by maukunze** [comment]
Hey @SecureCPU ,
yes thats exactly what i did, but now i cant activate the license on both instances.
I always get the above commented error as if the license is still activated somewhere.

**Comment by minghuiyu** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-im-activating-deactivating-a-module-but-it-stays-inactive-active

**Comment by maukunze** [comment]
@minghuiyu 
i also tried that but it didnt help

**Comment by freescout-helpdesk** [comment]
Send your keys to support@freescout.net, we'll take a look.
