### ISSUE TITLE
SPAM FILTER - what are the fields on the top?

### ISSUE THREAD

**Issue by zuzullo** [freescout-helpdesk/freescout#2443]
What are these 2 fields ont he top of the SPAM filter settings?
Are they to black list or to white list emails?
What kind of input is accepted here? Can I input domains to be white listed here such as "@zaui.com"
![image](https://user-images.githubusercontent.com/9383857/205770675-a7708a16-8f86-402d-9e0b-f04d1d45a44e.png)

**Comment by freescout-helpdesk** [comment]
They are black list type filters. They work only for Subject and Body.

**Comment by freescout-helpdesk** [comment]
Sure. Feel free to submit a feature request: https://freescout.net/request-feature/
