### ISSUE TITLE
e-mail not send without error and keeps blocking the queue

### ISSUE THREAD

**Issue by iReserveApps** [freescout-helpdesk/freescout#2448]
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/61552383/206292333-a952197b-e690-49c4-84ac-8d15902ee720.png">

Help needed!
Analysing this for days. Some of the email replies get stuck. 
The queue is then retrying and retrying. We checked all the logs and even tried to debug the job. 
We cannot find any information why the specific email is not handled. 

How can we capture this or where to store the error. Apparently something fails along the way of trying to send.

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.
Click "View Details" button next to each failed job.

**Comment by iReserveApps** [comment]
That is one big step further, thanks for swift reply. 

`[root@ 1]# pwd
/var/www/vhosts/<domain>/httpdocs/storage/app/attachment/5/7/1
[root@ 1]# ls -l "/var/www/vhosts/<domain>/httpdocs/storage/app/attachment/5/7/1/Scherm-afbeelding-2022-12-07-om-11.57.43.png"
ls: kan geen toegang krijgen tot /var/www/vhosts/<domain>/httpdocs/storage/app/attachment/5/7/1/Scherm-afbeelding-2022-12-07-om-11.57.43.png: Bestand of map bestaat niet
[root@ 1]# 
ls -l
totaal 368
-rw-r--r-- 1 <user> psacln 376472  7 dec 15:02 Schermafbeelding-2022-12-07-om-11.57.43.png`

It seems there is a dash inside the screenshot the user has attached. 

In the db the attachment can be found
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/61552383/206386736-1f57a850-3eb7-46d2-921a-ab7de407dde8.png">

In the jobs table, the job can be found, but not the attachment (probably WAI, but just to be complete). 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/61552383/206387535-e9e0b475-6d12-4e65-9b9a-5f47ca2e8841.png">


Its clear that the file the email sending job is trying to find is not correct, but how can such a thing happen?
And can we fix this somwhere in the data?

**Comment by freescout-helpdesk** [comment]
Most likely it happens due to https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by iReserveApps** [comment]
Before submitting this ticket we have checked the complete troubleshooting, including the permissions issue. 
We have made sure the complete storage folder has the right permissions. 

We have now also checked with user. 
Trying to reproduce. 
On MacOs: make screenshot. 
Upload in Freescout. IF there is a space, the attachment is uploaded by replacing the space with a dash ("-"). 
Two tests: one with space and one without. In both cases, the folder is created, the image is placed. Spaces are converted. 

In the case of the orignal post: the file IS created (so permission issues are not the case?) but with the wrong name.

**Comment by iReserveApps** [comment]
In addition to last
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/61552383/206443380-efb35bea-9b9d-47a3-8740-bd93fd7b499b.png">

If we check the app log we see a clear difference between the first and second hyphon/dash.
The character (which is replaced) is <0xad>

**Comment by freescout-helpdesk** [comment]
The problem was in the soft hyphen in the attached file name.
