### ISSUE TITLE
Cpanel Bandwidth issue

### ISSUE THREAD

**Issue by JinksKid** [freescout-helpdesk/freescout#2449]
Hi All.

Having an issue where everytime FreeScout fetches emails, it seems to download every email again including attachements.
With the cron doing this every minutes, Cpanel is reporting many GB of bandwidth used per day with just a few small attachements in the mailboxes. I have tried to switch between imap and pop3 with no difference. I have hit my 20GB limit in only 3 days.

Any suggestions?

**Comment by freescout-helpdesk** [comment]
FreeScout fetches only unread emails. Are you using any non-official modules?

**Comment by JinksKid** [comment]
Only LJPc calendar module  i have disabled it. Will see what happens

**Comment by freescout-helpdesk** [comment]
Make sure that emails are actually marked as "read" after fetching in your mail server.

**Comment by JinksKid** [comment]
Yep.  All marked as read in the mail server

**Comment by JinksKid** [comment]
With all modules disabled and with 2 emails in the mail server both marked as read I am still getting high bandwidth usage every minute.

![image](https://user-images.githubusercontent.com/52492202/206593253-1a1e0819-8f0c-4840-bd98-bc71ebabf144.png)

![image](https://user-images.githubusercontent.com/52492202/206592583-1a68b1b4-c71b-4487-8a01-63cb7ac52090.png)

**Comment by freescout-helpdesk** [comment]
Try to debug https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php

**Comment by JinksKid** [comment]
Found the issue.
If IMAP Folders dont match the IMAP server it will do some weird download everything every time the cron runs. So pressing 'Get Folders' solves the issue
