### ISSUE TITLE
Windows Server queue:work

### ISSUE THREAD

**Issue by bencgreen** [freescout-helpdesk/freescout#245]
I've installed FreeScout on a Windows Server - which the installation guide says is supported - but I'm having a few issues.

I fixed the schedule:run issue by installing cygwin and adding it to PATH - the cron executes unix-only commands, so you shouldn't really say you support IIS without extra steps...

However, in System, I have the following error for queue:work

`Last run: ? Last successful run: ? Cleared cache to force command to start.`

And, I've had to setup the scheduler to kill the artisan scheduled task if it's still running after a couple of minutes because sometimes it simply hangs.

I don't suppose you have a windows-friendly console class, so I can remove cygwin and get it all working natively on Windows?

**Comment by freescout-helpdesk** [comment]
Have you checked logs?

**Comment by freescout-helpdesk** [comment]
Closing for now activity.
