### ISSUE TITLE
Custom Folder / Tag Search

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#2451]
Hey,

is it somehow possible to make a custom Folder with a filter like (where active and "tag1" + "tag2" exists) same goes for search. Currently it seems freescout is only supporting to search for one specific tag but not a mix of tags.

I want all tickets tagged with tagA and tagB. 
I want all tickets tagged with tagC or tagD.

Just like the workflow posibility. 

Is that possible somehow with a special syntax?

**Comment by freescout-helpdesk** [comment]
Unfortunately no for now.
