### ISSUE TITLE
[Request] Compatibility with PHP 8.2

### ISSUE THREAD

**Issue by mzch** [freescout-helpdesk/freescout#2454]
Now Freescout can't be run with PHP 8.2. Do you plan to make Freescout compatible with PHP 8.2? If so, when will you be able to go public?

**Comment by freescout-helpdesk** [comment]
Next FreeScout releases will be introducing PHP 8.2 support.

**Comment by mzch** [comment]
Great! Thanks @freescout-helpdesk ! :)
