### ISSUE TITLE
No input file specified web installer error

### ISSUE THREAD

**Issue by TwoBrake** [freescout-helpdesk/freescout#2456]
Hey there! I am trying to setup Freescout with the web installer and I have followed all of the steps provided on the instructions page but I am still receiving an error.

I tried using the `php8.1-fpm.sock` first and it said "No input file specified".
After that, I assumed it had to due with the PHP version, so I tried `php7.4-fpm.sock` and then it said "File not found".

Please keep in mind that while doing this, I was opening this in the browser using `<domain>/install`.

Thank you in advance.

**Comment by freescout-helpdesk** [comment]
Incorrect nginx config.

**Comment by pf248** [comment]
Did you put in the correct php version in your nginx config in this line:
fastcgi_pass unix:/run/php/php8.1-fpm.sock;

(and also check if php-fpm is running and installed correctly)

Did a few different installations in the past few weeks and had to change it depending on the installed php version to make it work (if you made a manual installation and not via the FS ubuntu script) or the installer does not work properly.

**Comment by TwoBrake** [comment]
> Did you put in the correct php version in your nginx config in this line:
> fastcgi_pass unix:/run/php/php8.1-fpm.sock;
> 
> (and also check if php-fpm is running and installed correctly)
> 
> Did a few different installations in the past few weeks and had to change it depending on the installed php version to make it work (if you made a manual installation and not via the FS ubuntu script) or the installer does not work properly. 
> 

I changed the line to `php8.1-fpm.sock` and check if PHP-FPM was running and it was. Then when I restarted Nginx and went to the site `<domain>/install`, it said "No input file specified".

Also, I don't know if this is normal, but when I go to the domain without the `/install`, it says "403 Forbidden".

**Comment by freescout-helpdesk** [comment]
Good to know.

**Comment by hgolshenas** [comment]
> Incorrect nginx config.

@freescout-helpdesk 
i have the same error with iis 10 php 8.1.21 and mysql 5.7
all the steps are done
