### ISSUE TITLE
Enhancement: add reporting / analytics

### ISSUE THREAD

**Issue by gab-cass** [freescout-helpdesk/freescout#246]
Hi,

This is a really nice app that works great. Any chance to implement some sorts of reporting / analytics?

Thanks.

**Comment by freescout-helpdesk** [comment]
Yes. Reports will be implemented as a module.

**Comment by Benjii699** [comment]
Hi, is the reporting module still in development?

**Comment by freescout-helpdesk** [comment]
Maybe will be released this year.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/reports/
