### ISSUE TITLE
'502 Bad Gateway' after upgrade to 1.8.19

### ISSUE THREAD

**Issue by bulkinav** [freescout-helpdesk/freescout#2460]
Hello,

Previously, I used version 1.8.12 as self-hosted vie Docker, and today I desided to upgrade to the latest FreeScout version. But after the update, the error "502 Bad Gateway" appears.

I can't found any errors associated whith this problem in /logs directories (from the inside Docker container).

/log/php-fpm/error.log contains only the following:

```
[13-Dec-2022 11:52:15] NOTICE: fpm is running, pid 2362
[13-Dec-2022 11:52:15] NOTICE: ready to handle connections
[13-Dec-2022 12:50:48] NOTICE: [pool www] child 2380 exited with code 0 after 3512.556216 seconds from start
[13-Dec-2022 12:50:48] NOTICE: [pool www] child 5395 started
[13-Dec-2022 12:51:08] NOTICE: [pool www] child 2381 exited with code 0 after 3532.238491 seconds from start
[13-Dec-2022 12:51:08] NOTICE: [pool www] child 5456 started
[13-Dec-2022 12:59:49] NOTICE: Terminating ...
[13-Dec-2022 12:59:49] NOTICE: exiting, bye-bye!
[13-Dec-2022 13:03:20] NOTICE: fpm is running, pid 2362
[13-Dec-2022 13:03:20] NOTICE: ready to handle connections
[13-Dec-2022 13:10:37] NOTICE: Terminating ...
[13-Dec-2022 13:10:37] NOTICE: exiting, bye-bye!
[13-Dec-2022 13:13:31] NOTICE: fpm is running, pid 2364
[13-Dec-2022 13:13:31] NOTICE: ready to handle connections
```

/log/nginx/error.log contains:

```
2022/12/13 12:56:33 [warn] 2237#2237: *2312 upstream sent more data than specified in "Content-Length" header while reading upstream, client: 192.168.160.1, server: , request: "GET /thread/read/11175/53834/ HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "mysite.ru"
2022/12/13 13:03:39 [warn] 2238#2238: *15 upstream sent more data than specified in "Content-Length" header while reading upstream, client: 192.168.192.1, server: , request: "GET /thread/read/11145/53812/ HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "mysite.ru"
2022/12/13 13:07:49 [warn] 2238#2238: *381 upstream sent more data than specified in "Content-Length" header while reading upstream, client: 192.168.192.1, server: , request: "GET /thread/read/11009/53820/ HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "mysite.ru"
```

Experimentally, I managed to find out that the problem occurs in the version 1.8.19 (because version 1.8.18 works fine):
https://github.com/freescout-helpdesk/freescout/commit/fe4c69e3a981ae664235de56cead6cf932debb52 - but I don't understand what can cause such a fatal server error here.

Here https://github.com/tiredofit/docker-freescout/blob/master/CHANGELOG.md the Freecsout 1.8.19 associated with 1.15.51 version of Docker image and it does't contain any changes, except for upgrading the version to 1.8.19 of FreeScout.

I also disabled all active modules, but it didn't help.

How I can identify the cause of this problem?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by bulkinav** [comment]
@freescout-helpdesk of course I've read this, but unfortunately it doesn't describe the problem I'm facing.

Where can I view detailed logs to understand more precisely what is causing this problem? In /log/ directories this error is not present.

And again - no problems with FreeScout 1.8.12 and '502 Bad Gateway' error with 1.8.13 and above.

**Comment by freescout-helpdesk** [comment]
Check `/storage/logs`?. Use another update method and upgrade to the latest FreeScout version. There is no other alternatives.
