### ISSUE TITLE
Send and Close Module/Feature not sending last message

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2462]
Hey,
I have the Send and Close Module, and when I create a message and send it using the "Send and Close" button in the drop down, it doesn't send the message. It closes the ticket but doesn't email the message. But it doesn't so any attempts either. so there are no fails in the log

![Screenshot_20221213_021321](https://user-images.githubusercontent.com/99109793/207424865-2c598f32-aa73-4bd0-b9d8-de9c7a40fe95.png)

I have a workflow that sends an email when a ticket is closed. The workflow successfully sent the ticket is closed message. but the actual message I wrote was never sent.

Can someone help me with this issue?

System Info:
![Screenshot_20221213_021022](https://user-images.githubusercontent.com/99109793/207425031-e78ddadf-5cd8-464d-93d9-f06ffe18c4e2.png)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by SecureCPU** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

I followed these instructions, and everything is correct.

I have a workflow that sends an email when I close a ticket informing the client the ticket has been resolved and is now closed.
When I disable that workflow. Send and Close works perfectly. But when that workflow is active, it only sends the workflow message informing the client the ticket was closed, but not the last message I wrote (the actual message I wrote when I clicked Send and Close).

I wanted to test it on demo.freescout.net, but it didn't allow me to create the workflow.

And either Send and Close or workflow is sending the emails twice. otherwise, I never have this issue either.

**Comment by SecureCPU** [comment]
> And either Send and Close or workflow is sending the emails twice. otherwise, I never have this issue either.

I just tested it again. It's the workflow that's sending the email twice.

**Comment by freescout-helpdesk** [comment]
We've fixed it in the FreeScout `master` branch. The fix will be published in the next release.

The only thing the Workflow message will arrive to the customer before the actual message written by the support agent. There is no solution for this for now.
