### ISSUE TITLE
Emails for one customer are being assigned to another customer

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2463]
Today we received an email for one "customer". It is our support@XXXXX email address that we use ourselves. This is the FROM email address for notifications that our system sends to us.

<img width="1599" alt="Screenshot 2022-12-13 at 09 31 12" src="https://user-images.githubusercontent.com/382183/207427966-f4914f85-8dfc-43a2-ac07-259d53cf085e.png">

When we received this email we did NOT change the customer.

When clicking on the customer DEB here it shows up as the DEB customer.

<img width="1599" alt="Screenshot 2022-12-13 at 09 31 18" src="https://user-images.githubusercontent.com/382183/207428049-198c3014-183e-47d5-89b9-b95a52ddeb08.png">

---

Instead when receiving this email, we were expecting the SUPPORT@XXXXX customer to be applicable. And when clicking on that customer we were expecting to see that correct customer.

---

Our system is also showing other weird confusion between these customers as documented at https://github.com/freescout-helpdesk/freescout/issues/2455

**Comment by freescout-helpdesk** [comment]
We can't understand what exactly is happening here :)

**Comment by fulldecent** [comment]
Please clarify:

1. Do you understand what I'm saying in this issue?
2. Do you understand how my FreeScout installation is producing this outcome?

**Comment by freescout-helpdesk** [comment]
> Today we received an email for one "customer". It is our support@XXXXX email address that we use ourselves. This is the FROM email address for notifications that our system sends to us.

It's not clear what you are trying to say.

**Comment by fulldecent** [comment]
Here is the story, reworded:

1. We have a FreeScout installation
   1. The email address for this installation is support@OUR_DOMAIN_NAME
3. One of our systems sent an email to support@OUR_DOMAIN_NAME
   1. The from address of this email is also support@OUR_DOMAIN_NAME
1. FreeScout imported this message (shown in screenshot 1)
   1. This conversation is shown with a customer email address support@OUR_DOMAIN_NAME, that's good ✅ 
   2. This conversation is shown with a customer name of Deb, that's bad ❌ 
   3. When you click on the customer name it pulls up the Deb customer, that's bad ❌ 
   4. FYI, the Deb customer's email address is debbiem@OUR_DOMAIN_NAME, not support@OUR_DOMAIN_NAME (shown in screenshot 2, after clicking CLICK HERE in screenshot 1)

**Comment by freescout-helpdesk** [comment]
Can you share headers of the first email (from Original Message window).

**Comment by fulldecent** [comment]
Here is one example of the email that came in for support@ and was ingested as debbiem@.

This one doesn't have FROM == TO.

Also, FYI, at the time, this sender was on the SPAM filter blacklist.

I just removed our domain name to be XXXXX. Everything else is the same.

---


```
Delivered-To: support@XXXXX
Received: by 2002:a05:7010:3e1f:b0:306:c952:2005 with SMTP id
 w31csp5372132mdp; Wed, 2 Nov 2022 10:50:44 -0700 (PDT)
X-Google-Smtp-Source: AMsMyM5H2WhVhVMolpKqQLcMOM6ne3Kk1H/orGOGuuDHWvML3k6+Nc3nFfJnB9TbnZA54YxPkCqq
X-Received: by 2002:a17:907:8a18:b0:7ad:a942:f0e2 with SMTP id
 sc24-20020a1709078a1800b007ada942f0e2mr25160455ejc.119.1667411443837; Wed, 02
 Nov 2022 10:50:43 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1667411443; cv=none; d=google.com;
 s=arc-20160816;
 b=YlpwGbseS0vLTRTeG3JHi6FTLRueWE0bt1fEiFSdyTbGFBCuGSRetl3pngJQ8uK46g
 vlWyBk+5by6GLD1Uoq/tSVSJ+HG1qIdUxOTtI56k+svLZI8cXuoJw8QibOicAQWIrpzM
 274NFcHHd1WER2Ky7+G1CI2QT/UVZamgmkxisK6jpbd1uFeNUIbUONUtHsXIdPG7WqvO
 vXLtIBOwRPDyXmyu7wHCEWlRJkMwOFE/UtOJqf7hn7JJ8g6nYS0nMuEtsjS0B+g3x9Sb
 C7sS7AKSloZgYJJ3319rcymNHWZtWt86KGKHXheCp+3ggQWY5agmU0UtMBDWkkDXyQjM sl0A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com;
 s=arc-20160816;
 h=mime-version:message-id:subject:to:from:date:dkim-signature;
 bh=CjJuEbGtT+DqNt/mFVIyU5c/mowimAG2/Z/9fk/++gc=;
 b=cVdYQpC021vVf88fM60LVGjK6huk3bsawhR5xRah2iT/WpEq8B0AyUOyzA8HLxFtDt
 +K/bh6UaKi4O1skEM3VVug3Eksi7smhWmnXOcUuNM9v1mxm1DE221Hl2o/th3B+3KmK1
 npT3MhhJYjTD1L25q30w4smU8rZ+6tkdcPbh5PIgillQ6pfjvPuNVCNsdwiWBg5zerxr
 BAVUqVqjpy8QmGh1KRUifY7KorE8tfqvpz19kahFJoSUsvhn3EGMmWcl6/SULL6mNEEx
 jaVUI8Kk6FlI8j2PuXU9FTYeFi/w06SoCJpyyGGWEyRx4WuB2ZFgcisBP6ADuZBvb4sR b0Tw==
ARC-Authentication-Results: i=1; mx.google.com; dkim=pass
 header.i=@voipinterface.net header.s=default header.b=SPxQ5DKX; spf=pass
 (google.com: domain of noreply@voipinterface.net designates 208.100.31.27 as
 permitted sender) smtp.mailfrom=noreply@voipinterface.net
Return-Path: <noreply@voipinterface.net>
Received: from mail-sf1.voip.ms (mail-sf1.voip.ms. [208.100.31.27]) by
 mx.google.com with ESMTPS id
 dr8-20020a170907720800b00797e151e571si19082794ejc.36.2022.11.02.10.50.43 for
 <support@XXXXX> (version=TLS1_3
 cipher=TLS_AES_256_GCM_SHA384 bits=256/256); Wed, 02 Nov 2022 10:50:43 -0700
 (PDT)
Received-SPF: pass (google.com: domain of noreply@voipinterface.net designates
 208.100.31.27 as permitted sender) client-ip=208.100.31.27;
Authentication-Results: mx.google.com; dkim=pass header.i=@voipinterface.net
 header.s=default header.b=SPxQ5DKX; spf=pass (google.com: domain of
 noreply@voipinterface.net designates 208.100.31.27 as permitted sender)
 smtp.mailfrom=noreply@voipinterface.net
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voipinterface.net;
 s=default; t=1667411442; bh=XoK6UJMO0BWcmVx/qM5WKT5QzKZQ+Hvv8P+Yh9Kaw2w=;
 h=Date:From:To:Subject;
 b=SPxQ5DKXIOMVkPJISvSxMz20M7X69FQ7ez++Wrpol0xGsESlSw86jK+TnP1r9fQJ7
 TT45eXL9SV+uDrrOiGAURXfI79kyooYWSxvtKEcFwMlc7/iPhBb6IWrc1ez/D7Z3Ni
 WqJijEAA0M77C+AV6siRnNRaFq+KHBORlHmF5k+g=
Date: Wed, 02 Nov 2022 13:50:29 -0400
From: "Voicemail System" <noreply@voipinterface.net>
To: "PMT On Phone Right Now" <support@XXXXX>
Subject: =?ISO-8859-1?Q?New__voicemail_in_mailbox_100_from_=22JAN=2F_WIRE?=
 =?ISO-8859-1?Q?LESS_CALLER=22_=3C7159720147=3E?=
Message-ID: <Asterisk-1-1399367703-100-3380@voicemail-sf1.voip.ms>
X-Asterisk-CallerID: 7159720147
X-Asterisk-CallerIDName: JAN/ WIRELESS CALLER
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----voicemail_110033801286857734"
```

**Comment by rsw1981** [comment]
I'm having the same problem here.

Freescout is merging the email with the wrong clients. I really don't know how to troubleshoot this.

Can someone help me please?

thanks

skype:rwaldmann

**Comment by freescout-helpdesk** [comment]
> I'm having the same problem here.
> 
> Freescout is merging the email with the wrong clients. I really don't know how to troubleshoot this.
> 
> Can someone help me please?
> 
> thanks
> 
> skype:rwaldmann

Just update FreeScout to the latest version. But replies to previously sent emails still may be routed to the incorrect conversations.

**Comment by rsw1981** [comment]
I updated to the latest version yesterday to 1.8.43 and I will update today to 1.8.44

On 1.8.43 I still noticed some wrong merged emails sporadically

If it's not too much to ask, can you explain or tell me where to find how this process works? What is considered to merge the emails?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/5e38dc9abdb07630314343d7bde1273f1cf4d93a

**Comment by freescout-helpdesk** [comment]
The initial problem described in this issue was a bit different. We have not seen such issue on our FreeScout instances. So the only way to figure out what happened here https://github.com/freescout-helpdesk/freescout/issues/2463#issue-1495024915 is to make sure this issue can be steadily reproduced and debug it on your server.
