### ISSUE TITLE
Clone Conversation does not clone attachments

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#2465]
Thank you for the feature "Clone Conversation". This is really helpful.

However, one things is not working as expected. If I clone a conversation the attachments are not cloned and not available in the new conversation. I would say this is a bug. What do you think?

**Comment by freescout-helpdesk** [comment]
Yes. Will be fixed.

**Comment by obstschale** [comment]
Awesome. Thx 💪
