### ISSUE TITLE
Customer Field Not Creating

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2466]
I am trying to create a new Customer field.
But every time I try, it gives me the following error

`Error occured. Please check your internet connection and try again.`

![Screenshot_20221214_123950](https://user-images.githubusercontent.com/99109793/207668175-6aa75a21-bc3a-43a9-b4aa-ecae32008e80.png)

**Comment by freescout-helpdesk** [comment]
Make sure you are using the latest versions of modules.
Check Manage > Logs > App Logs.

**Comment by SecureCPU** [comment]
and everything is updated to the latest version

**Comment by freescout-helpdesk** [comment]
Fixed in CRM Module v1.0.19
