### ISSUE TITLE
Cant open ticket after customers merge

### ISSUE THREAD

**Issue by darkp-team** [freescout-helpdesk/freescout#2467]
Hello, I merged 2 customers in CRM by adding  email from one to second, then I deleted empty customer. Now it is not possible to open ticket created for this merged customer. Ticket in my inbox, but clicking on it system just gives me error "Whoops, looks like something went wrong". Is there any way how to open this ticket?

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.

**Comment by darkp-team** [comment]
Hello, sorry, how it could help me? https://prnt.sc/OonxcEcp4-Ra

**Comment by freescout-helpdesk** [comment]
The error message from logs is not related to this issue. Are there any other errors in logs?
Are you using the latest version of FreeScout?

**Comment by darkp-team** [comment]
Now, after updating to last version 1.8.40 it is not possible to open any folder, like Assigned, Sent... all the time error "Whoops, looks like something went wrong", there is LOG https://prnt.sc/t1mYHYHk4BPc

**Comment by darkp-team** [comment]
There is last version 1.8.40, there is error https://prnt.sc/SAo8VDNPLYlC
