### ISSUE TITLE
Can't Upload iPhone Photos with End-User Portal

### ISSUE THREAD

**Issue by grapeslush** [freescout-helpdesk/freescout#2468]
I'm able to upload most all photo types via an iPhone with the exception of a photo taken with an iPhone. I see this error.

iPhone utilizes HEIC formatting. 

<img width="422" alt="Xnapper-2022-12-14-21 11 55" src="https://user-images.githubusercontent.com/113303741/207767547-e9367de1-d899-4e7d-a0b0-4feaf0ad5e0f.png">

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.

**Comment by grapeslush** [comment]
2022/12/15 19:19:26 [error] 3587745#3587745: *182627 client intended to send too large body: 2621369 bytes, client: ***.***.***.***, server: *********.com, request: "POST /help/2137427074/upload HTTP/1.1", host: "******.com", referrer: "https://***********.com/help/2137427074"

So looks like the file is too large. Is this configurable? I haven't seen it in the web portal itself.

**Comment by freescout-helpdesk** [comment]
Yes. Via PHP or Nginx config.
