### ISSUE TITLE
Speed up the sending of queued emails

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#2469]
There is a problem with sending emails on the server, and there is a backlog of outgoing emails that is very slow to resolve once the problem is fixed.

How can I speed up the sending?

![2022-12-15_12-38](https://user-images.githubusercontent.com/77854832/207825690-6f8bd227-7084-4177-8473-533d37ca4b6e.png)

**Comment by freescout-helpdesk** [comment]
Are you using the latest FreeScout version?
Check "Manage > Logs > App Logs".

**Comment by il2020** [comment]
> Are you using the latest FreeScout version? Check "Manage > Logs > App Logs".

Yes, 1.8.40.
Everything works, I just want to somehow forcibly start sending, not to wait.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by il2020** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

There is no answer here.
Letters are sent, but slowly, as there is some delay between attempts. There are no errors. I cleaned the cache. Emails are sent, but slowly.

Is there any way to force all e-mails in the queue to be sent?

**Comment by ilyakonovalenko** [comment]
Maybe the issue is with your mail server? Are you sure your mail server is not responding slowly?

**Comment by freescout-helpdesk** [comment]
FreeScout is making incremental attempts to send emails: first after few hours, then days, etc. So all you can do is to wait and make sure mail server is functioning.
