### ISSUE TITLE
Compatibility with PHP 7.1, 7.2 and 7.3

### ISSUE THREAD

**Issue by mzch** [freescout-helpdesk/freescout#247]
Hi,

I tried to install freescout with PHP 7.3, 7.2, 7.1, but it said like "Woops,... something wrong".
Isn't this compatible with PHP7.1-7.3?

**Comment by jeverington** [comment]
I can confirm this works fine on 7.2, I would imagine its an issue with your environment.

**Comment by quangbahoa** [comment]
`Woops,... something wrong``
You're missing PHP Library

**Comment by freescout-helpdesk** [comment]
Please check installed PHP libraries.
