### ISSUE TITLE
Jira module can't create Jira issue.

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#2470]
With the Jira module, I can search and link existing Jira tickets, but can't create new ones.  When I click "create issue" it gives an error:

{"duedate":"Due date is required.","labels":"Labels is required."}

The form doesn't include these fields.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/jira/
_"Creating Jira issues with Types requiring custom fields in Jira is not possible for now."_

**Comment by justajeffy** [comment]
What's so custom about a due date?  Isn't that a pretty common thing on Jira issues?

**Comment by justajeffy** [comment]
The major use I had for the Jira module was to link our Freescout tickets (General helpdesk) to the Jira project used by our software dev team.  Different groups, using different systems.  Due dates and Labels are standard out-of-the-box default fields on Jira Software projects, as far as I know.  Any chance this might get improved in the very near future?

**Comment by freescout-helpdesk** [comment]
So you have not added those fields manually?

**Comment by justajeffy** [comment]
No.  They were included in the project automtically when it was created.  It is a Jira Software project.  Perhaps a Jira Servicedesk project doesn't include these fields?

**Comment by freescout-helpdesk** [comment]
OK. We'll see what can be done.

**Comment by freescout-helpdesk** [comment]
We've double checked - we are able to create tickets in Jira from FreeScout even with "Due Date" and "Labels" fields available in Jira issues:

![2022-12-16_10-15-31](https://user-images.githubusercontent.com/40499291/208043948-7e5453ab-41cd-4fb6-b6e3-adf13425bdde.png)

Have you configured them somehow to be required in your Jira?

**Comment by justajeffy** [comment]
I created a test Jira Software project using the provided scrum template
and both due date and labels fields are set to required by default.

**Comment by freescout-helpdesk** [comment]
Make them optional. Module will not support extra fields.
