### ISSUE TITLE
Custom translations are overwritten on update

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2471]
I noticed translations are overwritten every time you update FreeScout or modules. It is required to publish them again and again after every update to back to custom translations.

Is it possible to prevent such behaviour?
Maybe move custom translations files into some directory and make them a priority... Or perform custom translations publishing on every update.

**Comment by freescout-helpdesk** [comment]
Only by sending them to FreeScout Team.

**Comment by ilyakonovalenko** [comment]
Well, any custom translations remain in the FreeScout instance after update, you just need to re-publish them locally again. Why not run re-publishing on update?

**Comment by freescout-helpdesk** [comment]
You can run it via a custom module.
