### ISSUE TITLE
Fatal error in code regarding the CRM fields in conversation list.

### ISSUE THREAD

**Issue by kovoks** [freescout-helpdesk/freescout#2472]
ErrorException(code: 0): json_decode() expects parameter 1 to be string, array given (View: [...]/resources/views/conversations/conversations_table.blade.php) at [...]/Modules/Crm/Providers/CrmServiceProvider.php:318

`$conv_fields = json_decode(config('crm.conv_fields'), true) ?? [];`

Workaround for anyone else running into this, change this line to 

`$conv_fields = [];`

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version of CRM Module.

**Comment by kovoks** [comment]
Thanks. Worky.
