### ISSUE TITLE
From address

### ISSUE THREAD

**Issue by marclight** [freescout-helpdesk/freescout#2475]
When in a mailbox, I can see the from name but is there a way to show the from address?

Thanks.

**Comment by freescout-helpdesk** [comment]
Could you please send a screenshot illustrating what you are talking about.

**Comment by avenjamin** [comment]
I believe @marclight is referring to the list of conversations.
The first column is **Customer** and only shows the full name.


./resources/views/conversations/conversations_table.blade.php
line: 129

`@if ($conversation->customer_id && $conversation->customer){{ $conversation->customer->getFullName(true)}}@endif&nbsp;@if ($conversation->threads_count > 1)<span class="conv-counter">{{ $conversation->threads_count }}</span>@endif`

Something similar to this might work:

`@if ($conversation->customer_id && $conversation->customer){{ $conversation->customer->getFullName(true)}} <span class="conv-counter">{{ $conversation->customer->getMainEmail()}}</span>@endif&nbsp;@if ($conversation->threads_count > 1)<span class="conv-counter">{{ $conversation->threads_count }}</span>@endif`

It has the wrong CSS class, and the email addresses are wrapping so may need to be smaller or the column made bigger:

![Screen Shot 2022-12-20 at 1 28 16 pm](https://user-images.githubusercontent.com/869534/208567942-47d5fd71-0194-4ba2-b8c2-5914d0c0f3ac.png)

**Comment by marclight** [comment]
That's for the list view, for me it's not an issue to not see the from address but like @avenjamin said, a user preference would be nice.  My issue is more in the conversation view (when you click an item).  From name is there but not the from address.  It's only available when I click on the name.

Thanks.

**Comment by freescout-helpdesk** [comment]
> That's for the list view, for me it's not an issue to not see the from address but like @avenjamin said, a user preference would be nice. My issue is more in the conversation view (when you click an item). From name is there but not the from address. It's only available when I click on the name.
> 
> Thanks.

Please send a screenshot.

**Comment by marclight** [comment]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/10010263/208671626-45a66068-12ff-4c1c-b9c7-1c4d47654503.png)

I have to click the name to see the email address.

**Comment by freescout-helpdesk** [comment]
Customer's email should be visible in the right sidebar.

**Comment by marclight** [comment]
Ah, I was too zoomed in.  If I zoom out the right sidebar appears with the customer's email.  Maybe make it responsive and show up before the "To:" field when the sidebar is hidden?

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans for now.
