### ISSUE TITLE
Mail queue only sends once a day

### ISSUE THREAD

**Issue by petervansark** [freescout-helpdesk/freescout#2476]
Messages come in every minute. As per cron settings. But messages go out only once a day around 1AM. Until then, messages pile up in background tasks.
Manually running cron makes no difference.
Only purging cache manually seems to work.

Is there a way to fix this?

Kind regards,
Petrer

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by petervansark** [comment]
Thanks, tried those suggestions. 👍 But still had to purche cache every hour to keep background tasks running.

As it turns out, it was a memory issue.
After upgrading our server everything was working again. Background tasks haven't crached since.  🥇
