### ISSUE TITLE
freescout:fetch-emails shows 2 commands running at same time

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2478]
Hey,
After I upgraded to v1.8.41 I stated to receive the following error:
![Screenshot_20221220_020743](https://user-images.githubusercontent.com/99109793/208604857-09f17b72-0cc9-4185-8285-2479a62ef196.png)

I upgraded to v1.8.42 but the error keeps showing up. and the Fetch keeps having issues when it doesn't work.

Here are the Fetch Logs:

![Screenshot_20221220_021035](https://user-images.githubusercontent.com/99109793/208605157-6bf92d77-cf6f-41e2-b0d6-870c51dac4ee.png)
![Screenshot_20221220_021132](https://user-images.githubusercontent.com/99109793/208605287-820a3322-907d-42ad-91ab-7d04e5430c99.png)

If anyone can please help me out. that would be great.
Thank you!!

**Comment by freescout-helpdesk** [comment]
Have you tried to follow instruction given in red?

**Comment by SecureCPU** [comment]
Yup.
I actually just switched the connection from TLS to SSL
and restarted the server. the error went away.

**Comment by SecureCPU** [comment]
I guess I'll keep an eye on it now.

Just a quick question, what are the recommended hardware specs for running Freeescout on Ubuntu Server?

**Comment by freescout-helpdesk** [comment]
There is no such recommendations.
