### ISSUE TITLE
Styling is not showing but the CSS is loading

### ISSUE THREAD

**Issue by adriaanvanrossum** [freescout-helpdesk/freescout#248]
![firefox 2019-02-23 at 12 36 52 2x](https://user-images.githubusercontent.com/1079135/53282253-c7843400-3767-11e9-948b-12eca8bf6929.png)

I did run `php artisan freescout:clear-cache`, `php artisan storage:link`, and `ln -s storage/app/public public/storage`.

It looks like it is only returning library css: https://gist.github.com/adriaanvanrossum/08fce72b481591b395558c517a265f3b

Also fixed the permissions: `cd /var/www/html && sudo chgrp -R www-data storage bootstrap/cache public/css/builds public/js/builds && sudo chmod -R ug+rwx storage bootstrap/cache public/css/builds public/js/builds && sudo chgrp www-data /var/www/html && sudo chmod ug+rwx /var/www/html && sudo nginx -t && sudo service nginx restart && sudo service php7.0-fpm restart`

The logs (`laravel-2019-02-23.log`, `web-server.log`) don't show anything around this time.

**Comment by freescout-helpdesk** [comment]
Have you found the solution?

**Comment by adriaanvanrossum** [comment]
Nope, I gave up and use HelpScout now.

**Comment by freescout-helpdesk** [comment]
Ok, so closing the issue.
