### ISSUE TITLE
Slack module showing error

### ISSUE THREAD

**Issue by arungowda325** [freescout-helpdesk/freescout#2481]
Hi Team,

Slack module is showing below error. Please help

Whoops, looks like something went wrong — check logs in /storage/logs

![image](https://user-images.githubusercontent.com/38986419/208683722-6ac6a0b6-9a6a-4fcd-8923-24457cfe2ef1.png)

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules or customizations in your FreeScout?

**Comment by arungowda325** [comment]
no. We purchased 3 modules. 1 is working and 2 are not working

**Comment by freescout-helpdesk** [comment]
We can't reproduce your issues. Apparently something is wrong with your FreeScout installation.
Try to re-install or find someone who can investigate it on your server: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
