### ISSUE TITLE
Error fetching and sending emails

### ISSUE THREAD

**Issue by marianmurin** [freescout-helpdesk/freescout#2482]
I have a problem after installing grive app to fetch and receive emails in Freescout. 
I am using Gsuite email for helpdesk.

**Fetch errors:**
Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/novalidate-cert/ssl}. Retrying PLAIN authentication after [AUTHENTICATIONFAILED] Invalid credentials (Failure); Retrying PLAIN authentication after [AUTHENTICATIONFAILED] Invalid credentials (Failure); Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Invalid credentials (Failure); File: /www/wwwroot/helpdesk.improve.sk/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)

**Send errors:**
Failed to authenticate on SMTP server with username "support@improve.sk" using 3 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials dk11-20020a0564021d8b00b0046c91fa5a4asm6126442edb.70 - gsmtp " in /www/wwwroot/helpdesk.improve.sk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457 Stack trace: #0 /www/wwwroot/helpdesk.improve.sk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode() #1 /www/wwwroot/helpdesk.improve.sk/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand() #2 ....

<img width="702" alt="Snímka obrazovky 2022-12-20 o 21 10 29" src="https://user-images.githubusercontent.com/14167315/208757587-b97ea2f2-24dc-4bbe-b31e-67236bc762b6.png">

<img width="726" alt="Snímka obrazovky 2022-12-20 o 21 11 00" src="https://user-images.githubusercontent.com/14167315/208757598-b34a051f-7531-410d-aea4-dc421c06fd44.png">

**Comment by freescout-helpdesk** [comment]
Check these:
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues
https://github.com/freescout-helpdesk/freescout/wiki/Connect-G-Suite-to-FreeScout

**Comment by marianmurin** [comment]
I have already checked that and tried almost everything, but with no luck.
I have even talk 2 hours with Google with the same result. They talk about some certificate which is needed to communicate with Gmail server, but I did n ot find anything about this server stuff on the forum and our knowledgebase.

Could tbis be related with OpenSSL ON MY VPs?

**Comment by freescout-helpdesk** [comment]
Fetching and sending errors are indicating that your credentials were not accepted. It means your server is able to connect and OpenSSL is not a problem. Are you using App Passwords?

**Comment by marianmurin** [comment]
Yes, I am using App Password 2FA is turned ON.
I am attaching screebshot from connection setting for fetching and sending.

<img width="650" alt="Snímka obrazovky 2022-12-21 o 13 58 33" src="https://user-images.githubusercontent.com/14167315/208911171-72718c6e-e2bc-4e3c-a841-c10586bf5c2b.png">
<img width="636" alt="Snímka obrazovky 2022-12-21 o 13 58 45" src="https://user-images.githubusercontent.com/14167315/208911182-2af68077-edf0-485f-852e-02ba63af40e6.png">

**Comment by minghuiyu** [comment]
Sometimes, for whatever reason, fetching emails failed, and error below

Error fetching email | Error: connection setup failed; File: .. ... /vendor/webklex/php-imap/src/Client.php (391)

I also sometimes have this issue.

Whenever this error happens, system shows 2 cron jobs are running and one process shall be killed.

Whenever 2 cron jobs are running, server CPU utilization goes to 100%.

Questions:

-     How to prevent the error from happening? (It happens a few times a week. I have multiple mailboxes and frequency is 1 min each mailbox, so I would say it is an infrequent error)
-     Where to get the specific error logs? e.g.: which email fetching produced the error, and why? (I checked Manage->log->fetch email, but no useful information)
-     When it happens, how to kill the process automatically?

Thanks!

**Comment by freescout-helpdesk** [comment]
Try to change App Password.
Are you using GSuite or you've somehow set a custom domain (support@improve.sk) for a regular Gmail?

**Comment by marianmurin** [comment]
I have already changed App password, but It does not help. 2FA is trun ON and I am using paid GSuite.

**Comment by freescout-helpdesk** [comment]
We don't have any other ideas.

**Comment by marianmurin** [comment]
Me neither
