### ISSUE TITLE
[FR] Clicking on a tags in conversation list view should show all conversations with matching tag.

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2483]
FreeScout version: 1.8.42
Tags module version: 1.0.21

In the main mailbox conversation list view tags appear next to the conversation subject.
When you click on a tag it should take you to `/search?f[tag]=mytag` instead of opening the conversation.

Also a minor related bug I just noticed.
Clicking on tags in a conversation or when using the search page generates a url like this:
https://freescout.com/search?f%5Btag%5D=development

Compare that to when you go to Manage > Tags > mytag > View conversations:
https://freescout.com/search?f[tag]=development

i.e. the url is being escaped differently.

Cheers
Ben

**Comment by freescout-helpdesk** [comment]
Implemented in Tags Module v1.0.22
