### ISSUE TITLE
Request to make the Postgresql sslmode user adjustable setting.

### ISSUE THREAD

**Issue by Aegis8** [freescout-helpdesk/freescout#2485]
Hello,

Currently the postgresql sslmode is hardcoded to be sslmode=prefer, which does not allow for secure database connections.

https://github.com/freescout-helpdesk/freescout/blob/dist/config/database.php

` 'pgsql' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_HOST', '127.0.0.1'),
            'port'     => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'sslmode'  => 'prefer',
        ],`

A change to: `'sslmode'  => env('DB_SSLMODE', 'prefer'),` would allow the user to decide what to use. This is enough to allow the require option and for our use case.

It will be appreciated, if this can be added to freescout.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch. Use `DB_PGSQL_SSLMODE` .env variable.

**Comment by Aegis8** [comment]
Thank you, for adding this!
