### ISSUE TITLE
Add X-Auto-Response-Suppress header to notification emails

### ISSUE THREAD

**Issue by luryus** [freescout-helpdesk/freescout#2488]
Like the issue reported previously in #513, we're having an issue where our Exchange server responds to notification emails with out-of-office autoreplys. These autoreply messages get added in the conversation and sent to the customers.

The emails sent by Exchange do not have any headers that could be used to determine if they are autoreplys, so the autoresponder detection does not work here.

Exchange supports the header `X-Auto-Response-Suppress` in incoming messages. If that is set to `All` or `OOF`, Exchange will not send an autoreply to the message.

FreeScout could add this header to the notification emails to avoid getting autoreplys from FreeScout users. I think this would solve our issue.

**Comment by freescout-helpdesk** [comment]
The header has been added in the `master` branch. You can check it.
