### ISSUE TITLE
Sometimes, for whatever reason, fetching emails failed

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#2489]
Sometimes, for whatever reason, fetching emails failed, and error below

Error fetching email | Error: connection setup failed; File: .. ... /vendor/webklex/php-imap/src/Client.php (391)

I also sometimes have this issue.

Whenever this error happens, system shows 2 cron jobs are running and one process shall be killed.

Whenever 2 cron jobs are running, server CPU utilization goes to 100%.

Questions:

1. How to prevent the error from happening? (It happens a few times a week. I have multiple mailboxes and frequency is 1 min each mailbox, so I would say it is an infrequent error)
2. Where to get the specific error logs? e.g.: which email fetching produced the error, and why? (I checked Manage->log->fetch email, but no useful information)
3. When it happens, how to kill the process automatically?

Thanks!

_Originally posted by @minghuiyu in https://github.com/freescout-helpdesk/freescout/issues/2482#issuecomment-1363776438_

**Comment by freescout-helpdesk** [comment]
You need to find out why this command does not work for you: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L143

**Comment by minghuiyu** [comment]
> You need to find out why this command does not work for you: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L143

Thanks for the hints. Is this line the first place freescout running shell_exec? 

I had the issue again, here is the details of this process that the system failed to kill:
xxx@xxx:/etc/php/8.1/fpm# ps -F -p 1802665
```
UID          PID    PPID  C    SZ   RSS PSR STIME TTY          TIME CMD
www-data 1802665 1802664 98 27355 48436   1 Dec24 ?        1-01:25:55 /usr/bin/php8.1 artisan freescout:fetch-emails
```

```
xxx@xxxx:/etc/php/8.1/fpm# ps -u www-data
    PID TTY          TIME CMD
   2049 ?        00:00:40 nginx
   2050 ?        00:00:01 nginx
  85534 ?        00:07:17 php-fpm8.1
 255151 ?        00:00:00 sh
 255152 ?        00:09:59 php
 255184 ?        00:00:00 sh
 255185 ?        17-13:23:17 php8.1
 836386 ?        00:01:34 php-fpm8.1
 838294 ?        00:01:28 php-fpm8.1
1802631 ?        00:00:00 sh
1802632 ?        00:00:33 php
1802664 ?        00:00:00 sh
1802665 ?        1-01:22:06 php8.1
1942074 ?        00:00:00 sh
1942075 ?        00:00:01 php
1942184 ?        00:00:00 sh
1942185 ?        00:00:01 php8.1
```

**Comment by freescout-helpdesk** [comment]
Yes. Apparently by some reason PHP can't kill unneeded processed via shell_exec().

**Comment by minghuiyu** [comment]
> Yes. Apparently by some reason PHP can't kill unneeded processed via shell_exec() on your installation.

Thanks

```
xxx@xxx:/var/www/html/app/Console# ls -l
total 12
drwxr-xr-x 2 www-data www-data 4096 Dec 25 15:36 Commands
-rw-r--r-- 1 www-data www-data 6779 Dec 21 03:15 Kernel.php
```
Shall kernel.php permission be r-xr--r-- (544)? Thanks.

**Comment by freescout-helpdesk** [comment]
This line need to be debugged when **executed by cron**: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L143

**Comment by minghuiyu** [comment]
Got this issue again:

2 commands are running at the same time. Please stop extra commands by executing the following console command: kill 158852

# ps aux | grep fetch
www-data    8011  0.0  0.0   2888   976 ?        S    Jan20   0:00 sh -c '/usr/bin/php8.1' 'artisan' freescout:fetch-emails > '/var/www/html/storage/logs/fetch-emails.log' 2>&1
www-data    8012 99.7  1.2 111340 48784 ?        R    Jan20 1811:42 /usr/bin/php8.1 artisan freescout:fetch-emails
www-data  158851  0.0  0.0   2888  1012 ?        S    06:41   0:00 sh -c '/usr/bin/php8.1' 'artisan' freescout:fetch-emails > '/var/www/html/storage/logs/fetch-emails.log' 2>&1
www-data  **158852** 97.8  1.2 111340 48716 ?        R    06:41 129:55 /usr/bin/php8.1 artisan freescout:fetch-emails

**Comment by freescout-helpdesk** [comment]
> If I set this to run every 30 minutes, will that have any impact to the system?
> 
> php artisan freescout clear-cache

The system will work, just experience some extra load every 30 minutes. Try to update to the latest release and remove `sh -c '/usr/bin/php8.1' 'artisan' freescout:fetch-emails` from cron, leave just `...artisan schedule:run` command. The issue with background jobs should be fixed now.

**Comment by minghuiyu** [comment]
Shall cron job keep running, or it sleeps when not running?

I have two cron jobs running, one is eating all CPU resources

![image](https://user-images.githubusercontent.com/8637057/214742896-dbeea86a-696b-4e9d-8d98-e17b638f88fe.png)

**Comment by freescout-helpdesk** [comment]
Your process list looks fine. Just maybe your `freescout:fetch-emails` is experiencing some difficulties or hanging due to mail server problems. 

> Go to "Manage » System » Tools", click "Fetch Emails" and check the output.
> https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues

**Comment by minghuiyu** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php#L82 threw an exception

connection failed; File: /var/www/html/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (82) 

Not sure why. The issue seems not having a pattern. System status doesn't show two processes running.

It's an Office 365 email. Checked Azure AD log, didn't see error, though.

It seems I will have to kill such process running longer than 10 minutes automatically.

**Comment by freescout-helpdesk** [comment]
So what happens when you click "Fetch Emails" in "Manage » System » Tools"? You get the result immediately or it keep hanging?

**Comment by minghuiyu** [comment]
I got results immediately.

No high CPU incident in past 24 hours. Not sure what caused that. 

Will changing https://github.com/freescout-helpdesk/freescout/blob/dist/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php#L82 to $e->getMessage() help with getting exception details?

Thanks!

```
[2023-01-27 11:40:45] Fetching UNREAD emails for the last 3 days.
[2023-01-27 11:40:45] Mailbox: ... 
[2023-01-27 11:40:46] Folder: INBOX
[2023-01-27 11:40:46] Fetched: 0
[2023-01-27 11:40:46] Folder: Junk Email
[2023-01-27 11:40:46] Fetched: 0
[2023-01-27 11:40:47] Fetching finished
```

**Comment by minghuiyu** [comment]
Ok, mail server's IMAP authentication issue does cause a fetching issue (why it fails is a mystery), but the system doesn't kill the long running process. I suggest the team taking a look over why the process doesn't get killed. Thanks!

![image](https://user-images.githubusercontent.com/8637057/215253181-845d152d-f7e7-49be-9ef0-7944701e0609.png)
  

![image](https://user-images.githubusercontent.com/8637057/215253055-ab091a57-500c-4ded-a7cf-8bb5ef6a16c0.png)

**Comment by minghuiyu** [comment]
Another fetching email issue on 3AM
![image](https://user-images.githubusercontent.com/8637057/215278787-976e0ecc-d295-41cd-8d56-e05b61066619.png)

Resolved by itself around 4:02AM.
![image](https://user-images.githubusercontent.com/8637057/215278973-59d3a9a1-e660-49ab-958f-1f8849e056a0.png)

A fetching email process has been running since 3:15AM
![image](https://user-images.githubusercontent.com/8637057/215278898-6173c011-78da-4162-9fd1-6296850ba36c.png)

pstree shows this:
```
           ├─cron(628)─┬─cron(397164)───sh(397165)───php(397166)───sh(397220)───php8.1(397221)
           │                    └─cron(424200)───sh(424201)───php(424202)───sh(424323)───php8.1(424324)
```

**Comment by freescout-helpdesk** [comment]
When you execute `php artisan freescout:fetch-emails` in the console the command says "Error: connection setup failed" finishes or keeps waiting?

**Comment by minghuiyu** [comment]
After `running php artisan freescout:fetch-emails`, I got system prompt, so it finished. The system didn't fetch email.

I changed fetching from 1 min to 5 mins, and it has been good so far.

Pls add 2 mins, 3 mins to the drop-down menu. Thanks. Office 365 seems not very friendly to email fetching every minute.

**Comment by minghuiyu** [comment]
@freescout-helpdesk  Can you make changes below? Thanks!
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L42 
Add
```
const FETCH_SCHEDULE_EVERY_TWO_MINUTES = 2;
const FETCH_SCHEDULE_EVERY_THREE_MINUTES = 3;
```
https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/settings/emails.blade.php#L117
then add this?

```
<option value="{{ \MailHelper::FETCH_SCHEDULE_EVERY_TWO_MINUTES }}" @if (old('settings.fetch_schedule', $settings['fetch_schedule']) == \MailHelper::FETCH_SCHEDULE_EVERY_TWO_MINUTES )selected="selected"@endif>{{ __('Every 2 minutes') }}</option>
<option value="{{ \MailHelper::FETCH_SCHEDULE_EVERY_THREE_MINUTES }}" @if (old('settings.fetch_schedule', $settings['fetch_schedule']) == \MailHelper::FETCH_SCHEDULE_EVERY_THREE_MINUTES )selected="selected"@endif>{{ __('Every 3 minutes') }}</option>

```
