### ISSUE TITLE
Spamhaus has IP used by freescout.net listed in CSS URIBL

### ISSUE THREAD

**Issue by jmcclelland** [freescout-helpdesk/freescout#2490]
I was having trouble finding any of the messages sent by my new Free Scout installation. Then, I discovered they were in my spam folder.

That's because:

1. https://freescout.net is listed in the footer
2. It resolves to a (digital ocean) IP: 104.248.19.129
3. That IP address is listed as having a poor reputation in the [spamhaus CSS URIBL](https://check.spamhaus.org/listed/?searchterm=104.248.19.129)

It might not have anything to do with freescout if you are on a shared server with digital ocean. Not sure if this is something you can request being de-listed from or whether you would need to report to digital ocean.

I managed to work around the issue by disabling the branding in emails, but it would be nice to give freescout a boost.

**Comment by freescout-helpdesk** [comment]
It's very unlikely that the link in the body may cause this. Algorithms of sending emails to Spam are a bit different. What email service provider are you using to send outgoing emails?

**Comment by jmcclelland** [comment]
It's definitely the freescout.net link:

![image](https://user-images.githubusercontent.com/4511942/209391486-e76aebaa-a301-470c-befe-29332530c4fb.png)

And you can confirm via the link I posted in the original message - you'll find that your web site IP address is listed in the blacklist: https://check.spamhaus.org/listed/?searchterm=104.248.19.129

**Comment by freescout-helpdesk** [comment]
Thanks. We'll check how to improve it. Meanwhile you can just disable "Spread the word" feature.

**Comment by freescout-helpdesk** [comment]
![2022-12-23_21-47-48](https://user-images.githubusercontent.com/40499291/209393710-d8964bad-de63-4fa0-9cf5-fe4fb1861eff.png)
