### ISSUE TITLE
WooCommerce integration fail - HTTP Status Code: 500 (Internal store error)

### ISSUE THREAD

**Issue by rbettoni** [freescout-helpdesk/freescout#2491]
Hello :-)

I installed "WooCommerce Integration" module, created an API on WooCommerce as indicated and it seems it is not working properly. This is the error that appears when I try to save the settings. It also appears in app log:

> error | production | 2022-12-28 02:42:43 | [WooCommerce] HTTP Status Code: 500 (Internal store error) \| Requested resource: https://oficinapalimpsestus.com.br/loja/wp-json/wc/v3/orders

Any help will be fully appreciated. 
Thank you
R.

**Comment by freescout-helpdesk** [comment]
The error message states that there was an error in your store - check your store's error log.

**Comment by rbettoni** [comment]
> The error message states that there was an error in your store - check your store's error log.

Thank you for your reply. I checked all the logs in WooCommerce and the only record that appears when I try to integrate is this:

> 2022-12-28T07:42:43+00:00 CRITICAL Uncaught Error: Call to a member function get_cart_contents_count() on null in /home2/ofici679/public_html/wp-content/themes/fox/inc/plugin.woocommerce.php:546
> Stack trace:
> #0 /home2/ofici679/public_html/wp-content/themes/fox/parts/header-classic.php(59): fox_woocommerce_header_cart()
> #1 /home2/ofici679/public_html/wp-includes/template.php(785): require('/home2/ofici679...')
> #2 /home2/ofici679/public_html/wp-includes/template.php(718): load_template('/home2/ofici679...', false, Array)
> #3 /home2/ofici679/public_html/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
> #4 /home2/ofici679/public_html/wp-content/themes/fox/parts/header.php(44): get_template_part('parts/header', 'classic')
> #5 /home2/ofici679/public_html/wp-includes/template.php(785): require('/home2/ofici679...')
> #6 /home2/ofici679/public_html/wp-includes/template.php(718): load_template('/home2/ofici679...', false, Array)
> #7 /home2/ofici679/public_html/wp-includes/general-template.php(204): locate_template(Array, true, em /home2/ofici679/public_html/wp-content/themes/fox/inc/plugin.woocommerce.php, na linha 546

I appreciate your help -- I'm new to all of this. I don't know if this is the right place to ask for this kind of help.

Thanks

**Comment by freescout-helpdesk** [comment]
The problem is in the WordPress theme you are using or some plugin. The only way to find out is to check it on your server.

**Comment by rbettoni** [comment]
Dear friends,
Thank you for trying to help.
I have contacted Woocommerce, we made a lot of tests, including an API call specific to extract the results from the same URL reported by the Module: https:// oficinapalimpsestus .com . br/loja/wp-json/wc/v3/orders

When performing the tests, no error occurred. They said this: if API call is returning data with no errors, and considering all the log files analyzed, the problem is not with your website. 

They asked me to contact you again. Can you please help me solve the problem or suggesting what to do? I can post here all the conversation with the log files etc.
Thank you
