### ISSUE TITLE
Dark mode will not stay dark

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2492]
Here is a video demonstrating the problem.

I am using the latest paid version of the dark mode module.

Please make it so that setting dark mode keeps it on dark mode and does not flash colors.

---

![out](https://user-images.githubusercontent.com/382183/209885510-84512077-20ad-436b-b6e3-49e9ba90aba4.gif)

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by freescout-helpdesk** [comment]
Also check errors in the browser console when switching to/from dark mode.

**Comment by freescout-helpdesk** [comment]
> Same issue. Zero errors on the console.

What OS and browser are you using?

**Comment by freescout-helpdesk** [comment]
Also try:
1) Enable Dark Mode.
2) Check if your browser has `dm_enabled` cookie set to `1`.

**Comment by kajack** [comment]
W11. Edge.

When Dark Mode is enabled dm_enabled cookie is set to 1. If you disable it gets set to 0. Then when you load another page it becames again 1.

**Comment by freescout-helpdesk** [comment]
> When Dark Mode is enabled dm_enabled cookie is set to 1. If you disable it gets set to 0. Then when you load another page it becames again 1.

So your issue is different from described here https://github.com/freescout-helpdesk/freescout/issues/2492#issue-1513242295 ? Dark mode always stays "On" for you? If so - see explanation about `prefers-color-scheme` at https://freescout.net/module/dark-mode/

**Comment by maukunze** [comment]
Also have the same problem on Ubuntu 22.04 with firefox browser. In the Chrome Browser the error does not occur.

**Comment by kajack** [comment]
@freescout-helpdesk I understand. Still not the behavior I had expected or wanted.

**Comment by freescout-helpdesk** [comment]
> @freescout-helpdesk I understand. Still not the behavior I had expected or wanted.

Create a separate issue. No need to create confusion in existing issues.

**Comment by kajack** [comment]
Well, my point was that in EDGE Light mode it works well either Dark or Light but when EDGE is in Dark Mode it's always being forced to Dark. Maybe @fulldecent navigator is also set to Dark?

**Comment by dealend** [comment]
There really should be a permanent toggle for on an off. The current implementation is not great, especially for most non-tech-savvy users. If they have their system set to dark mode, but want the site in light mode, they have to keep clicking the toggle each time the page is loaded, or, they are expected to change things within the browser. This is a poor implementation.

**Comment by freescout-helpdesk** [comment]
Messages discussing different issue from the originally posted by @fulldecent have been removed.

**Comment by freescout-helpdesk** [comment]
Is it still reproduceable?
