### ISSUE TITLE
Oauth and IMAP to Microsoft365 stopped working

### ISSUE THREAD

**Issue by bekre10** [freescout-helpdesk/freescout#2493]
Since yesterday, our Oauth connection to 2 different Microsoft365 tenants has stopped working.
The key is still valid, and I checked pretty much everything. I realize I can't fetch IMAP folders; it says, "Connected, but no IMAP folders found." I am logged in to M365 in the same browser which used to work. We haven't changed anything, either on Freescout or on M365/Azure.

I then tried to connect via IMAP and ensured it was enabled on the M365 tenant for the corresponding email account.
Sadly, this doesn't work anymore either.

This is now a significant issue since we can't receive tickets anymore. Fetching is just plain dead.
On another note, I restored a 3-day-old instance of our Freescout server to see if the issue persists there as well, and it does.

Anyone can help or sees the same issue?

**Comment by freescout-helpdesk** [comment]
MS365 sometimes does experience some technical issues: https://github.com/freescout-helpdesk/freescout/issues/2264#issuecomment-1255149413

Also see https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues

**Comment by bekre10** [comment]
I am aware that MS sometimes has issues. But this is not a way to work with as tickets must be reliably come in.
I've tried all suggestions in the link you provided, previously. But didn't help.
I now redirect emails to our support to Google for Workplace instead of M365 and let Freescout fetch from there .This works just fine.

**Comment by freescout-helpdesk** [comment]
Try to contact MS365 support like the person in this issue and let us know the results: https://github.com/freescout-helpdesk/freescout/issues/2264#issuecomment-1255149413
