### ISSUE TITLE
Publish website source to GitHub

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2494]
Please publish the source code of https://freescout.net/ to https://github.com/freescout-helpdesk/freescout.net

And also https://api-docs.freescout.net to https://github.com/freescout-helpdesk/api-docs.freescout.net

Then publish both using GitHub Pages.

Then add a link at the bottom of homepage, or all pages to "edit this page" pointing to the GitHub edit page.

---

This will allow the community to contribute improvements, such as corrections and new language localizations. And it allows you to say "PRs welcome" if ever a documentation issue is raised.

**Comment by freescout-helpdesk** [comment]
Content of API Docs can be generated using `php artisan apidoc:generate` command when API & Webhooks Module is installed. The output will be available in `/Modules/ApiWebhooks/Docs` folder.

To send improvements for _freescout.net_ - feel free to email at support@freescout.net
