### ISSUE TITLE
Faster Search: Too many processes

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#2498]
We bought Faster Search and I installed it with Meilisearch. Thx for that :+1:  However we experience server problems with that Module.

I updated FS to v1.8.45 this morning and FS started to re-index all data. I don't mind this process, but FS spawend many index commands and the process skyrocketed. Many SQL processes started, waited and the index procedure blocked a lot of resources. As you can see the hills. The first hill was after the update, then I rebooted the VM and the process started to raise again.

![CleanShot 2023-01-02 at 12 20 27](https://user-images.githubusercontent.com/1058710/210224855-ab819ae0-25bc-46dd-ac8b-054a8ae69fdf.png)

Additionally, I see a bunch of error message for MeiliSearch in FS Logs. I don't know if this is related or another problem.
![CleanShot 2023-01-02 at 12 24 26](https://user-images.githubusercontent.com/1058710/210224978-fba2eb13-5536-4aa4-aacf-3501493ee843.png)

I don't mind if the re-indexing happens or takes some time. We have a lot of conversations. Faster Search Modules states around 30.000 thread (?).

But the process of re-indexing should not block other ressources and take all CPU. Maybe you can throttle the processes and don't spawnd many artisan commands?

**Comment by freescout-helpdesk** [comment]
The process of indexing is already as optimal as possible. It's mostly done by cron without creating extra processes.
If someone will be able to optimize it somehow - see how to send us updates: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by obstschale** [comment]
Unsatisfactory answer
