### ISSUE TITLE
Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated

### ISSUE THREAD

**Issue by MaximilianGT500** [freescout-helpdesk/freescout#2499]
When the system tries to send a reply, this error always occurs:

System:
- Firmware: Ubuntu 20.04
- Webserver: Apache 2.4.54
- Database: 10.7.3-MariaDB
- PHP: 7.4.33

```
[2023-01-02 20:02:28] production.ERROR: Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated {"exception":"[object] (ErrorException(code: 0): Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated at PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SwiftException.php:26)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SwiftException.php(26): Exception->__construct()
#2 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/IoException.php(26): Swift_SwiftException->__construct()
#3 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/TransportException.php(26): Swift_IoException->__construct()
#4 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(457): Swift_TransportException->__construct()
#5 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(358): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#6 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#7 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#8 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send()
#9 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#10 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send()
#11 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send()
#12 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable()
#13 PATH/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send()
#14 PATH/app/Jobs/SendReplyToCustomer.php(224): Illuminate\\Mail\\PendingMail->send()
#15 [internal function]: App\\Jobs\\SendReplyToCustomer->handle()
#16 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#17 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#19 PATH/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#20 PATH/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#21 PATH/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#22 PATH/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 PATH/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#24 PATH/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#25 PATH/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#26 PATH/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#27 PATH/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#28 PATH/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#29 PATH/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#30 PATH/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#31 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#32 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#33 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#34 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#35 PATH/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#36 PATH/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#37 PATH/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#38 PATH/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#39 PATH/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#40 PATH/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#41 PATH/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#42 PATH/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#43 PATH/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#44 PATH/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#45 {main}
"} 
```

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by MaximilianGT500** [comment]
Now this error comes.
`Swift_TransportException: Expected response code 220 but got code "", with message "+OK Dovecot ready.
" in PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457
Stack trace:
#0 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(358): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 PATH/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send()
#4 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage()
#5 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\Mail\Mailer->send()
#6 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\Mail\Mailable->send()
#7 PATH/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\Mail\Mailer->sendMailable()
#8 PATH/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\Mail\Mailer->send()
#9 PATH/app/Jobs/SendAutoReply.php(74): Illuminate\Mail\PendingMail->send()
#10 [internal function]: App\Jobs\SendAutoReply->handle()
#11 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#12 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#14 PATH/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call()
#15 PATH/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#16 PATH/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#17 PATH/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 PATH/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#19 PATH/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow()
#20 PATH/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call()
#21 PATH/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#22 PATH/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process()
#23 PATH/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob()
#24 PATH/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon()
#25 PATH/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker()
#26 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#27 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#28 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 PATH/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#30 PATH/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call()
#31 PATH/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#32 PATH/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#33 PATH/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run()
#34 PATH/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run()
#35 PATH/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand()
#36 PATH/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#37 PATH/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run()
#38 PATH/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run()
#39 PATH/artisan(62): Illuminate\Foundation\Console\Kernel->handle()
#40 {main}`

**Comment by freescout-helpdesk** [comment]
This is the proper error message saying that something is wrong with your Dovecot mail server. In the past people had all kinds of problems with Dovecot mail servers - try to search for them.

**Comment by MaximilianGT500** [comment]
But I use my own Mailcow Server on another VPS for my Mails and not the internal mailserver.

**Comment by MaximilianGT500** [comment]
Okay, it was my fault, I accidentally used the wrong port, I used IMAP port 993 instead of 464.
