### ISSUE TITLE
Send 2 emails on answering a ticket

### ISSUE THREAD

**Issue by mindubaBr** [freescout-helpdesk/freescout#250]
Hi, 

When I reply a ticket, the system creates another empty reply and ticket status is automatically set to "Pending". See image below:

![image](https://user-images.githubusercontent.com/113139/54460863-8faa5400-4749-11e9-930c-b2d56327f2de.png)

The user of the tickets receives two emails at the same time, one of them with just the signature, see images below:

**2 Emails received at same time**

![image](https://user-images.githubusercontent.com/113139/54460959-dac46700-4749-11e9-9f33-2f265e00b0f3.png)

**First Email it is the right one**

![image](https://user-images.githubusercontent.com/113139/54460980-f465ae80-4749-11e9-8fcd-386046cfd8ce.png)

**Second Email it is a empty email with just the signature**

![image](https://user-images.githubusercontent.com/113139/54461010-0b0c0580-474a-11e9-9321-250fbb50933f.png)

**Comment by freescout-helpdesk** [comment]
Can you provide your system details: app version, PHP, browser, etc.

**Comment by mindubaBr** [comment]
System Details:

FreeScout 1.1.6 installed on a cpanel account. 
PHP 7.1 
Browser Mozilla Firefox
I´m not using HTTPS at this time

Mailbox Settings:
Status After Replying: Pending
Default Assignee: Person Replying
Sending Emails trough SMTP with SSL
Fetching Emails trough IMAP with SSL
Auto-Reply disabled at this time

**Comment by freescout-helpdesk** [comment]
Are you experiencing this issue with the latest release?
