### ISSUE TITLE
system/status 502 Bad Gateway

### ISSUE THREAD

**Issue by redWaggonCompany** [freescout-helpdesk/freescout#2500]
hello, i tried to enter system/status but i got error 502 bad gateway, i checked Manage » Logs » Application logs and i get this error in web-server.log, 

2023/01/02 15:27:13 [error] 928#928: *8262 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: x.x.x.x, server: 10.0.0.214, request: "GET /system/status HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "ayuda.xyz.mx", referrer: "https://ayuda.xyz.mx/" 

can you help me or point me the way to go

regards

**Comment by freescout-helpdesk** [comment]
Check nginx config, especially the version of PHP in
```
fastcgi_pass unix:/run/php/php8.0-fpm.sock;
```
