### ISSUE TITLE
Mobile Notifications - Not Receiving Push

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2501]
Recently for the past 1-2 weeks. we have not been receiving any push or browser notifications.
I'm not sure what caused it.
I tried to uninstall and reinstall the mobile notifications module, but that didn't help.

I have notifications setup via the twillio module, and that's the only thing that works right now. 

Can someone please help me. Thanks!!

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-browser-push-notifications-are-not-working

**Comment by SecureCPU** [comment]
It's also the push notifications on the mobile app.

Https is configured correctly, and I check all the other settings. I haven't changed anything, it just stopped working for some reason.

**Comment by SecureCPU** [comment]
Ok,
So i'm getting browser notifications just fine.
Just not any mobile notifications.

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.

**Comment by SecureCPU** [comment]
[web-server.log](https://github.com/freescout-helpdesk/freescout/files/10345020/web-server.log)
[laravel-2023-01-04.log](https://github.com/freescout-helpdesk/freescout/files/10345021/laravel-2023-01-04.log)
[laravel-2023-01-03.log](https://github.com/freescout-helpdesk/freescout/files/10345033/laravel-2023-01-03.log)
[laravel-2023-01-02.log](https://github.com/freescout-helpdesk/freescout/files/10345035/laravel-2023-01-02.log)

These are the web-sever logs and laravel logs from today through the first of jan

**Comment by freescout-helpdesk** [comment]
There is nothing suspicious in logs. All we can suggest is already described in the Troubleshooting section here: https://freescout.net/module/mobile-notifications/

**Comment by SecureCPU** [comment]
I made an account on demo.freescout.net and tested mobile notifications.
I'm not getting those either.

**Comment by freescout-helpdesk** [comment]
It means that push notifications are not enabled for the FreeScout app. See instructions at https://freescout.net/module/mobile-notifications/

**Comment by SecureCPU** [comment]
I found the issue,
But everytime a mobile notification comes through, the app crashes
