### ISSUE TITLE
Always problems with updating on production server

### ISSUE THREAD

**Issue by maisen20** [freescout-helpdesk/freescout#2502]
Hello,

unfortunately I have always problems updating to the latest version of freescout. I have now managed the update again, but had to start the update process twice via the WebUI of freescout and failed twice, and the WebUI did not work at all. After that I managed the update via ssh and tools/update.sh command.

Error logs:
`[2023-01-03 07:28:25] production.ERROR: The process has been signaled with signal "9". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The process has been signaled with signal \"9\". at /path/to/support/freescout-dist/overrides/symfony/process/Process.php:434)
[stacktrace]
#0 /path/to/support/freescout-dist/overrides/symfony/process/Process.php(212): Symfony\\Component\\Process\\Process->wait()
#1 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(201): Symfony\\Component\\Process\\Process->run()
#2 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(176): Illuminate\\Console\\Scheduling\\Event->runCommandInForeground(Object(Illuminate\\Foundation\\Application))
#3 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(59): Illuminate\\Console\\Scheduling\\Event->run(Object(Illuminate\\Foundation\\Application))
#4 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle()
#5 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#10 /path/to/support/freescout-dist/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /path/to/support/freescout-dist/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /path/to/support/freescout-dist/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /path/to/support/freescout-dist/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /path/to/support/freescout-dist/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
[2023-01-03 07:28:25] production.ERROR: The process has been signaled with signal "15". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The process has been signaled with signal \"15\". at /path/to/support/freescout-dist/overrides/symfony/process/Process.php:434)
[stacktrace]
#0 /path/to/support/freescout-dist/overrides/symfony/process/Process.php(212): Symfony\\Component\\Process\\Process->wait()
#1 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(201): Symfony\\Component\\Process\\Process->run()
#2 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(176): Illuminate\\Console\\Scheduling\\Event->runCommandInForeground(Object(Illuminate\\Foundation\\Application))
#3 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(59): Illuminate\\Console\\Scheduling\\Event->run(Object(Illuminate\\Foundation\\Application))
#4 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle()
#5 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#10 /path/to/support/freescout-dist/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /path/to/support/freescout-dist/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /path/to/support/freescout-dist/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /path/to/support/freescout-dist/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /path/to/support/freescout-dist/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
[2023-01-03 07:28:48] production.ERROR: Error: rename(/path/to/support/freescout-dist/vendor,/path/to/support/freescout-dist/storage/app/updater/1.8.45/vendor_tmp) [<a href='https://secure.php.net/manual/en/function.rename.php'>function.rename.php</a>]: No such file or directory; File: /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php (203)  
[2023-01-03 07:30:28] production.ERROR: Class "Barryvdh\Debugbar\ServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Barryvdh\\Debugbar\\ServiceProvider\" not found at /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:635)
[stacktrace]
#0 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(582): Illuminate\\Foundation\\Application->resolveProvider('Barryvdh\\\\Debugb...')
#1 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register('Barryvdh\\\\Debugb...')
#2 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#5 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#6 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /path/to/support/freescout-dist/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"} 
[2023-01-03 07:30:37] production.ERROR: Error: include(/path/to/support/freescout-dist/vendor/composer/../../overrides/barryvdh/laravel-debugbar/src/Console/ClearCommand.php) [<a href='https://secure.php.net/manual/en/function.include.php'>function.include.php</a>]: Failed to open stream: No such file or directory; File: /path/to/support/freescout-dist/vendor/composer/ClassLoader.php (455)  
[2023-01-03 07:30:50] production.ERROR: Class "Barryvdh\Debugbar\ServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Barryvdh\\Debugbar\\ServiceProvider\" not found at /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:635)
[stacktrace]
#0 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(582): Illuminate\\Foundation\\Application->resolveProvider('Barryvdh\\\\Debugb...')
#1 /path/to/support/freescout-dist/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register('Barryvdh\\\\Debugb...')
#2 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#5 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#6 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#7 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#8 /path/to/support/freescout-dist/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#9 {main}
"} 
[2023-01-03 07:30:50] production.ERROR: Call to undefined method TorMorten\Eventy\Facades\Events::action() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method TorMorten\\Eventy\\Facades\\Events::action() at /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221)
[stacktrace]
#0 /path/to/support/freescout-dist/app/Subscription.php(406): Illuminate\\Support\\Facades\\Facade::__callStatic('action', Array)
#1 /path/to/support/freescout-dist/app/Http/Middleware/TerminateHandler.php(18): App\\Subscription::processEvents()
#2 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): App\\Http\\Middleware\\TerminateHandler->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#3 /path/to/support/freescout-dist/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#4 /path/to/support/freescout-dist/public/index.php(88): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#5 {main}
"} 
`

**Comment by freescout-helpdesk** [comment]
https://stackoverflow.com/a/33147159
Try to increase memory limits on your server.

**Comment by maisen20** [comment]
I have 256M memory limit on both production server and development server. Shouldn't that be enough if it is also enough for the dev server?

**Comment by freescout-helpdesk** [comment]
It should be enough. Apparently something else is limiting PHP during update process and kills it: `The process has been signaled with signal "9"`

You may need some professional admin who can investigate it on your server.
