### ISSUE TITLE
New Mail Forward function checks entire HTML and not HTML body only, resulting in tickets created as agent again.

### ISSUE THREAD

**Issue by Lucleonhart** [freescout-helpdesk/freescout#2503]
Hello and thannks for adding the forward mail feature.
Unfortunately it does not work for us, the tickets are still created as the agent was the customer.
I did some digging and the problem appears in the getOriginalSenderFromFwd function. The $fwd_body contains the complete HTML document which has a lot of formatting in its header:

`
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Consolas;
	panose-1:2 11 6 9 2 2 4 3 2 4;}
@font-face
	{font-family:Tahoma;
	panose-1:2 11 6 4 3 5 4 4 2 4;}
`

After that the body starts. If i send only that body to the getOriginalSenderFromFwd function, it filters out the correct mail. Using the complete HTML it returns an empty string after trying to sanitize the first result from that header.

**Comment by freescout-helpdesk** [comment]
Ca you attach an example of the HTML which does not work for you.

**Comment by Lucleonhart** [comment]
I cannot paste the whole header in here as github does not like it as input here. If you need it let me know.

**Comment by Lucleonhart** [comment]
[mail.txt](https://github.com/freescout-helpdesk/freescout/files/10335281/mail.txt)

Here you are.

**Comment by Lucleonhart** [comment]
Sorry but it still does not work but i am not sure why.
I added some outputs for me to check:
`// Try to get "From:" from body.
$this->line('BODY:'.$body);
$original_sender = $this->getOriginalSenderFromFwd($body);
$this->line('original sender:'.$original_sender);`

I get the body log and then an empty string for original sender.

But if i manually drop the body log text into a preg match tester with your expression it works fine.

Here is the body: 
[log.txt](https://github.com/freescout-helpdesk/freescout/files/10371563/log.txt)

**Comment by Lucleonhart** [comment]
Is it enough to reply here or do i need to reopen a new ticket?
