### ISSUE TITLE
incorrect conversion of strikethrough and shaded text

### ISSUE THREAD

**Issue by HuibertStolker** [freescout-helpdesk/freescout#2504]
In the attachment with html-text you can see 'strikethrough' and (kind of) 'shaded'.
The styles are not shown in the Freescout ticket.
Is it possible to show these styles in Freescout message?

Clients instruct me sometimes what to do by using these styles.
I easy not noticing it and skip tasks
[Text mail Klingen.txt](https://github.com/freescout-helpdesk/freescout/files/10337598/Text.mail.Klingen.txt)

**Comment by freescout-helpdesk** [comment]
Could you please attach a screenshot.

**Comment by HuibertStolker** [comment]
Here you see it in Freescout and in 'original' view.
By the way, I'm very happy with Freescout, thankful you offer this application as open source!

<img width="851" alt="23-01-05 Freescout - incorrect convesion strikethrough-01" src="https://user-images.githubusercontent.com/116333780/210764474-577290f3-b012-4848-8d63-da48fb3191cd.png">
<img width="850" alt="23-01-05 Freescout - incorrect convesion strikethrough-02" src="https://user-images.githubusercontent.com/116333780/210764485-f7ef400f-7603-43c4-a49d-e4bc62e69952.png">

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
