### ISSUE TITLE
Random User Logouts

### ISSUE THREAD

**Issue by dealend** [freescout-helpdesk/freescout#2506]
We've been having this problem for a few months now and nothings worked to resolve it. Users get logged out randomly sometimes in within 1 - 2 mins of logging in to sometimes hours. All users don't get logged out at the same time either, it's random to each individual user.

We first thought it might be a session issue with file session driver, so we moved to db, and the problem is still ongoing. Any suggestions on where to look for potential issues? None of the logs show anything that we think is related to this.

**Comment by freescout-helpdesk** [comment]
The issue is quite unique. So most likely related to the environment you are using. What hosting are you using?

**Comment by dealend** [comment]
We're hosting on an aws ec2 instance. It was launched using the docker image you provide.

Whenever the log out happens, the message a user sees when trying to do something is "Error Occurred: Please check your internet connection and try again" and a refresh takes them to the login page. There is no logout in the logs and the sessions themselves haven't expired either from what I can tell.

**Comment by dealend** [comment]
Just to add, while attempting to recreate it. The first message that comes up is "Lost internet connection" as a red error message. Can be immediately after a page is loaded, or, after a while.

**Comment by freescout-helpdesk** [comment]
Something is finishing users' session. We've never seen such behavior. Apparently some deep investigation is required on your server.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
