### ISSUE TITLE
Emails Send Error ( Expected response code 354 ... )

### ISSUE THREAD

**Issue by dipakcg** [freescout-helpdesk/freescout#251]
Somehome emails are stopped from being sent. It was working fine but not sure what happened suddenly and none of my emails are sending.

<img src="https://cldup.com/IeVGP_R82V.png" />

Any help will be highly appreciated.

-----
FreeScout Version: 1.1.6
PHP Version: 7.1.21
Web Server: Apache
MySQL Version: 14.14 Distrib 5.5.61

**Comment by dipakcg** [comment]
Just updated to FreeScout 1.1.7 today, but the mentioned issue is still there.

<img src="https://cldup.com/KMq616PGiF.png" target="_blank" />

I really appreciate any help here.

**Comment by freescout-helpdesk** [comment]
Which sending method are you using?

**Comment by dipakcg** [comment]
I am using SMTP which was working fine till I first reported about the issue. I've tried _PHP's mail() function_ though just to check whether it fixes the issue but no, it gives the same error too.

So no matter which sending method I use, it gives the same error.

**Comment by freescout-helpdesk** [comment]
> The 554 5.5.1 error is the SMTP error "no valid recipients". It can occur if you've misspelled the recipient addresses but it can also occur if you are not properly authenticating to the outgoing server.

https://stackoverflow.com/questions/54616706/how-do-we-solve-error-554-5-5-1-no-valid-recipients-when-using-php-swiftmailer

**Comment by dipakcg** [comment]
Sorry! That didn't help. As a PHP (not Laravel) Developer, I have already tried as many steps as I can at my own but no joy.

As said above, everything was working fine and then all of a sudden, it stopped sending emails. No changes in the server as well as it's fully managed by me itself.

Is there any particular file I should look and make changes?

**Comment by freescout-helpdesk** [comment]
You may need to debug https://github.com/freescout-helpdesk/freescout/tree/dist/vendor/swiftmailer/swiftmailer

**Comment by dipakcg** [comment]
I've tried to re-upload _swiftmailer_ folder but it didn't fix the issue. Anything else I should look into?

**Comment by dipakcg** [comment]
Finally, I've reinstalled FreeScout and it fixed the issue. Weird but worked :)

I had taken a backup before reinstallation which I've then restored so I am all set now.
