### ISSUE TITLE
Missing details for Google Apps SSO

### ISSUE THREAD

**Issue by miarosemathews** [freescout-helpdesk/freescout#2511]
It appears there are missing details in the SAML application that prevents it from authenticating with google apps. The entity ID is missing. Please advise as i am trying to set up google as an IDP for worksuite.

**Comment by freescout-helpdesk** [comment]
You need the FreeScout to provide you this Entity ID? Right? https://support.google.com/a/answer/6087519?hl=en

![2023-01-07_08-34-27](https://user-images.githubusercontent.com/40499291/211132912-2bfef64d-ba0f-416c-8718-41fe1f033c7c.png)

**Comment by miarosemathews** [comment]
Yes to set up a custom app with google sign in if you go to my sso it says once selecting google as the provider and selecting the google account that an app has not been configured for the user because without the entity id you cannot allow google workspace to create a saml connection you should update you docs for google because when you download the metadata for the saml connection it list that in that data but not in the settings which it should because no one would know to download the metadata and find out this information manually so yes it is very much a freescout issue @freescout-helpdesk

**Comment by miarosemathews** [comment]
https://drive.snnj.org/s/n2YE3goWz5GWD4k 

here is what google requires to allow saml

@freescout-helpdesk

**Comment by miarosemathews** [comment]
https://drive.snnj.org/s/ptNZcJwg6J4kgot

it is not set up correctly the plugin to work with Google SAML 2.0

@freescout-helpdesk

**Comment by miarosemathews** [comment]
https://drive.snnj.org/s/EHQiZMyoFbLogqX

**Comment by miarosemathews** [comment]
I will literally write the faq for you since i know how to fix it if you want @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
Sure. We'll add instructions to module's page (https://freescout.net/module/saml/).

**Comment by miarosemathews** [comment]
Login to your Freescout instance and navigate to Manage >  Settings > SAML 2.0



Configure Google Apps for sign in 

Login to admin panel and navigate to Apps > Web and mobile apps 



Click Add App > Add custom SAML app

Configure basic app information (This will be what is shown in available apps for your users) 



Click Continue

Copy the following from the next page which shows the IDP for Google 


In freescout:

Use SSO URL for Sign in URL
Use Entity ID for Entity
Use Certificate for x509 Certificate

In Google Click Continue 

Next you will be asked to input details from freescout

Use ACS URL for ACS URL
Use SP Metadata For ENTITY ID

Scroll down and select SIGNED RESPONSE

Scroll down further and change Name ID format to EMAIL from the default UNSPECIFIED and then the next field change NAME ID to BASIC INFORMATION  > PRIMARY EMAIL (This will use the domains email for your workspace account) 

ON the next screen after clicking continue you can map user fields. Click continue and select which groups in your org you want to have access to the app, the app is off for everyone by default. Once selecting on for everyone or the group you want click test sign in on the sidebar under the app. Make sure you are signed out of freescout first or else it will use the current sign in and trigger a false positive for sign in.

**Comment by miarosemathews** [comment]
Could be better but i hope that helps @freescout-helpdesk

**Comment by miarosemathews** [comment]
If you need screenshots please let me know @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
Thanks. Instruction has been added to https://freescout.net/module/saml/
