### ISSUE TITLE
Sender Time Zone

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#2512]
I have installed the Sender Time Zone module, but from the testing I have carried out, it needs to show the correct time zone for the emails.  

This is the header from my email and I think the GMT offset should be -0600
![Canute_Thursday, 5 January 2023_5](https://user-images.githubusercontent.com/27293201/210752379-9ca72da5-3dac-4f0a-a385-22d480b82ecb.png)

But when I check the time and zone, its back to GMT as below 

![Canute_Thursday, 5 January 2023_3](https://user-images.githubusercontent.com/27293201/210753532-3c5a8c0e-be28-4c5c-9187-f4ed4e24467d.png)

Can anyone please help me to sort this issue out, or is it that I need help understanding it correctly?

Thank you very much for any help.

John

**Comment by freescout-helpdesk** [comment]
The module takes timezone from the `Date` header.
