### ISSUE TITLE
iOS FreeScout is not opening

### ISSUE THREAD

**Issue by infornet1** [freescout-helpdesk/freescout#2513]
Hello All,
By unknown reason my Freescout on iOS is not opening my site, just looks freeze after I click on Go...
I have reinstalled several timer the iOS app in my iPhone still issue persist.
Do u know anything else about this?
Thks
Gustavo.-

https://user-images.githubusercontent.com/11906111/210768608-a9c1b16a-fddc-459d-bfcd-363e00ddd187.mp4

**Comment by freescout-helpdesk** [comment]
It looks like FreeScout is located in a subfolder? Could you please post here or send your FreeScout URL to support@freescout.net?

**Comment by infornet1** [comment]
Sent

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the FreeScout iOS app v1.0.5
