### ISSUE TITLE
SMS reopens old ticket not a new one - Feature Request

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2514]
Hey,
Is there any way to add the option so that once a ticket that was opened via SMS is closed, the next time that client sends a text it opens a new ticket and not the old one? Maybe to also be able to open a new ticket via SMS; as of now, we can only open tickets via email; only the client can open a ticket via SMS.

As of now, if a client opens a ticket via SMS and had previously opened a different ticket via SMS that is now closed, it reopens the old ticket and that mixes up the different tickets and time tracking. Also, if I try to split the new reply into a new conversation it only allows for email, not SMS. via SMS I know we can't have 2 tickets open at the same time, but if it can be changed so that if the ticket is closed, it opens a new ticket, not the old one.

This also applies to tickets opened via WhatsApp, Twitter, and Facebook. I haven't checked the other methods.

And really appreciate the work you guys are doing on Freescout. Really love the application!

**Comment by freescout-helpdesk** [comment]
Unfortunately till now we could not find a reliable solution for this.

**Comment by freescout-helpdesk** [comment]
We don't have a solution. Most likely it will stay as is.

**Comment by ilyakonovalenko** [comment]
> We don't have a solution.

It seems the best way is to provide two options:
- Use the same conversation for all messages
- Create a new conversation if there is no open conversation alreay

For the first option everything will be as it is now.
For the second option module has to check if there is any open module-related conversation for the customer. If nothing found - create one, else add a message to the open one. And it seems some hook must be added to prevent any closed module-related conversation to be re-opened in case other conversation is in active state already.

**Comment by freescout-helpdesk** [comment]
There is no way to figure out at what moment to start a new conversation. That's why it will stay as is.
