### ISSUE TITLE
Ticket Number Module active but does not appear anywhere to setup.   

### ISSUE THREAD

**Issue by mastenzales** [freescout-helpdesk/freescout#2516]
After activating the Ticket Number module, i do not see any where to setup the module.   Looked in "Manage -> Settings" but not in the settings list, looked in Mailbox Settings just in case and not there either.   Deleted the module, cleared cache, Installed, and activated and still in Manage-> Settings all I see is [General](https://help.pnw.com/app-settings/general)
[Mail Settings](https://help.pnw.com/app-settings/emails)
[Alerts](https://help.pnw.com/app-settings/alerts)
[Customization](https://help.pnw.com/app-settings/customization)
[OAuth](https://help.pnw.com/app-settings/oauth)
[Two-Factor Auth](https://help.pnw.com/app-settings/twofactorauth)
[Customer Fields](https://help.pnw.com/app-settings/customer-fields)
[Spam Filter](https://help.pnw.com/app-settings/spamfilter)

I also tried  https://help.pnw.com/app-settings/ticket-number  as a test and results in page not found

App Version | 1.8.46    Check for updates

Jan 5, 2023 15:33
America/Los_Angeles (GMT-0800)
HTTPS
Apache/2.4.52 (Ubuntu)
PHP 8.0.26
2M / 8M

**Comment by freescout-helpdesk** [comment]
The module does not have any settings. It simply adds a ticket number in the subject line of emails sent to customers.
