### ISSUE TITLE
WorkFlow doesnt get triggered

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2518]
We have a workflow setup that should remind the users about the ticket, after a certain amount of time:

![image](https://user-images.githubusercontent.com/110815495/210980125-d3abe2c7-6b7f-4d2f-bd69-c506dbc50b93.png)

![image](https://user-images.githubusercontent.com/110815495/210980224-8213687d-5e07-43ea-9d6f-0844fedde76a.png)

However it doesnt seem to trigger:

![image](https://user-images.githubusercontent.com/110815495/210986670-1e367d89-1a4b-4240-b479-fd345465be7e.png)

I've tried to Save and Execute, which saves correctly, but doesnt seem to trigger on the conversation either.

The work queue seems to be running fine aswell:

![image](https://user-images.githubusercontent.com/110815495/210987588-93868b42-94ae-44ab-8cea-9bee885dfcb0.png)

And there is no logs that correspond with the timing.

**Comment by freescout-helpdesk** [comment]
We've checked and it works fine for us. Make sure to set workflow to "Active" and save it.

**Comment by ID4600** [comment]
I seem to have the same issue. Workflow is active and even when I turn on "Apply to Previous" it doesn't do anything. 

**Running**: 1.8.46
**Modules**:
Customers Management (CRM) 
Custom Folders 
Customer Data Enrichment 
Customization & Rebranding 
Extended Attachments 
Extended Editor 
Global Mailbox 
LJPc alternative signatures module 
LJPc calendar module 
Mentions 
Saved Replies 
Tags 
Widgets White-Labeling Active
Workflows

**Comment by maxkvbn** [comment]
It has both Active and Apply to Previous applied.

**Comment by freescout-helpdesk** [comment]
Are you using Cloudron?

**Comment by maxkvbn** [comment]
No, we are not using Cloudron.

**Comment by freescout-helpdesk** [comment]
The only way to figure out why it does not work for you is to check it on your server. You can provide an access to your FreeScout (email at support@freescout.net) or https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
