### ISSUE TITLE
Freescrout fetch emails under 1 minutes

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2519]
Please correct me if i am wrong,
Freescout fetches email every one minute using the following crontab
 * * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1  - which runs every a minute

If i place this cmd into a script and run it every few seconds will that resolve the issue and make freescout almost "Realtime"

if not please let me know what does the above cmd does exactly running every 1 minute

Thank you

**Comment by freescout-helpdesk** [comment]
Here are the commands executed by `schedule:run`: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php#L30

Laravel console commands are designed to run every minute. So result of running them more of often is difficult to predict.
