### ISSUE TITLE
Email markup from clients not showing in tickets

### ISSUE THREAD

**Issue by ID4600** [freescout-helpdesk/freescout#2520]
It seems that the markup that clients use in their e-mail gets removed which is kind of annoying. 

As you can see there is a clear markup in the email, send out with a gmail client. 
![original_mail](https://user-images.githubusercontent.com/10940907/211147731-b199521e-bc83-4a87-b15f-06ac0a37abbc.jpg)

When received on our side it's pretty much all flat text with only a exception for the bold and underline 
![scout_mail](https://user-images.githubusercontent.com/10940907/211147726-bfba3153-c1da-4ace-bda6-86c99ef9ba32.jpg)

When looking at the "show original" it looks fine but it's annoying to have to open that. 
![show_original](https://user-images.githubusercontent.com/10940907/211147733-9cbd6c86-65b9-4478-8b04-8c3ce42ba5ab.jpg)

Sometimes clients or other contacts use markup in their mail and it gets removed, for the people on our end it gets pretty unclear in someone copies our texts into their mail and responds in them with colors because those colors get removed.  

Also, when they kopie the tekst and it includes the >> in front of the text (because it's copied in the editor I think) FreeScout removes the text including everything below it even though there can still be text under it thats not copied from an old email. 

I did not try using other email providers and their method of markup, but I feel like working with gmail should simply work?!

Running: 1.8.46
Modules:
Customers Management (CRM)
Custom Folders
Customer Data Enrichment
Customization & Rebranding
Extended Attachments
Extended Editor
Global Mailbox
LJPc alternative signatures module
LJPc calendar module
Mentions
Saved Replies
Tags
Widgets White-Labeling Active
Workflows

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed

**Comment by ID4600** [comment]
So there is a solution, just not implemented yet?

**Comment by freescout-helpdesk** [comment]
There is no solution yet.

**Comment by foliovision** [comment]
We are running into issues where some clients use **text background color** to highlight answers in their emails. This is how that looks in email notifications:

![Screen Shot 2023-01-16 at 11 09 55](https://user-images.githubusercontent.com/1180948/212652878-b4e3d14e-a90f-4114-b14a-2391a84d520d.png)

But nothing shows in Freescout:
![Screen Shot 2023-01-16 at 11 10 32](https://user-images.githubusercontent.com/1180948/212653039-c2b350c5-7a50-47bf-bb7e-990c4221346d.png)

Could the HTML filtering perhaps keep the color and background styles?

I can see the SPAN is still there:

![Screen Shot 2023-01-16 at 11 11 36](https://user-images.githubusercontent.com/1180948/212653273-6fec9917-9855-463c-aa53-15d183fdb1d3.png)

I also see the whole style attribute is **retained in database**:

`<p class="MsoNormal">I made some additional clarifications below <span style="background:yellow;mso-highlight:yellow">`
