### ISSUE TITLE
Feature request for global workflow module

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#2521]
Usecase is I have certain mailboxes where I want to run the same workflow, can we have a module where I can configure which module should this query run for?

There are some things that won't be available like custom fields.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans for now. What can be done - is cloning workflows into other mailboxes.

**Comment by freescout-helpdesk** [comment]
Feel free to submit feature requests here: https://freescout.net/request-feature/

**Comment by rosinghal** [comment]
Done. Does it make sense to have the option to clone workflow for now?
