### ISSUE TITLE
Messages not being pulled

### ISSUE THREAD

**Issue by shrogers45** [freescout-helpdesk/freescout#2524]
I installed Freescout on Windows but the emails are not being pulled every 1 minute.

If I ran the below, only then it's being pulled.
http://localhost/freescout/system/cron/206e5acfdbd789416e4e143a84b2b741

What am I doing incorrect?

**Comment by freescout-helpdesk** [comment]
Cron job need to be configured: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs
