### ISSUE TITLE
Workflows Module Add/Remove Tag Autocomplete

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2525]
FreeScout - Version: 1.8.47
Workflows Module - Version: 1.0.35

When creating a workflow and setting the action to Add or Remove a Tag it should auto-complete existing tags.
This behaviour exists when manually tagging a conversation and could work the same for this.

Thanks
Ben

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/
