### ISSUE TITLE
Knowledge Base: Format Toolbar Does Not Scroll

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2526]
In the Knowledge Base editor, the Sommenote Editor textbox is automatically extended to fit the whole content. This results in the format toolbar being unreachable when the user has to scroll within the article.

Just a small change like setting font bold requires to scroll all the way up, clicking the toolbar and scrolling down to the cursor again which makes editing of long articles very tedious. Please fix!

**Long example text:**

![image](https://user-images.githubusercontent.com/80592577/211321551-a40f3b63-7f1f-4b30-a119-c0e33bcec2b2.png)

---
**Scrolling down:**

![image](https://user-images.githubusercontent.com/80592577/211321561-13e223e3-c347-49c5-9a98-ddcf50e4970a.png)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
