### ISSUE TITLE
Knowledge Base: Showing a KB Article Has Category Collapsed

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2527]
Viewing a Knowledge Base article without adding the **category_id** GET parameter into the URL results in the category tree beeing collapsed and not showing any category opened when the article is shown, even if the arcticle has only a single category.

Expected behaviour: If no category_id parameter is supplied, the first article category should be expanded by default.

**Editor:**

![image](https://user-images.githubusercontent.com/80592577/211324436-2a2433d4-7fc4-4a80-816b-f312c4c2b275.png)

---

**Knowledge Base:**

![image](https://user-images.githubusercontent.com/80592577/211325232-abe91aaf-52a3-4f81-9a20-7ec227e14ae3.png)

**Comment by freescout-helpdesk** [comment]
Implemented in Knowledge Base Module v1.0.41
