### ISSUE TITLE
Knowledge Base: Change History (Feature)

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2528]
The Knowledge Base should keep a history of all saved versions of an article along with a change timestamp and the editing user. That way, it is obvious who created or changed a certain article and and which time.

This is an essential feature for being able to use the otherwise excellent KB functionality in a productive environment.

Currently, nothing is traceable.

**Comment by MarcoWel** [comment]
See also:
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/385203

**Comment by freescout-helpdesk** [comment]
This feature request is enough: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/385203

**Comment by MarcoWel** [comment]
Can we assign some more priority to this issue? Either funding development or having a separate paid module for it.
