### ISSUE TITLE
Validate Certificate option for Fetching

### ISSUE THREAD

**Issue by evolucja** [freescout-helpdesk/freescout#253]
Hello,

1. I couldn't get fetching email working on my shared server. Each time i'm getting the following error:

` map_open(): Couldn't open stream {daventi.pl:993/imap/ssl}. Certificate failure for daventi.pl: self signed certificate in certificate chain: /C=PL/O=Unizeto Sp. z o.o./CN=Certum CA`

2. Also when i'm going to /system/status page i'm getting:
`"Whoops, looks like something went wrong."`

3. How can I setup cron on shared hosting where I can only point in options to a specific .php file?

All tests during installation passed.

Any ideas?

Thank you
Dave

**Comment by evolucja** [comment]
I think I need to use "/novalidate-cert" for the first issue but where I should add it?

**Comment by pocketfulofrage** [comment]
/www/html/vendor/webklex/laravel-imap/src/IMAP/Client.php, line 457 in the container.

I ended up commenting out lines 456 and 458 to force it, then linked the file as a volume in my docker-compose.

**Comment by freescout-helpdesk** [comment]
We will add validate_cert option to the Fetching settings in FreeScout.
