### ISSUE TITLE
Move Deleted folder

### ISSUE THREAD

**Issue by eljakim** [freescout-helpdesk/freescout#2530]
See the screenshots below. The box for deleted messages ONLY shows if you click on 'closed' first.

### Deleted box does not show
<img width="247" alt="image" src="https://user-images.githubusercontent.com/203086/211486949-da83f81e-1b7e-4971-ad03-b8b24086d93c.png">

### Deleted box does show when 'closed' is selected
<img width="244" alt="image" src="https://user-images.githubusercontent.com/203086/211487032-221af96f-60e9-463a-9693-4ca2120c14f8.png">

Are you able to fix this?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#trash-folder-is-not-visible

**Comment by eljakim** [comment]
@freescout-helpdesk can you at least ensure then that the 'Deleted' mailbox shows up directly below the 'closed' box? Currently the order is:

- Closed
- Spam
- Deleted [only shown when you click on closed]

It turns out to be very confusing to our users.

I understand you've done it by design, which is fine. But would it be up for discussion to thus show the boxes in this order:

- Closed
- Deleted [only shown when you click on closed]
- Spam
