### ISSUE TITLE
Empty Trash button does not work from Global Mailbox

### ISSUE THREAD

**Issue by eljakim** [freescout-helpdesk/freescout#2531]
When you are in the 'Global' mailbox and go to 'Deleted messages', there is an 'Empty Trash' button at the top of the page. Clicking this button does nothing.

On the 'deleted messages' for individual mailboxes it works just fine. It's only the global mailbox where it does not work.

Can this be fixed?

**Comment by freescout-helpdesk** [comment]
Fixed in the Global Mailbox v1.0.6
