### ISSUE TITLE
Knowledge Base Article Names Visibility on Home

### ISSUE THREAD

**Issue by pf248** [freescout-helpdesk/freescout#2533]
Hello everyone, 
we work on our internal KB and I discovered a thing that I do not get at the moment. 

When I set all categories and articles visibility to "support members only", they got invisible to guests. So far so good.
Set it up on the Demo KB:
![demo_kb3](https://user-images.githubusercontent.com/81617453/211581764-31b48a11-66d1-4ace-922b-82cf39245471.PNG)

But when I access the "Home"-Page auf the KB as a guest visitor, the articles titles are all exposed:
![demo_kb](https://user-images.githubusercontent.com/81617453/211582626-ce7755c2-5f79-4d25-ae3c-d8b39da2cba8.PNG)

Is this intentional? Or is it not supposed to do so? (Cause it could display sensible information to the public and we do not want to allow all persons to read them)

Thanks in advance for any anwsers!

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module v1.0.42
