### ISSUE TITLE
Bug: reply editor cursor jumps after entering a URL  (Safari only)

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2534]
Freescout version: 1.8.48

When manually typing a URL in the reply editor the cursor jumps back to the beginning of URL after the URL is detected and converted to a link.

This appears to only happen in Safari.
Safari versions tested: 16.0 (macOS Monterey 12.6) and 16.2 (macOS Ventura 13.1)

Reproduce by typing "www.apple.com" and then press space.
The URL will be converted to a link (coloured blue) and the cursor jumps back to the start of the URL.

Expected behaviour is the cursor remains after pressing space.

**Comment by freescout-helpdesk** [comment]
Are you able to reproduce the issue here: https://summernote.org

**Comment by avenjamin** [comment]
Yup - behaves exactly as reported.

I also tested it on my iPhone X (16.3 beta) and it also behaves the same way.

**Comment by avenjamin** [comment]
I've filed a bug report with summernote: https://github.com/summernote/summernote/issues/4412

**Comment by freescout-helpdesk** [comment]
Summernote team could not fix this: https://github.com/summernote/summernote/issues/4412#issuecomment-1615587522
