### ISSUE TITLE
Can't delete mailbox if user authorized via SSO

### ISSUE THREAD

**Issue by andy-a2c** [freescout-helpdesk/freescout#2538]
When user created via OAuth & Social Login module it is not possible to him delete mailbox.
When you try to delete mailbox FreeScout asks to provide password 
![image](https://user-images.githubusercontent.com/121050024/211776323-3f8f6278-b030-4a78-acb0-7c2e9c758537.png)
And no matter what you will try to specify there - app reject to delete mailbox (I believe because for SSO bootstrapped users password is not stored on DB. Just guessing). When I specify IdP password I got responce from API `{"status":"error","msg":"Please double check your password, and try again"}`

It will be good to have delete confirmation flow that doesn't require password input. E.g. just ask to type mailbox name to make sure it is not accidental click

**Comment by freescout-helpdesk** [comment]
Can you check what you have in the `password` field for this user in DB users table?

**Comment by freescout-helpdesk** [comment]
Fixed in OAuth & Social Login Module v1.0.3
