### ISSUE TITLE
stucked work queue

### ISSUE THREAD

**Issue by phanousk** [freescout-helpdesk/freescout#2539]
Hi,
some days ago one of my users sent a reply from Freescout web and from that time this action blocks all the work queue. When I run schedule:run, it ends always like this:

    # time sudo -u www-data /usr/bin/php7.4 /opt/freescout/artisan schedule:run
    Running scheduled command: '/usr/bin/php7.4' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
    Running scheduled command: '/usr/bin/php7.4' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
    Running scheduled command: '/usr/bin/php7.4' 'artisan' freescout:fetch-emails > '/opt/freescout/storage/logs/fetch-emails.log' 2>&1
    Running scheduled command: '/usr/bin/php7.4' 'artisan' freescout:extendedattachments-cleanup > '/dev/null' 2>&1
    Running scheduled command: '/usr/bin/php7.4' 'artisan' queue:work --queue='emails,default,1f56738110375d8a61cf77e495db5890' --sleep=5 --tries=1 > '/opt/freescout/storage/logs/queue-jobs.log' 2>&1

    real    1m5,256s
    user    0m33,586s
    sys     0m26,055s

So the mails are fetched, it's sent one mail from that spoiled ticket and no more. The Outgoing mails ticket dialogs in other tickets say "There were no send attempts yet". The log `/opt/freescout/storage/logs/queue-jobs.log` states: 

    [2023-01-11 11:40:06] Processing: App\Jobs\SendReplyToCustomer
    Killed

I've tried `queue:flush`, `queue:forget` and `queue:restart`  but without any success. When I try to send a test mail from mailbox connection settings page, it is sent and then received at the destination address OK. Could you please someone bring some light into that? I am running version 1.8.48, there is no stuck artisan process when trying `ps faux` and rebooting the system doesn't help also.
Thank you, Petr

**Comment by freescout-helpdesk** [comment]
You can find SendReplyToCustomer job in Manage > Status page in Background Jobs and cancel if you want.
