### ISSUE TITLE
Email with *.p7m attachment not getting properly converted

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2540]
Hi,

sometimes we receive an email with no visible body but one attachment called smime.p7m. I noticed that I can kinda "unpack" such files into a standard eml file with the _openssl_ command. Are there any plans to add support for such emails to properly convert them into a thread on fetching?

Thanks in advance

**Comment by freescout-helpdesk** [comment]
This is signed/encrypted message: https://fileinfo.com/extension/p7m
Maybe in the future there will be a possibility to decrypt them.
