### ISSUE TITLE
How to migrate existing gmail account currently managed via Hiver plugin

### ISSUE THREAD

**Issue by ddresch** [freescout-helpdesk/freescout#2543]
We are using [Hiver](https://hiverhq.com/) as a tool to manage our shared mailbox. 

We have Freescout running, and we can connect to gmail via IMAP. Now the question is how to migrate the labels used by gmail/Hiver. Hiver uses labels to map mails to a specific conversation states like (open, closed etc.).

Is there an existing solution / tutorial how to migrate? We currently store about 20k mails in this mailbox, which is in no way manageable manually. Currently, all the mails show up in Freescout as unassigned.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such solution for now.
