### ISSUE TITLE
feature: Allow configuring SMTP headers in app-settings 

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#2546]
Some SMTP providers need some additional headers when sending. For instance **Elastic email** 
https://help.elasticemail.com/en/articles/2376848-how-to-manage-custom-headers

Allow to specify a collection of headers such as `"isTransactional" : true` when defining smtp server connection would make freescout work with the "pro" smtp servers

https://freescout.umakers.dk/app-settings/emails

**Comment by freescout-helpdesk** [comment]
Are you sure Elasticemail will read `isTransactional` header when sending an email via SMTP? All examples in their docs are using REST API. Try to check with them.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch. Add the following to your /.env file and clear cache:
```
APP_CUSTOM_MAIL_HEADERS="IsTransactional:True"
```

**Comment by jesperordrup** [comment]
@freescout-helpdesk wow thats fast :-)

I have to wait trying until your next release.
