### ISSUE TITLE
Workflows Module - Increase process_cron in config

### ISSUE THREAD

**Issue by adamsewell** [freescout-helpdesk/freescout#2549]
in Modules/Worflows/Config/config.php, there is a variable that appears to dictate how often the Workflows execute. Is there a method to adjust this cron in a manner that won't be overwritten? 

```
process_cron' => env('WORKFLOWS_PROCESS_CRON', '0 * * * *')
```

**Comment by adamsewell** [comment]
What would the format be for it? 'process_cron="* * * * *"'?

**Comment by freescout-helpdesk** [comment]
Yes.
