### ISSUE TITLE
Vacation

### ISSUE THREAD

**Issue by elfeffe** [freescout-helpdesk/freescout#255]
There is no advances for 3 months

**Comment by freescout-helpdesk** [comment]
FreeScout team is on a vacation. PR requests are still welcome, they will be revised after few months.

**Comment by elfeffe** [comment]
No updates for 3 months, and PR will be revised after a few months.
Those are vacations and not mine!

**Comment by galloppinggryphon** [comment]
@freescout-helpdesk Hi Freescout team! Glad to hear its not dead! I appreciate the software, I think it's got fantastic potential and it's really needed! I understand that you have to take a break and that you're doing this on your free time! Gotta make the monies too - that's grassroots open source development in a nutshell. However, we would also appreciate it if you let us know when you're taking that break! Seeing commits suddenly drop off and issues piling up without reason tends to make me nervous... I've seen the same thing happen with Rainloop - no commits for months, no replies to issues. I want to use it, but I can't until I know it's still under development and that bug reports will be looked into. Hope to hear that the project is back on track soon!

**Comment by galloppinggryphon** [comment]
@freescout-helpdesk  Maybe you could create an issue explaining you're on a break and maybe when you expect to be back, and pin it to the top? I understand that's possible since last year. Would be very helpful and transparent!

**Comment by freescout-helpdesk** [comment]
This issue has been pinned. Work will be continued in 2-3 months.
