### ISSUE TITLE
Searching for ticket# ID does not work well

### ISSUE THREAD

**Issue by MarcoWel** [freescout-helpdesk/freescout#2550]
You recently implemented a direct jump to the ticket when searching for a ticket number (instead of displaying the search results with only a single item as before).

However, this feature does not work very well yet:

- Even when using only the ticket ID (e.g. "116935") as a search term, it still takes a long time to complete the direct jump. It seems that Freescout is doing a regular full-text search first and when there is a single match only, the matching ticket is opened. It would be better to first check if the search term looks like a ticket ID (e.g. via regex), and then trying to jump to this ID directly.
- When the ticket ID in the search term includes a hashtag prefix (e.g. "# 116935" or "#116935"), there is no ticket found at all. This is bad, because ticket IDs are always referenced by a leading hashtag plus space ("# ") within Freescout (so support agents use this semantic to reference tickets within other systems and often copy/past ticket IDs including prefix).

Suggested pseudo code to solve this:
```php
$ticket_id_regex = '/^[#]?[ ]?(\d{1,8})$/m';
$search_term_is_ticket_id = preg_match($ticket_id_regex, trim($search_term), $match) === 1;

if ($searchterm_is_ticket_id)
{
   $ticket_id = intval($match[1]); // Extract ticket number as int from regex capture group
   // Jump to $ticket_id directly (optionally check for existance first)
}
else
{
   // Perform full text search
}
```

**Comment by MarcoWel** [comment]
See also #2390

**Comment by freescout-helpdesk** [comment]
User may search for some number in existing conversations. So we have to perform full search and if only one conversation found - redirect to this conversation. Otherwise the user may get surprised why he/she was redirected to a conversation when looking for "123" for example.

**Comment by MarcoWel** [comment]
I disagree on this. Searching an integer number without any context within hundreds of thousands of tickets does not make sense. It is like typing "123" into Google. Also, the regex will not match on anything like "O123", "Customer 123", "12-3" or whatever more specific might be searched.

Alternatively, there could be a setting for this (on/off). Or you only do a direct jump when the quick search on the top right is used, but never on the extended search.
