### ISSUE TITLE
'Lost internet connection' error results in user being logged in as a another account

### ISSUE THREAD

**Issue by ThatBrownGuy35** [freescout-helpdesk/freescout#2551]
Recently deployed Freescout on an ubuntu VM, started running into an concerning error. Happens randomly and is hard to replicate but it happens at least once a week, usually throwing the error pasted below. The following occurs which results in User 1 being logged in as User 2 without any sort of authentication. 

User 1 & User 2 are on separate machines, logged in with different accounts created via the LDAP module. 

1. User 1 & User 2 are logged in and using the system normally
2. User 2 experiences a seemingly random 'Lost internet connection' error on the top of the page
3. User 2 refreshes the page
4. User 2 is now logged in as User 1 without entering any login information or anything of the sort
5. User 1 can now see User 2 replying to tickets/emails as User 1
6. After a few minutes User 1 experiences the same 'Lost internet connection' error, refreshing the page requires both users to need to log back in.

`Call to undefined method Watson\Rememberable\Query\Builder::getRobotsCondition() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Watson\\Rememberable\\Query\\Builder::getRobotsCondition() at /www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2483)
[stacktrace]
#0 /www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1288): Illuminate\\Database\\Query\\Builder->__call('getRobotsCondit...', Array)
#1 /www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1474): Illuminate\\Database\\Eloquent\\Builder->__call('getRobotsCondit...', Array)
#2 /www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1486): Illuminate\\Database\\Eloquent\\Model->__call('getRobotsCondit...', Array)
#3 /data/Modules/Reports/Providers/ReportsServiceProvider.php(168): Illuminate\\Database\\Eloquent\\Model::__callStatic('getRobotsCondit...', Array)
#4 /data/Modules/Reports/Console/CollectData.php(36): Modules\\Reports\\Providers\\ReportsServiceProvider::collectData()
#5 [internal function]: Modules\\Reports\\Console\\CollectData->handle()
#6 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#11 /www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Modules\\Reports\\Console\\CollectData), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
"}
                    `

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of FreeScout and Reports Module?

**Comment by freescout-helpdesk** [comment]
Make sure to update FreeScout to the latest version and the error will disappear.

**Comment by ThatBrownGuy35** [comment]
Error continues to occur, running 1.8.56 albeit less frequently.
