### ISSUE TITLE
Style sheet refer to example.com

### ISSUE THREAD

**Issue by mywebhero** [freescout-helpdesk/freescout#2554]
I was attempting to instal a new server installation. However, it appears that the most recent version downloaded and installed contains a reference to example.com when it fetches the style sheet, causing the application to stop working.
<img width="1470" alt="Screenshot 2023-01-15 at 9 19 40 PM" src="https://user-images.githubusercontent.com/83342769/212543321-13e570c2-14e2-45a7-8e8d-f1d564bbbd37.png">
<img width="1274" alt="Screenshot 2023-01-15 at 9 16 31 PM" src="https://user-images.githubusercontent.com/83342769/212543342-e45ef967-f0da-414e-b046-4a104cea79dd.png">
<img width="902" alt="Screenshot 2023-01-15 at 9 16 22 PM" src="https://user-images.githubusercontent.com/83342769/212543354-708ade84-3fa3-467f-a721-74b4b6b3f9cf.png">

**Comment by freescout-helpdesk** [comment]
Something went wrong during installation. Set proper APP_URL in /.env file and clear cache.

**Comment by mywebhero** [comment]
You are correct! I forgot to change the URL, which caused the problem. I was overjoyed for a while when I discovered a bug, and it was me! Thank you for your prompt response on Sunday, which has greatly aided the overall operation. 

This community means a lot to me.
