### ISSUE TITLE
CC'd email addresses are duplicated when re-opening a draft

### ISSUE THREAD

**Issue by joseph-arun** [freescout-helpdesk/freescout#2555]
After saving a draft and re-opening the email to edit, the email addresses that are in the CC field are duplicated.

I am running version 1.8.48.

Please let me know if you need any logs or if you need me to troubleshoot anything.

Many thanks.

**Comment by avenjamin** [comment]
I'm able to reproduce this as well in 1.8.50

**Comment by avenjamin** [comment]
It looks like in the conversation view the reply form is hidden and already contains the CC'd recipients.
When the edit draft button is clicked it's pulling the CC'd recipients from the database and appending them to the CC field.

In ConversationController in the ajax function from line 1470 the switch case 'load_draft' is getting the CC'd recipients:
https://github.com/freescout-helpdesk/freescout/blob/6fba4d334b34edd594616e0fef0d22b2484c0911/app/Http/Controllers/ConversationsController.php#L1470

Then in the main.js script in the showReplyForm function from line 1442 the recipients are appended:
https://github.com/freescout-helpdesk/freescout/blob/6fba4d334b34edd594616e0fef0d22b2484c0911/public/js/main.js#L1442

I think if the showReplyForm function is supplied a data argument the fields should be cleared before adding data to them.

**Comment by freescout-helpdesk** [comment]
Could you please attach step-by-step instruction on how to reproduce it.

**Comment by avenjamin** [comment]
Sure.

1) Go to any conversation that has other recipients CC'd
2) Click on the reply button
3) Press the save draft button
4) Click on the edit button (you can also navigate away to a different folder and come back to the conversation or via the drafts folder and then press the edit button)
5) Notice the CC field now has the recipients duplicated.
