### ISSUE TITLE
Remove IMAP Message from server module

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2558]
I just want to clarify how the Remove IMAP Message from server module works.

When an email is fetched into FreeScout, and then removed from the IMAP server, I assume (never assume) that the email/conversation will still fully remain in FreeScout so that it is not lost?

Conversely (not related to module), what would happen if I deleted an email (that was already fetched) directly on the IMAP server? Does this affect anything in FreeScout? Does the conversations state change or get deleted/modified in any way?

Thanks

**Comment by freescout-helpdesk** [comment]
> the email/conversation will still fully remain in FreeScout so that it is not lost?

Yes.

When the email is moved/removed it does not affect fetched conversation in the FreeScout in any way.
