### ISSUE TITLE
Site breaks when updating Knowledge Base module.

### ISSUE THREAD

**Issue by mbtwr** [freescout-helpdesk/freescout#2559]
We have a custom URL: APP_URL defined in /var/www/html/freescout/.env.  When I update the knowledge base module past 1.35 the whole site breaks.  The URL of the site no longer re-writes to the APP_URL defined in the .env file and consequently most icons and functionality of the site breaks.  It does not create any app logs (laravel logs, web-server logs).  I assume this is a issue with the ability to now use a custom domainname added to the module.

We are not currently using the knowledge base module.  If I disable the module I can update it without breaking the site, but if I update the module while it is enabled, or enable the module after updating it the site breaks as described above.  

The site and all other modules are fully updated.

**Comment by freescout-helpdesk** [comment]
What happens to URL of broken icons? You can see URL in the browser console (Network tab).

**Comment by mbtwr** [comment]
PHP 8.0.27 (cli) (built: Jan 13 2023 10:42:52) ( NTS )

CORS errors on the icons and more:

Access to XMLHttpRequest at 'https://azuresite.net/polycast/connect' from origin 'https://hostname.private' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.





[TWR (Trans World Radio)]<http://www.twr.org/>

Matt Birnie
IT/IS
[https://www.twr.org/media/image/twr-phone-icon-cyan.png] +1.480.334.5897<tel:14803345897>
[https://www.twr.org/media/image/twr-globe-icon-cyan.png] twr.org<http://www.twr.org>

**Comment by freescout-helpdesk** [comment]
https://azuresite.net/polycast/connect
https://hostname.private/

Which one is your APP_URL? And where does another one come from?

**Comment by mbtwr** [comment]
https://hostname.private/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhostname.private%2F&data=05%7C01%7Cmbirnie%40twr.org%7C144c2db2542c4e2fb57508dafa055e8e%7C86fa1dc06d974ddab388bd951c3c490b%7C1%7C0%7C638097198237636692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qDOUPBdipPeTbDl%2Fc%2BQoRB0zYncibiCiLr1V0zjq0Yo%3D&reserved=0> is the hostname of the machine and the default URL.  We updated APP_URL in the .env file to be an Azure proxy connection with the new URL of https://azuresite.net/polycast/connect<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazuresite.net%2Fpolycast%2Fconnect&data=05%7C01%7Cmbirnie%40twr.org%7C144c2db2542c4e2fb57508dafa055e8e%7C86fa1dc06d974ddab388bd951c3c490b%7C1%7C0%7C638097198237636692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uK4O52WNnrwKUpcge1yse96H14kOOATQUaD5ZMiAF%2Fs%3D&reserved=0> and use it in production with that updated URL.

When we update the module, you can still connect to https://azuresite.net/polycast/connect<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazuresite.net%2Fpolycast%2Fconnect&data=05%7C01%7Cmbirnie%40twr.org%7C144c2db2542c4e2fb57508dafa055e8e%7C86fa1dc06d974ddab388bd951c3c490b%7C1%7C0%7C638097198237636692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uK4O52WNnrwKUpcge1yse96H14kOOATQUaD5ZMiAF%2Fs%3D&reserved=0> but the first time you change pages it re-writes the browser URL to https://hostname.private/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhostname.private%2F&data=05%7C01%7Cmbirnie%40twr.org%7C144c2db2542c4e2fb57508dafa055e8e%7C86fa1dc06d974ddab388bd951c3c490b%7C1%7C0%7C638097198237636692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qDOUPBdipPeTbDl%2Fc%2BQoRB0zYncibiCiLr1V0zjq0Yo%3D&reserved=0>.

Apparently the URL for many site elements still redirect too the APP_URL specification of https://azuresite.net/polycast/connect<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazuresite.net%2Fpolycast%2Fconnect&data=05%7C01%7Cmbirnie%40twr.org%7C144c2db2542c4e2fb57508dafa055e8e%7C86fa1dc06d974ddab388bd951c3c490b%7C1%7C0%7C638097198237636692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uK4O52WNnrwKUpcge1yse96H14kOOATQUaD5ZMiAF%2Fs%3D&reserved=0> and create CORS errors.



[TWR (Trans World Radio)]<http://www.twr.org/>

Matt Birnie
IT/IS
[https://www.twr.org/media/image/twr-phone-icon-cyan.png] +1.480.334.5897<tel:14803345897>
[https://www.twr.org/media/image/twr-globe-icon-cyan.png] twr.org<http://www.twr.org>

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. The configuration is quite weird. Try to fix it yourself or use https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer and send us updated code.
