### ISSUE TITLE
Error: imap_open() ... [CLOSED] IMAP connection broken (authenticate)

### ISSUE THREAD

**Issue by llunaCreixent** [freescout-helpdesk/freescout#2562]
Hello!
Since we installed Freescout in docker we are getting these errors in the Logs/Fetch errors every 1-2 hours. Is this normal? Do you know how I can fix it?
We get the emails with delay in general, and I think it's related to this.

```
Error: imap_open(): Couldn't open stream {mydomain.com:993/imap/ssl}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate); File: /www/html/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)
```

Thank you very much

**Comment by freescout-helpdesk** [comment]
Try to install `flock` utility and use the following in your cron:
```
* * * * * flock -n /tmp/cronlock.freescout php /var/www/html/artisan schedule:run >> /dev/null 2>&1 
```

Let us know if it helps.

**Comment by llunaCreixent** [comment]
In the cron inside the docker, or in the cron of the host system?

**Comment by freescout-helpdesk** [comment]
Inside the docker. `www-data` user should have this cron job: https://github.com/tiredofit/docker-freescout/blob/af68e6ce3b5a03f58a06faa22749b72122f84aff/install/etc/cont-init.d/30-freescout#L294

Try to change it.

**Comment by freescout-helpdesk** [comment]
How many mailboxes do you have?

**Comment by llunaCreixent** [comment]
We have 3 mailboxes

**Comment by llunaCreixent** [comment]
> Inside the docker.
> 
> `www-data` user should have this cron job: https://github.com/tiredofit/docker-freescout/blob/af68e6ce3b5a03f58a06faa22749b72122f84aff/install/etc/cont-init.d/30-freescout#L294 - Try to change it.

This line is in the crontab of `root`.

**Comment by llunaCreixent** [comment]
I've installed flock and changed the line in the `root`  crontab.
I've used `/www/html/artisan` instead of `/var/www/html/artisan`, since that's the value of `${NGINX_WEBROOT}`.
Let's see if the issue it's fixed.

**Comment by freescout-helpdesk** [comment]
Also try to install the latest version of FreeScout - it adds a small delay between IMAP connections.

**Comment by llunaCreixent** [comment]
I tried clearing cache and now the fetching doesn't even happen since then

**Comment by llunaCreixent** [comment]
How do I update to the last version in a running instance?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by llunaCreixent** [comment]
How do I update from the docker image?
https://hub.docker.com/r/tiredofit/freescout
