### ISSUE TITLE
Required User Fields to start Chat after KnowledgeBase-Widget not working

### ISSUE THREAD

**Issue by pf248** [freescout-helpdesk/freescout#2565]
Hello everyone,

we would like to integrate the live chat into our webiste. Before a customer can start a chat, he should have to put in his name and email. Using the normal "chat"-widget only, this functionality works fine. 

Now we came up with the idea to put the knowledge-base right before the "contact-us"/"start chat" and use it as a FAQ for our customers to reduce chat traffic. But now, when I press the button "contact us" on the KB-widget, the chat immediatly starts and the customers doesn't have to provide his name/email. Later, I tried to add the code snippet "require":["name","email"] from the chat-widget to the code of the kb-widget and yesterday it seemed to work out. But today, it doesn't anymore. 

How is the intended procedure on this? Is this behaviour intended? Or maybe can the KB / Chat Module be fixed/updated to use required fields correctly and in the same way?

Thanks in advance for any hint.

**Comment by freescout-helpdesk** [comment]
We'll check what can be done.

**Comment by freescout-helpdesk** [comment]
Fixed in Chat Module v1.0.21. Make sure to set "Require Visitor to Fill Out" option in Chat widget settings.

**Comment by pf248** [comment]
Thank you! So far so good. When I click on "Contact us" the "enter information"-Window pops up.
![1](https://user-images.githubusercontent.com/81617453/213136192-2cc07911-4a6b-424b-ada7-4fbf4d4d0a35.PNG)

But: Despite in my settings I set Email & Name to required, in the widget it displays "optional" and you can leave the field empty and continue. 
![2](https://user-images.githubusercontent.com/81617453/213136237-3bb45a32-c482-42dc-9179-26747ff99634.PNG)

**Comment by freescout-helpdesk** [comment]
Fixed in Chat Module v1.0.22
