### ISSUE TITLE
Microsoft OATH Connection

### ISSUE THREAD

**Issue by justinipg** [freescout-helpdesk/freescout#2567]
i'm getting an error from Microsoft saying the following.

AADSTS50011: The redirect URI 'https://servicedesk.xxx.net.au/mailbox/oauth' specified in the request does not match the redirect URIs configured for the application '288c5f41-5671-4726-9ece-XXXXXX'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

when i go to the /mailbox/oath address all i receive is a "Sorry, the page you are looking for could not be found"

**Comment by freescout-helpdesk** [comment]
Update FreeScout and modules to their latest versions. Make sure to follow this instruction: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth

There is nothing else we can do here.
