### ISSUE TITLE
Can't access System Tab

### ISSUE THREAD

**Issue by edellingham** [freescout-helpdesk/freescout#257]
I haven't gotten too far to know if there are other underlying issues, but I've tried installing twice just for good measure (and to make sure I didn't screw up the first time) and I can never access the System Tab.  Everything else works, as far as other tabs, creating mailboxes, etc..

The error I get in the log is:  symlink(): No such file or directory {"userId":1,"email":"user@domain.net","exception":"[object] (ErrorException(code: 0): symlink(): No such file or directory at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:228)

I think I followed the instructions pretty well, installed it on Ubuntu 16.04, but no dice with this issue.

**Comment by freescout-helpdesk** [comment]
Have you tried to follow Troubleshooting instructions https://github.com/freescout- helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by freescout-helpdesk** [comment]
Closing for now activity.
