### ISSUE TITLE
OAuth Authentication against Authelia does not work

### ISSUE THREAD

**Issue by rustymunkey** [freescout-helpdesk/freescout#2571]
We recently switched our OAuth authentication provider from [Dex](https://dexidp.io) to [Authelia](https://www.authelia.com). However, when we updated the URLs in the OAuth Module, we received errors  after clicking the "Sign In With Oauth" button on the login page.

The error message in the logs are: 
```
Jan 16, 10:00:21    DEBUG - OAuth token URL response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
Jan 16, 10:00:21    DEBUG - OAuth callback triggered: {"error":"invalid_state","error_description":"The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.","state":null}
```

We digged into the OAuth Module and found two issues which cause the problems:

 - The `scope` sent as URL parameter is not URL encoded. It is transmitted as `openid email profile` instead of `openid%20email%20profile` 
 -  There is no `state` parameter sent with the request. While technically this parameter is optional [according to the specs](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), it seems that Authelia still requires it.

We temporarily fixed both issues by patching the code. After that we were able to authenticate against Authelia and also against Dex, so it seems the changes do not break compatibility with Dex.

It seems that Dex is more relaxed with these parameters, but Authelia is not.

**Comment by freescout-helpdesk** [comment]
Thanks for the info. Feel free to send updated file: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules
We'll check it and release if it works fine.

**Comment by freescout-helpdesk** [comment]
Added in OAuth & Social Login Module v1.0.4
