### ISSUE TITLE
Empty messages with undefined attachments (e-mail is not parsed correctly)

### ISSUE THREAD

**Issue by pathab** [freescout-helpdesk/freescout#2572]
When we receive emails from Gmail, they are sometimes not parsed correctly. It results in empty messages with two undefined attachments.

One undefined attachment contains an html code of the message without html or body tag. The second undefined attachment contains the message as text.

The messages are displayed correctly in other email clients. I suspect Freescout has problems if the message only contains the content of the body tag.

I am currently trying to reproduce the problem, but still without success. can you please help?
![2023-01-18_11-01](https://user-images.githubusercontent.com/9745922/213148710-363d50e2-564d-46b4-b4da-b93fd77c2fc0.png)

**Comment by freescout-helpdesk** [comment]
Are you using MS365 with OAuth IMAP authentication?

**Comment by pathab** [comment]
> Are you using MS365 with OAuth IMAP authentication?

Yes

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/issues/1972#issuecomment-1385554715

**Comment by pathab** [comment]
> See [#1972 (comment)](https://github.com/freescout-helpdesk/freescout/issues/1972#issuecomment-1385554715)

Sorry, didn't see that this error was already being dealt with. Thanks for the link, this solved the problem for me.
