### ISSUE TITLE
Customer tags field

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2573]
In our organisation we have beside our users (employees) to other groups: Customers and partners. We get a lot of information or inquiries to customers from partners for example.
In a first step I would like to mark and group all partners which are "customers" in FreeScout. In a second one it would be nice to show this in a conversation.
Unfortunately the tag module seems to work only for conversations, not for administrating customers or am I wrong?

**Comment by freescout-helpdesk** [comment]
Try Customer Fields from https://freescout.net/module/crm/

**Comment by mokkin** [comment]
I tried, but I didn't find a possibility to add something like tags there. And the tags module seems to work only for communications, not for customers.
In my point of view it should be possible to attach various tags to a customer such as "customer" itself, "partner", "vip", "foo", "bar" and so on ...

**Comment by freescout-helpdesk** [comment]
You can vote here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/335595

**Comment by freescout-helpdesk** [comment]
Multiselect customer field type added in CRM Module v1.0.27

**Comment by mokkin** [comment]
Great to hear - thanks @freescout-helpdesk
