### ISSUE TITLE
re-download attachments

### ISSUE THREAD

**Issue by e-rwan** [freescout-helpdesk/freescout#2574]
hello,
I tried changing the freescout app url from mydomaincom/freescout to freescout.mydomain.com for some reasons(freescout keep trying to get the manifest from mydomain.com rather than the freescout folder), I kinda messed up and freescout became non fonctional for a few hours.
I suspect some tasks(like maybe attachments-cleanup?) ran during this time and after I got freeescout back and working all attachments from before the app url change had disapeared, deleted from the server.
Attachments from mail received after the change where present.

so my question, is there a way to force freescout to re-download attachments?

thanks
erwan.

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible.

**Comment by e-rwan** [comment]
ok thanks for the answer.
now, what if I make a temporary freescout install on a local server, download all past messages and then merge the new _attachment_ folder with the one on the original freescout install?
Will attachments be placed in the same folders as previously? if not I could make a php command that compare attachments path on server and change the file_dir key in attachments table accordingly, could that be source of any problem in the future?
anyway that solution won't get sent atachments back.
I discovered this issue a bit late and got no backup old enough to resolve the issue..

**Comment by freescout-helpdesk** [comment]
> Will attachments be placed in the same folders as previously?

Not necessarily. 

> if not I could make a php command that compare attachments path on server and change the file_dir key in attachments table accordingly, could that be source of any problem in the future?

No.

**Comment by e-rwan** [comment]
ok thanks I'll do that then.
