### ISSUE TITLE
Bug: Answer from customer between lines cut off the message in FreeScout

### ISSUE THREAD

**Issue by chriscorns** [freescout-helpdesk/freescout#2578]
If a customer writes his answer between lines of the support message, the answer message is cut of in FreesSout.
I use the latest version of FreeScout v.1.8.51 on an Debian server with nginx/1.14.2 and PHP 8.1.14.

Here is an example.

Customer mail answer
----
Dear Supporter,
thank you for the answer.
> Am 16.01.2023 um 11:29 schrieb Supporter:
> Dear Customer,
>
> text text text text
> .......
>
exactly, bla bla bla between answer lines ....
> text text text text
> text text text text
> text text text text
>
bla bla bla between answer lines.
> 	
> text text text text
> text text text text
> text text text text
>
>  {#FS:NNNNNNNN#}
>
Kind regards
Customer
XXXXXXXX

Backend view
----
Then, in backend of FreeScout are only the first lines of customer answer to see:

----

(CUSTOMER)
Dear Supporter,
thank you for the answer.

-----

**Comment by freescout-helpdesk** [comment]
[Unfor](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-a-customer-replies-within-the-cited-text-freescout-does-not-show-it)
