### ISSUE TITLE
Error with newly created users

### ISSUE THREAD

**Issue by S0mething4m3** [freescout-helpdesk/freescout#2580]
I emailed supports@freescout.com but didnt get a reply.

I just created 3 users but when they log in they get the following error screen: see attached log
 
![freescout-error](https://user-images.githubusercontent.com/54159614/213291195-68cfae1e-6692-4195-b5fc-aca6d402d596.png)

[log.txt](https://github.com/freescout-helpdesk/freescout/files/10450979/log.txt)

When i disable the following 2 modules Global Mailbox and Two-Factor Authentication i am able to log in with these users.

**Comment by freescout-helpdesk** [comment]
We'll check it.

**Comment by freescout-helpdesk** [comment]
Make sure to install the latest versions of FreeScout and modules.

**Comment by S0mething4m3** [comment]
We are using the latest as of 9:36am EST 01-19-23

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue with the latest versions of FreeScout and modules.
