### ISSUE TITLE
Unable to utilize composer install command without adding folder in natxet/cssmin

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#2583]
## Summary
Can not perform an install from source using composer install.

## Detail

I am trying to build for 1.8.51 the Docker images under PHP 7.4, 8.0, 8.1, and 8.2 but they are all failing at the composer install step.

Command executed 

````
tiredofit/freescout 22:50:49 /assets/install] $ composer install --ignore-platform-reqs
Cannot load Zend OPcache - it was already loaded
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 36 installs, 0 updates, 0 removals
...
  - Installing phpunit/phpunit (6.5.8): Extracting archive
Package anahkiasen/underscore-php is abandoned, you should avoid using it. No replacement was suggested.
Package chumper/zipper is abandoned, you should avoid using it. No replacement was suggested.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files

In ClassMapGenerator.php line 129:
                                                                                                                                 
  Could not scan for classes inside "/assets/install/vendor/natxet/cssmin/src/" which does not appear to be a file nor a folder  
                                                                                                                                 
install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
````

All I see in that folder is a README:
````
[tiredofit/freescout 22:56:56 /assets/install/vendor/natxet/cssmin] $ ls -l
total 4
-rw-r--r--    1 root     root           162 Jan 18 22:49 README
[tiredofit/freescout 22:56:57 /assets/install/vendor/natxet/cssmin] $ cat README 
This is just a copy of the CssMin by Joe Scylla to format it for Composer.
Composer: http://packagist.org/about-composer
CssMin: http://code.google.com/p/cssmin/
[tiredofit/freescout 22:56:58 /assets/install/vendor/natxet/cssmin] $ 
````

Do I need to be putting a binary in there? I can make the install complete when creating a blank `src` folder, but unsure if I am going to need anything else. 

Just checking in and don't want to blow up some installs.

**Comment by freescout-helpdesk** [comment]
Strange. For us it works just fine (composer version 2.5.1). There should be no .php files in `vendor/natxet/cssmin/src/`. The file from there moved to `overrides/natxet/cssmin/src/`.

**Comment by freescout-helpdesk** [comment]
Maybe you don't even need to do `composer install --ignore-platform-reqs` as each release's zip / tar.gz already contains all the vendor files?

**Comment by tiredofit** [comment]
I'm pulling from master rather than dist to allow for builds for the image outside of releases/tags for testing which is why I need to build. 

Has anything changed in your dist process? 

I looked a bit more at the composer package and it seems to be just a php file that needs to get injected. I can certainly build the workaround, just surprised that bringing in this composer package is causing the breakage. I'll check back in 24 hours, I'm supposed to be on holidays :P

**Comment by freescout-helpdesk** [comment]
> Has anything changed in your dist process?

No.

We've just cloned `master` branch into a new folder and `composer install --ignore-platform-reqs` worked fine. There is an empty `src` folder inside `vendor/natxet/cssmin`.

**Comment by freescout-helpdesk** [comment]
The `composer.json` has an instruction https://github.com/freescout-helpdesk/freescout/blob/dist/composer.json#L280 which deletes from /vendor files listed in "exclude-from-classmap" section of composer.json.

The "vendor/natxet/cssmin/src/CssMin.php" is listed there now. So maybe your system by some reason deletes also `src` folder from `/vendor/natxet/cssmin` when it becomes empty after deleting "vendor/natxet/cssmin/src/CssMin.php" file.

**Comment by freescout-helpdesk** [comment]
We've published a new release 1.8.52 with an addition in composer.json making sure that `vendor/natxet/cssmin/src` folder exists: https://github.com/freescout-helpdesk/freescout/blob/dist/composer.json#L285

**Comment by tiredofit** [comment]
Strange - Still didn't work with the fixes that we re added. However if I add my own folder with the same permissions the install completes. I'm going to just leave it in there for now and see if it sorts out over time. This should be good enough.

**Comment by freescout-helpdesk** [comment]
Ok. We'll remove an instruction creating `vendor/natxet/cssmin/src` folder from composer.json

**Comment by below43** [comment]
I'm building via Azure devops, and encountered this issue.

The mini patch from Jan 20 didn't work as it needed the dir there before the build.

Adding the following to composer.json fixed the issue for me:

```
        "pre-install-cmd": [
            "@php -r \"@mkdir('vendor/natxet/cssmin/src', 775);\""
        ],
```

![image](https://user-images.githubusercontent.com/10964995/225148139-e06d3502-a597-4824-b621-194eaf622c22.png)

**Comment by freescout-helpdesk** [comment]
We've added this instruction in the `master` branch.
