### ISSUE TITLE
Satisifcation rating now showing up

### ISSUE THREAD

**Issue by minghuiyu** [freescout-helpdesk/freescout#2584]
Satisifcation ratings module enabled, using the default configurations in mailbox setup, but it doesn't show up in reply emails.

**Comment by freescout-helpdesk** [comment]
_Rating is not sent in the first email sent by user_
https://freescout.net/wp-admin/post.php?post=1631&action=edit

**Comment by minghuiyu** [comment]
I tested: replied to user emails, not showing up in my replies

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Can you send screenshot of the ratings settings.

**Comment by minghuiyu** [comment]
Here are screenshots:

- Settings
- Reply snippet from FS mailbox
- (Received) reply snippet in Gmail

Thanks.

![image](https://user-images.githubusercontent.com/8637057/213392485-36010564-e73f-4760-936a-3d1f534caf43.png)

![image](https://user-images.githubusercontent.com/8637057/213392526-82f49524-69d5-43fa-983b-99b1a27a9544.png)

![image](https://user-images.githubusercontent.com/8637057/213392573-aa450644-082a-4462-bbd0-90d1f632039f.png)

**Comment by freescout-helpdesk** [comment]
It looks like it need to be debugged on your server (email at support@freescout.net if you can provide an access) or try to find some assistant: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by minghuiyu** [comment]
Email sent to [support@freescout.net](mailto:support@freescout.net). Thanks.

**Comment by minghuiyu** [comment]
This module appears having some issue.

No ratings show up in email
![image](https://user-images.githubusercontent.com/8637057/216224901-06de841d-7c10-4ee0-8820-4767674f592c.png)

In email preview mode, some random chars show up
![image](https://user-images.githubusercontent.com/8637057/216225128-f47f4211-501a-4467-982f-eacc404443b7.png)

In email source view, here it is:
![image](https://user-images.githubusercontent.com/8637057/216225378-dbabf9b9-8d8a-428a-8ee1-d84c8c9fbca4.png)

Manually added a test message to the blade, not showing up either
![image](https://user-images.githubusercontent.com/8637057/216225812-44fd25ff-4c08-47db-85d9-28b66a48becf.png)

I don't have a debug tool now. But it appears this module was not rendered at all.

**Comment by minghuiyu** [comment]
How to debug this issue?
