### ISSUE TITLE
Custom Module idea - need feedback

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#2585]
Hey there, last weekend I created my first custom module and it works. Thx for the possibility to enhance FreeScout.
I have a another idea for a custom module and I would kindly ask for feedback.

I would like to build a module, which adds the action to workflows to send an API call. If the workflow is triggered an external API is called. Kind of Webhooks.

External APIs have the possibility to block the current PHP process. Would you recommend, that the workflow adds a Job to the queue to call the API or would you call the API directly when the workflow is running? Do you have any recommendation here?

**Comment by freescout-helpdesk** [comment]
User \Helper::backgroundAction() function to create a background job: https://github.com/freescout-helpdesk/freescout/blob/b39cbe74028699e26f5f93dbc331368105a2beae/app/Listeners/SendReplyToCustomer.php#L52

**Comment by obstschale** [comment]
Nice. That makes sense. Thank you for your help.
