### ISSUE TITLE
Customer Fields URl Placeholders Not Working

### ISSUE THREAD

**Issue by TheMoodBoardz** [freescout-helpdesk/freescout#2586]
Hello,

We have two systems for our staff & to make it easier to find them in our other system we want to deploy quick links.

We have one Customer Field that holds the data (the staffs ID number) [AssetID] and another Customer Field [Asset Portal Profile] which uses the previous Customer Field (the staffs ID number) as a URL Placeholder...

However we cant seem to get it to work...
We are using the default {%cf_CUSTOMER_FIELD_ID%} URL placeholder with the [Names] & IDs however it does not want to generate the URL as expected.

Any ideas or are we interpreting this feature incorrectly?

**Comment by freescout-helpdesk** [comment]
Please attach screenshots of customer fields settings.

**Comment by TheMoodBoardz** [comment]
I Believe I have fixed it since posting however here it is:
![Screenshot 2023-01-20 063346](https://user-images.githubusercontent.com/59126098/213632778-2728c4e5-dd71-49f5-80bf-84da208746c2.png)

**Comment by freescout-helpdesk** [comment]
Ok. Good to know.
