### ISSUE TITLE
Mention/Reference another Ticket

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2587]
I wanted to know if there is a way to mention or reference another ticket when replying to a client or adding a note in a ticket,

for example:
in ticket # 1234 I want to reference a conversation from ticket # 1111 with a link or something that the client can click on to see it.

not necessarily a certain reply within the other conversation, though that would be great, But at least another ticket in general

Thanks!!!

**Comment by SecureCPU** [comment]
Similar to something like here in github, if I type in this message #1972 it automatically reference the github ticker 1972

**Comment by freescout-helpdesk** [comment]
Unfortunately not possible for now. Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by SecureCPU** [comment]
So this was already requested as says completed... but not the way i mentioned above.
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/372655
The feature seems to be available in the checklists module, but can't be linked within the ticket message or note itself.

But it looks like in the request someone posted a link to the exact module i mentioned above that was created and sold by freescout.shop:
https://freescout.shop/downloads/freescout-module-references/

Hope this helps anyone who's looking.

**Comment by SecureCPU** [comment]
> So this was already requested as says completed... but not the way i mentioned above. https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/372655 The feature seems to be available in the checklists module, but can't be linked within the ticket message or note itself.
> 
> But it looks like in the request someone posted a link to the exact module i mentioned above that was created and sold by freescout.shop: https://freescout.shop/downloads/freescout-module-references/
> 
> Hope this helps anyone who's looking.

I tried installing this reference module, but freescout basically stopped functioning once it was activated. looked like it broke a bunch of buttons and links.
I reached out to them to see if they can look into it.

otherwise, would this be a module you guys would be able to create?

**Comment by freescout-helpdesk** [comment]
> otherwise, would this be a module you guys would be able to create?


Yes. Maybe in the future.

**Comment by SecureCPU** [comment]
It actually ended working. There was just a missing file in the version I downloaded.
Reached out to them, they provided the fixed module and it's working perfectly.
