### ISSUE TITLE
Sending email best option

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2588]
Hi Freescout community,

i am with Microsoft exchange, in order to fetch emails i am using the below documentation and works great, see attached screenshot 
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth.
![image](https://user-images.githubusercontent.com/13112801/213512956-56b9b718-03a2-4716-afe1-f0da796bfc63.png)

However for sending emails i am using good old app password and plain username,
i have a feeling that is not the correct method and Microsoft does not like basic authentication 

looking forward to hearing everyone else setup

**Comment by freescout-helpdesk** [comment]
So SMTP is not working for you. Here is the instruction: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#sending-emails

**Comment by SecureCPU** [comment]
I'm setup up similarly.

Use the same setup as you for fetching email.

For sending, I have 2fa set to enforce, Security defaults disabled, and created an app password for Freescout. As far as I know, that's the standard way.

**Comment by sainiaj** [comment]
> So SMTP is not working for you? Here is the instruction: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#sending-emails

thank you for reading my question thoroughly and replying with the same link i posted in the question already -_-

**Comment by minghuiyu** [comment]
I highly suggest using a dedicated SMTP service provider, such as sendgrid, smtp2go, etc.
