### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by MartinH0** [freescout-helpdesk/freescout#259]
Somehow SMTP is not working and always gives me this error:

> SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'status_message' at row 1

This is just happening in "Connection Settings" > "Sending Mails", NOT in "Settings" > "Mail Settings"
I already tried twice a clean fresh install but its not working..

I'm using:
Debian 9.8
Plesk 17.8.11
Apache + nginX
PHP 7.0 - 7.3

Same SMTP Config works in other programs with phpmailer

**Comment by freescout-helpdesk** [comment]
Error message should be trancated before saving to DB.
