### ISSUE TITLE
Link to View Conversation Online

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2590]
I wanted to know if there was a way to add a link to all the emails sent that allows them to view the conversation online?

On the bottom of the message there would be something link:

`To view this Message Online, Please click here` or something like that. and when they click it, they can see the conversation or reply online in the browser and maybe even be able to reply online.

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible yet. Feel free to submit a feature request: https://freescout.net/request-feature/
