### ISSUE TITLE
TLS/SSL failure

### ISSUE THREAD

**Issue by advoenkin** [freescout-helpdesk/freescout#2591]
Hello, i have a problem with email fetching. 

I got error: imap_open(): Couldn't open stream {ran-crypto.tech:143/imap/novalidate-cert}. TLS/SSL failure for ran-crypto.tech: SSL negotiation failed

My mail server user STARTTLS encryption.

**Comment by freescout-helpdesk** [comment]
Try to change TLS to SSL or vice versa: https://stackoverflow.com/a/72376387

**Comment by advoenkin** [comment]
> Try to change TLS to SSL or vice versa: https://stackoverflow.com/a/72376387

I tried all variations, and even None including. It did not help.

**Comment by freescout-helpdesk** [comment]
Try the following and let us know the results:
1. Update FreeScout to the latest version.
2. Extract Mail.php from the [archive](https://github.com/freescout-helpdesk/freescout/files/10464029/Mail.zip) and copy to /app/Misc replacing existing Mail.php
3. Check IMAP connection.

**Comment by freescout-helpdesk** [comment]
Closing for no activlity.

**Comment by freescout-helpdesk** [comment]
Solution: 

Add the following to `.env` file and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache):
```
APP_NEW_FETCHING_LIBRARY=true
```

**Comment by dwishaventures** [comment]
I am running   Freescount behind traefik proxy. Outgoing email works using SMTP with SSL but incoming mail wont work. Connection failure. Whatever suggested here is already tried. How to troubleshoot ? or where should I start looking for problem.
