### ISSUE TITLE
No style after the migration to a new server

### ISSUE THREAD

**Issue by securityopa** [freescout-helpdesk/freescout#2593]
* If you have some error the first thing you should do is to check "Manage » Logs » App Logs"! If there are any errors there - make sure to provide them in the issue.
* Have you read FAQ? https://github.com/freescout-helpdesk/freescout/wiki/FAQ
* If you have "Whoops something went wrong" error see: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
* Feature requests for modules should be posted here: https://freescout.net/request-feature/
* Docker questions should go here: https://github.com/tiredofit/docker-freescout/issues
* Create separate issues for different topics - no need to mix all your problems into one issue.
* Questions on issues with payments for modules should be sent by email: https://freescout.net/contact-us/
* Mentioning how much you've spent on modules is the way to being banned.

Still here? Well clean this out and go ahead :)

**Comment by alichakery** [comment]
Hello,

Today I migrated my freescout installation from our old server to a new one.

Both have the same PHP (7.4) and after the migration I cleared the cache using the /tools.php.

But still my website has no sytle and impossible to work with.

I would appreciate your prompt help...

**Comment by alichakery** [comment]
Here is how my freescout looks like
![Screenshot from 2023-01-20 00-29-47](https://user-images.githubusercontent.com/12240218/213585248-dc72f5f6-1235-4863-bde5-74fe9ac1bc5f.png)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working
