### ISSUE TITLE
G Suite IMAP Error

### ISSUE THREAD

**Issue by DrMxrcy** [freescout-helpdesk/freescout#2594]
Hello! I am trying to connect a Gsuite Account and getting this error

```Jan 20, 06:56:02 | Error fetching email | Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Retrying PLAIN authentication after [ALERT] Please log in via your web browser: https://support.google.com/mail/acco; Retrying PLAIN authentication after [ALERT] Please log in via your web browser: https://support.google.com/mail/acco; Can not authenticate to IMAP server: [ALERT] Please log in via your web browser: https://support.google.com/mail/acco; File: /www/html/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)```

- Enabled IMAP in the Admin Console and User Gmail
-Activated 2FA and used an App Password
-Made sure SSL was selected.

**Comment by freescout-helpdesk** [comment]
This must be some G Suite's new "feature". There was another similar report on not being able to connect to G Suite via IMAP. Have you tried to contact G Suite support?

**Comment by DrMxrcy** [comment]
I can contact support to see.

**Comment by freescout-helpdesk** [comment]
We've just checked one G Suite account - it's able to connect by IMAP using App Password. So apparently just some G Suite accounts are affected by this "feature".

**Comment by freescout-helpdesk** [comment]
Also try [this solution](https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#possible-issues) although it may not work:

> Allow Unknown device at https://myaccount.google.com/u/1/device-activity
> 
> You may also need to do Google's "Captcha Unlock" (https://accounts.google.com/DisplayUnlockCaptcha) to unblock FreeScout from Gmail if you are getting this error.

**Comment by DrMxrcy** [comment]
I will contact support, I tried both with no luck

**Comment by DrMxrcy** [comment]
Seems looks like, according to Google a new account error. Going to give it 24 Hours. My Longer Active Account worked.

**Comment by freescout-helpdesk** [comment]
OK
