### ISSUE TITLE
VPS Recommendations and why ?

### ISSUE THREAD

**Issue by aj-saini** [freescout-helpdesk/freescout#2595]
Just wondering which VPS are you guys using and why

I tried the following and did not have much luck

Aws lightanail - kept hitting 20% CPU alarm currently on quad core cpu 
Tried ionos contobo and self hosted proxmox - keep getting all sorts of error after week of troubleshooting I gave up

So I am wondering where are you guys running freescout, below are recommendations by freescout. Some of them offer unlimited nvme storage and 30 days backup which sounds to good to be true honestly, how good are these server are feel free to recommenced the one you prefer?

[Kualo](https://www.kualo.com/webhosting/freescout-hosting) ($8.99/mo)
[KnownHost](https://www.knownhost.com/freescout-hosting.html) ($6.71/mo)
[A2 HOSTING](https://www.a2hosting.com/freescout-hosting) ($6.99/mo)
[InterServer](https://www.interserver.net/apps/freescout-hosting.html) ($5.00/mo

**Comment by minghuiyu** [comment]
DigitalOcean is very good.

Take advantage of its managed database offering, so you don't need to worry about MySQL too much, and can focus on the web server.

Here is the link. https://m.do.co/c/4b74cfebe9f1 (disclaimer: my referral link)
$200 credit, good for 60 days.

**Comment by freescout-helpdesk** [comment]
Shared hosting on DreamHost also would work fine.

**Comment by JSM25** [comment]
That's interesting DreamHost is not on the list (https://github.com/freescout-helpdesk/freescout/wiki/Cloud-Hosted-FreeScout)  can I ask you what sort of hosting you have shared or VPS.

John

**Comment by freescout-helpdesk** [comment]
This https://github.com/freescout-helpdesk/freescout/wiki/Cloud-Hosted-FreeScout is the list of hosting providing FreeScout One Click Install.

FreeScout works fine on DreamHost, but they don't provide FreeScout One Click Install.
