### ISSUE TITLE
2 commands were running at the same time. Commands have been restarted (work flows do not work/run)

### ISSUE THREAD

**Issue by S0mething4m3** [freescout-helpdesk/freescout#2601]
Hi,
We cannot get our workflow automations to work. The only thing i notice is this error 
[fetch-emails.log](https://github.com/freescout-helpdesk/freescout/files/10470053/fetch-emails.log)
[queue-jobs.log](https://github.com/freescout-helpdesk/freescout/files/10470054/queue-jobs.log)

in system:

2 commands were running at the same time. Commands have been restarted
or
Last run: ? Last successful run: ? Try to [clear cache](/system/tools) to force command to start.

i found a previous issue on this something but not sure how is related to my problem. I dont see any errors regarding IMAP.
https://github.com/freescout-helpdesk/freescout/issues/1696

I dont see any errors in the log files. Please help.
![workflow-3](https://user-images.githubusercontent.com/54159614/213800743-5b5419e0-15df-4319-bd87-163becca9a89.png)
![workflow-2](https://user-images.githubusercontent.com/54159614/213800745-8e275ecb-c421-4880-9cd2-d57856777e39.png)
![workflow-1](https://user-images.githubusercontent.com/54159614/213800747-426602ff-3232-4dcb-a537-3a62056d334c.png)

**Comment by S0mething4m3** [comment]
![workflow-5](https://user-images.githubusercontent.com/54159614/213802583-e9b1bd52-f8f0-4c78-a1d8-7f2b7fab0c7f.png)
![workflow-4](https://user-images.githubusercontent.com/54159614/213802584-4f248029-4c7d-40ff-8070-fe14697fde4d.png)

**Comment by S0mething4m3** [comment]
![Uploading workflow-6.png…]()

**Comment by S0mething4m3** [comment]
![workflow-7](https://user-images.githubusercontent.com/54159614/213808266-9c3b745d-0303-48fd-aff4-6d1571e443aa.png)

**Comment by S0mething4m3** [comment]
![workflow-8](https://user-images.githubusercontent.com/54159614/213808441-6a67baa0-3672-412f-844b-c130d66924bd.png)

**Comment by S0mething4m3** [comment]
![workflow-9](https://user-images.githubusercontent.com/54159614/213872707-4fc52b02-86ea-4120-9f5d-e4148c0b5938.png)

**Comment by freescout-helpdesk** [comment]
Your FreeScout version?

**Comment by S0mething4m3** [comment]
Its shown in the pictures above:
1.8.52 
(latest)

**Comment by freescout-helpdesk** [comment]
Are you using docker or Cloudron?

**Comment by S0mething4m3** [comment]
Neither

**Comment by freescout-helpdesk** [comment]
If you can give access to your FreeScout  to check feel free to message at support@freescout.net

**Comment by S0mething4m3** [comment]
is it possible to give me instructions what to check and i can post here? Since you don't have a sandbox or development option there is a security and privacy concern giving access to our live emails.

**Comment by S0mething4m3** [comment]
?

**Comment by S0mething4m3** [comment]
Why was this issued closed? I installed via [Softaculous](http://www.softaculous.com/apps/customersupport/FreeScout)
