### ISSUE TITLE
API: Prevent user notifications when creating a conversation

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2602]
Hello,

_This is probably a question in order to make some custom changes to the API module. But it would be nice if FreeScout team implements this._

Is there a possibility to prevent FreeScout to send any user notifications (new conversation, assigned notification) in case it is created via API? 

Use case: conversations are created automatically in a bulk to notify customers about maintenance, etc. "Import" option would not work in the case because customer notifications are mandatory.

Would be nice to have some API option.

**Comment by freescout-helpdesk** [comment]
Use `"imported": false`

**Comment by ilyakonovalenko** [comment]
This will not send email to customer. Is it not? We need to send normal emails to customers, but just avoid agent emails.

**Comment by freescout-helpdesk** [comment]
Yes, this will not send any emails to customers or support agents.

**Comment by ilyakonovalenko** [comment]
Well... 🤔 My initial message was to find out if there is a way to only send emails to customers, but not to agents

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. There is no plans to add this feature for now.
