### ISSUE TITLE
User notification of New Conversation on a per mailbox basis?

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2603]
I have some users that have access to more than one mailbox.

On one of the mailboxes they are the primary user that needs to get notification of a New Conversation.

But on another mailbox they are not the primary user so they only need to get notification when a Conversation is Assigned to them.

Is it possible to set their notifications preferences on a per mailbox basis? Right now I only see the users Notification preferences but it seems to be global, so they will notification of all new conversations for all mailboxes they have access too.

Thanks

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible.

**Comment by jshrek** [comment]
Can I make this a FEATURE REQUEST please?

**Comment by freescout-helpdesk** [comment]
Feel free to submit here: https://freescout.net/request-feature/
