### ISSUE TITLE
Get errors after system update failure.

### ISSUE THREAD

**Issue by watarutmnh** [freescout-helpdesk/freescout#2606]
I met below error when trying to update the system.
> Call to undefined method App\Misc\Helper::isInstalled() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Misc\\Helper::isInstalled() at /home/xxx/xxx.com/app/Console/Commands/ClearCache.php:58)`

After update failure, I get several errors.

When trying to access Manage > System:
> foreach() argument must be of type array|object, null given {"userId":1,"email":"xxx@xxx.com","exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, null given at /home/xxx/xxx.com/app/Http/Controllers/SystemController.php:34)

When trying send test at "Connection Settings" of the mailbox, it alerts:
> Error occured. Please check your internet connection and try again.

And error at App Logs:
> Call to undefined method App\Misc\Mail::prepareMailable() {"userId":1,"email":"xxx@xxx.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Misc\\Mail::prepareMailable() at /home/xxx/xxx.com/app/Mail/Test.php:26)

When I trying to access Edit  Mailbox:
> Call to undefined method Watson\Rememberable\Query\Builder::isDummyPassword() (View: /home/xxx/xxx.com/resources/views/mailboxes/update.blade.php) {"userId":1,"email":"xxx@xxx.com","exception":"[object] (ErrorException(code: 0): Call to undefined method Watson\\Rememberable\\Query\\Builder::isDummyPassword() (View: /home/xxx/xxx.com/resources/views/mailboxes/update.blade.php) at /home/xxx/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2483, BadMethodCallException(code: 0): Call to undefined method Watson\\Rememberable\\Query\\Builder::isDummyPassword() at /home/xxx/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2483)

I put "xxx" instead to provide personal data.

**Comment by freescout-helpdesk** [comment]
Follow https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout and use some other update method.

**Comment by watarutmnh** [comment]
I updated via git command and it run without a error. 
But the errors above occur still when accessing "Manage > System", "Edit Mailbox" and the sending test of "Connection Settings".

**Comment by freescout-helpdesk** [comment]
Use some other update method.
