### ISSUE TITLE
Knowledge Base Module

### ISSUE THREAD

**Issue by ubivaka** [freescout-helpdesk/freescout#2607]
Knowledge Base Module How to make it visible to all agents. One knowledge base for everyone

**Comment by ubivaka** [comment]
![image](https://user-images.githubusercontent.com/123378437/214049232-e3599874-fece-46fb-a883-d071013bd411.png)
if the user does not have the right "Agents are allowed to edit the knowledge base", the knowledge base is not displayed at all. how to make one common knowledge base visible to all agents?

**Comment by freescout-helpdesk** [comment]
Do you want to allow all users edit Knowledge Base settings, categories and articles?

**Comment by ubivaka** [comment]
we want the knowledge base to be the same for all agents.  one common to all.  now everyone has their own
--
Отправлено из Mail.ru для Android вторник, 24 января 2023г., 11:36 +03:00 от FreeScout  ***@***.*** :

**Comment by freescout-helpdesk** [comment]
Each mailbox has it's own Knowledge Base. Unfortunately there is no plans to allow one Knowledge Base for all mailboxes.

**Comment by ubivaka** [comment]
on our own, can we correct some kind of setting so that it becomes a single one?
--
Отправлено из Mail.ru для Android вторник, 24 января 2023г., 11:46 +03:00 от FreeScout  ***@***.*** :
