### ISSUE TITLE
The SHOW ORIGINAL button can show reply notes

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2608]
Here is the conversation in Gmail:

<img width="1281" alt="Screenshot 2023-01-23 at 09 55 43" src="https://user-images.githubusercontent.com/382183/214072309-2bceeb5f-746a-4877-9ac2-2cd0265f8869.png">

And here is how it loads in FreeScout:

<img width="1281" alt="Screenshot 2023-01-23 at 09 55 47" src="https://user-images.githubusercontent.com/382183/214072640-acdc47e5-d79f-4348-837a-6f5b815911bf.png">

This is FINE and I understand and appreciate that Scout is cutting off the context.

However the next screenshot is the problem:

<img width="1281" alt="Screenshot 2023-01-23 at 09 56 09" src="https://user-images.githubusercontent.com/382183/214072892-4f569bc3-1410-4b9c-823b-28f95e7797eb.png">

In FreeScout when I click the disclosure triangle next to that thread and then I click SHOW ORIGINAL this original message is clipped. Instead I was hoping the original message would be shown in full fidelity.

**Comment by freescout-helpdesk** [comment]
[Are you removing emails from m](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#why-does-show-original-window-shows-truncated-message-without-previous-history)

**Comment by freescout-helpdesk** [comment]
So you'll need to find out why FreeScout can't fetch original message via IMAP from the mail server.

**Comment by fulldecent** [comment]
Okay, I see this is looked up live.

This is an error condition. It would be nice in the GUI after clicking Show Original to say that "The original message failed to load from IMAP, here is the latest truncated copy we have stored, please see https://github.com/freescout-helpdesk/freescout/wiki/FAQ#why-does-show-original-window-shows-truncated-message-without-previous-history"
