### ISSUE TITLE
Migration did finish on updating

### ISSUE THREAD

**Issue by vladik1985ab** [freescout-helpdesk/freescout#2609]
The productivity report is extremely low.
I'm trying to retrieve a 7-day report, but the query takes more than 3 minutes to complete. (without success)
![image](https://user-images.githubusercontent.com/2471805/214104759-edfdbf3c-8443-4a6b-96c3-e3da5f337939.png)

**Comment by freescout-helpdesk** [comment]
Do you have any errors in Manage > Logs > App Logs?

**Comment by vladik1985ab** [comment]
Yes, its something new! 
should I create new column? 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' (SQL: select `meta` from `conversations` where `meta` != and `created_at` >= 2023-01-16 00:00:00 and `closed_at` <= 2023-01-23 23:59:59) {"userId":4,"email":"vlad@cashdo.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' (SQL: select `meta` from `conversations` where `meta` != and `created_at` >= 2023-01-16 00:00:00 and `closed_at` <= 2023-01-23 23:59:59) at C:\ untime\\Apache24\\htdocs\\freescout\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' at C:\ untime\\Apache24\\htdocs\\freescout\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' at C:\ untime\\Apache24\\htdocs\\freescout\\overrides\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:82)

**Comment by freescout-helpdesk** [comment]
Some of the previous updates did not finish properly. Try to run Migrate DB in `Manage » System » Tools`

**Comment by vladik1985ab** [comment]
![image](https://user-images.githubusercontent.com/2471805/214118918-85707003-4c54-4058-af17-72921a27ae16.png)
the meta column is still missing.

**Comment by vladik1985ab** [comment]
FYI - I'm using 1.8.18 version.
Can I fix it by modify the table?

**Comment by freescout-helpdesk** [comment]
> Can I fix it by modify the table?

No. Update FreeScout to the latest version: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
