### ISSUE TITLE
checklist can't be translated

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2611]
The checklist strings don't appear in the translation section.

**Comment by freescout-helpdesk** [comment]
![2023-01-24_08-31-16](https://user-images.githubusercontent.com/40499291/214219082-f143495b-a21b-4178-9d41-0d5db7a9189f.png)


![2023-01-24_08-30-45](https://user-images.githubusercontent.com/40499291/214218964-c405438a-2fa0-4d37-a3a9-22cbd36de09f.png)

**Comment by mokkin** [comment]
You are very quick on closing issues. Indeed checklist isn't visible on our instance. We installed it yesterday and it's working, but not translatable.

![grafik](https://user-images.githubusercontent.com/2938748/214252813-a34edb5f-fcfa-4595-bbfd-421314eea624.png)

![grafik](https://user-images.githubusercontent.com/2938748/214252640-25c39057-e24e-47b4-bbaf-198ad9ceeaba.png)

**Comment by freescout-helpdesk** [comment]
We can fix only issues which we can reproduce. In other cases you need to do it yourself or find someone (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer) and send us pull request.

**Comment by mokkin** [comment]
Works now - I think importing didn't work right in the first attempts.
