### ISSUE TITLE
Mail Forwarding still does not work and sets customer to agent.

### ISSUE THREAD

**Issue by Lucleonhart** [freescout-helpdesk/freescout#2615]
I added the info to issue https://github.com/freescout-helpdesk/freescout/issues/2503 but looks like nobody checks the closed issues. :)

Sorry but it still does not work but i am not sure why.
I added some outputs for me to check:
// Try to get "From:" from body. $this->line('BODY:'.$body); $original_sender = $this->getOriginalSenderFromFwd($body); $this->line('original sender:'.$original_sender);

I get the body log and then an empty string for original sender.

But if i manually drop the body log text into a preg match tester with your expression it works fine.

Here is the body:
[log.txt](https://github.com/freescout-helpdesk/freescout/files/10371563/log.txt)

**Comment by freescout-helpdesk** [comment]
We've checked it with the body you've provided. The `$original_sender` was detected as `original_sender@customer.de`
