### ISSUE TITLE
Los trabajos en cola no se ejecutan

### ISSUE THREAD

**Issue by 11benji** [freescout-helpdesk/freescout#2616]
hola, les escribo para pedir de su colaboración y ayuda acerca de un error que estoy teniendo, acabo de realizar la instalación de su proyecto, realice la configuración básica, para que el sistema pueda enviar y recibir correos y todo bien, también configure los cron necesarios para poder ejecutar las tareas adecuadas.
Pero por alguna razón en el estado del sistema me está mostrando un mensaje que no he logrado identificar el error, adjunto una imagen de como se queda el apartado de trabajos en segundo plano.
![Screenshot](https://user-images.githubusercontent.com/123223785/214432068-7f713257-cd98-4d65-9ed4-2705e2c91039.png)

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
