### ISSUE TITLE
Email from workflow doesn't show previous conversation history

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2618]
If an answer to the client is manually written and the setting and "send full conversation history" is enabled, the full history is sent as expected.

If an email to the customer is triggered by a workflow, the history is not sent.

**Comment by freescout-helpdesk** [comment]
It's by design. This action sends an email to the customer and does not include previous conversation history.

**Comment by mokkin** [comment]
That's a pity. Otherwise this could be used easily to create auto reminders after several days or weeks on open questions.
Maybe this can be changed and follow the "sent history" setting?

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/

**Comment by mokkin** [comment]
Done: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/398483

Feel free to vote everyone!
