### ISSUE TITLE
Wrong signature added when forwarding email (signature module)

### ISSUE THREAD

**Issue by pf248** [freescout-helpdesk/freescout#2620]
Hello, we currently experienced that when sending an email via forwarding, the default signature is always displayed/added to the mail. 
We use the "Custom Mail Signatures"-Modul (latest) and the latest FS version. 

If you choose another signature in the forwarding process, it gets ignored and the default signature is sended.

Maybe you can check it / reproduce it (I couldn't do it on the demo environment as sending an email currently did not work at all)

Greetings and thanks in advance.

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Mailbox Signatures Module v1.0.10
