### ISSUE TITLE
Spam workflow not working

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2621]
We have defined  the following "Spam workflow":

![grafik](https://user-images.githubusercontent.com/2938748/214521584-fcaf73c1-243a-415e-9129-968e11c6b92c.png)

![grafik](https://user-images.githubusercontent.com/2938748/214521636-dc327f52-423a-4382-bd0d-6c2047e5531c.png)

![grafik](https://user-images.githubusercontent.com/2938748/214521666-6ee2877c-aac8-4494-89ca-88ec0a697e28.png)

Unfortunately it doesn't seem to work on messages like this which are flagged as SPAM by the mail server:

![grafik](https://user-images.githubusercontent.com/2938748/214521744-fa33eb38-aa8e-4025-9b53-ded8105b6476.png)

**Comment by freescout-helpdesk** [comment]
Change "Is equal" to "Contains"

**Comment by mokkin** [comment]
Sometimes it's so simple...
Thank you! :smiley:
