### ISSUE TITLE
Newsletters

### ISSUE THREAD

**Issue by invmedia** [freescout-helpdesk/freescout#2622]
Hey!

I have a problem with the newsletters I receive for FreeScout. When I open a newsletter via webmail, I can easily click on the links in it. When I open an email in FreeScout, the links are not active. Has anyone encountered such a problem? Do you have any solution? @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
Try to post here the body from Show Original (in the message dropdown) or send to support@freescout.net

**Comment by freescout-helpdesk** [comment]
There is no clickable links in the received email body. If you mean Submit button - it won't be shows in FreeScout.

**Comment by freescout-helpdesk** [comment]
We've got the mail body. The link is placed there in a weird way, so it can't be displayed after HTML purification.
```
<a href="https://..." target="_blank" style="text-decoration: none; color: #212121"></a><table role="presentation">
```
