### ISSUE TITLE
Limit end-user portal only to defined users / addresses

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2624]
I would like to limit the usage and login to the module "end-user portal" to only some users / email addresses and prevent any other person with any other address the login to this portal.

Is there any possibility?

Further I can´t find any place, where I can see all customers that already submitted a ticket / email. Can you help me?

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. Customers can be seen using https://freescout.net/module/crm/

**Comment by BeSt1979** [comment]
So perhaps you can add IT as FeatureRequest. My Idea ist to add a checkbox
into CRM Module which allows to activate or deactivate the possibility to
User end-user Portal.

FreeScout ***@***.***> schrieb am Do., 26. Jan. 2023, 07:49:

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/

**Comment by BeSt1979** [comment]
I created a feature request.
