### ISSUE TITLE
Reports Module: Incorrect averages in Productivity report

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2625]
Hello,

Reports Module displays strange averages in productivity report.

See attached. It shows 14% of conversations have first response time = 1-2 days, but average is 10 days, which is incorrect and simply impossible.

![изображение_2023-01-25_232031301](https://user-images.githubusercontent.com/63669538/214693421-b2d57d24-86c0-4d13-886a-8a0573f62c47.png)

The same is for RESOLUTION TIME report. It shows 1257 days as an average resolution time. Which is impossible as well as we respond to everything in max 1 day. It may count some deleted or automated conversations which never have agents responses.
![image](https://user-images.githubusercontent.com/63669538/214693993-097a3f75-d443-4629-a268-c6e358b20079.png)

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1.0.24. There was a mathematical mistake in `Avg.` value formatting.
