### ISSUE TITLE
How not to send auto ticket closure to "thank you" reply

### ISSUE THREAD

**Issue by minghuiyu** [freescout-helpdesk/freescout#2626]
After a ticket is "closed", a workflow sends an auto-reply to notify ticket is closed.

Guest often replies with "thank you" etc., and it will re-open the ticket. When re-close the ticket, how can the system not send another auto-reply?

A workaround I can think of is to have a custom field, i.e.: "no auto-reply", such that the workflow doesn't run if "no auto-reply" is selected AND state is closed. Any better option?

Thanks!

**Comment by ilyakonovalenko** [comment]
> When re-close the ticket, how can the system not send another auto-reply?

Every workflow can only run once. So it is impossible to run it multiple times for the same conversation. It is better to send some template manually every time you close the conversation with reply.

**Comment by freescout-helpdesk** [comment]
Yes, automatic workflows simply don't run more than once per ticket. So there should be no such an issue.
