### ISSUE TITLE
Email to via CRM added customer fails

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2627]
I added a customer via CRM module.
The email address in the customer profile is definitely correct!
![image](https://user-images.githubusercontent.com/5738613/214830637-fc893893-cd27-44dd-a1fe-087843eb5784.png)

Then I created a new "ticket" (conversation) and tried to send a mail to the customer in this conversation.

But this fails:
![image](https://user-images.githubusercontent.com/5738613/214831184-077c5b33-5279-4455-b072-a8af8609270a.png)

In the error log I see this:
![image](https://user-images.githubusercontent.com/5738613/214831351-10d25f21-fee1-46ff-a711-4b47f7107952.png)

Obviously the email address is not set correct into the mail.

**Comment by BeSt1979** [comment]
In System > Status I see failed background services and if I click on "view details" I find this:
![image](https://user-images.githubusercontent.com/5738613/214833249-1ce2176b-9482-44aa-bf2b-67d4ce7100c3.png)

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net? and send us step-by-step instruction?

**Comment by BeSt1979** [comment]
Yes, I can reproduce it in demo.freescout.net

First I go to CRM module an create a new customer
![image](https://user-images.githubusercontent.com/5738613/215143587-63f936c6-3ef6-4d2d-a07e-6198f17ca9d6.png)

The go to mailbox and create new conversation
![image](https://user-images.githubusercontent.com/5738613/215143688-068ee498-2975-4105-bbef-ae6daa7dbd76.png)

Then I select "phone", because I talked to the customer at the phone and created the ticket for him. I select the customer I created in the first step
![image](https://user-images.githubusercontent.com/5738613/215143931-b8837d70-13b4-4d8c-90bd-155778555553.png)

Then I "reply" to the ticket and try to send an email to the customer
![image](https://user-images.githubusercontent.com/5738613/215144222-56edb154-ddf7-40d9-bd04-2d3df93ad639.png)

This mail fails
![image](https://user-images.githubusercontent.com/5738613/215144340-78376e99-b38f-4dd4-a6da-02d6075af137.png)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by BeSt1979** [comment]
Thank you for the fast fix.
Perhaps it is a dumb question - but can you tell me, how I can update my docker-driven freescout installation?
