### ISSUE TITLE
Some email addresses in text display incorrectly

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2628]
Some email addresses in conversation messages display incorrectly.

For instance:

The following agent reply:
```
Hello,
Please email support@domain.com
```

Will be displayed as:
```
Hello,<br>
Please <a href="mailto:email&nbsp;support@domain.com" target="_blank">email&nbsp;support@domain.com</a>
```

**Comment by freescout-helpdesk** [comment]
Some screenshots would be helpful.

**Comment by ilyakonovalenko** [comment]
Just tried to reproduce in live demo.

To reproduce:
1) Copy ` dasdasd@adasds.com` with space before email address.
2) Paste it in textarea after text, like "our support is [CTRL+C here](= dasdasd@adasds.com)":
![image](https://user-images.githubusercontent.com/63669538/214840531-f5babb2f-f319-41f9-83d0-635badf83d5a.png)
3) It will be saved as `our support is&nbsp;dasdasd@adasds.com`:
![image](https://user-images.githubusercontent.com/63669538/214840677-ec407fee-63a9-460b-ac48-12599b49b650.png)

So it seems in some cases `&nbsp;` being inserted between text and email address. In the case email address displays incorrectly.

**Comment by freescout-helpdesk** [comment]
It looks like this has been fixed.
