### ISSUE TITLE
Latest update breaks conversation view on incorrect width/height image attributes

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2629]
Hi.

After the update I somethimes get an `Whoops, looks like something went wrong — check logs in /storage/logs` when I try to view a conversation. The error is ` A non-numeric value encountered at /www/..../overrides/ezyang/htmlpurifier/library/HTMLPurifier/AttrValidator.php:157)`. The thread body contains image tags like `<img alt="Facebook" height="35px" src="data:image/png;base64...`, so my guess is that the falsy height attribute breaks the calculation @ AttrValidator.php:157. I know its incorrect html / a incorrect value. But since we get lots of such emails, I would highly appriciate if you could add some sort of a sanitizer or something that prevents this error.

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in FreeScout v1.8.54
