### ISSUE TITLE
Saved replies // Variable // Custom field with wrong replacement

### ISSUE THREAD

**Issue by treborxy** [freescout-helpdesk/freescout#2630]
Hi,
I'm using FC 1.8.53 with modules "Saved Replies" 1.0.19 and "CRM" 1.0.28
Within CRM I created a custom field (dropdown) named 'Anrede' with values "Frau" and "Herr".
Than I created a 'saved reply' using this custom field, inserting it by the dropdown 'Variable eingeben'.
Inserted is: 
Hallo {%customer.cf_1%} {%customer.lastName%},
which renders to 
Hallo 2 Stracke,
In Profile of Robert Stracke custom field 'Anrede' is filled with 'Herr'.

Any idea if I misconfigured something?
Regards, Robert

**Comment by freescout-helpdesk** [comment]
Screenshots would be helpful.

**Comment by treborxy** [comment]
Problem ist the "2" instead of "Herr"...
Regards, Robert

**Comment by freescout-helpdesk** [comment]
Fixed in CRM Module v1.0.29
