### ISSUE TITLE
Freescout won´t work after docker restart

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2631]
I had to restart the docker container. After that, freescount won´t work anymore.
![image](https://user-images.githubusercontent.com/5738613/214862482-d66b23ee-4de9-4e8a-8cf3-21a091be11d9.png)
![image](https://user-images.githubusercontent.com/5738613/214862311-9c53c621-5582-4f0a-bb40-de0f63d36073.png)

Has anybody an idea, what goes wrong here?

**Comment by BeSt1979** [comment]
After switching lavarel in the app.php from debug=false to debug=true I can again login to freescout.
But all JS functions fail.  The lavarel-log now shows:
![image](https://user-images.githubusercontent.com/5738613/214869812-dc89ff7a-e944-49d9-97c7-a4b602b76f18.png)

**Comment by freescout-helpdesk** [comment]
The first screenshot shows only the last part of the error message. Can you find the full error message.

**Comment by BeSt1979** [comment]
The screenshot shows the full error message 6 times.

**Comment by BeSt1979** [comment]
I now restartet the container many times - and I don´t know why, but now it seems to work again... Please don´t ask me, what I did to make it work.
