### ISSUE TITLE
Can't upload attachment:  "Error occured. Please try again later."

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2632]
<img width="1615" alt="Screenshot 2023-01-26 at 09 48 36" src="https://user-images.githubusercontent.com/382183/214867120-b5e5b350-a405-438e-86c2-8c66bd853f63.png">
<img width="1615" alt="Screenshot 2023-01-26 at 09 48 42" src="https://user-images.githubusercontent.com/382183/214867137-9f7f8bfe-e056-4f9b-aec0-a71457f90681.png">
<img width="1615" alt="Screenshot 2023-01-26 at 09 48 46" src="https://user-images.githubusercontent.com/382183/214867257-fe297b85-53b8-48ce-8b9c-9401f93ca48e.png">

And there are no recent relevant logs:

<img width="1615" alt="Screenshot 2023-01-26 at 09 52 50" src="https://user-images.githubusercontent.com/382183/214867722-5fd8054b-e874-4a53-95e7-34d84d27f0d9.png">

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs
