### ISSUE TITLE
Partially shown message

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#2633]
Dear support,

Today we got an email that was only partially shown on freescout.
This is a screenshot:
https://paste.pics/c2ee87da06dfe5819c05658693de1252
In the original email there was more text, and in Show Original I see this message:
https://paste.pics/989e4b343d112a575504e17fc95514ce

In "fetch errors" and fetch_emails.log there's nothing with today's date.

What can we check?
And an an idea: maybe the warning should be placed in the message itself?
We totally missed half of what they wrote us :)

Thank you

**Comment by freescout-helpdesk** [comment]
Both screenshots have the same text. 

See also https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-a-customer-replies-within-the-cited-text-freescout-does-not-show-it

**Comment by dabesa** [comment]
Ops @freescout-helpdesk sorry about the wrong screenshot.
In "Show Original" I see the whole message, and I don't see cited text:
https://paste.pics/a402f44a9866a9a96dea864d2c741a34

Thanks
