### ISSUE TITLE
Telegram Integration not fully working

### ISSUE THREAD

**Issue by torbikua** [freescout-helpdesk/freescout#2634]
Hello, buy you module Telegram Integration. Create bot, setup integration. When I send message to bot it is create a ticket, but my reply to them not sending to user...

Try different versions of PHP: 7.4, 8.0, 8.1 the problem is not solved

**Fond next errors in Logs:**

`Error retrieving user info: Bad Request: invalid user_id specified {"exception":"[object] (BotMan\\Drivers\\Telegram\\Exceptions\\TelegramException(code: 0): Error retrieving user info: Bad Request: invalid user_id specified at /var/www/html/Modules/TelegramIntegration/vendor/botman/driver-telegram/src/TelegramDriver.php:88)
`

`Bad Request: invalid user_id specified {"exception":"[object] (BotMan\\Drivers\\Telegram\\Exceptions\\TelegramException(code: 0): Error retrieving user info: Bad Request: invalid user_id specified at /var/www/html/Modules/TelegramIntegration/vendor/botman/driver-telegram/src/TelegramDriver.php:88)`

**Comment by freescout-helpdesk** [comment]
If you can give an access to your FreeScout instance in order to check the issue - email at support@freescout.net. Otherwise try to debug it yourself or find someone who can do it for you: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by torbikua** [comment]
Sent email to [support@freescout.net](mailto:support@freescout.net)
