### ISSUE TITLE
Address in mailbox given [] does not comply with RFC 2822, 3.6.2

### ISSUE THREAD

**Issue by mavanbro** [freescout-helpdesk/freescout#2637]
Hi,

When sending a reply on a call based ticket, the mail to the customer is not being sent.
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.; File: /pathreplaced/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php (355)

when the ticket was created by sending a mail to the mailbox, the reply is send correctly

please advise

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by mavanbro** [comment]
Thanks for resolving this issue!
