### ISSUE TITLE
Show original function stopped working in version 1.8.54

### ISSUE THREAD

**Issue by gilbanech** [freescout-helpdesk/freescout#2638]
hello after the update
1.8.52 to 1.8.54
The show original function does not work.
the "Preview" window opens, but there is only a truncated message and an error
**"The original message could not be loaded from mail server, below is the latest truncated copy stored in database."**
And this is on all mailboxes.
I don't see any errors in the logs.
Thank you.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. You can check it.

**Comment by gilbanech** [comment]
Thank you, I'll definitely check in the evening when there is a maintenance window.
