### ISSUE TITLE
Undefined variable $result in latest update

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2639]
Hi.

I got the error `Undefined variable $result at /www/..../app/Thread.php:1382`.

https://github.com/freescout-helpdesk/freescout/blob/b0ffdfb268afbabd05cbf2d74520c2e3ac66fb07/app/Thread.php#L1382

Thanks in advance

**Comment by minghuiyu** [comment]
https://github.com/freescout-helpdesk/freescout/blob/b0ffdfb268afbabd05cbf2d74520c2e3ac66fb07/app/Thread.php#L1381

Should be !empty($data->date) instead maybe?

**Comment by sofl88** [comment]
> https://github.com/freescout-helpdesk/freescout/blob/b0ffdfb268afbabd05cbf2d74520c2e3ac66fb07/app/Thread.php#L1381
> 
> Should be !empty($data->date) instead maybe?

Might be but in any case the return variable `$result` never gets set somewhere and because of that the undefined error occurs.
