### ISSUE TITLE
The process has been signaled with signal "9"

### ISSUE THREAD

**Issue by iGitnow** [freescout-helpdesk/freescout#264]
Hello,

**First of all, thank you for reading this request for help.**

I am getting the following error after each attempt to run the cron job (*/5 * * * *  /usr/local/bin/php /home/user/support/artisan schedule:run >> /dev/null 2>&1).
My shared hosting doesn't allow me to run the cron every minute but every 5 min.
The error appears in the laravel-2019-05-16.log file.

**Additional details that might help:** 
- This is a clean install.
- Used the web installer. All verification went through without any errors or warning.
- Using MySQL.
- Chose not to configure the e-mail fetching since I don't see the point of this feature. I would like my customers to receive notifications of replies and my admin to receive notifications of tickets creation or modifications. All exchanges must happen through freescout and not by e-mail.
- Sending tests are successful, be it I do not really understand why when my admin creates a user and an invitation is sent to the customer e-mail, the customer gets an email telling him/her that "his/her first and last name created an account for you at support.our domain.com". Shouldn't it be the "admin first and last name created an account for you at support.our domain.com" ? Anyway this is not a big deal.
- Despite a successful Sending test for both the admin and the new user, creating a ticket sends no notifications to the admin, and a reply from the admin doesn't send a notification to the user. I think it's related to the cron failing.
- In the queue-jobs.log everything seems to be processed: 
          - App\Jobs\TriggerAction - Processed x2
          - App\Jobs\SendReplyToCustomer - Processed
          - App\Jobs\SendNotificationToUsers - Processed
          - App\Jobs\SendReplyToCustomer - Processed
- In the fetch-emails.log everything seems ok:
          - Fetching finished

Please find attached the full stack-trace.
[laravel-2019-05-16.log](https://github.com/freescout-helpdesk/freescout/files/3184738/laravel-2019-05-16.log)

Thank you for any help you can provide.

Kind regards.

**Comment by freescout-helpdesk** [comment]
Hi. In FreeScout "users" are supports agents, not customers.

**Comment by freescout-helpdesk** [comment]
Closing for now activity.
