### ISSUE TITLE
Mailto links should remain clickable and not purged

### ISSUE THREAD

**Issue by AlecKinnear** [freescout-helpdesk/freescout#2640]
We have a related issue to [2628](https://github.com/freescout-helpdesk/freescout/issues/2628). Inside of some of our incoming messages, (specifically comment notifications from WordPress which we bring in to our Support support channel in FreeScout), we have automated mailto links embedded. We include those mailto links to allow us to directly email the customer if we don't want to publish a comment but wish to contact the author.

What happens to those mailto links is they are converted from:

```
<p>Reply to comment via email: <a href="mailto:%22Mustafa%22%20<Mustafa.ado@gmail.com>?subject=Your%20comment%20on%20%22The%20True%20Cost%20Of%20A%20Video%20Encoding%20Workflow%22&body=%0D%0A%0D%0A%3E%20%3Cp%3EHello%20Alec%20Kinnear%3C%2Fp%3E%0A%3E%20%3Cp%3EI%20appreciate%20your%20seek%20to%20help%20users%20%2C%20in%20this%20answer%20%0A%3E%20%E2%80%9C%20We%20could%20do%20this%20as%20custom%20development%20for%20your%20site%20or%20your%20own%20web%20%20%E2%80%9C%20i%20want%20more%20details%20because%20i%20really%20need%20it%20%3C%2Fp%3E%0A%3E%20%3Cp%3EThe%20last%20question%20about%20DRM%20text%20is%20%2C%20my%20videos%20background%20almost%20all%20time%20will%20be%20in%20white%20color%20%2C%20so%20is%20the%20watermark%20will%20be%20visible%20clearly%20%3F%3C%2Fp%3E">Email reply</a><br>
```

to this in FreeScout:

```
<p>Reply to comment via email: <a href="mailto:%22Mustafa%22%20" target="_blank">Email reply</a><br>Link to comment:....</p>
```

Email has been altered to protect the innocent.

Here's what it looks like (obligatory screenshot):

![freescout-mailto-links-destoyed](https://user-images.githubusercontent.com/107859958/215146457-c7320d61-bb9e-49d7-a6e5-c20bbabccf93.png)

Desired behaviour would be that the mailto would be retained within FreeScout. In this particular case, we'd have an option to change how we bring in these comment notifications, creating new tickets via API with the correct client name and email instead of automatically sending in normal WordPress comment notifications from our wp@ourdomain.com address.

I still think it would probably be better to retain the original mailto links with automated subject in incoming emails. Open to counter arguments.

**Comment by freescout-helpdesk** [comment]
Proper way to do it:

```
<a href="mailto:%22John%20Wayne%22%3ctest@example.org%3e?subject=test">test</a>
```

![2023-01-30_14-14-33](https://user-images.githubusercontent.com/40499291/215462378-455f5ee7-7256-404a-96d9-12ead6090a56.png)

**Comment by AlecKinnear** [comment]
Thanks very much for the tip. We were able to fix a plugin we were using to format the URLs as you suggested. FreeScout is working fine now with mailto links. Wonderful.
