### ISSUE TITLE
Wrong alignment RTL

### ISSUE THREAD

**Issue by vladik1985ab** [freescout-helpdesk/freescout#2642]
Hello,

Direction RTL is missing from the conversation start direction.
![image](https://user-images.githubusercontent.com/2471805/215279948-10692473-1588-416d-ad77-2d5360c5b985.png)

As a result, the email arrives with incorrect alignment. Please see the following example:
![image](https://user-images.githubusercontent.com/2471805/215280189-cef9ff97-df49-44cd-806f-50a661623e63.png)

Only when I align the text to the left and then back to the right does the direction appear and the email arrive OK.
![image](https://user-images.githubusercontent.com/2471805/215279958-f3bb318b-a3f2-48e3-bda5-3dcc96113305.png)

**Comment by freescout-helpdesk** [comment]
It looks like we don't have capacity to solve this. Maybe someone with better knowledge of RTL can find a solution.
