### ISSUE TITLE
Failed to parse time string

### ISSUE THREAD

**Issue by pf248** [freescout-helpdesk/freescout#2645]
Hello everyone,

for the last few weeks we encounter a lot of the following errors in our laravel-log-files:

**[Webklex\IMAP\Message] Error: Failed to parse time string ( mailDate) at position 0 (m): The timezone could not be found in the database; File: /install_path/overrides/nesbot/carbon/src/Carbon/Carbon.php (548)**

It is always the same error and it comes up 20 to 50 times a day. 

Freescout is the newest version 1.8.54 and also all modules are up to date. Emails are fetched correctly as we checked directly in the mailbox on the provider. 

What can we do here or is it a known bug or could you do something about it?

Thanks in advance!

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. You can check it.
