### ISSUE TITLE
queue:work dows not run

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2647]
I set up a whole new server without use of the docker container. 
I use a Ubuntu server, nginx and I set up everything exactly following the describtion on 
[https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#1-prerequisites](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#1-prerequisites)

Everything worked out very well. The server is running, freescout is running.

But I again see this problem:
![image](https://user-images.githubusercontent.com/5738613/215491721-02125f04-9ef0-470e-b8ab-6f117a0a92cf.png)

Even after trying to start the job via URL or direct in the ubuntu shell, I still see the error message.
The cronjob is set in /etc/crontab with this line
`* * * * * www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1`

Can anybody help me?

**Comment by BeSt1979** [comment]
I change to
`* * * * * www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1`

But still 
![image](https://user-images.githubusercontent.com/5738613/215495469-5a3599c0-ad57-4dfe-9c3c-0c5b49ee87a7.png)

**Comment by BeSt1979** [comment]
I change to
`* * * * * root php /var/www/html/artisan schedule:run >> /dev/null 2>&1`

But still 
![image](https://user-images.githubusercontent.com/5738613/215495469-5a3599c0-ad57-4dfe-9c3c-0c5b49ee87a7.png)

**Comment by pf248** [comment]
Maybe you can try these commands from their ubuntu installation script (dont forget to change install path to your path like /var/www or whatever):

sudo echo "* * * * * php install_path/artisan schedule:run >> /dev/null 2>&1" >> /tmp/wwwdatacron
sudo crontab -u www-data /tmp/wwwdatacron
sudo rm -f /tmp/wwwdatacron

and afaik the cron user has to be the webserver user with the permission for the install directory (e.g. www-data)

**Comment by BeSt1979** [comment]
That seemed to do the trick.
![image](https://user-images.githubusercontent.com/5738613/215499224-51faef78-b970-47df-8708-4f7fac2e9577.png)

Thank you!!!
