### ISSUE TITLE
Workflow mail to Team now working

### ISSUE THREAD

**Issue by maukunze** [freescout-helpdesk/freescout#2648]
Hello everybody,

i have the following problem:
i got a workflow which is being applied when we recieve a ticket to assign it to different teams. Now in this workflow we want to notify the team members when a team has been assigned a ticket. The problem is that the workflow doesnt send out a notification to the team members when triggered.
As a workaround i can put in all members at once  in the workflow.

Is there something planned to resolve this or am i doing something wrong?

**Comment by freescout-helpdesk** [comment]
Screenshots would be helpful.

**Comment by maukunze** [comment]
Hey,

ive configured the following Test-Workflow:

![image](https://user-images.githubusercontent.com/119842118/215499038-024670ca-a8c4-4628-b9a1-7b792e5edffe.png)

As you can see the E-Mail should be send to the menḿbers of this team as i understand it. But that doesnt happen. When triggering the Workflow it says that workflow was applied successfully but no mails send out to the members of the team.

On the other Side when i enter every user for themself to recieve the Mail it works.
As already said i cant find anything regarding that in the Logs.

**Comment by maukunze** [comment]
The Module is Version: 1.0.40  and Freescout itself is  1.8.54.
I saw that 5 hours ago an update was pushed but this kind of "bug" wasnt mentioned in the notes.

**Comment by maukunze** [comment]
any update on this one?

**Comment by freescout-helpdesk** [comment]
It will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in Teams Module v1.0.10
