### ISSUE TITLE
Spam Filter and Chat Module

### ISSUE THREAD

**Issue by pf248** [freescout-helpdesk/freescout#2649]
Hello! Since we use both of these modules (latest) we experienced that in some cases, conversations created by live chat directly went into the spam folder and don't get recognized.

As chat messages are quite short most of the time which is maybe detected by the filter(?), is it possible to prevent such behaviour? Or would a whitelist feature for subject or / type "chat" help?  Or is the only option to "train" the spam filter (which is not optimal)?

Maybe you have an idea on how to improve this.

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Fixed in Spam Filter Module v1.0.12
