### ISSUE TITLE
"Saved Replies" is missing in Modules Directory

### ISSUE THREAD

**Issue by sdemchuk** [freescout-helpdesk/freescout#265]
I have install last version of 1.1.7, but module **Saved Replies** missing in **Modules Directory**
So I can`t install it (I got License on site)

How I can find it?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#installing-modules

**Comment by sdemchuk** [comment]
yes, I doing in this way all other modules, but module Saved Replies is not exist in list, and your API (https://freescout.net/wp-json/freescout/v1/modules) also didn`t knows about this module

**Comment by freescout-helpdesk** [comment]
The issue has been fixed. You may need to clear FS cache in System > Tools.

**Comment by sdemchuk** [comment]
thank you
