### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by advoenkin** [freescout-helpdesk/freescout#2650]
Hello, 
When i'm tryin run update by press update button i got next error 

![image](https://user-images.githubusercontent.com/68369599/215694040-b805e939-3642-4a57-9f13-100e20c12db5.png)

I'ts okay, i was try to change permission on required folders 775 and files 664 but system back it to 755 and 644.

**Comment by advoenkin** [comment]
I'm was try using another method update, method # 2 by update.sh

Update was successfully, but with some errors. 
![image](https://user-images.githubusercontent.com/68369599/215695176-f873c762-3b23-412b-9b05-67e043822535.png)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-undefined-constant-ft_uid
