### ISSUE TITLE
email with multiple bcc recipients (all freescout mailboxes) only gets fetched once

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2652]
Hi.

I wasn't able to test this in the demo installation since there is only one active mailbox. Our installation has some minor adjustments but I think the behaviour is the same.

Lets say you send an email with 2 freescout mailboxes as bcc recipients, only the first is delivered/fetched. I know there is a part in the code to take care of such cases but it seems not to work with bcc. With the given scenario, the variable `$recipient_emails` and the return value of `$this->attrToArray($message->getBcc()` is an empty array.

https://github.com/freescout-helpdesk/freescout/blob/fe03177a800b6060c72da66c3964da43ecd35d73/app/Console/Commands/FetchEmails.php#L605

I think this kinda makes sense since the bcc is indeed not visible for the receiver (?)

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.
