### ISSUE TITLE
FAQ: notes for backup

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2653]
Here are backup instructions I have successfully used with FreeScout when using the default (first option each time) install instructions.

Pasting here in case they might be helpful to note at https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-to-backup-and-restore-the-freescout

---

```sh
# Get website files:
rsync --recursive --delete --times root@freescout.example.com:/var/www/html var-web-html

# Dump and get MySQL databases:
ssh root@freescout.example.com 'mysqldump --all-databases > ~/mysql-dump.sql' &&
rsync root@freescout.example.com:mysql-dump.sql mysql-dump.sql &&
ssh root@freescout.example.com 'rm ~/mysql-dump.sql'
```

---

Side reference: https://github.com/freescout-helpdesk/freescout/issues/2568

**Comment by freescout-helpdesk** [comment]
Added as an example to https://github.com/freescout-helpdesk/freescout/wiki/Backup
