### ISSUE TITLE
User ticket notification email content missing

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2654]
We've had a couple of emails sent to our mailbox that appears fine in the FreeScout web interface, but the email notification sent to the mailbox users only contains the subject:
![Screenshot 2023-02-01 at 5 10 22 pm](https://user-images.githubusercontent.com/869534/215965750-0f518631-aad1-4669-b7b0-50fe30813f8d.png)

Web Interface:
![Screenshot 2023-02-01 at 5 10 51 pm](https://user-images.githubusercontent.com/869534/215965761-d2d32e66-e742-48d6-84e0-2a834782b464.png)

The common pattern I can see is multiple workflows are trigged that each add a tag.
Initially I thought it was ones with more HTML formatting than normal, but I'm now leaning towards the workflows.

I can send some of the original emails to your support address if that helps.

I'll start digging into the code as well to see if anything jumps out.

**Comment by avenjamin** [comment]
I've just done a couple of tests:

1) I created two new workflows that look for subject contains: blah and subject contains: foo
I then sent an email with subject: blah foo and no workflows were triggered ?!
The user email displayed the body as expected.

2) I then looked at my existing workflows and they are testing if the body contains keywords so I tweaked my workflows to look for body contains: blah and body contains: foo
My next test email had the body set to: blah foo
The user email did **NOT** display the body which matches the issue.

We have plenty of other tickets that have been tagged via a workflow, but only one workflow was triggered.
The user email displayed the body as expected.

Now to work out why it happens.
- is it related to specific workflow conditions and/or actions
- why didn't the workflow trigger when it was looking at the subject?

**Comment by avenjamin** [comment]
Just noticed that normally when a new ticket is sent - the email says:

```Received a new conversation #20088```

In this case we get:

```Workflow replied to conversation #20244```

`Workflow` is the user that processes the various workflows so this kinda makes sense, but clearly there's some different logic running for these tickets.

**Comment by avenjamin** [comment]
@freescout-helpdesk So nothing's jumping out at me in the code unfortunately.

My understanding is that the workflow module is overriding the usual new conversation notification and is then sending a "user replied to conversation" notification instead which doesn't contain the original message because it's a workflow that's adding tags.

However the flaw to that logic is that it works fine when only a single workflow is triggered.
The message still shows `Workflow replied to conversation #20081` and the `Workflow Auto Tag - Foo was triggered` appears along with the body of the original email.

So some how when more than one automatic workflow is triggered the original thread is lost/dropped and not displayed.

I think the relevant section in the view is here - perhaps the `$threads` array is missing the original message:
https://github.com/freescout-helpdesk/freescout/blob/709c65563b2eb39b64b7e80f02b959725856616f/resources/views/emails/user/notification.blade.php#L113-L233


Looking at the workflows Module in Workflows/Entities/Workflow.php on lines 62-66 we have:
```
    /**
     * We have to store the last thread, as while processing workflows,
     * new last thread may be added.
     */
    public static $cond_last_thread = [];
```

And then further down on in the runAutomaticForConversation function on lines 606-634 there is code for keeping track of the last thread.

Lines 840-889 is where the conditions are checked for body and $cond_last_thread is updated.

Not sure how helpful all the above is for debugging, but hopefully it points us in the right direction.
Any further help would be appreciated.

**Comment by freescout-helpdesk** [comment]
![2023-02-02_10-38-12](https://user-images.githubusercontent.com/40499291/216261076-80344bd4-c0b3-4710-b3f6-46b7f5e79498.png)

Could you please attach screenshots of this workflow configuration.

**Comment by avenjamin** [comment]
![image](https://user-images.githubusercontent.com/869534/216264383-817769cb-d605-44de-a896-48c0956764f8.jpeg)

![image](https://user-images.githubusercontent.com/869534/216264434-7556a638-2abc-41d1-9e37-26f0e4ed6aa7.jpeg)

![image](https://user-images.githubusercontent.com/869534/216264472-3c5eac79-f182-4f99-8c1e-969c1b38d0bf.jpeg)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.

![2023-02-02_11-41-33](https://user-images.githubusercontent.com/40499291/216274218-c05feb59-434f-4de0-800e-0fd620c4b19b.png)

**Comment by avenjamin** [comment]
Odd - just had another one come through the morning - will keep digging.

Did your screenshot say `Workflow replied to the conversation` or the original customer?

**Comment by freescout-helpdesk** [comment]
"Original customer" replied to conversation #2864

**Comment by avenjamin** [comment]
@freescout-helpdesk I have about 10 auto tagging workflows and I just tried another test email with about 6 keywords.

The user agent email only shows the first two.
The web interface shows all of them. 

Are you able to test again with more than two workflows and try trigger all of them.

Does anyone else have this issue?

**Comment by freescout-helpdesk** [comment]
3 workflows also work fine.

**Comment by freescout-helpdesk** [comment]
It looks like it's some local issue of your FreeScout installation. Maybe something was broken during the previous update. Also try to disable all non-official modules (if any).
