### ISSUE TITLE
How to mail to groups?

### ISSUE THREAD

**Issue by treborxy** [freescout-helpdesk/freescout#2657]
Is it possible to send mailings to groups of customers?
If no => feature request
If yes => could you please explain how?
Any help highly appreciated!

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
There is a possibility to allow to select customers using Customer Fields when creating a new conversation. But in this case a new conversation will be created in FreeScout for each customer-recipient. Will such solution work for you?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/448#issuecomment-1680026033
