### ISSUE TITLE
Teams/Users notifications after 1.8.56 update

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2658]
Hello,

After 1.8.56 update users started to receive notifications of their own replies.

To reproduce:
- Enable all notifications for user
- Add a reply to any conversation
- FreeScout will send the user a notification which it sends when another user reply

Haven't tested if it is only related to Teams module because I can't disable it in production. But it probably is.

**Comment by ilyakonovalenko** [comment]
Also when customer answers to the conversation, two notifications for each user are sent. 
![изображение_2023-02-01_171832449](https://user-images.githubusercontent.com/63669538/216083370-7bcd9b23-82a9-4138-a05d-ba8cd30c36a5.png)

**Comment by ilyakonovalenko** [comment]
I also noticed the following in system info:
![изображение_2023-02-01_172215879](https://user-images.githubusercontent.com/63669538/216084343-3670fed3-2d7f-4346-b9e9-7cba2447252b.png)

Killing processes does not fix the issue. It seems the update breaks something :-(

**Comment by ilyakonovalenko** [comment]
While processes issue can be related to particular setup (but it for sure started to happen after update), duplicated user notifications do not relate to this. Any responding user will receive notification of his reply.

**Comment by freescout-helpdesk** [comment]
Notifications issue has been fixed in Teams Module v1.0.11 and Workflows Module v1.0.41
