### ISSUE TITLE
Latest fix for #2652 (multiple bcc recipients) breaks the functionality for cc's, to's or mixed

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2659]
Hi.

It seems there is a misconception in the latest fix for https://github.com/freescout-helpdesk/freescout/issues/2652 . It now solves the described issue but the same issue is now present with cc's, to's or both. 

My guess is, that this condition is false for `to` and `cc` and because of that `$duplicate_message_id` is not set to `null` which later in the code leads to `Message with such Message-ID has been fetched before...`

https://github.com/freescout-helpdesk/freescout/blob/709c65563b2eb39b64b7e80f02b959725856616f/app/Console/Commands/FetchEmails.php#L297

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
