### ISSUE TITLE
Suggestion: Option to enable 2fa

### ISSUE THREAD

**Issue by FixTheAdmin** [freescout-helpdesk/freescout#266]
Great piece of software, I'm really enjoying it.

Please consider adding the option to enable two factor authentication in order to improve security.

**Comment by freescout-helpdesk** [comment]
It will be implemented in future as module.

**Comment by sam-suresh** [comment]
+1

**Comment by idzard** [comment]
+1

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/two-factor-authentication/
