### ISSUE TITLE
"Send emails separately to each recipient" shows wrong threads count on the first conversation and adds first receiver as CC for all but the first.

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2661]
Hi.

I'm not sure if parts of the issue are intended but to me it doesn't seem so.

[bug.webm](https://user-images.githubusercontent.com/12407767/216129987-192e6ec2-dc4a-4022-b278-2dd32136cfea.webm)

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
