### ISSUE TITLE
Subject Line Does Not Populate when using the New Conversation Function

### ISSUE THREAD

**Issue by rosequaartz** [freescout-helpdesk/freescout#2662]
Hello! 

Previously, the functionality existed such that when using the `New Conversation` option, the newly created thread would autopopulate the `Subject Line`. This is no longer the case. This was a useful functionality and I'm curious if the change we are experiencing is a bug? 
In testing on the FreeScout Demo site, I can replicate the same behaviour. `New Conversation` does not autopopulate the new thread `Subject Line`. Thanks for any insight you can provide! :)

**Comment by freescout-helpdesk** [comment]
To understand the issue some screenshot would be helpful.

**Comment by rosequaartz** [comment]
For sure! 

1. log into **FreeScout Demo** site,
2. click on a message to open,
3. select `New Conversation`,
![2023-02-02_10-05](https://user-images.githubusercontent.com/116131733/216393796-872bca8a-d253-41a0-abfd-deec5ed8f884.png)

4. a new conversation thread opens but does not contain the `Subject` from the original conversation
5. previously, the `Subject` line would autopopulate with the original thread subject.
![2023-02-02_10-06](https://user-images.githubusercontent.com/116131733/216394199-438e6447-7bdf-41ca-8f07-1ee07630261d.png)

**Comment by freescout-helpdesk** [comment]
Fixed in the master branch.
