### ISSUE TITLE
[Feature] List of clients as table

### ISSUE THREAD

**Issue by EgorKlochkov** [freescout-helpdesk/freescout#2663]
On the customer management page _freescout/search?mode=customers&xs_crm=1_
show as a list (or table) instead of cards.
And provide an opportunity to show first the last name, and then the name of the client

**Comment by freescout-helpdesk** [comment]
What is the reason to have customers as a list/table?

**Comment by avenjamin** [comment]
Can I suggest a view mode option (and preference): Grid mode and list mode.

A list of customers with sortable columns would be quite useful.

**Comment by freescout-helpdesk** [comment]
Most likely it will not be implemented by us.
