### ISSUE TITLE
mute reply when customer has mailbox mail address

### ISSUE THREAD

**Issue by phanousk** [freescout-helpdesk/freescout#2664]
Hi,
when creating a ticket from GUI with Customer e-mail address which is the same as Mailbox e-mail address, the mail to Users is sent twice. Shouldn't be the mail to Customer silenced and sent only to Users? Great that we don't have autoreply in place so there is no chance to make a mail storm.
BTW if this is not a bug, could I please ask for a new rule in Workflows which would allow me to squelch mail to Customer when meet certain condition?
Thank you, Petr

**Comment by freescout-helpdesk** [comment]
We've checked - the user receives the second notification when the message is fetched from the mailbox. Looks fine. And there won't be auto-replies sent.

**Comment by phanousk** [comment]
Well I think it's not completed. So the lucky thing is that it wouldn't cause mail storm, but the mail is still sent twice. I consider this as unwanted. But maybe I am alone :)
