### ISSUE TITLE
Replying with the initial "To" email address

### ISSUE THREAD

**Issue by JinksKid** [freescout-helpdesk/freescout#2666]
Hello

We use mailman for a subscription list which is great. Initial email is sent, and all the replies attach to the one conversation.
Replying is almost perfect. A drop down box appears with everyone who has replied and can reply to the specific person. The only issue is we cant reply using the mailman email address that we first used if we need to reply to everyone.
Is it possibly to add the initial "To" email address into the list for replies without starting a new conversation?

**Comment by freescout-helpdesk** [comment]
Please attach a screenshot of the To you are talking about.

**Comment by avenjamin** [comment]
@JinksKid What's the freescout mailbox email address?

Is it allscouts@domain.com? Or is it different and just a member of the mailing list in mailman?

**Comment by JinksKid** [comment]
It would be ***@***.*** so differentSent on the go with Vodafone
-------- Original message --------From: Ben Perry ***@***.***> Date: 5/2/23  8:58 am  (GMT+10:00) To: freescout-helpdesk/freescout ***@***.***> Cc: JinksKid ***@***.***>, Mention ***@***.***> Subject: Re: [freescout-helpdesk/freescout] Replying with the initial "To" email address (Issue #2666) 
@JinksKid What's the freescout mailbox email address?
Is it ***@***.***? Or is it different and just a member of the mailing list in mailman?

**Comment by avenjamin** [comment]
Lol looks like Vodafone stripped all the email addresses in your reply. 

If the email address is different how does FreeScout know about the original address and all the members?

Are you sending the message to the mailman address from
FreeScout?

Does the mailman reply include everyone as a CC or a To?

Is the original address visible in the email that FreeScout sees?

Some of these questions may be silly, I'm just trying to understand the flow of mail.

**Comment by JinksKid** [comment]
> Lol looks like Vodafone stripped all the email addresses in your  #reply.

Sorry. The freescout email is different. scouts@domain.com


> If the email address is different how does FreeScout know about the original address and all the members?

The original address is from the inital email. FreeScout doesnt know all the members, only the ones that reply.
 
> Are you sending the message to the mailman address from FreeScout?

Yes

> Does the mailman reply include everyone as a CC or a To?

Nope
 
> Is the original address visible in the email that FreeScout sees?

No. Not from the replys.

> Some of these questions may be silly, I'm just trying to understand the flow of mail.

Ok. i will try and break it down.
mailbox is scouts@domain.com
We sent a new mail to allscouts@domain.com (mailman)
mailman then changes the replyto address to scouts@domain.com
mailman then sends the email to each member seperatly (members can not see each other)
members reply to scouts@domain.com
replies show up in FreeScout in the original conversation.
From here we can reply in FreeScout to individuals as seen in image above.
But we can not do a reply to everyone using the allscouts@domain.com email as its not listed.

My proposal is to add the inital "To" email address (allscouts@domain.com) to the "To" list when drafting a reply along with any

**Comment by freescout-helpdesk** [comment]
Most likely won't be implemented.
