### ISSUE TITLE
Workflows: "Applied to" shows wrong number or applies wrong

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2667]
Hello.

Im currently upgrading our FreeScout site along with its modules.
While testing the site out after being upgraded, i found the following issue:

I created a new Mailbox and set it up, as I normally would.
I tested the send/fetch mail features to make sure it worked, which it did.

However, when I went to setup the workflows and test it, I see that it had applied to a lot more conversations thats currently in the mailbox (2 test conversations currently).

![image](https://user-images.githubusercontent.com/110815495/216563892-d9eabc98-79a2-4c98-824f-b05490e8eb0d.png)

![image](https://user-images.githubusercontent.com/110815495/216563976-8b39d5b1-6804-4994-834e-2391b1ac7dd0.png)

So I was wondering if it was just a display issue of how many it was applied to, and looked into the code:
`$workflow->countConversationsApplied()`

Which gets me the following SQL:
![image](https://user-images.githubusercontent.com/110815495/216564391-fae67a3f-272d-4938-9e84-f218afc9c653.png)

I see this also contains 1166 conversations_workflows rows, but the mailbox which the workflow runs on, again, only has 2 conversations.

Maybe I have misunderstood something about it applies? or how it displays?

Thanks for the help :)

For good measure, the version of Workflow that im using is Version: 1.0.40

**Comment by freescout-helpdesk** [comment]
Check `conversation_ids` in `conversations_workflows` table. Do they belong to the chosen maibox?

**Comment by maxkvbn** [comment]
Looking at conversation_ids, they belong to completly different conversations. Again, in this mailbox, theres only 2 current conversations:

![image](https://user-images.githubusercontent.com/110815495/216591626-2bfa5310-8ce9-4d3e-adc1-32f76fb2c3c0.png)

**Comment by freescout-helpdesk** [comment]
You can open some of those conversations by their ID (/conversation/ID) and check their mailbox and see if the workflow really has been applied.

**Comment by maxkvbn** [comment]
That makes it even more weird. Looking at the conversations, it seems that it has indeed been triggered, but the date is all wrong?

![image](https://user-images.githubusercontent.com/110815495/216592900-81eb5e5f-ac3a-454b-a9a9-6c147bd9ad39.png)


Please note that no workflows named 'ftrest' has existed before today.

**Comment by freescout-helpdesk** [comment]
Yes. Workflow ID got messed up.

**Comment by maxkvbn** [comment]
Yup that is what caused it.
Thanks for the help!
