### ISSUE TITLE
Tags: Unable to create new or select exsisting

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2668]
Hi.

After upgrading our FreeScout site and testing the modules, I am unable add or select exsting tags to a conversation.

![image](https://user-images.githubusercontent.com/110815495/216568456-35cd204e-018c-46d8-9afa-17950d93b171.png)

It doesnt autofocus the input field, and if I click on it, it closes.

Inspecting the HTML while the box is visible gives me the following: 

```
<div class="input-group">
		<select class="form-control tag-input" multiple="">
		</select>
		<span class="input-group-btn">
			<button class="btn btn-default" type="button"><i class="glyphicon glyphicon-ok"></i></button>
		</span>
    </div>
```

It seems that it doesnt load the existing onces in, nor does it have a input field that users can enter a new tags into.

If I go to a old conversation which was handled before the upgrade, I can still see the tags below the input, but i am still unable to select new or create one:
![image](https://user-images.githubusercontent.com/110815495/216569289-d9416032-e015-45f4-8e73-4c9996a46995.png)

Just as a test, I also enabled the following setting, which unfortunately didnt have any effect on being able to interact with the tags box either:

![image](https://user-images.githubusercontent.com/110815495/216569517-d7a90e31-6257-418f-bd7d-26c665a648f4.png)

Tags version: Version: 1.0.24

**Comment by freescout-helpdesk** [comment]
Check JavaScript errors in the browser console.

**Comment by maxkvbn** [comment]
This is the output of the browser console:

```
Uncaught ReferenceError: eaReminderInit is not defined
    at 38766?folder_id=11467:902:176
4eb4675726e42d0fc239a0388ab0826d82040116582.js:44 Polycast connection established!
```

**Comment by freescout-helpdesk** [comment]
Update all modules to their latest versions and clear cache.

**Comment by maxkvbn** [comment]
All modules are currently updated to the latest version, and the cache has been cleared.
This did not resolve the issue unfortunately.

**Comment by freescout-helpdesk** [comment]
Try to re-install ExtendedAttachments module, `eaReminderInit` belongs to it.
