### ISSUE TITLE
Images in E-Mail are not displayed in FreeScout

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#2669]
Hey there,

we have repeatetly problems with missing images in FreeScout. The images are present in the mail. I can see them if I log into the corresponding e-mail account, but FreeScout has problems downloading/displaying the images.

This is a recent e-mail, where 3 images are attached but not visible in FS. Hopefully you can find and fix the problem.

[mail.txt](https://github.com/freescout-helpdesk/freescout/files/10578281/mail.txt)

**Comment by freescout-helpdesk** [comment]
Are you using modern oAuth IMAP authentication or regular?

**Comment by obstschale** [comment]
Regular. Simply imap with username + password

**Comment by freescout-helpdesk** [comment]
Does it happen with all the images in all emails?

**Comment by obstschale** [comment]
No, it does not happen to all mails. Some work, some don't. I'm willing to provide more examples, but I would prefer to not upload the mails to GitHub. Maybe I can mail them to you?

**Comment by freescout-helpdesk** [comment]
Can you send such email to support@freescout.com, but not as Fwd or attachment. This way will be able to reproduce the issue on our support@freescout.com instance.

**Comment by obstschale** [comment]
Thx. I will send you some mails. I hope I will find time to do that this week.

**Comment by freescout-helpdesk** [comment]
It looks like you are the only one having this issue. So most likely something's wrong with your installation. Check for example: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-inline-images-do-not-display-and-attachments-lead-to-404-errors

**Comment by obstschale** [comment]
I will check. Thank you

**Comment by localmarketingpros** [comment]
I am having the same issue in almost all emails....it's only images that are embeded in the email body.  We use Google Workspace and are using the Google OAuth connection

**Comment by neurit-matejka** [comment]
I have run to similar problems and it was incorrectly configured nginx.
My symptoms and checks:
* Browsers `GET` from URL `/storage/attachment/8/1/1/image.jpeg?id=7&token=...`, return 404
* Image exists on server in `/storage/app/attachment/8/1/1`
* nginx error_log has line ` open() ".../public/storage/attachment/8/1/1/image.jpeg" failed...` - that means it is served by nginx, not PHP
