### ISSUE TITLE
Customers default fields

### ISSUE THREAD

**Issue by advoenkin** [freescout-helpdesk/freescout#2671]
Hello, 

The cross buttons in the margins do not work in my customers, I circled them with a red.

And if possible, I would like to see the possibility of editing or deleting the standard customer fields.

Thank you.
![2023-02-04_162728](https://user-images.githubusercontent.com/68369599/216773094-37aedb32-10dc-4dd3-be74-5febb73991a3.png)

**Comment by freescout-helpdesk** [comment]
Click "Add an email address" or other "Add..." links first and the button will start working.

**Comment by advoenkin** [comment]
> Hello,
> 
> The cross buttons in the margins do not work in my customers, I circled them with a red.
> 
> And if possible, I would like to see the possibility of editing or deleting the standard customer fields.
> 
> Thank you. ![2023-02-04_162728](https://user-images.githubusercontent.com/68369599/216773094-37aedb32-10dc-4dd3-be74-5febb73991a3.png)

 thought this button removes the display of the field in the profile.

**Comment by advoenkin** [comment]
> Click "Add an email address" or other "Add..." links first and the button will start working.

 thought this button removes the display of the field in the profile.
