### ISSUE TITLE
Customer is coming in as an image string

### ISSUE THREAD

**Issue by bnewman-tech** [freescout-helpdesk/freescout#2672]
We have been seeing this for a couple of days. We just upgraded to version 1.8.57. 

 We now have about 200 "Customers" that are an image string. Any suggestions on why this is happening?

![Error](https://user-images.githubusercontent.com/60909819/216785778-e59c048f-6d93-4ef8-9593-213df6fd9740.jpg)
![image](https://user-images.githubusercontent.com/60909819/216785798-90ec7663-a846-4fbc-a883-7e2fd792fec4.png)

**Comment by freescout-helpdesk** [comment]
Does this happen in forwarded emails?

**Comment by bnewman-tech** [comment]
Yes it does appear to only happen when an email is forwarded to the mailbox.

**Comment by freescout-helpdesk** [comment]
Can you give an example of such email body from Show Original window (under message dropdown menu).

**Comment by bnewman-tech** [comment]
Attached is the example body. 
[example_body.txt](https://github.com/freescout-helpdesk/freescout/files/10612036/example_body.txt)

**Comment by freescout-helpdesk** [comment]
> Attached is the example body. [example_body.txt](https://github.com/freescout-helpdesk/freescout/files/10612036/example_body.txt)

Strange. This body does not produce the described issue.

**Comment by bnewman-tech** [comment]
It looks like it is using the image attachment name as the customer. 
![image](https://user-images.githubusercontent.com/60909819/217002729-6ae1f60a-103f-4d9a-ab4e-3ee3eaa4369f.png)

![Error](https://user-images.githubusercontent.com/60909819/217002578-028e945f-134c-4b98-a234-1d37c5cc56c1.jpeg)

**Comment by freescout-helpdesk** [comment]
Attachment name does not contain `@` sign. So it should be interpreted as a customer email. You'll need to debug this line: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L708

**Comment by bnewman-tech** [comment]
Yeah I agree the body does not seem to have caused the issue with that Regex line. But for some reason all forwarded emails are doing this. I checked some other email bodies and they look the same as before. I am not sure why it is picking up the image attachment name for the From field.

**Comment by ricbn96** [comment]
Same issue on our istance. seems to be a distributed problem!

**Comment by freescout-helpdesk** [comment]
> Same issue on our istance. seems to be a distributed problem!

How does the customer email look in your case? Can you share the email body?

**Comment by freescout-helpdesk** [comment]
Also both of you try to add  the following line right after https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L708
```
\Log::error('getOriginalSenderFromFwd: '.json_encode($b));
```
Fetch some problematic email, go to Manage > Logs > App Logs, find a line starting with `getOriginalSenderFromFwd: ...`, expand it, copy and post here.

**Comment by bnewman-tech** [comment]
Here is the error log, email body, and edited code. Same issue occurred. 

![Error](https://user-images.githubusercontent.com/60909819/218159651-c3cc5d2b-ea98-462c-9b3a-cf6c6a10a1e9.png)

![Code_Edit](https://user-images.githubusercontent.com/60909819/218161490-6b1de0c1-703e-415c-8ec1-e32a6b3b48ab.png)

[email_body.txt](https://github.com/freescout-helpdesk/freescout/files/10709969/email_body.txt)

**Comment by freescout-helpdesk** [comment]
Now try to replace `preg_match("/[\"'<:]([^\"'<:]+@[^\"'>:]+)[\"'>:]/", $body, $b);` line with:
```
$body = str_replace('cid:', '!', $body);
preg_match("/[\"'<:]([^\"'<:!]+@[^\"'>:]+)[\"'>:]/", $body, $b);
```

**Comment by bnewman-tech** [comment]
That has fixed the issue. I am not seeing the image name now on forward or normal emails.
Thank you!!

**Comment by ricbn96** [comment]
so, what is teh fix?

**Comment by freescout-helpdesk** [comment]
It will be released in the next release.
