### ISSUE TITLE
Admin notifications of new updates

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#2673]
Is there no way for an admin to receive an email notification of when there are new updates?

I've no idea when there are new updated to Freescout as there are no in-app notifications or emails. I only know when I manually check the System page.

**Comment by freescout-helpdesk** [comment]
https://github.blog/changelog/2018-11-27-watch-releases/

**Comment by zigojacko** [comment]
Got it, thank you. 👍
