### ISSUE TITLE
change state automatically

### ISSUE THREAD

**Issue by nfactorialbcn-arnau** [freescout-helpdesk/freescout#2674]
Hello. 

I install Freescout in a server and all is running fine but i have a question. 

I install the module "custom fields", "tags" and "Workflows".

I create in "custom fields" a new state field [new, open, pending, resolved, Close]

I need to change the status to "close" after a period of time (2 days) after "resolved" if the customer does not send any response. if the customer send a message, then the new state will be "pending". 

I try to configure "workflows" but dosen't work.

Can anybody help me? 

Thanks in advance. 

Best regards from Barcelona.

**Comment by ilyakonovalenko** [comment]
It won't work as you expect. Every workflow can only run once. So that you can get it work once the customer replies for the first time, but it will not work once the customer replies the second time and so on.

**Comment by freescout-helpdesk** [comment]
Yes, correct.

**Comment by nfactorialbcn-arnau** [comment]
Sorry, but if i have this workflow:

![Captura de pantalla 2023-02-21 a las 19 23 40](https://user-images.githubusercontent.com/60666576/220428400-55db0536-54b8-4071-a737-1c01242d4bbc.png)

i expect that if my state is "pendiente" and my last user reply is not in the last 1 hour... then do something.

The applications says:

"If automatic workflow does not contain any date-related conditions, it is executed when a new message is created or some condition's value changes (for example, conversation status changes)." but in this case there is a date-related condition. 

Also in your documentation is a very similar example. 
![Captura de pantalla 2023-02-21 a las 19 30 45](https://user-images.githubusercontent.com/60666576/220429638-17693f86-3a75-47cb-a534-7c0364bdff0b.png)

Thanks in advance for your help.

**Comment by freescout-helpdesk** [comment]
We've just checked it - it works fine.
Are you using Cloudron? Is everything OK in Manage > System

**Comment by nfactorialbcn-arnau** [comment]
I'm using:

Plesk Obsidian
Version 18.0.49 Update #2
Ubuntu 20.04.5 LTS 

All the service are running ok as you can see in the freescout console

![Captura de pantalla 2023-02-22 a las 9 51 40](https://user-images.githubusercontent.com/60666576/220570786-4b2786a3-5d52-441a-8098-77e3baee0337.png)


All the mails are retrieved correctly.

The applications and modules are all updated to the last version.

**Comment by freescout-helpdesk** [comment]
Can you show your custom field settings.

**Comment by nfactorialbcn-arnau** [comment]
![Captura de pantalla 2023-02-22 a las 10 01 28](https://user-images.githubusercontent.com/60666576/220572272-e221071a-b225-4759-86a2-fd213a0d5aa7.png)

Yes of course!!!

**Comment by freescout-helpdesk** [comment]
It works fine with dropdown custom field on our end.

Are there any errors in Manage > Logs > App Logs?

**Comment by nfactorialbcn-arnau** [comment]
No, any error. 

I only need to do an action If my client does not respond in a certain period of time.

**Comment by freescout-helpdesk** [comment]
And it's also triggers with time when "Last User Reply" is not in the last 1 hour.

If it does not happen for you, some deeper debugging may be needed (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).
