### ISSUE TITLE
Knwoledgebase visibility

### ISSUE THREAD

**Issue by dug-adm** [freescout-helpdesk/freescout#2676]
Hello everyone,

we would like to use the knowledgebase for IT internally and the rest of the employees.

now there's visibility, where you can choose whether it's free for everyone or support staff.

It's clear to everyone, but what do I get from the support staff? When I set this up, I don't see it as a logged-in user on the knowledgebase page, but only in the backend

![image](https://user-images.githubusercontent.com/124553804/216896354-7e27a231-2396-400d-bb9c-3a44eac2b78d.png)

**Comment by freescout-helpdesk** [comment]
It's not clear what you need. You have two categories of people. And there is frontend and backend. What you need to allow to each category of people.

**Comment by dug-adm** [comment]
Hello,

Thank you for your quick response.

Our problem is that I don't see these categories in the frontend even when I'm logged in as a support agent with .

Isn't there a distinction between everyone is allowed to see it and support staff?

**Comment by freescout-helpdesk** [comment]
Do you have articles in those categories?

**Comment by dug-adm** [comment]
yes.

![image](https://user-images.githubusercontent.com/124553804/216897663-209d9770-149e-4a79-8ee6-2c74faf5dcdc.png)

and if i opend the article then i bekomm this:

![image](https://user-images.githubusercontent.com/124553804/216897742-b85da75b-03fe-4108-aad4-127ac6969036.png)

**Comment by freescout-helpdesk** [comment]
Are you using custom domain for Knowledge Base?

**Comment by dug-adm** [comment]
yes. i´ve changed this

**Comment by freescout-helpdesk** [comment]
> Keep in mind that when a Custom Domain is used for the Knowledge Base categories visible to support agents only may not be visible even when support agent is logged in.

https://freescout.net/module/knowledge-base/

**Comment by dug-adm** [comment]
OK.

Thanks for the help. Will there be an adjustment here so that this also works with a custom domain?

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
