### ISSUE TITLE
Time Zone Problems 

### ISSUE THREAD

**Issue by Elos4Dope** [freescout-helpdesk/freescout#2679]
Hey, I run Freescout on Ubuntu 22.04.1 LTS
and I have the problem that no matter what timezone I take, the time will not change.
If I print out date over ssh on Ubuntu, every thing is fine and right.

![Unbenannt](https://user-images.githubusercontent.com/54165907/217005108-4244ba41-f940-422f-b575-a6f2b401a671.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/54165907/217005112-a952f028-480f-4571-b71b-815a330e0ded.PNG)

**Comment by maukunze** [comment]
i got the same problem. Timezone Etc/GMT-1 (GMT+0100) but time is always one hour behind.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-freescout-displays-incorrect-time
