### ISSUE TITLE
Add search filter/ scroll for saved replies

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#268]
When we have more than 16 saved replies, cannot scroll to see other saved replies at the bottom. The list cannot be scrolled or searched. 

<img width="457" alt="Screenshot 2019-06-11 at 11 39 14 AM" src="https://user-images.githubusercontent.com/5198092/59242297-93148500-8c3d-11e9-9c92-b5c0883bb3a7.png">

**Comment by freescout-helpdesk** [comment]
OK. It will be fixed.

**Comment by freescout-helpdesk** [comment]
It will be fixed in the next release of the module.
