### ISSUE TITLE
HTTPS not loading CSS and JS files

### ISSUE THREAD

**Issue by HazemHeakal** [freescout-helpdesk/freescout#2680]
Server : Ubuntu 22.4
php : 8.1
webserver : nginx

Hey there, 
When I'm trying to access my freescout by HTTPS i get no CSS with this error from DevTools in browser 
"Mixed Content: The page at 'https://172.16.72.128/login' was loaded over HTTPS, but requested an insecure stylesheet 'http://172.16.72.128//css/builds/b7c603c73b4916b3c8150f5f614e7b2543408293178.css'. This request has been blocked; the content must be served over HTTPS."

But with http every things going good but cannot fetch emails as it must be https to be fetched.

Please help with that.

**Comment by HazemHeakal** [comment]
![1](https://user-images.githubusercontent.com/56660650/217017399-9eccb40a-4833-4503-b5de-2fa1b6e3223d.png)
![2](https://user-images.githubusercontent.com/56660650/217017422-757802d7-c172-4532-b953-501b7a200882.png)

**Comment by HazemHeakal** [comment]
Any update here?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by HazemHeakal** [comment]
There is no solution in the troubleshooting page for this issue, Please check

**Comment by freescout-helpdesk** [comment]
Make sure you have correct APP_URL in .env file.

**Comment by HazemHeakal** [comment]
The correct protocol is in APP_URL in .env file.
I get ymthis error with https The page at 'https://172.16.72.128/login' was loaded over HTTPS, but requested an insecure stylesheet 'http://172.16.72.128//css/builds/b7c603c73b4916b3c8150f5f614e7b2543408293178.css'. This request has been blocked; the content must be served over HTTPS."

**Comment by freescout-helpdesk** [comment]
Try to clear cache: https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache

Are you using CloudFlare?

**Comment by HazemHeakal** [comment]
I do that multiple times but nothing changed.
As you can see in the above comment the request goes as HTTP, not HTTPS but the page loaded as https, and this is what makes it wired.

**Comment by freescout-helpdesk** [comment]
It means PHP thinks that the page is loaded via HTTP. If you are using using CloudFlare, try to disable it.

Find someone who https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer can figure out why PHP on your server is not aware that the page is loaded via HTTPS.

**Comment by HazemHeakal** [comment]
I don't using CloudFlare, 
It's not one page all pages in https not loading css or js as it blocked them because they fetched as http
here is my nginx confg
`server {

    listen 80;

    server_name tcs-support.com;
    root /var/www/ticket/public;
    index index.php index.html index.htm;
    error_log /var/www/ticket/storage/logs/web-server.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    # Uncomment this location if you want to improve attachments downloading speed.
    # Also make sure to set APP_DOWNLOAD_ATTACHMENTS_VIA=nginx in the .env file.
    #location ^~ /storage/app/attachment/ {
    #    internal;
    #    alias /var/www/html/storage/app/attachment/;
    #}
    location ~* ^/storage/attachment/ {
        expires 1M;
        access_log off;
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~* ^/(?:css|js)/.*\.(?:css|js)$ {
        expires 2d;
        access_log off;
        add_header Cache-Control "public, must-revalidate";
    }
    location ~* ^/(?:css|fonts|img|installer|js|modules|[^\\\]+\..*)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
    location ~ /\. {
        deny  all;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/tcs-support.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/tcs-support.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = tcs-support.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;


    server_name tcs-support.com;
    return 404; # managed by Certbot


}`

**Comment by HazemHeakal** [comment]
Here is .env
```# Every time you are making changes in .env file, in order changes to take an effect you need to run:
# php artisan freescout:clear-cache

# Application URL
APP_URL=https://tcs-support.com

# Use HTTP protocol and redirect to HTTPS
APP_FORCE_HTTPS=true

# Improve security
SESSION_SECURE_COOKIE=false

# Timezones: https://github.com/freescout-helpdesk/freescout/wiki/PHP-Timezones
# Comment it to use default timezone from php.ini
APP_TIMEZONE=Asia/Riyadh

# Default language
APP_LOCALE=en

# Database settings
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=freescout
DB_USERNAME=freescout
DB_PASSWORD="password"

# Run the following console command to generate the key: php artisan key:generate
# Otherwise application will show the following error: "Whoops, looks like something went wrong"
APP_KEY=base64:rNmPJy2gxsWtSnG9rZRmHXW+4SzElQiuUpGnfIVIycE=

# Uncomment to see errors in your browser, don't forget to comment it back when debugging finished
#APP_DEBUG=true```

**Comment by freescout-helpdesk** [comment]
1. Change this line https://github.com/freescout-helpdesk/freescout/blob/dist/config/minify.config.php#L44 to 
```
'css_url_path'   => env('APP_URL').'/css/builds/'.\Log::error('APP_URL = '.env('APP_URL')),
```

2. Add an extra line after this line https://github.com/freescout-helpdesk/freescout/blob/dist/vendor/devfactory/minify/src/MinifyServiceProvider.php#L43
```
\Log::error('minify.config.css_url_path = '.config('minify.config.css_url_path'));
```

3. Clear cache (https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache) and open FreeScout.

4. Go to `/storage/logs` on the server, find the latest laravel log and find `APP_URL = ...` and `minify.config.css_url_path = ...` in it and post here.

**Comment by HazemHeakal** [comment]
Here is the output
`\Log::error('minify.config.css_url_path = '.config('minify.config.css_url_path'));`

**Comment by freescout-helpdesk** [comment]
> Here is the output `2023-02-11 00:03:33] production.ERROR: minify.config.css_url_path = https://172.16.72.128//css/builds/ [2023-02-11 00:03:33] production.ERROR: APP_URL = https://172.16.72.128/ [2023-02-11 00:03:33] production.ERROR: minify.config.css_url_path = https://172.16.72.128//css/builds/`

URLs look fine. Try to open FreeScout and view page source code.  Search for `/css/builds/`. What URL do you have there?

**Comment by HazemHeakal** [comment]
Here are the source CSS links in the source code
`<link href="http://172.16.72.128//css/builds/b7c603c73b4916b3c8150f5f614e7b2543409098907.css" rel="stylesheet">`
Also, all links that refer to images and JS have the same links HTTP

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules?

Check errors in /storage/logs

Try to login, go to System Status page https://172.16.72.128/system/status and check if there are any errors.

**Comment by HazemHeakal** [comment]
No, all modules are official.
There is nor error rather than the 
`2023-02-11 00:03:33] production.ERROR: minify.config.css_url_path = https://172.16.72.128//css/builds/ [2023-02-11 00:03:33] production.ERROR: APP_URL = https://172.16.72.128/ [2023-02-11 00:03:33] production.ERROR: minify.config.css_url_path = https://172.16.72.128//css/builds/`
The System Status is OK for all requirements

**Comment by freescout-helpdesk** [comment]
We'll give up on trying to guess. Apparently something in Minify library is changing the protocol. The only way to figure out is to debug it on your server.

**Comment by igorhoop** [comment]
Hi everyone. I have the **same** problem.
Styles are not loaded after configuring HTTPS.

If the page was loaded over HTTPS, then for some reason the resources are loaded over HTTP.

In the browser console, the following error occurs:

```
Blocked loading mixed active content “http://example.com/css/builds/552811eceab9804ff8d211d76b95055a11982060965.css”
```

**Comment by MarioHNogueira** [comment]
So... i faced the same issue and after some research.
I solve using the setting the SITE_URL parameter to local ip
I was running over docker locally.
I hope this would be useful
