### ISSUE TITLE
UX-Issue: Loosing custom fields content when merging tickets

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2682]
**Steps to reproduce:**

1. Install modules "End-User-Portal" and "custom fields"
2. Create some custom fields and add them to your frontend portal.
3. Fill out the frontend form
-> a new ticket No.1 will be created and it will contain some data in the custom fields.
4. Now send an email to your inbox from the same email address that you used when filling out the form.
-> another ticket No.2 will be created. All custom fields will be empty in ticket No.2.
5. Open ticket No.2 and merge it with ticket No.1
-> In the merged ticket, all custom fields will be empty! So you lost the collected data from the custom fields!

**Why this is a problem:**
Loosing collected data is never a good thing. ;-)
I understand the technical logic behind it, but it is still bad UX / unexpected behaviour.

**Tried workaround (not working for me):**
Instead of starting the ticket merge from ticket No.2, I tried starting the ticket merge from ticket No.1 instead. In this case the content of the custom fields will not be lost!
Unfortunately this is **not** a solution for me, because of another UX problem:
#2681

**Questions**
Does anyone know a workaround which might work for me?
Can you fix this issue and maybe also the other UX issue #2681 which blocks me here from choosing the workaround?
Thank you!

**Comment by freescout-helpdesk** [comment]
Fixed in the Custom Fields Module v1.0.24
