### ISSUE TITLE
Feature Request: Custom Fields Module - "SelectMultipleOptionsDropdown"

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2683]
Found a bug in Custom Fields Module:
With Type "Multiselect" there is no possibility to define Multiselect Items. See Screenshots below.

![I6KJuSuI9D7QAtvt](https://user-images.githubusercontent.com/28296008/217125116-f25954a3-c43c-4e45-8e02-413a9d6b2397.png)

Browser: Firefox 109.0.1 64-Bit

**Can someone please solve this?**

**Comment by freescout-helpdesk** [comment]
It's by design. Items are added by support agents.

**Comment by freescout-helpdesk** [comment]
We'll rename "Multiselect" into something less confusing.

**Comment by ar-ml** [comment]
Ok, I see you renamed this field type to "Single Line Tags", right?
So does this mean, the Tags Module is needed for this field type to work?

**Comment by freescout-helpdesk** [comment]
> So does this mean, the Tags Module is needed for this field type to work?

No.

> (Just to clearify: What I am searching for is a possibility for the customer to select multiple predefined items from a list in the End-User Portal Form. For example: as demonstrated here in the Gravity Forms formular: https://demo.gravitywp.com/multi-select-form/)

There is no such possibility for now.

**Comment by ar-ml** [comment]
OK, that's a pitty. 
Maybe this can be added as a Feature Request:

End-User Portal Form:  Add another field type "SelectFromDorpdown" which adds the possibility for the customer to select multiple predefined items from a list in the End-User Portal Form.
Example: as demonstrated here in the Gravity Forms formular: https://demo.gravitywp.com/multi-select-form/
![grafik](https://user-images.githubusercontent.com/28296008/217273104-00b04528-eab1-46ad-ae2f-f60952b142df.png)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
