### ISSUE TITLE
Cross-Browser-Issue: End-User Portal not working in Safari, Chrome and Edge

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2684]
My freescout frontend form (End-User Portal) works fine in Firefox.
When testing it in Safari, Chrome or Edge I will get an error after sending the form. See Screenshot.

![image](https://user-images.githubusercontent.com/28296008/217126689-7765b7e6-6717-40ce-b22a-e6dcdc9a040f.png)

You can test it here:
https://teslaanwalt.de/neuerfall/

**Any ideas how to fix this?**
Or is it a bug in the End-User Portal Module?
Thx!

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue with the form from https://demo.freescout.net ?

**Comment by freescout-helpdesk** [comment]
We've checked - End-User Portal form is not supposed yet to be embedded via IFRAME. We'll try to implement this.

**Comment by freescout-helpdesk** [comment]
Possibility to embed Contact Us form via Iframe using the URL from "Open in New Window" link has been added in the End-User Portal Module v1.0.39
