### ISSUE TITLE
UX: When merging two tickets the Assignement gets lost

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2685]
**Steps to reproduce**
We have two tickets from the same sender.
Ticket No1 is assigned to me.
Ticket No2 is not assigned yet.
Now I open Ticket No2 and merge it with Ticket No1.
-> The merged ticket is not assigned anymore.

**Expected behaviour (from my point of view)**
I would expect that the merged ticket would keep its assignment to me.
Wouldn't it be better to change this behaviour?

**Comment by maukunze** [comment]
From how i understand it, the ticket you enter to merge from is the "Master" ticket and as your "Master" ticket was unassigned and you merged it, the merged ticket is unassigned.

**Comment by ar-ml** [comment]
@maukunze yes, I assume, that is the logic behind it. Logically it makes sense as it is.

Nevertheless, from a user perspective I find it irritating the way it works right now. It definitely does not feel right from an UX perspective. I think an existing assignment should be kept when merging. But maybe it's only me... ;-)

**Comment by freescout-helpdesk** [comment]
We'll keep it as it is.
