### ISSUE TITLE
Reappearing File permission problem

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2688]
Hi,
the following message keeps coming back on my system status page:

![grafik](https://user-images.githubusercontent.com/28296008/217322138-d6637573-59c7-4ec2-a44a-f37fc5263bf1.png)

Running the command sudo chown -R www-data:www-data /var/www/html in SSH only solves the problem temporarily. 
The message will re-appear soon.

**Two questions:**
1. How can I solve that permanetly?
2. Could this error be connected to the fact that I sometimes have problems forwarding tickets with attachments (attachments not being attahced correctly, or duplicated)?

Thanks a lot for your awesome support!

**Comment by freescout-helpdesk** [comment]
"Also make sure that the [cron task user](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs) or some other user is not messing up file permissions."
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by ar-ml** [comment]
thx!
My Linux admin could not find the reason why the file permission gets lost.
 
As a quick patch he created a crontask that executes
sudo chown -R www-data:www-data /var/www/html
every minute.

We'll see if that solves the issue.
