### ISSUE TITLE
Under the hood: Conversation vs. Thread?

### ISSUE THREAD

**Issue by mpdude** [freescout-helpdesk/freescout#2691]
Hey there 👋🏼,

being a PHP/Symfony developer myself, I am looking into FreeScout to see how it could replace our current helpdesk solution. One big challenge will be data migration and integration with existing other tools/processes. 

To better understand our options, can you explain what exactly a _conversation_ vs. a _thread_  is?

In the most simple case, a conversation is the "entire" thing where a customer sent an email or the conversation was started from within Freescout; and a "thread" is every single note, reply or message within that conversation. The database I am looking at might suggest that, but I have only a few simple test conversations and emails.

I am asking because in other discussion/forum software, there may be many nested/recursive threads, but that seems not to be the case here. Conversations are a sequential list of threads, is that right?

(Would be :100: acceptable for my use case and make things a lot easier to maintain.)

**Comment by freescout-helpdesk** [comment]
Conversation is the ticket. Thread is the message (note or reply).

**Comment by freescout-helpdesk** [comment]
No.

**Comment by mpdude** [comment]
Thank you for the quick responses!
