### ISSUE TITLE
action thread.attachment_append for extended attachment

### ISSUE THREAD

**Issue by e-rwan** [freescout-helpdesk/freescout#2692]
hello,
I don't think we can make pull request for module so i'm asking here
if you could consider adding an @action to sidebar_block.blade.php from the extended attachments module just like there is one to thread_attachments.blade.php

```
@foreach ($attachments as $attachment)
<li data-attachment-id="{{ $attachment->id }}" data-mime="{{ $attachment->mime_type }}">
    <a href="{{ $attachment->url() }}" class="attachment-link help-link" target="_blank"><i class="glyphicon glyphicon-paperclip"></i> {{ $attachment->file_name }} ({{ $attachment->getSizeName() }})</a>
    @action('extendedAttachments.attachment_append', $attachment, $thread, $conversation, $mailbox) {{-- this --}}
</li>
@endforeach
```

and also add some variables in the provider :
```
echo \View::make('extendedattachments::partials/sidebar_block', [
    'attachments' => $attachments,
    'thread' => $thread,
    'conversation' => $conversation,
    'mailbox' => $mailbox,
])->render();
```

thanks,
erwan.

**Comment by freescout-helpdesk** [comment]
If any hooks are needed in the core - feel free to submit a pull request.
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by e-rwan** [comment]
ok i just sent a email,,
thanks, 
erwan.
