### ISSUE TITLE
trouble with menus in app in iphone 14pro

### ISSUE THREAD

**Issue by lgnch** [freescout-helpdesk/freescout#2693]
When using menus in iphone 14pro and pro max the new apple design makes it impossible to click on head menu. The @ and back arrow symbol is obscured creating frustration for users navigating the menu system. A larger hit box is required or moving the app menu to the bottom would create a complete solution for future apple design.

**Comment by freescout-helpdesk** [comment]
Could you please attach a screenshot.

**Comment by lgnch** [comment]
![D788A8EA-7802-419D-9032-5B57BB253AD7](https://user-images.githubusercontent.com/4876162/217914397-85805301-c63f-4e97-8aa7-e21a261706e5.png)

you can see that the buttons are covered by the iPhones new header system

**Comment by ilyakonovalenko** [comment]
Not only iPhone 14. It is the same on iPhone 13. App often crashes as well so I need to unload it and open again a few times every day :-(

**Comment by ilyakonovalenko** [comment]
> Same for me on iPhone 12, the top part is covered by iphone's header system.

Unfortunately there are a lot to change and fix. In my case it also shows error about connection issue (happens if you use the app and then lock the screen), and it can only be resolved by closing the app completely and re-run it again.

**Comment by herroworrd** [comment]
Have y'all tried using a PWA version of freescout on your phones? Ignoring the obvious broken bits in the app, I find I like the PWA version better. It provides a cleaner interface and behaves more how I (I'm only one person though) think a phone app should behave.

I think there could be some improvements made to further embrace the PWA experience but those likely wouldn't come until the actual app is EOL'd.

Apple also lets you push notifications to PWA's...

https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_safari_and_other_browsers

**Comment by freescout-helpdesk** [comment]
What are your iOS versions?

**Comment by myde2001** [comment]
The same issue happens to me: I'm on 17.1

**Comment by freescout-helpdesk** [comment]
Can you please check it on a newly released FreeScout iOS App v1.0.6

**Comment by myde2001** [comment]
> Can you please check it on a newly released FreeScout iOS App v1.0.6

Can confirm is fixed
