### ISSUE TITLE
Clear cache not working

### ISSUE THREAD

**Issue by foc-pm** [freescout-helpdesk/freescout#2696]
While trying to run clear cache issue, 
`Class "Barryvdh\Debugbar\ServiceProvider" not found`

Is shown and it fails. please guide me to rectify this issue. This is happening to me in production environment.

**Comment by freescout-helpdesk** [comment]
It looks like a broken installation.

**Comment by foc-pm** [comment]
This was happening after we tried to clear cache. can you please recommend the next steps. it was working fine for last the last 10 months

**Comment by freescout-helpdesk** [comment]
Re-update FreeScout: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by foc-pm** [comment]
The update feature is not working because of this issue. will the manual update remove db and unlink the modules we purchased?

**Comment by foc-pm** [comment]
cleared items from vendor folder and it worked. thanks for the support :)
