### ISSUE TITLE
HTML & CSS Templet

### ISSUE THREAD

**Issue by Elos4Dope** [freescout-helpdesk/freescout#2697]
hey

I have bought the Customization & Rebranding Module and have problems using it correctly. Is there a kind of template that you can use as a guide.

**Comment by freescout-helpdesk** [comment]
If you need help with custom CSS - refer to https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by Elos4Dope** [comment]
i just need a basic templet wher it shows me the diferent bodys or text to change anyone ?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such template. You need CSS knowledge or see https://github.com/freescout-helpdesk/freescout/issues/2697#issuecomment-1423777755
