### ISSUE TITLE
Saving outgoing emails via "IMAP Folder To Save Outgoing Replies" does not save attachments

### ISSUE THREAD

**Issue by kovoks** [freescout-helpdesk/freescout#2699]
Hi, 

Steps:

- I received a mail with an attachment. 
- I choose more->forward from the menu. 
- A composer appeared to enter the body and to address. It clearly showed the attachment above the editor.
- Entered an emailaddress and some text, sent the mail. 
- We received an email notification that the Issue was replied to, it contained the attachment:
![2023-02-09 10 47 37](https://user-images.githubusercontent.com/5298235/217777946-f32ab15a-37fd-425d-a6f4-92af66127b4e.jpg)
- After looking at the outgoing mail to the customer itself, the attachment was not in the mail (there is only a html content part)
![message source](https://user-images.githubusercontent.com/5298235/217778844-ae570075-c567-4599-9720-0090889e4d11.png)

So, it seems that forwarding a mail with an attachment does not forward the attachment itself in the outgoing mail.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Are you using the latest FreeScout version?

**Comment by kovoks** [comment]
We are running 1.8.56, one minor behind. 
Could it be related to the xml-based attachment?

**Comment by freescout-helpdesk** [comment]
Maybe you receiving mail server rejected xml attachment. Try some other type of attachment.

**Comment by kovoks** [comment]
As I wrote, the email notification we received as users did contain the attachment.

Is the routine that saves the message in the configured 'IMAP Folder To Save Outgoing Replies' from the mailbox setting a separate routine than the actual message being sent? If so, maybe the storing of the outgoing reply has this bug and not so much the message that was actually sent?

**Comment by maukunze** [comment]
Maybe check your "Sent" or "Sent Items" folder. On our site  Freescout always sends the outgoing mails to the standard sent folder and then to the Folder specified in "IMAP Folder To Save Outgoing Replies".
In the normal send folder the mails are stored with attachments, in the other specified folder the mails are stored without the attachments.

**Comment by freescout-helpdesk** [comment]
Receiving mail server may cut out unwanted attachment.
Creating an email in "IMAP Folder To Save Outgoing Replies" does not affect the process of sending an email.

**Comment by freescout-helpdesk** [comment]
We've got it. You are checking email not in the recipient's mailbox, but in your mail server's "Sent" folder.
"IMAP Folder To Save Outgoing Replies" - this option does not add attachments to saved emails yet. But the recipient receives emails with attachments.

**Comment by kovoks** [comment]
Indeed. Confirmed this now. 

So, this way of creating an archive of outgoing mails is not the right way, it looses the attachments and therefor it is not a valid archive.

I guess I will change from using PHP's mail() function for outgoing mails to using SMTP and hope the mail-server then stores this in the Sent mailbox.

Thanks for helping. I leave it to you to close as wontfix or leave it open to fix this. Not sure this is intended and/or wanted (in any case it is unexpected and the setting should have warning / note).

**Comment by freescout-helpdesk** [comment]
> I guess I will change from using PHP's mail() function for outgoing mails to using SMTP and hope the mail-server then stores this in the Sent mailbox.

It won't help. We'll see what can be done.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

**Comment by kovoks** [comment]
Thank you, tested and fixed indeed. Thanks for the professional help and quick fix. Very impressed.
