### ISSUE TITLE
False error Error fetching email

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#270]
`Jun 13, 09:30:07 | Error fetching email | Error: Mailbox is empty; File: /srv/users/helpdesk/apps/helpdesk/app/Console/Commands/FetchEmails.php (151) | 
-- | -- | -- | --
`

This is being logged as error every time cron runs. I guess Mailbox empty is not an error.

**Comment by freescout-helpdesk** [comment]
Apparently your IMAP server returns "Mailbox is empty" as error. Which IMAP server are you using?

**Comment by sam-suresh** [comment]
GSuite/Google Apps
