### ISSUE TITLE
[Feature request]: Auto login for links in telegram notification

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2700]
Hi team,

I have the following modules installed:

- Auto Login Module
- Telegram Notifications Module

It would be cool if users automatically authenticate into the FreeScout accounts when following the conversation number link in the telegram notification.
For emails, it works just like a charm...

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
