### ISSUE TITLE
Manage > Modules - Broken?  Screen says Whoops, something went wrong? 

### ISSUE THREAD

**Issue by Flairevents** [freescout-helpdesk/freescout#2703]
Wondering if you could help.  Today I went to open our modules list to actually buy a new feature - the screen says 'whoops, something went wrong. Check Login/logs/storage -  Can anyone give me guidance what am i looking for?

**Comment by maxkvbn** [comment]
Inside the storage folder on your site, you have a logs folder.
This folder contains "all" the logs you need to see.

Most likley you need to view the log which has the name of the current date, and paste it here.

**Comment by Flairevents** [comment]
Hi Is this what you mean? I found the error – and paste it here?

Thank you in advance for your time.

Clare




.[cid:iconenoboarder_baf1e23b-87c6-4723-a5fd-68b7e55c10c3.png]  .[cid:058_line_9bae9502-1e3a-48a3-ba5e-34ed9cd44185.png]        Clare Peckham  |  CEO & Founder
T 0161 241 2441 | M 077696 51678
E ***@***.***>***@***.*** | <http://www.yourdomain.url/> www.eventstaffing.co.uk<https://www.eventstaffing.co.uk/>
T15 The Adelphi Mill • Bollington • SK10 5JB
[cid:group4549_5a48b116-d831-49a9-8d88-e64fb19d9c1b.png]<https://www.instagram.com/flaireventstaffing/> [cid:group4550_2c8ef426-d904-44d3-82ae-0d7eaf9b175a.png] <https://twitter.com/flaireventstaff?lang=en>  [cid:group4551_76340d54-139b-4bec-8ccf-232c7f0f0ae6.png] <https://www.facebook.com/flaireventstaffinglimited/>  [cid:group4552_b9451d61-f801-48db-af0a-e3fe156b9ed3.png] <https://www.linkedin.com/company/flair-event-staffing-ltd>
<https://www.pinterest.com/user_name_here>
[cid:flairpeople(2)_28419ea1-31da-40ee-98be-88591ca3c904.png]


E-MAIL DISCLAIMER This email and any attachments is intended solely for the addressee and may contain information that is confidential, proprietary and/or legal privileged. Please let me know if this email
 is not for you, please delete it completely from your computer system, please don’t copy, forward or store unless as stated you are the intended recipient. Whilst all reasonable care has been taken to avoid
transmission of viruses and bugs, the responsibility falls on the recipient to ensure that onward transmission, once opening does not adversely affect its systems or data. This email message is being sent to
you on behalf of Flair People Ltd which is a Registered in Scotland with company NO: SC453179 and has a registered office at T15 The Adelphi Mill, Bollington, SK10 5JB..

**Comment by freescout-helpdesk** [comment]
This error is not related to the Modules page.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
