### ISSUE TITLE
Telegram notification: 	API error: Bad Request: message is too long

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2705]
Hi Team,
we use the Telegram Notification Module (1.0.7)  to inform people of newly arrived tickets. 
It throws an error (API error: Bad Request: message is too long) when the message is too long.

This should not happen. Instead, the message should be truncated at the maximum possible length (maybe append '....' to indicate that there is more info) and sent off to Telegram

**Comment by freescout-helpdesk** [comment]
Fixed in Telegram Notifications Module v1.0.8
