### ISSUE TITLE
OAuth & Social Login module login error 

### ISSUE THREAD

**Issue by pabloctc** [freescout-helpdesk/freescout#2706]
In my organisation we bought the OAuth & Social Login module to log in with google sso. 

The problem is that when we log in, we get the following errors:

- Console error

```
[2023-02-09 11:14:20] production.ERROR: Call to undefined function Modules\OauthLogin\Http\Controllers\curl_init() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Modules\\OauthLogin\\Http\\Controllers\\curl_init() at /var/www/html/Modules/OauthLogin/Http/Controllers/OauthLoginController.php:34)
[stacktrace]
```

- Error when accessing the web
![image](https://user-images.githubusercontent.com/125025150/218072433-4bc76c1a-2314-450c-b454-6eeddf72b10e.png)

The version of FreeScout we are using is **1.8.57**

Why is this happening?

**Comment by freescout-helpdesk** [comment]
Are there any errors in Manage > System in "PHP Extensions" section?

**Comment by pabloctc** [comment]
Everything is correct, except for the following:

- PHP Extensions

`cURL: Not found`

- Permissions

```
storage/framework/cache/data/: Unable to write file found
/var/www/html/storage/framework/cache/data/85/2a/852af25182886d05af91be2a70b87c39cb4c88be
```

**Comment by freescout-helpdesk** [comment]
Install PHP's curl extension and fix permissions issue: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
