### ISSUE TITLE
Updating modules without updating core.

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2707]
Hello.

We're experiencing some issues with CustomFields 1.0.13 and Workflows 1.0.24, [see this](https://github.com/freescout-helpdesk/freescout/issues/2518), as such, we wanted to update them to the newest version.
However, our core version (FreeScout) is only 1.8.11.

Do you see any potential issues in upgrading the modules, without upgrading the core?

Thanks for the help so far. 👍

**Comment by freescout-helpdesk** [comment]
You'll need to update FreeScout also, as they require newer FreeScout version.
