### ISSUE TITLE
Customer management - best practices 

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2708]
Hi team,

I'm not sure whether this is the right place to ask. But as there doesn't seem to be a general forum I will just try my luck...

My question is wrt to customer management. I understand that the email address is unique and once a customer was created under a particular email address, its contact details are kind of "cast in stone".

How do you go about, if different contacts use the same email address like info@.....
Any variables in canned replies will only pick the details from the contact who opened the first ticket and hence may or may not insert the correct contact details.

Any best practise?

**Comment by freescout-helpdesk** [comment]
> How do you go about, if different contacts use the same email address like info@.....

In FreeScout two customers can not have the same email.
