### ISSUE TITLE
Telegram Notifications Module: impossible to update to 1.0.8

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2709]
It is impossible to update Telegram Notifications Module to 1.0.8. 
An error is "Failed to create folders". Absolutely nothing in app logs.

![изображение_2023-02-12_001437016](https://user-images.githubusercontent.com/63669538/218283307-b405cc10-1f94-46f4-866a-2f86c8141772.png)

**Comment by freescout-helpdesk** [comment]
Debug ModulesController.php: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ModulesController.php#L513

**Comment by ilyakonovalenko** [comment]
Well, I have no way to debug it as I don't have source ZIP to unzip it. Other modules are updating just fine.

**Comment by freescout-helpdesk** [comment]
Remove and install again the module. Comment `try` and `catch` to get the full error message in Manage > Logs > App Logs.

**Comment by freescout-helpdesk** [comment]
Here is the error message you are receiving: https://github.com/freescout-helpdesk/freescout/blob/dist/vendor/chumper/zipper/src/Chumper/Zipper/Zipper.php#L167

Zipper can not create some folder. It means you have an issue with permissions in Modules folder: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by andy-a2c** [comment]
In my case it was not permission issue but problem with recursive symlink
```
# ls -la /var/www/freescout/Modules/Telegram/Public
lrwxrwxrwx 1 www-data www-data 42 Dec  8 18:17 /var/www/freescout/Modules/Telegram/Public -> /var/www/freescout/Modules/Telegram/Public
```
After I removed symlink (`rm /var/www/freescout/Modules/Telegram/Public`) I was able to update plugin and it created normal directory by path /var/www/freescout/Modules/Telegram/Public

**Comment by ilyakonovalenko** [comment]
> In my case it was not permission issue but problem with recursive symlink

Yes, you are correct. It is the same here. I have seen such things before with other modules.
So it is actually a thing someone may need to investigate to prevent this from happening.
