### ISSUE TITLE
Bug: [Email sent. View or Undo]

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#271]
_Version:_ 
FS 1.1.8

_Description:_ 
When an email is sent and click "View" from the [Email sent. View or Undo] pop up, it returns to email composing screen. And shows email as draft. However the email is actually sent. 

_How to reproduce;_
1. Compose new email and Click send
2. In the  [Email sent. View or Undo] pop up, click view. 
3. It will open email composing screen

_Problem;_
Email is sent but going back to editing screen.
Email shows as draft in fact already sent.
No email ticket created although email is sent.

_Expected result:_
When click **View** from [Email sent. View or Undo] pop up, it should show the sent mail ticket.

**Comment by freescout-helpdesk** [comment]
Which browser are you using?
