### ISSUE TITLE
white label module - not fully white labeling the application

### ISSUE THREAD

**Issue by aj-saini** [freescout-helpdesk/freescout#2710]
Hi Freescout team, 

I just wanted to point out, The above module is not white labeling the title tag in the php page and rest of the website as well,

sudo nano /var/www/html/resources/views/layouts/app.blade.php

as you can see  - https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/layouts/app.blade.php

    <title>@if ($__env->yieldContent('title_full'))@yield('title_full') @elseif ($__env->yieldContent('title'))@yield('title') - {{ config('app.name', 'FreeScout') }} @else{{ config('app.name', 'FreeScout') }}@endif</title>

it shows the "freescout" I was under the impression white label would - show my company name 
    
https://freescout.net/module/white-label/

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
Also list other places where you want to see your company name.
