### ISSUE TITLE
In the message preview, lines without spaces are displayed

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#2711]
![image](https://user-images.githubusercontent.com/77854832/218295618-7126446b-68c3-47b0-8203-cfea506c74eb.png)

```html
<p class="conv-preview">The first lineThe second line</p>
```

![image](https://user-images.githubusercontent.com/77854832/218295304-3fd0dcca-e6fc-4f8e-b1fb-217085203480.png)

![image](https://user-images.githubusercontent.com/77854832/218295521-e3b9e46c-7608-43bb-afa9-2fc5a79b8c09.png)

FreeScout 1.8.58

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
