### ISSUE TITLE
Make validation of SMTP SSL/TLS certificate optional

### ISSUE THREAD

**Issue by JesperLK-Witt** [freescout-helpdesk/freescout#2714]
Hi, wouldn't it be nice if the validation of SMTP SSL/TLS certificate became an option?
Every time we update we have to manually edit 
/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php
and comment $options[] under "private function establishSocketConnection()"
and put this instead:
$options['ssl'] = array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true);

Yes yes - the right way was to get the certificate right at the SMTP end and it will at some point, but why not make it an optional setting? :-)

Great new week :-)
Jesper

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.
