### ISSUE TITLE
Print original HTML mail

### ISSUE THREAD

**Issue by ragman-mw** [freescout-helpdesk/freescout#2715]
Hi together,
is it possible to create a Button in original HTML view, to print only the content from the Mail. We have a table inside the mail, that only can be printed when i select the text and open the print dialogue. This workaround only work's in Edge and Safari.

Or maybe a button "Print original Message" after "Print" within the dropdown.

Thx for your reply.

![Bildschirmfoto 2023-02-13 um 10 03 55](https://user-images.githubusercontent.com/124563960/218415914-aa1059f8-dc55-45f9-90c3-e0bf6cbfee24.png)

**Comment by freescout-helpdesk** [comment]
Unfortunately this can't be done due to security reasons - original message can't be shown without a special `iframe`. And if it will be shown in the `iframe` when printing long messages they will be cropped.

**Comment by ragman-mw** [comment]
Okay, thank's for your reply.
