### ISSUE TITLE
[Feature Request] All Modules bundle

### ISSUE THREAD

**Issue by 12nick12** [freescout-helpdesk/freescout#2717]
Hi, I'm starting to use FreeScout and like it so far. I think it would be great if there was some option to purchase all modules for a discounted price. Looks like all modules right now are ~$500. I would love a $250 price tag, but even just 10% off would be awesome, that way also we can just hit a single buy bundle button instead of each item individually.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans.
https://freescout.net/modules-faq/#do-you-offer-bulk-discounts-do-you-offer-discount-for-nonprofits
