### ISSUE TITLE
Android Mobile Push Notifications Not Working

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2718]
Hey,
I have Freescout installed on my Android phone and tablet. Everything works perfectly except for Android Push Notifications.

I get notifications on my windows browser and by text.

Everytime a push notification comes through the android app crashes. I though it was my phone, but I got a new phone and its still not working. Pretty much the same. The app crashes when the push notifications come through and nothing shows up.

Tech Specs:
Samsung Galaxy S23
Android Version 13
&
Samsung Galaxy Tab S7
Android Version 12
&
Google Pixel 7 Pro
Android Version 13

![Screenshot_20230213_015137](https://user-images.githubusercontent.com/99109793/218548356-8f9aeac3-28ad-4f52-99f1-17cce5034f48.png)
![Screenshot_20230213_015200](https://user-images.githubusercontent.com/99109793/218548368-47295d48-2ccf-4411-8b15-1549df14f02e.png)

**Comment by freescout-helpdesk** [comment]
We've made some adjustments in the FreeScout app (v1.0.15) for Android. Please check it.

**Comment by SecureCPU** [comment]
I upgraded to 1.0.15, unfortunately I get the same.
I'm not sure how to check any looks or error for the app, but it still crashed when anotification came through.

**Comment by SecureCPU** [comment]
![Screenshot_20230216_023856_Device care.jpg](https://user-images.githubusercontent.com/99109793/219364830-61957a71-db74-4e73-bd9f-61cc9c27ba5a.jpg)

**Comment by freescout-helpdesk** [comment]
Fixed in the FreeScout app (v1.0.16) for Android.

**Comment by SecureCPU** [comment]
Thank you so much!!!
The Push Notifications started working perfectly once I updated the app to v1.0.16
