### ISSUE TITLE
Assigned count not showing

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#272]
While there is few tickets assigned for few people, there is no count showing for Assigned. 

<img width="243" alt="Screenshot 2019-06-13 at 5 25 42 PM" src="https://user-images.githubusercontent.com/5198092/59420976-69578b80-8e00-11e9-97ad-802ea814b198.png">

**Comment by freescout-helpdesk** [comment]
Number shows number of activee (ananswered) conversations.
