### ISSUE TITLE
Users cant login after latest update

### ISSUE THREAD

**Issue by maukunze** [freescout-helpdesk/freescout#2720]
Hello, 
i have installed the latest update of Freescout 1.8.59 and after the update when the Users login they get the following error message:
Whoops something went wrong. Check /storage/logs
In the logs the only thing i could find was that:
production.ERROR: strtr(): Passing null to parameter #1 ($string) of type string is deprecated (View: /var/www/html/resources/views/users/partials/web_notifications.blade.php)
I had to revert to a snapshot to get it working again.

**Comment by freescout-helpdesk** [comment]
Please post the full error message.
