### ISSUE TITLE
how to merge customers with no email address

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2722]
I have two newly created customers without email addresses. They are a result of creating a new conversation (phone call) for which email addresses are optional.

Now I wanted to merge them. I understand that if email addresses are identical customer records will be merged. So, I added an email address to the first record and saved it. However, when I added the same email address to the other record this message window pops up: "Customer saved successfully. Email petra.pan@blabla.de has been moved from another customer: [firstName lastName]."

How can Ithey be merged?

**Comment by freescout-helpdesk** [comment]
> I understand that if email addresses are identical customer records will be merged.

Only email is being moved in this case, no other user data is copied/moved.

**Comment by boehmgui** [comment]
what is the procedure to merge customers then - if there is any

**Comment by freescout-helpdesk** [comment]
Only manually.

**Comment by boehmgui** [comment]
can you please elaborate on "manually"? 
Is it like copying/pasting all info over to the target customer and then mapping all conversations from the "old" customer to the new one?
Any plans to implement merge functionality?

**Comment by freescout-helpdesk** [comment]
> Only email is being moved in this case, no other user data is copied/moved.

Correction: email and conversations are being moved.

**Comment by boehmgui** [comment]
hmmmm.....
this seems to work only if one customer had an email address from the beginning (at creation time). If both customers were created with no email address, e.g. in the course of creating a phone conversation, only the email address is moved but not the conversations.

As such the behavior is not conclusive

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. Now it should work.
