### ISSUE TITLE
 Allowed memory size exhausted & Module is already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by atakan72** [freescout-helpdesk/freescout#2723]
Hello I have 3 problems 

1. I get in the log these errors I have already looked in the php.ini and these modules are not duplicated there

```
**fetch-emails.log**
29 | PHP Warning: Module "pdo_mysql" is already loaded in Unknown on line 0
28 | PHP Warning: Module "mysqli" is already loaded in Unknown on line 0

**queue-jobs.log**
29 | PHP Warning: Module "pdo_mysql" is already loaded in Unknown on line 0
28 | PHP Warning: Module "mysqli" is already loaded in Unknown on line 0
27 | PHP Warning: Module "xmlreader" is already loaded in Unknown on line 0
26 | PHP Warning: Module "Phar" is already loaded in Unknown on line 0
25 | PHP Warning: Module "pdo_pgsql" is already loaded in Unknown on line 0
24 | PHP Warning: Module "mysqlnd" is already loaded in Unknown on line 0
23 | PHP Warning: Module "exif" is already loaded in Unknown on line 0
22 | PHP Warning: Module "zip" is already loaded in Unknown on line 0
21 | PHP Warning: Module "xmlwriter" is already loaded in Unknown on line 0

```
2. in the laravel.log is the following error which I can't get fixed.

```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 10928296 bytes) {"userId":1,"email":"admin@era-tec.de","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 10928296 bytes) at /www/html/overrides/webklex/laravel-imap/src/IMAP/Message.php:812)
[stacktrace]
#0 {main}
"}
```

4. under tools i can only import unread mails and when i try to click on all i get a message that something failed.
probably this is related to the 2. point.

**Comment by freescout-helpdesk** [comment]
It looks like there is a very big attachment in one of the emails. Increase `memory_limit` in PHP or delete that email from your mailbox.

**Comment by freescout-helpdesk** [comment]
How does the error message look now?

**Comment by atakan72** [comment]
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 2768176 bytes) {"userId":1,"email":"admin@era-tec.de","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 2768176 bytes) at /www/html/vendor/webklex/laravel-imap/src/IMAP/Attachment.php:138)`

and

`
29 | PHP Warning: Module "pdo_mysql" is already loaded in Unknown on line 0
28 | PHP Warning: Module "mysqli" is already loaded in Unknown on line 0
27 | PHP Warning: Module "xmlreader" is already loaded in Unknown on line 0
26 | PHP Warning: Module "Phar" is already loaded in Unknown on line 0
25 | PHP Warning: Module "pdo_pgsql" is already loaded in Unknown on line 0
24 | PHP Warning: Module "mysqlnd" is already loaded in Unknown on line 0
23 | PHP Warning: Module "exif" is already loaded in Unknown on line 0
22 | PHP Warning: Module "zip" is already loaded in Unknown on line 0
21 | PHP Warning: Module "xmlwriter" is already loaded in Unknown on line 0
`

**Comment by freescout-helpdesk** [comment]
Memory limit is the same (134217728 bytes) as in the previous error message. Are you sure you've properly set `memory_limit`? Check `phpinfo();` and keep in mind that console PHP may use a different php.ini.

**Comment by atakan72** [comment]
i have searched with `find / -name "php.ini" ` for the php.ini there are 3 results found in all i have changed the `memory_limit`

**Comment by atakan72** [comment]
![image](https://user-images.githubusercontent.com/74542485/218826296-15c17e88-2657-4a69-b3d9-a436fd9275f9.png)
apparently it has not been changed the question is where can i change it now is there maybe an environment variable for it?

**Comment by atakan72** [comment]
it also says that the file (`/etc/php81/php.ini`) i changed is the configuration file 
```
Configuration File (php.ini) Path => /etc/php81
Loaded Configuration File => /etc/php81/php.ini
Scan this dir for additional .ini files => /etc/php81/conf.d
Additional .ini files parsed => /etc/php81/conf.d/00-bcmath.ini,
/etc/php81/conf.d/00-bz2.ini,
/etc/php81/conf.d/00-ctype.ini,
/etc/php81/conf.d/00-curl.ini,
/etc/php81/conf.d/00-dom.ini,
/etc/php81/conf.d/00-fileinfo.ini,
/etc/php81/conf.d/00-gd.ini,
/etc/php81/conf.d/00-iconv.ini,
/etc/php81/conf.d/00-imap.ini,
/etc/php81/conf.d/00-intl.ini,
/etc/php81/conf.d/00-ldap.ini,
/etc/php81/conf.d/00-mbstring.ini,
/etc/php81/conf.d/00-opcache.ini,
/etc/php81/conf.d/00-openssl.ini,
/etc/php81/conf.d/00-pdo.ini,
/etc/php81/conf.d/00-pgsql.ini,
/etc/php81/conf.d/00-session.ini,
/etc/php81/conf.d/00-simplexml.ini,
/etc/php81/conf.d/00-tokenizer.ini,
/etc/php81/conf.d/00-xml.ini,
/etc/php81/conf.d/00-xmlwriter.ini,
/etc/php81/conf.d/00-zip.ini,
/etc/php81/conf.d/01-exif.ini,
/etc/php81/conf.d/01-mysqlnd.ini,
/etc/php81/conf.d/01-pdo_pgsql.ini,
/etc/php81/conf.d/01-phar.ini,
/etc/php81/conf.d/01-xmlreader.ini,
/etc/php81/conf.d/02-mysqli.ini,
/etc/php81/conf.d/02-pdo_mysql.ini,
/etc/php81/conf.d/10-igbinary.ini,
/etc/php81/conf.d/20-apcu.ini,
/etc/php81/conf.d/20-gnupg-gnupg.ini,
/etc/php81/conf.d/99-smtp.ini,
/etc/php81/conf.d/99-timezone.ini,
/etc/php81/conf.d/mongodb.ini
```

**Comment by atakan72** [comment]
![image](https://user-images.githubusercontent.com/74542485/218828157-266b4880-d8af-4373-a5d6-df316c2d8d9f.png)

now it should be changed or unfortunately still comes this error 

`Allowed memory size of 134217728 bytes exhausted (tried to allocate 3625680 bytes) {"userId":1,"email":"admin@era-tec.de","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 3625680 bytes) at /www/html/overrides/webklex/laravel-imap/src/IMAP/Message.php:812)`

**Comment by atakan72** [comment]
> phpinfo()

![image](https://user-images.githubusercontent.com/74542485/219143828-f06499e8-f7b9-4119-9657-33dab560ca63.png)

you were right but how can i increase the `memory_limit` i can't find another `php,ini` file

**Comment by freescout-helpdesk** [comment]
Check here https://github.com/tiredofit/docker-freescout/issues or find someone who can do it for you on your server: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
