### ISSUE TITLE
Mailbox Access for Team is removed after edit Mailbox Permissions

### ISSUE THREAD

**Issue by Bergrad** [freescout-helpdesk/freescout#2724]
PHP: 8.2.
Freescout: 10.8.60
Teams Module:  1.0.11

Hi,

If I change in Mailbox Permissions the Access Settings (Hide from Assign list or). All Mailbox Access Settings in the Teams will be removed.

I think this is not a feature.

Regards Alfred

**Comment by freescout-helpdesk** [comment]
Can you please attach some screenshots.

**Comment by Bergrad** [comment]
![Bildschirm­foto 2023-02-14 um 15 08 23](https://user-images.githubusercontent.com/124269798/218762679-3d5bebc5-77c9-4994-831f-162e42dd4342.png)

Before editing

**Comment by Bergrad** [comment]
![Bildschirm­foto 2023-02-14 um 15 09 30](https://user-images.githubusercontent.com/124269798/218762858-c7c6ad3c-6f2d-415c-a4d7-09acae695c6c.png)

After Editing and save

**Comment by Bergrad** [comment]
![Bildschirm­foto 2023-02-14 um 15 10 01](https://user-images.githubusercontent.com/124269798/218762985-aee3a089-fa03-4b0d-90de-6552a8aafc41.png)

After Saving: Mailbox Access in all Teamfolder are unset

**Comment by freescout-helpdesk** [comment]
It will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in Teams Module v1.0.12
