### ISSUE TITLE
Possible SPAMming on End-User Portal

### ISSUE THREAD

**Issue by GPeti07** [freescout-helpdesk/freescout#2726]
Is it possible to configure for "End-User Portal" to don't send "login link email" to those e-mails that is not in the database, so to those e-mail adresses who never sent us e-mail before (have no connected ticket to that e-mail), and also show this "error" (example: no ticket connected to this e-mail) for the customer who requested a login link?

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
