### ISSUE TITLE
LDAP and Custom fields sync

### ISSUE THREAD

**Issue by GPeti07** [freescout-helpdesk/freescout#2727]
In the LDAP module there is possible to sync more fields? Currently only the Email, First name, Last name is available for this. Could we add custom fields here somehow? We would like to sync Job Title and Phone Numbers too, and maybe more fields in the future.

**Comment by freescout-helpdesk** [comment]
Possibility to sync Job Title and Phone Number has been added in Ldap Module v1.0.23.

For synchronization of custom user fields feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by ro0p** [comment]
It looks good, but it seems the attributes in the drop-down lists are filtered, and the required LDAP attributes are not in the lists. I cant find any settings about this.

Are there any rule or setting leading to missing attributes?
Im not sure, but maybe a simple input box would be better instead of select.

Thank you

**Comment by freescout-helpdesk** [comment]
Set Job Title and Phone Number for some user in your LDAP and check again.

**Comment by ro0p** [comment]
We have, and use them in other apps for years.
ipPhone, mobile, title and some more, and all of them are missing from the lists.

**Comment by freescout-helpdesk** [comment]
Have you tried to reconnect to LDAP?

**Comment by ro0p** [comment]
You mean the Connect & Fetch Attributes button? No change.
The only different thing is that there is no empty item in the lists after reconnecting. So all values are filled with an attribute, and cannot set to empty (no binding).

How does this module fetch the attributes? As I can see the example attributes in brackets are come from a random user in Bind DN tree. This DN contains only technical accounts without any phone, title etc. attributes. The real users are in different tree.
Can it be a problem?

**Comment by ro0p** [comment]
Please reopen this issue because attribute mapping is not working as expected
