### ISSUE TITLE
Decrease Starred folder counter when discarding starred draft fixed, but counter not fixed

### ISSUE THREAD

**Issue by GPeti07** [freescout-helpdesk/freescout#2728]
In version 1.8.57 you fixed this issue: "Decrease Starred folder counter when discarding starred draft."
What is the best way to fix the already bugged counter?

**Comment by freescout-helpdesk** [comment]
There is no easy way. Only by writing a special script.

**Comment by GPeti07** [comment]
Could you help in this script, what kind of script running when we delete a starred conversation? Or it is possible to change or delete these "false" DB starred connection records to fix this counter?

**Comment by freescout-helpdesk** [comment]
Maybe someone will prepare such script.
