### ISSUE TITLE
emails can not be opened 

### ISSUE THREAD

**Issue by atakan72** [freescout-helpdesk/freescout#2729]
Hello, when I open the mails I get the following error:

`Uncaught Error: Typed property DOMElement::$tagName must not be accessed before initialization
in /www/html/vendor/symfony/var-dumper/Caster/DOMCaster.php:193
Stack trace:
#0 /www/html/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(295): Symfony\Component\VarDumper\Caster\DOMCaster::castElement(Object(DOMElement), Array, Object(Symfony\Component\VarDumper\Cloner\Stub), false, 1)
#1 /www/html/vendor/symfony/var-dumper/Cloner/VarCloner.php(187): Symfony\Component\VarDumper\Cloner\AbstractCloner->castObject(Object(Symfony\Component\VarDumper\Cloner\Stub), false)
#2 /www/html/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(234): Symfony\Component\VarDumper\Cloner\VarCloner->doClone(Object(DOMElement))
#3 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(169): Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Object(DOMElement), 1)
#4 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(208): Whoops\Util\TemplateHelper->dump(Object(DOMElement))
#5 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/frame_code.html.php(40): Whoops\Util\TemplateHelper->dumpArgs(Object(Whoops\Exception\Frame))
#6 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#7 [internal function]: Whoops\Util\TemplateHelper->Whoops\Util\{closure}('/www/html/vendo...', Array)
#8 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#9 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/panel_details.html.php(1): Whoops\Util\TemplateHelper->render('/www/html/vendo...')
#10 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#11 [internal function]: Whoops\Util\TemplateHelper->Whoops\Util\{closure}('/www/html/vendo...', Array)
#12 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#13 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/panel_details_outer.html.php(2): Whoops\Util\TemplateHelper->render('/www/html/vendo...')
#14 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#15 [internal function]: Whoops\Util\TemplateHelper->Whoops\Util\{closure}('/www/html/vendo...', Array)
#16 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#17 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/layout.html.php(24): Whoops\Util\TemplateHelper->render('/www/html/vendo...')
#18 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#19 [internal function]: Whoops\Util\TemplateHelper->Whoops\Util\{closure}('/www/html/vendo...', Array)
#20 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#21 /www/html/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php(295): Whoops\Util\TemplateHelper->render('/www/html/vendo...')
#22 /www/html/vendor/filp/whoops/src/Whoops/Run.php(370): Whoops\Handler\PrettyPageHandler->handle(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#23 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(339): Whoops\Run->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#24 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(313): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithWhoops(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#25 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(286): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#26 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#27 /www/html/app/Exceptions/Handler.php(53): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#28 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#29 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#30 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#31 {main}
  thrown {"userId":1,"email":"admin@era-tec.de","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught Error: Typed property DOMElement::$tagName must not be accessed before initialization in /www/html/vendor/symfony/var-dumper/Caster/DOMCaster.php:193
Stack trace:
#0 /www/html/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(295): Symfony\\Component\\VarDumper\\Caster\\DOMCaster::castElement(Object(DOMElement), Array, Object(Symfony\\Component\\VarDumper\\Cloner\\Stub), false, 1)
#1 /www/html/vendor/symfony/var-dumper/Cloner/VarCloner.php(187): Symfony\\Component\\VarDumper\\Cloner\\AbstractCloner->castObject(Object(Symfony\\Component\\VarDumper\\Cloner\\Stub), false)
#2 /www/html/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(234): Symfony\\Component\\VarDumper\\Cloner\\VarCloner->doClone(Object(DOMElement))
#3 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(169): Symfony\\Component\\VarDumper\\Cloner\\AbstractCloner->cloneVar(Object(DOMElement), 1)
#4 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(208): Whoops\\Util\\TemplateHelper->dump(Object(DOMElement))
#5 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/frame_code.html.php(40): Whoops\\Util\\TemplateHelper->dumpArgs(Object(Whoops\\Exception\\Frame))
#6 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#7 [internal function]: Whoops\\Util\\TemplateHelper->Whoops\\Util\\{closure}('/www/html/vendo...', Array)
#8 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#9 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/panel_details.html.php(1): Whoops\\Util\\TemplateHelper->render('/www/html/vendo...')
#10 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#11 [internal function]: Whoops\\Util\\TemplateHelper->Whoops\\Util\\{closure}('/www/html/vendo...', Array)
#12 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#13 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/panel_details_outer.html.php(2): Whoops\\Util\\TemplateHelper->render('/www/html/vendo...')
#14 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#15 [internal function]: Whoops\\Util\\TemplateHelper->Whoops\\Util\\{closure}('/www/html/vendo...', Array)
#16 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#17 /www/html/vendor/filp/whoops/src/Whoops/Resources/views/layout.html.php(24): Whoops\\Util\\TemplateHelper->render('/www/html/vendo...')
#18 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(250): require('/www/html/vendo...')
#19 [internal function]: Whoops\\Util\\TemplateHelper->Whoops\\Util\\{closure}('/www/html/vendo...', Array)
#20 /www/html/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php(248): call_user_func(Object(Closure), '/www/html/vendo...', Array)
#21 /www/html/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php(295): Whoops\\Util\\TemplateHelper->render('/www/html/vendo...')
#22 /www/html/vendor/filp/whoops/src/Whoops/Run.php(370): Whoops\\Handler\\PrettyPageHandler->handle(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#23 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(339): Whoops\\Run->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#24 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(313): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionWithWhoops(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#25 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(286): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#26 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#27 /www/html/app/Exceptions/Handler.php(53): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#28 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#29 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#30 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#31 {main}
  thrown at /www/html/vendor/symfony/var-dumper/Caster/DOMCaster.php:193)
[stacktrace]
#0 {main}
"}`

**Comment by freescout-helpdesk** [comment]
Are you using a docker? https://github.com/freescout-helpdesk/freescout/issues/2704#issuecomment-1427416273

**Comment by atakan72** [comment]
yes

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2712#issuecomment-1430130381
