### ISSUE TITLE
Lost all icons after last update 1.1.9

### ISSUE THREAD

**Issue by itinmind** [freescout-helpdesk/freescout#273]
Hello, just upgraded FreeScout to 1.1.9 and I lost all icons... Clear cache on the app and on server, upgrade to PHP 7.3, clear browser cache and tried on Chrome and Safari (MAC user) same issue... Anybody got the same problem? Thanks
<img width="1680" alt="Screen Shot 2019-06-17 at 12 08 30" src="https://user-images.githubusercontent.com/7705121/59622340-4af2d800-90ff-11e9-9ad4-8afd76cda90b.png">

**Comment by freescout-helpdesk** [comment]
Updating process finished without errors?
Can you provide your server configuration? Operating system?
Can you send screenshot of the Network tab of the browser debugger (F12).

**Comment by itinmind** [comment]
Thanks!
1 - no issue during update, went smoothly.
2 - App Version | 1.1.9    Check for updates
HTTPS
Apache/2.4.10 (Debian) on Cloudways server - Php 7.3 
PHP 7.3.1-1+0~20190113101844.25+jessie~1.gbp15aaa9
3 - see screenshot! Good one! Fonts are missing...
<img width="1674" alt="Screen Shot 2019-06-17 at 14 13 35" src="https://user-images.githubusercontent.com/7705121/59626539-26502d80-910a-11e9-9813-a48d3f47aa32.png">

**Comment by freescout-helpdesk** [comment]
It looks like you are missig the following symlinks or they are not working:

https://github.com/freescout-helpdesk/freescout/blob/dist/public/css/img
https://github.com/freescout-helpdesk/freescout/blob/dist/public/css/fonts

**Comment by itinmind** [comment]
Thanks but how I can recreate then? I am not a developer and a beginner with Freescout. Maybe a doc online I can follow?

**Comment by snazzypants** [comment]
Just wanted to comment that I have the same problem. Started using FreeScout a few months ago, and the icons just started to show up blank after the update to 1.1.9 this morning as well.

**Comment by freescout-helpdesk** [comment]
Which updating method did you use (https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout)?

**Comment by itinmind** [comment]
I used the automatic update, I cleared Cache, tried to Migrate DB but nothing happened.
Inside both folders, there is files and I compared it with the freescout zip file and they are identical.
<img width="305" alt="Screen Shot 2019-06-18 at 07 43 50" src="https://user-images.githubusercontent.com/7705121/59679591-4250df00-919d-11e9-929f-6648eb0c9b50.png">

**Comment by itinmind** [comment]
Ok so the 2 folders were missing, I uploaded them, clear cache but same issue...
<img width="1188" alt="Screen Shot 2019-06-18 at 08 12 02" src="https://user-images.githubusercontent.com/7705121/59681149-3830df80-91a1-11e9-9338-f91be06ec11a.png">

**Comment by freescout-helpdesk** [comment]
The issue will be fixed in the next release.

**Comment by itinmind** [comment]
Thanks! Any idea when the next release is scheduled? Also, in the meantime, how I can fix this issue?

**Comment by freescout-helpdesk** [comment]
In a few days. Download the following CSS files from `master` branch and clear cache:

https://github.com/freescout-helpdesk/freescout/blob/master/public/css/style.css
https://github.com/freescout-helpdesk/freescout/blob/master/public/css/fonts.css
https://github.com/freescout-helpdesk/freescout/blob/master/public/css/bootstrap.css

**Comment by itinmind** [comment]
Thanks. It worked. :)
<img width="1401" alt="Screen Shot 2019-06-18 at 13 51 42" src="https://user-images.githubusercontent.com/7705121/59707395-8a3d2980-91d0-11e9-9710-06843d60dded.png">
