### ISSUE TITLE
Unhelpful Error Message when E-Mail in Mail Settings is not properly set up

### ISSUE THREAD

**Issue by theAkito** [freescout-helpdesk/freescout#2730]
Was trying to figure out, why an invite mail to a new user wouldn't work out. No logs showed any error.
The error in the GUI log just said "Send error", rather than explaining, what the actual error is.

Then, I realised I have to set up the mail in the Mail Settings. I thought, I had already set it up, but it was actually only for the Administrator.

It would help a lot, if the error would just tell the user to set up or repair the configuration on the Mail Settings page!

### Related Issues
* https://github.com/freescout-helpdesk/freescout/issues/738
* https://github.com/freescout-helpdesk/freescout/issues/1958

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.
