### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Kyle-McCahon** [freescout-helpdesk/freescout#2731]
This is not an issue but more a cry for help...

Im wanting to know if this is possible please.

I have been running Freescout and am so impressed, we are wanting to take this to the next level,
So basically I would like to have all my company support emails going through one email address, The support staff assign the tickets to the relevant people but what I am wanting to do is have technicians on my freescout account too but I do not want them to see any tickets other than the ones assigned to them or their team but at the same time if they reply, I would like the emails to go out Via the support email address.

Any help would be greatly appreciated.
Thank you in advance for your assistance

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such possibility and no plans to implement.
