### ISSUE TITLE
Mail spoofing in ticket

### ISSUE THREAD

**Issue by pabloctc** [freescout-helpdesk/freescout#2733]
Good morning,
In my organisation we have configured gmail email accounts to receive tickets, the thing is that if someone forwards the email that receives the tickets from an existing thread it impersonates the origin of the email and not the one that forwards the email.

Is this behaviour normal?

**Comment by freescout-helpdesk** [comment]
Ca you give some screenshots.

**Comment by pabloctc** [comment]
For privacy reasons I can't provide a screenshot as there is corporate data. However, this is what I am telling you. 

The most usual is to open a ticket from your email client and write a support email to the associated freescout email and the freescout panel creates an incident in the name of the user who sent it. So far so good, isn't it?

Now the thing is that sometimes in my organisation they send support emails from an existing thread and the initial thread does not correspond to the person who sent the ticket, so the problem is that if someone forwards the email from an existing thread freescout creates it in the name of the person who started the thread and not in the name of the person who sent it.

That's why I ask if this behaviour is normal and if it can be corrected.

**Comment by freescout-helpdesk** [comment]
> The most usual is to open a ticket from your email client and write a support email to the associated freescout email and the freescout panel creates an incident in the name of the user who sent it. So far so good, isn't it?

Still not very clear. In FreeScout clients contacting the support are called customers.

> Now the thing is that sometimes in my organisation they send support emails from an existing thread and the initial thread does not correspond to the person who sent the ticket, so the problem is that if someone forwards the email from an existing thread freescout creates it in the name of the person who started the thread and not in the name of the person who sent it.

Write a step-by-step instruction allowing to reproduce it.

**Comment by pabloctc** [comment]
Reproduction of the steps:

1. As user "Pablo" I forward the email of the user "Alex" that he has sent me in CC to the associated email that is in freescout (support@myorganization.com). I have done this because the email that the user "Alex" has sent me in CC contains all the information and I avoid having to send a new email.
2. Once the user "Pablo" has sent the incident to the email associated to freescout, I go to the freescout administration panel and I see that the ticket is not in the name of the user "Pablo", but in the name of the user "Alex" who is the original owner of the email thread.

**Comment by pabloctc** [comment]
user = customer
email client = Gmail

**Comment by avenjamin** [comment]
@pabloctc are either Pablo or Alex also admins of your FreeScout server?

There are two scenarios:

1. A `User` (aka admin) forwards an email to the FreeScout server
2. A `Customer` forwards an email to the FreeScout server

Currently when a `User` (aka admin) forwards an email, FreeScout tries to find the original sender in the body. (This is good)
When a `Customer` forwards an email, FreeScout should use the value of the From header as the sender.

If you log into FreeScout as an admin using the same email address that you also forwarded the email from then the first scenario will be occurring.

Hope that helps clarify ?

**Comment by pabloctc** [comment]
The user Pablo is an administrator, but alex is not.  What happens is that it doesn't matter if a user is an administrator or not, scenario 1 always occurs.

**Comment by freescout-helpdesk** [comment]
Maybe this will help: https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-this-customer
