### ISSUE TITLE
Error: Failed to parse time

### ISSUE THREAD

**Issue by atakan72** [freescout-helpdesk/freescout#2734]
hello,
i have installed Freescout as docker and as `env ` i have taken `- TIMEZONE=Europe/Berlin` but i get this error: `[Webklex\IMAP\Message] Error: Failed to parse time string ( mailDate) at position 0 (m): The timezone could not be found in the database; File: /www/html/overrides/nesbot/carbon/src/Carbon/Carbon.php (548)`

**Comment by freescout-helpdesk** [comment]
Try to find the full error message in Manage > Logs > App Logs

**Comment by atakan72** [comment]
![image](https://user-images.githubusercontent.com/74542485/219357755-a4460693-7e7b-4bc5-bb25-7fed9146e7dc.png)
this is the full massage

**Comment by freescout-helpdesk** [comment]
This is more a warning. When it happens the email is still being successfully fetched.
