### ISSUE TITLE
Contact Form Widget, change the button image

### ISSUE THREAD

**Issue by MaximEdelink** [freescout-helpdesk/freescout#2735]
Hello! Please tell me, our company has purchased the End User Portal module and we want to embed a feedback form (Contact Form Widget) into our website. But we would like to change the picture of the button of this widget itself:
![image](https://user-images.githubusercontent.com/125574304/219383886-66527819-a4b8-47fe-bf98-915dbbd9db7e.png)

In the description of the End User Portal module, I found related information:
"You can adjust widget position or z-index on your website using CSS. Widget button element is #fsw-btn and widget window element is #fsw-iframe."

Do I understand correctly that we will be able to change the logo of this button only by purchasing the Customization module? Or is it possible to replace the picture without this module?

Once again I want to thank you for such a wonderful product!

**Comment by freescout-helpdesk** [comment]
The only what to change this icon is to modify module's files.
