### ISSUE TITLE
Slack Module - To Freescout

### ISSUE THREAD

**Issue by andreamichelon** [freescout-helpdesk/freescout#2737]
Hi, just running some tests with Freescout and Slack. I was wondering if is possible to create a ticket from a Slack message, like Halp: https://www.atlassian.com/software/halp

What I mean is: be able to send a message to Freescout from Slack where the content of the message is ‘a message in the channel’ that upon a trigger (Halo use the ticket emoji) it sends the message to Freescout.

Thank you in advance for the support

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Here is the place for feature requests: https://freescout.net/request-feature/
