### ISSUE TITLE
Free scout Workflows

### ISSUE THREAD

**Issue by eliseflair** [freescout-helpdesk/freescout#2738]
None of my workflows work. From what i can see myself and a colleague have set them up correctly. Could someone help with what the issue might be please?

**Comment by ilyakonovalenko** [comment]
Send screenshots and expected behaviour please.

**Comment by eliseflair** [comment]
![image](https://user-images.githubusercontent.com/125659538/219655916-094643bc-6167-4810-b6d4-40fc14f25bfe.png)
![image](https://user-images.githubusercontent.com/125659538/219655964-0a29607b-1ecc-468a-b7f0-0113095c604b.png)
![image](https://user-images.githubusercontent.com/125659538/219656010-88a64e27-a83e-4c8b-b604-2c4bc472e9d8.png)


Emails coming back into the inbox are not tagged, do not assign to user OR file away in custom folder
![image](https://user-images.githubusercontent.com/125659538/219656180-4c5c1935-313b-4bae-bc53-a24019e0e423.png)


This is the same for most of my workflows

**Comment by eliseflair** [comment]
I have quite afew issues with our account. Emails incoming state my name even though the email is not from me and i havent been connected to it. 

![image](https://user-images.githubusercontent.com/125659538/219658254-dcc7feab-9c17-4008-9cf5-d2d908f5abf5.png)

**Comment by eliseflair** [comment]
We are also not receiving all emails which is worrying.

**Comment by ilyakonovalenko** [comment]
> Emails coming back into the inbox are not tagged, do not assign to user OR file away in custom folder

It it because of incorrect conditions. It should compare subjects with OR, not AND, because conversation can not have TWO different subjects at the same time.

**Comment by eliseflair** [comment]
Ok. Please see below:
![image](https://user-images.githubusercontent.com/125659538/219665706-b6761b9f-b5f0-4111-b3e9-e319452273c2.png)

![image](https://user-images.githubusercontent.com/125659538/219665931-221e34dd-d05d-446d-8ee9-cf26c33c3725.png)


i have emails with subject P45 in unnassigned and not in the custom folder

**Comment by freescout-helpdesk** [comment]
At what moment are you expecting this workflow to trigger?
