### ISSUE TITLE
error while updating Module Telegram Notifications 

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#2739]
Got an error while updating Module Telegram Notifications Version: 1.0.7 => 1.0.8
App Version | 1.8.60
Error message: `Failed to create folders`
Log:
`Cache cleared successfully.
Nothing to migrate.
Error occurred creating [/var/www/html/public/modules/telegramintegration] symlink: symlink(): No such file or directory
The [/var/www/html/public/modules/telegramintegration] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js`

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-error-occurred-creating--symlink-symlink-no-such-file-or-directory

**Comment by sau7777** [comment]
All permissions are ok (www-data:www-data)
There are existing dead symlinks in `/var/www/html/public/modules`
`lrwxrwxrwx 1 www-data www-data 37 April 23  2021 telegram -> /var/www/html/Modules/Telegram/Public
lrwxrwxrwx 1 www-data www-data 48 April 23  2021 telegramintegration -> /var/www/html/Modules/TelegramIntegration/Public`

**Comment by freescout-helpdesk** [comment]
`/var/www/html/Modules/Telegram/Public` folder does not exist?

**Comment by sau7777** [comment]
> `/var/www/html/Modules/Telegram/Public` folder does not exist?

yes, it doesn't exist

**Comment by freescout-helpdesk** [comment]
Try to reinstall the module.

**Comment by freescout-helpdesk** [comment]
The original error you had was related to `telegramintegration`. Do you have a `Public` folder in `/var/www/html/Modules/TelegramIntegration/`?
