### ISSUE TITLE
Class 'Helper' not found

### ISSUE THREAD

**Issue by a2d8a4v** [freescout-helpdesk/freescout#274]
Hello, @freescout-helpdesk , Thank you for help me last time.
This time, I try another fresh installation with the latest 1.1.0 version of freescout with Apache 2.4.39 connecting with php-fpm, Nginx 1.15.2 as reserve proxy server and PHP 7.3.6.

I think this issue might have relationship with larveral, and I put the error logs below here.

`
[2019-06-22 11:25:20] production.ERROR: Class 'Helper' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Helper' not found at /var/www/mailserver/config/translation-manager.php:14)
[stacktrace]
#0 /var/www/mailserver/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(71): require()
#1 /var/www/mailserver/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#2 /var/www/mailserver/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#3 /var/www/mailserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#4 /var/www/mailserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#5 /var/www/mailserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#6 /var/www/mailserver/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#7 {main}
"} 
`

![螢幕快照 2019-06-22 上午11 27 05](https://user-images.githubusercontent.com/17486472/59958918-ac8cbb00-94e0-11e9-91e9-61ac182ab348.jpg)

Thank you for reading my long question!

**Comment by freescout-helpdesk** [comment]
Which installation method are you using https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#8-installing-the-application ? Web installer or manual?

**Comment by freescout-helpdesk** [comment]
Copy https://github.com/freescout-helpdesk/freescout/blob/master/config/translation-manager.php to `/config/translation-manager.php` and try again.

**Comment by a2d8a4v** [comment]
Wow ! After change the file, The Installation ran again! Thank you for your help!
