### ISSUE TITLE
CC users do not get admin replies notifications

### ISSUE THREAD

**Issue by imennodenis** [freescout-helpdesk/freescout#2740]
Hello!

It's a pretty often situation for us when a user sends a ticket and adds one or several CC users to his ticket (right in a **To** field or **CC** field of an email which creates ticket). This is really needed when a ticket is related to several users and they all need to see admins replies or they need to provide some additional information regarding a ticket.

But now when admin replies to such ticket (through a web interface or through an email) only the ticket initiator gets email notifications. Is it an expected behavior or am I doing something wrong?

And I haven't found any additional module to fix such situation.
It seems I can only add CC users manually when I reply through web interface, but that's very unhandy.

Thanks!

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

**Comment by imennodenis** [comment]
Wow! That was fast :)
Now it works as it should.
Thanks a lot!
