### ISSUE TITLE
Add "Following" folder

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2742]
I want to add a folder called "Following" to show followed conversations.
I've implemented 99% of it in my own fork: See https://github.com/avenjamin/freescout/commit/7124b024f652d0f4459df3eadd47308212bcce02

![Screenshot 2023-02-19 at 9 12 15 pm](https://user-images.githubusercontent.com/869534/219941751-a466d863-f8cf-4602-bc84-56b3d6b8f7c8.png)

My only issue at the moment is getting the folder to be added to the `folders` table for existing users.
I have to manually add a row for each user with type set to `26` (which is the value I gave to Folder::TYPE_FOLLOWING https://github.com/avenjamin/freescout/blob/master/app/Folder.php#L17)

Please let me know if you have any feedback or clues how best to add the folders.

I looked at Mailbox.php -> createUsersFolders() function but that skips existing users.
As does the User.php->syncPersonalFolders()  function.

Can I create a database migration that does this or should they only be used for modifying the schema?

**Comment by freescout-helpdesk** [comment]
It can be done via migration.

**Comment by avenjamin** [comment]
MIgration created and tested and working. PR created: https://github.com/freescout-helpdesk/freescout/pull/2744
