### ISSUE TITLE
Working nginx config for a subdirectory install

### ISSUE THREAD

**Issue by EugeneDae** [freescout-helpdesk/freescout#2747]
According to #1005 and #1610 FreeScout supports subdirectory installation (e.g. `https://example.com/freescout/` instead of `https://freescout.example.com`), however if I use [the nginx config from the Installation Guide](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#61-nginx) I cannot get nginx to serve static files without breaking FreeScout's routing.

Here's my current nginx config:
```
server {
    ...
    
    root /var/www/freescout/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

...and here's what it gets me:
![01](https://user-images.githubusercontent.com/980835/219974083-40d60dcf-a271-46d0-be27-b2881f23aa11.png)
![02](https://user-images.githubusercontent.com/980835/219974082-c283e2f3-6fe1-4bb0-90ef-7c01e3f31a54.png)

This is what I've tried:
```
server {
    ...
    root /var/www/freescout/public;
    index index.php index.html;

    location /freescout {
        alias /var/www/freescout/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        include fastcgi_params;
    }
}
```

It fixes static files but breaks the routing:
![03](https://user-images.githubusercontent.com/980835/219974630-bafffd4b-df48-4cfd-a219-2399909775bd.png)
![04](https://user-images.githubusercontent.com/980835/219974637-b87cf29f-ef86-487f-8bdd-58bbb62bb753.png)

Interestingly, in this case (if I clear the cookies) `/freescout/login/` works correctly:
![05](https://user-images.githubusercontent.com/980835/219974932-7f69de45-b679-48f3-8ffc-12a204c2be46.png)

(The `APP_URL` parameter in the `.env` file is set correctly).

I'm thinking I need a `rewrite` somewhere, but I wonder what is the recommended way of solving this? Any tips would be appreciated.

**Comment by freescout-helpdesk** [comment]
What's your APP_URL value?

**Comment by EugeneDae** [comment]
> What's your APP_URL value?

`APP_URL=https://my.domain.io/freescout`

Without the trailing slash, but if I add it, it makes no difference.

**Comment by EugeneDae** [comment]
This seems to work:

```
server {
    ...

    location /freescout {
        alias /var/www/freescout/public;
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }
}
```

**Comment by freescout-helpdesk** [comment]
Thanks. Can you share your full nginx config, so that we can add it to the Installation Guide.

**Comment by EugeneDae** [comment]
@freescout-helpdesk 

This is almost full configuration that I'm using right now, without `server_name` and SSL stuff, and I don't know yet how to adapt other "locations" from the Installation Guide (`location ~* ^/storage/attachment/` etc). That's why I asked if there's an official recommendation.

Seeing my installation is new and clean, I'd like to test it more. Meanwhile I suggest that you link this issue in the Installation Guide.
