### ISSUE TITLE
LDAP Module - PHP error 

### ISSUE THREAD

**Issue by jjs-josh** [freescout-helpdesk/freescout#2748]
I recently installed the LDAP extension module in my helpdesk project, now whenever i navigate to the login page at my-domain/login i encounter an error message stating 'something went wrong — check logs in /storage/logs' when i navigate to the application logs i see the following error message (see attached
<img width="1076" alt="log" src="https://user-images.githubusercontent.com/125841199/220007900-80a48a98-044a-4167-b72f-547ac390c850.PNG">
 file) what is casuing this error and how should i rectify the issue. 
Please note i am running php8.2

**Comment by avenjamin** [comment]
Function utf8 _encode() is deprecated in PHP 8.2 /var/www/html/Modules/Ldap/Overrides/AdIdap/Laravel/Middleware/WindowsAuthenticate.php on line 197

Article here about possible changes one can make:
https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated

**Comment by freescout-helpdesk** [comment]
Fixed in LDAP Module v1.0.27

**Comment by jjs-josh** [comment]
Hi 

Considering i am unable to enter the web portal how would i update the LDAP module from the server. i am running ubuntu version 22.04

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-application-or-module-is-not-working-after-installing-a-module or downgrade PHP to 8.0 or lower, update the module and upgrade back to PHP 8.2
