### ISSUE TITLE
IMAP Folder outgoing reply

### ISSUE THREAD

**Issue by mhktc** [freescout-helpdesk/freescout#2749]
Hello,

since the last update for the function "IMAP Folder To Save Outgoing Replies" where now attachments are included in those messages, the function doesnt really work. 
I tested it with a test email and from 25 mails i send out only 1 was redirected to the specified IMAP Folder for outgoing replies. The other ones couldnt be found anywhere else as nothing is stated in the Logs. The normal Outgoing Mail was always recieved by the "Customer" (Test E-Mail-Address) so there is no problem.
The thing is i want to save the outgoing replies in the Inbox, so that i always have the full Thread in my Inbox and dont have to search in the Sent Folder for what i have written to a customer.
Is there something i can do about this or is this how the function should behave?

**Comment by freescout-helpdesk** [comment]
> I tested it with a test email and from 25 mails i send out only 1 was redirected to the specified IMAP Folder for outgoing replies.
The saved email had no attachments and other 24 - had attachments?

**Comment by freescout-helpdesk** [comment]
Also are you using a modern OAuth IMAP authentication or regular IMAP authentication?

**Comment by mhktc** [comment]
No, i out of 25 mails only one mail has been successfully put in my Inbox with the Feature "IMAP Folder To Save Outgoing Replies". 
![grafik](https://user-images.githubusercontent.com/125896661/220275741-fd3760e4-cdf2-4bd4-ab7c-7cc2aeb229ee.png)

Im using regular IMAP Authentication.

**Comment by freescout-helpdesk** [comment]
> The saved email had no attachments and other 24 - had attachments?

**Comment by mhktc** [comment]
No the one mail which was successfully put into the INBOX Folder had the attachment but thats not the point. The point is that this feature doesnt work on a regular basis so that a can rely on it.

**Comment by freescout-helpdesk** [comment]
Saving attachments feature has been added recently. So most likely your issue is related to this.
All of 24 non-saved emails had attachments?

**Comment by mhktc** [comment]
no thats the thing. the "non-saved" werent saved in the inbox and so i cant find them in my IMAP-Account only in freescout itself where they were written.

**Comment by mhktc** [comment]
yes they all had attachments.

**Comment by freescout-helpdesk** [comment]
What mail service are you using?

Are there any errors in Manage > Logs > App Logs?

**Comment by mhktc** [comment]
we are using Exchange server on premise.
In the App Logs nothing is shown and i just tested it now.

**Comment by freescout-helpdesk** [comment]
If you have access to the Exchange server logs - check them also. Maybe your mail server blocks saving emails with some attachments by type or size.

What are the types and sizes of attachments in non-saved emails?

**Comment by mhktc** [comment]
i just tested again, i think its just the PDF Format which causes this Problem, i tested it also with JPEG and PNG Files and with them it works.
But when i save then as default in the Sent Folder they dont get "blocked".
Sizes of the PDF Files are around 18KB - 50KB.
