### ISSUE TITLE
The Timezone list is not a full match as PHP document.

### ISSUE THREAD

**Issue by nczz** [freescout-helpdesk/freescout#275]
As title.
PHP document: [List of Supported Timezones](https://www.php.net/manual/en/timezones.php)

**Comment by freescout-helpdesk** [comment]
All existing time zones are currently listed. Do you experience any issues with timezones?

**Comment by nczz** [comment]
Hi @freescout-helpdesk 
I can't find my timezone `Asia/Taipei` at all. Please check it.

**Comment by freescout-helpdesk** [comment]
GMT +08:00

**Comment by nczz** [comment]
Hi @freescout-helpdesk 
I know GMT+8 already. But I am not at Hong Kong.

**Comment by freescout-helpdesk** [comment]
It does not matter, jut choose any option with GMT +08:00
