### ISSUE TITLE
Tiny cosmetic inconsistency in the rightmost part of the navbar in macOS

### ISSUE THREAD

**Issue by EugeneDae** [freescout-helpdesk/freescout#2750]
Google Chrome 109.0.5414.119
FreeScout 1.8.60

![Screen-Shot-2023-02-21-at-00 11 13](https://user-images.githubusercontent.com/980835/220211461-0b117c55-8de7-44ce-9831-fbd27aa576f6.png)

A 2px offset only visible in hovered state. The other two buttons also have 1px offset.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue in any browser.

![2023-02-21_09-08-28](https://user-images.githubusercontent.com/40499291/220261760-0c3d80ac-61db-421e-b5d0-edc1847b6992.png)

**Comment by EugeneDae** [comment]
I can reproduce it in macOS in Firefox and Chrome, but not Safari.

But I cannot reproduce it in Firefox on Windows.

Seems to be a macOS thing.

**Comment by ilyakonovalenko** [comment]
> I can reproduce it in macOS in Firefox and Chrome, but not Safari.

Can not reproduce on macOS in Chrome.

**Comment by freescout-helpdesk** [comment]
@EugeneDae Do you have any customizations in the top menu? Custom logo, style adjustments, etc?

**Comment by EugeneDae** [comment]
@freescout-helpdesk Nothing at all, I've just installed FreeScout.

@ilyakonovalenko Would you mind to check it in my installation if I send you the account details?

**Comment by ilyakonovalenko** [comment]
> Would you mind to check it in my installation if I send you the account details? (privately)

Sure. https://t.me/ikonovalenko

**Comment by ilyakonovalenko** [comment]
@freescout-helpdesk Checked with Eugene. I can also reproduce the issue on my instance as well as on official demo instance. 

Left dropdowns are 50px:
![изображение_2023-02-22_212541276](https://user-images.githubusercontent.com/63669538/220737391-a7b603d0-c9cf-4afa-940a-e5e93140454b.png)

Right dropdown is 48-49px:
![изображение_2023-02-22_212652568](https://user-images.githubusercontent.com/63669538/220737658-e21fcb18-9cc4-46c0-bae7-c713dbd10520.png)

**Comment by freescout-helpdesk** [comment]
Not a big issue. If someone will find a solution, feel free to share it.
