### ISSUE TITLE
Attachments with umlauts in file name missing in the fetched thread

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2753]
Hello.

Today we received an email with 5 attachments but freescout showed only 2 of them. The only thing I noted is that the file names of the missing ones, contain umlauts. I tried to reproduce this with thunderbird as client but it worked as expected. After comparing the customer and my test email, I noted one difference that might be the issue. There was a difference in the way the file names are encoded in the structure header.

customer email (not working)

`Content-Type: image/jpeg; 
	name*=UTF-8''F%C3%BChrerschein%20R%C3%BCckseite.jpg
Content-Transfer-Encoding: base64
Content-Disposition: attachment; 
	filename*=UTF-8''F%C3%BChrerschein%20R%C3%BCckseite.jpg`

my test email (working)

`Content-Type: image/jpeg;
 name="=?UTF-8?Q?F=c3=bchrerschein_Vorderseite=2ejpeg?="
Content-Disposition: attachment;
 filename*0*=UTF-8''%46%C3%BC%68%72%65%72%73%63%68%65%69%6E%20%56%6F%72%64;
 filename*1*=%65%72%73%65%69%74%65%2E%6A%70%65%67
Content-Transfer-Encoding: base64`

Sorry that the actual given name differs but that shouldn't bother I think. I can't share you the original eml file since it contains sensitive data.

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Are you using the modern Microsoft OAuth IMAP authentication or regular IMAP authentication?

**Comment by sofl88** [comment]
The regular authentication.

**Comment by sofl88** [comment]
I was able to create an eml file that reproduces the issue with the demo installation.

![image](https://user-images.githubusercontent.com/12407767/220415714-e4965a3c-878d-4b0e-83ea-2b197634c5d4.png)

The eml content with 2 attachments (one is missing, both are visible in other clients)

https://gist.github.com/sofl88/abaed6bb7fe58ca027779d9bedf4be6b

**Comment by freescout-helpdesk** [comment]
Try to add the following to .env file and clear cache: `APP_NEW_FETCHING_LIBRARY=true`
And try to fetch the email again.

**Comment by sofl88** [comment]
That worked but now the filename is "undefined"

**Comment by freescout-helpdesk** [comment]
Please send one such email to support@freescout.net

**Comment by sofl88** [comment]
Done.

**Comment by freescout-helpdesk** [comment]
We've made some changes. The file name now will look like this:

![2023-02-22_09-42-05](https://user-images.githubusercontent.com/40499291/220543107-5e0571a1-eb0a-4ea4-a422-423468bde17d.png)

It's not perfect yet. Hopefully with time maintainers of the https://github.com/Webklex/php-imap library will find a solution to fix it.

**Comment by cluster15** [comment]
Hi,

I have the very same problem here, although Freescout is on 1.8.80 now, and to me it seems like the fix is already in place here. Do I need to do something actually get it going?

What I found out is, that the problem is actually connected to the way the filenames are encoded in the mime-part.

Thunderbird encodes it as: 
`Content-Type: application/pdf; name="=?UTF-8?B?w5xtbGF1dC5wZGY=?="
Content-Disposition: attachment;
 filename*=UTF-8''%C3%9C%6D%6C%61%75%74%2E%70%64%66
Content-Transfer-Encoding: base64`

which simply works. 

While the two webmailers (Roundcube, below and Horde similar) here encode it as 

`--=_8c70127d10aebcbbac492d6ccfefe820
Content-Transfer-Encoding: base64
Content-Type: application/pdf;
 name*=UTF-8''%C3%9Cmlaut.pdf
Content-Disposition: attachment;
 filename*=UTF-8''%C3%9Cmlaut.pdf;
 size=7306`

which does not work. 

Without Umlaut the encoding by Roundcube is:

`--=_f68cc6d5b1fb05e12005bb22772dd902
Content-Transfer-Encoding: base64
Content-Type: application/pdf;
 name=Umlaut.pdf
Content-Disposition: attachment;
 filename=Umlaut.pdf;
 size=7306`

and works as expected. 

Any idea, what could be going wrong here?

Best regard,
  Stefan

**Comment by freescout-helpdesk** [comment]
@cluster15 Send a screenshot of broken attachment name.

**Comment by cluster15** [comment]
There is no broken attachment name, it simply looks, like there is nothing attached to be shown (attached is a screenshot of the message view, below you find the body-part of the message). 

![NoAttachmentA](https://github.com/freescout-helpdesk/freescout/assets/19330010/24bb6e17-8106-478b-95d4-f24e90ed8866)

Here is the mime message body up to the start of the attachment itself, drectly from the imap-server, via thunderbird:

`Content-Type: multipart/mixed;`
` boundary="=_8c70127d10aebcbbac492d6ccfefe820"`

`--=_8c70127d10aebcbbac492d6ccfefe820`
`Content-Transfer-Encoding: 7bit`
`Content-Type: text/plain; charset=US-ASCII;`
 `format=flowed`

`test4`
`--=_8c70127d10aebcbbac492d6ccfefe820`
`Content-Transfer-Encoding: base64`
`Content-Type: application/pdf;`
 `name*=UTF-8''%C3%9Cmlaut.pdf`
`Content-Disposition: attachment;`
` filename*=UTF-8''%C3%9Cmlaut.pdf;`
` size=7306`

**Comment by cluster15** [comment]
PS: The attachments name is "Ümlaut.pdf "

**Comment by cluster15** [comment]
Hi, 
I applied the patch - in the hope it actually runs -  but that changes nothing looking at the code, the regexp in the surrounding will not match the encoded filename (the minimum matching string would look like "=?.?Q?.?=" with either Q or B in the middle). I admit, I did not have a look at the environment in which that if lives, but for me it does solve the problem. 

Best regards,
  Stefan

**Comment by cluster15** [comment]
I just upgraded to 1.8.81 and unfortunately the the problem persists. Any hint where I could start debugging the code?

**Comment by freescout-helpdesk** [comment]
> I just upgraded to 1.8.81 and unfortunately the the problem persists. Any hint where I could start debugging the code?

Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file?

**Comment by cluster15** [comment]
At the moment neither.

**Comment by cluster15** [comment]
After updating to 1.8.83, the problem is solved. Thanks a bunch.
