### ISSUE TITLE
curl error 7 when activating module behing http proxy

### ISSUE THREAD

**Issue by xiamaz** [freescout-helpdesk/freescout#2755]
When attempting to activate a freescout module behind an http proxy, we receive an curl error. 

The following error is shown in a popover:
```
cURL error 7: Failed to connect to freescout.net port 443 after 5 ms: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

This seems to be caused by https://github.com/freescout-helpdesk/freescout/blob/2a52506a2ce95cdca43997dd64a66c06773516b5/app/Misc/Helper.php#L761 not using Proxy settings as defined by `APP_PROXY`.

**Comment by freescout-helpdesk** [comment]
Try to add an extra line after line 769:
```
            $client->request('GET', $url, [
                'sink' => $destinationFilePath,
                'timeout' => 300, // seconds
                'connect_timeout' => 7,
                'proxy' => config('app.proxy' ), // add this
            ]);
```

**Comment by xiamaz** [comment]
Thanks. This fix works. Would be great if this fix could be mainlined!
