### ISSUE TITLE
Genereal suggestion | Best practice

### ISSUE THREAD

**Issue by aj-saini** [freescout-helpdesk/freescout#2757]
I would like to know where/how are everyone else using free scout,

we tried using it in production but too many fetch email errors happening all time randomly

can someone please share their best configuration/setup for example
we tried AWS lightsnails, in house proxmox servers hypervisor and also docker containers - they are have fetching errors delay or just very slow,
our email provider is msft office 365,

can someone please share production level setup which is reliable and best practices so that we can that shot overall i really like the freescout interface and powerful modules

But i just need help someone point me in the right direction

Thank you

**Comment by freescout-helpdesk** [comment]
What kind of errors are you having?

**Comment by aj-saini** [comment]
![image](https://user-images.githubusercontent.com/123153952/220556808-9a18a11e-9c00-46b8-95c8-94987c05564c.png)
![image](https://user-images.githubusercontent.com/123153952/220556858-80d6782d-47fd-4e61-a9b4-f53e958b0be1.png)

**Comment by aj-saini** [comment]
![image](https://user-images.githubusercontent.com/123153952/220557047-211bad1d-639f-4533-8097-5501920ed0fe.png)

**Comment by aj-saini** [comment]
Hi freescout-helpdesk team,

Please see the errors above, can you please also tell me the optimal recommended setup where you find people have least amount of errors, recommended hosting provider, operation system or anything else i should be focusing on moving forward

**Comment by freescout-helpdesk** [comment]
If there is a chance simply use some other email provider. No other email provider gives so much headache to users as MS Office 365.

**Comment by aj-saini** [comment]
interesting good to know, unfortunately that would be very very hard, any luck with the above errors ?

**Comment by avenjamin** [comment]
@aj-saini We use MS 365 and do get the occasional fetch error just as you're seeing.

However FreeScout is working great in our production environment and we haven't actually had any issues with mail fetching or sending despite the messages you see.

I suggest testing it out and you may find the fetch errors settle down after a while.
We average, per day, 10 new tickets, 20-30 customer messages, 10 agent replies.
I haven't had a fetch error for some time now.

In case it helps I'm running our instance on an Ubuntu VM with PHP 8.0.
I'd also recommend staying up to date as @freescout-helpdesk is maintaining the code fairly actively.

**Comment by freescout-helpdesk** [comment]
Also try to increase Fetching interval in "Manage » Mail Settings".

**Comment by aj-saini** [comment]
@avenjamin 
Can you please share your Ubuntu version you downloaded or prefer,

Also by any chance you know how much delay your getting in fetching emails,

Is it every one minute ?

**Comment by aj-saini** [comment]
Also is it Ubuntu VM - server or desktop Gui edition, 

I am trying to minimize failure and looking for best option

**Comment by aj-saini** [comment]
* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1 - this cmd runs/update the whole application once every minute, browser notifications fetch emails and blah blah 

what if i run only this cmd php artisan freescout:fetch-emails every 5 seconds for example > put it under a script and execute every 5 seconds,

one of the reason i believe  freescout is "slow" it makes a new connection every minute 
authenticates then fetch emails and then close connection ?

Please feel free to comment if above is a bad idea

**Comment by freescout-helpdesk** [comment]
What are you trying to achieve?

Proper configuration is described in https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

**Comment by aj-saini** [comment]
So one of the only issue I have noticed with freescout is the every minute fetching is very slow,

Why can we not run or not set by default "php artisan freescout:fetch-emails" to run like every 5 to 10 seconds

I am sure freescout developers are smarter then me, but i am curious to why it was not setup 

Thank you

**Comment by freescout-helpdesk** [comment]
1) Standard cron does not allow to run commands more often than one minute.

2) If you will connect by IMAP too often the mail server may start blocking FreeScout connections via IMAP.

**Comment by minghuiyu** [comment]
Reduce fetching email frequency, every 5 minutes will be much better.

If you have multiple emails to fetch (most likely), don't fetch all emails at the same time, fetching email one at a time.

**Comment by minghuiyu** [comment]
> So one of the only issue I have noticed with freescout is the every minute fetching is very slow,
> 
> Why can we not run or not set by default "php artisan freescout:fetch-emails" to run like every 5 to 10 seconds
> 
> I am sure freescout developers are smarter then me, but i am curious to why it was not setup
> 
> Thank you

I don't think you need to fetch emails so frequently. What's the use case? Your support agents need time to focus on tickets AND how many emails do you receive?

**Comment by minghuiyu** [comment]
> If there is a chance simply use some other email provider. No other email provider gives so much headache to users as MS Office 365.

I suggest adding kill $(ps aux | grep ...) in the cron job too. kill limbo freescout process that has run over 10 minutes.

**Comment by avenjamin** [comment]
@aj-saini we were fetching every minute, but today we dropped it back to every 2 minutes. No real need to have it that responsive - one or two minutes wait ain't gonna kill anyone at my work 😄 

It's a Ubuntu 22.04.2 LTS VM server (no GUI) - I have [Cockpit](https://cockpit-project.org) installed too, to help with basic monitoring/management.

**Comment by aj-saini** [comment]
We are using freescout as more of a shared mailbox VS traditional tickets
It's trucking company we get paperwork which needs to be approved or disapproved asap. So fetching as soon as possible would be ideal

**Comment by freescout-helpdesk** [comment]
Laravel commands system is designed to be executed every minute. Running it more often may have unpredictable results.
