### ISSUE TITLE
Re-send failed email

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2758]
We have had a few issues with our mailboxes due to invalid credentials or settings. This has been fixed now, and the mailboxes work again.

However, I see that some of the conversations replies failed to such an extend that the system or a admin removed them from the retry queue.

Executing this query in our database found 86 mails with a failed status since the start of 2023, which arent anywhere in the send-email retry system:
```
SELECT * FROM `threads` WHERE send_status=2 AND created_at > "2023-01-01 00:00:00"
```
My question is if there was any smart way we could add them to the query worker again to try and resend them? Since the issues that caused them not to send, has been fixed. Maybe with a SQL statement?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no possibility for now - only by adding messages again.
