### ISSUE TITLE
Installing Freescout with Laragon as server?

### ISSUE THREAD

**Issue by JSWoolf** [freescout-helpdesk/freescout#2760]
I'm trying to set up Freescout to run locally, just so I can try it out and see if it will meet my need for a single easy-to-use clearinghouse for communications about the company's websites and web-based applications - something that both developers and regular users can use.  Problem is, I'm not experienced with Linux so I'm at a loss on how to proceed with installing Freescout on a Windows 11 computer.   Note that this is for development/testing purposes only; if we use Freescout for-real, it will be hosted on a Linux server.

As of right now, my development computer has Windows 11 as the OS.  WSL is installed.  Our websites are done in Laravel, so I have Laragon running as a local server.   I got as far as step 6 of the installation guide, mostly by skipping anything that didn't seem to apply to a situation where I have an all-in-one server app like Laragon running - meaning I didn't do separate installs of Nginx, or Apache, or PHP, or MySQL.  I created the required Freescout database using HeidiSQL.  Now I'm looking at step 6, with its talk about user groups and so on, and wondering what to do next.  

Does anyone here have experience running Freescout in this sort of environment?  Dare I hope that someone has written a tutorial or "getting started" guide for how to run Freescout in this environment?  Even just some ideas on how to proceed would be welcome.

Thanks in advance for any help you can offer,
-- Jon W.

**Comment by GioSantory** [comment]
You can skip anything about user permissions with Laragon, it's pretty turn key. Just put the files in the www folder and then enter the db credentials in the installation and you should be good to go.
