### ISSUE TITLE
Email assigned to wrong customer

### ISSUE THREAD

**Issue by VacationTeam** [freescout-helpdesk/freescout#2761]
An email came in from Chris@rxxx.com to our Gmail Inbox.
When imported to Scout it was assigned to different customer
Barry@yxxx.com

![image](https://user-images.githubusercontent.com/90206057/220769250-885a9dcb-d5fb-4686-b175-76133847ff14.png)

I checked view original, and it shows the from address as Chris@xxx.com

Now  Chris did forward from his email (non-scout) a email from Barry.

What is causing scout to assign it to the Barry customer instead of the Chris Customer?

![image](https://user-images.githubusercontent.com/90206057/220769940-754c4863-a5ed-4490-b309-fb9958113d9f.png)

![image](https://user-images.githubusercontent.com/90206057/220770217-1e72e0dc-487e-4cc4-b3e8-a1bd65f7c328.png)

(When I click reply for example, the reply would go to Barry, Barry was not CC, or BCC, or TO on the forwarded email,  it just happened that Chris forwarded an email that he originally got from Barry)

Now while typing this out, I noticed:
![image](https://user-images.githubusercontent.com/90206057/220770571-11adeeec-7bf3-45b4-b487-1cabca6c4631.png)

Are these Hashed/Base64 Email addresses?
Not sure what In-Reply-To is for but maybe scout is grabbing from that?

**Comment by freescout-helpdesk** [comment]
The email was forwarded to FreeScout from email belonging to a support agent?

https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-the-customer

**Comment by VacationTeam** [comment]
Thank you for pointing that out, I didn't come across that in my search about this.
So it was forwarded from a support agent (Scout user).

How can I stop that functionality?  
At least in our case 9.9/10 if we forward something from our emails, its not meant to attach to the customer record.

**Comment by freescout-helpdesk** [comment]
We can use some special text as a marker preventing this from happening. I.e. if you add this text to the beginning of the email when forwarding it, the ticket in FreeScout will be created on your behalf. Will this work for you?

**Comment by freescout-helpdesk** [comment]
FreeScout searches for the first email address it can find in the email body to use a customer email address. If support agent forwarding an email has an email address mentioned in his/her signature, this email will be used as a customer email address for the new ticket. See an example marked with red on the image below. To prevent this behavior the support agent should remove his/her signature from the email when forwarding it (or simply remove his email address from his signature in the email body).

![2023-02-23_17-31-43](https://user-images.githubusercontent.com/40499291/220936798-14f05bcb-21eb-4300-83fb-8991b6d85e60.png)

**Comment by freescout-helpdesk** [comment]
Or can you add some extra recipient to the email when forwarding it? I.e. your FreeScout mailbox email and some other address in To or in Cc?

Which option is more preferrable?

**Comment by VacationTeam** [comment]
Hi Freescout.
Thank you for your assistance.

I will see if we add the email to the signature line, or I will look at the module for adding specific text to an email to help how it gets routed.

I appreciate the insight to how Scout looks at messages and deals with them.
