### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by sssracecar** [freescout-helpdesk/freescout#2762]
Hello Freescouters, 

Having issue with Freescout on multiple servers. Doesn't matter where I drop this software, it always takes 100% CPU usage after 24 hours of running on the server. As soon as I restart the server it goes back down and comes back up 24 hours later and stays at 100% until I restart the server again. Possibly cron job, but why does it get stuck at 100% CPU usage? Please help.

**Comment by freescout-helpdesk** [comment]
Check what's happening with background jobs using `htop` command.

**Comment by minghuiyu** [comment]
Same here. 

Freescout has certain fetching email related bugs. One fetching email got some issue, even if it resolved by itself later on, the process won't go away, and causes the high cpu usage issue. I will help with debugging when I have time. But the high CPU appears not real using CPU, just some sort of "in use" but still "idle" state. Server performance doesn't get a hit. 

I mentioned this issue a few times, @freescout-helpdesk team didn't pay much attention to that.

You can kill process manually or write a program to kill freescout process that run over 10 minutes.

**Comment by sssracecar** [comment]
This is what I see with htop

CPU 100% 
time: 22H58m30s
Command: /opt/sp/php8.0/bin/php artisan freescout:fetch-emails

How do I make it automatically shut down when its done? How do I get it unstuck without manually killing the process? 

Thank you very much in advance!

**Comment by brannan-holland** [comment]
I have this issue as well. I'm running my instance on AWS. It seems when a server hits 100% CPU utilization in AWS the entire instance stops responding. Unable to even SSH in. The only way we can resolve this is by stopping and starting the instance again. Very interested in potential fixes for this!

**Comment by freescout-helpdesk** [comment]
@sssracecar Now we need to figure out what exactly stuck during the fetching process:

1) Are you using a modern Microfost OAuth IMAP authentication or a regular IMAP authentication?

2) Can you give a list of your active modules.

3) Try to execute fetching from Manage > System > Tools and check: (1) Does it stuck; (2) Does it stuck always or only when there is a new incoming email.

4) If you are able you can provide an access to your FreeScout instance - email at support@freescout.net

**Comment by freescout-helpdesk** [comment]
Also please provide your crontab contents.

**Comment by minghuiyu** [comment]
I included some information in this post:
https://github.com/freescout-helpdesk/freescout/issues/2489

**Comment by freescout-helpdesk** [comment]
We've made some updates. Now fetch-emails command running for too long will be killed automatically.

**Comment by itinmind** [comment]
Hi, just applied the last 3 updates in the row and CPU at 100% and I have now 3 fetch commands running! No easy way to kill than as the server is managed by Cloudways. I need to contact them to kill those but last updates made it worst… I have around 30 modules installed and no easy way to give a list.

**Comment by freescout-helpdesk** [comment]
@itinmind You may need to find someone who can check fetching on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer) or feel free to provide an access to your FreeScout instance (email at [support@freescout.net](mailto:support@freescout.net))

**Comment by itinmind** [comment]
@freescout-helpdesk - well, ok I will send you access but now we are up to 4 commands running with me doing nothing so something is definitely wrong with the app! You fixed this issue a few weeks back, but it has reappeared in the last few updates!

**Comment by sssracecar** [comment]
> We've made some updates. Now fetch-emails command running for too long will be killed automatically.

Where do we download this update?

**Comment by freescout-helpdesk** [comment]
> Where do we download this update?

In your FreeScout in Manage > System.

We've checked one FreeScout instance with `fetch-emails` commands that got stuck. We've simply killed fetch-emails processes which had stuck via `htop` tool. Those processes belonged to the older FreeScout versions and FreeScout could not kill them automatically. Starting from v1.8.63 the FreeScout will be able to kill automatically `fetch-email` processes that get stuck (if they appear).

**Comment by sssracecar** [comment]
> > Where do we download this update?
> 
> In your FreeScout in Manage > System.
> 
> We've checked one FreeScout instance with `fetch-emails` commands that got stuck. We've simply killed fetch-emails processes which had stuck via `htop` tool. Those processes belonged to the older FreeScout versions and FreeScout could not kill them automatically. Starting from v1.8.63 the FreeScout will be able to kill automatically `fetch-email` processes that get stuck (if they appear).

Amazing. Freescount team fixed it all and even developed automatic updates to push the fixes to everybody pretty much automatically. Hmm.... I guess we're customers forever.
