### ISSUE TITLE
O365 Forwarded Email - Customer Name is: m@4@5l@4@11@9@11@9@5xe

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#2763]
We use Office 365 and have issues with some Internally received emails that are then forwarded to Freescout.  The recent update has fixed the issue with the image src being used as the “Customer”, however today we have a different forwarded email problem.

This email was initially sent from an internal person, to another, who forwarded to another internal person, who then forwarded it to Freescout.  Freescout has the Customer as: **m@4@5l@4@11@9@11@9@5xe**

I am not sure what it means or where it comes from – if I check the “Body” of message in Freescout I can see a reference to it towards the top.

![image](https://user-images.githubusercontent.com/47586638/220822805-d30f98e2-12a1-4e46-813d-99de9cfe0977.png)
![image](https://user-images.githubusercontent.com/47586638/220822770-2b3cd491-eb3b-46f3-b8d1-510ce6b807e4.png)

**Comment by freescout-helpdesk** [comment]
The email was forwarded to FreeScout from email belonging to a support agent?

https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-the-customer

**Comment by luketrip** [comment]
Yes it was, but Freescout did not get the customer details from the Forward, and used the random string above

**Comment by freescout-helpdesk** [comment]
And what does this customer's email look like?
Can you give a screenshot from the customer edit page.

**Comment by luketrip** [comment]
![image](https://user-images.githubusercontent.com/47586638/220837366-f00993d7-c3e2-4bd2-8894-05f8c2ab7f0c.png)

**Comment by freescout-helpdesk** [comment]
Should be fixed now in the `master` branch.

**Comment by luketrip** [comment]
I updated the file with the new code, and re-forwarded the email to Freescout.  It has got the Customer wrong again, but with a different name/address.  Please see below:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/47586638/220875794-006b4d6a-9f0d-4759-a6fc-7ae9aae3002f.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/47586638/220875958-783ebe65-2b76-4218-a340-0bdb4b1cf551.png">

**Comment by freescout-helpdesk** [comment]
Some more updates made in the `master` branch.

**Comment by luketrip** [comment]
Thanks for the update. I have tested it however it now creates the ticket with Customer as the support agent who forwarded it to Freescout, not the customer before.  While not perfect, it is much better now to see a real name and email against this ticket (not some random strings/text).  If I can help you to further modify the code to get the person who forwarded it to my agent, before he forwarded to Freescout - please let me know what you need to help troubleshoot and resolve...

**Comment by freescout-helpdesk** [comment]
Please attach screenshot of the top part of the forwarded email (where customer's email can be seen) and HTML code of the email.

**Comment by luketrip** [comment]
Hopefully this helps?  
<img width="656" alt="image" src="https://user-images.githubusercontent.com/47586638/220917073-2e606bbf-6fe2-4b5b-aad0-b0fff26e3d08.png">

**Comment by freescout-helpdesk** [comment]
Is the the email on whose behalf you want the ticket to be created?

![2023-02-23_16-26-56](https://user-images.githubusercontent.com/40499291/220920072-590f27bc-bdf5-4b61-bf73-2fdcf8f384e0.png)

**Comment by luketrip** [comment]
Yes, as she was the one who forwarded to Agent, and then he forwarded it to Freescout for action

**Comment by freescout-helpdesk** [comment]
And which email is being used as a customer email in the created ticket in reality?

**Comment by luketrip** [comment]
After the last update, the Agent Name and Email who forwarded to Freescout is being used as the Customer.  In my screenshot above, you can't see it in the Body, so I guess Freescout got his details from the Header??  Let me know if you need that

**Comment by freescout-helpdesk** [comment]
If support agent forwards an email the FreeScout tries to get the email from the body and use it as a customer email. If no email address is found FreeScout creates a conversation as usually using sender (from "From:" header) as a customer.

**Comment by luketrip** [comment]
Yes well in this case, our Agent Forwarded the email and the Customer Email is present in the body, which you highlighted above in Blue.  That is who should've been the Customer for this particular ticket.  I am not sure why Freescout used the Sender (Ie. my Agent) from the Header as Customer for this particular email

**Comment by freescout-helpdesk** [comment]
Please send full HTML body of the email to support@freescout.net
We'll try to check why the email marked with blue has not been found in the body.

![220920072-590f27bc-bdf5-4b61-bf73-2fdcf8f384e0](https://user-images.githubusercontent.com/40499291/220930960-80a53310-df63-4c1f-932d-07539476fe4d.png)

**Comment by luketrip** [comment]
Email sent. Have also forwarded you the actual email from the Agent that was trying to forward to Freescout 👍

**Comment by freescout-helpdesk** [comment]
FreeScout searches for the first email address it can find in the email body to use a customer email address. If support agent forwarding an email to FreeScout has an email address mentioned in his/her signature, this email will be used as a customer email address for the new ticket. See an example marked with red on the image below. To prevent this behavior the support agent should remove his/her signature from the email when forwarding it (or simply remove his email address from his signature in the email body).

![2023-02-23_17-31-43](https://user-images.githubusercontent.com/40499291/220936798-14f05bcb-21eb-4300-83fb-8991b6d85e60.png)

**Comment by luketrip** [comment]
OK this makes sense. Thank you for investigating - I will let our support team know this.

**Comment by SecureCPU** [comment]
This worked for me also,
Thank you!
