### ISSUE TITLE
Freescout tries to send notifications to users with completely disabled notifications

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2764]
I noticed FreeScout is trying to send user notifications about new conversations even when those users have all notifications disabled.
Maybe related to Teams module, as both users are in teams.

![изображение_2023-02-23_112647891](https://user-images.githubusercontent.com/63669538/220867953-1729779f-4476-42da-a521-f5422ca2ddb5.png)

**Comment by freescout-helpdesk** [comment]
When does it happen? When you assign a conversation, reply or in some other case?

**Comment by ilyakonovalenko** [comment]
It seems it happens in case only mobile notifications are enabled. I will test it out more and provide an update.

**Comment by ilyakonovalenko** [comment]
Here is an update.

If user has mobile notifications enabled and email notifications disabled, FreeScout will still send email notifications.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. May need some extra testing.
