### ISSUE TITLE
Pre-filled field in end-user portal

### ISSUE THREAD

**Issue by guenlm** [freescout-helpdesk/freescout#2765]
Hello

I am trying to prefill the fields in the end-user portal with this in the url
https://support.acces-vert.fr/help/990052819?f[message]=Text&f[cf_37]=Test
but nothing happens...
I have the last version (1.0.41)
Can you help me please ?
thank's
guen

**Comment by freescout-helpdesk** [comment]
Fixed in End-User Portal Module v1.0.42

**Comment by guenlm** [comment]
Yes it work's now. thank's a lot !
