### ISSUE TITLE
Phone type converts to email when adding note

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#2766]
For a conversation that is created as a phone type, adding a note to the conversation is changing the conversation to email type; which is causing all sorts of reporting issues.

I am able to replicate the issue in the demo system:

https://demo.freescout.net/conversation/50?folder_id=167

Before:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/13179697/221245484-df8426b1-6f21-46e8-968c-64b2054f595b.png">

After:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/13179697/221245364-a5708159-21fd-403c-a421-8a92334c22b9.png">

For the fix, it would be optimal to fix the conversations that got changed.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
