### ISSUE TITLE
New client with email address

### ISSUE THREAD

**Issue by EgorKlochkov** [freescout-helpdesk/freescout#2767]
Hello!
Thanks for you job!

When I delete an email address from a client, a new client appears with this email address. 
There is no conversation with such an email address.

ver. 1.8.62

**Comment by freescout-helpdesk** [comment]
When removing an email from some customer if there is a conversation with 'customer_email` field equal to the removed email address, new customer with this email address will be created.

**Comment by EgorKlochkov** [comment]
1. Add new any email address to client:

![2023-02-27_20-49-21](https://user-images.githubusercontent.com/124235399/221582407-c413b557-dba4-43cd-be6b-96aab92cb91c.png)
![2023-02-27_20-50-23](https://user-images.githubusercontent.com/124235399/221582436-7b692301-8377-4721-bd5d-9c460733f1e6.png)

2. Delete new address:
![2023-02-27_20-50-46](https://user-images.githubusercontent.com/124235399/221582547-700fa770-bba3-418a-888d-41796261d63a.png)

3. New customer without convesation:
![2023-02-27_20-51-11](https://user-images.githubusercontent.com/124235399/221582624-c0564076-27b9-455a-9a68-a00d1f8badcd.png)

**Comment by freescout-helpdesk** [comment]
It works as designed: https://github.com/freescout-helpdesk/freescout/issues/2767#issuecomment-1445345632

**Comment by EgorKlochkov** [comment]
even if there was no convesation?

**Comment by freescout-helpdesk** [comment]
In your DB there is a conversation with 'customer_email` field equal to the removed email address.

**Comment by EgorKlochkov** [comment]
No. I added an any address ala1@, saved the customer, then deleted this address, saved the customer and it ended up in a new customer

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
