### ISSUE TITLE
Multiple workflows not being sent to Telegram

### ISSUE THREAD

**Issue by mendriph** [freescout-helpdesk/freescout#2768]
Hi,

To reproduce the issue, create three or more unique workflows for a single mailbox associated with a Telegram Bot (using the Telegram integration) with the type "Automatic", and the condition "Body > Customer message contains > someword". The workflow should reply to the conversation with some message.

The first workflow (workflow1) works, and sometimes the second workflow (workflow2) works well too. However, after the third workflow, it is more likely that the messages will not be sent if you try it very closely with the other two workflows in terms of time. The workflows are still triggered, and it will appear on your backend that the workflow was triggered. However, the customer does not receive the message.

If you wait a few minutes and trigger any other workflow that was not triggered before, it may work (sometimes it works, sometimes it doesn't).

Is this a bug or some kind of network issue? I have tried with PHP versions 7.4 and 8.0, and it happens on both versions. Thank you in advance for any help, assistance, or feedback.

The following also appears in the logs:

Log: 
`Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php:1710)
[stacktrace]
#0 /public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php(1710): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /public_html/Modules/TelegramIntegration/Providers/TelegramIntegrationServiceProvider.php(105): Illuminate\\Support\\Collection->offsetGet()
#2 [internal function]: Modules\\TelegramIntegration\\Providers\\TelegramIntegrationServiceProvider->Modules\\TelegramIntegration\\Providers\\{closure}()
#3 /public_html/overrides/tormjens/eventy/src/Action.php(27): call_user_func_array()
#4 /public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\\Eventy\\Action->TorMorten\\Eventy\\{closure}()
#5 /public_html/overrides/tormjens/eventy/src/Action.php(28): Illuminate\\Support\\Collection->each()
#6 /public_html/vendor/tormjens/eventy/src/Events.php(139): TorMorten\\Eventy\\Action->fire()
#7 /public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TorMorten\\Eventy\\Events->action()
#8 [internal function]: Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 /public_html/app/Jobs/TriggerAction.php(42): call_user_func_array()
#10 [internal function]: App\\Jobs\\TriggerAction->handle()
#11 /public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#12 /public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#15 /public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#16 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#17 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#19 /public_html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#20 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#21 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#22 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#23 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#24 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#25 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 /public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#28 /public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30 /public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#31 /public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#32 /public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#33 /public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#34 /public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#35 /public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#37 /public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#38 /public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#39 /public_html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"}
`

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue on our end - all 3 replies are delivered to Telegram.

Try to attach your workflows settings.

**Comment by riehes** [comment]
I found out that previous updates were not being applied properly, so I executed a manual update through SSH. The behavior didn't change, but the error is slightly different now. I also changed to PHP 8.1.

I attached a screenshot of a single workflow. The only thing different from other workflows is the word (a simple word, no special characters or anything).

The slightly different error:

`[stacktrace]
#0  public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php(1710): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1  public_html/Modules/TelegramIntegration/Providers/TelegramIntegrationServiceProvider.php(105): Illuminate\\Support\\Collection->offsetGet()
#2 [internal function]: Modules\\TelegramIntegration\\Providers\\TelegramIntegrationServiceProvider->Modules\\TelegramIntegration\\Providers\\{closure}()
#3  public_html/overrides/tormjens/eventy/src/Action.php(27): call_user_func_array()
#4  public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\\Eventy\\Action->TorMorten\\Eventy\\{closure}()
#5  public_html/overrides/tormjens/eventy/src/Action.php(28): Illuminate\\Support\\Collection->each()
#6  public_html/vendor/tormjens/eventy/src/Events.php(139): TorMorten\\Eventy\\Action->fire()
#7  public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TorMorten\\Eventy\\Events->action()
#8 [internal function]: Illuminate\\Support\\Facades\\Facade::__callStatic()
#9  public_html/app/Jobs/TriggerAction.php(42): call_user_func_array()
#10 [internal function]: App\\Jobs\\TriggerAction->handle()
#11  public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#12  public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13  public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14  public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#15  public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#16  public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#17  public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18  public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#19  public_html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#20  public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#21  public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#22  public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#23  public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#24  public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#25  public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#27  public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#28  public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29  public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30  public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#31  public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#32  public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#33  public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#34  public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#35  public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#36  public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#37  public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#38  public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#39  public_html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"}`


![Screenshot 2023-02-27 203214](https://user-images.githubusercontent.com/36930509/221679001-4f5839cf-f32c-40cb-ac44-3f7c2840891e.jpg)
![Screenshot 2023-02-27 202215](https://user-images.githubusercontent.com/36930509/221679005-7ac1e827-5821-42fb-9cfc-96ce21cb23a6.jpg)
![Screenshot 2023-02-27 202136](https://user-images.githubusercontent.com/36930509/221679007-ff27c308-ddbc-4759-8a94-05dfb1bb6e38.jpg)
![Screenshot 2023-02-27 202108](https://user-images.githubusercontent.com/36930509/221679012-445bb0fa-bd34-4416-8734-1ddc70069118.jpg)
![Screenshot 2023-02-27 202050](https://user-images.githubusercontent.com/36930509/221679014-69c55f05-2634-470e-aaaa-f4574107717d.jpg)
![Screenshot 2023-02-27 202020](https://user-images.githubusercontent.com/36930509/221679015-05f2113b-f471-46b4-9eb5-e3e189827c6f.jpg)

**Comment by endoflevelboss** [comment]
Looks like this is connected to #2786

**Comment by freescout-helpdesk** [comment]
Let's continue in https://github.com/freescout-helpdesk/freescout/issues/2786
