### ISSUE TITLE
PHP error LDAP

### ISSUE THREAD

**Issue by jjs-josh** [freescout-helpdesk/freescout#2770]
<img width="1048" alt="log" src="https://user-images.githubusercontent.com/125841199/221446465-fa704bae-22cb-4b21-98f9-03aad35ad0a5.PNG">
Encountering the following error regarding the LDAP module, seems to be preventing me from registering users.
Would appreciate some assistance with the issue if possible. 
i believe it is related to the depreciation of dynamic properties associated with php version 8.2 which my helpdesk server is running.

**Comment by freescout-helpdesk** [comment]
Fixed in LDAP Module v1.0.28
