### ISSUE TITLE
Send & Close module - label issue

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2772]
I have purchased Send & Close modul;e v1.2

There is a minor bug/issue with how button commands are labelled in certain dropdown menus.

When you write a NOTE and click the dropdown beside ADD NOTE, it says **Send & Close**, but really the label should be **Add Note & Close.**

When you FORWARD a message and click the dropdown beside FORWARD, it says **Send & Close**, but really the label should be **Forward & Close**.

**Comment by freescout-helpdesk** [comment]
Ideally - yes, but we are a bit lazy to implement this.
