### ISSUE TITLE
Plans for integrating some AI?

### ISSUE THREAD

**Issue by rapsli** [freescout-helpdesk/freescout#2773]
As ChatGPT is taking the world by storm I was wondering if there were any plans to integrate some AI into Freescout? This could be a great feature.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by rapsli** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/400594

**Comment by freescout-helpdesk** [comment]
https://github.com/code-debug228/hostetskigpt
