### ISSUE TITLE
Top top in user list

### ISSUE THREAD

**Issue by eljakim** [freescout-helpdesk/freescout#2775]
Since last week we suddenly no longer see the names of the other users in the 'Assign' menu.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/203086/221516505-6bbcc45f-5fa1-4c48-852b-dd114aaa8df8.png">

Instead it shows `top top`. 

Under `Manage`->`Users` I see their full names.

Is there anything we can do to fix this?

**Comment by mhktc** [comment]
Fix the Attribute Mapping in Manage -> Settings ->LDAP -> Attribute Mapping
