### ISSUE TITLE
IMAP to different folder no attachments since new Update.

### ISSUE THREAD

**Issue by mhktc** [freescout-helpdesk/freescout#2776]
The function "IMAP Folder to send outgoing replies" doesnt safe any attachments at all after the latest update.
Reference to this issue: https://github.com/freescout-helpdesk/freescout/issues/2749

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. It must be related to your email provider.

**Comment by maltem-za** [comment]
@mhktc Out of interest, which config variable was it that you had to modify? I can see BASE64-encoded attachments in the source of messages that are copied to the Sent folder, but Thunderbird does not display these.

Possibly related: #2880 (and probably some others, there are many issues related to attachments)

**Comment by mhktc** [comment]
@maltem-za 
i set the setting as described in this link: https://www.bimminger.at/content/bereich/tips_diverses/tipp_thunderbird_all_attachments_alle_anhaenge.html
after setting this option EVERY attachment of every mail will get displayed, its nice for troubleshooting but for nothing else.
