### ISSUE TITLE
Conversation list does not refresh upon newly created conversation by customer.

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2777]
Hi team,

I actually expect the conversation list to refresh when a new conversation was created by the customer, e.g. via email).
However, only the badge counter increases but the new conversation only shows up in the list when manually refreshing it. I am not talking about the global inbox, for which autorefresh is not supported.

IMHO this piece of code
`        'App\Events\CustomerCreatedConversation' => [
            'App\Listeners\SendAutoReply',     
            'App\Listeners\SendNotificationToUsers',
        ],`

from app/Providers/EventServiceProvider.php is missing 
`'App\Listeners\RefreshConversations',`

**Comment by boehmgui** [comment]
e.g. this one for unassigned conversations:
![image](https://user-images.githubusercontent.com/102216227/221556493-64019a34-4880-4a94-9b7a-fce08b9564bf.png)

I sent a test email to the email address. The badge was incremented but the new conversation did not show up in the list until I manually refreshed it

When I added RefreshConversations the list was refreshed; without it wasn't

**Comment by freescout-helpdesk** [comment]
What's your FreeScout version?

**Comment by boehmgui** [comment]
It is 1.8.61

**Comment by boehmgui** [comment]
Ahhhh, it seems to work with FF but not with Chrome (Version 110.0.5481.177)

**Comment by freescout-helpdesk** [comment]
Check errors in the browser console. And in Manage > Logs > App Logs.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue in any browser. Try to debug it yourself or find someone who can do it on your server/browser: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
