### ISSUE TITLE
Problem Sending and receiving e-mail

### ISSUE THREAD

**Issue by PMendesID** [freescout-helpdesk/freescout#2778]
Hi,
I have problems with e-mail sending and receiving. Try with 2 e-mail provides but the result is the same.

Now I configured Gmail to test. 
In the SMTP configuration I can send an e-mail test with success. The same result in IMAP configurations.
When I send a TICKET for the the e-mail configured, the freescout doesn't received anything. I need to do the fetch manually in the Manage>system> tools.
I checked the Crontab and I have this entery:
* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1
In regarding of e-mails sends, when I responde a ticket, in the dashboard I can saw success, but the e-mail doesn't sanded.
Can you please help me? 
I saw all the wikis about this theme but nothing.

Thanks,
Regards.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues

**Comment by minghuiyu** [comment]
What is your SMTP gateway? Check SMTP gateway log.

I strongly recommend using dedicated SMTP services, like smtp2gp, sendgrid, etc.

**Comment by PMendesID** [comment]
I try with dedicated SMTP and the result is the same.
do you have more configurations checks?

**Comment by freescout-helpdesk** [comment]
You have problems with crontab or background jobs. Follow instructions in links above.
