### ISSUE TITLE
Uninitialized string offset 0 Error after LDAP import 

### ISSUE THREAD

**Issue by jjs-josh** [freescout-helpdesk/freescout#2780]
Hi 
Following the successful import of active directory users using the LDAP module I am unable to access the users tab within the freescout application and receive the following error(s) in the Laravel framework log (PHP)

![image](https://user-images.githubusercontent.com/125841199/221751109-a5909189-fc64-4aab-95a9-77aebac0049f.png)

I have also included the following in depth log errors in two sperate .txt files for troubleshooting purposes
[UserTab_Error1.txt](https://github.com/freescout-helpdesk/freescout/files/10846472/UserTab_Error1.txt)
[UserTab_Error2.txt](https://github.com/freescout-helpdesk/freescout/files/10846473/UserTab_Error2.txt)

Let me know what the best course of action would be to assist with the issue 

Php version 8.2.3
Freescout version 1.8.65

**Comment by freescout-helpdesk** [comment]
Apparently some data has not been imported into `users` table. Check data in this table in your DB and feel free to share some row from it.

**Comment by jjs-josh** [comment]
The issue seemed to be caused by a corrupted LDAP import, clearing the users table within the database fixed the issue, after that we did another LDAP import which worked fine
