### ISSUE TITLE
Image attachment, not available

### ISSUE THREAD

**Issue by elyazalee** [freescout-helpdesk/freescout#2782]
Hello :)

With some emails I have a problem with attached files.
Here is the email I received: it contains 2 images.

![screen1](https://user-images.githubusercontent.com/6560933/221808089-d9495521-09b4-402b-9cf0-b6e1b27e13e9.png)

And this is what it looks like on FreeScout : 

![screen2](https://user-images.githubusercontent.com/6560933/221808176-d572292f-2424-4321-8552-feb2fafc495e.png)

![screen3](https://user-images.githubusercontent.com/6560933/221808196-d1697cc1-01a8-4ae5-8d6a-997028084232.png)

Unable to view or download them :(

Thanks :)

**Comment by freescout-helpdesk** [comment]
Are you using a modern Microsoft OAuth IMAP authentication or regular?

**Comment by elyazalee** [comment]
I did not specify but : 
- the email arrived on Office 365
- I forwarded it to a regular IMAP email account (used by FreeScout)
- on this second email account : the attachments are correctly displayed (as seen on the webmail capture on my first message)

Source mail forwrded : 

```
--_000_DBBPR08MB45062677244127B2CE092A4DDAAC9DBBPR08MB4506eurp_--

--_005_DBBPR08MB45062677244127B2CE092A4DDAAC9DBBPR08MB4506eurp_
Content-Type: image/png;
	name="=?windows-1258?Q?Capture_d=92e=ECcran_2023-02-28_a=CC_09.30.42.png?="
Content-Description:
 =?windows-1258?Q?Capture_d=92e=ECcran_2023-02-28_a=CC_09.30.42.png?=
Content-Disposition: attachment;
	filename="=?windows-1258?Q?Capture_d=92e=ECcran_2023-02-28_a=CC_09.30.42.png?=";
	size=897856; creation-date="Tue, 28 Feb 2023 08:36:22 GMT";
	modification-date="Tue, 28 Feb 2023 08:52:59 GMT"
Content-ID: <9EF83B7D2B8ED7428776776C42FBC34B@eurprd08.prod.outlook.com>
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAABZ8AAAQHCAYAAACTNhefAAAK2GlDQ1BJQ0MgUHJvZmlsZQAASImV
lwdUU9kWhs+96SGhBSIgJfSOdAJICT0UQTqISkhCEkoMCUFF7AyO4FhQEUFlQIciCo6OgIwFsWBh.............
```


Same not forwaded :

```
--------------Mz2x4ro0NGHvkVOTDX20WD4z--
--------------v1RZBWCebI7AeVC4v38ZUf9D
Content-Type: image/png;
 name="=?UTF-8?B?Q2FwdHVyZSBk4oCZZcyBY3JhbiAyMDIzLTAyLTI4IGHMgCAwOS4zMC40?=
 =?UTF-8?Q?2=2epng?="
Content-Disposition: attachment;
 filename*0*=UTF-8''%43%61%70%74%75%72%65%20%64%E2%80%99%65%CC%81%63%72%61;
 filename*1*=%6E%20%32%30%32%33%2D%30%32%2D%32%38%20%61%CC%80%20%30%39%2E;
 filename*2*=%33%30%2E%34%32%2E%70%6E%67
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAABZ8AAAQHCAYAAACTNhefAAAK2GlDQ1BJQ0MgUHJvZmlsZQAA
SImVlwdUU9kWhs+96SGhBSIgJfSOdAJICT0UQTqISkhCEkoMCUFF7AyO4FhQEUFlQIciCo6O...............
```

I have temporarily disabled to try "Microsoft OAuth IMAP" it does the same thing.

Attachments are correct on RoundCube (in the email account used by FreeScout)

**Comment by freescout-helpdesk** [comment]
Try with attached `/app/Console/Commands/FetchEmails.php` file.

[FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/10849823/FetchEmails.zip)

**Comment by elyazalee** [comment]
Thanks !
I tried it and it didn't work :(

**Comment by freescout-helpdesk** [comment]
Can you send one email with problematic attachment to support@freescout.net

**Comment by elyazalee** [comment]
Done !

**Comment by freescout-helpdesk** [comment]
Try this: [FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/10850985/FetchEmails.zip)

**Comment by elyazalee** [comment]
Same :( it didn't work :(

**Comment by freescout-helpdesk** [comment]
Could you please send again a sample email to support@freescout.net

**Comment by elyazalee** [comment]
Done !

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

Updated file: [FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/10853269/FetchEmails.zip)

**Comment by elyazalee** [comment]
Oh nice :)
Thanks !!!
