### ISSUE TITLE
Which hooks/filters do I need: BEFORE New Conversation Notification Email is sent ?

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2783]
When a user has the box checked to receive an Email notification for a New Conversation, what hook/filter is available BEFORE the email is sent?

So the flow would be: 
New Conversation Created
  -> Get Email Address For Any Users That Need To Be Notified Of New Conversation
    -> Send Notification Email To User

Is there a hook/filter that is fired BEFORE the Notification Email is sent to user? So a hook/filter that would return the list of Users/Emails that will be notified, or a hook/filter that will return the Email (to, from, subject, body) just before it is sent?

Thanks

**Comment by avenjamin** [comment]
I'm not 100% sure but have a look at the ConversationController's `ajax` function. Specifically the "send_reply" switch case:
https://github.com/freescout-helpdesk/freescout/blob/7b5572f5de0296c29769a54b81ffd4e60aa9a4d3/app/Http/Controllers/ConversationsController.php#L595-L596

I think the hook you might be after is here:

https://github.com/freescout-helpdesk/freescout/blob/7b5572f5de0296c29769a54b81ffd4e60aa9a4d3/app/Http/Controllers/ConversationsController.php#L898-L899

or maybe further down in this `if` block:
https://github.com/freescout-helpdesk/freescout/blob/7b5572f5de0296c29769a54b81ffd4e60aa9a4d3/app/Http/Controllers/ConversationsController.php#L1086-L1116

and before this line:
https://github.com/freescout-helpdesk/freescout/blob/7b5572f5de0296c29769a54b81ffd4e60aa9a4d3/app/Http/Controllers/ConversationsController.php#L1118


Hope that helps

**Comment by jshrek** [comment]
@avenjamin Thanks for this ... I am not sure that is what I want, but I ended up downloading all the code and doing some searching and I actually came across the following usersToNotify code in freescout//app/Subscription.php
(sorry I don't know how to do all the fancy formatting that you used) ..

https://github.com/freescout-helpdesk/freescout/blob/7b5572f5de0296c29769a54b81ffd4e60aa9a4d3/app/Subscription.php#L156-L160

and within that I see this:
```
208        $events = \Eventy::filter('subscription.events_by_type', $events, $event_type, $thread); 
              // I think I am looking for event type EVENT_NEW_CONVERSATION=1

242        $subscriptions = \Eventy::filter('subscription.subscriptions', $subscriptions, $conversation, $events, $thread);

276        if (\Eventy::filter('subscription.filter_out', false, $subscription, $thread)) {

285        $users_to_notify = \Eventy::filter('subscription.users_to_notify', $users_to_notify, $event_type, $events, $thread);
```

So I think (not 100% sure because I am still learning hwo to write a module) that these eventy filters are what I can hook into?

**Comment by avenjamin** [comment]
nice work - hopefully what you found will do the trick.

You can have a look at the module I wrote here: https://github.com/avenjamin/freescout-Following-Module
The interesting bit of code you might want to look at is the `hooks` function in Providers/FollowingServiceProvider.php

Otherwise you should be able to find similar info in the [FreeScout SampleModule](https://github.com/freescout-helpdesk/SampleModule) repository and the [Module development guide](https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development)
