### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when trying to access localhost/install

### ISSUE THREAD

**Issue by Yariet** [freescout-helpdesk/freescout#2784]
Hello, 

I'm currently installing Freescout on an IIS server. I got the the point where I'm supposed to see an installation wizard but I get ERR_TOO_MANY_REDIRECTS error and can't proceed. Does anyone have any tip on how to solve the issue?

Thanks!

**Comment by freescout-helpdesk** [comment]
Debug https://github.com/freescout-helpdesk/freescout/blob/dist/public/install.php#L7

Also check your HTTPS configuration.

**Comment by freescout-helpdesk** [comment]
Web directory in your web server should be set to `/path/to/freescout/public/` instead of `/path/to/freescout/`
