### ISSUE TITLE
Stay on current ticket when adding a note

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#2785]
It may be nice to stay on the same ticket when you create a note for a ticket. If there's a way to easily hook into this, please let me know as I'm okay to add code for this if this isn't a viable feature.

Currently when you add a note to a thread/ticket you get redirected to the next assigned (mine) ticket.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-i-determine-what-happens-after-replying-changing-conversation-status-or-assigning-a-conversation

**Comment by andrewlimaza** [comment]
This would be for notes only, not actual replies.

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
