### ISSUE TITLE
Fetching Email on a specific Gmail account suddenly stopped (Others are okay)

### ISSUE THREAD

**Issue by loadpipe** [freescout-helpdesk/freescout#2787]
Hello,

We have multiple Gmail mailboxes. All are working fine for more than one year now without issues. Suddenly one Gmail mailbox stopped working 2 days ago. Sending emails is working fine. It sends immediately. The issue is fetching emails. When we try to click Check Connection, it takes forever to connect. Sometimes it doesn't, it just keeps loading. Below are the Fetching Emails settings:

Protocol: IMAP
Server: imap.gmail.com
Port: 993
Username: our company Gmail
Password: app password we set
Encryption: SSL
IMAP Folders: Inbox
Validate Certificate: OFF

We have no idea why it suddenly stopped fetching emails. All other Gmail mailboxes are fetching without issue. Help is much appreciated. Thank you in advance.

Have a great day ahead.

**Comment by loadpipe** [comment]
Thank you for the link. I have reviewed it. Unfortunately, it doesn't resolve our issue. The specific mailbox still doesn't fetch new emails.

The cronjob is configured.
https://www.screencast.com/t/Jz4CEE1w

It seemed that the cronjob is correctly configured coz it was running.
https://www.screencast.com/t/XMdeByqxh9q

Under Systems, we can also see that freescout:fetch-emails and queue:work are running.
https://www.screencast.com/t/Jv5Z1MHf0sN

The connection of the mailbox is also fine.
https://www.screencast.com/t/uDmLCJqrkvg

But it doesn't fetch the new emails.

It will only fetch if we click Manage -> System -> Tools -> Fetch Emails
https://www.screencast.com/t/5x0Uya29c6lr

We have no idea what's wrong. Kindly assist if you can. Thank you.

**Comment by freescout-helpdesk** [comment]
Check logs in Manage > Logs > App Logs and debug https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php to see what is going on during fetching.
