### ISSUE TITLE
Created new module - how do I access database?

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2788]
I have created a new module using the artisan make command, and I am now trying to figure out how to access the database.

At the top of the module it says `use Illuminate\Database\Eloquent\Factory;` which would suggest there is some kind of ability to access the DB, but I can not figure out how to do it.

I need to be able to run SELECT and UPDATE and INSERT commands.

Thanks

**Comment by jshrek** [comment]
Well this has taken me hours and hours to finally figure out ....

At the top of your module you can add a couple more `use` clause:
```
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
```

Once you have these added, then you can do things like this:
```
$results = DB::select('SELECT * FROM my_table ');
```

I have not tested UPDATE or INSERT yet but will report back once I see how they work.

**Comment by avenjamin** [comment]
If you're trying to access an existing table like `followers` you can use something like this:

```
Follower::where('followers.user_id', $folder->user_id)
   ->join('conversations', 'conversations.id', '=', 'followers.conversation_id')
   ->where('status', \App\Conversation::STATUS_ACTIVE)
   ->count();
```

There is a model for almost every table in the database which supports methods like above.

Or you can do raw queries like you found.

Have a look at the Laravel database docs:

- https://laravel.com/docs/4.2/queries
- https://laravel.com/docs/4.2/eloquent

Just note that those are for Laravel version 4.2 and Freescout is still using Laravel version 2 with no plans to ever upgrade.

**Comment by freescout-helpdesk** [comment]
Thanks for helping out.
