### ISSUE TITLE
Development Guide link correction (minor issue) to sample module

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2789]
Just a minor correction in the Development Guide...

There is a link on this page
https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development

which points to the Modules Development Guide here:
https://gdoc.pub/doc/e/2PACX-1vSLbWqFvwlTvr_akQ9hu52-TfRJ9J-0HhpMuuvxHq5ch9qkI6HoGat8Y2mDxyMTasFX2ijSybNFCkBx

Within the Development Guide, it says
```
Sample Modules
Sample FreeScout modules is available here: https://freescout.net/modules/
```

But the correct link to the Sample Module should be this:
```
https://github.com/freescout-helpdesk/SampleModule
```

**Comment by freescout-helpdesk** [comment]
Thanks. Fixed.
