### ISSUE TITLE
Better installation error feedback

### ISSUE THREAD

**Issue by galloppinggryphon** [freescout-helpdesk/freescout#279]
I accidentally entered the wrong MySQL credentials during the install wizard and got the message "Whoops, looks like something went wrong." First of all, that's a remarkably unhelpful error message to serve during the installation process. Of course I found the error in the logs, but for such a basic problem it would have been nice if I didn't have to. Second, the error only occurred after I entered admin user details on the next screen. It would be nice if it tested the DB connection settings immediately so there would be clear connection between user action and app feedback.

Thanks for your hard efforts!

**Comment by freescout-helpdesk** [comment]
Could you please tell:
- your MySQL version
- which field did you enter incorrectly: host, username, password?
