### ISSUE TITLE
New Module- Disable New Conversation Email Notification Per Mailbox

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2790]
I am working on a new module that will allow users to disable the New Conversation email notification for any mailbox they have access too, on an individual mailbox basis.

The main reason for this module is that currently if you enable/check the email box for Notify Me When There Is A New Conversation https://yourfreescoutdomain.com/users/notifications/1 then you will get an email for every new conversation from **every mailbox** that you have access too.

But this is not always desired. As an example, we currently have 12 different mailboxes of which I need access too, but in 10 of them, I only need to respond if an email is specifically assigned to me. There are only 2 mailboxes that I am in charge of reading the new conversations and then assigning to others. So I only need to receive notificaiton of a new conversation for 2 of the 12 mailboxes.

I have **a working version of this module**, however it currently requires me to manually enter the user_id and mailbox_id into a custom table in the db in order for it to work (so there is no gui yet, and you need to know to use something like phpMyAdmin to add the entries). It is available here:
https://github.com/jshrek/Freescout-Module-Disable-New-Conversation-Email-Notification-Per-Mailbox

Below is a list of items that I do not know how to complete. 

If anybody wants to contribute to the module, that would be great. I am even willing to completely hand it over to the Freescout team if they think they can polish it up and make it more user friendly.

TO DO - HELP LIST
- Need to show a checkbox (one per mailbox) on the /users/notifications/userid page that is to the right of the "Notify Me When There Is A New Conversation", so that you can turn on/off the New Conversation Email for each mailbox individually (see attached mockup.jpg). Note that alternatively, if its not possible to modify that existing page, we could setup a completly new settings page for this.
- Need to write the code that would actually update the custom table in the db when the user changes their preferences on the above mockup screen.

mockup.jpg
![mockup](https://user-images.githubusercontent.com/19673842/222621696-21113f0f-cc83-4176-b5a4-ce11d3836f96.jpg)

**Comment by avenjamin** [comment]
Interesting idea for a module. I can see that being useful when you have many mailboxes.

The first TODO item you can do by setting up a database migration file.
See the one in my repo as an example:

https://github.com/avenjamin/freescout-Following-Module/blob/main/Database/Migrations/2023_02_22_010101_add_followers_folder_to_folders_table.php

Note that the class name must match the filename (minus the underscores) e.g. AddFollowersFolderToFoldersTable 

There's probably a php artisan command for it - I just made mine manually 🙃

**Comment by freescout-helpdesk** [comment]
@jshrek Have you tried "mute" feature? https://github.com/freescout-helpdesk/freescout/wiki/FAQ#admins-get-notifications-for-all-mailboxes-what-to-do

**Comment by jshrek** [comment]
@freescout-helpdesk I assume that only works for admins? There are many users in our system that have access to multiple mailboxes, but only need New Conversation email from 1 or 2 of them.

**Comment by jshrek** [comment]
@avenjamin Thank you, I will look into that.

**Comment by freescout-helpdesk** [comment]
> I assume that only works for admins?

For all users.

**Comment by jshrek** [comment]
The mute notification button does not solve our problem for the following reason:
- It is controlled by user, not by admin, so admin can not turn off the New Conversation email when assigning user to a mailbox. When we assign the user to multiple mailboxes, we need to setup the notifications at that time and not wait and hope the user clicks on the Mute button.

I would also suggest that from an end user perspective, it is not clear to the user what notifications are going to be muted... email or in-browser or both? And also unclear as to which type of notification will be muted... New conversation? Update to conversation? Assigned?

**Comment by jshrek** [comment]
@avenjamin Ok I looked at your migration file and was able to figure out how to create the file for my module and now new table will be created upon activation. Thank you!!
