### ISSUE TITLE
Answer not correct mapping

### ISSUE THREAD

**Issue by ChrisStain87** [freescout-helpdesk/freescout#2791]
Hey guys,

first of all - awesome work. Freescout rocks! We just implemented it and everything works fine.

We got the problem that some mails a not correctly recognized as replies. I guess it's because of some header-attributes, but I'm not sure.

We got the ticketnumber-module. Is it possible to tell Freescout to map mails to conversation if the subject contains the ticketnumber?

Thanks!
Chris

**Comment by ChrisStain87** [comment]
Maybe some background: Some conversations are started from the ticketsystem of the customer, e.g. Topdesk.
When some agent in the other ticketsystem adds a reply, it is handled as a new mail, not a reply to any previous input.

**Comment by freescout-helpdesk** [comment]
Can you attach headers and body of one of such replies. You can find them in the message dropdown menu - "Show Original"

**Comment by freescout-helpdesk** [comment]
Yes. Ask Topdesk to properly populate `In-Reply-To` or `References` header. There is no other solutions.
