### ISSUE TITLE
Do not update customer name on every email fetch

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2792]
Currently FreeScout updates customer name on every email fetch.

For example:
* We have customer named "Joe Smith"
* This customer sends us an email which has "nobody" in "From" header
* FreeScout changes "Joe Smith" to "nobody" every time

Better to add  an option to skip such behaviour in case the customer already exists and has name.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Can you reproduce it on demo.freescout.net?

**Comment by freescout-helpdesk** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/346931

**Comment by ilyakonovalenko** [comment]
> We can't reproduce the issue. Can you reproduce it on demo.freescout.net?

I tried to send some emails to demo instance and I can't reproduce the issue there as well.
Strange... Is there any other things I should check? Maybe it gets overridden only in some cases?

**Comment by ilyakonovalenko** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L607

It seems this is where first and last names get changed. Not sure why demo has different behaviour, maybe because of CRM module (we don't have it).

**Comment by freescout-helpdesk** [comment]
It does not: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Customer.php#L950
