### ISSUE TITLE
Timzeone stuck

### ISSUE THREAD

**Issue by 7ergei** [freescout-helpdesk/freescout#2795]
System Timezone is stuck.
FreeScout v1.8.68

No matter to what timezone I'm changing the system, it still remain the same.
Also 12 or 24 hours stuck as well.

Any suggestions? 

Thanks.

**Comment by freescout-helpdesk** [comment]
Most likely FreeScout can not clear cache due to permissions issue.

See introduction instructions at https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by 7ergei** [comment]
Run 'Clear cache' from the system - 
![image](https://user-images.githubusercontent.com/88785658/222881651-4a1f71bc-d2c3-4e82-b2ed-31f3060ba26a.png)

And also 
sudo chown -R www-data:www-data /var/www/html

Still the same.

**Comment by freescout-helpdesk** [comment]
We don't have other ideas. You may need to debug it on your server or find someone who can do it: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
