### ISSUE TITLE
Notifications - bell icon

### ISSUE THREAD

**Issue by 7ergei** [freescout-helpdesk/freescout#2796]
Notification worked once, after initial setup then it stuck.
FreeScout v1.8.65

Tried all this - without success:
 - Mute/Unmute notifications.
 - Removed all notification in browser, saved. then allowed all checkboxes.
 - Cleared cookies in browser.

Please assists...

Thanks.

**Comment by 7ergei** [comment]
A couple of things done, and Bell icon/notifications - start to work again.
- Upgraded to the latest version 1.8.66
- Run from console 'php artisan config:clear'
- Run 'php artisan down'
- Run 'php artisan up'

Not sure if this is what made the notifications work again, but it looks like it is fine now.
The issue can be closed,
Thanks.

**Comment by freescout-helpdesk** [comment]
Great.
