### ISSUE TITLE
Development Guide improvement for module icon

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2797]
I have improvement for Module Development Guide related to the icon for a module, and how to include it within the module itself:
https://gdoc.pub/doc/e/2PACX-1vSLbWqFvwlTvr_akQ9hu52-TfRJ9J-0HhpMuuvxHq5ch9qkI6HoGat8Y2mDxyMTasFX2ijSybNFCkBx

Under the Step-by-Step Instruction under item 2. it says this:
```
To set custom icon:
        "img": “https://example.org/custom-icon.jpg”
```

Recommended improvement:
```
To set custom icon from external location:
        "img": “https://example.org/custom-icon.jpg”

To set custom icon from within the module directory (use all lowercase):
        "img": "/modules/mymodulename/img/my-module-icon.png"
And make sure to place the icon in your modules Public directory:
        /Modules/MyModuleName/Public/img/my-module-icon.png
```

**Comment by freescout-helpdesk** [comment]
Thanks. Updated.
