### ISSUE TITLE
Messed up my installation with SidebarApi

### ISSUE THREAD

**Issue by atchoooo** [freescout-helpdesk/freescout#2798]
My installation is completely broken after I installed SidebarApi. (I think the right choice was SidebarWebhook)

Web shows :
Whoops, looks like something went wrong — check logs in /storage/logs

I've got this in the logs...

`[2023-03-03 18:16:27] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'defaultdb.sidebar_apis' doesn't exist (SQL: alter table `sidebar_apis` add `mailbox_id` int null) {"userId":1,"email":"my@email.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'defaultdb.sidebar_apis' doesn't exist (SQL: alter table `sidebar_apis` add `mailbox_id` int null) at /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'defaultdb.sidebar_apis' doesn't exist at /www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'defaultdb.sidebar_apis' doesn't exist at /www/html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)
[stacktrace]` 

I tried a few things as listed in the module page, maybe I messed it up further?

I deleted the sidebarapi row from the Modules table.
I deleted the Module
I ran php artisan migrate
I ran php artisan freescout:clear-cache

Both commands output this...

`Class "Modules\SidebarApi\Providers\SidebarApiServiceProvider" not found`

Any idea?

Thanks!

**Comment by freescout-helpdesk** [comment]
See item 4): https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache

**Comment by atchoooo** [comment]
Thanks, clearing cache manually worked 👍

**Comment by freescout-helpdesk** [comment]
Great.
