### ISSUE TITLE
Are there filters to modify Manage Users pages?

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#2799]
When you click on Manage Users and select a specific user, on the left side of the page (/users/profile/1 /users/permissions/1 /users/notifications/1) there is a menu with the Profile Permissions Notifications and New User options. Is there a filter to modify this menu?

Also are there filters to modify the /users/profile/ /users/permissions/ /users/notifications/ pages as well?

I see the SampleModule lets you put text on the dashboard page, but there are not further details in the sample module to point to these other pages. I also searched the Freescout code for **:filter(** but was not able to determine if what I am looking for is available.

Thanks

**Comment by avenjamin** [comment]
@jshrek if you look at https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/users/sidebar_menu.blade.php there doesn't appear to be any hooks to add items via a custom Module.

We'd have to get @freescout-helpdesk to add the ability to add menu items.

Search for @filter views, and Eventy::filter or Eventy::action in the classes and controllers to find things you can tap into.

@freescout-helpdesk would it be possible to add a page to the Wiki with all the current filters/actions in the project?
Not sure if it's something that can be kept up to date with a git commit hook/action.

**Comment by jshrek** [comment]
@avenjamin yes I was looking at that and there does not appear to be any hook for that menu. I am playing around with Javascript and I think I can add to the menu item that way, but obviously a built in hook would be preferred option.

And as you suggested I have been browsing the code looking for filters and actions, but again this would be much easier if there was some kind of wiki page that already listed them all.

Thanks

**Comment by freescout-helpdesk** [comment]
If needed feel free to add the hook to the template and send a pull request.
