### ISSUE TITLE
Saved replies: only substitutes first variable

### ISSUE THREAD

**Issue by snazzypants** [freescout-helpdesk/freescout#280]
When inserting a saved reply, the variable only gets substituted for the first one found. I will often use the customer's name for a greeting, and the agent's name at the end, and the one at the end never gets inserted.

Also I'm not sure if I'm just going crazy, but I thought there was an "Insert variable" dropdown in the interface for creating a saved reply - I'm not seeing it anymore.  This is on v1.2.1.

**Comment by freescout-helpdesk** [comment]
It will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in the laster Saved replies release.
