### ISSUE TITLE
Admin email and password suddenly stop working

### ISSUE THREAD

**Issue by xteaun** [freescout-helpdesk/freescout#2800]
This is the second time this has happened. After a while of using my self-hosted instance of FreeScout without any problems, I get logged out and when I try to log back in, the password does not get recognized. When I try to change the password and enter the admin email address, that email address is not found. I then have to create a new admin user over ssh and can log in again and the old admin has disappeared. What is happening? Am I doing something wrong? :) Thanks for your help. 

Christian

**Comment by freescout-helpdesk** [comment]
Are you the only one admin? When it happens next time check contents of `users` table in the DB.
