### ISSUE TITLE
Custom Fields Module 1.0.26 not Saving

### ISSUE THREAD

**Issue by Mmasri6** [freescout-helpdesk/freescout#2801]
we were using freescout locally and everything thing was working fine with the modules. Once we published freescout online the modules disappeared suddently after couple of days and below error showed up

"Module Custom Fields has been deactivated due to invalid license: site_inactive" along with all other modules.

We deactivated the modules and reinstalled them. the configuration came back just the way it was configured before. but the module aint saving the data anymore.

could you please help

Custom Fields Module 1.0.26
App Version 1.8.54

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-one-of-official-modules-does-not-work-properly-or-just-stopped-working
