### ISSUE TITLE
Creating tickets only from IMAP subfolders

### ISSUE THREAD

**Issue by xteaun** [freescout-helpdesk/freescout#2802]
Hi there! I have not quite understood what the IMAP folder setting in the mailbox settings is for. Can I configure FreeScout in a way that it will only create tickets from emails in an IMAP subfolder? I tried setting the IMAP folder option to "INBOX.Ticket", a folder which I created on the server and which FreeScout offers in the IMAP folder list, but no tickets get created from emails in that subfolder. Am I missing something? :)

Thanks, 
Christian

**Comment by freescout-helpdesk** [comment]
Check fetching output in Manage > System > Tools

**Comment by xteaun** [comment]
Thank you for your swift reply. Here is the output:

[2023-03-05 17:53:50] Fetching UNREAD emails for the last 1 days.
[2023-03-05 17:53:51] Mailbox: Christian Michalak
[2023-03-05 17:53:51] Folder: INBOX.Ticket
[2023-03-05 17:53:51] Fetched: 0
[2023-03-05 17:53:51] Fetching finished

There are to emails in the folder. None get fetched.

**Comment by freescout-helpdesk** [comment]
Great.
