### ISSUE TITLE
Installing (clone) dev environment issue with build

### ISSUE THREAD

**Issue by iReserveApps** [freescout-helpdesk/freescout#2803]
Hi, 
We are using freescout plus a dozen modules in production mode for a few months now. 
Aiming to extend the functionality by adding a module, so in need of a local dev environment. 
Struggling to achieve this, as the manuals only state how to create a fresh environment (without modules+data). 

Our simplistic approach is: copy filesystem + db to a localhost environment, change the .env, change the symlink and perform freescout:clear-cache via CLI. So far so good. 

Whichever command we try, we end up with a page where no CSS/JS files are used. Ending in a page with some data from Freescout but no styling or functionality. 
Checked the laravel documentation on how to (re) build the assets. public/ js/builds and public/css/builds remain empty. 

What are we missing here? We dont mind executing manual steps but missing the knowledge why the build of the files is skipped. 
Any help appreciated.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working

**Comment by iReserveApps** [comment]
That part of the FAQ has been executed. It's only one step of a correct environment.

We have been digging further. 
- All modules needs to be installed, as these need to have a symlink in the folder public/modules. 
- If module table is out of sync between prod and dev environment, this caused the main part of our issue: a deactivated module was injected in minify which caused an exception. The exception was logged in storage.logs. Which helped us further. 

What would help in these cases -> if environment is in debug mode, these exceptions might be in output as well (next to the logging). 

Main question of this issue: how do you setup a dev (test) + prod environment. And how to deploy new versions. 
The need for a separate dev increased after the update in prod of the core freescout version failed via the UI. A message appeared: failed. try another way,. Should we download, FTP the new version and run a migration script?

**Comment by freescout-helpdesk** [comment]
There is no a manual for establishing and maintaining a dev environment yet.

All instructions on updating are here: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
_"If some updating method does not work or results in error simply use the next one or use manual updating which works always."_
