### ISSUE TITLE
Workflow action: Run a manual workflow

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2804]
This is a bit of a feature request plus discussion to see how feasible it would be to do.

I have a manual workflow that has a few actions and want to be able to run the workflow manually AND automatically based on some criteria.
Is it feasible to trigger a manual workflow from an automatic workflow?

Basically i'm looking for some keywords in the conversation and if present run the workflow.
If the keywords aren't present, but it's still related then I want to run the workflow manually.

I could duplicate the actions I suppose, but having to maintain two identical workflows isn't the ideal option.

An alternative would be to allow an Automatic workflow to appear in the manual workflow menu and it's actions would be run manually.

I'll file this as a feature request too, but any thoughts would be appreciated:
FR here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/401411

**Comment by avenjamin** [comment]
An alternative would be to allow an Automatic workflow's actions to be also be run manually.

FR here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/401411

**Comment by avenjamin** [comment]
I was able to implement this on my system by adding a TINYINT `show_in_action_menu` field to the `workflows` table and then modified the WorkflowsServiceProvider.php file:

From line 256:
```
        // In bulk actions.
        \Eventy::addAction('bulk_actions.before_delete', function($mailbox) {
            if (!$mailbox) {
                return;
            }
            $workflows = Workflow::where('mailbox_id', $mailbox->id)
                ->where('active', true)
                ->where('type', Workflow::TYPE_MANUAL)
                ->orWhere('show_in_action_menu', true)
                ->orderBy('sort_order')
                ->get();
```

I added `->orWhere('show_in_action_menu', true)`

I just need to update the workflow creation views to match the dummy screenshot above

**Comment by avenjamin** [comment]
The `orWhere` logic above isn't quite right as it's showing the `show_in_action_menu` workflows in other mailboxes.

We need something more like this raw SQL query:
```
SELECT * FROM workflows
WHERE mailbox_id = $mailbox_id
AND active = 1
AND (type = 2 OR show_in_menu = 1)
ORDER BY sort_order
```

**Comment by freescout-helpdesk** [comment]
It's the first this kind of functionality is requested. Feel free to submit a feature request: https://freescout.net/request-feature/
