### ISSUE TITLE
schedule:run does not terminate after 1800s

### ISSUE THREAD

**Issue by sannc** [freescout-helpdesk/freescout#2806]
Version: 1.8.66 

I have set up the schedule:run task embedded in a Bash script, because I cannot call the PHP binary directly via Cron.

`
#!/bin/bash

/usr/local/php8.0/bin/php /home/esshdmkn/service.essenzenladen.de/artisan schedule:run >> /dev/null 2>&1
`

Our hoster monitors cronjobs and terminates them automatically after 3600s. I get an email notification if this happens.

Although the queue:work script has a timeout set (--timeout=1800) it happens that it does not terminate by itself after 3600s and thus is terminated by the hoster. This behaviour occurs a couple of times over the day - about once every hour.

By now I have not been able to identify the circumstances under which the task does not terminate after 1800s.

Is there a way to make sure the script honors the set timeout?

**Comment by freescout-helpdesk** [comment]
`queue:work` runs for unlimited time. The timeout determines how long each individual job https://github.com/freescout-helpdesk/freescout/tree/dist/app/Jobs can run.

**Comment by sannc** [comment]
Ok. So what would be best practice to deal with the 3600s timeout by my hoster? 

Using /usr/bin/timeout? 

Or just suppressing the notification? The latter would also suppress real problems, though …

**Comment by freescout-helpdesk** [comment]
You can run `php artisan freescout:clear-cache` for example from time to time. It will cause `queue:work` to restart.

**Comment by sannc** [comment]
Thanks for your reply. However, that doesn't really solve my issue and would require an extra cronjob.

 I think I will go with `/usr/bin/timeout` and kill `queue:work` just before my hoster would. It will be then restarted by the cronjob …
