### ISSUE TITLE
Discussion: Behaviour of email sent to multiple mailboxes

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2807]
I'm setting up another mailbox for another department and some emails will be sent to both mailbox addresses.
Currently FreeScout creates two separate conversations with different conversation ID's (aka ticket numbers).

This causes a couple of issues:
- If auto replies are enabled then the customer gets two different responses.
- If a user from either mailbox replies then a _new_ conversation is created in the other mailbox with another new conversation ID

I think it would be ideal if an email is sent to multiple mailboxes, a single conversation ID is created and used by all mailboxes.

At the moment FreeScout ties each `conversation` to a single `folder_id` which is tied to a `mailbox_id` making this a little tricky to implement.

Potential issues:
- How do we handle auto-replies? which mailbox's auto-reply is used?
- If a user deletes the conversation from a mailbox should it deleted from the other mailboxes.

Could we separate the conversation_id and the message/ticket number so two conversation_id's could share the same ticket/message number?

I just noticed in Manage > Settings > General there is an option to set the Conversation Number to either the conversation ID or Custom..., but I'm not sure what Custom means - perhaps this is something that could be used?

Any ideas on how we could implement a solution for some future version (v2?) of FreeScout would be great.

Thanks

**Comment by freescout-helpdesk** [comment]
> If auto replies are enabled then the customer gets two different responses.

It's normal to get an auto reply from each recipient when sending an email to multiple recipients.

> I think it would be ideal if an email is sent to multiple mailboxes, a single conversation ID is created and used by all mailboxes.

Unfortunately it's not possible and no plans to implement.

> If a user from either mailbox replies then a new conversation is created in the other mailbox with another new conversation ID

Fixed in the `master` branch.

**Comment by avenjamin** [comment]
@freescout-helpdesk Unfortunately https://github.com/freescout-helpdesk/freescout/commit/05c76c6584aa7dcc4b389c95790c75806ffa335f doesn't seem to have fixed the issue of creating new conversations.

I sent an email from a personal (customer) address to my two mailboxes addresses.

When I replied as a user from mailbox A a new conversation was created in mailbox B from the mailbox A address.
Similarly, when I replied as a user from mailbox B a new conversation was created in mailbox B from the mailbox A address. 

Below are the various `Message-ID`'s, `In-Reply-To`'s, and `References` headers:
```
Original Email
As Seen by Mailbox A: Message-ID: <CACHpcMCPKBNeQrV2MaT43zDWZme+wXJ0cysP7MzBC3SovbE9iw@mail.gmail.com>
As Seen by Mailbox B: Message-ID: <CACHpcMCPKBNeQrV2MaT43zDWZme+wXJ0cysP7MzBC3SovbE9iw@mail.gmail.com>
```

```
Reply sent from Mailbox B to original email. Headers as seen by Mailbox A: 
Message-ID: <reply-3475-fa3735d429870ee6@**redacted**>
References: <fs-1981f0cfe6aae9c7381af12db0dbdf8b@mail.gmail.com>
In-Reply-To: <fs-1981f0cfe6aae9c7381af12db0dbdf8b@mail.gmail.com>
```

```
Reply sent from Mailbox A to original email. Headers as seen by Mailbox B: 
Message-ID: <reply-3474-2687440d1fa288c5@**redacted**>
References: <CACHpcMCPKBNeQrV2MaT43zDWZme+wXJ0cysP7MzBC3SovbE9iw@mail.gmail.com>
In-Reply-To: <CACHpcMCPKBNeQrV2MaT43zDWZme+wXJ0cysP7MzBC3SovbE9iw@mail.gmail.com>
```

Interestingly Mailbox B stored a self-generated `Message-ID` (fs-1981f0cfe6aae9c7381af12db0dbdf8b@mail.gmail.com) in the database instead of using the original one.

**Comment by freescout-helpdesk** [comment]
Closing as out of scope.
