### ISSUE TITLE
Module Update Error

### ISSUE THREAD

**Issue by tychoyrc** [freescout-helpdesk/freescout#2809]
I'm using freescout in a vm thats running in the google cloud. I'm mounting the Modules folder from a gcp bucket into the Modules folder. The folder is owned by the www-data user and has all the rights. After mounting i can install and delete modules but i cant update them.

When i try to update it gives the following error.

<img width="338" alt="Screenshot 2023-03-08 at 14 23 25" src="https://user-images.githubusercontent.com/100914449/223724372-b741cce6-6361-4671-b0c4-c03c2afa7160.png">

**Comment by ilyakonovalenko** [comment]
Check permissions and owners of the files and folders. Maybe `chmod 777` is required in your case.

**Comment by tychoyrc** [comment]
All the files and folders are owned by www-data so that shouldnt be an issue.

**Comment by ilyakonovalenko** [comment]
Depending on webserver configuration, chmod may be an issue.

**Comment by tychoyrc** [comment]
I just ran sudo chown -R www-data Modules/ and the issue is still there.

**Comment by ilyakonovalenko** [comment]
Have you checked chmod?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by tychoyrc** [comment]
I tried both chmod and chown but it doesnt fix the issue.

**Comment by freescout-helpdesk** [comment]
Find someone who can check it for you on your server: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
