### ISSUE TITLE
More email variables like "Job Title" and "Phone Number"

### ISSUE THREAD

**Issue by nczz** [freescout-helpdesk/freescout#281]
Hi,
My suggestion as title and thank you. It's really a good project!

**Comment by foliovision** [comment]
Fantastic product. We like to use title in our signatures so our customers know who they are dealing with (on our desk are mainly not support people but either programmers or designers so title is relevant).

What I'd like to see in signature is this: `{%user.jobTitle%}`

I tried it myself just for fun but it's not there. I have $100 bounty for jobTitle being added for signatures in October.

**Comment by frommMoritz** [comment]
I'll be giving it a shot!

**Comment by freescout-helpdesk** [comment]
Bounty will be supposed to go to @frommMoritz

**Comment by frommMoritz** [comment]
One more Idea, there is only one (main) property from the user that is not available as a template. At the moment there is no way to reference a users profile picture. My toughts on that:

I would tend to create a variable that contains the absolute URL to the profile picture. This way you could simply add an tag like this (when you want to personalize your E-Mall by adding an image of the agent):

```html
<img src="{%user.pictureUrl%}" title="Picture of {%user.fullName%}" alt="Picture of {%user.fullName%}">
```

I prefer this way over attaching an image for a couple of reasons:
  * It is way easier to implement. If you look at the way placeholders are filled this isn't quite compatible with attaching something. Basically the signature is takenand send to an function that replaces all of the matching strings. This function has absolutely no control over the final E-Mail, it only contributes a small text.
  * Attaching an image on every E-Mail will take an significant amount of storage. I do not know how much mail you are sending, but having an attachment on every single of your E-Mails would not impress the person on the other side. Especially in regions with slow internet connection downloading an additional 2-3KB when you are syncing your E-Mails seems somewhat unnecessary (imo).
  * Somewhat related to the point above, but the URL to the profile picture can easily be cached across multiple E-Mails, not so for an attachment (as far as I know).

My main point is the significant amount of work it would take to get an attachment from the text-only function to the final E-Mail. This doesn't fit to the "keep the core *neat and clean*" mentality.

If you (esp. @freescout-helpdesk @foliovision @nczz) could give me some feedback I'd implement it.

**Comment by freescout-helpdesk** [comment]
Agreed. Just better to call the variable `%user.photoUrl%`

**Comment by foliovision** [comment]
@frommMoritz That's a great idea to use a referenced image. The only issue with an external image is that many mail clients see images as tracking pixels and will not show the image, leaving a broken signature. But I agree that's better than cluttering everyone's mailbox with dozens/hundreds of little signature images.

Look forward to the final commit/release and delivering the bounty!

**Comment by nczz** [comment]
Perfect! Thank you all!  @frommMoritz @foliovision @freescout-helpdesk
