### ISSUE TITLE
Freescout Timeout error 

### ISSUE THREAD

**Issue by tychoyrc** [freescout-helpdesk/freescout#2811]
When clicking arround the application for a small time freescout freezes and our loadbalancer gives a timeout error.
Changing the max children or the amount of children spawning doesnt seem to fix this issue.

We are hosting are own version of freescout in a vm in the google cloud. We are using nginx/1.18.0 and ubuntu 22.04.2 LTS.

I attached a screenshot of the error im getting below.

<img width="1427" alt="Screenshot 2023-03-09 at 12 08 26" src="https://user-images.githubusercontent.com/100914449/224006790-2fdead0f-6fcb-43ed-a048-8eb46aa45697.png">

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by freescout-helpdesk** [comment]
You need an admin who can check it on your server. See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
