### ISSUE TITLE
Bug forward / attribution

### ISSUE THREAD

**Issue by elyazalee** [freescout-helpdesk/freescout#2813]
Hello,

I have forwarded an email from xxxx@xxxx.fr
This one instead of being attached to the sender's email account was attached to an email contained in the body of the email (ricjonesmyemail@gmail.com (spammer). This is very annoying :/

![bug](https://user-images.githubusercontent.com/6560933/224264024-fffdfdc5-bcc1-47bf-a764-95fe726a02b1.png)

Thanks :)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-this-customer

**Comment by elyazalee** [comment]
Hum. 

Yes, in my case it is a forwarded email and the first email was not taken into account.

If the tool takes into account first the email in the body of the mail, it is problematic.
For example, if I receive a technical request from A asking me to create an email account for B. 
The ticket will be assigned to B instead of A :/

**Comment by freescout-helpdesk** [comment]
Now the customer will not be substituted in the forwarded by support agent email if the email starts with `@fwd` text (implemented in the `master` branch):

https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-this-customer

**Comment by elyazalee** [comment]
Ohhh ! sorry ! ok
Thanks !

**Comment by spencercolletsyfan** [comment]
Is there any way to disable the substitution feature entirely? 
We are currently setup so our users can forward held email requests over to our freescout instance. However, due to the held email request notification emails containing an address, freescout is picking up that address and not the users. There is no way we will be able to get all of them to start adding an @fwd.

**Comment by freescout-helpdesk** [comment]
We've changed this behavior in the `master` branch. Now the customer in the forwarded email will be substituted only if there is "@fwd" text added in the beginning of the email.

**Comment by avenjamin** [comment]
Can we re-open this one.

I've forwarded a few emails both with and without `@fwd` as the first line and none of them are picking up the customer email address like it used to.

Also the last commit above and the last reply appear to be conflicting as to what the behaviour now is.
Commit 1bc5f60 says: "Do not substitute the customer in forwarded by support agent email if the email starts with @fwd"

Either way I can't get it to work anymore. Am I the only one?

Thanks
