### ISSUE TITLE
Workflow does not trigger for custom fields conditions

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2814]
Hello,

I noticed that workflows do not trigger for conditions with custom fields like:
`Priority [Dropdown] IS EQUAL TO High`

The same happens for `IS NOT EQUAL TO` conditions. It triggers for any value.

Unfortunately I can't check with demo instance as there is no way to create workflow (Access Denied).

Can you please check.

**Comment by freescout-helpdesk** [comment]
It works fine on our end. See https://github.com/freescout-helpdesk/freescout/issues/2786

**Comment by ilyakonovalenko** [comment]
I don't believe it is related to #2786 as workflows work, but not those which have "is equal" condition for dropdown custom fields.

I just tested:
* Let's say we have workflow which should trigger only in case custom field value is "High" (=3), condition "is equal"
* We create conversation with such custom field value
* Workflow does not trigger
* If we edit workflow and change condition to "is not equal", the workflow will trigger for any value, even for "High"

So it seems there is something wrong with conditions check.

**Comment by freescout-helpdesk** [comment]
Does it trigger if you change the custom field in the existing conversation?

**Comment by ilyakonovalenko** [comment]
Yes, it triggers but not in case workflow has condition "new / reply / moved". It seems this is where is issue is.

**Comment by freescout-helpdesk** [comment]
Can you give a screenshot of your conditions.

**Comment by ilyakonovalenko** [comment]
![изображение_2023-03-10_133025219](https://user-images.githubusercontent.com/63669538/224305151-61b97eae-f5a9-4860-8996-3fe8fe5d80f8.png)

This one does not work.

**Comment by freescout-helpdesk** [comment]
How does the customer set the custom field when he/she sends an email to your FreeScout?

**Comment by ilyakonovalenko** [comment]
In the scenario we create conversation via official API module.

**Comment by freescout-helpdesk** [comment]
We've checked - the workflow did not trigger when "New / Reply / Moved" was added using "AND". Try to add it using "OR" or remove completely.

![new-reply-moved-condition](https://user-images.githubusercontent.com/40499291/224306633-86293d59-3faa-4176-ada1-65e4255605b0.png)

**Comment by ilyakonovalenko** [comment]
I will try. Would the issue be fixed in the module?

**Comment by freescout-helpdesk** [comment]
When checking Custom Fields the "New / Reply / Moved" condition should not be used.

**Comment by ilyakonovalenko** [comment]
We supposed to use the condition to send various auto-replies based on priority. The auto-reply should be sent on conversation creation. How to implement this then? Workflows are for such things...

**Comment by freescout-helpdesk** [comment]
The only solution for now is not to check Custom Fields.

**Comment by freescout-helpdesk** [comment]
We've checked the configuration with just two conditions. It works when a support agent creates a new conversation in FreeScout and does not work via API.

![2023-03-10_15-04-23](https://user-images.githubusercontent.com/40499291/224311593-0a4cd9c9-ac91-48ce-bc12-cb43a0bd10c7.png)

**Comment by freescout-helpdesk** [comment]
We've made more tests. The workflow on the screenshot above does trigger for us even when the conversation is created via API (just with 1 minute delay sometimes).

If it still does not work for you via API - try to add conditions one-by-one to determine which condition blocks workflow execution.

**Comment by freescout-helpdesk** [comment]
Have you solved the issue?
