### ISSUE TITLE
queue:work Last run:? Last successful run: ?

### ISSUE THREAD

**Issue by CodeAndWeb** [freescout-helpdesk/freescout#2815]
Hi,

I've meanwhile found out what the reason for #2808 was.

I had started the `schedule:run` with ` --no-interaction` which prevents running `queue:work`... this new behaviour must have been introduced around version 1.8.58

With this
~~~
php /var/www/artisan schedule:run --verbose
~~~

it now works and mails are sent again.

However I still get this error message and wonder where it comes from:

<img width="919" alt="2023-03-10_11-28-02" src="https://user-images.githubusercontent.com/716009/224294780-9315bc0b-e134-466a-8ec6-58e30b3f6533.png">

`queue:work` never terminates - so what does that mean?

Is there still something broken with my setup?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/SystemController.php#L110

**Comment by CodeAndWeb** [comment]
Ah. Ok.

You are checking the execution on the same machine.
I've started 2 separate docker containers - one for the background worker and one for the main server.

The web app does not see the running background process in the other container.

**Comment by freescout-helpdesk** [comment]
Are you using Cloudron?

**Comment by CodeAndWeb** [comment]
No. Docker compose.

**Comment by freescout-helpdesk** [comment]
> I've started 2 separate docker containers - one for the background worker and one for the main server.

Why would you need this?

**Comment by CodeAndWeb** [comment]
I use php-fpm as the base image for the app itself and this created issues with the cron.
This is why I am running it in a separate container.

I'll look into the "official" docker version and see if I can move the cron job to the main container.

**Comment by xteaun** [comment]
So, I am having the same problem. What is the fix?

**Comment by CodeAndWeb** [comment]
I don't have any. I decided not to add cron to the php-fpm container and still run the updates from my 2nd docker container using a simple script.

It seems that there is no way to get rid of the error.

I think it would be more useful if the queue:work would put the last successful run into the database or something similar instead of checking if the process runs.
