### ISSUE TITLE
Multiple Tickets/end-user-portal per 1 mailbox?

### ISSUE THREAD

**Issue by freezingpt** [freescout-helpdesk/freescout#2817]
Greetings,

I'm currently setting up freescout and my goal is to have multiple tickets by type of request. In other words a x type question fill a x type form; a y type question should fill a y type form.

Currently, as far as I know we can only have one end-user portal/ticket per mailbox. 

Is there anyway of having one mailbox and multiple tickets/end-user portals?

Thank you

**Comment by freescout-helpdesk** [comment]
It's not quite clear what you need. But maybe [End-User Portal](https://freescout.net/module/end-user-portal/) form plus [Custom Fields](https://freescout.net/module/custom-fields/) is what you are looking for.
