### ISSUE TITLE
public/js/vars.js' does not exist

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#282]
Hi - I have just updated Freescout and it wouldn't load. I got a generic 'whoops something went wrong' error. After enabling debugging I got the following error.

public/js/vars.js' does not exist in /resources/views/layouts/app.blade.php

If I comment out the vars.js file in the bottom of the file then the file loads properly.

Thanks - Ben

**Comment by freescout-helpdesk** [comment]
Make sure that `public/js/` folder is writable by the web server and clear application cache in System > Tools.

**Comment by BinaryMoon** [comment]
That solved it, thanks
