### ISSUE TITLE
Conversations: "show original" does not take into account thet email could have been moved by IMAP Move module

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2820]
freescout version: 1.8.67  
Move or Remove IMAP Message Version: 1.0.1

After fetching our emails are moved to a subfolder by the above-mentioned module.

When we now click "show original" in a particular conversation it shows this message and some content is missing:
![image](https://user-images.githubusercontent.com/102216227/224637029-4d899af9-d8df-42aa-956c-05879408ac43.png)

If I move the email back into the mail server's inbox, the complete email thread is visible in "show original".

IMHO freescout should take into account that the module could have moved fetched emails

**Comment by freescout-helpdesk** [comment]
We'll fix it.

**Comment by boehmgui** [comment]
It still does not work. We have version 1.8.68 installed, which is supposed to have this fix incorporated.
However, when the original email is in the "abgeholt" folder (this is where the module moves the fetched emails to), the message wrt the latest truncated copy is still displayed and parts of the email are missing. As soon as I move the email back into the Inbox folder, "Show original" shows the full message and vice versa.

**Comment by freescout-helpdesk** [comment]
Yes. Here is the code retrieving the email from the mail server: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L691

https://github.com/freescout-helpdesk/freescout/wiki/Debugging
