### ISSUE TITLE
Faster Search is really Slow

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#2824]
I installed the faster search module and hooked it up with a Meilisearch instance hosted in Azure. The instance indexed around 60k threads and is able to search quickly using the meilisearch dashboard (worst case ~2000msec). I limited to the search results to 50. However, when using the search box in freescout results would take 40 seconds or more to return a result.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/13179697/225209902-bffe8415-7a16-484e-b0d2-bc04fa45c919.png">

Same search in Meilisearch:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/13179697/225209979-159a47e4-4f99-4b0b-ad42-b44b40ae71a7.png">

** Edit:
Added top during a search; the database is being searched instead of meilisearch!

<img width="642" alt="image" src="https://user-images.githubusercontent.com/13179697/225210639-9188dc52-b2cc-4515-9f16-56c30a33f07e.png">

**Comment by freescout-helpdesk** [comment]
Apparently the search still uses DB search instead of using Meilisearch or falls back to a regular DB search.
Check Manage > Logs > App Logs and Manage > Logs > Meilisearch.

**Comment by afawaz2** [comment]
I have no logs for meilisearch. the module shows as active 

![image](https://user-images.githubusercontent.com/13179697/225220053-07a851a9-67f7-47a4-ad6a-1631030a7ba1.png)

**Comment by freescout-helpdesk** [comment]
It means deeper debugging is needed. You can provide an access to your FreeScout instance (email at support@freescout.net) or find someone who can do it: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by afawaz2** [comment]
Unfortunately, we can't grant external people access to the instance. I am happy to add any logs you need to debug this module.

**Comment by freescout-helpdesk** [comment]
Add the following to the 388 line in /Modules/FasterSearch/Providers/FasterSearchServiceProvider.php:
```
\Log::error('api_response: '.json_encode($api_response));
```

After that perform a search and post here a line containing `api_response` from Manage > Logs > App Logs.

**Comment by afawaz2** [comment]
So I added logs to the provider.php file to see how it performs:
For this search it took around 40 seconds but the provider did return data within 7 seconds;

Logs:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/13179697/225362623-1d6ac5da-ab82-4f8f-ac4c-e18f8c7b85f3.png">

Code change:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/13179697/225363294-b90c5e76-a225-4527-b673-57e436081aed.png">

**Comment by freescout-helpdesk** [comment]
So debug further using `\Log::error('...');` to find out what is taking time.

**Comment by afawaz2** [comment]
can you help identity the points of entry and exist for this call? so that I can add my logs.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ConversationsController.php#L2626

**Comment by afawaz2** [comment]
I cannot replicate the issue anymore, however, I am interesting in knowing what performance are you seeing in your testing? We currently have around 70k indexed threads and we get search results return in the 7sec range, which seems to be slow for a tool that promises fast search. I would expect based on their advertised numbers to be in the ~50 msec response range.

I have it deployed on an instance with 4 vcpus and 7 gb of ram.

**Comment by freescout-helpdesk** [comment]
Great. Unfortunately we don't have such stats. Maybe someone can share their.
