### ISSUE TITLE
Error while exporting Conversation reports

### ISSUE THREAD

**Issue by foc-pm** [freescout-helpdesk/freescout#2825]
Facing error while trying to export conversation in encoding - ANSI

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' (SQL: update `conversations` set `updated_at` = 2023-03-14 23:58:19, `rpt_ready` = 1, `meta` = {"rpt":{"frt":-19643,"rst":75810,"rnt":650954,"rtr":4,"rfr":false}} where `id` = 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' (SQL: update `conversations` set `updated_at` = 2023-03-14 23:58:19, `rpt_ready` = 1, `meta` = {\"rpt\":{\"frt\":-19643,\"rst\":75810,\"rnt\":650954,\"rtr\":4,\"rfr\":false}} where `id` = 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' at /var/www/html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(490): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): Illuminate\\Database\\Connection->affectingStatement()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2173): Illuminate\\Database\\Connection->update()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(782): Illuminate\\Database\\Query\\Builder->update()
#5 /var/www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(628): Illuminate\\Database\\Eloquent\\Builder->update()
#6 /var/www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(543): Illuminate\\Database\\Eloquent\\Model->performUpdate()
#7 /var/www/html/Modules/Reports/Providers/ReportsServiceProvider.php(247): Illuminate\\Database\\Eloquent\\Model->save()
#8 /var/www/html/Modules/Reports/Console/CollectData.php(36): Modules\\Reports\\Providers\\ReportsServiceProvider::collectData()
#9 [internal function]: Modules\\Reports\\Console\\CollectData->handle()
#10 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#11 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#15 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#18 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#19 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#22 /var/www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 {main}
"}`

**Comment by freescout-helpdesk** [comment]
Something went wrong during some of the previous updates of your FreeScout instance. Run migration in Manage > System > Tools

**Comment by foc-pm** [comment]
Issue while Migrating db 
`Clearing cache:
PHP Warning:  require(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/artisan on line 43
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/artisan:43
Stack trace:
#0 {main}
  thrown in /var/www/html/artisan on line 43
Run DB migration and continue? (Y/n) [n]:Y
PHP Warning:  require(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/artisan on line 43
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/artisan:43
Stack trace:
#0 {main}
  thrown in /var/www/html/artisan on line 43
PHP Warning:  require(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/artisan on line 43
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/artisan:43
Stack trace:
#0 {main}
  thrown in /var/www/html/artisan on line 43`

**Comment by freescout-helpdesk** [comment]
Broken installation. Use method 5: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by foc-pm** [comment]
Was able to update to the latest version. migrated but the issue is still happening. got a new error though :) 
`
iconv(): Detected an illegal character in input string {"userId":1,"email":"noreply.questalliance@gmail.com","exception":"[object] (ErrorException(code: 0): iconv(): Detected an illegal character in input string at /var/www/html/Modules/ExportConversations/Http/Controllers/ExportConversationsController.php:435)
`

**Comment by freescout-helpdesk** [comment]
Fixed in Export Conversations Module v1.0.8

**Comment by foc-pm** [comment]
Thanks for the support. this is fixed
