### ISSUE TITLE
Workflow button open a blanck menu

### ISSUE THREAD

**Issue by dhaula** [freescout-helpdesk/freescout#2828]
Hi.

When we select a conversation, a floating bar with buttons appears.

In the "Workflow" button, I expect some options for workflows to appear (I don't know what comes up). But I always get blanck: https://drops.hormi.link/i/IpaRdO

Is this a known bug?

Thanks

**Comment by avenjamin** [comment]
The empty floating panel isn't ideal, but any manual workflow's you setup will appear here.

To setup a workflow look in the gear/cog menu at the bottom of the mailbox folder list.

<img width="252" alt="Screenshot 2023-03-16 at 8 06 37 pm" src="https://user-images.githubusercontent.com/869534/225568021-f1913873-e312-4cfe-aefb-cd5c8cd41061.png">

**Comment by dhaula** [comment]
Yes, I have some workflows created, but these do not appear in the Workflows floating menu.

Workflows: https://drops.hormi.link/i/u2sPdh
Floating workflow menu in the same inbox: https://drops.hormi.link/i/zkvYkF

I have the last version of FreeScout and modules.

Thanks

**Comment by avenjamin** [comment]
Your screenshot of workflows shows two Automatic workflows.
Only Manual workflows will appear in the menu.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/869534/225571105-809c846e-da40-406c-839c-545c550fcf36.png">

**Comment by dhaula** [comment]
Thanks!
