### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by TyrannosaurHex** [freescout-helpdesk/freescout#283]
Reported by another user here:
https://github.com/freescout-helpdesk/freescout/issues/248

Not sure why it is requesting CSS/JS resource from example.com

![image](https://user-images.githubusercontent.com/50612266/60415223-354dda00-9bf8-11e9-9b7d-9c9944d4bb99.png)

Any ideas where to fix this?

**Comment by freescout-helpdesk** [comment]
Check `APP_URL` in `.env` file and clear cache in System > Tools.

**Comment by TyrannosaurHex** [comment]
Working now. Thanks.

**Comment by freescout-helpdesk** [comment]
Which installation method did you use? manual or web installer?

**Comment by TyrannosaurHex** [comment]
It was a manual install a couple of versions back. Then updated to 1.1.0 where it broke for some reason. Now I don't remember how it managed to run correctly with incorrect APP_URL till 1.1.0.
