### ISSUE TITLE
when deleting a note, the note still shows up in the list view

### ISSUE THREAD

**Issue by psuter80** [freescout-helpdesk/freescout#2832]
Hi 
when i write a note into a ticket and then delete the note, it will still show in the conversation list preview text until another message is added to the conversation. 

Let me explain by example: 

here is a test conversation with two notes: 
![image](https://user-images.githubusercontent.com/22317472/225809284-b1efb1e7-6d43-400a-aaf7-9fda368e6a8d.png)

when i now delete the "this is the second note" from the conversation by clicking on the little down-arrow on the right side and selecting delete, the note disappears from the conversation. 

But, it still shows up in the conversation list like so: 
![image](https://user-images.githubusercontent.com/22317472/225809391-c694986f-68a4-4df2-8a45-63bafe5b7234.png)

Instead I would expect to see the latest remaining message in the conversation to be previewed in the list, like so: 
![image](https://user-images.githubusercontent.com/22317472/225809195-03bdd3d8-a7d6-4531-9a2b-231a0fba79d7.png)

cheers
Pascal

**Comment by avenjamin** [comment]
This looks like the conversation `preview` field in the database needs to be updated when the note is deleted.
I might dig into the code over the weekend and see if I can find what needs to change.
