### ISSUE TITLE
update 1.8.6.8 Reply-to: email change

### ISSUE THREAD

**Issue by jamieppuk** [freescout-helpdesk/freescout#2833]
reference:
https://github.com/freescout-helpdesk/freescout/issues/2826

This update seems to have messed up our incoming tickets
When someone fills in a contact form on our website it uses our 
ouremail@ourdomain.co.uk email smtp settings to send the email to itself which 
is then picked up by freescout

Typical headers would be...
Delivered-To: ouremail@ourdomain.co.uk
Return-Path: ouremail@ourdomain.co.uk
Delivered-To: ouremail@ourdomain.co.uk
Reply-To: Mister Customer customer@gmail.com

Before the update this would correctly create the ticket in the customer customer@gmail.com account with replies to the ticket going to Mister Customer   customer@gmail.com

After the update the Reply-To: name and address is ignored and they are instead created in a ouremail@ourdomain.co.uk account.
Is this an oversight that can be corrected or is this now how it will be and we will need to update our system to work with it ?
Thanks

**Comment by freescout-helpdesk** [comment]
Can you remove this header?
```
Precedence: junk
```

**Comment by freescout-helpdesk** [comment]
Nevermind, we'll revert this change.
