### ISSUE TITLE
When switching from one view to another, from time to time the view will take a long time to load

### ISSUE THREAD

**Issue by cherpake** [freescout-helpdesk/freescout#2834]
The logs don't show any errors so I looked in the web browser console and saw those.

![Screenshot 2023-03-18 at 14 31 50](https://user-images.githubusercontent.com/876484/226106384-ecdf1900-1776-43f5-a796-68c7d24f92d0.png)
![Screenshot 2023-03-18 at 14 32 05](https://user-images.githubusercontent.com/876484/226106386-837278f1-571d-4958-b433-97b903a96c73.png)

**Comment by freescout-helpdesk** [comment]
We don't have any clues. It need to be checked on the server.
