### ISSUE TITLE
Add extra Query Parameters to API GET api/conversations request

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#2835]
Is it possible to have the GET api/conversations query parameters extended so they could do the following?

- customerPhone (Find conversations by Phone Number)
- Subject (Subject contains keyword)
- Tag (Find by Custom Tag on Ticket)
- Type (Filter by Phone or Email Ticket)

We are using the API to create a lot of “Phone” style tickets for SMS Replies using a 3rd party SMS platform.  I need to be able to use the API to find these types of conversations, where a customerEmail doesn’t exist – and having any of the above could help me filter and find these types of conversations.  Ie. I would simply add a keyword like “SMS” to the Subject, a special tag, or list only Phone type tickets.  The best option for us though would be a search by phone number.

A createdSince style parameter would also be useful that works similar to updatedSince.

**Comment by freescout-helpdesk** [comment]
Added the following parameters for List Conversations method in API & Webhooks Module v1.0.55: type, subject, customerPhone, tag, createdSince.
