### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by RandomGuy70hz** [freescout-helpdesk/freescout#2836]
I have tried many different things. Both on Mac using MAMP (php 8.2.0 & php7.4) and windows IIS 10 and no matter what, I get the same error:

`[2023-03-19 19:55:25] production.ERROR: Undefined constant "FT_UID" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"FT_UID\" at C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\webklex\\laravel-imap\\src\\config\\imap.php:105)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\webklex\\laravel-imap\\src\\IMAP\\Providers\\LaravelServiceProvider.php(66): require()
#1 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\webklex\\laravel-imap\\src\\IMAP\\Providers\\LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#2 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#3 C:\\inetpub\\wwwroot\\freescout-dist\\overrides\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#4 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#5 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#6 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#7 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#8 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 C:\\inetpub\\wwwroot\\freescout-dist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#10 C:\\inetpub\\wwwroot\\freescout-dist\\public\\index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle()
#11 {main}
"} `

**Comment by avenjamin** [comment]
@RandomGuy70hz 

Have a look at the [Installation Guide(https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide).

There's a bunch of common issues listed at the bottom.
In particular:

> — Undefined constant "FT_UID"
> 
> Make sure you have php-imap extension enabled in web and console PHP: https://github.com/Webklex/laravel-imap/issues/30#issuecomment-348748107

There's a few previous issues about the same thing if you search closed issues for "FT_UID"

Hope that helps.

**Comment by RandomGuy70hz** [comment]
I've looked through those and cannot seem to resolve the issue. IMAP is also enabled along with the other required extensions. 

Could there be any other cause? 

Thanks for the reply

**Comment by avenjamin** [comment]
Odd. What do you get when you run the following:

`php /var/www/html/artisan freescout:check-requriements` _(yes there's a typo in requirements)_

(or)

`/usr/local/bin/php-8.0 /var/www/html/artisan freescout:check-requriements `

**Comment by RandomGuy70hz** [comment]
I am using a macbook with MAMP. None of these work but i would assume that I need to change the location to meet the requirements for my install location? sorry if thats a dumb question. I should note that any time i use a "artisan" command I get an error.

When i input the commands you gave me it gives an error. When switching the location to my isntall location, nothing happens.

`❯ php /Applications/MAMP/htdocs freescout:check-requriements               
                                                                                
~   
❯ 
`

**Comment by avenjamin** [comment]
Thats correct - the path should point to the folder where you installed FreeScout - you may also need to prepend it with `sudo` depending on the file permissions.

It looks like you're missing `artisan` in your command.
It should be:

`php /Applications/MAMP/htdocs/artisan freescout:check-requriements`

Given you have two versions of php there might be some conflicts as to what php extensions are installed in the different environments.

**Comment by bamb000cha** [comment]
Good day! We installed ubuntu 22.04 in the company, updated to the latest version. Using the github manual, we downloaded a script with automatic installation of components for freescout. When opening the installation page in the browser (by domain name or ip address), it goes to the page https://192.168.20.200/install , but the page is unavailable and gives a 404 error. Ngnix, MySQL are up and running. PHP 8.0 is installed. Please help me figure out the problem. Thanks!
