### ISSUE TITLE
Terminated fetching 

### ISSUE THREAD

**Issue by Beaudinn** [freescout-helpdesk/freescout#2838]
I have 3 mailboxes configured, Two of them retrieve messages fine, but the third one stops and I can't figure out what's going wrong. I can't find the error I'm getting anywhere in the code

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3606046/226339612-4d6d1f06-bc3e-45b1-886c-a3e89f93920d.png)

Error log stays empty

If I retrieve the messages from the Tool option or from the cli it works, but from the cronjob does not work

Freescout version  1.8.69
Php version 8.0

**Comment by Beaudinn** [comment]
I'm still investigating, when I run "php /var/www/html/artisan schedule:run" through the terminal it works but when done through the conjob I end up getting terminated,

**Comment by Beaudinn** [comment]
Oke, "shell_exec('kill" inside Kernel.php is called, 
I don't know how the conditions are built, but for now I've commented out the code and everything works fine again.

**Comment by freescout-helpdesk** [comment]
You may need to find a professional admin who can investigate it on your server.

**Comment by chkwok** [comment]
Leaving this solution here for anyone searching:

If a cron job is started while a previous one is still running, the old one is killed, by https://github.com/freescout-helpdesk/freescout/blob/42423bdf61c2d53dba9f4d5585a3116d8db97b6b/app/Console/Kernel.php#L105

That seems fair until you see that the default / recommended frequency is every minute, that means every fetch must finish within that time or get killed. If you have multiple mailboxes and the IMAP server is a bit slow to respond, you get "Terminated" in your log.

Solution: change mail fetch interval to 2 or 5 minutes and make also cron run less often. The default is too optimistic, fine for a few inboxes, not fine for a bigger installation or one with multiple queues (general, finance, reservations x different branches = many). Especially Google Workspace likes to delay responding or throttle the fetches.
