### ISSUE TITLE
Not able to connect SMTP server.

### ISSUE THREAD

**Issue by manishamittal16** [freescout-helpdesk/freescout#2840]
Connection could not be established with host smtp.gmail.com [Connection refused #111]; File: /home/xxxxxxxxx/support.com/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php (271)

**Comment by avenjamin** [comment]
Have you enabled access to 'less secure apps' in your google account?

**Comment by manishamittal16** [comment]
There is no option to enable 'Less secure apps'. I have added 2-steps verfication as per documentation.

**Comment by avenjamin** [comment]
Odd that 2FA not working for you. 

Have a look here:

https://support.google.com/accounts/answer/6010255?hl=en#more-secure-apps&zippy=%2Cif-less-secure-app-access-is-on-for-your-account%2Cuse-an-app-password%2Cif-less-secure-app-access-is-off-for-your-account

Might be worth looking at an App password and see if that works instead.

**Comment by manishamittal16** [comment]
![image](https://user-images.githubusercontent.com/64191398/226509370-94d9dace-a163-4ad9-a5eb-08806bb5afbe.png)

**Comment by avenjamin** [comment]
Hence the app password suggestion.

**Comment by manishamittal16** [comment]
@freescout-helpdesk Can you please help me?

**Comment by manishamittal16** [comment]
![image](https://user-images.githubusercontent.com/64191398/226893797-3edd6486-5877-4b34-b986-90461b634147.png)
Still facing same issue.

**Comment by freescout-helpdesk** [comment]
Apparently 465 port is closed on your server. Contact hosting provider or find an admin who can fix it.
