### ISSUE TITLE
feature request module: Extended Attachments open files that are txt

### ISSUE THREAD

**Issue by ioscanner** [freescout-helpdesk/freescout#2841]
It would help if the Extended Attachments module allow you to open a file to view the TXT.  Example we get RFC822 forwards of emails.  We need the header information, but we don't want to open in an email client as they could be dangerous. So for now we have to download them and open in a text editor.  We purchased the Extended Attachments to view them, but it has no way to adjust settings or just a simple solution: if it doesn't know how to open a file then prompt to open with text editor.

We have this issue everyday and hoped this module would have resolved it.

**Comment by freescout-helpdesk** [comment]
What's RFC822 files extension?

**Comment by ioscanner** [comment]
When you forward an email it attaches an email that is in text format.  But email clients will run the file in preview mode if you click them.  If they are just opened as a text file it is safe.  This happens when people forward suspicious emails, or viruses.  But also could be a config file or anything else.  That is why I suggested just a way that if extended attachments module doesn't know what to do with an attachment give the option to open as a text file when clicking, this would then work for any files that are txt format that people need to review: config files, code, text documents. etc.

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible due to security reasons.
