### ISSUE TITLE
Reply to Note from email client appears as normal reply

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2847]
When adding a note to a conversation, if a user replies using an email client, the reply is picked up as a normal response and the customer will also see the reply.

Replies to notes should be considered to be another note instead.

Implementing this could use something like a custom `In-Reply-To` header value or a custom header eg `X-FreeScout-Note`.

**Comment by freescout-helpdesk** [comment]
It's by design. See `@note` command: https://freescout.net/module/email-commands/
