### ISSUE TITLE
Not able to connect Imap. Earlier all worked (get email on freescout)

### ISSUE THREAD

**Issue by Asio259** [freescout-helpdesk/freescout#2848]
Now get every min error 
"Error: connection failed; File: /var/www/html/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (82)"
i am using MS Exchange 2013 like mailer
![image](https://user-images.githubusercontent.com/122514933/226823246-753c9ce5-4d0b-4ebb-9091-a450413f7082.png)

But trying get email on freescout with sendmail - itz work.

Any1 have ideais why not work with Exchange (imap)?

**Comment by freescout-helpdesk** [comment]
Have you followed "Fetching Emails" instruction: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#fetching-emails

**Comment by Asio259** [comment]
We are not using o365, We using on-premises exchange 2013

**Comment by freescout-helpdesk** [comment]
So are you using a modern Microsoft OAuth IMAP authentication or regular IMAP authentication?

Can you give a screenshot of your Fetching settings?

**Comment by freescout-helpdesk** [comment]
> 7. If your mail server does not like frequent connections try to increase "Fetch Mail Schedule" option in "Manage » Settings » Mail Settings".

https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues

**Comment by Asio259** [comment]
We solve it just some components was inactive 
![image](https://user-images.githubusercontent.com/122514933/227977684-bd91945c-1f40-4bdd-a466-9f03d04b71bf.png)
