### ISSUE TITLE
Auto Refresh Emails

### ISSUE THREAD

**Issue by NdT3Development** [freescout-helpdesk/freescout#285]
Hi,

We currently use this system and it is great. One feature that is missing from our old email system is that it appears that Freescout doesn't automatically refresh emails and if our staff need to check for new emails, they need to reload the page.

Would it be possible to add in an auto refresh feature (using XHR (XMLHttpRequest)) so it would get emails in the background at a set interval (like every minute) and add these to the page without needing a page reload.

**Comment by freescout-helpdesk** [comment]
Yes. In the future.

**Comment by foliovision** [comment]
This kind of functionality worries me. One aspect of Freescout which we appreciate very much coming from a very top heavy and overbuilt system is how light Freescout is on server and browser resources. Auto-refresh can result in huge memory consumption and slow down a computer.

Can we have an option to turn off AJAX functionality? Please understand, I'm not against advanced functionality. What I do oppose are selfish applications which hoard all resources to themselves and bog down computers.

**Comment by freescout-helpdesk** [comment]
No worries. It is already implemented and works within the Polycast websocket broadcasting using ajax which works since the beginning of the FreeScout.

**Comment by foliovision** [comment]
Thanks for letting me know. Please be very careful about adding additional polling style features which eventually make a web application an obstructive and interrupting monstrosity rather than a useful helpmate. We've all seen this lycanthropy happen to so many previously very useful services and sites.
