### ISSUE TITLE
fetching error Couldn't open stream

### ISSUE THREAD

**Issue by FlederFau** [freescout-helpdesk/freescout#2852]
Hello,

I recently installed freescout ver. 1.8.69 on our server. Everything seems to work just fine except fetching mails from our mail provider.
The configuration is like this:
![Bildschirmfoto vom 2023-03-22 13-04-08](https://user-images.githubusercontent.com/81045928/226901157-46c336d9-6f63-451e-8aee-8565cf22d407.png)
The server address is something like xy01s583.org-dns.net
We use the same seetings for fetching our mails with Thunderbird and this works like a charm.
With freescout I get the following error message:
`Error: imap_open(): Couldn't open stream {ha01s029.org-dns.com:993/imap}. [CLOSED] IMAP connection broken (server response); File: /var/www/lyssa/overrides/webklex/laravel-imap/src/IMAP/Client.php (230) `

Sending messages over SMTP with the mail account is working without issues.
I tried our setup with a free mail account from web.de and it is working without any errors.

Some help would be highly appreciated

**Comment by freescout-helpdesk** [comment]
Try to add the following to .env file and clear cache in Manage > System > Tools:
```
APP_NEW_FETCHING_LIBRARY=true
```

**Comment by FlederFau** [comment]
Thanks for the reply!

Now i get connection failed and this is in the log:
`connection failed; File: /var/www/lyssa/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (82) `
the web.de account seems still working

**Comment by freescout-helpdesk** [comment]
It looks like we can't provide more help here. It need to be investigated on your server.
