### ISSUE TITLE
PDF Attachments adding underscore to file extension

### ISSUE THREAD

**Issue by nicksilvia** [freescout-helpdesk/freescout#2853]
Hello,

I have noticed an issue where it seems any PDF that is encoded using PDF version 1.7 (this is what Excel and Word Online use when exporting as a PDF) has an underscore appended to the filename, making the attachment not able to be opened when downloaded unless the file extension is fixed. 

I have confirmed that the file does not contain this underscore when coming into the mailbox, it appears to only get added to the file when Freescout saves the attachments to the server after fetching the email. 

I can confirm that a PDF encoded using PDF 1.6 or 1.3 works fine. Acrobat Pro 2022 exports as 1.6 by default and these files come into Freescout just fine. Mac encodes at 1.3 and these work fine. Any 1.7 doc I download from Microsoft 365 get this underscore appended when Freescout fetches and saves the message/attachments.

I appreciate any assistance that could be offered here, I am at a loss for what to try to rectify the issue.

<img width="273" alt="Screenshot 2023-03-22 at 12 04 12 PM" src="https://user-images.githubusercontent.com/11464061/226966272-c0dfbac0-5800-47a9-a410-5aa2f707c7e9.png">

**Comment by freescout-helpdesk** [comment]
It's by design to avoid security issues.

**Comment by nicksilvia** [comment]
> It's by design to avoid security issues.

Can you clarify this a bit more? Our users are complaining and do not understand why some PDF's would work fine but only 1.7 encoded PDF's add an underscore. What is rationale for this and can it be disabled? This is making the experience of using Freescout confusing because end users just see the files as PDF's and do not understand the nuance of the encoding level. Is Freescout purposely renaming only 1.7 encoded PDF's and why is this? I appreciate any further clarification you can provide about your response so I can understand if this might change or if we have to find a workaround. Thank you for your prompt reply.

**Comment by freescout-helpdesk** [comment]
See:
"Change extension if uploaded PDF file contents JavaScript" https://github.com/freescout-helpdesk/freescout/commit/2a389c5034bdb6d6d4a1fadb6b45b20b3f9cba77

**Comment by nicksilvia** [comment]
> See:
> "Change extension if uploaded PDF file contents JavaScript" [2a389c5](https://github.com/freescout-helpdesk/freescout/commit/2a389c5034bdb6d6d4a1fadb6b45b20b3f9cba77)

Thank you for this information. Much appreciated.

**Comment by muhzak** [comment]
@nicksilvia how are you helping your users with this?

**Comment by muhzak** [comment]
@freescout-helpdesk Is there anyway to just disable this feature if we want? Maybe via env file or some other option?
