### ISSUE TITLE
SMS Module Twilio 11200 error when customer text pics via iPhone

### ISSUE THREAD

**Issue by twillett** [freescout-helpdesk/freescout#2854]
When customer is texting (SMS) the help desk, via Twilio, all works great. However when the customer text a pic Twilio / Freescout give an 11200 error code, per the Twilio logs. If the agent / user replies to the customer via the help desk and send a pic, no error and the customer receives the pic via SMS / MMS.
It appears Freescout is rejecting inbound images and I do not have the module that block external images. Am i missing something or is this and error. And yes, my 888 phone number via Twilio does allows SMS and MMS.

**Comment by freescout-helpdesk** [comment]
Can you give the full error message text.

**Comment by twillett** [comment]
Sure can. I'll post a few viewpoint of the error message, hope one of this is helpful.

NOTIFICATION SID
NO6d0be2ecf6a775b897ee9ac5a7867263
WARNING
 [11200 There was a failure attempting to retrieve the contents of this URL.](https://www.twilio.com/docs/errors/11200)
DESCRIPTION
There was a failure attempting to retrieve the contents of this URL.

**Comment by twillett** [comment]
![Screenshot 2023-03-23 at 8 44 46 AM](https://user-images.githubusercontent.com/2602050/227257755-34943a12-38aa-419b-8553-f237e38ea8f2.png)

**Comment by twillett** [comment]
From Twilio Docs:

Error 11200
ERROR - 11200
HTTP retrieval failure
There was a failure attempting to retrieve the contents of this URL. An 11200 error is an indicator of a connection failure between Twilio and your service. When Twilio requests a page from your server, we wait a maximum of 15 seconds for a response. A connection failure will occur if no response is returned in that time.

There are many reasons a connection timeout can occur; common causes are long running database queries or outside processes and calls to external systems taking a long time to return. It may be possible your application experienced one of these issues. If you are encountering this error only intermittently, it is possible that your web server was temporarily unavailable or experiencing a network outage.

**Comment by freescout-helpdesk** [comment]
Add the following code to /Modules/SmsTickets/Http/Controllers/SmsTicketsController.php on line 60:
```
\Log::error('SMS Tickets Files: '. json_encode($files));
```

Send an sms with an image and check the info in Manage > Logs > App Logs.

**Comment by freescout-helpdesk** [comment]
Closing for now activity.

**Comment by twillett** [comment]
Why is this being closed? I have not seen an update pushed to the module to resolve this.
