### ISSUE TITLE
SMS Module Customer text an issue to helpdesk does not create a new ticket.

### ISSUE THREAD

**Issue by twillett** [freescout-helpdesk/freescout#2855]
When a customer SMS the helpdesk and the ticket gets closed as a normal process, all is good. 
If the customer submits another SMS issue for a different topic a new ticket is not created, Freescout will open the last conversation / ticket and continue the original feed which is not the desired function.

**Comment by freescout-helpdesk** [comment]
All messages received from some customer via SMS always go to the same conversation in FreeScout. This can't be changed.
