### ISSUE TITLE
Freescout extremely slow

### ISSUE THREAD

**Issue by carloand** [freescout-helpdesk/freescout#2856]
Hello,
  every request on my Freescout installation is extremely slow and it finisches with a "mod_fcgid: read data timeout" in Plesk. I increased the max_execution_time from 45 to 120 and now some requests succeed, but some others still get a "mod_fcgid: read data timeout" error.. This is like that since I first installed the program, but now it's getting worse. All requests are like that: login, fetch messages, and even to system/status. Version is 1.8.60 and I can't update automatically. Server is running as FastCGI.
  Is there anyway I can debug the problem? Thank you. Regards;

Carlo

**Comment by freescout-helpdesk** [comment]
You need someone who can debug it. See for example: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by carloand** [comment]
Thank yuo, but I don't like the idea of letting people in my installation. Where could I begin testing it myself? 
Thank you. Regards;

Carlo

**Comment by carloand** [comment]
Ok, found the problem!
I had added APP_NEW_FETCHING_LIBRARY=true in the .env as explained in https://github.com/freescout-helpdesk/freescout/issues/2591 but probablu I hadn't cleared the cache. Clearing the cache as explained in https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache solved my problem.
Regards;

Carlo

**Comment by freescout-helpdesk** [comment]
Great.
