### ISSUE TITLE
Manage --> System unable to open after Update to 1.2.3

### ISSUE THREAD

**Issue by Amandilo1** [freescout-helpdesk/freescout#286]
After the Update to 1.2.3 manage --> system will not more working!

In error log is the following message:
Trying to get property 'id' of non-object (View: ....../resources/views/system/status.blade.php

**Comment by freescout-helpdesk** [comment]
Just open some other page and come back to System.

**Comment by Amandilo1** [comment]
Same Error, I opened other pages, they will work.... But system is not working!

Trying to get property 'id' of non-object (View: /www/htdocs/w01598d5/scout.zucher-duingen.de/resources/views/system/status.blade.php) {"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object (View: /www/htdocs/w01598d5/scout.zucher-duingen.de/resources/views/system/status.blade.php) at /www/htdocs/w01598d5/scout.zucher-duingen.de/storage/framework/views/d04f44d427fb1f9f8a171ad76357ef23d85ea107.php:19, ErrorException(code: 0): Trying to get property 'id' of non-object at /www/htdocs/w01598d5/scout.zucher-duingen.de/storage/framework/views/d04f44d427fb1f9f8a171ad76357ef23d85ea107.php:19)

**Comment by freescout-helpdesk** [comment]
Copy this file https://github.com/freescout-helpdesk/freescout/blob/master/resources/views/system/status.blade.php to `/resources/views/system/status.blade.php`

**Comment by Amandilo1** [comment]
> Copy this file https://github.com/freescout-helpdesk/freescout/blob/master/resources/views/system/status.blade.php to `/resources/views/system/status.blade.php`

Thanks for the fast response, after update the status.blade.php I got a new error in the error log!

> Undefined variable: output (View: /www/htdocs/w01598d5/scout.zucher-duingen.de/resources/views/system/status.blade.php) {"exception":"[object] (ErrorException(code: 0): Undefined variable: output (View: /www/htdocs/w01598d5/scout.zucher-duingen.de/resources/views/system/status.blade.php) at /www/htdocs/w01598d5/scout.zucher-duingen.de/storage/framework/views/d04f44d427fb1f9f8a171ad76357ef23d85ea107.php:39, ErrorException(code: 0): Undefined variable: output at /www/htdocs/w01598d5/scout.zucher-duingen.de/storage/framework/views/d04f44d427fb1f9f8a171ad76357ef23d85ea107.php:39)

**Comment by Amandilo1** [comment]
I had download all views new from GitHub, but it doesn't work anymore!

**Comment by freescout-helpdesk** [comment]
Just update to [1.2.4](https://github.com/freescout-helpdesk/freescout/releases/tag/1.2.4)

See alternative update method [here](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout).

**Comment by Amandilo1** [comment]
Great, good work! Thanks for your very Fast Service!!!!
Thank you very much!!!
