### ISSUE TITLE
Snapshots in Mail are not displayed in the ticket

### ISSUE THREAD

**Issue by dug-adm** [freescout-helpdesk/freescout#2860]
If a user copies a snapshot into an email and sends it to the ticket email address, the image remains in the email but does not appear in the ticket.

Is this due to our mail server or is this not taken over by freescout

**Comment by psuter80** [comment]
in my installation (1.8.69) this works flawlessly. I just sent a screenshot which I've copy/pasted into gmail to our freescout and it appeared nicely in full color in the ticket ;) 

i can think of two possible sources for your problem: 

1. maybe the email client or sending server uses a strange method to embed an image which is not treated correctly by freescout's message parsing
2. your local mailserver does something funky with incoming embedded content (maybe related to a security setting) which then brakes the image for freescout

here is how i would disect that: 

As stated before, I sent the test message using gmail and I embedded the image using copy/paste. So you could now also use a gmail account to send a message to your ticketing system. If that works, it is proably something like option 1 above, if it the image does not make it into your ticket, it is a strong indication for option 2

also check if you can see something in the logs of freescout, or in the debug console of your browser (try both the console and network view). 

hope that helps
