### ISSUE TITLE
no tickets created

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2861]
Right now we have four inboxes connected to Freescout. All of them are working, but since a couple of days only one of them has stopped creating new tickets on new mails.
The mails are read successfully via IMAP and set from unread to read, but no ticket is created. Sending emails works fine and replies to existing tickets are also working.

In the logfiles I can't detect anything suspicious.

**Comment by mokkin** [comment]
Today I received a message 
> fetching recovered
> Previously there were some problems fetching emails. Fetching recovered and functioning now! 

Is this some auto healing magic?

**Comment by Beaudinn** [comment]
maybe related to #2838

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues

**Comment by freescout-helpdesk** [comment]
Closing for now activity.

**Comment by mokkin** [comment]
Actually the number of mails is very low and it's hard to reproduce it. Additionally I have found a misconfiguration in a related sieve script.
I'll reopen it if it occurs again.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here - it need to be debugged on your server.

**Comment by mokkin** [comment]
Is there anything I can do for debugging?
