### ISSUE TITLE
The way to automatically authenticate customer on End-User Portal

### ISSUE THREAD

**Issue by dimono777** [freescout-helpdesk/freescout#2865]
Hello Team!

The documentation is quietly transparent but I could not find one thing. It would be great if you help me with it.

I want my customers to be automatically authenticated when they direct from my website to their Freescout End-User Portal due to the fact that they are already registered on the main website.

I didn't find an API method for getting auth tokens or something like that to authenticate my customers. I did find the module that allows me to log in to the portal from email but it's not fully cover my needs.

**Comment by ilyakonovalenko** [comment]
> I did find the module that allows me to log in to the portal from email but it's not fully cover my needs.

You can check that module code to find out how the link is generated. Then use the same way in your script. Can also be implemented in some different way via modules. There is no built-in option for this.
