### ISSUE TITLE
 Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by TyrannosaurHex** [freescout-helpdesk/freescout#287]
1. Error logs says:

`production.ERROR: file_put_contents(/home/helpdesk/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/home/helpdesk/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): failed to open stream: Permission denied at /home/helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)`

Checked the permission on file "/home/helpdesk/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8", it is 644, changed it to 755. Doesn't help.

2. .env file key exists in `APP_KEY`.
3. Tried clearing the cache, the terminal gives the same permission error. `file_put_contents(/home/helpdesk/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): failed to open stream: Permission denied`
4. Tried generating a new key. Same error as in Pt.3.

Any ideas?

_Originally posted by @TyrannosaurHex in https://github.com/freescout-helpdesk/freescout/issues/31#issuecomment-508523726_

**Comment by solariz** [comment]
Had that several times after Updates, CLI into zour freescout directory and run:

```
php artisan freescout:after-app-update
php artisan freescout:clear-cache
```

should be it.

**Comment by freescout-helpdesk** [comment]
You web server user does not have permissions to write in some folder in `storage`:
```
sudo chgrp -R www-data storage bootstrap/cache public/css/builds public/js/builds
sudo chmod -R ug+rwx storage bootstrap/cache public/css/builds public/js/builds
```

**Comment by TyrannosaurHex** [comment]
Freescout was installed through root, while the modification was being done through www user resulting in the error. 
Had to chmod 777 through root user for it work.
