### ISSUE TITLE
Personal inbox (sales person does not require to see unassigned)

### ISSUE THREAD

**Issue by mversteegh** [freescout-helpdesk/freescout#2871]
Business case: Our company is using a single e-mail adress. At the headquaters a person will assign an e-mail to one sales person. Note that sales persons should not see any messages which are not assigned to them.

Can this be implemented with Freescout?

**Comment by avenjamin** [comment]
Curious - I assume this means you want the conversation between the Sales person and the original ticket sender to be in kept in FreeScout?

Currently you might be able to make this work by CC'ing the sales person on the ticket and the FreeScout user could responding with something like "Sales person x has been assigned to this enquiry".

Both the sales person and the original sender will get the message and either can respond back and forth, both getting each others responses.

Alternatively you could look into setting up a dedicated mailbox for each Sales person that they have access to (user privileges only) and use the Move action to move the ticket from the primary mailbox to the Sales person mailbox.

That way they can use the interface to manage their tickets better.

You may also be able to use the Workflows module to automatically move messages to the Sale person's mail boxes.

Hope that helps

**Comment by freescout-helpdesk** [comment]
> No, you can't restrict access to some conversations, only to whole mailbox. You can write a module to make different logic.

Yes.
