### ISSUE TITLE
Memory Usage Spikes

### ISSUE THREAD

**Issue by zerofruchtshake** [freescout-helpdesk/freescout#2872]
Hi, i have freescout installed on Ubuntu 20.04.4 LTS with the provided Interactive installation bash-script.

I've noticed strange memory usage - see attached image.
Logs are also attached. Any ideas / tips on what to check?

[web-server.log](https://github.com/freescout-helpdesk/freescout/files/11101145/web-server.log)
![Bildschirm­foto 2023-03-29 um 14 55 21](https://user-images.githubusercontent.com/44063194/228544362-84e0be0c-443a-4488-a72b-8b6301cf102f.jpg)
![Bildschirm­foto 2023-03-29 um 14 55 38](https://user-images.githubusercontent.com/44063194/228544373-2a787d90-d553-44c0-b240-300890f73091.jpg)

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
