### ISSUE TITLE
Re-Send of old message, when draft is deleted "while" sending the message (concurrent conversation access)

### ISSUE THREAD

**Issue by psuter80** [freescout-helpdesk/freescout#2873]
I recently ran into the following situation: 
User A writes a reply to a conversation. Right before User A clicks the "Send" button, User B deletes the Draft of the message User A was writing. 

This resulted in a re-send of the last message in that ticket, and the complete loss of the new message. even though user A first saw the message in the conversation right after sending it. 

**Steps to reproduce:** 

1. create a new convesation
2. send a message to an external email address
3. create a new reply to the same conversation 
4. open a second browser window and open the same conversation where you see the draft
5. in the first browser window with the active editor, click send
6. immediately after sending the message, change to the second browser window and discard the draft. This step needs to happen before the message is sent via SMTP. 
7. reload the window in the first browser and note, that the new reply disappeared from the conversation
8. wait a few seconds, then check the "Outgoing Emails" view from the latest still existing message in this conversation, you will notice that it was sent a second time. 

**Screenshots:** 
Two windows, the left one is the "first" window with the active editor, the right one is the "second" window where the draft is shown
![Screenshot from 2023-03-29 17-31-38](https://user-images.githubusercontent.com/22317472/228593243-fee17c27-1eaf-4e26-8dcf-b050f9a0d9f0.png)

right after sending the message (the "Undo" message is still visible in the left window), Discard the draft via the second window: 
![Screenshot from 2023-03-29 17-32-23](https://user-images.githubusercontent.com/22317472/228593695-66309493-8443-4390-81a5-5835d23bc73a.png)

in the first window, the message still shows, in the right window, it is no longer there. once the left window gets reloaded it will look the same as the right one
![Screenshot from 2023-03-29 17-32-59](https://user-images.githubusercontent.com/22317472/228594027-d2beff3b-3951-4783-a443-35ab94d32c67.png)

on the remaining original message, open the "Outgoing Emails" dialog to see, that that message has now been sent twice
![Screenshot from 2023-03-29 17-33-57](https://user-images.githubusercontent.com/22317472/228594388-9cdfa2ae-b699-49ee-b980-b04e40827e90.png)

This is what the customer will see in his inbox: 
![Screenshot from 2023-03-29 17-52-34](https://user-images.githubusercontent.com/22317472/228596694-aaf1ba9f-015b-4e6a-90b9-25881999e314.png)

**Possible Solution**
This behavior could be avoided by adding a quick check if the draft is still a draft right before deleting it.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
