### ISSUE TITLE
Ticket messages jumbled after installing Sticky Notes module

### ISSUE THREAD

**Issue by dealend** [freescout-helpdesk/freescout#2875]
Hello,

We are running the latest version of freescout and just installed the sticky notes module. Upon activation some tickets have messages jumbled in terms of time. For example, instead of being latest at top and earliest at bottom, time stamps will be all over the place. Messages from today can be before messages from January in the same ticket. Screenshot attached. Issue can be consistently replicated anytime sticky notes is enabled.

![Jumbled order](https://user-images.githubusercontent.com/83796325/228624094-2f2e4640-9c0f-4edf-825e-b4e80fc57806.png)

**Comment by freescout-helpdesk** [comment]
Fixed in Sticky Notes Module v1.0.1
