### ISSUE TITLE
"There is a problem processing outgoing mail queue" False error message

### ISSUE THREAD

**Issue by TheMoodBoardz** [freescout-helpdesk/freescout#2876]
A new error message displays in our dashboard however it's false - no errors are occurring.
I can't seem to clear it, and it's caused a bit of confusion.

Checked the logs and nothing shows up as an issue

![image](https://user-images.githubusercontent.com/59126098/228791681-2b4874e2-2d5e-4da5-b009-a66c91e9db66.png)

**Comment by TheMoodBoardz** [comment]
Nope nothing there: 
![screenshot](https://user-images.githubusercontent.com/59126098/228843856-50f1772b-b5de-4fc4-9816-55e42418d8f1.png)

**Comment by freescout-helpdesk** [comment]
What do you see when running in the console:
```
php artisan freescout:send-monitor
```

**Comment by TheMoodBoardz** [comment]
"[2023-03-30 14:44:19] Sending is working"
