### ISSUE TITLE
Moving from One Server to Another

### ISSUE THREAD

**Issue by asasin114** [freescout-helpdesk/freescout#2878]
Here's a different one. We're wanting to move our Freescout install to a different server (from our hosting provider, which makes it an undocumented install, over to a shine new Vultr VPS with a MySQL DB cluster. How would I go about doing this with a way to migrate everything exactly how it is onto the new server?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such tutorial for now. Maybe backup page will be helpful: https://github.com/freescout-helpdesk/freescout/wiki/Backup
