### ISSUE TITLE
[LDAP] Unable to import emails

### ISSUE THREAD

**Issue by bellegarde-c** [freescout-helpdesk/freescout#2883]
When clicking on "Connect & Fetch attributes", I get this as email field:

![image](https://user-images.githubusercontent.com/57196916/229121621-f2e64ee1-89be-499d-8023-3ff7f4e83ea3.png)

This is missing my Active Directory "mail" attribute.

Settings ldap_mapping by hand allows me to workaround the issue:
```

MariaDB [freescout]> select * from options where name="ldap_mapping";
+----+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | name         | value                                                                                                                                                  |
+----+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| 27 | ldap_mapping | a:5:{s:5:"email";s:4:"mail";s:10:"first_name";s:9:"givenname";s:9:"last_name";s:2:"sn";s:9:"job_title";s:11:"displayname";s:5:"phone";s:8:"codepage";} |

```

**Comment by freescout-helpdesk** [comment]
Set `mail` attribute for some user mentioned in parenthesis as a `(e.g.)` .

**Comment by bellegarde-c** [comment]
Most users have a mail attribute. Some test users may not have it.

**Comment by freescout-helpdesk** [comment]
> Set `mail` attribute for some user mentioned in parenthesis as a `(e.g.)` .

There is no need to set `mail` for all users, just for those you see in `(e.g.)`.

**Comment by bellegarde-c** [comment]
Ok, thanks, it works like that. I think the code may be a little more robust et check for users where mail is not null first.
