### ISSUE TITLE
Move or copy saved replies to another mailbox? 

### ISSUE THREAD

**Issue by ipflowss** [freescout-helpdesk/freescout#2885]
Running freescout version 1.8.65  

Our entire team really appreciates and enjoys using freescout.  Thank you so much for an amazing service. 
Is there any way to move or copy saved replies from one mailbox account to another mailbox?  I did some searching and did not find an answer.   Any information will be helpful.

Cheers

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. The only way to copy & paste them manually or via DB.

**Comment by ipflowss** [comment]
What tables am I looking for in the DB?

**Comment by freescout-helpdesk** [comment]
`saved_replies` table.
