### ISSUE TITLE
Spam Module - identification of spam emails

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#2886]
I am wondering how emails are being identified as spam.
Lately quite a few ham emails landed in the spam folder.
The header look like this
` X-Spam-Level: 
X-Spam-Status: No, score=-1.9 required=5.0 tests=BAYES_00,HTML_MESSAGE,  `

I also have some keywords manually added to the Spam filter. But none of wich were present in these emails.

Is there a way to tell what rule was hit / why it was considered spam and tweak it accordingly?

**Comment by freescout-helpdesk** [comment]
When "Automatic Spam Filtering" is enabled the module learns when you mark emails as spam. Algorithm analizes only subject and body of the email and does not check email headers (like "X-Spam-Level", etc). In "Manage » Spam Filter" you can view and reset Spam Filter "Learning Memory" per mailbox.

**Comment by boehmgui** [comment]
By "you can view..." do you maen I can see what wad learned? 
I can only see the size of the learning memory or reset it, which means starting from scratch.

If I mark mails in the spam folder as "no spam" does this influence the classification?

**Comment by freescout-helpdesk** [comment]
You can view the size of the learning memory.

> If I mark mails in the spam folder as "no spam" does this influence the classification?

Yes.
