### ISSUE TITLE
Reporting filtered by custom fields comes Blank

### ISSUE THREAD

**Issue by Mmasri6** [freescout-helpdesk/freescout#2887]
when generating a report with filtering from custom fields it gives result but when downloading the report. it comes only with the header titles without any data.

**Comment by freescout-helpdesk** [comment]
What kind of report are you talking about?

**Comment by Mmasri6** [comment]
conversation report

**Comment by freescout-helpdesk** [comment]
Anything in Manage > Logs > App Logs?

**Comment by Mmasri6** [comment]
no nothing is being shown in the logs. and no error or exception is being thrown by Freescout. it just exports the excel conversation report without any data when custom fields filtering being used.

**Comment by freescout-helpdesk** [comment]
It works fine on our end. Can you reproduce the issue on https://demo.freescout.net/reports/conversations ?

**Comment by Mmasri6** [comment]
not able to register in demo stuck at https://demo.freescout.net/demo/request-access with white page.

**Comment by freescout-helpdesk** [comment]
Try again. You've tried to register during demo instance data resetting.
