### ISSUE TITLE
Implementing Multitenancy feature

### ISSUE THREAD

**Issue by Malekhourani** [freescout-helpdesk/freescout#2888]
I am thinking about implementing Multitenancy feature, but I'm not sure about something related to license-keys.
if `Tenant-1` has `Module-1` and `Module-2`, and `Tenant-2` has `Module-2` and `Module-3`
do i need to set a different license-key for `Module-2` in `Tenant-1` and `Tenant-2`, or it is ok to use the same license-key for all tenants?

**Comment by ilyakonovalenko** [comment]
License keys are per-domain. So you need to have different keys if domains are different as well. Not sure if this can be implemented in any way thought...

**Comment by Malekhourani** [comment]
@ilyakonovalenko what you meant by '_Not sure if this can be implemented in any way thought_' ? is the project's hierarchy/codebase won't allow such an edit? or there is another issue?

**Comment by ilyakonovalenko** [comment]
> is the project's hierarchy/codebase won't allow such an edit? or there is another issue?

There is no way to have more than one copy of the same module. You won't be able to have multiple copies of the same module with different keys or even the same module with different keys.
