### ISSUE TITLE
API / Webhook - Empty subject in Conversation object

### ISSUE THREAD

**Issue by audiopro-git** [freescout-helpdesk/freescout#2890]
PHP Version: 8.1.14
Freescout Version: 1.8.69 
API and Webhooks Version: 1.0.55 

Hello Freescout Team,

on event convo.created the subject is missing in the Conversation object.
The returned value is an empty array an not the subject string.

Thanks for advice
a.

`{
  "id": 754,
  "number": 754,
  "threadsCount": 0,
  "type": "email",
  "folderId": 1,
  "status": "active",
  "state": "published",
  "subject": [],
  "preview": "bla bla....",
  "mailboxId": 1,
....
}`

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. 

![2023-04-04_11-30-27](https://user-images.githubusercontent.com/40499291/229734411-b579588d-6e18-4cac-a42e-dc599558965c.png)

You may need to debug it yourself. Notice that "subject" in your json is an array instead of a string.

**Comment by Bergrad** [comment]
This only happens on the event 'convo.created' 

These are my returns from the API / Webhook Conversation object:

convo.deleted returns:  ..."subject": "Subject String...", -> OK
convo.status returns:  ..."subject": "Subject String...", -> OK
convo.assigned returns:  ..."subject": "Subject String...", -> OK
**convo.created returns:  ..."subject": "[]", ... -> Empty, only Brackets**

If subject on convo.created would by an array, it should not by empty, or?

This is the complete Conversation object for 'convo.created':

{
  "id": 764,
  "number": 764,
  "threadsCount": 0,
  "type": "email",
  "folderId": 1,
  "status": "active",
  "state": "published",
  "subject": [],
  "preview": "text.....",
  "mailboxId": 1,
  "assignee": null,
  "createdBy": {
    "id": 100,
    "type": "customer",
    "firstName": "xxxxxxx",
    "lastName": "xxxxxxx,
    "photoUrl": "https://postfach/storage/customers/e021930806f3dfd17cfcae335c3e6246.jpg",
    "email": "xxxxx@xxxx"
  },
  "createdAt": "2023-04-04T07:19:04Z",
  "updatedAt": "2023-04-04T07:19:04Z",
  "closedBy": null,
  "closedByUser": null,
  "closedAt": null,
  "userUpdatedAt": null,
  "customerWaitingSince": {
    "time": "2023-04-04T07:19:04Z",
    "friendly": "Jetzt gerade",
    "latestReplyFrom": "customer"
  },
  "source": {
    "type": "email",
    "via": "customer"
  },
  "cc": [
    "info@xxxxx.de"
  ],
  "bcc": [],
  "customer": {
    "id": 100,
    "type": "customer",
    "firstName": "xxxxx",
    "lastName": "xxxx",
    "photoUrl": "https://postfach/storage/customers/e021930806f3dfd17cfcae335c3e6246.jpg",
    "email": "xxxxxxxx"
  },
  "_embedded": {
    "threads": [
      {
        "id": 3621,
        "type": "lineitem",
        "status": "active",
        "state": "published",
        "action": {
          "type": "",
          "text": "Arbeitsablauf Posteingang -&gt; Zuweisung Innendienst wurde aufgerufen für Gespräch #764",
          "associatedEntities": []
        },
        "body": "",
        "source": {
          "type": "web",
          "via": "user"
        },
        "customer": null,
        "createdBy": {
          "id": 71,
          "type": "user",
          "firstName": "Workflow",
          "lastName": "",
          "photoUrl": "",
          "email": "fsworkflow@example.org"
        },
        "assignedTo": {
          "id": 8,
          "type": "user",
          "firstName": "Innendienst",
          "lastName": "Team",
          "photoUrl": "https://postfach/storage/users/inbox",
          "email": "fsteam-421254907@example.org"
        },
        "to": [],
        "cc": [],
        "bcc": [],
        "createdAt": "2023-04-04T07:19:04Z",
        "openedAt": null,
        "_embedded": {
          "attachments": []
        }
      },
      {
        "id": 3620,
        "type": "customer",
        "status": "active",
        "state": "published",
        "action": {
          "type": "",
          "text": "xxxxxxxx hat ein neues Gespräch gestartet #764",
          "associatedEntities": []
        },
        "body": "\r\n<div id=\"text\" style=\"text-align: left;\">text.....</div>\r\n",
        "source": {
          "type": "email",
          "via": "customer"
        },
        "customer": {
          "id": 100,
          "type": "customer",
          "firstName": "xxxxxx",
          "lastName": "xxxxx",
          "photoUrl": "https://postfach/storage/customers/e021930806f3dfd17cfcae335c3e6246.jpg",
          "email": "xxxx"
        },
        "createdBy": {
          "id": 100,
          "type": "customer",
          "firstName": "xxxxxx",
          "lastName": "xxxxxx",
          "photoUrl": "https://postfach/storage/customers/e021930806f3dfd17cfcae335c3e6246.jpg",
          "email": "xxxxxx"
        },
        "assignedTo": null,
        "to": [
          "info@xxxxxxx.de"
        ],
        "cc": [],
        "bcc": [],
        "createdAt": "2023-04-04T07:19:04Z",
        "openedAt": null,
        "_embedded": {
          "attachments": [
            {
              "id": 670,
              "fileName": "order.pdf",
              "fileUrl": "https://postfach/storage/attachment/1/7/1/order.pdf?id=670&token=6e152643c47963e93aa3cb5693ef99e2",
              "mimeType": "application/pdf",
              "size": 52524
            }
          ]
        }
      }
    ]
  },
  "event": "convo.created"
}

**Comment by freescout-helpdesk** [comment]
Works fine with `conv.created` event when a customer sends an email to FreeScout.
How are you creating a conversation?

**Comment by Bergrad** [comment]
Sending E-Mail to freescout. Account is IMAP outlook.office365.com 

If I create a Conversation via API it works!
