### ISSUE TITLE
Error: Adding Attachments via API (create Thread)

### ISSUE THREAD

**Issue by Bergrad** [freescout-helpdesk/freescout#2891]
PHP Version: 8.1.14
Freescout Version: 1.8.69
API and Webhooks Version: 1.0.55

Hi Freescout Team,

By adding a 'message' Tread with attachments via Api Request the following error occurs:

`Error downloading a remote file (/home/data/html/freescout/storage/app/attachment/0/2/1/test.pdf): Error: Undefined variable $uri; File: /home/data/html/freescout/app/Misc/Helper.php (1601)`

The thread is added but without the attachments.

The same with http URL (File is available):

`Error downloading a remote file (https://postfach/storage/attachment/0/2/1/test.pdf?id=666&token=4049e3645ebb200e546598012a5a8936): Error: Undefined variable $uri; File: /home/data/html/freescout/app/Misc/Helper.php (1601)` 

Please help, or fix.
A.

**Comment by freescout-helpdesk** [comment]
Do you have `APP_PROXY` set in your .env file?

**Comment by Bergrad** [comment]
No

**Comment by freescout-helpdesk** [comment]
Can you give your API request.

**Comment by Bergrad** [comment]
**Working:** 
`
$file_1 = base64_encode(file_get_contents("https://postfach/storage/attachment/8/4/1/cat-5.jpg?id=665&token=e3c9580d9a3580aded91022a8ad799fb"));
			$file_2 = base64_encode(file_get_contents("https://postfach/storage/attachment/0/2/1/test.pdf?id=666&token=4049e3645ebb200e546598012a5a8936"));

$reply = array (
		'type'			=> 'message',
		'text' 			=> "<div style='font-size: 13.4px;'>bla bla...</div>",
		'user' 			=> $conversation['assignee']['id'],
		'imported'		=> false,
		'status'		=> 'closed',
		'attachments'	=> array(
					0 => array(
					      "fileName" => "cat-5.jpg",
					      'data'		=> $file_1,
	 				      "mimeType" => "image/jpeg"
						),
					1 => array (
						"fileName" => "test.pdf",
						'data'		=> $file_2,
						"mimeType" => "application/pdf")
						)
					);

// Nachricht einfügen
WSFreescout::setThread($id, $reply);`

**NOT Working:**

`$reply = array (
 'type' => 'message',
'text' => "<div style='font-size: 13.4px;'>bla bla...</div>",
'user' 			=> $conversation['assignee']['id'],
'imported'		=> false,
'status'		=> 'closed',
'attachments'	=> array(
0 => array(
	"fileName" => "cat-5.jpg",
	fileUrl" => "https://postfach/storage/attachment/8/4/1/cat-5.jpg?id=665&token=e3c9580d9a3580aded91022a8ad799fb",
	"mimeType" => "image/jpeg"
 ),
 1 => array (
 "fileName" => "test.pdf",
 "fileUrl" => "https://postfach/storage/attachment/0/2/1/test.pdf?id=666&token=4049e3645ebb200e546598012a5a8936",
"mimeType" => "application/pdf")
)
);

// Nachricht einfügen / Add Tread
WSFreescout::setThread($id, $reply);`

**Comment by Bergrad** [comment]
'	
// ----------------------------------------------------------------- //
// Thread Freescout 
// ----------------------------------------------------------------- //

// Create Thread (Post)
public static function setThread($id = 0, $data = NULL) {

return self::getApiResponse("/conversations/$id/threads", 'POST', $data); 
}

// ----------------------------------------------------------------- //
// Freescout API Aufruf
// ----------------------------------------------------------------- //

private static function getApiResponse($url = NULL, $method = 'GET', $data = NULL) {	

try {

	// Array -> JSON
	if ($data) {
		$data = json_encode($data);
		}

	// Api Key für Freescout
	$freescout_api_key = self::$freescout_api_key;

	// Stream Options
	$opts = array(
		'http' => array(
			'header' 		=>	"X-FreeScout-API-Key: $freescout_api_key\r\n".
								"Content-Type: application/json\r\n",
			'method'  		=> $method,
			'ignore_errors'	=> true,
			'content'		=> $data
			),
		'ssl' => array(
			'verify_peer'      => false,
			'verify_peer_name' => false,
			)
		);

	// Stream Context
	$context = stream_context_create($opts);

	// API Aufruf
	if ($result = file_get_contents(self::$freescout_url.$url, false, $context)) {

		// POST Daten -> Array
		$result = json_decode($result, true);

		// Zurück
		return array_merge($result, array('http_response_header' => $http_response_header[0]));
	
	} else {

		return ['http_response_header' => $http_response_header[0]];
	}

} catch (Exception $e) {
	
	// Print error information if any
	return $e;
	}	
}'

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. You may need to debug it yourself.
