### ISSUE TITLE
We love FreeScout and we created a Stripe integration module

### ISSUE THREAD

**Issue by saiftheboss7** [freescout-helpdesk/freescout#2892]
We have been using FreeScout for a few months and we really love how it works. It had worked for us really well. Thanks to the team who worked so hard on this!

We recently created a Stripe integration module and activated it. We thought about open-sourcing the module as well

Here it is https://github.com/weDevsOfficial/Laravel-FreeScout-Stripe-Module

**Comment by freescout-helpdesk** [comment]
Thanks. Added to the Community Modules: https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules
