### ISSUE TITLE
Butten lost in layout stripping

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#2893]
Hi guys,

Quite sometimes we get emails and the cleaning of the layout removes the button. 
Mostly nice designed buttons. 

To know how that looks like we go to the arrow next to time and choose show original. 
Though clicking on that button in show original does not work. 
I go to code and search for the link, copy that and use that link. 

This works for me but not for my colleges :-)

Any idea what happens with these buttons that they do not work/open

**Comment by freescout-helpdesk** [comment]
Either it happens due to broken email HTML or they are being filtered out by HTML purifying algorithm.
