### ISSUE TITLE
Time Recording Module

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2894]
Hi 

I don´t understand the usage of the Time Recording Module.

I want, that the time is recorded as long as I am "in the ticket". So I activated this option in the settings. The clock starts running as soon as I assign the ticket to me. 

But when I navigate "away" from the ticket - for example go to settings or to antoher ticket, the time does not stop. It keeps running.

Another issue is: The Time Recorder never adds a new time record entry. There is always only the currently running clock. Isn´t it possible to see when I spent some time on this ticket? 

I hope you can understand what I mean.

Regards
Benjamin

**Comment by BeSt1979** [comment]
Hello

I have now created a completely new server, reinstalled freescout from scratch and made sure that everything is confirmed with "OK" on the status page. Also queue:work is shown as "running".

Nevertheless, the TimeTracking does not work as I thought it would.

When I open a ticket, the time starts running and when I navigate away from that ticket, the time either doesn't stop at all and never automatically saves a time entry in the ticket - it just keeps running. Or every time I open the ticket again, the timer restarts at 0.

I can recreate this exact behavior on demo.freescout.net. So either it doesn't work the way I understood or imagined, or I'm just too stupid ;-)

Can someone help me with this?

Regards
Benjamin

**Comment by freescout-helpdesk** [comment]
What is your "Tracking Mode" in Time Tracking settings?

**Comment by BeSt1979** [comment]
Sorry, I have a double post... Beacuse this ticket is closed perhaps we should go on in ticket #2944
