### ISSUE TITLE
queue:work shows error

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2895]
I installed FreeScout on my (managed) webserver.
Everythig is running, but the queue:work never changes from "last run: ? last succesful run?" to "running".

I set up the cronjob in the customer portal of my provider, and the cronjob is running. I also ca start it via the provided link as often as I want to, but the status page always shows the red error:

![image](https://user-images.githubusercontent.com/5738613/229785922-1bda686b-1e96-435e-a44e-e9abe428c408.png)

The result when hitting the link on the status page is:
> Running scheduled command: '/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
> Running scheduled command: '/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
>Running scheduled command: '/bin/php' 'artisan' freescout:fetch-emails --identifier=8ea***927 > '/html/freescout/storage/logs/fetch-emails.log' 2>&1
> Running scheduled command: '/bin/php' 'artisan' freescout:reports-collect-data > '/dev/null' 2>&1

The result of the cronjob from my provider is:

> Interpreter: /usr/local/bin/php
> Path: /html/freescout/artisan
> Parameter: schedule:run
> Errorcode: 0
> Date of execution: 22.03.2023 - 15:30:01
> Response:
> sh: ps: command not found
> sh: ps: command not found
> sh: ps: command not found
> sh: ps: command not found
> Running scheduled command: '/usr/local/php/usr/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
> Running scheduled command: '/usr/local/php/usr/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
> Running scheduled command: '/usr/local/php/usr/bin/php' 'artisan' freescout:fetch-emails --identifier=8ea***927 > '/html/freescout/storage/logs/fetch-emails.log' 2>&1
> Running scheduled command: '/usr/local/php/usr/bin/php' 'artisan' queue:work --queue='emails,default,d94***74c' --sleep=5 --tries=1 --timeout=1800 > '/html/freescout/storage/logs/queue-jobs.log' 2>&1

Do you have any idea what I have to do to make it work?

Regards
Benjamin

**Comment by BeSt1979** [comment]
With my webspace provider ps / procps is not installable
Am I right, that this is the problem with the queue:work?

Is it possible to "workaround" the need of procps by freescout or do I have to find another webspace provider?

**Comment by freescout-helpdesk** [comment]
Make sure everything is OK on Manage > System page.
Also see https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
