### ISSUE TITLE
disable to users to delete attachements from a conversation

### ISSUE THREAD

**Issue by GPeti07** [freescout-helpdesk/freescout#2896]
A simple user able to delete attachements from a conversation, but the user have no any permission to delete anything. Is it a bug, or could you add a permission option to withdraw the right to delete attachements?
<img width="196" alt="image" src="https://user-images.githubusercontent.com/96734399/229819065-9794d0de-75a1-4e42-ba22-e3579d688ed8.png">

We also have the Extended Attachments Module, and here is no delete icon, so this part is works well, i think:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/96734399/229819799-9016802f-510a-40c8-841c-5e10a166f3f7.png">

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
