### ISSUE TITLE
Unable to Install modules. 

### ISSUE THREAD

**Issue by jjs-josh** [freescout-helpdesk/freescout#2897]
Having an issue adding two separate modules to the system. 
When i go to install a new module after having purchased the license key i encounter the following error stating that the module was not found.
![image](https://user-images.githubusercontent.com/125841199/229989293-1e0d346c-0c13-450d-84d3-d92142178c13.png)
The issue is occurring with the workflows and custom homepage modules. i already have one module installed and configured but that one was installed some time ago. 

Have cleared cache and ensured free scout is updated to the newest version (1.8.70), both yield no result.

**Comment by freescout-helpdesk** [comment]
Check what result is being returned here: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ModulesController.php#L174

**Comment by jjs-josh** [comment]
![image](https://user-images.githubusercontent.com/125841199/231023948-e06c28a4-31c2-4aea-9485-04667f5621f3.png)
This is the result highlighted for the requested line of code

**Comment by jjs-josh** [comment]
![image](https://user-images.githubusercontent.com/125841199/231024081-a4ab2ae5-2156-4415-97a5-d8f40db975d5.png)
further output

**Comment by jjs-josh** [comment]
Issue is still occurring with the same error, any update on this?

**Comment by freescout-helpdesk** [comment]
It looks like you don't have programming skills to debug the issue. You may need to find someone: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by jjs-josh** [comment]
is there somewhere in the code that references where the nodule directory is being called from?
