### ISSUE TITLE
SMS Module >Add the following code to /Modules/SmsTickets/Http/Controllers/SmsTicketsController.php on line 60:

### ISSUE THREAD

**Issue by twillett** [freescout-helpdesk/freescout#2898]
Add the following code to /Modules/SmsTickets/Http/Controllers/SmsTicketsController.php on line 60:
```
\Log::error('SMS Tickets Files: '. json_encode($files));
```

Send an sms with an image and check the info in Manage > Logs > App Logs.

_Originally posted by @freescout-helpdesk in https://github.com/freescout-helpdesk/freescout/issues/2854#issuecomment-1490192620_

**Comment by twillett** [comment]
This needs to be deployed as an update to the SMS module. Some of us do not know how to update the php file.

**Comment by freescout-helpdesk** [comment]
You'll need to find someone who can do it for you and debug the issue (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer) or you can email us at support@freescout.net to check it on your server.

Also if you have `APP_PROXY` parameter sent in .env file make sure to update FreeScout to the latest version.
