### ISSUE TITLE
Read incoming forwarded emails as new ticket from original sender

### ISSUE THREAD

**Issue by pocketfulofrage** [freescout-helpdesk/freescout#290]
I would love to see FreeScout able to parse through a forwarded email and grab the OP's message as the ticket.

Let's say Joe Smith sends an email to my personal email address that I'd like to make a ticket.  I should be able to forward that message to my FreeScout mailbox, which would generate a new ticket from Joe Smith with his original email body.  (In other words, FreeScout should ignore the "forward" part of an incoming ticket)

**Comment by freescout-helpdesk** [comment]
Maybe it will be implemented in the future. For now you can use "New Conversation" feature, which will create a new conversation from forwaded email:

![2019-07-16_09-27-02](https://user-images.githubusercontent.com/40499291/61270986-eda88000-a7ab-11e9-90b0-9bfd5d31f362.png)

**Comment by webprogrammingsolutions** [comment]
@pocketfulofrage here's a workaround I just discovered. I created a folder called "Tickets" in my email account, and then setup Freescout to only check the Tickets folder. When it reads the new email, it creates the support request from the original sender.

I've only tried this with Gmail, and I found that the email has to be marked as **unread** in order to work.

**Comment by Lucleonhart** [comment]
Any updates on this topic? Forwarding mails from customers would be the one feature we are missing right now.
Thanks!

**Comment by DavidAnderson684** [comment]
I wonder how much is involved in a minimal "first attempt" at this feature?

- Notice that the incoming email address belongs to a support agent, and that the subject has a "Fwd:" prefix (any other prefixes?).
- If so, then read the message to look for the real sender; set the customer to that address instead

Anything else?

I'm not saying I have resources to look at this currently, just trying to understand the issue (I would like to see it implemented - I just forwarded a ticket into Freescout and learned then that that feature isn't there.

**Comment by fulldecent** [comment]
@avidras thank you, to sponsor development of this feature, please see https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

Forwarded email should contain "_F:_", "_Fw:_" or "_Fwd:_" in the subject and must contain forwarded email info in the body, for example:
```
---------- Forwarded message ---------
From: <customer@example.org>
Date: Tue, Dec 15, 2022 at 1:17 AM
Subject: Test
To: <support@demo.freescout.net>
```

**Comment by Lucleonhart** [comment]
Fantastic! Will check it as soon as the release is available.

**Comment by Lucleonhart** [comment]
Or, if thats too much work, can you add ‚WG‘ to the list by default to make all germans happy? ;)

**Comment by elyazalee** [comment]
Nice :) 
And add "De" for french :D

**Comment by freescout-helpdesk** [comment]
Have you ever received emails with these prefixes: "WG: " and "De: "?

**Comment by elyazalee** [comment]
Yes

**Comment by Lucleonhart** [comment]
Daily. As i said each mail forwarded using a mail tool in german will add WG: to the fron like you have FW:

**Comment by elyazalee** [comment]
Hello,

Thanks for adding Fwd in French & German, but there is a problem with this feature:

![bug](https://user-images.githubusercontent.com/6560933/210069538-73766b44-aa0c-4668-b91c-5db720fd6f42.jpg)

**Comment by elyazalee** [comment]
Hello,

@freescout-helpdesk Is it necessary to open a new thread?

**Comment by elyazalee** [comment]
Other example : 

```
<div class="elementToProof"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><br>
</span></div>
<div style="font-family: Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);">
<br>
</div>
<div id="appendonsend"></div>
<hr tabindex="-1" style="display:inline-block; width:98%">
<div id="divRplyFwdMsg" dir="ltr"><font face="Calibri, sans-serif" color="#000000" style="font-size:11pt"><b>De :</b> cedric xxxxxxx <cedsteph35@xxxxxxxx><br>
<b>Envoyé :</b> mardi 3 janvier 2023 22:14<br>
<b>À :</b> Loïc <xxxxxxx@elyazalee.com><br>
<b>Objet :</b> Re: Le paiement de €133,20 est en attente pour INV-002548</font>
<div> </div>
```

![bug3](https://user-images.githubusercontent.com/6560933/210557698-64063c51-7b56-4f6c-9719-47bc28944638.jpg)

**Comment by DavidAnderson684** [comment]
I'm running a version of Freescout including this feature, but it just doesn't work for me. I've tried various methods of forwarding from Thunderbird. The subject has `Fwd:`, the mail is in plain-text only (also tried HTML), and has forwarded email info - but it always gets detected as if it were from me, not from the actual customer.

**Comment by freescout-helpdesk** [comment]
> I'm running a version of Freescout including this feature, but it just doesn't work for me. I've tried various methods of forwarding from Thunderbird. The subject has `Fwd:`, the mail is in plain-text only (also tried HTML), and has forwarded email info - but it always gets detected as if it were from me, not from the actual customer.

Sender's email is the same as user's email in FreeScout? The email has just one recipient?

https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-this-customer

**Comment by DavidAnderson684** [comment]
Yes, and yes. I tried both my account email address and my alternative address as the sender.
I also tried sending from Alpine instead of Thunderbird (and adjusted the subject in Alpine to put the `Fwd:` at the front, since Alpine's default is instead to append `(Fwd)`), and that didn't work either.

**Comment by DavidAnderson684** [comment]
For what it's worth - the default forwarded messages (no alterations necessary) from both clients are accepted by Helpscout.

**Comment by freescout-helpdesk** [comment]
We've changed this behavior in the `master` branch. Now the customer in the forwarded email will be substituted only if there is "@fwd" text added in the beginning of the email.

**Comment by DavidAnderson684** [comment]
This still isn't working for me (Freescout 1.8.70, all modules up to date including Email Commands 1.0.6).... I've forwarded a mail with `@fwd`, and the address Freescout uses for the mail is mine (one of those listed in "Alternate Emails" in my profile), and not the first email found in the body.

In this case it's an HTML mail.

Here's the body, as shown in Freescout when requesting the original message:

```
    <p>@fwd<br>
    </p>
    <div class="moz-forward-container"><br>
      <br>
      -------- Message transféré --------
      <table class="moz-email-headers-table" cellspacing="0" cellpadding="0" border="0">
        <tbody>
          <tr>
            <th valign="BASELINE" nowrap align="RIGHT">Sujet :
            </th>
            <td>Example Support Topic</td>
          </tr>
          <tr>
            <th valign="BASELINE" nowrap align="RIGHT">Date : </th>
            <td>Thu, 6 Apr 2023 15:47:08 +0100</td>
          </tr>
          <tr>
            <th valign="BASELINE" nowrap align="RIGHT">De : </th>
            <td>Ronald McDonald <a class="moz-txt-link-rfc2396E" href="mailto:ronmcd@example.com"><ronmcd@example.com></a></td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      Hi David,
      <div class=""><br class="">
      </div>
      <div class="">(Snipped message - contained no email addresses)
      <div class=""><br class="">
      </div>
      <div class="">Thanks.<br class="">
        <div class="">
          <div dir="auto" style="caret-color: rgb(0, 0, 0); color:
            rgb(0, 0, 0); letter-spacing: normal; text-align: start;
            text-indent: 0px; text-transform: none; white-space: normal;
            word-spacing: 0px; -webkit-text-stroke-width: 0px;
            text-decoration: none; word-wrap: break-word;
            -webkit-nbsp-mode: space; line-break: after-white-space;" class="">
            <div dir="auto" style="caret-color: rgb(0, 0, 0); color:
              rgb(0, 0, 0); letter-spacing: normal; text-align: start;
              text-indent: 0px; text-transform: none; white-space:
              normal; word-spacing: 0px; -webkit-text-stroke-width: 0px;
              text-decoration: none; word-wrap: break-word;
              -webkit-nbsp-mode: space; line-break: after-white-space;" class="">
              <div dir="auto" style="caret-color: rgb(0, 0, 0); color:
                rgb(0, 0, 0); letter-spacing: normal; text-align: start;
                text-indent: 0px; text-transform: none; white-space:
                normal; word-spacing: 0px; -webkit-text-stroke-width:
                0px; text-decoration: none; word-wrap: break-word;
                -webkit-nbsp-mode: space; line-break:
                after-white-space;" class="">
                <div dir="auto" style="caret-color: rgb(0, 0, 0); color:
                  rgb(0, 0, 0); letter-spacing: normal; text-align:
                  start; text-indent: 0px; text-transform: none;
                  white-space: normal; word-spacing: 0px;
                  -webkit-text-stroke-width: 0px; text-decoration: none;
                  word-wrap: break-word; -webkit-nbsp-mode: space;
                  line-break: after-white-space;" class="">
                  <div dir="auto" style="caret-color: rgb(0, 0, 0);
                    color: rgb(0, 0, 0); letter-spacing: normal;
                    text-align: start; text-indent: 0px; text-transform:
                    none; white-space: normal; word-spacing: 0px;
                    -webkit-text-stroke-width: 0px; text-decoration:
                    none; word-wrap: break-word; -webkit-nbsp-mode:
                    space; line-break: after-white-space;" class="">
                    <div dir="auto" style="caret-color: rgb(0, 0, 0);
                      color: rgb(0, 0, 0); letter-spacing: normal;
                      text-align: start; text-indent: 0px;
                      text-transform: none; white-space: normal;
                      word-spacing: 0px; -webkit-text-stroke-width: 0px;
                      text-decoration: none; word-wrap: break-word;
                      -webkit-nbsp-mode: space; line-break:
                      after-white-space;" class="">
                      <div dir="auto" style="caret-color: rgb(0, 0, 0);
                        color: rgb(0, 0, 0); letter-spacing: normal;
                        text-align: start; text-indent: 0px;
                        text-transform: none; white-space: normal;
                        word-spacing: 0px; -webkit-text-stroke-width:
                        0px; text-decoration: none; word-wrap:
                        break-word; -webkit-nbsp-mode: space;
                        line-break: after-white-space;" class="">
                        <div dir="auto" style="caret-color: rgb(0, 0,
                          0); color: rgb(0, 0, 0); letter-spacing:
                          normal; text-align: start; text-indent: 0px;
                          text-transform: none; white-space: normal;
                          word-spacing: 0px; -webkit-text-stroke-width:
                          0px; text-decoration: none; word-wrap:
                          break-word; -webkit-nbsp-mode: space;
                          line-break: after-white-space;" class="">
                          <div dir="auto" style="caret-color: rgb(0, 0,
                            0); color: rgb(0, 0, 0); letter-spacing:
                            normal; text-align: start; text-indent: 0px;
                            text-transform: none; white-space: normal;
                            word-spacing: 0px;
                            -webkit-text-stroke-width: 0px;
                            text-decoration: none; word-wrap:
                            break-word; -webkit-nbsp-mode: space;
                            line-break: after-white-space;" class="">
                            <div dir="auto" style="caret-color: rgb(0,
                              0, 0); color: rgb(0, 0, 0);
                              letter-spacing: normal; text-align: start;
                              text-indent: 0px; text-transform: none;
                              white-space: normal; word-spacing: 0px;
                              -webkit-text-stroke-width: 0px;
                              text-decoration: none; word-wrap:
                              break-word; -webkit-nbsp-mode: space;
                              line-break: after-white-space;" class="">
                              <div dir="auto" style="caret-color: rgb(0,
                                0, 0); color: rgb(0, 0, 0);
                                letter-spacing: normal; text-align:
                                start; text-indent: 0px; text-transform:
                                none; white-space: normal; word-spacing:
                                0px; -webkit-text-stroke-width: 0px;
                                text-decoration: none; word-wrap:
                                break-word; -webkit-nbsp-mode: space;
                                line-break: after-white-space;" class="">
                                <div dir="auto" style="caret-color:
                                  rgb(0, 0, 0); color: rgb(0, 0, 0);
                                  letter-spacing: normal; text-align:
                                  start; text-indent: 0px;
                                  text-transform: none; white-space:
                                  normal; word-spacing: 0px;
                                  -webkit-text-stroke-width: 0px;
                                  text-decoration: none; word-wrap:
                                  break-word; -webkit-nbsp-mode: space;
                                  line-break: after-white-space;" class="">
                                  <div dir="auto" style="caret-color:
                                    rgb(0, 0, 0); color: rgb(0, 0, 0);
                                    letter-spacing: normal; text-align:
                                    start; text-indent: 0px;
                                    text-transform: none; white-space:
                                    normal; word-spacing: 0px;
                                    -webkit-text-stroke-width: 0px;
                                    text-decoration: none; word-wrap:
                                    break-word; -webkit-nbsp-mode:
                                    space; line-break:
                                    after-white-space;" class="">
                                    <div><br class="">
                                      Kind regards,<br class="">
                                      <br class="">
                                      Ron<br class="">
                                      <br class="">
                                      --------------------------------</div>
                                    <div><br class="">
                                    </div>
                                    <div>ADVANCED NOTICE </div>
                                    <div>I will be away from my office
                                      between<span class="Apple-converted-space"> </span><b class="">10  – 14 April 2023</b>.
                                      Thanks.</div>
                                    <div><br class="">
                                    </div>
                                    <div>--------------------------------------------<br class="">
                                      Ronald McDonald<br class="">
                                      Freelance Designer & Developer<br class="">
--------------------------------------------<br class="">
                                      <a href="http://example.com" class="" moz-do-not-send="true">example.com</a><br class="">
                                      <a class="moz-txt-link-abbreviated" href="mailto:ronmcd@example.com">ronmcd@example.com</a><br class="">
                                      +44 (0)1234 567890<br class="">
                                      <br class="">
                                      <br class="">
                                      <br class="">
                                      EMAIL CONFIDENTIALITY NOTICE<br class="">
                                      This message is private
                                      and confidential. If you have
                                      received this message in error,
                                      please notify me and remove it
                                      from your system.</div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br class="">
      </div>
    </div>
    <pre class="moz-signature" cols="72">
```

**Comment by avenjamin** [comment]
Just want to add it's also not working for me either. Doesn't matter if I have `@fwd` or not.

**Comment by freescout-helpdesk** [comment]
Debug this: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L614

You can use `\Log::error('some info');` to write messages to Manage > Logs > App Logs

**Comment by avenjamin** [comment]
So did a few tests and so far plain text emails seem to be ok, but an HTML email didn't pick up the original_sender so I'm thinking the `getOriginalSenderFromFwd()` function needs tweaking.

Will do more testing.

@DavidAnderson684 are you able to see if a plain text email forward works for you vs an HTML email?

**Comment by avenjamin** [comment]
@freescout-helpdesk can we have this issue re-opened while we investigate further

**Comment by freescout-helpdesk** [comment]
You can share here the HTML part of the email where customer's email is mentioned.

**Comment by avenjamin** [comment]
@freescout-helpdesk commit a94f97e appears to have fixed the issue for me now.
I'm happy for this to be closed for now until it rears it's head again 😝

**Comment by CHS-tech** [comment]
Hi @freescout-helpdesk - I am running version 1.8.120 and the @fwd command does not work in my setup. Looking at the Email Commands module, this command isn't listed there - do I have to have this module installed? Neither plain text or HTML emails with the command in the message work. FS displays my name as the sender (Customer) instead of that of the original. @avenjamin does yours work now?

**Comment by CHS-tech** [comment]
> @CHS-tech The @fwd should work without any additional modules.

OK thanks @freescout-helpdesk. It doesn't work either in plain text or HTML with the @fwd command. The issue patch [`here`](https://github.com/freescout-helpdesk/freescout/commit/a94f97e5a2a53ea256f6d286b05db380db74e2c3) exists in my environment but the functionality does not apply to emails sent to the helpdesk.

**Comment by CHS-tech** [comment]
> This doesn't work for me either, and never has (testing with multiple mail clients, different sending formats). Freescout 1.8.120, PHP 8.2.15. I test it every few months to see if it's begun working. Here's the attempt I made just now - this is the body up until the first email address (note the `@fwd` on the first line) - in this case it was forwarded from Thunderbird 115.7.0 :

Oh man don't tell me that! We're about to make this live to our customers and this is a key feature that we thought would work, but our testing has shown doesn't.
