### ISSUE TITLE
Mentions Module: No 'pop-up'

### ISSUE THREAD

**Issue by AdyGCode** [freescout-helpdesk/freescout#2900]
Freescout: 1.8.69
Mentions Module: 1.0.14

Have installed and activated the freescout module.
When using the @... mention capability no name pop-up appears.
Cannot see any JS errors, nor other errors.

Freescout is one bugfix behind, but doubt that a problem.

No log entries that are relevant to the issue.

![2023-04-06 13_53_02-(no subject) - FreeScout and 8 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/60425995/230284585-2fc03234-bb3f-4c2e-85e8-0e769e389860.png)

**Comment by ilyakonovalenko** [comment]
Mentions module only works for internal notes. You can not use it in reply.

**Comment by freescout-helpdesk** [comment]
Yes.
