### ISSUE TITLE
Laravel version upgrade!

### ISSUE THREAD

**Issue by Mohan-vidya** [freescout-helpdesk/freescout#2902]
I want to use your platform for the support panel. But I have a problem why you're not upgrading the Laravel version? At this time Laravel's **latest version is 10** but Freescout is ongoing in **laravel 5** which is an older version that supports **PHP 7.**
Why are you using laravel 5 and what are the benefits?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#why-freescout-is-still-using-laravel-5

**Comment by Mohan-vidya** [comment]
@freescout-helpdesk But I use the latest laravel system on another platform so how to connect to it?

**Comment by freescout-helpdesk** [comment]
Use API (https://api-docs.freescout.net) or Modules (https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development)

**Comment by Mohan-vidya** [comment]
Thanks, @freescout-helpdesk.

**Comment by b4oshany** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/FAQ#why-freescout-is-still-using-laravel-5

This link doesn't state the reason. It sends us down  in a rabbit hole.

I would love to know the reason and if there's any plans on upgrading the laravel version.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#maintaining-security-and-laravel-no-upgrade-policy
