### ISSUE TITLE
Merged tickets does not get merged but deleted

### ISSUE THREAD

**Issue by xteaun** [freescout-helpdesk/freescout#2903]
So, I got a new message from a customer and wanted to merge it with an existing ticket. I click on "merge" in the new message and choose the old ticket thread. Now the new message only gets deleted without being added to the old thread. Am I doing something wrong or is this a bug?

**Comment by freescout-helpdesk** [comment]
Apparently something is broken on your installation. Try to update your FreeScout manuually: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by ilyakonovalenko** [comment]
> Am I doing something wrong or is this a bug?

I personally use merge feature and it works fine. Probably something wrong on your side.
