### ISSUE TITLE
ChatGPT module?

### ISSUE THREAD

**Issue by ioscanner** [freescout-helpdesk/freescout#2905]
Are you working on a ChatGPT module?  One that can take a ticket request and see if chatGPT can answer the question first.  This would be a huge timesaver!

**Comment by freescout-helpdesk** [comment]
Most likely it will not be developed by us. See comments: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/400594

**Comment by freescout-helpdesk** [comment]
https://github.com/code-debug228/hostetskigpt
