### ISSUE TITLE
Satisfaction Rating Module: it gets added to the first email again

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2908]
It seems the module started to add rating code to the first email again. Probably after fix in #2857.

**Comment by freescout-helpdesk** [comment]
Yes. It will be added if Manage » Settings » Emails to Customers » Conversation History option is set to "Do not include previous messages"

**Comment by ilyakonovalenko** [comment]
Oh, sounds bad :-(
Previous code was actually correct, but required some additional threads count check because `count($threads)` was always `1` in case of "Do not include previous messages".
