### ISSUE TITLE
Port in APP_URL

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#2909]
@freescout-helpdesk and @PMendesID I'm also using apache and I've managed to configure apache to use a different port (for example, 9444). I've also updated the `APP_URL` variable inside the .env file to contain the new port (for example, https://www.example.com:9444/freescout).

I did also the `php artisan freescout:build` and `php artisan freescout:clear-cache` commands and now I can successfully open the freescout login page. The problem is the login form that is repeating twice the port value inside the URL action.

@freescout-helpdesk do you have any suggestion to solve this? Thanks.

_Originally posted by @ruben-cruz in https://github.com/freescout-helpdesk/freescout/issues/2831#issuecomment-1503180261_

**Comment by freescout-helpdesk** [comment]
Can you share what you have in the `action` form parameter in the HTML.

**Comment by freescout-helpdesk** [comment]
FYI. We've just checked it with `APP_URL=https://example.org:443` in the .env file and login form works fine.

**Comment by ruben-cruz** [comment]
@freescout-helpdesk it's appearing like this: `https://example.com:9443:9443/freescout/login`. The only way that I managed to put it working was:
- put apache and freescout running on 443 https port;
- added also the 9443 https port to apache;
- aaded proxyreverse to apache to be able to redirect all the 9443 requests to 443 port and respond.

**Comment by ruben-cruz** [comment]
@freescout-helpdesk my .env file has the following: `APP_URL=https://example.com:9443/freescout`.

**Comment by freescout-helpdesk** [comment]
We've checked similar `APP_URL` and it works fine. So it looks like we can't help here. The issue need to be debugged on your particular FreeScout installation.
