### ISSUE TITLE
Tags dropdown suggest

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#291]
The tag input box should search and display existing tags as we type. 

Otherwise we end up with so many different spelling for same item and it defeat the existence of tags.

**Comment by freescout-helpdesk** [comment]
Yes, it will be implemented.

**Comment by freescout-helpdesk** [comment]
Implemented.

**Comment by sam-suresh** [comment]
I afraid this is not implemented yet in yesterday's release;

<img width="410" alt="Screenshot 2019-07-31 at 8 38 02 AM" src="https://user-images.githubusercontent.com/5198092/62175016-a22ad000-b36e-11e9-9f82-e2bdc646deef.png">

**Comment by freescout-helpdesk** [comment]
You need to update Tags module.
