### ISSUE TITLE
Feature request:  SMS ticket response after notify.

### ISSUE THREAD

**Issue by ioscanner** [freescout-helpdesk/freescout#2910]
It would be nice if the SMS notify would allow the agent to respond to the notification of a ticket message.  If not they have to go into the app.  Load it find the ticket and open it and respond.  Tracking the response to a ticket They would need to copy the ticket number.  Say add #1234:  the response they went to send.  This would reply to the ticket number.   I am not sure if SMS tickets will then respond with the updates to the ticket or not once the user has replied to a ticket with SMS tickets.  But would be a nice way to enable full SMS ticket work and track the ticket.  I find once someone gets an agent number they just bypass the system and send SMS to the agent.  Then if they are on vacation they miss the messages.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
