### ISSUE TITLE
SMS messages not sending consistently 

### ISSUE THREAD

**Issue by jswolcott** [freescout-helpdesk/freescout#2912]
My SMS messages do not seem to be sending consistently. Receiving appears to have no problems. It has worked several times however then all of a sudden they just don't send for hours. I checked my twilio logs and don't see errors or attempts there either.

I'm having a hard time tracking down the source of the issue. I don't see any thing in the freescout logs that point to a problem. However, I also don't see any thing in logs that says an attempt is being made to send the SMS message either. I wonder if there is a way to increase the log level or verbosity so I have a better idea of what is going on?

I think the issue could potentially be cron related. I attempted to setup the cron per instructions however I found I was not fetching emails. I didn't see any errors thrown and the cron did seem to be running just fine. So I did a cron via the web URL which solved the email fetch problem. I noticed though it did say that using the web URL cron could have unexpected consequences and was not the suggested method. Again, the cron runs without error and I'm not sure what logs I should be looking at to see what is going on there

**Comment by freescout-helpdesk** [comment]
Yes, most likely your problem is in the background job. All the info is here: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

**Comment by jswolcott** [comment]
Well I was hopeful that would like it for me but unfortunately every thing "looks" to be running fine on that background jobs. Any other ideas?

![image](https://user-images.githubusercontent.com/24848744/232342344-c2972923-f509-4a98-92ec-fd87b8f1296d.png)

**Comment by jswolcott** [comment]
Ok tracked this down to a ton of php modules not being installed. I think the issue was I was running a different CLI php version than on the web front end so the web cron was working but not from CLI.

/usr/local/bin/php-8.0 /var/www/html/artisan freescout:check-requirements  

That bailed me out.

Inbound MMS is working. Replying to inbound MMS is also working. I think my impression was that the telephone icon in the new conversation interface would initiate a new ticket which was texted out to the customer however. I think on further investigation it looks like that functionality does not exist in the current modules.

**Comment by freescout-helpdesk** [comment]
Ok. Great.
