### ISSUE TITLE
Whoops errors on certain logins (2fa-Module Related?)

### ISSUE THREAD

**Issue by atchoooo** [freescout-helpdesk/freescout#2913]
We have an issue similar to what has been reported [here](https://github.com/freescout-helpdesk/freescout/issues/1165) in the past.  Some users gets a "whoops, look like something went wrong" error on login. Then reload the page and they are correctly logged in and the error went away.  It seems it happens only to users that have 2fa enabled.

One of our users also reported that the problem was solved after changing his timezone in his profile, and then reverting back to the right timezone and saving the profile modification again.  

Could saving the profile set some value that solves the problem?

It seems this is the error that shows up when the problem occurs....

`Type error: DarkGhostHunter\Laraguard\Eloquent\TwoFactorAuthentication::toString(): Return value must be of type string, null returned {"userId":14,"email":"jmatte@wealthica.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: DarkGhostHunter\\Laraguard\\Eloquent\\TwoFactorAuthentication::toString(): Return value must be of type string, null returned at /www/html/Modules/TwoFactorAuth/Overrides/DarkGhostHunter/Laraguard/Eloquent/SerializesSharedSecret.php:61)`

Thanks in advance for any help!
Martin

**Comment by freescout-helpdesk** [comment]
Try this https://github.com/freescout-helpdesk/freescout/issues/2849#issuecomment-1479419890 and see that you'll have in the Manage > Logs > App Logs.

**Comment by freescout-helpdesk** [comment]
Closing for now activity.

**Comment by atchoooo** [comment]
I did add it, but I still have reports for at least 1 user that he sees the "whoops" error each time he logs in.

**Comment by atchoooo** [comment]
It seems a fix has been posted:

Fix - Fixed \"toString(): Return value must be of type string, null returned\" (https://github.com/freescout-helpdesk/freescout/issues/2913)

I had posted an excerpt from the log at the top of the thread. Will validate if the fix published worked and if needed will post more logs if the issue is still present.
