### ISSUE TITLE
Open conversations in the same window

### ISSUE THREAD

**Issue by woolmilkpigs** [freescout-helpdesk/freescout#2914]
In conversation list or in search results every conversation opens in a new window/tab. In the HTML output the target of each link is set to "_blank". Is there any option to set it to "_self" by default?

Thanks!

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/10375817/231980736-5d763422-7d12-478d-a165-5ff23b7042a1.png">

If there is a relation to [#109](https://github.com/freescout-helpdesk/freescout/issues/109): the feature is very useful within a canversation to external links. Internal links within freescout should remain within the same window/tab.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to change this.

**Comment by woolmilkpigs** [comment]
Thank you for your reply! Could you please give me a hint where/in which file to edit this for my own installation?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/2a52506a2ce95cdca43997dd64a66c06773516b5/resources/views/conversations/conversations_table.blade.php

**Comment by woolmilkpigs** [comment]
Thanks!

**Comment by zackkatz** [comment]
Hi, I'd like to re-open/bump this. [According to accessiblity guidelines](https://www.w3.org/WAI/WCAG21/Techniques/general/G200), links should open in the same window by default.

Could this perhaps become a setting?
