### ISSUE TITLE
Modify styles of email-templates (e.g. `reply_fancy.blade.php`)

### ISSUE THREAD

**Issue by Moongazer** [freescout-helpdesk/freescout#2917]
The default HTML email source has the following CSS embedded without any possibility to change it: 
```
<style>
    p { margin:0 0 1.6em 0; }
    pre { font-family: Menlo, Monaco, monospace, sans-serif; padding: 0 0 1.6em 0; color:#333333; line-height:15px; }
    img { max-width:100%; }
    a { color: #346CC4; text-decoration:none; }
</style>

<div style="font-family:Arial, 'Helvetica Neue', Helvetica, Tahoma, sans-serif; color: #232323; font-size:13px; line-height:19px; margin:0;">
  <!--
    // ...
  -->
</div>
```
This destroys our company signature, because of inline-styles which makes it looking very different from mails sent by Thunderbird or Outlook. Specifically the global margin-bottom for `<p>`-tags and the `font-size:13px; line-height:19px;` for the main-content are the issues here.

The following template-files are affected:
- `resources/views/emails/customer/reply_fancy.blade.php`
- `resources/views/emails/user/notification.blade.php` (partially)

## Possible solutions:
1. Making it possible to easily overwrite the `reply_fancy.blade.php`, so it can be very well adjusted to the corporate-design.
2. Having general settings for `p-margin`, `font-family`, `font-size`, `color` and `line-height` which can have the above default-settings set. But it should be possible to empty these values so they are not set inside the template (resulting in plain format or fallback to the mail-client defaults). This would allow the administrator to adjust the email styling to make it look equal to company standards.

**Comment by avenjamin** [comment]
I agree it would be nice to have the ability to modify the CSS/template in the FreeScout GUI. 

However, @Moongazer, that line-height style is only applied to <pre> HTML tags so I'm not sure why that would be affecting your company signatures?

I suspect there might be some other CSS styling that could be affecting it.

**Comment by Moongazer** [comment]
@avenjamin Thanks for the fast response. Indeed I looked at the wrong `line-height` attribute while debugging the mail-source to find the issue (updated the answer above).

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
Maybe someone will implement a module for adjusting email templates.

**Comment by Moongazer** [comment]
Everyone who is interested in this feature can up-vote the proposals here:
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/384118
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/390981

**Comment by freescout-help** [comment]
Do you need the ability to adjust hard-coded styles of `<p>`, `<h3>` and other elements inside the email: https://github.com/freescout-help-desk/freescout/blob/dist/resources/views/emails/customer/reply_fancy.blade.php#L31

**Comment by freescout-help** [comment]
Customization & Rebranding Module now allows to add CSS and adjust header and footer of the emails sent to customers.
