### ISSUE TITLE
Advice on contact image

### ISSUE THREAD

**Issue by alberto464** [freescout-helpdesk/freescout#2919]
I would like to recommend a change to be made, it would be good to be able to upload images larger than 64x64 px for contact photos (or that they be resized to 128x128), because currently on retina screens the contact photo is seen very poorly, 64x64 is too little.

If you who know the code know in which file this change can be made I can commission it from our developers.

**Comment by freescout-helpdesk** [comment]
Do you mean to make photos two times bigger like this:

![2023-04-14_19-53-03](https://user-images.githubusercontent.com/40499291/232107898-ad156b2f-7acc-40f4-90ab-dd5ab6a045da.png)

**Comment by alberto464** [comment]
@freescout-helpdesk No, it is not necessary to enlarge the container box, but only the image inside.  Let me explain: if I import a 500x500px photo as a contact image, the platform resizes it to 64x64px.  Keeping the same size of the container boxes, a higher resolution image can be used within it.
On the sites we develop, we are used to using a box half the size of the internal image.  Example: my image is 500x500px wide but on the output HTML it is placed inside a 250x250px box.  This "trick" ensures that images are seen in high resolution even on retina displays.
To solve quickly on FreeScout in my opinion, just make sure that the images are not resized to 64x64 but 150x150.  Or similar.

**Comment by freescout-helpdesk** [comment]
Now it will be possible to set customer photos size via `APP_CUSTOMER_PHOTO_SIZE` .env file variable (implemented in the `master` branch).

**Comment by alberto464** [comment]
@freescout-helpdesk For the "Customer" it works great, but it doesn't work for the FreeScout user profile picture (the one you see by going to domain.tld/users/profile/1)

**Comment by freescout-helpdesk** [comment]
Use `APP_USER_PHOTO_SIZE` parameter in .env .file.

**Comment by alberto464** [comment]
@freescout-helpdesk Not if it needs a new commit other than this: https://github.com/freescout-helpdesk/freescout/commit/59f918f0998e9f35c3d8dbce804b93b4e2437e66

I added the line:

<img width="378" alt="Schermata 2023-04-15 alle 22 41 43" src="https://user-images.githubusercontent.com/23463559/232252424-44bcf57f-682a-40b2-909f-36fb17d636d6.png">

But the result does not change, while for the customer everything works correctly, here it always remains 50x50:

<img width="812" alt="Schermata 2023-04-15 alle 22 41 21" src="https://user-images.githubusercontent.com/23463559/232252482-c5053826-83ff-40f6-9136-acc023720b9a.png">

**Comment by freescout-helpdesk** [comment]
Make sure to pull all commits from `master` branch. https://github.com/freescout-helpdesk/freescout/commit/c329dd5f20461beea95da2a0f70a2fd8ae7aaa7b

**Comment by alberto464** [comment]
Everything is working fine, I'd say we can close the request! Thank you!

**Comment by DanielBendersky** [comment]
Hi, Im not familiar with laravel and want to increase the sice of the APP_USER_PHOTO_SIZE and 
APP_CUSTOMER_PHOTO_SIZE

I added this to the end of the .env file:

APP_USER_PHOTO_SIZE=200
APP_CUSTOMER_PHOTO_SIZE=200


Then Under System--->Tools clicked in CLEAR CACHE button.

Then uploaded a new larger photo to a user, but I stilll get the 50x50 size picture. Please any help in how to configure this will be appreciated.
