### ISSUE TITLE
Allow to store customer emails longer than 191 symbol

### ISSUE THREAD

**Issue by alberto464** [freescout-helpdesk/freescout#2920]
Hi, we are experiencing some problems importing emails that come from Google and notifying us of comments inside shared files. Here are the errors:

<img width="1427" alt="Schermata 2023-04-14 alle 18 15 49" src="https://user-images.githubusercontent.com/23463559/232100421-22929287-42e7-40bb-b95c-450ad4ca59e9.png">

**Comment by freescout-helpdesk** [comment]
We need some more info. Try to comment the following lines in https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L114:
```
            //try {
                $this->fetch($mailbox);
            //} catch (\Exception $e) {
            //    $successfully = false;
            //    $this->logError('Error: '.$e->getMessage().'; File: '.$e->getFile().' ('.$e->getLine().')').')';
            //}
```

Try to fetch an email and send us full error message from Manage > Logs > App Logs.

**Comment by alberto464** [comment]
@freescout-helpdesk after commenting out the code, are you okay with fetching any email or does it have to be the one that's causing the problem?

**Comment by freescout-helpdesk** [comment]
The one that's causing problems.

**Comment by alberto464** [comment]
@freescout-helpdesk I get this error:

<img width="1430" alt="Schermata 2023-04-16 alle 22 57 56" src="https://user-images.githubusercontent.com/23463559/232341955-014cd631-1402-455c-8275-00a2856555b8.png">

**Comment by freescout-helpdesk** [comment]
We need an error mesage from "laravel-2023....log" file.

**Comment by alberto464** [comment]
@freescout-helpdesk As you see from the screen yesterday was day 16, but there are no files with the name "laravel-2023-04-16.log". It does not seem to generate an error on the laravel file.

**Comment by freescout-helpdesk** [comment]
You'll need someone who'll be able to get the full error message and send to us: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by alberto464** [comment]
I understand the problem, the Google mail reports as "reply-to" this:

`s+aorgprfskfgagcliijp9devd2bxuvalopkw7wnlgbkcocbvbulqumnrxxa19hw3sohfzrpp4rkmuqcag_akq-thgbh6mphdrwl0u_anzmdkl9hscfgt5emqrlx-e9u1fakkw-diim99v9toezis87kvtofrzkiq9t_swu725ltaadf5o6cb9og8@docs.google.com`

So for FreeScout the address to be entered in the Database is this one just mentioned (table 'emails' column 'email').
The 'email' column in the Database is in "utm8mb4" which allows a maximum size of 191 characters (767 bytes), but that email address is 201 characters long.

If I set the 'email' column in "utm8_unicode" in the Database, the maximum number of characters becomes 255, and the import is successful.

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution.

**Comment by alberto464** [comment]
@freescout-helpdesk Will there be a fix for this in the next release or not?

**Comment by freescout-helpdesk** [comment]
No. We don't have a solution for emails longer than 191 symbol.

**Comment by alberto464** [comment]
@freescout-helpdesk Even if it's not implemented on installations already in production, why not implement it on new installations? Isn't it just changing the query that generates the database?

**Comment by freescout-helpdesk** [comment]
On some systems a unique index for a VARCHAR field longer than 191 symbol throws an error:
`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`.
https://github.com/freescout-helpdesk/freescout/blob/dist/database/migrations/2018_07_09_052314_create_emails_table.php#L21

Some more on this issue: https://stackoverflow.com/questions/42244541/laravel-migration-error-syntax-error-or-access-violation-1071-specified-key-wa
