### ISSUE TITLE
Responses sent using the ticket number in the subject line open a new ticket

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#2921]
Hello all,

When I send an e-mail to Freescout as a customer, a new ticket is opened in Freescout, as expected. I as a customer also receive the reply email configured in Freescout about the receipt of the ticket as well as the corresponding ticket number in the subject line (I have activated the ticket number module). 

If I as a customer reply to this incoming message (via reply button in my local mail client). This reply is also added to the ticket. Everything works as it should.

However, if I as a customer simply formulate a new empty email and manually add the ticket number to the subject line a la "[#401] My reply", Freescout does not recognise that this is a reply to ticket 401 and opens a new ticket instead. As a customer, I then receive the reply "[#402] [#401] my reply".

Why is it that FreeScout only recognises replies when they are sent using the reply button in the local mail programme and not when I formulate an empty e-mail and manually insert the ticket number in the subject line?

(I have tested this scenario with Thunderbird, Outlook and Apple Mail).

Thank you very much for your help in advance,
Best regards
Lukas

**Comment by lucollab** [comment]
I found a smiliar question at the osticket forum: https://github.com/osTicket/osTicket-1.8/pull/1486

Before freescout i used otrs and i never had this problem.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
