### ISSUE TITLE
Replys in Freescout always set the E-Mail-Adress of the Mailbox into CC

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#2922]
Hello all,

when I answer a customer request in Freescout via the "Reply" button, the email address of the mailbox I am replying from is automatically set to CC. In addition to the reply, this also adds the sent email to the entire conversation history. The reply text of the e-mail is then displayed twice in FreeScout (once as a reply and once as sent e-mails).

If I remove the automatically CCed email address in a reply by pressing "x". My reply is only displayed once and not additionally as a sent e-mail. This makes the conversation process much clearer. The reply is also saved in the "Sent" folder of the mailbox.

Is it possible to deactivate the automatic CC setting by default? Or is there a specific benefit to why the mailbox email address is always automatically CCed?

Many thanks in advance,
With kind regards
Lukas

<img width="1043" alt="Bildschirmfoto 2023-04-15 um 13 34 38" src="https://user-images.githubusercontent.com/14358967/232213998-5178cb9a-f8e4-4d8f-85fd-1c5cd025b995.png">

**Comment by freescout-helpdesk** [comment]
What are the detailed steps to reproduce the issue?
Can you reproduce the issue on demo.freescout.net?

**Comment by lucollab** [comment]
1. Send an email to an email address stored in Freescout.
2. Log in to Freescout.
3. Navigate to the mailbox.
4. open the ticket you have just received
5. click on Reply

Now the e-mail address of the mailbox is automatically set to CC.

I could not reproduce it in the demo version.

**Comment by freescout-helpdesk** [comment]
What's your mailbox email and to which email address are you sending an email. Most likely they are different.
To avoid the issue just specify all mailbox emails in the Aliases field in mailbox settings.

**Comment by lucollab** [comment]
Okay... its the module "sent folder" which causes this behaviour.

That makes sense, of course. I find the "Sent" folder really useful, but would like to do without the duplicate entries in the ticket history. Presumably this will not be so easy to do, right?

**Comment by freescout-helpdesk** [comment]
How does it cause this issue?

**Comment by lucollab** [comment]
You are absolutely right! I had probably accidentally entered the e-mail address with a capital initial letter in the mailbox setting (probably autocorrect of the browser due to the first character in the field).

With a small initial letter, the address is not set in CC. The system has therefore acted completely correctly.

If necessary, an adjustment could be made here regarding "non-compliance" with upper and lower case - if that makes sense.

Or simply enter the correct email address case sensitive :)

**Comment by joshuadouch** [comment]
This was my issue too... thanks guys!

**Comment by lucollab** [comment]
Perfect!

**Comment by JLoCascio** [comment]
Is my experience there is a 255 character limit for email aliases correct ? This seems arbitrary and not useful for situations where multiple aliases exist.
