### ISSUE TITLE
web hook error

### ISSUE THREAD

**Issue by stephenc01** [freescout-helpdesk/freescout#2923]
Hey, 

trying to find the best way to debug this. I am having an issue with web hooks an n8n with the following timeout error. Both URLs work via curl from the container console. 

cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I've tested the public URL and the internal docker URL directly to N8N

I am using free scout 1.8.57 with the api module version 1.0.56

**Comment by freescout-helpdesk** [comment]
Are you using `APP_PROXY` parameter in .env file?

**Comment by stephenc01** [comment]
I do not

<img width="540" alt="Screenshot 2023-04-16 at 8 47 14 AM" src="https://user-images.githubusercontent.com/4701543/232312492-ad81ab09-8c47-4650-a774-b155ec73e345.png">

**Comment by freescout-helpdesk** [comment]
The only way to find out the reason is to investigate it on your server. See https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
