### ISSUE TITLE
Order of messages in conversation are not sorted correctly

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#2924]
Noticed this problem where messages in a conversation are not sorted correctly. See screenshot for example. It should be Apr 4, Mar 29 and then Mar 27.

<img width="117" alt="Screenshot 2023-04-17 at 9 45 39 AM" src="https://user-images.githubusercontent.com/3481438/232376547-6523bc3d-2168-45cc-9b33-bfaaf912ebd3.png">

**Comment by freescout-helpdesk** [comment]
You are using not the latest version of Sticky Notes Module.

**Comment by rosinghal** [comment]
Updated the module. It's fixed now. Thanks for helping so quickly.
