### ISSUE TITLE
Workflow Module: Run multiple times for one conversation

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2926]
Hello.

Recently we added a workflow that assign conversations to everyone after they get closed (unassigned state). Now if customers answer to this conversations, they get reopend and manually reassigned by us, but after closing (again), they still assigned to a specific person because the workflow only triggers once per conversation in general (?). I'd like to know if there is any option we just missed, is this limitation intentional and are there any plans changing this behavior.

Thanks in advance

**Comment by ilyakonovalenko** [comment]
Every workflow only triggers once. So it will unassign conversation only once. You better to develop custom module which will unassign conversation on closed->open status change.
