### ISSUE TITLE
Threading Jira tickets in one conversation.

### ISSUE THREAD

**Issue by kovoks** [freescout-helpdesk/freescout#2927]
One of our customers is using Jira to email us. We do not use Jira. 

The incoming mails from Jira are not threaded into 1 conversation. They decided not adhere to the standard with Message-ID and In-Reply-To.  More about that at https://jira.atlassian.com/browse/JRACLOUD-3933

As I would like to see if Freescout can be adjusted to deal with this, I was looking at the code, but could not quite work out where I have to be, maybe you can point me in the right direction. 

They use the following format for the Message-ID:
<JIRA.$\{issue-id}.$\{issue-created-date-millis}@$\{host}>

So I would like to extract the issue-id from that header on incoming messages and combining that with the value of the X-JIRA-FingerPrint header (that holds a uniq jira-instance id), to make a unique identifier we can use for threading purposes.

Is that a good way to approach this and can you give some hints where to look in the code? If you want to implement it yourself, that's fine too of course, I can provide some demo mails (in private) for that.

**Comment by freescout-helpdesk** [comment]
Here:

https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L354

https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L382

**Comment by kovoks** [comment]
Hi,

Thanks a lot for the pointers.

I've created the patch below. I've kept it easy, as soon as the first Jira message of a Jira-thread roles in, we change the messageId ever so slightly. All follow-up e-mails will have a Reference/In-Reply-To with that MessageId, so will be threaded nicely. Took me a bit, because I ran it for a bit to test it.

```
--- app/Console/Commands/FetchEmails.php.orig	2023-04-19 21:37:38.346078745 +0200
+++ app/Console/Commands/FetchEmails.php	2023-05-10 21:29:44.181934531 +0200
@@ -299,6 +299,17 @@

             $duplicate_message_id = false;

+            // JIRA’s messages contain a Reference / In-Reply-To headers based on the ticket ID.
+            // if we are now seeing the first message of a ticket, adapt the Message-ID a bit,
+            // so all follow-ups in the ticket are nicely threaded.
+            $jira_message_id = preg_replace('/^(JIRA\.\d+\.\d+)\..*(@Atlassian.JIRA)/', '\1\2', $message_id);
+            if ($jira_message_id != $message_id) {
+                $does_it_exists = Thread::where('message_id', $jira_message_id)->first();
+                if (!$does_it_exists) {
+                    $message_id = $jira_message_id;
+                }
+            }
+
             if (!$extra) {
                 $duplicate_message_id = Thread::where('message_id', $message_id)->first();
             }
```

**Comment by freescout-helpdesk** [comment]
Added in the `master` branch.
