### ISSUE TITLE
Adding Cc emails

### ISSUE THREAD

**Issue by marameodesignteam** [freescout-helpdesk/freescout#2928]
Hi can I ask a general question?

We add another input field called Cc emails. This field just provide us to send an auto reply for other emails other than the one who send the ticket. Right now we are having an issue with regards about confirmation emails. We are trying to send also to confirmation emails in Cc email field but can't get the work done.

Can I ask for your input on insights on how can we modify this?

Many thanks!

**Comment by freescout-helpdesk** [comment]
It's not quite clear what you are trying to say.

**Comment by marameodesignteam** [comment]
Hi sorry If I'm not being clear

So we had a support ticket ( Image )
<img width="484" alt="image" src="https://user-images.githubusercontent.com/77822897/234436240-dd529875-dd19-4e8c-acd0-bdc345fd18c5.png">

As you can see there's a Cc field option where clients can add an email addresses if they want to Cc someone on their team about the ticket. Currently we have the auto confirmation email to the person who created the ticket. But what we want is to also send the confirmation email to the Cc email addresses also.

Can I ask for your help and point me onto the right direction where I can see the part of the code that send the confirmation emails? Thanks

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Jobs/SendAutoReply.php
