### ISSUE TITLE
@fwd-function in mail body is not working

### ISSUE THREAD

**Issue by bitworxdigital** [freescout-helpdesk/freescout#2929]
I tried today the @fwd-functions as mentioned in the [wiki](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-forward-customers-email-to-freescout-and-make-it-look-like-it-came-from-this-customer) but i couldnt get it working.

at first i sent a mail from my **gmail** to my personal m365 box (which is the freescout user) and then forwarded it from m365 to my monitored m365 box (support@...) and just added @fwd - no signature, no nothing.
ticket arrived in freescout, but with the email and the name of my personal m365 box, not the gmail, as the feature mentioned. (see screenshots below)

second i tried to forward a mail directly from my gmail (no freescout user) to my monitored m365 box (support@...) and only added @fwd - no signature, nothing else.

please can you help me out?
also in the app logs i couldnt find any error.
<img width="1177" alt="Screen 1" src="https://user-images.githubusercontent.com/22503896/233097322-629be409-3ce0-432c-aad1-3aefb52d32bd.png">

**Comment by freescout-helpdesk** [comment]
Can you attach html of the forwarded email.

**Comment by bitworxdigital** [comment]
> Try with attached `/app/Console/Commands/FetchEmails.php` file and send us messages starting with "[FetchEmails]" from "Manage > Logs > App Logs".
> 
> [FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/11275994/FetchEmails.zip)

see attachment
[laravel-2023-04-19.log](https://github.com/freescout-helpdesk/freescout/files/11277617/laravel-2023-04-19.log)

**Comment by freescout-helpdesk** [comment]
Some more information is needed. Try this FetchEmail.php:

[FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/11280078/FetchEmails.zip)

**Comment by bitworxdigital** [comment]
> Some more information is needed. Try this FetchEmail.php:
> 
> [FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/11280078/FetchEmails.zip)

see here 
[laravel-2023-04-20.log](https://github.com/freescout-helpdesk/freescout/files/11280147/laravel-2023-04-20.log)

**Comment by freescout-helpdesk** [comment]
This this. It should work now.

[FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/11280250/FetchEmails.zip)

**Comment by bitworxdigital** [comment]
indeed - it didnt cut out the header of the fwd email, but i dont know if it is supposed to.
but thx, it did as it should - see attachment.
<img width="1156" alt="Screen_working" src="https://user-images.githubusercontent.com/22503896/233272080-7e4cfa2f-82db-495a-a6af-783d4ce42f1c.png">
