### ISSUE TITLE
[Issue/Bug] Updating not working properly

### ISSUE THREAD

**Issue by MartinH0** [freescout-helpdesk/freescout#293]
When I want to maintain the System and click "Update now" it throws me this error.
But when I just ignore the Error and reload it shows it is on the latest Version.

Happened twice to me..
Here from 1.3.0 to 1.3.1
![FreeScout](https://user-images.githubusercontent.com/17692860/61877025-78952300-aeee-11e9-8e1a-c14e0a42154a.PNG)

Now after reloading it looks like it is on the latest version:
![FreeScout 1 3 1](https://user-images.githubusercontent.com/17692860/61877255-eccfc680-aeee-11e9-9dcb-ef3aab26ce76.PNG)

My question now: was the update completely successful or just partly?
I know some Systems which update the string of the version but the update is not completed so the System now thinks its up to date, but actually its not.
Is this the case or not?

Best regards,
Martin

**Comment by freescout-helpdesk** [comment]
It means your app has been updated.

**Comment by MartinH0** [comment]
Thanks! Just wondered why the error appears and is stating that something went wrong
