### ISSUE TITLE
Schedule Sending Extension: Defaultvalue / remember last used value (in session) for schedule

### ISSUE THREAD

**Issue by giemes** [freescout-helpdesk/freescout#2932]
The extension module "delayed sending" aka "schedule sending" currently works that way, that the dialog always uses the default value: 5 minutes:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/16294248/233183885-62efabd6-552f-402b-91a6-7287d8985ae4.png">

For a better usability:
a) Is there an setting option to at least "remember or set" the Time-UOM to not Minutes but eg. hours?
b) There a possibility to set the default "somewhere" in the settings/properties?
c) could you extend, that the "last used entered value" for the Time-UOM and the value are "remembered" in the current session and is defaulted that way, like: if I set 12 Hours > and send this current issue - we use this also as the default value for the next issue within the same session (means that I do not logout/in again. If I logout/in again, it has to be set again - that would not be a problem).

Appreciate your reply!

Gerd

**Comment by freescout-helpdesk** [comment]
There is no such features for now. Feel free to submit feature requests: https://freescout.net/request-feature/
