### ISSUE TITLE
Additional modules for Community Modules Wiki page and an awesome-freescout list

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#2933]
Just wanted to mention some modules that I created that could be added to the [Community Modules Wiki Page](https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules)

- [Themes](https://github.com/avenjamin/freescout-Themes-Module) - Pick a UI colour theme
- [Following](https://github.com/avenjamin/freescout-Following-Module) - Add a 'Following' folder to your mailboxes
- [Unassigned Count](https://github.com/avenjamin/freescout-UnassignedCount-Module) - Show the number of unassigned tickets in the Mailbox menu

I also created an "awesome-freescout" repo to make it easier for people to discover and add community modules:
- [Awesome-FreeScout List](https://github.com/avenjamin/awesome-freescout)

I've added a bunch already, but there are a fair few more out there that should be included.

Cheers 😛

**Comment by freescout-helpdesk** [comment]
Thanks. Added: https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules
