### ISSUE TITLE
Jira module doesn't change ticket status

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#2937]
FreeScout is connected to self-hosted Jira (v8.20.1). When I create a ticket in Jira from FreeScout, the ticket status and ticket type icons are not displayed. At the same time, if I use ticket search to link a Jira ticket, then everything is displayed correctly.

![2023-04-21_13-28-48](https://user-images.githubusercontent.com/101319104/233614226-3a35a88e-31df-4c63-bdfd-67a9dbbef3bd.png)

If I change the status in Jira from "Open" to "In Progress", then this change will not be reflected in FreeScout. Next to the link to the Jira ticket, the old status of the ticket will be indicated in brackets

![2023-04-21_13-41-24](https://user-images.githubusercontent.com/101319104/233617115-8042008f-3960-44df-b4d4-350e030ef983.png)

Changing the status of a Jira ticket to resolved does not change the status in FreeScout from pending to active, and does not add a note.

![2023-04-21_13-30-54](https://user-images.githubusercontent.com/101319104/233614505-d2f21fc6-2795-451e-b5d7-1904168bd238.png)

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs

Also check requirements (https://freescout.net/module/jira/)

![2023-04-23_17-15-34](https://user-images.githubusercontent.com/40499291/233845019-dad2a7f3-9c13-4f57-9920-bc5f352a83ba.png)

**Comment by SergeyMi88** [comment]
1. Our Jira supports API v.2. If I make a request to https://jira.domain.com/rest/api/2/search?jql=project=XXX it returns the following information:

![2023-04-27_09-18-13](https://user-images.githubusercontent.com/101319104/234778567-8cadc6ea-1e0a-41f0-9144-60b5cf556086.png)

2. Our service is configured to work using the https protocol:

![2023-04-27_09-29-01](https://user-images.githubusercontent.com/101319104/234778719-0e0d1458-1e79-491c-8f5c-e2541cd56aca.png)

3. Please tell me how can I check the third condition and change the settings if necessary (Your FreeScout should NOT be protected with Basic HTTP Authentication)?

There are no error messages in Manage > Logs

**Comment by freescout-helpdesk** [comment]
https://www.google.com/search?q=basic+http+authentication

**Comment by SergeyMi88** [comment]
We do not use Basic HTTP Authentication on our server

**Comment by freescout-helpdesk** [comment]
You'll need someone who can debug it on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer) and figure out what happens when the webhook is triggered.

**Comment by SergeyMi88** [comment]
Can you please tell me if I need to create a webhook in Jira to work with Freescout? If so, is it possible to see information about it somewhere?

**Comment by freescout-helpdesk** [comment]
It should be created automatically when you configure Jira connection in FreeScout.
You can check existing webhooks in Jira administration console > System > Webhooks

**Comment by SergeyMi88** [comment]
I set up the connection in the module using the Jira admin account, but the webhook was not automatically created. I tried setting up a connection on two different Jira servers, but the result was the same. Can I resend the command to add the webhook to Jira or add the webhook manually (if I add it manually, where can I see the settings for the webhook (URL and events))?

**Comment by SergeyMi88** [comment]
I'm sorry for the disturbance. Our admin and I found a problem in our network and now the status of the Jira ticket is displayed correctly and the comment from Jira is added to the ticket, but the option "Change FreeScout conversation status to Active and add a note when linked Jira issue is resolved" still does not work. A note is added, but the status of the ticket in FreeScout remains "Pending"

**Comment by freescout-helpdesk** [comment]
> If the FreeScout ticket was in the Closed status, then the status changes to Active, but this automation does not work for the Pending status.

Fixed in Jira Integration Module v1.0.8
