### ISSUE TITLE
Sometimes there is no a record in Outgoing Emails but the email is sent

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#2938]
Sometimes quite unexpectedly the letter is not sent to the client. For example, today I saw that my reply was not sent on April 20.

![Screenshot from 2023-04-22 06-34-43](https://user-images.githubusercontent.com/77854832/233760475-a7710541-f144-41eb-bdac-a0468a403e9e.png)

![Screenshot from 2023-04-22 06-35-09](https://user-images.githubusercontent.com/77854832/233760454-7e543c4c-693a-4f47-82f6-3b8f92b1b86b.png)

If you look at the list of emails sent, you will see that emails on other tickets were sent before, after, and right at 11:33 a.m.

![Screenshot from 2023-04-22 06-33-17](https://user-images.githubusercontent.com/77854832/233760739-d42542e8-a76b-49cd-a62d-b8a54fb41b76.png)

I checked the logs (https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues), there were no errors on April 20. Background tasks are working, no unnecessary tasks. PHP extensions are enabled in console version of PHP.

This is not the first time this situation has happened. How do I understand why the emails are not going out? Why doesn't the system notify me in any way that a reply hasn't been sent to the customer?

**Comment by freescout-helpdesk** [comment]
Check errors in Manage > Logs > App Logs.

**Comment by il2020** [comment]
> Check errors in Manage > Logs > App Logs.

Есть только одна ошибка, но сегодня.

![image](https://user-images.githubusercontent.com/77854832/233768190-b3a01d3a-0b5a-456b-b96d-4e0d11bf6100.png)

**Comment by il2020** [comment]
> Check errors in Manage > Logs > App Logs.

There are only one error, but today.

![Screenshot from 2023-04-22 09-55-02](https://user-images.githubusercontent.com/77854832/233768279-844fd121-5d90-42b0-a948-9edadbd212d8.png)

**Comment by il2020** [comment]
I ran some tests and was able to reproduce this situation. The good news is that the email does get sent to the client, but somehow strangely.

Steps:
1. In the client's ticket, press the reply button and write some text. You don't need to send it yet.
2. At this time, the client should send something to the same ticket.
3. In the client ticket press "View new message" and then send the message from point 1.

This will result in the client receiving an email with messages in that order:
- client response (from step 2)
- the FreeScout user's reply (from step 3)

But in the FreeScout ticket, the order is different:
- the FreeScout user's reply (from step 3)
- client response (from step 2)

And at the same time in the "Outgoing Emails":

![image](https://user-images.githubusercontent.com/77854832/234189161-b32688c2-01a1-49a0-acc7-1afced8573e7.png)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
