### ISSUE TITLE
user can edit admin profile (on updated installation - not on newly created one)

### ISSUE THREAD

**Issue by gpunktschmitz** [freescout-helpdesk/freescout#2939]
within my installation "prod" (which I set up through a installation-wizard from my hoster '1blu.de') I initially created an installation with v1.8.69 and my hoster automatically updated it over time to the most recent version (v.1.8.71).

the setup has two mailboxes, one admin and one user.

logging in as the user I can navigate to /users/profile/1 - which is the admin-profile where I am able to see and update everything.

I clicked through the wizard of my hoster again and created another freescout installation "test" and there the user is not able to see or update the admin profile page. Downloading both installation folders and comparing them showed that there is one file "/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php" in my "prod" installation which does not exist in the newly created "test".
There are no other differences in any other files other than URL and secrets.

I also double-checked the users-table in both databases - both settings are identical. beeing the admin has the role "2" and the user has the role "1".

how can I debug/find out why on the "prod" installation the user is able to edit the admin-profile whereas on the "test" installation there is a message "access denied".

**Comment by freescout-helpdesk** [comment]
The only way to figure it out is to check it on your server. Try yourself or find someone (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)
