### ISSUE TITLE
FR: Default Notification Settings

### ISSUE THREAD

**Issue by psuet** [freescout-helpdesk/freescout#294]
Just a Feature that would be nice to have:

I would like to be able to set a default "Notification-Policy" so that as a default every new user gets notifications via Mail for new Tickets.

**Comment by moqmar** [comment]
The code for that is in https://github.com/freescout-helpdesk/freescout/blob/dist/app/Subscription.php#L52. I'd suggest to just pull it from a new config file?

**Comment by psuet** [comment]
Thank you @moqmar and @freescout-helpdesk!
