### ISSUE TITLE
Problems with administrators replying directly to emails

### ISSUE THREAD

**Issue by MOACKDC** [freescout-helpdesk/freescout#2941]
After receiving a ticket, the corresponding administrator will receive an email, if they reply directly to the email, the system will report an error
Expected response code 250 but got code "554", with message "554 5.2.252 SendAsDenied; report@123.com not allowed to send as 2@123.com.
We use Microsoft 365, if we enable sendas permissions for this public mailbox(report@123.com), But the client will receive the email from 2@123.com, not from report@123.com.
Is there any way that after the admin replies to the email directly, the customer will receive an notice from the public email address? This way they can all discuss directly in the email without having to log into the system

**Comment by freescout-helpdesk** [comment]
What's your mailbox email in FreeScout?
What are these emails: report@123.com, 2@123.com

**Comment by MOACKDC** [comment]
Just an example mailbox
report@123.com is public mailbox and also is FreeScout SMTP/Fetch mailbox
2@123.com it's a staff email

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
