### ISSUE TITLE
No activations left for this license key

### ISSUE THREAD

**Issue by Bracer50** [freescout-helpdesk/freescout#2942]
Hello,

I found an FAQ showing how to deactivate the license but the issue is that I don't have that hosting anymore so I can't complete this task. I'm trying to use them on my new host. 

When trying to activate any of my modules I get the following error:
No activations left for this license key (Use Deactivate License button to transfer license key from another domain)

Any help would be appreciated.

Thanks,
Bracer50

**Comment by freescout-helpdesk** [comment]
The license can be deactivated on ANY FREESCOUT INSTANCE - old or new or even on https://demo.freescout.net (_just register there_)
