### ISSUE TITLE
Time Tracking Issue

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#2944]
Hello

After Ticket #2894 was closed due to my long "not answering" (SORRY), I have now installed a completely new cloud server, reinstalled freescout from scratch and made sure that everything is confirmed with "OK" on the status page. Also queue:work is shown as "running".

Nevertheless, the TimeTracking does not work as I thought it would.

When I open a ticket, the time starts running and when I navigate away from that ticket, the time either doesn't stop at all and never automatically saves a time entry in the ticket - it just keeps running. Or every time I open the ticket again, the timer restarts at 0.

I can recreate this exact behavior on demo.freescout.net. So either it doesn't work the way I understood or imagined, or I'm just too stupid ;-)

Can someone help me with this?

Regards
Benjamin

**Comment by BeSt1979** [comment]
I have "The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation" activated.

**Comment by freescout-helpdesk** [comment]
"...navigates away from the conversation" means closes the browser tab. Also keep in mind that the timer may stop with about 20 seconds delay.

**Comment by BeSt1979** [comment]
This does not work properly either.
I closed all browser tabs and browser windows last night after work, including the one from Freescout. This morning I have now noticed that the time is no longer running, but also has not saved a time entry. The timer is now set to 6 hours 30 minutes and just keeps running.

**Comment by freescout-helpdesk** [comment]
See Troubleshooting at https://freescout.net/module/time-tracking/

**Comment by BeSt1979** [comment]
There are two points in the Troubleshoot Guide: 

1. Using the latest version of Freescout and TimeTrackingModule. I use Freescout version 1.8.73 and TimeTrackingModule version 1.0.10. Both are the latest versions to my knowledge.

2. Make sure that background jobs are running in Manage > System > Status. Again, I can confirm that everything is set to "OK" on the Status page and the background jobs are set to "running".

Still, it doesn't work - neither with one tracking mode nor the other.

In this screenshot https://freescout.net/wp-content/uploads/edd/2019/11/freescout-time-tracking.png from the module's information page, I see that there are multiple time entries stored in the ticket. There is NO way to achieve this in my installation. 

But also on demo.freescout.net I did not manage to save a time entry, so that in one ticket such multiple entries are stored.

Yes, when I close the ticket, the window appears and I can save the time. Then one entry is saved to the ticket. But that can't be the purpose of the TimeTracking module. We often have tickets or projects that run over several months and where we work on the ticket again and again in several "sections" and then on other tickets in between. If an entry can only be saved when the ticket is completed, how am I supposed to create a traceable time list for the customer if I have to invoice on a monthly basis?

**Comment by BeSt1979** [comment]
Any idea? 
Did you check it on demo.freescout.net?
Is it because I don´t understand it or is there some kind of misunderstanding or is it intentionally or is it a bug?

**Comment by BeSt1979** [comment]
Ok, so there must be any mistake I make.
Could you please see this screen-capture-video: [https://file.io/ZCGqoEn4Zvzr](https://file.io/ZCGqoEn4Zvzr)

In this short clip I open a ticket assigned to me on demo.freescout.net.
The I close the tab and wait around 30 seconds and reopen the ticket. As you can see the timer went on running and no time-entry is stored.

**Comment by freescout-helpdesk** [comment]
Before testing make sure to check "Tracking Mode". On demo.freescout.net it is set to "_The timer starts when the conversation is assigned to the user_" by default and no-one except FreeScout team can change it there.

**Comment by BeSt1979** [comment]
I definitely checked this on my installation. I don´t want to make a publicly accessible video, because I don´t want my urls to be public.

But please trust me:
- All checks on the status page are "OK", queue:work is running
- Tracking Mode ist "The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation."
- I open the ticket in a new tab, work in it, time is running. Then I close the tab.
- Alternatively I also tried not to use a new tab to open the ticket, but open it in the only tab opened in browser and close whole browser after working in the ticket.
- Then I wait at least one minute, but I also tried waiting half an hour.
- Then I reopen the ticket and I see, that the time is either still running or it is paused. But NEVER it stored a entry in the ticket.

What is my mistake??

**Comment by freescout-helpdesk** [comment]
The time log entry is not stored when you close browser tab.

![2023-04-28_13-52-06](https://user-images.githubusercontent.com/40499291/235129307-4692e00c-e827-4797-966c-579ac413566b.png)
https://freescout.net/module/time-tracking/

**Comment by BeSt1979** [comment]
> The time log entry is not stored when you close browser tab.

I do not understand this statement. A little further up I read this:

> "...navigates away from the conversation" means closes the browser tab. Also keep in mind that the timer may stop with about 20 seconds delay.

These two sentences contradict each other. 

According to the latest statement, it is not possible to save a time entry without closing the ticket. This would probably make TimeTracking useless for me as well as for many other users, since you can only save one time per open ticket.

But according to the screenshot on https://freescout.net/module/time-tracking/ it must work somehow, because I see several time entries there. Or are these just due to reassignment to another agent?

**Comment by freescout-helpdesk** [comment]
> Or are these just due to reassignment to another agent?
Yes. Or closing and opening the ticket.

**Comment by BeSt1979** [comment]
Okay, this is sad news.
In this case I would like to give a feature request for TimeTracking:

My suggestion is to add a button to the timer that allows the user to manually save the current time and write it as a time entry in the ticket. This would allow a "work package" to be completed and written to the ticket for billing without having to close the ticket or reassign it.

**Comment by freescout-helpdesk** [comment]
Here: https://freescout.net/request-feature/

**Comment by BeSt1979** [comment]
I posted the Feature Request. 
Thank you.
