### ISSUE TITLE
404 when opening newly created mailboxes

### ISSUE THREAD

**Issue by StefanWirsingStretta** [freescout-helpdesk/freescout#2946]
Hello,

I have already created a few new mailboxes. Every once in a while, opening the mailbox would lead to a 404 ("Oops, the page can't be found).

Now it happens with every mailbox I try to create.

What could be the reason?

Thanks.

**Comment by freescout-helpdesk** [comment]
It's hard to tell what can be the reason. It looks like a broken installation. Try to update your FreeScout via manual updating method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by StefanWirsingStretta** [comment]
That didn't work. Everything is updated and I cleared the cache several times. I had also tried deleting a few mailboxes and creating new ones. Now even mailboxes that previously worked aren't available anymore...

There is no maximum number of mailbox-Ids, is there?

**Comment by freescout-helpdesk** [comment]
> There is no maximum number of mailbox-Ids, is there?
No.

You'll need someone who can debug it on your FreeScout instance (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)
