### ISSUE TITLE
Time Tracking Module showing for users when it shouldn't

### ISSUE THREAD

**Issue by networkpotato** [freescout-helpdesk/freescout#2948]
I have all of these ticked off:

<img width="788" alt="Skjermbilde 2023-04-25 kl  17 10 52" src="https://user-images.githubusercontent.com/32069841/234321940-7a0e6805-1dfd-4954-b54f-040150169180.png">

But the timer is still showing for regular users on assigned tickets.
Shouldn't it be completely hidden?

**Comment by freescout-helpdesk** [comment]
No.
