### ISSUE TITLE
/tmp folder is growing rapidly

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2949]
Observations:
1. Our Freescout server did not work anymore, ,"Connection Timeout.
2. Disc Space (80GB) was full.
3. Restarting server. -> Freescout could be reached again but disc space wass still almost full (approx 70GB) and rapidly growing (+1GB per minute).
4. Checked via SSH: /tmp folder was rapidly growing + 1 GB per Minute.
5. Restarted server again -> This time the tmp folder seemed to be deleted correctly. Only 15GB of disk space was used after restart, and everything seemed to work fine. tmp was not growing.
6. installed all available updates for frescout and modules.
7. tmp folder seemed to stay small, everything worked.
8. two hours later: tmp folder was 50GB again.

See screenshots attached for more details. 

My Linux Admin wrote  when I showed him the Screenshots:
"Seems like the temp files are from the web server, very weird. Must be a bug in Freescout. Please contact freescout support."
![freescout1](https://user-images.githubusercontent.com/28296008/234394735-3faf6890-fdac-4e95-9efb-e6e5ab9e5c2d.jpg)
![freescout2](https://user-images.githubusercontent.com/28296008/234394741-bc78443d-8810-495d-993c-aee8a8a48de3.jpg)
![freescout3](https://user-images.githubusercontent.com/28296008/234394743-2aaea777-b57f-4730-900f-4bde309a15af.jpg)

**Comment by ar-ml** [comment]
Ok, I investigated further:
These are some files that just were created:

sudo inotifywait -m -r -e create,access /tmp 
results in the following output:

/tmp/c816e8bfa1850ce63a4fd99421bd9c2b/ CREATE body
/tmp/ CREATE,ISDIR f806f3ee9737c33a8a08ed2b332a8a9f
/tmp/ CREATE,ISDIR 67c908e86d2bc68e90cec8cb02f638fc
/tmp/ CREATE,ISDIR 76ad311578f79268ec6332f75b35a61e
/tmp/76ad311578f79268ec6332f75b35a61e/ CREATE body
/tmp/ CREATE,ISDIR e835879c12f4ae1bdaf65b99903ce984
/tmp/ CREATE,ISDIR cf040730a13a94ca7c2881e8f8e4678c
/tmp/ CREATE,ISDIR a574a4c6891b23e3df6adca0f92f7c59
/tmp/ CREATE,ISDIR ce9a3df33b1e66053ad793411171bbfa
/tmp/ CREATE,ISDIR 69b928889ae48c4c0c47541f741ad8ea
/tmp/ CREATE,ISDIR 34a17e3abab7914b4f346a7b5c081052
/tmp/ CREATE,ISDIR 1f2b26affbaa31d503d2eca187b18bbd
/tmp/1f2b26affbaa31d503d2eca187b18bbd/ CREATE body
/tmp/ CREATE,ISDIR a4ab6bc9485296de53d5ad229d060816
/tmp/ CREATE,ISDIR 7d47d0c55688b1dffeb6fbd5d329a0f2
/tmp/ CREATE,ISDIR dd143453009462490e83c740db20f15e
/tmp/ CREATE,ISDIR e99a5fb40a86a69955f8906cec1d4e55
/tmp/ CREATE,ISDIR f7ae9e0ce0b3dfa26d3cfd6f94ccf136
/tmp/f7ae9e0ce0b3dfa26d3cfd6f94ccf136/ CREATE body

**Comment by ar-ml** [comment]
If I look into one of hthe "body" files I can see it is an Base64 encoded image file. I used an image decode to find out that each body file is another image attachment of a client that sent this attachment via freescout. 

So how do I proceed now?

**Comment by ar-ml** [comment]
OK, I can see that the files belong to a ticket that has a huge amount of big attachments. Also there seem to be many duplicates of those attachments and my colleague tried to forward it to another email address, which failed due to attachment size restrictions. I guess freescout still tries to send this email, which might create the temp files again and again?  until the disk space is full... Could that be?
How can I solve this?

**Comment by ar-ml** [comment]
Attached you can find a screenshot of the attechements of this ticket. You can see there is a huge amount of duplicates.

![grafik](https://user-images.githubusercontent.com/28296008/234434477-7dca8904-e48e-4ce9-a409-cead7b18d2b5.png)

**Comment by freescout-helpdesk** [comment]
FreeScout weekly cleans it's temp files. Make sure you are using the latest version of FreeScout. If temp files are still not removed try to debug this line: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/CleanTmp.php#L42

**Comment by ar-ml** [comment]
Hi @freescout-helpdesk 
Thank you for your reply. I am using latest freescout version.
Please read all my posts again. This is not an issue that could be solved by deleting the tmp files weekly. 1GB of tmpfiles are created every minute! 
It is an issue with big attachments / duplicated attachments - its a bug that should be fixed.

**Comment by freescout-helpdesk** [comment]
The thing is that in the latest FreeScout temp files are created with `fs-` prefix. Files on your screenshots don't have this prefix - check your web server and PHP configuration.

**Comment by ar-ml** [comment]
I have no idea why there is no fs- prefix on the tempfiles. I am definitely running the latest version.

I solved this for now by deleting the pending email sending job (In Freescout Admin / System settings area), which failed due to the big file size of the ticket attachments.
As soon as I canceled the email sending job and restarted the server, the issue with the growing temp file was gone.

Nevertheless I think, there is something buggy with tickets that have big file attachments. Maybe it also has something to do with merging several tickets with attachments.
As you can see in the screenshots above, the ticket has many duplicate attachments.

**Two suggestions:**
- Maybe Freescout should check for big attachments (> 10MB) when forwarding a ticket via email or generally when sending an email and give the user a warning?
- Maybe also Freescout should cancel an email sending job that could not be sent due to email size limits (after three tries) and display a warning?
