### ISSUE TITLE
Does not add notes to a conversation

### ISSUE THREAD

**Issue by iPublicis** [freescout-helpdesk/freescout#295]
![Adding a note does nothing](https://user-images.githubusercontent.com/2365930/61910033-6f767700-af2b-11e9-9082-b63b978eab93.png)

It keeps asking for a message.

**Comment by freescout-helpdesk** [comment]
Any error messages in browser console or in Manage --> Logs?

**Comment by pocketfulofrage** [comment]
It looks like something is failing to load - probably a CSS file.  Press F12 on your PC to bring up the developer window and check the "Console".  Based on the screenshot, it looks like summernote.css (or something related to summernote) isn't loading.

**Comment by iPublicis** [comment]
Reinstalled and it now works.
