### ISSUE TITLE
Workflow Module: Condition "New Conversation created via End-User-Portal"

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2952]
Hi,
I want to send an Auto-Reply to users that have started a new Conversation **via End-User Portal form**.  The Auto-Reply should **not** be sent, if the Conversation has been started via Email.
Therefore I installed the Workflow Module. But I think a Condition for that is missing.
Can you add it please? Thank you!

![grafik](https://user-images.githubusercontent.com/28296008/234721218-fe2b4fb9-c084-4f4b-bd78-2d92fee28f01.png)

**Comment by ar-ml** [comment]
Good alternative to adding a new Condition to the Workflow Module:

You could add a new text Input Field "SUBJECT-PREFIX" to the settings of the End-User-Portal. With this field it would be possible to specify a subject prefix which would be added to the subject of every ticket that has been submitted via the End user Portal Form.

With this I could easily filter all new Conversations that were started via the End-User-Portal by using an AND Condition.

Ideally you implement both of my suggestions. :-)

![grafik](https://user-images.githubusercontent.com/28296008/234721808-655eb88f-8b7c-4190-92ef-44153d543f13.png)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by ar-ml** [comment]
Hi @freescout-helpdesk   
I will submit a feature request, but just to be sure I understand correctly:
Currently it is NOT possible to send an Auto-Reply to users that have started a new Conversation via End-User Portal form???
(The Auto-Reply should not be sent, if the Conversation has been started via Email.)

**Comment by freescout-helpdesk** [comment]
> Currently it is NOT possible to send an Auto-Reply to users that have started a new Conversation via End-User Portal form?

Yes.

**Comment by freescout-helpdesk** [comment]
We've just double checked and auto reply is being sent for tickets created via End-User Portal form (if auto reply is enabled in mailbox settings).
