### ISSUE TITLE
Saved replies module suggestion

### ISSUE THREAD

**Issue by adrianmxh** [freescout-helpdesk/freescout#2955]
Could you please make the Saved Replies module so that when we click on Saved Replies icon, it automatically focuses on the field where we have to search for a reply? It would be nicer if this would be added so we can automatically search after clicking on the icon. This is the normal behavior in helpscout, would be nice to have it here too. At the moment we have to click on the icon and then click again on the search field to be able to search.

I have also attached a screenshot below:

https://prnt.sc/XiyAsJ9aki4g

**Comment by freescout-helpdesk** [comment]
Implemented in Saved Replies Module v1.0.23
