### ISSUE TITLE
@fwd not working anymore

### ISSUE THREAD

**Issue by adrianrss** [freescout-helpdesk/freescout#2956]
I just tried this feature again and it doesn't seem to work anymore in the latest version.
I'm adding the @fwd and it simply gets ignored and it makes me send the answer to the person who forwarded the email instead of the customer itself.

Screenshot attached:
https://prnt.sc/WguxsH29gVWy

Any ideas?

**Comment by avenjamin** [comment]
What version of FreeScout are you using?

There was a fix in a recent release that resolved this same issue for me.

If you're not on the latest update I'd recommend upgrading and testing again.
