### ISSUE TITLE
Multiple questions in the CSAT

### ISSUE THREAD

**Issue by VSinghhh** [freescout-helpdesk/freescout#2957]
Is it possible to create multiple questions in the CSAT like:
1. How knowledgable did you perceive the agent?
2. How fast did you feel you got a reply from us?
3. How satisfied are you, overall, of our services?
With a 1-5 rating

If not possible; are you guys considering implementing that? Preferably if we could have different set of questions for different inboxes.

Of course this should be possible to analyze in the reporting/analysis section

**Comment by freescout-helpdesk** [comment]
Unfortunately it's no possible. Feel free to submit a feature request: https://freescout.net/request-feature/
