### ISSUE TITLE
First line in answer is empty, if using saved replies

### ISSUE THREAD

**Issue by marckemmer** [freescout-helpdesk/freescout#2958]
please see my video describing this small issue: [https://youtu.be/Lv1p0gdU5Rw](https://youtu.be/Lv1p0gdU5Rw)

**Comment by freescout-helpdesk** [comment]
> It's a known issue, the developers didn't find a fix yet unfortunately

Yep.

**Comment by mokkin** [comment]
The [changelog](https://freescout.net/module/saved-replies/?changelog=1) suggests it is fixed in 1.0.26, but after updating it still occurs.

**Comment by freescout-helpdesk** [comment]
Can you share your Saved Reply source code? You can get it via Code View button:

![2023-08-13_16-20-40](https://github.com/freescout-helpdesk/freescout/assets/40499291/10ec50c6-1ff4-4ce7-870b-75cf7e667c5e)

**Comment by mokkin** [comment]
Thank you! Keep it closed.

There was just an additional `div` container.

**Comment by ilyakonovalenko** [comment]
This would fix the issue:
```
$('#body').summernote('code', response.text);
```
But it will also replace all the content. Sounds good for me though.

**Comment by ilyakonovalenko** [comment]
@freescout-helpdesk would it be possible to implement my fix? Looks like a stable solution.

https://github.com/freescout-helpdesk/freescout/issues/2958#issuecomment-1680380592

**Comment by freescout-helpdesk** [comment]
Unfortunately not, we don't want to replace the whole reply content.

**Comment by ilyakonovalenko** [comment]
It seems summernote actually fixed the issue (https://github.com/summernote/summernote/pull/4318). Does FreeScout use the latest version of summernote?

**Comment by freescout-helpdesk** [comment]
No. It's own vivisected version of summernote. We've applied the patch and will add to the next release.

**Comment by freescout-helpdesk** [comment]
Continuation here: https://github.com/freescout-helpdesk/freescout/issues/3319
