### ISSUE TITLE
Different name when using saved replies

### ISSUE THREAD

**Issue by adrianmxh** [freescout-helpdesk/freescout#2960]
Hi there,

Is there a way we could use the name which is in the subject/email name rather the one which is pulled by freescout? Freescout currently pulls the name out of the email address instead of email subject/email address name.
Basically we have the client p.ross@google.com and email subject says Contact message from Patrick and when using a saved reply, freescout says Hi p.ross instead of Hi Patrick.
I've also added a screenshot about this below.

Can anything be done about this? In most cases the real name of the client is actually the one provided by him as his inbox name, not the one in his email address like p.ross

Screenshot:
https://prnt.sc/bp5NZqgNsAin

**Comment by freescout-helpdesk** [comment]
Unfortunately technically  it's not possible.
