### ISSUE TITLE
Feature Request: Notification or Check if ticket has been updated in the mean time

### ISSUE THREAD

**Issue by srjbrouwer** [freescout-helpdesk/freescout#2961]
Feature Request

Scenario:
UserA is working on Ticket X
UserB assigns Ticket X to another agent or posts an internal message.
UserA does not get any notification until he refreshes

Solution:
Automatically update the screen of UserA in case the assigned user or internal messages change.

**Comment by freescout-helpdesk** [comment]
It's already implemented - check on demo.freescout.net

**Comment by srjbrouwer** [comment]
Thanks for the quick reply, we tested on our environment, what should we experience?

**Comment by freescout-helpdesk** [comment]
Check on demo.freescout.net to see how it works.

**Comment by nvnes-sba** [comment]
As tested in the demo environment:
![Screenshot](https://user-images.githubusercontent.com/132343397/235621301-028df3d1-c1e6-41fd-9918-4c047de77b3e.png)
On the right screen the internal note has been added.
On the left screen there is no visual indication that there has been a change in the internal note.

With a message there is a popup / alert that a new message is available, but with an internal note or change in appointed user there is no further visual indication.

Hope this clearifies.

**Comment by ilyakonovalenko** [comment]
> On the left screen there is no visual indication that there has been a change in the internal note.

This is what I noticed as well. Internal notes are only shown after page reload.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be released in the next release.
