### ISSUE TITLE
How can I switch to STARTTLS on an SMPT connection?

### ISSUE THREAD

**Issue by sanipai** [freescout-helpdesk/freescout#2962]
I have only TLS, SSL or no security on SMPT but I need STARTTLS as security

**Comment by AliakseyM** [comment]
Try it https://github.com/freescout-helpdesk/freescout/issues/2591#issuecomment-1398006156 and https://github.com/freescout-helpdesk/freescout/issues/2591#issuecomment-1434150716

**Comment by freescout-helpdesk** [comment]
You can do this in Docker too.
