### ISSUE TITLE
Inappropriate converting of umlauts in subject

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#2965]
Hello.

We got a strange behaviour reported when someone is trying to copy the subject of a conversation/email (Schadensmeldung FÜ230414439), paste it somewhere else inside the browser (atleast in latest chrome) and try to delete (backspace) the character Ü, which gets not deleted but instead, turns into an U.

The header information seems to be correct

`Subject: =?UTF-8?Q?Schadensmeldung_F=C3=9C230414439?=`

The website [https://unicodelookup.com/](https://unicodelookup.com/) reveals that the Ü is some sort of a combined character (?)

combined Ü

![image](https://user-images.githubusercontent.com/12407767/235680314-e1a25127-e7a1-4309-b0ea-8e3d729c1e9e.png)

manual typed Ü

![image](https://user-images.githubusercontent.com/12407767/235680475-4089b727-8680-4b3a-a27a-4201b28b9474.png)

This is a problem for us since we sometimes use the subject (or parts of it) to compare or search things in our database where things usually correct encoded/converted.

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY` env variable?

**Comment by sofl88** [comment]
No to both.

**Comment by freescout-helpdesk** [comment]
Try to add the following to .env file and clear cache:
```
APP_NEW_FETCHING_LIBRARY=true
```

**Comment by sofl88** [comment]
I tried but the issue is still there

**Comment by sofl88** [comment]
Reproducible in the freescout demo if that helps

**Comment by sofl88** [comment]
It seems the falsy conversation takes place here

https://github.com/freescout-helpdesk/freescout/blob/2fe0f518be3bf29a3677257b19fa482ea7d17d8c/overrides/webklex/laravel-imap/src/IMAP/Message.php#L330

when I change this line to

`$this->subject = iconv_mime_decode($header->subject,0,'UTF-8');`

But I don't know if this is a suitable solution in general.

**Comment by freescout-helpdesk** [comment]
Now `iconv_mime_decode()` function will be used for UTF-8 encoded subjects.
