### ISSUE TITLE
Insert Variable Field too big

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2966]
See Screenshot:
![image](https://user-images.githubusercontent.com/28296008/235722539-c692f513-eb16-43e3-a01d-7e7386c6f88c.png)

Proposal for fix:
Please add the follosing code to your CSS stylesheet:

.summernote-inservar{
max-width: 200px;}

![image](https://user-images.githubusercontent.com/28296008/235722870-c8c7184e-b086-4398-be04-3f486e7f4236.png)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. How have you managed to make the field so wide?
What browser are you using?

**Comment by ar-ml** [comment]
I am using firefox 112.0.2 (64-Bit) on a windows machine with a 4K monitor.
I did not change anything, the field just was that wide suddenly. Maybe it has to do with the German translation or my screen resolution / pixel density. 
Anyway, I really think you can add 
.summernote-inservar{
max-width: 200px;}
and this will solve the issue.
Also I am pretty sure the max-width property won't break anything for other users, right?

**Comment by freescout-helpdesk** [comment]
We've reproduced the issue in Firefox.
