### ISSUE TITLE
Fetch email settings for local user email account not working

### ISSUE THREAD

**Issue by razcgit** [freescout-helpdesk/freescout#2968]
Can anyone help?
I have created a local user account in our exchange server and am trying to test the Fetch email settings but keep getting the error attached.
FS has been installed on Ubuntu (nginx/1.18.0, PHP 8.2.5). Testing is being done on a win 11 client machine using Chrome.
Regards, Raz

![2023-05-03 15_52_20-Logs - FreeScout](https://user-images.githubusercontent.com/129358859/235841924-59d88da9-a9cf-4e7d-b48b-efd9f0b91054.png)
![2023-05-03 15_50_44-Connection Settings - ITSupport](https://user-images.githubusercontent.com/129358859/235841929-b6e7d036-95e1-47f2-a9db-c2e868afb45d.png)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth

**Comment by razcgit** [comment]
Thanks. Worked it out. Had the wrong name for the IMAP server. 
UI for FS mailbox looks really clean and simple. Loving it already..
