### ISSUE TITLE
A table in an HTML email does not display correctly

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#2969]
Below are two screenshots of the email: the first is on the conversation page, the second is in the original message window.

Is it possible to correct the display? Does this require any additional data?

![Screenshot from 2023-05-03 11-34-06](https://user-images.githubusercontent.com/77854832/235868352-73594dea-95ce-4973-b9d3-7063c4b73528.png)

![Screenshot from 2023-05-03 11-37-02](https://user-images.githubusercontent.com/77854832/235868520-2d41c114-07ae-43ed-b50b-cde55034ee84.png)

**Comment by freescout-helpdesk** [comment]
HTML code of the email from Body tab is needed.

**Comment by il2020** [comment]
The body of the email is very large, is not fully displayed:

![image](https://user-images.githubusercontent.com/77854832/236611267-e4bb5b35-f7d5-4fb1-bbe3-4ac6dc6b309f.png)

I was able to find the part where there are tables.

[msg.txt](https://github.com/freescout-helpdesk/freescout/files/11411834/msg.txt)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
