### ISSUE TITLE
SMTP without Password

### ISSUE THREAD

**Issue by psuet** [freescout-helpdesk/freescout#297]
When trying to save SMTP settings without password, the website saves the settings and shows the classic "Oops, something went wrong"-Page

Saving SMTP Settings without Username and Password should work without an error

**Comment by freescout-helpdesk** [comment]
Can not reproduce the issue. Which app version are you using? Are changing Mail Settings in System --> Settings or Sending settings for a mailbox? Could you please describe step-by-step what you are doing.
