### ISSUE TITLE
Workflow do not longer work

### ISSUE THREAD

**Issue by marckemmer** [freescout-helpdesk/freescout#2970]
after upgrading to 1.8.74 the workflows do no longer work.

We have a workflow which move e-mails with a special subject to another mailbox. 

This workflow does no longer work after upgrading to 1.8.74 today. If I click on the workflow and then press the button "Save & Execute" it does work.

What is the best way to find the problem?

**Comment by freescout-helpdesk** [comment]
Apparently something went wrong during update. Update using manual updating method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by marckemmer** [comment]
That did not help. I did a complete reinstall. That worked. Thank you for your help.
