### ISSUE TITLE
Tags improve search: "Dropdown Suggestions" and "Search for Tag Combinations"

### ISSUE THREAD

**Issue by zpfvo** [freescout-helpdesk/freescout#2971]
### 1. Dropdown Suggestions
Would be nice if tag search hat the same dropdown suggestions like when you create the tags (see  #291)

### 2. Search for Tag Combinations
As of today it is not possible to search for a combination of tags: For example we tag tickets with a general region and with a category the ticket falls in. If we want to list all tickets of a category in a specific region we can not do that.

**Comment by freescout-helpdesk** [comment]
Feel free to submit feature requests: https://freescout.net/request-feature/
