### ISSUE TITLE
no regular paste in "To" field possible

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2973]
Unfortunately it is not possible in Firefox 113.0 on Ubuntu 22.04 to paste email addresses via right click and paste into the "To" field of a new conversation.
Ctrl + V is working, but maybe not known by average users.

**Comment by mokkin** [comment]
[Bildschirmaufzeichnung vom 05.05.2023, 00:11:00.webm](https://user-images.githubusercontent.com/2938748/236340627-d9a8e524-199f-4319-80c2-ab5f0f43a5b1.webm)

**Comment by freescout-helpdesk** [comment]
It looks like no-one is interested in implementing this.
