### ISSUE TITLE
Reports module suggestions

### ISSUE THREAD

**Issue by adrianrss** [freescout-helpdesk/freescout#2974]
Hi there,

Could you add an option to choose to see the reports for Today, Yesterday or Last 7 days as HelpScout has? I think this would help moving faster other than choosing the dates and days manually every time.
I would be very much interested in having a Today or/and Yesterday button and see the exact reports instead of choosing the dates and days manually.

Thank you in advance, would love to see this added and I think others would like this too :)

Example:
https://prnt.sc/GMb83Ir9Vurf

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
