### ISSUE TITLE
Sending a e-mail invitation to a user - strange mail

### ISSUE THREAD

**Issue by mkduew** [freescout-helpdesk/freescout#2975]
If you send a e-mail invitation to a new user, the invitation e-mails looks very strange (see screenshot in Google Workspace).

We are using 1.8.74 with the German language.

![screenshot](https://user-images.githubusercontent.com/17476152/236222367-b06b98fa-8321-4d43-a913-5a6c2c5bf2eb.png)

**Comment by freescout-helpdesk** [comment]
Something is wrong with the mail server specified in Manage > Settings > Mail Settings.
