### ISSUE TITLE
Manage / Settings / Mail settings are prefilled

### ISSUE THREAD

**Issue by mkduew** [freescout-helpdesk/freescout#2978]
see screenshot 
![screenshot](https://user-images.githubusercontent.com/17476152/236260324-dc604feb-e47c-4bbf-89dc-f523b246dbf0.png)

we are using 1.8.74 - if we change the mail settings and switch the "Send Method" to SMTP, the server, port and password is prefilled (maybe from a testserver from the developers?)

**Comment by mkduew** [comment]
I installed via git

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
