### ISSUE TITLE
Some attachments from M365 mailbox not saving to emails in freescout.

### ISSUE THREAD

**Issue by ezy3** [freescout-helpdesk/freescout#2979]
Hi Team, 
We are having issues with freescout not saving attachments from emails. It pulls the email in but not the attachments. I get the following errors in the log file. I emailed the support email a couple of times now with no response? Is there paid support available? I really like the planform and don't want to have to abandon it. 

[laravel-2023-05-03 (1).log](https://github.com/freescout-helpdesk/freescout/files/11402275/laravel-2023-05-03.1.log)

**Comment by freescout-helpdesk** [comment]
There is nothing suspicious in the log. Most likely the problem is with permissions.

https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-inline-images-do-not-display-and-attachments-lead-to-404-errors
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by ezy3** [comment]
Hi Team, I will take a look at the links provided. If it were a permission issue would it not save any attachments. For us its not all attachments. Some save others don't. I can make any connection file type, size etc.

**Comment by ezy3** [comment]
Also got tow of these in Sent errors? Does that mean that response just never went out to the customer? 

Expected response code 250 but got code "554", with message "554 5.3.4 Content conversion limit(s) exceeded; STOREDRV.Submission.Exception:ConversionFailedException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]ExceedsLimit ConversionFailedException: ExceedsLimit[EndDiagnosticData] [Hostname=ME2PR01MB4417.ausprd01.prod.outlook.com] "; File: /home/homeinst/help.homeinstead.me/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php (457)

An then in the App logs there are heaps of these? Is this perhaps why only some attachments are attaching to incoming emails? 

Expected response code 250 but got code "554", with message "554 5.3.4 Content conversion limit(s) exceeded; STOREDRV.Submission.Exception:ConversionFailedException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]ExceedsLimit ConversionFailedException: ExceedsLimit[EndDiagnosticData] [Hostname=ME2PR01MB4417.ausprd01.prod.outlook.com]

**Comment by freescout-helpdesk** [comment]
`554 5.3.4 Content conversion limit(s) exceeded...` - this error is related to sending emails: https://social.technet.microsoft.com/Forums/windows/en-US/edda2d86-6f11-4b87-9515-8895d4a80387/554-534-content-conversion-limit-exceeded?forum=Exch2016MFSM

You'll need to contact MS365 Team to figure it out.

Incoming attachments most likely are not received due to similar issue with your MS365 configuration.

**Comment by ezy3** [comment]
This issue is only present in Freescout, attachments are delivered and sent fine from the mailbox itself on OWA and Outlook?

**Comment by freescout-helpdesk** [comment]
In this instruction https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth you are creating an app. The issue can be relatedto this app configuration.

**Comment by ezy3** [comment]
Thanks, I'll check it out. I did follow the guide on setup. But will review.

**Comment by ezy3** [comment]
The status wasn't granted for all of the API permissions. Only 3 were green. I did just gran admin consent. Will see if that fixes the issue. Thank you so much for your assistance with this. 
![image](https://user-images.githubusercontent.com/87155109/236401791-6c5be1bd-4392-4f1d-b803-c6d544a80d00.png)

**Comment by freescout-helpdesk** [comment]
Any news?

**Comment by ezy3** [comment]
Yes, I was waiting to ensure there were no more missing attachments. The issue seems was related to the dynamic attachment scanning feature in M365. It would deliver the email without its attachment and then freescout would grab it before the attachment is added back after the scan. Its set to grab emails every min and thus randomly it would grab ones that haven't completed the dynamic scan. I change the scanning method for the freescout mailboxes and set it to only deliver the email once the attachments have been scanned.  

Thanks again for your assistance, the team is loving the product now, everything is working perfectly!

**Comment by freescout-helpdesk** [comment]
> I change the scanning method for the freescout mailboxes and set it to only deliver the email once the attachments have been scanned.

Can you tell how you've done this? So that others can avoid this issue.

**Comment by ezy3** [comment]
This should only effect anyone who has enabled dynamic delivery policies. 

Navigate to https://security.microsoft.com/
Policies & rules>Threat policies>Safe attachments

<img width="333" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/87155109/6d44e198-7314-4e44-a1a8-33dbee79df65">

I excluded the Freescout mailboxes from the policy

Then created a new policy only for the Freescout mailboxes and set the action to Block instead of Dynamic delivery. 

Thanks again for your help.
