### ISSUE TITLE
[attachments] creating a new email or replying cannot attach files

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#2981]
@freescout-helpdesk 
**Issue**
Not entirely sure when this happend, but could be from the last update.

We are not able to attach files to emails. This has been tested with pdf, jpg.
We have tested with new and a reply to an existing email.

No logs are recorded. 
Screenshot of error when file is selected.

![image](https://user-images.githubusercontent.com/902376/236453443-bdfab0b5-2b2e-43f4-be30-608111be5e1f.png)

Could you please let me know how we can troubleshoot further.
Thanks
Matthew

**Environment**
App Version | 1.8.74
Web Server | nginx/1.21.4
PHP 8.2.5

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
Just to update you, that the latest update does not solve this issue.
I would appreciate if you could perhaps assist here.

As a note
- cleared all logs
- tried to add an attachment
- same error as noted
- nothing in the logs

Can we try get some info somewhere else?
M

**Comment by freescout-helpdesk** [comment]
You need a developer who can investigate it on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)

**Comment by raramuridesign** [comment]
@freescout-helpdesk We found the issue.
Cloudflare has had a recent update to the WAF rule sets.
Freescout was triggering new rulesets so the anonomaly scrores were way to high.

Just mentioning in case anyone also has this issue.
We have a paid account.

**Comment by freescout-helpdesk** [comment]
So how have you solved the issue?

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
We use Zero 1 from Cloudflare, so we have in theory by passed all the WAF rules, so avoid the issue. 
Since we know exactly who logs in.
