### ISSUE TITLE
Initiate SMS Conversation?

### ISSUE THREAD

**Issue by fiveohfive** [freescout-helpdesk/freescout#2983]
I installed the SMS Tickets module and was able to connect it to my Twilio account. The instructions were clear and well written. I can send a SMS to my Twilio number and respond to it from Freescout. I can't figure out how to initiate a conversation using SMS though. Is this possible? 

Thanks, 

Chris

**Comment by fiveohfive** [comment]
Thank you for the response. Would you be able to tell me why it likely won't be implemented? If it's simply not a priority that's fine. This is functionality that I need, so I may look into writing something myself, but if you've already looked into that and there were complications - whether technical limitations, or just in how the app works - it would be very useful to know that now, before I go too far down that road. 

Freescout is a fantastic product. Thank you for all you do!

**Comment by freescout-helpdesk** [comment]
It's not a priority.
