### ISSUE TITLE
no reply plugin

### ISSUE THREAD

**Issue by epp289** [freescout-helpdesk/freescout#2984]
May i ask you please concerning the no reply plugin that prevents the freescout from sending an auto reply once it receives a new email

how can i prevent from sending an auto reply to emails like this one:
2117244232-96zfl187otwzgypq6ol6y72at.19uokrq3ip0s4x1b7h4gsvj8h@mchat.booking.com

(the length of the user left to the domain is not fixed)

in the Custom Noreply Emails section inside the plugin settings i have already put
booking.com and
mchat.booking.com
without any luck

any suggestions?

**Comment by epp289** [comment]
please note that i call the cronjob to update the emails remotely with full url (in case that matters)

* * * * * wget https://www.******.com/emails/system/cron/*******0cf39163c1c6b                                                                                                             146*****1c

**Comment by freescout-helpdesk** [comment]
`*@mchat.booking.com`

**Comment by epp289** [comment]
thank you!
