### ISSUE TITLE
Unable to retrieve email subject content.

### ISSUE THREAD

**Issue by muzilong** [freescout-helpdesk/freescout#2987]
Hello, I really like this project. However, during testing, I found that I couldn't retrieve the subject content of the email, and it displayed "(no subject)". After checking the database, I found that the email subject was not correctly recognized and stored in the database.

```
php artisan freescout:fetch-emails

[2023-05-08 03:10:05] Fetching UNREAD emails for the last 3 days.
[2023-05-08 03:10:05] Mailbox: xxx
[2023-05-08 03:10:09] Folder: INBOX
[2023-05-08 03:10:12] Fetched: 1
[2023-05-08 03:10:12] 1) �Բ���
[2023-05-08 03:10:12] Message from: Customer

```

Below is the original email content:

`Delivered-To: xxx@gmail.com
Received: by 2002:a17:906:d789:b0:965:d252:c98d with SMTP id pj9csp709701ejb;
        Sun, 7 May 2023 19:21:38 -0700 (PDT)
X-Google-Smtp-Source: ACHHUZ7eLyTWsjZcDTprsFqOEtVIZo8YGdrcpdDKUYEXPHC+ZpwXMabx7DOMNwfT5+EiheQlWu3q
X-Received: by 2002:a05:6a21:3291:b0:100:5082:612e with SMTP id yt17-20020a056a21329100b001005082612emr2826055pzb.17.1683512497718;
        Sun, 07 May 2023 19:21:37 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1683512497; cv=none;
        d=google.com; s=arc-20160816;
        b=GErufLlJcFUgWMuBFk6W2er3jlYvKAizVAj2x+8wrwk1WBxoXYLFds4inI9/xzByEe
         mRysTdc5aeA/w3h3q9XDXyI87mn5pnT4jv7qzcPfhnE6jc88UJH5WJ4uGXQlk6jrITMl
         alq9mVFDLAtO3jArDz9cgp6J2BqleCl+JGGwq2cnkpX4opEqyTFaOpTiTiXSki6dKgU0
         xekD+4S80pyCpP/AjzrFOxe+ERRgdByDzW95BxKyHQiIWAroZkSt7MdL3qMdi0tCVn7s
         yMZjn+ZVAvZH/r3RA8Ww/IAYZPMbfZNXQwsgCHeMAM99uADhbhebC+WPB1C4UG0H+a+F
         u2lA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=message-id:date:content-transfer-encoding:mime-version:subject:to
         :from:dkim-signature;
        bh=XXt2Pes7HaxN8DkZcrasEHDyM4V8zf607OE2jE3wWuE=;
        b=m6XJtR5HlAsh4+gel8T/VJN3i+9mMaDI8qqBkNkmn9Buc14nYvlbpoNvt5VMhzVsLk
         mS649HyhdWbDvKPBHOrFjBADro+z+TB1Jre9FlM9AKzS7IML33vT9kOiCuFQCiMC76tC
         Hg3ZauDD1w9PyL8ZXJs5PmawN6QjA20+BAaLu5HwooAAbrCg+2EweabatrFCeF2j98Ej
         XlYcWLuEky994EZ4wPWPCJ7DU9yYG6l3zHkYtaUlLysZgR02gZEnUUTE5YoVHHVdgdiC
         QUvckVnT86mch6TRf50VBidaA9G+aOaB2SM+0sWfEiADRsP4LW7asHrGjpeV4d2uRAJd
         FbXw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@qq.com header.s=s201512 header.b=xSbrpgpZ;
       spf=pass (google.com: domain of xxx@qq.com designates 203.205.221.149 as permitted sender) smtp.mailfrom=xxx@qq.com;
       dmarc=pass (p=QUARANTINE sp=QUARANTINE dis=NONE) header.from=qq.com
Return-Path: <xxx@qq.com>
Received: from out203-205-221-149.mail.qq.com (out203-205-221-149.mail.qq.com. [203.205.221.149])
        by mx.google.com with ESMTPS id j190-20020a6380c7000000b0052c994c1f62si8080305pgd.149.2023.05.07.19.21.37
        for <xxx@gmail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Sun, 07 May 2023 19:21:37 -0700 (PDT)
Received-SPF: pass (google.com: domain of xxx@qq.com designates 203.205.221.149 as permitted sender) client-ip=203.205.221.149;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@qq.com header.s=s201512 header.b=xSbrpgpZ;
       spf=pass (google.com: domain of xxx@qq.com designates 203.205.221.149 as permitted sender) smtp.mailfrom=xxx@qq.com;
       dmarc=pass (p=QUARANTINE sp=QUARANTINE dis=NONE) header.from=qq.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=qq.com; s=s201512; t=1683512495; bh=XXt2Pes7HaxN8DkZcrasEHDyM4V8zf607OE2jE3wWuE=; h=From:To:Subject:Date; b=xSbrpgpZh0W86gzX9MK2A/DBVX+wytx94X3tI2LTZESzBm5SHoT+EZJNdCWbjk8lk
	 hbgbt6PG6haEk3jAre65vsYS/cGmSBV4HplD3lgWwFylAIaBYZ7ZiG+4HyxHO7/UW5
	 WJFmFGLiLZyrfpGEqaHEa2GXeWLveOHZ2UzLhqXw=
X-QQ-FEAT: zaIfg0hwV2qIr1cRyb/3r8rZadhZqn1X
X-QQ-SSF: 00010000000000F0000000000000
X-QQ-XMAILINFO: OfyS+5yLAReg1QhQ6XZ6tUsVitKJc0DhqJYVw4cfdYiIlo7xrOw10xKU1LrZDi
	 0Ov+wBnUm0wxRm8B+k6XY1VuAeU9dvlAJWB1NvbJIJOyEmf/ZTYibcd5IfpGxlW+4s7JZ3ldxDT47
	 Muf8PePGoxBlYtxK3DYKtdMGLfEGGaruGMfjGycgY9CVNnCpyF0HRUlZP+jiGSpfF6/rAL64RS4IN
	 vIS/+pC9Fwk97tlRCNEJzzionfBXgB/PgdnQUQizqsSi+QuCOXp/531ekkZpC9NXPU1JAXNg7ST8H
	 hcFkhmABPRHBd1qyeIVKfJ9iGB+izlJbauUkL5RSOHGtOikn81NOT4e6BWSzhN5LrMKjiY5dX9xGv
	 CX+A7S/wGwdUvB34O4YCBbsJZHwdN6jL7x7foeMK0tjGOPhNzTEvVAaGpk0v10tbb7FISLK1mt9xo
	 wTiPGHrAdvSf34HWcY4rtw1/PdxMafGpK1x9Wpsdle+U+mKSr3koWq1Yc+mwdcGagJQheB+T8Jmqi
	 Hi0Kvsil+eywiikg2QF9+jgcnMqk8Qwl9Wro6tbVmG262FWm5mhsc/RDSYAV0m3E9oqwsRYsNib7B
	 jwCS13qVmeVxzj7tKqS2SLZ0DbWoA+/lqfbEVLo5NtEMYubXNAd8QhgcOTZRP6NajKxHWwYO5vvpB
	 yWvxQYFW5gxLlelUWQWvvt9vyZLtNq5yoVVRiBKfSvInPJYNs6PACxV3w/1GqYljbLwBjCI6krro4
	 WecG1sgSTpHJpdBkjHexM+cMUDc3aB7ccRRn4WtLhoG4gpmmUDrkY3+nyvjgmE6IoUuoOAA/LE7Nm
	 E2cxiWTJzaItQ0Oo+PiF0LhJNVf/l1SwO5MucASyKjJbGnWN4k+DuKfBJy0Iizb/nyGWBrQ/7/p5d
	 Y0wyIO3X80=
X-HAS-ATTACH: no
X-QQ-BUSINESS-ORIGIN: 2
X-Originating-IP: 0.0.0.0
X-QQ-STYLE: 
X-QQ-mid: webmail638t1683512495t163816
From: xxx <xxx@qq.com>
To: xxx <xxx@gmail.com>
Subject: 对不起
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary="----=_NextPart_64585CAF_106CC378_3E7337C7"
Content-Transfer-Encoding: 8Bit
Date: Mon, 8 May 2023 10:21:35 +0800
X-Priority: 3
Message-ID: <tencent_A1258F9878F453294D839052E56E261DA807@qq.com>
X-QQ-MIME: TCMime 1.0 by Tencent
X-Mailer: QQMail 2.x
X-QQ-Mailer: QQMail 2.x

------=_NextPart_64585CAF_106CC378_3E7337C7
Content-Type: text/plain; charset="gb18030"
Content-Transfer-Encoding: base64

------=_NextPart_64585CAF_106CC378_3E7337C7
Content-Type: text/html; charset="gb18030"
Content-Transfer-Encoding: base64

PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJz
ZXQ9R0IxODAzMCI+PGltZyBzcmM9Imh0dHBzOi8vcmVzY2RuLnFxbWFpbC5jb20vemhfQ04vaW1h
Z2VzL21vL0RFRkFVTFQyLzYuZ2lmIj4=
------=_NextPart_64585CAF_106CC378_3E7337C7--`

THANKS

**Comment by freescout-helpdesk** [comment]
What's your FreeScout version?

**Comment by muzilong** [comment]
my version is 1.8.75

**Comment by freescout-helpdesk** [comment]
Could you please send such email to support@freescout.net

**Comment by freescout-helpdesk** [comment]
Copy attached file as `/overrides/webklex/laravel-imap/src/IMAP/Message.php` and clear cache in Manage > System > Tools.

[Message.zip](https://github.com/freescout-helpdesk/freescout/files/11418239/Message.zip)

**Comment by muzilong** [comment]
Perfect !

Thank you very much
