### ISSUE TITLE
Unable to open freescout Mail settings on arm64 install

### ISSUE THREAD

**Issue by djfreakthefirst** [freescout-helpdesk/freescout#2989]
I’m receiving the following error in the logs after getting the “whoops” page when trying to open the email settings page.  Pasting error here.  Has anyone seen or dealt with this?

 strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /www/html/resources/views/settings/emails.blade.php) (View: /www/html/resources/views/settings/emails.blade.php) {"userId":1,"email":"evan@certifiedmactech.com","exception":"[object] (ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /www/html/resources/views/settings/emails.blade.php) (View: /www/html/resources/views/settings/emails.blade.php) at /data/storage/framework/views/afc08c962418014aaf4c6cb9bea7b0d488830cba.php:49, ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /www/html/resources/views/settings/emails.blade.php) at /data/storage/framework/views/afc08c962418014aaf4c6cb9bea7b0d488830cba.php:49, ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated at /data/storage/framework/views/afc08c962418014aaf4c6cb9bea7b0d488830cba.php:49)

**Comment by freescout-helpdesk** [comment]
We need more info. Enable debugging via .env file:
```
APP_ENV=local
APP_DEBUG=true
```
Clear cache in Manage > System > Tools, open Manage > Users page and send us the text of the error message.

**Comment by dennisyakkz** [comment]
![freescout error](https://github.com/freescout-helpdesk/freescout/assets/133010656/0d949bd3-436a-4deb-b0ea-5bcecd10e9c4)

I'm having exactly this issue.
When opening the email settings page the following error is displayed with debugging enabled

**Comment by freescout-helpdesk** [comment]
Are you using Docker or Cloudron?
How many `APP_ENV` parameters do you have in the .env file?

**Comment by freescout-helpdesk** [comment]
It looks like `APP_ENV=local` parameter still does not have an effect.

**Comment by djfreakthefirst** [comment]
I tried changing the domain name in the compose file from my cloudflare tunnel domain to the local ip address:port number and the pages still load the same that way but it didn’t help with the mail settings page.

My email address that you see in the settings and logs is a g suite account and the error says gmail.  Just thinking of anything that might be causing this…

**Comment by djfreakthefirst** [comment]
Not sure why APP_ENV=local isn’t working

![image](https://github.com/freescout-helpdesk/freescout/assets/118140493/c781fadc-7edd-43f4-a7c4-36fac066ae1b)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by djfreakthefirst** [comment]
“ Fixed in the master branch.”

Forgive me, can you please explain?
