### ISSUE TITLE
Security: Loading of external pictures is allowed

### ISSUE THREAD

**Issue by psuet** [freescout-helpdesk/freescout#299]
If someone sends an HTML-E-Mail with externally linked pictures the pictures get loaded without warning etc.

There should be an option to disable remote content globally or per Mailbox.

**Comment by imc67** [comment]
It would be great to have a global option to show/not download images AND while reading te email it would be great to have a 'button' to "show images".

Nowadays it's default functionality in all email clients indeed because of security reasons and preventing unwanted tracking.

**Comment by imc67** [comment]
Almost 2 years after the initial request we still don’t have the possibility to prevent external images to load on opening email. 

As everyone knows this IS THE TRIGGER for spam mails to continue with much more spam and it might contain other security related issues.

I don’t know any client that doesn’t have this feature or actually basic setting.

How many upvotes are needed to make this implemented?

**Comment by freescout-helpdesk** [comment]
Implemented as Block External Images Module: https://freescout.net/module/block-external-images/

**Comment by imc67** [comment]
Wow this is great! I immediately bought 3 licenses!

Thanks for your effort!
