### ISSUE TITLE
How to have modules auto-update or notify admin there's an update available?

### ISSUE THREAD

**Issue by distresscode** [freescout-helpdesk/freescout#2990]
Hello,

I'm not sure if this a bug in my install or not but I don't get any notifications about available updates for my modules. Is it possible to get a notification sent via email or better yet, have the modules auto-update themselves? 

I'm using Freescout on Cloudron. Latest version of everything. Thanks!

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such possibility and no plans to implement it.
