### ISSUE TITLE
Mute button in the individual mailbox views is not persistent

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#2992]
Dear all,

if I as a user go into a mailbox in freescout and click on the function "mute mailbox" in the left bar at the bottom. The mailbox is muted. If I leave the mailbox again and then go into the mailbox again, the mute function is switched off again.

This problem occurs only on the user side. With my admin account i dont have this problem.

What could be the reason for this? Do you have any ideas?

Many thanks in advance,
with best regards
Lukas

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by lucollab** [comment]
Thanks! 💪
