### ISSUE TITLE
nginx: configuration file failed

### ISSUE THREAD

**Issue by Vl3G** [freescout-helpdesk/freescout#2993]
Hey guys, 

I am not an expert and wanted to ask what I am doing wrong. 
I have created a fresh new server Ubuntu 22.04 LTS 64bit and wanted to install freescout. 

wget https://raw.githubusercontent.com/freescout-helpdesk/scripts/master/install/ubuntu.sh

when i run the scrip i always get this error message: 

Configuring nginx...
Nginx configuration error. Terminating installation
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] open() "/usr/share/nginx/scout/storage/logs/web-server.log" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed

and then it aborts. What am I doing wrong or missing?

**Comment by freescout-helpdesk** [comment]
You may need to figure it out yourself or find someone who can do it for you (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)
