### ISSUE TITLE
Feature request form currently unreachable

### ISSUE THREAD

**Issue by OSdrossel** [freescout-helpdesk/freescout#2995]
Feel free to submit a feature request: https://freescout.net/request-feature/

_Originally posted by @freescout-helpdesk in https://github.com/freescout-helpdesk/freescout/issues/2921#issuecomment-1510116472_
            

My team wanted to create/support a feature request for the linked issue, but the feature request site is stuck on "Loading...". When can we expect the site to work again?

**Comment by avenjamin** [comment]
@OSdrossel the site is loading ok for me today - hopefully working for you too.

FYI: The feature request site isn't hosted by FreeScout - it's a 3rd party site www.userreport.com

**Comment by OSdrossel** [comment]
Yep, works again
