### ISSUE TITLE
Time does not show minutes

### ISSUE THREAD

**Issue by torrelasley** [freescout-helpdesk/freescout#2997]
On the website and in emails I have started seeing the Time formatted like this:

03:5pm (instead of 03:53pm)

It is odd because it isn't dropping the leading / trailing zero, it's dropping the second digit entirely.

I have seen this in the following locations:

- Email (in the thread history).
- Viewing a Conversation on the website (hovering over the friendly time if necessary).
- Under /system/status page (the "Date & Time" line).

The time is formatted correctly on the /users/profile page next to the Time Format example.

**Comment by freescout-helpdesk** [comment]
Your FreeScout version?

**Comment by torrelasley** [comment]
Just updated to 1.8.76 and the issue is still present.

**Comment by freescout-helpdesk** [comment]
Could you please attach screenshots. What language are you using?
