### ISSUE TITLE
Error during installation on php artisan key:generate step

### ISSUE THREAD

**Issue by mihha** [freescout-helpdesk/freescout#30]
Hi,

I have followed the official installation guide but during the step where I should generate application key in the .env file, I get the following error

```
php artisan key:generate

In imap.php line 105:

  Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP)
```

I am stuck at this point and can't go any futher

I am using PHP 7.2.9 on my server for this installation

**Comment by freescout-helpdesk** [comment]
Please make sure that you have IMAP extension enabled in your PHP.

To install the extension: 
`sudo apt-get install php7.2-imap`

**Comment by mihha** [comment]
Hi,

thank you for such a fast reply and straight to the point solution.

I apologise for being stupid because I couldn't realise that I am missing IMAP PHP extension

It works now :-)
