### ISSUE TITLE
What are the server requirements for self update to work?

### ISSUE THREAD

**Issue by BrianGilbert** [freescout-helpdesk/freescout#300]
Am using https://github.com/tiredofit/docker-freescout and self update doesn't work inside it.. trying to figure out what server requirements with regard to software may be causing this so that we can get it working.. git.. wget.. curl??

**Comment by freescout-helpdesk** [comment]
If self-updater script hits your hosting's `PHP memory size` limit or `PHP max execution time` you will see something like _"Error occured. Please check your internet connection and try again."_ 

https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-1-update-from-web-interface
