### ISSUE TITLE
How to use FreeScout without cookies

### ISSUE THREAD

**Issue by RienNeVaPlus** [freescout-helpdesk/freescout#3002]
I want to integrate FreeScout into an iFrame of a context, that does not allow cookies or localStorage.
In my case, this is an iFrame of a [Shopify App](https://shopify.dev/docs/apps/auth/oauth/session-tokens), run inside the Shopify Admin.

I figured the user authentication can be done using a query parameter (similar to the "Auto Login" module) and since I have full control of the parent context, doing this won't be an issue.
However, since my environment blocks all cookies, further requests fail and the login does not persist.

What would be a reasonable approach to solve this?
Would FreeScout be willing to accept pull requests for changes neccessary to support such a feature?

**Comment by freescout-helpdesk** [comment]
This can be done via a custom module.

**Comment by RienNeVaPlus** [comment]
I've successfully replaced the login with an URL-based authentication (using a custom module), but further requests still fail with a `419 unknown status` because of the missing cookie header.

- If so, how can a module change the session transport method?
- Or is there a property somewhere to globally attach a query parameter or a header to all requests?
- Besides the "Auto Login" module, is there any other module that does something similar?

I could manually extend all `a[href]` on the page with the values of the cookies, however this would not cover XHR requests.
Am I missing something obvious here? Would you kindly point me in the right direction?

Thanks!

**Comment by avenjamin** [comment]
In case it helps, Freescout is built on the Laravel PHP framework v5.5.40 - [See Laravel Documentation Here](https://laravel.com/docs/5.5/).
There may be some way to do what you're asking but you'll likely have to work it out yourself or find someone who knows Laravel well (I don't yet).

**Comment by RienNeVaPlus** [comment]
I wanted to give a quick update in case anyone is interested:

We're still having difficulty finding a solution for authenticating XHR requests with the "web" middleware without using cookies. Here are the issues we're facing:
- We are unable to simulate the cookie header in modern browsers (the cookie header can't be manually set in modern browsers).
- The native `tokenAuth` implementation doesn't function without the "in_app" cookie.
- Even when we remove the cookie dependency, we haven't been able to overcome the CSRF token validation because the session (from `StartSession`) still relies on the value of the header cookie.

If anyone has any suggestions, they would be greatly appreciated! I am also willing to pay for a solution.

**Comment by freescout-helpdesk** [comment]
It looks like no-one is interested in digging into this. We'll close this for now.
