### ISSUE TITLE
Does "Move or Remove IMAP Message Module" work with POP3?

### ISSUE THREAD

**Issue by hi-hori** [freescout-helpdesk/freescout#3007]
Our Freescout system uses POP3 for mail fetching.
I'm looking for a solution to an issue where a lot of email is accumulating in my email account.

Does "Move or Remove IMAP Message Module" resolve this issue?

**Comment by ilyakonovalenko** [comment]
> Does "Move or Remove IMAP Message Module" resolve this issue?

POP3 and IMAP are different protocols. You need to switch to IMAP in order to use that module.

**Comment by hi-hori** [comment]
Thank you. I would consider changing to the IMAP protocol.
