### ISSUE TITLE
Fetch mails via CLI?

### ISSUE THREAD

**Issue by StefanWirsingStretta** [freescout-helpdesk/freescout#3008]
I have to fetch a lot of old e-mails, which results in server time-outs.

Is it possible to fetch them via CLI?

Thanks.

**Comment by freescout-helpdesk** [comment]
Yes. See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

**Comment by StefanWirsingStretta** [comment]
I don't see how that link describes a way to fetch old e-mails via CLI?

**Comment by StefanWirsingStretta** [comment]
And how can I specify the date of the emails that should be fetched? Is there also a way to fetch e-mails for a specific mailbox only?

Thanks.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Console-Commands#fetch-emails

There is no way to specify the mailbox.
