### ISSUE TITLE
Bulk move of conversations between mailboxes

### ISSUE THREAD

**Issue by potvinp** [freescout-helpdesk/freescout#3011]
Hey there,

Was looking to migrate multiple conversations at once from one mailbox to another and noticed it is only possible on a per-conversation basis from what I was able to find. Is there any possibility currently or in the works to bulk move conversations between mailboxes instead of individually? If not, I can definitely make a feature request for this.

Thanks in advance!

PHP version: 8.1.18
FreeScout version: 1.8.77

**Comment by ilyakonovalenko** [comment]
You can probably use API module and write some script. API allows to move conversation between mailboxes.

**Comment by StefanWirsingStretta** [comment]
I added my own function to do this in freescout.

@freescout-helpdesk Let me know if you're interested in reviewing my code and adding it to your codebase.

**Comment by freescout-helpdesk** [comment]
@StefanWirsingStretta Yes, feel free to submit a feature request - we'll take a look.

**Comment by linozen** [comment]
The easiest way to achieve this is with a manual workflow. Simple to set up and easy to adapt.

**Comment by moofresh** [comment]
This would be handy for the Snooze module as well (to be able to snooze multiple messages at once).
