### ISSUE TITLE
Telegram Notifications module double escaped mailto hrefs

### ISSUE THREAD

**Issue by stasich7** [freescout-helpdesk/freescout#3012]
I've faced up Telegram notification message format issue concerning Customer Email: it is not formatted as a href link , it contains HTML markup instead, as follows:

```
Subject
Message

Customer
Mark <a href="mailto:mark1@example.org">mark1@example.org</a>
```

The issue has come with 1.0.8 -> 1.0.11 "Telegram Notifications" module update.

PHP version: PHP 7.3.31-1~deb10u2
FreeScout version: 1.8.31

**Comment by freescout-helpdesk** [comment]
Fixed in Telegram Notifications Module v1.0.12
