### ISSUE TITLE
Office 365 and local HTTPS (run in docker)

### ISSUE THREAD

**Issue by SteffenBernd** [freescout-helpdesk/freescout#3013]
Hey,
we use the Freescout docker and would like to use office 365 as mailbox. sadly freescout has to run with HTTPS.
We have not managed to achive that after several days.
We do not want to expose freescout to the internet.
Is there anyone willing to help us with this?
Greetings
Steffen

**Comment by RienNeVaPlus** [comment]
You need to create a reverse proxy. You can modify the nginx config or use a GUI like the [nginx proxy manager](https://nginxproxymanager.com/).
Someone made a [video](https://youtu.be/vw9boxStxyc?t=1105) on how to do it.

**Comment by SteffenBernd** [comment]
> You need to create a reverse proxy. You can modify the nginx config or use a GUI like the [nginx proxy manager](https://nginxproxymanager.com/). Someone made a [video](https://youtu.be/vw9boxStxyc?t=1105) on how to do it.

Hey,
this does not help. I have a Reverse Proxy NPM and i cant set it to HTTPS. ( I cant use LE to get a SSL Certficicate because i dont want to expose Freescout to the internet)
I cant use "Use a DNS Challange" because our DNS provider is not listed there.
So any other suggestions?

**Comment by freescout-helpdesk** [comment]
The only thing we can suggest is to expose your FreeScout instance to the Internet, connect you mailbox to MS365 and make FreeScout non-available from the Internet by changing APP_URL in .env file.
