### ISSUE TITLE
Fetching emails broken after update

### ISSUE THREAD

**Issue by bazizsafi** [freescout-helpdesk/freescout#3014]
PHP version: PHP 8.0.28 (cgi-fcgi) (built: Apr 18 2023 07:25:30)
FreeScout version: 1.8.77

Hi there,

Our email provider deactivated IMAP access using TLS v1.0 and v1.1. So I changed the Mailbox IMAP connection settings to Port 993 and Encryption SSL, saved the configuration and checked it, which resulted in a successful "Connection established."
While I was at it, I updated FreeScout via the Web Updater to version 1.8.76 and also updated all modules to their latest versions.

After that, email fetching did not work anymore.

The System Status showed all green: the queue was running, the cron jobs were successfully executed, and there were no errors in the App Logs. However, the `fetch-emails.log` only contained the word "Terminated".

I then updated to the latest version 1.8.77 and also added `APP_NEW_FETCHING_LIBRARY=true` to our `.env` configuration file but that did not change anything.

Manual email fetching worked flawlessly, though, so I executed the `fetch-emails` command directly in the SSH terminal and logged the output:
```
<path>$ '/usr/bin/php8.0' 'artisan' freescout:fetch-emails --identifier=<identifier> > 'path/to/freescout/storage/logs/fetch-emails.log' 2>&1
Terminated
<path>$
```
On a hunch I removed the `--identifier=<identifier>` part from the command and – surprise! – all emails where fetched successfully:
```
<path>$ '/usr/bin/php8.0' 'artisan' freescout:fetch-emails > 'path/to/freescout/storage/logs/fetch-emails.log' 2>&1
<path>$
```
The logfile showed:
```
[2023-05-15 17:15:14] Fetching UNREAD emails for the last 3 days.
[2023-05-15 17:15:14] Mailbox: <Mailbox Name>
[2023-05-15 17:15:14] Folder: INBOX
[2023-05-15 17:15:14] Fetched: 0
[2023-05-15 17:15:14] Fetching finished
Content-type: text/html; charset=UTF-8

```
I also noticed that using any other value for `--identifier` except for the actual one successfully fetched the emails.

I saw in the source code of FreeScout ([Kernel.php](https://github.com/freescout-helpdesk/freescout/blob/2fe0f518be3bf29a3677257b19fa482ea7d17d8c/app/Console/Kernel.php#L100) / [Helper.php](https://github.com/freescout-helpdesk/freescout/blob/2fe0f518be3bf29a3677257b19fa482ea7d17d8c/app/Misc/Helper.php#L1375)) how that identifier is derived, but could not see any problem with it regarding my configuration. The `.env > APP_KEY` in our productive configuration was (still) present.

Do you have any pointers for me?

**Comment by freescout-helpdesk** [comment]
Maybe something went wrong during the last update. All we can suggest is to re-update your FreeScout using manual updating: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually
