### ISSUE TITLE
ZenDesk importer

### ISSUE THREAD

**Issue by gdandersson** [freescout-helpdesk/freescout#3016]
Since Zendesk supports exporting of tickets via JSON/XML or CSV, an importer into FreeScout would make moving much simpler.

Any plans on implementing such a module?

https://support.zendesk.com/hc/en-us/articles/4408886165402-Exporting-data-to-a-JSON-CSV-or-XML-file

(using help-desk-migration might be a solution, but a company that can't even tell you their price.. I'm wary of)

**Comment by freescout-helpdesk** [comment]
Feel free to add a feature request: https://freescout.net/request-feature/
Maybe someone will implement it as a module.
