### ISSUE TITLE
[help/feature] auto follow-up

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#3017]
When you are sending out emails, a super important part of this is doing follow ups. I have found that more people respond to my THIRD email than my FIRST email.

If possible, we want to automate this process like so:

1. Compose a draft in FS
2. Send that email
3. In the same conversation, draft a new thread, instead of clicking SEND click another button SCHEDULE...
4. In the SCHEDULE... popup, you can choose the time to send and also there is an option "Only send if there is no customer reply" which is default off.

I can even use to draft the follow up and also draft a second follow up.

This means I can send one email, set up all the things right now when I am thinking about it, and then the computer will do everything else for me.

---

Hopefully this is possible as a module. So I wanted to ask here for some advice on what hooks I can use. I have a little experience writing (really simple) FS modules and might be able to get started on this.

**Comment by freescout-helpdesk** [comment]
Maybe someone from community will implement it as a module. Or you can find someone: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
