### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Captain-Sisko** [freescout-helpdesk/freescout#3018]
What's up with the "Test Fuck Feld" under priority in the demo?

**Comment by avenjamin** [comment]
@Captain-Sisko given it's a demo I suspect someone's being immature and entered that in. As it says on the demo homepage _"All data resets every day at 00:00 GMT"_ so it should be gone soon.

**Comment by freescout-helpdesk** [comment]
@avenjamin Thanks for helping out.
