### ISSUE TITLE
Change Ticket Numbering Convention

### ISSUE THREAD

**Issue by jjs-josh** [freescout-helpdesk/freescout#3019]
Our orgs previous helpdesk used a unique naming convention that followed the structure of having a set of alphabetical characters (identifier) which would remain static for all created tickets, followed by an ascending number depending on when the ticket was created.
for example, the 1st created ticket would be ABC1 and the 15th ticket created would be ABC15.

Does this function exist within freescout?

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. It can be implemented via a custom module. Feel free to submit a feature request: https://freescout.net/request-feature/
