### ISSUE TITLE
New conversation from FreeScout via SMS or WhatsApp

### ISSUE THREAD

**Issue by moijar** [freescout-helpdesk/freescout#3021]
Hi,

I would like ask that is it possible to start new conversation from FreeScout via SMS or WhatsApp in some how? At the moment it look that new can be started only via email.

If that is not possible, would it be possible develop thi sfeature?

With Best Regrards
Jari

PHP version: PHP 8.1.2-1ubuntu2.11
FreeScout version: 1.8.77

**Comment by ilyakonovalenko** [comment]
There are modules for such things. Please take a look at https://freescout.net/module/sms-tickets/ and https://freescout.net/module/whatsapp/

**Comment by freescout-helpdesk** [comment]
> is it possible to start new conversation from FreeScout via SMS or WhatsApp

Unfortunately it's not possible and probably will not be implemented.
