### ISSUE TITLE
webpage loss of formating 

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#3022]
Several times, I have found that I have lost all the formation, and Free Scout is just not usable for some time. I have caching switched off on the server and have cleared my browser cookies and site data, and any local cache, but it is still not fixed.

I try different browsers on the same computer but with the same result.

I have attached an image of what I get when I have the issue, and I would be very grateful if anyone could suggest how to fix the problem.

John. 

freescount version 1.8.77
PHP 8.0.28

![Screenshot 2023-05-17 145413](https://github.com/freescout-helpdesk/freescout/assets/27293201/fa72fcb8-9edd-46eb-a578-9e1f0cece757)

**Comment by freescout-helpdesk** [comment]
We can't help here. When this happens you need to open browser console and check Network tab to see what's happening to the CSS files.

**Comment by fmaytain** [comment]
I think I have something similar.
I got a mixed content error in the Console.

<img width="555" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/35375176/51ab5107-f494-4ee3-831c-9610f994f1d4">

FreeScout version 1.8.77
PHP 8.0.27

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working

**Comment by fmaytain** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working

For me editing the .env file worked.
Thank you !
