### ISSUE TITLE
Support for SameSite=None Cookie Attribute

### ISSUE THREAD

**Issue by RienNeVaPlus** [freescout-helpdesk/freescout#3023]
> Google Chrome treats cookies that have no declared SameSite value as SameSite=Lax cookies. **Only cookies with the SameSite=None; Secure setting will be available for external access**. <sup>[Source](https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure?hl=en)</sup>

The SameSite attribute is controlled by Symfony. However, the version of Symfony utilized by FreeScout does not support the value `none`. Nevertheless, more recent versions of Symfony do permit it, as you can see [here](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpFoundation/Cookie.php#L21).

Is there a possibility of updating Symfony or incorporating the value as an override?

**Comment by freescout-helpdesk** [comment]
What for do you need `none`?

**Comment by RienNeVaPlus** [comment]
To integrate FreeScout into an iFrame where third-party cookies are allowed, it is necessary to ensure that the SameSite value of the cookies is set to "none." Starting from 2020, Google Chrome [blocks cookies](https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure?hl=en) that have a different SameSite value.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

Set `same_site` to `none` in /config/session.php

**Comment by RienNeVaPlus** [comment]
Thank you.

If anyone comes across this in the future, here's a way to modify the session configuration dynamically using a module:
```php
// ModuleServiceProvider.php::hooks()

if($enable) {
  config(['session.same_site' => 'none']);
}
```
