### ISSUE TITLE
HTML content sent as plain text email

### ISSUE THREAD

**Issue by ProfDavidMora** [freescout-helpdesk/freescout#3024]
Hello.
This is a fresh install and I am a new user of FreeScout testing for a quite small setup. E-mail fetching is working fine and tickets are registered. When I write a response to these tickets through the UI, they are sent as expected, with history included as configured, to the user who opened it, but although the body is clearly HTML, all email clients (tested with Outlook on Web, Outlook for Desktop and Thunderbird) show the context as plain text, including all markup.

![Capture](https://github.com/freescout-helpdesk/freescout/assets/40967390/9a653718-18b6-4dbf-9ee6-8c15b87d0d5f)

How can I either (1) make sent messages display as HTML in the remote clients (something I have not enabled maybe) or (2) prepare the e-mail body as plain text so that it matches the headers?

I installed from zip on a cPanel host that is owned and operated by me, so I have full root access to anything and everything, meaning something might not be enabled that "commonly" would, and stuff like that, but Joomla and other types of webapp have installed without too much hassle.

**Comment by freescout-helpdesk** [comment]
Most likely the problem is in the mail server you are using to send emails. What mail server are you using?

**Comment by ProfDavidMora** [comment]
I have it currently set up to use PHP's mail function. SMTP would be through Exim on WHM. Would that be better?

**Comment by freescout-helpdesk** [comment]
Apparently your PHP's mail function does not work as expected. Try some other sending method.
