### ISSUE TITLE
Snooze module bug

### ISSUE THREAD

**Issue by adrianmxh** [freescout-helpdesk/freescout#3026]
Hi there,

Just noticed that the Snooze module doesn't unsnooze the tickets when they reach the day to be unsnoozed.

For example we have a ticket which was snoozed until 12 May and now it's 18 and it is still snoozed saying "Snoozed until: May 12, 2023 00:00".
Isn't the plugin supposed to unsnooze the ticket once it reaches the date?

Screenshot:
https://prnt.sc/65UWEe5VHQ2W

**Comment by freescout-helpdesk** [comment]
Something must be broken on your installation.  Check https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
