### ISSUE TITLE
Add current date to custom field

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#3029]
Hello. I have a question about the work of the Custom Fields module. 

I want to create a field that will record the date the ticket was created. I am creating a custom field with Date data type. Then, using the automation module, I want to set the current date. To do this, in the created custom field, I write the value "today". In this case, instead of the word "today" in the body of the ticket, a numerical value is written (for example, "2023-05-18"), as I need.
At the same time, if I enable the "Show In Conv. List" setting for the custom field, then the word "today" will be displayed in the tickets list, and the tickets filter also does not find the order by its numerical value.

Is it possible to use the Custom Fields and Workflows modules to record the date the ticket was created?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature. You may need to do it via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
