### ISSUE TITLE
Bug in chat module - exposed when editing ticket cc or bcc fields - gives an ajax error.

### ISSUE THREAD

**Issue by boerichsen** [freescout-helpdesk/freescout#3030]
PHP version: PHP 8.1.2-1ubuntu2.11
FreeScout version: 1.8.77 

Chat module: Version: 1.0.24 

I can't add cc or bcc to tickets when chat module is active. Also send is not available. Response is internet is not available. The cause is an error in the ajax response of the message windows ajax call. Uncaught TypeError: strlen(): Argument #1 ($str) must be of type string, referring to the js script in Modules/chat/public/js/.xxxxx.mo

**Comment by freescout-helpdesk** [comment]
Try to find the full error message in Manage > Logs > App Logs.

**Comment by boerichsen** [comment]
Apparently there was No error in the app logs. Den 19. maj 2023 kl. 07.52 skrev FreeScout ***@***.***>:﻿
Try to find the full error message in Manage > Logs > App Logs.

**Comment by freescout-helpdesk** [comment]
Can you attach some screenshots.

**Comment by boerichsen** [comment]
I found out it was a bug caused by malware not related to freescout :-)
