### ISSUE TITLE
Conversation HTML custom URI scheme being stripped

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#3031]
I have a conversation with an HTML email with a link that uses a custom URL scheme `fmp` (used by Claris FileMaker).
Annoyingly the `href` is being removed from the `<a>` tag when viewing the conversation in the browser which means I can't click on it.

I've dug as best I can and can't work out how to allow a custom scheme.
I see the `config/purifier.php` file has options for specifying different schemes, but even after editing and clearing the Freescout cache and manually clearing the files in `storage/app/purifier` I can't get it to work.

Starting from [the blade](https://github.com/freescout-helpdesk/freescout/blob/84314598d25ec1b5fc875112ee166f2a81c1234e/resources/views/conversations/partials/thread.blade.php#L275), the relevant chain of commands in `Thread.php` I've found is:

1) `function getBodyWithFormatedLinks(string null = '')` on [line 327](https://github.com/freescout-helpdesk/freescout/blob/84314598d25ec1b5fc875112ee166f2a81c1234e/app/Thread.php#L327)
2) `$body = \Helper::linkify($this->getCleanBody($body));` on [line 333](https://github.com/freescout-helpdesk/freescout/blob/84314598d25ec1b5fc875112ee166f2a81c1234e/app/Thread.php#L333)
3) `function getCleanBody($body = '')` on [line 299](https://github.com/freescout-helpdesk/freescout/blob/84314598d25ec1b5fc875112ee166f2a81c1234e/app/Thread.php#L299)
4) `return \Helper::purifyHtml($body);` on [line 316](https://github.com/freescout-helpdesk/freescout/blob/84314598d25ec1b5fc875112ee166f2a81c1234e/app/Thread.php#L316)

The `purifyHTML` function in `Helper.php` is then calling `$html = \Purifier::clean($html);`

From there I start to get a bit lost, but it does look like it's meant to be using the config from `config/purifier.php` but i'm not 100% sure.

Any clues?

Thanks

PHP version: 8.0.28
FreeScout version: 1.8.77

**Comment by avenjamin** [comment]
Also can we make `php artisan purify:clear` work some how as per the https://github.com/stevebauman/purify#cache documentation?

**Comment by freescout-helpdesk** [comment]
Unfortunately HTML Purifier library does not allow to allow `fmp` protocol and it's being stripped out.

https://github.com/freescout-helpdesk/freescout/blob/dist/config/purifier.php#L32
http://htmlpurifier.org/live/configdoc/plain.html#URI.AllowedSchemes

**Comment by avenjamin** [comment]
It looks like those are the defaults and can be modified - I just don't know why the modifications aren't being picked up.
I'll keep digging. 
Thanks
