### ISSUE TITLE
Webhook not passing custom customer details

### ISSUE THREAD

**Issue by tombrutoncoolmilk** [freescout-helpdesk/freescout#3032]
the webhook is not passing thought the data of custom customer fields

**Comment by freescout-helpdesk** [comment]
Full customer data can be retrieved via https://api-docs.freescout.net/#get-customer

**Comment by tombrutoncoolmilk** [comment]
Is it possible for this to be added to the web hook as it would simplify the process

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
