### ISSUE TITLE
Print version of ticket shows full link to attachment

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#3035]
Hello all,

when I use the print function in a ticket in FreeScout, the attachments are displayed to me in the browser print view as well as in the ticket system itself as a "blue file name" with extension.

If I then save the print view as a PDF file on my computer, I get the full link to the attachment displayed in the PDF file. Unfortunately, this makes the attachments a bit confusing and apparently automatically breaks the URLs by hyphen in the margin, so the links can only be clicked but not copied). 

Is it possible to display the link first in a new line (and with a space between it and the file name or even print it without the full link to file: https://stackoverflow.com/questions/3476393/print-a-website-without-printing-the-link-locations)? 

In addition, the full delete link is shown, which could be abused by unauthorised users.

`file_20230417_130602.pdf (https://subdomain.domain.de/storage/attachment/4/9/1/file_20230417_130602.pdf? id=161&token=156e173c11dsf34f3fdfasf34f8e48afc73)
(149 KB)

 (https://subdomain.domain.de/storage/attachment/4/9/1/file_20230417_130602.pdf? id=161&token=156e173c11dsf34f3fdfasf34f8e48afc73)`

Thanks for your help in advance!

Kind regards
Lukas

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
