### ISSUE TITLE
Japanese text got garbled

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3039]
PHP version: 8.0.20
FreeScout version: 1.8.77

Hello.I'm testing Freescout.
and I found some mail text is garbled. mail title is OK,only mail body text.
it seemed these mails sent by not well configured mail server. mostly spam but some mail from our customer got grabled.
Is there anything I could for this ?

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP authentication or regular IMAP?

**Comment by totake0224** [comment]
I'm sorry. I don't know how to identify it. but I'm sure we are not using microsoft service.

**Comment by totake0224** [comment]
Thank you, I will try it and report the result.

**Comment by totake0224** [comment]
I added that setting in my .env file. and clear cache using 'php artisan freescout:after-app-update'
after that it seemed Freescout dosen't fetch new coming mail at all.
but there is no error log.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache

**Comment by totake0224** [comment]
Thank you.
I did it from admin menu.and the result is not good.
freescout could fetch new mail using new library but it lost some mail's body text.
Using new fetching library make mail body text lost instead of decoding it garbled.

**Comment by freescout-helpdesk** [comment]
Could you please send a sample email to support@freescout.net

**Comment by totake0224** [comment]
I'm sorry, I don't know how to send garbled email.
because it's sender is not me. I could only do getting garbled mail from Freescout DB. or same mail received by thunderbird.or forward it from freescout system.
Is it useful for your purpose?

**Comment by totake0224** [comment]
I forward two mails to support@freescout.net
1,received by thunderbird, not garbled.
2,received by freescout, garbled

**Comment by freescout-helpdesk** [comment]
Can you download the problematic email as .EML from your mail server and send to us.

**Comment by totake0224** [comment]
Thank you.
I sent .EML file to support@freescout.net

**Comment by freescout-helpdesk** [comment]
Can you send us message's Body from FreeScout - click Show Original in the message's dropdown menu and go to Body tab.

**Comment by freescout-helpdesk** [comment]
We've got the Body. But it looks like we can't check and solve the issue if needed without a real email sent to support@freescout.net

**Comment by totake0224** [comment]
Hello,
I know several mail magazine got garbled. May I register  "support@freescout.net" to one of those mail magazine?
I will unregister it after you check real mail.

**Comment by freescout-helpdesk** [comment]
Ok

**Comment by freescout-helpdesk** [comment]
Fetched successfully. Apparently something does not work well on your FreeScout instance. Are you using Docker?

![2023-05-30_17-23-09](https://github.com/freescout-helpdesk/freescout/assets/40499291/382d5ffc-0f09-4c87-8d4b-0da16b3450f3)

**Comment by totake0224** [comment]
I'm using Docker.
I will check my environment and will report result.
Thank you. and sorry for getting involved.

**Comment by totake0224** [comment]
I have confirmed my mail box is not garbled. after I installed Freescout at latest image of tiredofit/freescout
I think updating freescout by command prompt of docker was a problem.
APP_NEW_FETCHING_LIBRARY=true
work correct. but I will confirm my mail box more days.
Thank you.

**Comment by freescout-helpdesk** [comment]
FYI. We've received an email from www.exwork.co.jp which is garbled. It's displayed properly in our mail service but when we download it from there as .EML file it's garbled. So it look like the problem here can be in the mail service - probably it sends already garbled email to FreeScout.

**Comment by totake0224** [comment]
Hello.
What does "probably it sends already garbled email to FreeScout." mean?
because it's displayed properly in your mail service.
and my Thunderbird shows same mail properly too. 
I'm confused.

**Comment by freescout-helpdesk** [comment]
We've made some adjustments in the `master` branch. Now with `APP_NEW_FETCHING_LIBRARY=true` option enabled the subject and body is decoded properly.


![2023-05-31_12-04-21](https://github.com/freescout-helpdesk/freescout/assets/40499291/33127558-eaed-4471-9135-0e4c70f078bf)

**Comment by freescout-helpdesk** [comment]
Could you please unsubscribe FreeScout support email from justsystems.com. They are still sending emails.

**Comment by totake0224** [comment]
I had done it already, and I reconfirmed it now. but status is already unregistered.
I will tell them what happened. sorry.
