### ISSUE TITLE
Fastspring charges more on mobile

### ISSUE THREAD

**Issue by Magneticdud** [freescout-helpdesk/freescout#3043]
Not a bug of the product itself, but of the payment processor. Maybe asshole design?

I don't understand why on mobile i have to pay more than on desktop

![image](https://github.com/freescout-helpdesk/freescout/assets/2940598/6ae99c4c-1d80-4411-b89b-d9b1fa6341b5)

Also 7 usd + 22% tax is 7,93 euro, not 8,99 euro

There's a way to pay for modules bypassing fastspring?

**Comment by Magneticdud** [comment]
Also: played around with a VPN. Why Germany pay 6.71 euro + tax, while italy pays 7.37 euro + tax? The extra charge is stolen by fastspring or goes to the developers?

**Comment by freescout-helpdesk** [comment]
Here are some links:
https://fastspring.com/tax-management/
https://fastspring.com/docs/about-vat-and-sales-tax/

Keep in mind that GitHub is the place for discussing development related things.
