### ISSUE TITLE
Telegram API Errors

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3044]
23 errors this month with the following event description:

API error: Bad Request: can't parse entities: Unsupported start tag `"email address"` at byte offset ###

Telegram module 1.0.12
FreeScout Docker: php8.2 https://hub.docker.com/layers/tiredofit/freescout/latest_php8.2/images/sha256-8b113cab889e0d0dfc6d80833d03b0964e2498e82ea5b0b3f79df62a349a0746?context=explore

**Comment by freescout-helpdesk** [comment]
Can you check where do you have this phrase - "email address"? Is some ticket subject or body?

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. This issue could be faced before Telegram Module v1.0.12. Try to delete and re-install the module.

**Comment by freescout-helpdesk** [comment]
> API error: Bad Request: can't parse entities: Unsupported start tag "email address" at byte offset ###

This error belonged to Telegram Notifications Module.
