### ISSUE TITLE
Printing Formatting Issues

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3045]
When printing, each Pin to Top icon displays strangely.  See the attached image.

![Image 1912](https://github.com/freescout-helpdesk/freescout/assets/96336813/f8f132c6-d819-4aa6-8a9b-3917dc284e63)

Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit)

FreeScout Docker: php8.2 https://hub.docker.com/layers/tiredofit/freescout/latest_php8.2/images/sha256-8b113cab889e0d0dfc6d80833d03b0964e2498e82ea5b0b3f79df62a349a0746?context=explore

**Comment by freescout-helpdesk** [comment]
What and how are you printing? Write a step-by-step instruction.
