### ISSUE TITLE
Email Printing Issues

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3046]
The email displays normally:

![Image 1914](https://github.com/freescout-helpdesk/freescout/assets/96336813/29a8a172-7b02-4cc9-9881-c8b4744e5b08)

Choosing the Print view causes the left edge of the text to be cut off.

![Image 1915](https://github.com/freescout-helpdesk/freescout/assets/96336813/ba8bd4d1-69a0-46d2-947d-1850aa78ec68)

Trying to print this page results in the left and left edges of the text being cut off.  There is a horizontal scroll bar; the text does not wrap.

![Image 1916](https://github.com/freescout-helpdesk/freescout/assets/96336813/5a81220a-4105-4aa5-bb8b-5c7ac048c30c)

Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit)

FreeScout Docker: php8.2 https://hub.docker.com/layers/tiredofit/freescout/latest_php8.2/images/sha256-8b113cab889e0d0dfc6d80833d03b0964e2498e82ea5b0b3f79df62a349a0746?context=explore

**Comment by freescout-helpdesk** [comment]
The problem is apparently in the email layout. Try to figure it out yourself or find a developer who can investigate it on your FreeScout instance (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).
