### ISSUE TITLE
Embed Image Module not working

### ISSUE THREAD

**Issue by zpfvo** [freescout-helpdesk/freescout#3047]
PHP version: 8.2.5
FreeScout version: 1.8.74
(running in docker)

When inserting an image with the Embed Image Module enabled, there is still only the link to the file inserted.
Looking at the source code of the outgoing email:
`<img src="http://<domain>/storage/attachment/1/3/1/<image>.png?id=7412&amp;token=dd879ee5bd6a9311d0e4275c1f405a17" style="width: 25%;" width="1280" alt="<image>.png">`

Is there any way I can debug this? The FreeScout instance is not public, so the links don't work.

**Comment by freescout-helpdesk** [comment]
![2023-05-24_13-16-20](https://github.com/freescout-helpdesk/freescout/assets/40499291/d795c3e9-0ed4-46bb-8a47-3baf88bc82b4)

**Comment by freescout-helpdesk** [comment]
If still does not work make sure the module is activated.

**Comment by zpfvo** [comment]
The first email was in the Sent-Folder of the Mail-Server (so was checking outside FreeScout), so I assume it left to the customer that way.
I deactivated and reactivated the Module and sent a Mail to myself and now the image is nicely embedded.

Thank you
