### ISSUE TITLE
OpenOffice attachments not being recorded in database due to bug in handling mime type

### ISSUE THREAD

**Issue by radiowavesurfer** [freescout-helpdesk/freescout#3048]
PHP version: 7.4 (via Ubuntu 20.04)
FreeScout version: 1.8.77

Hi. Periodically we get an email from a customer with an OpenOffice spreadsheet attached. The email is received into Freescout ok, but the attachment isn't, and in the Fetch Errors log, we get an entry like this:

`Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(127) (SQL: insert into "attachments" ("thread_id", "user_id", "file_name", "mime_type", "type", "embedded") values (422307, , 50460.xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheetapplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet, 3, 0) returning "id"); File: /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php (664)`

From the SQL insert statement in the above error, we can see that the mime_type value that the code is attempting to store in the database is:
`application/vnd.openxmlformats-officedocument.spreadsheetml.sheetapplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

The mime header from the raw message looks like this:
```
--934c35e111c54d1ab77182f018043f26
Content-Type: application/xlsx; name="50460.xlsx"
Content-Transfer-Encoding: base64
```

It seems that the mime type from the insert statement comes from the php function, mime_content_type(), and which contains a bug such that instead of answering:
`application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

... it will instead answer:
`application/vnd.openxmlformats-officedocument.spreadsheetml.sheetapplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

I.e., the mime type is given twice, and is therfore too long for the database field.

Details of the bug, open for 4 years, here: 
https://bugs.php.net/bug.php?id=77784

Commentors on that bug report also give an example of the corresponding output for a word processor document:
`application/vnd.openxmlformats-officedocument.wordprocessingml.documentapplication/vnd.openxmlformats-officedocument.wordprocessingml.document`

Given that we could be living with this bug for quite a few more years yet, I think it would be appropriate for Freescout to implement a workaround. 

My suggestion is that if the output of mime_content_type() includes the substring `"application/vnd.openxmlformats"` *after* position 0, then the string should be truncated at that position.

Something like this:
```
$mime = mime_content_type(....);

$duplicate = strpos($mime, "application/vnd.openxmlformats", 1);

if ($duplicate) {
    $mime = substr($mime, $duplicate);
}
```

Thanks.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by radiowavesurfer** [comment]
Thanks. I've just tested the new version of Attachment.php on our installation, and the spreadsheet attachments which were previously causing problems are now working fine.
