### ISSUE TITLE
Ticket re opens after getting responses

### ISSUE THREAD

**Issue by mapiixd** [freescout-helpdesk/freescout#3049]
Hi, i have this issue, when i close a ticket and then the other user answer it with 'Thanks' for example, it opens again, it's there any way to get the already closed tickets not to open again on new response? It's important to me, because i track the avg time i use to resolve an issue

PHP version: 8.1.2
FreeScout version:  FreeScout 1.8.77

**Comment by mapiixd** [comment]
> No, it is not possible by default. You can write custom module which will handle such tickets.

Do you have any example for that ?

**Comment by ilyakonovalenko** [comment]
> Do you have any example for that ?

I don't. There are a few open source modules which you can use, or maybe it is better to hire a developer.
You can also submit feature request to have your idea implemented as an option.

**Comment by freescout-helpdesk** [comment]
@ilyakonovalenko Thanks for helping out.
