### ISSUE TITLE
Allow recipient name in the To field

### ISSUE THREAD

**Issue by iPublicis** [freescout-helpdesk/freescout#305]
Version 1.3.1

Didn't check with later versions.

If you add the recipient (or Cc or Bcc) like `Pedro Manos <pmanos@gmail.com>` it will be converted to `pemanmaospmanos@gmail.com` and editing the "Customer" won't solve it.

**Comment by freescout-helpdesk** [comment]
Can not reproduce the issue in 1.3.4. Are you replying or creating a new conversation? Can you attach a screenshot?

**Comment by iPublicis** [comment]
Still happening in 1.3.5.

Image of the error at https://imgur.com/a/PABRiEF

Email address should be `Marta Gaspar <martagaspar@domain.tld>` and it was converted on sending by the program into `martagasparmartagaspar@domain.tld`

**Comment by freescout-helpdesk** [comment]
Thanks. Currently only email addresses (martagaspar@domain.tld) are supported in the To field, without a name.

**Comment by iPublicis** [comment]
Hi. Thanks for the reply.

But this is a little disrupting since people expect that it works like any regular email client. And the normal way to use the recipient address is in the format `Name Surname <email@domain.tld>`.

Any ETA on solving this? Is it too complex?

**Comment by iPublicis** [comment]
Can relabel it to `enhancement` please. I think it makes more sense. And thanks again.

**Comment by freescout-helpdesk** [comment]
Maybe month or two. Weanwhile [pull requests](https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow) are welcome.

**Comment by foliovision** [comment]
This is not such a big deal, on the other hand not being able to auto-BCC into our CRM system is a real nuisance.

**Comment by freescout-helpdesk** [comment]
> This is not such a big deal, on the other hand not being able to auto-BCC into our CRM system is a real nuisance.

Here is the issue you are looking for: https://github.com/freescout-helpdesk/freescout/issues/59

**Comment by iPublicis** [comment]
> 
> 
> Maybe month or two. Weanwhile [pull requests](https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow) are welcome.

Can you pint me to the part of the code where you deal with email addresses?
