### ISSUE TITLE
Reverse proxy: wrong redirect after the login

### ISSUE THREAD

**Issue by borgogelli** [freescout-helpdesk/freescout#3053]
Hi everybody
I have installed the 1.8.77 version with the Apache web server
Then I have deployed it behind a Caddy reverse proxy which add the https support to the service.
So I have edited the .env config file this:
```
# Application URL
APP_URL=https://help.domain.it
# Use HTTP protocol and redirect to HTTPS
APP_FORCE_HTTPS=true
```
Everything works fine except the login.
In detail, after a **successfully** login my Freescout instance redirect me to **http**://help.domain.it instead to **https**://help.domain.it 
So only if I click twice the login button, I can continue and finally access to the user interface.

Some considerations:
 * the address help.domain.it points to the proxy server
 * Freescout server can't resolve any host name
 
 Caddy file:
 
```
help.domain.it {
        tls /etc/ssl/server.crt /etc/ssl/server.key
        reverse_proxy * 192.168.0.120
}
```

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by freescout-helpdesk** [comment]
"I disconnected the user" - do you mean you've logged out.

Are you sure you are using new code from `master` branch?

Write a step-by-step instruction on how to reproduce the issue.

**Comment by freescout-helpdesk** [comment]
If pulling updates from `master` branch make sure to run the following commands afterwards:
```
composer install --ignore-platform-reqs
php artisan freescout:after-app-update
```

**Comment by borgogelli** [comment]
Ok, thank you a lot. I was pulling from the dist branch instead of master
Regards.
