### ISSUE TITLE
Email not showing when Assigned to unassigned using Workflow.

### ISSUE THREAD

**Issue by challenge3697** [freescout-helpdesk/freescout#3054]
I created a workflow that is triggered when a certain condition is met.

The first workflow assigns the ticket when a specific tag is triggered, and it is working correctly.

The second workflow removes the assigned ticket when both the initial tag and another specified tag are triggered. However, there seems to be an issue with this workflow.

When the condition is set to 'Assign to user > Unassigned' (which should be set to 'Anyone'),

the email does not appear in the Unassigned folder, and the email is gone from the Assigned folder. However, the Active conversation count is not being deducted.

When I click 'All,' I can see the email and it is set to 'Anyone.' The problem is that the email should be in the Unassigned folder, right? it's not showing there.

![image](https://github.com/freescout-helpdesk/freescout/assets/131429870/5ca0c3e6-922f-4c33-9cc0-dda563845525)

Thank you.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.

Make sure you are using the latest FreeScout and modules versions.

Convert the workflow into Manual workflow and check if it works.

Check errors in Manage > Logs > App Logs.

If the workflow still does not work re-update your FreeScout using manual updating method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually
