### ISSUE TITLE
Workflow Condition Tag does not contain not working.

### ISSUE THREAD

**Issue by challenge3697** [freescout-helpdesk/freescout#3055]
Hello,

I believe the "Does not contain" tag condition is not functioning correctly in the Workflow.

I have created two workflows:

1st workflow: This workflow tags the email if the body of the email contains the keyword "report".
Conditions:
Body > Customer message contains > report
Action > Add Tag(s) > Reporting

2nd workflow: This workflow assigns the email to a user called "Demo User" if the email's tag does not contain "Reporting".
Conditions:
Tags > Does not contain > Reporting
Action > Assign to User > Demo User

In the second workflow, the email is still assigned to the Demo User even if the Reporting tag is present. It should not be assigned.

I run the workflow in manual mode, and it seems that the condition "Tags" Does not contain is not working as expected.

I’m using the updated version of Workflow module and FreeScout app.

Thank you.

**Comment by challenge3697** [comment]
I hope someone from the development team can check this.


Thank you.

**Comment by freescout-helpdesk** [comment]
Please attach screenshot of Conditions of the workflow which is not working.

**Comment by freescout-helpdesk** [comment]
Fixed in Tags Module v1.0.28

**Comment by challenge3697** [comment]
Hello, I have already updated my Tag module to version 1.0.28 and I am also using the latest version of the Workflow, which is version 1.0.45. I'm happy to report that you were able to fix the issue with the Tag. Thank you!

Now, I decided to conduct more tests using an Office 365 email.

I created two emails:

- email 1: email1@xyz.com
- email 2: email2@external-xyz.com

**Email 1** email1@xyz.comis the mailbox I added in FreeScout, I set up an automatic email forwarding to email1@xyz.com. This means that all emails sent from email2@external-xyz.com will be automatically forwarded to email1@xyz.com.

However, after setting the workflow to automatic and manual, I noticed that all emails sent to email2@external-xyz.com and automatically forwarded to email1@xyz.com are encountering the same error again. The 'Does not contain TAG' function is not working as expected when forwarded automatically.


Email sent to **email2@external-xyz.com** will be forwarded automatically to email1@xyz.com to be managed by the FreeScout.

![image](https://github.com/freescout-helpdesk/freescout/assets/131429870/832dc1d0-1053-438e-a743-fceebcfb6780)

**Comment by freescout-helpdesk** [comment]
> Email 1 [email1@xyz.comis](mailto:email1@xyz.comis) the mailbox I added in FreeScout, I set up an automatic email forwarding to [email1@xyz.com](mailto:email1@xyz.com). This means that all emails received by [email2@external-xyz.com](mailto:email2@external-xyz.com) will be automatically forwarded to [email1@xyz.com](mailto:email1@xyz.com).

If forwarded email appears in FreeScout as a new conversation, the Tag "Does not contain" condition should work fine. If it does not try to debug it yourself or find someone who can do it for you (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).
