### ISSUE TITLE
Reports Module: non-admin user can see all tags used system-wide

### ISSUE THREAD

**Issue by ThomasEKolb** [freescout-helpdesk/freescout#3056]
Hello!

Since update 1.0.19 of the reports module [1] non-admin users can access statictical reports about their own mailboxes. The issue here is that they can see all existing tags within the tag dropdown field. This is a issue due to leaking sensitive information (encoded in the tag name) to mailbox users of foreign mailboxes.

The expected behavior would be that they can only see tags used in their own mailboxes. 

It would be really nice if this behavior could be changed to show non-admin users only tags used in their own maiboxes.

[1] https://freescout.net/module/reports/

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1.0..30

Now when non-admin user views Reports all metrics are calculated only for mailboxes available to this user.
