### ISSUE TITLE
Fetching issue: IMAP connection broken

### ISSUE THREAD

**Issue by kppp55** [freescout-helpdesk/freescout#306]
Dear Freescout,

I am facing an issue with setup of fetching emails and sending emails.

when i click check connection i get the msg "error occured Please check your internet connection and try again"

I have uninstalled and re installed freescout multiple times now. and the error keeps coming.

I have attached the log files Please can you assist.
 
[fetch-emails (1).log](https://github.com/freescout-helpdesk/freescout/files/3470443/fetch-emails.1.log)
[laravel-2019-08-05.log](https://github.com/freescout-helpdesk/freescout/files/3470444/laravel-2019-08-05.log)

**Comment by freescout-helpdesk** [comment]
Have you tried other Encryption methods?

Does your IMAP Folders field look like this:
![2019-08-06_08-22-03](https://user-images.githubusercontent.com/40499291/62513087-42776d80-b823-11e9-8cda-70ed22230399.png)

**Comment by kppp55** [comment]
Please find attached pic

I have tried SSL and TLS and none I have tried POP settings I have tried ports that are allowed by the server and work from clients like outlook and mobile phones.
all seems to give the same error.

![error1](https://user-images.githubusercontent.com/53550765/62513149-8ff3da80-b823-11e9-9273-5437a0143543.JPG)

**Comment by freescout-helpdesk** [comment]
Make sure that your mail server is available from your server on the ports you are using.

**Comment by kppp55** [comment]
We are checking the ports. but also to not that we have PHPLIST running on the same domain and that is working perfectly fine and we are able to send mailshots out. and receive bounces too which are automatically processed by phplist. will this affect freescout.

**Comment by kppp55** [comment]
would you be able to let me know where the php file is for sending and fetching emails so i can verify the connection settings.

**Comment by freescout-helpdesk** [comment]
You can create a php script (for example `test.php`) in /public folder and open it in the browser (`/test.php`):
```
<?php
$host = 'your.mailserver.com';
$ports = array(25, 143);
foreach ($ports as $port) {
    $connection = @fsockopen($host, $port);
    if (is_resource($connection)) {
        echo '<h2>' . $host . ':' . $port . ' ' . '(' . getservbyport($port, 'tcp') . ') is open.</h2>' . "\n";
        fclose($connection);
    } else {
        echo '<h2>' . $host . ':' . $port . ' is not responding.</h2>' . "\n";
    }
}
```

**Comment by kppp55** [comment]
mail.xxxxxxxxx.com:25 (smtp) is open.
mail.xxxxxxxxx.com:143 (imap) is open.

the reply after the test

**Comment by freescout-helpdesk** [comment]
Is it your personal mail server or public email service provider? Is is possible for us to test it?

**Comment by kppp55** [comment]
its our corporate mail server hosted in a datacenter
yes i can allow you to test on it
i can send you details on freescout login as admin
and then i can send you details for a FTP account which you can login and check the files.

**Comment by kppp55** [comment]
please send me a private msg or a chat so i can share details

**Comment by freescout-helpdesk** [comment]
@kppp55 you can send info to support@freescout.net

**Comment by kppp55** [comment]
sent the details in 2 emails with the same subject matter as above

**Comment by kppp55** [comment]
these are all the ports we use

mail.xxxxxxx.com:25 (smtp) is open.
mail.xxxxxxx.com:143 (imap) is open.
mail.xxxxxxx.com:110 (pop3) is open.
mail.xxxxxxx.com:465 (urd) is open.
mail.xxxxxxx.com:587 (submission) is open.
mail.xxxxxxx.com:993 (imaps) is open.
mail.xxxxxxx.com:995 (pop3s) is open.

**Comment by kppp55** [comment]
i seem to have found out some new information.
if i install freescout in the public_html folder it works. (i did this on a test domain)
if i install freescout in the public_html\freescout sub folder it says no internet connection (again tested it on a test domain)

i think you need to make amendments that it should work from a sub folder.

**Comment by freescout-helpdesk** [comment]
We will fix it and let you know.

**Comment by freescout-helpdesk** [comment]
Update to 1.3.5 and try again.
