### ISSUE TITLE
Timezone not working

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3060]
Hey,

the timezone is not changing the time as it should. We have set the time to GMT+2 but as you can see from the System Status page, this does not translate to the time of the system.

Please see the following Screenshots:
![Settings](https://github.com/freescout-helpdesk/freescout/assets/134635748/81c48c8d-fc9a-4a8f-a52e-48be219d2e34)
![System-Status](https://github.com/freescout-helpdesk/freescout/assets/134635748/72bdf27c-6cf8-4f74-9a3b-d96a58e5b774)
![GMT+2](https://github.com/freescout-helpdesk/freescout/assets/134635748/b7d3ebe9-d5d0-4e9e-9b42-cf80d40504b4)

Thank you very much for your help!

PHP version: 8.2.6
FreeScout version: 1.8.77

**Comment by freescout-helpdesk** [comment]
Keep in mind that each user has Timezone settings in their profile - it has precedence over global Timezone setting.
