### ISSUE TITLE
SAML: Changing the email of an account creates a new account at next login

### ISSUE THREAD

**Issue by t-aus-m** [freescout-helpdesk/freescout#3064]
I just encountered an issue with Freescout and the SAML module. When I change the mail address of an account on a Freescout instance with SAML enabled it creates a new account at the next login, because the attribute that the account is matched on has changed. I think it would be really useful if you could prevent the users to change certain attributes, especially the ones that are set by the Idp. 

PHP version: PHP 8.1.13
FreeScout version:  1.8.36 
SAML module version: 1.0.6

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
