### ISSUE TITLE
Custom Reporting

### ISSUE THREAD

**Issue by eburgers81** [freescout-helpdesk/freescout#3068]
Hi,

We are looking at building our own dashboards on top of the freescout data. We already have the reporting module, and for day to day reporting this is fine, but our internal customer also wants to add certain metrics from freescout into our already existing custom dashboards. 

We already sync the full freescout database to our datawarehouse. The question we have is how and where can we find information that describes certain values in the tables, for example, there is a table `status` , this table only contains integers, for example `1` which (I think) has the label Active. In the database we can't find this information, is there any other way to get to this details (with out reverse engineering). 

Thanks,

**Comment by freescout-helpdesk** [comment]
See files in https://github.com/freescout-helpdesk/freescout/tree/dist/app

They contain constants:
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Conversation.php#L70
