### ISSUE TITLE
display more options in header if space is available

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3069]
It would be cool to use the free space on large resolutions to display more icons. Otherwise users are forced to search for their options:

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/1b3ee2ce-10d8-4aeb-93c4-d795e512a695)

The workflows icon could be shown based on the availability of workflows. If available display the icon, if not don't display it. And it would be also click saving :smile:

**Comment by freescout-helpdesk** [comment]
We'll leave it as it is for now.
