### ISSUE TITLE
Message doesn't appear under conversation if multiple recipients

### ISSUE THREAD

**Issue by dipakcg** [freescout-helpdesk/freescout#307]
When we respond to client and also add CC, but then when a client responds with 'Reply All' option (multiple recipients), an email delivers in other Inboxes but doesn't show under FreeScout conversation.

In other words, when a customer sends email to multiple recipients and FreeScout user email is one of them, FreeScout doesn't fetch that email, hence doesn't show that message under FreeScout conversation.

FreeScout version: 1.3.4

**Comment by dipakcg** [comment]
...experienced the same in the older version of FreeScout as well.

**Comment by freescout-helpdesk** [comment]
It happens with different email service providers (Gmail, Yahoo, etc) or specific ones?

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue.
