### ISSUE TITLE
Workflow Module: Conditions on mail subject won't trigger automatic workflow

### ISSUE THREAD

**Issue by pool-alpin** [freescout-helpdesk/freescout#3071]
PHP version: 8.2.5
FreeScout version: 1.8.78

We've recently done a re-install on a new VPS but still have the problem that any condition on the mail subject will not trigger an automatic workflow.
I've tried different settings and variations for the subject condition (starts with, contains, equals), also tried re-installing the module, but can't get it to work.

When setting a condition for text in the body, the same workflow triggers just fine.

What else can I do, to get the subject conditions working?
![image](https://github.com/freescout-helpdesk/freescout/assets/90776042/8d49d551-0de2-443e-9b00-55c059e71c69)

**Comment by challenge3697** [comment]
For the body, please use a single word. If you want the entire word, try to change it to a regex pattern.

The same applies to the subject.

**Comment by pool-alpin** [comment]
Thanks for your answer!
Let's say the subject is "Something before svh24 in subject and something after" and the match should happen for "svh24 in subject", would the regex pattern be `/^.*svh24 in subject.*$/`?
This works in regexpal, but unfortunately not in Freescout.

Multiple words in the body match just fine without regex in my tests though.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.

![2023-06-03_13-25-53](https://github.com/freescout-helpdesk/freescout/assets/40499291/1482b642-a35e-436f-909c-ef1575b454a3)

After new email from customer arrived:
![2023-06-03_13-26-30](https://github.com/freescout-helpdesk/freescout/assets/40499291/e4706551-de69-48c2-a2fc-9d81de2c99af)

**Comment by pool-alpin** [comment]
Thank your for checking. Is there anything else I can check myself, or do I need to find a dev to look into this right away?

**Comment by freescout-helpdesk** [comment]
Yes, you'll need someone who can investigate it on your server.
