### ISSUE TITLE
Module Documentation Typos

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3072]
https://freescout.net/module/kanban/

"it's" should be "its"

https://freescout.net/module/end-user-portal/

"Customer can open each tickets and reply." -> "Customer can open each ticket and reply."

https://freescout.net/module/api-webhooks/

"n8n service receives an empty book in the Webhook

This [this instruction](https://github.com/n8n-io/n8n/issues/3679#issuecomment-1192327218)." -> delete second "this"

**Comment by freescout-helpdesk** [comment]
Thanks. Fixed. In the future feel free to send typos to support@freescout.net
