### ISSUE TITLE
[updating plugins] Trying to process updates results in: ziparchive is depreciated

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3073]
Hi @freescout-helpdesk 
Tried to update plugins and we are now faced with this error.

![image](https://github.com/freescout-helpdesk/freescout/assets/902376/ab31df98-7d1a-4c65-adae-8a0ba62877b4)

Could you advise what this is about and how to solve?

PHP version: 8.2.x
FreeScout version: 1.8.79

Thanks
M

**Comment by raramuridesign** [comment]
@freescout-helpdesk Have you had any chance to review this?

**Comment by raramuridesign** [comment]
@freescout-helpdesk This is an issue relating to php8. 
I found this on stackoverflow, and this only started in the previous update, so the change from php 7 to php 8 and now this happens.

Link to view
https://stackoverflow.com/questions/64698935/using-ziparchive-with-php-8-and-temporary-files

Please provide some feedback on this.

**Comment by freescout-helpdesk** [comment]
Check what happens here: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ModulesController.php#LL504C61-L504C61

Maybe you system does not download ZIP archive properly.

**Comment by raramuridesign** [comment]
@freescout-helpdesk ok, so I am not sure if this todo with the following but I did the following to solve this.
1. downgraded to php 8.1.x
2. Switched off cloudflare protection
3. Waited a few moments and updated as needed

Result: All modules updated.

I need to do more digging but there was an ajax call to freescout being blocked, the interesting thing is I have several freescout instances behind cloudflare zero1 and all the updates worked fine. except this one site.

If another update on modules comes out then I will do more troubleshooting.
M

**Comment by freescout-helpdesk** [comment]
Most likely the problem is in some of CloudFlare's rules.
