### ISSUE TITLE
Spam Filter Issues

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3074]
Typo on Settings Page: "Filter Using Spam-Filtering Altorithm & Learning" -> Algorithm

Nearly 600 emails were suddenly classified as SPAM.  While I understand that we can whitelist on a per customer basis, it should be possible to whitelist all emails from a particular domain since it is impossible to know every email address that could be used by a large company.  If the company is trusted, all emails from that domain should be trusted.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
