### ISSUE TITLE
Users cannot sign in with Google's SAML SSO after upgrade to FS 1.8.79 + SAML SSO 1.0.7

### ISSUE THREAD

**Issue by bartekhejnowicz** [freescout-helpdesk/freescout#3075]
PHP version: 8.1.2
FreeScout version: 1.8.79
SAML SSO version: 1.0.7

Since upgrading FreeScout to the most recent version, including the SAML SSO module, users have been unable to sign in to FreeScout using their Google Workspace accounts. We have been using SAML SSO since March without encountering any issues until now. Moreover, there have been no configuration changes made in the past month or so.

When attempting to sign in with SSO, the following error message appears:

"Error occurred during SAML SSO authentication: The response was received at http://[redacted].com/saml/4888888888/acs instead of https://[redacted]/saml/4888888888/acs"

![Captured 2023-06-05 at 15 07 39](https://github.com/freescout-helpdesk/freescout/assets/16392168/8a4c59e7-0397-41f3-a8c6-3141fd6ae0ca)

When the 'Force SAML Login' feature is activated, users get redirected to the Google Workspace domain, which subsequently leads to a redirect loop. After a few seconds, this results in a 502 error from FreeScout.

The ID in the URL has been obscured, but in both cases, it remains identical. The only variance is the protocol - the response is received via HTTP instead of HTTPS.

I have reviewed the URLs in the FreeScout SAML SSO module settings and in Google Workspace. All of them direct to HTTPS, with no mention of HTTP anywhere.

**Comment by bartekhejnowicz** [comment]
Thanks for getting back to me so quickly! I can confirm `APP_URL` is already pointing to https://. Sadly, the issue is still present.

![Captured 2023-06-05 at 15 22 42](https://github.com/freescout-helpdesk/freescout/assets/16392168/3967632e-561f-417b-8405-bc161a97a3af)

**Comment by freescout-helpdesk** [comment]
In Google Workspace make sure you have HTTPS in the ACS URL: "https://[redacted]/saml/4888888888/acs"
Most likely you have HTTP there.

**Comment by bartekhejnowicz** [comment]
Thank you @freescout-helpdesk ! It seems to be solving the issue.

@pathab I think you should reach out to Cloudron. I too cannot apply this fix to a Cloudron-based FreeScout instance. I suppose they introduced this issue in the recent update:

https://forum.cloudron.io/topic/2494/freescout-package-updates/137

> Remove app.force_https parameter and determine protocol from app.url parameter instead (#3053)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
