### ISSUE TITLE
Saved Replies Variables Not working

### ISSUE THREAD

**Issue by szucher** [freescout-helpdesk/freescout#3076]
Hi,

since the Last Update a Week Ago, in saved Replies the System will sent as example Not the correct first Name of the Customer. FreeScout sent the variable 

i Hope you know what i mean

**Comment by freescout-helpdesk** [comment]
The issue is not clear. Please attach some screenshots.

**Comment by szucher** [comment]
Hi,
here is an example. 

![IMG_1323](https://github.com/freescout-helpdesk/freescout/assets/50209392/6ad124c6-2530-4e58-83c2-4b8e8e789672)

The variable {%customer.firstName%} at the beginning of the saved reply will not be replaced by the first Name of the Customer.

Same with the other customer variables.

hope it will help you

**Comment by freescout-helpdesk** [comment]
Apparently this happens when you are creating a new conversation? And works fine when you are replying to existing conversation?

**Comment by freescout-helpdesk** [comment]
> Apparently this happens when you are creating a new conversation? And works fine when you are replying to existing conversation?

Fixed in Saved Replies Module v1.0.25

**Comment by szucher** [comment]
Thank you for the fast Support :) It works
