### ISSUE TITLE
New Custom Field Dropdown without Option error message misleading

### ISSUE THREAD

**Issue by Wapinpin** [freescout-helpdesk/freescout#3078]
Hello,

When creating a new "Custom Field" with "Dropdown" type and the "options" are empty, the error message is "An error occured check your internet connection and try again".

I've spent a lot of time searching if there were really a network error 🤣 

The error message should be "Options can't be empty" or something like that.

![freescout-customfield](https://github.com/freescout-helpdesk/freescout/assets/88892163/7c4ce02d-64e8-42fa-b802-dd75c520a2d3)
![freescout-customfield2](https://github.com/freescout-helpdesk/freescout/assets/88892163/a6f6b1fb-5836-4303-b096-bd7aae4b9547)

PHP version: 8.1
FreeScout version: 1.8.80

And thank you for your awesome software !!!

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Fields Module v1.0.28.
