### ISSUE TITLE
User add tag but dos'nt edit color of tag. (Tags module)

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3080]
I install Tags module.
and I noticed every user can create new tag by adding tag at conversation without access right to tag.
but user can't edit tag color at tag menu.
I'm little confused this behavior is collect? or just bug?

I expect admin or user with access right only can add new tag and user without access right can only choose one of them.

**Comment by freescout-helpdesk** [comment]
It's by design. There is no plans to change it.
