### ISSUE TITLE
Emails are not deleted from INBOX if trash in Freescout is emptied

### ISSUE THREAD

**Issue by Moongazer** [freescout-helpdesk/freescout#3081]
Not sure if we see this right, but Freescout is "a tool to manage the support-mailbox". Currently, if an email comes in and is deleted in Freescout, it shows up in "Deleted" (soft-deleted). Looking at the mailbox itself (e.g. via email client), the mail remains in the INBOX.

Wouldn't it better to sync the Freescout mail-state with the mailbox folders? If a mail is deleted in Freescout, it should be moved to trash (standard IMAP folder, or a new trash-folder option specified inside the mailbox settings similar to "IMAP Folder To Save Outgoing Replies"). "Empty trash" in Fresscout would than REALLY delete the mails from the trash-folder.

Currently there is no option to prevent the mailbox from growing infinite in size, because no email is ever deleted! ALL mails remain in the INBOX.

PHP version: 8.1
FreeScout version: 1.8.72

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/gdpr/
