### ISSUE TITLE
Sent errors need to be more visible

### ISSUE THREAD

**Issue by burner-** [freescout-helpdesk/freescout#3082]
With 2 separated system I have now hit that there is problems with sending emails but users wont notice that there is anything wrong. There is no way to notice that emailf fail and it is quite horrifying situation when you notice after week that there is hundreds of tickets at failed state. 
Things is even worse that there is no way to try resend failed messages. 
So 2 feature request:
- Proper visible error to show if message is not sent. Those need go to conversation list as red or somehting else. 
- possibility to try resend message.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2808
