### ISSUE TITLE
Password secure freescout site exept SatisfactionRatings

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3084]
Hi,

is there a way to restrict access (http access control) to freescout (running on nginx) while still allowing the customers to give Satisfactionratings?

Thanks a lot for your help!

Best regards

PHP version: 8.2.6
FreeScout version: 1.8.80

**Comment by ilyakonovalenko** [comment]
It is technically possible by configuring auth rules based on location.

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
Where location can be regex to match everything except satisfaction page urls.

**Comment by githubuser-112** [comment]
Thanks for your reply @ilyakonovalenko !

We put a block into our nginx directive for the following location and it works as a charm:

```
#Password secure all locations that do not start with "/feedback/"
location ~* ^/(?!feedback/).*$ {
    #your auth info
}
```
