### ISSUE TITLE
Kanban modal window issue

### ISSUE THREAD

**Issue by Maddmax76** [freescout-helpdesk/freescout#3086]
Good morning. In the Kanban view, when I open a request, a modal window appears, the title of the window is the subject of the request, there is the button to close, inside the window there is a gray panel with an icon that warns me that my site refused to connect.

can you help me?

Thank you

PHP version: 8.1.12-1ubuntu4
FreeScout version:   1.8.78

![Immagine 2023-06-07 181522](https://github.com/freescout-helpdesk/freescout/assets/47970623/79e86e42-d516-41ac-b5c1-82a8416176c2)

**Comment by Maddmax76** [comment]
It seems that in the modal window you are trying to open the conversation page in x-embed mode. Apache for safety does not allow it. Some idea?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1596

**Comment by Maddmax76** [comment]
Thanks for the report, I tried to change the apache configuration but without success. Is there any other test I can do?
Thanks again

**Comment by freescout-helpdesk** [comment]
> **Solved**, in addition to enabling "SAMEORIGIN" in "X-Frame-Options“ it is also necessary to enable the "Content-Security-Policy" for "SELF". When restarting Apache Kanban opens the tickets in the modal window.

Thanks for the info. Can you tell how you've set "Content-Security-Policy"?

**Comment by Maddmax76** [comment]
sure, in the configuration file (in my case security.conf) I added the lines:

Header set X-Frame-Options: "SAMEORIGIN"
Header set Content-Security-Policy "frame-ancestor 'self';"

and everything, as if by magic, started to work
