### ISSUE TITLE
about SPAM filter asterisk usage.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3088]
I want to move mails that their subject start from "[spam]".
so I set Filter 
[spam]*
at Filter by Subject column.
but SPAM filter doesn't work what I expected.
my asterisk usage is wrong?

I know Workflow will do same but Workflow can't move mails to spam folder.

**Comment by freescout-helpdesk** [comment]
Asterisk can be used only in "Filter by Email" filter.
