### ISSUE TITLE
Understanding how I can answer tickets

### ISSUE THREAD

**Issue by MarvinWeitz** [freescout-helpdesk/freescout#3090]
Hi everyone. I'm new to FreeScout and Mail services so this might seem like a trivial question.

My goal is the following:
- have a FreeScout mailbox (e.g. help@example.com) to get new tickets from customers
- have an agent email (e.g. agent@example.com) that can handle the tickets
- agent should be able to see the tickets and their other mail in one of the mailboxes

So to clarify, "Agent" shouldn't need to open FreeScout as well as Gmail to access their mail and assigned tickets. From what I've understood, this is not possible with Freescout correct? Or have I misunderstood something and it's possible to reply to a ticket from the Agent assigned mail (I know they can get a notification when a ticket reply arrives, is there an option to do what I want to achieve)?

Thanks for any help on this

**Comment by ilyakonovalenko** [comment]
Yes, agents are able to reply by replying to conversation notification.

**Comment by avenjamin** [comment]
@MarvinWeitz Freescout doesn't display any IMAP folders for a mailbox (maybe there's a custom Module for this?)
So if the agent wants to stay in a single interface where they can see emails and tickets then they'll have to do it from their mail client.

As @ilyakonovalenko said the agent can respond to tickets as they would a normal email just fine.

The only time I see this becoming an issue is when multiple agents are handling tickets.
Make sure each agent has the `"ticket is assigned to agent"` notification turned on to avoid multiple replies from different agents. 

Hopefully that makes sense.

Also you may want to consider the [Email Commands Module](https://freescout.net/module/email-commands/).
It'll help you access some of the other functions within FreeScout via email.

Enjoy FreeScout!

**Comment by MarvinWeitz** [comment]
Thank you for the fast responses!
