### ISSUE TITLE
usage of custom fields in knowledge base

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3091]
I'd like to combine the CRM, enduser portal and the knowledge base module. What I want to achieve is to build a knowledge base where partners of us can login and find their help articles including related affilliate URL. Those URLs always contain a unique identifier that I would like to replace dynamically based on a custom value saved in the CRM module.

An URL could look like this for example in the source code
`https://www.example.com/superproduct?partnerID={%customer.cf_1%}`
and like this resolved
`https://www.example.com/superproduct?partnerID=12345`

Is that possible?

**Comment by freescout-helpdesk** [comment]
Unfortunately not and no plans to implement.
