### ISSUE TITLE
Connection to Mailu email server does not work

### ISSUE THREAD

**Issue by bsk-eduardo-oliveira** [freescout-helpdesk/freescout#3092]
I have a Mailu email server with several domains and when I configure the connection to this server and send a test email, errors occur.

Connection could not be established with host smtp.selfxxxxx.com [ #0].

Port 587 is unlocked, user data is correct and all other information has already been checked.

Does Freescout have any incompatibility with Mailu Server?

Is this a Freescout bug?

How to fix this problem?

**Comment by ilyakonovalenko** [comment]
Check your mail server logs. Also try to run something like `telnet SERVER_ADDRESS 587` from FreeScout server to make sure it is accessible.

**Comment by bsk-eduardo-oliveira** [comment]
We tested telnet with multiple domains to port 587 and the return was ok, no errors and connected.
We also tested access with several email clients and it worked perfectly, only with FreeScout is the connection with Mailu Mail Server not working. The error returned by FreeScout is 500, see below.
Here the error we have is not a problem of firewall because connection is established but returning "500 5.5.1 Invalid command"
This means freescout is sending an SMTP command not supported by MailU

image.png
![erro_500_FreeScout](https://github.com/freescout-helpdesk/freescout/assets/49482276/476b6b82-ff4b-449b-a9d3-fc926aa7343c)

**Comment by ilyakonovalenko** [comment]
> This means freescout is sending an SMTP command not supported by MailU

May be related to incorrect encryption setting or some unsupported symbols in login or password. Try to check logs on the MailU side.

**Comment by bsk-eduardo-oliveira** [comment]
I spotted an unsupported auth error in Mailu the moment I tried to login with FreeScout. Now it's figuring out how to adjust this!
![print_log_error_mailu](https://github.com/freescout-helpdesk/freescout/assets/49482276/0e01cf25-0533-406c-a0a6-cfe7fb37fa65)

**Comment by freescout-helpdesk** [comment]
So have you managed to resolve it?

**Comment by ilyakonovalenko** [comment]
https://github.com/Mailu/Mailu/issues/2274

Maybe outdated Mailu version?

**Comment by bsk-eduardo-oliveira** [comment]
Encryption is enabled, we can use SSL. We even tried a proxy, but it didn't work.

**Comment by bsk-eduardo-oliveira** [comment]
Hello!

The problem was solved using the FreeScout postfix, where we point the postfix to our Mailu server, so the login is performed directly and as the servers are in the same internal network it is safe and solved our problem, at least until another option better be presented.

Thank you for your help!!!
