### ISSUE TITLE
custom htaccess modifications

### ISSUE THREAD

**Issue by maisen20** [freescout-helpdesk/freescout#3093]
For security reasons, access to my Freescout platform is only allowed from predefined IP addresses. I have implemented this by modifying my .htaccess file.

Now my question:
- Is the .htaccess file under /public overwritten after every update, so that my changes are no longer present? I assume so.

Therefore, I would like to program a module for myself, with which this .htaccess file can be adjusted. Is there already a way to automate this and have my .htaccess modifications automatically added when I have done an update? 

Doing this adjustment manually after each update is not good, because it will surely be forgotten at some point.

**Comment by freescout-helpdesk** [comment]
You can place your custom .htaccess in a folder above FreeScout's folder.

**Comment by maisen20** [comment]
I tried that, but unfortunately it doesn't work.

When I create the htaccess file in the parent folder of FreeScout, with my rules, it does not work. But if I put these rules in the htacess file of the public folder of FreeScout, it works.

My domain points directly to the public folder of FreeScout

**Comment by freescout-helpdesk** [comment]
There are two options:
1) Teach your web server to read upper-level .htaccess
2) Change FreeScout's .htaccess and update after each update.

**Comment by Nexulo** [comment]
In my opinion, these solutions are not correct. The _.htaccess_ file in the public folder should have the line: 
`RewriteOptions Inherit`

And in the root directory of FreeScout, the _.htaccess_ file with the automatic redirection to /public should not be present at all. You can really configure anywhere that a domain should point to the /public folder and not to the root directory.

If both were the case, it would work perfectly with a custom _.htaccess_ file placed before the FreeScout root directory.
