### ISSUE TITLE
Why is the sorting in "Closed" mixed up?

### ISSUE THREAD

**Issue by giemes** [freescout-helpdesk/freescout#3094]
If you do the sorting in "closed" Mailbox Folder, the sorting is mixed up - as you can see in the screenshot:

![image](https://github.com/freescout-helpdesk/freescout/assets/16294248/b3b312ad-20d7-4a16-b2ce-4e32a9c55778)

It seems to have something to do with the unit-of-measure if it is back "days" or just minutes ...

in other "folders" it works ... can anybody tell why or if there is a fix coming? Thnx!

regards, Gerd

**Comment by freescout-helpdesk** [comment]
Your FreeScout version?

Can you reproduce the issue on demo.freescout.net?

**Comment by giemes** [comment]
no to less data from the past

**Comment by giemes** [comment]
in the demo there ware just a few closed issues - we need issues across the last months to reproduce it - this is not possible in the demo, means: the sorting is messed up > you see in my screenshot the "latest" but it is not sorted properly, eg here a new screenshot:

<img width="716" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/16294248/fa30c8d8-4ac4-4562-a3a8-100b4043c3b1">

**Comment by freescout-helpdesk** [comment]
> Your FreeScout version?
