### ISSUE TITLE
How to turn it to SaaS ?

### ISSUE THREAD

**Issue by yamakrane** [freescout-helpdesk/freescout#3097]
Hello,

what are the steps to take to turn this into a SaaS product for my companie’s clients list ?

thanks

**Comment by yamakrane** [comment]
Multi tenant of course

**Comment by ilyakonovalenko** [comment]
It is impossible by default. You have to fork and customize code in the way you want.

**Comment by yamakrane** [comment]
Yes but what are the recommended steps so I know if it’s worth it or no
please.

Thanks for your kind answer

Le dim. 11 jui. 2023 à 13:16, ilyakonovalenko ***@***.***> a
écrit :

**Comment by ilyakonovalenko** [comment]
> Yes but what are the recommended steps so I know if it’s worth it or no please.

I can't recommend you anything on this. It is better to find developer which will help you. You can also write a script which will install instance per customer, so each customer will have its own instance with separated files and DB.

**Comment by freescout-helpdesk** [comment]
> what are the steps to take to turn this into a SaaS product for my companie’s clients list ?

There is no such possibility for now.

@ilyakonovalenko Thanks for helping out.

**Comment by yamakrane** [comment]
Wonderful. You the best.
