### ISSUE TITLE
NSURLErrorDomain error -999

### ISSUE THREAD

**Issue by cruunnerr** [freescout-helpdesk/freescout#3099]
PHP version: 8.1.2
FreeScout version: 1.8.67

I use the App on an iPhone 11. When I cold start the App, everything is fine. 
Then I turn the App in the Background as usual. I receive Push Notifications as well.
Sometimes, when I open the App from the Background I get this error:

> Error occured:
> The operation couldn't be completed.
> (NSURLErrorDomain error -999)

> Click OK to try again or Cancel to change Helpdesk URL

If I click ok, I will see a blank page. When I click Cancel and try to log in via "Go", I will see a blank page as well.

Only way to fix is to completely close the App and cold start again.

The domain is directly mapped to a stand-alone IPv4 Server without any reverse-Proxy or something like that. SSL via le's encrypt.

Nothing to see in the logs. Any idea?

**Comment by ilyakonovalenko** [comment]
Happens for me all the time since the first day of the app usage :-) What is interesting, it does not happen on some iOS devices and on iPad. Not sure what causing the issue.

**Comment by cruunnerr** [comment]
Seems to be wrong request habdling as far as I can estimate. 

https://stackoverflow.com/questions/16073519/how-to-fix-nsurlerrordomain-error-code-999-in-ios

**Comment by freescout-helpdesk** [comment]
So far we don't have clues on how to fix it in the app.

**Comment by myde2001** [comment]
Still happening

**Comment by cruunnerr** [comment]
yep, still happening. Would be great if this could be solved. I doesn't seem to have this problem on my iPad Air 4.

**Comment by Thiritin** [comment]
This unfortunately still occurs.

**Comment by Thiritin** [comment]
A customer of mine experiences an issue with their Freescout Installation. I have recommended them FreeScout and they have purchased plenty of addons.

They are using an iPhone 14 Pro Max with an iOS Version of 18.4.1

**Comment by freescout-help** [comment]
https://freescout.net/freescout-ios-app-help-needed/
