### ISSUE TITLE
Error access mine folder

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#310]
Using version 1.3.5 and I can't access `Mine`. One other person can access her `Mine` but she cannot access `Assigned`. So maybe tag/some mail causing error. 

This I found in the app error log. Any advice appreciated. 

error | production | 2019-08-14 20:45:35 | Call to a member function getColorClass() on null (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) {"userId":1,"email":"XXXXX","exception":"[object] (ErrorException(code: 0): Call to a member function getColorClass() on null (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) at /srv/users/helpdesk/apps/helpdesk/storage/framework/views/f9d8ed9c6ad997192ef0b24fe37897XXXXXX.php:1, ErrorException(code: 0): Call to a member function getColorClass() on null (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) at /srv/users/helpdesk/apps/helpdesk/storage/framework/views/f9d8XXXX24fe378979e1bc820c4.php:1, ErrorException(code: 0): Call to a member function getColorClass() on null (View: /srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php) at /srv/users/helpdesk/apps/helpdesk/storage/framework/views/f9d8ed9XXXXXX0b24fe378979e1bc820c4.php:1, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getColorClass() on null at /srv/users/helpdesk/apps/helpdesk/storage/framework/views/f9d8ed9XXXXX24fe378979e1bc820c4.php:1)
-- | -- | -- | --

**Comment by freescout-helpdesk** [comment]
Try to change content of the **/srv/users/helpdesk/apps/helpdesk/Modules/Tags/Resources/views/partials/conversation_list_tag.blade.php** to:
```
@if ($tag)
    <span class="tag {{ $tag->getColorClass() }}">{{ $tag->name }}</span>
@endif
```
