### ISSUE TITLE
Jira module. Module does not respond to some Jira statuses

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#3100]
Hello developers! I have a problem with a Jira module.

For some reason, the module does not respond to some Jira statuses. For example, when switching to Jira's default statuses of "In Progress", "Open", and "Done", I see these changes in the linked ticket. But the module does not react to some statuses, for example "Reopened", "Resolved". Also, the module correctly detects custom statuses created by Jira administrators and responds correctly to their changes.

I tried to set the "Jira Issue Resolved Status" status to "Resolved" in the Jira Module settings, but the module does not respond to this Jira status. At the same time, the module reacts correctly to the "Done" status and change FreeScout conversation status to Active.

I checked the Jira log. All webhooks were sent without errors. FreeScout logs show no errors

FreeScout version: 1.8.71
Jira module version: 1.0.8
Jira Server version: 8.20.1

**Comment by freescout-helpdesk** [comment]
Could you please attach screenshot of Jira settings in FreeScout.

**Comment by SergeyMi88** [comment]
Jira module settings:

![2023-06-13_21-39-18](https://github.com/freescout-helpdesk/freescout/assets/101319104/33ab455d-b8e0-40fc-aaa2-fd686eb40180)

Statuses in related tickets are updated, but not all statuses:

![2023-06-13_21-44-31](https://github.com/freescout-helpdesk/freescout/assets/101319104/e4291d9d-f4c7-417f-9632-2a17f51f6e88)

**Comment by SergeyMi88** [comment]
![2023-06-14_11-58-29](https://github.com/freescout-helpdesk/freescout/assets/101319104/a5a47b43-aa1d-445a-98fc-cc9822670a0e)

**Comment by freescout-helpdesk** [comment]
You'll need to add a "Fire a Generic Event event" manually.

**Comment by SergeyMi88** [comment]
Thanks, have a good day.
