### ISSUE TITLE
Missing Thread in Conversation

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3102]
Summary: We sent an email on June 8 however it does not appear when viewing the conversation.

When we search for the conversation, it shows a preview of the email that was sent in the search results.  It shows Waiting Since June 8, 2023 @ 01:32 pm with a status of "Last reply by User".  The thread count shows as 5.

Opening the conversation shows only four threads: the original email from the customer, two notes, and a reply on June 1.  The June 8 email to the customer is missing.

The Outgoing Emails log shows the email being sent with a status of Accepted for delivery.  Curiously, it shows two separate emails to the customer when only one was sent.  The timestamps in the Outgoing Emails log are:

- Jun 8, 01:32:13pm
- Jun 8, 01:32:27pm

There are no entries in the Send Errors log for this date.

There are 5 entries in the App Logs for this date, two of which have the same timestamps as the two entries in the Outgoing Emails log:  The content for each entry is:  Could not save outgoing reply to the IMAP folder: Error: fread(): SSL: Connection reset by peer; File: /www/html/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (108)

The email did not save to our mail server.  We are using Microsoft 365 with the following authentication: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth

Docker: https://hub.docker.com/layers/tiredofit/freescout/latest/images/sha256-ea1ecdbf14268d3e14a0541766a8164f45d1ce806fba257be02de0cfeda7fd2d?context=explore

**Comment by freescout-helpdesk** [comment]
> We sent an email on June 8

Have you sent an email as customer to your FreeScout or replied as a support agent to the conversation?

> The content for each entry is: Could not save outgoing reply to the IMAP folder: Error: fread(): SSL: Connection reset by peer

This error simply indicates that FreeScout could not save support agent reply to the "IMAP Folder To Save Outgoing Replies" due to your mail server IMAP connection issue.

**Comment by freescout-helpdesk** [comment]
"IMAP Folder To Save Outgoing Replies" option is not connected to the process of sending emails. You are using it just to backup emails on your mail server.

If support agent reply in your FreeScout is not saved to DB you'll need to debug it on your FreeScout as we've never seen such issue.

If support agent reply is saved in DB but is not sent to the customer - see https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by freescout-helpdesk** [comment]
The only way to figure out what happened there is to check it on your server.

**Comment by freescout-helpdesk** [comment]
Similar issue: https://github.com/freescout-helpdesk/freescout/issues/3164
Have you found a solution?
