### ISSUE TITLE
"Hide from assign list" also affects @mentions module

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3105]
Hey,

the "Hide from assign list" setting of a mailbox does also affect the @mentions module. So if you want to hide someone from the assign list, the person also cannot be mentioned anymore. This should be a separate permission, as these are two different things and are used independently.

Thanks a lot!

Best regards

PHP version: 8.2.7
FreeScout version: 1.8.80

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2083
We'll leave it as is.

**Comment by githubuser-112** [comment]
Thanks for your response, but that´s really sad to hear. The two features are totally distint and should have separate permissions. Mentioning someone for help in tickets happens with people that never need to be assigned a ticket. Would you reconsider this?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. You can adjust it via hooks and custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development

**Comment by githubuser-112** [comment]
That surpasses our skills and also the time input just for us seems unreasonable. We thought it might be a minor fix to the plugin. Thanks for your clear communication though!
