### ISSUE TITLE
Spam Module / Notifications

### ISSUE THREAD

**Issue by bekre10** [freescout-helpdesk/freescout#3106]
Is there any way to prevent notifications being sent for those emails which are filtered as spam?
My Client get's flooded with notifications.

**Comment by freescout-helpdesk** [comment]
This is how it works already.

**Comment by bekre10** [comment]
I do receive new ticket notifications and when I check, it is in the spam. Has this been changed just in the last few days?

**Comment by bekre10** [comment]
I have checked again and over a 100 tickets which the FreeScout spam module filters and moved to the spam folder, have still sent a notification to the customer.

**Comment by freescout-helpdesk** [comment]
> have still sent a notification to the customer.

Are you talking about email notifications to support agents or auto-replies to customers?

**Comment by bekre10** [comment]
Sorry, my wrong. I am talking about email notifications to the support agents.
They still receive it even for messages which are in the Spam folder.

**Comment by freescout-helpdesk** [comment]
Are you using the latest FreeScout and Spam Filter Module version?

**Comment by bekre10** [comment]
Yes, I do. Checking for updates of system and modules every day.

**Comment by freescout-helpdesk** [comment]
The only way to figure out why it happens on your FreeScout is to investigate it on your server.
