### ISSUE TITLE
Only one workflow is running per mailbox

### ISSUE THREAD

**Issue by Haribo112** [freescout-helpdesk/freescout#3107]
PHP version: 7.4
FreeScout version:  1.8.80   

We are trying to make use of the Workflow module but are encountering a severe issue. It seems like only the top workflow is ever run. When we remove that Workflow, the next one up runs. Our setup is as follows:

1) Apply a tag to all incoming messages
2) Check for "A" in subject -> apply tag "a" and close
3) Check for "B" in subject -> apply tag "b" and close

Workflow 1 works fine, all incoming messages are tagged. Workflows 2 and 3 however are never applied (as seen in "Applied to 0 conversation" within the workflow settings). When I remove Workflow 1, Workflow 2 runs fine but Workflow 3 still does not.

**Comment by freescout-helpdesk** [comment]
Attach screenshot of your workflows.
