### ISSUE TITLE
Conversation in reply

### ISSUE THREAD

**Issue by cmorin28** [freescout-helpdesk/freescout#3108]
Hello,

Would it be possible for the customer to receive the entire conversation following the response message in the emails? Like in an MS Outlook conversation, for example?

This is a requirement that has been raised by several of our customers.

**Comment by freescout-helpdesk** [comment]
Manage > Settings > Emails to Customers > Conversation History

**Comment by cmorin28** [comment]
Thank you !

**Comment by zerofruchtshake** [comment]
Is it somehow possible to set this per individual inbox?

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
