### ISSUE TITLE
Microsoft Exchange connect link missing !

### ISSUE THREAD

**Issue by SecteurA** [freescout-helpdesk/freescout#3109]
Hello, 

We have Freescout installed with 10 mailboxes, it's working with no issues, mailboxes are connected to Microsoft Exchange, today i wanted to add new mailbox, i couldn't because the connect to miscrosoft exchange link is messing ! i can't what should i do ? 

Thank you

Freescout version : [1.8.80]
Php version : PHP 8.1.2-1ubuntu2.11

**Comment by SecteurA** [comment]
You can see the screenshot here : 

https://i.ibb.co/RB34C9k/Capture-d-e-cran-2023-06-14-a-13-24-43.png

**Comment by freescout-helpdesk** [comment]
Enter Username and it will appear.

**Comment by Haribo112** [comment]
I don't entirely agree with what `freescout-helpdesk` said. You need to enter username and password and then hit 'Save settings' for the Connect link to appear.

**Comment by SecteurA** [comment]
Hello,

I followed precisely those instruction, as i stated before, i have other accounts connected to exchange, i just needed to add one more account and i got this issue !

Thanks

**Comment by freescout-helpdesk** [comment]
Here is the condition showing "Connect" link.
```
    @if ($mailbox->in_username && $mailbox->in_password && !strstr($mailbox->in_username, '@'))
         – <a href="{{ route('mailboxes.oauth', ['id' => $mailbox->id, 'provider' => \MailHelper::OAUTH_PROVIDER_MICROSOFT]) }}" target="_blank">{{ __('Connect') }}</a>
    @endif
```
https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/mailboxes/connection_incoming.blade.php

Check why it does not show the link.

**Comment by SecteurA** [comment]
Hello,

Thank you for your reply, there is nothing wrong with the code, i missed something, i followed the steps as you suggested and it works !

Thank you
