### ISSUE TITLE
Fetching emails without Message-ID

### ISSUE THREAD

**Issue by lanc2112b** [freescout-helpdesk/freescout#311]
I've recently installed Freescout and while running a few quick tests, I've noticed it's not processing new emails or responses from certain email accounts.

The initial test I did from an email account on the same server, although a different domain to that which the site is hosted. The initial email was picked up and turned into a ticket, replies etc and new updates worked as expected. I fired off another email, this time to make a new ticket, waited a while - no new ticket. Fired off another with another subject title, still no new ticket and got a message in the logs :

[2019-08-14 03:42:11] Fetched: 1
[2019-08-14 03:42:11] 1) What the hell is broken
[2019-08-14 03:42:11] Message with such Message-ID has been fetched before: 
[2019-08-14 03:42:11] Fetching finished

I tried sending from a second email address on the same server and got similar messages. If i send from my hotmail/live mail address, they get processed correctly and tickets created, likewise from my gmail account.

It only seems to skip / ignore (as fetched previously) for email accounts / domains hosted on the same server as the Freescout install for some reason. I know they have hit the mailbox as unread, the cron process pulls the emails and then marks them as read, as I've watched further tests via Horde. 

Any suggestions on what's occurring appreciated?

**Comment by freescout-helpdesk** [comment]
Most likely you server creates emails with same Message-ID or with empty Message-ID, which is wrong.

**Comment by lanc2112b** [comment]
The ids appear unique, I've checked the source of every email from this accounts

Headers from 3 seperate mails, picked up as already fetched, I've removed IP's and domains.

(1)
Received: from ...
	by ... with LMTP
	id iOmqOLdtU12ADQAA5S9q0A
	(envelope-from <...>)
	
Received: from ... ([...]:54434 helo=[...])
	by .... with esmtpsa (TLSv1.2:AES128-GCM-SHA256:128)
	(Exim 4.92)
	(envelope-from <...>)
	id 1hxikh-0002DJ-Qg
	for ...; Wed, 14 Aug 2019 03:11:03 +0100
(2)	
Received: from ...
	by ... with LMTP
	id uyuvECpqU13tVQAA5S9q0A
	(envelope-from <...>)
	for <...>; Wed, 14 Aug 2019 02:55:54 +0100
	
Received: from ... ([...]:54296 helo=[...])
	by ... with esmtpsa (TLSv1.2:AES128-GCM-SHA256:128)
	(Exim 4.92)
	(envelope-from <...)
	id 1hxiW2-0005iR-0K
	for ...; Wed, 14 Aug 2019 02:55:54 +0100
(3)	
Received: from ...
	by ... with LMTP
	id L7PWKsN0U11nHgAA5S9q0A
	(envelope-from <...>)
	for <...>; Wed, 14 Aug 2019 03:41:07 +0100
	
Received: from ... ([...]:54794 helo=[...])
	by ... with esmtpsa (TLSv1.2:AES128-GCM-SHA256:128)
	(Exim 4.92)
	(envelope-from <...>)
	id 1hxjDn-0002B4-Ht
	for ...; Wed, 14 Aug 2019 03:41:07 +0100

**Comment by freescout-helpdesk** [comment]
Debug this script: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php

You can execture fetching in System --> Tools

**Comment by lanc2112b** [comment]
From a little more testing, when sending from Samsung's default email client,  the message-id doesn't get added, depending on the smtp server it's sent through, some provide the fixup, others do not. In the one used for initial testing, it was indeed a lack of 'message-id' although other "id" 's are in there

Obviously I cannot control the mail client that's doing the sending, nor can I effect changes on other peoples smtp servers, so it seems likely that certain emails landing in the inbox won't end up generating tickets. 

Looking at the rfc5321 & previous rfc2821: 

> The following changes to a message being processed MAY be applied
>    when necessary by an originating SMTP server, or one used as the
>    target of SMTP as an initial posting (message submission) protocol:
> 
>    o  Addition of a message-id field when none appears
> 
>    o  Addition of a date, time, or time zone when none appears
> 
>    o  Correction of addresses to proper FQDN format

It's optional as to whether the server provides the fixup required.

I imagine there's more than just Samsungs client that doesn't play nicely, is this the only method used of identifying new mail in the mailbox?

**Comment by freescout-helpdesk** [comment]
Thanks. Fetching emails without Message-ID has to be implemented.
