### ISSUE TITLE
Error for some emails during fetch

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#3110]
I get a lot of fetch errors like this

```Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'status' cannot be null (SQL: insert into `conversations` (`preview`, `type`, `state`, `subject`, `mailbox_id`, `customer_id`, `created_by_customer_id`, `source_via`, `source_type`, `cc`, `customer_email`, `status`, `last_reply_at`, `last_reply_from`, `folder_id`, `number`, `updated_at`, `created_at`) values (Read on Website WP Weekly 149 / Plugins A good bunch of new plugins to track this week, like Spectra Pro, Dynamic Shortcodes, FuseWP, and User Feedback. Plus updates from page builder plugins, SEO plugins, WooCommerce, WordCamp EU, and Automattic’s AI div, 1, 2, WP Weekly 149 - Plugins - Test Spectra Pro, Jetpack with AI, Better Woo Performance, 10, 14441, 14441, 1, 1, ["test@test.com"], hello@thewpweekly.com, , 2023-06-12 08:10:18, 1, 89, 112335, 2023-06-12 08:10:18, 2023-06-12 08:10:18)); File: /home/runcloud/webapps/mail/vendor/laravel/framework/src/Illuminate/Database/Connection.php (664)```

Other emails are fetched and stored properly.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3050#issuecomment-1564302921
