### ISSUE TITLE
Signatures from e-mails are displayed in FreeScout as a code element

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#3111]
Hello all,

When I receive an email request in FreeScout, the signature of the email is often displayed as a code. In most cases, this is due to the fact that the e-mail and signature are separated by, for example, the following characters: "--" (or similar). These make the ticket display a little unattractive.

Enclosed you will find a screenshot of this representation.
What options do I have to adjust this display so that the signature is not recognised as a code? Is it possible to completely deactivate code displays, for example?

Many thanks in advance,
With best regards
Lukas
<img width="800" alt="Bildschirmfoto 2023-06-15 um 12 37 37" src="https://github.com/freescout-helpdesk/freescout/assets/14358967/ebb28766-569b-4a0b-b525-ae70556cf7eb">

**Comment by freescout-helpdesk** [comment]
> ...the signature of the email is often displayed as a code

If you see it like this in your FreeScout there is no way to change it.
