### ISSUE TITLE
A ticket, that was set to not send a closed notification, sent a notification when a team member changed the ticket name.

### ISSUE THREAD

**Issue by sgmcmiller** [freescout-helpdesk/freescout#3112]
A ticket, that was set to not send a closed notification, sent a notification when a team member changed the ticket name. The ticket was made a couple of months ago and was already in the closed state.

PHP version: PHP 8.1.2-1ubuntu2.11
FreeScout version:  1.8.80

**Comment by Stunt0265** [comment]
Not to help your issue, but what's a "closed notification"?  I haven't seen a way to set this.

**Comment by freescout-helpdesk** [comment]
We can't understand what you are talking about.

**Comment by sgmcmiller** [comment]
We have a workflow set up so that a customer is sent a notification when their ticket is closed. I also have conditions set in the workflow to not have the notification sent using tags. When a team member changed the name of a ticket, that had been closed for months, the workflow was triggered. I hope that clears some confusion.

**Comment by freescout-helpdesk** [comment]
Can you attach screenshots of Workflows settings.

**Comment by sgmcmiller** [comment]
![image](https://github.com/freescout-helpdesk/freescout/assets/136723815/a9a6fab1-3e64-429c-bc87-054099dc32b5)
![2023-06-26 08_20_21-DSC_0550 JPG @ 25% (RGB_8)](https://github.com/freescout-helpdesk/freescout/assets/136723815/2e7891c0-c523-4577-9303-20b9f9fe70a5)
![2023-06-26 08_20_38-Workflows - M  C  Miller Technical Support — Mozilla Firefox](https://github.com/freescout-helpdesk/freescout/assets/136723815/cfac3941-c4d8-4526-a08f-fdffe8c63b99)
![2023-06-26 08_20_13-Workflows - M  C  Miller Technical Support — Mozilla Firefox](https://github.com/freescout-helpdesk/freescout/assets/136723815/1e6393fc-2c95-4e29-9710-87b4209c6420)

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue.

**Comment by sgmcmiller** [comment]
Thanks for trying
