### ISSUE TITLE
Atfer installing 1 module somthing goes wrong with docker-compose

### ISSUE THREAD

**Issue by ebgtobi** [freescout-helpdesk/freescout#3113]
Hi there!

We need some help with our freescout server. After activating one module and installing it, docker-compose down and up is not working corretly anymore. We always get the notification "Whoops, looks like something went wrong - check logs in /storage/logs".

It looks like it dosent depand on the type of module we install. After installing the instance breaks and is not working anymore. Before installing docker-compose down and up works complety fine.

Any sugesstions for us? What can we check/do to solve that problem?

Thanks for your help!
Tobi

**Comment by freescout-helpdesk** [comment]
We have no idea what can cause it.

**Comment by ebgtobi** [comment]
Thats not good. We bought the modules and now we cant really use them.

Is there nothing to provide us? Any sugesstion, instruction or something? Or can we send any log files to you?

**Comment by freescout-helpdesk** [comment]
You can share errors from /storage/logs

**Comment by ebgtobi** [comment]
[Logs.txt](https://github.com/freescout-helpdesk/freescout/files/11891685/Logs.txt)

**Comment by freescout-helpdesk** [comment]
> production.ERROR: Aborted.

This looks like some kind of limitation from your server/hosting side. Maybe memory, CPU or some other limitation.

**Comment by ebgtobi** [comment]
![Screenshot 2023-06-28 112420](https://github.com/freescout-helpdesk/freescout/assets/133633946/cd74c533-90f2-4dae-bdef-f5864c9ce220)
![Screenshot 2023-06-28 112515](https://github.com/freescout-helpdesk/freescout/assets/133633946/ffdcf6d5-fb7d-4af6-a4cb-227968b1a400)

For us, it doesn't look like, that we are reaching the limit in some point.

**Comment by freescout-helpdesk** [comment]
PHP or web server may have some restrictions set. Anyway the only way to find out what Aborts the script is to check it on your server.

**Comment by ebgtobi** [comment]
How we can check the PHP or web server restrictions or remove them? Can you provide us there a instruciton or tutorial?

Where should we go to search on the server because of the script? We have installed the docker from ([quelle](https://github.com/tiredofit/docker-freescout/blob/main/examples/docker-compose.yml)). Is there anything we have to adjust here? maybe you can try to reproduce the situation with the docker and test it in your environment.

**Comment by freescout-helpdesk** [comment]
We ourselves have never seen such an issue when using docker installation. And as far as we can see there is no such issue mentioned in the Docker repo too: https://github.com/search?q=repo%3Atiredofit%2Fdocker-freescout+aborted&type=issues

Most likely the issue is related to your server or hosting. Try some other hosting.

**Comment by ebgtobi** [comment]
So for our hosting side we use VMware ESXi. What else we should use for our hosting side?

**Comment by zackkatz** [comment]
I've had this issue. Often it's the `storage:link` item below. Try the following:

### When things go wrong, I run

```bash
chown -R www-data:www-data /var/www/html/
```

```bash
php artisan storage:link
```

```bash
php artisan freescout:module-install {name of module}
```

```bash
php artisan view:clear
php artisan cache:clear
php artisan route:clear
php artisan config:clear
php artisan clear
```

**Comment by freescout-helpdesk** [comment]
> So for our hosting side we use VMware ESXi. What else we should use for our hosting side?

We've tested it on DigitalOcean - it works fine.

**Comment by ebgtobi** [comment]
> I've had this issue. Often it's the `storage:link` item below. Try the following:
> 
> ### When things go wrong, I run
> ```shell
> chown -R www-data:www-data /var/www/html/
> ```
> 
> ```shell
> php artisan storage:link
> ```
> 
> ```shell
> php artisan freescout:module-install {alias of module}
> ```
> 
> ```shell
> php artisan view:clear
> php artisan cache:clear
> php artisan route:clear
> php artisan config:clear
> php artisan clear
> ```

How should I apply that to my system? I am not that deep into Linux

**Comment by ebgtobi** [comment]
> > So for our hosting side we use VMware ESXi. What else we should use for our hosting side?
> 
> We've tested it on DigitalOcean - it works fine.

We use a normal ESXI cluster with normal settings. There we simply set up a Linux Ubuntu 22.04.2 VM and gave it the necessary resources. With other Linux Ubuntu VMs we don't have this problem, but with this one for Freescout we do for whatever reason.

**Comment by freescout-helpdesk** [comment]
We can't help here. The issue need to be investigated by admin on your server.
