### ISSUE TITLE
Addon Timing, choose to only start timing when click play

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#3114]
Hi guys,

The timing addon is great. 
Though in our case we want it only for certain tickets. 
Not all tickets and now they start running time whenever we open them. 
I use the option only when added to a user but that is not specific enough yet. 

So Is it not an idea to have the option to only start time when I click play?
Now the whole time I open ticket and reply. The time keeps on running for days untill I close it. 
Then I have the option to cancel to track the time if I did not even want it to start running at all. 

Or is this possible and am I missing a setting?

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
