### ISSUE TITLE
API/Webhooks Module Feature Request - search by customer email

### ISSUE THREAD

**Issue by adamsewell** [freescout-helpdesk/freescout#3115]
PHP version: 8.2.7
FreeScout version: 1.8.80
API and Webhooks: 1.0.58

When making an API call, the default functionality does not allow for searching based on partial email addresses such as the domain. So for example, using 'customerEmail' to search for a specific email works just fine but if I try to search for the the customerEmail domain, it returns nothing. 

Making one change seems to work to add this functionality. 

In `Modules/ApiWebhooks/Http/Controllers/ApiController.php` on line 199 if you change the following line from

```
$query->where('customer_email', $request->customerEmail);
```
to
```
$query->where('customer_email', 'like', '%'.$request->customerEmail.'%');
```

it adds the functionality without much fuss. Apologies if this is not the right place to place this but I couldn't find an appropriate place to submit this.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by adamsewell** [comment]
Done.
