### ISSUE TITLE
CustomFields with Single Line Tags not Saved

### ISSUE THREAD

**Issue by satsangswami** [freescout-helpdesk/freescout#3116]
CustomFields Module Bug

/Modules/CustomFields/Entities/CustomField.php
Line: 146
Replace
`$field->custom_field_id $custom_field_id;`
to
`$field->custom_field_id = str_replace("[","",$custom_field_id);`

This will make it work correctly.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Can you write a step-by-step instruction on how to reproduce it.
