### ISSUE TITLE
Can be installed via F-Droid AppStore

### ISSUE THREAD

**Issue by Lukas2112** [freescout-helpdesk/freescout#3117]
I would like to suggest that the mobile app can also be obtained via the F-Droid App Store (https://f-droid.org).

**Comment by freescout-helpdesk** [comment]
You don't have access to Google Play?

**Comment by asandikci** [comment]
I agree. F-droid is an appstore for foss applications and freescout app should be on f-droid in my opinion. And yes, I don't have access to Google Play.
