### ISSUE TITLE
Fetching failed

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3118]
Freescout 1.8.80 clean installed on ubuntu22.04
I change two parameters from default.
`APP_NEW_FETCHING_LIBRARY=true in .env`
`memory_limit=512MB in php.ini`

I set freescout and Thunderbird for same email account.
and I noticed number of mails that freescout fetched is differ from Thunderbird.
I found record in my log.
[2023-06-19 15:59:15] Error: Attempt to read property "mail" on string; File: /var/www/freescout/app/Console/Commands/FetchEmails.php (1261)
I will send EML file of this mail.please check it.

**Comment by totake0224** [comment]
I check this but still error occurred at 
[2023-06-19 16:43:11] Error: Attempt to read property "mail" on string; File: /var/www/freescout/app/Console/Commands/FetchEmails.php (1353)

**Comment by freescout-helpdesk** [comment]
We've checked EML file in Docker and it works fine. The issue need to be investigated on your server.

**Comment by totake0224** [comment]
My freescout on Docker (tiredofit/freescout) v1.8.80 couldn't fetch that mail.
Error: Attempt to read property "mail" on string; File: /www/html/app/Console/Commands/FetchEmails.php (1261) 
Which version of freescout your Docker environment is.?

**Comment by totake0224** [comment]
I could get that mail without APP_NEW_FETCHING_LIBRARY=true.
Is your Docker set that parameter?

**Comment by freescout-helpdesk** [comment]
> replace iconv to mb_convert_encoding

Where?

**Comment by freescout-helpdesk** [comment]
We don't have capacity to deal with your issues with Japanese texts, try to find someone who can fix them and sent pull request.
