### ISSUE TITLE
Error occurred. Please check your internet connection and try again.

### ISSUE THREAD

**Issue by maisen20** [freescout-helpdesk/freescout#3119]
When I want to activate a module I programmed, I always get the error message:
`Error occurred. Please check your internet connection and try again.`

If I delete the cache of Freescout and then reload the page, the module is then marked as "activated". In the logs I have no errors but there is clearly a problem.

When activating or deactivating my modules there is this problem with the xhr request from /modules/ajax. It also doesn't really load but immediately aborts the xhr request. Of course my internet connection works and the query seems to come to the server, because the module in the MySQL table then also changes the status (activated/deactivated). And there are no symlinks in the path /public/modules/modulename/, because the activation probably just does not work/finish correctly.

PHP version: 
PHP 8.1.18

FreeScout version: 
1.8.80

**Comment by maisen20** [comment]
The behavior is really very confusing. When I open /app-settings all is working, but as soon as I click on save, which sends a post request to /app-settings, it doesn't load the page and I get an error that the connection was unexpectedly closed. There are no errors in the logs.

**Comment by maisen20** [comment]
It seems that I have found the problem. The PHP extension xdebug seems to cause the problem. After disabling the extension on my Docker Compose (;zend_extension=xdebug) it seems to work now.

Maybe other users have this problem too and my post here is not completely useless 😆.

**Comment by SuneebGitHub** [comment]
I have same issuee please help:

when i install the module and paste the lisences key and then i press the insatll its showing 
this error: Error occurred. Please check your internet connection and try again. free scout install module

how to resolved the same issue on my php localhost and my php version is 8.0 and composer version is 2.6 and my freescout version is [1.8.153] i have provide all information

**Comment by freescout-help** [comment]
> If you get any errors, check app logs in Manage » Logs » App Logs.

https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#11-troubleshooting
