### ISSUE TITLE
Random user assignment for tickets

### ISSUE THREAD

**Issue by Warrennoa** [freescout-helpdesk/freescout#3121]
Hello,

I added the workflow module so I could have a "round robin" system where each ticket is assigned randomly to different agents. As far as I can tell that cannot happen. Am I wrong? I'd love to be able to add this. I used this prior with Zendesk and would love to keep using it

**Comment by aalvarezesc** [comment]
Tengo el mismo detalle y no encontre la configuracion. Espero puedan agrearla pronto.

**Comment by avenjamin** [comment]
> Tengo el mismo detalle y no encontre la configuracion. Espero puedan agrearla pronto.
"I have the same detail and I didn't find the configuration. I hope you can add it soon."

**Comment by avenjamin** [comment]
@freescout-helpdesk I'd be happy to look at implementing this - seems fairly simple.
What's the best way to submit a PR on a Module?
Do you have a private repo you can add me to?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by corsacca** [comment]
Hey @freescout-helpdesk. I'd love to know if this feature was developed.
