### ISSUE TITLE
ISO-2022-JP mail body garbled

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3122]
I found ISO-2022-JP encoded mail that contain certain characters garbled.
That characters defined as platform dependent characters in ISO-2022-JP but exists same character in UTF8.
so many of ISO-2022-JP decoder can assign it to appropriate UTF8 character code.
it's regretful that former Microsoft Office Outlook send mail in ISO-2022-JP.
I send EML file to support@freescout.net.

**Comment by totake0224** [comment]
it may also cause fetch error when platform dependent characters in sender name.

**Comment by freescout-helpdesk** [comment]
We can't fully fix it - the problem is in operating system used in the Docker container. The only solution for you is to re-install the FreeScout without using a Docker (on Ubuntu, Debian, etc).

**Comment by totake0224** [comment]
my testing environment is ubuntu22.04 and Docker(tiredofit/freescout) both.
I got same result from both( when installed 1.8.80.
I didn't test Docker and origin/master yet.
should I test that environment?

**Comment by totake0224** [comment]
this issue is derived from Japanese Text is still garbled. #3089

**Comment by totake0224** [comment]
I think I found a solution.
replace iconv to mb_convert_encoding fix many of this problem.
I also add
```
if($from =='ISO-2022-JP' ||$from =='iso-2022-jp'){
   $from='iso-2022-jp-ms';
}
```
before mb_convert_encoding.
this solve fetch fail when ISO-2022-JP platform dependent characters in sender name.

iconv coudn't convert iso-2022-jp platform dependent characters.
but mb_convert_encoding could treat these as iso-2022-jp-ms.

please use mb_convert_encoding instead of iconv.

**Comment by totake0224** [comment]
I think rest of this problem is caused by iconv_mime_decode.
but this function is not easy to replase for me.

**Comment by freescout-helpdesk** [comment]
> replace iconv to mb_convert_encoding fix many of this problem.

Where?

**Comment by totake0224** [comment]
Where.
it's difficult to explain.
just search iconv. and I found iconv is evaluate before  mb_convert_encoding like
```
if(function_exists('iconv')){
    iconv
}else if(function_exists('mb_convert_encoding'){
   mb_convert_encodhing
}
```
so, I delete former part of if like

```
if(function_exists('mb_convert_encoding'){
   mb_convert_encodhing
}
```
I'm sure my current environment has php-mbstring.

**Comment by freescout-helpdesk** [comment]
We are changing now `iso-2022-jp` encoding to `iso-2022-jp-ms` 
https://github.com/freescout-helpdesk/freescout/commit/e90c1838f1ea95df9ac0590b993f8e985f4f1db6

It fixed the body in one of examples you've sent. But to deal with further your issues with Japanese texts we don't have capacity, try to find someone who can fix them and sent pull request.
