### ISSUE TITLE
sender name garbled after commit  Fix decoding sender name in iso-2022-jp encoding - closes #3089

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3123]
I experienced some mail that contain iso-2022-jp platform dependent character in it's sender garbled at origin/master and NEW_FETCHING_LIBRARY=false. 
so I comment out 
```
if (\Str::startsWith($text, '=?iso-2022-jp?')) {
            return [(object)[
                "charset" => 'iso-2022-jp',
                "text"    => \MailHelper::decodeSubject($text)
            ]];
        }
```
from [overrides/webklex/php-imap/src/Header.php](https://github.com/freescout-helpdesk/freescout/commit/88932bfc67f8b5cd80f6dc6283b9349ec138640b#diff-181d59ea4a4ebc77a18ce2ba63919ae278460d5f64f1a897ee738bfb535aa01e)
and I got sender name correctly.
I think something wrong with this commits.
sorry I didn't what is it yet.

**Comment by freescout-helpdesk** [comment]
We don't have capacity to deal with your issues with Japanese texts, try to find someone who can fix them and sent pull request.

**Comment by totake0224** [comment]
this is bug report. so please don't close this issue, or please move this issue into bug list.
