### ISSUE TITLE
couldn't display iso-2022-jp platform dependent character in mail subject and attachment filename.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3124]
Sorry for many issue about Japanese encoding specific problem.
I'm using origin/master  88932bfc67f8b5cd80f6dc6283b9349ec138640b
and NEW_FETCHING_LIBRARY=false. 
iso-2022-jp platform dependent character displayed as ? in mail subject and attachment filename.
I think this two problem is caused by decoding process of header.
so I put these two as one issue.

**Comment by freescout-helpdesk** [comment]
We don't have capacity to deal with your issues with Japanese texts, try to find someone who can fix them and sent pull request.

**Comment by totake0224** [comment]
this is bug report. so please don't close this issue, or please move this issue into bug list.
