### ISSUE TITLE
Is it possible to get time spent from time tracking module sent out with API integration module?

### ISSUE THREAD

**Issue by oledmansfeld** [freescout-helpdesk/freescout#3125]
On behalf of my colleagues who are so tired and sad about registering time in old and tedious systems - we have now seen the light with Freescout Time tracking.

We would absolutly love if this time spent information could be attached the webhooks on convo.statusChanged so we can integrate our billing system and use the time registered in FS.

KInd regards Ole

**Comment by freescout-helpdesk** [comment]
You can retrieve it via API: https://api-docs.freescout.net/#list-conversation-timelogs
