### ISSUE TITLE
Possible to resend a bunch of emails with database tweak?

### ISSUE THREAD

**Issue by catbadger** [freescout-helpdesk/freescout#3126]
Our DMARC record was working and suddenly began failing. we have dropped a TON of emails that went out to mailgun. So freescout saw them as accepted to send, but they didn't go out. can I requeue a bunch of them by changing Thread::send_status? If so, what value should I set?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no a quick solution for this. Changing `send_status` in **threads** table won't work.
