### ISSUE TITLE
Start Ticket Number from a higher value?

### ISSUE THREAD

**Issue by DaveWBDP** [freescout-helpdesk/freescout#3127]
Hello all.

Just installed FreeScout, and so glad I didn't end up paying for HelpScout. 

I have a quick question... Is there a way to start the ticketing numbering at anything other than 1? The current helpdesk system I am using has user tickets starting at 102 (that is, I've had 101 previous tickets). To try to not confuse my customers, I'd like to set the first ticket that gets generated to something above 101. Is this possible?

Many thanks
Dave

PHP version: 7.4
FreeScout version: 1.8.80

**Comment by avenjamin** [comment]
We did this and haven't run into any issues.

First make sure in Manage > General > Conversation Number is set to `Equal to conversation ID`
Next, you'll need to modify the auto increment value on the `conversations` table in your MySQL database.

`ALTER TABLE conversations AUTO_INCREMENT = 102;`

Make sure you push a few test tickets through afterwards to make sure everything is appearing as expected.

**Comment by freescout-helpdesk** [comment]
Manage >> Settings

![2023-06-21_09-15-11](https://github.com/freescout-helpdesk/freescout/assets/40499291/0498c3b6-26e0-4f23-b4e0-877c8a819efc)

**Comment by avenjamin** [comment]
Or use the above 😄 I think that was added sometime after I'd already done it - forgot it was now possible via Settings.

**Comment by DaveWBDP** [comment]
Thanks, perfect, that works a treat!!

**Comment by W1BTR** [comment]
I dont have the "General" tab... am I crazy?
![image](https://github.com/user-attachments/assets/e4edc068-5cef-4c83-aa80-31fa551ad8ff)

**Comment by freescout-help** [comment]
![2024-10-03_08-12-28](https://github.com/user-attachments/assets/23e6e1bd-f1fb-4673-a5f4-f0cd1a316ae7)
