### ISSUE TITLE
Emails in gmail inbox being marked as read before any action performed in freescout

### ISSUE THREAD

**Issue by BrianGilbert** [freescout-helpdesk/freescout#313]
All incoming emails are getting marged as read within the gmail inbox, if we mark them as unread then they get marked as read again. is there a way to stop this?

**Comment by freescout-helpdesk** [comment]
No. Mailbox connected to the FreeScout is supposed to be accessed via FreeScout only.

**Comment by zuzullo** [comment]
1 year later :) is there a fix on this?
It would be really nice to keep some consistence between server and FreeScout.
