### ISSUE TITLE
define preferred email

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3130]
Many customers have more than one email address, such as private1, private2, work and so on.
It would be very helpful to define one as the preferred one. Otherwise communication can be misdirected.

**Comment by ilyakonovalenko** [comment]
It seems the first email in the list is preferred? Is it not?

**Comment by mokkin** [comment]
Indeed you're right!
But even so, there should be a preferred/preselected one to prevent users sending to the incorrect one.

**Comment by freescout-helpdesk** [comment]
Yes, by default the first email is the default one.
