### ISSUE TITLE
not retrieved automatically

### ISSUE THREAD

**Issue by marcbroe** [freescout-helpdesk/freescout#3132]
Hello, I have the following problem. The e-mails from my "Imap" mailbox are not retrieved automatically. Connection etc. everything is correct and works. Sending is also no problem. But if I click on e-mails manually under "System" > Tools, they are retrieved. I can't find any hints or errors in the logs either. Thanks in advance

PHP version: 8.0
FreeScout version: 1.8.81

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues
