### ISSUE TITLE
Who is this built by?

### ISSUE THREAD

**Issue by schengawegga** [freescout-helpdesk/freescout#3134]
Dear freescout-team,

as described on #161, the answer of this question is still missing.

Could you please provide more informations about the development-team and the recipients of the payment for several modules on your shop.

The reason for asking is the same as @mittkkoo https://github.com/freescout-helpdesk/freescout/issues/161#issuecomment-1262198138 is asking for.

It would be great to know, if there is any company or organization behind this project.
Or if its only a community driver project.

In both ways, it is always good to know, who has the lead of this project and where we send our money by buying freescout-modules.

I wrote an email to [support@freescout.net](mailto:support@freescout.net) but never got an answer.

Can you give us more informations, please?

Thank you

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#who-is-behind-the-project-is-there-a-list-of-developers-working-on-the-freescout

**Comment by schengawegga** [comment]
@freescout-helpdesk thank you.

But this are only two sentences about the the origin of this peace of software.

Can you provide a little bit more informations about the development structure, please?
