### ISSUE TITLE
IMAP Connection refused

### ISSUE THREAD

**Issue by mac-604** [freescout-helpdesk/freescout#3135]
Hello, I would like to set up a new mailbox. Username and password are correct. However, I cannot establish a connection via Freescout. I get the following error message

Error: imap_open(): Couldn't open stream {xxxx:993/imap/ssl}. Can't connect to xxxxx,993: Connection refused; File: /home/public_html/support/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching-issues
