### ISSUE TITLE
Install on laravel Vapor

### ISSUE THREAD

**Issue by chrismeats** [freescout-helpdesk/freescout#3137]
Would there be any issue install/running freescout on laravel vapor which runs on Lambda?

taking a quick browse at the documentation the first few things that jump out at me are:
1. Storage
2. Cron jobs, could these be setup as scheduled tasks inside of laravel instead of a cron?

**Comment by freescout-helpdesk** [comment]
We have not tried running FreeScout on Laravel Vapor yet. If you'll manage please let us know the result.

**Comment by chrismeats** [comment]
@freescout-helpdesk Are the cron jobs required? or can those items be setup as a scheduled task?
Is there any local storage required by free scout?

**Comment by freescout-helpdesk** [comment]
> be setup as a scheduled task
> local storage

It's hard to tell what you mean under these things. We'd recommend you start deploying FreeScout and see yourself if it works on Vapor or not.
