### ISSUE TITLE
Live chat documentation

### ISSUE THREAD

**Issue by msgok** [freescout-helpdesk/freescout#3139]
I would like to ask you for developer documentation for your Livechat add-on for Freescout. 

Specifically, we are looking for a way to programmatically open a widget and pre-populate a message from a customer (also if it is possible to pre-populate a custom variable/field).

We are working on implementing our service into Freescout for your clients.

No one is responding to the FreeScout Support <support@freescout.net> email, so we are trying this way.

**Comment by freescout-helpdesk** [comment]
See https://freescout.net/module/chat/

**Comment by msgok** [comment]
I know this link. Unfortunately there is no information about the method or function I can call to open the widget or prefill the message.

**Comment by freescout-helpdesk** [comment]
There is no such features for now. Feel free to submit a feature request: https://freescout.net/request-feature/
