### ISSUE TITLE
Follow-up Satisfaction rating email

### ISSUE THREAD

**Issue by Warrennoa** [freescout-helpdesk/freescout#3140]
Is there a way to make customer satisfaction ratings a follow-up email instead of an email signature?

So far we have tried

1. Saved Replies
2. Manual/Automated workflows

 Variables like {%ratings.great%} etc do not work as a saved reply or as a "email a customer" workflow, Either it will open a 404 not found page, or it will be a broken link.  

We'd really like to be able to make a follow-up email as we find the responses are more accurate and honest vs. people rating their ticket when they're mad midway through

**Comment by greggblazer** [comment]
Great point and idea. Following

**Comment by Warrennoa** [comment]
Looking more into it, I think a possible solution would be making the satisfaction rating a chooseable/custom signature or if we could assign the rating to specific users, and allow us to do workflows as users. 

So either we do a workflow and choose the correct signature that has the survey on it

or we have a workflow where user with sat. ratings enabled emails the ticket

**Comment by freescout-helpdesk** [comment]
> "email a customer" workflow, Either it will open a 404 not found page, or it will be a broken link.

It works fine on our end. You'll need to figure out on your FreeScout instance why whose links do not work.

**Comment by Warrennoa** [comment]
> Owner

Okay, can I confirm I am doing this right? Is there a tutorial?

Right now I am copying the code found in the default template:

<br>
How would you rate my reply?
<br>
<a href="{%ratings.great%}" style="color:#50bc1c;">Great</a> &nbsp;&nbsp; <a href="{%ratings.okay%}" style="color:#555555;">Okay</a> &nbsp;&nbsp; <a href="{%ratings.bad%}" style="color:#f10000;">Not Good</a><br>

Then pasting it in both a saved reply as well as a manual workflow of "send customer an email"  and a different workflow "reply to conversation"   When I try to click on those links through Gmail or Outlook nothing happens

**Comment by freescout-helpdesk** [comment]
It does not work this way.

Just enable Satisfaction Ratings for the mailbox, configure a Workflow containing an "Email the Customer" action and Satisfaction Rating will be added automatically to the email sent to the customer.

**Comment by Warrennoa** [comment]
Okay, is there a way to only have the Sat rating signature on the last email we send out/ only active when we change the status to closed? Or be able to choose different stat rating signatures like how the custom signature already works?


We'd like to either avoid having the rating signature normally or be able to have a much more eye catching one for our final email

**Comment by freescout-helpdesk** [comment]
No for now. Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
The feature has been added in Satisfaction Ratings Module v1.0.15: https://freescout.net/module/satisfaction-ratings/

![add](https://github.com/freescout-helpdesk/freescout/assets/40499291/7a47e601-f9da-4ec5-95ad-457b6d08fb5b)
