### ISSUE TITLE
Email Reply and User Invite Email functions not working

### ISSUE THREAD

**Issue by greggblazer** [freescout-helpdesk/freescout#3141]
* If you have some error the first thing you should do is to check "Manage » Logs » App Logs"! If there are any errors there - make sure to provide them in the issue.
* Have you read FAQ? https://github.com/freescout-helpdesk/freescout/wiki/FAQ
* If you have "Whoops something went wrong" error see: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
* Feature requests for modules should be posted here: https://freescout.net/request-feature/
* Docker questions should go here: https://github.com/tiredofit/docker-freescout/issues
* Create separate issues for different topics - no need to mix all your problems into one issue.
* Questions on issues with payments for modules should be sent by email: https://freescout.net/contact-us/
* Don't forget that you are not the project manager. Try to be humble, polite, friendly and positive. Otherwise your account may be banned.
* Mentioning how much you've spent on modules is the way to be banned.

Still here? Well clean this out and go ahead :)

PHP version: 
FreeScout version:

**Comment by greggblazer** [comment]
Hello. I look forward to using and upgrading to many of your awesome features. But out of the gate I am unable to get the Email Reply buttons to funtion or send ANY reply, or even Open a reply window. Button is dead.

And User Invite Email, to add to a mailbox has never sent out one email.

BUT, the Email settings are working and ALL the Send Test Emails fully worked and sent. As well as anyone sending a new email TO the support desk email all arrived in good order, BUT not one could be replied to.

Have reinstalled this in Cpanel multiple times, even with Hosting support help. Even bought a Softaculous license JUST to eliminate ANY use install error.. still same issues. And the VPS is fully updates to the latest Ngenix and PHP 8.2

At a road block and can not find any help menu that solves this.

Once this issue can be fixed would like to purchase many of your plugins, and I HOPE that those will install and work out of the box right away.

Thank you for your product, great work, and any help you can provide.

**Comment by freescout-helpdesk** [comment]
Check error in in the browser console.
