### ISSUE TITLE
Fetching failed at master branch

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3142]
at 2023/6/27 latest master branch on ubuntu 22.04
47ebc2f6945f741db5004d03141435310b60eecf
experienced error
Undefined property: Webklex\IMAP\Attachment::$config
when I did fetching mail from system/tools.
I did
composer install --ignore-platform-reqs
php artisan freescout:after-app-update
php artisan storage:link
and I set DB name and pass at .env

I had checked  2023/6/25 master branch
5732b8456fbb144842b7c6a99ff6e9caf2d030ab
and it's no problem at fetching.

I tried what is $config but I could not find out.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by totake0224** [comment]
Thank you.
I had confirmed $config error disappeared.
