### ISSUE TITLE
Switched to PHP 8.2.2

### ISSUE THREAD

**Issue by j0urna1ist** [freescout-helpdesk/freescout#3144]
PHP version: 8.2.2.
FreeScout version: 1.8.81
Switched to PHP 8.2.2. Mobile notifications stopped working. Now a permanent error (what to fix?):
Modules\MobileNotifications\Jobs\SendPushNotificationToUsers has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): Modules\\MobileNotifications\\Jobs\\SendPushNotificationToUsers has been attempted too many times or run too long. The job may have previously timed out. at /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:394)
[stacktrace]
#0 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 1)
#1 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#2 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#3 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#4 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#5 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#6 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#11 /home/k/kggn/lite.su/public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /home/k/kggn/lite.su/public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /home/k/kggn/lite.su/public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /home/k/kggn/lite.su/public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /home/k/kggn/lite.su/public_html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
"}

**Comment by freescout-helpdesk** [comment]
Anything in Manage > Logs > App Logs?

**Comment by j0urna1ist** [comment]
That's him.
Class "Modules\MobileNotifications\Providers\MobileNotificationsServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Modules\\MobileNotifications\\Providers\\MobileNotificationsServiceProvider\" not found at /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:635)
[stacktrace]
#0 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(582): Illuminate\\Foundation\\Application->resolveProvider('Modules\\\\MobileN...')
#1 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register('Modules\\\\MobileN...')
#2 /home/k/kggn/lite.su/public_html/vendor/nwidart/laravel-modules/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /home/k/kggn/lite.su/public_html/overrides/nwidart/laravel-modules/src/Module.php(279): Nwidart\\Modules\\Laravel\\Module->registerProviders()
#4 /home/k/kggn/lite.su/public_html/overrides/nwidart/laravel-modules/src/Repository.php(366): Nwidart\\Modules\\Module->register()
#5 /home/k/kggn/lite.su/public_html/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\Repository->register()
#6 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#7 /home/k/kggn/lite.su/public_html/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register(Object(Nwidart\\Modules\\Providers\\BootstrapServiceProvider))
#8 /home/k/kggn/lite.su/public_html/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#9 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#10 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#11 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /home/k/kggn/lite.su/public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#15 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Nwidart\\Modules\\LaravelModulesServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Nwidart\\Modules\\LaravelModulesServiceProvider), 22)
#17 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(774): array_walk(Array, Object(Closure))
#18 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /home/k/kggn/lite.su/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 /home/k/kggn/lite.su/public_html/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 {main}
"}

**Comment by j0urna1ist** [comment]
Declaration of GuzzleHttp\Psr7\Uri::withScheme($scheme) must be compatible with Psr\Http\Message\UriInterface::withScheme(string $scheme) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Declaration of GuzzleHttp\\Psr7\\Uri::withScheme($scheme) must be compatible with Psr\\Http\\Message\\UriInterface::withScheme(string $scheme) at /home/k/kggn/lite.su/public_html/vendor/guzzlehttp/psr7/src/Uri.php:13)
[stacktrace]
#0 {main}
"}

**Comment by freescout-helpdesk** [comment]
It looks like broken installation. Try to re-update the FreeScout using manual method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by j0urna1ist** [comment]
It didn't help.
When clicked, DB migration:
Incorrect PHP version (7.1+ is required): 8.2.2
Previously there was a version of PHP 7.1, now it has been updated to 8.2.2.
After the update, notifications stopped working

**Comment by j0urna1ist** [comment]
The problem has been solved:
In the crontab there was a line with the php 7.1 page
replaced:
//usr/local/bin/php 8.2 ~/lite.su/public_html/artisan schedule:run >> /dev/null 2>&1
