### ISSUE TITLE
multiline custom field - use in signature does not respect newlines

### ISSUE THREAD

**Issue by cfoellmann** [freescout-helpdesk/freescout#3146]
Hi,
I did add a "multiline custom field" to users called `Signature + name`. 
That way a user should set a custom mail signature partially.

The user saves a multi line value.
When using the variable in the signature setting the whole field is in one line. The newlines seem to be escaped before output.

Seems like a bug to me.

PHP version: docker image
FreeScout version: docker image - current

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
