### ISSUE TITLE
Licenses in the server's temporary domain

### ISSUE THREAD

**Issue by bsk-eduardo-oliveira** [freescout-helpdesk/freescout#3147]
Hello!

I bought two FreeScout modules and activated the licenses in the server's temporary domain, but after correct pointing to (app.domain.com.br) the modules were disabled and I can no longer apply them to the correct domain.
I also don't have access to the 'Delete' functionality in the FreeScout admin console.
How do I assign the licenses to the correct domain in this case?

Thanks!

**Comment by freescout-helpdesk** [comment]
https://freescout.net/modules-faq/#deactivate-license

**Comment by bsk-eduardo-oliveira** [comment]
I already read this documentation!
The problem is that the server was deleted and I no longer have access to the application. We are rebuilding a new server at Vultr and I want to move the licenses to this new server.

**Comment by freescout-helpdesk** [comment]
_"The license can be deactivated on ANY FREESCOUT INSTANCE – old or new or even on https://demo.freescout.net/ (just register there)."_ (https://freescout.net/modules-faq/#deactivate-license)
