### ISSUE TITLE
Reply on one element in a ticket

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#3148]
Hello all,

is there a possibility in FreeScout to only reply to a ticket post in a ticket?

Example: If I have a ticket that concerns several customers, I also receive several replies from the different customers in this ticket. A typical example is a collective ticket. If I now want to answer only one customer's answer in this collective ticket, I need a possibility to answer a single item in the series of this ticket.

Does such a possibility exist? Possibly through a module?

Many thanks in advance,
With best regards
Lukas

**Comment by freescout-helpdesk** [comment]
You can use one of these:

![2023-06-29_09-19-15](https://github.com/freescout-helpdesk/freescout/assets/40499291/fea391ea-716d-4eb9-b996-e5dab52dd96e)

**Comment by lucollab** [comment]
Okay, thanks! I must have overlooked that..
