### ISSUE TITLE
pagination error on mailbox Assigned tab

### ISSUE THREAD

**Issue by nczz** [freescout-helpdesk/freescout#315]
When I click the Next Page on Assigned tab the results are not showing with correct emails. All emails mixed together.

I've updated the newest version v1.3.5. Please check it. Thank you.

**Comment by freescout-helpdesk** [comment]
We can't reprodue the issue. Can you provide a screenshot?

**Comment by nczz** [comment]
@freescout-helpdesk Thank you for quick reply. Here is the screenshot > https://cl.ly/47ac83d460cd

**Comment by freescout-helpdesk** [comment]
Thanks. We will try to fix.
