### ISSUE TITLE
How to import translation zip file into Itm_translations table

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3151]
PHP version: 8.2.6
FreeScout version: 1.8.81 (origin/master)

I had translated several modules. and publish them. and download it as a zip file.
but after I did git pull from origin/master. translation window doesn't show my translation.
Modules still show my translation but translation window doesn't show. so I could not modify my translation.

I think unzip downloaded zip file into resources/lang will works for user menu. but translation window use DB Itm_translations table.
I want to know how to import zip file into that table.

Someone Please tell how to import downloaded zip file.

**Comment by freescout-helpdesk** [comment]
Click "Import Translations" button in Manage > Translate.

**Comment by totake0224** [comment]
I did. it's shows "importing... it may take several minutes"
after that translation windows shows groups. but when I choose one of groups that I did translate. 
it shows all the word  Empty.

**Comment by totake0224** [comment]
I did php artisan translations:import after "Remove non-published".
but same result.
I'm using nginx reverse proxy. 
Is it make difference?

**Comment by freescout-helpdesk** [comment]
Make sure you actually have your translations in `/Resources/lang` folders in Modules. If they are there - try to figure out why they are not imported.

**Comment by totake0224** [comment]
Hello. I'm sure I have tranlated json file in /resources/lang folder.
for example there is 
module.teams.ja.json
and it contains my translations.
Please give me some hint so what I could figure the problem out.
![スクリーンショット 2023-07-04 164752](https://github.com/freescout-helpdesk/freescout/assets/42058913/d9b09c3a-6d12-4050-b508-48f022ebc536)
