### ISSUE TITLE
Exception due to imap_utf8_to_mutf7 missing on debian php 8.2 builds

### ISSUE THREAD

**Issue by OttoWinter** [freescout-helpdesk/freescout#3152]
PHP version: 8.2.7
FreeScout version: 1.8.81

`imap_utf8_to_mutf7` is missing in debian (bookworm) builds of php8.2. 

For those php8.2-imap builds the following line throws an exception (Introduced here: 
https://github.com/freescout-helpdesk/freescout/commit/4141758ee48f3c389423492c04a951868b8facb1 ):

https://github.com/freescout-helpdesk/freescout/blob/24dc14c44ad74da8a8b89ddfc2369380e4a55b34/overrides/webklex/laravel-imap/src/IMAP/Client.php#L266

```
production.ERROR: Call to undefined function Webklex\IMAP\imap_utf8_to_mutf7() 
{
  "exception": "[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): 
  Call to undefined function Webklex\\IMAP\\imap_utf8_to_mutf7() at 
  /var/www/freescout/overrides/webklex/laravel-imap/src/IMAP/Client.php:266)
```

The [PHP manual for this function](https://www.php.net/manual/en/function.imap-utf8-to-mutf7.php) states in a note that "This function is only available, if libcclient exports utf8_to_mutf7().".

I assume that is the reason the function is not available.

You can check this function is not available via these docker commands:

```
$ docker run -it --rm debian:bookworm bash
# apt update
# apt install php8.2 php8.2-imap
# php8.2 -a
php > imap_utf8_to_mutf7('asdf');
PHP Warning:  Uncaught Error: Call to undefined function imap_utf8_to_mutf7() in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 
```

(for debian buster & bullseye the function is available).

Perhaps an alternative code path can be introduced to make freescout compatible with debian php8.2 builds?

Thanks for looking into this :)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
