### ISSUE TITLE
Freescout use in Iframe on extern Server without https  

### ISSUE THREAD

**Issue by gplast1981** [freescout-helpdesk/freescout#3153]
I use Freescout on Ubuntu NGINX Server  
FreeScout version:  1.8.82

I use freescout on a ubuntu nginx server without https but only accessible in the network under http, everything works fine.

Our intranet runs on a Xampp server in the network with http and wanted to integrate Freescout there via an iframe, but the login is not possible. in firefox it worked at first now after a few days it doesn't work anymore, what do I have to do to be able to use freescout in the iframe without https

**Comment by freescout-helpdesk** [comment]
We can't help here. Try to figure it out yourself.
