### ISSUE TITLE
Please be aware, attachments cannot be retrieved after upgrading to 1.8.82!

### ISSUE THREAD

**Issue by RichardDBrown** [freescout-helpdesk/freescout#3154]
After the upgrade, your IMAP was unable to retrieve email attachments, and currently, the specific error cannot be ruled out. I can only revert to the previous version to solve this problem. Please be careful when upgrading. Meanwhile, this update was also a failure, such an error should not have occurred.

**Comment by freescout-helpdesk** [comment]
Are you using a modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY` parameter in .env file?

**Comment by RichardDBrown** [comment]
> Are you using a modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY` parameter in .env file?

I'm using the GMAIL Business Plan, and there is no APP_NEW_FETCHING_LIBRARY in the .env file. We also didn't receive any notification or setup method, could you please provide more specifics? Thank you.

**Comment by freescout-helpdesk** [comment]
No need to setup it. Could you please send a sample email with non-retrieved attachments to support@freescout.net
