### ISSUE TITLE
Receiving thousands of UNDELIVERED/BOUNCE messages

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#3156]
So this issue, the best that I can figure... when a User is supposed to get notified of a New Conversation by email, but the email is bounced/undelivered, then Freescout repeatedly tries to notify the user by sending this email over and over again. 

How to reproduce:
For the user, the THERE IS A NEW CONVERSATION - EMAIL is CHECKED/ON
When a new convesation comes into that mailbox, Freescout tries to notify them that they have a new conversation.
Our email system has hit a limit and EXCEEDED MAX DEFERES AND FAILURES PER HOUR.

Temporary work around to stop this:
I have to disable fetching of emails by Freescout for about 24 hours to let the mail server reset.

Here is attached pic of a couple screens..

![firefox_2023-07-01_08-19-11](https://github.com/freescout-helpdesk/freescout/assets/19673842/b286e001-5473-4902-baf8-b46694186903)

![firefox_2023-07-01_08-29-22](https://github.com/freescout-helpdesk/freescout/assets/19673842/5cc2e067-c08f-4dda-b4d5-c186e59f34ff)

I am really not 100% sure what is happening. The above is just my guess.
It happened about a month ago as well.

**Comment by freescout-helpdesk** [comment]
Go to "Manage > Logs > Send Error" and send us error messages you see there.

**Comment by jshrek** [comment]
There is no specific Send Error option...

![logs](https://github.com/freescout-helpdesk/freescout/assets/19673842/f0a1b790-5b84-467c-a09d-833119c61c73)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

Now FreeScout will not try to resend email notifications on received bounce emails.

**Comment by jshrek** [comment]
Thank you!
