### ISSUE TITLE
ChatGPT & AI plugin

### ISSUE THREAD

**Issue by intered** [freescout-helpdesk/freescout#3157]
The forum link on the website redirected me to github, though shis is not an issue but rather a request.

I would like to request a plugin for ChatGPT, that would answer the mail at the click of a button. Think that would be very helpful for a lot of us

**Comment by medoix** [comment]
There is an open source one being worked on https://github.com/code-debug228/HostetskiGPT

**Comment by freescout-helpdesk** [comment]
Suggest this feature to https://github.com/code-debug228/HostetskiGPT

**Comment by dsmagghe** [comment]
actually this one isn't working anymore and is not maintained...
