### ISSUE TITLE
PHP 7.1 issue on Modules and system page 

### ISSUE THREAD

**Issue by pinalgirkar** [freescout-helpdesk/freescout#3158]
Hello,

I was in the process of manual installation of Freescout 1.8.83(https://freescout.net/download/) on Centos 7 with PHP 7.1, MYSQL 5.5, Apache 2.2. However after the successful installation when I login and try to visit the Manage>Modules and Manage>system it shows the following error

![error](https://github.com/freescout-helpdesk/freescout/assets/106646072/41eafa1f-bb4e-4218-a8d3-96eb76de9532)

On visiting Manage>Logs>AppLogs I have found this error log file [laravel-2023-07-03.log](https://github.com/freescout-helpdesk/freescout/files/11936031/laravel-2023-07-03.log).
 
When I try to install on Centos 7 with PHP 7.2, MYSQL 5.5, Apache 2.2, it loads the Manage>Modules and Manage>System without any error. I have checked the System requirements here: https://github.com/freescout-helpdesk/freescout#requirements. If the PHP requirements are changed if so please update the system requirements and even the requirements checks during the installation is successful for the PHP 7.1.

Could you please look over the issue.

PHP version: 7.1
FreeScout version: 1.8.83

**Comment by freescout-helpdesk** [comment]
Check errors in /storage/logs

**Comment by pinalgirkar** [comment]
the same error logs are creating in the /storage/logs checked that as well

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
