### ISSUE TITLE
HTML entities appear in plaintext email

### ISSUE THREAD

**Issue by linozen** [freescout-helpdesk/freescout#3159]
Hi there, 

it seems that HTML entities, e.g. `&gt;` are shown in plaintext email instead of the actual `>`. 

PHP version: 7.4.33
FreeScout version: 1.8.83

**Comment by freescout-helpdesk** [comment]
Can you send a screenshot and how it looks in the mail source code.

**Comment by linozen** [comment]
Hi @freescout-helpdesk, 

yes sure. Here is the plaintext part of an email where characters appear as HTML entities.

```plaintext
--_=_swift_1688387240_d30006d21a50bd0e216a43f69bff6b3b_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

-- Please reply above this line --

Received a new conversation #484
=

-----------------------------------------------------------
## Linus S=
ehn started the conversation, on Jul 3 @ 14:27 (Europe/Paris):
test
-- =

Linus Sehn &gt;&gt;&gt; System Hacker @ Free Software Foundation Europe=

matrix: @linus:fsfe.org | git@fsfe: https://git.fsfe.org/linus
Become =
a supporter of software freedom &gt; https://fsfe.org/join

Attached:=

1) OpenPGP_signature [https://helpdesk.fsfe.org/storage/attachment/9/8/1=
/OpenPGP_signature?id=3D297&amp;token=3De4b58ca3ee45ede9bce63d39c6d442ee]=


Conversation URL: https://helpdesk.fsfe.org/conversation/484?folder_i=
d=3D332

--
Reply with any of these commands to update the conversati=
on:
https://freescout.net/module/email-commands/

-------------------=
----------------------------------------

General (Admin):
https://he=
lpdesk.fsfe.org/mailbox/5

--_=_swift_1688387240_d30006d21a50bd0e216a43f69bff6b3b_=_

**Comment by freescout-helpdesk** [comment]
> Linus Sehn &gt;&gt;&gt; System Hacker

Is it a part of the signature? Can you send a signature HTML.

**Comment by linozen** [comment]
> > Linus Sehn >>> System Hacker
> 
> Is it a part of the signature? Can you send a signature HTML.

No, it's not part of a FreeScout signature in this case. It's just a ticket I created by sending an email with my usual signature that I have set up in my Thunderbird. It is plaintext, i.e. no HTML.

I used it because it shows the problem. The HTML-version of the emails that FreeScout sends are fine by the way, only the plaintext version contains the written-out HTML entities.

**Comment by freescout-helpdesk** [comment]
Is it incoming email or email sent by support agent. Send an example to support@freescout.net

**Comment by linozen** [comment]
> Is it incoming email or email sent by support agent. 

The error appears in both the notifications sent to support agents and the emails sent to customers (of course only if they view the plaintext version)

> Send an example to [support@freescout.net](mailto:support@freescout.net)

Just did.

**Comment by freescout-helpdesk** [comment]
We've received the email, it contains only text/plain body and looks fine in our FreeScout.

![2023-07-04_11-31-52](https://github.com/freescout-helpdesk/freescout/assets/40499291/3cf75f8f-2549-4304-aa45-b5ddc027cd44)

**Comment by linozen** [comment]
> We've received the email, it contains only text/plain body and looks fine in our FreeScout.

Yes, FreeScout displays everything fine, it's about the plaintext part of the email generated by FreeScout (e.g. notificatino, auto-replies to customers) where the issue appears.

You could easily test this by adding some of the symbols to an auto-reply and then look at the plain-text part of the email generated by FreeScout that you get in response to creating a ticket.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
