### ISSUE TITLE
ReferenceError: viewMailboxInit is not defined

### ISSUE THREAD

**Issue by Meloman-zz** [freescout-helpdesk/freescout#316]
Hi,

I just installed freshscout on a 18.4 Ubuntu Server. Hte system si working and I installed with assistant. I created and configured IMAP mailbox and now I can't modify it anymore. All the configuration buttons are not responding (cog icons)

In the browser console, I get the following error : 
`ReferenceError: viewMailboxInit is not defined`
`<anonymous> https://mydoain.../mailbox/1/5:229`

**Comment by freescout-helpdesk** [comment]
You have problems with loading JS. Any messages in System --> Logs?

**Comment by Meloman-zz** [comment]
> You have problems with loading JS

Yes it looks like.

No error when I arrive at first page but topbar menu buttons like notifications or accoun are not working.

And what's strange is that in the Source code of the page, there is not any javascript call like <script src=..."> or <script> in Network panel of firebug, not any js loaded.

**Comment by freescout-helpdesk** [comment]
If you have problems with loading JavaScript, menu will not work, so you need to check logs on the server in `storage/logs` folder.

Most likely you have problems with permissions in some folder.

**Comment by Meloman-zz** [comment]
Ok, so in storage/logs I have 3 files : 
fetch-emails.log  laravel-2019-08-22.log  queue-jobs.log

by running ` tail -f laravel-2019-08-22.log` is getting the following :

[2019-08-22 15:11:44] production.ERROR: Error: File '/var/dmh/helpdesk/freescout/public/storage/js/vars.js' does not exist; File: /var/dmh/helpdesk/freescout/vendor/devfactory/minify/src/Providers/BaseProvider.php (124)

**Comment by freescout-helpdesk** [comment]
Your web server can not write into `/var/dmh/helpdesk/freescout/public/storage/js/`

**Comment by Meloman-zz** [comment]
ok.
storage in public/ folder doens't exist.

I made the `chmod -R 0777 public/` and even with this it is still not working! Strange !!!
Do I need to install again ?

**Comment by Meloman-zz** [comment]
I just installed php7.2-fpm, cleared bootstrap cache, removed .env and .installed files and after a new install, JS is now ok.

**Comment by SFFLAB** [comment]
I am encountering the same issue as @Meloman-zz did. I've tried the same steps as him and re-run the commands/performed the remedial steps at the end of the installation guide, but these don't fix the issue.

I'm struggling to understand what is causing this – are we mis-configuring permissions during installation, and breaking the install as a result? Once discovered, this issue persists even after letting any account add/edit/delete in the entire public directory, and per @Meloman-zz the directory in question doesn't exist.

**Comment by martinlegat** [comment]
In my case it was that on hosting I am using is by default disabled function symlink. After web installation there was no symlink from public/storage to storage/app/public and I had to create it manually from console.

**Comment by fulldecent** [comment]
This is the fix:

```sh
php /var/www/html/artisan storage:link
```

**Comment by zackkatz** [comment]
[This](https://github.com/freescout-helpdesk/freescout/issues/316#issuecomment-811262397) fixed it for me, too 👆 Thanks!
