### ISSUE TITLE
Attachment Not Received

### ISSUE THREAD

**Issue by tp-edjunior** [freescout-helpdesk/freescout#3160]
PHP version: 8.1
FreeScout version: 1.8.83

Hello guys.

I'm here because something weird is going on on my daily basis routine.

I have two mailboxes working on my account, so far so good, I've started to receive some tickets from the other mailbox agent user  informing that some attachments aren't in the message and when the requester is confronted, he did prove that the attachment was in the original mail message.

So the situation is, some attachments arrive fine and some not.

I'm attaching some screenshots.

Edit 1: I'm using Freescout on Interserver web hosting.

![Screenshot 2023-07-03 at 17 30 02](https://github.com/freescout-helpdesk/freescout/assets/138527765/83f62d44-5cbb-4b8e-86ed-dcf64e092f7d)
[Logs - FreeScout.pdf](https://github.com/freescout-helpdesk/freescout/files/11940812/Logs.-.FreeScout.pdf)
[Logs - FreeScout2.pdf](https://github.com/freescout-helpdesk/freescout/files/11940815/Logs.-.FreeScout2.pdf)

**Comment by freescout-helpdesk** [comment]
Make sure to update FreeScout to the latest version https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.83

**Comment by tp-edjunior** [comment]
I'm using the latest version but the issue still happening and it is random because sometimes the attachment came and sometimes not. Do I need to provide more logs or another information to help investigate this?

Thank you.

**Comment by freescout-helpdesk** [comment]
In you email to which the mailbox is connected.
