### ISSUE TITLE
How to STOP all failed notifications from re-sending? Causing mail server to shut down.

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#3161]
Had an issue on our mail server that caused multiple notification messages to fail, and now there are hundreds (thousands?) of failed attempts trying to resend, and this immediately causes the mail server to hit its MAX sends per hour and then shuts down sending and creates even more failed notifications that are trying to resend.

Is there a database command I can run to DELETE every notification that is trying to re-send so that it stops trying to resend them?

**Comment by freescout-helpdesk** [comment]
See Background Jobs in Manage > System

**Comment by freescout-helpdesk** [comment]
Go to "Manage > Logs > Send Error" and send us error messages you see there.

**Comment by jshrek** [comment]
It is related to this issue: https://github.com/freescout-helpdesk/freescout/issues/3156
