### ISSUE TITLE
Incorrect PHP version on tools.php update

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#3162]
I am trying to update (have blank system status screen, but everything else work) and have tried manual method and am now trying tools.php method but getting the following error that says I need PHP 7.1+ but have PHP 7.4 installed:

![firefox_2023-07-04_16-11-51](https://github.com/freescout-helpdesk/freescout/assets/19673842/e3686ab0-9c2d-4776-85c5-fc9b5e6e2da0)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

You can simply manually update the following line in /public/tools.php: https://github.com/freescout-helpdesk/freescout/commit/550e2d30cceceb87b45c89ba56ed09bffad05448

**Comment by jshrek** [comment]
Got it. Thanks

**Comment by jshrek** [comment]
Got it. Thanks
