### ISSUE TITLE
End-User Portal Module. Draft response is visible to the client

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#3163]
Hello!
Just found a bug in the End-User Portal Module. If I start typing a response to a ticket or leave this response in draft, then the text of my response becomes visible to the client on the list of tickets screen before it is published. The ticket itself is marked as answered. If the client opens a ticket in the End-User Portal Module, it will be empty

how to reproduce:
1. create a ticket in the End-User Portal
2. start typing the answer
3. look at the list of customer requests in the End-User Portal

version of End-User Portal Module 1.0.50

**Comment by freescout-helpdesk** [comment]
Fixed in End-User Portal Module v1.0.52
