### ISSUE TITLE
Messages Disappearing

### ISSUE THREAD

**Issue by tp-edjunior** [freescout-helpdesk/freescout#3164]
PHP version: 7.4.33
FreeScout version: 1.8.83

Hi guys,

I have another issue bothering the legal team.
The messages are disappearing from the thread.

This thread on the screenshot has 7 messages but when I open the thread it appears only 5 messages and this is happening with another threads on the account.

I really don't know what to do to track this.

Could you help me?

I have downgraded the php version to test and disabled some extensions like extended attachments and custom fields, but the issue persists.

Thank you.

![Screenshot 2023-07-05 at 09 39 21](https://github.com/freescout-helpdesk/freescout/assets/138527765/9cbc08fc-ab1d-49f7-a053-8f7ce91e4263)

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules?
Do you have "missing" messages on your mail server?

**Comment by tp-edjunior** [comment]
Only official modules. Follow some attachments to help tracking.

Where do I look for missing messages log?

Thank you.

![Screenshot 2023-07-05 at 10 32 49](https://github.com/freescout-helpdesk/freescout/assets/138527765/3145b82b-f4b5-4d4f-b13e-80b410f329a1)
![Screenshot 2023-07-05 at 10 32 41](https://github.com/freescout-helpdesk/freescout/assets/138527765/2a13a597-b473-4404-9139-977990cfe827)
![Screenshot 2023-07-05 at 10 32 28](https://github.com/freescout-helpdesk/freescout/assets/138527765/122dcd6f-a1e4-40be-a309-ef9026ec9744)
![Screenshot 2023-07-05 at 10 24 24](https://github.com/freescout-helpdesk/freescout/assets/138527765/44fcc030-cf6d-4b7f-9a10-b823af4d5bde)

**Comment by freescout-helpdesk** [comment]
> Where do I look for missing messages log?

In the email to which your mailbox is connected.

**Comment by freescout-helpdesk** [comment]
> What is missing from the thread is some replies that the agent did.

Have they been there after support agent submitted them as replies? Or they disappeared after some time?

**Comment by tp-edjunior** [comment]
The messages never been there.

**Comment by tp-edjunior** [comment]
Follow the errors. The app password on gmail is set and the mail account on freescout is using the app password.
![Screenshot 2023-07-05 at 17 58 53](https://github.com/freescout-helpdesk/freescout/assets/138527765/83d43b3d-5a98-4bf2-b23f-bd72d19870c9)
![Screenshot 2023-07-05 at 17 58 45](https://github.com/freescout-helpdesk/freescout/assets/138527765/7187dda9-0a37-46c1-81e2-7a3cf4e54772)

**Comment by freescout-helpdesk** [comment]
Errors from laravel-xxx.log files are needed.
Does this issue happen only with one mailbox and does not happen with the other one?

**Comment by tp-edjunior** [comment]
It happens only in one account.

![Screenshot 2023-07-05 at 17 58 45](https://github.com/freescout-helpdesk/freescout/assets/138527765/54a65e41-0975-4891-b079-d9466fefedbb)
![Screenshot 2023-07-05 at 17 58 53](https://github.com/freescout-helpdesk/freescout/assets/138527765/4a7b1c7c-ab4c-4f43-9694-506dea253a9d)
![Screenshot 2023-07-06 at 08 51 34](https://github.com/freescout-helpdesk/freescout/assets/138527765/3ef0fa54-f2c9-4a83-a9cd-56ae91dcef82)
![Screenshot 2023-07-06 at 08 51 43](https://github.com/freescout-helpdesk/freescout/assets/138527765/f9ba8cbc-f542-43ae-8a95-22381dc9eef0)
![Screenshot 2023-07-06 at 08 51 52](https://github.com/freescout-helpdesk/freescout/assets/138527765/399bac2d-f11c-4476-92b4-3b613f1d5ca9)
![Screenshot 2023-07-06 at 08 52 01](https://github.com/freescout-helpdesk/freescout/assets/138527765/f3337034-d643-43c9-8428-10716dd3efa2)
![Screenshot 2023-07-06 at 08 52 14](https://github.com/freescout-helpdesk/freescout/assets/138527765/543426f5-ccd5-4a0f-9601-98655d18a1f0)
![Screenshot 2023-07-06 at 08 52 30](https://github.com/freescout-helpdesk/freescout/assets/138527765/305029f0-8b02-4158-8f12-dfbbe04d8ed4)
![Screenshot 2023-07-06 at 08 53 00](https://github.com/freescout-helpdesk/freescout/assets/138527765/5f46df91-0d4d-465a-b4aa-7a2250e08d2e)
![Screenshot 2023-07-06 at 08 53 12](https://github.com/freescout-helpdesk/freescout/assets/138527765/f3cbd3f8-1507-48e9-8548-904ad156bb7c)

**Comment by freescout-helpdesk** [comment]
> It happens only in one account.

Under account you mean mailbox or FreeScout instance?

Nothing suspicious in logs. Are you using CloudFlare, Docker or Cloudron?

**Comment by freescout-helpdesk** [comment]
Try to disable all CloudFlare WAF rules (https://github.com/freescout-helpdesk/freescout/issues/2981)

**Comment by tp-edjunior** [comment]
Hi.

The WAF is already disabled.

**Comment by tp-edjunior** [comment]
Ok.

It happens only on one mailbox out of two.
One is completely normal replies and responses flows flawlessly but in the second mailbox only the responses flows normally, the agent replies disappear.

Thank you.

**Comment by freescout-helpdesk** [comment]
> in the second mailbox only the responses flows normally, the agent replies disappear.

All of agent replies disappear or just some of them?

**Comment by tp-edjunior** [comment]
There's only one visible, the first agent reply. All other replies vanish.

**Comment by freescout-helpdesk** [comment]
If you want you can provide an access to your FreeScout instance to investigate the issue (email at support@freescout.net)

**Comment by tp-edjunior** [comment]
I let you know how to do that on Interserver web hosting.

**Comment by tp-edjunior** [comment]
I'm talking with Interserver support to check how can we give access to you.

**Comment by tp-edjunior** [comment]
Hi.

I've sent the credentials through email to support@freescout.net

Thank you.

**Comment by freescout-helpdesk** [comment]
The issue could not be reproduced.
