### ISSUE TITLE
System status page is blank, but everything else works fine

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#3165]
This is a continuation of closed issue: https://github.com/freescout-helpdesk/freescout/issues/3042

So I noticed my /system/status screen was blank again.

I have manually updated to v1.8.83 and migrated db and cleared cache, but the page is still blank.
Everything else appears to be functioning fine.

I am then seeing the following error in the LOG right after I attempt to access the status page:

![log](https://github.com/freescout-helpdesk/freescout/assets/19673842/42d5b4fe-89af-4ffb-8dbf-ca0273d356aa)

It seems like memory allocation should be more than enough, but something is not quite right!
What else should I check?

**Comment by jshrek** [comment]
That is already expanded... stacktrace is hidden and shows up when I click the message.

There are several of the same error and all show the same thing when expanded.

![firefox_2023-07-07_08-56-38](https://github.com/freescout-helpdesk/freescout/assets/19673842/521aa45a-853b-445f-8e2a-8ed3c5598344)

**Comment by freescout-helpdesk** [comment]
Debug this function: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/SystemController.php#L31

**Comment by jshrek** [comment]
Sorry, I do not know how to "debug this function"

**Comment by jshrek** [comment]
Well I found this in the PHP error logs, but I am not sure this helps much, other than confirming that it is somehow running out of memory!

[Sat Jul 08 22:28:12.188877 2023] [lsapi:error] [pid 16977:tid 47243281594112] [remote 71.138.95.154:1043] [host freescout.mydomain.com] Backend fatal error: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 21577728 bytes) in /home/mydomain/public_freescout/overrides/symfony/http-foundation/Response.php on line 1285\n, referer: https://freescout.mydomain.com/

**Comment by freescout-helpdesk** [comment]
Probably you have a lot of queued background jobs. Check how many records you have in `jobs` and `failed_jobs`.

**Comment by jshrek** [comment]
Both the `jobs` table and `failed_jobs` table in DB have noting in them (zero rows).

**Comment by freescout-helpdesk** [comment]
Try to add the following code to line 200 in https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/SystemController.php#L200 :
```
echo 'non_writable_cache_file length:'.strlen($non_writable_cache_file);
exit();
```

And send the output.

**Comment by jshrek** [comment]
I actually de-activated all modules and then the system status page started working again.
I re-activated all modules and it is still working.

I will use the above code if it happens again.
And I will also try de-activate one module at a time if it happens again.

Thanks

**Comment by freescout-helpdesk** [comment]
Most likely the problem is with permissions in `storage/framework/cache/data/` folder: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
