### ISSUE TITLE
Increase allowed attached file size for mails sent to Freescout

### ISSUE THREAD

**Issue by oledmansfeld** [freescout-helpdesk/freescout#3166]
We recieve mails with files up to 95 mb. These emails are not imported into freescout.
Mail is recieved on the mail server.
I have increased the allowed file size in php.ini and I am able to upload the files via the Web Portal module and create a ticket.

Is there a way to allow emails with file sizes up to 100mb?

Kr Ole

**Comment by freescout-helpdesk** [comment]
Are you using the latest FreeScout version?

**Comment by oledmansfeld** [comment]
I believe so
![image](https://github.com/freescout-helpdesk/freescout/assets/38720025/39dcb46f-5c15-4f19-a750-777b2c697d74)

**Comment by freescout-helpdesk** [comment]
Check errors in Manage > Logs > App Logs

**Comment by freescout-helpdesk** [comment]
Edit `memory_limit` to your desire value in php.ini

**Comment by oledmansfeld** [comment]
Hi again
I have changed mem limit and restartet the server to no avail.
Freescout is hosted in an AWS Plesk server. Do you know if this could be causing the issues?

![image](https://github.com/freescout-helpdesk/freescout/assets/38720025/64dee50b-eb0a-4de8-af18-6d6dd727938a)

**Comment by freescout-helpdesk** [comment]
Does the issue still persist? Try to set 512M

**Comment by oledmansfeld** [comment]
Yes its still there.

**Comment by oledmansfeld** [comment]
What frustrates is that even though I increase the memory it still says allowed mem size is 128MB

Allowed memory size of 134217728 bytes exhausted (tried to allocate 16105496 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 16105496 bytes) at /var/www/vhosts/jma.dk/websupport/overrides/webklex/php-imap/src/Structure.php:133)

**Comment by freescout-helpdesk** [comment]
php.ini file for console version of PHP may be different from the general php.ini

**Comment by oledmansfeld** [comment]
THANKS for the hint on console - Found the solution - cron jobs was running under another PHP version using another php.ini file for settings...
My fault.. sorry for wasting your time.
