### ISSUE TITLE
Subject de/en-coding issues

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3167]
Hi,

I noted there were some updates with subject decoding recently. Unfortunatly I still encountered two cases where the decoding goes wrong on our installation (latest version 1.8.83). 

### case 1
**mail header** _Subject: =?ISO-8859-1?Q?Vorgang 538336029: M=F6chten Sie Ihre E-Mail-Adresse =E4ndern??=_
**decoded into** _=?ISO-8859-1?Q?Vorgang 538336029: M=F6chten Sie Ihre E-Mail-Adresse =E4ndern??=_ **(untouched)**
**expected result** _Vorgang 538336029: Möchten Sie Ihre E-Mail-Adresse Ändern?_

### case 2
**mail header** _Subject: =?utf-8?Q?Gesch=C3=A4ftskonto?= erstellen =?utf-8?Q?f=C3=BCr?=
 249143_ **(newline included)**

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/e39a5d1e-bd85-4344-a900-2590e5d60f15)

**decoded into** _Geschäftskonto für_
**expected result** _Geschäftskonto erstellen für 249143_

The interesting fact with case 2 is that it was sent from one freescout mailbox to another.

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
