### ISSUE TITLE
Installed licenses for "Custom Mailbox Signatures" and "Saved Replies" and the FS SMTP settings got erased

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3169]
System: FS 1.8.83, nginx 1.22.0, PHP 8.1.12-1ubuntu4.2

I installed them both at the same time, so I don't know which one is related to this issue.

The two modules are:
https://freescout.net/module/custom-signatures/
and
https://freescout.net/module/saved-replies/

SMTP had been setup and working fine with 365, but after installing these modules mail stopped working.  Went to look at my settings and they were just gone.  It was back to trying to use phpmail(), and when I reselected SMTP there was nothing there.  I re-entered the config and it works again, but it was an unpleasant surprise.  IMAP settings were not affected.

**Comment by freescout-helpdesk** [comment]
Unfortunately we have no idea what could cause this.
