### ISSUE TITLE
Saved Replies Module

### ISSUE THREAD

**Issue by lanc2112b** [freescout-helpdesk/freescout#317]
![image](https://user-images.githubusercontent.com/2247147/63560788-38f24300-c54f-11e9-9b0a-d94063a21fce.png)

![image](https://user-images.githubusercontent.com/2247147/63560888-b6b64e80-c54f-11e9-8456-dd2a6fa41bee.png)

There seems to be an issue with the 'Saved Replies' module. It appears in the reply window options with the 'save this reply...' option. However the link in the sidebar in the mailbox settings as shown in the screenshots on the purchase site do not appear.

Regards

**Comment by freescout-helpdesk** [comment]
Hae you followed troubleshooting instructions https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#troubleshooting?

**Comment by lanc2112b** [comment]
Hi, 

Yes, first thing I had tried. I also tried step 3. even though it is partly functioning. There is only that one link / page missing in mailbox settings.

**Comment by lanc2112b** [comment]
Forgot to mention, nothing in the logs related to this module or installation.

A little more digging, after pulling the route for the module (php artisan route:list | grep 'Modu                                                                                          les\\SavedReplies'). And trying the route directly, the page does appear, I can view and add replies without issue.

Just no link being inserted in the sidebar.

**Comment by freescout-helpdesk** [comment]
By some reason hook in the mailbox menu is not working.

**Comment by lanc2112b** [comment]
Seems to be the permissions test 'auth()->user()->hasPermission(User::PERM_EDIT_SAVED_REPLIES)' in SavedRepliesServiceProvider.php that's returning false. I haven't had the chance to take a look back through the auth / permissions system, not sure that will be helpful (virtually nil Lavarel experience).

Both users I'm testing with are admin. I can't see any extra options in the 'permissions' pages other than giving users access to specific mailboxes - should there be options to give users access to specific modules as well? Although surely to be able to add/edit saved replies show the users already have the permissions required?

**Comment by freescout-helpdesk** [comment]
Make sure that users you are logged in are really admins.

Admins are able to edit Saved Replies in mailboxes settings by default. To allow regular users edit Saved Replies go to `Manage » Settings » General`:

![2019-08-25_17-41-27](https://user-images.githubusercontent.com/40499291/63651650-b7253400-c75f-11e9-974f-00de5e86f9c3.png)

**Comment by lanc2112b** [comment]
Ok, both users are set to 'Administrator', the account I'm using currently is the initially created 'System Administrator' is there any case or reason why this user wouldn't really be an admin? Neither user has the menu appearing. The option in your reply does turn on the menu item for both. 

So it looks like users with Administrator role are missing something?

**Comment by freescout-helpdesk** [comment]
This seems to be an issue in the module. We will fix and let you know.

**Comment by lanc2112b** [comment]
Ok, cheers.

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version.
