### ISSUE TITLE
Recurring "non-writable files found" error

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3170]
System: FS 1.8.83, nginx/1.22.0, PHP 8.1.12-1ubuntu4.2
Installed using the ubuntu.sh script on the Installation instructions page.

After the initial install, under /system/status, I only had one error:
> Non-writable files found
> /var/www/html/storage/framework/cache/data/1a/b7/1ab7cd0b2e433a03e7819212849e30c1f634bfe3
> Run the following command (read more):
> sudo chown -R www-data:www-data /var/www/html

I run the sudo chown command, refresh and the error is gone.  Until later in the day or the next day it comes back and I run it again. 

The directory with the issue is always the same:
> /var/www/html/storage/framework/cache/data

See attached image of directory listing.

When the error occurs, many of the 2-digit-named folders there will be owned by 'root:root' instead of www-data:www-data.  The command fixes them, but the problem keeps coming back.
![MobaXterm_303](https://github.com/freescout-helpdesk/freescout/assets/18216162/be5bb934-c86d-4393-ad3f-d186dd1d0133)

**Comment by HenrysCat** [comment]
Exactly the same problem here v1.8.83 nginx/1.22.1 PHP 8.2.7 Debian 6.1.37-1

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by HenrysCat** [comment]
Thanks, I set the cron by using 'crontab -e' should have been 'crontab -u www-data -e'

**Comment by apecity** [comment]
It was my mistake.  I'd scheduled the "* * * * * php /var/www/html/artisan
schedule:run >> /dev/null 2>&1" cron job to run as root, not as www-data.
