### ISSUE TITLE
Install problems true softaculous

### ISSUE THREAD

**Issue by julianl890** [freescout-helpdesk/freescout#3173]
PHP version: 8.1
FreeScout version: 1.8.81

[2023-07-09 07:18:56] production.ERROR: Undefined constant "FT_UID" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"FT_UID\" at /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/webklex/laravel-imap/src/config/imap.php:105)
[stacktrace]
#0 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(66): require()
#1 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#2 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#3 /home/axeas57/domains/xdizziex.nl/public_html/freescout/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#4 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#5 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#6 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#7 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#8 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 /home/axeas57/domains/xdizziex.nl/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#10 /home/axeas57/domains/xdizziex.nl/public_html/freescout/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle()
#11 {main}
"} 

All needed php extensions are installed.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-undefined-constant-ft_uid

**Comment by julianl890** [comment]
Fixed for directadmin admins this is the sulution:

cd /usr/local/directadmin/custombuild
./build update
./build set_php "imap" yes
./build "php_imap"
