### ISSUE TITLE
Delete Module Database Table Data

### ISSUE THREAD

**Issue by medoix** [freescout-helpdesk/freescout#3174]
I have had some trouble with a Module and after Deactivating and even Deleting the module entirely when re-installing all of the settings and data remains.

Is there a way to force delete/cleanup of database data created/stored by a specific Module? Should this be taken care of by the Module removal process automatically? Or is this being stored somewhere else possibly?

PHP version: PHP 8.2.8
FreeScout version: 1.8.84

**Comment by freescout-helpdesk** [comment]
For now module's data is kept in DB to preserve their data.

**Comment by medoix** [comment]
So i would need to connect directly to the database to remove these module settings?

**Comment by freescout-helpdesk** [comment]
Yes, you can try.
