### ISSUE TITLE
Mail Header - References

### ISSUE THREAD

**Issue by bajz01** [freescout-helpdesk/freescout#3175]
Dear team,

could you please verify if Mail Header "REFERENCES" follows RFC2822 when creating REFERENCE Header 

-- SNAP - IETF RFC 2822 -
When creating a reply to a message, the "In-Reply-To:" and
   "References:" fields of the resultant message are constructed as
   follows:

   :

   The "References:" **field will contain the contents of the parent's
   "References:" field (if any)** followed by the contents of the parent's
   "Message-ID:" field (if any).  
-- SNAP - End

I have tried to send messages between Gmail (GM) and FreeScout (FS). If I understand the RFC2822 correctly, then in answer from FS on answer from GM in STEP **4**, the FS  has not put previous fields from REFERENCES header

# 1st step - email :: GM -> FS
	From: Caller <caller@gmail.com>
	Subject: my Thread
	Message-Id: <267EE9C9-372A-4E9B-A6FD-62262CE38F5D@gmail.com>
	Date: Mon, 10 Jul 2023 19:52:31 +0200
	To: Callee <callee@freeScout.net>

# 2nd step - answer on 1st step  :: FS -> GM
	Message-ID: <reply-24672-e100108cb593554a@freeScout.net>
	Date: Mon, 10 Jul 2023 19:55:29 +0200
	Subject: [#6802] my Thread
	From: Callee <callee@freeScout.net>
	To: Caller <caller@gmail.com>
	X-FreeScout-Mail-Type: customer.message
	References: <267EE9C9-372A-4E9B-A6FD-62262CE38F5D@gmail.com>
	In-Reply-To: <267EE9C9-372A-4E9B-A6FD-62262CE38F5D@gmail.com>

# 3rd step - answer on 2nd step  :: GM -> FS

	References: <267EE9C9-372A-4E9B-A6FD-62262CE38F5D@gmail.com> <reply-24672-e100108cb593554a@freeScout.net>
	In-Reply-To: <reply-24672-e100108cb593554a@freeScout.net>
	Message-ID: <CAD93x3GBHYGS99QDQt6XQrCFrLK3ZfWxxdbmVk8_LTfCVjfDbw@mail.gmail.com>
	Subject: Re: [#6802] my Thread
	From: Caller <caller@gmail.com>
	To: Callee <callee@freeScout.net>

# 4th step - answer on 3rd step  :: FS -> GM 
**HERE** I am missing in REFERENCES header previous IDs : <<267EE9C9-372A-4E9B-A6FD-62262CE38F5D@gmail.com>> <<reply-24672-e100108cb593554a@freeScout.net>> 

	Message-ID: <reply-24674-761fba6a2270bc5e@freeScout.net>
	Date: Mon, 10 Jul 2023 20:04:33 +0200
	Subject: [#6802] my Thread
	From: Callee <callee@freeScout.net>
	To: Caller <caller@gmail.com>
	X-FreeScout-Mail-Type: customer.message
	References: <CAD93x3GBHYGS99QDQt6XQrCFrLK3ZfWxxdbmVk8_LTfCVjfDbw@mail.gmail.com>
	In-Reply-To: <CAD93x3GBHYGS99QDQt6XQrCFrLK3ZfWxxdbmVk8_LTfCVjfDbw@mail.gmail.com>

**Comment by bajz01** [comment]
Yes, exactly - there is missing parents "references"-header content before parents "Message-ID". 

What impact that has:  this behaviour segments the email thread - like in example above many remote-side mail systems will "merge" 1+2 and 3+4 as two threads. This could cause loose of information in remote HelpDesk systems (is our experience with different companies where we answer with our FreeScout).

Having whole references content from parent + parent message-Id in that, then the remote email thread would be only one (messages 1+2+3+4) on remote side. (e.g. something like some parameter **references** in the **last_customer_thread** structure 

`$headers['References'] =$last_customer_thread->references  . '<'.$last_customer_thread->message_id.'>';`

) 

So in step 4 we would expect to have

**References**: <267EE9C9-372A-4E9B-A6FD-62262CE38F5D@gmail.com> <reply-24672-e100108cb593554a@freeScout.net> <CAD93x3GBHYGS99QDQt6XQrCFrLK3ZfWxxdbmVk8_LTfCVjfDbw@mail.gmail.com>

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

**Comment by bajz01** [comment]
Dear team,

I have tested just the latest version (1.8.85 ) - but in step #4 I get towards Gmail only one REFERENCES entry. Have you tested it if the amount of References-Header entries is increasing?

```
Date: Fri, 14 Jul 2023 16:05:40 +0200
Subject: [#6940] Thread #2
References: <76918829-2A72-4952-8858-3C3C0583D203@gmail.com>
In-Reply-To: <76918829-2A72-4952-8858-3C3C0583D203@gmail.com>

```

**Comment by bajz01** [comment]
Update:

when Settings->Manage ->General->Emails to Customers  is set to

a) **Include the last message** => NOK -> DOESN'T put parent References

b) **Send full conversation history** => OK -> all references are included


```
Message-ID: <reply-25199-01e2742bd0993871@freeScout.net>
Date: Fri, 14 Jul 2023 16:40:03 +0200
Subject: [#6941] Thread #3
X-FreeScout-Mail-Type: customer.message
References: <DDBADA07-2BBA-4431-9898-AFD72CB99167@gmail.com> <reply-25196-71b0f21f88001573@freeScout.net> <6BA2335D-48E8-4DA2-89F7-6E80563EB9B3@gmail.com> <reply-25198-76dc35136d131593@freeScout.net>
In-Reply-To: <6BA2335D-48E8-4DA2-89F7-6E80563EB9B3@gmail.com>

```

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` bnranch.
