### ISSUE TITLE
Another subject decoding issue

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3177]
Hi.

I got another wrong decoded subject  (I was not sure if I just add a comment on https://github.com/freescout-helpdesk/freescout/issues/3167 or open a new issue)

_Subject: =?UTF-8?B?UmU6IMKgUmU6wqBSZTogUsO8Y2tzZW5kdW5nIGRlcyBBcmJlaXRzbWF0?=
 =?UTF-8?Q?erials?=_

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/2dfe3e1b-182c-42fa-984c-73618101dfd1)

expected: _Re:  Re: Re: Rücksendung des Arbeitsmaterials_
actual result: _Re:  Re: Re: Rücksendung des Arbeitsmatz???_

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
