### ISSUE TITLE
Freescout APP Android13 - http access Error: err_cleartext_not_permitted 

### ISSUE THREAD

**Issue by gplast1981** [freescout-helpdesk/freescout#3179]
We use Freescout in the local network with http on an ubuntu nginx server, we wanted to connect our new cell phones with Android13 and the Freescout app, but the message err_cleartext_not_permitted android comes up

How can you solve this? The app works perfectly with older Android versions. Thanks very much

**Comment by freescout-helpdesk** [comment]
You must be using HTTP on your FreeScout. Try to enable HTTPS on your FreeScout.
