### ISSUE TITLE
Send error. Expected response code 250 but got code "554"

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#318]
Hi

I'm using Google Apps. 

What this error means;

`Send error. Expected response code 250 but got code "554", with message "554 Message rejected: Stream is more than 10485760 bytes long. "`

The same mail I can send through Gmail but cannot send through FS.

**Comment by freescout-helpdesk** [comment]
This is your email provider response. Maybe email provider has different size limits for attachments sent from web interface and via SMTP.
