### ISSUE TITLE
Knowledge base search without characters error

### ISSUE THREAD

**Issue by mihaj3kr** [freescout-helpdesk/freescout#3181]
Hello,

if you open knowledge base portal https://demo.freescout.net/en/hc/1321731726/ and click search without input there will be error.

Reporuction:
-open demo kb https://demo.freescout.net/en/hc/1321731726/
-click on search

Result is error
`Whoops, looks like something went wrong — check logs in /storage/logs`
https://demo.freescout.net/en/hc/1321731726/search?q=

**Comment by freescout-helpdesk** [comment]
Thanks. This issue has been already fixed in the Knowledge Base Module but it has not been updated on demo.freescout.net yet.
