### ISSUE TITLE
Mail sent error

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3182]
Hello.
I experienced mail send error like
`Attempt to read property "id" on null (View: /www/html/resources/views/emails/customer/reply_fancy.blade.php); File: /www/html/app/Conversation.php (1057)`
so I change Conversation.php :1057 like
before
       ` } elseif (($user && $this->user_id == $user->id) || (!$user && $this->user_id == auth()->user()->id)) {`
after
      `  } elseif (($user && $this->user_id == $user->id) || (!$user && auth()->user() && $this->user_id == auth()->user()->id)) {`
then that error disappeared.
Do I have to make pull requests for this?
or I did something wrong ?

**Comment by totake0224** [comment]
my freescout version is 1.8.81 origin/master

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by totake0224** [comment]
Thank you. but I'm wonder why auth()->user() is null at my freescout.
Is it possible?
I'm thinking is my configuration good ?
