### ISSUE TITLE
Undisclosed-Recipient in Webklex/laravel-imap

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3183]
I want share this information. if some one could fix this.
(I'm trying but I could not find where this error occurred.)

I got mail fetch error.
`Folder: INBOX; Error: Unexpected characters at end of address: :;>`
and I think I found message that this error occurred.
the header of this message contains 
`To: <Undisclosed-Recipient:;>`
(this happens only BCC is set.)
and Freescout shows message [to address]
`undisclosed-recipient@unknown, missing_mailbox_terminator@.syntax-error, unexpected_data_after_address@.syntax-error`

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP Authentication or `APP_NEW_FETCHING_LIBRARY` parameter in .env file?

**Comment by totake0224** [comment]
Hello.
No. and APP_NEW_FETCHING_LIBRARY=false
and my version is 1.8.81

**Comment by freescout-helpdesk** [comment]
Set `APP_NEW_FETCHING_LIBRARY=true` in the .env file and clear the cache.
