### ISSUE TITLE
Japanese subject and attachment filename still garbled.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3185]
version 1.8.84
APP_NEW_FETCHING_LIBRARY=false

I fixed this in my fork and make pull request.
but still garbled in official freescout.
there is big difference between official source and my soucre.
so I couldn't explain how to merge these two source.

**Comment by freescout-helpdesk** [comment]
Send examples to support@freescout.net

**Comment by totake0224** [comment]
I sent sample.

**Comment by freescout-helpdesk** [comment]
See how to do it: https://github.com/freescout-helpdesk/freescout/issues/3177

**Comment by totake0224** [comment]
correct image
![Screenshot from 2023-07-14 19-44-00](https://github.com/freescout-helpdesk/freescout/assets/42058913/02c1c78a-2319-4f63-8b62-0439f803dcb5)

garbled image
![Screenshot from 2023-07-14 19-44-11](https://github.com/freescout-helpdesk/freescout/assets/42058913/d95f605c-9d49-4e8d-9dde-920d598ff986)

mail body decode correctly but subject and attachment filename is garbled.

it's header image
![Screenshot from 2023-07-14 19-51-10](https://github.com/freescout-helpdesk/freescout/assets/42058913/0a6f6c44-3531-4a95-86f7-38b475f758ca)

and header text
Subject: =?iso-2022-jp?B?GyRCLWokIiQkJCYkKCQqfGIkKyQtJC8kMSQzGyhC?=
X-FE-Attachment-Name: =?UTF-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pGhLnR4dA==?=

**Comment by totake0224** [comment]
I edit former uploaded image.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
