### ISSUE TITLE
lost message body

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3186]
I experienced message body lost. and got error message like 
`Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'd58fa7ed-b230-6fd2-60e9-e3008c7d96ff@minocraft.co.jp' for key 'threads_message_id_index' (SQL: insert into `threads` (`conversation_id`, `user_id`, `type`, `status`, `state`, `message_id`, `headers`, `body`, `from`, `to`, `cc`, `bcc`, `source_via`, `source_type`, `customer_id`, `created_by_customer_id`, `first`, `updated_at`, `created_at`) values (`

this happens when I use system->tools-> fetch.
crontab may also fetching same time because there is many mails. 
Is system->tools->fetch dengerous?
I could not recover these mail body because of I'm using Move or Remove IMAP Message module.

**Comment by totake0224** [comment]
conversation list shows mail. but it contain no body message and could not show original message.

**Comment by freescout-helpdesk** [comment]
> this happens when I use system->tools-> fetch.
> crontab may also fetching same time because there is many mails.

If same email is being fetched via Tools and in the background you may get the error you've described. In this case simply remove the conversation which has no body - it has been fetched before.
