### ISSUE TITLE
Would you help me to add Vietnamese language support?

### ISSUE THREAD

**Issue by nguyencongvan** [freescout-helpdesk/freescout#3187]
Dear FreeScout!

I am from Vietnam and I would like to try your open-source software and deploy it in my company. However, I have noticed that the language does not include Vietnamese. Could you please help me add Vietnamese language support?

Thanks for your help!
Best regards:
Van

**Comment by freescout-helpdesk** [comment]
Just follow the instruction: https://github.com/freescout-helpdesk/freescout/wiki/Translate

**Comment by nguyencongvan** [comment]
Thanks, I will follow this instruction :D!

**Comment by nguyencongvan** [comment]
Dear admin!

I have problem with npm run development
How can I fix this?

<img width="928" alt="Untitled3232" src="https://github.com/freescout-helpdesk/freescout/assets/56850571/522a004e-44cb-4669-8e77-5273b2343d78">

Thanks!

**Comment by freescout-helpdesk** [comment]
You don't need to run it. See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

**Comment by nguyencongvan** [comment]
thank you, another question would you can help?
![image](https://github.com/freescout-helpdesk/freescout/assets/56850571/d223961a-107f-44bf-8039-3a457d92dd4a)
I successfully loged in but it just present it button, did I miss something?

**Comment by nguyencongvan** [comment]
Oh, I resolved this :D
