### ISSUE TITLE
Exclude e-mail addresses

### ISSUE THREAD

**Issue by TyrannosaurHex** [freescout-helpdesk/freescout#319]
Is there anyway to exclude certain email addresses from receiving the auto-response notification?

**Comment by freescout-helpdesk** [comment]
No for now.

**Comment by CH4931** [comment]
I just wanted to ask the same question as @TyrannosaurHex back in August 2019.

We have customers who don't want to receive the auto-response notification. The option to create  a list  of email addresses to exclude would be a great feature! Thanks.
