### ISSUE TITLE
Question: pcntl PHP extension a hard requirement now?

### ISSUE THREAD

**Issue by maltem-za** [freescout-helpdesk/freescout#3190]
PHP version: 8.1.21
FreeScout version: 1.8.86

I just upgraded to the latest version and noticed that `intl` and `pcntl` are now listed under the PHP extensions, which I hadn't noticed before. `intl` is marked optional but `pcntl` is not - will something break without the latter? Everything seems to be working and no errors in the logs...

![freescout-php-extensions-pcntl](https://github.com/freescout-helpdesk/freescout/assets/1404980/0157d0e3-da6a-467c-9bd3-15c0d06ad619)

**Comment by freescout-helpdesk** [comment]
Yes. Without it FreeScout is unable to kill hanging background processes: https://stackoverflow.com/questions/53669484/use-of-undefined-constant-sigkill-assumed-sigkill

**Comment by freescout-helpdesk** [comment]
Are you using Docker or Cloudron?

**Comment by maltem-za** [comment]
Thank you. No, I installed using the bash script.

**Comment by freescout-helpdesk** [comment]
@tiredofit Thanks.

@maltem-za Actually the `pcntl` extension may be already enabled in the console version of PHP (it's needed only in the console version). Try to execute `php -i | grep pcntl` in the console and check if you see:
```
pcntl support => enabled
```

**Comment by freescout-helpdesk** [comment]
Now Status page will be checking `pcntl` extension in the console version of PHP.

**Comment by SecureCPU** [comment]
Hey, i'm having an issue with this.
I has the same error. So I installed the PHP intl extension. and in the status page is now says OK.
However the pcntl still says not found.
I ran the command 'php -i | grep pcntl' and got the following output.
![Screenshot 2023-07-30 190728](https://github.com/freescout-helpdesk/freescout/assets/99109793/9cff9809-d9cf-43e2-aa8f-eb14b6e9b51f)

however in the status page of FreeScout it still shows:
![Screenshot 2023-07-30 190857](https://github.com/freescout-helpdesk/freescout/assets/99109793/f348a9ac-fed6-4076-b4a2-58ad313b3107)

How do I resolve this issue?

Would anyone be able to help me? 

Thanks!!

**Comment by freescout-helpdesk** [comment]
Just wait for the next release.

**Comment by SecureCPU** [comment]
But i seem to be having an issue. I though it was related to this.
See pic
![Screenshot 2023-07-31 005331](https://github.com/freescout-helpdesk/freescout/assets/99109793/d233a33a-5c24-41d5-893c-800b98bad8ff)

**Comment by maltem-za** [comment]
@SecureCPU Check the "Outgoing Emails" and "Send Errors" logs. Sounds like you might have 6 mails that are failing to send for some reason.
