### ISSUE TITLE
CRM module filters give 403 

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#3191]
Steps to reproduce:
1. Click on Manage->Customers
2. Click on a custom field under "Filters"
3. Select a value and click "Search"

The URL is something like:
/search?mode=customers&xs_crm=1&f%5B%23Type%5D=&q=
(where Type is the name of the custom field)
But I see a 403 Forbidden error.

Manage->Logs doesn't show any error.
Also the error log in cPanel doesn't show error.

What can we do?

PHP version: 8.1.20
FreeScout version: 1.8.86

Thanks!

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by dabesa** [comment]
Hello,
No, it works on demo.
What can I check on our server?

Thanks

**Comment by freescout-helpdesk** [comment]
Send screenshot of 403 page. Are you using CloudFlare?

**Comment by dabesa** [comment]
We don't use Cloudflare, here is the screenshot:
https://paste.pics/1ff552869dd9f0019b43ca182c0291be

Thanks

Il giorno lun 17 lug 2023 alle ore 19:17 FreeScout ***@***.***>
ha scritto:

**Comment by freescout-helpdesk** [comment]
This page is not shown by FreeScout but by your web server or something else. Ask your admin to figure it out.
