### ISSUE TITLE
2FA and reCaptcha don't work together

### ISSUE THREAD

**Issue by GPeti07** [freescout-helpdesk/freescout#3193]
Firstly, thank you for the new module: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/384695/comments

We have found a bug during testing, and we almost locked ourself from our admin account.

The problem:
If the 2FA module (https://freescout.net/module/two-factor-authentication/) and the reCaptcha (https://freescout.net/module/extra-security/) is active on the account, after entering 2FA code, it give back "invalid captcha" error on the main login page ( /login ).
If the 2FA is not activated on an account, then the login works with reCaptcha.

**Comment by freescout-helpdesk** [comment]
Fixed in Extra Security Module v1.0.1
