### ISSUE TITLE
On the Enduser Portal, EULA accept "required" not required

### ISSUE THREAD

**Issue by GPeti07** [freescout-helpdesk/freescout#3194]
On the Enduser Portal, EULA accept "required" not required. So it send the form without checking the checkbox.

Maybe, is the problem the default: value="1" parameter in the input line?

_(on the image we use custom translation for this label)_
![image](https://github.com/freescout-helpdesk/freescout/assets/96734399/5a57746d-5a3c-4d67-a298-8cc396c757e6)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue on demo.freescout.net

![2023-07-18_17-02-46](https://github.com/freescout-helpdesk/freescout/assets/40499291/cbfcfb60-e7b4-4ad7-b08a-cce9b4f95a8c)

Are you using any non-official modules?

**Comment by freescout-helpdesk** [comment]
As we can't reproduce the issue you'll need to try to investigate it yourself.
Check for example errors in the browser console.
