### ISSUE TITLE
End char of Japanese text in subject and filename garbled. 

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3195]
version 1.8.86
APP_NEW_FETCHING_LIBRARY=false;

I test new version of freescout and found very strange behavior. End char of some Japanese text in subject and filename garbled.
you could find attachment filename's [.txt] in image below became [.t__] (_ means square box)
![Screenshot from 2023-07-18 19-07-52](https://github.com/freescout-helpdesk/freescout/assets/42058913/249157f8-6b06-46fe-ae94-d392747f1ad1)

I gather more information about this and found [iconv_mime_decode] did this. I add \Log output before and after of iconv_mime_decode like below,

> app\Misc\Mail.php   around line number 922 

> \Log::error("iconv_mime_decode1:" . $joined_parts);
            $subject_decoded = iconv_mime_decode($joined_parts, ICONV_MIME_DECODE_CONTINUE_ON_ERROR, "UTF-8");
            \Log::error("iconv_mime_decode1_decode:" . $subject_decoded);

and I got this

> 

Level | Context | Date | Content
-- | -- | -- | --
error | production | 2023-07-18 19:03:12 | iconv_mime_decode1_decode:㈱あいうえお髙かきくけこ①で⓶.t
error | production | 2023-07-18 19:03:12 | iconv_mime_decode1:=?utf-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pO2LnQ=eHQ=?=

I confirm encoded string is OK ( I could decode it normally by another decoder.) but decoded string is garbled.
hear is the site that I decode the encoded string
`=?utf-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pO2LnQ=eHQ=?=`
[https://www.bungu-do.jp/tools/mail_subject](https://www.bungu-do.jp/tools/mail_subject)

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no a solution for this issue.

The file name is encoded improperly. It should be:

`=?utf-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pO2LnQ=?= =?utf-8?B?eHQ=?=`

instead of 

`=?utf-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pO2LnQ=eHQ=?=`

**Comment by totake0224** [comment]
I'm sorry. my report is missing original eml source.
here is it.

![スクリーンショット 2023-07-19 084546](https://github.com/freescout-helpdesk/freescout/assets/42058913/b8f61ed3-c3ee-4c17-ab4b-bb929e6d4b81)

original source of eml is
`=?utf-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pO2LnQ=?= =?utf-8?B?eHQ=?=`

decodeSubject function merge this into
`=?utf-8?B?44ix44GC44GE44GG44GI44GK6auZ44GL44GN44GP44GR44GT4pGg44Gn4pO2LnQ=eHQ=?=`
after that calling iconv_mime_decode.

**Comment by freescout-helpdesk** [comment]
It has been fixed in the `master` branch.

**Comment by totake0224** [comment]
I have confirmed this fixed.
Thank you very much.
