### ISSUE TITLE
imap_utf8 could not decode iso-2022-jp-ms properly.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3196]
version 1.8.86 
APP_NEW_FETCHING_LIBRARY=false

I tested latest freescout. and I found mail subject garbled. 
I tried to identify which decode function make garbled. and I found it imap_utf8.
garbled image(attachment filename decoded correctly.)
![Screenshot from 2023-07-18 19-55-00](https://github.com/freescout-helpdesk/freescout/assets/42058913/0c58923a-fd49-4551-98e4-55652e44d20c)

correct image
![Screenshot from 2023-07-14 19-44-00](https://github.com/freescout-helpdesk/freescout/assets/42058913/c7af9a2d-9ada-4dd6-b03d-469292217d7b)

This is how I identify the function.
I added \Log function before and after imap_utf8 and I got this.
Modified code
> app\Misc\Mail.php  around line number 955

> \Log::error("imap_utf82:" . $subject);
            $subject_decoded = \imap_utf8($subject);
            \Log::error("imap_utf82_decoded:" . $subject_decoded);

Log output
> 
Level | Context | Date | Content
-- | -- | -- | --
error | production | 2023-07-18 20:06:55 | imap_utf82_decoded:(株)あいうえお�かきくけこ
error | production | 2023-07-18 20:06:55 | imap_utf82:=?iso-2022-jp-ms?B?GyRCLWokIiQkJCYkKCQqfGIkKyQtJC8kMSQzGyhC?=

**Comment by totake0224** [comment]
I also confirm mb_decode_mimeheader decode attachment filename properly by Log output.

**Comment by totake0224** [comment]
I'm very sorry. decodeSubject function is very complex. it need time for me modifying it without side effect.

**Comment by freescout-helpdesk** [comment]
We need just 3 things and nothing else:

1. How it looks when garbled.
2. How it should look.
3. How it looks in the original code of the email (or attach .EML file).

Number 3 is missing.

See how to report decoding issue: https://github.com/freescout-helpdesk/freescout/issues/3177

**Comment by totake0224** [comment]
I have confirmed this fixed.
Thank you.
