### ISSUE TITLE
[Question] PHP 8.2 or not ?

### ISSUE THREAD

**Issue by marcatsmci** [freescout-helpdesk/freescout#3199]
https://github.com/freescout-helpdesk/freescout#requirements => `PHP 7.1 - 8.2`

https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#php => `DO NOT use PHP 8.1 ...`

So my question : is it safe to run FreeScout latest under PHP 8.2.x ?

I can't find a definitive answer on the wiki nor elswhere...

Thanks in advance,
Marc

**Comment by freescout-helpdesk** [comment]
Yes.

**Comment by marcatsmci** [comment]
Great, thanks !
BR,
Marc
