### ISSUE TITLE
Workflows sometimes non-working Subject conditions #3095 not resolved

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3200]
Dear freescout-Team,

you closed [issue #3095](https://github.com/freescout-helpdesk/freescout/issues/3095) with an update of the Workflow plugin. Unfortunately the error was not resolved and the functionality has not been restored.

Please kindly take another look. Thank you very much!

Freescout: 1.8.86
PHP: PHP 8.2.8

**Comment by freescout-helpdesk** [comment]
The issue we've found - it has been fixed. Make sure to update the module to the latest version and restart all background jobs: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
If still no luck, you'll need to debut the issue yourself on your server.

**Comment by githubuser-112** [comment]
Dear freescout-Team,

the issue is, that **conversations created through a forward** do not trigger workflows at all. If a new mail comes in with a subject that starts with "Fwd:" it works all fine. Backround-Jobs on our server run just fine and work with everything exept forwards-created conversations.

Have you really tried the workflow with a **conversation created through a forward**?

**Comment by freescout-helpdesk** [comment]
![2023-07-21_08-26-30](https://github.com/freescout-helpdesk/freescout/assets/40499291/27314ac8-283d-4d7d-9816-16e671eb8709)

**Comment by freescout-helpdesk** [comment]
Are you checking emails forwarded by customers to your FreeScout or emails forwarded by support agents from your FreeScout?

**Comment by githubuser-112** [comment]
We are checking emails forwarded by support agents from freescout. This creates a new ticket and on these tickets the workflow does not work.
