### ISSUE TITLE
After updating to version 1.8.86, freescout doesn't download all email messages

### ISSUE THREAD

**Issue by janselato** [freescout-helpdesk/freescout#3202]
At the moment I have rolled back the application version to 1.8.85. All work in this version.

Freescout didn't download all email messages from the mailbox (It only downloaded messages from 2 out of 11 available directories). The logs indicated 0 messages, although there were over 100 in the mailbox. It downloaded all messages for some directories and found none for others. I thought that the problem was with some plugin/module because I updated them too and even after disabling them it still didn’t work. 

I have the following mailbox architecture. There is one mailbox on which directories/tabs are created and they correspond to mailboxes in freescout. 

The logs were empty, only when trying to download messages manually was there a timeout return:
_2023/07/20 13:17:50 [error] 3646614#3646614: *6 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XX.XX.XX.XX, server: domain.name, request: "POST /system/tools HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock", host: "domain.name", referrer: "https://domain.name/"_

PHP version: 8.2.8
FreeScout version: 1.8.85
Plugins: API and Webhooks, 
Global Mailbox, 
Move or Remove IMAP Message, 
Inbox, 
Knowledge Base, 
Mentions, 
Saved Replies, 
Tags, 
Workflows

**Comment by freescout-helpdesk** [comment]
Version 1.8.86 does not have commits touching in any way the process of fetching emails: https://github.com/freescout-helpdesk/freescout/commits/dist - see commits between v1.8.85 and v1.8.86.

**Comment by janselato** [comment]
I understand, but I have looked through the FAQ and tried to update the application manually again and it still didn't download messages. Only rolling back the version solved the problem.

**Comment by freescout-helpdesk** [comment]
It looks like the issue need to be investigated on your FreeScout instance.

**Comment by janselato** [comment]
Should I run a test or enable debugging?

**Comment by raramuridesign** [comment]
@janselato Just a thought, if the message is **read status** on the mailbox, it will not be downloaded. All messages must be **unread** for freescout to fetch the emails.
Perhaps check if this is the issue.

**Comment by janselato** [comment]
Thanks for the answer. Before I started the thread, I was looking for the reason why this was happening. All messages that were not downloaded were marked as unread.

Today I made another update, and strangely everything works. At the moment there are no errors.
