### ISSUE TITLE
Send errors in front-end?

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#3204]
Dear support,

When a message sent is not delivered due to an error, the user doesn't receive any notice.
The error is only visible for admins in the Logs->Send errors.

Is there an option or do you have plan to make these errors visible for users?

Thank you

**Comment by freescout-helpdesk** [comment]
In FreeScout it's admin's task to take care of email delivery: https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-support-team-know-that-there-are-problems-with-sending-emails-and-emails-are-not-being-sent
