### ISSUE TITLE
Extra Security Module - Turnstile

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#3206]
Hey,
I wanted to know if its possible to add Cloudflare Turnstile to the Extra Security Module as a second option to Google's  reCAPTCHA

Thanks!!

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by SecureCPU** [comment]
The page doesn't load to submit a feature request.

<img width="1280" alt="brave_XKMRwmPuen" src="https://github.com/freescout-helpdesk/freescout/assets/99109793/a7a5d4f0-5338-48d8-b793-6c6422009bb2">

**Comment by SecureCPU** [comment]
The request feature page is still down. Is there another way to request this feature?
<img width="960" alt="brave_Jw0N3YDf9j" src="https://github.com/freescout-helpdesk/freescout/assets/99109793/511c8f04-504e-419e-a7df-8c1185e83086">
