### ISSUE TITLE
Question: FreeScout + CyberPanel

### ISSUE THREAD

**Issue by yabloky** [freescout-helpdesk/freescout#3207]
Hi.

Is there any way to install FreeScout via CyberPanel? By installing CyberPanel - it automatically installs the same components that FreeScout requires, and if you install on top of FreeScout with a bash script, it will install copies of those components and everything will work with conflicts. Maybe there is a FreeScout installation script with checks and configuration of already installed components?

**Comment by freescout-helpdesk** [comment]
Follow https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide
