### ISSUE TITLE
The problem with the encoding of emails and the activation of the agent

### ISSUE THREAD

**Issue by zuevav** [freescout-helpdesk/freescout#3208]
I haven't activated the agent for a long time, I can't say when it started, but on version 1.8.86 the agent is not activated, the activation letter comes with a violation of the encoding, and the link reports that there are problems.
____
There was a problem when configuring the user
The invitation was not found. Please contact the administrator to have a new invitation letter sent to you.
___

I also receive test emails with a violation of the encoding, everything was fine before

[test message error.txt](https://github.com/freescout-helpdesk/freescout/files/12146635/test.message.error.txt)

PHP version: 8.0.17
FreeScout version: 1.8.86

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY` parameter in .env file?

Try to send an example of the email with broken encoding to support@freescout.net

**Comment by zuevav** [comment]
I added this parameter to the file, but it did not give any result.

**Comment by freescout-helpdesk** [comment]
> Try to send an example of the email with broken encoding to [support@freescout.net](mailto:support@freescout.net)

**Comment by freescout-helpdesk** [comment]
We've received the test email. Other email clients are also showing it in a garbled form. It's HTML is broken:

![2023-08-01_13-33-22](https://github.com/freescout-helpdesk/freescout/assets/40499291/3a5f6234-c965-4b4b-9e5c-d24926ee6bfc)

**Comment by zuevav** [comment]
what do you mean and how to fix it?

**Comment by zuevav** [comment]
I have not made any changes to the configuration files, after the next update I cannot attach the user to the system, he receives an email with destroyed formatting. Please tell me where to dig to fix it and apparently a related problem. The link coming for the agent in the registration does not work.
Screen
 User Setup Problem
No invite was found. Please contact your administrator to have a new invite email sent.

**Comment by zuevav** [comment]
this is how the letter that came to the new agent looks like

--_=_swift_1695050447_ffb08246e6369b047894897a68f9a61e_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hi alexey zu, an account has been created for you at [https://support.d-fis=/
.ru]

Create a Password
---------------------------------------------=
----
https://support.d-fis.ru/user-setup/NsimKHukyzVY8mjFjAs5Dp3eXOLNxpHo=
Q0m8vMBuVtOSk2CXuu0G


Welcome to the team!
---------------=
----------------------------------
Someone on your team created an accoun=
t for you.

--_=_swift_1695050447_ffb08246e6369b047894897a68f9a61e_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html lang=3D"en" style=3D"background: #F1F3F5; height: 100% !important; ma=
rgin: 0; padding: 0; width: 100% !important">
<head>
    <meta http-equ=
iv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8" />
    <meta c=
harset=3D"utf-8" />
    <meta name=3D"viewport" content=3D"width=3Ddevice=
-width" />
    <meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge"=
/>
</head>

<body leftmargin=3D"0" topmargin=3D"0" marginwidth=3D"0"=
marginheight=3D"0" style=3D"background: #F1F3F5; height: 100% !important; =
margin: 0 auto; padding: 0; width: 100% !important" bgcolor=3D"#F1F3F5">
=
=09<table bgcolor=3D"#F1F3F5" cellpadding=3D"0" cellspacing=3D"0" border=3D=
"0" height=3D"100%" width=3D"100%" style=3D"border: 0; border-collapse: col=
lapse; border-spacing: 0 !important; margin: 0 auto; mso-table-lspace: 0pt;=
mso-table-rspace: 0pt; vertical-align: top">
=09=09<tr>
=09=09=09<td s=
tyle=3D"mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" =
valign=3D"top">
=09=09=09=09<table border=3D"0" width=3D"600" cellpadding=
=3D"0" cellspacing=3D"0" align=3D"center" style=3D"background: #F1F3F5; bor=
der: 0; border-collapse: collapse; border-spacing: 0 !important; margin: au=
to; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; widt=
h: 600px" bgcolor=3D"#F1F3F5">
=09=09=09=09=09
          <tr>
       =
   =09<td height=3D"40" style=3D"font-size: 0; line-height: 0; mso-table-ls=
pace: 0pt; mso-table-rspace: 0pt; vertical-align: top" valign=3D"top">=
=C2=A0</td>
          </tr>

          <tr>
          =09<td style=
=3D"mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" vali=
gn=3D"top">
          =09=09<table border=3D"0" width=3D"600" cellpadding=
=3D"0" cellspacing=3D"0" align=3D"center" style=3D"background: #ffffff; bor=
der: 0; border-collapse: collapse; border-spacing: 0 !important; margin: 0 =
auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%" bgcolor=3D=
"#ffffff">
          =09=09=09<tr>
          =09=09=09=09<td style=3D"m=
so-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 40px 50px 30px; verti=
cal-align: top" valign=3D"top">

                            =09=09=09=
=09  =09<p style=3D"color:#72808e;font:400 20px/26px 'Helvetica Neue',Helve=
tica,Arial,sans-serif;padding:0">
=09  Hi <strong style=3D"color:#1e1e1e"=
>alexey zu</strong>, an account has been created for you at <a href=3D"http=
s://support.d-fis.ru" style=3D"border:0;color:#3197d6;text-decoration:none"=
target=3D"_blank">support.d-fis.ru</a>
=09</p>
=09<p>
=09=09<a href=
=3D"https://support.d-fis.ru/user-setup/NsimKHukyzVY8mjFjAs5Dp3eXOLNxpHoQ0m=
8vMBuVtOSk2CXuu0GL0WSsQQx" style=3D"background:#0078d7;border-color:#0078d7=
;border-radius:3px;border-style:solid;border-width:8px 18px;color:#ffffff;d=
isplay:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif=
;font-size:16px;text-decoration:none" target=3D"_blank">Create a Password</=
a>
=09</p>
=09<div style=3D"color:#2a3b47;font:500 20px/26px 'Helvetica=
Neue',Helvetica,Arial,sans-serif">Welcome to the team!</div>
=09<p style=
=3D"color:#72808e;font:400 16px/26px 'Helvetica Neue',Helvetica,Arial,sans-=
serif;padding:0">
=09=09Someone on your team created an account for you.=

=09</p>
                 =20
          =09=09=09=09</td>
          =
=09=09=09</tr>

          =09=09</table>
=09=09=09=09=09=09</td>
=
=09=09=09=09=09</tr>
=09=09=09=09=09<tr>
=09=09=09=09=09=09<td style=3D=
"mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" valign=
=3D"top"><table border=3D"0" width=3D"600" cellpadding=3D"0" cellspacing=3D=
"0" align=3D"center" style=3D"background: #F1F3F5; border: 0; border-collap=
se: collapse; border-spacing: 0 !important; margin: 0 auto; mso-table-lspac=
e: 0pt; mso-table-rspace: 0pt; width: 100%" bgcolor=3D"#F1F3F5">
=09=09=
=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td height=3D"25" style=3D"fo=
nt-size: 0; line-height: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; v=
ertical-align: top" valign=3D"top">=C2=A0</td>
=09=09=09=09=09=09=09</tr>=

=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td align=3D"center"=
style=3D"color: #8c93a0; font-family: 'Helvetica Neue', Helvetica, Arial, =
sans-serif; font-size: 12px; line-height: 22px; mso-table-lspace: 0pt; mso-=
table-rspace: 0pt; text-align: center; vertical-align: top" valign=3D"top">=

                                                        =09=09=09=09=09=
=09=09=09</td>
=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09<tr>
=
=09=09=09=09=09=09=09=09<td height=3D"25" style=3D"font-size: 0; line-heigh=
t: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" va=
lign=3D"top">=C2=A0</td>
=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<=
/table>
=09=09=09=09=09=09</td>
=09=09=09=09=09</tr>
=09=09=09=09</ta=
ble>
=09=09=09</td>
=09=09</tr>
=09</table>
</body>
</html>

--_=_swift_1695050447_ffb08246e6369b047894897a68f9a61e_=_--

**Comment by freescout-helpdesk** [comment]
Try some other SMTP server which does not garble outgoing emails.

**Comment by zuevav** [comment]
Thank you. I changed the settings to SMTP and enter the addresses of my server, and everything worked.
<img width="478" alt="Снимок экрана 2023-09-19 в 13 11 45" src="https://github.com/freescout-helpdesk/freescout/assets/34027267/61d855aa-e941-4334-ae57-5a509800c7bb">
