### ISSUE TITLE
Support defining a primary email address for a customer

### ISSUE THREAD

**Issue by zackkatz** [freescout-helpdesk/freescout#3210]
Emails are always sorted alphabetically, which means that a primary email may not appear first. This affects our ability to use the primary email in sidebar widgets.

## To reproduce:

1. Add an email for a customer `primary@example.com`
2. Add another email `a.not.important.email@example.com`

### What happens:

The sorting of the emails changes to have `a.not.important.email@example.com` above `primary@`

### What should happen:

There should be a way for users to override sorting.

There should be a way to define what email a customer prefers to be contacted by. This likely will need changes to the database, including adding something like a `primary` column in the `emails` table or `sort_order`.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. How are you adding emails to the customer? Can you reproduce the issue on demo.freescout.net?
