### ISSUE TITLE
Fix of #3200 does not work for the workflow-user/workflow forwards

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3211]
Dear Freescout Team,

really sorry to bother you again with this one. You´re fix works great for support agent forwards, thanks!

When forwarding a mail through a workflow, the fix of #3200 does not apply though.

We gave our Workflow-User a different name in the .env file, just as info in case this could interfere.

Thanks for taking another look!

Freescout: 1.8.86
PHP: PHP 8.2.8

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.49
