### ISSUE TITLE
Japanese Subject still garbled.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3212]
Hello. this is just report.
version master branch 6c8771375113db37f5d19984249fc44632a421f3
I experienced garbled text like this.
![スクリーンショット 2023-07-26 103019](https://github.com/freescout-helpdesk/freescout/assets/42058913/95bd27d1-265a-49ce-ba02-1df09ffd6b9a)

it should be.
![スクリーンショット 2023-07-26 103104](https://github.com/freescout-helpdesk/freescout/assets/42058913/bb85a4e4-aa01-4fd8-9ac8-b5bd3e330e9a)

and source of email.
![スクリーンショット 2023-07-26 104132](https://github.com/freescout-helpdesk/freescout/assets/42058913/4dc69255-9a3f-450e-93ac-87d0409e41c8)

Subject: =?iso-2022-jp?B?Rlc6IBskQjpGJWwlJCUiJSYlSDBNTWohIUJoGyhCMjQbJEI2cBsoQg==?=
	=?iso-2022-jp?B?GyRCQDgtYhsoQjQbJEIhIT83RURNTUUhGyhC?=

I'm sorry current decodeSubject() function is very complex and I think I could not fix it without side effect.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. The subject is decoded into: `FW: 再レイアウト依頼　第24駒生№4　新田様邸`

**Comment by totake0224** [comment]
I'm very sorry.
I may have done something wrong. I will recheck my environment.
