### ISSUE TITLE
freescout.net/request-feature is not working?

### ISSUE THREAD

**Issue by pool-alpin** [freescout-helpdesk/freescout#3213]
When trying to access `https://freescout.net/request-feature/` it forwards to a uservoice page that only shows "Loading..."  

Has the feature request page been moved?

**Comment by raramuridesign** [comment]
@pool-alpin looks correct and has been like this for sometime.

**Comment by freescout-helpdesk** [comment]
Sometimes uservoice experiences some technical issues - in such cases just try after some time.
