### ISSUE TITLE
IMAP Connection Issue: Unexpected host name

### ISSUE THREAD

**Issue by cbettinger** [freescout-helpdesk/freescout#3214]
I try to fetch mails using IMAP. The IMAP connection parameters I am using in Freescout work perfectly when used in an regular e-mail client.

The error log says (domain replaced with `XXX`):

> `Error: imap_open(): Couldn't open stream {imap.XXX:993/imap/ssl}. Can't connect to imapv.XXX,993: Connection timed out; File: /var/www/html/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)`

I am a bit confused about the suffix "v" in "imapv" in the second log sentence. Where does this come from and is it expected?

FreeScout version: 1.8.86

**Comment by freescout-helpdesk** [comment]
What do you have in "Server" field in "Mailbox >> Connection Settings >> Fetching Emails"?

**Comment by cbettinger** [comment]
imap.XXX, not imapv.XXX

**Comment by freescout-helpdesk** [comment]
We have no idea what can be the reason. It need to be investigated on your server.
