### ISSUE TITLE
Chinese Characters in imported emails

### ISSUE THREAD

**Issue by ConvarDeutschland** [freescout-helpdesk/freescout#3215]
PHP version:  PHP 7.4.33
FreeScout version: 1.8.74

Hello we have some problems with emails fetch from our email server. Sometimes the body result in an  chinese text.
The original email that was BCC to our email archiv server is fine. Only the email imported in freescount has the chinese text.

The same email send again to an other email account using evolution mail is also fine to be read.

I think somewhere in the process of get the mail from the email server and import the body in the database some encoding is done that should not happend. How can we solved this?
![Screenshot from 2023-07-26 14-32-14](https://github.com/freescout-helpdesk/freescout/assets/14978257/65cf1906-0496-4c08-b224-e955c623e008)

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP authentication or APP_NEW_FETCHING_LIBRARY parameter in .env file?

Try to update FreeScout to the latest version.

Try to send an example of the email to [support@freescout.net](mailto:support@freescout.net)

**Comment by ConvarDeutschland** [comment]
Hi,

we do not use modern Microsoft OAuth IMAP authentication or APP_NEW_FETCHING_LIBRARY parameter in .env file.
we will update to new version, but problem was in all versions we had till now.

Which email should be send to support ? the one in Freescout or the original one?

**Comment by freescout-helpdesk** [comment]
Forwarding us an email you received won't work. If you can't produce an email and send us we can't investigate the issue.
