### ISSUE TITLE
SentFolder Module - Missing public directory causes broken symlink

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3217]
Hello.

It does not cause any harm but when I activate the SentFolder Module, a broken symlink is created under /public/modules. I think this happens because this module is missing a public directory and freescout creates the symlink anyway in this method

https://github.com/freescout-helpdesk/freescout/blob/cf2f488aaf8e30990f45bd1fd70135d5ca5711a8/app/Console/Commands/ModuleInstall.php#L89

Thanks in advance

**Comment by freescout-helpdesk** [comment]
It's by design.
