### ISSUE TITLE
Move Spam to Spamfolder on IMAP server too

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3220]
Hi,

we have rspamd set up on our email-server and it learns with each messag that is moved to the spam folder. When you mark a conversation as spam in freescout it is not moved on the IMAP-server unfortunately, it only gets marked in freescout. So since using freescout we have not been able to train rspamd.

Is there a possibility to move the mail to the IMAP-junk-folder when marking it as spam in freescout?

Thanks a lot!

Freescout: 1.8.86
PHP: PHP 8.2.8

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. Maybe someone can implement it via a custom module.
