### ISSUE TITLE
Problems with workflows containing date-related conditions

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3221]
Hi,

we´re having problems with workflows containing date-related conditions or we are not sure if we understand them correctly.

For example the action of the following workflow should get started automatically 1 hour after the last user reply if the ticket is pending, right? The goal is to close tickets, if the customer does not respond within a given timeframe, 1 hour was just for testing purposes.

![Conditions-2](https://github.com/freescout-helpdesk/freescout/assets/134635748/f76e054c-8067-438d-a55d-d8c519f993c2)

If we set it to "apply to previous conversations" the workflow works.

We saw that queue:work is always "Running". It never shows as "Last successful run: ...". Is that how it is supposed to look or is something with the queue:work going wrong?

![queue-work](https://github.com/freescout-helpdesk/freescout/assets/134635748/accfa7af-f0f6-4909-914f-704a4fe20b88)

Workflows without date-related conditions (e.g. on change of status) work fine. Snoozing also works perfectly fine, which is kind of a date-related reactivation.

Thanks for your help! :)

Freescout: 1.8.86
PHP: PHP 8.2.8

**Comment by freescout-helpdesk** [comment]
> If we set it to "apply to previous conversations" the workflow works.

This checkbox should be always set in your case.

**Comment by githubuser-112** [comment]
Thanks, seems to work! Should this workflow work always **exactly** 1 hour after the last user reply? It was processed 1 hour and 3 minutes after.

The following workflow in our tests was worked 1 hour and 40 minutes and 1 hour and 47 minutes after on other tickets.

![unassign](https://github.com/freescout-helpdesk/freescout/assets/134635748/576b7bea-af81-409d-99ad-4581b0d625ef)

What can we do so the workflow gets processed at the exact time?

**Comment by freescout-helpdesk** [comment]
Something is wrong with your background jobs: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

**Comment by githubuser-112** [comment]
Hey, could you take a look at our processes if there's something that does not look right?

```
web11    1413383  0.0  0.0  48088  3152 ?        S    14:01   0:00 sh -c '/opt/php-8.2/bin/php' 'artisan' queue:work --queue='emails,default,1da7b20b9daf157d72d52efb2a105583' --sleep=5 --tries=1 --timeout=1800 > '/var/www/clients/client1/web11/web/storage/logs/queue-jobs.log' 2>&1
web11    1413384  0.0  0.1 358460 73028 ?        S    14:01   0:01 /opt/php-8.2/bin/php artisan queue:work --queue=emails,default,1da7b20b9daf157d72d52efb2a105583 --sleep=5 --tries=1 --timeout=1800
```

Thanks!
