### ISSUE TITLE
Module: Ticket Translator Module

### ISSUE THREAD

**Issue by yabloky** [freescout-helpdesk/freescout#3222]
Guys, the module is awesome! It's cool that it translates clients' messages, but it will be just wow if you make it possible to translate my answers to the client into the client's language and send them translated. 

And also that it would memorise my language to which it should be translated, each time to choose - it is not convenient.

**Comment by freescout-helpdesk** [comment]
> if you make it possible to translate my answers to the client into the client's language and send them translated.

Feel free to submit the feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
> And also that it would memorise my language to which it should be translated, each time to choose - it is not convenient.

This has been implemented in Ticket Translator Module v1.0.8

**Comment by yabloky** [comment]
> > And also that it would memorise my language to which it should be translated, each time to choose - it is not convenient.
> 
> This has been implemented in Ticket Translator Module v1.0.8

Where is this setting? Every time I click "translate" I get a window with two dropdowns and in the second one I select a different language each time.

*of course I will offer the desired functionality on your link. Thank you.

**Comment by freescout-helpdesk** [comment]
The module now remembers "Into" field in the Translate modal.
