### ISSUE TITLE
help with installation and setting up

### ISSUE THREAD

**Issue by cimenta** [freescout-helpdesk/freescout#3223]
Hi
I am looking for helpdesk support system. And looks like freescout could the one.  I am looking for someone who would help me to confirm that all my requirement are met and then install freeshout (somewhere in the cloud) and help me to set it up.

I need 

- the helpdes to be multilingual for now English and Czech languages
- to support few projects and have more than one support agent
- creating of new support tickets could be done via email and via web form. Ideally I need different form and different email for each project
- Knowledge base - ideally different for each project

Thank you
Radek

**Comment by freescout-helpdesk** [comment]
FreeScout support these features with modules help (https://freescout.net/modules/).

**Comment by cimenta** [comment]
I know, I read that page. I hoped that someone would help me not just close this ticket. To be honest I expected different response from official helpdesk.
