### ISSUE TITLE
Module: Custom Fields Module

### ISSUE THREAD

**Issue by yabloky** [freescout-helpdesk/freescout#3224]
Do I need to manually add 2-3 active links to each client? I found the Multi line field - but the links added there are not active. I also found the Links field, but it is impossible to insert arbitrary links there, but only templates from client fields? And how can I make a field with a list of active arbitrary links? Thank you.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
