### ISSUE TITLE
Module: Chat

### ISSUE THREAD

**Issue by yabloky** [freescout-helpdesk/freescout#3225]
Thanks for the module. Everything is great, only one request. Let you change the names of contact fields, hide them and ideally add custom ones. 

For example, I don't need the phone number of my clients, and this field can scare away clients, so I would disable it and the user would see the standard "Name" and "Email" when opening a chat, and if it was possible to change these fields, I would change the word "phone" to Telegram or WhatsApp, which would greatly increase the chances that the client will share the username. 

Also, there is a problem (which is critical on mobile devices) if you open a chat window and change your mind to contact and fill in the data - the window can not be closed, until you fill in the data do not save and minimise it - this is not right.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
> Also, there is a problem (which is critical on mobile devices) if you open a chat window and change your mind to contact and fill in the data - the window can not be closed, until you fill in the data do not save and minimise it - this is not right.

Fixed in Chat Module v1.0.26
