### ISSUE TITLE
Make the Option "Send emails separately to each recipient" always active per default

### ISSUE THREAD

**Issue by Ephesus666** [freescout-helpdesk/freescout#3226]
Hello there

Is there a possibility to make the checkbox "Send emails separately to each recipient" on E-Mails to more then one recipient market active per default? That would help us a lot.

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. It can be implemented via a custom module.

**Comment by Ephesus666** [comment]
Is there already a Module that can do that? We are no developer, so it would not be possible do made one :(

**Comment by freescout-helpdesk** [comment]
Not yet.
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
