### ISSUE TITLE
Upstream timed out (110: Connection timed out)

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3227]
Dear Freescout-Team,

we are seeing the following error in our Server error log a lot recently. There are no errors in the Freescout error log though. 

> 2023/07/31 01:34:06 [error] 31820#31820: *113694644 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.70, server: domain.name, request: "POST /polycast/receive HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web11_f01dd6a2.sock", host: "domain.name", referrer: "https://domain.name/"

Any idea how to check what´s causing that problem? Only increasing the timeouts does not seem like the preferred solution.

PHP version: PHP 8.2.8
FreeScout version: 1.8.86

**Comment by freescout-helpdesk** [comment]
How many support agents do you have?

Any errors in Manage > Logs > App Logs?

**Comment by githubuser-112** [comment]
We have 7 user accounts, but only 2 of them are really working at the same time, the rest is just occasionally using freescout.

We have errors, but they don´t coincide with the error log of the server. So we see the error in the server log on days that do not have any errors in the freescout app log.

**Comment by freescout-helpdesk** [comment]
There are some problems with connection between your browser and web server. It need to be investigated on your end and on your server.
