### ISSUE TITLE
Last name not first name

### ISSUE THREAD

**Issue by j0urna1ist** [freescout-helpdesk/freescout#3229]
It is required to be able to change the display of the last name instead of the first name of the agents.
First names are repeated more often than last names. Very often there are problems with assigning tickets to agents who have the same names:
Phil Spencer
Phil Soner
Phil Ryden

**Comment by ilyakonovalenko** [comment]
You can just use "Scencer Phil" instead of "Phil Spencer".
I don't personally think changing the display is a good idea. Very rare case.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to implement this.
