### ISSUE TITLE
Way to order Unassigned by oldest first?

### ISSUE THREAD

**Issue by BrianGilbert** [freescout-helpdesk/freescout#323]
In our use case we'd ideally like to process older emails first, so it would be great if there was a way to set this as a default sort order, an have the ability click the 'Waiting since' header to reverse the order.

**Comment by psuter80** [comment]
actually it would be nice if any ticket-list could be sorted by any of the columns in either way (i mean ascendig or decending) by just clicking on the title, like in most email clients. What are they currently ordered by? i can't seem to find any order in the lists at the moment.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/919
