### ISSUE TITLE
Send emails from user personal account (or Send On Behalf)

### ISSUE THREAD

**Issue by lpgab** [freescout-helpdesk/freescout#3230]
Hi there,

Is there any way to set up a mailbox so that replies to clients are sent from the user's "personal" account instead of being sent from the shared mailbox account?

The "Send On Behalf" functionality would also be useful for me. 
Is there any way to achieve this? 

Thank you very much!

**Comment by freescout-helpdesk** [comment]
Unfortunately not and there is no plans to implement this.
