### ISSUE TITLE
Replies to closed conversations being merged into single (incorrect) conversation

### ISSUE THREAD

**Issue by verygoodplugins** [freescout-helpdesk/freescout#3231]
I have checked the logs for errors ✅ 
I have read the FAQ ✅ 

PHP version: 8.0.29
FreeScout version: 1.8.86

We have a recurring and somewhat frustrating issue whereby if a customer replies to a closed conversation, in some cases those replies are being attached to the wrong conversation. It is always the same wrong conversation, ID #9476, with subject line "_Re: UM: Profile Completeness_"

This conversation #9476 was originally opened in April 2020. It was closed on April 20th, 2020.

The first instance of the problem happened shortly after we moved to FreeScout from HelpScout. Customer "Tim" replied to a conversation that was previously closed in HelpScout, with subject "_Re: WooMemberships Profile Field Checkbox to Keap Checkbox_".

We are using Gmail for the IMAP inbox. Here we can see the new message from the customer. It's correctly in its own thread:

![image](https://github.com/freescout-helpdesk/freescout/assets/13076544/0b112534-b2bf-4b1f-8a63-002292a059f4)

Here we can see in FreeScout the customer's existing conversation that was imported from HelpScout:

![CleanShot 2023-08-01 at 13 42 29@2x](https://github.com/freescout-helpdesk/freescout/assets/13076544/ae349ab2-06d5-47e0-abb6-26f3dedcd5d6)

The conversation ID is 24558. The subject line is the same. The conversation is correctly associated with the customer in the sidebar.

**Expectation:** Any replies by this customer to this conversation would be attached to this conversation ID ✅ 

Instead, the reply is attached to this conversation #9476. In this first instance, it re-opened the closed conversation from 2020:

![CleanShot 2023-08-01 at 13 45 14@2x](https://github.com/freescout-helpdesk/freescout/assets/13076544/5e2abff2-021f-4b7c-ad67-fa0add802088)

You can also see in the screenshot that several replies from other random customers have become attached to this conversation. 

So far this has happened to about 8 customers. We've been fixing it by going into the _threads_ database table and manually changing the `conversation_id` back to the correct one... but obviously this isn't practical long-term.

Some other notes:

1. In the majority of cases, replies to closed conversations re-open the correct conversation. I'd say it's only failing maybe 10% of the time.
2. As far as I can tell, all of the replies have "Re:" in the subject line. Conversation #9476 also has Re: in the subject line, perhaps this is causing a false match?
3. All the threads that go to the incorrect conversation end up on this one with ID #9476, from 2020. They never attach to other conversations.

Any suggestions? 🤔 

It seems to me like something in the message-to-conversation matching logic is incorrectly thinking these replies are replies to #9476.... but I don't know where to start troubleshooting it. Here are the headers from one of the messages that were incorrectly attached to this conversation: https://pastebin.com/szikCg3A

My first thought is to just delete #9476, but I'm afraid then the replies might start re-opening _random_ old conversations. At least at the moment we have all the orphaned threads in a single conversation ID.

Thanks for your help 🙂

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#sometimes-customer-replies-are-connected-to-the-wrong-conversation-in-freescout

**Comment by verygoodplugins** [comment]
I saw this, but it was marked closed and fixed in December 2022. We've only been using FreeScout for one week, and the latest version is installed.

**Comment by freescout-helpdesk** [comment]
"In order to avoid this issue you need to update your FreeScout to the latest version **and ask your customer to do the same**."

**Comment by verygoodplugins** [comment]
I see. Thanks. I will ask the customer if they are using FreeScout.

I saw the message ID `Message-ID: <CABrk3k94TJZOJ8kP176oc_JnFCcQCaJYMbg+mvmUtC+AcQOT6A@mail.gmail.com>` and assumed the message was sent by Gmail.

I checked the other message IDs as well and most are from Gmail. One is a custom domain.

Regardless, this is happening every day... we've only been using FreeScout for a week. If this is indeed the issue, it means hundreds (maybe thousands) of our customers are using outdated versions of FreeScout 🤔 

We can't practically ask all of them to upgrade. Is there anything we can do from our end? Would deleting this conversation #9476 help, or would they just start getting attached to another random conversation?

**Comment by freescout-helpdesk** [comment]
Try to debug this: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L378

You can use `\Log::error('Some text: '.$prev_message_id);` to write message to "Manage > Logs > App Logs"

**Comment by verygoodplugins** [comment]
I've heard back from two of the affected customers and they are not using FreeScout. One is using standard Gmail, another is using Gmail Pro with a user alias domain.

I've added the logging. The issue hasn't happened yet today but I'll try and capture what I can from `FetchEmails.php` and report back. Thanks for your help 🙏

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by verygoodplugins** [comment]
Nice 🔥. Makes sense to me. I've just patched it on the site, assuming that'll do it 🤞 

Thanks again for the assist!

**Comment by LIJIN395** [comment]
im also facing email mergining issue with old thread email
...how resolve..with differnet subject also its going to merge
