### ISSUE TITLE
too large body error => mail now "pending"

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3232]
Dear freescout team,

we had a error today: `client intended to send too large body`

We already increased the limit, which was way too small. But now the agents response is "pending". Under "outgoing email" is says that it was accepted for delivery. Was the mail sent or is it pending for sending? And if it is pending, how do we make sure it gets sent again?

![pending](https://github.com/freescout-helpdesk/freescout/assets/134635748/73b31f8c-02de-4657-899f-8805099dbc97)
![outgoing](https://github.com/freescout-helpdesk/freescout/assets/134635748/9a0fa70a-4a6c-4e44-a4b8-ab164a15804d)

Thanks a lot

PHP version: PHP 8.2.8
FreeScout version: 1.8.86

**Comment by freescout-helpdesk** [comment]
> we had a error today: client intended to send too large body

Where?

**Comment by githubuser-112** [comment]
In the conversation from which I posted the screenshots:

> client intended to send too large body: 3109929 bytes, client: xx.xx.xx.xx, server: domain.name, request: "POST /conversation/upload HTTP/2.0", host: "domain.name", referrer: "https://domain.name/conversation/707?folder_id=4"

**Comment by githubuser-112** [comment]
This is the only ticket and the only message in all of our system that shows pending there. None of the other "pending" tickets have this info.

**Comment by githubuser-112** [comment]
And that means the server has sent this mail even though it showed this error? Any way we can check this, as the sent folder of the mailbox is empty?
