### ISSUE TITLE
Failed App\Jobs\SendReplyToCustomer Job

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3234]
Hey,

we're seeing some failed App\Jobs\SendReplyToCustomer Jobs, but the error message is not very descriptive. It just says "Error occurred. Please try again later.". What can we do to find out what happend? On retrying the Job, it fails again.

![error](https://github.com/freescout-helpdesk/freescout/assets/134635748/b06d792e-2487-410d-b560-12d0d6a407f3)

Thanks!

Freescout: 1.8.86
PHP: PHP 8.2.8

**Comment by freescout-helpdesk** [comment]
Check logs in Manage > Logs: App Logs and Send Errors.

**Comment by githubuser-112** [comment]
There are no Errors in Send errors for those dates. Only two old ones.

![send-errors](https://github.com/freescout-helpdesk/freescout/assets/134635748/0295c669-88ad-44bc-b19c-c218286dcc47)

There are errors in App Logs, but nothing that has to do with mail sending:

```
Attempt to assign property "type" on null {"userId":6,"email":"user@domain.name","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Attempt to assign property \"type\" on null at /var/www/clients/client1/web11/web/app/Http/Controllers/ConversationsController.php:1389) 
```

```
Attempt to read property "mailbox_id" on null {"userId":6,"email":"user@domain.name","exception":"[object] (ErrorException(code: 0): Attempt to read property \"mailbox_id\" on null at /var/www/clients/client1/web11/web/app/Http/Controllers/ConversationsController.php:2464) 
```

**Comment by freescout-helpdesk** [comment]
Debug it: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php

**Comment by githubuser-112** [comment]
We are getting these errors every day and there are no errors in Send Errors or App Logs. Shouldn't there be an error information other than `Error occurred. Please try again later.`? 

Does not seem like it was intended to debug in the code just to get the error message.

**Comment by freescout-helpdesk** [comment]
There should be some info in Manage > Logs: App Logs and Send Errors but by some reason you don't have it. So the only way is to debug it on your end.
