### ISSUE TITLE
Empty mail: When customers using a webmailer and put their reply between "Please reply above this line" and "On YYYY-MM-DD help wrote:" 

### ISSUE THREAD

**Issue by cluster15** [freescout-helpdesk/freescout#3235]
Hi,
strictly speaking this is not a bug, the software does, what it is seemingly supposed to. But we have an increasing number of replies where customers using a webmailer (roundcube), and then taking the "Please reply above this line" literally leading to  their reply looking like e.g.:

On 2023-08-02 12:12, Helpdesk wrote:
> Dear Helpdesk, 
>  
> many thanks for your answer, please find the requested information attached
>  Best regards
>  
> -- Bitte über dieser Linie antworten/Please reply above this line --

consequently freescout does not display the content of the reply. 

The content gets the ">" prepended by the webmailer the customers use (roundcube). The reason is that the webmailer inserts an empty cited line (with a leading ">") between "On 2023-08-02 12:12, Helpdesk wrote:"  and the "Please reply above...". So if they start their reply there, all lines of the reply get the ">" prepended. 

If  they use a simple mail program or app, usually the ">" is not prepended, even when they start their reply at the same line and then the mail is not displayed as empty, but the "On 2023-08-02 12:12, Helpdesk wrote:" is still part of the customer's reply and somewhat confusing. 

Probably a simple rewording might help:  "Please reply right at the top of this email". Although, I am not certain it will always work. 

Best regards, 
   Stefan

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-a-customer-replies-within-the-cited-text-freescout-does-not-show-it

**Comment by cluster15** [comment]
I know that, I've read the FAQ and browsed through the closed and opened issues. 
The problem is the customers from their point of view follow the rule and reply right above that line, but below the "On 2023-08-02 12:12, Helpdesk wrote:" line. In combination with the damn roundcube webmailer, they start typing in the cited email region, thus the mail content will not be displayed. What I think is actually meant by the separator-line  is that the customers should reply above _any cited email content_, and I was thinking, whether that could be more accurately  stated in the reply separator. 
I patch the freescout  installation here and now use "Please reply above this email" and I will report, whether it improves the situation.
