### ISSUE TITLE
web push instead of websockets

### ISSUE THREAD

**Issue by morta5** [freescout-helpdesk/freescout#3237]
Hello everyone,

thanks for making this great help desk!
I wanted to suggest using web push instead of websockets as they also deliver notifications when the browser/tab is closed and work on mobile too. 
I think it would be more secure than the current push plugin for mobile too as it wouldn't involve a third server (which I think is getting used here?) which gets the unencrypted notification contents.
You could for example use this library to implement web push: https://github.com/web-push-libs/web-push-php

**Comment by freescout-helpdesk** [comment]
Maybe in the future. Browser support for web push notifications is still quite weak: https://caniuse.com/push-api

**Comment by morta5** [comment]
Yeah but that's really only Apple not supporting it. 
But thanks for considering implementing it in the future!

**Comment by morta5** [comment]
Maybe now web push makes sense? 
It is available for almost 95% of all devices according to the linked website.
Websockets is available for 96% of all devices.
