### ISSUE TITLE
Sending Emails:  SMTP Header

### ISSUE THREAD

**Issue by flowdee** [freescout-helpdesk/freescout#3238]
When sending emails via Postmark and IMAP, you sometimes have to set a custom header to use their correct message stream.

![Bildschirmfoto 2023-08-04 um 13 12 15](https://github.com/freescout-helpdesk/freescout/assets/2278756/7f4ad76a-fbe4-4f19-b363-3a243bce9718)

Unfortunately, right now, FreeScout does not support that. 

![Bildschirmfoto 2023-08-04 um 13 14 09](https://github.com/freescout-helpdesk/freescout/assets/2278756/248e73e2-ed57-425d-804a-677cf57d96d5)

It would be great to have a way to add those (optional) headers such as `X-PM-Message-Stream: support` like in the case of Postmark.

**Comment by freescout-helpdesk** [comment]
This can be done via a custom module.

**Comment by flowdee** [comment]
I would consider this as core functionality 🤯
