### ISSUE TITLE
Workflows Module: customer does not receive an email notification

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#3240]
Hello,

When using action "Email to customer" which is executing right after new conversation created, customer will not receive the email's text via email. Rather FreeScout sends customer's initial message to the customer email with subject "Re: ...".

**Comment by freescout-helpdesk** [comment]
Can you share screenshot of the Conditions tab.

**Comment by ilyakonovalenko** [comment]
Yes, sure.
![изображение_2023-08-05_113756003](https://github.com/freescout-helpdesk/freescout/assets/63669538/f1e759f4-2a94-47a9-b400-d35ab19bdd72)

**Comment by freescout-helpdesk** [comment]
How does the customer create a conversation?

**Comment by ilyakonovalenko** [comment]
We use API module to create the conversations. Not sure if it happens for normal emails, but it always happens for API-created conversations.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
