### ISSUE TITLE
Installation Freescout in IIS Error 404 

### ISSUE THREAD

**Issue by hgolshenas** [freescout-helpdesk/freescout#3242]
@freescout-helpdesk
i have the 404 error while installing latest version of freescout in  iis 10, php 8.1.21 and mysql 5.7
all the steps in instructions are done
what should i do?

Cheers

**Comment by freescout-helpdesk** [comment]
Find someone who can do it for you: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
