### ISSUE TITLE
Telegram bot automation

### ISSUE THREAD

**Issue by yabloky** [freescout-helpdesk/freescout#3243]
Hi.

Once again I want to thank you for the wonderful system and have a question, about the telegram bot - is there any possibility of automation? Right now the only automation is a pre-made message in response to /start, I need to add a FAQ to the bot, i.e. a series of buttons in the bot, when clicked on which the bot gives a pre-made message. Can you please tell me what service can be used to realize this? Maybe someone has successful cases?

**Comment by freescout-helpdesk** [comment]
The only way for now is to manually amend Telegram Integration Module. It uses `botman/driver-telegram` library.
See for example: https://github.com/botman/driver-telegram/issues/43

**Comment by yabloky** [comment]
Thanks for the quick reply! Any instructions or proper google queries? I haven't come across this before.

**Comment by freescout-helpdesk** [comment]
Actually the module is designed to allow support agents communicate with customers. For creating interactive Telegram bot we'd recommend develop something else.

**Comment by yabloky** [comment]
Yes, you are right, but if you screw to the module a couple of buttons with prepared answers - it will greatly facilitate and relieve the operators )
