### ISSUE TITLE
Default MAILTO Protocol

### ISSUE THREAD

**Issue by Io-Qo** [freescout-helpdesk/freescout#3244]
Couldn't find a previous request but I would find it extremely helpful if FreeScout was to ask to handle the MAILTO protocol to make it my default mail application when I click on a "mailto:" link. Would that be possible?

![image](https://github.com/freescout-helpdesk/freescout/assets/105042120/5dea1aed-0ed0-4491-a0fd-1c76184e0845)

**Comment by Io-Qo** [comment]
You can define that systemwide. What I'm thinking of is this tutorial here:
https://4sysops.com/archives/set-chrome-firefox-edge-as-default-mail-client-mailto-handlers/

Which FreeScout could implement like this I think:
https://web.dev/registering-a-custom-protocol-handler/

So whenever I click a mailto link anywhere on my system, it will open a FreeScout E-Mail. Would that be possible?

**Comment by freescout-helpdesk** [comment]
This does not seem to be a very required feature. Feel free to submit a feature request at https://freescout.net/request-feature/ - maybe someone will implement it as a module.

**Comment by Io-Qo** [comment]
Thank you for your response! I don't think though it needs to be a separate module and a mail application should come with this functionality. It's not an exotic request, all mail apps offer this option and I think it would be appreciated within the community. It's just that few people know you can actually register web apps as default mail apps but it's super handy once set up.

 All it would need is a button maybe in the user settings that triggers this one javascript line:
`navigator.registerProtocolHandler( 'mailto', 'https://mail.freescout.net/mailbox/{mailbox-id}/new-ticket&q=%s', 'FreeScout');`
I did it with a javascript injection extension and it works perfectly fine, except two things:
- the "%s" variable needs to be processed correctly to hand over the address
- there should be a dropdown on the button to select the default mailbox for new mails

Otherwise this one line does the trick, maybe you reconsider my request, I would appreciate it. I think the workload to implement this feature is rather small. Anyway, have a great weekend!

**Comment by sofl88** [comment]
I'd suggest writing a tiny custom module. We did this a while back and added a custom route for the protocol handler which allowed us further validation of the mailto uri and a mailbox selection if the user had multiple access.

**Comment by Io-Qo** [comment]
> I'd suggest writing a tiny custom module. We did this a while back and added a custom route for the protocol handler which allow us further validation of the mailto uri and a mailbox selection if the user has multiple access.

That's awesome and exactly what I need, would you be willing to share this module with me?
