### ISSUE TITLE
pcntl (console PHP) wrongly shown as not present

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#3245]
PHP version: 8.1.22
FreeScout version: 1.8.89

(Related: https://github.com/freescout-helpdesk/freescout/issues/3190)

On the page `/system/status`, I see: `pcntl (console PHP) 	Not found`.

It is,however, present:

```
# php81 -i | grep pcntl
pcntl
pcntl support => enabled
```

If I do `ln -s /bin/php81 /bin/php` then the page then displays `pcntl (console PHP) 	OK`. So, apparently Freescout insists on using `/bin/php`. for its external calls. That doesn't exist on my system, where I've installed the popular "remi-safe" repository (for RHEL, Rocky, Oracle, AlmaLinux etc.), which installs packages so that they don't clash with any system packages (https://rpms.remirepo.net/). And in my case, I haven't installed the system PHP anyway as I have no other need for it. So there just is no `/bin/php`.

I don't know what would be best. Perhaps it could carry an array of possibilities, or make it configurable so that the system owner can point to the desired binary.

**Comment by freescout-helpdesk** [comment]
You've made sure this extension is installed in your console PHP, so you can just ignore this warning on Status page.

**Comment by freescout-helpdesk** [comment]
Checking `pcntl` extension is the only place where FreeScout makes external PHP binary call.
