### ISSUE TITLE
Problems with background jobs

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3246]
Hi, 

because of problems with our background jobs we checked the steps in your wiki. 

In the first step, your processes look a little different. Could you take a look and tell us, if something in our processes could be the cause?

```
web11    1413383  0.0  0.0  48088  3152 ?        S    14:01   0:00 sh -c '/opt/php-8.2/bin/php' 'artisan' queue:work --queue='emails,default,1da7b20b9daf157d72d52efb2a105583' --sleep=5 --tries=1 --timeout=1800 > '/var/www/clients/client1/web11/web/storage/logs/queue-jobs.log' 2>&1
web11    1413384  0.0  0.1 358460 73028 ?        S    14:01   0:01 /opt/php-8.2/bin/php artisan queue:work --queue=emails,default,1da7b20b9daf157d72d52efb2a105583 --sleep=5 --tries=1 --timeout=1800
```

Thanks a lot!

PHP version: 8.2.8
FreeScout version: 1.8.8

**Comment by freescout-helpdesk** [comment]
Your processes list looks fine.

**Comment by githubuser-112** [comment]
Thanks for checking! We do not know what to do, because everything looks fine, but workflows like this do not fire at exactly 1h but at 1:40, 1:45 or 1:48. 

![grafik](https://github.com/freescout-helpdesk/freescout/assets/134635748/1dcf9ec6-547e-443c-af48-a7c063cc86c2)

Any other idea what we could look for or do?

**Comment by freescout-helpdesk** [comment]
We've just double checked - the workflow was triggered after 1 hour and 5 minutes.
You'll need to debug Workflows code on your server.

**Comment by freescout-helpdesk** [comment]
Try:
```
WORKFLOWS_PROCESS_CRON="0 * * * *"
```

**Comment by githubuser-112** [comment]
Thanks, this solved our problem we were trying to fix for weeks now!!

 It would have been great though if this information was publically available as you told us various times that we have problems with our background-jobs even though it was only delayed because of this setting. With the standard setting every time-related workflow can take up to an hour to be processed after it has met its conditions. This is pretty counter-intuitive and should be mentioned in the https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
