### ISSUE TITLE
hosting issue thousands of files 

### ISSUE THREAD

**Issue by epp289** [freescout-helpdesk/freescout#3247]
May i ask you i have problem with my hosting company. They say that i have a lot of files
![image](https://github.com/freescout-helpdesk/freescout/assets/75975706/ebebc091-cf93-40dc-a76c-a40887aa0c31)

Is it coming from the two freescout installations i have? What do you think?

the sql databases look okay 1gb the one and 845 mb the other
![image](https://github.com/freescout-helpdesk/freescout/assets/75975706/08a2ea9c-632a-46a8-be17-abc9a3a285eb)

i see that there is a vmail folder beside the public_html folder what is it? 
The freescout sends and fetches the emails through gmail servers
Do you think that i can change something or do i have to move to a managed server? thank you

**Comment by epp289** [comment]
i see that
the most files are stored in the mailboxes:

721182  ./vmail  ( => Mailboxes, folder cannot be viewed via webFTP )


What do you suggest? thank you

**Comment by freescout-helpdesk** [comment]
Do you have Postfix/Dovecot on your server?

**Comment by freescout-helpdesk** [comment]
./vmail folder does not belong to FreeScout, so you'll need to find out what software writes files there.
