### ISSUE TITLE
Sometimes the extensions of attached files are corrupted

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3248]
Sometimes emails from customers show the wrong file extension:

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/f46a3d5d-e532-4cd7-8df7-4e64dd78d469)

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/1187f9a1-83c8-4140-b11c-1dfd1dc880d8)

But if you look at the email in Thunderbird or the webmail, the file extension is correct:

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/b9b8ad00-674e-45ed-a58d-165a4dec5496)

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/c5b6340c-79be-416c-b032-94c0b73e26ec)

Here's the data from the source of the message:

```text
Content-Type: application/octet-stream;
	name="=?koi8-r?B?69fP1NkuLfTF09QtMS4t9MXT1C3Tz8/U18XU09TXydEty8HUxcfP0snJLmpz?=
 =?koi8-r?Q?on?="
Content-Description:
	=?koi8-r?B?69fP1NkuLfTF09QtMS4t9MXT1C3Tz8/U18XU09TXydEty8HUxcfP0snJLmpz?=
 =?koi8-r?Q?on?=
Content-Disposition: attachment;
	filename="=?koi8-r?B?69fP1NkuLfTF09QtMS4t9MXT1C3Tz8/U18XU09TXydEty8HUxcfP0snJLmpz?=
 =?koi8-r?Q?on?="; size=28217;
	creation-date="Mon, 31 Jul 2023 09:35:26 GMT";
	modification-date="Fri, 07 Jul 2023 08:40:35 GMT"
Content-Transfer-Encoding: base64
```

```text
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document;
	name="=?koi8-r?B?7MHCzsVf5M/NwdvOxcUg1MXT1MnSz9fBzsnFK0NUIHY0IGNvcnIgbmV3LmRv?=
 =?koi8-r?Q?cx?="
Content-Description:
	=?koi8-r?B?7MHCzsVf5M/NwdvOxcUg1MXT1MnSz9fBzsnFK0NUIHY0IGNvcnIgbmV3LmRv?=
 =?koi8-r?Q?cx?=
Content-Disposition: attachment;
	filename="=?koi8-r?B?7MHCzsVf5M/NwdvOxcUg1MXT1MnSz9fBzsnFK0NUIHY0IGNvcnIgbmV3LmRv?=
 =?koi8-r?Q?cx?="; size=124856;
	creation-date="Tue, 25 Jul 2023 21:03:59 GMT";
	modification-date="Tue, 25 Jul 2023 15:27:19 GMT"
Content-Transfer-Encoding: base64
```

PHP version: 7.4.33
FreeScout version: 1.8.86

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
