### ISSUE TITLE
Workflow action: Email the customer - missing subject

### ISSUE THREAD

**Issue by flowdee** [freescout-helpdesk/freescout#3249]
![Bildschirmfoto 2023-08-09 um 11 09 39](https://github.com/freescout-helpdesk/freescout/assets/2278756/ba30b0b1-256d-4527-a32d-2ad5fee6cecc)

In the workflow actions, I can "email the customer" but I can't define a subject which will be used for the email the customer receives? This is not good, especially when it comes to opening rates.

**Comment by freescout-helpdesk** [comment]
Conversation subject is used.

**Comment by flowdee** [comment]
Mh doesn't sound right if you ask me.

For this, I would have selected "Add reply to conversation", isn't it? 

When selecting "Email the customer", I would assume that It's a new conversation

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by arjit65** [comment]
I also recommend this feature to be included in Workflow Module

. Its mostly used in all support desk solutions.
