### ISSUE TITLE
Update is not working 

### ISSUE THREAD

**Issue by PaulBartelings** [freescout-helpdesk/freescout#3250]
Hi,
I hope you can help me.

I have an installation for a long-time, and it will not update anymore.

I hope you can tell me what to do.

Thanks, Paul

[laravel-2023-08-09.log](https://github.com/freescout-helpdesk/freescout/files/12300576/laravel-2023-08-09.log)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
