### ISSUE TITLE
Rocky 8 Installation

### ISSUE THREAD

**Issue by MaMi364** [freescout-helpdesk/freescout#3251]
Hey, I've been trying to install freescout for 2 days now I don't know what more I can do to just install it.
I am working on a rocky 8 linux trying to install it locally with an ip and trying to access the install page on Chrome windows. I have followed the installation of Freescout while it was for ubuntu I managed to do everything for rocky 8. That didn't work both Nginx and apache. After a few more tries I found this guide https://techviewleo.com/install-freescout-help-desk-on-centos-rocky-rhel/?expand_article=1 which is nearly what I did but I still can't see the install page.

My virtual host file is in the conf.d directory just like in the guide if I go to /install I get not found if I go to /install.php it redirects me to /install.
I cleared my bootstrap cache, I don't have an env file. When I surf to the ip I get redirected to /login with a not found error. I can access other maps in the public directory like css. When I try to go the index.php It redirects to index.php/login with states access denied.

PHP version: 8.0

**Comment by freescout-helpdesk** [comment]
/install.php is supposed to redirect to /install where you come through the Installation Wizard.

> When I try to go the index.php It redirects to index.php/login

It means your web server sends some incorrect values in `$_SERVER['REQUEST_URI']` or `$_SERVER['PHP_SELF']`. Try to debug index.php.

**Comment by MaMi364** [comment]
> 

I didn't change anything for index.php though. My feeling was that the issue lies with the domain name because I try to use it locally and with an IP.

**Comment by MaMi364** [comment]
Only thing I did different from the guide was that I changed the document root of the main httpd conf file to /var/www/html/freescout/public  the default was /var/www/html  but when I use the default I get this
![image](https://github.com/freescout-helpdesk/freescout/assets/114657583/ee70d043-7a1f-4ddc-b419-eee96839cb78)

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
