### ISSUE TITLE
Is it possible to change the color for each Knowledge Base / End-User Portal?

### ISSUE THREAD

**Issue by sydios** [freescout-helpdesk/freescout#3252]
Hello,

I bought the Customization module. I have 3 mailboxes and I want to use a different color for each knowledge base and end-user portal. Is this possible?

Thanks!

**Comment by freescout-helpdesk** [comment]
Unfortunately not. You can do it via a custom module: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
