### ISSUE TITLE
Is it possible to search for tickets that have been sent TO a specific email address?

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#3253]
Sorry to ask here but is there no way to search for tickets that have been sent to a specific email address in the search functionality?

**Comment by freescout-helpdesk** [comment]
Search by Customer.

**Comment by zigojacko** [comment]
Ah yeh I guess every email that comes in will create a customer so if no customer found then no tickets sent to that address. 

Sorry, didn't think that through 😂 Thanks
