### ISSUE TITLE
One customer's name is not displayed correctly in the From field

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3254]
![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/2208ad99-1d04-45ae-b2d2-4a3df09c59f7)

But if you look at the email in Thunderbird or the webmail, the name is displayed correctly.

Here's the source of the Form field:

```text
From: =?ks_c_5601-1987?B?rKSs0azarOSs4KzTrNEgrLOs0azSrNqs36zR?= <mail@example.com>
```

PHP version: 7.4.33
FreeScout version: 1.8.86

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file?

**Comment by il2020** [comment]
No, I've added that parameter now. Is this supposed to solve the problem?

**Comment by freescout-helpdesk** [comment]
Check how it goes.
