### ISSUE TITLE
Assigned to user is not equal to unassigned not working as expected

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3255]
Hi,

the following workflow meets its conditions even though a conversation is assigned to "anyone". A conversation assigned to "anyone" should count as unassigned, right? If not, there is no sense in having this option as there is no possibility to have an "unassigned" conversation.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/134635748/b7d9a605-8520-43c0-acc6-503932c73b27)

PHP version: PHP 8.2.8
FreeScout version: 1.8.89

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.50
