### ISSUE TITLE
Translations issue

### ISSUE THREAD

**Issue by lumian** [freescout-helpdesk/freescout#3257]
FreeScout version: 1.8.89

Hello! I would like to make a suggestion about the separation of translations variables.

1. Group translation: "App". Key: "Closed".
It is used in two places: in the main menu and in ticket statuses, which, in my opinion, is illogical. The word "Closed" means an action that has already been performed. In the ticket status, the action has yet to be performed and it would be more logical to use the word "Close". Perhaps this is a mistake, because there is a "Close" key in the translations

2. Group translation: "App". Key: "Pending"
It is used in two places: when creating a ticket before the ticket number appears, as well as in ticket statuses. I think it is logical to use the "Pending" key in statuses, but in the first case, it is better to use "Waiting".

Perhaps there are still the same problems / flaws somewhere, but at the moment I have found only these and I would like to fix it. This problem does not allow me to make a correct translation into my language.

P.S.: Thank you for a great product!

**Comment by freescout-helpdesk** [comment]
Could you please attach screenshots.

**Comment by lumian** [comment]
![2023-08-11_13-31-33](https://github.com/freescout-helpdesk/freescout/assets/743700/add24d86-5aad-4751-a239-c1b939eaab1d)

**Comment by freescout-helpdesk** [comment]
We'll leave it as it is.
