### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by yabloky** [freescout-helpdesk/freescout#3258]
CSV import to the customer database is not working.

I created custom fields, loaded the table with clients, compared the fields found by the parser in the table with the fields in the freescout including custom fields) made the import - out of 733 items imported only 262, and only those who had email. 
In addition, custom fields did not add anyone (probably because they have links in the table), as well as did not add Telegram (probably because they also have links http://t.me/name_user).
But the main problem is that import doesn't work for clients without email.

How do I correctly import the customer base? This is very critical for me. ready to pay for support.
Thank you.

**Comment by freescout-helpdesk** [comment]
Make sure customers have either First Name or Email specified.

**Comment by yabloky** [comment]
Of course, everyone has a name, but not everyone has e-mail, and those who have e-mail are copied, but those who only have a name (as well as a number of other fields) are not copied. In addition, the field "telegram" was not copied, which is critical because all my clients are from telegram. How to cure?
Here's an example


Name | Telegram | Email | ЕТC (Mh/s) | ЕТН (Mh/s) | Minerall.login
-- | -- | -- | -- | -- | --
arsnelle | https://t.me/arsnelle |   |   |   |  
Kirill JetHash | https://t.me/Kirill |   |   |   |  
Anton Sapov |   |   |   | 800 | Shapovalov

**Comment by freescout-helpdesk** [comment]
How does it look when opened in a Notepad as a text file?

**Comment by yabloky** [comment]
Active client,Anton Shv,,,,,800,Shv,https://minerall.io/minerstats/MV81zIxXzQy,https://the.hiveos.farm/farms/340/workers,https://the.hiveos.farm/farms/975/workers,,,

Converted,Kirill JetHash,https://t.me/JetHasirill,,,,,,,,,,,12-06-2019

**Comment by freescout-helpdesk** [comment]
The issue with importing customers without emails has been fixed in CRM Module v1.0.34

If you want to import customers’ social networks, specify them in the following format in your CSV file:

```
"Twitter:https://twitter.com/example123,Facebook:https://facebook.com/example123,Telegram:https://t.me/example123"
```
But don’t expect customers to be linked when receiving messages from them via Telegram Integration, Facebook Integration or Twitter Integration modules.

**Comment by yabloky** [comment]
Is it necessary to correlate this field with social? On the second step of import?
Exactly what I expected ... and that there is no check for matching user fields? Not even custom ones?

**Comment by yabloky** [comment]
Or maybe there's some kind of merger? If a person writes to Telegram and a contact is created, is there any way to merge that contact with the one I imported?

**Comment by freescout-helpdesk** [comment]
Unfortunately not.

**Comment by yabloky** [comment]
Any solution, please. For money. It's critical for work (((

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by yabloky** [comment]
Having the ability to migrate your customer base from another helpdesk and use it in freescout should be the default. 
If I knew that I would not be able to work with my customer base, I would not have started the migration, would not have agonized with the installation of freescout on VPS and would not have bought a bunch of modules.

Is it so hard to write how you can link the contacts that are created when a person writes to telegram and those that were imported? Okay this f-functional is not available, but it is possible somehow through the database?

I understand that the software is conditionally free (without modules it makes absolutely no sense, and modules are paid, so the software is not free in fact), but it is possible to show at least a little participation, not soullessly send to the "site of proposals"?

**Comment by yabloky** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/416418

**Comment by freescout-helpdesk** [comment]
See how it works: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Development-Process

**Comment by yabloky** [comment]
I see, ok. Tell me, are there any plans to fully integrate database import with telegram modules? It turns out that my entire contact database is lost without it :( 
Am I the only one with this problem?

**Comment by yabloky** [comment]
Yes, I understand, then it is not a priority. Can you give me some advice on your own? Can somehow through BD can be combined? Do you know your system better

**Comment by freescout-helpdesk** [comment]
We'll try to implement matching social profiles in 1-2 weeks.

**Comment by yabloky** [comment]
That's great news. Thank you so much. We'll be able to continue working.

Maybe it would be better to make a new paid module in this case? Import custom database? This will allow people to move from other helpdesk without fear, because the most valuable thing is the customer base, with which you can continue to work.

**Comment by freescout-helpdesk** [comment]
Matching customers by their Telegram username specified in Social Profiles implemented in Telegram Integration Module v1.0.16

**Comment by freescout-helpdesk** [comment]
> Or just when the client will write, the module will check if there is such a name in the contacts and take this contact?

Yes.

> And add missing fields? For example, a phone number if there is one or an avatar?

Only avatar. Telegram API does not allow to get Telegram user phone number.

**Comment by yabloky** [comment]
You're great, thank you, you've really helped us out!

**Comment by yabloky** [comment]
As promised, I'm writing back on testing. I updated freescout and the telegram module, - everything works fine, when a person writes to the bot, the conversations go to a pre-created/imported contact with the same username. The only nuance - avatars from telegram are not added to the contact )
Thanks.

**Comment by freescout-helpdesk** [comment]
> avatars from telegram are not added to the contact

Check errors in Manage > Logs

**Comment by yabloky** [comment]
I looked right away, it's blank, not a single error. At the same time in the contact I imported there was no avatar and when now I wrote a client from telegram with an avatar, it was not added.
-
Can this be because when I imported the contacts and mapped the CSV fields to the client fields in freescout, I specified "empty" in front of the "photo" field?

**Comment by yabloky** [comment]
> > avatars from telegram are not added to the contact
> 
> Check errors in Manage > Logs

I looked right away, it's blank, not a single error. At the same time in the contact I imported there was no avatar and when now I wrote a client from telegram with an avatar, it was not added.
*Can this be because when I imported the contacts and mapped the CSV fields to the client fields in freescout, I specified "empty" in front of the "photo" field?

**Comment by yabloky** [comment]
> > avatars from telegram are not added to the contact
> 
> Check errors in Manage > Logs

I looked right away, it's blank, not a single error. At the same time in the contact I imported there was no avatar and when now I wrote a client from telegram with an avatar, it was not added.
*Can this be because when I imported the contacts and mapped the CSV fields to the client fields in freescout, I specified "empty" in front of the "photo" field?

UPD - No, it's not a merge problem, after updating the telegram module, avatars disappeared even for those who write for the first time and who don't have a saved contact yet.

**Comment by freescout-helpdesk** [comment]
It should be fixed in the next release.

**Comment by freescout-helpdesk** [comment]
Fixed in Telegram Integration Module v1.0.18. Avatars will be fetched only for customers which don't have yet existing conversations in your FreeScout.

**Comment by yabloky** [comment]
> Fixed in Telegram Integration Module v1.0.18. Avatars will be fetched only for customers which don't have yet existing conversations in your FreeScout.

Thanks for remembering.

I just updated freescout and the Telegram module, unfortunately the avatars are not loading. While the client definitely doesn't have any dialogs.
There are no errors in the logs. Checked on three different clients. I can provide logs or whatever you need.

**Comment by freescout-helpdesk** [comment]
Check what you have in `photo_url` field for those customers in `customers` table.

**Comment by yabloky** [comment]
Where can I see that? BD?

**Comment by freescout-helpdesk** [comment]
Yes, in database.

**Comment by yabloky** [comment]
It seems to have everything, so here's the conclusion:

MariaDB [jetdbscout]> SELECT photo_url FROM customers;
+--------------------------------------+
| photo_url                            |
+--------------------------------------+
| NULL                                 |
| NULL                                 |
| NULL                                 |
| NULL                                 |
| 678442d5d63ff8290614f3bac95ab55f.jpg |
| 1e359acbfb68d3cc3991a87a3ea61c58.jpg |
| b13ee62fd78f9d6dc4fb3a78b37aed3c.jpg |
| NULL                                 |
| NULL                                 |
| NULL                                 |
+--------------------------------------+
690 rows in set (0.001 sec)

**Comment by yabloky** [comment]
> Yes, in database.

It seems to have everything, so here's the conclusion:
*I've shortened the list ))

MariaDB [jnd]> SELECT photo_url FROM customers;
+--------------------------------------+
| photo_url                            |
+--------------------------------------+
| NULL                                 |
| NULL                                 |
| NULL                                 |
| NULL                                 |
| 678442d5d63ff8290614f3bac95ab55f.jpg |
| 1e359acbfb68d3cc3991a87a3ea61c58.jpg |
| b13ee62fd78f9d6dc4fb3a78b37aed3c.jpg |
| NULL                                 |
| NULL                                 |
| NULL                                 |
+--------------------------------------+
690 rows in set (0.001 sec)

UPD - two clients did not download the avatar (even though I deleted the dialogs), but the third client downloaded the avatar.

MariaDB [jbd]> SELECT photo_url FROM customers;
+--------------------------------------+
| photo_url                            |
+--------------------------------------+
| NULL                                 |
| NULL                                 |
| NULL                                 |
| NULL                                 |
| 678442d5d63ff8290614f3bac95ab55f.jpg |
| 1e359acbfb68d3cc3991a87a3ea61c58.jpg |
| b13ee62fd78f9d6dc4fb3a78b37aed3c.jpg |
| NULL                                 |
| NULL                                 |
| NULL                                 |
| NULL                                 |
| NULL                                 |
| 69ff8792df569aa1de8cd894d834e70a.jpg |
| NULL                                 |
+--------------------------------------+
690 rows in set (0.001 sec)

**Comment by freescout-helpdesk** [comment]
> even though I deleted the dialog

Deleting conversation is not enough as there are records in other tables. Avatars are fetched only for customers who never had conversations in your FreeScout.

**Comment by yabloky** [comment]
> > even though I deleted the dialog
> 
> Deleting conversation is not enough as there are records in other tables. Avatars are fetched only for customers who never had conversations in your FreeScout.

I understand, thank you. 
So for those who have already chatted it is not enough to delete the conversation through the interface? You have to go into the database and delete it manually? Or is there a simpler method?

**Comment by freescout-helpdesk** [comment]
There is no way around. You can upload avatar manually for them.

**Comment by yabloky** [comment]
> There is no way around. You can upload avatar manually for them.

Manually? But I didn't see that interface, I clicked on the place where the avatar should be, but no upload window appeared

**Comment by freescout-helpdesk** [comment]
![2023-08-26_14-43-01](https://github.com/freescout-helpdesk/freescout/assets/40499291/0b07d385-5e1b-4cb1-a169-c460a41a9363)

**Comment by yabloky** [comment]
> ![2023-08-26_14-43-01](https://user-images.githubusercontent.com/40499291/263462332-0b07d385-5e1b-4cb1-a169-c460a41a9363.png)

Thank you so much for helping import the customer base and fixing the Telegram module. Have a great day!
