### ISSUE TITLE
Widget (end-user portal) removes simple newlines

### ISSUE THREAD

**Issue by cfoellmann** [freescout-helpdesk/freescout#3259]
We are using the javascript widget to allow users to submit tickets on our internal pages.
Some users "create lists" by putting each item on a new line.
The resulting ticket has all these items on a single line. Only double newlines result in a new line in the ticket.

This is not intuitive for users. especially if they never see the agent side of the system it is a hard sell to educate.

Does this make sense to change? or is there some quick hotfix I can apply to the code?

PHP version: 8.2 (docker)
FreeScout version: 1.8.89

**Comment by freescout-helpdesk** [comment]
Fixed in End-User- Portal Module v1.0.58

**Comment by cfoellmann** [comment]
Thanks
