### ISSUE TITLE
Freescout won't send email notifications

### ISSUE THREAD

**Issue by masterdigerati** [freescout-helpdesk/freescout#326]
I keep getting this error in the logs:

Error sending email to user | proc_open() has been disabled for security reasons; File: helpdesk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php (296)

I have this in the php.ini file in the root directory:
disable_functions = dl, system, passthru, pfsockopen, leak, apache_child_terminate, posix_kill, posix_mkfifo, posix_setpgid, posix_setsid, posix_setuid

I've set it to use PHP7. It is receiving emails, but refuses to send any notifications out. any thoughts?

**Comment by freescout-helpdesk** [comment]
Sorry, we can't help you with your server configuration.
