### ISSUE TITLE
Subject field in the Submit a Ticket form in the End User Portal

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#3261]
Hello dear support!

In the new version of the End-User Portal module (1.0.59) the option to enable/disable the Subject field has been added. This is a very useful option, and thank you very much for finally adding it. We encountered a problem that after the ticket is created, this field remains in the body of the ticket and continues to be required. Can you remove this field from the request body and leave it only at the stage of creating a request?

**Comment by freescout-helpdesk** [comment]
> this field remains in the body of the ticket and continues to be required

Could you please attach a screenshot.

**Comment by freescout-helpdesk** [comment]
Fixed in the End-User Portal Module v1.0.60
