### ISSUE TITLE
Saved Replies - multiple lines are inserted between text

### ISSUE THREAD

**Issue by networkpotato** [freescout-helpdesk/freescout#3264]
After the latest update of the module to v1.0.26, multiple blank lines are inserted between text even though the reply itself does not contain them. This is how the text really is saved:

<img width="1042" alt="Skjermbilde 2023-08-15 kl  09 36 43" src="https://github.com/freescout-helpdesk/freescout/assets/32069841/80eb4372-6d94-4bdf-a018-97a33d565e46">

And this is how it looks when used in a ticket. Note that there is even a new line inserted at the end, below the last sentence:

<img width="901" alt="Skjermbilde 2023-08-15 kl  09 32 01" src="https://github.com/freescout-helpdesk/freescout/assets/32069841/f35fa3a3-6605-40a8-bc88-181f5a9f7e6d">

**Comment by freescout-helpdesk** [comment]
Fixed in Save Replies v1.0.27
