### ISSUE TITLE
Module webhook - add event type triggered to payload

### ISSUE THREAD

**Issue by jesperordrup** [freescout-helpdesk/freescout#3265]
It would be very usefull to be able to see which event triggered.  This would allow us/me to create one webhook endpoint to deal with all events. Today it seems we have to create a webhook for each event and then handle it with a parameter to the webhook endpoint.

Most of the time its the same endpoint dealing with the different events. 

For instance:

    "source": {
          "type": "email",
          "via": "customer",
          "event": "convo.created"
      },

**Comment by freescout-helpdesk** [comment]
> Each webhook includes the following FreeScout headers:
> X-FreeScout-Event: Name of the event for which this webhook has been triggered.
https://freescout.net/module/api-webhooks/

We will not change the webhook body structure as it will break logic for those who are already using Webhooks.

**Comment by jesperordrup** [comment]
Thanks for response. Totally understand the concern. But consider this - you are adding to structure not changing around. 

Also - you could make it a config option in backend when setting up the webhook
