### ISSUE TITLE
Faster Search Module and search.conversations.apply_filters filter

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3267]
Hello.

After we tried the Faster Search Module, we noted that one of our custom module seems not to work anymore. The custom module hooks into `search.conversations.apply_filters`. The hook is introduced in the Conversation::search method
https://github.com/freescout-helpdesk/freescout/blob/40fc84546168c7fed1eacf55759ff008371815f4/app/Conversation.php#L2252
but this method never gets called, when the faster search module is active, due to this line
https://github.com/freescout-helpdesk/freescout/blob/40fc84546168c7fed1eacf55759ff008371815f4/app/Http/Controllers/ConversationsController.php#L2699

I'd like to know, do I miss something here or is this hook just not available in combination with the Faster Search Module?

Thanks in advance

**Comment by freescout-helpdesk** [comment]
> but this method never gets called, when the faster search module is active, due to this line

Yes. This is how it works.

**Comment by sofl88** [comment]
Okay but in simple, it is not possible to add more search filter with a custom module, when the Faster Search Module is active.. right?

**Comment by freescout-helpdesk** [comment]
Yes, only by altering module's code.
