### ISSUE TITLE
Inadequate Warning of Failed Send

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3268]
We have had trouble sending an email to a particular recipient.  It has twice failed however all other emails send without issue.  I will try to diagnose the reason that it is not able to send.

The user had no idea that the message did not send.  There should be some kind of persistent prominent warning to tell the user that an email could not send so the user can check the email and fix it.

The only indication of a problem is this notification in the email conversation:

![image](https://github.com/freescout-helpdesk/freescout/assets/96336813/5542f813-1c99-467a-8a46-03698cf2d983)

**Comment by freescout-helpdesk** [comment]
> There should be some kind of persistent prominent warning to tell the user that an email could not send so the user can check the email and fix it.

What else can you suggest?

Also see https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-support-team-know-that-there-are-problems-with-sending-emails-and-emails-are-not-being-sent

**Comment by freescout-helpdesk** [comment]
Feel free to submit pull requests with fixes.

**Comment by freescout-helpdesk** [comment]
We've made some changes - now if an email could not be sent a support agent will see an error message after 1 hour (while FreeScout will continue attempts to send it).
