### ISSUE TITLE
Connecting with Google App Passwords not working

### ISSUE THREAD

**Issue by zigojacko** [freescout-helpdesk/freescout#3269]
We have got mailboxes set up which don't actually exist as physical mailboxes at Google Workspace. We just connect to catchall and then fetch a specific label for the address we need to fetch from but none of these seem to connect with the Google App Password (which is for the main physical mailbox) for some reason.

I'm stumped as to what else I can try with it currently... 🤷‍♂️

**Comment by freescout-helpdesk** [comment]
Use physical mailboxes.

**Comment by zigojacko** [comment]
We have hundreds of email addresses though across our organisation for different purposes that are basically aliases. 

We're not going to pay £thousands a month just to receive email at different physical mailbox addresses.

I am sure this used to work with Freescout and it is possible with other software.

**Comment by freescout-helpdesk** [comment]
We are not sure how to help here. Let us know if you'll find some solution.

**Comment by zigojacko** [comment]
In fact actually, as a test with one mailbox, I've set it up to fetch from the actual physical main mailbox and even that does not connect with an app password... I have tried with SSL, TLS and None.

The error message in the log is:

imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Retrying PLAIN authentication after [AUTHENTICATIONFAILED] Invalid credentials (Failure); Retrying PLAIN authentication after [AUTHENTICATIONFAILED] Invalid credentials (Failure); Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Invalid credentials (Failure); File: /.../overrides/webklex/laravel-imap/src/IMAP/Client.php (230)

I've tried creating a new app password and it makes no difference. This is the issue I have across multiple mailboxes right now, even ones connected to physical mailboxes. 

Bit odd?

**Comment by freescout-helpdesk** [comment]
Maybe you have similar issue: https://github.com/freescout-helpdesk/freescout/issues/3272#issuecomment-1680285260

**Comment by zigojacko** [comment]
Yes this sounds like the same issue. I have reached out to the OP in that thread. 👍

**Comment by zigojacko** [comment]
@freescout-helpdesk I have spoken to Google Workspace support and they confirm there are no issues with any of our configuration or our app passwords and that it is Freescout that is randomly not accepting our app password for the IMAP connection (we have other mailboxes working fine set up exactly the same way oddly).

**Comment by zigojacko** [comment]
To go even one step further, we are not even receiving many of our email notifications from Freescout about tickets now neither. Got no idea what is going on but the application is falling apart on us.

**Comment by freescout-helpdesk** [comment]
Try to re-update the app manually: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by zigojacko** [comment]
@freescout-helpdesk that made no difference to anything.

Wow, I actually can't believe this but I'm going to have to leave Freescout, it is absolutely screwed all of a sudden - I am missing notifications all over the place and have no idea clients have even replied. Nothing in the queue apparently. 

No idea what the hell is going on with it but this is basically unworkable with now... Been fine for years!! Seems like 15th August everything started messing up when it was all working perfectly before. 🤷‍♂️
