### ISSUE TITLE
Attachments Not Viewable

### ISSUE THREAD

**Issue by Speedy059** [freescout-helpdesk/freescout#327]
I've noticed that if an attachment has "#" in it, you can't view it. The attachments directs to a page with: "Sorry, the page you are looking for could not be found.". I've checked on the server and the file is there, but the "#" character throws it off.

Reproduce Instructions: Send an email with an attachment and put "#" somewhere in the file name (EX: PO#4262254.pdf). Doesn't matter on the extension, can be .pdf,.jpg,etc.

**Comment by freescout-helpdesk** [comment]
Thanks. It will need to be fixed.

**Comment by freescout-helpdesk** [comment]
Has been fixed a year ago.
