### ISSUE TITLE
Workflow, trigger Type=phone, Action='e-mail the customer' is not working

### ISSUE THREAD

**Issue by ssstofff** [freescout-helpdesk/freescout#3270]
When manually a phone call is registered, customer is entered (that moment e-mail field dissapears, but e-mail is mentioned in customer field), the Workflow with condition Type=Phone is triggered, but the action to send an e-mail to the customer is not working.

When watching the ticket itself, the workflow itself is correctly added with the action.

When checking the 'Outgoing Emails' on a Workflow trigger, it says also "There were no send attempts yet".

**Comment by freescout-helpdesk** [comment]
Please attach screenshot of your conditions and actions.

**Comment by ssstofff** [comment]
Type is automatic

![image](https://github.com/freescout-helpdesk/freescout/assets/5623149/d4c73ded-00f2-4613-b090-e680f53168e3)
![image](https://github.com/freescout-helpdesk/freescout/assets/5623149/be6d8d44-00e4-4d0e-8320-50faca643b36)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by ssstofff** [comment]
I tried the update, but no change, same behaviour

**Comment by freescout-helpdesk** [comment]
Make sure to clear cache after pulling updates from `master` branch.
