### ISSUE TITLE
Module: Knowledge Base in Reply Editor issues

### ISSUE THREAD

**Issue by avenjamin** [freescout-helpdesk/freescout#3271]
Howdy,

Thanks for adding the "Insert Knowledge Base Reference" button.

Are there any specific requirements to get it to work?
I've tried searching with various keywords of articles in our KB but nothing appears.
The UI jumps down a bit and then back up.

Ben

**Comment by avenjamin** [comment]
After a little bit of debugging in `KnowledgeBaseController.php` in the `ajaxAdmin` function the line...

`$locales = \Kb::getLocales($mailbox);`

...is returning an empty array on my installation.
This means the `foreach` loop that follows never adds an articles to the `$items` array.

I suspect this is because we don't have any languages defined in the Knowledge Base settings as we only use English.

<img width="829" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/869534/590fa0e2-8752-4cd4-91a3-79f3f86412c4">

**Comment by avenjamin** [comment]
Quick fix is to add:

```
if (!count($locales)) 
    $locales = array('');
```

after `$locales = \Kb::getLocales($mailbox);`

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Module v1.0.53
