### ISSUE TITLE
Phone and email buttons

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#3275]
When phone logging is enabled, please also show the phone button here.

<img width="1721" alt="Screenshot 2023-08-16 at 11 06 17" src="https://github.com/freescout-helpdesk/freescout/assets/382183/4419ef43-e769-449d-82e5-8eee2f12a8f0">

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by fulldecent** [comment]
Thank you, added here https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/416461
