### ISSUE TITLE
MySQL user already has more than 'max_user_c onnections' active connections

### ISSUE THREAD

**Issue by 11benji** [freescout-helpdesk/freescout#3276]
Hola, espero me puedan ayudar en saber como puedo solucionar este tema:

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [1203] User reactor_ayuda already has more than 'max_user_c  
  onnections' active connections (SQL: select * from `options` where (`name`   
  = fetch_emails_last_run) limit 1)                                            
                                                                               

In Exception.php line 18:
                                                                               
  SQLSTATE[HY000] [1203] User reactor_ayuda already has more than 'max_user_c  
  onnections' active connections                                               
                                                                               

In PDOConnection.php line 38:
                                                                               
  SQLSTATE[HY000] [1203] User reactor_ayuda already has more than 'max_user_c  
  onnections' active connections

**Comment by freescout-helpdesk** [comment]
Please write in Englihs.

**Comment by 11benji** [comment]
my freescout crashes from time to time and shows me the following log, how can I fix it?

In Connection.php line 664:

SQLSTATE[HY000] [1203] User reactor_ayuda already has more than 'max_user_c
onnections' active connections (SQL: select * from options where (name
= fetch_emails_last_run) limit 1)

In Exception.php line 18:

SQLSTATE[HY000] [1203] User reactor_ayuda already has more than 'max_user_c
onnections' active connections

In PDOConnection.php line 38:

SQLSTATE[HY000] [1203] User reactor_ayuda already has more than 'max_user_c
onnections' active connections

**Comment by freescout-helpdesk** [comment]
Check `max_user_connections` parameter for you DB.
Check if there are some background jobs that got stuck: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
