### ISSUE TITLE
Error on opening message - preg_match(): Passing null to parameter #2

### ISSUE THREAD

**Issue by letmesearchplease** [freescout-helpdesk/freescout#3277]
PHP version: 8.2 (Also occurred on 8.1)
FreeScout version: 1.8.90 (Also occurred on 1.8.81)

Getting an error when opening some emails on 2 recently setup mailboxes. Seems to occur just from these two newer mailboxes

Get a Whoops Something Went Wrong error when visiting /conversation/168?folder_id=435. The storage/logs/laravel-$date.log shows:
```
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) {"userId":472,"email":"email@email.com","exception":"[object] (ErrorException(code: 0): preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) at /var/www/html/overrides/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php:369, ErrorException(code: 0): preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) at /var/www/html/overrides/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php:369, ErrorException(code: 0): preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) at /var/www/html/overrides/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php:369, ErrorException(code: 0): preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated at /var/www/html/overrides/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php:369)
```

I originally got the error on FreeScout version 1.8.81 and PHP 8.1. When reading the wiki, it mentions to not use PHP 8.1, so I moved to PHP 8.2 and upgraded Freescout (no issues during that process).

The same error still occurs after those upgrades and I am at a loss!

**Comment by freescout-helpdesk** [comment]
We've made some adjustments in the `master` branch. If the issue will be still present try to find and send us `body` value from `threads` table for those conversations.

**Comment by letmesearchplease** [comment]
I did some further tests and it was just specific emails with certain body content that was causing this (something to do with images/fonts/html). Besides the one bad email, it cannot get it to reproduce. 

If I have a chance, I will test the main branch out, but the commit 14e56cd appears to resolve that error!

Thanks!
