### ISSUE TITLE
Faster Search Module does not find content with leading or inner html tags

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3278]
Hello.

I'm not 100% sure how meilisearch works in this regard but lets say I create a new conversation/thread with a single word like `test`, it will not be found by the freescout search since the indexed content is leading a div or a p tag. Then again when I search for `<div>test`, I got the expected result. The problem also appears in scenarios where part of the text content is styled with bold/italic/etc.

Wouldn't it be more accurate to index just the plain text version anyway?

Thanks in advance

**Comment by freescout-helpdesk** [comment]
We've made some adjustments in Faster Search Module v1.0.5. It should work fine now.
