### ISSUE TITLE
Tag issue when trying to do GDPR delete

### ISSUE THREAD

**Issue by akiradk** [freescout-helpdesk/freescout#3279]
Hi there.

I had an issue with the tag module when combined with the GDPR module.
When i went in and selected a customer to be GDPR deleted with all the conversations everything seemed normal, it said that the system was deleting the customer in the background.

After an hour the customer was still there and i went to the logs and had a peak, then i was greeted with the back trace i have attached to this request.

After doing some extra digging it resulted in there was a tag binding on a conversation but the tag itself was deleted (and did not show up on the conversation), so after deleting the tag binding in the `conversation_tag` database it went trough without any issue.

My hunch here is that one of my users managed to delete a tag that was in use and then left the conversation_tag table with orphaned entries that then messed it up for the GDPR delete module.

I hope this explains the issue well enough, if you need more info then do let me know :) 

[freescout.log](https://github.com/freescout-helpdesk/freescout/files/12378108/freescout.log)

**Comment by freescout-helpdesk** [comment]
Should be fixed in Tags Module v1.0.31

**Comment by akiradk** [comment]
Nice, i will give it an update and report if i find anything :)

Thanks for a great piece of software :)
