### ISSUE TITLE
Contents of field out_password in the database is in plain text

### ISSUE THREAD

**Issue by nielsdrost7** [freescout-helpdesk/freescout#328]
Hi guys,

I was checking the database and unfortunately in the `mailboxes` table in the `out_password` field the password for sending emails (mailbox) is saved as **plain text**, it's not encrypted like the `in_password`.

For `in_password` the field is saved encrypted.
In `2018_11_13_143000_encrypt_mailbox_password.php` the password for `in_password` is encrypted. Maybe it's an idea to do the same for `out_password`

**Comment by davask** [comment]
This is true too for mail_password in options table.

@freescout-helpdesk if you point me where can I modify these 2 variable I can make the modification.
Any prefered encryption method ?

Is the default WordPress method good enough for you ? 

https://developer.wordpress.org/reference/functions/wp_hash_password/
https://www.openwall.com/phpass/

**Comment by davask** [comment]
https://github.com/freescout-helpdesk/freescout/pull/1217

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/1226
