### ISSUE TITLE
Running cron job as a oneshot systemd service

### ISSUE THREAD

**Issue by jmcclelland** [freescout-helpdesk/freescout#3280]
PHP version: 7.4
FreeScout version: 1.8.86

On our server, we are limited to running the cron job as a systemd service of the type oneshot that is triggered via a systemd timer.

Since oneshot systemd services do not expect any background processes to be launched, it doesn't go well (the command never completes, so we end up with just the background job running and systemd won't run it again because it thinks it is still running).

I can get the job running properly by passing `--no-interaction`. Then, email is checked, but not sent (the [installation page makes clear that this is not ideal](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs)).

I set another systemd timer that uses curl to access the URL version of the cron job and now email is received and sent, so basic functionality seems to be working.

I was wondering if there is an alternative? In particular - I can run a systemd service as a standard service. Is there an artisan command that just runs the background job (but runs it in the foreground)?

Thanks for the solid softare. It's been a big help for us.

**Comment by jmcclelland** [comment]
Thanks for the tip. I see that my free scout is launching the `queue:work` command with a random string in the `--queue` argument to differentiate it from other free scout instances on the same server. But I'm not sure how it's generated. Is it always the same string for my site so I can just copy it in my systemd file? Or is it dynamically generated?

**Comment by freescout-helpdesk** [comment]
It's always the same.

**Comment by jmcclelland** [comment]
Thanks for the help. For anyone else trying this out:

The main cron job is run as a systemd timer with the following service file:

```
[Unit]
Description=Freescout schedule run

[Service]
ExecStart=php /home/xxxxx/web/artisan --no-interaction schedule:run
WorkingDirectory=/home/xxxx/web
Type=oneshot
```

And the following timer file:

```
[Unit]
Description=Timer for Freescout schedule run

[Timer]
OnCalendar=minutely
RandomizedDelaySec=10
[Install]
WantedBy=default.target
```

And the following is the service file for running the queue work job. I ran `ps -eFH` to find the arguments to use, including the unique id.

```
[Unit]
Description=Freescout queue work job

[Service]
ExecStart=php /home/xxxx/web/artisan queue:work --queue=emails,default,xxxxx --sleep=5 --tries=1 --timeout=1800
WorkingDirectory=/home/xxxx/web
Type=simple

[Install]
WantedBy=multi-user.target
```

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the solution.
