### ISSUE TITLE
Forward in manual workflow creates error, manual forward works

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3281]
Hey,

we now found out, what is causing the errors in #3234:

When we forward a mail within a workflow, that forward does not get sent. It creates an error in App\Jobs\SendReplyToCustomer without any specific error message, as shown in #3234.

Any idea, what changes between a manual forward and workflow forward, so they behave differently?

Thanks!

PHP version: 8.2.8
FreeScout version: 1.8.91

**Comment by freescout-helpdesk** [comment]
We've just checked and forwarding via Workflow works on our end.
Maybe you are forwarding Phone conversation?

If the issue still persists try to re-update your FreeScout using manual updating method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually
