### ISSUE TITLE
Newely created workflow causes whoops error on management click

### ISSUE THREAD

**Issue by SigMarinetti** [freescout-helpdesk/freescout#3283]
PHP version: 8.2.8
FreeScout version:  1.8.89

The main modules involved in this are the Workflows module and the Checklist module.

What happens:

- I created a new workflow
- Selected manual
- Added a single "Add checklist" action
- Selected the "Active" switch
- Saved.
- The workflow got created but set as "Incomplete"
- Clicking on it in the management window leads to a Whoops, something went wrong error page
- The following error get's logged
NOTE: i redacted the user email from the log.
`Undefined array key "type" (View: /www/html/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) (View: /www/html/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) {"userId":1,"email":"redacted@redacted.com","exception":"[object] (ErrorException(code: 0): Undefined array key \"type\" (View: /www/html/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) (View: /www/html/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) at /data/storage/framework/views/4bd8f035cd82636e01c4ee935add120225ffa488.php:64, ErrorException(code: 0): Undefined array key \"type\" (View: /www/html/Modules/Workflows/Resources/views/partials/dynamic_block.blade.php) at /data/storage/framework/views/4bd8f035cd82636e01c4ee935add120225ffa488.php:64, ErrorException(code: 0): Undefined array key \"type\" at /data/storage/framework/views/4bd8f035cd82636e01c4ee935add120225ffa488.php:64)
`
[workflows error.txt](https://github.com/freescout-helpdesk/freescout/files/12381223/workflows.error.txt)

As added context: before this one I created an almost identical workflow in a different mailbox (same name, same action, same settings) and it didn't cause any problem.

Thanks in advance, let me know if you need more information

**Comment by freescout-helpdesk** [comment]
Apparently something went wrong during the process of saving the workflow. You can try to find the workflow in DB and check what's in its `conditions` and `actions` fields.
