### ISSUE TITLE
Fetching emails work from the interface, but not when using cli

### ISSUE THREAD

**Issue by sitemapxml** [freescout-helpdesk/freescout#3285]
Greetings,

I recently installed Freescout and successfully connected my first mailbox, but I came across a strange issue, for which I couldn't find an answer.

The situation is as following:
 - mailbox is created, and email account is connected to my own mail server
 - when the "Check Connection" button is pressed, the green message "Connection established!" appears
 - when "Get folders" link is pressed, the current list of folders is retrieved, as it should be

The problem is that, when I  manually run `php artisan schedule:run`, the new emails are not fetched, and there is no error logged at all, but when I go to "Manage" > "System" > "Tools", and press "Fetch Emails" button in the interface, then the new emails from email account are successfully fetched.

I also tried to trigger fetching of new emails by manually running `php artisan freescout:fetch-emails`, to see if I would get some more information, but I get only this as output:

```
[2023-08-19 15:57:44] Fetching UNREAD emails for the last 3 days.
[2023-08-19 15:57:44] Mailbox: Support
[2023-08-19 15:57:45] Could not get mailbox IMAP folder: INBOX
[2023-08-19 15:57:45] Could not get mailbox IMAP folder: Junk
[2023-08-19 15:57:45] Could not get mailbox IMAP folder: Sent
[2023-08-19 15:57:45] Could not get mailbox IMAP folder: Trash
[2023-08-19 15:57:45] Could not get mailbox IMAP folder: Drafts
[2023-08-19 15:57:45] Fetching finished
```

The version of Freescout I have installed is currently the latest, 1.8.91.
The "PHP Extensions" section of "System Status" have green "OK" labels on each field.
No errors are logged in the application logs, except the error I pasted above, which were written to "fetch-emails.log" file.

Do you have some idea for further analysis?

**Comment by freescout-helpdesk** [comment]
Try `php artisan freescout:check-requirements`

**Comment by sitemapxml** [comment]
Hello,

Thank you very much for a fast response, and for your time to review the issue.
After running the command you suggested, the output was as following:

```
PHP Version
 8.1.2-1ubuntu2.13............. OK
PHP Extensions
 OpenSSL....................... OK
 PDO........................... OK
 Mbstring...................... NOT FOUND
 Tokenizer..................... OK
 JSON.......................... OK
 XML........................... OK
 IMAP.......................... OK
 GD............................ NOT FOUND
 fileinfo...................... OK
 ZIP........................... NOT FOUND
 iconv......................... OK
 cURL.......................... NOT FOUND
 DOM........................... OK
 libxml........................ OK
 intl.......................... NOT FOUND
 pcntl (console PHP)........... OK
Functions
 shell_exec (PHP).............. OK
 proc_open (PHP)............... OK
 fpassthru (PHP)............... OK
 ps (shell).................... OK
```

So, one of the listed missing extensions was preventing the application from fetching emails.

Since my installation is intended for production use, I just hurried to install all the extensions that were missing, and after that the fetching of emails by using system cron job was working properly.

I don't know why these extensions were marked as "OK" on the "System Status" page, but after installing them with a default package manager, everything was fine.

Just for reference, my server is using CyberPanel with `LiteSpeed/1.7.16` on `Ubuntu 22.04.2 LTS`.

When I get some time, I would try this again in some testing environment, and share details here.

Have a nice day :)

**Comment by freescout-helpdesk** [comment]
PHP used by web server and console PHP are different and may have different set of extensions.
