### ISSUE TITLE
Typo and Clarification

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3286]
https://freescout.net/module/custom-fields/

"Date: Date in YYY-mm-dd format."

Should be YYYY

"When merging two conversations custom fields are also merged – empty custom fields in the original conversation are replaced with values from the second."

Please clarify what happens with the merger.  If both text fields are populated, are they concatenated? What happens with number fields?  Are dropdowns and dates overwritten by the second conversation?  It would be helpful if, before merging the conversations, a preview of the merged data was displayed to prevent accidental destruction. Instead of always merging, perhaps the user would prefer that the custom field data from one conversation be saved as a note prior to being overwritten by the custom field data from the other conversation.  This would allow the user to manually revert if the conversation merger yielded unexpected results.

**Comment by freescout-helpdesk** [comment]
> Please clarify what happens with the merger. If both text fields are populated, are they concatenated? What happens with number fields? Are dropdowns and dates overwritten by the second conversation?

If some custom field in the original conversation has a value this value is preserved unchanged during the merge.

**Comment by freescout-helpdesk** [comment]
> The following screenshot on https://freescout.net/module/time-tracking/ suggests that my understanding may be incorrect.

The screenshot is outdated. We'll update it to show 3 options.
