### ISSUE TITLE
Tickets not visible after update

### ISSUE THREAD

**Issue by mhktc** [freescout-helpdesk/freescout#3287]
Hello,

i wanted to update from 1.8.89 to 1.8.91 but you just released a new update a couple of minutes ago and it did install the 1.8.92 update. After installing it i had a bug where the unassigned and assigned tickets dont get displayed anymore when you click on unassigned and assigned. I had to revert the snapshot because its a production system. If you need logs i can maybe try to update a test freescout instance.

PHP version: PHP 8.1.2-1ubuntu2.13
FreeScout version: 1.8.89

**Comment by freescout-helpdesk** [comment]
Fixed in FreeScout v1.8.93
