### ISSUE TITLE
Android app doesnt ask for notification 

### ISSUE THREAD

**Issue by colofdurty** [freescout-helpdesk/freescout#3288]
Hey,

the android app doesnt ask for permission to send notification --> cant activate it in the System Settings. Demo also doesnt work

**Comment by freescout-helpdesk** [comment]
We've just double checked - push notifications work fine in Android app. Android app is not supposed to ask for permissions to send push notifications. See also "Android" section at https://freescout.net/module/mobile-notifications/

**Comment by colofdurty** [comment]
Hey,

ive checked every setting inclouding battery opti. 

But i seema that the app need to ask on first Launch for Notifications. (See Photos)
![Screenshot_20230821-210756](https://github.com/freescout-helpdesk/freescout/assets/54286923/877cb49c-9ff3-404b-8f20-b42c7e8dcfd9)
![Screenshot_20230821-210751](https://github.com/freescout-helpdesk/freescout/assets/54286923/d6620d7c-eb2f-41c6-b330-38782c4923ff)

**Comment by freescout-helpdesk** [comment]
You can enable push notification for apps in the phone Settings.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3290#issuecomment-1689821951
