### ISSUE TITLE
FreeScout on Laravel 6, when?

### ISSUE THREAD

**Issue by blackyzero** [freescout-helpdesk/freescout#329]
Hi Team,

Is there any plan to upgrade FreeScout on Laravel 6?

Thank you.

**Comment by freescout-helpdesk** [comment]
Hi. No for now.

**Comment by blackyzero** [comment]
i see. do you have any est for released date.

Thanks a lot.

**Comment by freescout-helpdesk** [comment]
No plans to upgrade Laravel.
