### ISSUE TITLE
Jira-Module: Projects not listed when I want to create a ticket from Freescout

### ISSUE THREAD

**Issue by caligula-maximus** [freescout-helpdesk/freescout#3291]
When I try to create a new Jira-ticket, the list of Jira-projects is empty and I can't submit a new ticket.
It is possible to link a Freescout ticket to an existing Jira-ticket and I can also search for a Jira-ticket from the module. 
We have selfhosted Jira instance and we connect by username & password to Jira.

Any idea what's wrong?

Jira: Selfhosted, Ver. 9.10
Freescout: Ver. 1.8.86
PHP Ver: 8.2.8

**Comment by caligula-maximus** [comment]
We don't use CloudFlare. The Jira-server is not accessible from outside. (but I can search for tickets)
There is no error in the App Log.

**Comment by freescout-helpdesk** [comment]
It looks like we can't help from here. The issue need to be debugged on your server.

**Comment by caligula-maximus** [comment]
What should look after? When does the module ask for the projects? When loading the ticket? When click the button "Link Jira Issue"?
Some more information would be appreciated :-)
