### ISSUE TITLE
Chat module breaks in Chrome incognito window

### ISSUE THREAD

**Issue by LucyE** [freescout-helpdesk/freescout#3292]
Hii,
I'm using the Chat module on my website. I added the script to my header and its working fine. Accept when visiting the site in incognito mode (Google Chrome). The buttons aren't working in that case and console is mentioning: Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Any idea how to fix this for incognito mode? Thanks in advance!

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2347
