### ISSUE TITLE
Freescout table locking issue when trying to get conversation

### ISSUE THREAD

**Issue by Baskkra** [freescout-helpdesk/freescout#3294]
Hi guys, so recently our team got issues related to freescout and it's mysql database. Our freescount suddenly getting slow at some times especially when trying to access conversation and conversation detail pages. And randomly got error messages,

So we decide to look at the logs and databases running query, here what we found :
- database got [ERROR] mysqld: Lock wait timeout exceeded; try restarting transaction
- and we found out this query is take time and maybe make our freescout getting slow 
```
update `notifications` set `read_at` = ?, `updated_at` = ? where `notifications`.`notifiable_id` = ? and `notifications`.`notifiable_id` is not null and `notifications`.`notifiable_type` = ? and `read_at` is null and `data` like ? order by `created_at` desc
```

we also think that this happen because either the query is not optimized enough or it's getting slow at some numbers of conversation that we got (we had almost 6000+ conversation when this issues created)

PHP version:  8.2.5
FreeScout version: 1.8.73

P.S : the db and freescout app deployed on top of kubernetes 

Best Regards,
Panji

**Comment by freescout-helpdesk** [comment]
How many records do you have in `notifications` table?

**Comment by Baskkra** [comment]
hi @freescout-helpdesk thank you for responding my issues, after i check as per this reply we got `583333` records

**Comment by freescout-helpdesk** [comment]
We'll need to implement automatic removal of old notifications from this table.

**Comment by Baskkra** [comment]
i see, but can you give me short explanation of what it used for? and what if i do manual remove to some record directly from the db? will it break because have some constraint with another table?

**Comment by freescout-helpdesk** [comment]
You can freely remove old records.

**Comment by Baskkra** [comment]
hoho, that's great news. But it will not affect like the mailing or something that relate to the conversation right?

**Comment by freescout-helpdesk** [comment]
It will not affect.

**Comment by Baskkra** [comment]
Actually we get started using freescout at mid may until today

Pada tanggal Kam, 24 Agu 2023 00.27, FreeScout ***@***.***>
menulis:
