### ISSUE TITLE
Issue with IMAP - Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3298]
@freescout-helpdesk 

We have an issue which started yesterday - our platform has been running without issues.
Error below

Allowed memory size of 268435456 bytes exhausted (tried to allocate 24738824 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 268435456 bytes exhausted (tried to allocate 24738824 bytes) at /home/home-helpdesk/webapps/app-helpdesk/public/overrides/webklex/laravel-imap/src/IMAP/Message.php:825)[stacktrace] #0 {main} "}

Freescout - 1.8.93
PHP 8.2.x

We would appreciate if you can give guideance as soon as possible, as processing emails has stopped.

thanks
Matt

**Comment by freescout-helpdesk** [comment]
Check if there is an email with large attachment or body.

Also you can try to use another IMAP library: add  `APP_NEW_FETCHING_LIBRARY=true` parameter to .env file and clear cache. Maybe it will be able to digest your problematic email.

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
Added the new env variable, but I am not getting anything meaningful.
We have identified several emails which are large. Some have attachments but others are general conversations which have been added over and over to the email, contributing to the size of the email. We are aware of the setting which controls this. 

How can this be avoided in the future, where we still see conversations from the past in the email thread?

**Comment by freescout-helpdesk** [comment]
Give your console PHP enough memory. There is no other options.

**Comment by freescout-helpdesk** [comment]
Sure. Everything depends on how much memory you give to console PHP.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#allowed-memory-size-of-nnn-bytes-exhausted-error-when-fetching-large-attachments

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks.
We have approached this by setting a limit on the mailbox as to what size email it can receive. 
Thanks for your quick response.
