### ISSUE TITLE
Customer label swapped places with custom tags

### ISSUE THREAD

**Issue by kovoks** [freescout-helpdesk/freescout#3299]
Hi there!

We just ran some updates and now we see a change which makes the conversations list a little less organized: The (in our case grey) customer tag has swapped places with the custom tags, so now the customer is not always first in the list. Also the right margin hasn't moved to the left so now there are uneven margins when there are custom as well as customer tags: 

![FreeScout](https://github.com/freescout-helpdesk/freescout/assets/119448948/25b774e4-c0f8-46bb-bacb-d79fc025acbb)

**Comment by freescout-helpdesk** [comment]
Fixed in Tags Module v1.0.32
