### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by delitestudio** [freescout-helpdesk/freescout#330]
Is it possible a user can only see the tickets assigned to him?

Thanks for this great tool!

**Comment by freescout-helpdesk** [comment]
Hi. Now for now.

**Comment by sainf** [comment]
Hi.
User permissions would be great, any prediction when it might be implemented?

**Comment by foliovision** [comment]
Workaround - create a mailbox without private tickets and move the sensitive tickets from the current mailbox to the less sensitive one. We're using this to keep sensitive matters from the eyes of general support and it's enough.

**Comment by delitestudio** [comment]
Brilliant! But how do you move tickets from one mailbox to another?

**Comment by foliovision** [comment]
Freescout has move between mailboxes functionality. I was surprised and delighted to find move already built-in.

![Basecamp-migration-final-header-colours](https://user-images.githubusercontent.com/1180948/66392117-419fbb00-e9cf-11e9-8cf0-a6d88d826776.png)

**Comment by delitestudio** [comment]
Very interesting, thanks. I didn't see that menu item having just one mailbox :)

**Comment by freescout-helpdesk** [comment]
No plans to implement user permissions for now.
