### ISSUE TITLE
ISSUE - Your email update could not be processed

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3301]
@freescout-helpdesk 

Could you please explain what this issue is? We are getting this several times every hour, and need to resolve this issue. 
If we can have a step by step to resolve that would be great.

M.

![image](https://github.com/freescout-helpdesk/freescout/assets/902376/3a914b0d-c3a8-4421-892e-3f5c293b1934)

**Comment by freescout-helpdesk** [comment]
You support agents should reply from emails which they have in your FreeScout.

**Comment by raramuridesign** [comment]
Thanks @freescout-helpdesk Seems like we have solved this issue now. Appreciated.
