### ISSUE TITLE
Show sent mails of all users in sent folder

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3302]
Hi,

is there an option to show all sent mails in the sent folder, not just the ones the current user has sent?

Thanks a lot!

PHP version: 8.2.9
FreeScout version: 1.8.91

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. Maybe there was already such feature request here: https://freescout.net/request-feature/

**Comment by githubuser-112** [comment]
Thanks, heres the feature-request I found if anyone wants to vote too:

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/414279
