### ISSUE TITLE
Connect converstion number with Converstion url for auto login

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3304]
I didn't see the ticket number with a link in either ticket body or footer, per auto login module says, user can log in their account after following the email ticket number link. How can I set up? I can see only this {%conversation.number%} tag, I cannot find the conversation url so that I can connect url to number and put it on the footer, do you have any other suggestion? Thanks
PHP version: 8.2
FreeScout version: 1.8.94

**Comment by jeffrey4680** [comment]
Sorry, it is a typo. Conversation

**Comment by freescout-helpdesk** [comment]
You don't need to do anything - just activate the Auto Login Module and proper URLs will be set in the email notifications automatically.

**Comment by jeffrey4680** [comment]
I don't see the ticket number with a link either in email header or email body, this is why I am asking this question. Thank you for the response. Please see the screenshot https://prnt.sc/7sqavzI0Y9EQ

**Comment by freescout-helpdesk** [comment]
What you have on screenshot is not a user email notification - it's an email to a customer.

**Comment by jeffrey4680** [comment]
This is an email to customer which was exactly sent by a user https://prnt.sc/QaBgMiluFdWi

**Comment by freescout-helpdesk** [comment]
Auto Login Module does not work with emails to customers.
