### ISSUE TITLE
{%mailbox.fromName%} empty on email compose

### ISSUE THREAD

**Issue by naturaw-canine-food** [freescout-helpdesk/freescout#3305]
Hey - new here - new to the system - 2 things that were noticed:

a. {%mailbox.fromName%} variable does not populate the user's name when the setting in the mailbox outgoing "From Name" is as shown below:
![image](https://github.com/freescout-helpdesk/freescout/assets/123727042/209129fb-0a39-4e85-9955-7635cf158bb6)

- It is important for us to be able to create the From Name as custom & be able to add the agent's name, followed by the company name (for example).

b. By having the above From Name to custom, it also removes the  {%mailbox.fromName%} variable populating from the signature email. _If the above option is switched to either "Mailbox Name" or "User's Name", the signature variable populates again._
![image](https://github.com/freescout-helpdesk/freescout/assets/123727042/a0d22840-28c5-4374-b063-cc872158af37)

Am I doing something wrong? Is this functionality not possible?

**Thanks in advance,**
Panagiotis 🇬🇷

PHP version: 8.1.2-1ubuntu2.9
FreeScout version: 1.8.94

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1031
