### ISSUE TITLE
How can we update English translation files?

### ISSUE THREAD

**Issue by naturaw-canine-food** [freescout-helpdesk/freescout#3307]
How can one edit/add their own custom english file?

I noticed that by creating a manual en.json, I am able to add them in there and they take effect, however, how does one obtain the json in english?

Or what is the correct approach for what I need done?

**Comment by freescout-helpdesk** [comment]
There is no way to edit English translation as it's written right in the code of the app.

**Comment by freescout-helpdesk** [comment]
There are some .json files here: https://github.com/freescout-helpdesk/freescout/tree/dist/resources/lang
