### ISSUE TITLE
Article Overview in every Ticket

### ISSUE THREAD

**Issue by lucollab** [freescout-helpdesk/freescout#3308]
Dear FreeScout Community,

I run a FreeScout instance with about 20 mailboxes. The employees get along very well with the system, but have some wishes regarding the overview of the system.

I have two questions regarding this:

1. is there a possibility to adjust the blue tones that are displayed alternately for each ticket element?

2. Most important: is there a possibility to add an Article Overview to FreeScout? Such an Article Overview exists in e.g. OTRS and looks like this:
This overview shows a clear list of all ticket elements of a ticket at the beginning of each ticket.
![OTRS_5_Wikimedia_en](https://github.com/freescout-helpdesk/freescout/assets/14358967/615ece3a-5aef-43c5-8464-791fd60a21ec)

Thanks a lot for your help,
with best regards
Lukas

**Comment by freescout-helpdesk** [comment]
> 1. is there a possibility to adjust the blue tones that are displayed alternately for each ticket element?

Only by editing CSS.

> 2. Most important: is there a possibility to add an Article Overview to FreeScout? Such an Article Overview exists in e.g. OTRS and looks like this:

It's not quite clear what you mean under Overview.

**Comment by lucollab** [comment]
thanks for your help!

1. I run Freescout using Docker. What would be the best and cleanest way to edit the CSS data?

2. Please excuse the not quite clear description. Our employees used to use OTRS and therefore still know the view shown in the screenshot. At the beginning of each ticket there is a small list of all ticket elements of a ticket. This list is called Article Overview.  

In the screenshot, the list has two individual elements:

1. customer - email-external
2. agent - email-external

these two elements are shown again in full form below this Article Overview. Clicking on an element will take you to the detailed form further down in the ticket history.

This Article Overview is only meant to be a clear list of all ticket elements of a tick in order to keep an overview and to be able to jump directly to individual tickets if necessary.

**Comment by freescout-helpdesk** [comment]
> What would be the best and cleanest way to edit the CSS data?

This module https://freescout.net/module/customization/ allows to add custom CSS.

Regarding the Overview block - feel free to submit a feature request https://freescout.net/request-feature/, maybe someone will implement it as a custom module.
