### ISSUE TITLE
Google recaptcha not working for China mainland

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3311]
PHP version: 8.2
FreeScout version: 1.8.94  
Hi there, I just got an Extra Security Module because of security considering. Unfortunately, Google reCaptcha doesn't work for Chinese mainland vistors because all google services are blocked by China's GFW. I just find a document in regard to how to bypass google GFW and using Recaptcha service. Can you please add this feature to that module so that I can use it properly, since it has a chinese language page only, you may have to translate to your language with some tool. Sorry about that.https://cloud.tencent.com/developer/article/2199414

**Comment by freescout-helpdesk** [comment]
Fixed in Extra Security Module v1.0.2
