### ISSUE TITLE
Japanese subject garbled

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3312]
Hi,

1,How it looks when garbled.
![Screenshot from 2023-08-29 14-58-19](https://github.com/freescout-helpdesk/freescout/assets/42058913/cdf6e83f-eaf5-4549-9298-e96ab521ddd9)

2,How it should look.
  
![Screenshot from 2023-08-29 14-59-37](https://github.com/freescout-helpdesk/freescout/assets/42058913/8e7dab8e-bdac-4deb-85cc-0139da8f61cd)

3,How it looks in the original code of the email (or attach .EML file).
![Screenshot from 2023-08-29 15-01-13](https://github.com/freescout-helpdesk/freescout/assets/42058913/2e2efbc5-7d6f-4f1c-a9f7-23608afd1128)
```
Subject: =?ISO-2022-JP?B?GyRCIVpLST9lISY7Xz9lRkM9OCFbQmZJdyRkOWsxKyRKGyhC?=
 =?ISO-2022-JP?B?GyRCJEkkSyRoJGs/Oz9lSG8zMiQrJGk3ekoqJHI8aSRrO18/ZUhEGyhC?=
 =?ISO-2022-JP?B?GyRCJGQhIk1NITkkSktJP2U0WE8iQD1JSiRKJEkkciVUJUMlLyUiGyhC?=
 =?ISO-2022-JP?B?GyRCJUMlVxsoQg==?=
```

In addition to this.
Fetching result displays different garble text ( it looks only first and last line is decoded). 

```
[2023-08-29 15:06:11] Fetching UNREAD emails for the last 8 days.
[2023-08-29 15:06:11] Mailbox: テスト
[2023-08-29 15:06:11] Folder: INBOX
[2023-08-29 15:06:11] Fetched: 1
[2023-08-29 15:06:11] 1) 【防水・止水特集】台風や豪雨な=?iso-2022-jp-ms?B?GyRCJEkkSyRoJGs/Oz9lSG8zMiQrJGk3ekoqJHI8aSRrO18/ZUhEGyhC?= =?iso-2022-jp-ms?B?GyRCJGQhIk1NITkkSktJP2U0WE8iQD1JSiRKJEkkciVUJUMlLyUiGyhC?= ップ
[2023-08-29 15:06:11] Message from: Customer
[2023-08-29 15:06:12] Thread successfully created: 2571
[2023-08-29 15:06:12] Fetching finished
```

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by totake0224** [comment]
I try to identify this problem and found,
around line 914 of App/Misc/Mail.php
   $subject = str_ireplace('=?iso-2022-jp?', '=?iso-2022-jp-ms?', $subject);
comment out this line will solve this garbled subject. but I confirmed this make another garbled text.

when line 914 of App/Misc/Mail.php commented out
1,How it looks when line 914 commented out.
![Screenshot from 2023-08-29 15-27-29](https://github.com/freescout-helpdesk/freescout/assets/42058913/c6f7fe17-e093-4bee-a85b-049e4b62da1f)
2,How it should look.
 ![Screenshot from 2023-08-29 15-27-50](https://github.com/freescout-helpdesk/freescout/assets/42058913/042459b5-9d98-495d-a051-82d7c5fa5a0e)
3,How it looks in the original code of the email (or attach .EML file).
![Screenshot from 2023-08-29 15-30-37](https://github.com/freescout-helpdesk/freescout/assets/42058913/57eae30e-9b6e-4095-a469-c6a395cd2ecb)

`Subject: =?iso-2022-jp?B?GyRCLWokIiQkJCYkKCQqfGIkKyQtJC8kMSQzLSEkRy0iGyhC?=`

**Comment by totake0224** [comment]
Thank you.
I confirmed this at master branch.

**Comment by totake0224** [comment]
it seems perfect. I did not experience any garbled subject until now.
