### ISSUE TITLE
quote below original message not visible

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3314]
I received a message of a client created by Thunderbird 102.14.0
The client answered and quoted his message below, not above the original message. I think this is the default setting in Thunderbird.
Unfortunately FreeScout doesn't recognize it and displays an empty message. Via clicking on "original message" it can be retrieved.

PHP version: 8.2.9
FreeScout version:  1.8.94

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/267a1821-ce90-489a-9a08-918f8a4837af)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-a-customer-replies-within-the-cited-text-freescout-does-not-show-it

**Comment by mokkin** [comment]
Ok, thanks for the hint. I enabled the email header. Maybe it helps reducing the issue.
