### ISSUE TITLE
ISSUE - Server time zone vs Freescout Time Zone

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3317]
@freescout-helpdesk 
I would like to propose a slight change in the time-zone setup.

In our example, the server is set to 
![image](https://github.com/freescout-helpdesk/freescout/assets/902376/ddb809af-489e-4a4e-ab75-9cebdd9171ed)

In freescout we have to manually set time zone in the settings to the server time. If we do not do this, then everything is incorrect.
![image](https://github.com/freescout-helpdesk/freescout/assets/902376/d5802599-a640-414b-92a4-97e846919be3)

We then need to update all users to the same time-zones (as they are all in the same time-zone). 

**It would be more useful if the following happened at installation and user creation**
1. Settings page could default to the server time. So the information would be more accurate.
2. When adding a new user, the time-zone defaults to the time-zone used in the settings, as this would also make it more accurate for the user in terms of seeing the dates/time etc.

I think this would improve the date/time issue, as it was not 100% clear as to how this is setup.

I hope this makes sense.
M

**Comment by freescout-helpdesk** [comment]
How did you install the FreeScout?

**Comment by raramuridesign** [comment]
@freescout-helpdesk I think it was manual. But hounestly I cannot remember, as its been running for sometime.

**Comment by freescout-helpdesk** [comment]
![2023-08-30_10-18-30](https://github.com/freescout-helpdesk/freescout/assets/40499291/7d438501-73be-493c-8486-e4fa82b8bb64)

You choose Timezone during installation and all users when you create them have this Timezone by default.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Ok, thanks, I will check this out when we do a new installation.
Closing for now.
