### ISSUE TITLE
module mail signing & ecryption can not sending testing email

### ISSUE THREAD

**Issue by abunajmi** [freescout-helpdesk/freescout#3318]
Dear Admin,
module bug when i try to sending testing email using mail signing & encryption  there is error like this
![Screenshot error bug freescout 2023-08-30 211947](https://github.com/freescout-helpdesk/freescout/assets/47467302/c44f54fd-0bdf-4ffe-8e34-8b8110b56ed3)

hope you could give silution for this issue thank

**Comment by freescout-helpdesk** [comment]
Apparently the key has not been uploaded properly: https://stackoverflow.com/questions/32937118/gnupg-get-key-failed-in-php

Make sure your file permissions are OK in Manage > System. See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by abunajmi** [comment]
I have tried to create an OpenPGP key pair on Kleoptara without a keyphrase according to the instructions provided in the mail signing and encryption document, so how do I get the gpg key to be uploaded correctly, what steps must be taken, I really hope you can help me with my difficulties, thank you

**Comment by freescout-helpdesk** [comment]
> Make sure your file permissions are OK in Manage > System. See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

Also check errors in Manage > Logs > App Logs

**Comment by abunajmi** [comment]
This is the result of generating the key using the gpg --gen-key command

root@cakrawalamediasolusindo:~# gpg --list-keys
gpg: WARNING: unsafe permissions on homedir '/home/abunajmi/.gnupg'
/home/abunajmi/.gnupg/pubring.kbx
---------------------------------
pub   ed25519 2023-08-30 [SC] [expires: 2026-08-30]
      218A1A01FAAC832A92E84E95DEC895DB93E52A4C
uid           [ unknown] admin <admin@cakrawalamediasolusindo.com>
sub   cv25519 2023-08-30 [E] [expires: 2026-08-30]

pub   rsa3072 2023-08-31 [SC]
      29E882795D5BCBC746407783FEF4FBA5090BD201
uid           [ unknown] pimpinan <pimpinan@cakrawalamediasolusindo.com>
sub   rsa3072 2023-08-31 [E]

I think from the results of generating the key above, is there anything that is not appropriate, please give me your guidance and guidance, thank you

**Comment by abunajmi** [comment]
i have check the manage sistem everything is ok here the setting :

![Screenshot 2023-08-31 140820](https://github.com/freescout-helpdesk/freescout/assets/47467302/6d7495aa-63df-44ab-acc9-af0a99377c21)

**Comment by freescout-helpdesk** [comment]
Try https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85

**Comment by abunajmi** [comment]
I have set the directory permissions but the error is still the same as get_key failed

**Comment by freescout-helpdesk** [comment]
Unfortunately we don't have any other clues.

**Comment by abunajmi** [comment]
i have another issue the get_key failed is gone now the issue i attached below :
![Screenshot 2023-09-02 193614](https://github.com/freescout-helpdesk/freescout/assets/47467302/2d78847f-539a-4afd-a091-1e0640fa254b)

hope for this isseu you could give a clue to solve it out thanks

**Comment by abunajmi** [comment]
If trace the log email it give message like this:
Send error. get_key failed. Message-ID: reply-3-0c5da8ceae64a69d@cakrawalamediasolusindo.com

so from that error , may be you can give the clue for the solution

**Comment by abunajmi** [comment]
i trace the from send_error log there for the get_key failed is in this module get_key failed; File: /var/www/html/Modules/MailSigning/Lib/Gnupg.php (21) 

can you check that code for make sure right thank
