### ISSUE TITLE
Snooze time pickup dialog problem  

### ISSUE THREAD

**Issue by sau7777** [freescout-helpdesk/freescout#3322]
When system set to 24H time representation Snooze time picker still in AM/PM mode 

FreeScout version: 1.8.93
Snooze Version: 1.0.9

![snoose](https://github.com/freescout-helpdesk/freescout/assets/8371994/ba64a675-4b4f-44b2-add7-60185b977142)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
