### ISSUE TITLE
read_by_user flag

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3324]
I have intention to modify mailbox display that change font style whether conversation is read or not like ordinary mail client.
and I found [read_by_user] column at conversations table.
I think that column is not used.( I could not found code that set this column to 1)
Is it possible to use this column for this purpose ?
and, Is there any needs of this function.

**Comment by freescout-helpdesk** [comment]
Most likely it's not used. But keep in mind that there are many users in FreeScout and this flag should be unique for each user.

**Comment by totake0224** [comment]
Thank you.
I think it's better suspend this modification.
because I want to use official version of freescout.

**Comment by totake0224** [comment]
Thank you.
I think it's better suspend this modification.
because I want to use official version of freescout.
