### ISSUE TITLE
Possible mistake in 1.8.95 - variable named $time instead of $date

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3325]
I have not updated yet but scrolling through the changes, I noted this line which seems incorrect.

https://github.com/freescout-helpdesk/freescout/blob/9be2c1df5a14747a811156b0bc08730107f1c24f/app/Console/Commands/FetchEmails.php#L1023

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Thanks. It will be fixed in the next release.
