### ISSUE TITLE
New Connection Issue in 1.8.95

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3326]
Running 1.8.95 in Docker (php8.2-1.17.24). Every action such as adding a note, moving a conversation, changing status, or replying to an email shows a connection error.

![Image 2122](https://github.com/freescout-helpdesk/freescout/assets/96336813/e97ec0a5-9a46-4c34-abdd-91cf0e22cfe6)

It appears to have failed and never actually shows that the action completed.  When refreshing or checking where the conversation is supposed to be, it appears that everything worked correctly each time.  In one case, my three apparently unsuccessful attempts to move a conversation to another mailbox somehow shows the following:

![image](https://github.com/freescout-helpdesk/freescout/assets/96336813/94eb5201-cd9e-4cd1-aeb7-02f583733c93)

Reverting to php8.2-1.17.23 resolves the issue.

**Comment by freescout-helpdesk** [comment]
Anything in logs?

**Comment by freescout-helpdesk** [comment]
Also are you using CloudFlare? It's rules may block some requests.

**Comment by freescout-helpdesk** [comment]
> Column not found: 1054 Unknown column 'counter' in 'field list'

Migration did not work when you updated Workflows Module. Run the migration in Manage > System > Tools.

**Comment by freescout-helpdesk** [comment]
Now FreeScout in the `DB` section on Status page will show migrations which have not been migrated yet.
