### ISSUE TITLE
Kanban Board: Longer email addresses should be hidden perhaps with a hover over?

### ISSUE THREAD

**Issue by naturaw-canine-food** [freescout-helpdesk/freescout#3328]
Issue with longer email addresses coming off the view.

![email view](https://github.com/freescout-helpdesk/freescout/assets/123727042/0306de71-361a-4bbc-a5c1-f8b0ac19353c)

Kanban Board: Longer email addresses should be hidden perhaps with a hover over?

**Comment by freescout-helpdesk** [comment]
Whose email is it? How are you displaying it? Is it a part of the conversation text preview?

**Comment by freescout-helpdesk** [comment]
Can you send full screenshot to support@freescout.net

**Comment by freescout-helpdesk** [comment]
We've figured it out: you have customers without names, so their emails are being shown instead.

Fixed in Kanban Module v1.0.16
