### ISSUE TITLE
Content of the E-Mail is not parsed when the an attachment has no name

### ISSUE THREAD

**Issue by frommMoritz** [freescout-helpdesk/freescout#333]
When one of our contacs sends an E-Mail containing an Attachment without a name no text from the E-Mail gets parsed. Therefore, only the attachments are displayed. While this certainly is't complaint with any standart, it happens and users are user..

**Comment by freescout-helpdesk** [comment]
Related to https://github.com/freescout-helpdesk/freescout/issues/320
