### ISSUE TITLE
Loopback: Exclude domains or emails

### ISSUE THREAD

**Issue by naturaw-canine-food** [freescout-helpdesk/freescout#3332]
I don't know why I was asked to post this here - but here it goes anyways:

![image](https://github.com/freescout-helpdesk/freescout/assets/123727042/f67761ff-1caf-418a-aba6-13f535f5c55a)

Sometimes we need to CC someone internally but that someone may be an email inside the CRM.

This causes a loopback between freescout and the email coming in, and starts to send the auto reply from freescout back to the email fetch.

**Comment by freescout-helpdesk** [comment]
> This causes a loopback between freescout and the email coming in, and starts to send the auto reply from freescout back to the email fetch.

How to reproduce this? Write a step-by-step instruction.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Step 1 and 3 are done in the same FreeScout instance?

**Comment by freescout-helpdesk** [comment]
If someone will be able to reproduce it - try to fix it and send pull request.
