### ISSUE TITLE
data signing failed

### ISSUE THREAD

**Issue by abunajmi** [freescout-helpdesk/freescout#3333]
Dear Admin,

I have found new error from your aplication about data signing failed when i try to test send email using pgp sing & encryption feature , in meanwhile i try to test using gpg encryption in terminal using gpg sintax " echo "test" | gpg --clearsign and the result give me below , if the result as such as i gave below it means the data has been sign successful is that corect? but why when I try to test via appilcation it's always came's up " data signing failed"

test
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEEShEMepkl6noqDHp4DIYJBh9uAjQFAmT1POEACgkQDIYJBh9u
AjSskAv+K91TJrQWltcQrDAluZOt6FiPmVppfFRKFtjUdJYT65MjLm1XhO87zGw7
8MYP3tYhre8eBJvFJQsIb2Tq4mp2xxl66EuNoC5QhTEM/mSd6GRHEVyoVfj3qSpW
5deBaJtdKfoFFnB08tHVq8XK7Js5s/5/6t19D7oz6UzPftN6HX6gTlrADTxuHFt6
jqVujEVP58ptWZ+poQ+GAiUmSrzIG4vs5xFFT5nbGHLMM1UB+pgOGWwFo/unQ0Bg
Tt89lPni1k9sdsyzyYK/OWjszyacrkEpAbNBfq8aeGsqr+/UyMD85raLbrPg7m32
yzimIaMfUoxxrkR/rCK4cFRLgJ6g5dLxxdfCYInaURpGEh246iHQxlohULyo0NRY
PNPM51k7sT32i7yttTdOEhRa2hSJe5hojBHN3ZS3aFG1prRfETMM3H9KaWVtFWqv
AStpo/eFUfmB5Yv42DwSbvB2UnCNFQaN/Zgm9RL6vceCSBK4FCgHjej93PHjd9OQ
DedZt9Di
=TxVz
-----END PGP SIGNATURE-----
abunajmi_new@mailal:~$ echo "test" | gpg --clearsign

hope you could give me clue for the solution for this issue thanks

**Comment by freescout-helpdesk** [comment]
You are the first having all these issues https://github.com/freescout-helpdesk/freescout/issues/3318 with signing & encryption. The problem may be in your operating system, gpg configuration or in PHP. Anyway it looks like you need someone who can perform a deep investigation on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).

**Comment by abunajmi** [comment]
ok thank about your suggestion , but before I would like to know about your mail signing & encryption spesification to be running I want to know about what nupg version support for this module? I hope you give the information thanks, I Worried my gnupg installed version not support

**Comment by freescout-helpdesk** [comment]
We've tested on gpg (GnuPG) 2.2.4. It's unlikely that the problem is in Gnupg version.

What's your operating system and PHP version?

**Comment by abunajmi** [comment]
I have try in operating system ubuntu 22.04 and php version 8.1.2 , I came's up with the isseu I have found and told you above, so what's your suggestion to make your module running smoothly , hope you can give information :
what gnupg , php and operating system version requirement to run well that module , thanks anyway for all your respon

**Comment by freescout-helpdesk** [comment]
Any Gnupg version should work. See https://github.com/freescout-helpdesk/freescout/issues/3333#issuecomment-1704635573
