### ISSUE TITLE
Can not install module correctly due to symlink error.

### ISSUE THREAD

**Issue by gaozhenbao** [freescout-helpdesk/freescout#3335]
When I purchased the API and webhook module and install it on my server,  when I try to active the module, the ajax requeset get 500 error and below is the error message. I think it blocks all modules installed.  Please review it.

[2023-09-04 02:15:21] production.ERROR: Call to undefined function App\Console\Commands\symlink() {"userId":2,"email":"david@verdanttea.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function App\\Console\\Commands\\symlink() at /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Console/Commands/ModuleInstall.php:105)
[stacktrace]
#0 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Console/Commands/ModuleInstall.php(83): App\\Console\\Commands\\ModuleInstall->createModulePublicSymlink()
#1 [internal function]: App\\Console\\Commands\\ModuleInstall->handle()
#2 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#3 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#6 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#7 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#8 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#9 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#10 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#12 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#13 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(177): Illuminate\\Console\\Application->run()
#14 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(249): Illuminate\\Console\\Application->call()
#15 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call()
#16 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Controllers/ModulesController.php(321): Illuminate\\Support\\Facades\\Facade::__callStatic()
#17 [internal function]: App\\Http\\Controllers\\ModulesController->ajax()
#18 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#19 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#20 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#21 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#22 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#23 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#24 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Middleware/CheckRole.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#25 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckRole->handle()
#26 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Middleware/CustomHandle.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#28 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle()
#29 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#31 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle()
#32 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#34 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle()
#35 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Middleware/HttpsRedirect.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#37 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle()
#38 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#40 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#41 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/overrides/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#43 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#44 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#46 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#47 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#49 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#50 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#52 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle()
#53 /home/1070809.cloudwaysapps.com/taryyftfmd/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

PHP version: PHP 8.1.22
FreeScout version: 1.8.94

**Comment by freescout-helpdesk** [comment]
Apparently `symlink()` function is disabled in your PHP.

**Comment by gaozhenbao** [comment]
@freescout-helpdesk yes, you are right. I found it today. Thank you.
