### ISSUE TITLE
Can not find translation string for End user Portal Headline

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#3336]
Hi, 
quick question:
I can not find the translation string for this line of text in the End user portal:

![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/791def3e-f202-4a0b-b0d0-b517c3d6a100)

I searched here, but I think it is not there:
![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/dcf9b29a-6533-4001-a25d-1ea8ecbd3e20)

Where can I change the headline of the End user Portal (embedded via iframe) in German?

**Comment by ar-ml** [comment]
Thanks for your reply @freescout-helpdesk 

Unfortunately it does not work:
Even after hitting this button, I am not able to translate the Headline of End user Portal:
![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/677a4536-8939-4b4e-949a-229871ea18db)

It looks like this, obviously many German strings have not been imported / are missing (which is not my primary problem here). Primary problem is: I can not find the string, which is responsible for the end user portal headline:


![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/0423e770-f3a9-48a9-8be5-b8a6e2b2185f)

**Comment by ar-ml** [comment]
Please note: 
Under End-User-Portal settings there is another text field where I can enter some kind of headline for the end user portal. Maybe this is somehow conflicting with the translation system?

![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/12f635d1-a7a0-4f0d-8f53-e753271d17b9)

**Comment by ar-ml** [comment]
And I can see that the text I entered for the headline in the  End-User-Portal settings, will show up If I open the end user portal in a new tab from there.

But If I integrate it via iframe (using the "open in new window" link at the bottom of the End-User-Portal settings page) the header of the end user portal will look different (blue) and have a different text content.

**Comment by ar-ml** [comment]
![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/620e99e6-4b03-40ba-960e-5b64fe42e340)

**Comment by freescout-helpdesk** [comment]
> And I can see that the text I entered for the headline in the End-User-Portal settings, will show up If I open the end user portal in a new tab from there.
> 
> But If I use the "open in new window" link at the bottom of the End-User-Portal settings page, the header of the end user portal will look different (blue) and have a different text content.

Yes. This is how it works. The form is present in two places:
- End-User Portal itself. It's title is controlled via "Submit a Ticket" field in End-User Portal settings.
- In a Contact Form Widget. It's title is "Contact us". It's language and color is controlled via options in End-User Portal settings.
