### ISSUE TITLE
"Allow to reply from aliases" option is set to false after saving

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3337]
When an administrator sets the mailbox option "Allow to reply from aliases" to true (check the box), saves it and later someone else edits the signature (same page), the option is set to false in the background. The person who update the signature, is only permitted to edit the signature of the mailbox. So the checkbox for "Allow to reply from aliases", is not visible for them.

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
