### ISSUE TITLE
Manual workflows don't show up in table view

### ISSUE THREAD

**Issue by StefanWirsingStretta** [freescout-helpdesk/freescout#3340]
As the title says, my manual workflows show up in an individual conversation but not in the table view:

It's just a blank menu.

Help is appreciated.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/45820616/1ce950ce-3068-475c-a325-837c2029c056)

**Comment by freescout-helpdesk** [comment]
Make sure you are checking right mailbox and your workflows are active.

**Comment by StefanWirsingStretta** [comment]
I am in the right mailbox and the workflows are active. I have de- and reactivated them, I've created new manual workflows. It always shows up blank.

**Comment by freescout-helpdesk** [comment]
If you are in the Global Mailbox you won't see workflows there.

**Comment by StefanWirsingStretta** [comment]
Not a global mailbox.

**Comment by freescout-helpdesk** [comment]
Can you attach screenshots of one of workflows.

**Comment by StefanWirsingStretta** [comment]
Sure:

![grafik](https://github.com/freescout-helpdesk/freescout/assets/45820616/f6f8cf30-68dd-459d-b714-4f06fded16fe)
![grafik](https://github.com/freescout-helpdesk/freescout/assets/45820616/6ded694f-bc9d-425e-be84-0acbedc5e928)

**Comment by freescout-helpdesk** [comment]
Check in the browser console (https://balsamiq.com/support/faqs/browserconsole/) and send to us.

**Comment by freescout-helpdesk** [comment]
Also add the following code after line 271 in /Modules/Workflows/Providers/WorkflowsServiceProvider.php
```
            \Log::error('[Debug workflows] mailbox_id: '.$mailbox->id);
            \Log::error('[Debug workflows] count: '.count($workflows));
```

And send us lines starting with _"[Debug workflows]"_ from Manage > Logs > App Logs ("laravel...log").
