### ISSUE TITLE
Some HTML emails have bad formatting

### ISSUE THREAD

**Issue by naturaw-canine-food** [freescout-helpdesk/freescout#3342]
Some emails are shown with the html formatting as broken. Although the email is fine on outlook for web.

Issue persists when we forward the email, it gets broken to what you see below.

Anyway to fix it?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed
