### ISSUE TITLE
Time Tracking Module - manuel mode

### ISSUE THREAD

**Issue by BeSt1979** [freescout-helpdesk/freescout#3344]
Hi.

I was excited to discover today that a couple of updates to TimeTrackingModule have come out, bringing manual mode among other things.

But unfortunately I do not understand it. I have switched to "manual". Now I can start and pause time tracking with the play and pause icons. But I still can't save a time entry in a way that I can save multiple "work packages with one time entry" in one ticket.

Is this still not possible with the manual mode, or did I not understand it?

Regards
Benjamin

**Comment by freescout-helpdesk** [comment]
> But I still can't save a time entry in a way that I can save multiple "work packages with one time entry" in one ticket

We can't understand what you are trying to say.

**Comment by BeSt1979** [comment]
With the "manual mode" I imagine the following functionality:

Besides the "Play" and the "Pause" button I wish to have a "Save" button. If you then click on this button, then a "work package" is saved in the ticket, so that it then looks like on the following "mockup":

![mackupFreeScout](https://github.com/freescout-helpdesk/freescout/assets/5738613/7df1c565-4653-4c62-9530-5241d8f13ced)

An exciting extension of this function would be if you could also enter a short description for each "work package" stored in this way. In this way, after the ticket has been completed, it would be possible to show the customer when the ticket was worked on and for how long, and what was done in these "work packages" / time periods.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
