### ISSUE TITLE
Problems fetching IMAP emails on custom mail server 

### ISSUE THREAD

**Issue by Pablohn26** [freescout-helpdesk/freescout#3345]
```
PHP version:  8.2.10
FreeScout version: 1.8.95
`````

Hi, I have had issues fetching emails using a custom mail server. The error I was having is:
```
Error: imap_open(): Couldn't open stream {mydomain.com:993/imap/tls}. [CLOSED] IMAP connection broken (server response); File: /www/html/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)
```
![image](https://github.com/freescout-helpdesk/freescout/assets/1228418/9f63cba0-edf8-4579-be9a-d3ab6aca4fac)

I have fixed it [using this](https://github.com/freescout-helpdesk/freescout/issues/2591#issuecomment-1434150716) as it is documented [here](https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#common-issues), but that documentation does not contain exactly the error that I mention.

My custom mail server is providing TLS connection using port 993 and STARTTLS connection using port 143. After adding `APP_NEW_FETCHING_LIBRARY=true` and clearing cache I can confirm fetching is only working with port 993 TLS connection. 

@freescout-helpdesk I have created this issue because this info could be useful to help people that is having email fetching problems. I think would be useful adding to [Fetching emails common issues](https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#common-issues) the error `IMAP connection broken (server response)`. Feel free to close this issue as it is just for information.

**Comment by freescout-helpdesk** [comment]
Thanks, added to https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#common-issues

**Comment by daljitsingh** [comment]
I wanted to share my experience for anyone who might find it relevant. After trying all the troubleshooting steps mentioned in various threads, including this one, I was still unable to resolve the "Error: imap_open(): Couldn't open stream...".

**My Setup:**

- Shared hosting server
- 1-click installer Freescout
- Email provider: Migadu

**The Issue:**

In Freescout, "TLS" means StartTLS, whereas "SSL" means TLS (in Migadu). Simply switching from TLS to SSL fixed the issue for me.

However, now I'm facing very slow email sync. Can anyone direct me to the relevant thread to address this?

**Comment by catbadger** [comment]
The new owners of the company fired me. sadface. are you guys hiring?
