### ISSUE TITLE
Connection Settings - Fetching Emails - IMAP Folders

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3346]
When I chose "Get folders", some of the folder names were so long that they extended beyond the right edge of the text box.  I was unable to click on the X to delete that folder because the right edge of the folder name and the X were hidden from view.  The folder name was long, in part, because it was a nested folder and the path of that folder was displayed.

This issue might be of lesser significance if the following feature request is implemented since the user will manually select the folder from the dropdown: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/418349

**Comment by freescout-helpdesk** [comment]
Unfortunately won't be fixed by us. Feel free to submit a pull request.
