### ISSUE TITLE
Menus Extending Outside of Viewport

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3347]
Selecting "Mailbox Settings" for the top row of mailboxes on the dashboard page causes the top of the menu to extend above the top of the viewport.  Five items in the menu are hidden from view.
![Image 2132](https://github.com/freescout-helpdesk/freescout/assets/96336813/73bbb945-ffbd-4db1-aeb8-4991c534082a)
![Image 2133](https://github.com/freescout-helpdesk/freescout/assets/96336813/006e80ce-c8c2-42ec-9239-2c1199867a98)

**Comment by freescout-helpdesk** [comment]
Click one of the items and after that select the one you need.
