### ISSUE TITLE
still curios with your module

### ISSUE THREAD

**Issue by abunajmi** [freescout-helpdesk/freescout#3348]
I'm still curious about your module, from your previous answer that there is something wrong with my gpg configuration, then I tried this command: gpg --encrypt --sign -r admin@cakrawalamedia Solusindo.com test.txt and it worked , then regarding PHP, from the moment I installed it until I ran it, I didn't change anything, I installed and activated the module, after I ran it, that's all, nothing else, are there any steps that can be taken to ensure that this module can run normally? Can you try the freescout demo for mail signing and encryption? I really hope for a response from you

Thank's for you respon

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3333#issuecomment-1704635573
