### ISSUE TITLE
Chat window for web-version looks broken on iPhone SE

### ISSUE THREAD

**Issue by mit2sumit** [freescout-helpdesk/freescout#3349]
On iPhone SE or smaller screens, as I start typing, the chat window zooms in and I see horizontal and vertical scroll.
I initally get lost on how to press send or close the popup as its not there on visible-area. See screenshot attached below.
![IMG_7339](https://github.com/freescout-helpdesk/freescout/assets/5330405/27e2c989-1b6a-43b4-b341-f84db13e7747)
You can check that on our [website](nknews.org). 

PHP version: 8.2.8
FreeScout version: 1.8.90

**Comment by freescout-helpdesk** [comment]
Have you embedded the chat into the iOS app or you are using standard iOS browser?

**Comment by mit2sumit** [comment]
> Have you embedded the chat into the iOS app or you are using standard iOS browser?

Yes, Its from safari browser on iPhone.

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://freescout.net/chat-demo/ ?
