### ISSUE TITLE
Option to add a custom Ticket Status "Closed without conversion"

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#3350]
Hi!
Is there an option to add another ticket status "Closed without conversion"?

It should behave like any closed ticket, but for statistical reasons it would be very interesting to close tickets that did not generate any revenue in a special way. Especially in combination with timetracking and reports module this would be great!

![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/340edc84-f33f-47a7-8353-e4eba264edfd)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by FranciscoTemponi** [comment]
How we do to change the default status name? We need, Active -> "To Do" , Pending -> "Em andamento" , Close -> "Fechado"

**Comment by freescout-helpdesk** [comment]
> How we do to change the default status name? We need, Active -> "To Do" , Pending -> "Em andamento" , Close -> "Fechado", this is the basic feature to all platforms. We need urgency.

You do it in "Manage > Translate". Just keep in mind upon application update custom translations may be overwritten.
