### ISSUE TITLE
Star mark getting lost when merging tickets

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#3351]
**Steps to reproduce:**
- Create a new ticket, lets say # 001
- Mark ticket # 001 with a star.
- Create another ticket, lets say # 002
- Now merge ticket # 001 with # 002

-> Star mark is getting lost, merged ticket will not have a star.

**Expected behaviour:** 
Star mark should be transfered from the old ticket to the merged ticket.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/.github/ISSUE_TEMPLATE/general_help_request.md

> Create separate issues for different topics - no need to mix all your problems into one issue.

**Comment by ar-ml** [comment]
Ok, I created a separate issue for the problem with the tags getting lost on merging the tickets: #3353
