### ISSUE TITLE
Tickets not generating from emails with over 16 recipients

### ISSUE THREAD

**Issue by magicsurfer** [freescout-helpdesk/freescout#3352]
PHP version: PHP 8.1.2-1ubuntu2.11
FreeScout version: 1.8.71

Good morning,
I have experienced a weird issue with one of the installation of FreeScout have on a customer.

The installation has 26 mailboxes managed under FreeScout (the mailbox is on Office365 tenant) and I found out that when an email arrives and has as recipiets over 16 of the mailboxes managed under FreeScout , the tickets don't get generated for all of them.

Sometimes tickets get generated for 2 out of the 17 recipients, sometimes 16 out of 17 get the ticket.
There are no errors reported in the logs and the fetching seems to happen for every mailbox without fail since the emails get moved into the specified IMAP folder set on the mailbox fetching settings.

For example an e-mail arrives at 18 mailboxes on office 365, all of which are managed on FreeScout, only 16 tickets get generated for 16 of those mailboxes under FreeScout, for the remaining 2 no tickets get generated but the email is still moved in the specified outlook folder as if FreeScout read it

I tried many combinations but couldn't figure out a pattern for this issue, I also tried disabling the workflow module thinking it might affect the fetching but nothing changed, I also tried to increase the fetching time settings to 2 minutes thinking FreeScout just didn't have enough time to process all the emails before timing out but even that didn't change a thing unfortunately.

The issue presents itself both with emails sent from mailboxes of the same domain of the email managed by FreeScout and also form mailbox outside FreeScout domain (for example mail sent by xxx@gmail.com).

Each and every mailbox has been tested individualy and presents no issue when receiving emails nor when generating tickets from emails with under 16 recipients.

I considered updating both FreeScout and the modules but none of the changelogs mentioned anything that could relate to this issue in my eyes so i'm a bit hesitant since other than this weird issue everything else is working nicely.

In case further informations or tests are needed please let me know.
Any idea what could cause this?

Thank you for the support

**Comment by freescout-helpdesk** [comment]
Here is the place to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L125

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue.
