### ISSUE TITLE
Tags getting lost when merging tickets

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#3353]
When merging an older ticket that has tags with a newer ticket, that does not have tags, the tags will be lost.

**Expected behaviour:**
The merged ticket should have all tags of both tickets.

Loosing tags is actually even worse than the star mark getting lost (also see this issue here: #3351 ). ;-)

**Comment by freescout-helpdesk** [comment]
Fixed in Tags Module v1.0.35
