### ISSUE TITLE
Unable to process your update

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3354]
We have received three of the following emails today:

Subject: Unable to process your update
Your email update couldn't be processed
If you are trying to update a conversation, remember you must respond from the same email address that's on your account. To send your update, please try again and send from your account email address (the email you login with).

Let's call the user "Jane".  She logs into FreeScout with "jane@asdf.com" which is an alias of her usual email address "jdoe@asdf.com".  She has her own mailbox in FreeScout called "Jane" which has the Email Address jdoe@asdf.com.

The "Unable to process your update" emails appear as a new conversation in a mailbox called "Shared" (shared@asdf.com).  The customer email address is jdoe@asdf.com.

**Logs**

The Outgoing Emails log shows:

Sep 6, 03:24:27pm | User replied from wrong email address | shared@asdf.com | Accepted for delivery |   | Jane Doe |  
-- | -- | -- | -- | -- | -- | --

The Fetch Errors log shows:

Sender address shared@asdf.com does not match Jane Doe user email: jane@asdf.com. Add jane@asdf.com to user's Alternate Emails in the user's profile to allow the user reply from this address.

Jane Doe's profile shows jane@asdf.com in the Email field.  It is not clear why adding it again to the Alternate Emails field would be different.

The problem seems to be that Jane had enabled Email notifications for only "A conversation Jane is following is updated".  She was only following one conversation which explains why the issue coincided with notes in that conversation.

We are trying to use FreeScout for all purposes; users do not ever check their external email account.  Please advise what, if anything, is wrong with the setup.  Perhaps an entry in the FAQ section would be helpful.

**Comment by freescout-helpdesk** [comment]
It looks like quite complicated case. We can't grasp all your emails, aliases and mailboxes structure.
