### ISSUE TITLE
Workflow Module: Condition "Communication Channel" is missing a field!

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#3355]
I would expect a dropdown where I can select "Email" / "End User Portal" / ... There is no dropdown, see Screenshot.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/68ee4dac-eb83-4dbd-92b5-3037373687f4)

**Comment by ar-ml** [comment]
All Modules and freescout is up to date here. problem persists.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/4c77bf32-8fa8-4c38-9f6a-fdd9732d29ba)

**Comment by freescout-helpdesk** [comment]
"Communication Channel" condition requires one of the following modules: Chat, Telegram Integration, Twitter Integration, Facebook Integration or WhatsApp integration.

**Comment by ar-ml** [comment]
Ok, thank you. Maybe a hint in the UI would be nice to easier understand this requirement.

Will close this ticket.
