### ISSUE TITLE
Problems with workflow in Live Demo

### ISSUE THREAD

**Issue by Fieck** [freescout-helpdesk/freescout#3356]
FreeScout version: 1.8.84

Hi, I'm having trouble when i add a new workflow and when i click save, it will say access denied and back to homepage. Does this mean that the live demo doesn't support trying out our own workflow?

I have another question regarding emailing back to customer. The email that i sent from Freescout is not received on my gmail and i tried to change the server but the access denied page pop up when im trying to change the mail settings. Is is not possible to test it out on the live demo as well?

**Comment by freescout-helpdesk** [comment]
Yes to both.
