### ISSUE TITLE
Kanban board: only owner can edit board settings

### ISSUE THREAD

**Issue by dvdjaco** [freescout-helpdesk/freescout#3358]
PHP version: 8.2.10
FreeScout version: 1.8.95

What we see: 
Kanban board settings can only be accessed by the user that created the board originally.

What we expected:
Any user with admin permissions on the mailbox linked to that Kanban board should be able to modify the board settings (eg to modify columns or swimlanes)

**Comment by freescout-helpdesk** [comment]
> Any user with admin permissions on the mailbox...

What do you mean under "admin permissions on the mailbox"?

**Comment by freescout-helpdesk** [comment]
Fixed in Kanban Module v1.0.17
