### ISSUE TITLE
Consider integrating replying to cutomer from Slack

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3359]
As the subject says, it seems like not possible to reply to customers from Slack, can you consider to integrate this feature in the next release? or something I configured wrong? Thanks
PHP version: 8.2
FreeScout version: 1.8.95

**Comment by freescout-helpdesk** [comment]
For this purpose a new module will be needed. Slack Notifications module is designed to send notifications to Slack only. Feel free to submit a feature request: https://freescout.net/request-feature/
