### ISSUE TITLE
ACL integration.

### ISSUE THREAD

**Issue by chetanmadaan** [freescout-helpdesk/freescout#336]
Would be great if there are multiple user levels who can login and only access tickets of a particular mailbox (NOT have to worry about connection settings and stuff).

**Comment by UnderDogg** [comment]
a good acl package is laratrust, find it here on github.
All you need to do is:
Install
Make up roles & permissions (in the config)
Apply permissions in the view files

**Comment by chetanmadaan** [comment]
Thanks for the update!
