### ISSUE TITLE
Workflow Not Evaluating Subject After Colon

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3361]
The workflow consists of two parts.  The second part of the workflow is:

AND

Subject does not contain ABC Company

An email with the subject "INTERAC e-Transfer: A money transfer from ABC Company has been automatically deposited." was received and the workflow still triggered.

My suspicion is that it stopped evaluating the subject after the colon.

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue.

**Comment by freescout-helpdesk** [comment]
There was an issue with checking subjects in older FreeScout versions but that issue has been fixed.
