### ISSUE TITLE
Cannot Save Lengthy Saved Reply

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3362]
When the saved reply is very long, the "Save Reply" button disappears from the bottom of the viewport.  The only to actually save this reply is to either:

- Reduce the page zoom so more information is displayed
- Press F11 to increase the available vertical height
- Change the monitor's resolution
- Move the browser tab to a vertical monitor

This is not intuitive.  There does not appear to be any option to scroll.

**Comment by freescout-helpdesk** [comment]
Can you attach a screenshot.
