### ISSUE TITLE
Snooze Module - Improved Documentation

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3363]
https://freescout.net/module/snooze/

This page does not say what happens if a person responds to the conversation while it is snoozed.  I assume that it becomes Active however is the Snooze cancelled?  If not, closing the conversation right away will result in it again being revived when the snooze period ends.

**Comment by freescout-helpdesk** [comment]
Canceling Snooze when customer replies implemented in Snooze Module v1.0.12
