### ISSUE TITLE
feature request - custom field for notes/replies

### ISSUE THREAD

**Issue by crisicon** [freescout-helpdesk/freescout#3364]
Hi

In many support organizations, there are two time-based parameters to track: SLAs and work effort. Additionally, for work effort, there is a need to track entries as they progress over a time period - something that is already achieved well by applications such as Kimai.
Which makes the time tracking in Freescout a bit too simple to achieve good results.

I'd suggest adding an extra field to notes and replies, for storing time worked.
I use this very method in two organizations and it is very effective. The platform used is OTRS the community edition, which I'd hapily replace with Freescout should it have that functionality.

The data in this field could then be available via API calls for entries and for billing systems.

Would that be something we could see in Freescout in the future?

**Comment by freescout-helpdesk** [comment]
Most likely not, but feel free to submit a feature request: https://freescout.net/request-feature/
