### ISSUE TITLE
Is it possible to make knowledge base completely private?

### ISSUE THREAD

**Issue by skippey1** [freescout-helpdesk/freescout#3365]
Hi.
We would like to use knowledge base for internal use only. Is there any way to disable the public functions completely or limit them for a certain mailbox?

Limiting the access to agents only does work for this, but we're a bit uncomfortable with the chance that someone could accidentally publish some internal document by forgeting to set a private category for example...

I tried to have look around here and in feature-request, but couldn't spot anything definite.

PS. We've had Freescout for a year now and so far liking it more and more.

**Comment by freescout-helpdesk** [comment]
No for now.

**Comment by skippey1** [comment]
Ok, thanks.
I'll make a feature request then: https://freescout.net/request-feature/
;)
