### ISSUE TITLE
[file ownership] cache objects getting ownership as "root'

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#337]
Hi Support
So we have a problem where our installation breaks after a short period of time.
Upon further investigation we seems to have 2 problems

**1. the ownership** of files located here
bootstrap/cache/
Seem to take on the ownership of root:root
This then causes the error: Whoops, looks like something went wrong

Our web-server does not have issues normally and we are unsure why some of the files here are taking on the ownership of root. Would help with some clarification.

**2. File & Directory chmod**
We also had issues when installing modules. This had to be done manually - and we found that the main files would install, but files located here would not be copied across.
public/modules/
The directory for the installed module was missing including the assets. This again resulted in the error above.
So we had to manually extract and upload this. 
Any insight as to why this was happening would be appreciated.

**Our solution** to solve the above (probably not ideal, but it works)
We created a bash script
Inside the bash script we 
- chmod files and folders to the correct settings (fixed point 2)
- set the chown to the projects users (fixed point 1)
- we also clear the cache using freescout artisan command
php artisan freescout:clear-cache

We hope the above can be  used by others experiencing the same issues.
If the developers of freescout could comment on the above it would be appreciated.
Matthew

**Comment by freescout-helpdesk** [comment]
1. Do you have any cron jobs running for **root** user?

2. Take a look at the latest suggested permissions structure: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
We have this cronjob running as root which does the schedule.
artisan schedule:run >> /dev/null 2>&1

Plus we also run the bash script above as root.

We have viewed the link and this is what we are running in our bash-script to stop the issue we are experiencing.

**Comment by freescout-helpdesk** [comment]
Cron job should executed under **www-data** user: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks. We have moved the cronjob to the user. Lets see what happens.
