### ISSUE TITLE
One Email Sent as Six Separate Emails

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3370]
We sent an email that had one recipient in the To field and five recipients in the BCC field.  One email was sent to just the recipient in the To field.  A separate email was generated for each BCC recipient with that email also being sent to the recipient in the To field.  In total, six emails were sent.  The recipient in the To field received all six emails.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue - To recipient receives one email. The issue may be related to your mail server.
