### ISSUE TITLE
Forwarding emails when the workflow rule is disabled 

### ISSUE THREAD

**Issue by Paul4466** [freescout-helpdesk/freescout#3371]
Hi All, 
A workflow was created to forward emails to another mailbox, after deleting this workflow the forwarding when creating a ticket still works, even when the workflow module is deactivated. Please help me how to disable this forwarding which was configured in the workflow. 
Thanks in advance 

App Version : 1.8.97 
PHP: PHP 8.1.2-1ubuntu2.14

**Comment by freescout-helpdesk** [comment]
Have you tried to clear cache?

**Comment by freescout-helpdesk** [comment]
Are you using Docker or Cloudron? Probably by some reason the background `queue:work` job keeps running and does not restart: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

**Comment by Paul4466** [comment]
Yes, cache was cleared

**Comment by Paul4466** [comment]
Freescout is installed on a physical server, how can I manually delete forwarding addresses that I have canceled?

**Comment by freescout-helpdesk** [comment]
> forwarding addresses that I have canceled

We can't understand what you are trying to say.
