### ISSUE TITLE
Company Profile

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#3372]
Is there a way out a module that allows us to connect customers to a company Profile or something along those lines?

For example u can assign a customer to a company, and you would be able to load the company Profile, use the users(customer) who are part of that profile, see a combined list of tickets open by all the users of that company, and be able to save notes and info to the company profile that would load in the company notes field of the customer assigned to that company or their tickets?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature.

**Comment by ilyakonovalenko** [comment]
For now you can probably add multiple emails to the same customer.
However, having an ability to ssign multiple customers to some property would be nice!
