### ISSUE TITLE
LogIn Page shows expried

### ISSUE THREAD

**Issue by ghost** [freescout-helpdesk/freescout#3374]
Hi Guys,
my login page always shows as expired in Free Scout. 
It doesnt help to refresh the page neither to delete the cookies or use another Browser.
Do you know what i can do?

**Comment by freescout-helpdesk** [comment]
Check your web server or CloudFlare caching.

**Comment by Tectu057** [comment]
No i am also getting the same reply and now he sends me to google to change my password?

**Comment by freescout-helpdesk** [comment]
It need to be checked on your server.
