### ISSUE TITLE
[issue] officehours restriction in effect

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3375]
@freescout-helpdesk 
**Issue with open_basedir restriction in effect**

Freescout: 1.8.97
PHP 8.2.x

**ISSUE**
As a result I cannot access the
/system/status
/modules/list

file_exists(): open_basedir restriction in effect. File(/home/projects/webapps/app-helpdesk/public/public/modules/officehours) is not within the allowed path(s): (/home/projects/webapps/app-helpdesk:/var/lib/php/session:/tmp) {"userId":1,"email":"[xxxx@xxxx.com](mailto:xxxx@xxxx.com)","exception":"[object] (ErrorException(code: 0): file_exists(): open_basedir restriction in effect. File(/home/projects/webapps/app-helpdesk/public/public/modules/officehours) is not within the allowed path(s): (/home/projects/webapps/app-helpdesk:/var/lib/php/session:/tmp) at /home/projects/webapps/app-helpdesk/public/app/Module.php:285)

**Comment by freescout-helpdesk** [comment]
See https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

Is this correct path to the folder with symlinks: /home/projects/webapps/app-helpdesk/public/public/modules/?

**Comment by raramuridesign** [comment]
@freescout-helpdesk Yes it is.

**Comment by freescout-helpdesk** [comment]
Try to replace line 285 in /app/Module.php with the following:
```
if (!@file_exists($from) || !is_link($from)) {
```

**Comment by freescout-helpdesk** [comment]
Check if `/home/projects/webapps/app-helpdesk/public/public/modules/officehours` symlink exists. If it exist where does it lead to?

**Comment by raramuridesign** [comment]
@freescout-helpdesk 

Symlink info

![image](https://github.com/freescout-helpdesk/freescout/assets/902376/6156fc44-d974-4ddf-af4e-a92654db3b06)

**Comment by raramuridesign** [comment]
@freescout-helpdesk I have solved the one issue, it seems like a symlink was created in this location, see image, I have removed this, and I can now access the sysinfo and module.
![image](https://github.com/freescout-helpdesk/freescout/assets/902376/fa7857b5-3902-4c78-9dee-dff169ed6fc1)

I am now checking the other instace if this has a similar issue

**Comment by raramuridesign** [comment]
@freescout-helpdesk It seems the other system the symlinks look incorrect.

![image](https://github.com/freescout-helpdesk/freescout/assets/902376/4899963f-ab3b-49ac-b44c-235b7f2d05d7)

to confirm the modules under public/Modules/...
Each individual module also contained symlinks which caused an issue.

I then removed these as well and it all works.

Now I have a new error looking at system status, see new issue.

https://github.com/freescout-helpdesk/freescout/issues/3378

Hope the above helps

**Comment by raramuridesign** [comment]
@freescout-helpdesk Are there meant to be symlinks in 
public/Modules/ directory?

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks. This solves it then.
But very strange that symlinks where created in thsi folder: public/Modules/
See this screenshot for office hours.
https://github.com/freescout-helpdesk/freescout/issues/3375#issuecomment-1713910735

I had a few folders with similar weird symlinks.

Perhaps you need to remove symlinks in this area if they exist?

**Comment by freescout-helpdesk** [comment]
Yes. Fixed in the `master` branch.

**Comment by raramuridesign** [comment]
Closing
