### ISSUE TITLE
[Question] Freescout & EU Cyber Resilience Act

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3379]
@freescout-helpdesk 
I am hoping you could shed some insight into this topic and what your thoughts are moving forward with such a Law in the EU
https://digital-strategy.ec.europa.eu/en/library/cyber-resilience-act

I don't want to open a hornets nest but if software like Freescout is to be used more widely in the EU, this act will be the first stumbling block for companies in the future.

For reference, this article is a good starting point to understand more from an opensource perspective.
https://devops.com/the-cyber-resilience-act-threatens-the-future-of-open-source/

Would be great to get some sort of understanding of where Freescout sits in this mix?

Thanks
M.

**Comment by freescout-helpdesk** [comment]
We'll try to make sure the project complies with CRA requirements over the time.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thank you.
