### ISSUE TITLE
SAML module - strict mode

### ISSUE THREAD

**Issue by cfoellmann** [freescout-helpdesk/freescout#3381]
With the current version of the saml module I could not get our SSO to work.

As a workaround I set strict = false in the source.
Could you please add a toggle in the UI to set Strict mode to false?

**Comment by freescout-helpdesk** [comment]
"Strict Mode" option has been added in SAML SSO Module v1.0.9

**Comment by cfoellmann** [comment]
was implemented in the release version from the freescout devs
