### ISSUE TITLE
Mails are not working

### ISSUE THREAD

**Issue by ghost** [freescout-helpdesk/freescout#3382]
Hey guys,
my connection now is working and I created a Company App in Azure AD and configured it how its shown in the faq.
But my inbox isnt loading into the freescout mailbox. And I can't send out any mails.
So config is right but nothing is working

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#troubleshooting-oauth-emails-fetching
