### ISSUE TITLE
Workflow condition last change / last ticket log entry

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3383]
Hey,

it would be great if there was a workflow condition for last ticket log entry or last change in ticket.

A lot of the time none of the current date-related conditions change, so there is no customer reply, no user reply, date created never changes and waiting since is the same as (user or customer) reply.

With this option, there would be a trigger for ticket assignments, changing ticket status, triggered workflows etc.

Thanks!

PHP version: 8.2.10
FreeScout version: 1.8.94

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/
