### ISSUE TITLE
update scripts

### ISSUE THREAD

**Issue by eljakim** [freescout-helpdesk/freescout#3384]
Would it be possible to change the `tools/update.sh` script with the following changes:

a) a flag '`--yes`' that answers yes to everything, also the database migration
b) a flag '`--modules`' that updates all modules (to be combined with '`--yes`' where needed)
c) a flag '`--dryrun`' that outputs whether something would be updated and what (to be combined with '`--modules`' to see updates for the modules)

We're trying to automate everything, which is where CLI tools would be useful.

We don't know of a mechanism to update all modules from the CLI, right now we need an admin to login to via https to then manually click on 'update' for each module that we have bought.

Obviously, anything similar, that allows us to run more things automatically is welcome.

**Comment by freescout-helpdesk** [comment]
`tools/update.sh` is not supposed to update modules, only FreeScout core.

Feel free to send a pull request or updated `tools/update.sh` with "a)" item.

**Comment by eljakim** [comment]
Is there another script for b) available somewhere?

**Comment by eljakim** [comment]
And -- yes, I'll send a pull request for `tools/update.sh` with the a) item.

**Comment by DavidAnderson684** [comment]
Related: add your vote here to indicate your interest in a button in the UI for updating all modules at once: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/399213

**Comment by freescout-helpdesk** [comment]
`freescout:module-update` command has been added in the `master` branch.

**Comment by freescout-helpdesk** [comment]
`tools/update.sh` now also will be automatically updating modules via `freescout:module-update` command.

`--yes` flag has been added to the script.
