### ISSUE TITLE
WorkFlow Email Issue

### ISSUE THREAD

**Issue by arjit65** [freescout-helpdesk/freescout#3385]
As per the WorkFlow Dcoumentation,

I set  up a workflow that gets triggered

when Status is "Closed"
Then
Email to Customer.

I feeded the mail content there. but there was no option to specify subject. Due to this the emails are triggered as reply thread to the end user.

How to change the subject line  of new email ?

![image](https://github.com/freescout-helpdesk/freescout/assets/144830536/3d807ad3-ea3f-4f12-bbb0-151d8c249b7c)

**Comment by freescout-helpdesk** [comment]
It's impossible for now.
