### ISSUE TITLE
User interface: options on the Send / Add Note menus which are option selections should be more clearly presented as such

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#3386]
PHP version: 8.1.23
FreeScout version: 1.8.98

This is the menu that appears if you press the down arrow on the "Add Note" or "Send" buttons in a conversation:

![image](https://github.com/freescout-helpdesk/freescout/assets/1962275/4198441c-317e-4ad3-acb5-518e9d31c865)

The top three items are (in their behaviour) not actions, but mutually exclusive option selections for what will happen if you press the main "Add Note"/"Send" button. That is to say, pressing "Send and stay on page" does not send anything; it merely selects what will happen if you later press the main button again.

i.e. They are radio options, of which one is the pre-selected default. They do in fact behave this way, and the currently-selected option is  indicated by the different background colour.

However, a different background colour for three radio options (separated by a horizontal divider from the rest of the menu, which are not radio options) which are not actions on a menu is not a UI convention that any user is likely to be familiar with. I cannot recall seeing the UI convention of a different background colour on a menu used to indicate radio options anywhere else.

It would be clearer to users if the more common convention of showing an unchecked or checked radio icon next to each of the radio options was used. Unlike the current convention, this would clearly indicate that the three options are linked, and that one, and one only, of the three can be selected.

**Comment by freescout-helpdesk** [comment]
It's fine as it is.

**Comment by freescout-helpdesk** [comment]
Although thanks for the suggestion...
