### ISSUE TITLE
Issue with pasting lists into the editor

### ISSUE THREAD

**Issue by marcatsmci** [freescout-helpdesk/freescout#3387]
FreeScout : 1.8.97
PHP : 8.0.30
Debian 11

Hello !
After copy-pasting an email sent by Thunderbird, the presentation is not correct (image 1).
If you edit the message, the presentation is correct (image 2). But as soon as you leave the editor, the presentation is incorrect again.

View original message - body : 

```
<div>Relancé VSInformatique à l'instant.</div><div>=======================================================<br></div><div><p>Bonjour,</p>
    <p>ce matin à Genève : <br>
    </p>
    <ol><li>tentative de connexion de JBH à 8h07 : <span></span></li><ul><li><span><font face="Courier New, Courier, monospace">2023-09-13
              08:07:43 RESOLVE: Cannot resolve host address:
              pf29.ganesh-hosting.ch:1194 (Hôte inconnu. )</font></span></li></ul><li><span>les logs du FW ne montrent aucune tentative à ce moment</span></li><li><span>les logs du FW montrent la connexion établie lors de la
          tentative suivante à 8h12</span></li></ol>
    <p>Il semble bien qu'il y a un problème de réseau à un moment
      donné...</p>
    <p>À dispo,</p>
    Marc</div><div>=========================================================<br></div>

```

![230913-view-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/55563371-7e23-453e-8529-364a8d45f315)

![230913-edit-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/5d2322c8-caaf-4013-b56c-7224cb5b4926)

![230913-orig-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/905d87fe-e44c-4a72-9fa0-1bf6b510d01f)

**Comment by marcatsmci** [comment]
**Where** : 
![230913-global](https://github.com/freescout-helpdesk/freescout/assets/47881838/86341554-38e5-4b69-826f-1d5d42334a42)

**What** : 
![230913-orig-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/baf42f65-25fa-4582-9ecc-4e01904c017a)
![230913-edit-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/7560d842-155e-4f58-bceb-cd97887f1690)
![230913-view-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/e81c7f4e-6522-4d10-bb6f-4059f9ade47d)

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://summernote.org ?

**Comment by marcatsmci** [comment]
![230913-html-message-summernote](https://github.com/freescout-helpdesk/freescout/assets/47881838/14467b6e-b39d-437a-8612-1aa52d1067fb)
![230913-edit-message-summernote](https://github.com/freescout-helpdesk/freescout/assets/47881838/bfd1169a-510a-484e-a25a-6786244df97c)

**Comment by marcatsmci** [comment]
Which "original message" do you expect ? The email ? The entry in FreeScout ?

**Comment by marcatsmci** [comment]
**Thunderbird email - source** : 

```
Content-Type: multipart/alternative;
 boundary="------------nx0BeKLyHqUnZ3iQ7IJNmySs"
Message-ID: <dcb8e486-7472-4955-ba7a-ebd652bc5fab@f3nix.ch>
Date: Wed, 13 Sep 2023 08:45:07 +0200
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Subject: =?UTF-8?Q?Re=3A_=5BSupport_VSInformatique=5D_Re=3A_Re=3A_=5BSupport?=
 =?UTF-8?Q?_VSInformatique=5D_Re=3A_Probl=C3=A8me_connexion_Open_VPN_depuis_?=
 =?UTF-8?Q?wifi_EAM-INT_=28Ticket_Nr=2E_=23232220=29_=28Ticket_Nr=2E_=232333?=
 =?UTF-8?B?MjIp?=
From: Marc F3 <masc@f3nix.ch>
To: Support VSInformatique <support@vsinformatique.com>
References: <YWEKN4DX3WP@zendesk.com>
 <VI1PR07MB652718ED5131C100D6C127C6FFF2A@VI1PR07MB6527.eurprd07.prod.outlook.com>
 <bf68ae64-7202-4a63-8110-3de38a84c0c5@f3nix.ch>
 <YWEKN4DX3WP_64ff1274ccb3b_3746a0119157_sprut@zendesk.com>
 <221c8aed-e3fe-4ce4-ad51-6dc6378f2f1a@f3nix.ch>
Content-Language: fr
Cc: Pascal Gasser <p.gasser@ganesh-hosting.ch>,
 Hansenne Jean-Baptiste <JB.Hansenne@eliteassetmanagement.ch>
Disposition-Notification-To: Marc F3 <masc@f3nix.ch>
In-Reply-To: <221c8aed-e3fe-4ce4-ad51-6dc6378f2f1a@f3nix.ch>

This is a multi-part message in MIME format.
--------------nx0BeKLyHqUnZ3iQ7IJNmySs
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 8bit

Bonjour,

ce matin à Genève :

 1. tentative de connexion de JBH à 8h07 :
      * 2023-09-13 08:07:43 RESOLVE: Cannot resolve host address:
        pf29.ganesh-hosting.ch:1194 (Hôte inconnu. )
 2. les logs du FW ne montrent aucune tentative à ce moment
 3. les logs du FW montrent la connexion établie lors de la tentative
    suivante à 8h12

Il semble bien qu'il y a un problème de réseau à un moment donné...

À dispo,

Marc

```
![230913-mail-orig-message](https://github.com/freescout-helpdesk/freescout/assets/47881838/c6407387-a1d5-4215-9de0-4c8f047dff89)

**Comment by freescout-helpdesk** [comment]
Can you send a sample email with properly formatted list to support@freescout.net

**Comment by marcatsmci** [comment]
Sent...

**Comment by freescout-helpdesk** [comment]
We still can't reproduce the issue. If someone will be able to reproduce try to fix or provide a link where we can copy the text which allows to reproduce it.
