### ISSUE TITLE
Tag issue in recipient's mail

### ISSUE THREAD

**Issue by soadart** [freescout-helpdesk/freescout#3389]
Hello!I need help with emails. Strange thing found out:
when I sent a mail, recipient gets mail with some kind of tag:
Something like this : **{#CN: AaJzM3k5NssBbr3mzpmp2Hv4RQ6z4ifjrDjow9JSPZEDdSSn#}**
This **tag is seen only on inbox page after the subject and messag**e, when you open message, nothing strange are noticed.
Could someone help me with this issue? What kind of tag it could be, and how I can resolve this?

**Comment by freescout-helpdesk** [comment]
What's your FreeScout version? There was such issue in the past but it was fixed: https://github.com/freescout-helpdesk/freescout/issues/2752

Also FreeScout have another marker: `{#FS...#}`. Are you sure you are seeing emails sent by FreeScout?

**Comment by soadart** [comment]
FreeScout version is 1.8.45
Yes emails was sent by Freescout, yes, it is the same issue like here https://github.com/freescout-helpdesk/freescout/issues/2752
Only update can resolve this?

**Comment by freescout-helpdesk** [comment]
Yes, of course.

**Comment by soadart** [comment]
Good, thank you for help!
