### ISSUE TITLE
Feature suggestion, quoting someone in a note

### ISSUE THREAD

**Issue by yamsellem** [freescout-helpdesk/freescout#339]
It would be great if FreeScout offers the ability to quote someone when creating a note with `@username`, which will notify him/her (and may add an option in `Notify me when another FreeScout user replies or adds a note…`, maybe `with my name quoted in it`)

As a bonus, the ability to trigger the send action with cmd + enter (on mac) or ctrl + enter (on pc) would also be great.

Thanks /a lot/ for your open source solution to shared inbox, this is a great polished solution.

**Comment by foliovision** [comment]
Yam, it's not entirely clear to me what it is you want here which is not covered by the existing simple and to the point interface. I've put in a feature suggestion #342 to allow users to quickly subscribe or unsubscribe other support team members to a ticket. This might cover a lot of your use case as well.

My team is thrilled to be out of a help desk with too many obscure shortcuts and where clicking the return key in the wrong way could send a message before it's ready.

**Comment by fulldecent** [comment]
The followers sidebar is great!

But other products that everyone uses (Slack, Gmail, Google Docs, Office 365, GitHub) will auto-complete `@` to access a list of followers. So people are going to expect that to work too.

**Comment by fulldecent** [comment]
Currently when you mention somebody, it will email to them to notify of the update.

We use this frequently with the notes feature.

Adding a "notify if quotes me" is weird and difficult to implement. Recommend to close issue and use at-mentions as needed.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/mentions/
