### ISSUE TITLE
Spam filter - better filtering

### ISSUE THREAD

**Issue by adrianmxh** [freescout-helpdesk/freescout#3391]
Is there a way to improve the spam filter so it can filter such emails?
![image](https://github.com/freescout-helpdesk/freescout/assets/94862625/1b4f3e9f-accd-4a37-bf88-aac624b9180e)

I added thousands of those random letters and numbers emails to the spam filter but somehow they still get to the inbox, so they never really get filtered.
Their content is just random letters and numbers as seen in the screenshot.

**Comment by freescout-helpdesk** [comment]
Can you give a screenshot of your Smap Filter settings.

**Comment by freescout-helpdesk** [comment]
Try to reset learning memory or use "Filter by Body" option.

**Comment by freescout-helpdesk** [comment]
"Contact message from"

**Comment by freescout-helpdesk** [comment]
Those emails contain just random letters, Spam Filter algorithm can't filter out such things.
