### ISSUE TITLE
API: update customer emails issue

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#3392]
Hello,

For the `PUT api/customers/{customerId}` endpoint:
- Only one email is passed in `emails`
- FreeScout adds the email to the customer emails

How to replace all emails by the `emails` object emails?

**Comment by freescout-helpdesk** [comment]
You can pass several emails. For now this method does not allow to replace or delete emails.

**Comment by ilyakonovalenko** [comment]
> You can pass several emails. For now this method does not allow to replace or delete emails.

So, there is no way to edit customer's email? 😬 Sounds bad. It is better to replace emails with the array passed, not add those emails to the list. It is also not clear enough on the API docs side.

**Comment by freescout-helpdesk** [comment]
Updated in API & Webhooks Module v1.0.69.

The 'emails' parameter now replaces customer emails with the passed list of emails. Added 'emails_new' parameter allowing to add emails to the customer.

**Comment by freescout-helpdesk** [comment]
In API & Webhooks Module v1.0.70 the 'emails_new' parameter has been renamed into 'emails_add'.

**Comment by ilyakonovalenko** [comment]
@freescout-helpdesk Thank you very much!
