### ISSUE TITLE
Github API error

### ISSUE THREAD

**Issue by rabiks** [freescout-helpdesk/freescout#3393]
Client error: `GET https://api.github.com/repos/freescout-helpdesk/freescout/tags` resulted in a `403 rate limit exceeded` response: {"message":"API rate limit exceeded for 1xxxx. (But here's the good news: Authenticated requests get a higher r (truncated...)
Hello, 1.8.98 version, error when check new updates. In previous this same, how can I unblock IP address?

**Comment by freescout-helpdesk** [comment]
Are you on a shared hosting?

**Comment by rabiks** [comment]
yes

**Comment by freescout-helpdesk** [comment]
The only solution is to move to a dedicated IP as apparently someone else on this IP is making requests to https://api.github.com

**Comment by SecureCPU** [comment]
I'm having the same error, and using a private hosting. how do i get unblocked

**Comment by freescout-helpdesk** [comment]
Contact your hosting to find out if some other clients are using the same IP as you and contact GitHub (provide them IP of your dedicated server) to find out and let us know the results.
