### ISSUE TITLE
emalis don't fetching

### ISSUE THREAD

**Issue by invmedia** [freescout-helpdesk/freescout#3394]
Hi! Starting today, around 11:00, I have a problem with downloading e-mails in all mailboxes. I checked the box connection configuration - everything is OK. Cron has been added correctly. I tried to enter the system - tools, download emails - after a while I get the message "Whoops something went wrong". I looked in the logs (file: laravel-2023-09-14.log) and there is information about the time zone error (I have UTM + 2:00 set). logo content:
Call to a member function setTimezone() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setTimezone() on null at /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/app/Console/Commands/FetchEmails.php:665)
[stacktrace]
#0 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/app/Console/Commands/FetchEmails.php(255): App\\Console\\Commands\\FetchEmails->processMessage(Object(Webklex\ \IMAP\\Message), '604125138.01694...', Object(App\\Mailbox), Object(Illuminate\\Database\\Eloquent\\Collection))
#1 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/app/Console/Commands/FetchEmails.php(115): App\\Console\\Commands\\FetchEmails->fetch(Object(App\ \Mailbox))
#2 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#3 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\ Container\\{closure}()
#5 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object (Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object (Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array )
#8 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\ Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\ Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\ \Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\ \Console\\Commands\\FetchEmails), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\ \Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application-> run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run (Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /home/daclawntee/domains/invmedia.com.pl/public_html/emailup/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input \\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"}

Can I ask for help in solving the problem?

**Comment by freescout-helpdesk** [comment]
You've probably enabled "Use date and time from mail headers" option. Change it to "Use actual fetching date and time".

**Comment by freescout-helpdesk** [comment]
Mark un-fetched emails as "Unread" in your mail server.

**Comment by invmedia** [comment]
Marked undownloaded emails as "Unread" and still the same: https://prnt.sc/pxqF00EXNBOu

**Comment by invmedia** [comment]
I tried to download e-mails in "system-tools", I get the error: "Whoops something went wrong"

**Comment by invmedia** [comment]
???

**Comment by freescout-helpdesk** [comment]
Check logs.

**Comment by invmedia** [comment]
przesyłam 2 logi:
[fetch-emails.log](https://github.com/freescout-helpdesk/freescout/files/12609830/fetch-emails.log)
[laravel-2023-09-14.log](https://github.com/freescout-helpdesk/freescout/files/12609831/laravel-2023-09-14.log)

**Comment by invmedia** [comment]
Everything broke after updating the system yesterday after updating to version 1.8.98. Application support does not exist. I don't know why you have this github if you can't solve the problem with your own system. I advise against updating the system to this version.

**Comment by freescout-helpdesk** [comment]
Here is the fixed /app/console/FetchEmails.php: https://raw.githubusercontent.com/freescout-helpdesk/freescout/master/app/Console/Commands/FetchEmails.php
