### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3396]
"Note" action in either manual or automatic workflow cannot be saved, After added custom note in the workflow and save it, you can see it to be disappeared in the note editor, and the note content will not be shown up in the thread after executing the workflow. I have tried many time to identify this bug. it is a bug at least in Manual workflow. Thanks

PHP version: 8.2
FreeScout version: 1.8.98

**Comment by freescout-helpdesk** [comment]
Something is broken in your FreeScout. Check errors in the browser console when entering a note. Try to re-install the FreeScout using manual updating method.

**Comment by jeffrey4680** [comment]
Thanks, it was fixed
