### ISSUE TITLE
New Module show data from... Monday

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#3397]
Hi guys,

Many times it is usefull to show information from users in the Sidebar. 
We build this for Teamleader and Joomla. 
We also use the Woocommerce plugin. 

Now I have a client that has Monday. 
Any idea if you guys have this feature request more often that this is in the Pipeline to build?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to build it.
