### ISSUE TITLE
mail send

### ISSUE THREAD

**Issue by kosmosfr** [freescout-helpdesk/freescout#3398]
1) The mailbox does not pick up letters. Forcibly through the system it takes it normally.
2) A response to a ticket does not send a letter to the recipient.
Test emails are sent

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails

https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues
