### ISSUE TITLE
Queue not working

### ISSUE THREAD

**Issue by evgenmedia** [freescout-helpdesk/freescout#340]
Hello!

When i try to run `artisan queue:work --queue='emails,default' --sleep=5 --tries=1` nothing happens, but worker kills 

All jobs are still in database

I run it on my private server, other projects in neighboring directories are perfect works with `php artisan  queue:work` command

In system section got error: 2 commands were running at the same time. Commands have been restarted

**Comment by evgenmedia** [comment]
Any news?

**Comment by freescout-helpdesk** [comment]
You can find proper command to run in System --> Status.

You need to debug the issue and find the reason by yourself. See https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php

**Comment by evgenmedia** [comment]
Okay, I fixed the problem

The problem was that the queue:work process was not correctly defined by grep command

For example, in the file `app/Http/Controllers/SystemController.php` you need to replace `queue:work` with `emails,default` in commands_list array  at line 79

And in the file `app/Console/Kernel.php,` you need to replace `queue:work` with `emails,default` at line 157
 
This problem occurs on those hosts where `queue:work` processes from other projects are already running.

It's hot fix for my environment, but without changing the logic of the code, it is necessary to add a prefix `freescout` for each queue and search for processes by this prefix

P.S. Thanks for the system, bought a couple of modules
