### ISSUE TITLE
internal message workflow

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3400]
What is the best workflow with internal messages between colleagues / support agents? Until today we simply sent us emails about general topics that didn't belong to customers such as bookkeeping, paying the office rent or informing about sickness.
There already was a [similar question](https://github.com/freescout-helpdesk/freescout/issues/1376), but I do not want an(other) internal chat system.
Should users keep their own mailboxes, but administrated by FreeScout or is it better to have all in one mailbox or at least in team mailboxes?

**Comment by mokkin** [comment]
> It's up to you how to organize it.

I can imagine that, but I'm curious if there is a recommend way or how other users of FreeScout are doing this.

**Comment by nooblag** [comment]
You could use the Notes feature in Freescout to make messages to each other in conversations instead of sending emails?
