### ISSUE TITLE
Bug: Custom Field Type "Multi Line" showing up as Single line Text input in End User Portal

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#3401]
Tested in Firefox and Chrome. See Screenshot.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/28296008/27a7ddb2-2f0d-44b6-9c22-667ace9b054d)

**Comment by freescout-helpdesk** [comment]
Fixed in End-User Portal Module v1.0.63
