### ISSUE TITLE
Consider inserting a variables dropdown into the reply and note editors

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3403]
Hi there, could you please consider inserting a variables' dropdown into the reply and note editors so that we can quickly add customer information to the reply box. In my memory, this feature is inside the previous version, I don't know why I cannot see it anymore, thank you for this amzing ticketing system.

**Comment by freescout-helpdesk** [comment]
Variables dropdown is available in the Signature and Auto Reply editor. Unfortunately there is no plans to add it to the reply editor. Maybe you can do it with a module.

**Comment by jeffrey4680** [comment]
With What module I can do this? I have had an extended editor module already.

**Comment by mokkin** [comment]
You can prepare answers with variable in the saved replies module.

**Comment by freescout-helpdesk** [comment]
> With What module I can do this? I have had an extended editor module already.

There is no such module.
