### ISSUE TITLE
Get Unassigned Tickets from API

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#3404]
I am trying to use the API GET api/conversations Endpoint to retrieve the number of Unassigned tickets for a particular mailbox.  Is this possible?  If so, what should be the Endpoint I call?  I can see how to find tickets assigned to a particular user (Ie. curl -X GET -G "https://demo.freescout.net/api/conversations?mailboxId=123&assignedTo=35), but I am looking for only tickets not assigned to any user.

**Comment by freescout-helpdesk** [comment]
Pass an empty `assignedTo` parameter to https://api-docs.freescout.net/#list-conversations method
