### ISSUE TITLE
Workflows Module strips Space before and After in Conditions

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#3405]
I am using the Workflows Module to add a tag to a Ticket where Subject contains *string*.  I am adding a Space before and after the string, so that only that particular word/string is matched, not matching when found inside any other word.

Freescout strips the spaces on Save so a string of " tba " goes back to "tba" which means a ticket that has "Football" in the subject is meeting the Workflow Criteria.  I only ant the Workflow to fire when that subject has " TBA" or " TBA " in it.

Is there another method to use to include these spaces, or a reason why the spaces should be removed from the Workflow Criteria on save?

My biggest most common issue is when I use Workflows in the Body of the message (Ie. Body > Customer message contains) as the Tags often get added when the keyword is in a random URL or something else inside the message I have forwarded to Freescout inbox.  If it took into account the spaces in my criteria then the tag wouldn't trigger on Random URLs.  The Subject Line example above is the easiest to explain and replicate.

**Comment by freescout-helpdesk** [comment]
It's done to avoid the opposite problem when a space being accidentally added and workflow does not work as expected.

You can use "Matches the regex pattern condition": `/ tba /`
