### ISSUE TITLE
Some messages are not fetched from IMAP mailboxes

### ISSUE THREAD

**Issue by dvdjaco** [freescout-helpdesk/freescout#3406]
PHP version: 8.2.10
FreeScout version: 1.8.95

We have Freescout configured to fetch 3 mailboxes via IMAP, see a screenshot of one of the configurations:
![imatge](https://github.com/freescout-helpdesk/freescout/assets/1502076/f699cd77-dfc8-4b0a-94a0-bcc3a1495e3b)

We have noticed on several occasions that some messages are not fetched by Freescout. So far we haven't been able to find a common factor for these skipped messages, or an explanation as to why they were not fetched.

We don't have errors in the fetch log or the app log that could explain this either, only a few `imap_open()` errors in the fetch log that seem to be due to temporary connectivity issues.

Any pointers on how to debug this will be greatly appreciated. Could it be that a message is not fetched if it was marked as read on the IMAP mailbox by a different client?

Thanks!
^dj

**Comment by freescout-helpdesk** [comment]
> Could it be that a message is not fetched if it was marked as read on the IMAP mailbox by a different client?

Yes. FreeScout fetches only Unread messages.

**Comment by dvdjaco** [comment]
Thanks for the reply! I'll make sure no other clients are connected to these accounts and check again in a few days.

^dj
