### ISSUE TITLE
blank page after upgrade?

### ISSUE THREAD

**Issue by thewho2018** [freescout-helpdesk/freescout#3409]
PHP version: 7.3
FreeScout version: 1.8.99

Hi! I'm trying here to help a friend out and her host is PHP7.3 and had a 1.7.22 if i remember correctly so i first tried from the page to upgrade from settings and that failed and then i tried to FTP and now tried SSH and all i get is a blank white page so i tried to clear cache from the WIKI and nothing seems to help.

I'm really new to all of this but anyone know what could be wrong?

**Comment by thewho2018** [comment]
i now moved all the files away and unpacked a new 1.8.99 and that worked.

**Comment by thewho2018** [comment]
Is there a way to recover all her data?

**Comment by Web7D** [comment]
Did you not take a backup of the site and database before updating?

Have you checked the data in the database to see if it still there?

**Comment by thewho2018** [comment]
did not solve it... had to reinstall.. but now im stuck with lots of weird things so i cannot access settings or send email.. might be file rights..
