### ISSUE TITLE
Workflow Max Executions

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3410]
It may be desirable for some workflows to not have any limit on the number of executions.  For example, the workflow might be triggered when a user posts a note and it cannot be determined in advance how many notes might be in a particular conversation.  Rather than choosing an arbitrarily large number for max executions, it would be better if this can be optionally toggled off entirely.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to implement.
