### ISSUE TITLE
Irrelevant Search Results

### ISSUE THREAD

**Issue by lawfulsoftware** [freescout-helpdesk/freescout#3411]
I tried today to search for Conversation #4507.  I was presented with a list of conversations 27 conversations and I had to scroll to near the bottom of the page to find conversation #4507.

I could not find a reference to 4507 in the other conversations that were displayed in the search result.  The only references to 4507 were contained in the following img tag when I viewed the message body.  4507 was not contained in the email headers.

`<img alt="shutterstock_1840324507" src="https://hs-1875170.f.hubspotemail.net/hub/1875170/hubfs/shutterstock_1840324507.png?width=520&upscale=true&name=shutterstock_1840324507.png" style="outline:none; text-decoration:none; -ms-interpolation-mode:bicubic; max-width:100%; font-size:16px" width="260" align="middle" srcset="https://hs-1875170.f.hubspotemail.net/hub/1875170/hubfs/shutterstock_1840324507.png?upscale=true&width=520&upscale=true&name=shutterstock_1840324507.png 260w, https://hs-1875170.f.hubspotemail.net/hub/1875170/hubfs/shutterstock_1840324507.png?upscale=true&width=1040&upscale=true&name=shutterstock_1840324507.png 520w" sizes="(max-width: 260px) 100vw, 260px">`

Since this image was sent as part of mass emails, emails from this sender appear multiple times throughout our system and in the results of the search for 4507.

Another conversation appeared in the search results because of 4507 contained in the following link:

`<a href="https://click.connect.telus.com/?qs=d2be5358c137ef4507837f073808a04852b59cdb7b9abea21c7bf6a1c06a87277834d033b01bbb04a576367ca366bb2b37227dd720850516" target="_blank" style="color: #ffffff; text-decoration: none;" title="Privacy">`

I suggest the following to improve functionality:

- Exclude text contained **within** HTML tags, but not between them, from the search index.
- Provide a quick search option for the conversation number within the search drop down

![image](https://github.com/freescout-helpdesk/freescout/assets/96336813/67f8a717-b18c-4e17-8691-0a674bec986a)

- Alternatively, provide some or all of the filter options in the drop down so the original search is more useful.  Otherwise, the user has to search and then perform another search to narrow the results.
- Rename "number" in the search filters to "conversation" or "conversation number" to make it more clear.

**Comment by freescout-helpdesk** [comment]
Go to the Search and select "Number" filter.

![2023-09-21_08-19-24](https://github.com/freescout-helpdesk/freescout/assets/40499291/9c6c5b21-ac75-4c7e-9a0a-f9b1bfeccd4f)

**Comment by freescout-helpdesk** [comment]
FYI. You are generating a log of irrelevant ideas/suggestions wasting our time. Try to share only the most important or report only bugs, otherwise your access to the forum may be limited.
