### ISSUE TITLE
Feature Request: force users to enduser portal

### ISSUE THREAD

**Issue by cfoellmann** [freescout-helpdesk/freescout#3414]
For us it would be great to have th option to force users to use the enduser portal.

My idea: 
Would be a simple notifcation like "your ticket has been updated. Click link to open" (with autologin)

That way we see when a user has viewed the answer and we reduce the extreme amount of baggage produced by mail signatures being sent by the user to the system.

PHP version: current-docker
FreeScout version: 1.8.97

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/

**Comment by cfoellmann** [comment]
moved to feature request platform. Sorry.
