### ISSUE TITLE
Installing along/with YunoHost

### ISSUE THREAD

**Issue by harcesz** [freescout-helpdesk/freescout#3416]
Not a bug, more of a general support question. 

I'm attempting to set up Freescout to work with the rest of my work environment (in a NGO), and finding it surprisingly hard. I'm not much of a sysadmin, but currently the only thing that actually worked for me was setting up FS on a separate VPS on docker with no proxy, pretty much anything else fails one way or another. Most likely this could be solved by someone with a better understanding of nginx - maybe I'm just missing something. I seem to get very good at hitting any and every possible problem and undocumented step, so mostly looking to document it and share config examples. 

Ideally there would be a YNH install script, allowing to fully integrate it into that environment.

**Comment by freescout-helpdesk** [comment]
If someone will prepare an YNH installation script - feel free to share.

**Comment by freescout-helpdesk** [comment]
FYI. FreeScout install.sh script is compatible with Debian now: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#interactive-installation-bash-script-ubuntu--debian--etc

**Comment by freescout-helpdesk** [comment]
Also see https://userreport.audienceproject.com/de28276c-2049-4544-b9eb-3849bc5585ed/reports/feedback/374156?mediaId=25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f
