### ISSUE TITLE
DKIM support

### ISSUE THREAD

**Issue by tillmon** [freescout-helpdesk/freescout#3419]
Would be great if freescout supports DKIM.

https://docs.helpscout.com/article/666-use-dkim-to-help-with-email-delivery

https://github.com/simonschaufi/laravel-dkim

**Comment by freescout-helpdesk** [comment]
DKIM is configured on your SMTP mail server.

**Comment by tillmon** [comment]
This is one option, but not possible with all SMTP servers. You can also sign a message with your private key and add your public key to your DNS records.

**Comment by ilyakonovalenko** [comment]
> DKIM is configured on your SMTP mail server.

PHP can also sign emails. But I agree with you it is better to configure on the server side, not FreeScout.
