### ISSUE TITLE
Allow support agents to subscribe themselves or others to tickets

### ISSUE THREAD

**Issue by foliovision** [freescout-helpdesk/freescout#342]
Currently a ticket can only be assigned to one desk agent. That's great and how it should be. It would be nice to add additional subscribers or followers to any given ticket. Those subscribers/followers would get email notifications as if they were the assignee for the ticket (based on their existing user preferences). There's space to add a list of followers on the right hand side.

Use case: for the more interesting tickets we like the whole support crew to be able to contribute. And/or for training.

**Comment by foliovision** [comment]
For smaller support teams it would make sense to just have the list of agents on the right hand side and click each one to turn them on or off. In off mode, the agent's name could be very light grey.

For larger support teams, some kind of dialogue might be necessary. We're a small team and would probably be a small team (per mailbox) even if we become a big team so one click on/off mode without dialogue/dropdown type interface would suit us better.

**Comment by foliovision** [comment]
Here's some screenshots of one existing interface with no-one added yet:

![Freescout-followers-interface-from-Teamwork-Desk](https://user-images.githubusercontent.com/1180948/66767517-eed37100-eeb0-11e9-8bc2-6b12751c9d21.png)

Here's how the same interface looks with followers added:

![Freescout-followers-interface-from-Teamwork-Desk-with-followers](https://user-images.githubusercontent.com/1180948/66767552-fe52ba00-eeb0-11e9-9d87-55aa38216a6d.png)

I'd suggest again that the Helpdesk interface should already include the name of everyone on the helpdesk partially transparent (about 50%). By clicking on someone's name/avatar, that person would then become a follower or removed as a follower. That's a lot faster and more convenient than the Add Followers dialogue.

**Comment by frommMoritz** [comment]
As you mention, this interface doesn't scale well with larger teams. While I understand you mentality, I would ilke to bring another example. I use freescout for out local Fridays for Future Organisation, at the moment we are at arround 20 Users, tendency increasing. I (personally) would create the interface in a way that it scales well.

I'll try to fit it in this week, and create the functionality in the first place. The UI-Design is something we can discuss once it's functional.

**Comment by foliovision** [comment]
Thanks for your comment, Moritz. I'm willing to subsidise an interface which is fast and efficient small teams and not willing to pay for an interface which is convenient for large teams but slow or awkward for small teams (like the original one as described above).

Let me be very clear. Until I hear about something better than all the agents at 50% transparency in the right hand column with single click to make them followers, that's the only interface for which I am willing to provide a bounty.

**Comment by frommMoritz** [comment]
I get your point, you provide an bounty for something that works for you. What I'd like to try: create a interface that works well for small teams, but also scales well. In the end, the goal should be an interface that works well for everyone and it isn't bound to an bounty for me!

My toughts:
 - It should be in the right collumn, agreed
 - Let's have two main Items:
    - Subscribe (like the button in github issues)
    - The dropdown as used in the `Asign to xxxx`
 
If we could gather some Ideas and toughts from some other people, bringing their own experiences and Team-Sizes. I'll try to make it functional and then try some designs and gibve them for a quick vote on here.

**Comment by foliovision** [comment]
Moritz, your use scenario is not a helpdesk:

> I use freescout for out local Fridays for Future Organisation, at the moment we are at arround 20 Users, tendency increasing. I (personally) would create the interface in a way that it scales well.

This is newsletter territory. Horses for courses. Adding a complex followers interface which is not  one click to cover newsletter scenarios is exactly why open-source software fails to be attractive or usable in later iterations. I don't have a helpscout account to be able to tell you exactly how Helpscout addresses this issue.

[Rather poorly it turns out](https://docs.helpscout.com/article/671-following-a-conversation). Helpscout hides a follow action under an elipsis (granted they have a keyboard shortcut for it).

![Helpscout-how-to-follow](https://user-images.githubusercontent.com/1180948/66790418-d171c780-eeef-11e9-826d-72ea0ebc6849.png)

It's the same awkward interface to unfollow. Following tickets (subscribing to tickets) is such core functionality that in my experience the interface should be as simple and straightforward as possible and always visible. I could imagine an option in personal or mailbox preferences to make Follow visible. That way someone who works alone or a huge team who don't use follow (can't imagine working that way but somebody must) don't have to look at a feature they don't use.

Helpscout doesn't envision a scenario where one agent might want to subscribe another agent. Very short-sighted. Here's an opportunity for Freescout to be better than the original.

**Comment by foliovision** [comment]
Moritz, I'm not willing to subsidise a dropdown.

If a dropdown is what you want to build, I don't want it and I'll hire someone to build a custom follow module (which might be the way to go anyway: that way small teams can have something usable and people like you who want to turn Freescout into newsletter software or huge companies will have the opportunity to desecrate Freescout with your own module with dropdowns, checkboxes, elipsis and lots more extra clicks and browser chrome).

**Comment by freescout-helpdesk** [comment]
There should be two parts:

1) "Follow/Unfollow" button in the dropdown allowing user to subscribe/ubsubscribe. Users who subscribe by themselve can not be unsubscribed by others.
![2019-10-15_09-37-20](https://user-images.githubusercontent.com/40499291/66806140-6fd14d80-ef2f-11e9-9ac0-6b70c8886ad1.png)


2) Followers section in the right sidebar below "Previous Conversations". Section should display number of followers in it's header: `Followers (2)`.
![2019-10-15_09-49-48](https://user-images.githubusercontent.com/40499291/66806824-284bc100-ef31-11e9-86e7-9c166bf9236c.png)

Sidebar section displays available users and all subscribed users. Those who subscribed by themselve are also displayed but can not be unsubscribed by others. By default section displays 5 available users. If there are more users than displayed in the section, show "Add" link at the bottom. 
![2019-10-15_09-40-38](https://user-images.githubusercontent.com/40499291/66806332-f2f2a380-ef2f-11e9-85c0-c2ae0f2943ac.png)

"Add" link opens a dialog showing all the users and a search field allowing to filter them.
![2019-10-15_09-27-33](https://user-images.githubusercontent.com/40499291/66805754-78755400-ef2e-11e9-86b3-f0866be0d935.png)

On mobile devices Followers section functions similar to "Previous Conversations":
![2019-10-15_09-43-45](https://user-images.githubusercontent.com/40499291/66806518-67c5dd80-ef30-11e9-8520-8cfbda2f09be.png)

In the Manage --> Settings there should be added a new "Followers" page with the checkbox allowing to show/hide Followers section in the sidebar (visible by default) and input allowing to set number of users displayed in the Followers sidebar block (5 by default). Two options should have `env` type:
```
'settings' => [
	'followers_enabled' => [
		'env' => 'APP_FOLLOWES_ENABLED',
	],
	'followers_count' => [
		'env' => 'APP_FOLLOWES_COUNT',
	],
]
```

So the task is quite complex.

**Comment by foliovision** [comment]
Thanks for your personal attention Freescout to this feature.

Follow/subscribe functionality is so core to our use of a helpdesk that I don't want to see it buried in any kind of a menu or under an ellipsis.

I also have a strong aversion to an extra dialogue with a filter to choose people. The whole point of the visible list is to allow agents to **quickly** add two to five people to a support ticket, not to create an elaborate process with lots of extra clicky-click, searching and multiple dialogues.

**Not allowing agents to unsubscribe agents who subscribed themselves**: have complex thoughts on this one. It would be simpler to just allow agents to do so. The solution here to avoid absurd and cryptic popups - "I'm sorry you can't do that" - would be to show a lock beside names which can't be unsubscribed. My original version of the interface is clicking anywhere on the name adds or removes the subscriber.

**Mobile**: I don't even mind if this doesn't show up on mobile. Mobile space is at a premium and mobile use of Freescout (or any other helpdesk) should be about following a conversation for bosses or quick answers for agents not wasting company time by having agents fiddling with their whole queue of support tickets on a non-keyboard device.

You write:

> In the Manage --> Settings there should be added a new "Followers" page with the checkbox allowing to show/hide Followers section in the sidebar (visible by default) and input allowing to set number of users displayed in the Followers sidebar block (5 by default). Two options should have env type...

In my vision of this feature, all the agents from that mailbox would be shown in the sidebar (there could be an option to switch view to just show the ones actually subscribed by clicking the "Followers" label) so there would be no need for that complex setting.

You point out as you have described the task: "So the task is quite complex." Yes it is.

What I asked for here is a simple and *very* powerful followers feature which would not be difficult to code or maintain. I put a reasonable bounty on it.

Is there a possibility of getting the simple functionality I requested in a module? I don't want and have no desire to support or subsidise a complex and clickety-click model for helpdesks with massive agent lists. Those companies need software with far deeper permissions structures than what Freescout supports. There's lots of overfeatured, unattractive, permissions-based enterprise helpdesk software out there both paid and open source. There's no need to add another one to the stack.

I've spent two years working a helpdesk with the interface you describe for adding and removing followers. I don't want to spend one more day of my life in such a helpdesk. Freescout was like a breath of fresh air with its simplicity, directness of interface and speed. I'd like to help keep it that way.

**Comment by freescout-helpdesk** [comment]
Part 1 should be included in the core of the app. The table with three columns should be created (Conversation ID, Follower ID, ID of the user who added). Sending notifications to followers should be also implemented.

Part 2 should be implemented as a module, which will be provided at https://freescout.net/modules/.  `"input allowing to set a number of available users displayed in the Followers sidebar block"` - this feature will allow to display all support agents in the list to those who need it (@foliovision your case) and those who has hundreds of support agents will be able to show just few of them or show only "Add Follower" link.

@frommMoritz please let us know if you will decide to implement this functionality.

**Comment by frommMoritz** [comment]
Sorry  that I was a bit inactive the last moth. I am looking into it and will do my best to implement it.
I'll take look at the Notifications logic used to send out notifications about new messages and probably extend it a bit. First I'll implement the plain feature it self, how it's to be implemented in the UI is something to solve later, I'll take my fair time to implement the backend functionality...

**Comment by freescout-helpdesk** [comment]
`Follow conversation` feature added to the core: https://github.com/freescout-helpdesk/freescout/commit/7ea54b6f03f75d2c7ccca65969ee093be941c957

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/followers/

**Comment by foliovision** [comment]
The followers feature is very well done and very intuitive. There's no huge click-click overhead. This follower feature is a great addition to HelpScout. We're still testing it, but so far so good.
