### ISSUE TITLE
Snoozed module don't work properly

### ISSUE THREAD

**Issue by mailer21** [freescout-helpdesk/freescout#3420]
Tried to install Snoozed module - works fine, but when I'm trying to list snoozed messages in UI menu I get error message "Whoops, looks like something went wrong — check logs in /storage/logs" and in logs folder:

production.ERROR: SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: ""
CONTEXT:  unnamed portal parameter $3 = '' (SQL: select count(*) as aggregate from "conversations" where "mailbox_id" = 1 and "status" = 3 and "snoozed_until" != ) {"userId":1,"email":"my@mail.net","exception":"[object] (Illuminate\\Database\\QueryException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: \"\"

**Comment by freescout-helpdesk** [comment]
Your database?

**Comment by mailer21** [comment]
> Your database?

postgesql 15.2

**Comment by freescout-helpdesk** [comment]
Any news on this?

**Comment by mailer21** [comment]
> Try to change line 106 in /Modules/Snooze/Providers/SnoozeServiceProvider.php to:
> 
> ```
> ->where('snoozed_until', '!=', null);
> ```
> 
> or
> 
> ```
> ->where('snoozed_until', '<>', null);
> ```
> 
> or
> 
> ```
> ->where('snoozed_until', '>', date('Y-m-d H:i:s', strtotime('-1 year')));
> ```
> 
> And let us know which one would work.

Thank you! Both versions make it work. Where can we create merge request for module?

**Comment by freescout-helpdesk** [comment]
We'll update it.

> Both versions

There are 3 versions. It works with all of them?

**Comment by freescout-helpdesk** [comment]
Fixed in Snooze Module v1.0.13

**Comment by mailer21** [comment]
> Fixed in Snooze Module v1.0.13

Thank you. Now it works!
