### ISSUE TITLE
Issues in Workflow - on sending email on ticket closed

### ISSUE THREAD

**Issue by arjit65** [freescout-helpdesk/freescout#3421]
Dear Team

Can you please help me by sharing that what conditions and actions should i set in workflow module so that the a automatic email is triggered when the conversation is marked as closed.

I am using send and closed module

**Comment by freescout-helpdesk** [comment]
![2023-10-02_10-41-19](https://github.com/freescout-helpdesk/freescout/assets/40499291/26916a1b-9d28-4781-a1ec-a04da95d938b)
