### ISSUE TITLE
Custom Fields in Email Notifications

### ISSUE THREAD

**Issue by nicksilvia** [freescout-helpdesk/freescout#3422]
Hello,

I want to preface this by saying I apologize if this is more pertinent to post in module feature requests. I do not know if this is purposely not a feature or if I am missing a configuration option or something. We use the Custom Fields module to pull in a few different required bits of information when a ticket is submitted from the End User Portal. For example, a user selects a Location dropdown when submitting a ticket. 

Currently, we we get email notifications from FreeScout about tickets, the Custom Field data is not included. So when I get the initial notification that a new ticket has been created, I do not have all the context I need because I need to sign into Freescout to see the custom field data on the Ticket. 

Is there a way to get this custom field data to output on the email notifications? I realize this may be due to data privacy concerns about not wanting to reveal the custom field data back to the customer, but perhaps we could mark a field "confidential" or not to determine if it is outputted on emails.

Thank you,

Nick

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
