### ISSUE TITLE
link customers with each other in CRM module

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3423]
We'd like to link customers to each other in the CRM module.
For example:
* husband - wife
* company - employee
* brother - sister
* [...]

Is this somehow possible or could it be added? This would be very helpful for support agents to get the background of a customers. Sometimes parts of the conversation could be also attached to the other customer part.

Thank you!

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible. Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by mokkin** [comment]
Done: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/420224
