### ISSUE TITLE
Update via web from 1.8.95 to 1.8.100 failed.

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3424]
See attached screenshot of error.

In storage/logs/laravel-2023-09-26.log I see:
[2023-09-26 07:15:18] production.ERROR: Error: include(/var/www/html/vendor/composer/../laravel/framework/src/Illuminate/Queue/Listener.php): Failed to open stream: No such file or directory; File: /var/www/html/vendor/composer/ClassLoader.php (578)

Looking in the directory /var/www/html/vendor/laravel/framework/src/Illuminate/Queue, I see there is no "Listener.php", the closest file being "ListenerOptions.php".  See attached screenshot of directory listing.

I will try again after business hours, using method 2, the update shell script, mentioned at https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout.

I have done other updates successfully. This is the first that has failed.  But it is also the first where I've been behind 5 releases. 

If there is more information I can provide that would be useful to you, please let me know.

Thank you.  I will update this after I run the shell script update.

![firefox_459](https://github.com/freescout-helpdesk/freescout/assets/18216162/9f87771f-c958-4bcc-8bd2-a14b4620c646)
![MobaXterm_462](https://github.com/freescout-helpdesk/freescout/assets/18216162/c9de1ef1-ee45-484d-8602-6bf1924b26ed)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by ilyakonovalenko** [comment]
I actually had the same issue while upgrading from 1.8.99 to 1.8.100. Had to run updater one more time with no issues.

**Comment by mhktc** [comment]
had the same issue, running update.sh from command line worked though..

**Comment by apecity** [comment]
Tried it a second time and it worked.  Odd behavior, but it worked.
