### ISSUE TITLE
S/MIME decrypted Mail not getting displayed

### ISSUE THREAD

**Issue by mhktc** [freescout-helpdesk/freescout#3426]
PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version:  1.8.100

Hello,

we have a s/mime gateway infront of our mailsystem which decrypts incoming encrypted mails and it works just fine.
But freescout doesnt display the contents of the decrypted file  but only the attached smime.p7m file.

When entering the following command "openssl smime -inform DER -verify -noverify -in smime.p7m -out mail.docx" i can get the contents of the mail on plain text.

Why cant freescout display the contents of the mail right?

Regards.

**Comment by freescout-helpdesk** [comment]
FreeScout does not decrypt encrypted emails.

**Comment by mhktc** [comment]
The email is already decrypted by the gateway so freescout doesnt have to decrypt it.

**Comment by mhktc** [comment]
i sent it to support@freescout.net

**Comment by freescout-helpdesk** [comment]
The email does not have a body and contains only attachment containing the decoded email:
```
Content-Type: application/x-pkcs7-mime; name=smime.p7m; smime-type=signed-data
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7m"
```

FreeScout does not process `smime.p7m` attachments as of now.
