### ISSUE TITLE
Script installer.sh not work

### ISSUE THREAD

**Issue by sidreshot** [freescout-helpdesk/freescout#3427]
After completing the installer on Ubuntu 22.04, I was given an error - "File not found."
What should I do in this case?
![image](https://github.com/freescout-helpdesk/freescout/assets/10060394/017c4b9f-e266-4499-a6fd-406372c36b21)

OS: Clean  LXC container with UBUNTU 22.04
PHP version: 
PHP 8.0.30 (cli) (built: Sep  2 2023 08:05:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.30, Copyright (c), by Zend Technologies
FreeScout version: 
[1.8.100](https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.100)
Log error:
FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.16.100.22, server: _, request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "*****-park.com"

**Comment by freescout-helpdesk** [comment]
What was the last message from the installer?

**Comment by sidreshot** [comment]
> What was the last message from the installer?
To complete installation please open in your browser help desk URL and follow instructions.
You can skip setting up a cron task, as it has already been done for you.

URL: http://*********/install

Database Host: localhost
Database Port: 3306
Database Name: freescout
Database Username: freescout
Database Password: ******

**Comment by freescout-helpdesk** [comment]
Apparently something went wrong during installation. It's hard to tell what. Most likely some files have not been downloaded.

**Comment by sidreshot** [comment]
> Apparently something went wrong during installation. It's hard to tell what. Most likely some files have not been downloaded.

If you just clone the git as the script does, some files are missing.
I downloaded a zip file (not a whale) and put it manually - it works. 

The truth is only on Apache. On nginx, the configs that are in the documentation do not work. I had to spend a couple of hours on it all. Sadly.

**Comment by SuneebGitHub** [comment]
its working before when i was install the crm module and active this module the drops are missing i have click the drop down but it is not showing the dropdwon menus pleas help bro
