### ISSUE TITLE
Improve uploads folder security

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#3428]
In order to improve `uploads` folder security:

- If you are using **Apache** web server - there is no need to do anything, update will arrive with the 1.8.101 release.

- If you are using **nginx** web server, add the following instruction to your nginx config (see [nginx configuration](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#61-nginx) in the Installation Guide):
```
    location ~* ^/storage/.*\.((?!(jpg|jpeg|jfif|pjpeg|pjp|apng|bmp|gif|ico|cur|png|tif|tiff|webp|pdf|txt|diff|patch|json|mp3|wav|ogg|wma)).)*$ {
        add_header Content-disposition "attachment; filename=$1";
        default_type application/octet-stream;
    }	
```

**Comment by freescout-helpdesk** [comment]
FYI @tiredofit @nebulade

**Comment by freescout-helpdesk** [comment]
Also everyone please notice that `filename=$1` changed to `filename=$2` in the nginx config above.

@tiredofit @nebulade

**Comment by nebulade** [comment]
Thanks for letting us know, we use apache in the package, so we added the headers module now.

**Comment by Lars-** [comment]
Nice, all attachments return a 404 now...
