### ISSUE TITLE
Add customize feature to conversation

### ISSUE THREAD

**Issue by hungdq123** [freescout-helpdesk/freescout#3429]
Hi, 
I want to add some field /column to conversation table or existed table and process it to show on conversation.
I have tried but the code gone after upgrade freescout
Do you have any guide or advised to make it?
Thank you so much!

**Comment by pm112** [comment]
Of course for a few Bucks you can get one of the official Plugins 

https://freescout.net/module/custom-fields/

That would exactly do what you want :)
