### ISSUE TITLE
One Ticket 2 Customers

### ISSUE THREAD

**Issue by pm112** [freescout-helpdesk/freescout#3430]
Hello, 

i would like to ask if there is any possibility to add 2 Customers to one Ticket.

i have a Project that affect 2 of my customers but one of them dont see the Ticket in the Helpdesk after Login. I think because the Ticket self is assigned to the other Customer.

Any Advice?

Thank you very Much

**Comment by ilyakonovalenko** [comment]
No. It is impossible. You can only communicate both of them by adding email to CC.
