### ISSUE TITLE
Error occurred while activating End-User Portal: "Error occurred creating a module symlink"

### ISSUE THREAD

**Issue by abicocchi** [freescout-helpdesk/freescout#3434]
Error occurred creating a module symlink (C:\inetpub\Abstraqt\Ticketing\freeScout\public/modules/enduserportal). Please check folder permissions.
Cache cleared successfully.
Nothing to migrate.
Error occurred creating [C:\inetpub\Abstraqt\Ticketing\freeScout\public\modules\enduserportal » C:\inetpub\Abstraqt\Ticketing\freeScout\Modules\EndUserPortal/Public] symlink: symlink(): Cannot create symlink, error code(1314)
The [C:\inetpub\Abstraqt\Ticketing\freeScout\public\modules\enduserportal] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage\app/public/js/vars.js

PHP version: 7.3.25
FreeScout version: 1.8.100
installed on Windows (IIS)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
