### ISSUE TITLE
Include "Exclude Satisfaction Ratings" Option in "Email the Customer" Workflow Action

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#3436]
Problem:

Currently, I have a workflow set up in the FreeScout Helpdesk that sends an email to the customer when they rate the reply as good. This email prompts the customer for a review. However, there's a usability issue with this workflow. The email sent by the workflow also includes the satisfaction rating, which can lead to confusion and is not a good user experience.

Request:

I would like to propose the addition of an "Exclude Satisfaction Ratings" option within the "Email the Customer" workflow action in FreeScout. This option should allow users to send an email to the customer without including the satisfaction rating in the email content.

Expected Behavior:

When creating or editing a workflow, users should have the option to include or exclude satisfaction ratings when using the "Email the Customer" action.

If the "Exclude Satisfaction Ratings" option is selected, the email sent to the customer should not include the satisfaction rating.

Benefits:

This enhancement would greatly improve the user experience for customers by preventing confusion caused by the inclusion of satisfaction ratings in emails requesting reviews. It will also provide more flexibility and customization options for workflow creators.

Thank you for considering this enhancement request.

**Comment by freescout-helpdesk** [comment]
In Satisfaction Ratings Module v1.0.20 now it's possible to disable ratings for a particular reply by adding `{%ratings.off%}` shortcode to the reply.

**Comment by rosinghal** [comment]
Awesome. That works.
