### ISSUE TITLE
How to delete and close DRAFT conversations

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#3437]
Hi, I use Freescout for a while, about 1 year and with all the updates and I experience that evry some days I get some DRAFT conversations. No body take care of them, so I want to build a BOT that every 1 hour or so, will delete all this DRAFT conversations.

So my questions is what will be the right query to do this? it will be correct to do that?

My guess is something like:

UPDATE conversations
SET state = 3, status = 3
WHERE state = 1;

Any help will be apreciated!

**Comment by freescout-helpdesk** [comment]
Better to create a script or a module discarding drafts: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/ConversationsController.php#L1523
