### ISSUE TITLE
CRM modules - Tags single line search failed

### ISSUE THREAD

**Issue by kimsonvu** [freescout-helpdesk/freescout#3438]
Hi,

I am running live FreeScout on Docker. I also purchase 2 modules from Home page. One is tags and second is CRM (Customer Field).

I found that tags single line on CRM does not work. I already try to clear cache, open PHPADMIN to check database. Everything is right and database had data too.

Where do i miss? Or this is a bug?

Thank you!

**Comment by freescout-helpdesk** [comment]
> I found that tags single line on CRM does not work

What does it mean? Attach a screenshot.

**Comment by kimsonvu** [comment]
Hi,

I have more than 1 customer with tags like this:

![msedge_rOiLadoELm](https://github.com/freescout-helpdesk/freescout/assets/10061253/74915221-2e81-4938-bc96-7b154547c634)

But search does not show them. I don't know what wrong here.

**Comment by freescout-helpdesk** [comment]
Are you searching as admin or as a regular user?

**Comment by freescout-helpdesk** [comment]
Also attach screenshot of your customer field configuration.

**Comment by freescout-helpdesk** [comment]
Fixed in CRM Module v1.0.38.

**Comment by kimsonvu** [comment]
@freescout-helpdesk : Do you know when will update docker image? I want to test it again with new docker image.

**Comment by freescout-helpdesk** [comment]
You can update FreeScout in Manage > System and the module in Mange > Modules.

**Comment by kimsonvu** [comment]
@freescout-helpdesk It require to update Freescout to new version to: Module requires app version: 1.8.101. I am using 1.8.100 from this docker: ghcr.io/tiredofit/docker-freescout:latest

**Comment by freescout-helpdesk** [comment]
> You can update FreeScout in Manage > System

**Comment by kimsonvu** [comment]
@freescout-helpdesk : . I check update from Manage > System but no update.

![msedge_1G51yhrnHW](https://github.com/freescout-helpdesk/freescout/assets/10061253/f19518da-22df-461e-97ce-2972de694fd1)

It is something strange that i run script to update <bash> update.sh successful but it still running 1.8.100

![msedge_dGiIbdMt1U](https://github.com/freescout-helpdesk/freescout/assets/10061253/39a4bbec-ea40-4fbd-802d-1ab0167711ab)

**Comment by kimsonvu** [comment]
@freescout-helpdesk I success to update and it work now. Thanks!
