### ISSUE TITLE
JS error with scheduled sending module

### ISSUE THREAD

**Issue by calebscoolcodes** [freescout-helpdesk/freescout#3439]
Hey FreeScout team!

When I try to schedule a new ticket, I'm getting some errors in the JavaScript console:

![image](https://github.com/freescout-helpdesk/freescout/assets/91237841/652bb10a-3eae-4820-97b0-1c454dc11f08)

Copied from console:

```
Uncaught TypeError: $(...).flatpickr is not a function
    at HTMLDocument.<anonymous> (9980d18011fc7ee4b46f452e75a574b733911226746.js:508:579)
    at l (9980d18011fc7ee4b46f452e75a574b733911226746.js:1:29459)
    at c (9980d18011fc7ee4b46f452e75a574b733911226746.js:1:29761)
```

Scheduling a reply to an already existing ticket seems to work fine, so it seems to be only related to the new ticket view / screen. 

PHP version: 8.2
FreeScout version: 1.8.100

Let me know if any other information is needed! Thanks in advanced 😁

**Comment by freescout-helpdesk** [comment]
Fixed in Send Later Module v1.0.13
