### ISSUE TITLE
Workflows sometimes non-working Body conditions

### ISSUE THREAD

**Issue by skippey1** [freescout-helpdesk/freescout#3440]
Hi.
Workflows Version: 1.0.55

We're using Google sheets and Apps script to create recurring tickets. We want to use a #keyword# text to trigger more processing with workflow for the recurring tickets. 

![image](https://github.com/freescout-helpdesk/freescout/assets/144424425/30ab61b0-392e-42bb-bc0b-5089bf3f5117)

It seems that the workflow only triggers when running it with Apply to Previous enabled. 

I found this issue with similar problem but with Subject. #3200 
https://github.com/freescout-helpdesk/freescout/issues/3200

If we change the keyword into the Subject field, the workflow runs just fine with Subject condition.
Maybe this could be a more wide spread issue?

**Comment by freescout-helpdesk** [comment]
We have not heard of such issue from others yet. In the past there were issues with the Subject condition, but not with the body.
How are you receiving tickets?

**Comment by skippey1** [comment]
Hi.
We get them from IMAP folder from Gmail.

**Comment by freescout-helpdesk** [comment]
It's hard to tell what can cause the issue as we can't reproduce it on our FreeScout instance.
Are you using the latest version of FreeScout?

**Comment by skippey1** [comment]
we have 1.8.97

**Comment by freescout-helpdesk** [comment]
Update to the latest version.

> Fixed the issue due to which long fetching may be killed before it finishes (https://github.com/freescout-helpdesk/freescout/issues/3417)
https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.100
