### ISSUE TITLE
Snooze Time wrong

### ISSUE THREAD

**Issue by gplast1981** [freescout-helpdesk/freescout#3441]
Hello I have a problem with the Snooze module, if I go to 5 min later then the time shows me exactly one hour less, although I have already set time zone +3, no matter what time zone you set the time remains one hour less and thus the module does not work accurately. What is the reason 

![Screenshot 2023-10-05 124317](https://github.com/freescout-helpdesk/freescout/assets/138209591/47056cfc-7048-4cff-a90d-1c13e2464dee)

System Info
Zeitzone | Europe/Berlin (GMT+0200)

Mysql (8.0.34-0ubuntu0.22.04.1)
nginx/1.18.0 PHP 8.1.2-1
ubuntu2.14
Freescout 1.8.101
Snooze 1.0.14

php.ini
date.timezone = "Europe/Berlin" 

.env
APP_TIMEZONE=Europe/Berlin

nginx.conf
location ~ \.php$ {
    fastcgi_param   TZ "Europe/Berlin";
}

if i set the time on the server one hour ahead, which would be wrong, then the time on freescout will also change, the time zone setting on freescout has no influence, no matter what you set.

Have checked all settings I can not find the error

**Comment by freescout-helpdesk** [comment]
Keep in mind that the timezone is set in two places: in "Manage » Settings" and each user's profile.
