### ISSUE TITLE
Attachments not being shown correctly

### ISSUE THREAD

**Issue by tmertz** [freescout-helpdesk/freescout#3442]
FIrst of all, thanks to the Freescout team for an amazing tool. I use it across multiple projects and organisations, and by and large it really does work really well. 

Unfortunately, we've run into an issue where attachments are correctly stored in `storage/app/attachment/` but clicking the attachment link in a message will take you to the dashboard of the app. Clicking the download button will force the browser to download a html file with the filename of the attachement, but the html content of the dashboard of Freescout. 
I have noticed this behaviour across both the installs I am presently running.

I've checked that the symlinks check out and that nginx has the, per the install instructions, correct vhost config. 
I am kinda fumbling in the dark here, so any help or suggestions would be greatly appreciated. 

PHP version: 8.2
FreeScout version: 1.8.101

**Comment by freescout-helpdesk** [comment]
Are you using Docker or Cloudron? Are you using apache or nginx?

**Comment by freescout-helpdesk** [comment]
Are you using CloudFlare? https://github.com/freescout-helpdesk/freescout/issues/3431#issuecomment-1749636284

**Comment by freescout-helpdesk** [comment]
Also please share your nginx config.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/issues/3449#issuecomment-1754949661
