### ISSUE TITLE
FreeScout v1.8.102 release enables Content Security Policy (CSP)

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#3443]
FreeScout v1.8.102 release enables Content Security Policy (CSP) via meta tag in order to strengthen helpdesk security event more.

Right after updating your FreeScout to v1.8.102 make sure to update all modules to their latest versions.

If some links or buttons do not work for you anymore please create an issue on GitHub.

If you are maintaining some custom modules, read [this instruction](https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#javascript-and-content-security-policy-csp) on how to make them CSP compatible.

**Comment by bfren** [comment]
After this update I am unable to install modules, e.g.

```
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("script-src").
Source: javascript:installModule('ticketnumber')…
```

My understanding is that it's up to module authors to update as necessary, rather than end users?
