### ISSUE TITLE
Too Many Redirects error when click on any email received.

### ISSUE THREAD

**Issue by gabrieltackitt** [freescout-helpdesk/freescout#3446]
working on a new install to try out freescout before I commit. So far I've really liked it, but I am running into one issue that makes it basically impossible to use. Any time I click on a received email in any folder I get a too many redirects error. 

The only errors in my log are this, which I expect that I have already resolved with rerunning the chown command on /var/www/html

```
 file_put_contents(/var/www/html/storage/framework/cache/data/ee/2f/ee2f842aa7bb1f53edf3a2ed2c09a1807ffa6c90): failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/storage/framework/cache/data/ee/2f/ee2f842aa7bb1f53edf3a2ed2c09a1807ffa6c90): failed to open stream: Permission denied at /var/www/html/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
```

PHP version: 7.4.33
FreeScout version: 1.8.103

**Comment by freescout-helpdesk** [comment]
Is everything OK in Manage > System?

**Comment by gabrieltackitt** [comment]
Yes, everything is listed as "ok"

**Comment by freescout-helpdesk** [comment]
Something must be messed up in the DB - conversations and folders tables.
