### ISSUE TITLE
Star

### ISSUE THREAD

**Issue by jamaltiftafeh** [freescout-helpdesk/freescout#3447]
As previously mentioned, the Star function can only be seen by the indiviual user.  I would prefer this funtion be seen across all users I the group.  This can then be used to notified user the ticket is high proirity.  Aslo when a ticket is Starred and then closed, the ticket remains in the starred section, can once a ticket is closed the star will automatically be removed and only show in the Closed section.

**Comment by freescout-helpdesk** [comment]
We see that you've posted a feature request at https://freescout.net/request-feature/
