### ISSUE TITLE
Apache headers module

### ISSUE THREAD

**Issue by jespernissen** [freescout-helpdesk/freescout#3450]
After i updated our FreeScout instance, we couldn't download attachments.
After reading the logs i found out i didn't have the Apache headers module enabled.
I guess it has something to do with CSP.

Maybe adding a check for the headers module under "System status" would be a good idea?

Feel free to mark this issue as closed if the idea is dumb :-))

**Comment by freescout-helpdesk** [comment]
Here is the fixed .htaccess file: https://raw.githubusercontent.com/freescout-helpdesk/freescout/master/storage/app/public/.htaccess

Download it to `/storage/app/public/.htaccess`
