### ISSUE TITLE
Customer gets changed when replying from another email

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#3454]
Hello,

Steps:
1) Conversation is created for email@A.com
2) Customer replies from email@B.com because of email@A.com sends copies to email@B.com
3) FreeScout changes the conversation customer to email@B.com and sets email@A.com in CC.

Can we have this changed to add email@B.com to CC (or even disable this by .env setting) instead of changing the conversation original customer.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to change this.

**Comment by ilyakonovalenko** [comment]
Can you please share your point of view. What is the purpose of changing original conversation customer to another customer on every reply. It is also a security issue because conversation gets assigned to another entity and can be viewed via customer portal module.

**Comment by freescout-helpdesk** [comment]
This is how other helpdesks work.

**Comment by ilyakonovalenko** [comment]
Hm. Never seen such things before. It is ok to add other parties on CC list and this is what other helpdesks do, but not changing the main customer assignment which was originally set. I would highly appreciate if you implement both ways to make it suitable for everyone.
