### ISSUE TITLE
Agent reply via e-mail to a ticket moved to another mailbox causes null deref

### ISSUE THREAD

**Issue by sschaap** [freescout-helpdesk/freescout#3455]
PHP version: 7.4.33
FreeScout version: 1.8.100

**Problem outline**

1. Customer sends e-mail and FreeScout creates ticket 123 in mailbox ALPHA.
2. FreeScout sends out notification e-mails to agents for ticket 123 creation.
3. Ticket 123 is moved to FreeScout mailbox BETA.
4. Agent replies to ticket 123 creation notification using e-mail.
5. FreeScout fails to process the agent's reply e-mail (mailbox mismatch?).

**Problem description**

We noticed an issue today where one of our agents (i.e. FreeScout user) replied to a ticket notification e-mail using their mail client, but the reply never appeared in FreeScout. I verified that the message was successfully received by the mailbox that FreeScout fetches messages from. Notably, the message was marked "read" while this mailbox is used only by FreeScout.

The log files did not show anything worthwhile, so I ran `php artisan freescout:fetch-emails -vv --unseen=0` and got the following output:

```
[2023-10-12 20:07:56] Fetching ALL emails for the last 3 days.
[2023-10-12 20:07:56] Mailbox: Other
[2023-10-12 20:07:56] Folder: INBOX
[2023-10-12 20:07:59] Fetched: 10
<snip>
[2023-10-12 20:08:00] 10) Re: [#2548] <redacted>
[2023-10-12 20:08:00] Message from: User
[2023-10-12 20:08:00] Error: Trying to get property 'conversation' of non-object; File: /var/www/html/app/Console/Commands/FetchEmails.php (1037)
```

At [`FetchEmails.php:1037`](https://github.com/freescout-helpdesk/freescout/blob/fbf2f1f0637867db88c534e5976bd3e28a5b947f/app/Console/Commands/FetchEmails.php#L1037) in `saveUserThread()` it looks like `$prev_thread` is `null`. This value is provided by the caller at [`FetchEmails.php:752`](https://github.com/freescout-helpdesk/freescout/blob/fbf2f1f0637867db88c534e5976bd3e28a5b947f/app/Console/Commands/FetchEmails.php#L752) in `processMessage()` where `$prev_thread` must also be `null`. While I am not certain about the exact cause, the following snippet stands out to me, as the ticket had been moved to another mailbox after receipt.

```php
// Make sure that prev_thread belongs to the current mailbox.
// It may happen when forwarding conversation for example.
if ($prev_thread) {
    if ($prev_thread->conversation->mailbox_id != $mailbox->id) {
        // https://github.com/freescout-helpdesk/freescout/issues/2807
        // Try to get thread by generated message ID.
        if ($in_reply_to) {
            $prev_thread = Thread::where('message_id', \MailHelper::generateMessageId($in_reply_to, $mailbox->id.$in_reply_to))->first();

            if (!$prev_thread) {
                $prev_thread = null;
                $is_reply = false;
            }
        } else {
            $prev_thread = null;
            $is_reply = false;
        }
    }
}
```

Sure enough, when I moved the ticket back to its original FreeScout mailbox and re-ran `php artisan freescout:fetch-emails -vv --unseen=0`, the reply e-mail was picked up correctly and the output contained no errors.

I'm not sure why the above mailbox mismatch check exists, but (if my guess is correct) it seems to break agent e-mail replies when a ticket is moved to another mailbox.

**Random thoughts**

The agent reply e-mail contains an `In-Reply-To` header that correctly references the `Message-ID` of the notification e-mail.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by sschaap** [comment]
Awesome.
