### ISSUE TITLE
'Notification Emails to Users' showing email content

### ISSUE THREAD

**Issue by nooblag** [freescout-helpdesk/freescout#3456]
Firstly, thanks for great software and great support.

I'm facing an issue that is either unexpected given the User Interface options, or I am understanding incorrectly. I have the `Conversation History` setting for both `Emails to Customers` and `Notification Emails to Users` set to "Do not include previous messages."

![Screenshot 2023-10-13 at 14-28-13 Settings - General](https://github.com/freescout-helpdesk/freescout/assets/1122344/125ed77d-0b6c-45b2-8ecd-4413c261eca1)

But, for the User Notifications for example, I get the email body content per notification, like so (but redacted for privacy):

![Screenshot from 2023-10-13 14-29-53](https://github.com/freescout-helpdesk/freescout/assets/1122344/3b3131aa-073b-4f04-8cb5-25f3299a1d52)

My expectation given the menu options is that "do not include previous messages" would mean there would be no body included in the notifications (i.e. the notification does not contain any message content, just the fact that there's new info inside Freescout to be looked at).

My use case is that I do not want the contents of our organisational emails going into the email addresses of the Freescout users.

Is there a way to turn this off? Or if not, I'll write up a feature request?

Thanks!

**Comment by ilyakonovalenko** [comment]
> My expectation given the menu options is that "do not include previous messages" would mean there would be no body included in the notifications (i.e. the notification does not contain any message content, just the fact that there's new info inside Freescout to be looked at).

Your expectation is incorrect. That option means FreeScout will not include **previous** emails in the notification. It is clear from the option titie.

**Comment by nooblag** [comment]
Hi there, thanks for getting back. Okay, I'll lodge a feature request? In the meantime, is there a way I can turn this off so the User Notification emails do not contain any message content?

**Comment by freescout-helpdesk** [comment]
Here: https://freescout.net/request-feature/

>  In the meantime, is there a way I can turn this off so the User Notification emails do not contain any message content?

Unfortunately it's not possible.

**Comment by nooblag** [comment]
Thanks for getting back. Okay, have lodged a feature request. In the meantime, can you point me to the repo files responsible for displaying the email body content in User Notifications? Perhaps we can look at taking this on and maybe even PR if we have capacity.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/emails/user/notification.blade.php

But most likely this "feature" will not be included in the app - https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#new-features

**Comment by nooblag** [comment]
All of that is very helpful, thank you. Sorry, I didn't know that was your developer process. Thank you for the guide.

Okay, since we have an issue open, would you want to discuss a little if it's something we can either assist with or collaborate on?

The approach that comes to mind, for example, is to add `Do not include *any* messages` to the drop down pictured below, and then adjust the code accordingly to introduce that behaviour.

![Screenshot from 2023-10-20 17-02-54](https://github.com/freescout-helpdesk/freescout/assets/1122344/37719efd-fb5b-4d89-b0fd-b7077484cab0)

So the notifications just end up looking something like this, for example:

![eg](https://github.com/freescout-helpdesk/freescout/assets/1122344/42749636-532b-49d3-8018-7960481c94a5)

**Comment by ilyakonovalenko** [comment]
Do you really need email notifications in your organization? You may use custom module and send notifications to some other app (Slack, MatterMost, Telegram, etc) with specific content, also maybe create some dashboard with API. You may disable email notifications at all.

**Comment by nooblag** [comment]
Thanks for your note. Well, I think we are in the middle. No notifications at all is too little, and notifications at the moment with email body content is too much.

We do use Zulip, but nobody there needs any notifications. The structure in the organisation is that specific users handle the email, and so it's desirable that those specific users get notifications of the type that Freescout is providing already, just without the message bodies for data privacy.

**Comment by ilyakonovalenko** [comment]
Not best solution, but you can probably edit email templates files to suite yiur needs and then disable an ability to change them by `chattr +i` command.

**Comment by nooblag** [comment]
Thanks for that. I'll give that a try. :+1:

**Comment by nooblag** [comment]
Hi there, just returning to this as I just updated to 1.8.106.

Have made changes to the notification files as we want, and everything is working great.

Freescout appears to overwrite the files on update though, even with `chattr +i` set (before updating):

```
$ lsattr /var/www/freescout/resources/views/emails/user/notification*
----i---------e------- /var/www/freescout/resources/views/emails/user/notification.blade.php
----i---------e------- /var/www/freescout/resources/views/emails/user/notification_text.blade.php
```

and now we have those two files in the temporary storage which aren't cleaned up because of the `+i` flag:

```
/var/www/freescout/storage/app/updater/1.8.106/resources_tmp/views/emails/user/notification.blade.php
/var/www/freescout/storage/app/updater/1.8.106/resources_tmp/views/emails/user/notification_text.blade.php
```

Just wondering what other ideas might be out there to approach this issue.

Thanks!
