### ISSUE TITLE
Workflow not running after ticket is closed

### ISSUE THREAD

**Issue by PepeGonzalesNFC** [freescout-helpdesk/freescout#3457]
PHP version: 8.2.10
FreeScout version: 1.8.100

I have created a workflow so that after 24 hours of closing a ticket, if no replies from a user or a customer have been received, then the system should send an email informing the customer that their ticket has been closed. However, I can see that the workflow is not being triggered. I am wondering if I have a logical issue here, or if is something else.

Please ignore the "Applied to" field, since I have changed the workflow a few times and that is why it has ran previously.

![image](https://github.com/freescout-helpdesk/freescout/assets/107308290/91d812fd-7c75-43ab-8009-114c5b0d3900)

![image](https://github.com/freescout-helpdesk/freescout/assets/107308290/066f96f8-681b-47ba-a4ab-ccea68a796a8)

![image](https://github.com/freescout-helpdesk/freescout/assets/107308290/88cf8142-8d30-48ef-b5c4-176bdf3a48e7)

Any input is appreciated. Thanks!

**Comment by freescout-helpdesk** [comment]
Try to change 24 hours to 1 hour and check.
