### ISSUE TITLE
set sender name for workflow emails in freescout

### ISSUE THREAD

**Issue by kwm365** [freescout-helpdesk/freescout#3458]
It would be nice to have the ability to set a free sender name when workflows send emails to a specific address (e.g. customer email). Since the emails sent are related to the workflow of a specific mailbox, I don't understand why the system doesn't at least use the sender name of that mailbox as default.

regards
Martin

**Comment by freescout-helpdesk** [comment]
> By default Workflow user’s name is “Workflow”. If you want to change it, add the following parameter to the .env file and [clear the cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache):
 WORKFLOWS_USER_FULL_NAME=”Robot”

https://freescout.net/module/workflows/

**Comment by kwm365** [comment]
that has not worked yet. I set the value in the docker .env file, rebuilt and cleared the cache. Still "Workflow" as the sender name.

Does the value for WORKFLOWS_USER_FULL_NAME need to be set in quotes?

**Comment by freescout-helpdesk** [comment]
Yes:
```
WORKFLOWS_USER_FULL_NAME=”Robot”
```

Try to kill background jobs manually: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
