### ISSUE TITLE
Loading very slow

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3459]
Hi Freescout team,

I have freescout installed and its being used by 10+ peoples, they are reporting it loads very slow sometimes, though it not happens everytime but sometime it loads very slow. Nothing gets loaded and they see only blank white screen.

What could be possible reason for same and what needs to be optimized to make it load faster for everyone.

Thanks!

**Comment by freescout-helpdesk** [comment]
Are you on a shared hosting?
Are you using Reports Module?

**Comment by mahavirn** [comment]
I am not on shared hosting, have setup my own VPS.

Yes, i am using Reports module.

<img width="749" alt="Screenshot 2023-10-16 at 11 25 36 AM" src="https://github.com/freescout-helpdesk/freescout/assets/118246547/7a0ae59e-37ea-4634-907e-830bebbb4754">

**Comment by freescout-helpdesk** [comment]
Try to disable Reports Module and see how it goes.

**Comment by mahavirn** [comment]
Okay, Sure

Let me disable that module, Will keep you updated, Thanks!

**Comment by freescout-helpdesk** [comment]
Any news?

**Comment by mahavirn** [comment]
Hello @freescout-helpdesk,

Since the Reporting module is crucial for us, we have decided not to disable it. Instead, we will monitor the situation and disable the module on-the-fly when FreeScout starts loading slowly.

We will provide an update and share the results once this situation occurs.

Thank you for your support :)

**Comment by freescout-helpdesk** [comment]
Find someone who can investigate it on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)
