### ISSUE TITLE
Move freescout to a new server with new URL

### ISSUE THREAD

**Issue by JSM25** [freescout-helpdesk/freescout#3462]
We have been having an issue which locks up our server and hope someone may be able to help us. I have checked the log and this is the message that we are getting

99302 ?        S      0:01 /usr/local/php81/bin/php artisan freescout:extendedattachments-cleanup
99322 ?        S      0:00 sh -c '/usr/local/php81/bin/php' 'artisan' freescout:extendedattachments-cleanup > '/dev/null' 2>&1

But we get hundreds of them which then take down the server with a 502 error.

We have had freescout running for months now without any issues until about to days ago so I think something must have changed.  Any advice would be very much appreciated. 

John

**Comment by freescout-helpdesk** [comment]
Try to run console command and send us the output:
```
php artisan freescout:extendedattachments-cleanup
``

**Comment by JSM25** [comment]
Thank you for your advice I think the issue is that Siteground is just not compatible with freescout so I am going to move it to A2 hosting.  Do you have any instructions on how to migrate the server?  

I know how to move the database and have already tested this and its works.

Can I just copy all the files over to the new server to complete the move?
I also have a lot of your modules which I will need to move as I will be on a new domain.

Any other helpful advice would be greatly received 



John

**Comment by JSM25** [comment]
I have moved the database to a new A2 hosting and have that working ok. I have also copyied all the files accross as well.

I have made the changes in the .env file including changeing the URL. When I run 
php artisan freescount:clear-cache i just get an error

 file_put_contents(/home/customer/www/<xxx>.com/public_html/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): Failed to open stream: No such file or directory

This is still pointing to the old site, how can I make the changes please.

**Comment by avenjamin** [comment]
That file path looks like it's missing your site's domain - it's just `.com` after `/home/customer/www/` unless you removed it for privacy reasons? :)

Or are you saying the path at A2 is different to SiteGround

**Comment by JSM25** [comment]
My old file path was:

php /home/customer/www/helpdesk.<domainname>.com/public_html/artisan schedule:run >> /dev/null 2>&1

The new one is:

/opt/alt/php81/usr/bin/php /home/<private>/public_html/helpdesk/artisan schedule:run >> /dev/null 2>&1

I have managed to get a clean install of freescount working on the new server the issue is when I copy the file over from the old.

Yes the donal I am useing has changed

Any assistance much appreciated

**Comment by JSM25** [comment]
We have now installed freescout on a shared hosting on A2 Hosting which has been very successful. We have had the system running for about a week now and it's looking to be very stable and faster than on the old SiteGround which we had before.  The only issue we have found is that you or restricted to 15 min intervals for a CRON job.    

Hope this helps anyone who is looking for a host provided

**Comment by freescout-helpdesk** [comment]
Thanks for the info.

**Comment by bekre10** [comment]
Rather than a hosting provider you are much better off running an AWS Lightsail server for $5 a month.
