### ISSUE TITLE
Editing config files in /config (changes are lost with updates)

### ISSUE THREAD

**Issue by verygoodplugins** [freescout-helpdesk/freescout#3463]
PHP version: 8.0.30
FreeScout version: 1.8.104

In the [development guidelines](https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#development-guidelines) it says:

> After changing config files in `/config` don't forget to run `php artisan config:clear`.

We've made some changes in `purifier.php` and everything is working... but the changes are lost with each FreeScout update.

Is there a better way to preserve those changes between updates?

Thank you.

**Comment by freescout-helpdesk** [comment]
Development guide is for developers who make changes in files, commit them and submit as pull requests.

The only way is to copy your version of the file after each update.

What updates do you have in purifier.php? Can you share your purifier.php?

**Comment by verygoodplugins** [comment]
I see. Makes sense.

For allowed HTML we'd like to have `div[style]`, `td[style|colspan|rowspan|width]`, `table[width|class]` and `tr[bgcolor]`

And for CSS we'd like `padding,padding-top,padding-bottom`

(Our contact form sends HTML and the default styling makes it quite hard to read).

I can't think of any security issues with those 🤔 . Can I create a PR?

Or is it better to try and add the styles back in later via custom CSS?

**Comment by freescout-helpdesk** [comment]
> Can I create a PR?

Ok.

**Comment by freescout-helpdesk** [comment]
We've made changes in the `master` branch.

**Comment by verygoodplugins** [comment]
Thanks! 🙏
