### ISSUE TITLE
Bug: HTML link auto-tagging captures non-URL characters

### ISSUE THREAD

**Issue by verygoodplugins** [freescout-helpdesk/freescout#3464]
PHP version: 8.0.30
FreeScout version: 1.8.104

When including a URL in a conversation, FreeScout auto-converts URLs to an `<a>` tag, but this picks up any trailing punctuation unless an extra space is added after the URL. For example `.` or `)`

![CleanShot 2023-10-17 at 16 28 32@2x](https://github.com/freescout-helpdesk/freescout/assets/13076544/df171176-6da4-4e3f-8085-6b3e58f75056)

When we send a URL in parentheses this results in a 404:

<img width="672" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/13076544/02a05882-b3fb-4b98-b2f8-4b92c4bbaf29">

The link is sent to the customer correctly and stored in the DB... it's just something about the editor that is a little too greedy when wrapping it in a tag.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
