### ISSUE TITLE
Replies are not put in threads despite having matching In-Reply-To and References headers

### ISSUE THREAD

**Issue by jensolsson** [freescout-helpdesk/freescout#3465]
I start a conversation from support@ourcompany.com to support@anothercompany.com

Here is the Message ID of that message:
message-id=<reply-18400-fb26ceb5a996b8a4736c4e9ad00f7362@ourcompany.com>

Now I get an auto reply from anothercompany and it contains the following headers:
Message-ID:
 <c83dfb13ea4e46c49cdef354c269c1e5@GVYPXXX.PROD.OUTLOOK.COM>
References: <reply-18400-fb26ceb5a996b8a4736c4e9ad00f7362@ourcompany.com>
In-Reply-To: <reply-18400-fb26ceb5a996b8a4736c4e9ad00f7362@ourcompany.com>

Should it not be enough to receive the message in the same thread?

We are from time to time required to send from our freescout instance to another helpdesk somewhere and 90% of the time we will get an auto reply that ends up in a loop having the systems send back and forth for eternity.
Since most help desk installations get the headers wrong I think it would really be an advantage to be able to map incoming messages to a issue ID in the subject line, because almost all helpdesks do keep the subject line, and it is also easy to tell them "you need to keep the ID in the subject line"

I made a pull request to fix this, I think a year ago, but it was not accepted in the core. Then I tried making it into a plugin but I failed to make it work, my changes to the plugin did not seem to go live and there were no errors in the log. After many hours I gave it up.

Anyway, I still think it would be a great advantage to recognise issue IDs in the subject line. Any chance this can be reevaluated? Are there any more users with the same problem as me or do I just have bad luck trying to e-mail a lot of help desks which cant handle the headers?

**Comment by ilyakonovalenko** [comment]
> Are there any more users with the same problem as me or do I just have bad luck trying to e-mail a lot of help desks which cant handle the headers?

The problem is that every helpdesk acts its own way. Some keep reference of the initial email in the headers, some don't. It looks like there is no universal solution for this. Keeping ID in the subject would not help because some helpdesks add their own internal ID to the subject.

**Comment by jensolsson** [comment]
Yes most of then do, but then I could tag it with [XYX12345] where XYZ is my company designator and 12345 is the issue ID. I believe that is why many help desk systems have a prefix before the number?

**Comment by freescout-helpdesk** [comment]
The only way to achieve what you need is via custom module as there is no way to make a solution satisfying all helpdesks.
