### ISSUE TITLE
Chat Module "Whoops" Error.

### ISSUE THREAD

**Issue by NBSUKLTD** [freescout-helpdesk/freescout#3466]
Hello,

Facing a issue with the chat module, have embedded it on our website [www.e-liquids.uk](https://www.e-liquids.uk)

But we get the whoops error it says check storage logs but nothing is popping out to me regarding it.

Permissions are correct, core install is up to date, modules all up to date and cleared cache. 

Just looking for some help :)

**Comment by NBSUKLTD** [comment]
OK after some further debugging and trial and error we have narrowed this error down to the following:

Extra Security Module : (reCAPTCHA) End-User Portal "Submit a Ticket" Form.

When this Recaptcha setting is enabled; it causes the error, simply turning this off allows the chat widget to work as normal. 

Having both:
(reCAPTCHA) Main Login Form
(reCAPTCHA) End-User Portal Login Form

Enabled causes no problems.

**Comment by NBSUKLTD** [comment]
`[2023-10-21 01:24:37] production.ERROR: Undefined variable $errors (View: /home/nbs/notblowingsmoke/public/support/freescout/Modules/ExtraSecurity/Resourc>
[stacktrace]
#0 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\C>
#1 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engin>
#2 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEn>
#3 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents>
#5 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /home/nbs/notblowingsmoke/public/support/freescout/overrides/symfony/http-foundation/Response.php(206): Illuminate\\Http\\Response->setContent()
#7 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(724): Symfony\\Component\\HttpFoundati>
#8 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router::toR>
#9 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->pre>
#10 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illu>
#11 /home/nbs/notblowingsmoke/public/support/freescout/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}>
#12 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize>
#13 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#14 /home/nbs/notblowingsmoke/public/support/freescout/app/Http/Middleware/HttpsRedirect.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{clo>
#15 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRed>
#16 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#17 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\>
#18 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware>
#19 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#20 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illum>
#21 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\>
#22 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#23 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(61): Illuminate\\Ro>
#24 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\>
#25 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#26 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->>
#27 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->
#28 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->ru>
#29 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->ru>
#30 /home/nbs/notblowingsmoke/public/support/freescout/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->di>
#31 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Route>
#32 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Ker>
#33 /home/nbs/notblowingsmoke/public/support/freescout/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{>
#34 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Terminat>
#35 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#36 /home/nbs/notblowingsmoke/public/support/freescout/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{c>
#37 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Response>
#38 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#39 /home/nbs/notblowingsmoke/public/support/freescout/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing>
#40 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->
#41 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#42 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illum>
#43 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\M>
#44 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#45 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illum>
#46 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\M>
#47 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#48 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illumi>
#49 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\M>
#50 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#51 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46):>
#52 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\M>
#53 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->I>
#54 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->>
#55 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipe>
#56 /home/nbs/notblowingsmoke/public/support/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Ht>
#57 /home/nbs/notblowingsmoke/public/support/freescout/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 {main}`

**Comment by NBSUKLTD** [comment]
Also the chat module is caching customer Names and Emails across browsers and devices not very GDPR friendly:

<img width="391" alt="Screenshot 2023-10-21 at 12 52 33" src="https://github.com/freescout-helpdesk/freescout/assets/45541645/fc449a35-bf09-4c67-bdce-e3bb8c1cab5a">

**Comment by freescout-helpdesk** [comment]
Are you using the latest versions of modules?
