### ISSUE TITLE
Login logs IP addresses

### ISSUE THREAD

**Issue by nooblag** [freescout-helpdesk/freescout#3467]
Heya,

Thanks for great software!

We have Freescout installed on a server with Cloudflare in front of it.

I notice the IP address logging in _Manage -> Logs -> Users_ shows proxied IP addresses, and not user's actual origin WAN IP addresses:

![Screenshot from 2023-10-21 02-17-19](https://github.com/freescout-helpdesk/freescout/assets/1122344/c2274be4-9972-4bf5-a0d7-56cf5133af18)

I'm taking a guess that this might be because something like `$_SERVER['REMOTE_ADDR']` is used to pick up the IP and not `$_SERVER['HTTP_X_FORWARDED_FOR']`?

I noticed this when trying to troubleshoot some failed logins.

PHP version: 8.2
FreeScout version: 1.8.104

**Comment by freescout-helpdesk** [comment]
What "SSL/TLS encryption mode" are you using in CloudFlare? Under "SSL/TLS -> Overview".

**Comment by nooblag** [comment]
Full.

**Comment by freescout-helpdesk** [comment]
Update FreeScout to the latest version add the following line to the /.env file and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache):
```
APP_CLOUDFLARE_IS_USED=true
```

**Comment by nooblag** [comment]
Wow, that was quick! Thank you for the fix! :)

**Comment by DavidAnderson684** [comment]
Isn't the proper solution (as recommended by Cloudflare) to this to use `mod_remoteip`, so that `$_SERVER['REMOTE_ADDR']` can be used (otherwise you'll need a second solution in your webserver anyway to make sure the webserver logs record the same IP address as you're seeing in Freescout logs).
