### ISSUE TITLE
Problem with freescout installation 

### ISSUE THREAD

**Issue by Seregamgt** [freescout-helpdesk/freescout#3469]
Hi all! I have some problems with Freescout installation - if I try to connect on MyIP/install I see error with link on log file, in log:
[2023-10-23 10:01:37] production.ERROR: Undefined constant "FT_UID" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"FT_UID\" at /var/www/freescout/vendor/webklex/laravel-imap/src/config/imap.php:105)
[stacktrace]
#0 /var/www/freescout/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(66): require()
#1 /var/www/freescout/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#2 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#3 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#4 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#5 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#6 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#7 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#8 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#10 /var/www/freescout/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle()
#11 {main}
"} 
I think that's problem with PHP module but don't know in what... PHP and PHP modules installed correctly...
I use Apache2, MySQL and php 8.2.1software configuration. Please help me solve this problem...

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-undefined-constant-ft_uid

**Comment by Seregamgt** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-undefined-constant-ft_uid

I check this and see that php-imap installed in system.

**Comment by freescout-helpdesk** [comment]
Make sure php-imap is installed in the PHP you are using in cron:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

**Comment by Seregamgt** [comment]
> Make sure php-imap is installed in the PHP you are using in cron: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs
Run php -m and I see IMAP module in list of installed modules
Run php /var/www/html/artisan freescout:check-requirements and I see 
"In imap.php line 105:
Undefined constant "FT_UID" "

**Comment by Seregamgt** [comment]
> Make sure php-imap is installed in the PHP you are using in cron: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs
Now I use again sudo apt-get install php8.2-imap and see IMAP module is installed, then run php /var/www/html/artisan freescout:check-requirements and all status OK 
PHP Extensions
 OpenSSL....................... OK
 PDO........................... OK
 Mbstring...................... OK
 Tokenizer..................... OK
 JSON.......................... OK
 XML........................... OK
 IMAP.......................... OK
 GD............................ OK
 fileinfo...................... OK
 ZIP........................... OK
 iconv......................... OK
 cURL.......................... OK
 DOM........................... OK
 libxml........................ OK
 intl.......................... OK
 pcntl (console PHP)........... OK
Functions
 shell_exec (PHP).............. OK
 proc_open (PHP)............... OK
 fpassthru (PHP)............... OK
 symlink (PHP)................. OK
 ps (shell).................... OK
But I can't run installer again error
[2023-10-23 11:58:46] production.ERROR: Undefined constant "FT_UID" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"FT_UID\" at /var/www/freescout/vendor/webklex/laravel-imap/src/config/imap.php:105)

**Comment by Seregamgt** [comment]
Another error... I make changes in config/imap.php in 105 string
before 'fetch' => FT_UID, - after 'fetch' => 'FT_UID',
and now I see error:
[2023-10-23 13:07:40] production.ERROR: file_put_contents(/var/www/freescout/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/freescout/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): Failed to open stream: Permission denied at /var/www/freescout/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
