### ISSUE TITLE
Can't remove attachments when forwarding a conversation

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#3470]
PHP version: 8.1.24
FreeScout version: 1.8.105

Since version 1.8.102 (I think), when I forward a conversation that has more attachments, I can delete only the first one.
When clicking on "x" to delete other attachments, nothing happens and there's no error in the browser console.
I made a short video here:
https://watch.screencastify.com/v/m7wFIVCn3UqbHFKzHEZJ

Notes:
- no App Log error
- no error in browser console
- tested on multiple browsers and OS
- I could not reproduce this on the demo site, but I could not receive an email there to test the exact same scenario

Thank you

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/20fe99a820f2642134660476f93b4c1baaa8472a

**Comment by dabesa** [comment]
Thanks!
