### ISSUE TITLE
Failure to Deliver Email to Shared Inbox When Using "Reply All" with CC Recipient Modifications

### ISSUE THREAD

**Issue by rosequaartz** [freescout-helpdesk/freescout#3473]
# Summary

We have encountered an issue in Freescout where utilizing the `Reply All` or `Reply` functionality to respond to an email, specifically when modifying the existing CC recipients to include a Freescout shared inbox, leads to the shared inbox not receiving the email. 

## System Specs

PHP version: 8.2

Freescout version: 1.8.100

# Steps to Replicate

1. Create an email and send from Freescout shared inbox AA account to Mail Client Recipient A and cc to Mail Client Recipient B and Mail Client Recipient C,

1. The email is received to Mail Client Recipient A as well as both cc'd Mail Client Recipients B and C,

1. Mail Client Recipient A clicks `Reply All` or `Reply` to respond to the thread,

1. With `Reply All` Mailclient autofills the to Recipient as Freescout shared inbox AA and cc to Mail Client Recipient B and C,

1. Mail Client Recipient A then **removes** both cc'd addresses that were auto-filled when selecting `Reply All`,

1. Mail Client Recipient A then manually adds three new cc recipients: Mail Client Recipient D, Mail Client Recipient E and Freescout shared inbox account BB

1. The email is received to Freescout shared inbox AA as well as Mail Client Recipient D and Mail Client Recipient E,

1. Email was **NOT** received to the newly added cc Freescout BB shared inbox account.

# Current Behaviour

The current behaviour is as follows: When using the `Reply All` or `Reply` functionality to respond to an email and making modifications to the existing CC recipients by including a Freescout shared inbox, the shared inbox does not receive the email as expected. We can remove recipient addresses successfully, but adding a new recipient address, post `Reply All` or `Reply` isn't successful. This behavior results in a failure to deliver the email to the intended shared inbox, which is a critical issue, as it hampers the system's core functionality. We have experienced this with earlier versions of Freescout as well.

# Expected Behaviour

The expected behaviour should ensure the uninterrupted delivery of emails to all designated cc recipients, inclusive of Freescout shared inboxes when utilizing the `Reply All` or `Reply` features. 

# Potential Solutions

Review the code responsible for handling email delivery when using the `Reply All` or `Reply` features. Ensure that the code accurately processes modifications to CC recipients.

**Comment by freescout-helpdesk** [comment]
Could you please add to each step information where this step is performed: in FreeScout or in the email client.

**Comment by freescout-helpdesk** [comment]
> 3. Mail Client Recipient A clicks Reply All or Reply to respond to the thread,
> 4. With Reply All Freescout autofills the to Recipient as Freescout shared inbox AA and cc to Mail Client Recipient B and C,

Where does the step 4 takes place? FreeScout does not have "Reply All" button.

**Comment by rosequaartz** [comment]
Apologies that was a typo on my part! Step 4 has been updated to reflect Mail Client. 😄

**Comment by freescout-helpdesk** [comment]
You can try with the attached `/app/Console/Commands/FetchEmails.php` file:

[FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/13125267/FetchEmails.zip)

**Comment by rosequaartz** [comment]
awesome! thank you! 😄

**Comment by rosequaartz** [comment]
## Steps Taken

Freescout instance was manually patched with the recommended `/app/Console/Commands/FetchEmails.php` file:

[FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/13125267/FetchEmails.zip)

## Test Performed

1. Create an email and send from Freescout shared inbox AA account to Mail Client Recipient A and cc to Mail Client Recipient B and Mail Client Recipient C,
2. The email is received to Mail Client Recipient A as well as both cc'd Mail Client Recipients B and C,
3. Mail Client Recipient A clicks Reply All or Reply to respond to the thread,
4. With Reply All Mail Client autofills the to Recipient as Freescout shared inbox AA and cc to Mail Client Recipient B and C,
5. Mail Client Recipient A then removes both cc'd addresses that were auto-filled when selecting Reply All,
6. Mail Client Recipient A then manually adds three new cc recipients: Mail Client Recipient D, Mail Client Recipient E and Freescout shared inbox account BB
7. The email is received to Freescout shared inbox AA as well as Mail Client Recipient D and Mail Client Recipient E,
8. Email is SUCCESSFULLY received to the newly added cc Freescout BB shared inbox account.

## Result

Emails are now successfully received to a shared inbox when using `Reply All` or `Reply` with CC recipient modifications.

Thanks very much @freescout-helpdesk! 😸
