### ISSUE TITLE
Outgoing replies not saving to IMAP folder

### ISSUE THREAD

**Issue by mitchplze** [freescout-helpdesk/freescout#3474]
Hello,

I saw a few previously resolved issues about this, but outgoing emails are not saving to the IMAP folders, for any of the three mailboxes I have configured in Freescout. 

The "get folders" button works instantly, and the "Sent" folder I need, appears in the "IMAP folders" box as a little label, for testing purposes. Incoming IMAP fetch works flawlessly. Unfortunately there are zero log entries regarding any failures or successes, at all. No messages are being written to the Sent folder at the mail host (Fastmail). 

PHP version: 8.2.10
FreeScout version: 1.8.105

<img width="674" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/25162574/9cd17d30-74c5-4680-80ae-7d8c9e7244b6">

<img width="1035" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/25162574/b4030077-6a0b-45f1-9428-85806a818e35">

**Comment by freescout-helpdesk** [comment]
If some error occurs during saving an email to the IMAP folder it's logged to Manage > Logs > App Logs.

**Comment by mitchplze** [comment]
There have not been any errors generated at all for the IMAP issue. There are not even any logs for several days. I just sent an email a moment ago, and this is all I have. 

![IMG_1505](https://github.com/freescout-helpdesk/freescout/assets/25162574/46388a8b-eacf-4f8b-9239-240414f81412)

**Comment by freescout-helpdesk** [comment]
Someone need to investigate it on your server.
