### ISSUE TITLE
Ticket Category

### ISSUE THREAD

**Issue by bekre10** [freescout-helpdesk/freescout#3475]
Our support agents need to assign categories to each ticket, such as
Password reset
Printing issue
Windows issue
M365 issue
Request

Currently we use the Custom Fields module for this (drop down menu).
But we and some of our customers as well, would love to be able to see a report of the ticket categories.
So if we see that last months there were 150 SAP password reset tickets, then we can talk to the developer and see how this can be improved.

Is this possible to be added / module to be created? I am happy to pay for it.

**Comment by ilyakonovalenko** [comment]
Maybe use tags module? Reports module allows to see number of conversations per tag.

**Comment by bekre10** [comment]
Thank you. But we are already assigning tags to each customer (with their company name) so we can see in the Report section, how many tickets we processed for each customer. While I could add more, I find it confusing with so many tags and to ensure my staff won't forget to categorize each ticket, a drop down menu would work best. But the "Custom Fields" module doesn't show in Reports.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
