### ISSUE TITLE
Is there any SQL Query Reports Documentation?

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#3477]
Hi, I like the reports that comes with freescout. I will like to re create some of them outside freescout in an intranet so I can monitor some KPI remotely. My question is if any one have any documentation or simple the query's to recreate the reports?
I will really apreciate it.

Thanks.

**Comment by freescout-helpdesk** [comment]
Unfortunately not. You'll need to figure it out from source code.

**Comment by DavidAnderson684** [comment]
You could turn on SQL query logging on your SQL server.
