### ISSUE TITLE
"All from current mailbox" search option

### ISSUE THREAD

**Issue by DavidAnderson684** [freescout-helpdesk/freescout#3480]
The "All from current mailbox" search option appears if you are viewing the list of mails in a mailbox; but not if you are viewing an individual mail from that mailbox.

I frequently am reading a mail in a mailbox, and wish to search the whole mailbox (because the customer's issue has reminded me of a similar issue on the same product); but to do this requires navigating back to the mailbox index.

Suggestion: add the "All from current mailbox" search option when viewing an individual conversation.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.
