### ISSUE TITLE
[Tags extension] activities with tags are not shown in timeline

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#3483]
When somebody assigns or closes a conversation this is shown in the timeline for that conversation.

However when a conversation is tagged it is not shown in the timeline. Please include that here.

This is useful for accountability.

![Screenshot 2023-10-28 at 19 25 45](https://github.com/freescout-helpdesk/freescout/assets/382183/e47e8821-afbb-4c4a-99ea-32ee2e436cbc)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by fulldecent** [comment]
Moved to https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/422918
