### ISSUE TITLE
Bug: Inconsistent Default Redirect behavior

### ISSUE THREAD

**Issue by verygoodplugins** [freescout-helpdesk/freescout#3486]
PHP version: 8.0.30
FreeScout version: 1.8.106

We've been experiencing inconsistent behavior with the Default Redirect feature. On our instance, after Replying and Closing a conversation, or adding a note and assigning it to another user, it jumps to the next _Pending_ conversation in the list, even when there are other _Active_ conversations available.

For simplicity's sake I've reproduced this twice in the FS demo site:

1. Send and Close takes me to the next _Pending_ conversation despite there being an _Active_ conversation assigned to me: https://i.wpfusion.com/YjdKy3YJ
2. Adding a note and assigning to another user takes me to the next _Closed_ conversation: https://i.wpfusion.com/dy35NxsN

Thank you.

**Comment by freescout-helpdesk** [comment]
We've reproduced the issue. It happens when sending & closing the last active conversation.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by verygoodplugins** [comment]
Thanks! 🙏
