### ISSUE TITLE
Cannot assign ticket if mandatory custom ticket fields are not filled in

### ISSUE THREAD

**Issue by sasustefan** [freescout-helpdesk/freescout#3487]
Hello,

I am using mandatory custom fields with the intent to have agents log some critical information before closing the ticket. I enabled the mandatory fields but now I can't assign any ticket to the team unless I fill in all required fields.
I am using the official modules without any customization. Is there an option to achieve the behavior described above?

PHP version: 8.1
FreeScout version: 1.8.98

Thank you in advance!

**Comment by freescout-helpdesk** [comment]
Unfortunately not. The only way is to make those fields optional.
