### ISSUE TITLE
No bottom scroll for knowledge base pages on mobile

### ISSUE THREAD

**Issue by sasustefan** [freescout-helpdesk/freescout#3488]
Hello,

I am using the official modules and for wide pages there is no bottom scroll and I can't see the entire page, even in landscape mode. I am able to see the full page in landscape mode on bigger screens (6.7 inches and above).

Thank you in advance!

PHP version: 8.1
FreeScout version: 1.8.98

![Screenshot_20231031_110245_Chrome](https://github.com/freescout-helpdesk/freescout/assets/148548597/87d4d3b0-968a-4f18-b227-334955aca30b)
![Screenshot_20231031_173042_Chrome (1)](https://github.com/freescout-helpdesk/freescout/assets/148548597/5f22a196-c1ab-4996-aaaa-3f918ef7a8b1)

**Comment by freescout-helpdesk** [comment]
Fixed in Knowledge Base Movule v1.0.62. Now horizontal scroll will be shown at the bottom of an article when article content is too wide.
