### ISSUE TITLE
Error during import LDAP users

### ISSUE THREAD

**Issue by Azziii** [freescout-helpdesk/freescout#3489]
For some users an errors appears during import with LDAP Integration module:

- SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(100) 
- Unable to import user User: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "first_name" of relation "users" violates not-null constraint

Will you fix this in future releases or will these restrictions remain?

**Comment by freescout-helpdesk** [comment]
> null value in column "first_name" of relation "users" violates not-null constraint

It means some record in your LDAP is missing "first_name" value. First Name is required for users.

**Comment by freescout-helpdesk** [comment]
Also what database are you using?

**Comment by Azziii** [comment]
Using postgresql.
And yes, we have users with title longer than 100 symbols.
