### ISSUE TITLE
User reply gets wiped out if written between ticket response text

### ISSUE THREAD

**Issue by stockmind** [freescout-helpdesk/freescout#349]
Hi!
We have problems when users reply to tickets writing in the middle of the ticket's reply text (trying to "quote/cite" phrases):

Wiped body seen from FreeScout:
![image](https://user-images.githubusercontent.com/5653847/66919670-0e3ddb80-f022-11e9-8802-92d1800ff74b.png)

![image](https://user-images.githubusercontent.com/5653847/66919884-7e4c6180-f022-11e9-94f5-8b75d9a819d2.png)

Original mail seen from a standard mail client

![image](https://user-images.githubusercontent.com/5653847/66920834-61189280-f024-11e9-8632-d1ec6b29ab2d.png)

First lines of original body:
```
<html>
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    Gentile,<br>
    <br>
    <div class="moz-cite-prefix">Il 15/10/2019 16.39, **Mailbox** ha
      scritto:<br>
    </div>
    <blockquote
      cite="mid:reply-1390-359f38463d487e9e29bd20e24f0c050a@**domain**.it"
      type="cite">
      <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
      <meta name="viewport" content="initial-scale=1.0">
      <style>
        p { margin:0 0 1.6em 0; }
        pre { font-family: Menlo, Monaco, monospace, sans-serif; padding: 0 0 1.6em 0; color:#333333; line-height:15px; }
        img { max-width:100%; }
        a { color: #346CC4; text-decoration:none; }
    </style>
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
          <tr>
            <td>
              <table id="fsReplyAbove" class="fsReplyAbove" border="0"
                cellpadding="0" cellspacing="0" width="100%">
```

There is something we can do?
I've seen ticketing systems that add a "DO NOT WRITE UNDER THIS LINE" or is just something that need a fix in the mail body parser?

Is something you already seen?

Thanks!

**Comment by freescout-helpdesk** [comment]
This is a non-trivial task. If somebody will find a solution, it will be great.
For now it is possible to see full conversation using "Show Original" dropdown menu item.

**Comment by stockmind** [comment]
> This is a non-trivial task. If somebody will find a solution, it will be great.
> For now it is possible to see full conversation using "Show Original" dropdown menu item.

Actually no, that doesn't work:
![image](https://user-images.githubusercontent.com/5653847/66922719-e8b3d080-f027-11e9-880f-6bf4ca0603d7.png)

We have no way to see the original full reply without open a mail client with this mailbox configured at the moment

**Comment by freescout-helpdesk** [comment]
Update to the latest version.

**Comment by stockmind** [comment]
Ops, my fault, missed the "Show preview of the full message for the thread in Show Original modal." fix!
Updated! This will apply only to new messages, right?

Wouldn't a `-- Please reply above this line --` work like GitHub does on notifications mail?
![image](https://user-images.githubusercontent.com/5653847/66937702-3e947280-f040-11e9-9a2e-988723e99bb1.png)

Or a `## Please do not write below this line ##` as they do in their ticket system:
![image](https://user-images.githubusercontent.com/5653847/66937907-8b784900-f040-11e9-8697-a9dd74fc7d74.png)

on top of their reply 

Just to instruct users about what they should/shouldn't do to be sure that their messages are not cut off

**Comment by stockmind** [comment]
Wouldn't a `-- Please reply above this line --` work like the first alert you get, on top of the replies?
![image](https://user-images.githubusercontent.com/5653847/66939222-f0cd3980-f042-11e9-9e66-835ebf61d197.png)

Or a `## Please do not write below this line ##` as GitHub does in their ticket system:
![image](https://user-images.githubusercontent.com/5653847/66939295-19edca00-f043-11e9-8847-56edcd1ea46d.png)
on top of their reply

Just to instruct users about what they should/shouldn't do to be sure that their messages are not cut off

I apologize if there is an option and I have not seen it.

**Comment by freescout-helpdesk** [comment]
If support agent sends customer a message and customer writes his reply inside of the text written by support agent, it will not be visible in the conversation, only in "Show Original" modal.

**Comment by stockmind** [comment]
Sure, but a kind reminder "do not write below this line" to the customer could help him avoid writing inside of the text written by support agent

**Comment by stockmind** [comment]
Pinging about this issue, there is a way to customize the reply template header to add this "do not write below this line" string?

**Comment by freescout-helpdesk** [comment]
> Pinging about this issue, there is a way to customize the reply template header to add this "do not write below this line" string?

Such an option will need to be added.

For now you can add the text to the very bottom of your mailbox signature.

**Comment by freescout-helpdesk** [comment]
`Text Before The Reply` option will be added to mailboxes.

**Comment by foliovision** [comment]
Not the same issue but related: when quoting back a lot of customer text, I find it more efficient and reliable to copy the customer's reply and take it into a Markdown editor where it's easy to break each part of the customer's section into a quote and reply to it. At the end, select all and copy HTML pastes nicely into the code option in the Freescout composer.

I don't even mind doing this kind of writing in a separate application as composing long replies like this within browser applications is living dangerously. Thanks for offering that very simple and effective source code button. Allows us to help ourselves.
