### ISSUE TITLE
White text with dark background disappears unless in Dark Mode

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3492]
Freescout 1.8.106 on Ubuntu.

We received an email that, in Outlook, shows some white text on a dark background, and the text is visible and readable.

Freescout doesn't seem to render the dark background, and it looks like the message body is empty.  But if we enable 'Dark Mode' in Freescout the text is visible.

So it would seem the 'dark background' of the text isn't getting rendered as it should?
![firefox_564](https://github.com/freescout-helpdesk/freescout/assets/18216162/b7ed8192-e2fb-41cd-bd53-2af7ae06c440)
![firefox_565](https://github.com/freescout-helpdesk/freescout/assets/18216162/3156492b-47cc-4d44-a668-1c6d15d6298a)
![MobaXterm_561](https://github.com/freescout-helpdesk/freescout/assets/18216162/5b92e328-85cd-4a66-b56b-e076d59242f4)

I've attached screenshots of what the message looks like in Outlook, and in light/dark mode of Freescout.

Thanks!

**Comment by apecity** [comment]
Here is the relevant source from the email
<div class="WordSection1">
<p class="MsoNormal"><span style="font-size:13.5pt;font-family:&quot;Roboto&quot;,serif;color:white;background:#434857">7095695154<o:p></o:p></span></p>
<p class="MsoNormal"><span style="font-size:13.5pt;font-family:&quot;Roboto&quot;,serif;color:white;background:#434857"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="font-size:13.5pt;font-family:&quot;Roboto&quot;,serif;color:white;background:#434857">7095695154</span><span style="font-size:12.0pt;font-family:&quot;Dante&quot;,serif;color:#0070C0;mso-fareast-language:EN-US"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="font-size:12.0pt;font-family:&quot;Dante&quot;,serif;color:#0070C0;mso-fareast-language:EN-US"><o:p>&nbsp;</o:p></span></p>
<div>

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.
