### ISSUE TITLE
Timetracker does not commit when status is changed to Pending

### ISSUE THREAD

**Issue by carlaionita** [freescout-helpdesk/freescout#3494]
PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version: 1.8.105

Hi guys, we just bought the TimeTracker module and we're trying to understand how it works. I'm not 100% sure, but i think there's a bug(?)

According to the documentation, the logged time should be committed on the conversation when the status is changed, but it only dues when changed to "Closed". Isn't "Pending" considered a status? Normally we only close a conversation when the customer confirms. Meanwhile we keep it Pending, This is the moment when we'd like to commit the time spent for that issue. 

![image](https://github.com/freescout-helpdesk/freescout/assets/149695313/b7cf217d-9852-4ac9-bc80-f48afbac27b4)

Thanks for your inputs!
Carla

**Comment by freescout-helpdesk** [comment]
It works only for Closed status. There is no possibility to enable it for "Pending" status for now. The only way is to manually adjust the code of the module.

**Comment by freescout-helpdesk** [comment]
> will this change be overwritten by the next update of the app?

Yes.
