### ISSUE TITLE
Issues sending Mail from 2nd Mailbox

### ISSUE THREAD

**Issue by rhomson2** [freescout-helpdesk/freescout#3495]
PHP version: PHP 8.2.10
version: 1.8.106

Hi guys
We are troubling with Mails not being sent from our 2nd Mailbox
Our first Mailbox works just fine. But with our 2nd Mailbox we are only able to send Test-Mails. All other Customer related Mails are never being processed.
Every messages has the following message: `There were no send attempts yet`

I've tried to debug but with no success, since i am not really fluent in anything PHP

Some steps we did:
1. Run `php /www/html/artisan freescout:send-monitor` Result is: `Emails queue processing is working`
2. Cleared the cache
3. Checked crontab for `php /www/html/artisan schedule:run >> /dev/null 2>&1` which exists.

We are using different Mailservers for the 1st Mailbox and the 2nd one. But i thought that this would not be an issue. Both are connected by SMTP. 

Thanks for the help

**Comment by freescout-helpdesk** [comment]
Anything in Manage > Logs > App Logs?

**Comment by rhomson2** [comment]
Sadly there is noting in the App logs. Also not in the "Outgoing Emails" log, apart from the working 1st mailbox.
Could the issue be that we are sending internal mails from the 2nd mailbox ending in .local. Do you have filter that does not let "real" top-level-domains through?
Thanks for the help!

**Comment by freescout-helpdesk** [comment]
All we can advice is written here: https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues#1-if-emails-are-not-sent-or-sent-with-delay
