### ISSUE TITLE
Issue with {%ratings.add%} Placeholder in Satisfaction module

### ISSUE THREAD

**Issue by YoaviX** [freescout-helpdesk/freescout#3496]
Bug Description:
I'm experiencing an issue with the {%ratings.add%} short code, when using the Satisfaction Rating Module in Freescout. When I send emails with this placeholder, I encounter the following error:

Error: parse: body: from string: ...

his error suggests that the "ratings" tag is not found, although I've configured the Satisfaction Rating Module according to the documentation.

Steps to Reproduce:

Configure the Satisfaction Rating Module in Freescout.
Create an email template containing the {%ratings.add%} placeholder.
Send an email with the template.
Expected Behavior:
The email should be sent without errors, and the {%ratings.add%} placeholder should be replaced with the satisfaction rating options.

Actual Behavior:
I receive an error, and the "ratings" tag is not found in the email template.
Additional Information:

Freescout Version: 1.8.106

Any Help or Insights:
I would greatly appreciate any assistance or insights into resolving this issue. I rely on the Satisfaction Rating Module to collect feedback from our customers, and it's crucial for our support processes.

Thank you for your attention and support.

**Comment by freescout-helpdesk** [comment]
> I encounter the following error

Where do you see this error?

Are using any non-official modules? Try to disable them.

**Comment by YoaviX** [comment]
I see this error when checking on our mail server the mail status. We do
not use non-official modules.

**Comment by freescout-helpdesk** [comment]
The issue must be related to your mail server. The module does not throw this kind of errors.

**Comment by YoaviX** [comment]
we will change the mail server for testing, will update afterwards.
