### ISSUE TITLE
Change Request: Conversation should be marked as 'Unread' by default when asignee is changed

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3498]
We're using ver 1.8.106 on Ubuntu.

A user pointed out to us that a conversation assigned to him should be marked as "Unread"/displayed in bold, as he hasn't read it yet.

We think this makes sense, and on a practical level, the newly assigned conversation would 'stand out' in the user's queue more by be displaying in bold.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to implement this for now. But feel free to submit a feature request: https://freescout.net/request-feature/
