### ISSUE TITLE
phone customers always appear in the customer search results

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3499]
When I search for a customer, it seems that always every existing "phone customer" shows up regardless of the search term/parameters.

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/6573f23c-e894-49c8-8ed9-65f987fbdfc0)

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
