### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#35]
Implement adding tags to conversations.

**Comment by WebSpanner** [comment]
Can we discuss some acceptance criteria for this feature? Here's my draft concept:

- A user can apply a tag to a conversation
- A user can remove a tag from a conversation
- A user can filter conversations by tag

Possible future extensions of this feature:

- A user can create a filter to automatically apply tags to a new conversation based on to:address
- A user can create a filter to automatically apply tags to a new conversation based on from:address
- A user can create a filter to automatically apply tags to a new conversation based on matching string in incoming message

**Comment by freescout-helpdesk** [comment]
Yes.

There should be a possibility to filter conversations by clicking on a tag and also there should be a possibility to search by tags using search function: "tag:tagname" 

In `Manage > Settings > User Permissions` there is a **"Users are allowed to manage tags"** option, it  need to be taken in to account (see how "Users are allowed to delete notes/conversations" is implemented)

**Comment by freescout-helpdesk** [comment]
We will implement this
