### ISSUE TITLE
Error when fetching emails from non-ascii imap folder

### ISSUE THREAD

**Issue by Skryabind** [freescout-helpdesk/freescout#3502]
When fetching email from folders with non-ascii characters there is an error occurs. The reason is that Webklex IMAP library just pass folder name to the server without any encoding.

The fix is simple, just replace 
```$folder_name```
to 
```mb_convert_encoding($folder_name, "UTF7-IMAP","UTF-8")```

in app/Console/Commands/FetchEmails.php:166

**Comment by freescout-helpdesk** [comment]
Similar issue has been already fixed in the past. What's your FreeScout version? What's your folder name?

**Comment by Skryabind** [comment]
I have the latest version from git, 1.8.107.
Folder name is Спам ("Spam" in russian).
Before fixing that I had an error:
Folder: ????????; Error: [CLIENTBUG] SELECT Folder encoding error. sc=2Oh8MKBqJCg0_061924_63

For folder INBOX all worked correct.

**Comment by freescout-helpdesk** [comment]
What mail server are you using?

**Comment by Skryabind** [comment]
I'm using free public service https://mail.yandex.ru/
"Спам" is default created folder for spam.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by sofl88** [comment]
@freescout-helpdesk are you aware of the double encoding here ? https://github.com/freescout-helpdesk/freescout/blob/4c9f247cf67eaf20d136516e012372d71d0d1ad0/overrides/webklex/laravel-imap/src/IMAP/Client.php#L267

It is now given encoded (`&BCEEPwQwBDw-`) but gets encoded again (`&-BCEEPwQwBDw-`). I expected an error but it seems like it doesn't matter (the folder is recognized anyway) ... but maybe there are cases where it does matter (?)

**Comment by Skryabind** [comment]
I've checked that function_exists('.imap_utf8_to_mutf7') (with trailing dot) returns false for me, and function_exists('imap_utf8_to_mutf7') (without dot) returns true, so in my case encoding occurs only once.

**Comment by sofl88** [comment]
You are right. I overlooked the leading dot in the function name so it basicly always return false I asume (?) Thanks for clarification!
