### ISSUE TITLE
Undefined array key 1

### ISSUE THREAD

**Issue by mateit-cloudware** [freescout-helpdesk/freescout#3503]
HI There, 
we have setup the Azure AD Connection to fetch mail. But are facing the following issue:

<img width="624" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/69690256/f4b20d3f-6290-4709-bc63-76f3045f9d51">

This is when I try to test the connection in the settings.
Also no E-Mails appear in the inbox. So it's not working.

We cleared the cache and also connected again. Folders where fetched perfectly all premissions are set in Azure. So still the same issue. Can you please help?

We have installed Freescout via Cloudron.

**Comment by freescout-helpdesk** [comment]
Anything in Manage > Logs > App Logs?

**Comment by mateit-cloudware** [comment]
No unfortunately not. I tried it today, too. But no log was created. But the issue still appears like in the screenshot.

**Comment by freescout-helpdesk** [comment]
Replace this block of code https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/MailboxesController.php#L627 with:
```
                    //try {
                        $test_result = \App\Misc\Mail::sendTestMail($request->to, $mailbox);
                    //} catch (\Exception $e) {
                    //    $response['msg'] = $e->getMessage();
                    //}
```

Click "Send Test" again and send us full error message from Manage > Logs > App Logs.

**Comment by mateit-cloudware** [comment]
Sorry I'm a littlebit new at it. I searched for the file in the cloudron filemanager for this application, but it could not find it. Can you may help how i got access to it?

**Comment by freescout-helpdesk** [comment]
https://forum.cloudron.io/topic/4856/modifying-files-in-app-code/6

**Comment by mateit-cloudware** [comment]
[fetch-emails (1).log](https://github.com/freescout-helpdesk/freescout/files/13296935/fetch-emails.1.log)

HI There, please find the stepts I take and the log file: 
![image](https://github.com/freescout-helpdesk/freescout/assets/69690256/20ec1476-21a8-424a-beda-bbc0f4df880b)

**Comment by freescout-helpdesk** [comment]
So it looks like you have an issue with fetching emails, not with sending.

Replace this block of code https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/MailboxesController.php#L673 with:
```
                    //try {
                        $test_result = \MailHelper::fetchTest($mailbox);
                    //} catch (\Exception $e) {
                    //    $response['msg'] = $e->getMessage();
                    //}
```

Click "Check Connection" again and send us full error message from **"laravel-...log"** file from Manage > Logs > App Logs.

**Comment by mateit-cloudware** [comment]
Hi There, 

I have done these steps and tried to fetch the Mails. After that I looked at Manage > Logs > App Logs, but no log there: 
![image](https://github.com/freescout-helpdesk/freescout/assets/69690256/3bac75a4-a788-42c7-b6a2-ecbc9acecdee)

**Comment by freescout-helpdesk** [comment]
Have you clicked "Check Connection" button on "Fetching Emails" tab?

**Comment by mateit-cloudware** [comment]
Yes i tried it several times...

**Comment by mateit-cloudware** [comment]
I have a theroie, because we have a lot of folders inside of the exchange. And not all can be fetched. Is this maybe the reason the code is crashing?

**Comment by freescout-helpdesk** [comment]
Yes, something must be wrong with your folders. In the log also there is:
```
Could not get mailbox IMAP folder: INBOX
```

Anyway the only way to find out is for someone to debug it on your server.

**Comment by mateit-cloudware** [comment]
Have it. Please find the Log file attached
[laravel-2023-11-08.log](https://github.com/freescout-helpdesk/freescout/files/13298669/laravel-2023-11-08.log)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by mateit-cloudware** [comment]
Hi there, do you already know when the new release will come out?
