### ISSUE TITLE
"OAuth & Social Login" Module does not work for capitalised emails

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3504]
Hi,

We just set up freescout using docker, with this image "tiredofit/freescout:php8.2-1.17.41", installed the OAuth Module, and it seems to mostly work as expected. But whenever we have some inconsistencies with how emails are returned from Microsoft, we get issues with matching the email when logging in, and the user is presented with "Error creating user".

After some debugging, we found that User::create does a call to Email::sanitizeEmail, which modifies the email, including making it all lower case. This sanitizeEmail function is not called when the OAuth Module checks if a user already exists, which just calls `$user = User::where('email', $user_email)->first();`

Modifying the code in /www/html/Modules/OauthLogin/Http/Controllers/OauthLoginController.php, importing `use App\Email;` at the top of the file, and adding the line `$user_email = Email::sanitizeEmail($user_email);` before the call to User::where, fixes the issue. However, this issue will be back any time we choose to restart the app (which reinstalls modules), so it would be great with a permanent fix!

Some more info: We tried a few different approaches for getting the email, e.g. using userPrincipalName and changing the endpoint where we get the user data, however, none are guaranteed to be consistent that we have found, and some emails may be capitalised somewhere, and we are back at the issue.

At least using the docker image above, we have not found a permanent workaround, except modifying the code every time we deploy.

PHP version: 8.2.10
FreeScout version: 1.8.106
Database: PostgreSQL
Are you using CloudFlare: No

Thanks for the help!

**Comment by freescout-helpdesk** [comment]
We'll fix it. It's PostgreSQL - it uses case sensitive search by default.

**Comment by freescout-helpdesk** [comment]
We've double checked - `User::create()` does sanitize the email address: https://github.com/freescout-helpdesk/freescout/blob/dist/app/User.php#L991

Does it happen for you for users created via the OAuth & Social Login Module? Or those users were created via something else?

**Comment by borgarlie** [comment]
We create all users using that Module. Haven't tested anything else as it is irrelevant for us. The OAuth module uses the User::create() and User::where.

What happens is that: We create a user. The email is sanitized and put into database. We can check the database, and the email is "first.last@company.com". Then, when that person tries to log in at a later point he is faced with "Error creating user" as "First.Last@company.com" is not the same as "first.last@company.com".
