### ISSUE TITLE
iFrame embed not appearing in conversation after save

### ISSUE THREAD

**Issue by cj-cuccaro** [freescout-helpdesk/freescout#3505]
PHP version:  PHP 8.1.24
FreeScout version:  1.8.108
Database: Mysql (10.6.12-MariaDB) 
Are you using CloudFlare: No

When I embed an iframe element into the code view of the conversation and then return to the visual editor I see the embedded video but when I save the conversation and view the conversation I don't see the embedded video.  Why?

This is the embed code...
<iframe src="https://drive.google.com/file/d/1RyXeSopcjPmDqdh8SX1N8Mdpx4BR3S7g/preview" width="640" height="480" allow="autoplay"></iframe>

Thanks

**Comment by freescout-helpdesk** [comment]
It's impossible to save iframes in replies.
