### ISSUE TITLE
"Older"/"Newer" buttons do cycle between two specific tickets

### ISSUE THREAD

**Issue by truaddict** [freescout-helpdesk/freescout#3506]
PHP version:  8.2.11
FreeScout version:  1.8.108 (bug was also on previous version)
Database: PostgreSQL
Are you using CloudFlare: No

Hi,
seems older/newer buttons do cycle between two specific tickets, when I open one of them. I found some old request about this, but it was marked as fixed around a year ago. No errors in Manage - Logs section.

**Comment by freescout-helpdesk** [comment]
What's their status? Active, Pending?
Can you give a screenshot of the conversations list.

**Comment by freescout-helpdesk** [comment]
Should be fixed in the `master` branch.

**Comment by truaddict** [comment]
Thank you very much
