### ISSUE TITLE
Tags Module: Persistent tags even if not assigned to any ticket (enhancement request)

### ISSUE THREAD

**Issue by distresscode** [freescout-helpdesk/freescout#3507]
I'd like to suggest an improvement to the tags module where created tags are persistent and do not disappear if unassigned to a ticket. Currently, I have to re-create a tag and then re-apply the color to it. I use the tags to indicate the "stage/phase" of a project so tags do not remain assigned to tickets indefinitely.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by distresscode** [comment]
The page won't open. It just says "Loading...". I tried in Firefox and Brave, same thing happens.

**Comment by freescout-helpdesk** [comment]
Try again after some time.
