### ISSUE TITLE
Firefox is not allowed to open embedded pages - updated to 1.8.108

### ISSUE THREAD

**Issue by gplast1981** [freescout-helpdesk/freescout#3509]
Since I have updated to 1.8.108, Freescout can no longer be opened in Firefox in the iframe, before it worked without problems, now I get the error message. Firefox is not allowed to open embedded pages. But we need Freescout in the iframe.

How can I undo the upade? Or fix the problem. Thanks for your help

![wewew](https://github.com/freescout-helpdesk/freescout/assets/138209591/09b7c085-6966-477d-8101-c48e06155785)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#im-receiving-sameorigin-error-in-the-browser-when-embedding-freescout-via-iframe-on-another-website

**Comment by gplast1981** [comment]
Thank you very much it works again
