### ISSUE TITLE
Another agent reply indication

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#3510]
Hello,

For now, another agent replying circle indication is too small and is barely visible. This may result in duplicate responses when multiple employees (users) are working at the same time.

I would ask for two changes:
1. Make agents "viewing" / "replying" indication more visible (maybe make red border thicker or even make it blinking).
2. Add some confirmation in case there are some new messages added.

Thank you!

**Comment by freescout-helpdesk** [comment]
When support agent is replying his/her icon is highlighted with the red border:

![2023-11-15_09-16-39](https://github.com/freescout-helpdesk/freescout/assets/40499291/7be36eee-f465-4a05-9c8c-7b2cf0a7c45d)

**Comment by ilyakonovalenko** [comment]
> When support agent is replying his/her icon is highlighted with the red border:

It is too small and is barely visible on any modern displays.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to change it.
