### ISSUE TITLE
Run tools/update.sh as sudo or as web server user?

### ISSUE THREAD

**Issue by nooblag** [freescout-helpdesk/freescout#3511]
Hi there,

Just looking to clarify, with the [documentation](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-2-update-using-console-script), that page says to run this command on a shell to update:

```
tools/update.sh
```

But is it expected that shell script to be run as sudo, or as the web server user like the php artisan tool?

e.g.

```
sudo -u www-data /var/www/freescout/tools/update.sh`
```
or

```
sudo /var/www/freescout/tools/update.sh
```

?

Thank you.

**Comment by freescout-helpdesk** [comment]
> sudo -u www-data /var/www/freescout/tools/update.sh

**Comment by nooblag** [comment]
Thanks for that, and thanks for the update to the docs. :+1:
