### ISSUE TITLE
Jira module. Jira statuses in multiple languages

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#3512]
Hello, dear support!
Could you please add information to the Jira module description that in the "Jira Issue Resolved Status" field it is necessary to record the names of statuses in all languages that your team uses. For example, in our team, the majority of employees use English in the Jira interface, but some use the Russian interface.
In the settings of the Jira module, I specified all the statuses we needed in English. At the same time, standard Jira statuses have built-in localization and change when you select another language. As a result, the Jira module did not respond to the required statuses, since they were in a different language.

![2023-11-08_15-43-32](https://github.com/freescout-helpdesk/freescout/assets/101319104/d022fe1b-afa5-4838-894b-ca64e4aff465)

![2023-11-08_15-42-31](https://github.com/freescout-helpdesk/freescout/assets/101319104/38725da2-b2a5-49f8-8081-ca2efdf4f629)

![2023-11-08_15-45-26](https://github.com/freescout-helpdesk/freescout/assets/101319104/4910dd9f-b0cf-46a3-bfb3-fb08d4736bcc)

I spent a long time trying to understand what was the reason why the Jira module did not work. Hope this helps other users.

Best regards, Sergey.

**Comment by freescout-helpdesk** [comment]
Thanks. Information has been added in Jira Module v1.0.10
