### ISSUE TITLE
Greek translation issue el.js missing

### ISSUE THREAD

**Issue by pnkr** [freescout-helpdesk/freescout#3513]
Greek is missing so I went to Manage > Translate. From there I selected Greek (Ελληνικά) and added the language.
I translated all the strings and I published.
After that, I went to Manage > Settings and selected the language to greek and pressed save. The translations were ok but when I selected a user profile I got errors to check storage/logs.

From there I saw that the error was
[2023-11-08 11:23:47] production.ERROR: File '/var/www/public/js/flatpickr/l10n/el.js' does not exist

I went to js/flatpickr/l10n and the thing is that the app is searching for el.js but the greek js file is called gr.js

I created a newone called el.js with the contents of gr.js to solve it.

PHP version: 8.1
FreeScout version: 1.8.108
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Ok. Feel free to send the translation, we'll add it to the app.

**Comment by pnkr** [comment]
I'm checking it one more time to make sure all language strings are ok and then I will send it.
