### ISSUE TITLE
Incorrect detection of pcntl

### ISSUE THREAD

**Issue by MrCyjaneK** [freescout-helpdesk/freescout#3515]
"Basically nothing" of the core features works when I'm trying to run the 'stock' version of FreeScout (that is on every update I just go to the `/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php`

and replace 
```php
    protected function supportsAsyncSignals()
    {
        return version_compare(PHP_VERSION, '7.1.0') >= 0 &&
               extension_loaded('pcntl');
    }
```

With

```php
    protected function supportsAsyncSignals()
    {
        return false;
    }
```

Without the patch I'm getting following error:

```plain
[2023-11-03 01:21:02] production.ERROR: Call to undefined function Illuminate\Queue\pcntl_signal() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Illuminate\\Queue\\pcntl_signal() at /public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:527)
```

Little php test:
```plain
version_compare(PHP_VERSION, '7.1.0') >= 0: 1
extension_loaded('pcntl'): 1
function_exists(pcntl_signal):bool(false)
```

My guess is that adding `&& function_exists(pcntl_signal)` to the supportsAsyncSignals function would solve the issue, but I know only basics of php. Let me know if I can provide you with any extra details.

PHP version: PHP 8.2.11
FreeScout version: 1.8.108
Database: MySQL
Are you using CloudFlare: No
Cron run method: php cli command

**Comment by freescout-helpdesk** [comment]
What hosting and operating system are you using?

**Comment by MrCyjaneK** [comment]
OS: `Debian 12.2 (aarch64)` with Hestia Control Panel, stock settings.

**Comment by MrCyjaneK** [comment]
`$ php artisan freescout:check-requirements` returns all green `OK`.

I've created this script to test that behavior: 
```php
<?php
echo "version_compare(PHP_VERSION, '7.1.0') >= 0: ";
var_dump((version_compare(PHP_VERSION, '7.1.0') >= 0));
echo "extension_loaded('pcntl'):";
var_dump(extension_loaded('pcntl'));
echo "function_exists(pcntl_signal):";
var_dump(function_exists('pcntl_signal'));

```

When ran from commandline it outputs:

```plain
$ php test.php 
version_compare(PHP_VERSION, '7.1.0') >= 0: bool(true)
extension_loaded('pcntl'):bool(true)
function_exists(pcntl_signal):bool(false)
```

And on web returns the same text, with the difference of extension_loaded('pcntl') being false.
```plain
$ curl [domain]/test.php
version_compare(PHP_VERSION, '7.1.0') >= 0: bool(true)
extension_loaded('pcntl'):bool(false)
function_exists(pcntl_signal):bool(false)
```

**Comment by freescout-helpdesk** [comment]
If `pcntl` extension is available but `pcntl_signal` function does not exist it means something's wrong with your PHP. Try some other PHP version or other server.

**Comment by MrCyjaneK** [comment]
Okay, I found the issue, due to security settings those functions are in disabled_functions= in php.ini. I'm unsure if you want to take that special case into that if statement, but looks like this is what causes the issue. I'll just go with curl for cronjob as this have worked for me.

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the info. We've added `pcntl_signal()` function check to the System Status page.

**Comment by MrCyjaneK** [comment]
Any chances of warning the user that the cli option won't work there? Or could you add `function_exists('pcntl_signal')` to the `supportsAsyncSignals` - so it will detect it correctly?

**Comment by freescout-helpdesk** [comment]
Unfortunately not, `pcntl_signal` function is required for FreeScout's background jobs to work smoothly. Doing so will only cause other hard-to-debug issues when `queue-worker` freezes and you don't know why your background jobs are not processed anymore.

**Comment by MrCyjaneK** [comment]
But the code currently detects if `extension_loaded('pcntl');` and if not it works just fine (I get the drawbacks), but for this check to work in case when `pcntl_signal` is not available addinational check must be made. (Adding `function_exists('pcntl_signal')` didn't break the instance or any modules that are installed, everything works just fine).

**Comment by SecureCPU** [comment]
> Thanks for sharing the info. We've added `pcntl_signal()` function check to the System Status page.

Hey, I see the `pcntl_signal()` in the System Status Page, but it shows as "Not found"
But when I run `php -i | grep pcntl` it gives me the following results:

```
pcntl
pcntl support => enabled
```

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by SecureCPU** [comment]
awesome. thank you!
