### ISSUE TITLE
Merge multiple tickets with multi-select

### ISSUE THREAD

**Issue by sebix** [freescout-helpdesk/freescout#3516]
Currently merging tickets is only possible one-by-one within the ticket-view via the 'More actions' menu. Merging multiple tickets could be sped up significantly by selecting multiple tickets in the list view with checkboxes and then merging them at once.

PHP version: 8.2.7
FreeScout version: 1.8.99
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible.

**Comment by sebix** [comment]
Technically impossible or (financially) unfeasible?

**Comment by freescout-helpdesk** [comment]
Not very required feature: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Development-Process#new-features

**Comment by sebix** [comment]
For anyone following this issue: Release [1.8.110 ](https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.110) contains this feature according to the release notes. Haven't tested it yet.

@freescout-helpdesk Thank you for the implementation!
