### ISSUE TITLE
Allow re-sending of an email

### ISSUE THREAD

**Issue by anastis** [freescout-helpdesk/freescout#3517]
There are quite some instances when sending a reply back to the customer may fail, due to SMTP issues or other.
Some can be detected by Freescout (as in the screenshot) and some cannot.

![Screenshot 2023-11-09 at 10 48 15](https://github.com/freescout-helpdesk/freescout/assets/682312/4515cf2c-989b-49bb-baf4-bd136d299f74)

It would be beneficial to add an option to re-send a reply as the original user.
In this instance, the freescout user who replied is not me, but I'm the admin sorting the issue out.

Right now, the only ways to resolve this are:
1. Copy the previous (failed) reply, create a new reply, paste, send. This will send it using my name.
2. Tell my user to do the same thing instead of me so that the sent email will have his name.

**Comment by freescout-helpdesk** [comment]
Do you have that message in "Failed Job" section in Manage > System?
If yes, you can retry it from there.

![2023-11-09_14-19-11](https://github.com/freescout-helpdesk/freescout/assets/40499291/63e8cb2e-ad40-4a0d-a28d-0ad8113f59e0)

**Comment by anastis** [comment]
Ah, yes, it appears there.

Thank you very much.
