### ISSUE TITLE
Odd behaviour with "cc" when replying to a ticket.

### ISSUE THREAD

**Issue by JLoCascio** [freescout-helpdesk/freescout#3519]
Currently running a self hosted 1.8.84 of freescout

Have an issue in one mailbox, where when the agent uses "reply" there is a pre-populated value of the customer service email address in the "cc" field.

When you perform the same action in our 3 other mailboxes, the "cc" field is left blank.

Despite over an hour poring over every setting and config, we are unable to find where this behaviour is defined (we would like to disable it).

Can anyone explain ?

**Comment by freescout-helpdesk** [comment]
CC appears if there were CCed email or several recipients in the original email from customer.
