### ISSUE TITLE
Integration into WP

### ISSUE THREAD

**Issue by FlederFau** [freescout-helpdesk/freescout#3520]
Hello,

I am running freescout and I am quite happy with it. Right now I am looking into integrating freescout as a contact possibility for my Homepage that is realized via Wordpress. I did understand, that there is no plugin but the End-User Portal Module to do so.

I still have some questions regarding this and was hopping, that someone could enlighten me :)

I am not really interested in the widget and the possibility to click on it to open a contact form. 
I would prefer to embedded the contact form in my WP appearance. Is this possible?  

Is there a possibility to add a captcha or something else to prevent spam? (Preferable something conform with DSGVO)

Help or Advise would be highly welcome

**Comment by freescout-helpdesk** [comment]
Contact form can be embedded on the website via iframe - embedding URL can be obtained via "Open in New WIndow" link in "Wontact Form Widget" settings.

For captcha see https://freescout.net/module/extra-security/
