### ISSUE TITLE
Issue about Migrating the ticketing system from DIgital Ocean to AWS

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3521]
Hi there,  I just migrated the Freescout system from digital ocean droplet to AWS hosted by Cloudways. Everything is working fine except, the branding data disappeared and the header bar with menu doesn't work as well. I have tried to clear the cache as per this instruction https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working  
I did also implement commands such as clearn cache or php artisan storage:link etc, I got only this response below, can you please help me fix it as soon as you could? Thanks
  Could not open input file: artisan

PHP version: The latest version
FreeScout version: 
Database: MySQL 
Are you using CloudFlare:  No

**Comment by thaheem110** [comment]
Hi jeffrey! 
I have a problem with my website's menu. When I click on some menu options, the smaller choices that should show up don't appear. I've checked the code that's supposed to make them show, but it's not working right. I took some pictures to show what I mean. Can you help me figure out why these smaller options aren't showing up? Thanks a lot!

**Comment by jeffrey4680** [comment]
Hi, thaheem110, sorry to hear about that. Unfortunately, I am not a developer, I am also looking for an assistance from the Freescout developer team. ;)

**Comment by freescout-helpdesk** [comment]
All advices we can give are already listed here: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
