### ISSUE TITLE
Uploading SVGs

### ISSUE THREAD

**Issue by SushiBob** [freescout-helpdesk/freescout#3522]
Hi,

Is there a specific format to follow when uploading SVG's in the customisation section? Png's work fine, but everytime I try to upload an SVG, it returns a broken image icon. 

Thanks,
Bob

PHP version: 8.0.30
FreeScout version: 1.8.108
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Can you send a sample of the SVG image you are uploading.

**Comment by SushiBob** [comment]
![arrow-white](https://github.com/freescout-helpdesk/freescout/assets/150467791/f9b876aa-6527-4510-a5c7-21e29da12a8e)
![logo - black](https://github.com/freescout-helpdesk/freescout/assets/150467791/51609172-6a34-44f3-ad47-fd279b46d2d0)

Thank you,
Bob

**Comment by avenjamin** [comment]
@SushiBob are you aware that first SVG image (the white arrow) has an embedded PNG image instead of being a true vector graphic? Essentially its a PNG wrapped in some SVG tags.

The Sushi wp image appears to be a proper SVG image.

Do you have issues with both files?

Ben

**Comment by freescout-helpdesk** [comment]
Yes, The first image the broken SVG image. The second one is valid.

**Comment by freescout-helpdesk** [comment]
We've fixed displaying the SVG image on the Apache web server (in the `master` branch).
