### ISSUE TITLE
Add prefix to tables to be created (same-name tables already exist)

### ISSUE THREAD

**Issue by nichierichetti** [freescout-helpdesk/freescout#3523]
Goodmorning,

I just found freescout system, and it seems great!
I only have a little problem.. I already have a "users" table, and therefore the system crashes when I run the web installer...
Is there a way to put a prefix to the tables freescout wants to create or anything similar?

Thanks in advance

**Comment by avenjamin** [comment]
I don't know the answer to the prefix, but if possible I'd recommend setting up a dedicated database to avoid table conflicts.

**Comment by freescout-helpdesk** [comment]
> I don't know the answer to the prefix, but if possible I'd recommend setting up a dedicated database to avoid table conflicts.

Yes. This is the only way for now.
