### ISSUE TITLE
Emails forwarded from mailgun aren't showing

### ISSUE THREAD

**Issue by mikedov** [freescout-helpdesk/freescout#3524]
PHP version: 8.2.10
FreeScout version: 1.17.38 in Docker.
Database: MySQL
Are you using CloudFlare: No
compose.yaml:
`
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout:latest
    container_name: freescout-app
    ports:
      - 127.0.0.1:3000:80
    links:
      - freescout-db
    volumes:
      ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
      - ./data/html:/www/html
        ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
      - ./data/data:/data
        ### If you want to just keep the original source and add additional modules uncomment this line
        #- ./modules:/www/html/Modules
      - ./logs/:/www/logs
    environment:
      - CONTAINER_NAME=freescout-app
    env_file:
      - ./.env
    restart: unless-stopped

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - CONTAINER_NAME=freescout-db
    env_file:
      - ./.env
    restart: unless-stopped

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
      - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_TYPE=mariadb
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    env_file:
      - ./.env
    restart: unless-stopped
`

The mailbox settings are:
SMTP:
mail.domain.com
587
call@domain.com
password
TLS

IMAP:
Fetch from call@domain.com
IMAP
mail.domain.com
993
call@domain.com
password
TLS
INBOX folder
No validate certificate
Outgoing to SENT

Emails sent to my mailgun domain (domain.net) are forwarded to call@domain.com. This is configured in Mailgun in Receiving > Routes > catch_all() forward("call@domain.com").

The email forwarded from mailgun shows up in Roundcube and Thunderbird. The headers (that I tried to redact private info from) are:

Return-Path: <bounce+000000.000000-call=domain.com@domain.net>
Delivered-To: call@domain.com
Received: from 0.0.0.0.host.secureserver.net
    by 0.0.0.0.host.secureserver.net with LMTP
    id 
    (envelope-from <bounce+000000.000000-call=domain.com@domain.net>)
    for <call@domain.com>; Fri, 10 Nov 2023 22:16:09 +0000
Return-path: <bounce+000000.000000-call=domain.com@domain.net>
Envelope-to: call@domain.com
Delivery-date: Fri, 10 Nov 2023 22:16:09 +0000
Received: from 00000-00.mailgun.net ([0.0.0.0]:00000)
    by 0.0.0.0.host.secureserver.net with esmtps (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    (Exim 4.96.2)
    (envelope-from <bounce+000000.000000-call=domain.com@domain.net>)
    id 
    for call@domain.com;
    Fri, 10 Nov 2023 22:16:09 +0000
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=domain.net;
    q=dns/txt; s=k1; t=; x=; h=Content-Type: Subject:
    Subject: From: From: To: To: MIME-Version: Date: Message-ID: Sender;
    bh==;
    b=
X-Mailgun-Sending-Ip: 0.0.0.0
Received: from 0000000000.prod.phx3.secureserver.net
    (0000000000.prod.phx3.secureserver.net [208.109.80.53]) by 0000000000
    with SMTP id  (version=TLS1.2,
    cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256); Fri, 10 Nov 2023 22:15:25 GMT
Received: from 0000000000.prod.phx3.secureserver.net
    (0000000000.prod.phx3.secureserver.net [208.109.80.53]) by 0000000000
    with SMTP id <undefined> (version=TLS1.2,
    cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256); Fri, 10 Nov 2023 22:15:25 GMT
X-Envelope-From: mike@domain.com
X-Mailgun-Incoming: Yes
Received: from 0.0.0.0.host.secureserver.net ([0.0.0.0])
    by : HOSTING RELAY : with ESMTP
    id ; Fri, 10 Nov 2023 15:14:24 -0700
X-SECURESERVER-ACCT: 0.0.0.0
x-originating-ip: 0.0.0.0
X-CMAE-Analysis: 
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
    d=domain.com; s=default; h=Content-Type:Subject:From:To:MIME-Version:
    Date:Message-ID:Sender:Reply-To:Cc:Content-Transfer-Encoding:Content-ID:
    Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc
    :Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:
    List-Subscribe:List-Post:List-Owner:List-Archive;
Received: from [0.0.0.0] (port=00000 helo=[192.168.0.3])
    by 0.0.0.0.host.secureserver.net with esmtpsa (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    (Exim 4.96.2)
    (envelope-from <mike@domain.com>)
    id 
    for call@domain.net;
    Fri, 10 Nov 2023 22:14:24 +0000
Message-ID: <id@domain.com>
Date: Fri, 10 Nov 2023 16:14:23 -0600
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: call@domain.net
From: Mike <mike@domain.com>
Subject: Testing
Autocrypt: addr=mike@domain.com; keydata=
    mykey
Content-Type: multipart/signed; micalg=pgp-sha256;
    protocol="application/pgp-signature";
    boundary=""
X-CMAE-Envelope: 
X-From-Rewrite: unmodified, no actual sender determined from check mail permissions

I'm sorry if I took too much out of the headers; let me know what to add back and I'll fix it.

None of the logs mention any errors.  I don't see any logs mentioning anything to do with this.

No emails from any email to the mailgun address (domain.net) that were forwarded to the email that Freescout is set up with show in Freescout. Emails directly to call@domain.com all show up, and the mailgun emails show up in Roundcube.

Sorry for the confusing explanation. I hope it makes sense.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching
