### ISSUE TITLE
255 character limit for email aliases

### ISSUE THREAD

**Issue by JLoCascio** [freescout-helpdesk/freescout#3525]
From https://github.com/freescout-helpdesk/freescout/issues/2922

it seems the field can only accept 255 characters. Is there a technical reason ? Could this be extended ?

**Comment by freescout-helpdesk** [comment]
Are you talking about mailbox "Aliases" field? Currently it's max length is 128 characters.

**Comment by JLoCascio** [comment]
Yes, the aliases field (not quite sure why I doubled it :) )

We have quite a few aliases and can't fit them all in which is tripping the "cc" issue mentioned.

**Comment by freescout-helpdesk** [comment]
Max length limitation has been removed from mailbox's Aliases field in the `master` branch.
