### ISSUE TITLE
Search by customer field "Company"

### ISSUE THREAD

**Issue by myde2001** [freescout-helpdesk/freescout#3526]
Would it be possible to filter the conversations search by the customer field "Company"?

Thanks

![image](https://github.com/freescout-helpdesk/freescout/assets/93825819/b57cca09-8d90-42a0-a031-9ee7f4184e06)

**Comment by freescout-helpdesk** [comment]
Unfortunately it's not possible.

**Comment by freescout-helpdesk** [comment]
Implemented in CRM Module v1.0.40

**Comment by myde2001** [comment]
Thanks! How do I use it?

**Comment by freescout-helpdesk** [comment]
Update the module to the latest version and use Customer Fields filters in the Search.

**Comment by myde2001** [comment]
I updated the module but I don't seem to find the customer fields in the filter panel. I am new to the software sorry about my inexpertice.

**Comment by freescout-helpdesk** [comment]
![2023-11-15_14-23-58](https://github.com/freescout-helpdesk/freescout/assets/40499291/d9985115-fbaf-4f31-8045-eda41dd8de7e)

**Comment by myde2001** [comment]
Found it, I was trying with the default fields, but as soon as I added a custom field I saw it. Thanks

**Comment by foxandbutter** [comment]
This doesn't work on latest FreeScout, with CRM module and Custom fields module. There is no "Company" filed in filters.
