### ISSUE TITLE
Send Later Module not sending

### ISSUE THREAD

**Issue by Fireful0** [freescout-helpdesk/freescout#3527]
Hello!

We are using the latest version of Freescout, but ever since we have installed the Send Later module several weeks ago, we have had an issue with scheduled sending.

It works fine if we schedule sending for the same day, but if we schedule something to be sent after a day or more, we get an error "There is a problem processing outgoing mail queue".

We can clear the error by killing the processes and jobs, and then clearing the cache, but the message does not send. 

We have this tied to a Gmail box.

Any assistance is appreciated!

![7b381ecfcb67fc35bef01908a5a461ac955aa6d435e552c7e88001c16d5c3d37](https://github.com/freescout-helpdesk/freescout/assets/26516812/fe44cf9a-ab54-4551-b1d8-2feab911672e)

FreeScout version: 1.8.108

**Comment by freescout-helpdesk** [comment]
You'll need someone who can investigate it on your server.

**Comment by webpreparejordy** [comment]
Since today I've the same issue, although I'm not using the Send Later module. Using Google Workspace as well.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues#1-if-emails-are-not-sent-or-sent-with-delay

**Comment by webpreparejordy** [comment]
There seems nothing to be wrong with sending mails. For example, when I sent a test mail using FreeScout, this mail is being sent. It seems that there is a problem with the job called `App\Jobs\SendReplyToCustomer`. Already tried to clear the cache, check if the processes are running (which it seems):

```
[web2566@dhs10 ~]$ ps aux | grep queue
web2566  2509841  0.0  0.0 222528  1244 ?        S    11:15   0:00 sh -c '/opt/alt/php80/usr/bin/php' 'artisan' queue:work --queue='emails,default,a39c2753f5af3904c708186ab264b687' --sleep=5 --tries=1 --timeout=1800 > '/home/web2566/domains/webprepare.support/public_html/storage/logs/queue-jobs.log' 2>&1
web2566  2509842  0.3  0.3 333228 57960 ?        S    11:15   0:00 /opt/alt/php80/usr/bin/php artisan queue:work --queue=emails,default,a39c2753f5af3904c708186ab264b687 --sleep=5 --tries=1 --timeout=1800
web2566  2512056  0.0  0.0   9220  1104 pts/1    S+   11:17   0:00 grep --color=auto queue
```

It seems the process is starting, but after that nothing happens:

```
[web2566@dhs10 ~]$ tail -f /home/web2566/domains/webprepare.support/public_html/storage/logs/queue-jobs.log
[2023-11-15 11:15:02] Processing: App\Jobs\SendReplyToCustomer
```

This is since yesterday the case. I change my SMTP settings from Gmail to Postmark, and then everything is being processed exactly how it should be:

```
[2023-11-15 11:36:04] Processing: App\Jobs\TriggerAction
[2023-11-15 11:36:04] Processed:  App\Jobs\TriggerAction
[2023-11-15 11:36:04] Processing: App\Jobs\TriggerAction
[2023-11-15 11:36:04] Processed:  App\Jobs\TriggerAction
[2023-11-15 11:36:04] Processing: App\Jobs\TriggerAction
[2023-11-15 11:36:04] Processed:  App\Jobs\TriggerAction
[2023-11-15 11:36:04] Processing: App\Jobs\TriggerAction
[2023-11-15 11:36:05] Processed:  App\Jobs\TriggerAction
[2023-11-15 11:37:15] Processing: App\Jobs\SendReplyToCustomer
[2023-11-15 11:37:16] Processed:  App\Jobs\SendReplyToCustomer
[2023-11-15 11:37:16] Processing: App\Jobs\TriggerAction
[2023-11-15 11:37:16] Processed:  App\Jobs\TriggerAction
```

One last thing to mention, is that after I changed the SMTP credentials to Postmark, all mails which were in the queue, directly processed.

So I think there is something wrong with the connection between Google Workspace and FreeScout.

**Comment by freescout-helpdesk** [comment]
> One last thing to mention, is that after I changed the SMTP credentials to Postmark, all mails which were in the queue, directly processed.

Apparently there are some problems connecting from your server to Gmail. Try to send test email from mailbox settings.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3590#issuecomment-1851878446
