### ISSUE TITLE
"OAuth & Social Login" Module - Logout issues

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3529]
Hi,

We have set up Microsoft Azure OAuth, and it seems to be working well. However, we were hoping to enable the "Force OAuth Login" option, and this has some issues.
1) This redirects the user to the microsoft sign in flow automatically, and the user sort of loose track of where he is. If he is already signed in with Microsoft in the browser, he will also be automatically signed in. It would be beneficial with having to actually click the "sign in with microsoft" button. Although, this is a minor issue, compared to the rest.
2) When "Force OAuth Login" is enabled, and the user tries to log out, the user is immediately logged in again. Making it impossible to really log out of the service. This seems like a pretty big issue. Is there any way to circumvent this? This issue wouldn't be as apparent if (1) was resolved. Perhaps not be an issue at all.

Another related question: For single sign out to work with Microsoft Azure provider, we need to set the "Front-channel logout URL" in the azure app registration. "This is where we send a request to have the application clear the user's session data. This is required for single sign-out to work correctly."
- What URL would this be?

PHP version: 8.2.10
FreeScout version: 1.8.106
Database: PostgreSQL
Are you using CloudFlare: No

Thanks for the help!

**Comment by borgarlie** [comment]
Follow up, an additional nice option to have would be to force account selection upon login, instead of automatically logging in to last used user. This is especially important in cases where multiple people potentially would share a work computer.

Ref https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow
- `prompt=select_account` interrupts single sign-on providing account selection experience listing all the accounts either in session or any remembered account or an option to choose to use a different account altogether.

**Comment by freescout-helpdesk** [comment]
> prompt=select_account

Just add it to the "Authorization URL" in the oAuth Provider settings.

**Comment by borgarlie** [comment]
Cool. Will try the Authorization URL part.

The problem with disabling force oauth login is that you still have the regular login form there, which we do not use. Is it possible to remove that somehow, and only show the microsoft login?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
We've added "Logout URI" for oAuth Providers in OAuth & Social Login Module v1.0.15

**Comment by borgarlie** [comment]
Thanks for the quick responses!

We got the authorization URL prompt=select_account to work.

I also tested the Logout URI, by adding it to the "Front-channel logout" in the Azure App Registration, however, I could not get that to work. I am signed out of other applications immediately, but my session in freescout still remains.

Did you test this with an Azure App Registration? Could I be missing something? Or is there some way to debug it?

Thanks!

**Comment by freescout-helpdesk** [comment]
Try to open "Logout URI" manually in your browser and make sure it log you out of FreeScout.

**Comment by borgarlie** [comment]
It does, at least if I open it in the same browser. If I try it in a different browser than where I am logged in to freescout, nothing happens (but that is probably expected). I don't know exactly how this is supposed to work, but since this is supposed to log you out regardless of browser / device etc, I would assume it sends some more info in the request from microsoft.
