### ISSUE TITLE
Attached file / image patch open failed with "%" on file name.

### ISSUE THREAD

**Issue by kimsonvu** [freescout-helpdesk/freescout#3530]
Hi,

I found this problem with my Freescout. With file name include "%". It will not be possible to view / download it.

![msedge_90uiUS83o3](https://github.com/freescout-helpdesk/freescout/assets/10061253/93935916-f6b2-494a-b535-2f96747a7805)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
