### ISSUE TITLE
Settings to increase font size?

### ISSUE THREAD

**Issue by nooblag** [freescout-helpdesk/freescout#3532]
Hi there, thanks for great software!

Just wondering if there's a setting to increase the font size throughout the web interface for Freescout Users **and** also settings to change font and font size for email content?

At the moment, we have an accessibility issue for customers with the small font in emails, they're saying our messages are hard to read.

Freescout Users with large monitors also have an interest in a larger font size setting for them while they're using the portal.

Thanks

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such settings. Maybe someone can implement as a custom module.

**Comment by nooblag** [comment]
Okay, I'll try have a look at it.

With your familiarity with the code base, and to point me in the right direction, which files would I need to look at? Or is the font size hardcoded everywhere?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/emails/customer/reply_fancy.blade.php
