### ISSUE TITLE
APP_NEW_FETCHING_LIBRARY=true copies outbound mails as unread

### ISSUE THREAD

**Issue by gramakri** [freescout-helpdesk/freescout#3533]
We were testing out this flag after the conversation at https://github.com/freescout-helpdesk/freescout/issues/1412 .

When this flag is enabled, emails are copied into the "IMAP Folder To Save Outgoing Replies" folder as Unread. Because of this, when you reply to a mail in FreeScout, the reply gets picked up again by FreeScout and it changes the state of the ticket to "Active".

PHP version: 8.1
FreeScout version: 1.8.108
Database: MySQL
Are you using CloudFlare: No

The Fetch configuration is like below. INBOX is set as the copy folder:

![image](https://github.com/freescout-helpdesk/freescout/assets/82041/80ed2ef5-6fbd-4c49-9edf-a2a9c8c0a3be)

**Comment by gramakri** [comment]
It works as expected without the flag. Email responses from FreeScout are copied into INBOX as "read"

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
