### ISSUE TITLE
Problem: Email with Apple-Mail some time is blank!

### ISSUE THREAD

**Issue by kimsonvu** [freescout-helpdesk/freescout#3534]
Hi,

Email include is fetching with blank:

![msedge_adO8vDnHbh](https://github.com/freescout-helpdesk/freescout/assets/10061253/002a472a-5839-4777-8b01-8e43d70ea932)

![msedge_P75lACG5e8](https://github.com/freescout-helpdesk/freescout/assets/10061253/cc4f3c01-52b9-4a75-b0cf-e72b9f5cbf11)

**Comment by freescout-helpdesk** [comment]
Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file?

**Comment by kimsonvu** [comment]
I use docker http://ghcr.io/tiredofit/docker-freescout:latest
I don't touch any config on .env and my mail server is Zoho with IMAP protocol

**Comment by kimsonvu** [comment]
> Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file?

I also don not use APP_NEW_FETCHING_LIBRARY	option when i install docker.

**Comment by freescout-helpdesk** [comment]
Try to set `APP_NEW_FETCHING_LIBRARY=true`, clear cache and see how it goes.

**Comment by freescout-helpdesk** [comment]
What's your FreeScout version?

**Comment by kimsonvu** [comment]
Hi,

I already delete old docker and use newest 1.8.109

**Comment by kimsonvu** [comment]
Hi,

Pls open this ticket again because it is seriously problem.

**Comment by freescout-helpdesk** [comment]
Can you share EML file of the email here or send to support@freescout.net.

**Comment by freescout-helpdesk** [comment]
The email body is being successfully retrieved. 
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#some-emails-are-empty-in-freescout

**Comment by freescout-helpdesk** [comment]
The only way around for such cases is to use "Show Original" button: https://github.com/freescout-helpdesk/freescout/wiki/FAQ#some-emails-are-empty-in-freescout

**Comment by kimsonvu** [comment]
Hi,

It is "Empty" when i use "Show Original" too!
