### ISSUE TITLE
Module activation problem

### ISSUE THREAD

**Issue by eguvenc** [freescout-helpdesk/freescout#3535]
Hello, my problem is this; when I try to activate the module, freescout says "No internet connection" after second try to activate, all apps go to "! oops something went wrong page"

After deleting modules and cache folder i checked the system status and it says: 
![image](https://github.com/freescout-helpdesk/freescout/assets/482833/80df3cb1-6094-4257-a625-09cc2a7d66f8)

Then i realised that the freescout user write to cache folders as a root.
![image](https://github.com/freescout-helpdesk/freescout/assets/482833/54d2af2d-20a8-4fcc-b671-3c993ea77d6e)

I tried to solve this issue like this:
sudo useradd -g www-data freescout
sudo chown www-data:www-data /var/www/freescout

When I click to clear cache button again and i see the same issue:
**Non-writable files found/var/www/freescout/storage/framework/cache/data/96/5f/965fa3ce2995f370a94d0bdcd4f9f4935b5d4290**

For modules activation error logs says:

[2023-11-16 23:23:55] prod.ERROR: Class "Faker\Factory" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Faker\\Factory\" not found at /var/www/freescout/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:78)
[stacktrace]
#0 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(749): 

PHP version: 8.1.2
FreeScout version: 1.8.108
Database: MySQL
Are you using CloudFlare: No

What i need do ?
Thanks.

**Comment by freescout-helpdesk** [comment]
Check which user runs you cron jobs: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#91-main-cron-job--schedulerun

**Comment by eguvenc** [comment]
ok after adding cron-job user to crontab section www-data problem fixed. But still i could not activate the module.
When I click the activate button i get this error:

**"Error Occured ! Please check the internet connection !"**

After that, I refresh the page, but the application does not open and says "whoops!" goes to page again.

Here is the laravel error.log


[2023-11-17 10:46:11] prod.ERROR: Class "Faker\Factory" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Faker\\Factory\" not found at /var/www/freescout/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:78)
[stacktrace]
#0 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\\Database\\DatabaseServiceProvider->Illuminate\\Database\\{closure}()
#1 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build()
#2 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve()
#3 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make()
#4 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php(83): Illuminate\\Foundation\\Application->make()
#5 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\\Database\\DatabaseServiceProvider->Illuminate\\Database\\{closure}()
#6 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build()
#7 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve()
#8 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make()
#9 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Illuminate\\Foundation\\Application->make()
#10 /var/www/freescout/Modules/EndUserPortal/Providers/EndUserPortalServiceProvider.php(401): app()
#11 /var/www/freescout/Modules/EndUserPortal/Providers/EndUserPortalServiceProvider.php(43): Modules\\EndUserPortal\\Providers\\EndUserPortalServiceProvider->registerFactories()
#12 [internal function]: Modules\\EndUserPortal\\Providers\\EndUserPortalServiceProvider->boot()
#13 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#14 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#17 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call()
#18 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider()
#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#20 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk()
#21 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#22 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#23 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#24 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#25 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#26 /var/www/freescout/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle()
#27 {main}

**Comment by eguvenc** [comment]
I saw a lots of dependency problems especially which is regarding doctrine/annotations package and maybe others does not support the php 8.2 for current freescout version. 

I created another php 7.4 installation on my local computer. Then it worked very well.
So i guess freescout is not ready for php 8 versions yet.

**Comment by freescout-helpdesk** [comment]
What was your exact PHP 8.2.x version?

**Comment by eguvenc** [comment]
PHP 8.2.12

**Comment by freescout-helpdesk** [comment]
We've tested FreeScout on PHP 8.2.12 and works fine.

![2023-11-19_09-15-23](https://github.com/freescout-helpdesk/freescout/assets/40499291/ecb10746-311a-468d-9f8d-3162aa3f0a4a)

Apparently something went wrong during the installation process.

**Comment by eguvenc** [comment]
Hi, did you test the module installation and activating the modules ?

19 Kas 2023 Paz 09:16 tarihinde FreeScout ***@***.***> şunu
yazdı:
