### ISSUE TITLE
Bug: filters are not applied on selection

### ISSUE THREAD

**Issue by vigleikn** [freescout-helpdesk/freescout#3536]
Hi, the filters in the search page are not applied until you hit search, which is strange since dropdown filters usually work immediately for populated pages. It would be great to have a fix for this issue whenever possible.

![kap2](https://github.com/freescout-helpdesk/freescout/assets/151235360/a992a46e-d223-4e45-ac51-e6bef9857b36)

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to change it.
