### ISSUE TITLE
allow to define email domain to customer

### ISSUE THREAD

**Issue by wejrcze** [freescout-helpdesk/freescout#3537]
Hello,
do you plan or is a way to set a email domain at customer, so when new email arrives it will be assigned to that customer?

For example:

Customer A - domain @customerweb.com

so any email which contains @customerweb.com will go to Customer A

Thank you in advance.

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/workflows/

**Comment by wejrcze** [comment]
Hello,
we just bought Workflows, but there is no action which i can use to set customer to conversation :(.
![image](https://github.com/freescout-helpdesk/freescout/assets/31951593/501c02cc-a787-4812-95ce-90e14487c43b)

btw downside of this solution i have to create manualy workflow for each customer, i was looking for something more automated, what i will set at customer.

So solution is to try create an custom module for this.

Thank you anyway
