### ISSUE TITLE
LDAP group filter does not work with AD, user is on group and get disabled

### ISSUE THREAD

**Issue by simonitfi** [freescout-helpdesk/freescout#3539]
Hello,

there is issue on LDAP group filter.

We have set fillter as "(&(memberOf=CN=some_group,OU=Groups,OU=Some,DC=example,DC=com))" and we have user that belongs exactly on group with DN: "CN=some_group,OU=Groups,OU=Some,DC=example,DC=com" and if we sync permissions the user gets disabled on freescout.

LDAP Integration Version: 1.0.33

PHP version: 8.2.9
FreeScout version: 1.8.101
Database: PostgreSQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
The only way to figure it out is to debug it on your server.
