### ISSUE TITLE
workflows module /  workflow doesn't work

### ISSUE THREAD

**Issue by epp289** [freescout-helpdesk/freescout#3540]
Hello. My workflow (using workflows module) doesn't work. See the attached screenshots.  
All the conditions have OR between them.
i want it to run based on the sender email address, so i have set 
"Customer Email" / "Contains" / "info@asdasdas.com" etc

i have tried instead of the "Contains" the "Starts with" with no luck
any idea?

i have another workflow that is based on the "Subject" of the email and it works fine

![nZhB2283SP](https://github.com/freescout-helpdesk/freescout/assets/75975706/c2ea6f6c-637c-45ff-92aa-3813baf3360e)
![F5xJszXFAp](https://github.com/freescout-helpdesk/freescout/assets/75975706/da47da96-2280-49f2-bab1-4d26dbc3b9b6)
![VpDwumefak](https://github.com/freescout-helpdesk/freescout/assets/75975706/6aca94e2-330e-47c9-9c69-cb066dca238e)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Try to start with one condition and make sure it works.
