### ISSUE TITLE
Not fetching Emails

### ISSUE THREAD

**Issue by socialistmia** [freescout-helpdesk/freescout#3542]
Hello Friends, 

I cannot seem to get this to work on cPanel. I have scheduled a cron job 

*	*	*	*	*	php /home/cnjdsahelpdesk/public_html/artisan schedule:run >> /dev/null 2>&1

The application is not fetching emails and in my settings I have it set to fetch every minute and still nothing. I cannot seem to figure out anything in the logs either.

Any help would be greatly appreciated. I have a few modules working fine but just the fetching is not. 

PHP version:  8.2 
FreeScout version: 1.8.109  
Database: MySQL 
Are you using CloudFlare: No

**Comment by socialistmia** [comment]
App Version | 1.8.109
-- | --
Nov 22, 2023 21:38
America/New_York (GMT-0500)
HTTPS
Mysql (10.6.16-MariaDB)
LiteSpeed
PHP 8.2.11
512M / 512M

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching

**Comment by socialistmia** [comment]
I have done that.... still no luck.
