### ISSUE TITLE
Show addresses and telephone numbers as link

### ISSUE THREAD

**Issue by cruunnerr** [freescout-helpdesk/freescout#3544]
Hello everybody,

is there a way to show addresses and telephone numbers as a link.

If I open a ticket with my mobile phone for example I want to be able to directly press on an address to open google maps or directly press on a telephone number to set up a call.

Is this possible?

At the moment only email addresses and links will be detected.

**Comment by freescout-helpdesk** [comment]
URLs are already converted into links. Send an HTML of your message where URLs have not been converted into links.

**Comment by cruunnerr** [comment]
I don't have problems with URLs.

I want telephone numbers and addresses to be converted.


For example this is the content of a ticket:

`<p><br>
Tel.Number: 0123 / 456789<br>
<br>
_________________________________________<br>

Customer Name<br>
Customer Street 11<br>
45454 City<br>
_________________________________________<br>

_________________________________________<br>
 • email: <a target="_blank" href="mailto:test@test">test@test.de</a><br>
<br>

</p>`


The email address is automatically converted to an email-link.

But I want freescout to convert the Tel.Number and Customer address automatically as well.

**Comment by freescout-helpdesk** [comment]
Unfortunately it's impossible.
