### ISSUE TITLE
Customizable User Notification Email Templates

### ISSUE THREAD

**Issue by AndreasRiedel95** [freescout-helpdesk/freescout#3545]
Hi there,

I'm curious if there are any plans in consideration to create customizable notification email templates specifically tailored for users within the platform. At present, when adjusting the Email Signature within a mailbox, I've noticed that as the initiator of a conversation, I receive notification emails solely displaying this Email Signature. Meanwhile, all other users receive the default Email Template generated by freescout. 

Your insights would be greatly appreciated. Thank you.

**Comment by freescout-helpdesk** [comment]
> I receive notification emails solely displaying this Email Signature

Can you provide a screenshot to understand it better.

**Comment by AndreasRiedel95** [comment]
Sorry for the late response. 

I create conversations over API. All users assigned to the mailbox and which has notifications enabled receive such a notification per mail: 
<img width="987" alt="Bildschirmfoto 2023-11-30 um 11 56 04" src="https://github.com/freescout-helpdesk/freescout/assets/43568086/8aa6ccda-d31b-4d6c-8d96-296ac6c3b5ca">

As the creator of this conversation, I get the email signature as notification email, that can be defined in each mailbox. However, the question is more about whether you consider to implement an option to customize the above email notification template for all users. 

Thank you.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature for now.
