### ISSUE TITLE
Bug: Mailbox Permissions - Manually Set Checkboxes Not Clearing Upon 'Select None' Action

### ISSUE THREAD

**Issue by AndreasRiedel95** [freescout-helpdesk/freescout#3546]
In the Mailboxes > Permissions section, there's an observed behavior where manually selected checkboxes persist even after using the 'Select None' option. 

**Steps to Reproduce:**
Navigate to Mailboxes > Permissions.
Manually select checkboxes for various permissions.
Click on the 'Select None' button.
Expected Behavior:
The 'Select None' action should clear all previously manually selected checkboxes, resetting permissions to an unchecked state.

**Observed Behavior:**
After clicking 'Select None,' the manually set checkboxes persist, not reverting to an unchecked state as expected.

Freescout Version: 1.8.98
PHP: 8.2.10

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by GTLSlb** [comment]
hello i create a user with none permissions (readonly user) to just access knowledge base but after that he can still access manage dropdown box how i can fix it
