### ISSUE TITLE
Whoops, looks like something went wrong — check logs in /storage/logs

### ISSUE THREAD

**Issue by chrish789** [freescout-helpdesk/freescout#3547]
Hi

I am trying to get freescout to work , i am using the docker image.

When i try and go to the url, i get the message 'Whoops, looks like something went wrong — check logs in /storage/logs'

I have checked the log files and see this message

production.ERROR: Error: File '/www/html/public/storage/js/vars.js' does not exist; File: /www/html/overrides/devfactory/minify/src/Providers/BaseProvider.php (124)>

production.ERROR: Error: File '/www/html/public/storage/js/vars.js' does not exist; File: /www/html/overrides/devfactory/minify/src/Providers/BaseProvider.php (124)>

Any ideas what is wrong or how to fix?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue
