### ISSUE TITLE
How can i enter translated pages ?

### ISSUE THREAD

**Issue by eguvenc** [freescout-helpdesk/freescout#3548]
I added all translations from admin panel but how freescout will understand it is ?

I tried like this:
https://support.oloma.dev/help/0934894884875/tr
but it does not work.

Help please.

**Comment by eguvenc** [comment]
No I am talking about end user portal.  Is there a parameter that will trigger to language selection?

![end-user-portal](https://github.com/freescout-helpdesk/freescout/assets/482833/f0ca4593-2f46-40a8-a745-297046211eb6)

**Comment by freescout-helpdesk** [comment]
See "Language" section: https://freescout.net/module/end-user-portal/

**Comment by eguvenc** [comment]
"If you are logged in as a FreeScout user End-User Portal uses user’s language. Otherwise it uses language from Manage > Settings."

I mean about not logged user.  Not logged user always see system default language.

**Comment by freescout-helpdesk** [comment]
> Not logged user always see system default language.

Yes, this is how it works.

**Comment by eguvenc** [comment]
Yes, but I think it should be changed in the new version. Otherwise, public users will never see translated pages. This means that the app does not support 100% translation.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/
