### ISSUE TITLE
Ticket ownership switched to email CC user

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-helpdesk/freescout#3551]
When someone is CC'd on a ticket and that CC'd individual replies to the ticket, the ticket switches ownership to the CC'd person. This has resulted in customers losing visibility of the ticket in their accounts.

In the screenshot, the initial ticket was created from the **"Jahidul Hassan Mojumder"** account and kept the **"Tanjir Al Mamun"** account in the CC. After replying from the CC'd account, the ticket ownership switched to the CC'd account.

**Screenshot:** https://snipboard.io/KfHFAw.jpg

**Comment by ThomasBergmann123456** [comment]
I can absolutly confirm this "bug" or "feature" and i'm missing an option: if customer is set on a ticket, don't update it, regardless of who answers to the ticket.
it's really part of my daily work to reassign tickets manually because the customer is changed due to CC issues or someone else replies to the ticket no..

**Comment by ThomasBergmann123456** [comment]
@freescout-helpdesk Thanks a lot. What will happen when a new "customer" (not in cc) answers to an existing ticket? In my case we get replies from a second external helpdesk (defined the mail-adress in freescout as user/agent) and the customer is changed.

So in my case, I want to keep the initial customer under any circumstances, but thinking about it - maybe it's a bug, that the system doesn't recognize the mail-adress as user/agent and thinks it's a new customer?

**Comment by freescout-helpdesk** [comment]
Initial customer will be preserved.
