### ISSUE TITLE
How to send code block (HTML, CSS) etc in reply

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3553]
Hi @freescout-helpdesk Team,

Sometimes we have to send some css or html code to our customers, how can we send them inside reply, as if we are trying normal tags: either they are converted to HTML or hidden.

Also wrapping it inside `<code></code>` doesnot work.

<img width="725" alt="Screenshot 2023-11-29 at 9 51 18 PM" src="https://github.com/freescout-helpdesk/freescout/assets/118246547/26761b09-c040-48fc-8837-049f7c3a4a83">

Thanks!

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/extended-editor/
