### ISSUE TITLE
Error: The payload is invalid

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3554]
Hi @freescout-helpdesk Team,

When i check App Logs, i see this message always:

```
Error: The payload is invalid.; File: /vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php (191)
```

My FreeScout version is : 1.8.108

Can you please suggest how to fix it?

Thanks!

**Comment by freescout-helpdesk** [comment]
Try to send full error message.
