### ISSUE TITLE
End-User Portal Consent checkbox

### ISSUE THREAD

**Issue by wejrcze** [freescout-helpdesk/freescout#3555]
Dear freescout,
is there a reason that when i check Consent in portal settings, that everyone have to check it in every response after logging in?

It's good to have it when im creating new ticket but not at every response, are you planning to add option to settings?

Thank you very much! :)
![image](https://github.com/freescout-helpdesk/freescout/assets/31951593/6677fc6f-1088-416b-812a-8e5e52a38ea5)

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
