### ISSUE TITLE
Global inbox: Is it a way to HIDE all tickets for a user, except the tickets I have assigned to the user?

### ISSUE THREAD

**Issue by Netthandel** [freescout-helpdesk/freescout#3557]
I searched, and found [this thread about stopping access](https://github.com/freescout-helpdesk/freescout/issues/701) to tickets the user isn't assigned to. 

So I tried this:

`APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS=4`

In the .env file. 

All the tickets are still showing for the user, but he can't access them. 

EDIT: This is only in the Global inbox. In the other inboxes all tickets are hidden, except those assigned. 

But I would like the user to not see any tickets at all, except the specific tickets he is assignes to. 

Is it a way to do this that I have missed?

I have bough almost all modules today, and have been spending pretty much time in this very well thought out software, but haven't found this function yet.

**Comment by Netthandel** [comment]
Actually, it's only in the GLOBAL inbox this is a problem. So it's likely a bug. 

In the other inboxes the tickets that are not assigned to this user is actually hidden.

**Comment by freescout-helpdesk** [comment]
Fixed in Global Mailbox Module v1.0.13

**Comment by Netthandel** [comment]
Thank you! I appreciate this!
