### ISSUE TITLE
Help with chat (create conversations)

### ISSUE THREAD

**Issue by oclick** [freescout-helpdesk/freescout#3558]
Hi,

I am trying to integrate an automated chatbot tool, which we already have, with Freescout’s chat. The user can choose to “escalate to a human”. In this case I want to transfer (visually and historically if possible) to your chat widget. I am having trouble with that. Here is what I already do:

1) I get the chat history from the chatbot and call https://myfreescout.org/api/conversations . It works. It gives me an ID which seems to be the “conversation id” (exemple: 64), which I see listed in Frescout’s web UI. Perfect.

2) I transition my iframe inner URL in my chatbot to your iframe’s inner URL, [https://myfreescout.org/chat/widget/form/465576049?color=0068bd&position=br&id=465576049&visitor_name={user}&visitor_email={email}](https://myfreescout.org/chat/widget/form/465576049?color=0068bd&position=br&id=465576049&visitor_name=%7Buser%7D&visitor_email=%7Bemail%7D)
This is non-ideal, of course, because some of the features like the collapse button do not work.
Here I am looking for a way to pass the user name, email and “conversation id” if possible. Can I?

3) Currently I end up with a visual transition BUT the conversation from this point on will NOT go into the one I created via REST (the “64” I mentioned above). The visual representation is not connected to the historic one which I populated via REST..

    So, I guess my question is:

   What is the oficial way to transition an existing chat which started in another tool into a Freescout’s chat and continue in there, as smooth as possible?

   I looked at the Freescout PHP code and it does not seem that you can take these IDs in query parameters. You use “local storage”, which makes it awkward to pass these values in. I thought of some creative possibilities:

a) Create a custom PHP file in the Freescout tree which takes these parameters as queryParams and injects then into the Local Storage before redirecting to the final URL. I would redirect into this one first, which would do the trick before the final transition.

      or

b) Hack your existing chat code to make it take values from queryParams. I would be forking the code, non ideal.

      or

c) email support to see if there is an easier, more correct approach :-)

This message is an attempt at (c) above :-) Looking forward to some tips. 

Thanks in advance for any help. 
Cheers,
Erick

**Comment by freescout-helpdesk** [comment]
> What is the oficial way to transition an existing chat which started in another tool into a Freescout’s chat and continue in there, as smooth as possible?

Unfortunately there is no official way. You'll need to invent some workaround, edit module code if needed.
