### ISSUE TITLE
There is a problem processing outgoing mail queue..

### ISSUE THREAD

**Issue by Aventerica89** [freescout-helpdesk/freescout#3559]
PHP version: 8.0
FreeScout version: 1.8.109
Database: MySQL 
Are you using CloudFlare: Yes

Hello! I've just installed FreeScout and everything appears to be working, but I am getting this message in my inboxes:

There is a problem processing outgoing mail queue — an admin should check [System Status](https://support.jbmdcreations.dev/system/status#cron) and [Recommendations](https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs)

It was not there originally. Emails are sent and received properly.

Everything is good in System Check except for this:
![CleanShot 2023-11-30 at 13 36 12@2x](https://github.com/freescout-helpdesk/freescout/assets/152549279/54445d2e-274d-4b1c-85e4-13b45735eb1d)

I have no idea how to resolve that, if that's a core issue.

Then in the logs, the only errors I see are the Laravel logs:

Call to undefined function Illuminate\Queue\pcntl_async_signals() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Illuminate\\Queue\\pcntl_async_signals() at /home/jbmd/webapps/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:525)

I could use some help!

Thank you!

**Comment by freescout-helpdesk** [comment]
Added `pcntl` extension to your console PHP.

**Comment by Aventerica89** [comment]
> Added `pcntl` extension to your console PHP.

I am still seeing the same errors and absence of pcntl. Is there anything I need to do on my end to trigger it?

**Comment by freescout-helpdesk** [comment]
No. just to properly install it into your console php.ini
