### ISSUE TITLE
Email Connection Settings and Email Delete functionality.

### ISSUE THREAD

**Issue by pnkr** [freescout-helpdesk/freescout#3560]
PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version: 1.8.109
Database: Mysql (5.5.5-10.2.43-MariaDB-1:10.2.43+maria~bionic)
Are you using CloudFlare:  No

Even though I select POP3 Method, there is still a field called IMAP Folders in the form with the default "INBOX" as a folder name selected. Is it something I must do or check? Because I am having an issue that my Emails, even though I pressed delete message are not deleted from the server. I have the GDPR Module enabled and I have set it to remove messages from server.
![Email Connection setting](https://github.com/freescout-helpdesk/freescout/assets/4727788/99efd5b4-d701-4f69-8dc0-40f1dfc1131f)

**Comment by freescout-helpdesk** [comment]
Add `APP_NEW_FETCHING_LIBRARY=true` parameter to the .env file and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache).

Also keep in mind that email is deleted from the mail server only when you are deleting the conversation forever from "Deleted" folder.
