### ISSUE TITLE
Satisfaction Rating module with Chat Module {%ratings.add%} issue

### ISSUE THREAD

**Issue by pnkr** [freescout-helpdesk/freescout#3561]
PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version:  1.8.109
Database: MySQL 
Are you using CloudFlare:  No

When I add {%ratings.add%} to a chat (As an agent) it does not work as a shortcode. It works only in the email conversation. Shoudn't work ?

**Comment by freescout-helpdesk** [comment]
> It works only in the email conversation.

Yes.
