### ISSUE TITLE
Some Emails are not sent to users

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3562]
Hi @freescout-helpdesk 

We've noticed that some emails are not being sent to users. The Queue worker is running, and we've confirmed its status on the system status page; it's already running.

Just to clarify, we are using Laravel Horizon + Redis as the Queue Driver.

This issue doesn't occur for all outgoing replies, only for some of them.

<img width="913" alt="Screenshot 2023-12-01 at 2 34 27 PM" src="https://github.com/freescout-helpdesk/freescout/assets/118246547/48d1b723-76cb-40e4-ade6-30664368f2c8">

Thank You.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues
