### ISSUE TITLE
Possibility to edit folders shown in the home panel

### ISSUE THREAD

**Issue by myde2001** [freescout-helpdesk/freescout#3563]
Hi, would it be possible to add a feature to edit the folders shown in the home panel page? For example, to show folders from the "Custom Folders" module or the "All" folder from the "Inbox" module. Thanks.

![image](https://github.com/freescout-helpdesk/freescout/assets/93825819/0e569046-2e8f-4995-a457-3825ada12782)

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to add this feature.
