### ISSUE TITLE
Slow Performance

### ISSUE THREAD

**Issue by VacationTeam** [freescout-helpdesk/freescout#3564]
PHP version: 8.1.25
FreeScout version: 1.8.109  
Database: MySQL 
Are you using CloudFlare: Yes 

Have been experiencing performance issues (slow response time) from database on my server for a week now.
After lots of digging, it seems scout is getting backed up.
Best I can figure is a query that is running over every threads row.
"select * from `threads` where `threads`.`conversation_id` = 67121 and `threads`.`conversation_id` is not null and `type` in (1, 2) and `state` = 2 order by `created_at` desc limit 1"

Everytime I refresh
[show full processlist](https://mariadb.com/kb/en/library/show-processlist/)
I see this command running, (incremental conversations_id).  It takes a long time (800+ seconds).
If I kill the ID, it just replaces it with another and picks up where it left off.

All other queries are waiting until this process is finished
When it finishes, it starts all over again, from the lowest number conversation_id.

Can you give me some insight to what is going on?

**Comment by freescout-helpdesk** [comment]
Are you using Reports or Workflows modules? Try to disable them one-by-one and see how it goes.

**Comment by VacationTeam** [comment]
Thank you for quick follow up.
We are
Modules installed
Custom Folders
Inbox
@ Mentions
Sent Folder
Tags
Workflows

Ill go ahead and disable 1 by 1 and update.

**Comment by VacationTeam** [comment]
Disabled all extentsions,
That query still regenerated.
I cleared cache, and it still continued.
Insert query gets delayed and just hangs for now its at 267 seconds
![image](https://github.com/freescout-helpdesk/freescout/assets/90206057/9fb35af4-7d7a-46e9-9f2f-086c92554f64)

**Comment by VacationTeam** [comment]
Updating to show the pile up of the queries
![image](https://github.com/freescout-helpdesk/freescout/assets/90206057/e88ca5ff-eff8-436c-b35f-47f16f53ed02)

**Comment by freescout-helpdesk** [comment]
All we can suggest is to move to a more performant server.

**Comment by VacationTeam** [comment]
Hi @freescout-helpdesk 
Thank you for the follow up.
I have moved to a new server by itself to diagnose.
1) the previous and current server both have 4gb of memory and 2 processors running.  I will look for the spec's recommended for FreeScout.
2) after migration, attachments are not opening.
PDF says Failed to open, PNG attachments just show blank when clicked on.
So the files exist, but can render or maybe a permissions issue?
Any guidance?

**Comment by VacationTeam** [comment]
I should learn my lesson to look at logs,
Anyway here is what in the logs
Call to undefined function Illuminate\Filesystem\fpassthru() {"userId":1,"email":"USER@EMAIL.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Illuminate\\Filesystem\\fpassthru() at /home/***/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:136)

**Comment by VacationTeam** [comment]
Ok so Fpassthru was not turned on for somereason, even though scout reported OK.

I have fixed and refreshed.
All services are OK expect for pcntl_signal (PHP)	Not found 
Working on figuring that out now

**Comment by VacationTeam** [comment]
On a new server box
with 4GB ram and 2 cores, we are still having some performance issues
Will close this for now as we work through and update with future findings.
