### ISSUE TITLE
Module "Teams" does not allow a user to see the tickets he is assigned to through a team, when restricted with "APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS="

### ISSUE THREAD

**Issue by Netthandel** [freescout-helpdesk/freescout#3568]
I have installed the module "Teams v 1.0.16" and I do love the functionality. 

However, when a user is restricted to only access tickets he is assigned to, he can't access the tickets he is assigned to via "Teams". 

**It works like this:**

I have restricted him by updating the .env file with this:

`APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS=4`

**This happens:** 

When _he alone is assigned_ to a ticket, he can both see it and reply. 

When he is _assigned through a "team"_ via Teams, he can see the listing in the inbox, but he _can not view or reply_. He get's a "Access denied" message. 

**Is this more a lacking (not yet made) functionality of APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS?**

I assume this is not quite a bug, but a functionality that isn't added yet to "Teams", or more so to the APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS function that actually reads the user's "rights".

Would be very helpful if the restrictions set in the .env file worked well with assigning multiple people to a ticket via the Teams module.

So maybe the function for APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS need an update to look for both single and teams assignments?

Thank you again for a great software. This makes my day so much easier. 🙂

**Comment by freescout-helpdesk** [comment]
Fixed in Teams Module v1.0.17
