### ISSUE TITLE
Possibility to add pronouns within profile

### ISSUE THREAD

**Issue by im-fabian** [freescout-helpdesk/freescout#3572]
It would be wonderful if there was the possibility to add pronouns within the freescout profile. 

Those could then be used within the signature so that recipients know how to address the person correctly they're having a conversation with.

On why it is important to communicate pronouns and which there are: https://www.gsrc.princeton.edu/understanding-pronoun-use

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/user-fields/
