### ISSUE TITLE
Show subject texts in a single line instead of multiples

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-helpdesk/freescout#3573]
At times, users may opt not to invest additional effort in crafting a ticket subject and simply copy-paste the description, resulting in an untidy appearance in the ticket inbox.

Enhancing the user experience could involve displaying the subject in a single line, with any overflowing text hidden, to maintain a cleaner and more organized appearance in the ticket inbox.

Screenshot of the issue: https://snipboard.io/12oS8a.jpg

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to change it.
