### ISSUE TITLE
Laravel Horizon Support

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3574]
Hi @freescout-helpdesk 

Will there be any official support for "Laravel Horizon"

Although I have configured it using "Redis" and "Laravel Horizon" but everytime i update freescout, i have to do everything from scratch again. 

Are you planning to include support for same?

Also need to update Kernel.php and make it compatible with "Laravel Hoizon"

Thanks!

**Comment by freescout-helpdesk** [comment]
Feel free to create a pull request if you can. We'll merge it if it will not bring too much code and issues.

**Comment by donnyxray** [comment]
@mahavirn please share the changes you make.

If a pull request is not feasible, you can probably automate the changes using composer's ```post-update-cmd```.

**Comment by mahavirn** [comment]
Hi @donnyxray let me know if you still need it....
