### ISSUE TITLE
Feature Request: MYSQL_ATTR_SSL_CERT attribute support in database.php 

### ISSUE THREAD

**Issue by crixle** [freescout-helpdesk/freescout#3575]
Required for Azure Web App deployments of the tiredofit:docker-freescout image.

For context, using an Azure MySQL server which requires SSL by default and provides a .pem for it.
In similar programs like SnipeIT that utilize Laravel, they support the attribute which allows for successful deployments on Azure without any security risks.

**Comment by freescout-helpdesk** [comment]
Feel free to create a pull request if you can.
