### ISSUE TITLE
iOS app not longer available in app store

### ISSUE THREAD

**Issue by zimme** [freescout-helpdesk/freescout#3576]
The iOS app seems to be unavailable in the app store (at least in the Swedish region).

Have anything changed recently? Is there some active review process by Apple? Have the app been removed in some regions?

Does anyone else have the same issue?

**Comment by VacationTeam** [comment]
I am not seeing it in the USA IOS Appstore.
The app is still on my device and working.

Thought from what I can tell, the freescout app really just feels like a "browser" viewing the mobile page of the scout install.
So you might just want to link your scout install on from your mobile browser.

**Comment by DavidAnderson684** [comment]
The apps are just thin wrappers round a web view: https://github.com/freescout-helpdesk/freescout/issues/1304#issuecomment-877294297

**Comment by zimme** [comment]
I beleive it might include some mobile notification support stuff, becuase you can set notification settings for mail, browser or mobile.

**Comment by Netthandel** [comment]
I (my colleague) can't access the iOS app in the app store. Is it officially removed, or is it limited by someone?

I would like him and others to get mobile-notifications and also easily read and reply to tickets I assign to him (and them). He is always on the road, so a good mobile app was one of the reasons I chose Freescout. 

Myself I use Android, and it works very well there.

**Comment by freescout-helpdesk** [comment]
The app is available now: https://freescout.net/ios-app/
