### ISSUE TITLE
Coud not disable spam filter learning Algorithm.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3577]
I'm using spam filter and disable Spam-Filtering Algorithm & Learning. and clear Learning Memory.
but the filter still working( and seems still learning. learnig memory increased)
I just want to learn sender that user select it as spam.(like black list of sender)

**Comment by freescout-helpdesk** [comment]
Reset learning memory and disable "Filter Using Spam-Filtering Altorithm & Learning" checkbox.

**Comment by totake0224** [comment]
Hello.
I already did that.

**Comment by freescout-helpdesk** [comment]
Also keep in mind that when you disable "Filter Using Spam-Filtering Altorithm & Learning" checkbox it stops automatic emails filtering but it does not stop the process of learning.

**Comment by totake0224** [comment]
Thank you. I will try to kill them.
