### ISSUE TITLE
Messages truncated in Thunderbird when replying by email to FreeScout email notification

### ISSUE THREAD

**Issue by bcampano** [freescout-helpdesk/freescout#3580]
PHP version: PHP 7.4.33
FreeScout version: 1.8.110
Database: MySQL
Are you using CloudFlare: No

When sending or responding to FreeScout tickets from Thunderbird (or perhaps other email clients) which include quoted text (prefixed with '>') or indented (prefixed with '    */' or '*/T/**/') using standard email formatting tools are truncated at the first occurrence.

It is very difficult to ensure none of this standard formatting is used or we do not simply respond to or quote previous emails as these all get truncated by FreeScout.

Is there a configuration change we can use to avoid this truncation?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#why-does-show-original-window-shows-truncated-message-without-previous-history

**Comment by bcampano** [comment]
Here are the steps to reproduce the issue shown two ways:

1. Customer sends email from Thunderbird (does not seem to matter what versions but done here using V115.4)

<img width="563" alt="1" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/8f2ec327-cadf-4e84-8986-411e9a8050d4">


2. FreeScout notification message appears fine when sent out via email with indents and quoted text

<img width="689" alt="2" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/70f2651c-abe6-4d12-a3a1-5b204d8df02d">


3. In this case, (because its easier) we use the same submission account to respond as the one from which originally sent the test ticket.

<img width="756" alt="3" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/0b737e85-5ce8-4117-8766-7f017be64f19">


4. Next email notification to the submitted ticket is truncated at the first occurrence of an indentation or quoted text.

<img width="719" alt="4" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/0f9ce31a-2122-48ab-b076-b1e5c56400a7">


5. And also (for the complete picture) if we respond to the original email from another account configured for notifications in FreeScout the email directly back to the original submitter is truncated the same way:

<img width="718" alt="5" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/506a699d-977f-4fa2-affa-21374f46dd5a">


6. The notification email sent from FreeScout is also truncated the same way.

<img width="718" alt="6" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/ec861b30-ce32-4ea2-948e-d2ba3320bd51">

Hope this helps!!!

**Comment by freescout-helpdesk** [comment]
How does the message from step 4 look like in FreeScout?

**Comment by bcampano** [comment]
Its truncated as well as can be seen in the following image:

<img width="718" alt="7" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/8a690624-61da-472c-9f3b-e1587381cf73">

**Comment by freescout-helpdesk** [comment]
Can you reproduce this issue by replying from Gmail interface?

**Comment by bcampano** [comment]
Can't easily from Gmail but I was able to test from Apple Mail (standard mail client) and the same truncation occurred! Here's the original message in Apple Mail:

<img width="531" alt="8" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/d5d80f32-7fe6-4a0c-8f92-b5227485a8c1">

And what appears in FreeScout:

<img width="585" alt="9" src="https://github.com/freescout-helpdesk/freescout/assets/21370132/1a9d7336-1139-4fad-bf52-d192293dbc8f">

**Comment by freescout-helpdesk** [comment]
We'll need HTML code (or .EML file) of the reply email sent from Thunderbird or Apple Mail on Step 3:

<img width="531" alt="289388576-d5d80f32-7fe6-4a0c-8f92-b5227485a8c1" src="https://github.com/freescout-helpdesk/freescout/assets/40499291/f8fbef5f-7399-4954-ac68-50d4f4edfaff">

**Comment by bcampano** [comment]
Here is the HTML extracted from both Apple and Thunderbird. Hope it helps!!! Couldn't attach inline here so attached as a zip.

[html_source.zip](https://github.com/freescout-helpdesk/freescout/files/13637412/html_source.zip)

**Comment by bcampano** [comment]
Awesome!!! Great to (hopefully!) help make this great product even better!!!

**Comment by freescout-helpdesk** [comment]
If you are able try to test updates from `master` branch on your end.

**Comment by bcampano** [comment]
Unfortunately, this bug has reappeared in a recent upgrade of FreeScout. Same conditions and same ease to recreate. Perhaps the fix was lost in one of the builds?

We are running 1.8.140 and it is exhibiting the same issues as reported above.

Please advise if you need me to perform any additional testing.
