### ISSUE TITLE
Error with reciving and sending emails

### ISSUE THREAD

**Issue by smiell** [freescout-helpdesk/freescout#3581]
Hi, I ran freescout in a docker container. I was able to run the application and complete the installation. Unfortunately, when sending and receiving email messages, I receive the following log messages:

`Connection could not be established with host mail0.small.pl [Connection timed out #110]; File: /var/www/html/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php (271)`

(hosted mail server, 100% operational)

Even though when adding e-mail boxes to freescout, the connection test was performed correctly... Unfortunately, I was unable to send a test e-mail from my inbox.

Should I open port 25 and 143 for SMTP communication from my container? I am asking for help, because when I launched another listmonk application to handle newsletters, it was not necessary to open additional ports apart from the port to the web panel.?

I built the freescout application using the following Dockerfile container:
```
FROM php:8.0-apache

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    libzip-dev \
    zip \
    libc-client-dev \
    libkrb5-dev \
    libpng-dev

# Enable mod_rewrite
RUN a2enmod rewrite

# Install PHP extensions
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
    docker-php-ext-install pdo_mysql zip imap

RUN docker-php-ext-install gd

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Copy the application code
COPY . /var/www/html

# Set the working directory
WORKDIR /var/www/html

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install project dependencies
RUN composer install --ignore-platform-reqs

# Set permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Expose port 80
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]
```

PHP version: PHP 8.0.30
FreeScout version: 1.8.110 
Database: MySQL 
Are you using CloudFlare: no

**Comment by smiell** [comment]
Still I do not know how to handle this... I am using listmonk for example where I do not have to expose extra ports for SMTP comunication. Here I only expose port to run web interface. 

I think outgoing comunication form container is not blocked..

**Comment by freescout-helpdesk** [comment]
Have you managed to solve it?
