### ISSUE TITLE
Move system to another server under the same domain

### ISSUE THREAD

**Issue by MGT-GitHub-Dev** [freescout-helpdesk/freescout#3583]
Hello,

how can I move a Freescout installation? The domain remains the same, but the system paths on the new system are different. How and where can I adjust these?

Will all purchased modules be retained? Do I need to take anything else into account?

Best regards

Sandro

PHP version: 8.0
FreeScout version: 1.8.86
Database: MySQL / MariaDB
Are you using CloudFlare: No

**Comment by raramuridesign** [comment]
@MGT-GitHub-Dev We have done this several times and not really had any issues.
You best bet is to use rsync. 
Ensure you update the env file with the new info.
If you have your database on external to the current server, then it should be easy.
Important, you might want to clear the cache on the new server manally or using CLI.  In fact this is very important.
Then it should work.
Good luck
M.
