### ISSUE TITLE
Feature Request: Option to keep conversation snoozed, even if customer replies

### ISSUE THREAD

**Issue by nvnes-sba** [freescout-helpdesk/freescout#3584]
Could there be an option to keep a conversation snoozed, even if the customer replies to the conversation?
If we make an appointment with a person, then they would often reply with a confirmation even if the conversation is already snoozed.
Then the snooze will become inactive, and it will not open at the appointment time (snooze time).

Could there be an option to keep snooze active even if the customer replies?

PHP version: 8.2
FreeScout version: 1.8.110
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
