### ISSUE TITLE
How to access Knowledge Base Module from mailbox

### ISSUE THREAD

**Issue by FlederFau** [freescout-helpdesk/freescout#3587]
Hello,

I recently extended our freescout installation with the Knowledge Base Module.
I did understand, that each Mailbox has it's own knowledge base. But how can a support agent access the knowledge base from the mailbox. Is there a link or something? In my case the knowledge base is only displayed if I chose the option that all users can change the knowledge base. 

Some help would be highly appreciated

**Comment by freescout-helpdesk** [comment]
> In my case the knowledge base is only displayed if I chose the option that all users can change the knowledge base.

This is the only way for now (or you can manually send a link to your users).
