### ISSUE TITLE
Any way to delete some post on long conversation?

### ISSUE THREAD

**Issue by kimsonvu** [freescout-helpdesk/freescout#3589]
Hi,

I found only way to:

![chrome_yBSCZi98SU](https://github.com/freescout-helpdesk/freescout/assets/10061253/950ab361-3081-4cfb-bf0c-b366ec19e970)

- Edit
- Clone
- New conversaion 

From one posting on 1 Converation. Anyway to delete some post that duplicate by some mistake?

**Comment by freescout-helpdesk** [comment]
Unfortunately no for now.

**Comment by kimsonvu** [comment]
Hi,

Pls consider about it.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
