### ISSUE TITLE
Attachements from received email are not stored on the server

### ISSUE THREAD

**Issue by finalwebsites** [freescout-helpdesk/freescout#359]
Hi,

I have the following issue: 
If I create a new message or reply and upload an attachment, the file is uploaded to the server and attached to the message. 
The problem I have, is about the attachments from emails I'm receiving. I can see the name in the email (and the file size) and also the paperclip in the message list, but if I click the name to open the attached file. I get the message "Sorry, the page you are looking for could not be found.". 
If I check the specific directory on my server, I see only the attachments uploaded by myself.

Is there something I'm doing wrong? If this is a bug, I can't believe that I'm the first user with that issue :)

**Comment by freescout-helpdesk** [comment]
Did it happen before?

**Comment by finalwebsites** [comment]
Hi,
it happens for all messages, I just didn't realized it (I don't get so much attachments)
I checked multiple messages and all 3rd part attachments are missing.

**Comment by freescout-helpdesk** [comment]
Since which release does it happen for you?

**Comment by finalwebsites** [comment]
I have no idea, I noticed the problem since the last days. But I remember me that I was missing attachments ~3 month ago. Is there a way to debug that issue?

**Comment by freescout-helpdesk** [comment]
The user under which `schedule:run` cron job is running does not have permissions to write into attachments folder.

**Comment by finalwebsites** [comment]
I double checked and it looks like it started a few days ago (or the has been loaded with a delay).
A few days ago I moved the site to a new server while using the same Linux user.
The strange this is that my own attached files go right into the storage sub directories.
The system page doesn't show any permission problems.

**Comment by freescout-helpdesk** [comment]
Web user and cron user most likely are different in your case.

**Comment by finalwebsites** [comment]
I'm using serverpilot, where PHP scripts are executed by the Linux user (there is no www-data user)
This cronjob works fine for everything except the 3rd party attachments

* * * * * php7.3-sp /srv/users/helpdesk/apps/helpdesk/public/artisan schedule:run >> /dev/null 2>&1

I enabled also debugging via the .env file, but there is nothing to see :(

**Comment by finalwebsites** [comment]
This looks okay too:

```
root@vps:~# ps -Af | grep artisan
helpdesk 24193 24191  0 19:12 ?        00:00:00 /bin/sh -c php7.3-sp /srv/users/helpdesk/apps/helpdesk/public/artisan schedule:run >> /dev/null 2>&1
helpdesk 24195 24193  0 19:12 ?        00:00:00 php7.3-sp /srv/users/helpdesk/apps/helpdesk/public/artisan schedule:run
helpdesk 24246 24195  0 19:12 ?        00:00:00 sh -c '/opt/sp/php7.3/bin/php' 'artisan' queue:work --queue='emails,default' --sleep=5 --tries=1 > '/srv/users/helpdesk/apps/helpdesk/public/storage/logs/queue-jobs.log' 2>&1
helpdesk 24247 24246  0 19:12 ?        00:00:00 /opt/sp/php7.3/bin/php artisan queue:work --queue=emails,default --sleep=5 --tries=1
root     26034 17962  0 19:20 pts/0    00:00:00 grep --color=auto artisan

```

**Comment by freescout-helpdesk** [comment]
> The user under which `schedule:run` cron job is running does not have permissions to write into attachments folder.
