### ISSUE TITLE
Getting the message "There is a problem processing the outgoing mail queue", but status page shows all greens and emails are beeing sent

### ISSUE THREAD

**Issue by rustymunkey** [freescout-helpdesk/freescout#3590]
PHP version: 8.2.13
FreeScout version: 1.8.110
Database: PostgreSQL 14
Are you using CloudFlare: No
Using docker image: tiredofit/freescout

~~I am currently facing the issue on all our instances, that sending of emails does not work reliable~~.
We occasionally get the message "There is a problem processing the outgoing mail queue [...]". System status tells me, that the "queue:work" job is running. Replies to customers are stuck in the status "Pending".

The problem seems to be, that the process `/usr/bin/php82 artisan queue:work --queue=emails,default [...]` is started, but does not complete. Killing all running processes and executing the command by hand has the same effect.

I tried to debug the issue and look where exactly the process is stuck, but i have a hard time finding the right spots in the source. I am not a developer, just some guy with a little bit of php knowledge. I guess I managed to find the [lines](https://github.com/freescout-helpdesk/freescout/blob/1.8.110/vendor/laravel/framework/src/Illuminate/Console/Application.php#L82) from where the command is actually run, but after that i am lost.

Could you give me some pointers to the source where the actual magic happens? For example where the SMTP connection is created and the mails get sent. 

Thanks for your help!

Update: Sending of emails is working, we had a configuration issue on one of our instances.

**Comment by raramuridesign** [comment]
@rustymunkey 
On your server you will have a default php setup, usually php 7. 

If you check the cronjobs, they will be executed using the server default php package. Even if your freescout install is setup with php 8.2.x
We had a similar issue, and ensuring the servers default php is the same as the installed version for freescout solve our issue.

Remember this was specific to our issue. But try that and see if it helps.
M

**Comment by freescout-helpdesk** [comment]
> is started, but does not complete

It should run continuously in the background. https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

Check SendReplyToCustomer jobs on the System page.

**Comment by raramuridesign** [comment]
@rustymunkey If you have emails which are scheduled - I did notice that they sit in que job...
This is normal behaviour, I guess it might make more sense to have better wording, so one can see this is for scheduled emails.

Glad the other issue is sorted out.
M.

**Comment by freescout-helpdesk** [comment]
> On the instance where we encounter the "There is a problem processing the outgoing mail queue" message, the sending of emails is working as expected.

Fixed in the `master` branch and will be published in the next release.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks for sorting this out.

**Comment by Fireful0** [comment]
Excited to see the new update! Thanks, all!
