### ISSUE TITLE
Logs Monitoring hard to understand?

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#3591]
Dear support,

I have a general question about Logs Monitoring.
This is an example of an email received:
`Send Errors
● [2023-12-07 14:08:34] Error sending email to customer {"error":"Expected response code 250 but got code \"400\", with message \"400 Unexpected long headers length, got: 4310 want: less than 4096 chars\r\n\"; File: \/home\/123\/vendor\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Transport\/AbstractSmtpTransport.php (457)","to":""}
● [2023-12-07 14:08:35] Error sending email to customer {"error":"Expected response code 250 but got code \"400\", with message \"400 Unexpected long headers length, got: 4310 want: less than 4096 chars\r\n\"; File: \/home\/123\/vendor\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Transport\/AbstractSmtpTransport.php (457)","to":""}`

There's no reference to the actual email giving the problem (no destination email address, or conversation ID).

Am I missing something?
How can an admin understand the conversation this is referring to?

Thanks

**Comment by freescout-helpdesk** [comment]
Manage > Logs > Send Errors and Outgoing Emails.
