### ISSUE TITLE
LDAP Filter based Access Repeatedly Resets Mute Setting

### ISSUE THREAD

**Issue by OttoWinter** [freescout-helpdesk/freescout#3593]
I recently switched to using LDAP Filter based access for a mailbox. Since then, the "mute" setting for a mailbox gets repeatedly reset to non-muted for admin users.

Steps to reproduce:
1. Have freescout set up with LDAP
2. Configure a mailbox with LDAP filter based access
3. Have an admin user for who the LDAP filter does NOT match (but because of being an admin user still has access to the mailbox)
4. Mute the mailbox for that user
5. Log out the user, then relog (this reloads the LDAP accesses).
6. Now the mailbox is unmuted again for this admin user.

For admin users for which the LDAP filter _does_ match the behavior is correct (mute setting does not reset). The issue is only with admin users for whom the LDAP mailbox filter does NOT match.

---------

PHP version: 8.2.7
FreeScout version: 1.8.110 (ldap integration v1.0.34)
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
We've reproduced the issue.
