### ISSUE TITLE
1.8.111 update issue

### ISSUE THREAD

**Issue by ramboramage** [freescout-helpdesk/freescout#3594]
Morning,

I'm having an issue updating freescout to 1.8.111 from 1.8.110.

Clicking update now goes through the usual process and I get the 'application succesfully updated message' however the version doesnt change and the 'update now' button remains.

I'm not seing anything in the logs, maybe just the version change is missing?

No functional issues visable.

PHP version: 8.2.12 
FreeScout version: 1.8.110
Database: MySQL 
Are you using CloudFlare:  No

Thanks and kind regards,

Stuart.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by ramboramage** [comment]
Thanks, I changed the version number in app.php which cleared it. All other changes are present.

**Comment by ramboramage** [comment]
@janselato Sure, its config/app.php

**Comment by freescout-helpdesk** [comment]
If version number does not change after updating it means updating process has not finished properly and there may be all kinds of unexpected problems in the future. In this case switch to another update method or use manual updating method (which works always).

**Comment by ramboramage** [comment]
I done a comparison between 1.8.110 and 1.8.111 and the version number isn't updated
Compared to 1.8.109 and 1.8.110 where it is.
Every other change shown has been applied.

-Stuart.

**Comment by janselato** [comment]
@ramboramage is right. Following the suggestion, I tried the manual update method and unfortunately, the version number still has not changed.
![image](https://github.com/freescout-helpdesk/freescout/assets/99269288/998bc72d-418d-486e-acf8-cc611ef87299)

**Comment by freescout-helpdesk** [comment]
Fixed in FreeScout v1.8.112.
