### ISSUE TITLE
Twillio error

### ISSUE THREAD

**Issue by oclick** [freescout-helpdesk/freescout#3595]
Could you help me understand why I'm getting this error when replying to WhatsApp messages?

[WhatsApp Webhook - Twilio] (Suporte ao Cliente) Error occurred sending WhatsApp message to 554896604890: API error: {"code":63007,"message":"Twilio could not find a Channel with the specified From address","more_info":"https:\/\/www.twilio.com\/docs\/errors\/63007","status":400}

**Comment by freescout-helpdesk** [comment]
There are some hints on this page: https://www.twilio.com/docs/api/errors/63007
