### ISSUE TITLE
Chat module not working globally?

### ISSUE THREAD

**Issue by matthonesty** [freescout-helpdesk/freescout#3597]
Hello,

trying to install the chat module it appears it acts as a form, not what's shown on the 'Live Chat' modules page.

Investigating this I took to the chat demo website;
https://freescout.net/chat-demo/

Also just a form, no integrated chat.

Submit info, get the following;
Your message has been sent!
[Submit another message](https://demo.freescout.net/help/widget/form/758373728?name=test&email=test%40test.com&subject=test&message=&color=%230068bd&position=br&id=2312787837&success=)

Am i missing something?

**Comment by freescout-helpdesk** [comment]
Chat widget can work together with Contact Us form (see "Contact Form Widget" at https://freescout.net/module/end-user-portal/)
