### ISSUE TITLE
Replacing the word "customers" with "contacts"

### ISSUE THREAD

**Issue by morris4ever69** [freescout-helpdesk/freescout#3599]
Hi, I have a a general request. Is there an easy and quick way to replace the word "Customers" with "Contacts"? We are planning to use FreeScout, plus some modules, to manage a shared inbox where we receive emails from the customers but also from suppliers and other kind of contacts. Thank you.

**Comment by fit4web** [comment]
same here. We are a doctors office and we have patients and partners but no clients :-) "Contacts" would make more sense.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Is there an option to override a language file ? 
So this can be customised?
M.

**Comment by freescout-helpdesk** [comment]
You have not followed the instruction above.

![2023-12-13_16-21-18](https://github.com/freescout-helpdesk/freescout/assets/40499291/50dc8f6a-b4b1-4d2e-a5bb-9c49560338a7)

**Comment by raramuridesign** [comment]
@freescout-helpdesk see my steps
1. add english
2. no option afterwards under choose group
3. ... cannot continue from here

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

Also the instruction above has been updated a bit.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thank you.

**Comment by morris4ever69** [comment]
Thank you for the information!
