### ISSUE TITLE
Freescout Satisfaction ratings whitelabel URL

### ISSUE THREAD

**Issue by chrish789** [freescout-helpdesk/freescout#3601]
Hi

We have using the Freescout Satisfaction ratings module. We use multiple different mailboxes with different domains.

For the satisfaction module, we have noticed, that the URL uses the base url of our installation. Is there a way to whitelist the domain url used?

**Comment by raramuridesign** [comment]
@chrish789 
I am not sure this would work as a base url is set in the env file.

```
# Application URL
APP_URL=https://example.com
```

However, you could also try using a generic domain, so you can allow different emails to share the install. 
Hope this helps
M.

**Comment by freescout-helpdesk** [comment]
> For the satisfaction module, we have noticed, that the URL uses the base url of our installation. Is there a way to whitelist the domain url used?

Unfortunately not.
