### ISSUE TITLE
Change Count of Active Converstions to Count Active And pending

### ISSUE THREAD

**Issue by GTLSlb** [freescout-helpdesk/freescout#3603]
I am working on modifying the Freescout Ticketing system to display both active and pending conversation counts. A new field 'pending' was added next to the 'active' field in each conversation table. However, I am encountering issues with incorrect counts in assigned tickets and peculiar behavior in the deleted folder.
![image](https://github.com/freescout-helpdesk/freescout/assets/123725092/b1e648bd-704e-4a86-b0a9-ee24ebfa061b)
Details:

Incorrect Count in Assigned Tickets:

When tickets are assigned in our mailbox, the count doesn’t seem accurate.
This might be related to the aggregation of counts after introducing the pending status.

Behavior of Deleted Folder:

In the FreeScout demo, the deleted folder's 'active' field returns the total number of conversations.
All conversations in this folder have a 'deleted' status.
Seeking clarification on whether this is intended behavior.
![image](https://github.com/freescout-helpdesk/freescout/assets/123725092/8d3cd3c3-e807-47ea-a305-70765ba2bb95)

**Comment by freescout-helpdesk** [comment]
Simply subtract number of active conversations from total number of conversations in a folder.
