### ISSUE TITLE
The Productivity Report view loads a really long time

### ISSUE THREAD

**Issue by gbanina** [freescout-helpdesk/freescout#3604]
We try to generate a productivity report at the end of each month. Our monthly average is 3000+ replays over 800+ customers (8 agents). Productivity report sometimes generates 2-3 mins.

Is there any way we can optimize this?

I appreciate your help!

**PHP version: 8.0.23
FreeScout version: 1.8.81
Database: MySQL
Are you using CloudFlare:  No**

**Comment by freescout-helpdesk** [comment]
The only way is to increase your server performance.
