### ISSUE TITLE
Change Ticket Status Text to Custom Text

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3605]
Hi @freescout-helpdesk,

I would like to inquire if it is possible to change the ticket status text to custom labels. Specifically, we are interested in changing the "Closed" status to "Responded," and we want this modification to be reflected as "Responded" on the "End User Portal."

Is there a method available that would allow me to update the labels associated with these statuses?

Thank you in advance for your assistance.

**Comment by freescout-helpdesk** [comment]
1. Go to "Manage » Translations".
2. Add English language in "Languages" section.
3. Select "App" in "Choose a group to display translations".
4. Add translations for words/phrases you want to change.
5. Go back to Translate page and click "Publish translations".

**Comment by raramuridesign** [comment]
refer #3599 similar issue.

**Comment by freescout-helpdesk** [comment]
Closing as duplicate.
