### ISSUE TITLE
Freescout repeatedly sending same email

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3607]
We're using 1.8.112 on Ubuntu.  We didn't see this issue until after updating from 1.8.108 to 1.8.112.

Sometimes when a user sends an email from Freescout, Freescout will re-send the same email every 2-3 minutes.  I have attached a sequence of 25 duplicate msgs here, but it has sent more than this.

In the Freescout Outgoing logs, there is no record of these messages being sent.  However, there is a copy of each sent message in the mailbox we have setup for auto Bcc.  So no doubt 25 messages were sent here.

The duplicate sending doesn't go on indefinitely.  In this example, for ticket #19113, the message was sent 25 times, then it stopped.

We use a MS 365 account for sending.

PHP version: PHP 8.1.12-1ubuntu4.3 (cli) (built: Aug 17 2023 17:37:48) (NTS)
FreeScout version: 1.8.112
Database: MySQL / PostgreSQL. DB is MySQL
Are you using CloudFlare: Yes / No. NOT using Cloudflare
![seamonkey_658](https://github.com/freescout-helpdesk/freescout/assets/18216162/03922255-66c5-4254-b11a-a9f410f4c622)
[19113-25-duplicates-freescout.zip](https://github.com/freescout-helpdesk/freescout/files/13666298/19113-25-duplicates-freescout.zip)

**Comment by freescout-helpdesk** [comment]
Check Manage > Logs > App Logs.

**Comment by bekre10** [comment]
I have exactly the same issue on two different FreeScout Servers.
They all run the latest version of freescout.
We do use Cloudflare and we use AWS SES to send out emails.
Both Servers are on AWS Ligthsail.

Server A
Ubuntu 22.04.3
MariaDB 10.6.12
PHP 8.0.30
nginx 1.18.0

Server B
Ubuntu 20.04.6
MariaDB 10.3
PHP 7.4.3
nginx 1.18.0

In some instance, we had around 200 duplicate mails sent. Sometimes, it's ok for a few days and then happens again.

**Comment by freescout-helpdesk** [comment]
> I have exactly the same issue on two different FreeScout Servers.

What SMTP server are you using?

**Comment by freescout-helpdesk** [comment]
Here is the place you both can try to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php#L270

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by bekre10** [comment]
As mentioned in my original post, we use Amazon SES to send out emails. Different SES accounts on both servers,
