### ISSUE TITLE
Cant install Push Notification Module

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#361]
Hi,

just wanted to buy and integrate the new notification module, unfortunately after Installation the Activation fails:

```
Error occured creating a module symlink (/var/www/html/public/modules/mobilenotifications). Please check folder permissions.

Cache cleared successfully.
Nothing to migrate.
Error occured creating [/var/www/html/public/modules/mobilenotifications] symlink: symlink(): No such file or directory
The [/var/www/html/public/modules/mobilenotifications] symlink has been created
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js
```

The Directory Access rights are correct, owner & group = webserver, drwxr-xr-x

The symlink is there:
https://imgur.com/a/UF7n6SK

Other Modules I use are working, just for testing deactivated and reactivated the tag module without issue.

**Comment by freescout-helpdesk** [comment]
Just create manually "Public" folder in `/Modules/MobileNotifications` and activate the module. It will be fixed in the next release.

**Comment by solariz** [comment]
thanks, this does the trick. Is there a direct link to the android app?

**Comment by freescout-helpdesk** [comment]
https://freescout.net/android-app/
