### ISSUE TITLE
Module creation

### ISSUE THREAD

**Issue by iantearle** [freescout-helpdesk/freescout#3610]
I am attempting to save a unique value against each support request from the sidebar, I have exhausted the documentation and my understanding here, and am struggling to get a value to save. I have achieved saving within the settings page, but when I attempt to do the same within the "thread" and sidebar I get a whoops and no logging errors.

I have tried to take a look at the community modules too, but these don't appear to be saving where I'd like to save.

Is anyone able to provide further documentation on how to specifically save unique data from a sidebar input value on each email/support request?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such particular documentation. You can try to find some developer: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
