### ISSUE TITLE
Connect G Suite to FreeScout

### ISSUE THREAD

**Issue by ConnectronX** [freescout-helpdesk/freescout#3612]
Hello,

We use Google as a mail provider using APP passwords

However, I get this message: Connection could not be established with host smtp.gmail.com [ #0]

No matter what I try, it won't allow a connection

PHP version: 8.1.22
FreeScout version: 1.8.113
Database: MySQL
Are you using CloudFlare: Yes what DNS

**Comment by freescout-helpdesk** [comment]
Try to insert the following code on line 131 in /config/mail.php file:
```
    'stream' => [
        'ssl' => [
            'allow_self_signed' => true,
            'verify_peer' => false,
            'verify_peer_name' => false,
        ],
    ],
```

After that [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache) and try again.

**Comment by ConnectronX** [comment]
I've done that now, but the same message keeps coming

( Outgoing emails Log records )

Send error. Connection could not be established with host smtp.gmail.com [ #0]. Message ID:

( Log records )

Undefined constant "FT_UID" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant \"FT_UID\" at /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/webklex/laravel-imap/src/config/imap.php:105)
[stacktrace]
#0 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(66): require()
#1 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#2 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#3 /home/cxy7ekhphfswe/Subdomains/www_replydesk/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#4 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#5 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#6 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#7 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#8 /home/cxy7ekhphfswe/Subdomains/www_replydesk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#9 /home/cxy7ekhphfswe/Subdomains/www_replydesk/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#10 {main}
"}

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. Someone needs to figure out why your server can't connect to smtp.gmail.com

**Comment by ConnectronX** [comment]
So it's not the server's fault, as other systems can connect to Google's mail server that are on the same server
