### ISSUE TITLE
Customer not added as CC

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3613]
**Steps to reproduce:**
1. Send an email to FreeScout like a customer.  You need to add another address to the CC. For example, the customer's address is email1@example.com and the CC is email2@example.com.
2. Reply to a customer from FreeScout.
3. After receiving the response from step 2, reply to the email from the email2@example.com box using Reply All in your email client.
4. After receiving the email from step 3 press Reply button in FreeScout conversation.

**Result:**
Only email1@example.com you can see in the reply form. And if you send an email, it will not come to email2@example.com.

**Expected result:**
Emails are sent to all participants in the conversation.

PHP version: 7.4.33
FreeScout version: 1.8.113
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
> 1. Send the first email from the costumer (email address 1) with CC to your coworker (email address 2).

How does the email get into FreeScout?

**Comment by il2020** [comment]
> > 1. Send the first email from the costumer (email address 1) with CC to your coworker (email address 2).
> 
> How does the email get into FreeScout? Under coworker you mean FreeScout mailbox?

No. I've updated the description. Does it make sense now?

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by il2020** [comment]
> Fixed in the `master` branch and will be published in the next release.

It's working. Thank you.
