### ISSUE TITLE
Malformated email output

### ISSUE THREAD

**Issue by bellegarde-c** [freescout-helpdesk/freescout#3615]
PHP version: 7.4.33-1+deb11u4
FreeScout version: 1.8.110
Database: MySQL
Are you using CloudFlare: No

When receiving this email:  [freescout.txt](https://github.com/freescout-helpdesk/freescout/files/13701419/freescout.txt) , it is shown as (missing content):

![Capture d’écran du 2023-12-18 09-48-01](https://github.com/freescout-helpdesk/freescout/assets/57196916/88c8c143-0e71-40b4-89c2-1e341b9200d2)

While original is shown as:

![Capture d’écran du 2023-12-18 09-48-15](https://github.com/freescout-helpdesk/freescout/assets/57196916/0d43f628-3a41-4da0-bc3b-12441dfc8c22)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-a-customer-replies-within-the-cited-text-freescout-does-not-show-it
