### ISSUE TITLE
Inline images are not showing up in e-mails all the time

### ISSUE THREAD

**Issue by MCH-Operate** [freescout-helpdesk/freescout#3616]
Hi!

First of all, thank you for a great project.

We're experiencing some difficulties displaying some inline images in emails that we recieve from different clients. We haven't been able to pin-point the problem, but here's some further information:

When inspecting the DOM in the browser, no sign of an image is present in the HTML-code in FreeScout. The paragraph, where the image should be located, is just empty:
![image](https://github.com/freescout-helpdesk/freescout/assets/154278955/f0b605d7-05a2-4d18-b54a-ecfdcc6fb138)

But when forwarding the email, and displaying it in Outlook for Mac or Outlook on iOS, the image appears at once and is included in the source of the email. Nothing has been done to the mail, and works just fine for the reciever as a cc-contact to the same email as well:
<img width="482" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/154278955/3506320d-b844-444f-b0ef-da601228fcf0">

The image is not showing up in FreeScout in any browser: Safari, Chrome or Firefox. It is not rendered in the body of the mail, when shown in FreeScout - just empty. It doesn't appear in the app-version for iOS either.

I've found a similar issue, that didn't provide any direct solution: https://github.com/freescout-helpdesk/freescout/issues/2669

Any idea where we shoud look or test, to get a better idea of the problem? I'm guessing some kind of configuration issue somewhere, but I'm feeling the good-old needle in a haystack-moment.

Regards,
Mattias

**Comment by freescout-helpdesk** [comment]
We'll need the unprocessed body's HTML-code of the received email - you can find it in Show Original window, Body tab.

**Comment by MCH-Operate** [comment]
Hi, the image is present in the unpocessed body of the HTML:

`<div class="WordSection1">
<p class="MsoNormal"><span lang="EN-US" style='font-size:10.0pt;font-family:"Verdana",sans-serif'>Hej Mattias<p></p></span></p>
<p class="MsoNormal"><span lang="EN-US" style='font-size:10.0pt;font-family:"Verdana",sans-serif'><p> </p></span></p>
<p class="MsoNormal"><span style='font-size:10.0pt;font-family:"Verdana",sans-serif'>Håber du nyder december måned.<p></p></span></p>
<p class="MsoNormal"><span style='font-size:10.0pt;font-family:"Verdana",sans-serif'><p> </p></span></p>
<p class="MsoNormal"><span style='font-size:10.0pt;font-family:"Verdana",sans-serif'>Vi har fået fortaget en scan på eksterne adresse som er relateret til os og et af resultaterne er denne:<p></p></span></p>
<p class="MsoNormal"><span style='font-size:10.0pt;font-family:"Verdana",sans-serif'>**<img width="1160" height="33" style="width:12.0833in;height:.3437in" id="Picture_x0020_6" src="cid:image001.png@01DA31DC.66FC5530">**</span><span style='font-size:10.0pt;font-family:"Verdana",sans-serif'><p></p></span></p>`

**Comment by freescout-helpdesk** [comment]
Try to add add `APP_NEW_FETCHING_LIBRARY=true` parameter to the .env file and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache). After that fetch a new email and check.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3649#issuecomment-1875491173
