### ISSUE TITLE
oAuth - POST to Logout URI doesnt work

### ISSUE THREAD

**Issue by kluvi** [freescout-helpdesk/freescout#3617]
When performing POST request to `Logout URI`, it returns `419 - The page has expired due to inactivity. Please refresh and try again.`.
The reason is CSRF protection - it must be disabled for this route. (I implemented oauth login in own app past week and facet same issue).

BUT after I manualy add exception to `VerifyCsrfToken` middleware and amnually performing , it still doesnt work. User is not logged out.

It looks, that the endpoint logs-out only current user (=Front-channel logout). My goal is to achieve backchannel logout, which can logout any user without any user interaction.
If you dont want to implement parsing any JWT tokens, it should be better to logout all users logged through this provider (only when method is POST). I think its safer to force login of other users, than keep logged-in some potentialy malicious user.

Relates to my feature request: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/427460/comments

PHP version: 7.4.33
FreeScout version: 1.8.112 (all modules updated to latest version)
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in OAuth & Social Login Module v1.0.16
