### ISSUE TITLE
Remove new line from signature if the variable is empty

### ISSUE THREAD

**Issue by morris4ever69** [freescout-helpdesk/freescout#3618]
Hi,

Is there a way to remove the new line in the signature when a variable is empty?

Example of signature:

```
{%user.fullName%}
{%user.jobTitle%}
{%user.phone%}
```

If the job title is empty in the user's profile, it would be nice that, in the final signature, also the new line (br) is removed, avoiding an empty line between `user.fullName` and `user.phone`.

Thank you for your suggestions.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such possibility.
