### ISSUE TITLE
Android app can't find FreeScout installation

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#362]
Hey there, 

First of all: thank you for your great work on this fantastic system. I love it!

I just wanted to install the Android app, but it can't find the installation when I enter the link. Am I doing something wrong?

I have updated the installation, and installed the Notifications Module.

https://imgur.com/a/Be4QP1v

**Comment by freescout-helpdesk** [comment]
Does it work for you with demo.freescout.net ?

**Comment by matsn0w** [comment]
Nope, sadly enough that doesn't work neither. I'm on Android 10...

**Comment by freescout-helpdesk** [comment]
For now maximum Android 9 is supported.
We will try to make the app compatible with Android 10.

**Comment by matsn0w** [comment]
Got it, thank you for your help 👍

**Comment by freescout-helpdesk** [comment]
@matsn0w Try v1.0.2: https://play.google.com/store/apps/details?id=net.freescout.app

**Comment by matsn0w** [comment]
I'm sorry, but it still doesn't work.

I also tried reinstalling the app, but that didn't work either.

**Comment by solariz** [comment]
Just a hint; maybe you can try to add the protocol if it is https. I had trouble to connect to my freescout installation too, until I completely specified **https://**subdomain.domain.test/

**Comment by matsn0w** [comment]
Confirm, it does work for me when I enter https://demo.freescout.net.
My domain indeed has no SSL enabled for now.

**Comment by matsn0w** [comment]
I have enabled SSL, but now I get some errors about mixed content in my Chrome dev tools. The css in particular won't load over https, because the request goes over http somehow. How can I fix that?

The app does work now. (but again doesn't load the stylesheets)

**Comment by freescout-helpdesk** [comment]
Update protocol in APP_URL in .env file and clear the cache.

**Comment by matsn0w** [comment]
Yeah, I found that as well, fixed 👍

**Comment by freescout-helpdesk** [comment]
Congratulations :+1:
