### ISSUE TITLE
When customer's last name is blank, it will be change at next mail receive.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3622]
Version 1.8.108
and CRM module(1.0.41)
We delete customer last name.
but it will be changed at next mail receive from the customer.
Is this behavior is correct?

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by totake0224** [comment]
Thank you.
I think it not good way to blank last name. but I'm very glad to hear it fixed.
