### ISSUE TITLE
Does freescout have StartTLS support or how to add it?

### ISSUE THREAD

**Issue by Maks-Redka** [freescout-helpdesk/freescout#3624]
Greetings, I need freescout to have full support for StartTLS, both for Incoming and Outgoing mail servers.
Does freescout have StartTLS support? If it doen't, how can i add StartTLS?

**Comment by freescout-helpdesk** [comment]
### StartTLS on Fetching Emails

By default StartTLS is included in `TLS` encryption method in mailbox "Fetching Emails" settings.

![tls](https://github.com/freescout-helpdesk/freescout/assets/40499291/4cee2d9f-89d4-46f4-8dd3-a9cd9e42e2fc)

If you are using modern Microsoft OAuth IMAP authentication or you have `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file set - we've just added a new `StartTLS` encryption option to the mailbox "Fetching Emails" settings (this option will be available in the next release):
![starttls](https://github.com/freescout-helpdesk/freescout/assets/40499291/657f1c2f-b72c-4588-adb0-07ac60a2b0de)

### StartTLS on Sending Emails

By default StartTLS is included in `TLS` encryption method in mailbox "Sending Emails" settings.

![tls](https://github.com/freescout-helpdesk/freescout/assets/40499291/4cee2d9f-89d4-46f4-8dd3-a9cd9e42e2fc)

**Comment by Maks-Redka** [comment]
Got it, then for now I'll use TLS and check the new version. Thank you!
