### ISSUE TITLE
How to switch Free Scout from HTTPS mode (expired certificate) to HTTP.

### ISSUE THREAD

**Issue by v-a-moroz** [freescout-helpdesk/freescout#3625]
How to switch Free Scout from HTTPS mode (expired certificate) to HTTP?
And when the certificate is received, switch back to HTTPS?

PHP version: 8,1
FreeScout version: 1.8.114
Database: MySQL  8.0.35-0ubuntu0.22.04.1
Are you using CloudFlare:  No

**Comment by freescout-helpdesk** [comment]
Just change APP_URL in .env file and clear cache. After that re-configure your web server.

**Comment by v-a-moroz** [comment]
Yes, change APP_URL in .env  /var/www/html

# Every time you are making changes in .env file, in order changes to take an effect you need to run:
# php artisan freescout:clear-cache

# Application URL
APP_URL=http://*****.*****.ru  /*- hidden for safety
APP_FORCE_HTTPS=false

how to re-configure web server?

**Comment by v-a-moroz** [comment]
thanks for the help
instructions
https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache
