### ISSUE TITLE
Error  sending emails SMTP protocol

### ISSUE THREAD

**Issue by v-a-moroz** [freescout-helpdesk/freescout#3626]
Hi, i was able to run the application and complete the installation. Unfortunately, when sending  email messages (SMTP protocol), I receive the following log messages:
"Connection could not be established with host relay.*****.ru [Connection timed out #110]; File: /var/www/html/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php (271)"
hosted mail server, 100% operational
If install and configure sendmail, switch in the Free Scout settings "sendmail", then the mail works.
But need to configure it using the SMTP protocol.
p.s.mail server self-signed SSL certificate/
p.s.2 FreeScout perfectly accepts mail via IMAP from a web server, but cannot send via SMTP

PHP version: 8,1
FreeScout version: 1.8.114
Database: MySQL 8.0.35-0ubuntu0.22.04.1
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
"Connection timed out" - it means there is no connection from your server to the SMTP server.

**Comment by v-a-moroz** [comment]
If connect email client  "The bat",  server works.
FreeScout for SMTP no work.

12/27/2023, 10:45:24: SEND - Sending mail - letters in queue: 1
  12/27/2023, 10:45:24: SEND - Connection to the SMTP server relay.*****.ru via port 465
  12/27/2023, 10:45:24: SEND - Starting TLS greeting
>12/27/2023, 10:45:24: SEND - Certificate properties: 420000000A658BD46B, algorithm: RSA (2048 bits), Valid from: 06/28/2023 7:38:19, to: 06/26/2024 7:38:19, to hosts in quantity 2 pcs.: relay.*****.ru, 192.ХХХ.ХХ.ХХХ.
>12/27/2023, 10:45:24: SEND - Owner: RU, ХХХХХХХХХХХХХХХХХХХ , IT Dept, 192.ХХХ.ХХ.ХХХ, postmaster@****.ru.
>12/27/2023, 10:45:24: SEND - Supplier: AO Kaspersky Lab, Kaspersky Anti-Virus Personal Root Certificate.
  12/27/2023 10:45:24 AM: SEND - TLS hello completed
  12/27/2023, 10:45:24: SEND - Connection to the SMTP server was successful
  12/27/2023, 10:45:24: SEND - Authentication (verification of username and password)...
  12/27/2023, 10:45:25: SEND - Sending a letter to moroz@****.ru
<27.12.2023, 10:45:29: SEND - A letter was sent to moroz@****.ru (2282 bytes)
  12/27/2023, 10:45:29: SEND - Connection completed - emails sent: 1

![1111111111111](https://github.com/freescout-helpdesk/freescout/assets/154814394/fc1fc565-5dd3-45cc-88f4-fd3fa1c22e6c)
![2222222222](https://github.com/freescout-helpdesk/freescout/assets/154814394/6c6d7358-8914-4e60-aa8e-c92c46d25c96)
![4444444444](https://github.com/freescout-helpdesk/freescout/assets/154814394/84b870f0-c85e-44f6-a8c3-dd882b39937c)
![3333333333333](https://github.com/freescout-helpdesk/freescout/assets/154814394/62727d49-64b8-4e70-909a-95ee4ea2d082)

**Comment by freescout-helpdesk** [comment]
In the `master` branch we've added displaying SMTP logs when there are some errors during "Send Test". It may help to figure out the reason of the issue.

![2023-12-27_12-04-51](https://github.com/freescout-helpdesk/freescout/assets/40499291/301a449e-2124-4dda-bdfb-b5a9a42584ff)

**Comment by v-a-moroz** [comment]
I have the Russian version, I don’t understand where “In the main branch” is located?

**Comment by freescout-helpdesk** [comment]
You can wait for the next FreeScout release (1-2 weeks) or you can add a temporary workaround - replace lines 290-315 in /app/Misc/Mail.php with the following code:
```
        if ($mailbox) {
            // Configure mail driver according to Mailbox settings
            \MailHelper::setMailDriver($mailbox);
			$logger = new \Swift_Plugins_Loggers_ArrayLogger();
			\Mail::getSwiftMailer()->registerPlugin(new \Swift_Plugins_LoggerPlugin($logger));
            $status_message = '';

            try {
                \Mail::to([$to])->send(new \App\Mail\Test($mailbox));
            } catch (\Exception $e) {
                // We come here in case SMTP server unavailable for example
                $status_message = $e->getMessage();
				\Log::error('[SMTP logs] '.$logger->dump());
            }
        } else {
            // System email
            \MailHelper::setSystemMailDriver();
			$logger = new \Swift_Plugins_Loggers_ArrayLogger();
			\Mail::getSwiftMailer()->registerPlugin(new \Swift_Plugins_LoggerPlugin($logger));
            $status_message = '';

            try {
                \Mail::to([['name' => '', 'email' => $to]])
                    ->send(new \App\Mail\Test());
            } catch (\Exception $e) {
                // We come here in case SMTP server unavailable for example
                $status_message = $e->getMessage();
				\Log::error('[SMTP logs] '.$logger->dump());
            }
        }
```

After that try to send an email and search for `SMTP logs` in laravel logs in "Manage > Logs > App Logs"

**Comment by v-a-moroz** [comment]
replace lines 290-315 in /app/Misc/Mail.php with the following code

laravel log:
Parse error: syntax error, unexpected token "if", expecting ";" or "{" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected token \"if\", expecting \";\" or \"{\" at /var/www/html/app/Misc/Mail.php:290)
![888888](https://github.com/freescout-helpdesk/freescout/assets/154814394/ef6c2b23-2729-4688-9e4f-556e033fa00e)

Can you send the required file to my email?
v.a.moroz@ya.ru

**Comment by freescout-helpdesk** [comment]
/app/Misc/Mail.php file is attached.

[Mail.zip](https://github.com/freescout-helpdesk/freescout/files/13778380/Mail.zip)

**Comment by v-a-moroz** [comment]
thanks added
log varavel:

error | production | 2023-12-27 16:19:12 | [SMTP logs] ++ Starting Swift_SmtpTransport
!! Connection could not be established with host relay.vnmz.ru [Connection timed out #110] (code: 0)

![9999999](https://github.com/freescout-helpdesk/freescout/assets/154814394/a98f94f8-2e1a-4d8d-8f6f-02f3f7c41802)

**Comment by freescout-helpdesk** [comment]
Some suggestions here: https://stackoverflow.com/questions/25517281/swiftmailer-connection-could-not-be-established-with-host-smtp-gmail-com-conne

**Comment by v-a-moroz** [comment]
my server provider blocked the connection to port 25 and 465. now there is a connection. 
```
:~# telnet relay.*******.ru 465
Trying 77.ХХХ.ХХХ.ХХХХ...
Connected to relay.*******.ru.
Escape character is '^]'.
Connection closed by foreign host.

:~# telnet relay.*******.ru 25
Trying 77.ХХХ.ХХХ.ХХХХ...
Connected to relay.*******.ru.
Escape character is '^]'.
220 ksmg.*******.ru ESMTP MTA
421 4.4.2 ksmg.*******.ru Error: timeout exceeded
Connection closed by foreign host.
```
but this did not solve the problem of connecting via smtp port 465

laravel-2023-12-28.log:
[SMTP logs] ++ Starting Swift_SmtpTransport
!! Connection to tcp://relay.*******.ru:465 Timed Out (code: 0)

![7777777](https://github.com/freescout-helpdesk/freescout/assets/154814394/f5409bb9-fe81-4db2-8b2a-cbca1ec6ef45)

install ssmtp to server
ssmtp work!
log:
```
/var/log/mail.log:Dec 28 08:51:15 help sSMTP[85081]: Set MailHub="relay.*******.ru"
/var/log/mail.log:Dec 28 08:51:15 help sSMTP[85081]: via SMTP Port Number="465"
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: Creating SSL connection to host
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: SSL connection using RSA_AES_256_CBC_SHA1
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: 220 relay.*******.ru ESMTP mail server ready at Thu, 28 Dec 2023 08:51:18 +0300 (MSK)
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: EHLO localhost
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: 250 HELP
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: AUTH LOGIN
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: 235 2.0.0 OK Authenticated
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: MAIL FROM:<help@*******.ru.ru>
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: 250 2.1.0 <help@*******.ru.ru>... Sender ok
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: RCPT TO:<help@*******.ru>
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: 250 2.1.5 <help@*******.ru>... Recipient ok
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: DATA
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: 354 Enter mail, end with "." on a line by itself
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: Received: by localhost (sSMTP sendmail emulation); Thu, 28 Dec 2023 08:51:15 +0300
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: From: "root" <help@*******.ru.ru>
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: Date: Thu, 28 Dec 2023 08:51:15 +0300
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]:
/var/log/mail.log:Dec 28 08:51:18 help sSMTP[85081]: .
/var/log/mail.log:Dec 28 08:51:23 help sSMTP[85081]: 250 2.0.0 3BS5pIwM078671 Message accepted for delivery
/var/log/mail.log:Dec 28 08:51:23 help sSMTP[85081]: QUIT
/var/log/mail.log:Dec 28 08:51:23 help sSMTP[85081]: 221 2.0.0 relay.*******.ru closing connection
/var/log/mail.log:Dec 28 08:51:23 help sSMTP[85081]: Sent mail for help@*******.ru.ru (221 2.0.0 relay.*******.ru closing connection) uid=0 username=root outbytes=289
/var/log/mail.log:Dec 28 08:51:39 help sSMTP[85118]: Set MailHub="relay.*******.ru"
/var/log/mail.log:Dec 28 08:51:39 help sSMTP[85118]: via SMTP Port Number="465"
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: Creating SSL connection to host
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: SSL connection using RSA_AES_256_CBC_SHA1
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: 220 relay.*******.ru ESMTP mail server ready at Thu, 28 Dec 2023 08:51:46 +0300 (MSK)
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: EHLO localhost
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: 250 HELP
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: AUTH LOGIN
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: 235 2.0.0 OK Authenticated
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: MAIL FROM:<help@*******.ru>
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: 250 2.1.0 <help@*******.ru>... Sender ok
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: RCPT TO:<help@*******.ru>
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: 250 2.1.5 <help@*******.ru>... Recipient ok
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: DATA
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: 354 Enter mail, end with "." on a line by itself
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: Received: by localhost (sSMTP sendmail emulation); Thu, 28 Dec 2023 08:51:39 +0300
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: Date: Thu, 28 Dec 2023 08:51:39 +0300
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: To: moroz@*******.ru
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: From: help@*******.ru
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: Subject: test#015#012
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: test#012ct: test#015
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]:
/var/log/mail.log:Dec 28 08:51:46 help sSMTP[85118]: .
/var/log/mail.log:Dec 28 08:51:51 help sSMTP[85118]: 250 2.0.0 3BS5pk6d078686 Message accepted for delivery
/var/log/mail.log:Dec 28 08:51:51 help sSMTP[85118]: QUIT
/var/log/mail.log:Dec 28 08:51:51 help sSMTP[85118]: 221 2.0.0 relay.*******.ru closing connection
/var/log/mail.log:Dec 28 08:51:51 help sSMTP[85118]: Sent mail for help@*******.ru (221 2.0.0 relay.*******.ru closing connection) uid=0 username=root outbytes=327
```

FreeScout, SMTP no work!

**Comment by freescout-helpdesk** [comment]
It looks you'll need someone who can investigate it on your server. We can't reproduce it on your end. Maybe the issue lays in some PHP configuration.

**Comment by v-a-moroz** [comment]
I can arrange access for you via AnyDesk (https://anydesk.com), write to moroz@vnmz.ru

**Comment by freescout-helpdesk** [comment]
Try to increase SMTP timeout: https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues#12-possible-issues
