### ISSUE TITLE
FreeScout redesign?

### ISSUE THREAD

**Issue by adrianmxh** [freescout-helpdesk/freescout#3627]
Hi there and Merry Christmas! :-)

Thank you so much for all the work you're doing with FreeScout, it's one of the best projects I've seen so far and I'm actively using!

I wanted to ask, is there a redesign planned? The current design seems quite dated and doing a personal redesign would make updating FreeScout really hard.
For example, we currently have our own custom made design for FreeScout, but this really makes updating extremely hard because on each update FreeScout replaces all the files with the original ones. Any way we could improve this process somehow or is there a redesign planned?

**Comment by freescout-helpdesk** [comment]
There was no such plans. But you can suggest your improvements one-by-one via pull requests.
