### ISSUE TITLE
Migration from a cPanel to Linode

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#3628]
Hi, I want to migrate my Freescout instance from a share hosting (cPanel) server to a self hotsed Web server in a linux server (VPS hosted by Linode).
My question is about how to do it safely ? I have a lot of data already in the server, and I want to keep it. Also, all the databases, configurations, purchased modules, etc... Any advice will be welcomed.

**Comment by freescout-helpdesk** [comment]
If you don't know how to do it, better to find someone who can do it for you to be safe.

**Comment by freescout-helpdesk** [comment]
Also we've added some info here: https://github.com/freescout-helpdesk/freescout/wiki/FAQ#what-is-the-proper-way-to-move-freescout-to-another-server
