### ISSUE TITLE
reply-to not honored

### ISSUE THREAD

**Issue by yuri-chanz** [freescout-helpdesk/freescout#3629]
We send support tickets to Freescout from our server, but we can use only FROM emails that are registered domains, so not from the clients (Yahoo, gmail etc). But in FreeScout you reply to the FROM message (which is the server: no-reply). Thus we added REPLY-TO when sending it to Freescout. However, Freescout does not honor or recognize this. Hopefully a small change, but this would help a lot.

Thus: I want in Freescout to reply to the "REPLY-TO" header, if that is set. 

PHP version: 8.2
FreeScout version: 1.8.114 
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Example of email headers and some screenshots would be helpful.

**Comment by yuri-chanz** [comment]
Ah, sorry. Those are default email headers. Hereby an example (see 4th line)

Subject: Website Contact
Date: Mon, 25 Dec 2023 22:45:38 +0000 (UTC)
From: Website <noreply@website.com>
Reply-To: customer@gmail.com
Message-ID: <aeiQDrkgD2P8pOpAawOV4F3JXexD2WA6FqR4FknEMX8@www.website.com>
X-Mailer: PHPMailer 6.9.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

**Comment by freescout-helpdesk** [comment]
By default FreeScout uses Reply-To value as a customer email when fetching emails.

It looks like by some reason it does not work for you. Maybe FreeScout can't parse "From:" field.

Here is place to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L270

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by yuri-chanz** [comment]
That is odd indeed. Will have it checked out here and report back. Thank you a lot for the fast reply.

**Comment by yuri-chanz** [comment]
Hi. Issue solved! It was on our side, not on FreeScout! 

**Cause of the problem:**
In our app (Laravel) the Reply-To was set in the setting: "mail,php". Thus when sending to Mailscout, the reply-to was concatenated to the address in the setting, resulting in 2 addresses in the mail-to. MailScout is using the 1st mail address found in the reply-to line (which was the default set in the setting). 

Thanks!
