### ISSUE TITLE
Messages are not showing properly

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#363]
Hey there, back again with another issue :)

I found that when I try to, for example, delete a module, I get a confirmation message that looks a bit weird:

EDIT: this happens in multiple places

![image](https://user-images.githubusercontent.com/15019582/68758492-33683e80-060e-11ea-8a52-a8d5a1227a39.png)

I couldn't find these strings in the translation, so I guess it has something to do with that...

**Comment by matsn0w** [comment]
btw, I send my translations for the Dutch language to you.

**Comment by freescout-helpdesk** [comment]
Something is wrong with your `/storage/app/public/js/vars.js` file which is generated on clearing the cache.

**Comment by matsn0w** [comment]
So I noticed there's no 'nl' folder in resources/lang. Should I create one and transalte those files as well? I also noticed there aree sections for messages in the vars.js file, but not for nl. Maybe that's the problem. How can I fix that?

**Comment by freescout-helpdesk** [comment]
Have you tried to clear the cache?

**Comment by matsn0w** [comment]
About a hundred times ;)

**Comment by freescout-helpdesk** [comment]
Did you make Dutch translation using Manage --> Translate tool?

**Comment by matsn0w** [comment]
Yep!

**Comment by freescout-helpdesk** [comment]
Try to set English as default FreeScout language and publish translations again.

**Comment by matsn0w** [comment]
That doesn't seem to work neither. I also tried setting both the system language and my personal language, but that also doesn't work. 

I did notice that the messages were in proper Dutch when my language was English! Setting it back to Dutch removed the translations again...

Isn't that weird?

**Comment by freescout-helpdesk** [comment]
This issue will be fixed in the next release. If you have any translations ready feel free to send them to support@freescout.net, so that they can be added to the release too.
