### ISSUE TITLE
Facebook Integration outside Eu and Japan

### ISSUE THREAD

**Issue by YoaviX** [freescout-helpdesk/freescout#3630]
Europe and Japan Facebook Regulation affect us, and we are not in Europe.
I have a business set to be Outside of Europe And Japan.
I have installed Facebook integration module.

For some reason, I get affect by Facebook Regulation for Europe and Japan. The names of the users sending us messages through our messenger in our Facebook page are getting as "Facebook" instead if the user's Name.

it tried restricting the app only to local user that are not from Europe.

Does anyone else faces this issue?
is there anything in configuration that we can do to solve this one?

Thanks,
Yoav.

**Comment by freescout-helpdesk** [comment]
Unfortunately we don't know. Try to contact Facebook support.
