### ISSUE TITLE
Time Tracking Module not working after update

### ISSUE THREAD

**Issue by mhktc** [freescout-helpdesk/freescout#3633]
Hello,

after updating freescout to the latest version the Time Tracking Module doesnt automatically start tracking times when inside a ticket.
Version of the Time Tracking Module is 1.0.17.

PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version:  1.8.115 
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
