### ISSUE TITLE
cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#3635]
Hi, I installed a clean install server and I get this error en the freescout status page:
![2023-12-28 at 14 50](https://github.com/freescout-helpdesk/freescout/assets/84030633/25506a23-250d-43d1-9010-3a0201f18c63)

Running the comand of requeriments, looks fine:

php /var/www/html/freescout/artisan freescout:check-requirements
PHP Version
 8.0.30........................ OK
PHP Extensions
 OpenSSL....................... OK
 PDO........................... OK
 Mbstring...................... OK
 Tokenizer..................... OK
 JSON.......................... OK
 XML........................... OK
 IMAP.......................... OK
 GD............................ OK
 fileinfo...................... OK
 ZIP........................... OK
 iconv......................... OK
 cURL.......................... OK
 DOM........................... OK
 libxml........................ OK
 intl.......................... OK
 pcntl (console PHP)........... OK
Functions
 shell_exec (PHP).............. OK
 proc_open (PHP)............... OK
 fpassthru (PHP)............... OK
 symlink (PHP)................. OK
 pcntl_signal (console PHP).... OK
 ps (shell).................... OK

PHP version: **8.0.30**
FreeScout version: **1.8.115**
Database: MySQL (10.5.16-MariaDB)
Are you using CloudFlare: No

Any Idea where to look in order to fix this? When I try to update the freescout I get this error:

Error occurred: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors. html)
![curl 2023-12-28 at 15 20](https://github.com/freescout-helpdesk/freescout/assets/84030633/b48565f0-fb90-4850-9084-373f05966957)

Any help or idea will be very thanksfull

**Comment by freescout-helpdesk** [comment]
Something is blocking Curl request on your server, firewall or something else.
