### ISSUE TITLE
Freescout Blank Message or Text Cut-off Issue

### ISSUE THREAD

**Issue by NaveenKharwar** [freescout-helpdesk/freescout#3636]
Hi creators,

I'm Naveen from the Brainstorm Force support team. Our support agents have encountered an unusual problem with Freescout. There's an issue where, intermittently, when users send us responses as comments, we receive either blank messages or truncated text within Freescout.

Here's an example:

- What the user sent us: [Screenshot](https://bsf.d.pr/i/XlpwpB)
- What we received: [Screenshot](https://bsf.d.pr/i/b16jj2)

My team member has provided additional details and demonstrated the issue in this screen recording: [Screencast](https://bsf.d.pr/v/21fxgj). We would appreciate it if you could take a look and suggest a solution.

**Additional Information:**
- PHP version: 7.4.33
- FreeScout version: 1.8.108
- Database: MySQL (5.5.5-10.11.6-MariaDB-1:10.11.6+maria~ubu2204)
- Web server details
- CloudFlare usage: No

Thank you for your attention to this matter.

Best regards,
Naveen

**Comment by freescout-helpdesk** [comment]
Have you checked FAQ?

**Comment by NaveenKharwar** [comment]
> Have you checked FAQ?

Thank you for your reply.

Yes, we have reviewed the FAQ. Initially, we attempted to resolve this issue using the "[Show Original](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-a-customer-replies-within-the-cited-text-freescout-does-not-show-it)" button, but as shown in the recording, it appears to be ineffective.

**Comment by freescout-helpdesk** [comment]
Update FreeScout to the latest version and try to figure out why the email can not be loaded from the mail server:

![2023-12-29_08-48-16](https://github.com/freescout-helpdesk/freescout/assets/40499291/b9b4d09e-0f11-4cee-92f8-32c241e993ca)

**Comment by NaveenKharwar** [comment]
> Update FreeScout to the latest version and try to figure out why the email can not be loaded from the mail server:
> 
> ![2023-12-29_08-48-16](https://private-user-images.githubusercontent.com/40499291/293315672-b9b4d09e-0f11-4cee-92f8-32c241e993ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzA3NzAsIm5iZiI6MTcwMzgzMDQ3MCwicGF0aCI6Ii80MDQ5OTI5MS8yOTMzMTU2NzItYjliNGQwOWUtMGYxMS00Y2VlLTkyZjgtMzJjMjQxZTk5M2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA2MTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NDE3ZjVhN2UzMGQzMjdiNzAwZDkzODAxZjg4MDU3MDJkM2I2MTE0ODQwZDljMzRhMzAzNGEwOWNmNGU2ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NHibRRkQ74uviVDvfYDOuAHrAN_gI472F-F_NQt-GD0)

Sure! We will perform this and update you.

**Comment by ilyakonovalenko** [comment]
Do you mean your customer added the details to your quoted reply, not in his reply? If so, it is quite unusual case,

**Comment by prajnajogi** [comment]
@ilyakonovalenko Yes, There are instances where we ask users to provide specific details such as URLs, usernames, passwords, etc., or they may add comments directly to the information we've previously sent them. While it might seem uncommon, it helps streamline the communication process and ensures we have all the necessary information to assist them effectively.

**Comment by prajnajogi** [comment]
@freescout-helpdesk We have updated FreeScout to the latest version, yet we are still encountering the same issue. Screencast: https://bsf.d.pr/v/GhFycM

**Comment by ilyakonovalenko** [comment]
> Yes, There are instances where we ask users to provide specific details such as URLs, usernames, passwords, etc., or they may add comments directly to the information we've previously sent them.

This is not how emails work. It is not supposed to add something to previous replies. Quoted replies are just for history. Just ask your users to send you details, not edit your reply.
