### ISSUE TITLE
Global filters or Global workflows?

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#3638]
I have the workflow module installed which works great for each mailbox individually.

We currently have 14 mailboxes (and will be adding more soon), so having to setup a workflow, 14 different times is tedious.

Is there a way to setup a Global workflow, that would apply to all mailboxes?

Or is there a way to setup a Global filter of some kind?

A couple scenarios are as follows:
(1) From a Global workflow perspective (I currently have to set this up in every mailbox seperately), is a new email is still unassigned after 24-hours, then it gets tagged with STILL UNASSIGNED. This would be great to setup only once.
(2) From a Global filter perspective, there is a particular customer with a specific email address that I would like always assigned to me, regardless of which mailbox they send it too.

Thanks

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature for now.

**Comment by jshrek** [comment]
Where in the code does the initial retrieval of emails from server occur?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php
