### ISSUE TITLE
Can you add Timezone for Santiago, Chile?

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#3639]
Hi, I use Eastern Time GMT -4 in order to get the correct time, but as the summer saving is different to other countries, will be nice to have Chile as an option in the configurations. Hope you can add this. Thanks!

![Time Zone 2023-12-31 at 10 41](https://github.com/freescout-helpdesk/freescout/assets/84030633/e8a8965e-f022-427b-bdc8-f75dcc1ac02d)

**Comment by freescout-helpdesk** [comment]
We've added `(GMT-04:00) Atlantic Time (Santiago)` timezone n the `master` branch, it will be published in the next release.

**Comment by DanielBendersky** [comment]
Excelent!

Just one questions. Tiis will consider summer time savings? so we will not need to change it from summer to winter?




Daniel Bendersky
Co Fundador
 +56 9 9998 9122
 ***@***.***
 Av. La Dehesa 1844, of 721, Lo Barnechea
 www.prorenta.cl
  <https://www.facebook.com/Prorenta-109267268128263>  ***@***.***>  <https://www.youtube.com/embed/HHT3oaUjNE0?autoplay=1&mute=0>

**Comment by freescout-helpdesk** [comment]
It should.
