### ISSUE TITLE
[Enhancement Request]: Filter tickets by "Assigned to" users

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-helpdesk/freescout#3641]
It would be a good enhancement if tickets could be filtered by "Assigned to" users.

Screenshot: 
![image](https://github.com/freescout-helpdesk/freescout/assets/34626059/ab1276ce-09d9-4ad0-9a22-6e4af379a790)

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch and will be published in the next release.
