### ISSUE TITLE
Different URLs for mailbox Knowledge Bases?

### ISSUE THREAD

**Issue by sydios** [freescout-helpdesk/freescout#3643]
Hello,

I manage three distinct help desks, each integrated within a single FreeScout installation. Correspondingly, we have established three unique URLs, one for each mailbox: xxx.support, yyy.support, and zzz.support. These URLs all redirect to the same server, with xxx.support serving as the primary domain. Currently, all URLs displayed in FreeScout follow the format xxx.support/....

I'm seeking a solution to dynamically alter these URLs based on the specific mailbox being accessed. For example, when I manually modify the URL from xxx.support/hc/12345 to zzz.support/hc/12345, the appropriate page loads correctly. It would be significantly more convenient if there was a way to directly link to these pages, eliminating the need for manual URL adjustments each time.

Thank you for your assistance!

**Comment by freescout-helpdesk** [comment]
It's no quite clear what you are trying to say. In FreeScout each Knowledge Base is already connected to some mailbox and can have it's own custom domain.
