### ISSUE TITLE
[Enhancement Request]: Filter Reports Data by User

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-helpdesk/freescout#3644]
Adding a filtering option for user-specific data in all reports (Conversations, Productivity, Satisfaction) would be a valuable improvement. Consider incorporating an additional select field to facilitate the filtering of data.

<img width="1680" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/34626059/9e8fb18a-2eea-4dc7-931f-0d85384ac6b2">

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
