### ISSUE TITLE
Translation of mentions module not applied

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3645]
v1.8.115

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/4f5456bc-6131-4c99-b573-6e1691cda7dc)

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/4bddc057-d0a4-4cee-bd19-f8e02758408f)

I didn't translate them manually. Those are the strings coming from the central repository.

**Comment by freescout-helpdesk** [comment]
Fixed in Mentions Module v1.0.18.
