### ISSUE TITLE
Forwarding a single message with relative attachments

### ISSUE THREAD

**Issue by morris4ever69** [freescout-helpdesk/freescout#3647]
Hi, when I try to forward a single message with the "New conversation" button, I see the pre-compiled message with the original text, but without the attachments. Is it possible to include them in the new draft? Thank you.

**Comment by freescout-helpdesk** [comment]
It's not quite clear what you are trying to say. Some screenshots would be helpful.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by morris4ever69** [comment]
Thank you very much! You're doing a very good job with FreeScout :)
