### ISSUE TITLE
Inline images not displaying

### ISSUE THREAD

**Issue by gdandersson** [freescout-helpdesk/freescout#3649]
PHP version: PHP 7.4.3-4ubuntu2.19
FreeScout version: 1.8.108
Database: MySQL
Are you using CloudFlare: No

When a user (using Apple Mail) sends an email with inline images, they are stripped/not shown.

From "Original Message" in FreeScout, under Preview:
<img width="293" alt="Screenshot 2024-01-03 at 15 23 54" src="https://github.com/freescout-helpdesk/freescout/assets/52959348/53cdac87-1a10-4d0b-af89-9969a883b633">

The actual code (from Body) looks like this:
`<img alt="image0.jpeg" src="cid:BDA1BB86-2991-457D-8094-4B8F3E72318E-L0-001"><img alt="image1.jpeg" src="cid:10C9CF5E-91CF-434F-983B-13CC317FECB3-L0-001"><img alt="image2.jpeg" src="cid:0B821A22-7ED0-49F3-A326-2144A32454C8-L0-001">
`

In the normal message view, there is just an empty p-tag.

**Comment by freescout-helpdesk** [comment]
Try to add `APP_NEW_FETCHING_LIBRARY=true` parameter to the .env file and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache).

**Comment by freescout-helpdesk** [comment]
Also make sure your console PHP is able to save files: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by gdandersson** [comment]
Yeah, I'm ashamed, forgot to check the logs. Found: failed to open stream: Permission denied

chmod and all is good. Thanks!
