### ISSUE TITLE
Don't send previous responses/replies

### ISSUE THREAD

**Issue by rNianios** [freescout-helpdesk/freescout#365]
Hi,

When as an engineer/admin you respond to a ticket it sends back to the customer previous responses/replies which might be a bit confusing. Is there any way to disable this? If not could this be added in the future?

Thanks

**Comment by freescout-helpdesk** [comment]
Yes. Such option can be added in the future.

Would you prefer to have it for each mailbox or just a global option?

**Comment by rNianios** [comment]
Hi,

Thanks for your reply. I currently have only one mailbox so it doesn't make
a difference to me. Maybe somebody else can answer that question.

**Comment by matsn0w** [comment]
I guess being abled to choose on a per mailbox basis is the most flexible, but I think most people don't want this at all. Most email programs show the history themselves.

**Comment by rNianios** [comment]
I was testing freescout using Gmail and it was quite confusing as Gmail
shows my admin response including all the other replies and then shows all
the other emails on the thread as well.

**Comment by matsn0w** [comment]
I would suggest turning it off by default, but make it optional on a per mailbox basis.

**Comment by freescout-helpdesk** [comment]
So now application will send only support agent reply without full conversation history in emails to customers. Later if needed the option to enable sending full conversation history can be added.

**Comment by tiredofit** [comment]
Maybe an alternative look at this would be to allow an option for 
- no history
- previous response from customer 
- all history

Then I think you've covered all the edge cases as well/meeting in the middle.

**Comment by MathijsA** [comment]
> So now application will send only support agent reply without full conversation history in emails to customers. Later if needed the option to enable sending full conversation history can be added.

Is this option implemented jet? if not, could this be added?
We would like our recipients to get the full history.
