### ISSUE TITLE
Allowing variables to be used in email fields.

### ISSUE THREAD

**Issue by sgmcmiller** [freescout-helpdesk/freescout#3650]
We would like to use a variable in the cc field in order to cc the customer onto the forwarded email. We are attempting to create a workflow that will assist in moving feature requests from our help desk and in to GitLab. I have created a feature request as well, as I am not sure what would be more appropriate. 

![image](https://github.com/freescout-helpdesk/freescout/assets/136723815/c83b4055-75f4-4f09-8527-025dd748fb52)

PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version: 1.8.115    
Database:  Mysql (8.0.35-0ubuntu0.22.04.1)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
