### ISSUE TITLE
Customers Management (CRM) Module export also Mailbox Name 

### ISSUE THREAD

**Issue by sydios** [freescout-helpdesk/freescout#3653]
Hello,

Can the mailbox name also be added to the export file? Right now it exports all the customers and you can't differentiate them from each other.

Thanks!

**Comment by freescout-helpdesk** [comment]
Unfortunately not.

**Comment by sydios** [comment]
Could I put in a feature request? Since you can sort them by mailbox it should be very easy to add this also to the export, or?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-have-separate-contactscustomers-per-mailbox

**Comment by sydios** [comment]
I think I maybe didn't make it clear enough. I mean the module CRM. It exports the customers from all mailboxes in one file without a field from which mailbox they are. But if you sort them by mailbox in the CRM module itself it shows them by mailbox. 

![image](https://github.com/freescout-helpdesk/freescout/assets/7102852/bc7fba92-e13e-4f46-8ce6-36b033f640e5)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
