### ISSUE TITLE
Broken file in the origin mailbox breaks fetching of the messages

### ISSUE THREAD

**Issue by mattly6** [freescout-helpdesk/freescout#3654]
Hi,

A few days ago I encountered an issue connected to a file in the origin mailbox being broken (somehow) - in the mailbox (from which the mail is fetched) it was shown as IMAGE file (with no extension) and when I tried to download it, the link pointed to a broken URL on the mail server and the server sent back 500-something error code, I think it was 502.

Point is: 
Freescout failed to fetch all of the mail because of the above message (most probably the first in the array of messages to be fetched) being broken and has shown error:
**_Folder: INBOX; Error: Undefined property: stdClass::$subtype_**
So I guess that the broken attachment caused an IMAP error (?)

When I deleted the "faulty" message from the origin mailbox, fetching was restored and worked as usual.

Sadly, I didn't receive a message about mail fetching being broken, so for 2+ hours I was unaware of the problem (don't get me like I'm trying to point fingers, just providing additional info in case it could help - you guys are great and doing a good job).

I don't know if such solution is possible, but wouldn't it be good to let the system skip the messages for which it encountered problems, proceed with fetching the rest of the messages and let the admin know which one(s) caused the problem so it (they) could be checked?

Unfortunately, I didn't save the broken message anyhow, so it's gone...

I'm using IMAP with SSL to fetch the mail.

PHP version: PHP 8.1.2-1ubuntu2.14 (cli)
FreeScout version: 1.8.110
Database: MySQL 
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
What was IMAP folder name for that message?

**Comment by mattly6** [comment]
It was just regular INBOX, the only folder we use for fetching.

I forgot to mention this, but the message itself was a response to the
previous ones (that didn't cause any problem), if that's any help.

pt., 5 sty 2024, 06:16 użytkownik FreeScout ***@***.***>
napisał:

**Comment by freescout-helpdesk** [comment]
We've double checked - when an error occurs fetching some message other messages should be successfully fetched. So without the original email causing the issue it will be impossible to reproduce and fix this issue.

**Comment by mattly6** [comment]
> We've double checked - when an error occurs fetching some message other messages should be successfully fetched. So without the original email causing the issue it will be impossible to reproduce and fix this issue.

Alright, if the error occurs again I'll save the email and re-open the issue.

Thank you for your time.

**Comment by mattly6** [comment]
>We've double checked - when an error occurs fetching some message other messages should be successfully fetched. So without the original email causing the issue it will be impossible to reproduce and fix this issue.

Alright, if the error occurs again I'll save the email and re-open the issue.

Thank you for your time.

**Comment by mattly6** [comment]
>We've double checked - when an error occurs fetching some message other messages should be successfully fetched. So without the original email causing the issue it will be impossible to reproduce and fix this issue.

Alright, if the error occurs again I'll save the email and re-open the issue.

Thank you for your time.
