### ISSUE TITLE
Questions re mailbox alias

### ISSUE THREAD

**Issue by minghuiyu** [freescout-helpdesk/freescout#3655]
A Microsoft 365 mailbox, e.g.: feedback@company.com has multiple aliases. e.g.: feedback.locationA@company.com, feedback.locationB@company.com.

Can I:

1. Create multiple mailboxes in FreeScout, with each mailbox corresponds to one email alias.
2. When fetching emails from feedback@company.com (the only one real mailbox on Microsoft 365), each mailbox in freescount only fetch emails from Microsoft that recipient address is the alias this freescount mailbox uses.

e.g.:

In freescount, I'd like to have two mailboxes, feedback.locationA@company.com and feedback.locationB@company.com

When fetching emails, both mailboxes fetch emails from feedback@company.com. However, (freescount mailbox) feedback.locationA@company.com only fetch emails sent to feedback.locationA@company.com, does not fetch emails sent to feedback@company.com or feedback.locationB@company.com

Thanks.

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
