### ISSUE TITLE
urgent. gmail fetching problems Folder: Starred; Error: [NONEXISTENT] Unknown Mailbox: Starred (now in authenticated state) (Failure)

### ISSUE THREAD

**Issue by epp289** [freescout-helpdesk/freescout#3656]
Hello in two freescout accounts i get the same gmail fetching problems 
Folder: Starred; Error: [NONEXISTENT] Unknown Mailbox: Starred (now in authenticated state) (Failure)
Folder: Important; Error: [NONEXISTENT] Unknown Mailbox: [Gmail] (now in authenticated state) (Failure)
Folder: Sent Mail; Error: [NONEXISTENT] Unknown Mailbox: [Gmail] (now in authenticated state) (Failure)
Folder: [Gmail]; Error: [NONEXISTENT] Unknown Mailbox: [Gmail] (now in authenticated state) (Failure)

etc
i clicked "Get folders" and several other thing with no luck
any idea please? 
![image](https://github.com/freescout-helpdesk/freescout/assets/75975706/8f17789f-aca5-47d0-b091-761cc5835dd0)

**Comment by freescout-helpdesk** [comment]
Leave just INBOX folder.

**Comment by epp289** [comment]
Thank you. 
No errors now but it doesn't fetch the emails. i sent 2 test emails to the gmail account from other accounts. It shows them as read in the gmail account (if i open gmail,com directly) but it doesn't show them in them freescount inbox. (no other app connects to this gmail).

however i send through freescout using this gmail account succesfully

**Comment by epp289** [comment]
i am using cloudflare's nameservers if that matters

![image](https://github.com/freescout-helpdesk/freescout/assets/75975706/896d674a-01ef-4f13-90ab-9e926a4f2a0d)
![image](https://github.com/freescout-helpdesk/freescout/assets/75975706/2cc02099-7c7a-49a9-a07b-00c97e7fc76c)

**Comment by epp289** [comment]
![image](https://github.com/freescout-helpdesk/freescout/assets/75975706/55823010-c370-4379-b656-8886a5640ca9)
