### ISSUE TITLE
Custom folders don't show Closed

### ISSUE THREAD

**Issue by vigleikn** [freescout-helpdesk/freescout#3657]
If a ticket is set to closed and tagged to appear in a custom folder, the ticket erronously does not show up in the custom folder despite this Status: Closed being selected for the folder.

<img width="734" alt="bilde" src="https://github.com/freescout-helpdesk/freescout/assets/151235360/f1cab7f8-9b08-41c9-954d-484e6eb98cc2">

**Comment by freescout-helpdesk** [comment]
Unfortunately we can't reproduce the issue.
