### ISSUE TITLE
Original message preview fails to fetch the message via IMAP

### ISSUE THREAD

**Issue by dvdjaco** [freescout-helpdesk/freescout#3659]
```
PHP version: 8.2.14
FreeScout version: 1.8.115
Database: Mysql (10.6.7-MariaDB) 
Are you using CloudFlare: No
```

We sometimes need to see the original body of a message. If we go to *Show Original* --> *Preview* in the message's drop down menu, we only see the truncated body with the following error message:

![image](https://github.com/freescout-helpdesk/freescout/assets/1502076/714ac67d-adab-48f1-abf5-0a75e4465f61)

The mailbox is configured with IMAP, fetched messages are not deleted from the IMAP server. We see no fetch errors in the `Fetch Errors` log or in the `App Logs`. Any pointers on how to debug this would be very appreciated.

**Comment by freescout-helpdesk** [comment]
Duplicate: https://github.com/freescout-helpdesk/freescout/issues/3658#issuecomment-1878767720
