### ISSUE TITLE
Feature request: adding images to mailbox signature

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#366]
Hey there, it's me again :)

I was wondering if it is possible to add some more options to the signatures. I like the variables for name and function, etc. but I'm missing things like images.

We want to add our company logo to the signature.

Would be great if this will be implemented!

**Comment by sam-suresh** [comment]
Quick tips: You can switch to < > Code editor and add HTML for images.

`<img src="https://cdn.shortpixel.ai/client/banner-RED.png">`

**Comment by matsn0w** [comment]
Thank you for your comment, but this doesn't seem to be working. The `img` tag is removed once saved. It looks like it is filtered automatically.
