### ISSUE TITLE
spam folder doesn't show rejected emails

### ISSUE THREAD

**Issue by epp289** [freescout-helpdesk/freescout#3660]
i was wondering why i hadn't received any replies to my emails the week. i found out that the spam filter was rejecting them
i had enabled the "Filter Using Spam-Filtering Altorithm & Learning". I disabled it and new emails came up
Also when i click (and several other times in the past) on spam folder it says "There are no conversations here" . and i am  using the freescout for more than a year. how is it possible not to have at least one email message shown up there?

**Comment by freescout-helpdesk** [comment]
Either there was no emails filtered as spam or someone removed them.
