### ISSUE TITLE
Nice to have icons view when we want to choose one.

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#3661]
Hi, wen we want to assign an icon to a custom folder, we only see the list of names of the icons. Will be very usefull to have the name AND the icon, so will be easier to choose the icon we want. Hope you can add this in the near future. 😄

![2024-01-06 at 11 39](https://github.com/freescout-helpdesk/freescout/assets/84030633/e8c98d39-f2f2-40b8-ab92-6fcbdac34ff0)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
