### ISSUE TITLE
HTML messages not displayed correct

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3664]
This is urgent. We have migrated our whole company to FreeScout last night. Everyone is getting notification via Email from our CRM with topics belonging to our customers, but they can't be read anymore in the usual way. Those emails contain a couple of metadata about the customer and most important the URL to the position in the CRM where the topic is located.
Unfortunately this section is not getting rendered and is completely removed by FreeScout.

This is how it has to look like:
![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/89dfb8e5-08c4-488d-9205-deea45369494)

and this is it what happens in FreeScout:
![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/61ee9286-cc9c-4e6a-a42a-866276d45cb3)

It's changing the colour (not important) and removing the whole section (where the red arrow was) with the URL (very important).
If a user clicks on "show original" the original view can be retrieved, but the URL isn't working there as expected because it's trying to open it within the frame when it should be opened in a new window.

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#some-emails-are-empty-or-truncated-in-freescout

**Comment by janselato** [comment]
_I stumbled on this issue earlier today and solved it (for us). You can edit the allowed HTML and CSS in /config/purifier.php. After editing, run php artisan config:clear to clear the cache._
Source: https://github.com/freescout-helpdesk/freescout/issues/1719#issuecomment-1656112523
Here is my settings file that I prepared today to achieve greater compatibility. Check if it works for you:
`<?php
/**
 * Ok, glad you are here
 * first we get a config instance, and set the settings
 * $config = HTMLPurifier_Config::createDefault();
 * $config->set('Core.Encoding', $this->config->get('purifier.encoding'));
 * $config->set('Cache.SerializerPath', $this->config->get('purifier.cachePath'));
 * if ( ! $this->config->get('purifier.finalize')) {
 *     $config->autoFinalize = false;
 * }
 * $config->loadArray($this->getConfig());.
 *
 * You must NOT delete the default settings
 * anything in settings should be compacted with params that needed to instance HTMLPurifier_Config.
 *
 * @link http://htmlpurifier.org/live/configdoc/plain.html
 */

return [
    'enabled'       => false,
    'encoding'      => 'UTF-8',
    'finalize'      => true,
    'cachePath'     => storage_path('app/purifier'),
    'cacheFileMode' => 0755,
    'settings'      => [
        'default' => [
            'HTML.Doctype'             => 'HTML 4.01 Transitional',
	    //Custom value:
            'HTML.Allowed'             => 'div[style|class],b,strong,i,em,u,a[href|title|class|style],ul,ol,li,p[style|class],br,span[style|class],img[width|height|alt|src|style],table[style|border|bgcolor|cellspacing|cellpadding|border|width|class],tr[bgcolor],td[style|colspan|rowspan|width|bgcolor|border|valign|align|class],th[style|colspan|rowspan],thead,tfoot,tbody,blockquote,pre,s,strike,font[style|color|class],h1[style|class],h2[style|class],h3[style|class],h4[style|class],h5[style|class],h6',
	    // Standard value:
            //'HTML.Allowed'             => 'div[style],b,strong,i,em,u,a[href|title],ul,ol,li,p[style],br,span[style],img[width|height|alt|src],table[width|class],tr[bgcolor],td[style|colspan|rowspan|width],th[style|colspan|rowspan],thead,tfoot,tbody,blockquote,pre,s,strike,font[style|color],h1,h2,h3,h4,h5,h6',
            //Custom value:
            'CSS.AllowedProperties'    => 'display,overflow,border-radius,letter-spacing,white-space,font-size,margin,background,text-transform,max-width,max-height,width,height,font,padding,font-family,border-color,font-weight,font-style,text-decoration,color,background-color,text-align,border,border-top,border-left,border-bottom,border-right',
	    // Standard value:
	    //'CSS.AllowedProperties'    => 'font-weight,font-style,text-decoration,color,background-color,text-align,border,border-top,border-left,border-bottom,border-right',
            'AutoFormat.AutoParagraph' => true,
            'AutoFormat.RemoveEmpty'   => true,
            //Custom value:
            'CSS.Proprietary' => true,
            //Custom value:
	    'CSS.AllowTricky' => true,
            'URI.AllowedSchemes'   => [
                'http' => true,
                'https' => true,
                'mailto' => true,
                'ftp' => true,
                'nntp' => true,
                'news' => true,
                'tel' => true,
                'data' => true,
            ],
        ],
        'test'    => [
            'Attr.EnableID' => 'true',
        ],
        'youtube' => [
            'HTML.SafeIframe'      => 'true',
            'URI.SafeIframeRegexp' => '%^(http://|https://|//)(www.youtube.com/embed/|player.vimeo.com/video/)%',
        ],
        'custom_definition' => [
            'id'       => 'html5-definitions',
            'rev'      => 1,
            'debug'    => false,
            'elements' => [
                // http://developers.whatwg.org/sections.html
                ['section', 'Block', 'Flow', 'Common'],
                ['nav',     'Block', 'Flow', 'Common'],
                ['article', 'Block', 'Flow', 'Common'],
                ['aside',   'Block', 'Flow', 'Common'],
                ['header',  'Block', 'Flow', 'Common'],
                ['footer',  'Block', 'Flow', 'Common'],

                // Content model actually excludes several tags, not modelled here
                ['address', 'Block', 'Flow', 'Common'],
                ['hgroup', 'Block', 'Required: h1 | h2 | h3 | h4 | h5 | h6', 'Common'],

                // http://developers.whatwg.org/grouping-content.html
                ['figure', 'Block', 'Optional: (figcaption, Flow) | (Flow, figcaption) | Flow', 'Common'],
                ['figcaption', 'Inline', 'Flow', 'Common'],

                // http://developers.whatwg.org/the-video-element.html#the-video-element
                ['video', 'Block', 'Optional: (source, Flow) | (Flow, source) | Flow', 'Common', [
                    'src'      => 'URI',
                    'type'     => 'Text',
                    'width'    => 'Length',
                    'height'   => 'Length',
                    'poster'   => 'URI',
                    'preload'  => 'Enum#auto,metadata,none',
                    'controls' => 'Bool',
                ]],
                ['source', 'Block', 'Flow', 'Common', [
                    'src'  => 'URI',
                    'type' => 'Text',
                ]],

                // http://developers.whatwg.org/text-level-semantics.html
                ['s',    'Inline', 'Inline', 'Common'],
                ['var',  'Inline', 'Inline', 'Common'],
                ['sub',  'Inline', 'Inline', 'Common'],
                ['sup',  'Inline', 'Inline', 'Common'],
                ['mark', 'Inline', 'Inline', 'Common'],
                ['wbr',  'Inline', 'Empty', 'Core'],

                // http://developers.whatwg.org/edits.html
                ['ins', 'Block', 'Flow', 'Common', ['cite' => 'URI', 'datetime' => 'CDATA']],
                ['del', 'Block', 'Flow', 'Common', ['cite' => 'URI', 'datetime' => 'CDATA']],
            ],
            'attributes' => [
                ['iframe', 'allowfullscreen', 'Bool'],
                ['table', 'height', 'Text'],
                ['td', 'border', 'Text'],
                ['th', 'border', 'Text'],
                ['tr', 'width', 'Text'],
                ['tr', 'height', 'Text'],
                ['tr', 'border', 'Text'],
            ],
        ],
        'custom_attributes' => [
            ['a', 'target', 'Enum#_blank,_self,_target,_top'],
        ],
        'custom_elements' => [
            ['u', 'Inline', 'Inline', 'Common'],
        ],
    ],

];`

**Comment by mokkin** [comment]
I already tried to apply this manually, cleared cache and config, but I couldn't see a difference :(
This is the example source code of such a notification after clicking on "show original":

```html
<!--<![endif]-->
        <table class="wrapper bg-color" cellpadding="0" cellspacing="0" role="presentation">
            <tbody>
                <tr>
                    <td>
                        <div role="banner">
                            <div class="pre-header column">
                                <div> </div>
                            </div>
                            <div class="header column">
                                <!--[if mso]><table align="center" class="header" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="width: 600px"><![endif]-->
                                <div class="logo">
                                    <div class="logo-center">
                                        <img src="https://thumbs.example.com/thumb/bWFuZGFudF9sb2dvL2Jlc3RmaXQvMzAweC8xMDAxL2xvZ28ucG5nOXlhUx%252F1xtAX%252FEYU2oYmYNSGGIOWrCpDaNRz7dPa4xiiC4%252FlJc84%252FiFt3d5KAovcu8RTKC4wNpGY7NCodu7Htg%253D%253D?1531927817" alt="">
                                    </div>
                                </div>
                                <!--[if mso]></td></tr></table><![endif]-->
                            </div>
                        </div>
                        <div role="section">
                            <div class="body column size-14">
                                <div class="body-wrapper bg-color-text">
                                    <!--[if mso]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="width: 600px"><![endif]-->
                                    <div class="pre-content">
                                        <div> </div>
                                    </div><div class="content">
    <h2><strong>Moin moin,</strong></h2>
    <p class="size-16">es wurde ein neues Dokument für Dich hinterlegt.</p>
    <p class="size-16">Kunde:<br><strong>Tommy Testinger</strong></p>
    <p class="size-16">Datum:<br><strong>15.01.2024 23:33</strong></p>
    <p class="size-16">Betreff:<br><strong>test</strong></p>
    <p class="size-16">
        Verträge:<br>
                <strong>Boot - 1234567890-5</strong><br>
            </p>
</div>

<div class="post-content">
    <div class="btn btn-flat fullwidth btn-large">
        <!--[if !mso]><!--><a href="https://www.example.biz/portal/?show=kunde&kunde=5002970262&Job_archiveintrag=02d23241cb1a14f0712c">zum Dokument</a><!--<![endif]-->
        <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" href="https://www.example.biz/portal/?show=kunde&kunde=5002970262&Job_archiveintrag=02d23241cb1a14f0712c" style="width:560px" arcsize="9%" fillcolor="#DCEDF2" stroke="f"><v:textbox style="mso-fit-shape-to-text:t" inset="0px,11px,0px,11px"><center style="font-size:14px;line-height:24px;color:#44A8C7;font-family:sans-serif;font-weight:bold;mso-line-height-rule:exactly;mso-text-raise:4px">zum Dokument</center></v:textbox></v:roundrect><![endif]-->
    </div>
</div>

                
  
                                    <!--[if mso]></td></tr></table><![endif]-->
                                </div>
                            </div>
                            <div role="contentinfo">
                                <div class="footer column">
                                    <div class="footer-wrapper">
                                        <!--[if mso]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="width: 400px;" valign="top"><![endif]-->
                                        <p class="footer-signature size-12">
                                           example <br>Kexample<br>example<br><br>Telefon: example<br>E-Mail: info@example.de<br><br>Handelsregister example HRB-Nr. example<br>Geschäftsführung: example<br></p>
                                        <!--[if mso]></td></tr></table><![endif]-->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
```

**Comment by mokkin** [comment]
I tested right now with v1.8.118 and as mentioned before unfortunately there is no effect on new messages like the one in my last post.

Could you please reopen @freescout-helpdesk ?

**Comment by freescout-helpdesk** [comment]
Your post https://github.com/freescout-helpdesk/freescout/issues/3664#issuecomment-1892840189 shows HTML from "Show Original". The message shown in conversation will never be the same as it's being sanitized and purified.

**Comment by Marphies** [comment]
Freescout is crashing  since release 1.8.118 on some messages with the following error:
`Whoops, looks like something went wrong — check logs in /storage/logs`

App Logs is saying:
`ctype_lower(): Argument of type bool will be interpreted as string in the future (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) {"userId":2,"email":"****@****.com","exception":"[object] (ErrorException(code: 0): ctype_lower(): Argument of type bool will be interpreted as string in the future (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) at /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Length.php:81, ErrorException(code: 0): ctype_lower(): Argument of type bool will be interpreted as string in the future (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) at /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Length.php:81, ErrorException(code: 0): ctype_lower(): Argument of type bool will be interpreted as string in the future (View: /var/www/html/resources/views/conversations/partials/thread.blade.php) at /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Length.php:81, ErrorException(code: 0): ctype_lower(): Argument of type bool will be interpreted as string in the future at /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Length.php:81)`

**Comment by mokkin** [comment]
Honestly I have no idea if this is related, but maybe it's a good idea to update HTML Purifier. The version included is 4.12.0 and around five years old. This was long time before PHP 8.
The latest release is https://github.com/ezyang/htmlpurifier/releases/tag/v4.17.0

**Comment by mokkin** [comment]
There is also https://github.com/ezyang/htmlpurifier/issues/277 related to `itemscope` etc. in their source repo. Maybe that's the solution?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3721

**Comment by smilemittal** [comment]
Please check your commit 
https://github.com/freescout-helpdesk/freescout/commit/0826102f6e97d918dd5091fd4a0bbf4679870e76

It is not fixing the issue, it removes all email content, just leaving the only link behind.
![image](https://github.com/freescout-helpdesk/freescout/assets/13959872/a8ace2d6-8c46-4431-9cbb-fba0d42785c2)

Original content
![image](https://github.com/freescout-helpdesk/freescout/assets/13959872/7daa6d03-f139-4041-bcd9-01f8a6c171c1)
