### ISSUE TITLE
mentions module: no users selectable

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3666]
Since yesterday we can't mention any users by typing `@`

In the browser console there are no hints nor did I remove the rights of any users.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/df331ef5-b817-425a-bc6c-0dd790c3bd84)

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch of FreeScout and will be published in the next release.

**Comment by nvnes-sba** [comment]
Nice to see it will be available in the next release.
Could this be the same issue with the table option in summernote?

![image](https://github.com/freescout-helpdesk/freescout/assets/132343397/a1d381cf-0b14-4f80-b539-a5cbd6b4a740)

**Comment by iantearle** [comment]
I'm seeing this too, is this error in console related:
`TypeError: undefined is not an object (evaluating 'mentions_users.length')`
I also have in console log:

`TypeError: null is not an object (evaluating 'taskInput.addEventListener')`

Is there a timescale for release?
