### ISSUE TITLE
memory size exhausted Html2Text.php

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3667]
I'm getting this error once a minute:
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 18015496 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 18015496 bytes) at /path/to/freescout/vendor/html2text/html2text/src/Html2Text.php:369)
[stacktrace]
#0 {main}
"}
                    
```
Any ideas what can I do against this?
Might this be connected with https://github.com/freescout-helpdesk/freescout/issues/3664 ?

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Increase `memory_limit` in your web and console PHP.

**Comment by mokkin** [comment]
Unfortunately I can't raise the limit (on this machine) because it's a shared hosting.
Nevertheless it seems to be working.

My question is: Why does FreeScout need so much memory? It doesn't cache all the emails in memory or am I wrong? Otherwise it would need tons of memory in big companies.

**Comment by freescout-helpdesk** [comment]
It looks like you have some quite large email:
https://github.com/freescout-helpdesk/freescout/blob/dist/vendor/html2text/html2text/src/Html2Text.php#L369

You can download it as EML file from your mail server to check its size.

**Comment by mokkin** [comment]
I can imagine that. For sure there are some big ones. Two nights ago I migrated thousands of emails from our old mail server to our new one with FreeScout on top.
Does the log show which emails are problematic? Otherwise it's really difficult to determine which of the ten inboxes is problematic...

**Comment by freescout-helpdesk** [comment]
Where do you have this error "Allowed memory size of 134217728 bytes exhausted"? In which log?

**Comment by mokkin** [comment]
It appeared in the app log > laravel.log
The last occurance was two days ago, the right after the night when I imported tons of email from the old system. Since yesterday the error doesn't occure again. Maybe it was just "too much" importing...

I already shared the full text of the error. No matter if in webinterface or in the downloaded log file - there isn't displayed more in each entry.

**Comment by freescout-helpdesk** [comment]
> It appeared in the app log > laravel.log

In this case unfortunately it's impossible to determine which email exactly caused this issue.

**Comment by mokkin** [comment]
Hopefully it's gone after migration - closing this for now.
I'll report it here if it occurs again.
