### ISSUE TITLE
Installer always redirects to login and leads to "not found" error

### ISSUE THREAD

**Issue by YetAnotherHam** [freescout-helpdesk/freescout#3668]
Hello team,
I am struggeling with the installation on Ubuntu 20.04, PHP7.4, Apache Webserver.
There are already several Wordpress and Nextcloud instances in different vHosts on the same system.
But for some reason, I cannot get Freescout running.

I followed the installation manual and tried the installation via download build: https://freescout.net/download/
as well as git clone option. The web installer just gives me a "not found" error so I tried a manual install.
But editing the .env doesn't change anything at all.
What I noticed is, that after running the web installer, an skeleton .env will be created with just the app key but no more information.
Access and error logs don't produce any helpful leads.
All files are owned by www-data (user and group).
I've created a dummy php-file in the public folder of Freescout and in general, php is working.

Any advice, where to start with debugging to get this running?
Many thanks
B.

**Comment by YetAnotherHam** [comment]
I did a little more debugging and it looks like .htaccess or rewrite topic.
When just typing the URL like https://link.tomyfreescout.com, I got redirected to https://link.tomyfreescout.com which results in a 404 error. But if I type https://link.tomyfreescout.com/index.php the URL changes and I get a login screen but with a very basic layout. I assume, no css or anything else can be loaded.
This is, what the vHosts config looks like:

ServerSignature Off
ServerName EDITED myservername
Include /etc/letsencrypt/options-ssl-apache.conf
Options Indexes FollowSymLinks
RewriteEngine on

    <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>

#    <IfModule mod_negotiation.c>
#      Options MultiViews
#    </IfModule>

<Directory "/var/www/cloud.faw.de/public">
  Require all granted
  AllowOverride All
  Options FollowSymLinks MultiViews
</Directory>

**Comment by YetAnotherHam** [comment]
More debugging. The previously mentioned layout topic was due to wrong privileges after cloning all files again.
After fixing that, I get a nice login screen, when accessing https://link.tomyfreescout.com/index.php/login but after typing in the credentials, I get redirected to https://link.tomyfreescout.com/login and receive the 404 again.
Any hint is most welcome. :)

**Comment by YetAnotherHam** [comment]
More debugging: With nginx it is running. So I can narrow it down to the Apache configuration.
Can anybody confirm, that the apache setup as described is correct?

**Comment by freescout-helpdesk** [comment]
> Can anybody confirm, that the apache setup as described is correct?

Here is the recommended Apache config: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#62-apache

**Comment by YetAnotherHam** [comment]
That was the first config I've tried and this leaded to the result, as described above. :(

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. You may need to figure it out yourself.
