### ISSUE TITLE
Feature Request: Transferring Message to Any Shared Mailbox

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#367]
This may or may not be a unique case, but in large organizations where some teams are on their own island, some messages get redirected improperly to the incorrect team. Would there be possibility for functionality to exist for lets just say an agent in one mailbox be able to transfer the entire content of the message and history over to a new shared inbox?

An example of use case would be:
- Message comes in to general mailbox
- Agent realizes that this is definitely an HR matter
- Transfers to HR Shared Inbox (can no longer see the content/messages)
- Freescout itself somehow logs that it has been forwarded by either Agent or just the Shared Inbox itself. 

Our organization embarrassingly has over 70 shared inboxes and I feel I would be able to implement Freescout if it contained this functionality (either as addon/core)

**Comment by matsn0w** [comment]
As a work-around: you could just forward the message to another mailbox, by using the Forward option. After that, you simply delete the message from the mailbox.

**Comment by tiredofit** [comment]
We currently use that "sneakernet" workflow right now which creates a bit of a mess in our sent items (not everyone has good housekeeping with keeping their inboxes) - But I think the more glaring issue with that approach is that the message would be perceived as an issue with being the "info" mailbox being the client (since it was the that forwarded) - unless it is smart enough to detect the original message sender?

**Comment by freescout-helpdesk** [comment]
Have you tried "Move" button?

![2019-11-14_19-42-05](https://user-images.githubusercontent.com/40499291/68877299-e45a0080-0716-11ea-9851-1f1db296e07d.png)

**Comment by tiredofit** [comment]
OK, I am embarrassed that I havent noticed it's already been implemented in some fashion, unfortunately I don't see it in my test install of `1.3.10` - I just attempted to add another mailbox and assign myself permissions in hopes that it would appear however is still not appearing.

I can try a fresh install. In the meantime can I clarify, does the user have to have access to both of the shared inboxes as well in this scenario? Ideally I'd like for them to just be able to move the message but not see the contents of the other shared inbox.

Many thanks for your patience with me.

**Comment by tiredofit** [comment]
OK, I have tried with a fresh install and I can see how this works with two mailboxes connected to the same user permissions which then shows the "Move" option to appear - slick. 

This method does open some privacy concerns on my end for teams that normally don't work in the "moved" mailbox seeing things that they shouldn't. With little to no development skills in PHP/Laravel how difficult would this be to implement a feature that allowed a mailbox to have some sort of boolean value allowing it to move to any box that is on the system (or configurable mailboxes) without having permission to see the actual mailbox?

**Comment by freescout-helpdesk** [comment]
It is possible.

**Comment by freescout-helpdesk** [comment]
Probably a better solution will be to allow to move conversation by entering mailbox's email address (in addition to selecting a mailbox from the list of user mailboxes). In this case there is no need to create additional option for the mailbox and support agents will not see mailboxes where they don't have an access in the "Move conversation" dialog.
