### ISSUE TITLE
Pagination in Saved Replies

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3672]
Hi @freescout-helpdesk 

Can we paginate "Saved Replies" list? As i have 500+ Saved Replies and it takes too long to load that page and edit anything.

Is there any way to optimize it?

I am using FS 1.8.115

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by mahavirn** [comment]
Hi @freescout-helpdesk 

I upgraded FreeScout to latest version: 1.8.118 and the problem is still there?

Not sure why it has been marked as "Closed"
