### ISSUE TITLE
Create a permission for user not edit Time Tracking

### ISSUE THREAD

**Issue by stratrock** [freescout-helpdesk/freescout#3673]
Today, any user can edit Time Tracking for all reports, even if the user is not owner of the report. 

This may cause users to start altering other users' time entries.

If possible, a permission flag/attribute that the Admin can define which users can edit Time Tracking hours.

PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
