### ISSUE TITLE
Error when upgrading to Version 1.8.117

### ISSUE THREAD

**Issue by cymuc** [freescout-helpdesk/freescout#3674]
Error when upgrading to Version 1.8.117

Call to undefined method App\Misc\Helper::shellExec() {"userId":388,"email":"redacted@example.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Misc\\Helper::shellExec() at /var/www/anfrage/app/Http/Controllers/SystemController.php:56)

PHP version: PHP 7.4.3-4ubuntu2.19 
FreeScout version: 1.8.117  
Database: Mysql (5.5.5-10.3.38-MariaDB-0ubuntu0.20.04.1)
Are you using CloudFlare:  No

The application seems to be working fine after the upgrade without further issues.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
