### ISSUE TITLE
deleted folder visible in closed folder

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3675]
We do not have licensed the deleted folder module, but after clicking on "closed" it appears an is accessible. This happens only while being on "closed", not on the other folders.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/949350fa-f89d-44c8-bb5c-6a64d48046ae)

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/76a67f31-9b40-4294-901c-7cddfb9a48a7)

PHP version: 8.2.12
FreeScout version:  1.8.117
Database: MySQL
Are you using CloudFlare:  No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#trash-deleted-folder-is-not-visible
