### ISSUE TITLE
OAuth as authorization backend with LDAP as identity backend

### ISSUE THREAD

**Issue by OttoWinter** [freescout-helpdesk/freescout#3676]
Hi,
I have a question on whether the oauth module supports a certain setup. From the [contact us](https://freescout.net/contact-us/) page it seems like the github issues are the place where this should be asked, if not, please excuse me :)

I'm already using the LDAP module, but ideally for security reasons I want to switch to a setup where LDAP is used to synchronize users, and [the OAuth module](https://freescout.net/module/oauth-login/) for authenticating users (this way, the user password is not exposed to the ticket system).

Is this mode supported by the LDAP&OAuth modules - I'd like to know before I buy the OAuth module :)

Thanks!

**Comment by freescout-helpdesk** [comment]
It should work as long as users' emails are same across your LDAP & oAuth.

**Comment by OttoWinter** [comment]
Thanks!
