### ISSUE TITLE
Workflow module: "Do not include signature" option when using reply to conversation

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3677]
In the workflow module on reply to conversation we have ticked "Do not include signature" to avoid displaying the "Workflow" user.
Unfortuantely the signature is sent no matter if I tick the option or not.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/84a6a83e-93f2-4461-b3fb-43d81947de14)

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/c3422e70-7c15-4a1e-b586-b7f3185276ca)

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.63
