### ISSUE TITLE
Page info of wrong type in list api

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3679]
When I use ListUsers or ListTickets API,

When I dont give paging info in query params, the page response is fine as follows 

"page": {
        "size": 50,
        "totalElements": 3,
        "totalPages": 1,
        "number": 1
    }

When but when I give the page info in query params, I get this 

"page": {
        "size": "2",
        "totalElements": 3,
        "totalPages": 2,
        "number": 1
    }

If you observe page.Size is string here. It should be number. It happened to me in both list users and list tickets api. Please check on priority

**Comment by freescout-helpdesk** [comment]
Fixed in API & Webhooks Module v1.0.72
