### ISSUE TITLE
don't display delete (trash) symbol in mailbox for users

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3680]
In  our config users are not allowed to delete conversation. They can only close them for example.

Unfortunately the trash symbol is still displayed in the mailbox view when ticking messages but can't be used. It should be hidden instead in this case.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/7bba7d97-81b0-4984-b83d-08e6631a2728)

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
