### ISSUE TITLE
Oauth Module

### ISSUE THREAD

**Issue by pablokbg** [freescout-helpdesk/freescout#3681]
Hello,

I have a doubt. If I force the oauth with google, but it fails and I can not enter, how could I disable the forced and thus enter with conventional login?

PHP version: 7.3
FreeScout version: 1.6.13
Database: MySQL 
Are you using CloudFlare:  No

**Comment by freescout-helpdesk** [comment]
Just remove "OAUTHLOGIN_FORCE_OAUTH_LOGIN=1" parameter from .env file and clear cache.

**Comment by pablokbg** [comment]
Good morning,

The variable "OAUTHLOGIN_FORCE_OAUTH_LOGIN=1" has been removed from the .env and is still forcing Google OAuth.

Why is this happening?

PS: The cache was cleared
