### ISSUE TITLE
Bulk remove old attachments

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#3682]
Hello,

Due to hosting limits I am interested in removing all attachments older then 3 years. 
The attachments are not by year shown in the FTP so I have no idea how to delete them. 

Is it not an idea in extended attachments to (automatically OR/AND by hand ) delete attachments by a certain timeframe, size, mailbox?

Would love that!

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
