### ISSUE TITLE
Auto-assign based on user's availability

### ISSUE THREAD

**Issue by youngstudiosnyc** [freescout-helpdesk/freescout#3684]
Is there a way to auto-assign conversations to users based on their availability and workload? For example 1/If user is not available, don't assign any tickets to them, 2/If 4 users are available, assign conversation to the user that doesn't have any open tickets (or assign it to a user that has least open tickets)?

Thanks!

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature for now. 
Feel free to submit a feature request: https://freescout.net/request-feature/
