### ISSUE TITLE
Export Conversations module threads content

### ISSUE THREAD

**Issue by anastis** [freescout-helpdesk/freescout#3685]
PHP version: 8.1.26
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: Yes

Hi there,
perhaps I'm missing something obvious, but how can I include the actual threads contents of the conversations in the csv file?
It seems like everything else is exportable except the actual conversation taking place.

Thanks for your help.

**Comment by freescout-helpdesk** [comment]
> Module exports only conversations data and does not export text of the conversations’ threads with text.

https://freescout.net/module/export-conversations/
