### ISSUE TITLE
update error via web interface

### ISSUE THREAD

**Issue by feckerd** [freescout-helpdesk/freescout#3686]
![freescout_error](https://github.com/freescout-helpdesk/freescout/assets/156678747/fe16f97b-bc80-437e-8a22-0182d5787d93)

I got this error while trying to update my freescout docker-compose installation via web GUI from version 1.8.115 to 1.8.117. Can anyone help out?

PHP version: PHP 8.2.14
FreeScout version: 1.8.115
Database: Mysql (10.6.7-MariaDB)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Usually docker installations are updated by updating docker image: https://github.com/tiredofit/docker-freescout/releases
