### ISSUE TITLE
Update manually by downloading ZIP ... via SSH? yikes

### ISSUE THREAD

**Issue by tiny-k12-it-admin** [freescout-helpdesk/freescout#3687]
Regarding: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

1. Remove /vendor directory: rm -rf /path/to/freescout/vendor
2. [Download](https://freescout.net/download/) and extract archive into FreeScout directory on your server overwriting all existing files (no worries, no configuration files will be overridden).

It would help if you would actually document how to go about downloading and extracting the archive over the top of the web install directory. wget doesn't know what to do with "301 moved".  Eventually I went with "curl -F https://freescout.net/download/ -o file.zip" since it too can't handle this automatically.

Then there's a problem that you seem to have embedded "freescout-dist" as the root of the extracted ZIP files. It's not possible to "sudo mv ~/freescout-dist/* /var/www/html/." with the extracted zip file .... mv doesn't know what to do with subdirectories.

Linux unzip can overwrite an existing directory structure, but again the leading "freescout-dist" in the archive keeps tripping me up. 

After trying to manually mv a hundred subdirectories by hand into /var/www/html, it hit me.

- sudo mv ~/freescout-dist.zip /var/www
- cd /var/www
- sudo mv html freescout-dist
- sudo unzip freescout-dist.zip
- Overwrite All
- sudo mv freescout-dist html

Yes, it's "just that easy" to force an update via ssh.... sigh.

**Comment by dpgdoc** [comment]
If you have SSH access, there are other easier ways to handle the update process, why would you go the manual way?

The probable easiest way would be to unzip it locally and then rsync the local folder with the remote folder, if you can't use the git repository or the script freescout has.

https://www.digitalocean.com/community/tutorials/how-to-use-rsync-to-sync-local-and-remote-directories

**Comment by tiny-k12-it-admin** [comment]
I had an older install from Dec 2021, not updated since then. The web based update failed, the scripted update failed, it was not built using git so that command didn't work...

Unzipping by overwriting files to update is the only method that actually worked.

**Comment by raramuridesign** [comment]
We have a bash script we run for all updates. 
All other update methods caused issues, and the bash script has extra processes in it to allow us to update the site in a few seconds. We also backup, unzip, reset permissions and do a cleanup.
Works well, but will require testing. 
M.

**Comment by dpgdoc** [comment]
> I had an older install from Dec 2021, not updated since then. The web based update failed, the scripted update failed, it was not built using git so that command didn't work...

Then I think this is an infrastructure problem, not a freescout issue. The solutions are there and are working as intended.
