### ISSUE TITLE
Option in Custom Field cannot be deleted

### ISSUE THREAD

**Issue by karrierekick-dev** [freescout-helpdesk/freescout#3689]
When deleting an existing Option from an already defined Custom Field, I get a confirmation dialog, telling me, that my history and connected workflows will be removed. After confirming this dialog, my entry keeps in place - even after reloading the page.

No Errors in Console.

PHP version: 8.2
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
You need to click "Save Field" button.

**Comment by karrierekick-dev** [comment]
Well, that works. It' visually still very irritating, as nothing changes when saving it. Only when reloading.
