### ISSUE TITLE
Unable to login - Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by blackyzero** [freescout-helpdesk/freescout#369]
Hello,

I am unable to login or reset password, even completed update to latest version
The error shows when trying to reset password

Whoops, looks like something went wrong.

Also refer this instruction here, but still not work, https://github.com/freescout-helpdesk/freescout/issues/287

Please help to correct this issue.
Thank you.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#10-checking-installation

**Comment by blackyzero** [comment]
this issue happens after upgrading.
In addition, i enable app debug, but there is no log, and unable to login.

**Comment by blackyzero** [comment]
could be issue with reverse proxy, cause i am using haproxy, still finding a way to fix it.

**Comment by blackyzero** [comment]
i tried to add "APP_FORCE_HTTPS=true", this works before upgrading, now it doesn't.
The login page shows not load via https from browser console message.

Any idea how to fix this issue?
Thank you.

**Comment by blackyzero** [comment]
just run update again and it works, not sure if having any fix recently.
