### ISSUE TITLE
Cannot search for Custom Field when Custom Fields with same name exists in multiple Mailboxes

### ISSUE THREAD

**Issue by karrierekick-dev** [freescout-helpdesk/freescout#3690]
I have a Custom Field "Priority" (Dropdown) in all my Mailboxes (2 in total).
When I go to search and selet the Custom Field "Priority" from the Sidebar to the left, it shows this as a Dropdown and I can select an Option. When pressing search, a second "Priority" Dropdown gets displayed and no results will be shown,

PHP version: 8.2
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
The only solution for now is to give custom fields different names.

**Comment by karrierekick-dev** [comment]
Well, that's the workaround we use right now, but this is pretty ugly

**Comment by freescout-helpdesk** [comment]
Yes, maybe with time some solution will appear.
