### ISSUE TITLE
how to recognize unread notifications?

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3693]
My notification list looks like this:

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/ce1535d6-3881-4de5-8478-ffe29719ad94)

How can I figure out which notifications are new / unread and which not? In the example the counter "5" is shown but I can't distinguish between the ones shown.

Browser: Firefox 121.0.1
OS: Ubuntu 22.04

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by mokkin** [comment]
Meanwhile I have found out, that the light blue ones are the unread ones ;)

Let's change the topic: Could you please improve the contrast of the unread notifications or put a symbol there?
Even better would be to show only the unread ones in a separate tab.

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to change it.
