### ISSUE TITLE
Fails auto fetching IMAP only without errors.

### ISSUE THREAD

**Issue by SyberSin** [freescout-helpdesk/freescout#3694]
Hello,

Just got FreeScout setup on Unraid with the official docker image. Everything is working with zero errors in the logs, except fetching emails automatically with IMAP does not work. I have connected other services to this email account through IMAP without issues. 

The cron job shows it connects, finds mailboxs and folders, but fetches zero new emails when there are new emails to be fetched. 

If I do a manual fetch by running `php artisan schedule:run` or `freescout:fetch-emails` it does the same thing, runs without errors but fetches nothing.

The strangest part is that if I do a manual fetch with the built in system tool it DOES grab all the new emails with no issues or errors. So, my IMAP connection must be correct.

Also, if I change the email account type to POP, everything works fine, including the cron job, it fetches new emails without issue. It's only the cron fetching of IMAP that is not working. Again, not a single error is in the logs, all this leaves me to believe it is an issue with FreeScout.

This is the only thing preventing me from converting to FreeScout and purchasing a bunch of the modules.

The email account is hosted in cpanel from NameCheap. Default email setup. I have checked all credentials a hundred times, and tried with and without ssl, and have read through the documentation on here multiple times and have tried everything recommended without success.

Any help would be greatly appreciated.

FreeScout version: 1.8.117
Database: PostgreSQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Can you share fetch log from Manage > Logs.

**Comment by SyberSin** [comment]
Sure, I am actually getting an error from in the laravel log all of a sudden.

[fetch-emails.log](https://github.com/freescout-helpdesk/freescout/files/13966634/fetch-emails.log)
[laravel-2024-01-16.log](https://github.com/freescout-helpdesk/freescout/files/13966635/laravel-2024-01-16.log)

**Comment by freescout-helpdesk** [comment]
Make sure that something does not mark emails as "READ" in your mail server. Background fetching fetches only unread emails.

**Comment by SyberSin** [comment]
Wow. Thank you! I can't believe it was something so simple. I disconnected all services from the email and set cPanel to never mark email as read, and it fixed it. I'm not sure if it was a service or cPanel that was marking them, but that work.

**Comment by ohader** [comment]
FYI: I've created a PR #3931 to make this behavior configurable.

This seems to be handy, when mail accounts are still used in a hybrid way - e.g. some folks still accessing messages directly via IMAP, while others already migrated their workflow to use FreeScout.
