### ISSUE TITLE
Popup for sending options is partly hidden for short conversations

### ISSUE THREAD

**Issue by karrierekick-dev** [freescout-helpdesk/freescout#3696]
When getting a small conversation with only one line of text and I open the sending option with the down arrow besides the "Send" button, the popup is partly hidden because there is not enough space at the bottom of the page. I cannot scroll to see it completely.

PHP version: 8.2
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Screenshot?

**Comment by karrierekick-dev** [comment]
![error](https://github.com/freescout-helpdesk/freescout/assets/97171654/15c10b22-ee73-4ea7-b74a-8bf5545d686d)

**Comment by freescout-helpdesk** [comment]
If someone can fix this please submit a pull request.
