### ISSUE TITLE
WORKFLOWS_USER_FULL_NAME in E-Mail gets cut to 20 characters

### ISSUE THREAD

**Issue by karrierekick-dev** [freescout-helpdesk/freescout#3698]
When I use a workflow which sends an E-Mail, the senders name is the value defined in WORKFLOWS_USER_FULL_NAME (.env file). 
We defined "Karriere Kick Support" but as senders name we always get "Karriere Kick Suppor". The last character "t" is missing. I've tested this a bit and it seems, that the string gets always cut after 20 characters.

PHP version: 8.2
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
User names in FreeScout are limited to 20 symbols, same with Workflow user names.

**Comment by karrierekick-dev** [comment]
Well, then. Increasing that size shouldn't be a big deal.
According to my tables, the first name is 20 characters and the last name 30 characters. I think that's enough for nearly any name. But why is the Workflow name limited to 20 characters when it is just an entry in the env file?

After setting up FreeScout and creating my own customer frontend using the incredible easy API, I immidiately fall in love with FreeScout. Then I looked at the Customer Portal Module and everything I created so far was already there. You've done an amazing job with all of this.

However the more I use it the more I come across these little annoying things and the answer when reporting them is often "That's how it is in FreeScout".

**Comment by freescout-helpdesk** [comment]
> But why is the Workflow name limited to 20 characters when it is just an entry in the env file?

Value from .env file is used as `users.first_name` field value.

**Comment by karrierekick-dev** [comment]
OK, so the solution might be to add two more entries in the .env file
WORKFLOWS_USER_FIRST_NAME
WORKFLOWS_USER_LAST_NAME

If both are given, they will be used, else WORKFLOWS_USER_FULL_NAME will be used.

**Comment by freescout-helpdesk** [comment]
In emails sent to customers only user's first name is shown, so it's no use.

**Comment by karrierekick-dev** [comment]
Not for me when using variables.

When I use a manual workflow to directly answer to a customers message, the default signature gets added. This includes variables like user->last_name. So because of the missing last_name and other missing details, the signature contains only some of the usual content and looks ugly.

This is one of the annoying things I've talked about. I get the impression, that I can use variables and add the default signature, but some of them are not usable and I don't know why. (Well, actually I can look in the code and I know why...)

So for me, the better and much more customizable solution would be to select an existing user which will be added as the workflow's user. A special workflow-User might be created by default. This would not only solve these workflow-user issues but would also be much easier and less scary to change the workflow user. Editing the env file should not be an option for the default user.

**Comment by karrierekick-dev** [comment]
I wanted to change the source in Modules/Workflows/Entities/Workflow.php directly on my live system, however the user in self::$wf_user is cached. I cleared the cache on system/tools page, however, the user is still cached.
How can I programmatically flush the cache?
And should this be cleared then I clear the cache in system/tools?

**Comment by karrierekick-dev** [comment]
I've now created a patch to get the desired custom user and avoid the 20 characters limitation
https://github.com/karrierekick-dev/freescout-custom-workflow-user

**Comment by freescout-helpdesk** [comment]
Good job. We'll reference it on Workflows Module page.
