### ISSUE TITLE
[API and Webhooks module] Filtering conversation status with boolean operators

### ISSUE THREAD

**Issue by floatingpurr** [freescout-helpdesk/freescout#3699]
Hello, here's my env: 

PHP version: 8.3
FreeScout version: 1.8.117
API and Webhooks Version: 1.0.72
Database: MySQL 
Are you using CloudFlare:No

I'm wondering if there's a way for [listing conversations](https://api-docs.freescout.net/#list-conversations) that are active OR pending via API. It looks like there isn't. Just want to double check.

**Comment by freescout-helpdesk** [comment]
There is no such feature.
