### ISSUE TITLE
Webhooks Module - Customer.created webhook is not sent

### ISSUE THREAD

**Issue by Joaofariasglobal** [freescout-helpdesk/freescout#3700]
PHP version: 8.1.2
FreeScout version: 1.8.117
Database: MySQL 
Are you using CloudFlare: No

Hi, I've set many webhooks, it worked alright, including the "customer.updated" event, but the "customer.created" event isn't working. 

When an email doesn't get its goal, the "customer.created" webhook is sent to the URL, as on the screenshot, but not when I create a customer from GUI.

![image](https://github.com/freescout-helpdesk/freescout/assets/145355461/258d63d3-2dfe-4e21-ace9-dda531fa0e7d)

**Comment by freescout-helpdesk** [comment]
Fixed in CRM Module v1.0.43
