### ISSUE TITLE
PostgreSQL: Trailing data error

### ISSUE THREAD

**Issue by SyberSin** [freescout-helpdesk/freescout#3702]
Hello,

Just purchased the Two Factor Module. When I try to turn on for a user it fails and shows a "Whoops, something went wrong message."

The error log attached does not display anything helpful to know what's causing the issue, I searched the GitHub issues with no luck.

I followed the below instructions and troubleshooting with no luck as well:
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#7-faq

Reinstalled FreeScout, the module, cleared cache, nothing works even on a fresh install with no other modules or changes.

Also, the first attempt to turn on Two Factor shows the key under the QR code, then all attempt after the key is missing. Even if I reinstall the module.

I have no other errors but this one when I attempt to turn on for a user:
[laravel-2024-01-18.log](https://github.com/freescout-helpdesk/freescout/files/13974674/laravel-2024-01-18.log)

**Comment by freescout-helpdesk** [comment]
Your DB?

**Comment by SyberSin** [comment]
Postgres.

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of the module and FreeScout?

**Comment by SyberSin** [comment]
Yes

**Comment by freescout-helpdesk** [comment]
Try to add the following code to the line 884 in /overrides/nesbot/carbon/src/Carbon/Carbon.php:  https://github.com/freescout-helpdesk/freescout/blob/dist/overrides/nesbot/carbon/src/Carbon/Carbon.php#L884
```
        if ($format == 'Y-m-d H:i:s' && strlen($time) > 19) {
            $time = substr($time, 0, 19);
        } 
```

**Comment by SyberSin** [comment]
Yes that seemed to work, but this is running in a docker which means that change won't persist. What can I do about that? 
It did not fix the code from displaying the text version below though, I needed my phone to scan.

Also, I started getting another error repeating in the log about postgres.

`SQLSTATE[08006] [7] could not translate host name "Postgres" to address: Name does not resolve {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not translate host name \"Postgres\" to address: Name does not resolve at /www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"Postgres\" to address: Name does not resolve at /www/html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)`

[laravel-2024-01-19.log](https://github.com/freescout-helpdesk/freescout/files/13999499/laravel-2024-01-19.log)

When I setup Postgres I simply used pgAdmin, and created a database with defaults. Is there something else I need to do means all this seems related to postgres?
