### ISSUE TITLE
Unable to add satisfaction ratings to email template created by workflow

### ISSUE THREAD

**Issue by ozan-simpliwifi** [freescout-helpdesk/freescout#3704]
We have a workflow that we trigger when a ticket has been closed which then emails the customer asking for feedback using the satisfaction rating module.

Adding {%ratings.add%} to the email template does not then generate the feedback options in the email it simply has {%ratings.add%}

Anyone else see this issue?

Frescout Version: 1.8.117
Workflow Version: 1.0.63
Ratings Version: 1.0.22

Regards,

Oz

**Comment by freescout-helpdesk** [comment]
With just double checked it with "Email the Customer" Workflow action and it works fine.
Make sure your modules are up-to-date.
