### ISSUE TITLE
When using workflows to send email to cutomers, agent Full Name varible is incorrect

### ISSUE THREAD

**Issue by ozan-simpliwifi** [freescout-helpdesk/freescout#3705]
Hi,

When using workflows to generate emails to customers and you include the {%user.fullname%} variable instead of showing the name of the agent who dealt with the issue it show **Workflow** as the name.

Frescout Version: 1.8.117
Workflow Version: 1.0.63

Regards,

Oz

**Comment by freescout-helpdesk** [comment]
Yes, this is how it works in FreeScout.

**Comment by karrierekick-dev** [comment]
It's not a bug, it's a feature!

Maybe my feature request will help to lower the irritation level.

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/429816
