### ISSUE TITLE
Infrequent memory issue

### ISSUE THREAD

**Issue by iantearle** [freescout-helpdesk/freescout#3706]
Have an intermittent issue that's causing emails to get stuck in the queue and continually send out emails, the only logs are not that clear as to whats the cause to me, but perhaps helps you?

```Allowed memory size of 268435456 bytes exhausted (tried to allocate 134217736 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 268435456 bytes exhausted (tried to allocate 134217736 bytes) at /www/html/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:275)```

PHP version:  8.2
FreeScout version: 1.8.117 
Database: MySQL / PostgreSQL
Are you using CloudFlare: No

This is on Docker Freescout.

**Comment by freescout-helpdesk** [comment]
Looks like duplicate of https://github.com/freescout-helpdesk/freescout/issues/3632

**Comment by freescout-helpdesk** [comment]
And can you share the full error message.

**Comment by iantearle** [comment]
Closed due to duplicate
