### ISSUE TITLE
Google turning off support for IMAP using App Passwords

### ISSUE THREAD

**Issue by sschaap** [freescout-helpdesk/freescout#3707]
Google plans to remove IMAP access using Less Secure Apps (i.e. app passwords). Starting June 15th, creation of new LSAa will no longer be possible. From September 30th onwards, existing LSAs will stop working. The only remaining authentication mechanism for IMAP access is using the XOAUTH2 mechanism.

https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html

As far as I am aware, FreeScout does not currently support IMAP using OAuth2 authentication. What measures, if any, are planned to continue support for Gmail and Google Workspaces mailboxes?

**Comment by raramuridesign** [comment]
@sschaap 
You might want to try this, we have been using app password for several years now and it works well. 
Specifically we changed this when we added 2FA & Security Keys to our emails, so the app password assisted with allowing us to still connect to the mailbox. Google will not be removing this feature. Its also a good solution as you can revoke passwords if you no longer require a service to conenct to it, without having to adjust your main password or 2FA access. 
Hope this helps.
M

https://support.google.com/accounts/answer/185833?fl=1&sjid=5096892822431981466-NA 

![image](https://github.com/freescout-helpdesk/freescout/assets/902376/4af7e403-e6c7-497a-b0ec-ef95cd83e0f9)

**Comment by freescout-helpdesk** [comment]
App Passwords will work forever (according to Google Support).

**Comment by freescout-help** [comment]
![2024-09-25_11-13-58](https://github.com/user-attachments/assets/f9cd7268-0a3f-465d-ab7a-94c2e0cc6dc2)
https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html
