### ISSUE TITLE
Menu does nolonger open on mobile

### ISSUE THREAD

**Issue by hereditas** [freescout-helpdesk/freescout#3708]
When logged in on mobile device, the submenues do not open. also i cannot scroll the meassage overview

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-if-styles-or-javascripts-are-working-incorrectly-top-menu-is-not-working

**Comment by boehmgui** [comment]
I am having the same issue - it was introduced with the update to version 1.8.118

The symlink is there: 
storage -> /var/www/vhosts/xxxxx/storage/app/public

Pulldown menus work on desktop PCs but not on mobile phones. Permissions look OK too

**Comment by freescout-helpdesk** [comment]
Can you send a screenshot.

**Comment by boehmgui** [comment]
![Untitled](https://github.com/freescout-helpdesk/freescout/assets/102216227/cbee3173-a5b4-448a-a9c3-8c149612b6da)

**Comment by freescout-helpdesk** [comment]
Screenshot or video of the menu.

**Comment by boehmgui** [comment]
oh, apologies...
here you go:
![2024-01-22 09 06 50](https://github.com/freescout-helpdesk/freescout/assets/102216227/cac93549-c60b-4e40-8843-828e5edabd2e)
1. click on the 3 bars upper right corner
2. click on e.g. "Manage"
"Manage" will only be highlighted but not opened

Again, this worked until 1.8.117 and stopped working with 1.8.118 - at least for me

**Comment by hereditas** [comment]
Same with me, was working till 1.8.117

**Comment by freescout-helpdesk** [comment]
Here is the fixed `/public/js/html5sortable.js` script:
https://github.com/freescout-helpdesk/freescout/blob/master/public/js/html5sortable.js

You can copy it to your FreeScout installation and clear cache.

**Comment by boehmgui** [comment]
works like a charm - many thanks for the swift support!
