### ISSUE TITLE
don't show workflow symbol in bulk actions when no workflows are available

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3709]
Don't show workflow symbol in bulk actions when no workflows are available (for this mailbox). The same applies for tags.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/fc9e1d26-fc13-45b3-9af7-6cac645a5196)

PHP version: 8.2.12
FreeScout version: 1.8.118
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.65.
