### ISSUE TITLE
Paid Module LDAP Authentication not using full DN

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#371]
Hi, I have uncovered a problems with the (paid) LDAP Module which is limiting my ability to use it properly.

I initially had trouble with getting the Bind Account to work. After reviewing the logs I found that you need to strip the base-dn off the tail end of the bind username which then allows me to perform a successful test and import users.

The real problem is that when I have imported the users, upon attempting to login to the Freescout interface it is not properly searching the tree for the user.

Our Users are in a variety of LDAP OUs and accessible by searching (sub) from the Base DN. An example of a user looks like this:
 `uid=user,ou=people,ou=IT,ou=Department,dc=example,dc=org`. 

 When freescout attempts to authenticate, it first checks the existence of the user existing by means of the filter. Then it attempts to login based on the uid of the result returned - yet tries to do it at the root, not facotring in the entire users DN.

 Here is a log for example:

````bash
5dd58bf4 conn=1354 fd=37 ACCEPT from IP=172.22.0.110:37044 (IP=0.0.0.0:389)
5dd58bf4 conn=1354 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5dd58bf4 conn=1354 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5dd58bf4 conn=1354 op=0 RESULT tag=97 err=0 text=
5dd58bf4 conn=1354 op=1 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(mail=username@example.org))"
5dd58bf4 conn=1354 op=1 SRCH attr=*
5dd58bf4 conn=1354 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
5dd58bf4 conn=1354 op=2 BIND anonymous mech=implicit ssf=0
5dd58bf4 conn=1354 op=2 BIND dn="uid=username,dc=example,dc=org" method=128
5dd58bf4 conn=1354 op=2 RESULT tag=97 err=49 text=
5dd58bf4 conn=1354 op=3 BIND dn="cn=admin,dc=example,dc=org" method=128
5dd58bf4 conn=1354 op=3 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5dd58bf4 conn=1354 op=3 RESULT tag=97 err=0 text=
5dd58bf4 conn=1354 op=4 UNBIND
5dd58bf4 conn=1354 fd=37 closed
5dd58c00 conn=1355 fd=37 ACCEPT from IP=172.22.0.110:37374 (IP=0.0.0.0:389)
5dd58c00 conn=1355 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5dd58c00 conn=1355 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5dd58c00 conn=1355 op=0 RESULT tag=97 err=0 text=
5dd58c00 conn=1355 op=1 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(mail=username@example.org))"
5dd58c00 conn=1355 op=1 SRCH attr=*
5dd58c00 conn=1355 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
5dd58c00 conn=1355 op=2 BIND anonymous mech=implicit ssf=0
5dd58c00 conn=1355 op=2 BIND dn="uid=username,dc=example,dc=org" method=128
5dd58c00 conn=1355 op=2 RESULT tag=97 err=49 text=
5dd58c00 conn=1355 op=3 BIND dn="cn=admin,dc=example,dc=org" method=128
5dd58c00 conn=1355 op=3 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5dd58c00 conn=1355 op=3 RESULT tag=97 err=0 text=
```` 

If you would be able to set it to use the full DN when authenticating this module will begin to work as intended.

**Comment by freescout-helpdesk** [comment]
Which LDAP server are you using?

**Comment by tiredofit** [comment]
Server: `ldap`
Base DN `dc=example,dc=org`
Filter `(memberOf=cn=app-freescout,ou=groups,ou=Access,dc=example,dc=org)`
Bind User: `cn=dsa-freescout,ou=dsa,ou=System`

We are using OpenLDAP 2.4.48. We have approximately 30 other services working in the same fashion. The filter properly finds all members with the group membership (In our case 9), and when the Freescout Module connects to attempt to authenticate a user on the welcome screen successfully finds a result based on a query for the users `mail` attribute.

After it recieves confirmation that the user does indeed exist, then it tries to login directly with the uid/mail attribute with only the base dn attached.. The way it is currently setup is if the users were all sitting in their own OU at the Base DN - What it should be doing is when finding that there is indeed a user, is requesting the full users DN, and attempting to login that way. Most environments have seperate OUs and organization for departments, locations, or their own way of organization.

Further short example: it tries to login with `uid=user,dc=example,dc=org` when it should be using  `uid=user,ou=people,ou=IT,ou=Department,dc=example,dc=org`

**Comment by freescout-helpdesk** [comment]
OK. We will try to fix.

**Comment by tiredofit** [comment]
Contact me privately if you'd like an LDAP server to work with.

**Comment by freescout-helpdesk** [comment]
Thanks. Try updated LDAP Module 1.0.3

**Comment by tiredofit** [comment]
Fantastic, thanks for the fix. I and others are able to login to our test server. Looking forward to getting this going in production.

**Comment by Ntworkadmin** [comment]
@tiredofit can you share the ldap setting for your freescout change your domain name to example.com and please share the setting
