### ISSUE TITLE
conversations can't be sorted by customers

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3710]
I can sort conversations ascending and descending by subject, ticket number and waiting time, but unfortunately not by customer:

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/cdbf01bd-1152-4b99-ae68-6f7efe3ea326)

Is this a bug? If not, please add this as it is helpful sometimes to get all conversations of a customer at once.

PHP version: 8.2.12
FreeScout version: 1.8.118
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
