### ISSUE TITLE
Ticket Number still included after disabling Ticket Number module

### ISSUE THREAD

**Issue by karrierekick-dev** [freescout-helpdesk/freescout#3711]
The ticket number ist still included in the E-Mail subject after I disabled the Ticket Number module.

PHP version: 8.2
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Try to delete module's folder from /Modules. Also make sure that some other non-official modules does not add it.
