### ISSUE TITLE
Mentions Module Not Showing Users

### ISSUE THREAD

**Issue by SyberSin** [freescout-helpdesk/freescout#3712]
Just installed the mention module and I cannot get the user dropdown list to work.

I checked the users have access to the mailbox and are not hidden in permissions, but the dropdown list of users is empty. No errors are thrown. I have cleared cache with no luck. I have tried on multiple browsers

Any ideas how to fix this?

![Screenshot 2024-01-20 184207](https://github.com/freescout-helpdesk/freescout/assets/10297314/044fdba0-8bad-461d-b04e-368ac4b3817c)

Docker: Latest
PHP version: 8.2.14
FreeScout version: 1.8.117
Database: PostgreSQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Update to the latest FreeScout version.

**Comment by SyberSin** [comment]
Works now. Thank you!
