### ISSUE TITLE
Not able to find CreatedBy filter in ListConversations API

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3713]
I can see CreatedBy fields in conversation object but I dont see the filter in the list conversations API. For me it will be really helpful to fetch conversation created by a certain freescout user. Please let me know If I am missing it because this sounds basic to me. I am happy to raise a feature request if needed.

**Comment by freescout-helpdesk** [comment]
`createdByUserId` and `createdByCustomerId` filter parameters added in API & Webhooks Module v1.0.73
