### ISSUE TITLE
Read status tracking not working

### ISSUE THREAD

**Issue by ting-ff** [freescout-helpdesk/freescout#3714]
Hello! We are just wondering if anyone else has noticed issues with read status tracking. Starting about 2 weeks ago, we have not seen a single tracking update. That is, messages like "Customer viewed this xxx ago" don't appear when customers read the messages, for all emails. All emails are still sent successfully and replies are coming in just fine, but we've lost this status update.

Is there any tip for how to debug this issue? Any configuration we should check? There are no obvious error messages in the logs either. Thanks!

-------

PHP version: PHP 8.2.15
FreeScout version: 1.8.118
Database: MySQL 8.0.35
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment]
You can try to find the tracking image in the outgoing email and open it manually in different browsers.

**Comment by ting-ff** [comment]
Ah thanks for the advice! We've figured out the issue - we put freescout behind cloudflare's Zero Trust authentication recently and that prevented the image from ping the server. We changed that and all is good!
