### ISSUE TITLE
"ldap" and "errors in receiving letters" logs are not deleted

### ISSUE THREAD

**Issue by SakhOnline** [freescout-helpdesk/freescout#3715]
Greetings. When deleting the “ldap” and “letter receiving error” logs, I receive a notification that the logs have been deleted, but in fact they remain and are not deleted. There are already 5000+ pages accumulated. Please help me fix the problem.

**Comment by freescout-helpdesk** [comment]
It means your server is not powerful enough to delete records from your DB. So possible solution is to upgrade your DB server.

**Comment by SakhOnline** [comment]
Thank you! I added resources to the virtual machine and everything became normal.
