### ISSUE TITLE
Question About Module Updates

### ISSUE THREAD

**Issue by SyberSin** [freescout-helpdesk/freescout#3716]
Hello,

I'm running Freescout in a docker and the data path to modules is mapped to local path on the server. 

If I change module code in my local path, will it be overwritten? How are modules updated and are they automatic?

I updated the ticket number module to put the number after the subject and it's working as expected. I'm also thinking about putting an if check to only apply ticket numbers to certain mailboxes, but I want to be certain that code will never change and I accidently send an email with a ticket number attached when it should not be.

Thanks for any insight into this.

**Comment by freescout-helpdesk** [comment]
Here is how to make modules update automatically: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#92-cron-job-for-automatic-updates

When you (or automatic update system) updates some module it's being overwritten.

**Comment by SyberSin** [comment]
Okay so modules are never updated unless I update them manually or setup the cron job, correct?

Thank you!

**Comment by freescout-helpdesk** [comment]
Yes.
