### ISSUE TITLE
Translation system does not work

### ISSUE THREAD

**Issue by Maddmax76** [freescout-helpdesk/freescout#3717]
Good morning, this morning, after applying the FreeScout update to version 1.8.118, the translation management does not work.
As usual, after updating the App, I apply the extension updates, then import the translations, then check if there are new labels to translate.
This time too, I go to the translations module, import the published translations, wait for it to finish, choose a group, in this case I choose APP, and nothing happens.
Before the update, by choosing a group from the drop-down menu, another drop-down menu appeared where I could choose the language. This doesn't happen anymore.
I cleared the server cache, restarted the server, but it still doesn't work.
Could you check?
Thank you.

PHP version: PHP 8.2.10-2ubuntu1
FreeScout version:  1.8.118 
Database: MySQL / PostgreSQL Mysql (8.0.35)
Are you using CloudFlare: Yes / No NO

**Comment by freescout-helpdesk** [comment]
Unfortunately we don't have any ideas what may cause it. Someone may need to debug it on your server.

**Comment by Maddmax76** [comment]
hi, thanks for the reply. I tried to search the logs, but I don't seem to find anything on the server side, I'm analyzing the browser console, and I see that there are errors:


```
Uncaught SyntaxError: redeclaration of let DragDropTouch
    <anonymous> https://[OMISS]/js/builds/6ca715d11aa7f8525aa2790eaf4bfaa171504019163.js:1
[6ca715d11aa7f8525aa2790eaf4bfaa171504019163.js:1:1](https://[OMISS]/js/builds/6ca715d11aa7f8525aa2790eaf4bfaa171504019163.js)
    <anonima> https://[OMISS]/js/builds/6ca715d11aa7f8525aa2790eaf4bfaa171504019163.js:1
```

```
jQuery.Deferred exception: $(...).editable is not a function @https://[OMISS]/translations:943:24
e@https://[OMISS]/js/builds/3e2b5b7f1e835625e3e5537b48e2371495388981739.js:1:30126
Deferred/then/l/</t<@https://[OMISS]/js/builds/3e2b5b7f1e835625e3e5537b48e2371495388981739.js:1:30428
 undefined
```
 

```
Uncaught TypeError: $(...).editable is not a function
    <anonymous> https://[OMISS]/translations:943
    e https://[OMISS]/js/builds/3e2b5b7f1e835625e3e5537b48e2371495388981739.js:1
    t https://[OMISS]/js/builds/3e2b5b7f1e835625e3e5537b48e2371495388981739.js:1
[translations:943:24](https://[OMISS]/translations)
    <anonima> https://[OMISS]/translations:943
    e https://[OMISS]/js/builds/3e2b5b7f1e835625e3e5537b48e2371495388981739.js:1
    t https://[OMISS]/js/builds/3e2b5b7f1e835625e3e5537b48e2371495388981739.js:1
```
 

I hope it can be indicative

**Comment by freescout-helpdesk** [comment]
Try with this `/public/js/html5sortable.js` file: https://github.com/freescout-helpdesk/freescout/blob/master/public/js/html5sortable.js

Make sure to clear cache.

**Comment by Maddmax76** [comment]
It works, perfect!
Thank you very much, have a nice day
