### ISSUE TITLE
No IMAP folders found - office365

### ISSUE THREAD

**Issue by 7ergei** [freescout-helpdesk/freescout#3719]
Hi,
No matter what have I done still can't manage to get the folders from the mailbox...
This is on my second, new mailbox (for different purpose).
The old one which serves us as IT Ticketing system is working well.
Latest v1.8.118
![image](https://github.com/freescout-helpdesk/freescout/assets/88785658/163642fe-f869-423c-93be-3a1070e428e5)

Please your assistance.

**Comment by raramuridesign** [comment]
@7ergei Did you check that the folders are allowed to be synced? Like folder off vs on

**Comment by 7ergei** [comment]
The only place I've checked this as it is a brand new mailbox is in OWA and this is what I have:
![image](https://github.com/freescout-helpdesk/freescout/assets/88785658/2d0ebfde-315d-47af-b7d0-85210e5c38c4)

**Comment by 7ergei** [comment]
Got the folders, not sure what fixed it but - 
1. Updated to the latest version of FreeScout.
2. Deleted the mailbox and re-added it again.
3. Put wrong port # on purpose for IMAP 992 and with the arrows fixed it to 993.

All folders synced...

**Comment by raramuridesign** [comment]
https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
;-)

I think you can close this - if its working.
