### ISSUE TITLE
Module Service Provider Missing

### ISSUE THREAD

**Issue by SyberSin** [freescout-helpdesk/freescout#3722]
I duplicated the reports module and was editing the code just to experiment and ended up deletling the module and now I cannot access FreeScout. It keeps saying Service Provider Not Found with a reference to the custom module I made.

Attached are logs.

I cannot even clear cache in the console as I get the same error. Please how do I fix this?

I restarted the docker with no luck, the console will not run any php artisan commands as it throws that same error.

[laravel-2024-01-22.log](https://github.com/freescout-helpdesk/freescout/files/14017612/laravel-2024-01-22.log)

**Comment by PhrantiK** [comment]
Had the same thing a few times, clearing everything manually worked for me:

https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache

**Comment by SyberSin** [comment]
I just checked before trying your recommendation and now all of a sudden, I have access again. I gave up after an hour, and it's been sitting for about 6 hours now and it appears to have fixed itself?

Thank you for your input, I will keep that in mind if I run into this issue again.

Any idea of a better way to change official module code without risk of it being overridden from an update?

**Comment by PhrantiK** [comment]
Not too sure sorry! I have an open issue on a similar subject myself with a change to the main project files. 

Maybe for a module the way to do it might be to put it in a private git repo and your changes in a separate branch that you can rebase after updates. No clue if the .git folder is overwritten though.
