### ISSUE TITLE
Mobile Notifications not working

### ISSUE THREAD

**Issue by svenbrier** [freescout-helpdesk/freescout#3726]
I recently put a FreeScout instance into operation and purchased, installed and activated the Mobile Notifications plug-in. I turned on new ticket notifications in Settings, but I'm not receiving new ticket notifications. Neither on iOS (iPhone 14 Pro) nor on Android (Pixel 5).

PHP version: 8.2.7
FreeScout version: 1.8.119 
Database: MySQL (10.11.4-MariaDB-1~deb12u1)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
All the advices we can give are already listed on https://freescout.net/module/mobile-notifications/
