### ISSUE TITLE
[Reports Module]:Average response time show 5 d 143 h 41 min

### ISSUE THREAD

**Issue by tchoblond59** [freescout-helpdesk/freescout#3729]
On the productivity reports page, average time show 5 d 143 h 41 min. Is it normal ? How hours can be more than 23 hours ?
Thank you.

PHP version: 8.1.2
FreeScout version: 1.8.119
Report Module Version: 1.0.36
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1.0.37
