### ISSUE TITLE
Cannot send email via API

### ISSUE THREAD

**Issue by tuxmartin** [freescout-helpdesk/freescout#3731]
Hello,

I want to email with an attachment over FreeScout API (I bought API & Webhooks module).

I wrote simple Python code according to https://api-docs.freescout.net/?javascript#create-conversation

The script returns me the HTTP 201 code, creating a Freescout conversation. But no emails were sent. My customer didn't receive any email.

Can you please help me? What's wrong?

FreeScout version: 1.8.115 docker from  https://github.com/tiredofit/docker-freescout/issues
Are you using CloudFlare: No

My python script:

```python
#!/usr/bin/python3

import requests
import sys
import os
import datetime
import base64
import json

TOKEN = os.environ['TOKEN']

url = "https://helpdesk.xxxxxxx.eu/api/conversations"
current_year = datetime.date.today().isocalendar().year
current_week = datetime.date.today().isocalendar().week
email_to = "abc@gmail.com"
email_cc = "martin.xxx@tXXXXXXXXXX.eu"
message = '''
Hello,
this is message.
'''

subject = "Report za tyden %s-T%s" % (current_year, current_week)
mailbox_id = 14 
user_id = 1 

file_name = str(sys.argv[1])

with open(file_name, "rb") as file:
  file_b64 = base64.b64encode(file.read()).decode('UTF-8')

headers = {
  "X-FreeScout-API-Key": TOKEN,
  "Content-Type": "application/json",
  "Accept": "application/json"
}

body = {
  "type": "email",
  "mailboxId": mailbox_id,
  "subject": subject,
  "customer": {
    "email": email_to
  },
  "threads": [
    {
      "text": message,
      "type": "customer",
      "cc": [
        email_cc
      ],
      "customer": {
        "email": email_to
      },
      "attachments": [
        {
          "fileName": file_name,
          "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          "data": file_b64
        }
      ]
    }
  ],
  "assignTo": user_id,
  "status": "closed",
  "imported": False
}
print(json.dumps(body, indent = 2))

x = requests.post(url=url, headers=headers, json=body, allow_redirects=True, timeout=5)
if x.status_code != 201:
  print("error (status code = %s)" % x.status_code)
  exit(1)
else:
  print("success (status code = %s)" % x.status_code)
  exit(0)
```

body.json:
```json
{
  "type": "email",
  "mailboxId": 14,
  "subject": "Report za tyden 2024-T2",
  "customer": {
    "email": "abc@gmail.com"
  },
  "threads": [
    {
      "text": "\nHello,\nthis is message.",
      "type": "customer",
      "cc": [
        "xxxxxxxxx@tXXXXXXXXXX.eu"
      ],
      "customer": {
        "email": "abc@gmail.com"
      },
      "attachments": [
        {
          "fileName": "xxxxsupport_2024-01-01--2024-01-31.xlsx",
          "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          "data": "UEsDBBQAAAAIAAAAPwBhXU........ABCGwAAAAA="
        }
      ]
    }
  ],
  "assignTo": 1,
  "status": "closed",
  "imported": false
}
```

![freescout](https://github.com/freescout-helpdesk/freescout/assets/1219067/08ec3972-fe14-4c04-8fc3-85316abdb1b0)
![freescout2](https://github.com/freescout-helpdesk/freescout/assets/1219067/ddda1a7f-5f9d-405c-b358-14ae1068a341)

**Comment by freescout-helpdesk** [comment]
Make sure emails are sent when you reply manually.

https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by tuxmartin** [comment]
@freescout-helpdesk I still have the same problem.

I updated to the latest FreeScout version: 1.8.119 (Docker from https://github.com/tiredofit/docker-freescout/issues).

I sent exactly the same message (To, Cc,  Subject, Body, Message, Attachment) manually from FreeScout web, and it works. However, the same message sent through API never arrived to the recipient. 
I don't see API-mail in the log https://xxx.yyy.zz/app-logs/out_emails, but mail sent from FreeScout web is there.

So my opinion is the answer is not in https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by tuxmartin** [comment]
@freescout-helpdesk please re-open this issue. It's not completed.

**Comment by freescout-helpdesk** [comment]
Take a look at the "imported" flag:  https://api-docs.freescout.net/#create-conversation

![2024-02-18_13-12-11](https://github.com/freescout-helpdesk/freescout/assets/40499291/69828583-e557-4559-bdfb-fe4f7822e095)

**Comment by tuxmartin** [comment]
Hello @freescout-helpdesk 
I still have the same problem. I'm using FreeScout 1.8.145 (I had 1.8.115 when I created the issue).

I tried set `imported` to both `false` and `true`, but the result is the same.
I can see the mail in FreeScout, but nothing is sent.
Can you please advise me what I am doing wrong?

The source code is still the same: https://github.com/freescout-help-desk/freescout/issues/3731#issue-2097973072
Can you please try this code?

Thank you.

**Comment by freescout-help** [comment]
The only way to figure it out is to debug it on your FreeScout instance.
https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer
