### ISSUE TITLE
Forward Ticket from Different Mailbox

### ISSUE THREAD

**Issue by Marphies** [freescout-helpdesk/freescout#3732]
We are using Freescout in a productive environment and it works very well so far! Thank you for this fantastic piece of software.

One very common case for us:
- Customer has a support request (Mailbox A)
- Our team needs to check back with the manufacturer anonomously regarding the request (Mailbox B)

The ticket in mailbox B should be cross-referenced in the original ticket of mailbox A and vice versa, so team members can jump between the two tickets quickly.

### Forwarding a Ticket

![grafik](https://github.com/freescout-helpdesk/freescout/assets/147406642/aa8071e5-baf4-481b-855d-211fc4c6a9dd)

When forwarding a message, this X-referencing is done by Freescout automatically (see above) and forwarding can be done with a single click, so this would be perfect, BUT:
- Forwarded message is always in same mailbox A. It could be moved to mailbox B manually afterwards, but this requires additional steps. The forwarded message will still be originally sent from mailbox A which is not right.
- Forwarded message will always have the full original message attached without the possibility of editing. This is not possible due to privacy reasons.

### Current Workaround

![grafik](https://github.com/freescout-helpdesk/freescout/assets/147406642/1fe20913-f69d-40ed-af7a-dbfb1da166de)

- Open a new ticket in mailbox B to the manufacturer.
- Copy in relevant text and attachments from the customer message manually.
- Send new ticket. Copy ticket link B into a note of the original ticket A. Pin note to top.
- Copy ticket link A into a note of the new ticket B. Pin note to top.

Is there another way for this in Freescout?
If not, it would be a fantastic new feature / module which saves lots of daily hassle.

**Comment by freescout-helpdesk** [comment]
There is no such feature for now.

Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by Marphies** [comment]
Thank you for the link. I see there are related feature requests already that would complete this issue.

**Add customer e-mail to forwarded mails**
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/357651
Just left a comment here. Adding the original e-mail as a quoted block in the editor would be a nice solution.

**Forward Specific Email / Choose Sender**
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/411050
Choosing sender mailbox.

I hope this can be tackled soon! We would for sure buy a module as soon as available.
