### ISSUE TITLE
Issues with downlaods after migrating to a different server and changing domain.

### ISSUE THREAD

**Issue by mikemuller** [freescout-helpdesk/freescout#3733]
We recently moved our ticket platfom to a new server and updated the domain name. All is working fine except any file attachments are not downloading. The attachment folder in the storage/app/attachment directory is there and contains all the files.  When I try to download the file, it appears to download but chrome give an error of "Site Wasn't Available". I assume this is just a setting or path that needs to be updated? Thanks in advance.

**Comment by raramuridesign** [comment]
@mikemuller check your env file if you changed everything there.
Then perhaps do a quick check in the database and search for the old domain, the off chance that there might be reference there.
M

**Comment by freescout-helpdesk** [comment]
Also make sure that paths are correct in your web server config: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server
