### ISSUE TITLE
Bug: To email required when you start a new conversation with emails in BCC

### ISSUE THREAD

**Issue by sydios** [freescout-helpdesk/freescout#3735]
Hello,

I am trying to send an new email to a few customers at the same time for the same issue. 
When I try to add them just to the BCC field so they don't see each other I can't send the email because it demands an email in the To field as well. 

Thanks.

![image](https://github.com/freescout-helpdesk/freescout/assets/7102852/96c27c8a-d16f-4e13-aa42-3d80e9cee9db)

**Comment by freescout-helpdesk** [comment]
In FreeScout conversation needs a recipient (To), it can't exist without "To" recipient.
