### ISSUE TITLE
Translation of SentFolder to norwegian

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3736]
Hi!

It would be nice to have the SentFolder module translated into Norwegian (Norsk bokmål)

"Sent" should be "Sendt"

Additional question: When the translation doesn't exist for that language, we can't seem to find the key and not able to add it ourselves. Is it possible for us to add it manually somehow? We can see the "Sent" key in e.g. german and spanish, but can't see it in norwegian. If it showed up in the list, but as an empty value, we could just fix the missing translations. Maybe it is possible, but we just haven't found it?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Translate

**Comment by freescout-helpdesk** [comment]
Is it related? https://github.com/freescout-helpdesk/freescout/issues/3717

**Comment by borgarlie** [comment]
I don't think so. I don't see any errors on the client side, and translation works for whatever keys exist already.

Do you mind explaining how it is supposed to work?

E.g. how do you get a set of keys with empty values? I assume that is what we should expect?

If I go to module lang folder `/www/html/Modules/SentFolder/Resources/lang`, then I see these exist:
```
cs.json     de.json     es.json     fr.json     it.json     pt-PT.json  zh-CN.json
```

Does that mean it is not possible to add other languages from the UI? or should I still see the keys in other languages with empty value?

**Comment by freescout-helpdesk** [comment]
It is related. Just wait for the next release.

![2024-01-29_17-45-47](https://github.com/freescout-helpdesk/freescout/assets/40499291/285c6445-98f6-4520-887b-77ea0dd833d7)
