### ISSUE TITLE
wrong interpretation/view of emails

### ISSUE THREAD

**Issue by proserver1** [freescout-helpdesk/freescout#3738]
we quite often have problem with viewing emails.
most of the time its a problem because the customer replies "inline" (within the quote of our answer) what I think is OK, but we accept the limitations of a ticket system.

now we have a misinterpreted HTML-Email with quite normal quoating/answering but the complete answer is not shown.
in the screenshot you see

) left side: original email in thunderbird (saying "Danke, sent with huawei....")
) left side: relevant part of the source (its base64)
) right side: HTML view in browser laking everthing the customer answered

html-view in thunderbird and "original view" all the same: not one word of the customers answer

![Screenshot from 2024-01-26 15-05-27](https://github.com/freescout-helpdesk/freescout/assets/5900693/a33fc108-0259-4ad3-ae9f-23b5c6475676)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ

**Comment by proserver1** [comment]
yes I see, you always give that answer. but its just not true. 
at least in this case, it was a total legit answer by email and freescout doest NOT display it correct.
and I wrote it: even "show original view" does NOT display the correct email (like e.g. thunderbird does).

so imo it's a parsing problem, not a "customers dont know how to email" or "this is not the way email works"

**Comment by proserver1** [comment]
i stand corrected... "show original" works and shows the answer of the customer.
