### ISSUE TITLE
Email address in a table creates display issues

### ISSUE THREAD

**Issue by foliovision** [freescout-helpdesk/freescout#374]
Email address in the body of a message in a table or on its own line creates significant display issues. Here's what it looks like in Freescout:

![Freescout-email-display-bug-br-tag-2](https://user-images.githubusercontent.com/1180948/69368999-7cb62f00-0c9b-11ea-92eb-8d1b1a828534.png)

Here's what the code looks like via "Show Original" (nothing wrong with the underlying code):

```
<table cellpadding="4" cellspacing="1">
<tr style="background-color: #DFE3E4">
<td><strong>To whom:</strong></td>
</tr>
<tr>
<td>Web contact form - General Inquiries</td>
</tr>
<tr style="background-color: #DFE3E4">
<td><strong>From:</strong></td>
</tr>
<tr>
<td>Richard Sil</td>
</tr>
<tr style="background-color: #DFE3E4">
<td><strong>Email:</strong></td>
</tr>
<tr>
<td>macup@facon.com</td>
</tr>
<tr style="background-color: #DFE3E4">
<td><strong>Subject:</strong></td>
</tr>
<tr>
<td>Third Time's a Charm</td>
</tr>
<tr style="background-color: #DFE3E4">
<td><strong>Message:</strong></td>
</tr>
<tr>
<td>I've manually fixed the name up there.  But I've also already fixed it in Freescout so I probably have to send yet another form with a different from address.</td>
</tr>
</table>
```

This was in our contact form so it was important to solve. I've solved this issue by:

1. switching to plain text only
2. not putting a line break in front of an email address
~~3. configuring the filled in form from as "$fname$" <$fmail$>~~ This is relevant only to WordPress Filled In users.

These changes have fixed our contact form, thank heavens. On the other hand, the display part of this bug is the kind of bug which can bite again or someone else and should be tracked down. I've documented it in detail so that someone else will perhaps find it in the future.

It's not urgent for us as we've worked around it.

**Comment by freescout-helpdesk** [comment]
Fixed by https://github.com/freescout-helpdesk/freescout/pull/400
Will be included in the next release
