### ISSUE TITLE
prevent notifications and status changes for certain auto replies

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3740]
We are working with a company that is sending an auto reply message on almost every single step they are doing. For example if you send a message to them and you are closing the ticket it is automatically reopened. Also the user is getting a notification. In this case you have to deal with the same thing for free many times per day and user.
I could setup a workflow to change the status back to closed or pending, but this doesn't prevent notifying the user senselessly.

Is there a way to prevent this with FreeScout?

PHP version: 8.2.15
FreeScout version: 1.8.118
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
There is no such feature for now.

**Comment by mokkin** [comment]
I guess this might interest other users too as auto replies are very common.

Should this be part of the workflows module, core app or a new module?

**Comment by mokkin** [comment]
Done: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/431111
