### ISSUE TITLE
Sending attachment does not work on chat module.

### ISSUE THREAD

**Issue by eguvenc** [freescout-helpdesk/freescout#3741]
Please go and try to send attachment on our web address.
[https://oloma.dev/](https://oloma.dev/)

PHP version: 7.1
FreeScout version: Latest
Database: MySQL
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment]
Manage > Logs > App Logs.

**Comment by eguvenc** [comment]
![image](https://github.com/freescout-helpdesk/freescout/assets/482833/95ed1e46-6c42-4afd-82a8-7e3605ac5228)

**Comment by freescout-helpdesk** [comment]
The error from the log is related to another issue: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#allowed-memory-size-of-nnn-bytes-exhausted-error-when-fetching-large-attachments

To figure out the issue with uploading attachments you may need someone who can investigate it on your server including checking web server and PHP config.

**Comment by eguvenc** [comment]
Thanks. After i upgraded to new version it works fine.
