### ISSUE TITLE
HTTPS redirect loop

### ISSUE THREAD

**Issue by 0nen0** [freescout-helpdesk/freescout#3742]
Hi everybody
Im trying to self host Freescout. It should work over our internal reverse proxy with a subdomain-> https://sub.example.domain/ So far so good. I've created the entry on our reverse proxy server and I was able to reach the installation wizzard from Freescout over my HTTPS domain. I was able to to setup all, DB and local admin account. As APP Url I used https://sub.example.domain/. And after I want to finish the setup and pressed on "Login" I get an redirect Error. So I belive my misstake/missunderstanding is in the part with App Url. Because while the setup I was able to reach my instance.

On the webserver I added a virtual host on Port 80 an as server sub.example.domain.
My .env file looks like:

```
# Every time you are making changes in .env file, in order changes to take an effect you need to run:
# php artisan freescout:clear-cache

# Application URL
APP_URL=https://sub.example.domain

# Improve security
SESSION_SECURE_COOKIE=

# Timezones: https://github.com/freescout-helpdesk/freescout/wiki/PHP-Timezones
# Comment it to use default timezone from php.ini
APP_TIMEZONE=Etc/GMT-1

# Default language
APP_LOCALE=en

# Database settings
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=freescout_db
DB_USERNAME=freescout
DB_PASSWORD="MyTopSecurePassword"

# Run the following console command to generate the key: php artisan key:generate
# Otherwise application will show the following error: "Whoops, looks like something went wrong"
APP_KEY=base64:TheAppKey

# Uncomment to see errors in your browser, don't forget to comment it back when debugging finished
#APP_DEBUG=true
``` 

I'm grateful for any help.

**Comment by 0nen0** [comment]
Sorry but I'm not that versed with the whole header forwarding. Do I have to set the force_https to true or something in the .env?

**Comment by 0nen0** [comment]
As additional info, I did not install freescout with the install.sh script. May someone give me some more advice.

**Comment by freescout-helpdesk** [comment]
You may need to find someone who can investigate it on your server.
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
