### ISSUE TITLE
Dark mode end user portal and end user portal questions.

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3743]
Hi,
I have **two questions** about **1. Dark mode** and **2. End user portal**

## 1. Dark mode

From the demo I can see the dark mode is active only on operator / admin side.
There is no dark mode for end user side?
When I go on the knowledge and try to open the page in a new window, all is white, not dark.
There is no dark switch.

## 2. End user portal

In the demo I'm able to open the Knowledge base and the end user portal.
This are two different pages but if I want user have a single page with all inside means the knowledge base as main page and also on the top menu the button to open a ticket?

This is a screenshot of the knowledge base:
![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/8b9f1413-a8dd-4caa-8258-45ea83b2fcfd)

There is no navigation menu to let user create ticket.

The following screenshot show the ticket page submission, there is no link to the knowledge base. There is a way to have this two different pages in just one pages where user can navigate in the menu?

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/045c4ea9-8f27-4a1c-961a-a7036b7235b2)

In both pages I'm unable to see the dark mode active or a switcher to have dark mode active.
This screenshots are from the demo that has enabled the dark mode but seems is working only on operator / admin side?

Thanks.

**Comment by freescout-helpdesk** [comment]
Dark Mode module does not apply to End-User Portal or Knowledge Base.

>  There is a way to have this two different pages in just one pages where user can navigate in the menu?
There is no.

**Comment by PeopleInside** [comment]
Thanks for the reply.

So currently there is no support for end user about dark mode? Should I try to open a feature request?

Thanks

-- 
[https://www.peopleinside.it/wpi22/wp-content/uploads/2022/04/default-monochrome.png]
*Marco Borla*
www.peopleinside.it[https://www.peopleinside.it]
www.marcoborla.com[https://www.marcoborla.com]

[https://livechat.peopleinside.it/livechat/index.php/site_admin/restapi/onlineimage?&online=Live%20chat%20online&offline=Live%20chat%20offline&w=200][live-butt][https://livechat.peopleinside.it/livechat/index.php/site_admin/restapi/onlineimage?&online=Live%20chat%20online&offline=Live%20chat%20offline&w=200]
[https://livechat.peopleinside.it/ita/chat/start/(theme)/9]Il contenuto di questa e-mail potrebbe essere confidenziale e destinato esclusivamente al destinatari specificati nel messaggio; è vietata ogni forma di riproduzione, l'inoltro, la condivisione o la stampa senza consenso scritto del mittente.

The content of this email can be confidential and intended for the recipient specified in the message only; any form of reproduction is prohibited. Forwarding, sharing or printing without the written consent of the sender is prohibited.
 

----------------------------------------

*Da: *FreeScout ***@***.***>
*A: *freescout-helpdesk/freescout ***@***.***>
*CC: *Marco Borla ***@***.***>; Author ***@***.***>
*Data: *29 gen 2024 15:51:33
*Oggetto: *Re: [freescout-helpdesk/freescout] Dark mode end user portal and end user portal questions. (Issue #3743)
