### ISSUE TITLE
Ticket No. Series

### ISSUE THREAD

**Issue by arjit65** [freescout-helpdesk/freescout#3745]
Please give an option in settings in Ticket Module or Mailbox so that for every mailbox, new series of Ticket No. is generated

For Example,
If we have 3 mailbox i.e MailBox1, MailBox2, MailBox3 then give an an option to allot ticket no in MailBox1 as A-1, A2, A3 . Similarly for Mail Box 2 as B1, B2 series and for Mailbox3 as C1,C2,C3 Series

Presently, if 2 conversations are arrived in Mailbox 1 and 3rd is Arrived in MailBox2 then freescout is alloting Ticket No. as 3 ... whereas it should be as Ticket No. 1 as it is the first conversation for MailBox2 . You can also give an option for Prefixes

You can explore to release as separate Module

**Comment by freescout-helpdesk** [comment]
We see that you've created a feature request.
