### ISSUE TITLE
Kanban Module: Show `[All Mailboxes]` by default (or by setting)

### ISSUE THREAD

**Issue by michalpulpan** [freescout-helpdesk/freescout#3746]
PHP version: PHP 8.2.15
FreeScout version: 1.8.119
Kanban version: 1.0.20
Database: MySQL
Are you using CloudFlare: No

Hi! 

firstly, thank you very much for maintaining Freescout project, it helped us a lot.

We're using Kanban module, however we're facing some difficulties that we miss e-mails in different Inboxes, because, by default, our Kanban shows the first Inbox in the list and not the "[All Mailboxes]" / `mailbox_id=-1` option.

Is there any way to force this behavior? 

Thank you in advance!

**Comment by freescout-helpdesk** [comment]
There is no such feature for now. Feel free to submit a feature request: https://freescout.net/request-feature/
