### ISSUE TITLE
Send error with message "552 5.3.4 Message is too long. "

### ISSUE THREAD

**Issue by nczz** [freescout-helpdesk/freescout#375]
Hi,

I'm using AWS SES with FreeScout. I got this 552 error message sometime after few thread discussions.

Any idea for this issue?

Thank you!

**Comment by freescout-helpdesk** [comment]
This is AWS SES response, check with them.

**Comment by nczz** [comment]
@freescout-helpdesk Yes, I see. But anyway to avoid this error in FreeScout? Seems other users face this kind issue too. ref: https://github.com/freescout-helpdesk/freescout/issues/318

**Comment by freescout-helpdesk** [comment]
The only way is to contact AWS SES.

**Comment by nczz** [comment]
@freescout-helpdesk I think if FreeScout can choose how many threads should include in reply email that could be fix this issue. There are so many duplicate threads including in reply email that cause this problem and make email bad readability.

**Comment by freescout-helpdesk** [comment]
Do you mean the number of threads in the email notifications to support agents?

**Comment by nczz** [comment]
@freescout-helpdesk Yes! These threads make the email too fat to send after few rounds discussions.
