### ISSUE TITLE
Subject cut on reply

### ISSUE THREAD

**Issue by InformaticaJBM** [freescout-helpdesk/freescout#3753]
Hello, had weird problem with email subject.  
Receive email with subject 
Fwd: FERREMAYOREO RECOJIDA : **JBM CAMPLLONG** BARCELONA - VERACRUZ // 1X40'HC // FOB ** PO7234 / P06633 / PO6764 / PO7248** - FE1896184

And when agent reply, it converts to 
Re: Fwd: FERREMAYOREO RECOJIDA : **JBM CAMPLLONG** BARCELONA - VERACRUZ // 1X40'HC // FOB ** PO7234 / P06633 / PO6764 / PO7248**

Is there a way to fix it? For me its looks like some length limitation on mail send. 
Thank you

PHP version:  7.4.33
FreeScout version: 1.8.119  
Database: Pgsql (15.4)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Can you share headers of the original email.
