### ISSUE TITLE
Need help with webhooks debugging

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3754]
Hello team, 
This is not an issue. I just need your help with something 
We have a dependency on webhooks module and bought license for it. But I am not getting the webhooks on the target. 
I want to debug it but I dont know where to look exactly. Can you guide me on that 

We did a ubuntu installation and I am looking at /var/www/vhosts/storage/logs currenlty. 
I dont know If i need to look at larvel logs or web server logs. Please guide me. 

Thanks a lot in advance

**Comment by freescout-helpdesk** [comment]
Webhooks have their own logs on Webhooks page. Also your background jobs are running: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

And here is the tool which may help to check webhook requests: https://webhook.site/

**Comment by sarsony1** [comment]
Hello, Thanks for webhook.site. 
Can you be more specific on what you meant by webhooks have their own logs on webhooks page. Didnt get that. 
Can you guide me here

**Comment by sarsony1** [comment]
I actually didnt get what you meant by webhooks page. Can you be more specific on that @freescout-helpdesk
