### ISSUE TITLE
SLA within working hours

### ISSUE THREAD

**Issue by SRTC01** [freescout-helpdesk/freescout#3756]
I have jut started out using Freescout and, I have to say, it does everything I need for an intuitive ticketing system.... except one thing....

And that is... SLA's.

Now I know it's possible, using the Workflow module, to trigger tags and email warnings etc if a ticket has not been responded to within x hours etc.  However, I really need these hours to be considered during workling hours only.

For example:  Say my working hours are 09:00 to 17:00 and a new P1 ticket is submitted at 4pm.  A P1 ticket carries a response time of 4 hours.  Therefore, I need to trigger an email/tag at 12pm the following working day and not at 8pm on the day that the ticket was submitted...

How is this achieved, if at all?

Many thanks in advance.

**Comment by freescout-helpdesk** [comment]
> How is this achieved, if at all?

Unfortunately not.
