### ISSUE TITLE
Allow users to move messages into mailboxes they can't access

### ISSUE THREAD

**Issue by Jonty** [freescout-helpdesk/freescout#3760]
Our users can only access the subset of mailboxes they need access to, but frequently people will email the wrong address and we need to reassign a message to another team.

Currently it's not possible for users to move messages to another mailbox that they don't have access to, which makes this rather frustrating as they have to ask an admin to do it for them.

Is it possible to make the list of mailboxes visible to all users and allow them to move messages to mailboxes they don't have access to?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-i-move-a-conversation-to-some-mailbox-to-which-i-dont-have-access

**Comment by Jonty** [comment]
We would really like these to appear in the drop-down to be selectable rather than forcing our users to enter the address, is that not possible?
