### ISSUE TITLE
WorkFlow scenario not working [Last reply from]

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3761]
**Some details:**
- PHP version: 8.3
- FreeScout version: 1.8.120
- Database: MySQL
- Are you using CloudFlare: Just the name server but not using Cloudflare proxy
- If you need know the version of the Workflow module let me know. I don't know if I can post here.
- If I should not open an issue about a module, please let me know and sorry in advance, I can explain why I'm opening an issue here.
- I had read FAQ and also website help section.
---
**Premise:**
Other workflow tested (different from what I'm reporting) works,
Freescout time is correct because I checked on the page system/status

**What seems is not working?**
All workflows I have created that has rule to check "Last customer reply" or "Last operator reply" seems are not working.

### **1. The first workflow that is working:**
I created a workflow to add two tags: one that indicate that operator replied to the ticket "risposta operatore" and a tag that indicate the ticket is pending user feedback "in attesa di feedback utente".

This works with **the condition**: 
1c. New / reply / moved , user or customer replied and status is equal to pending
**Actions**
- Add the two tags

This workflow works!

Screenshot 1 of 2
![Screenshot 2024-02-04 131207](https://github.com/freescout-helpdesk/freescout/assets/5006150/cc7c9764-6268-4e3c-8cf0-a598fb057c44)

Screenshot 2 of 2
![Screenshot 2024-02-04 131213](https://github.com/freescout-helpdesk/freescout/assets/5006150/fc4cd661-3eee-4962-a6ae-637499944572)

So when the operator made a reply to the customer, the default ticket status will be changed on pending and the workflow to add the two tags will be trigged. Now the ticket of the customer will be pending, will have a reply from the operator and two tags "replied by the operator and waiting user feedback"

### **2. The second workflow that is not working:**

**Condition:** 
1. status is equal to pending
2. Last customer reply is not in the last 3 days
3. Tags doesn't contain "in lavorazione" (translation: working)
4. Tags contain "in attesa di feedback utente" (translation: waiting user feedback)

**Actions**
- Reply to conversation
- Add Tag "Chiuso automaticamente" (translation: closed automatically)
- Change status: closed
- Remove Tags "in attesa feedback utente" (translation: waiting user feedback)

Screenshot 1 of 2
![Screenshot 2024-02-04 130711](https://github.com/freescout-helpdesk/freescout/assets/5006150/51851566-cc4c-4073-83cd-55d276944b9e)

Screenshot 2 of 2
![Screenshot 2024-02-04 130719](https://github.com/freescout-helpdesk/freescout/assets/5006150/948427ce-30a7-432b-87c8-2905f5dca844)

3 days since user and operator replies has been past.
The label waiting user feedback was present in the pending ticket, the status was pending and no working label was present.
The workflow has not been applied.

I tried to change the days from 3 to one and apply to the previously tickets but also in this case the Workflow doesn't works.

---

I hope this topic can help to figure out why and discover if there are some bugs issue.
Thank you.

PS: I will continue to monitoring this to try to understand what can be the cause of this issue.
I have also a workflow that add a view label if the ticket has been view by the customer.
I need to test if the fact a workflow is called maybe forbid another workflow, that should work, to work correctly.

**Comment by PeopleInside** [comment]
I have to confirm this issue.
I created a test MailBox just to test better this BUG.

The test Mail Boxes has no workflow setup so I setup the following Work Flow:
![Screenshot 2024-02-04 211614](https://github.com/freescout-helpdesk/freescout/assets/5006150/5b705e1e-99ca-42e6-aba6-14740ffb5bf7)
![Screenshot 2024-02-04 211625](https://github.com/freescout-helpdesk/freescout/assets/5006150/c6b5da38-1573-4db6-88f0-979bfe34e06e)
![Screenshot 2024-02-04 211633](https://github.com/freescout-helpdesk/freescout/assets/5006150/9d4ee41f-d06a-4088-b3ed-62b44ffc5c43)
![Screenshot 2024-02-04 211639](https://github.com/freescout-helpdesk/freescout/assets/5006150/55a9ba46-fa2c-44b3-afa2-400c342914a2)

![Screenshot 2024-02-04 211658](https://github.com/freescout-helpdesk/freescout/assets/5006150/7eacbbc3-a3eb-4e8f-a9fd-37d4226be4be)
![Screenshot 2024-02-04 211723](https://github.com/freescout-helpdesk/freescout/assets/5006150/b06ddc32-0d35-438c-8c55-13350f29c15f)
![Screenshot 2024-02-04 211746](https://github.com/freescout-helpdesk/freescout/assets/5006150/33a9632d-8e7d-4112-a5cd-47fc669dd623)

As you can see in the screenshots two ticket are present.
One created by the web interface and the other one created by email.

Both tickets has not activated the automatic workflow.
In the email ticket test there is also the operator reply old more then 1 hours (1 hours showed in the screnshot) but workflow has not send any alert and has not closed the ticket.

**Comment by netlane** [comment]
Hello, I think you misunderstood "tags". A tag is a single word only, so "in lavorazione" is actually 2 tags, "in" and "lavorazione".
Looking at it in that way, your conditions are "must contain `_in_` " and "must not contain the tag `_in_` " - so the workflow will never apply.
Ciao, credo che tu abbia frainteso i "tag". Un tag è una sola parola, quindi "in lavorazione" è in realtà 2 tag, "in" e "lavorazione".
In questo modo, le tue condizioni sono "deve contenere `_in_`" e "non deve contenere il tag `_in_`" - quindi il flusso di lavoro non sarà mai applicato.

Ciao, Peter

**Comment by PeopleInside** [comment]
Hi, Ciao Peter (netlane),
thank you for your reply! 

> Hello, I think you misunderstood "tags". A tag is a single word only, so "in lavorazione" is actually 2 tags

Umh this is interesting. Hard for me to understand alone as I use other software where tag is all inside the same background rectangle.

Also when I tell to a workflow to add a tag like "in lavorazione" the tag is added successfully just discovered some workflow is not working as expected.

I will maybe try to test workflow with different tag that has no spaces between words and see if with this I'm able to see workflow working correctly. Thanks.

I will keep this issue open for now as still be valid but I will try to test with tags of just one words and no spaces between letters.

**Comment by PeopleInside** [comment]
I'm asking if I can use "in_lavorazione" so replace the space with the underscore character.
Will this work to be only one tag? I have to test this.

**Comment by netlane** [comment]
Check the list of your tags in Administration > tags 
(The url of that page is yourdomain.com/tags )

**Comment by PeopleInside** [comment]
I know and all seems to be fine here. I see spaces are used to be in the tag as I expect.
I started to test tags without spaces

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/429e7e7e-df8e-4da8-b6a1-cccbb5ac133a)

**Comment by PeopleInside** [comment]
If you also see the developer extension pages https://freescout.net/module/tags/ tags are showed in images with spaces so I think space are supported and should maintain the tag to be a single tag.

**Comment by netlane** [comment]
Ok, so I was wrong, sorry  :(
Please check my new issue #3840 - when the last reply was from a user (you) then there exists no last customer reply. This could also be your problem.

**Comment by PeopleInside** [comment]
Hi, why this issue has been flagged as resolved?
From my recent test with FreeScout issue still be present even on the latest release.

I will monitor my open issue here: https://github.com/freescout-helpdesk/freescout/issues/3762

**Comment by freescout-helpdesk** [comment]
> If you also see the developer extension pages https://freescout.net/module/tags/ tags are showed in images with spaces so I think space are supported and should maintain the tag to be a single tag.

No. Only one tag can be specified in Workflows conditions or actions (no spaces or commas allowed).

**Comment by PeopleInside** [comment]
> No. Only one tag can be specified in Workflows conditions or actions (no spaces or commas allowed).

Thanks for the reply but I'm unable to understand what you are saying.

>Only one tag can be specified in Workflows

What this means?
A workflow can have just one tag as condition or action and if a tag is present in the condition cannot have a tag action?
Your system never limitate the actions or condictions.

I don't understand.
If only one tag is supported then your system should never allow me to add more tags or have multiple actions and condictions.

I'm not understanding.
I'm unable to have ticket overdue workflow.

Unable to have a reminder that alert me if a ticket never get an operator reply in 13, 24 and 48 hours.
I'm also unable to close a ticket if customer never reply to the operator reply.

I created workflows but no one is working.

I'm unable to find a guide how to setup ticket auto close or ticket overdue.

I opened issues here in GitHub with a lot of screenshot that showed what workflow I created and it's not working.

**Comment by PeopleInside** [comment]
I will try to run other test but I do a lot of test.
Some workflow works, some one else not.

I will do other test but... I'm quite sure something is not working correctly.
Thanks for the reply and for re-opening this.

What I expect to be able to do is:

- Set a workflow that remind operator to reply to an active ticket that is never get a reply from operators in 12, 24 and 48 hours and also send an email to the customer.
- Set a workflow that close a ticket if is pending and if no reply from customer has been made after the operator reply.

Currently no one of this workflow are working.
I was just able to see the first overdue label and email. When I do test i change the 12, 24 and 48 hours to be 1 hours, 2 hours, 3 hours.

I will test better and update you but I'm sure something is not working correctly in workflow.
I'm testing very and really simply workflow, nothing of complex.

**Comment by freescout-helpdesk** [comment]
Are you running cron jobs every minute? https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

Try to manually kill background `queue:work` process and see how it goes: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

If still no luck you'll need to debug `checkConditions()` function in /Modules/Workflows/Entities/Workflow.php (line 724): https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by PeopleInside** [comment]
> Are you running cron jobs every minute?

Yes I'm.

Workflow are working where is not bugged.

Can I ask, are you able to create a scenario where you have 3 overdue alert for every hour ( 1 hour, 2 hour and 3 hour) that add 3 different label overdue1, overdue2, overdue3 and send an email notification?

Are you able to create a scenario where if the customer DO NOT reply to the operator reply after some times the ticket is auto closed?

I want you understand that my installation is fully working means ticket are created from email, some workflow are correctly working. What is not working is some specific very simple workflow so looks to me this are bugs in the workflow module.

For example the conduction Last Customer Reply seems is not working.

Are you able to have the following workflow working for you?

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/970707c5-4bfe-4dbe-b94e-8a912758ac18)

You can skip the replied label action if you want

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/163e26da-d05e-4aae-bbc7-082cd71bc150)

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/42230341-a1b2-474f-b3bc-f869992a78f3)

I think if you test this you will find one of the workflow bugs and issues I'm reporting.

**Comment by freescout-helpdesk** [comment]
> Are you able to create a scenario where if the customer DO NOT reply to the operator reply after some times the ticket is auto closed?

Yes. You should use "Is not in the last" 4 hours condition. On your screenshot (before editing) it was "Is in the last" 4 hours.

![2024-03-09_10-13-21](https://github.com/freescout-helpdesk/freescout/assets/40499291/6b906756-60f3-461b-8bef-cc7b04a61cfe)

Also no need to add many scenarios into one issue. It makes it difficult to understand and debug. Good luck.

**Comment by PeopleInside** [comment]
I'm not the only one who fix a message editing it, you done the same in this conversation where you said (before edit a previous message) that spaces in tags are not supported.

> You should use "Is not in the last" 4 hours condition. On your screenshot (before editing) it was "Is in the last" 4 hours.

I know, this is why the screenshot was corrected.
I'm still testing what I'm reporting and I'm sure there is some bug in the workflow.

So you was recently able to create an overdue workflow that add overdue1, overdue2 and overdue3 labels and send alert by email?
I don't believe you tested this.

Now I'm again testing the auto closure of a ticket but I have already tested in the past with the correct "Is not in the last" 4 hours condition and still not work.

You are free maybe to close the issue and ignore what I'm reporting.
Looks quite strange you are able to made this two workflow for overdue and for ticket closure working.

I was hoping in a fix from you.
Looks strange to me all works except some workflow, this let me think there is issues and bug on workflow module.

**Comment by freescout-helpdesk** [comment]
> So you was recently able to create an overdue workflow that add overdue1, overdue2 and overdue3 labels and send alert by email?

Yes. It works fine on our end.

![2024-03-09_14-01-03](https://github.com/freescout-helpdesk/freescout/assets/40499291/b731d812-ce0a-4268-8c1f-61ab65e9083b)

**Comment by PeopleInside** [comment]
Is strange.
Maybe so the issue is in how my FreeScout is installed?

Is installed in a subfolder like helpdesk.domain.ext/support

Maybe something related on how I installed Free scout as for the tools.php page not loading fully CSS maybe your install is installed differently.

I cannot understand how it works to you and not to me and not all workflow are broken just I'm able to trigger the overdue just once and I'm unable to see ticket auto closed.

Will still be a mastery for me.

**Comment by freescout-helpdesk** [comment]
All our suggestions are here: https://github.com/freescout-helpdesk/freescout/issues/3761#issuecomment-1986729263

**Comment by PeopleInside** [comment]
Thanks 
![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/ab6fab6a-dbed-4ed5-a7f3-40b48cfa6fe9)
Maybe I need try to resolve this last thing in red

**Comment by PeopleInside** [comment]
Hi, I run a process to activate the pcntl on Plesk PHP 8.3.3
https://talk.plesk.com/threads/how-to-add-pcntl-support-to-php-8-3.373618/

Doing the SSH command /opt/plesk/php/8.3/bin/php -m | grep pcntl
show me a red line with pcntl , this should means the component is running?!

If I open the /system/status page still showing to me 

![311437275-0e348cb7-7ef4-48ad-a690-52a3c23c1f4f](https://github.com/freescout-helpdesk/freescout/assets/5006150/cb1b4f52-913b-4161-b1bb-be09a1c0ed32)

Any idea why and how can I resolve this?

I need configure something else as I do some process to activate this on PHP after the Freescout install?

**Comment by freescout-helpdesk** [comment]
It means `pcntl_signal` function is disabled in your PHP and PHP can not kill processes. You need to enable this function.

**Comment by PeopleInside** [comment]
Any idea on how to enable it?
I'm searching for that but I fund only instructions on how to see run pcntl but pcntl seems is running.
I will still investigate, I'm looking how to enable pcntl_signal on Plesk.

**Comment by PeopleInside** [comment]
From the server side actually seems all is maybe working.
I do everything I think should be require to activate pcntl.

Someone has told in the config/installer.php, pcntl is commented in the required extension.
I'm sure that I dont need change something in your app for see pcntl working?

**Comment by PeopleInside** [comment]
Hum I tested in a test VPS on Plesk and all was working.
Seems there is an issue on my productive server where I followed the procedure to enable pcntl and from the php info file I see that pcntl is active but freescout still show pcntl_signal not found.

I checked also php.ini file and there is no disable row for pcntl.

Any idea where I can look to understand why freescout is not finding  pcntl_signal?

**Comment by freescout-helpdesk** [comment]
`pcntl_signal` function can be disabled in some PHP config for example: https://stackoverflow.com/questions/52791039/pcntl-async-signals-has-been-disabled-for-security-reasons-ubuntu-16-lara

**Comment by PeopleInside** [comment]
Thanks for the reply.
I'm always in Plesk test VPS and production VPS.
As I told I don't see any php config where this is set to be disabled.

In the link given by you
https://stackoverflow.com/questions/52791039/pcntl-async-signals-has-been-disabled-for-security-reasons-ubuntu-16-lara

the screenshot show the command php artisan queue:work then a security message is printed.

There is a similar procedure I can do with FreeScout to see if is a permission issue?
Currently I was not able to have any particular error that let me think there is a block somewhere.

I will continue to investigate this anyway.

**Comment by PeopleInside** [comment]
I'm still investigating the issue with the Plesk team, also.
They was able to made the SSH command:
/opt/plesk/php/8.3/bin/php artisan freescout:check-requirements

give all results ok 
but in the web UI the page still say pcntl_signal (console PHP) not found.

Strange issue, there is a command I should run to update the UI?

In any case seems made pcntl_signal work on Plesk is or easy or very hard.

In one test server every step I did activated successfully without any issue all.
In two other server is not working fully.

In my production server I have to understand what Plesk did to resolve the requirement by SSH but still not resolved in the UI.
In the test server they was able to get all OK in SSH but not in the web interface where pcntl_signal still showed as missed.

**Comment by PeopleInside** [comment]
Seems if the SSH command 

/opt/plesk/php/8.3/bin/php artisan freescout:check-requirements

is runned as root then pcntl_signal function is not found as the UI said.

If the SSH command is run by the SSH interface of plesk so from the user who the domain are associated then... by SSH pcntl_signal function is showed as OK.

I had to see if I will be able to get help from Plesk to resolve the issue of not being able to see freescout work on Plesk because of pcntl_signal function not found.

**Comment by PeopleInside** [comment]
Finally the solution for fix all requirement was, after some steps to compile the Plesk PHP to support and to have enabled pcntl need access SHH as root, cd / then go on usr/bin and create a symbolic link to the PHP:

ln -s /opt/plesk/php/8.3/bin/php php

With this now also the UI will be aligned.

**Comment by PeopleInside** [comment]
Sadly also if now I have all check passed on /system/status the new test done give evidence that

- ticket are not closed by the workflow if ticket is pending since more then 1 hours change the ticket status to close.
I'm still testing but I think also the overdue 2 will not work.

The last step I miss from you is try to run diagnostic

If still no luck you'll need to debug checkConditions() function in /Modules/Workflows/Entities/Workflow.php (line 724): https://github.com/freescout-helpdesk/freescout/wiki/Debugging

Could you say where I need add the line of code and what exact line of code I need to add?

The link provided by you report this string:

\Log::error('[Debugging] some variable value: '.$some_variable);

At whta line I need add this?
725?

This line should be added without change anything or I need replace $some_variable with something else?
Once added the line what I need to do, wait a minute and check logs?

Thanks

**Comment by MarianBMI** [comment]
Hello @PeopleInside did you manage to fix this? I'm experiencing the same issues. Time-related workflows are not working, no matter what I'm changing. 
All server side configs are correctly done.

**Comment by PeopleInside** [comment]
Hi @MarianBMI 
I'm sorry but I'm not able to help with this.

I don't know what suggestion give and i don't understand well why I was not able to use last reply from.

**Comment by MarianBMI** [comment]
@PeopleInside thanks for the feedback. Are you still using Freescout?

**Comment by PeopleInside** [comment]
@MarianBMI I'm still using Freescout but unfortunately I'm not able to help about the issue I opened and never get a fix because for the team all works.

I tried to read the post again and also some recent iteration you may have on GitHub but I was not able to get a suggestion to give. Sorry. I'm not a developer. I saw also the workflow you are trying to doing and to me looks correct, nice but I remember also with me was not working, I was not able to see the workflow works as I expect.

Maybe we are not understanding something. I don't know :)
I used a workaround in the workflow that now I cannot remember what it was.

If you need support you can ask at the Freescout support or hope in some user that can help.
Maybe hire a developer, something I cannot do... because for me is already hard managing the cost of the server, the panel, license of software, etc. and I'm not into any business :)

I wish you the best and sorry to be not able to give a great suggestion to fix, resolve this issue with workflow :)

**Comment by PeopleInside** [comment]
@MarianBMI I suggest to check in the module page of your FreeScout install if you have the new update about workflow module. From logs seems they released a fix, you can check if this work and resolve for you. 

https://freescout.net/module/workflows/?changelog=1

**Comment by MarianBMI** [comment]
hi @PeopleInside 
I think the update was done after they checked my server as I gave them access directly and they fixed it.
