### ISSUE TITLE
WorkFlow scenario not working [Ticket overdue, multiple alert]

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3762]
PHP version: 8.3
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: Just the name server but not using Cloudflare proxy
If you need know the version of the Workflow module let me know. I don't know if I can post here.
If I should not open an issue about a module, please let me know and sorry in advance, I can explain why I'm opening an issue here.
I had read FAQ and also website help section.

---

I'm investigating this issue to confirm the issue but I'm already pretty sure the issue exist.

I'm unable to set three different workflows to let operator and user to be alerted when an operator reply is not arriving in 12, 24 and 48 hours. For the test purpose timing will be 1 hours, two hours, three hours.

I tested this and worked only for the first workflow so for the first hours.
The next two hours and three hours overdue workflow did not work.

Now I'm testing again changing days in hours so 3 workflow for alert the user and the operator if a reply is not made in 1, 2 or 3 hours.

**The workflow:**
![1](https://github.com/freescout-helpdesk/freescout/assets/5006150/4fc2cfaf-410c-49c2-a3e3-19667dca00d9)

Results screenshot will be posted soon here I suppose in 24 / 48 hours.
Test in progress.

I have already tested this but I'm re testing in a clean testing Mail Box and creating report here.

**Comment by PeopleInside** [comment]
I see that the first workflow that alert by email and add the label > 1 hour overdue worked.

When the Workflow is trigger maybe the waiting time is deserted. I suppose so the first one hours workflow will applied again on the next hours as in this demo test I set the workflow max execution time 3. Let's see if works if I will get another alert email after 1 other hours.

Let's see if after the workflow has been executed the maximum 3 times the other two workflow to alert if the ticket is overdue since 2 and 3 hours will be trigger.

Test in progress. I will update once done.
Closing for now.

**Comment by PeopleInside** [comment]
Issue confirmed. Asap I will post screenshot.

**Comment by PeopleInside** [comment]
![Screenshot 2024-02-05 102835](https://github.com/freescout-helpdesk/freescout/assets/5006150/7feb6c06-8480-4c8a-8602-928dbc7b52a4)
![Screenshot 2024-02-05 102844](https://github.com/freescout-helpdesk/freescout/assets/5006150/a97858ef-2b7a-4c8b-b416-8e9086760ee2)

![Screenshot 2024-02-05 103441](https://github.com/freescout-helpdesk/freescout/assets/5006150/2d5b4e09-389d-4849-b186-2e5fa545b98f)

![Screenshot 2024-02-05 103529](https://github.com/freescout-helpdesk/freescout/assets/5006150/860f3b97-40d0-4ac7-acfd-91ebe613c997)
![Screenshot 2024-02-05 103536](https://github.com/freescout-helpdesk/freescout/assets/5006150/08b699a9-b759-484e-aa86-202709160f91)
![Screenshot 2024-02-05 103545](https://github.com/freescout-helpdesk/freescout/assets/5006150/42851c7d-da0e-4152-b5dd-f740af0ec1c0)
![Screenshot 2024-02-05 103553](https://github.com/freescout-helpdesk/freescout/assets/5006150/a22d74b2-e008-46f0-9a41-c31dd5495a76)
![Screenshot 2024-02-05 103559](https://github.com/freescout-helpdesk/freescout/assets/5006150/2e7710f4-033a-4ef1-8d1c-178a86410248)
![Screenshot 2024-02-05 103604](https://github.com/freescout-helpdesk/freescout/assets/5006150/fa8ec69b-26e7-4263-9aa3-1fd044a9da6e)

As you can see from the screenshots, only workflow 1 was triggered and max execution time was 3 and was executed just once. I did not get other email notification, just the first trigger alert that alert me about ticket overdue of 1 hours.

Two issue here:

1. The workflow to add the label > 1 hour overflow send me just one email. Max execution time was 3 but the workflow has been run just once. Should be not repeated the next hours? This first workflow should be trigged 3 times and in my test was trigged just once.
2. Next two workflow in the screenshot was not trigged. I expect also this two workflow must be trigged. Why they did not activate?

In my test seems I can confirm bugs here, with Workflow.

**Comment by PeopleInside** [comment]
Recently my issue about workflow https://github.com/freescout-helpdesk/freescout/issues/3761 has been closed but from my test, also with the latest update, the issue still exist. Workflow are still not working.

**Comment by PeopleInside** [comment]
I still have this issues and it's very strange.
All workflow work except for SLA and ticket closure.

SLA workflow works only for the first SLA after the first time and not for a second alert and label.
Ticket are not closed when last customer reply is bypassed.

I have all check green in system/status

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/12bd2a39-096d-494f-8cd4-0cb9884ffbe8)

This issue still be valid for me, I really hope to find, with your help what can be then all my system will work correctly and all my issues will be solved.

## What can help me?

If still no luck you'll need to debug checkConditions() function in /Modules/Workflows/Entities/Workflow.php (line 724)
https://github.com/freescout-helpdesk/freescout/wiki/Debugging

Well, what I need to do to debug checkConditions() function?
The linked guide say to use the function
`
\Log::error('[Debugging] some variable value: '.$some_variable);`

How to use that?
I need add this exact string in a line on the code of Workflow.php?
This line should be pasted as it is or I need customize for checkConditions() ?

If you can provide steps to do I will try this last thing. I want see workflow fully work, is bad that ticket are not auto closed and still be frozen in pending state after the operator reply.

Also it's hard to me understand why SLA work only for the first time and not for the others. This means worflow seems work but only partially.

Would be useful also know what workflow rules you used in your test, is mine rules wrong?
I don't think.

For ticket closure I had rule:
Close ticket with no reply
automatic, max ex time 3
if status is equal to pending
and last customer reply is not in the last 1 hours (testing)
change status to close

**Comment by freescout-helpdesk** [comment]
It looks like something does not work well on your server: https://github.com/freescout-helpdesk/freescout/issues/3761#issuecomment-1999546100
It needs to be investigated on your server further.
