### ISSUE TITLE
Protect widget with captcha. Allow widget to be turned off in attack case.

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3763]
PHP version: 8.3
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: Just the name server but not using Cloudflare proxy

---

Can I ask how can I add the re-captcha protection also to the ticket widget?

I have the issue that currently the end user interface for guest don't support multi language so, I need use the English widget for allowing English user to be able to submit a ticket in their language but... this widget page is unprotected from spam.

Can you suggested the part of code to paste in the relative file for protect the widget?

I hope in the future you can implement multi-language also for the user interface for guest user.
I saw today there is a feature request opened but too less votes, very bad :)

[Set End-User Portal language according to browser language](https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/364681)

**Comment by PeopleInside** [comment]
From the widget, if direct URL is discovered, a bot or a spammer seems can create a lot of ticket request without the protection of the recaptcha. In this case admin has no option to turn off the widget so to invalidate the direct widget link.

Can be good for security allow the admin to turn off the widget function and to enable also the captcha as option so maybe a check box in the settings to allow an antispam check also on the widget.

**Comment by freescout-helpdesk** [comment]
Use https://freescout.net/module/extra-security/

**Comment by PeopleInside** [comment]
> Use https://freescout.net/module/extra-security/

I have already this extension and the widget is unprotected.

**Comment by PeopleInside** [comment]
I opened this issue to get help or to see a fix.
The issue has been closed by you but is not resolved.
