### ISSUE TITLE
550 5.7.0 bad DKIM signature data (in reply to end of DATA command)

### ISSUE THREAD

**Issue by mattly6** [freescout-helpdesk/freescout#3765]
Hi, 

So about two weeks ago we started receiving bounce messages from a number of our customers. 
Those are a minority - 50 messages in the last two weeks out of almost 3k sent messages, but it's annoying enough to try and do something about it. 
The messages get bounced by the same set of recipients, no randomness here - if I know the message sent to a customer got bounced in the past, it's certain it would get bounced again.

We are running and accessing Freescout via Zerotier virtual network - could this be the problem here?
So far it worked like a charm and there were no issues with DKIM at all.

We're sending messages via SMTP with TLS, receiving via IMAP with SSL.

When sending the message through mail service provider's website, the messages don't get bounced.

This is an example (anonymised) bounce message received from our mail services provider:

[Automatically generated message]

We are sorry to inform that your mail message was not delivered to one
or more recipients. Its fragment is attached to this e-mail.
You can find the error message below.
__

<customer@mail.com>: host customer.domain.com[<<customer IP>>]
said: 550 5.7.0 bad DKIM signature data (in reply to end of DATA command)
Return-Path: <freescout@mail.com>
Received: from mmw7.pf.interia.pl (unknown [10.217.1.86])
by smtpo.poczta.interia.pl (INTERIA.PL) with ESMTP id B5DD55C86B
for <customer@mail.com>; Mon, 5 Feb 2024 09:46:19 +0100 (CET)
Received: from fmi6.pf.interia.pl (fmi6.pf.interia.pl [127.0.0.1])
by poczta.interia.pl (INTERIA.PL) with ESMTP id 959CAE02F4
for <customer@mail.com>;
Mon, 5 Feb 2024 09:46:19 +0100 (CET)
X-Interia-R: Interia
X-Interia-R-IP: <<our external IP>>
X-Interia-R-Helo: <[172.30.18.39]>
Received: from [172.30.18.39] (unknown [<<our external IP>>]) (using TLSv1.2
with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)) (No client certificate requested)
by interia.eu (INTERIA.PL) with ESMTPSA
for <customer@mail.com>;
Mon, 5 Feb 2024 09:46:19 +0100 (CET)
Message-ID: <reply-84157-616661a471e273db@domain.com>
Date: Mon, 05 Feb 2024 09:46:18 +0100
Subject: Re: Subject
From: Freescout Helpdesk<freescout@mail.com>
To: "customer@mail.com Customer"
<customer@mail.com>
MIME-Version: 1.0
X-FreeScout-Mail-Type: customer.message
References: <a1b74145-a96d-4fdb-8413-f55820ab2168@clientdomain.com>
<reply-80147-74345df26b3418fb@domain.com>
<reply-80155-42ea94d52b0865ba@domain.com>
In-Reply-To: <a1b74145-a96d-4fdb-8413-f55820ab2168@clientdomain.com>
X-IPL-Priority-Group: 0-0
X-Interia-Antivirus: OK
X-EMID: 8f755bf8
Content-Type: multipart/mixed; boundary="C8F18A410C892D3E416A9D19ED4BC99A"
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=interia.pl;
s=biztos; t=1707122779;
bh=eic7yjgFjj4zulXXSJMCSELGskp/fm+buBlQ4N7uyeE=;
h=Message-ID:Date:Subject:From:To:MIME-Version:Content-Type;
b=HMoOjxHciixBE3k1KNYGGJnlOcJ+js3gSlLVh/hm9s9oh9qmLjrnH6N02sXX2DgjC
ZbbnRoRaImDXoc+7AqzZfoIt10g7AYyENMsl5fAoEdQIbOk2wYQGD+/xu6mA0RrOCN
LfPwSRGhqDIGWUmRr2udtChxrmZsM8pny3sRClAk=

PHP version: 8.1.2-1ubuntu2.14
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3419

**Comment by PeopleInside** [comment]
@mattly6 DKIM is something that must be configured on your server side.
The Help Desk system cannot configure DKIM for you because is a server configuration.

There is a website that helps you to test you email and see what can be wrong to not have a 10/10 score.
If I'm not wrong you have three free test available for day or week.
https://www.mail-tester.com/

You can also use the following website to check your email health: https://mxtoolbox.com/emailhealth

I hope this info(s) will help you to figure out what can be wrong.

**Comment by mattly6** [comment]
> @mattly6 DKIM is something that must be configured on your server side. The Help Desk system cannot configure DKIM for you because is a server configuration.
> 
> There is a website that helps you to test you email and see what can be wrong to not have a 10/10 score. If I'm not wrong you have three free test available for day or week. https://www.mail-tester.com/
> 
> You can also use the following website to check your email health: https://mxtoolbox.com/emailhealth
> 
> I hope this info(s) will help you to figure out what can be wrong.

Thank you, I've contacted our mailing services provider and am looking for further assistance. Hopefully it's going to solve our problems.

**Comment by mattly6** [comment]
> > @mattly6 DKIM is something that must be configured on your server side. The Help Desk system cannot configure DKIM for you because is a server configuration.
> > There is a website that helps you to test you email and see what can be wrong to not have a 10/10 score. If I'm not wrong you have three free test available for day or week. https://www.mail-tester.com/
> > You can also use the following website to check your email health: https://mxtoolbox.com/emailhealth
> > I hope this info(s) will help you to figure out what can be wrong.
> 
> Thank you, I've contacted our mailing services provider and am looking for further assistance. Hopefully it's going to solve our problems.


I'm still waiting for the response from mailing services provider, but I noticed a weird thing.
When sending a test mail from Connection Settings panel, the DKIM shows a PASS, but when I send a message from an agent's perspective, the DKIM shows a FAIL.


So that's a PASS:
`Delivered-To: my@mail.com
Received: by 2002:a05:6520:303:b0:285:9997:51b0 with SMTP id gk3csp268452lkb;
        Thu, 8 Feb 2024 07:54:32 -0800 (PST)
        X-Google-Smtp-Source: AGHT+IG5X3QdTb6VMKVL+RI3xDyJ+CyJTDotLiREtKS+hTDd37yjn2UYrq4W4iO6tGktN4WKVpPs
        X-Received: by 2002:a2e:240f:0:b0:2d0:41d1:8124 with SMTP id k15-20020a2e240f000000b002d041d18124mr7250921ljk.1.1707407672195;
        Thu, 08 Feb 2024 07:54:32 -0800 (PST)
        ARC-Seal: i=1; a=rsa-sha256; t=1707407672; cv=none;
        d=google.com; s=arc-20160816;
        b=NTveY+E9bShGgWksAP7koDZatHCTWiqHW3ewjh1zXrALdx6enU4ZmoAv5eaiXoOuFh
        aRJy4KWipacPTrVaHil5MmCAEQO4aDDtmwoteEJgpApCcbGACBc7gTp1TbWWsxgdlVNf
        FY3dj3NPjGja7rpdhCkoIarUCaRoTMN6COybVnnBhzg32c/m27gJTU2Wcd8IrrWBHt6e
        ZArON3MfGoNxo1s2ejk+XFVUAkGT7ckcDTXZWBcLz9qdDcc9iPpAWeFbqQuB216R1ntj
        x/kcdS/bieUaimXTYbm5y0Hego67dlEe+lW2GsP9h/hOETLiQZTC9ZLAMFF4mGYNFeAj
        6zbA==
        ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=dkim-signature:mime-version:to:from:subject:date:message-id;
        bh=HmwNW0sGpjkqvCLHC8iuO7w8bLs4jqnIzA7PMwlWRw8=;
        fh=QwnPi3pnkHn3lioazsfuRWD297lzmBc2EstosLaT/aU=;
        b=LLS8nCYviEyKAuiZ0jQXNprFm8n18xi/TZo2XzXUs8jcc7fOGDnrkYTgPlDc+u5sYS
        9aft4zxCpSv92CIN49dLjvffe2+yKltRdwiWcYmh3Tcl6W5ALRFVrB3FvzVYPbynKeGU
        x823dN34xuri+8hJPmwJRurMl7Cnn+3tri95tLYLAp+UhhzRM7YN+S7HHaTQCo+3vr+w
        KIwyhMGIkEvE0xwiF8zltwjjW2lkd64zF/bS09S4Ad98qM4L8m47sGot3KIJb2Cmxwoh
        L3r23DBQER5PU2VFWplgJ4d/gHL1fW3KyenuqP0knt+/w0uxgHH86BbgcMSVIvi1uTMj
        K5iw==;
        dara=google.com
        ARC-Authentication-Results: i=1; mx.google.com;
        dkim=pass header.i=@interia.pl header.s=biztos header.b="bkVZ/pHp";
        spf=pass (google.com: domain of our@company.mail designates 217.74.67.59 as permitted sender) smtp.mailfrom=our@company.mail;
       dmarc=pass (p=QUARANTINE sp=NONE dis=NONE) header.from=....pl
               Return-Path: <our@company.mail>
        Received: from smtpo59.interia.pl (smtpo59.interia.pl. [217.74.67.59])
        by mx.google.com with ESMTPS id n6-20020a2e8786000000b002d097cfb924si81249lji.320.2024.02.08.07.54.32
        for <my@mail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 08 Feb 2024 07:54:32 -0800 (PST)
        Received-SPF: pass (google.com: domain of our@company.mail designates 217.74.67.59 as permitted sender) client-ip=217.74.67.59;
        Authentication-Results: mx.google.com;
        dkim=pass header.i=@interia.pl header.s=biztos header.b="bkVZ/pHp";
        spf=pass (google.com: domain of our@company.mail designates 217.74.67.59 as permitted sender) smtp.mailfrom=our@company.mail;
       dmarc=pass (p=QUARANTINE sp=NONE dis=NONE) header.from=....pl
               Received: from [172.30.18.39] (unknown [<<IP>>])	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))	(No client certificate requested) by ag.....pl (INTERIA.PL) with ESMTPSA	for <my@mail.com>; Thu,
        8 Feb 2024 16:54:31 +0100 (CET)
        Message-ID: <52f01d9f4f1f3a1650aa964d7e2fb389@172.30.18.39>
        Date: Thu, 08 Feb 2024 16:54:31 +0100
        Subject: FreeScout Testowy E-mail
        From: ... <our@company.mail>
        To: my@mail.com
MIME-Version: 1.0
        X-FreeScout-Mail-Type: test.mailbox
        X-IPL-Priority-Group: 0-0
        X-EMID: 6b5758ee
        Content-Type: multipart/related; boundary="=-j/0xFuwxxTCpzAa1cSwk"
        DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=interia.pl; s=biztos; t=1707407671; bh=HmwNW0sGpjkqvCLHC8iuO7w8bLs4jqnIzA7PMwlWRw8=; h=Message-ID:Date:Subject:From:To:MIME-Version:Content-Type; b=bkVZ/pHpkoYn+tFMBU9hfoOk17+32DJ5H011yY5S9tPdC+hAaT5y0xu0Ik+3NfsAc
        nWkcqCtUBHAkPIdpQg5wUl2lPT3tsTlexJ6HRHKXNG5qp3+Y5YKXPNoMJE+XK0Y3bn
        2Ch9oNkbKkNCwmvDFQGaciG7q8OSprX5Muju+cHk=

        --=-j/0xFuwxxTCpzAa1cSwk
        Content-Type: text/html; charset="utf-8"
        Content-Transfer-Encoding: quoted-printable

<html lang=3D"en" style=3D"background: #F1F3F5; height: 100% !important; ma=
        rgin: 0; padding: 0; width: 100% !important">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8=
        " />
<meta charset=3D"utf-8" />
<meta name=3D"viewport" content=3D"width=3Ddevice-width" />
<meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge" />
</head>

<body leftmargin=3D"0" topmargin=3D"0" marginwidth=3D"0" marginheight=3D"0"=
        style=3D"background: #F1F3F5; height: 100% !important; margin: 0 auto; pad=
        ding: 0; width: 100% !important" bgcolor=3D"#F1F3F5">
        =09<table bgcolor=3D"#F1F3F5" cellpadding=3D"0" cellspacing=3D"0" border=3D=
        "0" height=3D"100%" width=3D"100%" style=3D"border: 0; border-collapse: col=
        lapse; border-spacing: 0 !important; margin: 0 auto; mso-table-lspace: 0pt;=
        mso-table-rspace: 0pt; vertical-align: top">
        =09=09<tr>
=09=09=09<td style=3D"mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertica=
        l-align: top" valign=3D"top">
        =09=09=09=09<table border=3D"0" width=3D"600" cellpadding=3D"0" cellspacing=
        =3D"0" align=3D"center" style=3D"background: #F1F3F5; border: 0; border-col=
        lapse: collapse; border-spacing: 0 !important; margin: auto; mso-table-lspa=
        ce: 0pt; mso-table-rspace: 0pt; vertical-align: top; width: 600px" bgcolor=
        =3D"#F1F3F5">
        =09=09=09=09=09
<tr>
          =09<td height=3D"40" style=3D"font-size: 0; line-height: 0; mso-t=
        able-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" valign=3D"top=
        ">=C2=A0</td>
</tr>

<tr>
          =09<td style=3D"mso-table-lspace: 0pt; mso-table-rspace: 0pt; ver=
        tical-align: top" valign=3D"top">
        =09=09<table border=3D"0" width=3D"600" cellpadding=3D"0" cellspa=
        cing=3D"0" align=3D"center" style=3D"background: #ffffff; border: 0; border=
        -collapse: collapse; border-spacing: 0 !important; margin: 0 auto; mso-tabl=
        e-lspace: 0pt; mso-table-rspace: 0pt; width: 100%" bgcolor=3D"#ffffff">
        =09=09=09<tr>
          =09=09=09=09<td style=3D"mso-table-lspace: 0pt; mso-table-rspace:=
        0pt; padding: 40px 50px 30px; vertical-align: top" valign=3D"top">

        =09=09=09=09  =09<div style=3D"color:#2a3b47;fo=
        nt:500 20px/26px 'Helvetica Neue',Helvetica,Arial,sans-serif">Gratulacje! T=
        woja skrzynka pocztowa mo=C5=BCe wysy=C5=82a=C4=87 e-maile! </div>
        =09<p style=3D"color:#72808e;font:400 16px/26px 'Helvetica Neue',Helvetica,=
        Arial,sans-serif;padding:0">
        =09=09To jest wiadomo=C5=9B=C4=87 testowa wys=C5=82ana przez <strong>FreeSc=
        out</strong>. Oznacza to, =C5=BCe ustawienia poczty wychodz=C4=85cej skrzyn=
        ki pocztowej <a href=3D"http://172.30.18.39/mailbox/connection-settings/1/o=
        utgoing" style=3D"border:0;color:#3197d6;text-decoration:none" target=3D"_b=
        lank">mail name</a> s=C4=85 w porz=C4=85dku.
        =09</p>
        =20
        =09=09=09=09</td>
        =09=09=09</tr>

        =09=09</table>
        =09=09=09=09=09=09</td>
        =09=09=09=09=09</tr>
        =09=09=09=09=09<tr>
=09=09=09=09=09=09<td style=3D"mso-table-lspace: 0pt; mso-table-rspace: 0pt=
        ; vertical-align: top" valign=3D"top"><table border=3D"0" width=3D"600" cel=
        lpadding=3D"0" cellspacing=3D"0" align=3D"center" style=3D"background: #F1F=
        3F5; border: 0; border-collapse: collapse; border-spacing: 0 !important; ma=
        rgin: 0 auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%" bg=
        color=3D"#F1F3F5">
        =09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td height=3D"25" style=3D"font-size: 0; line-heigh=
        t: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" va=
        lign=3D"top">=C2=A0</td>
        =09=09=09=09=09=09=09</tr>
        =09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td align=3D"center" style=3D"color: #8c93a0; font-=
        family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; li=
        ne-height: 22px; mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: =
        center; vertical-align: top" valign=3D"top">
        =09=09=09=09=09=09=
        =09=09</td>
        =09=09=09=09=09=09=09</tr>
        =09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td height=3D"25" style=3D"font-size: 0; line-heigh=
        t: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top" va=
        lign=3D"top">=C2=A0</td>
        =09=09=09=09=09=09=09</tr>
        =09=09=09=09=09=09</table>
        =09=09=09=09=09=09</td>
        =09=09=09=09=09</tr>
        =09=09=09=09</table>
        =09=09=09</td>
        =09=09</tr>
        =09</table>
<div style=3D"color:#1D497D;font-size:14px;">
<br>

<a href=3D"mailto:our@company.mail">our@company.mail</a><br>=
        =20
<br><img src=3D"cid:data-inpl-footer@..._logo" width=3D"104" height=3D"18=
        " alt=3D"..."> </div></body>
</html>

        --=-j/0xFuwxxTCpzAa1cSwk
        Content-Type: image/png
        Content-Id: <data-inpl-footer@..._logo>
        Content-Disposition: inline
        Content-Transfer-Encoding: base64


        --=-j/0xFuwxxTCpzAa1cSwk--`

And that one is a FAIL:
`    Message ID	<reply-87033-efe2c3645d1dca46@ag.....pl>
        Created on:	8 February 2024 at 16:56 (Delivered after 1 second)
        From:	... <our@company.mail>
        To:	Mateusz L <my@mail.com>
        Subject:	Subject
        SPF:	PASS with IP 217.74.67.57 Learn more
        DKIM:	'FAIL' with domain interia.pl Learn more
        DMARC:	'PASS' Learn more


        Download original	Copy to clipboard
        Delivered-To: my@mail.com
Received: by 2002:a05:6520:303:b0:285:9997:51b0 with SMTP id gk3csp269263lkb;
        Thu, 8 Feb 2024 07:56:06 -0800 (PST)
        X-Google-Smtp-Source: AGHT+IFvx3ImajJ4NTH3OSXrZxWfFA2aeB4GTKDZ+754oYlziBXeSv7oxHrC0D7h/UJtREwnJpEE
        X-Received: by 2002:a05:6512:108b:b0:511:706a:81c5 with SMTP id j11-20020a056512108b00b00511706a81c5mr1271824lfg.3.1707407765805;
        Thu, 08 Feb 2024 07:56:05 -0800 (PST)
        ARC-Seal: i=1; a=rsa-sha256; t=1707407765; cv=none;
        d=google.com; s=arc-20160816;
        b=hwXcvQstXCkv6zz6/3cA/lTuqdpErFrI4aOwxQBXHbmB0+K1MyuVSH3yHTvuu/WmCt
        UBBcq5eusAuDSQuvTYztMS7e3ZmSUoSEkGejSOiKJt7WgHxe4PU7045eL4dd34SvqSes
        sY869lKqsMHuMWQ8Dbu8rGq6LOkCwivI9GMmrVzf3ssOsnBcDmIjQR9RrFIxbkWD1GFg
        zauj/7uyfsCO5SXAAxe9RxaHmrd/fJtzmwJq1EOQgQwz8KZxGZaD/ydqh9stsHYY1wmf
        zUDC+gfgvMBp1OLlwg58GI6mni03AdsJFN8ob8AOpPG/yesUjTtmCGkCOe/5oE+j5aag
        lvKQ==
        ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=dkim-signature:mime-version:to:from:subject:date:message-id;
        bh=R2c6tzqVxu3iKObsbZuWT8ShU6bYuR8YEMgicVrwesE=;
        fh=v3IVNPxjt6FG9dMlP5ct10pNHiY4AUuBk/9PaGC94Yc=;
        b=D7Pu6ssIRQGEd99tbbWu219A1nLqRUz8rckNTf3YHqjggEGLNGi/1EBHNTgxRO9GMW
        i8lr1oTxtlL+2MPc0cTUzO+Lj2CwU+2tIfNxzct09cGEZxaQqtUB6Mgfz89BFlQfnULs
        TVplmz2fT4kC0FQ5dAq1ObYJdc8tKvxVSVcTyk3C0kdtdAeGzeMs/b7mufS54y49r7vs
        vuK/mzZV15Xfe4UbYFRsKPRw2u1tKzmXr7wwd+tlt4QKZnWpu5mR85abHxad9vS+6sWB
        LBQHJaSMt5505zXVLoVbaQwTs97EdHw4vxYbC3ys31lyk4mfA9KL82XpPhUmnQ3a1jCm
        yAVg==;
        dara=google.com
        ARC-Authentication-Results: i=1; mx.google.com;
        dkim=neutral (body hash did not verify) header.i=@interia.pl header.s=biztos header.b=mmZbYat9;
        spf=pass (google.com: domain of our@company.mail designates 217.74.67.57 as permitted sender) smtp.mailfrom=our@company.mail;
       dmarc=pass (p=QUARANTINE sp=NONE dis=NONE) header.from=....pl
               Return-Path: <our@company.mail>
        Received: from smtpo57.interia.pl (smtpo57.interia.pl. [217.74.67.57])
        by mx.google.com with ESMTPS id s17-20020a056512315100b0051156cf0826si82187lfi.615.2024.02.08.07.56.05
        for <my@mail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 08 Feb 2024 07:56:05 -0800 (PST)
        Received-SPF: pass (google.com: domain of our@company.mail designates 217.74.67.57 as permitted sender) client-ip=217.74.67.57;
        Authentication-Results: mx.google.com;
        dkim=neutral (body hash did not verify) header.i=@interia.pl header.s=biztos header.b=mmZbYat9;
        spf=pass (google.com: domain of our@company.mail designates 217.74.67.57 as permitted sender) smtp.mailfrom=our@company.mail;
       dmarc=pass (p=QUARANTINE sp=NONE dis=NONE) header.from=....pl
               Received: from [172.30.18.39] (unknown [<<IP>>])	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))	(No client certificate requested) by ag.....pl (INTERIA.PL) with ESMTPSA	for <my@mail.com>; Thu,
        8 Feb 2024 16:56:05 +0100 (CET)
        Message-ID: <reply-87033-efe2c3645d1dca46@ag.....pl>
        Date: Thu, 08 Feb 2024 16:56:04 +0100
        Subject: Subject
        From: ... <our@company.mail>
        To: Mateusz L <my@mail.com>
        MIME-Version: 1.0
        X-FreeScout-Mail-Type: customer.message
        X-IPL-Priority-Group: 0-0
        X-EMID: 1a2dbf8
        Content-Type: multipart/alternative; boundary="A423BA8854199CEB58ABE17A79F35B22"
        DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=interia.pl; s=biztos; t=1707407765; bh=m+emEUKwX1lE9UGLxuOvgDW3kKxoLrDHC+9cTzOY2cE=; h=Message-ID:Date:Subject:From:To:MIME-Version:Content-Type; b=mmZbYat9HAcFAWH6cRtNoYZQCjzndyuQ6vsKY5SmmPNm5bhtvOYtUZiQUBVzHFozW
        cYrMjsODwkAGSjUJcY2MTillcagSPye+LAneHfAaneJgpgCsVxKAbDajY50Y3HMVe5
        a+e2RfPc8LGNedpN3GTmdiy8Lfp3Uf9a4xOd8o2c=

        --A423BA8854199CEB58ABE17A79F35B22
        Content-Type: text/plain; charset="utf-8"
        Content-Transfer-Encoding: 8bit
        
<< CONTENT HERE >>

</div>
</div>
</div>

        =09=09=09<div style=3D"height:1px"><div style=3D"border-bottom:1px solid #e=
        7e7e7;"></div></div>
        =09=09=09<div style=3D"height:15px;"></div>
        =09=09=09=09=09=09<div style=3D"height:0; font-size:0px; line-height:0px; c=
        olor:#ffffff;">=09                    =09
        =09=09=09=09=09=09<span style=3D"font-size: 0px; line-height: 0px; color:#f=
        fffff !important;"> &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;=
        &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwn=
        j; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &z=
        wnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; =
        &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj=
        ; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zw=
        nj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &=
        zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;=
        &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwn=
        j; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &z=
        wnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj; &zwnj;{#FS:cmVwbHktODcwMzMtZWZlMmMz=
        NjQ1ZDFkY2E0NkBhZy53YXJ0YS5wbA=3D=3D#}</span>
        =09=09</div>
        =09</div>
<div style=3D"color:#1D497D;font-size:14px;">
<br>

<a href=3D"mailto:our@company.mail">our@company.mail</a><br>=
        =20
<br><img src=3D"cid:data-inpl-footer@..._logo" width=3D"104" height=3D"18=
        " alt=3D"..."> </div></body>
</html>


        --=-lPXtp/t4eCSAlPiz6j8q
        Content-Type: image/png
        Content-Id: <data-inpl-footer@..._logo>
        Content-Disposition: inline
        Content-Transfer-Encoding: base64


        --=-lPXtp/t4eCSAlPiz6j8q--
        --A423BA8854199CEB58ABE17A79F35B22--`
