### ISSUE TITLE
Enhancement Request: Filter tags by Date & Inboxes

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-helpdesk/freescout#3766]
Requesting the addition of filtering options for tags based on creation/modification date and specific inboxes in FreeScout like `HelpScout`. This enhancement would improve tag management efficiency by enabling users to organize tags more effectively according to relevant timeframes and contexts.

Screenshot of Filter by Date - HelpScout
<img width="319" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/34626059/ee201199-aeb4-4319-b62e-8cdff970ef18">

Screenshot of Filter by Inboxes - HelpScout
<img width="275" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/34626059/85f0cb25-744a-4c1d-9c4f-a7ad40f952a2">

**Comment by PeopleInside** [comment]
Hi, feature request should be searched then posted here if never exist: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/recent
