### ISSUE TITLE
Question about Export conversations and Date and Time upload

### ISSUE THREAD

**Issue by vy34vlg** [freescout-helpdesk/freescout#3767]
Freescout is used with 2 extensions are Reports and Export conversations.

Is it possible to upload tickets to a CSV file, and for the fields' created _ at ',' updated _ at ',' last _ reply _ at ',' closed _ at ',' user _ updated _ at ', upload the entire Date and Time?

Can this be set up using standard means?
If not, where do you want to change the date to be uploaded in Date & Time format?

Reports module: 1.0.37
Export conversations module: 1.0.8

PHP version: PHP 7.4.30
FreeScout version: 1.8.120 
Database: PostgreSQL 14.5
Are you using CloudFlare: No

**Comment by vy34vlg** [comment]
Not relevant. Depends on the editor in which the file opens.

**Comment by freescout-helpdesk** [comment]
We could not understand what you were saying.
