### ISSUE TITLE
reset user password error

### ISSUE THREAD

**Issue by Remon-Nagy** [freescout-helpdesk/freescout#3768]
i configured mailbox setting and it work fine for customer and sending replays but i have error when i try to make reset password for user give me error check internet connection and when i view logs i found the error below : 
Send error. Failed to authenticate on SMTP server with username "support@example.com" using 2 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535 Incorrect authentication data " in C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:457 Stack trace: #0 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode() #1 C:\inetpub\wwwroot\support\overrides\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand() #2 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\Auth\LoginAuthenticator.php(36): Swift_Transport_EsmtpTransport->executeCommand() #3 C:\inetpub\wwwroot\support\overrides\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\AuthHandler.php(177): Swift_Transport_Esmtp_Auth_LoginAuthenticator->authenticate() #4 C:\inetpub\wwwroot\support\overrides\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo() #5 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand() #6 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start() #7 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(451): Swift_Mailer->send() #8 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage() #9 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(119): Illuminate\Mail\Mailer->send() #10 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(250): Illuminate\Mail\Mailable->send() #11 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(205): Illuminate\Mail\Mailer->sendMailable() #12 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\PendingMail.php(99): Illuminate\Mail\Mailer->send() #13 C:\inetpub\wwwroot\support\app\Jobs\SendAlert.php(71): Illuminate\Mail\PendingMail->send() #14 [internal function]: App\Jobs\SendAlert->handle() #15 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(28): call_user_func_array() #16 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #17 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(27): Illuminate\Container\BoundMethod::callBoundMethod() #18 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call() #19 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call() #20 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() #21 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #22 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then() #23 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(48): Illuminate\Bus\Dispatcher->dispatchNow() #24 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(76): Illuminate\Queue\CallQueuedHandler->call() #25 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(320): Illuminate\Queue\Jobs\Job->fire() #26 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(270): Illuminate\Queue\Worker->process() #27 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(114): Illuminate\Queue\Worker->runJob() #28 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(100): Illuminate\Queue\Worker->daemon() #29 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker() #30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle() #31 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(28): call_user_func_array() #32 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #33 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(27): Illuminate\Container\BoundMethod::callBoundMethod() #34 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call() #35 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call() #36 C:\inetpub\wwwroot\support\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute() #37 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Symfony\Component\Console\Command\Command->run() #38 C:\inetpub\wwwroot\support\vendor\symfony\console\Application.php(992): Illuminate\Console\Command->run() #39 C:\inetpub\wwwroot\support\vendor\symfony\console\Application.php(255): Symfony\Component\Console\Application->doRunCommand() #40 C:\inetpub\wwwroot\support\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun() #41 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Console\Application.php(88): Symfony\Component\Console\Application->run() #42 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(121): Illuminate\Console\Application->run() #43 C:\inetpub\wwwroot\support\artisan(60): Illuminate\Foundation\Console\Kernel->handle() #44 {main}. Authenticator PLAIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535 Incorrect authentication data " in C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:457 Stack trace: #0 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode() #1 C:\inetpub\wwwroot\support\overrides\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand() #2 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\Auth\PlainAuthenticator.php(35): Swift_Transport_EsmtpTransport->executeCommand() #3 C:\inetpub\wwwroot\support\overrides\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\AuthHandler.php(177): Swift_Transport_Esmtp_Auth_PlainAuthenticator->authenticate() #4 C:\inetpub\wwwroot\support\overrides\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo() #5 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand() #6 C:\inetpub\wwwroot\support\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start() #7 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(451): Swift_Mailer->send() #8 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage() #9 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(119): Illuminate\Mail\Mailer->send() #10 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(250): Illuminate\Mail\Mailable->send() #11 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(205): Illuminate\Mail\Mailer->sendMailable() #12 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Mail\PendingMail.php(99): Illuminate\Mail\Mailer->send() #13 C:\inetpub\wwwroot\support\app\Jobs\SendAlert.php(71): Illuminate\Mail\PendingMail->send() #14 [internal function]: App\Jobs\SendAlert->handle() #15 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(28): call_user_func_array() #16 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #17 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(27): Illuminate\Container\BoundMethod::callBoundMethod() #18 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call() #19 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call() #20 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() #21 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #22 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then() #23 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(48): Illuminate\Bus\Dispatcher->dispatchNow() #24 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(76): Illuminate\Queue\CallQueuedHandler->call() #25 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(320): Illuminate\Queue\Jobs\Job->fire() #26 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(270): Illuminate\Queue\Worker->process() #27 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(114): Illuminate\Queue\Worker->runJob() #28 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(100): Illuminate\Queue\Worker->daemon() #29 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker() #30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle() #31 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(28): call_user_func_array() #32 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #33 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\BoundMethod.php(27): Illuminate\Container\BoundMethod::callBoundMethod() #34 C:\inetpub\wwwroot\support\overrides\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call() #35 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call() #36 C:\inetpub\wwwroot\support\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute() #37 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Symfony\Component\Console\Command\Command->run() #38 C:\inetpub\wwwroot\support\vendor\symfony\console\Application.php(992): Illuminate\Console\Command->run() #39 C:\inetpub\wwwroot\support\vendor\symfony\console\Application.php(255): Symfony\Component\Console\Application->doRunCommand() #40 C:\inetpub\wwwroot\support\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun() #41 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Console\Application.php(88): Symfony\Component\Console\Application->run() #42 C:\inetpub\wwwroot\support\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(121): Illuminate\Console\Application->run() #43 C:\inetpub\wwwroot\support\artisan(60): Illuminate\Foundation\Console\Kernel->handle() #44 {main}.. Message-ID:

**Comment by freescout-helpdesk** [comment]
Check Manage > Settings > Mail Settings.
