### ISSUE TITLE
Api Webhooks - Custom Fields Module - Display on profil customers

### ISSUE THREAD

**Issue by profexpress** [freescout-helpdesk/freescout#3770]
Freescout : v1.8.120 
API and Webhooks : 1.0.74
Customers Management: 1.0.43

It seems to have a bug into the "edit customers" or display

We have set a customer-fields "statut", on dropdown type

In this case the value are :  AAA, BBB, CCC

we asked that it be in the profiles and in the conversations :

![image](https://github.com/freescout-helpdesk/freescout/assets/21359948/6de9f842-2e9f-4970-9cb9-a3489cc62dfa)

It displays well in conversation

![image](https://github.com/freescout-helpdesk/freescout/assets/21359948/faea3c4b-8b12-4feb-929e-57744c228ca2)

but if you go to the conversation or to the customer's profile, it's empty.

![image](https://github.com/freescout-helpdesk/freescout/assets/21359948/edad3660-1ca6-4ee7-ab6a-6fc7606a0ce1)

Profils 

![image](https://github.com/freescout-helpdesk/freescout/assets/21359948/d7364a45-b95f-4111-a853-208f16791c18)

The status is set by the API module

**Comment by freescout-helpdesk** [comment]
Please share your API request.
