### ISSUE TITLE
Custom Folder: Order changes

### ISSUE THREAD

**Issue by obstschale** [freescout-helpdesk/freescout#3773]
PHP version:  7.4.33
FreeScout version: 1.8.120
Database: Mysql (5.5.5-10.5.22-MariaDB-1:10.5.22+maria~ubu2004) 
Are you using CloudFlare:  No

I use "Custom Folders". When I add a fourth folder the order of links in our sidebare changes.

| 3 Folder | 4 Folder |
|--------|--------|
| ![CleanShot 2024-02-07 at 12 17 03](https://github.com/freescout-helpdesk/freescout/assets/1058710/6f2808be-625e-495d-9c9e-698a501f4875) | ![CleanShot 2024-02-07 at 12 17 21](https://github.com/freescout-helpdesk/freescout/assets/1058710/ae0a14a4-36e8-414a-81a8-e9a4ffe3b3f4) |

As you can see, the MINE Folder is not 2nd anymore and the Team Folder are moving up. Also Snoozed has a different place.

**Comment by freescout-helpdesk** [comment]
Are all modules up-to-date?
Are you using any non-official or custom modules?

**Comment by obstschale** [comment]
System and Modules are all up to date. I have one custom module, which does not hook into this menu list. I have deactivated my custom module to make sure this is not the problem.

I have installed and activated the following modules:

- API and Webhooks
- Block external Images
- Checklists
- CRM
- Custom Fields
- Custom Folders
- Customer Data Enrichment
- Customization & Rebranding
- Email Commands
- Extended Attachments
- Extended Editor
- Followers
- GDPR
- Global Mailbox
- Kanban
- Keyboard Shortcuts
- Mentions
- Mobile Notification
- Noreply E-Mails
- oAuth & Social Login
- Reports
- Rocket Chat
- Satisfaction Ratings
- Saved Replies
- Send Later
- Snooze
- Spam Filter
- Sticky Notes
- Tags
- Teams
- Ticket Number
- Time Tracking
- Wallboards
- Workflows

**Comment by freescout-helpdesk** [comment]
We'll return to this if we'll manage to reproduce it.

**Comment by johanoloflindberg** [comment]
I also have the same problem? 😫

**Comment by markusuidl** [comment]
@freescout-helpdesk  we have the same problem, is it possible to set a fixed order for the folders?

**Comment by andrewlimaza** [comment]
Any update on this? Is there a filter we can use to reorder this stuff?

**Comment by andrewlimaza** [comment]
I used the following code to squeeze custom folders (Custom Folders Module) above the default folders:

```php
// Reorder the mailbox folders, maintain the default folders structure and squeeze in custom folders above the default. Default folders are 'type' 1-80, custom folders are 81+.
\Eventy::addFilter('mailbox.folders', function ($folders, $mailbox) {
    return $folders
        ->filter(fn($folder) => $folder->type > 80)  // Pull high-priority types first
        ->concat($folders->filter(fn($folder) => $folder->type <= 80) ) // Append the default as-is
        ->values();
}, 90, 2);
```
