### ISSUE TITLE
Issue with Sat Rating Workflow Conditions Triggering After Rating Submission

### ISSUE THREAD

**Issue by sumodhar** [freescout-helpdesk/freescout#3774]
**Issue:**
Sat Rating Workflow Conditions are not triggering as expected when the rating mode selected is the following - Save rating after Send button is clicked on the rating page

**Expected Behavior:**
We expect the Sat Rating Workflow Conditions to trigger and execute the specified actions after the user submits the rating by clicking the "Send" button on the rating page.

**Steps to Reproduce:**

1. Navigate to the Sat Rating Workflow Conditions setup in FreeScout.
2. Configure the desired conditions and actions.
3. On the rating page, rate the experience and click the "Send" button to submit the rating.
4. Observe that the Sat Rating Workflow Conditions fail to trigger.

If we use the first option of the saving mode the workflow triggers as expected. Can you help review this issue?

PHP version: 7.4.33
FreeScout version: 1.8.118
Database: MySQL 
Are you using CloudFlare: Not sure

**Comment by freescout-helpdesk** [comment]
Fixed in Satisfaction Ratings Module v1.0.23
