### ISSUE TITLE
Need add a script on knowledge and ticket page. What core file can I edit to add that?

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3775]
PHP version: 8.3
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: Just the name server but not using Cloudflare proxy
End user module updated to the latest version.
Browser used Firefox 122.0

---

I need put a script in the knowledge base and in the page where user open a ticket.
How can I do?

From the FreeScout interface I see this is not possibile and I broke my installation when I tried to put that on the field that let customize the footer.

I suppose currently FreeScout never allow me to insert a script code in the pages.
Can you suggest if I can edit some core file to insert my script, even if I know this will be lost on every update?

Thanks.

**Comment by PeopleInside** [comment]
I found the page where put the script but I get the error:
`The script loading a resource to inline was blocked by page settings (“script-src”)`

After a deeper investigation I discovered the SRC policy is set in the app/config/app.php file where I found:

```
    /*
    |--------------------------------------------------------------------------
    | Enable Content-Security-Policy meta tag to prevent possible XSS attacks.
    |-------------------------------------------------------------------------
    */
    'csp_enabled'    => env('APP_CSP_ENABLED', true),
    'csp_script_src' => env('APP_CSP_SCRIPT_SRC', ''),
```

If I set this to false and clean cache the script works but I'm asking how can I enable a single script without set to false this option?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#javascript-and-content-security-policy-csp

**Comment by PeopleInside** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#javascript-and-content-security-policy-csp

Thanks.

<script type="text/javascript" {!! \Helper::cspNonceAttr() !!}>
// Some JS code
</script>

I need replace \Helper::cspNonceAttr() with a random string?
I don't know how to create a script nonce.

I'm trying but without success. Could you write an example like how the example above should be customized?

Sorry for that request, thanks.

**Comment by PeopleInside** [comment]
Resolved.

```
<script type="text/javascript" {!! \Helper::cspNonceAttr() !!}>
// Some JS code
</script>

```

This is correct, the issue is that the script I put inside this call other external script that must be included in the .env file as for the guide.

Thank you, your link help me a lot!
