### ISSUE TITLE
multiple tickets created on internal communication

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3776]
It's offen necessary to send internal emails between users, because not everything is customer related. This causes the creation of at least two tickets, but also more if some other user is in CC.

How can this be prevented?

## Situation:

There are several mailboxes fetched by FreeScout. For example:
1. info@example.com
2. john.doe@example.com
3. lisa.miller@example.com
4. [...]

## What is happening?
John sends a message to Lisa about some internal topic. Ticket 1 is created with status pending at John's mailbox. One minute later FreeScout is retrieving the new email at Lisa's mailbox and creating an active Ticket 2.

This could be related to https://github.com/freescout-helpdesk/freescout/issues/3332 and https://github.com/freescout-helpdesk/freescout/issues/3400

PHP version: 8.2.15
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by nooblag** [comment]
Why do you have Freescout set up like this? I think it would make more sense to create multiple users accessing your `info` address and then just using the Notes feature inside Freescout to internally communicate with other users.

**Comment by mokkin** [comment]
Thanks for your hint @nooblag but John and Lisa are already users accessing the `info` address.
I basically understand what you mean to do that internally within this mailbox and notes feature, but nevertheless FreeScout forces me to select a customer - no matter if I create an email or phone conversation.
Is there something I am missing?

**Comment by freescout-helpdesk** [comment]
This looks like some weird configuration. Unfortunately we can't provide much help here.
