### ISSUE TITLE
original message can't be viewed when message was moved to another mailbox

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3777]
When a message was moved from one mailbox to another, the "show original" doesn't work as expected and is giving this [hint](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#why-does-show-original-window-shows-truncated-message-without-previous-history).
That might be true for some cases, but in this case the message isn't deleted on IMAP nor any DB issue occurs. It can just be retrieved from the original IMAP folder.

PHP version: 8.2.15
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no a solution for this for now as FreeScout does not save the history of conversation movements between mailboxes.
