### ISSUE TITLE
Is SAML SSO module is working with an IDP Shibboleth ?

### ISSUE THREAD

**Issue by dens38** [freescout-helpdesk/freescout#3778]
Hi,
I'm trying to use freescout with a shibboleth authentication.
I put all parameters required by SAML Module for freescout but my IDP always return me an error message : « Request is not supported »
Is there someone already use freescout behind a shibboleth authentication ?
If yes is there an extra configuration to make it work in this context ?
If no, is it possible to have this module compatible, as we have like 120000 users so not managable manually.
Best regards,

Here is all of my software versions
PHP version: 8.2.7
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by dens38** [comment]
Hi,
I arrived to make works the authentification in my context !
Neverthless, there is a strange behavior in the connexion unfolding : 
By default, if I let the defaut parameters the RelayState is set with the name of the webserver that is unknown by the IDP.
So I change the above line in Modules/Saml/Providers/SamlServiceProvider.php :
$sso_redirect_url = $auth->login(null, array(), false, false, true);
BY :
$sso_redirect_url = $auth->login("https://service.xxxxxx.fr/login", array(), false, false, true);
To force the url known by IDP. If I saw the requests done, there is still one request done on the name of webserver and not the website url...
![saml](https://github.com/freescout-helpdesk/freescout/assets/14909355/926c12c6-c04f-4d10-ba96-04da0a4a7ea8)

**Comment by freescout-helpdesk** [comment]
It looks like we can't provide much help here. Try to check with some Shibboleth professionals.
