### ISSUE TITLE
Push notifications stopped working

### ISSUE THREAD

**Issue by idia** [freescout-helpdesk/freescout#3779]
Since some time ago we noticed notifications stopped working.
Both mobile and browser.
Before when new conversations came, we received notifications on mobile and via browser… MacOS Chrome - badge on the top right corner..
It's hard to identify exact moment when it stopped working, but its around 2-3 weeks issue supposed.

With logging out and in again it seems we could make mobile work… But one day later it's not working anymore (no mobile notifs)/
On laptop we still miss every new conversation.

Mobile notifications module is purchased and active.
macOS Sonoma 14.3
Chrome browser latest

Could you suggest what could be wrong?
After updating Freescout on server and updating all modules, there seem to be following errors in Logs

<img width="1499" alt="Screenshot 2024-02-08 at 14 47 30" src="https://github.com/freescout-helpdesk/freescout/assets/2283990/088e4b84-6609-487d-abcf-070cf3911448">

`Error: include(/home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/../laravel/framework/src/Illuminate/Queue/Listener.php): failed to open stream: No such file or directory; File: /home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/ClassLoader.php (578)`

` include(/home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/../symfony/http-foundation/Cookie.php): failed to open stream: No such file or directory {"userId":1,"email":"mr.korsakov@gmail.com","exception":"[object] (ErrorException(code: 0): include(/home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/../symfony/http-foundation/Cookie.php): failed to open stream: No such file or directory at /home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/ClassLoader.php:578)
[stacktrace]
#0 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/ClassLoader.php(578): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/home/k...', '/home/k/korsako...', 578, Array)
#1 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/ClassLoader.php(578): include()
#2 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}('/home/k/korsako...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Symfony\\\\Compone...')
#4 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(159): spl_autoload_call('Symfony\\\\Compone...')
#5 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->addCookieToResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#6 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/k/korsakovru/scout-neptn-ru/public_html/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/k/korsakovru/scout-neptn-ru/public_html/overrides/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#25 /home/k/korsakovru/scout-neptn-ru/public_html/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#26 /home/k/korsakovru/scout-neptn-ru/public_html/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#27 /home/k/korsakovru/scout-neptn-ru/public_html/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#28 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#29 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/k/korsakovru/scout-neptn-ru/public_html/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/k/korsakovru/scout-neptn-ru/public_html/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 /home/k/korsakovru/scout-neptn-ru/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#54 /home/k/korsakovru/scout-neptn-ru/public_html/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#55 {main}
"}`

**Comment by freescout-helpdesk** [comment]
Try to re-update FreeScout using https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by idia** [comment]
@freescout-helpdesk I tried it several times...  /vendor folder deleted, Files overwritten on top of existing, cache cleared, DB migrate clicked (nothing to migrate).

Behavior is extremely strange... It worked over some time... Push notifs came from Chrome over MacOS desktop. But then it stopped working. Nothing changed over our side.

Is there a manual way to ignite a push from freescout just to understand whether they come through or not?

**Comment by idia** [comment]
Looking at /storage/logs/queue-jobs.log
this is what it looks like

`[2024-02-09 14:37:25] Processing: App\Notifications\WebsiteNotification
[2024-02-09 14:37:25] Processed:  App\Notifications\WebsiteNotification
[2024-02-09 14:37:25] Processing: App\Notifications\WebsiteNotification
[2024-02-09 14:37:25] Processed:  App\Notifications\WebsiteNotification
[2024-02-09 14:37:25] Processing: App\Notifications\BroadcastNotification
[2024-02-09 14:37:25] Processing: App\Events\RealtimeBroadcastNotificationCreated
[2024-02-09 14:37:25] Processed:  App\Events\RealtimeBroadcastNotificationCreated
[2024-02-09 14:37:25] Processed:  App\Notifications\BroadcastNotification
[2024-02-09 14:37:25] Processing: Modules\MobileNotifications\Jobs\SendPushNotificationToUsers
[2024-02-09 14:37:25] Processed:  Modules\MobileNotifications\Jobs\SendPushNotificationToUsers
[2024-02-09 14:49:25] Processing: App\Notifications\WebsiteNotification
[2024-02-09 14:49:25] Processed:  App\Notifications\WebsiteNotification
[2024-02-09 14:49:25] Processing: App\Notifications\WebsiteNotification
[2024-02-09 14:49:25] Processed:  App\Notifications\WebsiteNotification
[2024-02-09 14:49:25] Processing: App\Notifications\BroadcastNotification
[2024-02-09 14:49:25] Processing: App\Events\RealtimeBroadcastNotificationCreated
[2024-02-09 14:49:25] Processed:  App\Events\RealtimeBroadcastNotificationCreated
[2024-02-09 14:49:25] Processed:  App\Notifications\BroadcastNotification
[2024-02-09 14:49:25] Processing: Modules\MobileNotifications\Jobs\SendPushNotificationToUsers
[2024-02-09 14:49:26] Processed:  Modules\MobileNotifications\Jobs\SendPushNotificationToUsers`

**Comment by freescout-helpdesk** [comment]
It looks like we can't provide much help here.
Make sure push notifications are enabled in the browser.

**Comment by idia** [comment]
Is there a way to manually ignite push so that we can try different ways to determine where the problem is? 
How? @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
Trigger some event corresponding to user Notifications settings.
