### ISSUE TITLE
Email test works, but not the mail box

### ISSUE THREAD

**Issue by viniciusalvess** [freescout-helpdesk/freescout#378]
When I send the test email in the mailbox configuration, I get the email on the destination email.
But when I create a new email in the mailbox , I don't get the email at the destination email.

The log says:
Status: `Accepted for delivery`

crontab log:
```
Running scheduled command: '/usr/local/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' freescout:fetch-emails > '/shared/httpd/freescout/storage/logs/fetch-emails.log' 2>&1

```
Running on fedora 30 at digital ocean.
I created a support ticket to make sure they weren't blocking anything, 
their test was: telnet connects to gmail on ports 465 and 993.

Also I have the email account on thunderbird, and it sends and receives emails there.

Any Idea of what it could be ?

**Comment by freescout-helpdesk** [comment]
Anything in Manage --> Logs?

**Comment by viniciusalvess** [comment]
Manage Log: 
```
Dec 4, 06:19:20 | Email to customer | viniciusalvess@gmail.com | Accepted for delivery | #4 |   | viniciusalvess@gmail.com
-- | -- | -- | -- | -- | -- | --
Dec 4, 06:19:18 | Email to customer | viniciusalvess@gmail.com | Accepted for delivery | #3 |   | viniciusalvess@gmail.com
Dec 4, 06:19:17 | Email to customer | viniciusalvess@gmail.com | Accepted for delivery | #2 |   | viniciusalvess@gmail.com
Dec 4, 05:45:26 | Email to customer | viniciusalvess@gmail.com | Accepted for delivery | #1 |   | viniciusalvess@gmail.com
Dec 4, 05:42:37 | Test email | viniciusalvess@gmail.com | Accepted for delivery |   |   |  
```
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mcrypt
memcache
memcached
mongodb
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

***** fetch-emails.log
```
[2019-12-05 05:16:20] Fetching UNREAD emails for the last 3 days.
[2019-12-05 05:16:20] Mailbox: Test
[2019-12-05 05:16:20] Folder: INBOX
[2019-12-05 05:16:20] Fetched: 0
[2019-12-05 05:16:21] Fetching finished
```

***** queue-jobs.log
Is empty


I created a simple method in laravel's api.php and it works, the email gets delivered.
 
```
Route::post('/test',function(Request $request){
//    try {
        \Illuminate\Support\Facades\Mail::to([['name' => '', 'email' => 'viniciusalvess@gmail.com']])->send(new \App\Mail\Test());
        return 'horay';
//    } catch (\Exception $e) {
//        // We come here in case SMTP server unavailable for example
//        $status_message = $e->getMessage();
//    }
});
```
 
Is the SendReplyToCustomer is the main job resposible to send emails ?

**Comment by freescout-helpdesk** [comment]
> Is the SendReplyToCustomer is the main job resposible to send emails ?
Yes

Is your mailbox email same as your Gmail email?

**Comment by viniciusalvess** [comment]
This is the text dump of my mailbox: 

```
|1|Test|NULL|ana.flavia@elladesign.com.br|NULL|1|NULL|2|2|1|&lt;br&gt;&lt;span style=&quot;color:#808080;&quot;&gt;--&lt;br&gt;
{%mailbox.name%}&lt;/span&gt;|3|mail.elladesign.com.br|ana.flavia@elladesign.com.br|ehtzI,iC?LnA|465|2|mail.elladesign.com.br|993|ana.flavia@elladesign.com.br|eyJpdiI6IlJybEtFOWxcL044UEFXT1J2ZEkxWHlRPT0iLCJ2YWx1ZSI6IlVySWVtQWt2K3RKdnFmM0xtU2dHOUluWHg4ZlJVZTIxVjJvMHk0RWEwaVU9IiwibWFjIjoiMTM5MDZmZThiNzI5MjA5NTEwMjRkNTEzZDA1NmRhOTAxYTcwNjgzZDEyYTQxZjVlOTYyNGI4YTNmODQ5NWNiMyJ9|1|2|0|NULL|NULL|0|0|1|NULL|2019-12-04 05:42:00|2019-12-04 05:44:09|0|[]|NULL
```

I just tested , if I change the code at ConverversationController.ajax:
in the case 'send_reply' block.

```
if ($is_create) {
                       //the line bellow works , and the email gets sent.
                        \Illuminate\Support\Facades\Mail::to([['name' => '', 'email' => 'viniciusalvess@gmail.com']])->send(new \App\Mail\Test());
                        
                        // New conversation.
                        event(new UserCreatedConversation($conversation, $thread));
                        \Eventy::action('conversation.created_by_user_can_undo', $conversation, $thread);
                        // After Conversation::UNDO_TIMOUT period trigger final event.
                        \Helper::backgroundAction('conversation.created_by_user', [$conversation, $thread], now()->addSeconds(Conversation::UNDO_TIMOUT));
                    } elseif ($is_forward) {
```
I feel like the SendReplyToCustomer handle is neve being called.

Any Idea what it could be ?

**Comment by freescout-helpdesk** [comment]
Something is wrong with the background jobs.

Do you see any jobs at the bottom of the Manage --> System?

**Comment by viniciusalvess** [comment]
![freescout_debug](https://user-images.githubusercontent.com/17517866/70301851-5a9ad180-17b0-11ea-9ae1-b4aeeb286b48.png)

This is a print of my crontab , and the Manage ->> System.
If I tail -f the file I write the date to the file, e executes, every minute.

I fell like the crond process is working ok, but for some reason it doesn't call the schedule:run.
I have tried different ways to make it call, but it doesn't like it for some reason.

**Comment by freescout-helpdesk** [comment]
You may need to debug https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php
