### ISSUE TITLE
Query on Attachment URLs via API 

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3783]
Hello team,
I see the attachment url we get from api is a static one and has no expiry. Can we set an expiry on top of this. Because we deliver this to our frontend and it will be a security concern for us.  If there is already expiry, please let me know how to make use of it 

Also I am thinking if there is a module where I can use s3 as our object destination instead of local file system. Is that possible

**Comment by freescout-helpdesk** [comment]
> I see the attachment url we get from api is a static one and has no expiry. Can we set an expiry on top of this.

Unfortunately it's not possible and we don't have plans to implement it. Maybe someone can implement as a custom module.

> Also I am thinking if there is a module where I can use s3 as our object destination instead of local file system. Is that possible

https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-can-attachments-be-stored-in-amazon-aws-s3

**Comment by sarsony1** [comment]
Thanks a lot. I was able to make some changes using flysystem API and make it work
