### ISSUE TITLE
UI display issues in light mode

### ISSUE THREAD

**Issue by ezy3** [freescout-helpdesk/freescout#3785]
We are currently experiencing an issue where the UI is displaying incorrectly. Its working fine on dark mode but light mode doesn't work.  

![Free Scout Issue](https://github.com/freescout-helpdesk/freescout/assets/87155109/42f0d13a-c20b-43d8-b747-3dee166275cd)

PHP version: 8.1.27
FreeScout version: 1.8.120 
Database: MySQL
Are you using CloudFlare:  No

Following modules installed and active: 
Auto Login
Version: 1.0.2

Block External Images
Version: 1.0.7 

Custom Folders
Version: 1.0.19

Custom Mailbox Signatures
Version: 1.0.14

Customization & Rebranding
Version: 1.0.18

Dark Mode
Version: 1.0.14

Embed Images
Version: 1.0.2

Extended Attachments
Version: 1.0.19

Move or Remove IMAP MessageActive
Version: 1.0.3

Inbox
Version: 1.0.3

Kanban
Version: 1.0.20

Mailbox Icons
Version: 1.0.4

OAuth & Social Login
Version: 1.0.16

Reports
Version: 1.0.37

Satisfaction Ratings
Version: 1.0.22

Saved Replies
Version: 1.0.37

Send & Close
Version: 1.0.8

Sent Folder
Version: 1.0.13

Snooze
Version: 1.0.16

Tags
Version: 1.0.36

Teams
Version: 1.0.17

Time Tracking
Version: 1.0.17

User Fields
Version: 1.0.4

**Comment by freescout-helpdesk** [comment]
Does it get back to normal when Dark Mode module is disabled?
Do you have some custom CSS adjustments on your FreeScout?

**Comment by ezy3** [comment]
No it does not. Don't have any custom CSS. This must have happened after a recent update as its a new issue and we haven't added any new modules or anything in the last year. Its been perfect.

**Comment by ezy3** [comment]
![image](https://github.com/freescout-helpdesk/freescout/assets/87155109/7f73df09-2e33-44a2-8942-0e0a932f1dcd)
![image](https://github.com/freescout-helpdesk/freescout/assets/87155109/c84210ba-61ba-40ff-a1ec-0edd4366e1fa)
Had a look at the Elements via inspector and seems like the footer in dark mode the css is set to display: none but in light mode it has other styling. 

The only custom css i have is this below but i removed it and still the same issue: 

.navbar-default .navbar-brand:hover {
     background-color: #1c7589;
}

**Comment by freescout-helpdesk** [comment]
Try to re-update your FreeScout using manual updating method.

**Comment by ezy3** [comment]
Hi, I have worked around this issue by simply adding the following CSS: 

.footer {
    display: none;
}

We don't really need the footer so that's ok for now. I'll see with the next auto update if it fixes the issue.

**Comment by ezy3** [comment]
Managed to fix the issue. The custom signature was the problem. I cut the signature. Saved it. Then pasted it back in and saved it. All the CSS seems normal now. Even the footer works.
