### ISSUE TITLE
Additional Thread Created for CC Recipient

### ISSUE THREAD

**Issue by rosequaartz** [freescout-helpdesk/freescout#3789]
# Summary

I'm seeking clarification on whether our current issue constitutes a bug or is an expected behaviour. The scenario entails emails sent from a Mail Client to Freescout Inbox "A" with a CC to Freescout Inbox "B." Following replies from Freescout Inbox "A," also CC'ing Freescout Inbox "B," an extra thread is generated in Inbox "B."

## System Specs

- PHP version: 8.2.14
- FreeScout version: 1.8.115
- Database: MySQL
- Are you using CloudFlare: No

# Steps to Replicate

1. Email sent from Mail Client to Freescout Inbox A with CC to Freescout Inbox B,
2. Reply sent from Freescout Inbox A to Mail Client with CC to Freescout Inbox B,
4. Two threads are now created in Freescout Inbox B.

# Current Behaviour

Currently, emails sent from a Mail Client to a Freescout Inbox "A" with a CC to an additional Freescout Inbox "B" will create one thread in the CC inbox "B". When the thread is replied to by Freescout Inbox "A" and CC Freescout Inbox "B", an additional thread is then created in Freescout Inbox "B".

# Expected Behaviour

The email will remain within a single thread in Freescout Inbox "B," as it constitutes part of a unified thread involving the same three inboxes.

**Comment by freescout-helpdesk** [comment]
It is an expected behaviour.
