### ISSUE TITLE
Reply creates multiple threads in email clients (no grouping)

### ISSUE THREAD

**Issue by lieblinger** [freescout-helpdesk/freescout#3790]
Every reply send from a FreeScout thread generates a new mail in Outlook client without grouping.

**Freescout:**
![freescout1](https://github.com/freescout-helpdesk/freescout/assets/10740088/c10e1d8d-07dc-48a0-b614-3161ead4c153)

**Outlook:**
![outlook](https://github.com/freescout-helpdesk/freescout/assets/10740088/6508ec26-0f91-4b16-a57e-c6c9ffba9e78)

Is this desired? Or should it group mails like any other mail program?

**Outlook Grouping Example:**
![grouping](https://github.com/freescout-helpdesk/freescout/assets/10740088/25bccfd0-d6f5-4ac0-b91f-fed84416828d)

**Comment by freescout-helpdesk** [comment]
It works find in Gmail.
How do you access the Outlook?

**Comment by lieblinger** [comment]
Online via chrome (OWA). But I think it's not only OWA related we've a couple of customers which are using different mail clients and they're having the same issue.

**Comment by freescout-helpdesk** [comment]
We've checked on https://outlook.live.com and grouping works fine. Make sure to update FreeScout to the latest version.

**Comment by lieblinger** [comment]
Thanks for your update and checking! We're on latest version and using https://outlook.office.com/. 
Still the same issue... Every mail send from freescout (same ticket) ends into a new mail on outlook.

**Comment by freescout-helpdesk** [comment]
Try to send test email to support@freescout.net and check grouping.

**Comment by lieblinger** [comment]
Dear Freescout Support Team,

I would like to provide an update on the issue we reported a few months ago, which is still persisting. The problem occurs when we send multiple replies from the same ticket, causing the email thread to become disjointed for the recipient.

Recently, we migrated our Freescout installation from a virtual machine to Docker. After the migration, everything functioned correctly until we reactivated all the modules we use. Once the modules were back in place, the issue reappeared. I attempted to delete the modules again, but the problem persisted even after deletion.

Here is the complete list of modules we are currently using:

- API and Webhooks
- Block External Images
- Checklists
- Customers Management (CRM)
- Custom Fields
- Extended Attachments
- Extended Editor
- FollowersAktiv
- Global Mailbox
- LDAP Integration
- Mentions
- Mobile Notifications
- Out of Office
- Saved Replies
- Snooze
- Tags

Please note that all modules and Freescout itself are installed and updated to the latest versions.

We would greatly appreciate your assistance in resolving this issue, as our customers quickly lose track of conversations when emails are not properly threaded.
