### ISSUE TITLE
Attachment files not downloading (Sees different folder!)

### ISSUE THREAD

**Issue by pnkr** [freescout-helpdesk/freescout#3792]
PHP version: 8.2.14
FreeScout version: 1.8.120    
Database: MySQL
Are you using CloudFlare: (Yes but not firewall)

When i create a ticket with an attachment, the attachments is being send.
When as an agent trying to view or downlod the attachment. For example an image, I cant download it.

Searching the DOM in browser console I see that it searches at: /storage/attachment/
But such a folder does not exist and the files are uploaded to /storage/app/attachment/
So why this is happening?

**Comment by freescout-helpdesk** [comment]
Maybe this is the reason:

>     # Uncomment this location if you want to improve attachments downloading speed.
>     # Also make sure to set APP_DOWNLOAD_ATTACHMENTS_VIA=nginx in the .env file.
>     #location ^~ /storage/app/attachment/ {
>     #    internal;
>     #    alias /var/www/html/storage/app/attachment/;
>     #}

https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#61-nginx

**Comment by pnkr** [comment]
This is for nginx configuration. I dont use nginx.

**Comment by pnkr** [comment]
I dont have an NGINX server. Im on Apache.
