### ISSUE TITLE
Run module-install against all modules without interaction

### ISSUE THREAD

**Issue by jthomperoo** [freescout-helpdesk/freescout#3793]
PHP version: 8.0.30
FreeScout version: 1.8.120
Database: PostgreSQL
Are you using CloudFlare: Yes

Thanks for the great project, really useful, everything is very easy to use, and the module system is great.

In our setup we are replacing the server that Freescout runs on each time we update, we do this as we use Packer to build an image that we then apply configuration to. This means that we are frequently migrating our Freescout instance between servers (all of the data is persisted through an external database and persistent volumes which are mounted in).

This mostly works great, the one issue we have is that whenever this happens and Freescout is started the modules are not installed, so the CSS and JS for these modules is not loaded.

This means that our end user portal does not have any styling after one of these migrations.

This is fixed by manually by loading the Manage > System page, which then installs all of the modules, or we can interactively run this command:

```
php artisan freescout:module-install
```

It would be great if there was a way we could install these modules through our startup scripts to make sure they were already set up when the application starts, without us having to intervene at all.

I have tried running the command above with the `-n` flag for no interaction:

```
php artisan freescout:module-install -n
```

However this skips installing any modules, and just clears the cache.

If we could run this command non interactively and choose the positive option to install the module instead of skipping this would be really useful for us.

Thanks again for the great project!

**Comment by freescout-helpdesk** [comment]
Check https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#92-cron-job-for-automatic-updates
