### ISSUE TITLE
Blocked autofocusing on a form control in a cross-origin subframe on Contact-Widget

### ISSUE THREAD

**Issue by abombelli** [freescout-helpdesk/freescout#3794]
Hello

We try to embed to contact widget in an iFrame.
Unfortunately we get an "Blocked autofocusing on a form control in a cross-origin subframe" error on each page load.
Is there any way to disable autofocusing or any other way to fix this issue?

Thanks,
Aldo 

PHP version: 8.1.27
FreeScout version: 1.8.120 
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3023#issuecomment-1552491537

**Comment by freescout-helpdesk** [comment]
Also try https://stackoverflow.com/a/60957499

**Comment by abombelli** [comment]
We ended up removing "autofocus" in submit_form.blade.php from the name and mail fields, as it still invokes a JS error in Chrome. It does not allow autofocus if the site where the widget is added has a different domain than the one where Freescout is installed. This should be removed.
