### ISSUE TITLE
Pictures are not showing up in the body on email clients

### ISSUE THREAD

**Issue by Fireful0** [freescout-helpdesk/freescout#3796]
Hello!

We are having an issue where we can drag a photo into the body of a message, but our client's are unable to see the photo.

Below are some photos showcasing what I am talking about.

This is what it shows on our end:

![Sent](https://github.com/freescout-helpdesk/freescout/assets/26516812/86baf38f-366f-4e3a-a370-df54dc843f52)

But this is what it shows on our client's end:

![Screenshot_2024-02-16-08-54-35-24_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/freescout-helpdesk/freescout/assets/26516812/57c8356e-ac15-444a-a942-68b2c68d547b)

Inserting the image as an attachment works, but we need to be able to put photos in the body of the message.
Any recommendations on how to fix this, or is this planned to be fixed in the future?

Thanks!

PHP version: PHP 8.2.13
FreeScout version: 1.8.120
Database: MySQL

**Comment by freescout-helpdesk** [comment]
Make sure that your FreeScout is available from the Internet and not protected using Basic HTTP Authentication.
