### ISSUE TITLE
multiple tickets created on CC messages

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3797]
Sometimes customers are sending emails to several mailboxes such as
1. info@example.com
2. john.doe@example.com

Both are served by FreeScout as separate mailboxes. In this case two (or more) tickets are created, one in each mailboxes, but for the same customer.

Can this be prevented to avoid double work and doubled answers?

**Comment by freescout-helpdesk** [comment]
Unfortunately not.
