### ISSUE TITLE
Image size is not saved when displayed in Freescout

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3798]
**Steps to reproduce:**
1. Click Reply and paste a large picture into the text of the conversation.
2. Click on it and select a size of 25%.
3. Click Send

**Result:**
The picture is displayed at full size.

**Expected result:**
The picture has been reduced to 25%.

**Screenshots:**
![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/d7b8e259-755a-41bd-8226-edbbab8e2133)

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/72584487-07d4-4c87-8a94-377db7e17910)

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/fa017c24-9c13-45a1-9e31-81621d59fea1)

PHP version: 8.2.7
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
