### ISSUE TITLE
HTML in email signatures is not rendering

### ISSUE THREAD

**Issue by gabllux** [freescout-helpdesk/freescout#3799]
PHP version: PHP 8.2.7
FreeScout version: 1.8.120
Database: MySQL (10.11.6-MariaDB-0+deb12u1)
Are you using CloudFlare: No

Hello, I noticed that sometimes only images and not the text in the signature of incoming emails from the customers are rendered in a conversation. However, if I click on "show original" or if I try to open the email in other email clients the whole signature is shown correctly.
I'm pasting an example of a redacted HTML signature containing the text that is not rendered so you can reproduce the issue. I spoke with some customers and the HTML should be generated by the popular enterprise software Exclaimer, so I think it shouldn't be sanitized or purified by Freescout. I tried it on http://htmlpurifier.org/demo.php and the text is shown correctly but I don't know exactly what are the settings used for Freescout.

```
<div dir="ltr" style="mso-line-height-rule:exactly;-webkit-text-size-adjust:100%;font-size:1px;direction:ltr;">
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;font-size:1px;">
<tbody>
<tr style="font-size:0;">
<td align="left" style="vertical-align:top;">
<table cellpadding="0" cellspacing="0" border="0" style="font-size:0;">
<tbody>
<tr style="font-size:0;">
<td align="left" style="padding:20px 0 0;vertical-align:top;">
<table cellpadding="0" cellspacing="0" border="0" style="font-size:0;color:#000001;font-style:italic;font-weight:700;white-space:nowrap;">
<tbody>
<tr style="font-size:17px;">
<td align="left" style="vertical-align:top;font-family:Arial;">John<span style="font-family:remialcxesans;font-size:1px;color:#FFFFFF;line-height:1px;">​<span style="font-family:'template-W6ukeCZCEe6puwANOry-ig';">​</span><span style="font-family:'zone-1';">​</span><span style="font-family:'zones-AQ';">​</span></span></td>
<td align="left" style="vertical-align:middle;font-size:0;">
<table cellpadding="0" cellspacing="0" border="0" style="font-size:0;color:#000001;font-style:italic;font-weight:700;white-space:nowrap;">
<tbody>
<tr style="font-size:17px;">
<td align="left" style="padding:0 0 0 4px;vertical-align:middle;font-family:Arial;">
Doe<br>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>

</td>
</tr>
</tbody>
</table>
</div>
```

Thank you in advance for your support.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed

**Comment by gabllux** [comment]
Ok, from your suggestion I understand I should debug /config/purifier.php by myself.
Thank you

**Comment by gabllux** [comment]
Is there a reason why <tr> elements aren't allowed to have a style attribute? Simply changing from `tr[bgcolor]` to `tr[style|bgcolor]` seems to fix my issue. I'm just asking because I see that <td> and <table> elements are allowed to to have a style, and I don't know if I can safely add this to my /config/purifier.php or not.

**Comment by freescout-helpdesk** [comment]
It is safe to add it.
