### ISSUE TITLE
Password shouldn't be required for send_invite mode

### ISSUE THREAD

**Issue by dryabov** [freescout-helpdesk/freescout#38]
https://github.com/freescout-helpdesk/freescout/blob/020c9e1b8f37da86879e18f138024e82803612b3/resources/views/users/create.blade.php#L73

I've wrapped `required autofocus` into `@if (empty(old('send_invite')) && !empty(old('role'))) required autofocus @endif`, but most likely it's better to extract this condition into a variable.

 Browser (Chrome) doesn't allow to submit form with empty `required` field.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/4f1e74a821a81769fd64c67794a51ea63a58d60b
