### ISSUE TITLE
Reporting on usrs/agents performance

### ISSUE THREAD

**Issue by diondkb** [freescout-helpdesk/freescout#380]
Hi,

Are there any reporting facilities in Freescout, specifically user or agent performance?

Regards,
Dion

**Comment by freescout-helpdesk** [comment]
It will be implemented as a module.

Which metrics do you need?

**Comment by diondkb** [comment]
I need to know how much work may users/agents have done in a given time. I am paying them by the hour. How many issues are still unresolved and for how long.

Thanks

**Comment by vlance11** [comment]
Did this ever get developed?
