### ISSUE TITLE
The wrong user who is viewing the conversation is displayed (yellow triangle)

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3801]
**Steps to reproduce:**
1. Open one conversation from user1, user2 and user3.
2. Wait until all three users have 2 pictures each of users who are viewing the conversation.
3. At user1, navigate to the folder where this conversation is located.
4. Hover your mouse over the yellow triangle in the upper left corner of the conversation.

**Result:**
Shows user1.
![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/932baf21-73b9-4953-b4c5-3fb201266425)

**Expected result:**
Shows the other two users.

PHP version: 8.2.7
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by il2020** [comment]
Updated the description.

**Comment by freescout-helpdesk** [comment]
We still can't reproduce it on our end. If someone will be able to reproduce - try to fix and send pull request.
