### ISSUE TITLE
FreeScout Upgrade Recommendations

### ISSUE THREAD

**Issue by dangrayza** [freescout-helpdesk/freescout#3805]
Could you please advise / recommend how we can utilize the latest version and its features. Should we upgrade incrementally or can we just go to the latest version? We attempted to do incremental upgrades but failed at one of the following version. Please also suggest a recommended upgrade path given our versions of PHP/MySQL and FreeScout and if any versions of PHP/MySQL might need to be upgraded to get to the latest version. Thanks

PHP version: 7.4
FreeScout version: 1.8.26
Database: MySQL 8.0
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
All information is here: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout
