### ISSUE TITLE
How send Mail to Postbox if contact widget is submitted

### ISSUE THREAD

**Issue by abombelli** [freescout-helpdesk/freescout#3806]
Hello

How can we send a mail to the postbox address if the contact form widget is submitted?
We would like to inform the agent about new requests.

Thanks
Aldo

PHP version: 8.2
FreeScout version: 1.8.120 
Database: MySQL 
Are you using CloudFlare:  No

**Comment by freescout-helpdesk** [comment]
Create a custom module (https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development) or try to use Webhooks (https://freescout.net/module/api-webhooks/).

**Comment by abombelli** [comment]
I ended up buying the workflow module.
Would be great if there is also a specific trigger for when a ticket is created in the widget form.
