### ISSUE TITLE
MySQL configuration error during installation

### ISSUE THREAD

**Issue by MaxSeck** [freescout-helpdesk/freescout#3807]
PHP version: 8.1.2-1ubuntu2.14
FreeScout version: 1.8.120
Database: MySQL 
Using CloudFlare:  No
 
Currently I'm running into following error messages during the installation of freescout:

**Configuring MySQL...
ERROR 1269 (HY000) at line 1: Can't revoke all privileges for one or more of the requested users
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY "NGIzNDk5N"' at line 1**

Besides this issue the whole process of the installation works fine. I was able to able to open the free scout helpdesk in my browser, reaching it via my domain. I created also an admin user to log in but when it comes to the login screen, freescout tells me that no such user is existing. I think this error is linked to the database errors which appear during the installation. 

Maybe some of you ran already in this error and know what to do.

Thank you.

**Comment by freescout-helpdesk** [comment]
There is a special comment coming after these errors.

**Comment by MaxSeck** [comment]
You mean this one:

"You may see a MySQL privileges error above. Don't worry - the script executes two different commands for different DB versions and one of them always fails - just continue the installation"

**Comment by freescout-helpdesk** [comment]
Yes.
