### ISSUE TITLE
Webhooks not being sent

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3809]
1. My webhooks setup is not working and I want to debug it. I didnt get what you meant by "webhooks page" in other issue. Could you be more specific. Because in logs page, I only seee webserver and laravel logs. 
2. Also is running a cron job in the setup madatory for webhooks to work. I've skipped that part because at the moment we are only using the api and dont need to fetch from external mail

_Originally posted by @sarsony1 in https://github.com/freescout-helpdesk/freescout/issues/3754#issuecomment-1951734182_

**Comment by freescout-helpdesk** [comment]
> 1. I didnt get what you meant by "webhooks page" in other issue.

If some error happens during webhook execution you will see it on Manage > API & Webhook page next to your webhook.

> 3. is running a cron job in the setup madatory for webhooks to work

Yes.

**Comment by sarsony1** [comment]
Hii, I dont see anything at Manage > API & Webhook when I expect a webhook. I am using website.site for debug and setup  webhooks on convo.assigned. Also I've setup the cron job as per the installation doc. Here are my background jobs 
```
ubuntu@iXXXX:/var/www/vhosts/current$ ps aux | grep queue
www-data   48379  0.0  0.0   2892  1664 ?        S    08:56   0:00 sh -c '/usr/bin/php8.3' 'artisan' queue:work --queue='emails,default,27466cab9c54bd7f7e0e907183a2bfd3' --sleep=5 --tries=1 --timeout=1800 > '/var/www/vhosts/current/storage/logs/queue-jobs.log' 2>&1
www-data   48380  0.8  1.2 141528 50512 ?        S    08:56   0:00 /usr/bin/php8.3 artisan queue:work --queue=emails,default,27466cab9c54bd7f7e0e907183a2bfd3 --sleep=5 --tries=1 --timeout=1800
ubuntu     48428  0.0  0.0   7008  2304 pts/0    S+   08:56   0:00 grep --color=auto queue
```

**Comment by sarsony1** [comment]
@freescout-helpdesk We are blocked on this. Could you plz help with this

**Comment by freescout-helpdesk** [comment]
Someone will need to debug it on your server.
