### ISSUE TITLE
Fetching emails with multiple HTML parts

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#381]
Steps to reproduce:

1. compose an email with Apple Mail iPhone client or Apple Mail MacOS client
2. enter some text
3. add an attachment
4. after attachment use a signature or other text

Result:

1. mail is received (in Freescout)
2. text above the attachment in the original email is gone
3. attachment is present
4. text after attachment is visible

This is a rather serious issue as there are millions of Apple Mail users and as a receiver you don't know what you're missing.

**Comment by freescout-helpdesk** [comment]
Which FreeScout version are you using?

**Comment by imc67** [comment]
It was with 1.3.12 and also now on 1.3.13

**Comment by freescout-helpdesk** [comment]
Can you send one such email to support@freescout.net

**Comment by imc67** [comment]
Just sent you an email and as a second a pdf of how it was sent and a screenshot how it was received in Freescout.

Keep up the good work on Freescout as it is absolutely great!!

**Comment by imc67** [comment]
I just installed update 1.3.14 and send the test email again, this time it's fully received!!

Thank you very much for your quick responses and very quick solution!
