### ISSUE TITLE
Conversation text formatting for API

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3810]
Hello team,
I am using API for creating a thread for a conversation. I am trying to send an JSON with indentation ( with chars like \t etc). But those are getting trimmed when I look at it from freescout UI. Could you let me know if this is a bug or expectation. 
We needed to show indented JSON on the freescout UI conversation text. 
2. Is sending html snippet supported. Please share me a sample payload if possible 

Thanks a lot of the quick support

**Comment by freescout-helpdesk** [comment]
> Is sending html snippet supported

Thread body should be sent as HTML.
