### ISSUE TITLE
I am unable to update avatar (profile photo) as it appears broken after uploading

### ISSUE THREAD

**Issue by murshed** [freescout-helpdesk/freescout#3814]
Hello,

I am Fahim from the Brainstorm Force support team. We are utilizing FreeScout for our operations.

I am encountering an issue with FreeScout. Despite my attempts, I am unable to update my avatar as it seems to be broken after uploading. I have made several efforts, including uploading a 50x50 px photo in PNG and JPEG/JPG file formats, but unfortunately, I have not had any success.

Refer to this [screencast](https://d.pr/v/ep3Lz2).

I request that you investigate this matter and provide a resolution. 

Thank you.

**Comment by freescout-helpdesk** [comment]
Someone may need to investigate it on your server.

**Comment by sumodhar** [comment]
@freescout-helpdesk Could you please clarify what specifically needs investigation on our server? Are you requesting access as a user on our server?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
