### ISSUE TITLE
Attachments of deleted threads and threads in spam should not be downloadable publicly

### ISSUE THREAD

**Issue by rlanyi** [freescout-helpdesk/freescout#3815]
## Environment

```
PHP version: PHP 8.2.15 (running docker image tiredofit/freescout:1.17.54)
FreeScout version: 1.8.120
Database: MariaDB
Are you using CloudFlare: No
```

## Problem

From time to time, mailboxes get spam messages that are either marked as spam manually or automatically by the spam module. The issue is that somehow some spammers leart that our mailbox email address is handled in Freescout, and they started to send malicious attachments with their messages. We didn't care much about this until we learnt that even if you mark these messages as spam or delete them, the malicious attachments are available online. We learnt the hard way that spammers are using the publicly available links to spread those malicious files to many email addresses, those recipients try to download them, Gmail/Chrome stops the malicious download. The result: our domain got flagged in Gmail, our support team gets all of the incoming tickets in spam or see the message that "this message seems dangerous". Also, most of the replies we send to customers also goes to spam the same way.

We also learnt that the only way to avoid this is to delete the messages AND then select them and click the Delete Forever button. Once we do this, attachments are not downloadable anymore.

For now, we've removed the attachment files from the filesystem manually, and requested a review for our domain via Google Search Console. We hope that it will remove the flag and our emails will be delivered again.

## Suggestion

Attachments of emails marked as spam (either manually or by the spam module) or deleted should not be downloadable. Maybe the files could be kept in the filesystem, so in case someone restores the thread, they would become downloadable again.

## Attachments

Support email in Gmail:

<img width="1097" alt="image (31)" src="https://github.com/freescout-helpdesk/freescout/assets/13754361/c2e54bec-c25b-4424-8e92-a24fa8806626">

Dangerous URLs in Google Search Console for our domain:

![searchconsole](https://github.com/freescout-helpdesk/freescout/assets/13754361/0b73f683-75ef-423c-ac63-6ac01dd426f8)

**Comment by freescout-helpdesk** [comment]
> We also learnt that the only way to avoid this is to delete the messages AND then select them and click the Delete Forever button.

Yes, this is how it works.

Unfortunately there is no plans to change this. You can do it via a custom module.

**Comment by rlanyi** [comment]
Thanks for the fast reply, it's appreciated.

I'd strongly suggest to reconsider the current behaviour, at least for threads that are marked as Spam. The way it works can have a huge negative effect on the domain reputation and I see no cause why attachments of spam messages should be downloadable.

**Comment by rlanyi** [comment]
@freescout-helpdesk you closed this as completed on 24 Feb, but I can't see any related changes in the release notes. Is it not released yet or (per your previous message) you actually don't plan to fix this issue, at least for the messages marked as Spam?

Thank you!

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3815#issuecomment-1959149642

**Comment by rlanyi** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3815#issuecomment-1959168997 -> please also see the likes on my comment

Instead of "completed" you should have closed this as "wontfix". Thanks anyway!
