### ISSUE TITLE
Unable to delete conversation from trash for unknown reason

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3816]
When the Empty Trash button is pressed or when the conversation is selected with a flag and the delete button is pressed, a flag and the delete button is clicked, an error message is displayed:

> Error occurred. Please check your internet connection and try again.

In this case, you can see such a request and its response in the browser:

```json
{
	"action": "bulk_delete_conversation",
	"conversation_id[]": "30672"
}
```
```json
{
	"message": "Server Error"
}
```

```text
POST https://example.com/conversation/ajax
Status 500 Internal Server Error
Version HTTP/1.1
Transferred 1.10 kB (33 B size)
Referrer Policystrict-origin-when-cross-origin
Request Priority Highest
DNS Resolution System
```

All other conversations were able to be deleted, the problem occurred on one. How to understand what is wrong?

PHP version: 8.2.7
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Manage > Logs > App Logs

**Comment by il2020** [comment]
It's like this:

```text
Corrupted path detected: attachment/6/6/1/Цифровая-валюта-в-расчетах-сентябрь-2023зF` {"userId":1,"email":"user@example.com","exception":"[object] (League\\Flysystem\\CorruptedPathDetected(code: 0): Corrupted path detected: attachment/6/6/1/Цифровая-валюта-в-расчетах-сентябрь-2023\u0002з\u0006F` at /var/www/html/vendor/league/flysystem/src/CorruptedPathDetected.php:15) 
```

**Comment by freescout-helpdesk** [comment]
Can you give source code of the email to which this file has been attached?

**Comment by il2020** [comment]
No, I deleted it manually already.

**Comment by freescout-helpdesk** [comment]
Without having the original file name from the email we can't fix the issue. So we'll close it for now.

**Comment by Querens** [comment]
I've encountered the same issue but I have been able to track down the problematic email. Here's it's source code with my ip address changed to 'my_ip_address'
[freescout_bug.txt](https://github.com/user-attachments/files/17412390/freescout_bug.txt)
