### ISSUE TITLE
search on custom fields results in error 403

### ISSUE THREAD

**Issue by modist** [freescout-helpdesk/freescout#3817]
PHP version: PHP 7.4.33
FreeScout version: 1.8.120
Database: Mysql (8.0.36-cll-lve)
Are you using CloudFlare: Yes (not cached)

how to reproduce - example:

1. create a custom field (named Urgency in this example - a dropdown)
2. use search 
3. select the custom field on the left
4. perform search - > /search?f%5B%23Urgency%5D=1&q=

this results in a 304 page - nothing in the logd

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. We need some logs or error message to be able to fix it.
