### ISSUE TITLE
Install broken after the latest update freescout 1.8.121

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3818]
PHP version: 8.3
FreeScout version: 1.8.121
Database: MySQL 
Are you using CloudFlare: Yes / No

Hi, after the update to the new latest version UI is completely broken on front end and back end.
The developer console show the error:
`Uncaught ReferenceError: initTagsBulk is not defined`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

Clear cache from the UI seems doesn't help.
I just updated via UI interface and install get broken. 

I think I need restore a backup.

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/80436113-da8e-431a-8d8f-af0f80c86a2a)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by PeopleInside** [comment]
I tried all the procedure, also the manual one. Nothing work.

**Comment by PeopleInside** [comment]
I found what is causing the issue.
The issue is caused by the file minify.config.php
where in the new version you removed the APP_URL.

If I replace the new file with my backup file, the FreeScout return to work.

Now can tell me it's this update wrong or I need change something in my install to fit the new changes made by you?

My instance is installed at https://helpdesk.peopleinside.it/support/help/2135130453

The main .htaccess https://github.com/freescout-helpdesk/freescout/blob/dist/.htaccess 
redirect to the public folder but as you removed the the APP_URL from minify.config.php seems Freescout is no more able to load correctly CSS and JS
