### ISSUE TITLE
When using the Spam filter module, are we expected to never delete the spam emails?

### ISSUE THREAD

**Issue by sgmcmiller** [freescout-helpdesk/freescout#3819]
PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version:  1.8.121    
Database: MySQL
Are you using CloudFlare: No

When using the Spam filter module, are we expected to never delete the spam emails? I noticed that most of our spam was getting through the filter when we cleared the spam folder on a regular basis. We have not cleared the folder in some time now and have amassed over 400 spam emails. During this time, the filter has been working. We would prefer to be able to clear the folder without losing function of the filter.

"When you move a conversation out of the spam folder, customer will be removed from the blacklist." taken from the spam filter module page.

This is about all I could find in reference to my issue.

**Comment by freescout-helpdesk** [comment]
Spam folder can be cleared. Spam filter uses it's own learning memory.
