### ISSUE TITLE
After updating Freescout to 1.3.13 crash on Translate page

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#382]
Steps to reproduce:

1. Update to 1.3.13 (after update there was an unknown error)
2. Go to Manage > Translate
3. Choose a Group
4. Error page: Whoops, looks like something went wrong.

Detailed logs per item:

1. (not 100% sure this error was related to the update)
Call to undefined method App\Misc\Helper::getAllLocales() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Misc\\Helper::getAllLocales() at /home/abcd/domains/abcd.tv/public_html/redactie/app/Console/Commands/GenerateVars.php:46)

4. 
Undefined variable: selected_locale (View: /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/index.blade.php) {"userId":2,"email":"abcd@abcd.tv","exception":"[object] (ErrorException(code: 0): Undefined variable: selected_locale (View: /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/index.blade.php) at /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/content.php:86, ErrorException(code: 0): Undefined variable: selected_locale at /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/content.php:86)

**Comment by freescout-helpdesk** [comment]
> after update there was an unknown error

It means updating did not finish properly. Try to reupdate: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by imc67** [comment]
Ok, I did Update Method 4, it gave an error and advised to:
1. download FreeScout and upload + extract via ftp
2. then migrate DB.

Did these steps, result of step 2. was something like "there is nothing to migrate".

However, the issue with the Translate page is still there

**Comment by freescout-helpdesk** [comment]
Try to clear the cache in System --> Tools, open Tranlate page and check the latest error in the App Logs.

**Comment by imc67** [comment]
Hi, followed your steps in a new incognito browser tab (just to be sure of no local cache) and this is the error log:

Undefined variable: selected_locale (View: /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/index.blade.php) {"userId":1,"email":"abcd@abcd.tv","exception":"[object] (ErrorException(code: 0): Undefined variable: selected_locale (View: /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/index.blade.php) at /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/content.php:86, ErrorException(code: 0): Undefined variable: selected_locale at /home/abcd/domains/abcd.tv/public_html/redactie/resources/views/vendor/translation-manager/content.php:86)

**Comment by freescout-helpdesk** [comment]
FreeScout 1.3.14 has been released. Just update to the latest version and Translate page will work.

**Comment by imc67** [comment]
Indeed!!! GREAT WORK!!!
