### ISSUE TITLE
tools.php page loading issue

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3820]
PHP version: 8.3.3
FreeScout version: 1.8.121
Database: MySQL
Are you using CloudFlare: No

I think there is an issue with tools.php page.

My install has located in https://support.domain.ext/freescout
This is the address setup in the .env file.

The .htaccess file into FreeScout do the redirect to the public folder.
All works fine except when, in this configuration I try to load the page tools.php

For load that page I need insert the public folder in the web address:
https://support.domain.ext/freescout/public/tools.php and in this case the page is showed without a good graphic CSS etc also if seems work correctly.

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/450a2e27-02fd-4e95-8210-98693890ee5b)

Today do the issue https://github.com/freescout-helpdesk/freescout/issues/3818 resolved by you, I discovered this page should look different 

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/194c9874-51ae-4b28-b835-3064dc9047f7)

so with this issue I may ask if there is something you can do to made also work the tools.php page to load correctly his graphic aspect?

**Comment by freescout-helpdesk** [comment]
Unfortunately we don't have solution for this case. If someone has - feel free to submit a pull request.
