### ISSUE TITLE
[Issue] Extra Security 1.0.7 for when captcha fail

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3824]
PHP version: 8.3.3
FreeScout version: 1.8.122
Database: MySQL / PostgreSQL
Are you using CloudFlare: No

Hi, thank you for recently [fix an issue](https://github.com/freescout-helpdesk/freescout/issues/3764) with the Extra Security Module!
I just wanna report another small / medium issue to see if you may improve the working of the Extra Security.

If the user after compiling the module are asked to resolve the captcha and click outside of the captcha area the module will be frozen and the send button disabled.

There is a way to avoid this maybe unlock the send button after a while or avoid the click outside the captcha close the captcha?
I don't know if this topic can help: https://stackoverflow.com/questions/66061518/google-recaptcha-v2-invisible-only-fires-once
or https://copyprogramming.com/howto/how-to-reload-the-google-recaptcha-after-submit-button-without-refreshing-page-duplicate

What I mean is the captcha is called just once, if the user click for error outside of the captcha will be unable to send the form without refresh the page. In my test once i lost also the text after a while then i refresh the page.

Find a way to let user retry the captcha can be useful.
Actually if user click outside of the captcha can be unable to send the form if they don't understand to refresh the page. Sometime refresh the page can made user loose the text.

![captissuefreescout](https://github.com/freescout-helpdesk/freescout/assets/5006150/5990cfab-ea08-4c58-9a14-5ec618504dbd)

**Comment by freescout-helpdesk** [comment]
Fixed in Extra Security Module v1.0.8

**Comment by PeopleInside** [comment]
Thank you!  🎉
