### ISSUE TITLE
SAML SSO Module with Microsoft Azure 2fa Error in Android App

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#3825]
When I activate SAML SSO Module for Freescout with Microsoft Azure it works perfectly in the browser, and in the app, unless I have a 2fa method setup with a Security Key, then the app doesn't work.

If I setup 2fa in Microsoft with an Authenticator App it works perfectly. But if a Security Key is setup, Even if the Authenticator App is still setup, Microsoft tries the Security Key first.
With other apps that don't with the security key, there was always an option to switch to the authenticator, but here in the Freescout Android App it just shows a Blank Page after entering in my Microsoft Password.

Again this is only on the Android app, not the browser.

**Comment by freescout-helpdesk** [comment]
Apparently Freescout Android App won't work with this your configuration.

**Comment by SecureCPU** [comment]
Now I'm getting this error:

![Screenshot_20240307_183106_FreeScout.jpg](https://github.com/freescout-helpdesk/freescout/assets/99109793/7e6f3ec9-22dc-4406-9ceb-46d12f50e74b)

How do I fix the configuration for microsoft SAML?

**Comment by SecureCPU** [comment]
According to microsoft the problem lies within the built-in browser of the Freescout app. Is there anyway to configure the android app to use the phones browser instead of s built in one?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. We'll add a notice to Module's page.

**Comment by SecureCPU** [comment]
Hi, so this isn't just the android app, but even through the browser.
its regarding an issue where its already signed in but needs to reuthinticate.

This was the resolution for the issue:

**Root cause:**
The application is requesting the user to sign in using a specific method but the user has already authenticated with a different method prior to access the application. For example, in the SAML request the application has a RequestedAuthnContext with the specific AuthnContextClassRef value urn:oasis:names:tc:SAML:2.0:ac:classes:Password but the user has used multifactor authentication to sign in.

**Resolution:**
Request to the developer of the application to remove the RequestedAuthnContext from the SAML request.
Another option is to request the application owner to always prompt the user for a fresh authentication. To accomplish this, the application needs to add the value forceAuthn="true" as a parameter in the request to Microsoft Entra ID.

**Comment by lucafabbri365** [comment]
Hello,
just to add this (I hope useful) information.
I managed to solve the **AADSTS75011** error by adding the authentication context _urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified_ on SAML2 module configuration:

![image](https://github.com/user-attachments/assets/7b7cba9c-22e0-433e-bf08-727fa16671d1)
