### ISSUE TITLE
Icons & navigation work only on localhost + app is blank/plaintext when accessed on (port-forwarded) host browser

### ISSUE THREAD

**Issue by tonymugo** [freescout-helpdesk/freescout#3828]
PHP version: 8.1.2
FreeScout version: 1.8.122
Database: Mariadb
Are you using CloudFlare: No

Hello Freescout mods. I work for a bank and I've been trying to deploy Freescout as our official helpdesk/ticketing system. I've successfully installed it on an Ubuntu (22.04.4 LTS) VM running via Oracle VM (7.0.12) on a Windows (10 Pro) desktop host. So far, I've been able to log in with the MySQL credentials I created, and browse through the app on [localhost](url). Good so far, but that's about it. Which leads me to problem 1: the icons, dropdowns do not work anywhere other than localhost. I'm pretty sure this has something to do with HTTPS and certificates, but to be honest, I'm stuck. After tinkering around with the Certbot commands, I successfully generated keys for [www.localhost](url), but both Chrome and Firefox refuses to recognize the .crt file. The app is also accessible on [127.0.0.1](url), [127.0.0.0](url), [0.0.0.0](url), and [10.0.2.xx](url) (my VM's IP address), and [www.localhost](url), only without any navigation and with Chinese-like symbols for icons. Please have a look at the attached screens. Problem 2: trying to access the app on (port-forwarded) host brwoser rids it of all CSS and UI design leaving only a plaintext login page. Logging in yields a blank page with an unresponsive "toggle navigation" button at the top. Please help. 

SCREENSHOTS:
![Screenshot (131)](https://github.com/freescout-helpdesk/freescout/assets/88681526/7b5e9724-1c8e-4ce3-a995-4c468b45db71)
![Screenshot (133)](https://github.com/freescout-helpdesk/freescout/assets/88681526/e44c1f06-567b-4e75-bd5c-db048b5eb7d4)
![Screenshot (134)](https://github.com/freescout-helpdesk/freescout/assets/88681526/4fb19825-c83d-47d1-9732-9658f540b6c9)
![Screenshot (135)](https://github.com/freescout-helpdesk/freescout/assets/88681526/efac9ee5-93e8-4c04-8bcd-cb695f10c4c0)
![Screenshot (136)](https://github.com/freescout-helpdesk/freescout/assets/88681526/86802af5-7213-4883-905b-7d905547f421)
![Screenshot (137)](https://github.com/freescout-helpdesk/freescout/assets/88681526/b0f10a1b-391d-413d-9830-e0b2024e3d8b)
![Screenshot (129)](https://github.com/freescout-helpdesk/freescout/assets/88681526/5aad8394-096c-4283-a2ea-12a0f4be3dd2)
![Screenshot (153)](https://github.com/freescout-helpdesk/freescout/assets/88681526/d570a5cf-74e8-4d41-97de-50aa606cad08)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
