### ISSUE TITLE
Auto reply config: {%user.photoUrl%} variable available but doesn't work (of course)

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#383]
When you configure the Auto Reply text it is possible to add {%user.photoUrl%}. But the result is that (of course) there is no image in the Auto Reply (because it is not sent by a user).

It would be great if you could add an image to the MailBox configuration so you can choose if you want to use {%user.photoUrl%} or for example {%mailbox.photoUrl%} in either auto reply or signature.

**Comment by freescout-helpdesk** [comment]
> It would be great if you could add an image to the MailBox configuration so you can choose if you want to use {%user.photoUrl%} or for example {%mailbox.photoUrl%} in either auto reply or signature.

No plans to implement this for now.

**Comment by imc67** [comment]
Ok I understand. 

1. Is there another way to use our (small volunteer) organization logo in i.e. auto-reply or signature? Now I uploaded in every user account our logo as user picture, however:
2. If a receiver doesn't load images you see the text "Picture of {username}" (where username is the real name). That's a bit strange ;-)

**Comment by freescout-helpdesk** [comment]
There is already a task for this: https://github.com/freescout-helpdesk/freescout/issues/366
