### ISSUE TITLE
"Show original" shows random mail, not original from ticket

### ISSUE THREAD

**Issue by darkp-team** [freescout-helpdesk/freescout#3830]
Hello, when I click "Show original" it shows some random mail, not original from ticket. On example I have ticket # 48211 with just "Test" in email text, but when I click to "Show original" I see original from ticket # 180 in Preview tab, but in the same time I see right email in Body tab.
![test2](https://github.com/freescout-helpdesk/freescout/assets/63156637/915880d0-a5fd-490a-a385-6196a44e9897)

![_48211_Test_-_Dark_Power-2](https://github.com/freescout-helpdesk/freescout/assets/63156637/4febca66-045e-46d1-9667-28868ea67784)

**Comment by freescout-helpdesk** [comment]
Here is the place you may need to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L715

**Comment by darkp-team** [comment]
Sorry, could You please help, what I have to do there?
I migrated about 45000 tickets from zendesk and there are just about 100 new and last emails in mailbox connected by IMAP. I understand system trying to find also old emails in mail box, but there are no ones. Is it possible to fix?
Thanks in advance!
