### ISSUE TITLE
ListConversations API query

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3832]
Hello team,
From what I understand, multiple tags cant be passed on as a parameter to  ListConversations API. I tried with multiple tags comma seperated and it didnt work. Is there a plan to support it. Let me know so I can plan my project. Thanks in advance

**Comment by freescout-helpdesk** [comment]
Only one tag is supported.

https://api-docs.freescout.net/#list-conversations

![2024-02-28_09-32-10](https://github.com/freescout-helpdesk/freescout/assets/40499291/1d219b31-3d83-48e2-9e43-cee9fc174076)
