### ISSUE TITLE
Correct the markup in the Extended Attachments module

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3833]
If the filename is without spaces, the text extends beyond the block.

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/b67933ca-e976-47e0-bb17-90872a7f7b19)

PHP version: 8.2.7
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in Extended Attachments Module v1.0.20
