### ISSUE TITLE
Confusing UI transition when a conversation is moved from a view

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3834]
Hello team,
Whenever I am on conversation detail page and I do actions  which results in it being moved to different view, I see a different conversation and it is confusing. Can we exit to list view in that case. 

Example: 
1. I am in unassigned view of 218
2. Assign it to someone else
3. I immediately see some random 245 

Going back to list view is better imo. Do let me know what you think

**Comment by sparker81** [comment]
Hi @sarsony1. You probably need to change the Default Redirect rule for your mailbox.

When you're in your Unassigned folder, click on the Mailbox Settings drop-down and click on Default Redirect.
![Default_Redirect](https://github.com/freescout-helpdesk/freescout/assets/102618401/84b2dcd2-81d4-4a39-a7f9-a2de9fa6db5e)

Choose 'Stay on the same page' in the pop-up window, then select Ok.
![Stay_on_the_same_page](https://github.com/freescout-helpdesk/freescout/assets/102618401/1e02e7c8-f431-435f-a4f7-5eafe12f9e22)

That should prevent you from moving on to the next open ticket.

**Comment by freescout-helpdesk** [comment]
@sparker81 Thanks for helping out.
