### ISSUE TITLE
status on created phone conversations

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3835]
If a phone conversation is created, it's status becomes automaticall `pending` if not manually changed to `active`. Is this intended?
In my point of view the status should be the same like with new email conversation, because the agent that takes the note is not the first responder.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/fcd7e37f-8f9e-4ad2-a29a-f47299ec5efd)

PHP version: 8.2.15
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Yes, it's by design.

Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by mokkin** [comment]
Done: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/434185

Could you tell me why it's designed like that? In my opinion conversation could not get the attention they deserve by the agents because they are not marked as active.

Meanwhile I'm going to solve this by a workflow that sets the conversation to active.
