### ISSUE TITLE
Many mailboxes best practises

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3836]
Hi,

We are using freescout as more of a shared-mailbox solution and not just a helpdesk.

We currently have around 80 mailboxes configured. And plan to have about 300 when we are finished setting it up.
However, we are struggling a bit with scaling it seems.

Mailboxes are from Microsoft, fetching with IMAP from outlook.office365.com.
We have set the fetching interval to 5 minutes, which seems a bit slow, but we can live with that if it actually worked every 5 minutes.

What we experience in practise is that it often takes ~20-30 minutes to get emails. We quite often (multiple times per day) get system emails that there are issues fetching. And then that recovers a few minutes later (after 20-30 minutes total from last fetch). In addition, even when things are seemingly working, we see quite a few `Error: connection setup failed; File: /www/html/vendor/webklex/php-imap/src/Client.php (391)` errors daily. Earlier, when we only had 5-10 mailboxes, and a fetch interval of 1 minute, things were working better, but sometimes had 5-10 minutes lags. So it seems behaviour is similar now with more mailboxes, but the delays get a lot more noticable.

We don't really know why things are lagging. There are no errors in logs that indicate things being slow or stopping up. And we feel a bit lost as to what is going on. If anyone has any suggestions that may help improve the state we are in, it is very welcome!

Note: We are not able to use any other provider than Microsoft.

We are running on the docker image provided by tiredofit: tiredofit/freescout:php8.2-1.17.56
Freescout version: 1.8.122
PHP 8.2.16
Pgsql (15.4) (managed postgres by azure)
We are running in kubernetes, with these requests / limits currently set (and it is far from using all of it)
resources:
  requests:
    memory: "3Gi"
    cpu: "1"
  limits:
    memory: "6Gi"
    cpu: "2"

We have also set PHP_MEMORY_LIMIT=2048M,
which can be increased. But we haven't seen any issues caused by that as far as we can see.

We were previously running on freescout version 1.8.106, but it has not really changed between the versions.
We have also now set this environment flag to see if it helps `APP_NEW_FETCHING_LIBRARY=true`, but it has not really changed anything in the few days we have been testing it.

Additionaly, but not the important part of this thread: We have struggled a bit to import history. Maybe because we have so many mailboxes, and many historical folders per mailbox. In general we want to import mails many years back from all the mailboxes, and are writing custom scripts to do this, which also includes things like fixing the dates (as they all have the date "right now" when imported, which makes things quite messy). If anyone has suggestions for ways to do this in a simpler way, feel free to comment on that too.

Hoping for some good suggestions!
Thanks

**Comment by freescout-helpdesk** [comment]
Most likely it's MS 365 issue. Those who are using MS 365 often report this kind of issues.

**Comment by Beaudinn** [comment]
@freescout-helpdesk 

I think the issue happens because the fetching and workflow execution are done sequentially for every mailbox. That means the first mailbox will always be the fastest, and each subsequent mailbox has to wait longer.

For example, if you have 20 mailboxes and each one takes around 5 minutes to fetch, the last mailbox will only start fetching after 20 * 5 minutes. As a result, conversations in the later mailboxes are delayed significantly.

Is there a way to make this faster, for example by running mailbox fetching in parallel instead of sequentially?
I’d also like to place a bounty (€1000) on this to get it fixed or improved.
