### ISSUE TITLE
Extra Security Module reCAPTCHA doesn't work 

### ISSUE THREAD

**Issue by AzureInformatique** [freescout-helpdesk/freescout#3838]
Hi, 

I have an error after configuring keys (reCAPTCHA V2) 
![ERROR](https://github.com/freescout-helpdesk/freescout/assets/124894927/ff157529-79a9-470d-8cf7-6acbdb3e90e8)

Logs : <html>
<body>

Févr 29, 18:59:13 | reCAPTCHA validation error (HTTP Status Code: 400): {"success":false,"error-codes":["invalid-input-response"]}
-- | --

</body>
</html>

Could you help me ? 

PHP version: 8.2
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

**Comment by AzureInformatique** [comment]
Second Error : Invalid captcha

no matter the version V2, V3

**Comment by PeopleInside** [comment]
1. Hi, could I ask where you faced the error: login customer page, operator login page or settings page?
2. Are you trying to install the Captcha in FreeScout for the first time or you did already before and with latest update you are experiencing issues?
3. Have you added the domain in the Google ReCaptcha panel to allow the captcha to work?

I'm using the Extra Security Module version 1.0.8 with PHP 8,3 but I'm not aware of any current issue.
All seems work fine so maybe I'm missing how to reproduce the issue you are reporting?

**Comment by AzureInformatique** [comment]
> 1. Hi, could I ask where you faced the error: login customer page, operator login page or settings page?

Plugin activating for login customer page, operator login page and settings page

> 2. Are you trying to install the Captcha in FreeScout for the first time or you did already before and with latest update you are experiencing issues?

First experience with this plugin, buy recently

> 3. Have you added the domain in the Google ReCaptcha panel to allow the captcha to work?

I tested with the domain and a sub domain same error

**Comment by PeopleInside** [comment]
Thanks for the reply.

I installed the Extra Security Module with a past version, some recent updates fixed some issues but I don't believe introduced a new bug that forbid you to activate and use the plugin. With my active install all seems is working fine, I'm able to login into the operator panel.

Have you added your domain without any http/https and www prefix on the Google Re Captcha configuration page?
If your domain is something like `https://helpdesk.domain.ext` you need add just `helpdesk.domain.ext` on the Google ReCaptcha domain list.

I'm using the invisible re-captcha V2

Are you using the invisible captcha?
Have you selected invisible captcha also in the security configuration type field in app-settings/extrasecurity?
Are you sure, have you checked twice that the site key is the site key corresponding on Google without spaces at the start and at the end? Same for the Secret Key?

Currently I'm not able to see any issue on the Extra Security module, if there is an issue will be useful know the exact step to reproduce.

Anyway I leave this topic to the FreeScout staff. I wrote to you just to give some point of checks you can do as I'm unable to see any issue currently. This never means there is no bugs.. just a way to say to you to check better and be sure everything is correctly setup.

Oh I forget another question: when you load the login page do you see the captcha widget?
In your screenshot I'm unable to see.

**Comment by AzureInformatique** [comment]
Thank you for your response, I have configured everything as you specified, however I just thought about my Apache configuration, I have this lines in my virtual host:

Header set X-XSS-Protection "1; mode=block"
Header set X-Content-Type-Options "nosniff"
Header add Content-Security-Policy "default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src * 'self' data: https:;"

Could this be a problem?

**Comment by AzureInformatique** [comment]
Problem solved ! Apache virtual host configuration is too strict ;)

**Comment by AzureInformatique** [comment]
Problem solved ! Apache virtual host configuration is too strict ;)

**Comment by AzureInformatique** [comment]
To help other people, here is the solution to add to your Apache configuration :

`Header add Content-Security-Policy "default-src 'self' https://recaptcha.net https://recaptcha.net/recaptcha/api.js  www.google.com www.gstatic.com 'unsafe-inline' 'unsafe-eval' data:;"`
