### ISSUE TITLE
Send Later Module error 

### ISSUE THREAD

**Issue by AzureInformatique** [freescout-helpdesk/freescout#3839]
Hi,

I have this error when I tried to send later 
![Capture d'écran 2024-02-29 190406](https://github.com/freescout-helpdesk/freescout/assets/124894927/75fc9157-9d47-4273-9a33-7e5374c04cc0)

Could you help me ? 

PHP version: 8.2
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

**Comment by markusdolla89** [comment]
I confirm the BUG

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Check errors in the browser console and in Manage > Logs > App Logs.

**Comment by alberto464** [comment]
> We can't reproduce the issue. Check errors in the browser console and in Manage > Logs > App Logs.

Hi, I also confirm the BUG, when you are planning a new conversation and want to schedule it this error appears, but if it is a response to an existing conversation it seems to work. Nothing appears in our logs.

**Comment by freescout-helpdesk** [comment]
Can someone record a video?

Are you using the latest version of the Send Later Module?

**Comment by alberto464** [comment]
> Can someone record a video?
> 
> Are you using the latest version of the Send Later Module?

Yes, it's the latest version. I sent you the video privately in the support email, there is data that unfortunately we cannot make public.

**Comment by freescout-helpdesk** [comment]
Are you using any non-official modules?

Check what is going on on Network tab in the browser console when you open the Schedule dialog.

**Comment by AzureInformatique** [comment]
I suspect this error due to CSP Header in Apache vHost config

**Comment by freescout-helpdesk** [comment]
Fixed in Send Later Module v1.0.17

**Comment by AzureInformatique** [comment]
It works ! Thanks a lot ! 
![ERRGH](https://github.com/freescout-helpdesk/freescout/assets/124894927/e76b171e-08d4-4c29-9bc4-ad341042e8c6)
