### ISSUE TITLE
Workflows module: combination of "last user reply..." AND "last customer reply..." not possible

### ISSUE THREAD

**Issue by netlane** [freescout-helpdesk/freescout#3840]
I tried to get a Workflow going that never fired - it contained 2 conditions "last user reply not within..." AND "last customer reply not within..." 

After studying the code and table structure I realized that there are no separate database fields for user reply and customer reply, so it can never trigger.

To avoid frustrations I would like to suggest, that you adjust the select boxes when creating conditions accordingly:
Only one "Last reply from" and then a selectbox with

- from customer
- from user
- from customer or user
- from customer and user

(last 2 being the same, but one cannot know this from outside)

and then following (already there) the selectbox for

- within the last
- not in the last

Thank you for your consideration
Peter

**Comment by MarianBMI** [comment]
Hello, I'd like to add to this one that even though they ar firing now, the module doesn't count the time correctly. If I want a workflow set for last user reply is not in the last 10 hours AND last customer reply is not in the last 24 hours, the workflow will trigger in 10 hours and will totally ignore the AND condition. 
@freescout-helpdesk please assist here.
