### ISSUE TITLE
Tags Module: add more colors / custom color creation or selector

### ISSUE THREAD

**Issue by distresscode** [freescout-helpdesk/freescout#3846]
Hello, 

I'd like to request the ability to add custom colors in the TAGS module. Ideally, I'd like to create/select our own colors. Adding more colors would suffice too. Thanks!

Below are some colors for easy reference that add more shades of the main colors for better usability:

#F6CE33 
#3437E9
 #DB33C8 
#38D5A9 
#37d742 
#DB3636 
#366FDB

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
