### ISSUE TITLE
No Imap Foders found

### ISSUE THREAD

**Issue by yassar-moonyadza** [freescout-helpdesk/freescout#3847]
Hello everyone.
I just installed Freescout. I was able to configure everything more or less easily.
However, I am stuck fetching emails. I use Office 365 as my mail server. I was able to connect freecout to the account using the imap parameters, but freescout gives me this error "connected, but no imap folder found". Can someone help me please.

![FreeScout errors 2](https://github.com/freescout-helpdesk/freescout/assets/154607841/63fd7611-db40-482b-9b98-dad5728d711a)
![Uploading FreeScout errors.png…]()

**Comment by freescout-helpdesk** [comment]
![2024-03-04_09-15-17](https://github.com/freescout-helpdesk/freescout/assets/40499291/4b5fe00d-3698-4082-8146-2a28bbba524a)
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#fetching-emails

**Comment by sparker81** [comment]
You can try this:

1. Open a private browsing window
2. Navigate to the Fetching Emails page
3. Disconnect the connection to Microsoft Exchange
4. Connect again by logging in on the Microsoft login pop-up with the credentials for the mailbox you want to fetch emails

The problem we ran into was that we were already logged in to Outlook with user1@domain.com, and for some reason when you try to connect the fetching email, it uses the credentials of your already logged in user. Logging in as user2@domain.com in a private browsing window fixed the problem.

**Comment by yassar-moonyadza** [comment]
Thanks a lot,

It works...
________________________________

**Comment by sidlery** [comment]
I have an update on this: With the Kiosk License on Microsoft Exchange IMAP is not supported (anymore). Minimum License required is Exchange Online Plan 1.
