### ISSUE TITLE
Accepted for delivery not sending 

### ISSUE THREAD

**Issue by ikester700** [freescout-helpdesk/freescout#3850]
Hello everyone, 

I have recently started using freescout and I love the layout. However, I am struggling to set up email SMTP with Outlook. The test email goes through without any issues, but when I try emailing a ticket, nothing goes through. I checked the log and noticed no issue, but I am confused as to why it's not working. I am sending this a different Gmail account test went to all my emails but normal ticket does not. 

This is my email log 
![Screenshot 2024-03-04 214316](https://github.com/freescout-helpdesk/freescout/assets/38677582/3f9f7431-530d-4d4f-9522-9a4661df120a)

Queued Jobs
![cron](https://github.com/freescout-helpdesk/freescout/assets/38677582/d97048d4-2e1d-4697-a0aa-b9ef4c175295)
It says 0 failed which i assume it means it send right?

Also this is the system status if need 
![status](https://github.com/freescout-helpdesk/freescout/assets/38677582/f61bdd2d-7cc4-444c-b85f-04a19a92d510)

If anyone knows how to fix this please help
 

Can anyone help me with this? Thanks.
PHP version: 8.2.16
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: Yes
I am hosting this on a Plesk Subdomain 

Edited:
I checked this link, and still nothing I am using just a normal outlook not business 365 but still checked it out :) 

https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#fetching-emails

**Comment by freescout-helpdesk** [comment]
Background jobs are not running on your FreeScout: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
