### ISSUE TITLE
jshrink error possibly causing all buttons to break

### ISSUE THREAD

**Issue by limechris** [freescout-helpdesk/freescout#3852]
PHP version: Docker 
FreeScout version: Docker 
Database: MySQL
Are you using CloudFlare: No

For some reason, today all dropdowns on the site broke and do not work anymore. I cannot get the dropdown menu under "Manage » Logs » App Logs" as the Manage menu does not open. I was able to view source and found the following starting yesterday:

```
  error 	production 	2024-03-05 17:26:42 	Error: Unclosed string at position: 571083; File: /www/html/vendor/tedivm/jshrink/src/JShrink/Minifier.php (500) 
```

The exact same is taking place with ALL buttons, I cannot reply, assign or anything.  

When this happened, I decided to update the docker image to the latest version. When I logged in, the problem persisted.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Try to disable all non-official modules or re-update the app using manual updating method.

**Comment by limechris** [comment]
I did not have any unofficial modules installed, only two that I purchased. I have pulled the docker containers again, restarted them and re-activated the modules. After a while (not immediately) the software worked normal again. You can close the issue, but just be aware that this happened without any changes from our side - the software was running perfectly fine and all of a sudden this happened. And it is not just a browser/PC, this was on different computers and operating systems. 
Anyways, since all is working, you can resolve this issue.
