### ISSUE TITLE
Pieces of markup are sometimes displayed in emails

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3853]
There are similar emails coming from some customers to FreeScout:

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/9af57410-481e-44a0-9765-8a4162942a9c)
![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/ac103c04-0755-4626-ab2e-5a3dfb195624)

PHP version: 8.2.7
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
If someone is willing feel free to fix and submit a pull request.
