### ISSUE TITLE
IMAP Fetch Error: Check Internet Connection and try again

### ISSUE THREAD

**Issue by 42deluxe** [freescout-helpdesk/freescout#3854]
Hey there.

I get the above error when I try to create new mailbox / set the IMAP collection.

An error with the IMAP settings is out of the question. I already got 2 mailboxes with the same settings (self-evident with different credentials) running fine.

The logs says:

Error: imap_open(): Couldn't open stream {mail.example.com:993/imap/novalidate-cert/tls}. [CLOSED] IMAP connection broken (server response); File: /var/www/freescout/overrides/webklex/laravel-imap/src/IMAP/Client.php (230)

I'd appreciate any help. Thanks.

PHP version: 8.2.13
FreeScout version: 1.8.122
Database: MySQL / PostgreSQL MariaDB 10.5.22
Are you using CloudFlare: No

**Comment by grrinch** [comment]
Not sure if this will help, but I'd try POP3 to see if this will work.

The error shows that it's a connection issue but also mentions something about SSL validation. I know you said you have other mailboxes with the same settings, but I'd still try to play around with the below options:
- Validate Certificate - flip it between Yes/No and re-try both
![image](https://github.com/freescout-helpdesk/freescout/assets/5729796/0fc9a4af-529b-4873-bfa1-2f63725253e9)

- Encryption - try different options.
![image](https://github.com/freescout-helpdesk/freescout/assets/5729796/1fdfee57-8121-4d31-8865-e616e63a265d)

It probably goes without saying, but just remember to save every time you change something before Checking the connection.

Hope it helps, but if it doesn't, then I can't be of much more help and we gotta wait for the FS guys.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails#troubleshooting-fetching
