### ISSUE TITLE
Stuck in loop using Older/Newer buttons 

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3855]
Hi,

when using the older/newer buttons in the conversations, sometimes you get stuck in a loop where it will keep changing between to tickets indefinitely and never go to a newer or older ticket.

Best regards

PHP version: 8.2.16
FreeScout version:  1.8.119 
Database: MySQL
Are you using CloudFlare:  No

**Comment by freescout-helpdesk** [comment]
There was such issue in the past. It's difficult to reproduce it. If you can try to debug it on your FreeScout instance and send a pull request.

**Comment by githubuser-112** [comment]
I would not know how to debug it, unfortunately. Would it be possible to show you on our system the next time it happens?

**Comment by freescout-helpdesk** [comment]
Try to debug it on your server or https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
