### ISSUE TITLE
WhatsApp messages are delayed

### ISSUE THREAD

**Issue by kirschkern** [freescout-helpdesk/freescout#3856]
When using the WhatsApp message Plugin with twilio we encounter a relatively long delay when sending messages for about 20 seconds. While this is not much in an email conversation, it is a bad user experience in a chat. Is this delay caused by FreeScout and is there an option to disable it for Chat messages? IMHO there is a default delay included for email to undo sending of my message. Is this also active when using WhatsApp?

**Comment by freescout-helpdesk** [comment]
> IMHO there is a default delay included for email to undo sending of my message. Is this also active when using WhatsApp?

You don't need it in both regular mode and chat mode?

**Comment by alberto464** [comment]
Hi, we also noticed this with WhatsApp, the ideal would be to have a variable to set in the .env file where you can specify this delay, only for chats, not for emails. In my opinion, this could be fine for emails.

**Comment by kirschkern** [comment]
> Yes. You don't need it in both regular mode and chat mode?

No, I don't need it in my chat as it is more irritating than useful to me. We are very much accustomed to receiving instant feedback when using a messenger and sending many short messages within a short period of time, especially when we are actively chatting with each other. This is different with email in my opinion.

So, I would be happy to simply disable the delay/undo feature. A hint about not being able to undo the message then might be helpful.

Also, with WhatsApp (native), it is usually possible to delete a message afterward. Maybe this could be implemented within the plugin as well?

And, thanks for the fast support. It's really awesome. We've been using Freescout for two months now, and I would never go back. Well done!

**Comment by freescout-helpdesk** [comment]
We've disabled Undo feature for chat conversations in Chat Mode.
