### ISSUE TITLE
Auto-Refresh not working on the Freescout main Page - Where you can see the all mailboxes

### ISSUE THREAD

**Issue by yoseabe** [freescout-helpdesk/freescout#3859]
Hello,
Fetching email works fine, but I have to refresh the page manually that it shows the email in the inbox?
Can someone help. Everything else works fine
PHP version: 8.1.2
FreeScout version: 1.8.125
Database: MySQL
Are you using CloudFlare:  No

**Comment by freescout-helpdesk** [comment]
There is no auto-refreshing on the Dashboard yet.

**Comment by yoseabe** [comment]
What about when I am in one mailbox? It only shows the 1 when reciving email, but I have to refresh the page to get the email?

**Comment by alberto464** [comment]
To solve this, we use an app for Chrome called "Easy Auto Refresh", it allows you to set a timer to automatically refresh the page.

**Comment by yoseabe** [comment]
@alberto464 but when you go another page it deactivates itsself

**Comment by vanessa804** [comment]
Hi @freescout-helpdesk  , possible to have the auto-refreshing inside a conversation?
