### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by ecotechie** [freescout-helpdesk/freescout#386]
I see there is a img/logo-brand.png being used for the branding:

![image](https://user-images.githubusercontent.com/11607383/70769819-e320f100-1d1f-11ea-9a0b-51ee5f75a798.png)

Any chance of making that image changeable through the general settings panel?

**Comment by freescout-helpdesk** [comment]
It will be possible soon.

**Comment by freescout-helpdesk** [comment]
Do you need to adjust anything else in the FreeScout look and feel?

**Comment by ecotechie** [comment]
I like the suggestion to be able to change colors and favicon as well. Though not sure about making it a module. I would think you'd want a robust system to start with.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/customization/
