### ISSUE TITLE
status page not available

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3860]
Since version 1.8.122 I can't access anymore `system/status` page. It simply doesn't load the page.
Upgrading to 1.8.126 didn't change this.

PHP version: 8.2.16
FreeScout version: 1.8.126
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
> doesn't load the page

You see some error or it takes too much time to load it?

If there is an error - send us logs.

If it takes too much time to load it - you'll need to debug this https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/SystemController.php#L31 (https://github.com/freescout-helpdesk/freescout/wiki/Debugging)

**Comment by PeopleInside** [comment]
You can try to load the tools.php page then clean cache from that page.
After that system page should load, if not maybe add more details will help the freescout team.

https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache

**Comment by mokkin** [comment]
> You can try to load the tools.php page then clean cache from that page.

Thank. I already did that but it didn't help.



> If it takes too much time to load it - you'll need to debug this

Thank you too. I just wanted to try it but now the page is working again.

Maybe some very very large logs (around 1.6 GB per log) of a custom module where the reason.
