### ISSUE TITLE
Disable incoming emails creating conversations

### ISSUE THREAD

**Issue by datznoah** [freescout-helpdesk/freescout#3861]
Hi there, I am just wondering if there is a way to disable incoming emails from creating conversations but still accept emails to update existing conversations. I want to require people to use a contact form I have that is integrated with the API but by disabling emails that would also presumably disable replies.

PHP version: PHP 7.4.33
FreeScout version: 1.8.126
Database: MySQL
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such feature.

**Comment by datznoah** [comment]
Not sure how complex this would be to add but in [FetchEmails.php](https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L588) couldn't you just add an env option to stop the logic if `$is_reply` is true? I understand this is a really niche feature but it could be useful for those using contact forms like myself.
