### ISSUE TITLE
Freescount security and GDPR privacy credentials

### ISSUE THREAD

**Issue by BriT999** [freescout-helpdesk/freescout#3863]
There is info on this page about Freescout security
[https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Security]

which says 

> `"FreeScout is built with strong focus on all aspects of cyber security. The software went through a series of security audits and penetration tests, and we continue to check and monitor it's security."`

Can any of these audits / pen test results be shared either privately or publicly?  

I am considering deploying Freescout for a large organisation --> so security and data prvacy is extremely important. Any helpful replies will be greatly appreciated

**Comment by freescout-helpdesk** [comment]
Unfortunately no such plans for now. Maybe with time.
