### ISSUE TITLE
Notes WYSIWYG only complete on initial creation

### ISSUE THREAD

**Issue by mitchplze** [freescout-helpdesk/freescout#3866]
Hello, 

Version **1.8.126** on Docker. 

Noticed an issue whereby when you create a new private note on a ticket, you get a full toolbar in the WYSIWYG: 

![image](https://github.com/freescout-helpdesk/freescout/assets/25162574/57ca559f-eac3-40c4-9a7e-30692bbda40d)

However, when you _edit_ an existing note, only a partial WYSIWYG is shown, and features are missing: 

![image](https://github.com/freescout-helpdesk/freescout/assets/25162574/22226e97-84a5-43b4-8826-3b2589018647)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release. But two last buttons still will be missing, there is no a solution for this for now.
