### ISSUE TITLE
The "Reply to Conversation" workflow action runs twice

### ISSUE THREAD

**Issue by SergeyMi88** [freescout-helpdesk/freescout#3867]
Hello!
I came across the following problem: I have a workflow configured in which if I select a value from the list in a custom field, a pre-prepared response will be created. The workflow settings indicate that it is executed 1 time. In this case, this response is sent twice. 
If I increase the number of executions of the script to two, then the first time it also publishes 2 answers, then when I run it again, only 1 answer is published. I have attached screenshots of the script settings to the message. How can I make sure that only one message is sent?

App version 1.8.119

![2024-03-11_19-13-09](https://github.com/freescout-helpdesk/freescout/assets/101319104/fe52df7d-4fc2-49f8-ae80-8ca6252bab58)
![2024-03-11_19-13-20](https://github.com/freescout-helpdesk/freescout/assets/101319104/e5978039-fc30-4a94-a703-03f026650026)
![2024-03-11_19-13-34](https://github.com/freescout-helpdesk/freescout/assets/101319104/fe919b9d-fa89-4e39-b546-4d2bdfc532bb)
![2024-03-11_19-14-20](https://github.com/freescout-helpdesk/freescout/assets/101319104/5b44945d-b2d9-4c51-8bc1-111338ee01a4)

**Comment by freescout-helpdesk** [comment]
There were similar reports in the past but we could not reproduce and fix the issue.
If we'll be able to reproduce it we'll fix it.
