### ISSUE TITLE
Workflows new tag value based on regexp

### ISSUE THREAD

**Issue by jjp-git** [freescout-helpdesk/freescout#3868]
Hello,

Looking for a simple ticket tracking tool for our team and just discovered Freescout, which is a really effective approach to the topic.
Very pleased after deploying a test server. Overall I think my team we'll go with it but I have a question regarding workflows and tags.

Can workflows set the tag value to a a regexp match in conversation subject ?
I toyed with live demo, but could not see anything approaching that.

The context: 
- track actual users requests > this is covered
- track some automatic email some old alerting tools sends us
Messages come in the form of [FIRING] XYZ > [FIRING] XYZ > [FIRING] XYZ > [RESOLVED] XYZ
This sequence would create 4 differents conversations in Freescout.
I know the tool is not designed for that, but I'm looking for a way to close (and merge) related mails.
If I could set the tag value to "server: XYZ", I could then have good condition options for further workflows.

Thanks for any feedback.

Cheers.

JJ

FreeScout version: live demo

**Comment by freescout-helpdesk** [comment]
There is no such feature for now.
Feel free to submit a feature request: https://freescout.net/request-feature/
