### ISSUE TITLE
Sound notification when a new chat pops up

### ISSUE THREAD

**Issue by Rodrigo-Enviou** [freescout-helpdesk/freescout#3869]
Is it possible to configure a sound when a new chat pops up? It would be very helpful for the agent to identify when someone is waiting on the chat.

PHP version: 8.2.15
FreeScout version: 1.8.120
Database: MySQL (10.6.7)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
