### ISSUE TITLE
Error:   No application encryption key has been specified.  

### ISSUE THREAD

**Issue by igorhoop** [freescout-helpdesk/freescout#3873]
I deployed **Freescout** to my **VPS** following the instructions. I use **nginx**, but writes an error when logging in through the browser

```
502 Bad Gateway
```

Then I tried to run the script `index.php` to find out what is happening:

```
cd public
php index.php
```
and I get the following error:

```
In EncryptionServiceProvider.php line 42:
No application encryption key has been specified.
```

How to fix it? I want to finally get into the web interface

---

PHP version: 7.4.3-4ubuntu2.20
FreeScout version: I don't know, I downloaded the **freescout-dist** archive from the **Download** button on your website
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://stackoverflow.com/a/48303288 or re-install the application.

**Comment by igorhoop** [comment]
Okay, it helped get rid of the **encryption** problem. Thank you.

But now **nginx** reports: `502 Bad Gateway`

Run the **index.php** script:
```
PHP Notice:  Undefined index: REQUEST_URI in /var/www/freescout/public/index.php on line 9
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=https://:/login#" />

        <title>Redirecting to https://:/login#</title>
    </head>
    <body>
        Redirecting to <a href="https://:/login#">https://:/login#</a>.
    </body>

```

**Comment by igorhoop** [comment]
The problem has been **resolved** and was in the wrong **nginx** configuration.

In the file `/etc/nginx/sites-available/freescout` change the line:
```
fastcgi_pass unix:/run/php/php8.0-fpm.sock;
```

it was necessary to change **php8.0** to **php7.4**, which is installed on my system
