### ISSUE TITLE
Folder: Starred; Error: [NONEXISTENT] Unknown Mailbox

### ISSUE THREAD

**Issue by eddie477** [freescout-helpdesk/freescout#3874]
PHP version: 8.2.16
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare:  No

Hello to all, 

I am getting this error and I do not understand why:

Mar 13, 13:00:09 | Error fetching email | Folder: Starred; Error: [NONEXISTENT] Unknown Mailbox: Starred (now in authenticated state) (Failure) | Agentes de Viaje
-- | -- | -- | --
Mar 13, 13:00:09 | Error fetching email | Folder: Trash; Error: [NONEXISTENT] Unknown Mailbox: Trash (now in authenticated state) (Failure) | Agentes de Viaje
Mar 13, 13:00:09 | Error fetching email | Folder: Trash; Error: [NONEXISTENT] Unknown Mailbox: Trash (now in authenticated state) (Failure) | Agentes de Viaje
Mar 13, 13:00:09 | Error fetching email | Folder: [Gmail]; Error: [NONEXISTENT] Unknown Mailbox: [Gmail] (now in authenticated state) (Failure) | Agentes de Viaje
Mar 13, 13:00:08 | Error fetching email | Folder: Sent Mail; Error: [NONEXISTENT] Unknown Mailbox: Sent Mail (now in authenticated state) (Failure) | Agentes de Viaje
Mar 13, 13:00:08 | Error fetching email | Folder: Sent Mail; Error: [NONEXISTENT] Unknown Mailbox: Sent Mail (now in authenticated state) (Failure) | Agentes de Viaje
Mar 13, 13:00:08 | Error fetching email | Folder: Spam; Error: [NONEXISTENT] Unknown Mailbox: Spam (now in authenticated state) (Failure) | Agentes de Viaje

Please help ... I am connecting to GMAIL Google Suite.

**Comment by freescout-helpdesk** [comment]
Just remove "Starred" folder from mailbox's Fetching Settings.

**Comment by freescout-helpdesk** [comment]
Fetching from INBOX is enough, you don't need any of Starred folders.

**Comment by eddie477** [comment]
All the folders were populated after clic on Get folders.
