### ISSUE TITLE
Problems activating Telegram modules

### ISSUE THREAD

**Issue by ggadmin1** [freescout-helpdesk/freescout#3875]
PHP version: PHP 8.1.2-1ubuntu2.14
FreeScout version: 1.8.126 
Database: MySQL
Are you using CloudFlare: No

**Comment by ggadmin1** [comment]
So apparently my text wasn't included:

We have the problem that when you want to activate the Telegram notification you always get an error:

Error occurred setting up a Telegram webhook: file_get_contents(https://api.telegram.org/***/setWebhook?url=https://***/telegram/webhook/1/***): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

We've already looked at the firewall, but nothing is being blocked here.


Can you support us here?

**Comment by freescout-helpdesk** [comment]
Unfortunately not. It need to be investigated by someone on your server.

**Comment by ggadmin1** [comment]
OK.

Who could help here or take a look at something like this?

**Comment by freescout-helpdesk** [comment]
You can try to find someone: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
