### ISSUE TITLE
Forwarding Emails not creating with correct email

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#3876]
Hey,
 I'm forwarding emails to freescout adding the @fwd to the email, but the tickets gets created using the sent email that the one in the body.
How to I fix this issue?

![image](https://github.com/freescout-helpdesk/freescout/assets/99109793/bdf7bab0-8152-4c72-889d-9d185d2c9600)

**Comment by SecureCPU** [comment]
Server Specs:
App Version	1.8.126    
Date & Time	Mar 14, 2024 10:01am
Timezone	America/New_York (GMT-0400)
Protocol	HTTPS
Proxy	
CloudFlare
DB	Mysql (8.0.36-0ubuntu0.22.04.1)
Web Server	nginx/1.18.0
PHP Version	PHP 8.2.15
PHP upload_max_filesize / post_max_size	100M / 100M

**Comment by freescout-helpdesk** [comment]
Try to debug it on your server and submit a pull request if you'll find a solution.
