### ISSUE TITLE
Slack Module Listing Archived public channels

### ISSUE THREAD

**Issue by alister-cf** [freescout-helpdesk/freescout#3878]
While adding the slack module i have noticed it's showing a lot of old archived channels, it would be nice if archived channels were filtered out. It's also missing the only channel I am looking for! Is a free text field an option?

PHP version: 8.2.16
FreeScout version: 1.8.126 (docker)
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in Slack Integration Module v1.0.17.
