### ISSUE TITLE
Conversations bulk actions - not visible

### ISSUE THREAD

**Issue by kowach** [freescout-helpdesk/freescout#3879]
There is special case when bulk actions toolbar is not visible:
1. Click on header column to sort by Conversation or Number or Since.
2. Go back (click on browser back button)
3. Check one or more conversations (bulk actions are not shown)

If you click to "Unassigned" and check one or me conversations, bulk actions are shown.

PHP version: 8.1
FreeScout version: 1.8.126
Database: MariaDB
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
It should be fixed now in the latest FeeScout.
