### ISSUE TITLE
Feature Request: LDAP mapping groups to Mailboxes

### ISSUE THREAD

**Issue by brennanmurphy** [freescout-helpdesk/freescout#388]
Hi there, we're looking at implementing Freescout at our organization and the only hold back for us right now is we would like to have LDAP auto imported users assigned to mailboxes based on the groups they are a member of. We have around 30 mailboxes with over 100 users, so our IT teams isn't too keen on having to be constantly setting up new accounts on the system.

I would actually be willing to build this feature in myself, we use a few different open source projects based on Laravel all with LDAP and group mapping that I've built. Not sure how you handle development on modules though.

**Comment by freescout-helpdesk** [comment]
If you wish you can implement the functionality and send updated module to support@freescout.net

**Comment by zottelchin** [comment]
Hey, 
we started using freescout in our student council lately. We now added the ldap module and were looking for the same feature @brennanmurphy descriped. Was there any progress in implementing this?
Kind regards Phillipp

**Comment by freescout-helpdesk** [comment]
Unfortunately, not. Hard to say when it can be ready.

**Comment by zottelchin** [comment]
Ok, i'm willing to try to implement this feature. Where can i get the module for development purposes?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs

**Comment by freescout-helpdesk** [comment]
The feature has been added in LDAP Module v1.0.16
