### ISSUE TITLE
Browser notification not working for more than one user

### ISSUE THREAD

**Issue by yoseabe** [freescout-helpdesk/freescout#3880]
Hello, 
when testing freescout as an admin the browser notification works fine, but as soon as I one more user to have access to the mailbox the browser notification stops working for me(admin) and for all other users, which means only one user is able to recive browser notifications.
Is there a solution for this issue?
We want to be able to use one Mailbox with multiple users that work on it.

PHP version: 8.3
FreeScout version: latest 
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Are you using any non-official modules?

**Comment by yoseabe** [comment]
Yes, everything is OK and I am not using any modules

**Comment by freescout-helpdesk** [comment]
If you'll manage to find the reason feel free to submit a pull request.

**Comment by yoseabe** [comment]
@freescout-helpdesk am I the only one getting this issue? I installed by using Interactive installation bash-script (Ubuntu / Debian / etc). I tried changing php Versions 7.4 and 8.0 both of them with the same issue.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
