### ISSUE TITLE
Duplicated sent messages through WhatsApp 

### ISSUE THREAD

**Issue by eddie477** [freescout-helpdesk/freescout#3881]
PHP version: 8.2.16
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare:  No

Hello to all!! 

I do not know if this is the normal behavior but when someone replies a WhatsApp chat through WhatsApp the platform shows two times the reply.

I think one is from the user and the other from the admin. I hope the user is not receiving two replies.

Please advise.

<img width="581" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/3789038/7f30bee6-e7e3-4239-80b0-e69ba282727f">

**Comment by freescout-helpdesk** [comment]
Unfortunately we have not experienced the issue on our end. Somehow it needs to be investigated on your FreeScout instance.
