### ISSUE TITLE
Ticket viewing loading time issue

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-helpdesk/freescout#3882]
We are encountering a challenge with the loading time for ticket views. Occasionally, it is taking upwards of 10 seconds to display a single ticket. Are there any strategies or optimizations we can implement to improve the speed of this process?"

PHP version: 7.4.33
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
The issue needs to be investigated on your server. All we can recommend is to try to monitor background jobs.
