### ISSUE TITLE
Override translation and files template

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3883]
PHP version: 8.3.3
FreeScout version: 1.8.126
Database: MySQL 
Are you using CloudFlare: No

---

I need use custom translation and custom footer template also I edited some module core file to fix some issues.
Every time an update occur I loose my custom translation and fix I made in the modules and in the core translation.

There is a way to avoid this loosing maybe recreating a custom file in a override folder?

If there is no way I hope will be possible in the future so maybe keep this as feature request.

- I have custom translation
- I have custom footer
- I have custom module code that fix issue with dark theme and responsiveness

Every update made me loose this customization.
I need a way to not have to replace that change every time manually :-)

**Comment by freescout-helpdesk** [comment]
There is no such feature for now. You can create some custom module for this.

**Comment by PeopleInside** [comment]
I'm not a developer. How I can create a custom module to not loose my live chat in the footer.
Freescout has a live chat but it doesn't fit my need currently and i have already a live chat active also I loose language customization, all code I need to have in the footer. My CSS modification to support the dark mode also for user and rating interface.

OK I understand seems there is no way to not loose customization.

**Comment by PeopleInside** [comment]
As Freescout doesn't allow me to auto update because if I do I loose all customization (translation) and fix that i made for have a dark mode available also on user interface side I need to update manually all time.

If I'm able to track any new version of Freescout on GitHub and get notified by email when is available, how to be informed by email when a module update is available?

I suppose there is no way so I get some issues on keep FreeScout updated:

- on each update I loose my custom translation
- on each update I loose my custom edit to have dark mode available also on user side
- I'm able to get email notification from GitHub when a new version of FreeScout is available but not for modules when they need an update.
