### ISSUE TITLE
Duplicate "delete messages" confirmation box if you sort messages

### ISSUE THREAD

**Issue by cicoasm** [freescout-helpdesk/freescout#3884]
Report a bug. Duplicate "delete messages" confirmation box if you sort messages. Here are the steps:

1. Go to a box
2. Sort messages by subject, number, etc...
3. select messages
4. Click the delete button
5. The confirmation box will appear twice.
![screen](https://github.com/freescout-helpdesk/freescout/assets/15195823/f5f88cd1-a101-4a71-b382-4b236177a35f)

PHP version: 7.4.10
FreeScout version: 1.8.126
Database: MySQL Mysql (5.5.5-10.0.38-MariaDB-0ubuntu0.16.04.1)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
