### ISSUE TITLE
Fetching job killed with signal 15

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3885]
Hi,

Our fetching jobs are being killed with:
> The process has been signaled with signal "15". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The process has been signaled with signal \"15\". at /www/html/overrides/symfony/process/Process.php:434)

We are having issues where the fetching job is killed now and then. After a lot of debugging we have found out that the reason is that the mutex that is checked against is always null. So what happens is if the job (scheduleRun = true) is run while fetching is still going on, it kills the job. However, it does not start a new job until FETCH_MAX_EXECUTION_TIME has run out. It almost seems like the schedule library and the code accessing Cache in the kernel file are using different caches or something.

We tried modifying the code to get the mutex value and logging it, but it is always null.
```
$mutex_name = $schedule->command($fetch_command_name)
                ->skip(function () {
                    return true;
                })
                ->mutexName();
$mutex_value = Cache::get($mutex_name);
```

We have not found a way to inspect the cache. The file cache structure is very cryptic, and the library doesn't give an option to list all keys. We even tried using redis as cache, but setting the environment variables for that does not seem to do anything.

It is quite clear that there is some issue here, but we don't really know how to proceed.

Any insight or help is appreciated!

We are running on the docker image provided by tiredofit: tiredofit/freescout:php8.2-1.17.56
Freescout version: 1.8.122
PHP 8.2.16
Pgsql (15.4) (managed postgres by azure)

Thanks

**Comment by freescout-helpdesk** [comment]
No need to duplicate issues: https://github.com/freescout-helpdesk/freescout/issues/3844

**Comment by borgarlie** [comment]
Closed as duplicate.
