### ISSUE TITLE
Browser, mail and mobile notifications not working.

### ISSUE THREAD

**Issue by Osten625** [freescout-helpdesk/freescout#3888]
Greetings!
My notifications don't work. Neither notification by mail, nor in the browser, on the mobile application (Android).
I checked the mailbox for sending and receiving - everything is ok. An entry appears in the log that the letter is accepted for delivery only when I send a test letter from the mailbox settings. When I create a new ticket, no records of sending a letter to the client appear in the log.
What should I do?

PHP version: 8.2.7
FreeScout version: latest
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Make sure everything is OK on Manage > System page.

https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues
