### ISSUE TITLE
Setting CACHE_DRIVER=redis does not do anything

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3889]
Hi,

We tried to change cache to redis by setting the environment variables:
```
CACHE_DRIVER=redis
REDIS_HOST=tls://RESOURCE_NAME.redis.cache.windows.net
REDIS_PASSWORD=password
REDIS_PORT=6380
```
But it does not do anything. Don't see anything in logs either. Everything functions as before.
File cache is still used. Is this intended behaviour?

Freescout version: 1.8.122
PHP 8.2.16

**Comment by freescout-helpdesk** [comment]
We have not tried to use redis as a cache driver. If you'll find a solution - feel free to share.

**Comment by voipexpert** [comment]
> Hi,
> 
> We tried to change cache to redis by setting the environment variables:
> 
> ```
> CACHE_DRIVER=redis
> REDIS_HOST=tls://RESOURCE_NAME.redis.cache.windows.net
> REDIS_PASSWORD=password
> REDIS_PORT=6380
> ```
> 
> But it does not do anything. Don't see anything in logs either. Everything functions as before. File cache is still used. Is this intended behaviour?
> 
> Freescout version: 1.8.122 PHP 8.2.16

Have you managed to get redis to work?
