### ISSUE TITLE
Reply with adjusted subject: reply resets subject

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#389]
When I sent an email from FreeScout to ie. a Helpdesk, they reply with a changed subject containing an unique ID. 

When I reply to that reply the subject is changed to the original one without that unique ID. This results in creating a new ticket at that helpdesk.

**Comment by freescout-helpdesk** [comment]
For FreeScout subject does not matter. It identifier replies by Message-ID headers and unique code inside of the sent email.

It means recipient removes both of them. The only way to fix this is to change recipient's behaviour.
