### ISSUE TITLE
Please check your commit

### ISSUE THREAD

**Issue by smilemittal** [freescout-helpdesk/freescout#3891]
Please check your commit 
https://github.com/freescout-helpdesk/freescout/commit/0826102f6e97d918dd5091fd4a0bbf4679870e76

It is not fixing the issue, it removes all email content, just leaving the only link behind.
![image](https://github.com/freescout-helpdesk/freescout/assets/13959872/a8ace2d6-8c46-4431-9cbb-fba0d42785c2)

Original content
![image](https://github.com/freescout-helpdesk/freescout/assets/13959872/7daa6d03-f139-4041-bcd9-01f8a6c171c1)

_Originally posted by @smilemittal in https://github.com/freescout-helpdesk/freescout/issues/3664#issuecomment-2008981567_

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/3865#issuecomment-1990945964

**Comment by smilemittal** [comment]
understood but still this made a big issue for me, I can't see my full email

**Comment by mokkin** [comment]
I can confirm this. The patch from @smilemittal works for us, but with the two newer commits you made it doesn't work.

Is there a reason?

**Comment by smilemittal** [comment]
You've implemented the following code, which unfortunately conceals my entire email. I would prefer if you just remove the link:

```php
$body = preg_replace('/<!\-\-\[if !mso\]><!\-\->(.*?)<![ ]+\-\-<!\[endif\]\-\->/s', '$1', $body);
```

However, my original code is as follows:

```php
// Remove only the <!--[if !mso]><!--> and <!--<![endif]--> comments surrounding the <a> tag
$body = preg_replace('/<!--\[if !mso\]><!-->(.*?)<!--<!\[endif\]-->/s', '$1', $body);
```

Could you please review and correct the issue?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/issues/3894

**Comment by mokkin** [comment]
I have updated to v1.8.128. It is bringing the content back but still removes the link with the URL.
