### ISSUE TITLE
User Notification Emails

### ISSUE THREAD

**Issue by ThomasBergmann123456** [freescout-helpdesk/freescout#3895]
Hi,

Version 1.8.127

I'm owner of the ticket and also customer for testing reasons. I want to be informed as customer as soon as a new reply is done by mail or via helpdesk. Why is the system sending "randomly" a notification? In other words - sometimes a notification is sent, sometimes not (marked in red). Why? Is this a bug?

![2024-03-21 15 05 29](https://github.com/freescout-helpdesk/freescout/assets/152280874/a62fdce3-df1a-4920-8451-34615bf09ee9)

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by ThomasBergmann123456** [comment]
Thanks, but the message on the red posts means: no sending tries yet. So I can't see a technical error.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
