### ISSUE TITLE
Backup of Freescout using a Module

### ISSUE THREAD

**Issue by semaf** [freescout-helpdesk/freescout#3896]
Hey,

The documentation for backup so poor, forwarding to an external wordpress backup script which has to be edited to get it working. On docker it wont work and there is no solution for docker. I am trying to set up Borgmatic which has some issues.

Why not a backup modul that connects over SFTP, SSH, WEBDAV, RSYNC, RCLONE, etc.. ?

**Comment by raramuridesign** [comment]
@semaf Write your own script. Might be a better solution or use hosting which has this all included.

**Comment by semaf** [comment]
> @semaf Write your own script. Might be a better solution or use hosting which has this all included.

👏👏👏 I wouldn't have thought of it. Very solution-orientated, thank you!

**Comment by freescout-helpdesk** [comment]
We don't plan to implement such a module. If someone would like - feel free to implement and share it.

**Comment by semaf** [comment]
Done but wont share
