### ISSUE TITLE
$prev_customer_id is not initialized

### ISSUE THREAD

**Issue by dryabov** [freescout-helpdesk/freescout#39]
https://github.com/freescout-helpdesk/freescout/blob/020c9e1b8f37da86879e18f138024e82803612b3/app/Console/Commands/FetchEmails.php#L462

PHP 7.2 gives error at the above line if $prev_customer_id is not initialized. The solution is trivial
```php
        $prev_customer_id = 0;
```
at the beginning of `saveCustomerThread` method

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/12b4fc23785c058a08979c986560a7be8151835f
