### ISSUE TITLE
Difference in headers of sent message vs. stored in IMAP `INBOX.Sent`

### ISSUE THREAD

**Issue by ohader** [freescout-helpdesk/freescout#3900]
Headers of sent message (taken from the recipient) - all good, headers as expected:

```
  Message-ID: <reply-247-4cf3a52c61712247@in-die-musik.de>
  Date: Sun, 24 Mar 2024 16:28:04 +0100
  Subject: [#111] TEST
+ From: "Oliver Hader | IN.DIE.musik e.V." <info@in-die-musik.de>
+ To: Oliver Hader <oliver.hader@typo3.org>
  MIME-Version: 1.0
```

Headers of message stored in IMAP `INBOX.Sent` folder - `From:` and `To:` headers lack names:

```
  Date: Sun, 24 Mar 2024 16:28:05 +0100
- From: info@in-die-musik.de
  Subject: [#111] TEST
- To: oliver.hader@typo3.org
  Message-ID: reply-247-4cf3a52c61712247@in-die-musik.de
```

The `From:` and `To:` mail headers should be the same in both cases.

---

PHP version: 8.2
FreeScout version: [1.8.128](https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.128)
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by ohader** [comment]
The mentioned commit above just concerns the `From:` header, but leaves the `To:` header.

Besides that, substitutions are not applied:

```
Date: Mon, 01 Apr 2024 20:24:25 +0200
From: "| ACME Inc." <redacted@example.org>
Subject: [#325] Test
To: oliver.hader@typo3.org
```

Having the custom from name defined as `{%user.fullName%} | ACME Inc.`.

I can try fixing this with a separate PR during the next few days...

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
