### ISSUE TITLE
Customer reply is not displayed in message

### ISSUE THREAD

**Issue by apecity** [freescout-helpdesk/freescout#3904]
Here is how the message from the client appears in Outlook. You can see his reply, starting with "good morning".

![OUTLOOK_2024-03-26-08-29-57](https://github.com/freescout-helpdesk/freescout/assets/18216162/7e6274ff-bf5e-4153-ac40-2cf8da84c461)

But in Freescout, his reply isn't shown at all.  I mean, we can see there is a reply but there is no content.
![firefox_2024-03-26-08-30-15](https://github.com/freescout-helpdesk/freescout/assets/18216162/69b38141-03e8-4d98-ac09-fe218a99e46c)

When we try using 'show original', we get the error, "The original message could not be loaded from mail server, below is the latest truncated copy stored in database." But Outlook and webmail are both able to access and display the message on the mail server, so I am not sure that error is accurate.

Thank you!

PHP version: PHP 8.1.12-1ubuntu4.3
FreeScout version: 1.8.128
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ

**Comment by apecity** [comment]
I tried adding APP_ALTERNATIVE_REPLY_SEPARATION=true to the .env file as recommended in the FAQ. No change.  

The message hasn't been deleted from the mail server.

**Comment by freescout-helpdesk** [comment]
> In such cases the email can be viewed using "Show Original" button.

https://github.com/freescout-helpdesk/freescout/wiki/FAQ#some-emails-are-empty-or-truncated-in-freescout

**Comment by fulldecent** [comment]
On the page

https://github.com/freescout-help-desk/freescout/wiki/FAQ#why-does-show-original-window-shows-truncated-message-without-previous-history

it will be nice if can say how to further debug this issue
