### ISSUE TITLE
Domain migration

### ISSUE THREAD

**Issue by latamclickcom** [freescout-helpdesk/freescout#3905]
I have installed FreeScout on a .net domain and I want to move it to another .com domain that is hosted on the same server, what is the safest way to avoid losing the data and settings? Thanks.

cPanel Version: 118.0 (build 4)
FreeScout version: 1.8.128
Database: 10.6.17-MariaDB
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment]
Move files and DB. Maybe this will help: https://github.com/freescout-helpdesk/freescout/wiki/Backup
