### ISSUE TITLE
WhatsApp Module - Images Not Displaying in Received Messages

### ISSUE THREAD

**Issue by Matthias-Ab** [freescout-helpdesk/freescout#3906]
PHP version: 8.3.4
FreeScout version: 1.8.128
Database: MySQL
Are you using CloudFlare: No

Hello to All

The WhatsApp Integration Module is not displaying images from messages received via WhatsApp in FreeScout. While text messages appear as expected, images are missing entirely.

Expected Behavior:

The received message should display the embedded image alongside the text content.

Actual Behavior:

The image is absent from the message.

Additional Information:

FreeScout version: 1.8.128
WhatsApp Integration Module version:  1.0.22

Severity:

High - This issue impacts the ability to view complete message content, potentially hindering communication and troubleshooting efforts.

Possible Causes:

Issue with the WhatsApp Integration Module's image handling.
Configuration issue with the module or FreeScout itself.
Request:

We kindly request an investigation into this issue to determine the cause and a potential solution to ensure images are displayed correctly within received WhatsApp messages in FreeScout.

**Comment by Matthias-Ab** [comment]
@idressos

**Comment by freescout-helpdesk** [comment]
You may need to find someone who can investigate it on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer) as we have not experienced this issue on our servers.

**Comment by idressos** [comment]
Hello,

After investigation we have figured out that in order for FreeScout to be able to fetch media from Twilio API, we have to disable Basic HTTP Authentication for media access in our Twilio account Messaging settings.

Apparently when making the relative HTTP requests, the WhatsApp Integration module seems to not use HTTP authentication, at least not properly.

It's most definitely **insecure** to leave this option disabled just for FreeScout to be able to fetch media - I believe this functionality needs to be patched in to the module as soon as possible.

Official Twilio explanation (also see screenshot below):
https://support.twilio.com/hc/en-us/articles/223183748-Prevent-Unauthorized-Access-to-Your-Programmable-Messaging-Media-with-HTTP-Basic-Auth-

![image](https://github.com/freescout-helpdesk/freescout/assets/96877388/4a06f708-ebb0-497c-b6c5-eed0089b19fa)

**Comment by freescout-helpdesk** [comment]
Please email us at support@freescout.net - we'll send you a patch to test.

**Comment by freescout-helpdesk** [comment]
Fixed in WhatsApp Integration Module v1.0.23
