### ISSUE TITLE
queue:work and serious cron job issues

### ISSUE THREAD

**Issue by MikeP1990** [freescout-helpdesk/freescout#3909]
Hello,

I'm having some issues with a fresh installation of Freescout and the cron jobs.  I set the cron job as displayed in the system status area but it began killing my VPS, launching several processes and none of them dying off.  I'm on a 4GB VPS with very little traffic elsewhere but Freescout seems to be bringing it to its knees.

![image](https://github.com/freescout-helpdesk/freescout/assets/1528466/854672ab-4fce-42ab-858a-a3461e6578fe)

The queue:work has never worked - even though the cron job is running but seems to never complete.

PHP version: 8.1.27
FreeScout version: 1.8.128
Database: MySQL / PostgreSQL - Mysql (10.6.17-MariaDB) 
Are you using CloudFlare: Yes / No - No

All requirements are green OK.

Any help would be appreciated.

**Comment by wejrcze** [comment]
Had similiar problem and it was storage speed

**Comment by freescout-helpdesk** [comment]
The only way to figure out the reason of your issue is for someone to check it on your server.  You may need to find someone who can investigate it on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer)
