### ISSUE TITLE
Issue: CSS not loading after installation

### ISSUE THREAD

**Issue by jxs714** [freescout-helpdesk/freescout#391]
Hey guys,

Excellent job on the software. Been struggling for hours trying to figure out why CSS isn't being loaded at all when vising domain.com/login. 

The installation worked fine and confirmed all folders writable and readable, but once the installation finishes, the login pages has no css loaded. I tried both nginx and apache, same thing occurs. Not sure what to do at this point. This is my installation setup using Plesk

httpdocs/ = root folder of web server account. Main files of the freescrout zip files were moved here
httpdocs/domain.com = the domain root web folder of website. Files from "public" were copied over to this folder

Installation works fine, after installing, forwarded to login but no css at all. Checked logs in plesk and do not see any errors.

Looking forward to hearing back soon. Thanks!

**Comment by freescout-helpdesk** [comment]
Check CSS in `public/css/builds`. If they are not there, it means PHP can not write there.

**Comment by jxs714** [comment]
Hey my friend,

Thanks so much for reaching back very quickly, that was very kind of you. You are right, that folder is blank! How can I resolve this? Does that mean permissions are wrong somewhere?

**Comment by freescout-helpdesk** [comment]
It means PHP can not write there.
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server

**Comment by jxs714** [comment]
Thanks for the response. I see. So is there a way to move the entire file to the main web root folder instead of web server folder? I believe that is the issue, which i found weird because I've never installed a php software that required webserver root folder instead of html main web folder. Is this possible? I believe this should solve it, but not sure if its possible since I tried it previously and receive non-stop errors of files missing.

Please advise, thanks!
