### ISSUE TITLE
swiftmailer package deprecated / abandoned

### ISSUE THREAD

**Issue by michaeleichmann** [freescout-helpdesk/freescout#3910]
Hi guys

I just wanted to quickly ask whether there are any plans for replacing the deprecated and abandoned "swiftmailer" package? E.g. with https://github.com/symfony/mailer or a similar one?

Thanks for maintaining this great software and have a great day!

**Comment by freescout-helpdesk** [comment]
Nope. https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#maintaining-security-and-laravel-no-upgrade-policy

**Comment by michaeleichmann** [comment]
Alright! Thanks for the quick response!
