### ISSUE TITLE
database suddenly truncated

### ISSUE THREAD

**Issue by DianaChica** [freescout-helpdesk/freescout#3912]
PHP version: 8.3
FreeScout version: 1.8.120
Database:  PostgreSQL
Are you using CloudFlare: No

Im having freescout locally and i havent had problems before with the database, but i got a problem yesterday with my db. After changing the database password with the same user and same database and after restarting the service most of the data was truncated from the tables. Intriguingly,  this included tables for modules (e.g., the workflows table from the Workflows plugin, the webhook table from ApiWebhooks, etc.), which, under normal circumstances, would retain information such as licenses in the modules table. However, the modules table was also found to be empty.  
My questions are:

1. Have you ever seen this problem before(all data empty in all tables)?
2. Is there a trigger action that could cause for freescout truncate data from the tables?
3. Is there a method to determine the root cause of this problem, to ascertain whether it originated from FreeScout or the database itself?

Please note, both FreeScout and its database are deployed on Kubernetes.

Thank you so much for the advance response, we appreciate it.

**Comment by freescout-helpdesk** [comment]
Unfortunately "No" to all questions.
