### ISSUE TITLE
"Show original" shows random mail, not original from ticket

### ISSUE THREAD

**Issue by darkp-team** [freescout-helpdesk/freescout#3913]
Sorry, I asked before, but couldn't fix it. Could You please help, what I have to do there?
I migrated about 45000 tickets from zendesk and there are just about 300 new and last emails in mailbox connected by IMAP. I understand system trying to find also old emails in mail box, but there are no ones. Is it possible to fix?
**Thanks in advance!**

My old post - when I click "Show original" it shows some random mail, not original from ticket. On example I have ticket # 48211 with just "Test" in email text, but when I click to "Show original" I see original from ticket # 180 in Preview tab, but in the same time I see right email in Body tab.

![307936117-915880d0-a5fd-490a-a385-6196a44e9897](https://github.com/freescout-helpdesk/freescout/assets/63156637/778699fe-7d08-4314-b152-c469fa96215b)
![307936869-4febca66-045e-46d1-9667-28868ea67784](https://github.com/freescout-helpdesk/freescout/assets/63156637/b9eb2d64-600e-4b49-9f19-45be5aec4013)

**Comment by freescout-helpdesk** [comment]
> I understand system trying to find also old emails in mail box, but there are no ones. Is it possible to fix?

We can't understand your question.

> My old post - when I click "Show original" it shows some random mail, not original from ticket. 

Apparently `Message-ID`s got messed up somehow during migration.

**Comment by darkp-team** [comment]
The biggest problem is new messages show wrong originals. I mean messages coming after migration and fetched via IMAP also with wrong body. Is there any way to fix it or find any help?

**Comment by freescout-helpdesk** [comment]
You can try to debug it yourself (https://github.com/freescout-helpdesk/freescout/wiki/Debugging) or find some professional who can do it.
