### ISSUE TITLE
Workflows not firing

### ISSUE THREAD

**Issue by natzar** [freescout-helpdesk/freescout#3914]
PHP version: 7.4.3
FreeScout version: 1.8.125
Database: MySQL 
Are you using CloudFlare:  No

error in logs:
  error	production	2024-03-26 00:01:02	 The process has been signaled with signal "15". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The process has been signaled with signal \"15\". at /usr/www/users/gophpj/crm/overrides/symfony/process/Process.php:434)

Hi, Workflows are not firing no matter I do.

I have this permanent error:
![Captura de pantalla 2024-03-27 a las 8 41 53](https://github.com/freescout-helpdesk/freescout/assets/1593064/fad62011-5e80-4a3e-a3f1-4bcd20a15bd3)

And I fixed it by calling the crons like this....

![Captura de pantalla 2024-03-27 a las 8 42 36](https://github.com/freescout-helpdesk/freescout/assets/1593064/c9da1804-640e-448e-9825-dc6c5e3c5241)

**Comment by freescout-helpdesk** [comment]
All we can suggest is already here: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs
