### ISSUE TITLE
Issues with email reply chains

### ISSUE THREAD

**Issue by natzar** [freescout-helpdesk/freescout#3915]
PHP version: 7.4.3
FreeScout version: 1.8.125
Database: MySQL
Are you using CloudFlare: No

error in logs:
error production 2024-03-26 00:01:02 The process has been signaled with signal "15". {"exception":"[object] (Symfony\Component\Process\Exception\RuntimeException(code: 0): The process has been signaled with signal "15". at /usr/www/users/gophpj/crm/overrides/symfony/process/Process.php:434)

When I receive the typical message with: "Find my comments under your questions",  I scroll down but copy of my message with the new comments inserted in the reply are not visible.

Also, when an email have more than 4 people CC'ed, mail gets cutted too.

Is there any posibility to add a "VIEW FULL MESSAGE" feature? In case the cutting of previous emails has gone wrong.

Thanks

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#some-emails-are-empty-or-truncated-in-freescout
