### ISSUE TITLE
LDAP Active Directory, 'automatic' disabling users

### ISSUE THREAD

**Issue by TecnotramitGestion** [freescout-helpdesk/freescout#3916]
PHP version:  8.2
FreeScout version: 1.8
Database: MySQL
Are you using CloudFlare: No

Hi,

I wonder if it would be possible to automatically disable deactivated AD users. I mean, if I disable the users' account in AD, I would to see it also "disabled" in the FreeScout user panel. (Although I know that deactivated AD users can't login in FreeScout the same moment we "cancel" the account...)

Actually I have this filter to import only enabled users
''dc=company,dc=com(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))''

So, I thought the automatic process (ran at night or out-of-work hours) could be:
1. Deactivate ALL LDAP accounts in FreeScout
2. Re-enable ONLY LDAP accounts that are imported and create new if they are not already in FreeScout

Best regards

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
