### ISSUE TITLE
Update to the wiki: Microsoft Exchange Online Kiosk license

### ISSUE THREAD

**Issue by christiaangoossens** [freescout-helpdesk/freescout#3919]
According to https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth, you would need a "Business Basic license" for the mailbox. These licenses cost 5,60 euros per user per month.

You can however also use any Exchange Online plan instead, with the cheapest option being the unadvertised Exchange Online Kiosk plan, that only costs 1.87 euros per month per user. If you can live with a 2 GB limit for the mailbox linked to Freescout, this would be a great option. You can add that plan at https://admin.microsoft.com. Then, you would convert the shared mailbox into a user mailbox instead with that Kiosk plan.

Could the wiki be updated to include the detail that you can use Exchange Online Kiosk or Exchange Online (Plan 1) instead of Microsoft 365 licenses to save some money?

_I have tested the Kiosk plan and it works well._

**Comment by freescout-helpdesk** [comment]
Thanks.  We've added the info to https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth

**Comment by etranger7** [comment]
Hi, @christiaangoossens , how did you get the kiosk license to work?  
When I went through the instructions I ran into the same problem defined here  
#2264 

Despite connecting with the same user as the mailbox owner, I kept having the same problem until I changed Kiosk license to MS 365 Business Classic. Then it worked just fine.  
  
Here is the screenshot and the error that comes up after I try to turn IMAP on and save the settings using the Kiosk license.  
 

![](https://github.com/freescout-helpdesk/freescout/assets/5760298/3b588898-ed99-45ab-bfa7-67b8e3f4b720)

**Comment by christiaangoossens** [comment]
@etranger7 Okay, two things:

1. For sure, the cheapest plan that just includes IMAP out of the box, no tricks, even according to MS, is still Exchange Online (plan 1), which is still a lot cheaper than MS 365 Business Classic. Therefore, no need to have that one.

2. For what I did: I created a shared mailbox first, then converted that one to a user mailbox. At that point, all of these checkboxes were already checked, but no licence was assigned. After that, I assigned the Kiosk one, and IMAP remained enabled. I now understand from your post that you cannot do this after assigning the licence, is that correct?

My theory would thus be that:

- Exchange Online Kiosk can be used, as long as you have IMAP enabled prior to assigning licence, possibly by assigning a different licence first, or converting it from a shared mailbox
- Exchange Online Plan 1 or 2 would also work without this trick, but do not give you M365 features, just Exchange. Not that you need it if you want only a mailbox for Freescout
- M365 Business Basic would be the cheapest licence if you need full Microsoft 365, not just Exchange

@freescout-helpdesk If this is correct, it would help to update the wiki page to just:

_If you need to connect a shared Microsoft 365 mailbox to FreeScout you need to apply at least a Exchange Online (plan 1) or M365 Business Basic licence to the shared Microsoft 365 mailbox (read more [here](https://github.com/freescout-helpdesk/freescout/issues/3919))._

**Comment by etranger7** [comment]
@christiaangoossens Thank you for the detailed notes.

I checked if going back to Kiosk after enabling IMAP under MS 365 Business Classic for that same account would work but it didn't. As soon as the license changes to Kiosk, the IMAP option automatically gets disabled and trying to enable it causes an error.

I bought an Exchange Online Plan1 license and that works great, thank you for the tip.

I'm not sure if creating a shared mailbox and then converting it to Kiosk still works. If and when I create an additional mailbox, I might try that first.

My advice would be to change the setup instructions to trying Exchange Plan 1 if Kiosk fails. If you'd like me to revise those, please feel free to let me know.

**Comment by freescout-help** [comment]
> With the Kiosk License on Microsoft Exchange IMAP is not supported (anymore). Minimum License required is Exchange Online Plan 1.

https://github.com/freescout-help-desk/freescout/issues/3847#issuecomment-2563946650

**Comment by rinshadka** [comment]
Hi @etranger7 , I am having  a shared mailbox and able to configure the same in Thunderbird email client using a licensed member accessible to that shared mailbox account.  But the mailbox in not a able to configure for sending email out from freescout.  getting authentication error.

<img width="276" height="481" alt="Image" src="https://github.com/user-attachments/assets/2f975f7a-915a-4805-b2b8-6ca4081549e1" />

I have used poweshell to enable SMTP_AUTH for shared mailbox ID and account using to authenticate having accessible this share.

**Comment by etranger7** [comment]
@rinshadka as mentioned above, I was only able to get this working by assigning an Exchange Online Plan 1 license, directly to the user and not using a shared mailbox. 
So the idea isn't using a licensed user to access the shared mailbox, it's to create a standalone user with a license. I hope that clarifies things.
