### ISSUE TITLE
Custom folders

### ISSUE THREAD

**Issue by hee-jee** [freescout-helpdesk/freescout#392]
It would be great to let create custom folders on the left side menu.
I see they are hard-coded there: https://github.com/freescout-helpdesk/freescout/blob/master/app/Folder.php

Thank you.

**Comment by freescout-helpdesk** [comment]
It will be possible soon, but extra folders will be just like a tool for quick access to conversations. Conversations will be present in one of the main folders (Unassigned, Mine, Assigned, Closed).

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/custom-folders/
