### ISSUE TITLE
Contacts (customers) shared

### ISSUE THREAD

**Issue by TecnotramitGestion** [freescout-helpdesk/freescout#3921]
PHP version: 8.2
FreeScout version: 1.8.128
Database: MySQL
Are you using CloudFlare: Yes

Hi, we've several mailboxes configured. When we create new "email" to send, we get the address book with all the "customers". Please, could it be possible to link each customer with the mailbox in which he has started the conversation? It's important in order to maintain privacy between departments (maiboxes).

Best Regards,

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ

**Comment by TecnotramitGestion** [comment]
Thanks
! I missed [it](https://github.com/freescout-helpdesk/freescout/wiki/FAQ#is-it-possible-to-have-separate-contactscustomers-per-mailbox). For us it turns to be useless as we must isolate each mailbox (hundreds of it) and configure modules for each instance.

It's a must-have characteristic in order to accomplish GDPR for example.
