### ISSUE TITLE
To or CC only work for customer contacts

### ISSUE THREAD

**Issue by TecnotramitGestion** [freescout-helpdesk/freescout#3922]
PHP version: 8.2
FreeScout version: 1.8.128
Database: MySQL
Are you using CloudFlare: No

Hi,

The "To:" or "Cc:" fields only do a search in "customer" database. But as we have many agents, sometimes we will to re-adress a ticket via "redirect email", it would be useful to get also accounts via a LDAP search to external database.

Best regars,

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no plans to implement it.
