### ISSUE TITLE
Cannot access  system option

### ISSUE THREAD

**Issue by yassar-moonyadza** [freescout-helpdesk/freescout#3924]
Hello everyone,

Hope you are doing good. I am really enjoying the app since I have installed it.

But since this morning I have an issue. When I try to go to "System" I have an error page. I checked the log there is nothing that can Help me. Everything is working well except  what I discribed.

Could you please help

Thanks
![Error 1](https://github.com/freescout-helpdesk/freescout/assets/154607841/eae7a1cd-a064-456a-b4d9-28b632fb065f)
![Error 2](https://github.com/freescout-helpdesk/freescout/assets/154607841/660185ec-9b50-480d-9aad-9c269a451ce2)

**Comment by mkko2600** [comment]
I have the same issue. Started out of nowhere with 1.8.128

PHP version: 8.2
FreeScout version: 1.8.128
Database: MySQL
Are you using CloudFlare: No

**Comment by yassar-moonyadza** [comment]
Do someone has an idea on how to fix this ?

**Comment by iom-atan** [comment]
In my case, I updated the allowed memory size further, which allowed the logs page to load the errors. When trying to access the System page, I was then able to see the actual error it was encountering, and was able to rectify it afterwards.

**Comment by freescout-helpdesk** [comment]
It can be also related to https://github.com/freescout-helpdesk/freescout/issues/3970

**Comment by borgarlie** [comment]
We have recently experienced a similar issue. The system page takes a long time to load, and sometimes it just fails to load with timeout.

We had a failed send in there when that happened. Trying to look at the details also failed. Just loading for a long time then a blank box. Retrying did not fix it. But deleting the failed job made the system page load normally again.

<img width="1357" alt="Screenshot 2024-04-18 at 11 36 12" src="https://github.com/freescout-helpdesk/freescout/assets/5425754/fc933779-f70e-4901-90c8-5fe72228695d">
