### ISSUE TITLE
Can we remove the # from the subject line as well as disable replying from email?

### ISSUE THREAD

**Issue by xboxhaxorz** [freescout-helpdesk/freescout#3927]
I couldnt find the option to remove the # from the email subject line and i couldnt find the option to disable reply from email to force users to reply directly from freescout portal

Is it possible to do both of these?

**Comment by freescout-helpdesk** [comment]
> I couldnt find the option to remove the # from the email subject line

Can you send a screenshot to understand what you are talking about.

>  option to disable reply from email to force users to reply directly from freescout portal

There is no such feature for now.

**Comment by xboxhaxorz** [comment]
> > I couldnt find the option to remove the # from the email subject line
> 
> Can you send a screenshot to understand what you are talking about.
> 
> > option to disable reply from email to force users to reply directly from freescout portal
> 
> There is no such feature for now.

Oh never got the email notification for this github comment, but anyways in the left corner of this screenshot https://imgur.com/fKtDmz7 is the # we want to remove from the subject line

I know there is a module that includes the # in the subject line, we dont have that, we just have the basic freescout

In our non profit we would use freescout in conjunction with gmail to respond to volunteer application submissions so having the ticket # in the email replies in gmail kind of ruins things for us

**Comment by freescout-helpdesk** [comment]
You are talking about the subject of email notifications sent to support agents.
There is no such feature for now. 
Feel free to submit a feature request: https://freescout.net/request-feature/
