### ISSUE TITLE
Issue with the change of the time

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3928]
PHP version:  8.3.4
FreeScout version: 1.8.130
Database: MySQL
Are you using CloudFlare: No

Hi from Italy, Turin!
The time has been changed from GMT +1 to GMT +2

I dont need to do any action on my server because the SSH command data gives the right time.
Also logging in Wordpress show the right time.

In Freescout the time is wrong and seems I need fix manually but even switching to GMT +2 show the wrong time in /system/status

Current time is 08:33 of the morning and Freescout still show 7:33

![immagine](https://github.com/freescout-helpdesk/freescout/assets/5006150/70768fe0-d1d0-4896-b2c5-124f3aa568c4)

Even in email fetching the time is wrong.

**Comment by PeopleInside** [comment]
Seems I not only need fix the time from the FreeScout settings on app-settings but even on my operator profile users/profile.
In this case now the time is showed correctly.

Is normal that I had no issue with time in my server and on Wordpress but I need fix manually in FreeScout?

Thanks.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#timezone-setting-does-not-work

**Comment by PeopleInside** [comment]
Thanks for the quick reply.

**Comment by PeopleInside** [comment]
In any case seems Freescout is the only app where I need fix the time. Wordpress and server time has been update automatically while FreeScout need a manual intervention.
