### ISSUE TITLE
Per-KB color

### ISSUE THREAD

**Issue by cweagans** [freescout-helpdesk/freescout#3929]
Hi there! I'm using the knowledge base and customization modules, but it seems like things can't be customized on a per-KB basis (which I think you confirmed in https://github.com/freescout-helpdesk/freescout/issues/3252).

I see that there is a color selector for the help widget already in the KB settings. Would you accept a patch to the KB module to just use that color for the entire KB instead of just the widget?

**Comment by freescout-helpdesk** [comment]
Feel free to send it to us (support@freescout.net) - we'll take a look at it.
