### ISSUE TITLE
Row size too large

### ISSUE THREAD

**Issue by bencgreen** [freescout-helpdesk/freescout#393]
While upgrading to 1.3.15 I got the following error in Connection.php line 664:

`SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: alter table 'mailboxes' add 'before_reply' text null)`

And again in PDOStatement.php line 107 and PDOStatement.php line 105.

Everything seems to be ok at the moment, except I can't set the email header 'please reply above this line' option in the mailbox settings.

Not sure if this is something to do with my setup - MariaDB 10.4 - or not?  Table type is InnoDB, with character set utf8mb4, collation utf8mb4_unicode_ci.

**Comment by freescout-helpdesk** [comment]
https://stackoverflow.com/a/25373052
