### ISSUE TITLE
File upload in End-User Portal Module does not work

### ISSUE THREAD

**Issue by sydios** [freescout-helpdesk/freescout#3930]
I have the latest version 1.0.82 installed. But on the "Submit a Ticket" form the "add attachments" button does not work. 
Any ideas?

![image](https://github.com/freescout-helpdesk/freescout/assets/7102852/521f8200-12e0-4172-8688-1719f936d341)

**Comment by sydios** [comment]
It works on your demo site. 
MY form is here: https://podmkr.support/help/4088020982

**Comment by freescout-helpdesk** [comment]
According to the error message in the browser console something is messed up with your FreeScout domain (APP_URL):

![2024-04-02_08-15-33](https://github.com/freescout-helpdesk/freescout/assets/40499291/104a70e7-4360-4ea4-a52e-0d79e4ec8de3)

Try to clear FreeScout cache. If it does not help - find someone who can investigate it on your server.
