### ISSUE TITLE
Fetching IMAP folders leaves out `INBOX.` prefix

### ISSUE THREAD

**Issue by ohader** [freescout-helpdesk/freescout#3933]
### Description

<img width="560" alt="Screenshot 2024-04-01 at 13 37 27" src="https://github.com/freescout-helpdesk/freescout/assets/402145/783586a4-85e5-4954-b124-2a6ca1d718f5">

The screenshot shows the (reduced) result after clicking "Get folders". The folder `Archive` actually should be `INBOX.Archive`.

As a result, the mail fetch command would fail with an error message like this:

```
[2024-04-01 13:36:34] Folder: Archive
[2024-04-01 13:36:34] Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).
[2024-04-01 13:36:34] Folder: Archive; Error: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).
[2024-04-01 13:36:34] Fetched: 0
```

Manually configuring `INBOX.Archive` solves this (like shown in the screenshot below):

<img width="545" alt="Screenshot 2024-04-01 at 13 38 44" src="https://github.com/freescout-helpdesk/freescout/assets/402145/caa14c85-fc2e-471b-bea7-5ea4038772d5">

### Additional notes

I did not debug yet, whether this has been introduced by the recent changes in 01dec5160e4917fff873e0e301d3818ff1330b5b or whether it existed before.

I guess(!) that the property `$imap_folder->full_name` (or its fallbacks) should be used instead of just `$imap_folder->name`. The current source code seems to lack a prefix of the parent folder name when being invoked recursively in `i(n)terateFolders()`...

https://github.com/freescout-helpdesk/freescout/blob/01dec5160e4917fff873e0e301d3818ff1330b5b/app/Http/Controllers/MailboxesController.php#L825-L829

### Environment

PHP version: 8.2
FreeScout version: 1.8.130
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
We've intentionally excluded folders with `INBOX.` prefix as some users were receiving errors when fetching from such folders. Ok, we'll return them back.
