### ISSUE TITLE
Message having attachment is incorrectly stored to IMAP sent folder

### ISSUE THREAD

**Issue by ohader** [freescout-helpdesk/freescout#3934]
### Description

The message that is stored to the IMAP sent folder seems to be corrupted in case at least one file has been attached. I did not experience problems in case there weren't any attachments. However, the message delivered to the recipient seems to be fine.

The faulty line seems to be at the mime-subtype `alternative`, which refers to multiple different representations of the same content. However, when having an attachment, that particular section probably needs to be `multipart/mixed` (SwiftMailer seems to sanitize that flaw when actually sending out mails):

```
Content-Type: MULTIPART/alternative; BOUNDARY="8323329-464180355-1711995865=:3091887"
```

#### Message stored in IMAP sent folder (seems to be broken ❌)

```
Date: Mon, 01 Apr 2024 20:24:25 +0200
From: "| IN.DIE.musik e.V." <redacted@example.org>
Subject: [#325] Test
To: oliver.hader@typo3.org
Message-ID: reply-634-fbef42d0a86e7322@example.org
MIME-Version: 1.0
Content-Type: MULTIPART/alternative; BOUNDARY="8323329-464180355-1711995865=:3091887"

--8323329-464180355-1711995865=:3091887
Content-Type: TEXT/html; CHARSET=utf-8

<div>redacted</div>
--8323329-464180355-1711995865=:3091887
Content-Type: TEXT/octet-stream; name=anyfile.md
Content-Transfer-Encoding: BASE64
Content-Description: 
Content-Disposition: attachment; filename=anyfile.md

IyBBbnkgRmlsZQouLi4K
--8323329-464180355-1711995865=:3091887--
```

#### Message delivered to recipient (seems to be fine ✅)

```
Return-Path: <redacted@example.org>
Delivered-To: oliver.hader@typo3.org
X-Fuglu-Spamstatus: NO
X-Fuglu-Suspect: f51bcda45d60499cbef70a565ee93bf3

Message-ID: <reply-634-fbef42d0a86e7322@example.org>
Date: Mon, 01 Apr 2024 20:24:24 +0200
Subject: [#325] Test
From: "Oliver Hader | IN.DIE.musik e.V." <redacted@example.org>
To: Oliver Hader <oliver.hader@typo3.org>
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="_=_swift_1711995864_cc7a84166e2435835a9cfd76268b25e3_=_"
X-FreeScout-Mail-Type: customer.message
X-Authenticated-Sender: redacted@example.org
X-Virus-Scanned: Clear (ClamAV 0.103.10/27232/Mon Apr  1 10:23:51 2024)
X-Rspamd-Queue-Id: A8CAA141EE82
X-Rspamd-Pre-Result: action=no action;
	module=Unknown lua;
	ip matched with forward hosts
X-Spamd-Result: default: False [0.00 / 15.00]


--_=_swift_1711995864_cc7a84166e2435835a9cfd76268b25e3_=_
Content-Type: multipart/alternative;
 boundary="_=_swift_1711995864_604422d5f501caa01fcf727cd484f653_=_"


--_=_swift_1711995864_604422d5f501caa01fcf727cd484f653_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

redacted

--_=_swift_1711995864_604422d5f501caa01fcf727cd484f653_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<div>redacted</div>
--_=_swift_1711995864_604422d5f501caa01fcf727cd484f653_=_--


--_=_swift_1711995864_cc7a84166e2435835a9cfd76268b25e3_=_
Content-Type: application/octet-stream; name=anyfile.md
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=anyfile.md

IyBBbnkgRmlsZQouLi4K

--_=_swift_1711995864_cc7a84166e2435835a9cfd76268b25e3_=_--
```

### Environment

PHP version: 8.2
FreeScout version: 1.8.130
Database: MySQL
Are you using CloudFlare: No

**Comment by ohader** [comment]
I'm wondering whether adjusting this part from `alternative` to `mixed` is enough:

https://github.com/freescout-helpdesk/freescout/blob/9b359abcce2557552bf18d4c11da51feca426bd3/app/Jobs/SendReplyToCustomer.php#L402-L407

Besides that, I'm also wondering whether a prepared SwiftMessage (before being queued for delivery) could be appended to the IMAP folder for sent messages...

**Comment by freescout-helpdesk** [comment]
> The message that is stored to the IMAP sent folder seems to be corrupted in case at least one file has been attached.

How do you determine that the email is corrupted? You can't open it in the Sent folder of your mail client?

**Comment by ohader** [comment]
Correct. I was not able to show the whole message in the `sent` folder neither with Apple Mail nor with Outlook (on macOS, did not test Windows yet) - it just displayed the attachment part, but omitted the text part.

**Comment by freescout-helpdesk** [comment]
Does it happen with all attachments or just some of them? Can you send a sample attachment file to reproduce the issue?

**Comment by freescout-helpdesk** [comment]
> Besides that, I'm also wondering whether a prepared SwiftMessage (before being queued for delivery) could be appended to the IMAP folder for sent messages...

Unfortunately not. Emails are send and stored in the Sent folder using different libraries.

You can try to manually change `mime-subtype` in /app/Jobs/SendReplyToCustomer.php (line 405), clear cache and check how it works: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php#L405

**Comment by ohader** [comment]
> You can try to manually change `mime-subtype` in /app/Jobs/SendReplyToCustomer.php (line 405), clear cache and check how it works: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php#L405

Yepp, that worked, having `MULTIPART/mixed` in the message.
