### ISSUE TITLE
 Error attaching files

### ISSUE THREAD

**Issue by carlozleite** [freescout-helpdesk/freescout#3939]
Hello, I noticed that adding attachments was not working, generating the following error:

`message": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: \"eyJpdiI6Ilc0cDlCR3pZTHp3cDRQVWtUcytGUGc9PSIsInZhbHVlIjoieHEwTkpPNkQyZWRIVEZQVnowR2g1UT09IiwibWFjIjoiMjYxMTcwNWFlOWE4YTM5NDRlMjQzZGFkNGQwMDMzZTVjZmVhMmY5NzZlZDhkYzAyMzZkNmUwMTcxNzFiN2JjMCJ9\" (SQL: select \"size\" from \"attachments\" where \"id\" in (eyJpdiI6Ilc0cDlCR3pZTHp3cDRQVWtUcytGUGc9PSIsInZhbHVlIjoieHEwTkpPNkQyZWRIVEZQVnowR2g1UT09IiwibWFjIjoiMjYxMTcwNWFlOWE4YTM5NDRlMjQzZGFkNGQwMDMzZTVjZmVhMmY5NzZlZDhkYzAyMzZkNmUwMTcxNzFiN2JjMCJ9))",`

Looking at the ConversationsController.php controller, I noticed that there is a select for an array of attachments_ids in the attachments table where the ID column is INT and sequential, very different from the sequence of characters sent in the payload:

```
                if (!$response['msg']) {
                    $max_message_size = (int)config('app.max_message_size');
                    if ($max_message_size) {
                        // Todo: take into account conversation history.
                        $message_size = mb_strlen($body, '8bit');

                        // Calculate attachments size.
                        $attachments_ids = array_merge($request->attachments ?? [], $request->embeds ?? []);

                        if (count($attachments_ids)) {
                            $attachments_to_check = Attachment::select('size')->whereIn('id', $attachments_ids)->get();
                            foreach ($attachments_to_check as $attachment) {
                                $message_size += (int)$attachment->size;
                            }
                        }

                        if ($message_size > $max_message_size*1024*1024) {
                            $response['msg'] = __('Message is too large — :info. Please shorten your message or remove some attachments.', ['info' => __('Max. Message Size').': '.$max_message_size.' MB']);
                        }
                    }
                }
                
```

I did a test and commented the IF between lines 834 and 839 and the attachment worked correctly.

REF:  https://github.com/freescout-helpdesk/freescout/blob/2c39ba9d9e7c506b52b5b84284b3bec1d899cb74/app/Http/Controllers/ConversationsController.php#L834C1-L839C26

I thought there was an error with the payload but on the demo site the payload is the same and the attachment works.
    
I'm opening this issue because I don't understand what's really happening.

Best regards

PHP version: 8.2
FreeScout version: 1.8.130
Database: PostgreSQL
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
