### ISSUE TITLE
Open source modules?

### ISSUE THREAD

**Issue by Perflyst** [freescout-helpdesk/freescout#394]
I can understand that you provide paid modules to keep the project alive. But basic things like LDAP are often needed and if I want to stay open source only it is not possible to use it.

Is there any chance to get the modules open?

**Comment by freescout-helpdesk** [comment]
All modules are open source and AGPL-3.0.

**Comment by Perflyst** [comment]
Maybe I am blind but where is the source code?

**Comment by freescout-helpdesk** [comment]
You get it after downloading modules. You probably have common misunderstanding of what open source is and how it works, thinking that open source means free. See https://opensource.com/business/12/7/four-insights-selling-and-marketing-open-source-software

**Comment by Perflyst** [comment]
I am completely fine with the business model. I though these are closed source extensions and I was not aware that you get the source code after paying.
