### ISSUE TITLE
Emails to multiple mailboxes is not always copied to all mailboxes

### ISSUE THREAD

**Issue by borgarlie** [freescout-helpdesk/freescout#3941]
Hi,

We are having some issues with emails that should go to multiple recipients. They sometimes end up not getting copied into every relevant mailbox. So e.g. a mail that should be sent to mailbox1, mailbox2 and mailbox3, sometimes only end up in 1 or 2 of those mailboxes.

We have checked on the outlook side and everything seems fine there. We also checked in the database, and the "to" and "cc" fields are there, with all recipients in them, as expected. It seems quite arbitrary, as sometimes it all works. I can do the same experiment multiple times and get different results, with no errors in logs or anything that seem relevant to explain the behaviour. This is a quite critical and serious issue as a lot of important information gets lost because of this. And it is quite hard to track and find out when it happens.

When doing experiments, we see that the fetching jobs are completing as expected, and usually test emails sent to multiple recipients end up where they should. But sporadically, with no trace, they don't. I haven't been able to find any pattern explaining the difference in when it works vs. when it does not work. One thing to note is that the email always show up in at least one mailbox. So it seems to be something strange with the extra_import and copying process.

We currently have 74 mailboxes, and quite a lot of emails are sent to ~half of these, or in some cases all. So far we are 224929 threads in the database and 208579 conversations (in case those numbers are interesting).

Any help greatly appreciated!

Versions:
PHP: 8.2.16
Freescout version: 1.8.122
Database: PostgreSQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Try to update FreeScout to the latest version. There were some fetching related fixes in https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.128

**Comment by borgarlie** [comment]
The fix for long running fetch jobs has already been applied to our instance.
"Fixed long running fetch commands being killed (https://github.com/freescout-helpdesk/freescout/issues/3844)"

Are there other relevant changes?

We will try to update regardless, but I didn't see any other relevant changes on first look.

**Comment by borgarlie** [comment]
Ideally duplicating the message to all mailboxes should be an atomic operation. And if it fails before it is stored in all mailboxes it should rollback, so that it may try again later. Otherwise there will always be the potential to get into an unrecoverable state.

**Comment by borgarlie** [comment]
We have thought about 3 potential ways to fix the problem:

1) Remove extra_import, and rather have a unique constraint that is per message_id and mailbox. This was the message can be processed per mailbox instead of in bulk.
2) Process extra_import immediately (add to other mailboxes at once instead of waiting for it), and add to the original + all the extra mailboxes in a transaction, so that it gets rolled back if something crashes along the way. Commit when all are added.
3) Store extra_import outside of memory, so that the process can be continued if it doesn't complete. This means signing off that something is done (or removing from the list).

We are not PHP developers and don't have any laravel experience, and are also quite new to freescout. So perhaps someone here have opinions on which is the better approach. (1) sounds like it would reduce complexity quite a lot, and seems favorable. (2) also seems to be a good approach. I don't think (3) is that viable.

The hardest part about (1) is how to do the migration. How do we make sure that we don't get duplicates if we import mails far back in time.

**Comment by freescout-helpdesk** [comment]
You can try to add some debugging to figure out what happens: https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by borgarlie** [comment]
Hi,

I would not say that this is really closed. It is a real issue. In the current state of the code, it is quite likely to get in a unrecoverable state where you need to manually clean things up if you want a consistent database.

It is quite easy to reproduce the issue as well.

1) Change the fetch email job so that it crashes before it starts processing the extra_import list.
2) Send an email that is supposed to go to 2 mailboxes.
3) The mail gets processed and stored in db for one of the mailboxes.
4) The job crashes
5) On next job run, the mail will be seen as a duplicate and never get stored in the second mailbox.
At this point we are in a state where the system can not fix itself.

I don't think it is good enough to "fix the cause of crash". Not at all. There will always be some reason you can not 100% account for.

We have fixed this in our instance now, by removing all of the extra_import logic, and postfix the message_id upon processing with the mailbox id. e.g. `$message_id = $message_id.'::'.$mailbox->id;`. In addition, we check for duplicates with the old id and the old id generated during extra_import to make sure we are backwards compatible in case we ever want to import mail back in time.

Note: We could have used the old extra_import MailHelper::generateMessageId as the message_id, but it is a bit more cryptic to use for debugging etc imo. It is nice to e.g. be able to check how many threads in the db has the same prefix.

Our solution might not be optimal. But it works. It works because it makes sure that there is no delayed batched processing. Every email to each mailbox is processed and stored individually, and there is no batched work that is dependant on previous information. So we don't need to use transactions or anything similar.

As I outlined in a previous message here, there are other ways to solve it, but I think this way is more clean. It also simplifies the code a lot.

I would highly recommend looking into fixing this properly (but make sure that it is in a backward compatible way). I am very surprised not more are having this issue. Perhaps it is just not that common to have many mailboxes and often having mail sent to multiple mailboxes at once.

**Comment by freescout-helpdesk** [comment]
We've made fetching emails sent to multiple mailboxes a bit more atomic. Now extra emails are fetched right after each mailbox instead of fetching them after all the mailboxes. You can check it in the `master` branch.

**Comment by borgarlie** [comment]
It doesn't solve the entire problem, but it does make it a lot less likely to occur. So it is at least a big improvement.
I would still suggest looking into a proper fix down the line. But hard for me to say how much of a priority that should be of course. We have a solution in our instance already, which is outlined above, so I suppose if others find this required, they can try to follow that approach as an alternative solution.
