### ISSUE TITLE
Error sending notification email to user: Call to a member function getFullName() on null

### ISSUE THREAD

**Issue by AlexXF73** [freescout-helpdesk/freescout#3942]
PHP version: 7.4.3-fpm
FreeScout version: 1.8.131
Database: MySQL 
Are you using CloudFlare:  No

`Call to a member function getFullName() on null (View: /home/support/.www/resources/views/emails/user/notification.blade.php) {"exception":"[object] (ErrorException(code: 0): Call to a member function getFullName() on null (View: /home/support/.www/resources/views/emails/user/notification.blade.php) at /home/support/.www/storage/framework/views/4e07df108944f431eff3917d25ac0024ec6614b3.php:82, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getFullName() on null at /home/support/.www/storage/framework/views/4e07df108944f431eff3917d25ac0024ec6614b3.php:82)
[stacktrace]
#0 /home/support/.www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(47): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /home/support/.www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /home/support/.www/overrides/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /home/support/.www/overrides/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /home/support/.www/overrides/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(328): Illuminate\\View\\View->render()
#6 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(301): Illuminate\\Mail\\Mailer->renderView()
#7 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(218): Illuminate\\Mail\\Mailer->addContent()
#8 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send()
#9 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send()
#10 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable()
#11 /home/support/.www/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send()
#12 /home/support/.www/app/Jobs/SendNotificationToUsers.php(148): Illuminate\\Mail\\PendingMail->send()
#13 [internal function]: App\\Jobs\\SendNotificationToUsers->handle()
#14 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#15 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#18 /home/support/.www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#19 /home/support/.www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#20 /home/support/.www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/support/.www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#22 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#23 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#24 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#26 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#27 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#28 /home/support/.www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#29 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#30 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#31 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /home/support/.www/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#34 /home/support/.www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#35 /home/support/.www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#36 /home/support/.www/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#37 /home/support/.www/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#38 /home/support/.www/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /home/support/.www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#40 /home/support/.www/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#41 /home/support/.www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#42 /home/support/.www/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#43 {main}
"}`

What it can be related? Looks like there is no object to send notification?

**Comment by AlexXF73** [comment]
Due to some investigation i've found that error connected to the tickets that marked as SPAM by helpdesk

**Comment by freescout-helpdesk** [comment]
Maybe you deleted a customer of that conversation?

**Comment by AlexXF73** [comment]
Looks like there is a conflict between Workflow module and SPAM engine.

Message has been marked as SPAM automatically, but due to Workflow rules it has been added to notification queue.

**Comment by freescout-helpdesk** [comment]
Can you write a step-by-step instruction on how to reproduce the issue?

**Comment by AlexXF73** [comment]
Add Workflow Rule:

Conditions: New/Reply/Moved -> New conversation
Action: Send user notification -> any user

If message will be auto-marked as SPAM by FreeScout anti-spam filter, then you'll get that error in log

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by AlexXF73** [comment]
Thank you!
