### ISSUE TITLE
Issues with Incorrect Report Values in Reports Module

### ISSUE THREAD

**Issue by darkp-team** [freescout-helpdesk/freescout#3943]
Hello!
I'm experiencing a problem with the Reports Module where the reports are not displaying correctly, and the values significantly differ across different selected periods. The only accurate report I've received was for a 2-day period. However, when selecting periods longer than 2 days, the values change unpredictably.

For instance, for today, April 6th, we received 9 tickets. Yet, when generating a report for the week, it shows 14 tickets, even though the earlier days of the week are almost at zero, which is inconsistent with our average daily ticket volume of 10-20.

This discrepancy in report values makes it challenging to accurately track our customer service performance and needs. Could you provide any insights or solutions to ensure the Reports Module reflects accurate information across all selected periods? Is there a specific setting or update I might be missing that could resolve this issue?

Thank you for your assistance and looking forward to any advice you can offer.

2-Days report
![2days](https://github.com/freescout-helpdesk/freescout/assets/63156637/64d2b530-76be-4580-981c-778e67041a67)

3-Days report
![3days](https://github.com/freescout-helpdesk/freescout/assets/63156637/b3a2d880-a887-4c00-8046-3634483c9ec2)

Weekly report
![week](https://github.com/freescout-helpdesk/freescout/assets/63156637/6efe7d5d-5904-4254-819d-6f8f5e6abae4)

**Comment by freescout-helpdesk** [comment]
The only way to check is for someone to go to your database and check conversations there.

**Comment by darkp-team** [comment]
Thank you for answer! Could you, please, suggest somebody help with this issue and also with my previous one, i think they are connected? Thanks in advance!

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
