### ISSUE TITLE
Access Issue with Fresscout

### ISSUE THREAD

**Issue by marwanzz1** [freescout-helpdesk/freescout#3946]
Hello,

 

Allow me to introduce myself, I am Marwan, Customer Success Manager at SKEZI. I'm reaching out to you today because we've been experiencing difficulties accessing Fresscout since this morning. It appears that the site is currently inaccessible. Given the importance of this platform for our operations, it's crucial that we regain access as soon as possible. We would greatly appreciate it if you could update us at your earliest convenience.

 

Looking forward to your response,

**Comment by freescout-helpdesk** [comment]
Are you talking about https://freescout.net website? Or you are talking about your FreeScout instance managed by your admins?

**Comment by marwanzz1** [comment]
yes

**Comment by marwanzz1** [comment]
![image](https://github.com/freescout-helpdesk/freescout/assets/166377399/7242e38e-4eef-492f-bb92-9226be971a60)

**Comment by freescout-helpdesk** [comment]
You need to contact your admins who installed FreeScout for you and who maintain it on your server.
