### ISSUE TITLE
Support multiple status filter in List conversations API

### ISSUE THREAD

**Issue by anjan-rpf** [freescout-helpdesk/freescout#3947]
Current Support:
We can filter conversations with a single status 
`https://demo.freescout.net/api/conversations?status=active`

Needed Support:
Filter conversations by multiple statuses
`https://demo.freescout.net/api/conversations?status=active,pending` 
currently the above returns conversations with all statuses ( active, pending, closed, spam )

**Comment by freescout-helpdesk** [comment]
Implemented in API & Webhooks Module v1.0.77
