### ISSUE TITLE
Attachments cloned after discard forwarding draft

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3949]
https://github.com/freescout-helpdesk/freescout/assets/12407767/410e1e26-2f26-48b2-9b0b-b2565a85bfa2

edit:

It seems like the issue also occurs when the conversation gets forwarded normally. The attachment is **not** present in the retrieved email.

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by sofl88** [comment]
I tried this in my local test system and it seems like this fixed the cloning issue but not the fact that the attachment is not sent at all.

**Comment by freescout-helpdesk** [comment]
There are also other commits in the master branch.
