### ISSUE TITLE
Discard a draft while its edited by someone else, causes log spam

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3951]
As described, if someone discards the draft from another editor, this editor gets a error message spam of "Lost internet connection" and the error log gets filled with a php error.

`Attempt to assign property \"type\" on null at /www/htdocs/.../app/Http/Controllers/ConversationsController.php:1486`

https://github.com/freescout-helpdesk/freescout/blob/ad76e2d3cecd6290e37b3cdf3d669b5e6afca036/app/Http/Controllers/ConversationsController.php#L1486

I would appreciate if this could be prevented somehow

Thanks in advance

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.

**Comment by sofl88** [comment]
https://github.com/freescout-helpdesk/freescout/assets/12407767/260419c1-05c6-44ed-8168-a683e9c2b6cc
