### ISSUE TITLE
Team folder order

### ISSUE THREAD

**Issue by Rezolve-IT** [freescout-helpdesk/freescout#3952]
Hi Freescout team, 

How do change the order of Team folders? I cant seem to find any way of doing it via the UI? I want to move the ones with the cloud icon to the top and the crosses to the bottom. Is this possible?

![image](https://github.com/freescout-helpdesk/freescout/assets/159972083/cc779f18-d032-49f3-8970-9f7ee4884dcc)

Regards,

Emil Badenhorst

**Comment by freescout-helpdesk** [comment]
There is no such feature for now. 
Feel free to submit a feature request: https://freescout.net/request-feature/
