### ISSUE TITLE
Embed the submit help form into our webflow site

### ISSUE THREAD

**Issue by corptek** [freescout-helpdesk/freescout#3953]
We are currently using Webflow for our main website and just wondering if we are able to insert the submit a ticket as a snippet into our contact us page? So that all support enquires go to freescout? We are looking to buy the end user module.

https://demo.freescout.net/help/1321731726

![image](https://github.com/freescout-helpdesk/freescout/assets/94516284/a41ce6ca-d9e9-4fdd-b963-94106d6dd4b0)

Above is the example of what I would like to insert something like this:

**Comment by freescout-helpdesk** [comment]
> Contact form can be also embedded on the website via iframe – embedding URL can be obtained via “Open in New Window” link.

https://freescout.net/module/end-user-portal/
