### ISSUE TITLE
Multiple responsible customers on the same ticket

### ISSUE THREAD

**Issue by zuevav** [freescout-helpdesk/freescout#3954]
How to make several clients manage the same task in the user portal. Now, when a task is created, only one client is assigned and others in the copy (CC), the clients in the copy are responsible for the task, but they do not have the opportunity to see this task in the client portal and cannot log in to it if they do not have other tasks for which they are responsible. How to assign and enable to see tasks one task for several clients.

**Comment by ilyakonovalenko** [comment]
There is no way to assign the same ticket to multiple customers, as of now.
