### ISSUE TITLE
Attachment not showing in reopened draft but is still bound and will sent in the final email 

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#3957]
Hello.

I can not reproduce this in the freescout demo since it seems currently out of date (1.8.130). When I try anyway, I get an _Whoops, looks like something went wrong_. 

Step by Step
1. Create a new message
2. attach a file (no embedd)
3. navigate somewhere else/close the draft
4. navigate back to the draft folder -> draft should be in the list with a paperclip
5. after open this draft, the file name is missing above the editor 
![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/9ddec852-404f-441d-9191-74cfb7a0ff81) <- this is missing

Without this, there is no option to remove the attachment from the draft anymore. Since I cannot test this on the demo page, I'm not sure if this issue only exists on our installation.

Sorry for adding so much issues recently. You guys doing great.

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
