### ISSUE TITLE
upstream timed out (110: Unknown error) while reading response header from upstream

### ISSUE THREAD

**Issue by chrish789** [freescout-helpdesk/freescout#3958]
when trying to perform a search from the main home screen, it opens up a new tab on the broswer. After a while, this fails with 504 Gateway Time-out

when i check the web-server.log, i see the entries as

2024/04/12 11:17:30 [error] 455#455: *80806 upstream timed out (110: Unknown error) while reading response header from upstream, client: 192.100.4.59, server: inbox.xxxx.com, request: "GET /search?q=tlee%40test.com HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock", host: "inbox.xxxx.com", referrer: "https://inbox.xxxx.com/"

We have multiple mailboxes attached to our freescout installation. I suspect this is causing the time out due to having to search through lots of mailboxes.

Is there a way to increase the time out length? Or is this a bug?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#the-search-times-out-or-takes-too-much-time
