### ISSUE TITLE
Module "Send Later": Difference in schedule time and actual sent-time

### ISSUE THREAD

**Issue by zcdevop** [freescout-helpdesk/freescout#3959]
Using the module "[Send Later](https://freescout.net/module/send-later/)", we experienced that scheduling an email e.g. to be send at 13:00 next day, the email is actually sent out at 15:00 on the next day.

Probably this is an issue in the front-end JavaScript, using UTC time or not properly taking the local timezone into account. The server runs with timezone Europe/Berlin and the agents browser is located in Germany (so its local time is also Europe/Berlin). In FreeScout .env `APP_TIMEZONE="Europe/Berlin"` is set as well.

The issue was discovered yesterday, so +2 hours time-shift makes sense, since the change to summer-time took place on 31.03.2024 (probably the issue was only +1 hour before, which was not too bad. But its better if one could rely on the scheduled setting made by agents). We know that dealing with dates/times/timezones is always a hassle, so hopefully the fix is not a too big headache :-)

PS: Just writing this issue and checking the environments, there is something else strange. Manage > System >  System Status shows the following:
```
Date & Time 	Apr 12, 2024 14:27
Timezone 	Europe/Berlin (GMT+0200)
```

Log via SSH into the server and executing `$ date` on CLI prints `Fr 12. Apr 15:27:19 CEST 2024`, which is the correct time right now writing this. So it seems that FreeScout "Date & Time" value is 1 hour off.

PHP: v8.1.27
FreeScout: v1.8.120
Module "Send Later": v1.0.17

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#timezone-setting-does-not-work
