### ISSUE TITLE
Multi selected attachments not attached

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#396]
Hi,

I found out that if you want to attach something to an outgoing email, you are able to choose multiple items from the file-browser-window. 

However they are NOT attached. 

You have to select one and attach, then select another one and attach.

It would be best if a. it is possible to attach multiple items in one time, otherwise b. make sure the file-browser-window can only select one at a time.

Kind regards,

Marcel.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Multiple attachments are attaching just fine. Which browser are you using?

**Comment by freescout-helpdesk** [comment]
Apparently the issue has been already fixed.
