### ISSUE TITLE
1.8.133 after update, emails are not fetching. 

### ISSUE THREAD

**Issue by devops786k** [freescout-helpdesk/freescout#3960]
Hi,

I have installed freescout yesterday and was working perfectly. However after updating to the new version today it has stopped fetching emails. I get this error:

Folder: INBOX; Error: Method Webklex\PHPIMAP\Header::decode() is not supported.

This happens when I manually try to fetch emails under, system>tools and select "all" as i am trying to fetch old emails. This did work yesterday but not after the update.

Selecting unread works but I require old emails.

Thanks

PHP version: 8.2.17
FreeScout version: 1.8.133
Database: MySQL 
Are you using CloudFlare: No

![image](https://github.com/freescout-helpdesk/freescout/assets/166836387/c79d7ada-9f7c-45db-8139-2308c62275f4)

![image](https://github.com/freescout-helpdesk/freescout/assets/166836387/d50f5c6d-3a9d-47a4-9355-2fdb13b3065a)

**Comment by EAS-FBeckmann** [comment]
Same problem here, is there any solution or workaround? In my case so new E-Mails are fetched at all, so this makes the mailbox with the error unusable at the moment.
