### ISSUE TITLE
vars.js file created in the wrong directory

### ISSUE THREAD

**Issue by Sgroove** [freescout-helpdesk/freescout#3961]
There seem to a path configuration issue that causes the vars.js file to be created in the wrong folder.
When I run `php artisan freescout:clear-cache` I get the following output:

**The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js**

As you can see, the file vars.js is created in the storage/app/public/js/ folder instead of **/public/storage/js/**
This causes the following error when running the app:

production.ERROR: Error: File '/var/www/html/freescout/public/storage/js/vars.js' does not exist; File: /var/www/html/freescout/overrides/devfactory/minify/src/Providers/BaseProvider.php (124)  

PHP version: 8.3
FreeScout version: 1.8.133 
Database: MySQL
Are you using CloudFlare: No

**Comment by Sgroove** [comment]
Solved.

Had to simply delete the public/storage folder and run:
php artisan storage:link

**Comment by freescout-helpdesk** [comment]
Ok
