### ISSUE TITLE
How to add new button?

### ISSUE THREAD

**Issue by silicahd** [freescout-helpdesk/freescout#3966]
Is there a way to insert a back button? 
I also want to add words like reply to the other buttons.

![image](https://github.com/freescout-helpdesk/freescout/assets/7761519/32dcfe47-a09a-4b96-a494-2f5bbd65af77)

**Comment by freescout-helpdesk** [comment]
Via a custom module for example: https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development

**Comment by silicahd** [comment]
Thank you i see, I will need to get a pull request for these changes. We are working on a new theme and wanted to add these small changes. I thought there was some implementation that i did not see like OCMOD https://github.com/opencart/opencart/wiki/Modification-System

**Comment by silicahd** [comment]
Google Theme Module will be published soon. 

![image](https://github.com/freescout-helpdesk/freescout/assets/7761519/88ff9de2-d4c8-475c-907f-729ef3343ceb)
