### ISSUE TITLE
Can't save filter settings on Kanban board and can't share a link with filters set

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3968]
**Steps to reproduce:**
1. Apply any filter.
2. Refresh the page.

**Result:**
Filters are reset and there are no filter parameters in the link.

PHP version: 8.2.7
FreeScout version: 1.8.130
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
It'd by design. To copy the link with filters use Copy Link:

![2024-04-15_10-20-01](https://github.com/freescout-helpdesk/freescout/assets/40499291/93fb43f4-4ab0-440f-9330-839678fbea4c)

**Comment by buzzzo** [comment]
Yes but the copy link is useless if  is not possible to store the link on the web ui itself.
