### ISSUE TITLE
Search suddenly takes forever and we get 504 Gateway Time-out

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3969]
Hi,

search worked fine all the time and now, suddenly it takes forever and does not yield results. It takes so long, that we get a 504 Gateway Time-out.

We have a total of like 25000 conversations, so nothing crazy. Also, our server should be easily able to handle it.

It feels like something else must be wrong, because it happened from one moment to the other, not gradually getting worse.

Any ideas?

Thanks a lot!

PHP version: 8.2.17
FreeScout version:  1.8.119 
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#the-search-times-out-or-takes-too-much-time
