### ISSUE TITLE
Old emails not showing original dates even after editing .env file. 

### ISSUE THREAD

**Issue by devops786k** [freescout-helpdesk/freescout#3972]
Hi I have pasted the command: APP_USE_MAIL_DATE_ON_FETCHING=true 

to import old emails and keep their original dates as mentioned here: https://github.com/freescout-helpdesk/freescout/wiki/FAQ. I will remove the command as suggested after importing the old emails. 

However, it is not showing and showing from 1 minute ago for all the emails 500+:

![image](https://github.com/freescout-helpdesk/freescout/assets/166836387/006b2771-65c2-43d8-a2f0-c7f9fb660f82)

env file:
![image](https://github.com/freescout-helpdesk/freescout/assets/166836387/1a112051-919f-4df1-b365-d5da21a8a9a9)

Thanks

PHP version: 8.2.17
FreeScout version: 1.8.135    
Database: MySQL
Are you using CloudFlare:No

**Comment by freescout-helpdesk** [comment]
Maybe the cache has not been cleared and the option not applied. Anyway the only way to figure it out is for someone to investigate on your server.

**Comment by maltem-za** [comment]
@freescout-helpdesk You disabled the option in b6c015e (ref. #3380)

**Comment by maltem-za** [comment]
Oh OK, my bad, I thought the linked commit disabled it completely.
