### ISSUE TITLE
1 click deployment on Railway

### ISSUE THREAD

**Issue by toi500** [freescout-helpdesk/freescout#3973]
Please add installation support on Railway at https://railway.app/templates

**Comment by freescout-helpdesk** [comment]
Please contact them and ask to add FreeScout to their templates.

**Comment by toi500** [comment]
Yes, I can do that. But then don't ask user to contact you for this 👇🏼

![Screenshot_2024-04-17-05-43-25-74_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/freescout-helpdesk/freescout/assets/138339291/8991797b-cdc4-4584-84d6-fb45beb745c9)
