### ISSUE TITLE
After reply behavior

### ISSUE THREAD

**Issue by silicahd** [freescout-helpdesk/freescout#3974]
Once you reply to a ticket the system will automatically show the next conversation. Is there a setting that will allow to go back to the filter index or ability to stay on the same ticket? Maybe I am missing it somewhere. I realized that I set the wrong fields for the wrong ticket because we don’t realize that it moved to the next one.

**Comment by ilyakonovalenko** [comment]
By default you will be redirected to the next conversation. You can change it by clicking right to the send reply button:
![изображение_2024-04-17_103252725](https://github.com/freescout-helpdesk/freescout/assets/63669538/dd809986-679c-4f29-9324-020ee3991437)

@freescout-helpdesk, it is actually something I don't personally like in current default settings. Would be nice to have "Send and stay on page" as a default. Is it possible to set/change?

**Comment by silicahd** [comment]
> By default you will be redirected to the next conversation. You can change it by clicking right to the send reply button: ![изображение_2024-04-17_103252725](https://private-user-images.githubusercontent.com/63669538/323143228-dd809986-679c-4f29-9324-020ee3991437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzg0NTAsIm5iZiI6MTcxMzM3ODE1MCwicGF0aCI6Ii82MzY2OTUzOC8zMjMxNDMyMjgtZGQ4MDk5ODYtNjc5Yy00ZjI5LTkzMjQtMDIwZWUzOTkxNDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE4MjIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNjA3MDc4MTQ4ZjEwYjhmOTQ5ZDc0MzcyOTk0MmZlYTA2Nzk3NDM0NmM4N2E3MTE3ZjJhZWNlMDFlNmE1YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SPw6giWoGyCPDu3uwuM04tdBTYseoWtvvR9BgmprpiI)
> 
> @freescout-helpdesk, it is actually something I don't personally like in current default settings. Would be nice to have "Send and stay on page" as a default. Is it possible to set/change?

thank you i figured we can change it on our own fork but was curious if it was a setting we can set by default as well. I dont like to make to many changes to the fork if we can get things done via modules and hooks. But this one will need to be a code change. I really apricate the help.

**Comment by silicahd** [comment]
> By default you will be redirected to the next conversation. You can change it by clicking right to the send reply button: !
> 
> @freescout-helpdesk, it is actually something I don't personally like in current default settings. Would be nice to have "Send and stay on page" as a default. Is it possible to set/change?

I realized we can set the default in the change default redirect but this only applies to the one user. We will have to make the default change in the fork. Thank you for the help.

**Comment by ilyakonovalenko** [comment]
> I realized we can set the default in the change default redirect but this only applies to the one user. We will have to make the default change in the fork. Thank you for the help.

It would be nice if you submit pull request with your changes to make it possible to set the default behaviour for all users.

**Comment by silicahd** [comment]
By next week we will do that, because we have a bunch of little annoying changes that would found and fixed. I was trying to keep it with the modules and hooks as much as I can. We also made a new theme that looks more like google and hope to also release that.

**Comment by Sokolset** [comment]
Hi, I have 2 problems, 1 I received a ticket and I assign it to the agent, he answered the ticket, clicked the send button and the ticket went to the folder, unassigned, I want the ticket to remain with the agent until the closure of all the correspondence. 2 The problem is due to the fact that when the application was assigned to the agent, he worked it out and closed the repeated appeal of the same client after closing, he sends a ticket to the agent and I would like that in the public folder not assigned received zero reset the agent from this application!
