### ISSUE TITLE
Not receiving webhooks

### ISSUE THREAD

**Issue by anjan-rpf** [freescout-helpdesk/freescout#3976]
Module: API & Webhooks

we missed several webhooks for `convo.note.created`, `convo.status` ( not sure about other statuses as we are not using them as of now )

Previously we used `convo.created` webhook which has similar issue, so we have updated the implementation to avoid reconciliation issues

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/api-webhooks/ --> Troubleshooting

**Comment by anjan-rpf** [comment]
@freescout-helpdesk we are getting webhooks sometimes and sometimes we are not getting them.

I will also go through the troubleshooting once

**Comment by freescout-helpdesk** [comment]
It means there problems either with connection to your webhook URL or with background jobs.
