### ISSUE TITLE
Password reset emails are not being sent out

### ISSUE THREAD

**Issue by danielmilner** [freescout-helpdesk/freescout#3978]
PHP version: 8.1.27
FreeScout version: 1.8.135
Database: MySQL
Are you using CloudFlare: No

When either a user or an administrator triggers a Password Reset email to be sent out, nothing actually happens. The email is not showing up in Outgoing Emails Log Records either. Emails for "Email to customer", "User notification", "User invite", and "Test email" are all working though.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#101-alerts

**Comment by danielmilner** [comment]
System emails are set up and working...except for password reset emails.

**Comment by freescout-helpdesk** [comment]
It need to be investigated on your server.
