### ISSUE TITLE
Spam filter false positive

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#3983]
Dear support,

Since a couple of days, some emails are marked as spam by the spam filter, for example:
https://paste.pics/f76946a0e90795a975c536c861555d57

But in the header there's no indication of Spam:

`X-Proofpoint-Spam-Details: rule=notspam policy=default score=0 spamscore=0 clxscore=1015
 impostorscore=0 adultscore=0 bulkscore=0 phishscore=0 mlxlogscore=999
 mlxscore=0 lowpriorityscore=0 malwarescore=0 priorityscore=1501
 suspectscore=0 classifier=spam adjust=0 reason=mlx scancount=1
 engine=8.12.0-2404010000 definitions=main-2404180109
X-Spam-Status: No, score=0.8
X-Spam-Score: 8
X-Spam-Bar: /
X-Ham-Report: Spam detection software, running on the system "sofia.svrsh.com",
 has NOT identified this incoming email as spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 root\@localhost for details.
 Content preview:  FedEx U ontvangt uw factuur als bijlage bij dit bericht We
    hebben uw nieuwe factuur 130351052 bijgevoegd. Als u vragen of opmerkingen
    over deze factuur heeft, kunt u contact met ons opnemen via . U kunt oo [...]
    
 Content analysis details:   (0.8 points, 7.0 required)
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
  0.0 URIBL_DBL_BLOCKED_OPENDNS ADMINISTRATOR NOTICE: The query to
                             dbl.spamhaus.org was blocked due to usage
                             of an open resolver. See
                             https://www.spamhaus.org/returnc/pub/
                             [URIs: mailchimp.com]
  0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was
                             blocked.  See
                             http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                              for more information.
                             [URIs: mailchimp.com]
  0.0 T_OBFU_PDF_ATTACH      BODY: PDF attachment with generic MIME type
  0.1 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
  0.0 HTML_MESSAGE           BODY: HTML included in message
  0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily
                             valid
  0.1 DKIM_INVALID           DKIM or DK signature exists, but is not valid
  0.0 KAM_DMARC_STATUS       Test Rule for DKIM or SPF Failure with Strict
                             Alignment
  0.5 KAM_NUMSUBJECT         Subject ends in numbers excluding current years
X-Spam-Flag: NO
`

It happened with multiple emails now, how can I troubleshoot this?

Thanks

**Comment by freescout-helpdesk** [comment]
Simply reset the Learning Memory.

**Comment by dabesa** [comment]
Thank you, I was not aware of this setting.

Just a minor typo:
"Filter Using Spam-Filtering Altorithm & Learning"
it should be "Algorithm"

**Comment by dabesa** [comment]
the typo was fixed in spam module version 1.0.25, thanks
