### ISSUE TITLE
Knowledge Base .. Documents open for everyone...?!?

### ISSUE THREAD

**Issue by rickwaltmann** [freescout-helpdesk/freescout#3984]
Hello everyone, yesterday I installed Freescout on our server and purchased almost all modules. Nice to give it a try. One of my goals for purchasing was the knowledge base. Now, I have a question about it: even if I set up a knowledge base as 'visible only to support agents', all documents placed in the knowledge base can still be accessed with the URL, even if you're not logged in! A knowledge base is intended for storing critical company questions including workflows and drawings, for example. But if ALL documents can simply be accessed with the original URL, I'm not sure if it's secure enough to expose it to the internet like this. I would appreciate your advice on this.

**Comment by rickwaltmann** [comment]
Thanks for your answer. Isnt it possible to protect a storage folder in Laravel for logged in users only? 
(see https://dev.to/kennyhorna/restricting-access-to-certain-files-in-our-laravel-app-27gh) 

Thats more secure instead of opening the storage folder for everyone.  In my opinion this is a mayor problem to solve.  (because of safety) What you think? Is this something to fix together?

**Comment by freescout-helpdesk** [comment]
There are two types of files stored in `storage` folder: attachments and uploaded files.
See https://github.com/freescout-helpdesk/freescout/wiki/FAQ#freescout-attachments-are-available-via-direct-link

**Comment by rickwaltmann** [comment]
Okay, thank you. Securing attachments is definitely a good idea. Do I understand correctly that this is already implemented? Or do I need to implement it via the link you sent? I'd also like to apply security to uploads. It would be great if you could simply check a box in Freescout under settings: 'uploads only viewable/downloadable when logged in'. That way, users can choose for themselves. I'll look into how to secure the uploads then.

**Comment by freescout-helpdesk** [comment]
> Do I understand correctly that this is already implemented?

Already implemented.

> It would be great if you could simply check a box in Freescout under settings: 'uploads only viewable/downloadable when logged in'.

Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by rickwaltmann** [comment]
Yes, I understand... the thing is, I've already purchased €150 worth of modules only to find out that our company doesn't agree with publicly publishing documents in the upload folder. I would appreciate it if you could help us with an easy fix so that at least we (and others who want this) can secure the upload folder. We use Freescout's knowledge base as an INTERNAL knowledge base. So only for employees, not for non-logged-in customers. Of course, I'm willing to pay for a good solution.

**Comment by freescout-helpdesk** [comment]
Gentle reminder:
https://github.com/freescout-helpdesk/freescout/blob/0ecfa248ee214adf706d9e474bc4c56656848a75/.github/ISSUE_TEMPLATE/general_help_request.md?plain=1
