### ISSUE TITLE
Save email as EML / MBOX / MSG mail format

### ISSUE THREAD

**Issue by athoik** [freescout-helpdesk/freescout#3990]
PHP version: 8.2.18
FreeScout version: 1.8.135
Database: MySQL
Are you using CloudFlare: No

Dear Freescout,

I would like to know if there is somehow a possibility to export/save an email. Eg save mail as  EML / MBOX / MSG mail format.

We have a case where an email should be forward to a new department and they need original email.
This is possible using Outlook / Thunderbird etc, but when using Freescout I wasn't able to detect that functionality. 

What are you suggesting? 
Is this something completely new?
A feature request?

Thanks for your recommendations.

Best Regards,
Athanasios

**Comment by freescout-helpdesk** [comment]
There is no such feature for now. 
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by athoik** [comment]
Sure, a feature request created: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/437837/comments

Thank you!
