### ISSUE TITLE
Unknown hashing algorithm: crc32c

### ISSUE THREAD

**Issue by dreyerretief** [freescout-helpdesk/freescout#3991]
We did an update on Thursday we are getting the following error when fetching emails..

Unknown hashing algorithm: crc32c

Any ideas what it could be?

We have checked the mailboxes mails are being marked as read but nothing is being downloaded to the ticketing q. It also looks like the issue is only occurring the 365 mailboxes

**Comment by freescout-helpdesk** [comment]
We've fixed it in the `master` branch. You can check it.

**Comment by dreyerretief** [comment]
Thanks updated and it works... Lost a day of work getting lots of bugs into production these days...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
