### ISSUE TITLE
Fetch emails via mail forwarder instead of POP/IMAP to work with Google Group email inboxes

### ISSUE THREAD

**Issue by aaversa** [freescout-helpdesk/freescout#3992]
We're working on configuring Freescout with Google Group email inboxes. These are not accessible via POP/IMAP, however I can forward emails from these accounts to any arbitrary email address. This is how we were able to use them with Helpscout. I've searched Freescout's docs but was not able to find anything. Is this possible?

**Comment by raramuridesign** [comment]
@aaversa As long as you setup freescout to fetch from a imap/pop box, then this will work.
However, you send setup would or must be checked, as this may not align using some random account.
M.

**Comment by dpgdoc** [comment]
@aaversa, I'm currently managing Google Group email inboxes, and here's how I've set it up:

1. Establish a user/email account that will centralize all emails.
2. Create a Google Group and include the user created in step 1 as a participant.
3. Configure permissions to allow anyone to post, but restrict visibility.
4. In the email account from step 1, create separate folders for each group.
5. Implement a filter to automatically direct conversations to their respective folder (for example, emails sent to github@aaversa.com are automatically sorted into the "GitHub" folder).
6. Set up an alias for sending emails from the account mentioned in step 1.
7. Integrate the newly created email account with Freescout, ensuring it fetches emails solely from the designated folder.

This system has proven to be highly effective in our company! I might consider contributing a guide to the documentation later on.

**Comment by aaversa** [comment]
> @aaversa, I'm currently managing Google Group email inboxes, and here's how I've set it up:
> 
> 1. Establish a user/email account that will centralize all emails.
> 2. Create a Google Group and include the user created in step 1 as a participant.
> 3. Configure permissions to allow anyone to post, but restrict visibility.
> 4. In the email account from step 1, create separate folders for each group.
> 5. Implement a filter to automatically direct conversations to their respective folder (for example, emails sent to [github@aaversa.com](mailto:github@aaversa.com) are automatically sorted into the "GitHub" folder).
> 6. Set up an alias for sending emails from the account mentioned in step 1.
> 7. Integrate the newly created email account with Freescout, ensuring it fetches emails solely from the designated folder.
> 
> This system has proven to be highly effective in our company! I might consider contributing a guide to the documentation later on.

All of this makes sense up until the last part (7). How can you fetch solely from a designated folder...?

**Comment by freescout-helpdesk** [comment]
@diogogpinto Thanks for sharing the info.

**Comment by diogogpinto** [comment]
> @diogogpinto Thanks for sharing the info.

Thank you @freescout-helpdesk for your work with this amazing software. I'm glad to help the community in any way I can.

**Comment by b4oshany** [comment]
> @aaversa, I'm currently managing Google Group email inboxes, and here's how I've set it up:
> 
> 1. Establish a user/email account that will centralize all emails.
> 2. Create a Google Group and include the user created in step 1 as a participant.
> 3. Configure permissions to allow anyone to post, but restrict visibility.
> 4. In the email account from step 1, create separate folders for each group.
> 5. Implement a filter to automatically direct conversations to their respective folder (for example, emails sent to [github@aaversa.com](mailto:github@aaversa.com) are automatically sorted into the "GitHub" folder).
> 6. Set up an alias for sending emails from the account mentioned in step 1.
> 7. Integrate the newly created email account with Freescout, ensuring it fetches emails solely from the designated folder.
> 
> This system has proven to be highly effective in our company! I might consider contributing a guide to the documentation later on.

I've also had this setup from 2021 and it has been very effective for us too.
