### ISSUE TITLE
Timer tracking export to UTF-8

### ISSUE THREAD

**Issue by krzysztofklonowski** [freescout-helpdesk/freescout#3993]
Hello,

When exporting to UTF-8 (semicolon) file is saved in code page UTF-8 BUT without BOM character.

If i have in tickets polish letters and export report to file I have weird letters like: IloĹ›Ä‡ godzin (it should be "Ilość godzin"), drukujÄ… siÄ™ w pionie (it should be "drukują się w pionie") etc.

![2024-04-23_08h31_27](https://github.com/freescout-helpdesk/freescout/assets/167428698/2afbd789-2128-40b8-ab7d-3c18114fafca)

Fix required.

Regards

**Comment by freescout-helpdesk** [comment]
Are you talking about exporting feature in Time Tracking Reports?

**Comment by freescout-helpdesk** [comment]
We've added BOM to UTF-8 encoded data in Export Conversations Module v1.0.10.
You can try it now.

**Comment by krzysztofklonowski** [comment]
Hello,

Thank you. Now it's working great! Thank you.

Reagrds
