### ISSUE TITLE
oAuth support for freescout

### ISSUE THREAD

**Issue by anidi0t** [freescout-helpdesk/freescout#3995]
According to Google, they will suspend support for LSA https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html.
I see the freescout does not support oAuth, and password-based access will no longer be supported, do you have any plan to implement oAuth support for freescout?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3707

**Comment by diogogpinto** [comment]
@anidi0t you should use an App Password to connect to the App. oAuth isn't support in Freescout.

To get an App Password, go to your Account, 2FA seetings, App Password and create one. You should insert that App Password on your mailbox password for sending/fetching.

All instructions [are in the documentation](https://github.com/freescout-helpdesk/freescout/wiki/Connect-G-Suite-to-FreeScout) (although the UI has been updated a bit).
