### ISSUE TITLE
Configure the X-Frame-Options add_headers correctly

### ISSUE THREAD

**Issue by Maddmax76** [freescout-helpdesk/freescout#3996]
Good morning. I'm trying to integrate the Knowledge Base module widget into my intranet site. Clicking on the popup tells me that the site refused the connection.
This is because my Apache is configured to avoid cross-site scripting (XSS) attacks.
The setting that blocks attacks should be add_header X-Frame-Options set to "SAMEORIGIN".

I would also like to allow intranet servers to access the Knowledge Base, web servers can be reached by entering the same domain as the FreeScout server.

I would like help on how to configure my Apache to allow the opening of iframes also from certain URLs or IP addresses as well as from SAMEORIGIN.

Thank you!

PHP version:  PHP 8.2.10-2ubuntu1
FreeScout version:  1.8.137
Database: MySQL / PostgreSQL: Mysql (8.0.35)
Are you using CloudFlare: Yes / No: NO

**Comment by freescout-helpdesk** [comment]
There are some instructions in the Troubleshooting section of https://freescout.net/module/knowledge-base/

**Comment by freescout-helpdesk** [comment]
Try to add the following parameter in the .env file and clear cache:
```
APP_CSP_SCRIPT_SRC="; frame-ancestors 'self' address1 address2 .... addressN;"
```

**Comment by Maddmax76** [comment]
thanks for this other solution, I will try to apply it if after a trial period I still encounter difficulties, for now the CSP frame-ancestors declared in the Apache security configuration seem to work.

Thanks again

**Comment by fulldecent** [comment]
I tried adding to my .env:

```
APP_CSP_CUSTOM="; frame-ancestors 'self' https://mysubdomain.example.com;"
```

and then clearing cache with:

```sh
php artisan freescout:clear-cache
```

Then when checking in browser, FreeScout is serving the page with `x-frame-options: SAMEORIGIN` and the browser produces the error:

> Refused to display 'https://scout.pacificmedicaltraining.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

---

So this did not work. Is there more I can try?

**Comment by fulldecent** [comment]
Now I tried this and it worked:

```
APP_CSP_CUSTOM="; frame-ancestors 'self' sub.example.com;"

APP_X_FRAME_OPTIONS="ALLOW-FROM sub.example.com"
```

and then again 

```sh
php artisan freescout:clear-cache
```
