### ISSUE TITLE
Data isolation between operators authorized for different mailboxes.

### ISSUE THREAD

**Issue by Maddmax76** [freescout-helpdesk/freescout#3997]
Good morning. 

Is it possible to ensure that the TAGs created by operator A for messages in mailbox 1 are not seen by operator B who only has access to mailbox 2?

Thank you

PHP version:  PHP 8.2.10-2ubuntu1
FreeScout version:  1.8.137
Database: MySQL / PostgreSQL  Mysql (8.0.35)
Are you using CloudFlare: Yes / No: NO

**Comment by freescout-helpdesk** [comment]
Unfortunately not and there is no plans to implement it.
