### ISSUE TITLE
Issue with bold font

### ISSUE THREAD

**Issue by dryabov** [freescout-helpdesk/freescout#40]
https://github.com/freescout-helpdesk/freescout/blob/05e5502412fe9a0ec39c321e0acecf2b4b5fdc0e/public/css/fonts.css#L5

There should be full font name (not just a family name) inside of `local` declaration, i.e. `local('Liberation Sans Bold'), local('LiberationSans-Bold')` (see example of `Helvetica Neue Bold` on https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face). But note that such a patch works in latest Firefox, but not in Chrome 62 (see https://stackoverflow.com/questions/47098699/chrome-update-suddenly-breaks-font-face). Not sure what is better, remove `local` declarations, or set proper font names (hoping it will be fixed in Chrome 63).

**Comment by freescout-helpdesk** [comment]
Thanks. What was your original issue? Fonts are not cached or displayed incorrectly?

**Comment by dryabov** [comment]
Original issue is that I have `Liberation Sans` installed on Windows 10 (so that `local` font is used), but new messages are not displayed in bold.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/d64433edaccfaf1d7c031415be0671eb0f0e7683
