### ISSUE TITLE
Using URL instead of cron doesn't fetch emails

### ISSUE THREAD

**Issue by kirschkern** [freescout-helpdesk/freescout#4000]
After updating to 1.8.137 we don't receive any new mails.
Instead of the cron job, we use the URL that gets shown below with the hint "use at own risk". 
When calling this URL in the browser I get "No scheduled commands are ready to run."

In "system / status" I see the line
  queue:work 	Last run: ? Last successful run: ? Try to clear cache to force command to start.
However, clearing the cache doesn't change anything.

Any hint would be great to get email fetching running again would be great.

We currently use the URL solution, because our server only alows cron jobs to run every 5 minutes which is way to long. We use a cron job from another server to call that URL.

When using the 5 minutes Cron job, the mails get fetched.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

Meanwhile you can simply change line 36 in `/app/console/Kernel.php` to:
```
if (!$this->isScheduleRun() && !\Helper::isRoute('system.cron')) {
```

**Comment by Hamza31231** [comment]
**changed         if (!$this->isScheduleRun()) {
to                   if (!$this->isScheduleRun() && !\Helper::isRoute('system.cron')) {**

now it seems to work!

thank you very much !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
