### ISSUE TITLE
Help me identify why my server is reaching timeout with 504 error

### ISSUE THREAD

**Issue by altdsoy** [freescout-helpdesk/freescout#4003]
Hi there,

My freescout instance is not working all of a sudden.
We're getting 504 timeout errors.
Although it's a docker installation (will probably go there to ask for docker related stuff)
So, here I just wanted to know how can I troubleshot my server?
Is there some kind of commands I can run?

The [Troubleshooting](https://github.com/freescout-helpdesk/freescout) section suggest to go to Manage >> System, but I don't have any access to the web interface.

As per the logs in `storage/logs`, I don't see any useful information:
- in `freescout` I only have `fetch-emails.log` (with successful fetching messages - even after a restart while still having the server not responding) and `queue-jobs.log` which is empty
- in `nginx` everything is empty
- in `php-fpm`I have `NOTICE: ready to handle connnections`

Many thanks for any hint on how I can troubleshoot what's going on..
It's really annoying to have no answer...

PHP version: Not sure - where do I look if the server is not responding?
FreeScout version: Not sure - where do I look if the server is not responding?
Database: PostgreSQL
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment]
The only way to figure it out is for someone to investigate it on your server.
https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer
