### ISSUE TITLE
MySQL 8 / PHP 8.3 Supported?

### ISSUE THREAD

**Issue by ztheory** [freescout-helpdesk/freescout#4004]
Thanks for this excellent project.

I couldn't find this information, so I'm asking :)

Can HelpScout run on MySQL 8? The prerequisites mention MySQL 5+, but the installer script actually installs MariaDB 10.x, so pretty sure the answer is "yes", but thought I'd check.

Is PHP 8.3 known working, or is 8.2 recommended for now?

Thanks in advance.

**Comment by freescout-helpdesk** [comment]
> Can HelpScout run on MySQL 8?

Yes.

> Is PHP 8.3 known working


Yes.
