### ISSUE TITLE
Mail not Sent after cloning

### ISSUE THREAD

**Issue by volvisti** [freescout-helpdesk/freescout#4011]
PHP version:  8.2.17
FreeScout version: 1.8.127
Database: MySQL 
Are you using CloudFlare: No

**First of all...
Thanks for launching such a helpful "working-together-tool".
All of us are happy that we found your tool.**

Our issue:
When cloning a conversation with one or more CC-mails, the CC-mail-addresses are set in brackets: 
_CC: [email1@host.com, email2@host.com]_

The answer then is not sent, due to freescout recognizes the brackets as part of the e-mail-address.
The log shows the following (mailaddress is changed)
_Address in mailbox given [[email1@host.com] does not comply with RFC 2822, 3.6.2.; File: /www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php (355)_ 

Is it bug? 
Is there a workaround for it's usual in our conversations with some customers?

Thanks for helping
Regards 
S.Roggatz

**Comment by freescout-helpdesk** [comment]
How are you cloning the conversation?

**Comment by volvisti** [comment]
Hi. 

We are cloning conversations by right klicking on the arrow down near the notification when recidved.
On the right top of the conversation. 


Mit freundlichem Gruß
Sönke Roggatz
Dipl.-Ing. (FH) Druckereitechnik
IT &amp; Technik

--------
MAILING-WERKSTATT
Inh. Heike Sydow | Am Weinberg 2 | 35619 Braunfels | USt-IdNr. DE278827840
Tel.: 06442 95446-0 | Fax: 06442 95446-2 | E-Mail: ***@***.*** | www.mailing-werkstatt.de [http://www.mailing-werkstatt.de/] 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

-----------------------------------------------------------
## freescout-helpdesk/freescout, am May 5 @ 07:46 (Europe/Berlin): 
How are you cloning the conversation?

**Comment by freescout-helpdesk** [comment]
Can you send a screenshot?

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by volvisti** [comment]
Hi,
thanks for your answer. 

When will it be released?
Just to have a time-line.


Mit freundlichem Gruß
Sönke Roggatz
Dipl.-Ing. (FH) Druckereitechnik
IT &amp; Technik

--------
MAILING-WERKSTATT
Inh. Heike Sydow | Am Weinberg 2 | 35619 Braunfels | USt-IdNr. DE278827840
Tel.: 06442 95446-0 | Fax: 06442 95446-2 | E-Mail: ***@***.*** | www.mailing-werkstatt.de [http://www.mailing-werkstatt.de/] 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

-----------------------------------------------------------
## freescout-helpdesk/freescout, am May 5 @ 18:46 (Europe/Berlin): 
Fixed in the master branch and will be published in the next release.

**Comment by freescout-helpdesk** [comment]
In about a week. You can also patch it manually: https://github.com/freescout-helpdesk/freescout/commit/c4932c4c8e342204f1e46696c4f209886bd9070a
