### ISSUE TITLE
Too many redirect - Knowledge Base

### ISSUE THREAD

**Issue by semaf** [freescout-helpdesk/freescout#4013]
Hey,

We activated the module Knowledge Base and added the freescout domain for it too which create domain.com/hc/4163215353. If I call the domain, I get browser Error "too many redirects". No logs found about it.

**Comment by freescout-helpdesk** [comment]
You need to debug the function at line 154 in /Providers/KnowledgeBaseServiceProvider.php:
https://github.com/freescout-helpdesk/freescout/wiki/Debugging
