### ISSUE TITLE
Sort conversations in Custom Folder in ascending order by the last_reply_at column by default

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#4014]
Hi @freescout-helpdesk 

We had a requirement that we wanted to sort conversations in Custom Folders in ascending order by the last_reply_at column. So, I checked the code, and there was an Eventy filter available for the same. Therefore, I added the following listener in the AppServiceProvider.

```
\Eventy::addFilter('folder.conversations_order_by', function($order_by) {
            return [
                    ['last_reply_at' => 'asc']
                ];
        }, 20, 1);
```

But after doing that, the in page Table Sorting is not working. Please fix it for Custom Folders.

Thank You.
<img width="1020" alt="Screenshot 2024-05-03 at 10 38 23 PM" src="https://github.com/freescout-helpdesk/freescout/assets/118246547/497d4b79-0e64-4a2d-a093-0b7712033417">

**Comment by freescout-helpdesk** [comment]
It looks like you want conversations in Custom Folders to be sorted in ascending order by the `last_reply_at` column **by default**?

**Comment by mahavirn** [comment]
Yes, Thats what i want, but when i am doing via above code, the front-end pagination is not working.

**Comment by freescout-helpdesk** [comment]
There is no such possibility for now. 
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by mahavirn** [comment]
But i can do it via `Eventy` code that i shared above. The only fix needed from your side is to make sure the front-end sorting is working fine after doing changes in AppServiceProvider.

**Comment by freescout-helpdesk** [comment]
Feel free to send a pull request.

**Comment by mahavirn** [comment]
Okay understood. Thanks!
