### ISSUE TITLE
How do we remove the Freescout signature at the end of every ticket ?

### ISSUE THREAD

**Issue by groovelikeapig** [freescout-helpdesk/freescout#4015]
I want to remove this

<img width="1461" alt="Screenshot 2024-05-06 at 13 51 57" src="https://github.com/freescout-helpdesk/freescout/assets/82309061/925e30a8-0051-4f7e-9a94-0a8cee309c46">

It is something easy to do?

Thanks.

PHP version: 
FreeScout version: 
Database: MySQL / PostgreSQL
Are you using CloudFlare: Yes / No

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#how-to-remove-branding-from-emails-to-customers
