### ISSUE TITLE
A module for accessing organization tickets.

### ISSUE THREAD

**Issue by ASTIN-UA** [freescout-helpdesk/freescout#4016]
Hi. Is there a module or a plan for a module so that you can put in the head of the organization, or several people who would have access to view all tickets within the organization? 

There is such a possibility in Jira. And here it is sorely lacking. 

Thank you in advance.

**Comment by freescout-helpdesk** [comment]
Unfortunately not.

**Comment by ASTIN-UA** [comment]
Perhaps it's time to create such a module? You already have a lot of useful modules, but unfortunately, in some areas of development, there are almost none. And this is one of them. I think there are many people who would like to buy a module with such functionality. But before that, you need to finalise the directory of organisations, with the ability to bind users (not support administrators, but external "users"). Add functionality to the User Portal module, such as classic email and password authentication, password recovery, etc. 
You have a great system, really! But there are still some little things missing. And this is one of them.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
