### ISSUE TITLE
WooCommerce Integration is Spotty

### ISSUE THREAD

**Issue by aaversa** [freescout-helpdesk/freescout#4017]
I have the WooCommerce module installed and correctly configured with my store's API key. My store is hosted on the same domain (different server), on enterprise-grade hardware. We previously used Helpscout which integrated with the store without any issue.

However, with Freescout, when loading a given conversation with a customer that DEFINITELY has WooCommerce orders, the majority of the time the orders section simply 'spins' for 30-45 seconds before timing out and saying there are no orders.

This doesn't happen 100% of the time. **Sometimes** if I refresh the page a few times, the orders will eventually load. Some customers' orders load instantly, too. It's not clear what if any pattern there is.

We have many, many services integrated with our WooCommerce store and none of them exhibit this behavior so I don't think it's an issue with our WooCommerce database or server response time.

Our Freescout installation is on a Hetzner server with 3 vCPUs and 4GB of RAM. I have been monitoring our CPU utilization and it has never crossed 50%.

PHP version: 8.3
FreeScout version: Latest
Database: Nginx
Are you using CloudFlare: No

EDIT: I just checked the Laravel log and I am seeing a bunch of this:

[WooCommerce] HTTP Status Code: 0 (Store not found at the specified URL) | Requested resource: https://impactsoundworks.com/wp-json/wc/v2/orders

I can most definitely guarantee our store is at https://impactsoundworks.com/. Also, this integration was (at least sort of) working yesterday... What's going on?

**Comment by freescout-helpdesk** [comment]
The only way to figure it out is to debug on your server. Try https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by aaversa** [comment]
This is the error in the logs, are you looking for more detail than this?

[WooCommerce] HTTP Status Code: 0 (Store not found at the specified URL) \| Requested resource: https://impactsoundworks.com/wp-json/wc/v2/orders

I am 100% sure this is the correct endpoint. I have just used Postman and tested it for myself - it is correct and returning data as expected with a simple GET request.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/4017#issuecomment-2104600271

**Comment by freescout-helpdesk** [comment]
Unfortunately we can't tell what can be the reason of the problem from here. The only way to do it is for someone to investigate it on your server.

**Comment by aaversa** [comment]
By "your server" do you mean the server hosting Freescout? If so, as I showed in the logs, the only error is that HTTP Status Code 0. But that doesn't make sense as, like I said, every other application that uses my store's API (there are dozens) work perfectly, including Postman running on my computer. Is the WooCommerce module open source? Can I open it up and see if I can debug this myself?

**Comment by aaversa** [comment]
@freescout-helpdesk I have just rewritten some aspects of the WooCommerce integration.

The retrieval time has gone from 40s to less than 1 second.

I did this by working with Automattic to create a new endpoint via WC plugin that is orders of magnitude faster. I then added an integration via a separate plugin on the Orders page for customers allowing them to submit a ticket easily. See screenshots.

The plugins are not really polished but they do work and makes the functionality equivalent to Helpscout.

Are you interested in taking a look at our work?

![need help form](https://github.com/freescout-helpdesk/freescout/assets/1279358/f2d5beab-07c4-449a-abf6-133fdcaf4982)
![Orders screen](https://github.com/freescout-helpdesk/freescout/assets/1279358/27ba9fd6-0fa6-4820-ac20-adc1afda8535)

**Comment by freescout-helpdesk** [comment]
You can send the code to support@freescout.net
We'll take a look.

**Comment by OneTwo3D** [comment]
Hi,
has there been any update? I have also the Woocommerce module installed and it isn't loading any previous orders.

**Comment by aaversa** [comment]
> Hi, has there been any update? I have also the Woocommerce module installed and it isn't loading any previous orders.

Not from the Freescout team, but you can look at the new endpoint we created here.

https://pastebin.com/9MFKXESy

Then you would just point Freescout to this endpoint instead of the regular WooCommerce one. Works literally orders of magnitude faster.

**Comment by OneTwo3D** [comment]
Thanks, I'll have a look at it :) But would be good if FreeScout would update their plugin.

**Comment by OneTwo3D** [comment]
@aaversa do you have an example how you added the alternative API to the WooCommerceServiceProvider.php in Freescout? Unfortunately the Freescout original plugin using the standar Woo API isn't working for me (the ?search string can search for anything but an email address in my installation it seems).
