### ISSUE TITLE
LDAP configuration with AD OK, But none can login.

### ISSUE THREAD

**Issue by innov2e** [freescout-helpdesk/freescout#4018]
PHP version: 7.4.30
FreeScout version: 1.8.122
Database: MySQL
Are you using CloudFlare: No

I am configuring the LDAP Module with Active Directory and the **successful steps are**:
- **I can bind the Active Directory** fine with the _Connect and Fetch_ Attributes button
- **I can fetch attributes from AD** and assign them to Freescout fields in this way:
      Email -> email
      First Name -> givenname
      Last Name -> sn
      Job Title -> description
      Phone Number -> telephon number
- **I can import users from AD** using the memberOf into the _DNs and Filters_ field. 
The Imported users are the right one with the right attributes read from the AD Group.
Then I have set the **LDAP Authentication** switch ON

**BUT** None of imported users can login into Freescout. 
Into Users log I found an entry _Failed login_ for each login attempt from which I get **These credentials do not match our records.**  even if the user is present and correctly imported.

I found nothing into the logs, do you ave any suggestion about how debug this issues?

**UPDATE:** If, as admin, I start the reset password for an imported user, he receives the mail and is able to chenge password, BUT this becamew handled as LOCAL user. When he successful login with the new password no LDAP authentication is daon, but it is authenticaed as a LOCAL user.

If I use ldapsearch from command line I can connect and query orrectly the AD.

**Anyone has some hints about how debug it?**

What what drives me crazy is that before updating Freescout all was working fine....

**Comment by freescout-helpdesk** [comment]
All we can suggest is to try to re-update the FreeScout.

**Comment by ureman2** [comment]
техподдержка на высоте ))
дружище, помоги советом
Требуется добавить пользователей только из одной группы "freescout_ldap". Мне не нужны пользователи всего домена. DN=CN=freescout_ldap,OU=OKS,OU=zavod,OU=kkt,DC=prom,DC=com (objectclass=member). Перепробовал уже кучу вариантов (( но все кончается ошибкой
