### ISSUE TITLE
DigitalOcean or AWS image

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#402]
Which image would you prefer for quick deployment of the FreeScout? Please vote below.

**Comment by freescout-helpdesk** [comment]
DigitalOcean image

**Comment by freescout-helpdesk** [comment]
AWS image

**Comment by amirkhan7** [comment]
is it possible to do a GCP image as well?

**Comment by freescout-helpdesk** [comment]
Use the following installation script:
```
curl https://raw.githubusercontent.com/freescout-helpdesk/scripts/master/install/ubuntu1804.sh | sh
```

**Comment by vlance11** [comment]
Running this command on a fresh Ubuntu 18.04 install gives an error 

Configuring nginx...
sh: 136: Syntax error: Unterminated quoted string


curl https://raw.githubusercontent.com/freescout-helpdesk/scripts/master/install/ubuntu1804.sh | sh
