### ISSUE TITLE
Replies to tickets not shown in freescout when sent via Thunderbird/webmail

### ISSUE THREAD

**Issue by Sick-Andrew** [freescout-helpdesk/freescout#4021]
PHP version: 7.4
FreeScout version: 1.8.139 
Database: MySQL
Are you using CloudFlare: No

I set up FS on a shared hosting. Including a new email address for the helpdesk.
When a ticket comes in to help@mydomain.com I can reply to it without problems from the FS dashboard.
But if I do so from my email client (Thunderbird) or webmail (Roundcube), the reply is not shown in the dashboard.
It kind of simply becomes a regular email conversation.

I also noticed that when a message comes in to help@mydomain.com and I open it in Thunderbird/Roundcube, Freescout does not get a hold of it. "Sent" folder is shown in the connection setting though and I was actually thinking FS would sync all involved messages into a ticket conversation.

**Comment by freescout-helpdesk** [comment]
We can't get what you are trying to say. Some screenshots or videos would be helpful.

**Comment by Sick-Andrew** [comment]
There is no screenshot or video I can take.
I'm refering to the seamless email integration feature.

My helpdesk email is help@mydomain.com
This is a mailbox I set up for Freescout and this mailbox can be accessed via webmail or IMAP (e.g. Thunderbird, Outlook).

My customer sends a request to help@mydomain.com.
This message appears on Freescout as a ticket but also as a regular email in the "regular" Thunderbird mailbox too.

If I reply from Thunderbird to that message, the reply is not shown in Freescout.
If I reply from Freescout dashboard a ticket conversation happens.

Maybe I'm not getting the seamless email integration feature. I thought I can either reply from my email client/webmail or via Freescout to continue the conversation and keep all messages in freescout. But that's not how it seems to work.

**Comment by freescout-helpdesk** [comment]
> If I reply from Thunderbird to that message, the reply is not shown in Freescout.

You should not reply from Thunderbird. You reply only from FreeScout when using FreeScout.

**Comment by freescout-helpdesk** [comment]
You work via FreeScout and sends and receives emails via your email service.
