### ISSUE TITLE
Loading issues with the request feature page

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#4024]
When I try to open [https://freescout.net/request-feature/](https://freescout.net/request-feature/) , I see this

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/bfefc4fe-d0e5-4d8a-a89a-d8fab3b3cfdc)

The console log reveals there seems to be an issue

Chrome 124.0.6367.207 64bit Linux

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/6fa8ce71-1b72-49a3-b3fb-fb683a76e969)

Mozilla Firefox 124.0.2 64bit Linux

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/75008446-3438-4f64-ac17-107bbb49a1e8)

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/dd73013d-89b7-4ae1-8442-a094e268572f)

Thanks in advance

**Comment by freescout-helpdesk** [comment]
Sometimes they have some technical issues. Just try another time.

**Comment by sofl88** [comment]
Turns out our DNS-Software (Pi-hole) was blocking some resources.
