### ISSUE TITLE
Workflow Module: Trigger Webhook action does not work

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#4025]
Hello,

According to the documentation:
> Trigger Webhook — trigger a custom Webhook (requires API & Webhooks Module). In the action setting enter your custom Webhook event name (example: custom.webhook.event) and after that use this event in the API & Webhooks section to create a Webhook.

However, when you set anything in the workflow settings, it does not save.

For example, this is how workflow is configured:
![image](https://github.com/freescout-helpdesk/freescout/assets/63669538/a71a6bc4-a762-4ff9-80a9-7379431710e1)

This is what after I save workflow (empty field):
![image](https://github.com/freescout-helpdesk/freescout/assets/63669538/6fc9bdd3-e50f-4818-8532-1c8f6cbaeec3)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Try to disable all non-official modules and customizations. Also try to re-update the FreeScout.

**Comment by ilyakonovalenko** [comment]
It seems I found what is wrong.

Input has name `actions[2][0][value]` and we have another input with the same name close to that input. So it seems FreeScout grabs second input's value which is empty.

![image](https://github.com/freescout-helpdesk/freescout/assets/63669538/63e81688-0cb8-4106-b0ba-ce0d1553e00c)

**Comment by freescout-helpdesk** [comment]
Can you send full screenshot.

**Comment by freescout-helpdesk** [comment]
![2024-05-15_16-26-01](https://github.com/freescout-helpdesk/freescout/assets/40499291/f5cf119d-81e4-4d41-a1f4-e4ebf3124aa2)

**Comment by ilyakonovalenko** [comment]
I don't know. It gets added to the action only.

![image](https://github.com/freescout-helpdesk/freescout/assets/63669538/6d94e151-d4a1-480d-ac3b-264067833a40)

**Comment by freescout-helpdesk** [comment]
Try to debug line 390 in /Modules/CustomFields/Providers/CustomFieldsServiceProvider.php

Or recreate this workflow and see if the issue persists.

**Comment by ilyakonovalenko** [comment]
Yes, it seems it comes from Custom Fields module. However, re-creating / editing the workflow does not help. It is impossible to configure Trigger Webhook action in our instance for now with Custom Fields module enabled.

This is what I see when Custom Fields module is disabled:
![image](https://github.com/freescout-helpdesk/freescout/assets/63669538/c7458879-735a-4385-9217-3132e6339739)

So some additional input gets added to Trigger Webhook action only in any case.

**Comment by ilyakonovalenko** [comment]
It seems I found the issue. It was caused by custom module. Sorry for that.
