### ISSUE TITLE
Workflows module. Replay delay

### ISSUE THREAD

**Issue by ADMAROG** [freescout-helpdesk/freescout#4027]
Hello. There is a small problem with the Workflows module.
Task: Duplicating information on custom fields in a ticket so that the user who sent it could see what was generated in the request.
To do this, we decided to use Workflows, where we would work out the “Reply to Conversation” action, which uses variables. But the response happens so quickly that the variables do not have time to receive information from the custom fields. But if you execute the script with a delay of a few seconds, then there is no problem and the information has time to catch up.
![image](https://github.com/freescout-helpdesk/freescout/assets/169902680/3420544e-06e2-4264-9f77-9525a77c4353)

PHP version: 8.2.7
FreeScout version: 1.8.139    
Database: Mysql (10.11.4-MariaDB-1~deb12u1)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Can you attach screenshots of Events and Actions tabs of your Workflow.

**Comment by ADMAROG** [comment]
Of course. ![markup_1000020087](https://github.com/freescout-helpdesk/freescout/assets/169902680/84637645-82c1-4abb-8e72-d5024e617c78)
![markup_1000020089](https://github.com/freescout-helpdesk/freescout/assets/169902680/db5a29f9-e6f7-48ca-8368-9dcb89a196a2)
![markup_1000020090](https://github.com/freescout-helpdesk/freescout/assets/169902680/da0987ac-cc35-421b-b17f-88c4791004c4)
![markup_1000020091](https://github.com/freescout-helpdesk/freescout/assets/169902680/a548a60f-b7ec-4541-a579-7e1663f544f4)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue on our end.

**Comment by ADMAROG** [comment]
Is it possible in the future to add a Relpy to Conversation delay to the wokrflows module in actions?
It would be very cool and it would solve our problem.

**Comment by ADMAROG** [comment]
Hi, it seems this error is described here and it was solved. Could you see if there is a connection, maybe it will be possible to implement it in the same way? 
https://github.com/freescout-help-desk/freescout/issues/1038
