### ISSUE TITLE
Extended Editor Module

### ISSUE THREAD

**Issue by VovaSnova** [freescout-helpdesk/freescout#4028]
Hello, please help. I bought the module from you:

Customers Management (CRM) Module

and a separate module: Extended Editor Module, but I can't add an editor even if I create a new field from the client:

This is the editor I mean:
![Screenshot_7](https://github.com/freescout-helpdesk/freescout/assets/169980093/15ee58af-34ba-4065-a033-a80ff0712643)

How do I change the font and color of the text in the customers fields? Maybe some other module is needed?
![Screenshot_6](https://github.com/freescout-helpdesk/freescout/assets/169980093/65ef3683-89c3-4201-b975-fb2d226b765d)

-->

PHP version: PHP 8.1.12-1ubuntu4.3
FreeScout version: 1.8.140 
Database: MySQL 
Are you using CloudFlare:  No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
> How do I change the font and color of the text in the customers fields? Maybe some other module is needed?

It's not possible. Unfortunately there is no such module for now. 
Feel free to submit a feature request: https://freescout.net/request-feature/
