### ISSUE TITLE
Search and exact match

### ISSUE THREAD

**Issue by dabesa** [freescout-helpdesk/freescout#4029]
Dear support,

It looks like the search only works on exact match.
Does it change with Faster Search Module or is there a syntax to use to search for multiple words in broad search?

Thanks

**Comment by freescout-helpdesk** [comment]
Not only exact match: https://demo.freescout.net/search?q=tes

**Comment by dabesa** [comment]
Yes, the search also works with partial match.

My question is regarding this scenario:
String: "one two three"
How to search for "one three" and get the conversation with "one two three" as result?
Is it possible?


Thank you

**Comment by freescout-helpdesk** [comment]
It's not possible. Maybe Faster Search will be able to do it.
