### ISSUE TITLE
queue:work latest run ?

### ISSUE THREAD

**Issue by wauwturrr** [freescout-helpdesk/freescout#403]
Hi guys,

I've added the default cron to the crontab, and receiving mails and stuff, but queue:work is still receiving an error:

![image](https://user-images.githubusercontent.com/16634704/71665382-00fcd700-2d5d-11ea-8995-10d0f77e2ba4.png)

Cache have been cleared quite some times now.

**Comment by freescout-helpdesk** [comment]
Are all of your mailboxes have correct connection configured?

**Comment by wauwturrr** [comment]
Hi there!

Yes they have.

**Comment by freescout-helpdesk** [comment]
If there are no erros in `Manage --> Logs --> Fetch Errors` you mayb need to debug https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php

**Comment by wauwturrr** [comment]
The latest error in the logs is: 

Error: imap_open(): Couldn't open stream {mail.woutr.io:993/imap/ssl}. TLS/SSL failure for mail.woutr.io: SSL negotiation failed; File: /www/html/overrides/Webklex/IMAP/Client.php (230)

**Comment by kaibrune** [comment]
![Bildschirmfoto 2020-01-02 um 15 32 51](https://user-images.githubusercontent.com/33369042/71672067-33b2c980-2d75-11ea-97b4-dd99d598b7cd.png)

Same error for me... getting the same error as @wauwturrr. After clearing the cache it works again for 5 Minutes.

**Comment by kaibrune** [comment]
In addition I'm getting on some cron jobs the error "killed".

**Comment by freescout-helpdesk** [comment]
@wauwturrr connection of one of your mailboxes is not working properly.

@kaibrune your issue is different: https://github.com/freescout-helpdesk/freescout/issues/384

**Comment by kaibrune** [comment]
@freescout-helpdesk but I'm getting the same error as @wauwturrr got.

**Comment by wauwturrr** [comment]
@freescout-helpdesk how is it possible that i receive tickets then? 😉

**Comment by Jatarii** [comment]
Try to disable the verification of the certificate. Reset the cache (follow the link from your first screenshot) and it worked for me.

**Comment by wauwturrr** [comment]
Thanks for not solving the problem and closing man. Lots of love.

**Comment by freescout-helpdesk** [comment]
> Thanks for not solving the problem and closing man. Lots of love.

Detailed bug report or pull request are welcome.
