### ISSUE TITLE
Connect FreeScout to Microsoft 365 Exchange

### ISSUE THREAD

**Issue by elg0ch0** [freescout-helpdesk/freescout#4031]
How can I connect FreeScout to Microsoft 365 Exchange if my Freescout instance is not accessible from the internet?
[This document](https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth) describes how to perform oAuth authentication but requires your Freescout instance to be accessible from MS365 (setting the  Redirect URI)

Environment description:
PHP version: 8.2.4
FreeScout version: 1.8.71
Database: MySQL / PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: No

Thx

**Comment by innov2e** [comment]
What you're asking seems strange to me: You want connect your FreeScout to an Internet service (Microsoft 365 Exchange) whitout be connected to Internet? You cannot, the MS365 need to see the Freescout instance in order to return to it the oAuth result!

**Comment by elg0ch0** [comment]
I don't want to expose publicly my Freescout instance (HTTPs) but I want it to fetch emails from MS 365 

` You cannot, the MS365 need to see the Freescout instance in order to return to it the oAuth result!
`

no option then?

**Comment by freescout-helpdesk** [comment]
You can try to enter local address of your FreeScout as "Redirect URI".

**Comment by elg0ch0** [comment]
> You can try to enter local address of your FreeScout as "Redirect URI".

What do you mean by local address?
Freescout's public address? --> I want to avoid exposing it to the internet
Freescout's private address? --> MS365 can not reach it (as expected)

I guess my question is more like this: Is there any option, other than using OAuth, for Freescout to fetch emails from MS365 ?

**Comment by elg0ch0** [comment]
`Is there any option, other than using OAuth, for Freescout to fetch emails from MS365 ?
`
It looks like there is no other option:

[Basic Authentication for Exchange online is deprecated](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)
