### ISSUE TITLE
Send Later Module - "Schedule Send" not working

### ISSUE THREAD

**Issue by jaydio** [freescout-helpdesk/freescout#4032]
Hi folks,

the "schedule send" function provided by the "Send Later" module stopped working.

When clicking "schedule" nothing happens, the ticket isn't updated.

Tested with several browsers, including Firefox (v125.0) and Chromium (124.0.6367.78).

This issue can be reliably replicated using the official freescout demo (https://demo.freescout.net/).

PHP version: 8.2.19
FreeScout version: 1.8.140
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by jaydio** [comment]
- No errors in app log file
- Cleared application cache via System -> Tools -> Clear Cache
- Migrated Database via System -> Tools -> Migrate DB
- Tried to Enabled/Disable the module

**Comment by freescout-helpdesk** [comment]
![2024-05-17_20-55-20](https://github.com/freescout-helpdesk/freescout/assets/40499291/a97a3d59-9305-4e01-a080-c80624fc32d3)
https://freescout.net/module/send-later/

**Comment by jaydio** [comment]
Just tried that and it sent the message straight away. Damn...

**Comment by jaydio** [comment]
Was this behavior changed at some stage? I can remember that it used to schedule the messages when clicking "schedule". It's definitely not obvious and currently not working, I'd suggest changing the behavior to make this more obvious.

**Comment by jaydio** [comment]
Tried it on a new conversation, and scheduling is working. Weird stuff. To avoid these accidents, pretty please change the behavior, so that the message is scheduled when user clicks "schedule" instead of two steps and it not being obvious whether it's set to be scheduled or not.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by jaydio** [comment]
Can you handle an adjustment to improve the user experience from a paying user without putting them through the wringer? I've bought almost all the modules across multiple instances. Cheers! ;-)
