### ISSUE TITLE
Error with composer install

### ISSUE THREAD

**Issue by jogehl** [freescout-helpdesk/freescout#4033]
Hi, I have problems when using the composer.json. Is there a way to update the packages?
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mews/purifier 3.2.2 -> satisfiable by mews/purifier[3.2.2].
    - mews/purifier 3.2.2 requires php ^7.2 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires spatie/laravel-activitylog 2.7.0 -> satisfiable by spatie/laravel-activitylog[2.7.0].
    - spatie/laravel-activitylog 2.7.0 requires php ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires fzaninotto/faker v1.9.2 -> satisfiable by fzaninotto/faker[v1.9.2].
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 4
    - Root composer.json requires doctrine/inflector v1.2.* -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 5
    - Root composer.json requires doctrine/annotations v1.4.* -> satisfiable by doctrine/annotations[v1.4.0].
    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 6
    - Root composer.json requires doctrine/cache v1.6.* -> satisfiable by doctrine/cache[v1.6.0, v1.6.1, v1.6.2].
    - doctrine/cache[v1.6.0, ..., v1.6.2] require php ~5.5|~7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 7
    - Root composer.json requires doctrine/collections v1.4.* -> satisfiable by doctrine/collections[v1.4.0].
    - doctrine/collections v1.4.0 requires php ^5.6 || ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 8
    - Root composer.json requires webmozart/assert 1.3.0 -> satisfiable by webmozart/assert[1.3.0].
    - webmozart/assert 1.3.0 requires php ^5.3.3 || ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
  Problem 9
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your php version (8.2.19) does not satisfy that requirement.
    - laravel/framework v5.5.40 requires doctrine/inflector ~1.1 -> satisfiable by doctrine/inflector[v1.2.0].
    - Root composer.json requires laravel/framework v5.5.40 -> satisfiable by laravel/framework[v5.5.40].`

PHP version: 8.2.19
FreeScout version: 1.8.140
Database: Mariadb
Are you using CloudFlare:No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
> When running composer commands always add --ignore-platform-reqs flag.

https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow

**Comment by Mythique** [comment]
Could the composer.json be updated to not require the `--ignore-platform-reqs`?

It's a bit too error prone, and messes up some workflow (for example the git deployment in plesk, it automatically try to run composer install, but fail and break the website until the proper commands are run).
