### ISSUE TITLE
FWD is Not working

### ISSUE THREAD

**Issue by szucher** [freescout-helpdesk/freescout#4036]
Hi,

i forward a mail to my FreeScout Mailbox. I removed the Signatur and the First in the Mail is @fwd

Why its Not working that FreeScout Open a ticket as the original Sender?

Here the Text from FreeScout:
```
<div dir="ltr">
<div id="mail-editor-reference-message-container" class="ms-outlook-mobile-reference-message" dir="ltr">
@fwd
<div id="" class="" dir="ltr">
<br>
</div>
</div>
<div class="ms-outlook-mobile-reference-message">
<div id="divRplyFwdMsg" dir="ltr"><font face="Calibri, sans-serif"><b>Von:</b> Lexmark OnePrint <donotrespond@commerce.lexmark.com><br>
<b>Gesendet:</b> Dienstag, Mai 21, 2024 4:41 PM<br>
```

**Comment by freescout-helpdesk** [comment]
Here is the place to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L647

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
