### ISSUE TITLE
Knowledge Base does not show all categories

### ISSUE THREAD

**Issue by kleingeld-de** [freescout-helpdesk/freescout#4038]
PHP version:  8.2.19
FreeScout version: 1.8.140
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

In the knowledge base:
I have created 4 categories.
3 categories are visible to all.
1 category is only visible to the support agents.
Anonymous access from the Internet only shows the 3 public categories.
Access by a logged-in agent shows all 4 categories.
So far everything is okay.

But when I create a "custom domain" and try to access the knowledge base, only the 3 public categories are displayed. 
Regardless of whether I want to access the page as an anonymous user or as a logged-in agent.

Does anyone else have the same problem or know how to fix it?

Thx,
Jens
(thanks to deepl for the translation)

**Comment by freescout-helpdesk** [comment]
See "Custom Domain" section at https://freescout.net/module/knowledge-base/

**Comment by kleingeld-de** [comment]
Sorry, my mistake. I overlooked this reference:
_"Keep in mind that when a Custom Domain is used for the Knowledge Base categories visible to support agents only may not be visible even when support agent is logged in."_
