### ISSUE TITLE
Attachments smime.P7s : howto hide or remove ?

### ISSUE THREAD

**Issue by marcatsmci** [freescout-helpdesk/freescout#4039]
PHP version: 8.0.30
FreeScout version: 1.8.140
Database: Mysql (10.11.6-MariaDB-0+deb12u1)
Are you using CloudFlare: No
Are you using non-official modules: No
Module Mail Signing & Encryption is active

Hi !

![image](https://github.com/freescout-helpdesk/freescout/assets/47881838/c7b62ff6-060b-44b6-974b-1bc51529245f)

Smime attachments pollute the attachment list and are useless for tracking problems. 

How can we hide or delete them?

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such possibility.
