### ISSUE TITLE
Webnotifications

### ISSUE THREAD

**Issue by Jatarii** [freescout-helpdesk/freescout#404]
Hi

In order to web notifications to work, do I need to have the module Mobile Notifications? 
Because it doesn't work now...

Thanks!

**Comment by freescout-helpdesk** [comment]
No

**Comment by Jatarii** [comment]
You have some ideas what could go wrong then?

**Comment by freescout-helpdesk** [comment]
- If browser push notifications are not working make sure that HTTPS is configured.
- Make sure user has properly configured notification settings.
- Check app logs in Manage » Logs.

**Comment by Jatarii** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/18144491/71765702-4570aa00-2ef8-11ea-9d75-36afd6db6fab.png)

- If browser push notifications are not working make sure that HTTPS is configured. **Check!**
- Make sure user has properly configured notification settings. **Check!**
- Check app logs in Manage » Logs. **Check!**

**Comment by freescout-helpdesk** [comment]
Sorry. It looks like you may need to find out the reason of the problem by yourself.
