### ISSUE TITLE
Search in Tags

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#4040]
PHP version: 8.1
FreeScout version: latest
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: Yes 

I would love to search in our tags:
You can imagine this takes some time to search them :-)
https://capture.dropbox.com/QktydS3dkKbLUzrC

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
