### ISSUE TITLE
"All from current mailbox" search option does not work properly when viewing a conversation

### ISSUE THREAD

**Issue by fredralm** [freescout-helpdesk/freescout#4041]
Hi,

We have noticed that the seach option "All from current mailbox" does not follow expected behaviour when a conversation is selected. From the search url it seems like the search uses the conversation id instead of the mailbox id when a conversation is selected and "All from current mailbox" is clicked. 

When I search from the mailbox 1 landing page I get this url suffix:
"search?f%5Bmailbox%5D=1"
When I search from mailbox 1 and selecting a conversation with conversation id 54 I get this suffix:
"search?f%5Bmailbox%5D=54"

It seems to me like there is some problem with getting the proper id here, and it makes the search unintuitive and hard to use for our users. Any help or fix would be greatly appreciated.

PHP version: 8.2.18
FreeScout version: 1.8.135
Database: PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
We've removed "All from current mailbox" link from the conversation page.
