### ISSUE TITLE
Older and Newer Arrows do not work

### ISSUE THREAD

**Issue by minnten** [freescout-helpdesk/freescout#4042]
PHP version: 8.2
FreeScout version: 1.8.140 
Database: MariaDB
Are you using CloudFlare: No
Are you using non-official modules: Yes

I am using the Tags and Folder-Module to sort my Tickets.

As I went into a Folder and open up a Ticket, everything works as expected. But if I use the newer and older Buttons on the right upper corner, I only can switch between 2 Tickets, not between all Tickets in this folder.

This happens to me in all non Standard-Folders, so in all Folders, I created with the Folder-Module.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Maybe there are some extra conditions to reproduce it. Try to record a video for example.

**Comment by minnten** [comment]
Hello, 

here is a short video with the problem:


[https://github.com/freescout-helpdesk/freescout/assets/50588960/6ae2c7a6-336a-43cb-8884-1339f70ae1a0](https://github.com/freescout-helpdesk/freescout/assets/50588960/6ae2c7a6-336a-43cb-8884-1339f70ae1a0)

One thing came to my mind, could it be a problem, that I use a ü in the markings?

**Comment by minnten** [comment]
This is my actual list, everything that is activated is up to date:

![Bildschirmfoto vom 2024-05-28 18-47-48](https://github.com/freescout-helpdesk/freescout/assets/50588960/33666e39-84b5-4238-923b-066bc00c1f41)

**Comment by freescout-helpdesk** [comment]
The only way to figure it out is for someone to check it on your server.

Here is the place to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Conversation.php#L674
