### ISSUE TITLE
E-Mail with Subject "Die E-Mail-Aktualisierung konnte nicht durchgeführt werden"

### ISSUE THREAD

**Issue by TrendShed** [freescout-helpdesk/freescout#4044]
Good day,

We get E-Mails with Subject "Die E-Mail-Aktualisierung konnte nicht durchgeführt werden"
Text of these E-Mails: "Zum Aktualisieren eines Gesprächs muss von der gleichen E-Mail-Adresse wie in Ihrem Benutzerkonto geantwortet werden. Zum Aktualisieren bitte erneut versuchen und von der E-Mail-Adresse des Benutzerkontos aus senden (von der E-Mail, die zum Login benutzt wird).“

What exactly triggers this email and what do we need to consider / do differently?
It is also unclear whether there was an email that was not sent.
Is this email because we get an email on one mail box and send the answer with another mail-box / e-mail-address?
What can we do to avoid this email?

Thanks!
Ronald

PHP version: 8.2
FreeScout version: 1.8.130
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
It means your support agents are trying to reply to the email notification from some random email. They should reply from the email address they have in your FreeScout or you should add extra emails to user's "Alternate Emails" on user's profile page.

 _"If you are trying to update a conversation, remember you must respond from the same email address that's on your account. To send your update, please try again and send from your account email address (the email you login with)."_

https://github.com/freescout-helpdesk/freescout/blob/2d871f27590424e2a33368878a01dd41ebb462e1/resources/lang/de.json#L343

**Comment by TrendShed** [comment]
Thank you very much!


Viele Grüße

Ronald 

-------------------------
TrendShed GmbH
Trenntrader Weg 27
24149 Kiel

T: 0431 221 399 85
F: 0431 221 399 81

USt-ID-Nr.: DE278027809
WEEE-Reg.-Nr.: DE 18460083
Geschäftsführer: Ronald Rathje
Handelsregister Amtsgericht Kiel
Handelsregisternummer: HRB 13032 KI
-----------------------------------------------------------
Support unterstützt durch FreeScout - Kostenloser quelloffener Helpdesk & geteiltes Postfach
