### ISSUE TITLE
Thunderbird Message Truncated Bug Returns (Formerly Issue #3580)

### ISSUE THREAD

**Issue by bcampano** [freescout-helpdesk/freescout#4045]
Unfortunately, the truncation bug reported and previously fixed in issue #3580 has reappeared in a recent upgrade of FreeScout. Same conditions and same ease to recreate. Perhaps the fix was lost in one of the newer builds?

We are currently running 1.8.140 and it is exhibiting the same issues as previously reported.

Please advise if you need me to perform any additional testing!

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.
