### ISSUE TITLE
API Webhooks module via Zapier with woocommerce | conversation could not be sent to FreeScout. The app returned "Error occurred"

### ISSUE THREAD

**Issue by tuton012** [freescout-helpdesk/freescout#4046]
I am currently having an issue getting Zapier to work with FreeScout. I keep getting 

Failed to create a conversation in FreeScout

The app returned "Error occurred.".

There is nothing in the FreeScout logs, and Zapier only provides that error with no logs. I can't figure out why the error occurs. I try deactivating stuff here and there, but it won't work. 
I want Zapier to create a conversation when a new order is created in WooCommerce; it gets connected to WooCommerce but not FreeScout. 

Api Module version: 1.0.78
Server: nginx/1.25.5

<img width="1580" alt="Screenshot 2024-05-29 at 12 38 23 AM" src="https://github.com/freescout-helpdesk/freescout/assets/108067270/2d4abab5-c2d3-49ad-9eab-1545bac18964">

-->

PHP version:  8.2.19
FreeScout version: 1.8.140
Database: Mysql (10.11.8-MariaDB-ubu2204)
Are you using CloudFlare: Yes 
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
Most likely the problem is in CloudFlare or some other proxies blocking requests to your FreeScout.

**Comment by tuton012** [comment]
> Most likely the problem is in CloudFlare or some other proxies blocking requests to your FreeScout.

I pause cloudflare and still does it, I check the waf event logs and theres nothing there either

**Comment by freescout-helpdesk** [comment]
The only way to find out the reason is for someone to debug it on your server.

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by tuton012** [comment]
> The only way to find out the reason is for someone to debug it on your server.
> 
> https://github.com/freescout-helpdesk/freescout/wiki/Debugging

I did that and there's this error

<img width="1388" alt="Screenshot 2024-06-01 at 12 15 31 AM" src="https://github.com/freescout-helpdesk/freescout/assets/108067270/acf5cdec-194e-4d72-a302-df7123860f00">

**Comment by freescout-helpdesk** [comment]
Try https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory
