### ISSUE TITLE
Uncapitalized Freescout in page title

### ISSUE THREAD

**Issue by Brugman** [freescout-helpdesk/freescout#4048]
PHP version: 8.2.19
FreeScout version: 1.8.140
Database: MySQL
Are you using non-official modules: No

Why is my dashboard title `Dashboard - Freescout` instead of `Dashboard - FreeScout`? (more pages are affected by this)

![2024-05-30-00-42-41](https://github.com/freescout-helpdesk/freescout/assets/2203813/c9a381e9-8f3b-4ba9-a573-65749b1864c0)

[config/app.php](https://github.com/freescout-helpdesk/freescout/blob/dist/config/app.php#L34) has the name capitalized, and [the layout template](https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/layouts/app.blade.php#L13) has a capitalized fallback. What else could cause this?

**Comment by freescout-helpdesk** [comment]
We don't know. Only you can figure it out on your server.

![2024-05-30_08-11-33](https://github.com/freescout-helpdesk/freescout/assets/40499291/9a46ea90-f3ad-4a3c-93c7-d194077c3374)

**Comment by Brugman** [comment]
It's a completely fresh Docker install tho. I'm interested in customizing but I haven't done a single thing yet.

**Comment by freescout-helpdesk** [comment]
It's due to uncapitalized spelling in the Docker config: https://github.com/tiredofit/docker-freescout/issues/181

**Comment by Brugman** [comment]
Gotcha! Sorry for bringing it to the wrong repo.
