### ISSUE TITLE
Teams Module permissions 

### ISSUE THREAD

**Issue by anxodio** [freescout-helpdesk/freescout#4049]
```
PHP version:  	PHP 8.3.6
FreeScout version: 1.8.138
Database: Mysql (8.0.36-28) 
Are you using CloudFlare: No
Are you using non-official modules: No
```

When I create a Team, I add some members to it, and I grant access to some mailbox for that team, the users added can't see the mailbox. They need also an individual permission to see and access the mailbox.

I would expect that the team permissions are inherited by the team members, but something is not working (or maybe it's not a feature?)

Or maybe I have done something wrong, but I tried it a couple of times and I don't know what can I do.

Thank you :)

**Comment by freescout-helpdesk** [comment]
For now Teams only allow to assign a conversation to a group of users. But those users need to be added to the mailbox manually.

**Comment by anxodio** [comment]
Oh, so this feature is not implemented! And why a team have a permissions management? And there is any idea of implement this feature in the near future? :)

**Comment by freescout-helpdesk** [comment]
It determines in which mailboxes the Team will be available for assigning conversations.

**Comment by anxodio** [comment]
I close the issue because I was asking for a new feature, it's not a real issue
