### ISSUE TITLE
Failing cronjob

### ISSUE THREAD

**Issue by kaibrune** [freescout-helpdesk/freescout#405]
Hi, 
after some debugging, I'm getting a error when running the cronjob.

  ```
In Filesystem.php line 122:
                                                                               
file_put_contents(/var/www/vhosts/httpdocs/support.domain.com/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdf  
  f8): failed to open stream: No such file or directory  
```

I cleared the cache and all directories have sufficient permissions. I checked the file and it is there. 

In addition I'm getting these errors when running the cronjob the first time after clearing the cache:

```
Running scheduled command: '/opt/plesk/php/7.3/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/opt/plesk/php/7.3/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '/opt/plesk/php/7.3/bin/php' 'artisan' freescout:fetch-emails > '/var/www/vhosts/httpdocs/support.domain.com/storage/logs/fetch-emails.log' 2>&1
Running scheduled command: '/opt/plesk/php/7.3/bin/php' 'artisan' queue:work --queue='emails,default,c60938b1bbfb84c7e5b67bf430faa576' --sleep=5 --tries=1 > '/var/www/vhosts/httpdocs/support.domain.com/storage/logs/queue-jobs.log' 2>&1
Killed
```

Somehow the task gets killed after running the last line. Any help is appreciated!! :)

**Comment by freescout-helpdesk** [comment]
Not all permissions are ok in one of the folders: /storage/framework/cache/data/

**Comment by kaibrune** [comment]
I checked all of them, even increased them to 777. Still getting the mistake when running:

`/opt/plesk/php/7.3/bin/php -f 'httpdocs/support.domain.com/artisan' -- 'schedule:run' &> httpdocs/error.log`

**Comment by kaibrune** [comment]
@freescout-helpdesk Any ideas?

**Comment by freescout-helpdesk** [comment]
> @freescout-helpdesk Any ideas?

Unfortunately, not.

**Comment by bencgreen** [comment]
After a number of times where for some reason permissions went a bit awry, I've created a little bash script to run from my home folder periodically if / when I get permissions issues.  Obviously you need to change the chown and username commands to whatever user you run Freescout as.

```
#!/bin/bash

chown www-data:www-data /path/to/root
cd /path/to/root
chgrp -R www-data storage bootstrap/cache public/css/builds public/js/builds
chmod -R ug+rwx storage bootstrap/cache public/css/builds public/js/builds
cd ~
```

Apologies if I'm teaching you to suck eggs!
