### ISSUE TITLE
selecting the recipient from the list of email addresses to the client's card

### ISSUE THREAD

**Issue by VovaSnova** [freescout-helpdesk/freescout#4057]
If I want to reply to a customer or create a new support ticket, or copy and paste an email address from a list of addresses associated with a customer's account, the email will always be sent to the first address in the list. Is it possible to ensure that when selecting an address from the saved list, the ticket is always sent to the correct person, rather than the first person in the list?
![Screenshot_49](https://github.com/freescout-helpdesk/freescout/assets/169980093/db78fd07-602f-4198-af71-3adf40145f13)
![Screenshot_50](https://github.com/freescout-helpdesk/freescout/assets/169980093/5bba5757-c9e3-4874-b76d-d75e22023f91)

PHP version: PHP 8.1.12-1ubuntu4.3
FreeScout version: 1.8.140
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by VovaSnova** [comment]
In addition, if the client responds to a request, and if there are multiple email addresses listed on the client's account, it can be difficult to determine which address the response originated from. This information can only be found in the headers of the emails.

**Comment by freescout-helpdesk** [comment]
When replying to the ticket FreeScout automatically preselects customer's email address from which he/she sent the last message.

**Comment by VovaSnova** [comment]
> When replying to the ticket FreeScout automatically preselects customer's email address from which he/she sent the last message.

If an email arrives from the email addresses linked to the client's card and a new ticket is created, the ticket itself does not show which specific email address the request came from, only the client's name and a list of all the client's email addresses are visible at once.  The only way to identify the sender is to look at the email headers.
