### ISSUE TITLE
How to see the sender's email address when there are multiple email addresses listed on a client's contact card.

### ISSUE THREAD

**Issue by VovaSnova** [freescout-helpdesk/freescout#4059]
If a new ticket is received from a customer with multiple email addresses listed on the card, it is not possible to see the specific email address of the person who sent the message. Is there a way to make the sender's address visible in the body of the ticket? Currently, I can only view this information in the headers of the email.
![Screenshot_5](https://github.com/freescout-helpdesk/freescout/assets/169980093/d80f5479-4723-48a8-a05f-bf2d41af7681)

PHP version: PHP 8.1.12-1ubuntu4.3
FreeScout version: 1.8.141
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch and will be published in the next release.
