### ISSUE TITLE
How do we see what conversations we are following?

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#406]
As per subject - Is it just showing notifications when a conversation is being followed? Is there a possibility that this can be enhanced with a new "Folder" showing "Following" ?

**Comment by freescout-helpdesk** [comment]
It is possible. "Follow conversation" is the core functionality.

**Comment by freescout-helpdesk** [comment]
Also it can be implemented via search filter "Following", this way support agent can see conversations he is following across all the mailboxes.

**Comment by tiredofit** [comment]
Many thanks!
