### ISSUE TITLE
"Error: mailbox is empty" and emails with headers shown since updating from 1.8.115 to 1.8.141

### ISSUE THREAD

**Issue by webdados** [freescout-helpdesk/freescout#4060]
Hi,

I have 5 mailboxes on my FreeScout install and all of them are on the same server, same cPanel account, and all are fetched via POP3 with the exact same configuration:

<img width="555" alt="Screenshot 2024-06-06 at 15 19 32" src="https://github.com/freescout-helpdesk/freescout/assets/6853605/c28182d8-cbde-4d6f-a3d9-3e8df0b3c4f0">

Since the last update, I'm getting random "Mailbox is empty" errors on some of the accounts (not always the same accounts) even if they have emails waiting to be fetched (confirmed by accessing the email account via cPanel webmail). Even if they were actually empty, the output in the log should have been "Fetched: 0" and not "Mailbox is empty".

Sometimes it takes more than 24h to the fetch finally works and I'm getting emails with very long delays.

Crons are properly set, as you can see by the "Error fetching email" Date on logs:
<img width="475" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/6853605/1acb417a-ad28-4b42-86e6-00ba9947537a">

```
[2024-06-06 15:11:44] Fetching UNREAD emails for the last 3 days.
[2024-06-06 15:11:44] Mailbox: A
[2024-06-06 15:11:44] Folder: INBOX
[2024-06-06 15:11:44] Fetched: 0
[2024-06-06 15:11:44] Mailbox: B
[2024-06-06 15:11:44] Error: Mailbox is empty; File: /.../vendor/webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php (103)
[2024-06-06 15:11:45] Mailbox: C
[2024-06-06 15:11:45] Folder: INBOX
[2024-06-06 15:11:45] Fetched: 0
[2024-06-06 15:11:45] Mailbox: D
[2024-06-06 15:11:45] Folder: INBOX
[2024-06-06 15:11:45] Fetched: 0
[2024-06-06 15:11:45] Mailbox: E
[2024-06-06 15:11:45] Error: Mailbox is empty; File: /.../vendor/webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php (103)
[2024-06-06 15:11:45] Fetching finished
```

In other news, I also started getting email headers on the body of received messages, before the content (selected in blue below):
<img width="770" alt="Screenshot 2024-06-06 at 15 31 14" src="https://github.com/freescout-helpdesk/freescout/assets/6853605/fc59536d-ec5e-4d5c-b99c-bc0563b7dad7">

System info:
```
PHP version: 7.4.33
FreeScout version: 1.8.141
Database:  Mysql (5.5.5-10.6.18-MariaDB) 
Are you using CloudFlare: No
Are you using non-official modules: No
```

**Comment by freescout-helpdesk** [comment]
The "Mailbox is empty" issue has been fixed in the `master` branch and will be published in the next release.

Regarding the headers in the email body - create a new issue and send us the EML file of the email.

**Comment by webdados** [comment]
> The "Mailbox is empty" issue has been fixed in the `master` branch and will be published in the next release.

Nice!

> Regarding the headers in the email body - create a new issue and send us the EML file of the email.

How can I make my server and email address information private?
