### ISSUE TITLE
Displaying an article from the knowledge base.

### ISSUE THREAD

**Issue by VovaSnova** [freescout-helpdesk/freescout#4063]
If the article contains a lot of information, including tables, when you open it, you may need to use the scrollbar to see the entire content. However, there is plenty of free space on either side of the article. Is it possible to display the article in full screen without the need for scrollbars?
![Screenshot_8](https://github.com/freescout-helpdesk/freescout/assets/169980093/82df9192-a99b-4e68-9999-4940a496594c)

PHP version: PHP 8.1.12-1ubuntu4.3
FreeScout version: 1.8.141
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
Unfortunately there is no such plans.

**Comment by VovaSnova** [comment]
and how do you add this to your plans? You just need to remove the left column and move it to the top!

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/
