### ISSUE TITLE
Automatic linking of email addresses from the same domain with the client's card.

### ISSUE THREAD

**Issue by VovaSnova** [freescout-helpdesk/freescout#4065]
Is it possible to automatically link all tickets from a specific email domain, for example, @companyname.com, to a single "companyname" customer? I tried entering the address in the customer's profile in the format "*@companyname.com", but it didn't seem to work.

PHP version: PHP 8.1.12-1ubuntu4.3
FreeScout version: 1.8.142
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
There is no such feature for now.

**Comment by raramuridesign** [comment]
@VovaSnova What we have done is add variations of the emails to the users profile and then this pulls in the emails.
However you can only have one user, ie with multiple emails.
Hope this helps
M.
