### ISSUE TITLE
Auto Login Module does not ask for 2FA

### ISSUE THREAD

**Issue by kleingeld-de** [freescout-helpdesk/freescout#4068]
PHP version:  8.2.20
FreeScout version: 1.8.143
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No
Auto Login Module : 1.0.2
Two-Factor Authentication Module: 1.0.11

Hello,
our administrator has activated 2fa “Required For All Users”. 
When I want to login, I am asked for the second factor. That's Okay.
But when I click on a link in an email notification, I am logged in directly without having to enter a second factor. That is not okay.
The description of the Auto Login module says:
"If 2FA authentication is enabled the user will be required to pass two-factor authentication."

Is this a bug or have I forgotten to configure something?

Greetings,
Jens

**Comment by freescout-helpdesk** [comment]
It works as designed.

**Comment by kleingeld-de** [comment]
It works as designed. ???
Just so I understand correctly: the design is that the auto-login module **never** queries the second factor?

**Comment by freescout-helpdesk** [comment]
Yes.

**Comment by kleingeld-de** [comment]
But that makes this module a big security hole and I will probably have to switch it off :-(

In addition, your module description is not correct "_If 2FA authentication is enabled the user will be required to pass two-factor authentication._”. You should adjust it accordingly.

**Comment by freescout-helpdesk** [comment]
We've added a notice regarding the Auto Login process.

**Comment by TechTronicLLC** [comment]
This is still an issue. I agree with @kleingeld-de that it's both a major security vulnerability, and is not working as described, despite the assertion from @freescout-helpdesk that it's working as designed.

The [product page for the Auto Login module](https://freescout.net/module/auto-login/) plainly states "If 2FA authentication is enabled the user will be required to pass two-factor authentication." but this is not how it actually works. The URL in the emails allows full authentication with no 2FA prompt for a user with 2FA enabled. Changing the user's password does invalidate previous links, but future links still do not prompt for 2FA.

This renders the Auto Login module virtually useless for anyone that cares about security, which should be everyone.

**Comment by freescout-help** [comment]
It was a typo, it has been fixed now at https://freescout.net/module/auto-login/

![2024-12-31_08-12-18](https://github.com/user-attachments/assets/b9cba2c3-dcfc-4a6a-9154-4c4d6a46c9d1)
