### ISSUE TITLE
Ability to change tab title with (x) for outstanding notifications?

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#407]
My team has started using Freescout today after many months of dangling the concept to them. One of the comments that came out - was if there was a possibility to change the name of the Tab title in the browser for the oustanding notifications that have appeared?

e.g (3) - Dashboard   -- Meaning that there is 3 new notifications that need to be reviewed/cleared.

**Comment by freescout-helpdesk** [comment]
Not quite clear what you mean. Picture would be helpful.

**Comment by tiredofit** [comment]
Sorry I'm unclear here: This would be the <title> of the website itself, that automatically updated with the amount of notifications. Here's an example from gmail:

![image](https://user-images.githubusercontent.com/23528985/71909904-c6f94f80-3125-11ea-95de-4391ea5ac531.png)

**Comment by freescout-helpdesk** [comment]
Added to the todo.

**Comment by DanielBendersky** [comment]
Hi, is there any update on this? I will like to customize the page title. I already have purchased the module for customization, but I dont see any place to change the title. Thanks for any help.

**Comment by fulldecent** [comment]
This now appears to be implemented.

Recommending to close issue

<img width="1403" alt="Screenshot 2022-11-07 at 11 07 01" src="https://user-images.githubusercontent.com/382183/200357988-79d07b0a-0da7-4bb7-b9e5-6a96c95c1594.png">
