### ISSUE TITLE
Report -> Time tracking wrong IDs in Conversation section

### ISSUE THREAD

**Issue by krzysztofklonowski** [freescout-helpdesk/freescout#4071]
Hello,

I have a issue with reports (time tracking).

Like below in section "Conversation" IDs (number of ticket) are showing wrong.

On list I have number 184 but link provides to 221. 

![image](https://github.com/freescout-helpdesk/freescout/assets/167428698/f2897824-eecb-401e-8291-f0ffc985463c)

![image](https://github.com/freescout-helpdesk/freescout/assets/167428698/47721940-fbb3-4004-bbb0-3cf0fb03cf5f)

On conversation list showing number not ID, but ID is showing on ticket and this number (221) is a reference to ticket for customer.

![image](https://github.com/freescout-helpdesk/freescout/assets/167428698/7766901a-d677-466d-9636-ebcc44e53ba9)

We are waiting for fix.

Best regards,

Krzysztof Klonowski

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1.0.42

**Comment by krzysztofklonowski** [comment]
Thank you. Works.
