### ISSUE TITLE
Removing admin users from assignee in kanban view

### ISSUE THREAD

**Issue by cryptid1x** [freescout-helpdesk/freescout#4075]
Need to be able to hide users with admin access in "kanban view - group by - assignee" for specific mailboxes.

I have tried going into mailbox settings and marking users with the "hide from assign list".
Have tried taking users permission for the mailbox away.
Have had no luck with the above.

The only work around I saw for this was taking users admin privileges away, but we can't ideally do this need admin access to manage freescout.

**Comment by freescout-help** [comment]
Fixed in Kanban Mobule v1.0.23
