### ISSUE TITLE
Huge Database

### ISSUE THREAD

**Issue by shiroi2003** [freescout-helpdesk/freescout#408]
I'm receiving some messages from my host that MySQL are reaching about 10GB and I don't have even 10 messages on my mailbox, looks like it's logs. How can I solve that?

![Capturar](https://user-images.githubusercontent.com/2958083/71892077-d331dc80-3126-11ea-90f6-bcf11b695c65.PNG)

**Comment by freescout-helpdesk** [comment]
Just click "Clear Log".

**Comment by shiroi2003** [comment]
I'm not sure if it's just logs, usually logs are the huge table indeed?

**Comment by freescout-helpdesk** [comment]
Yes. You have several mailboxes with incorrect IMAP configuration.
