### ISSUE TITLE
Javascript errors everywhere

### ISSUE THREAD

**Issue by f-liva** [freescout-helpdesk/freescout#409]
Any page you visit there are problems with Javascript. Most interface actions do not work. Here are some of the errors reported in the console:

1:341 Uncaught ReferenceError: viewMailboxInit is not defined
    at 1:341

67c170ad5951969d1f570df9366d88411578404631.js:62 Uncaught TypeError: Cannot read property 'fn' of undefined
    at 67c170ad5951969d1f570df9366d88411578404631.js:62
    at 67c170ad5951969d1f570df9366d88411578404631.js:1
    at 67c170ad5951969d1f570df9366d88411578404631.js:1
(anonymous) @ 67c170ad5951969d1f570df9366d88411578404631.js:62
(anonymous) @ 67c170ad5951969d1f570df9366d88411578404631.js:1
(anonymous) @ 67c170ad5951969d1f570df9366d88411578404631.js:1
1?folder_id=1:522 Uncaught ReferenceError: initReplyForm is not defined
    at 1?folder_id=1:522

**Comment by f-liva** [comment]
Solved with php artisan storage:link

**Comment by fulldecent** [comment]
More specifically, this is the fix:

```sh
php /var/www/html/artisan storage:link
```
