### ISSUE TITLE
Remove admins from Assignee dropdown

### ISSUE THREAD

**Issue by ePascalC** [freescout-helpdesk/freescout#410]
In an environment with multiple mailboxes connected, when opening an email and clicking the dropdown to assign the email to someone, also the admins are listed.
In most cases the admins are only dealing with the pure admin side of FreeScout and will not necessary work on the emails.

Proposal to have a general button in the permissions of each mailbox (e.g.  http://example.com/mailbox/permissions/3) with possibility to exclude admins from showing up in the assignees, but of course still keeping the access for them to all mailboxes.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/456
