### ISSUE TITLE
Manually add customer conversation / reply to phone conversation by email

### ISSUE THREAD

**Issue by bencgreen** [freescout-helpdesk/freescout#411]
Often when I receive a phone call and create a ticket, I would like to reply to it by email (when I know the customer's email address as well as their phone numbers).

Also, I often get emails sent directly to me, rather than the helpdesk address (as the helpdesk is a new addition, people are used to emailing me directly).  So I would like to be able to manually add a ticket that I can then reply to (by email) through Freescout.

I cannot work out how to do this, so either a) could someone tell me, or b) could this be a feature request, please?

**Comment by freescout-helpdesk** [comment]
Use "New Conversation" button (below folders).

**Comment by bencgreen** [comment]
Does that not send an email to a customer, rather than log an email from a customer?

**Comment by bencgreen** [comment]
(Also, I am aware of that button - hence the opening phrase 'Often when I receive a phone call and create a ticket'.)

**Comment by freescout-helpdesk** [comment]
```
So I would like to be able to manually add a ticket that I can then reply to (by email) through Freescout.
```
No plans for now.
