### ISSUE TITLE
How to delete a failed job

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#413]
I have a job failed to send due to the wrong email.

But I don't see the delete button. Which then the system sends 114 emails to remind about this failed job. 

How to delete this failed job? 

![Screenshot 2020-01-13 at 10 52 01 AM](https://user-images.githubusercontent.com/5198092/72230825-f2cb7800-35f2-11ea-9c84-de702f515ac9.png)

**Comment by freescout-helpdesk** [comment]
> Which then the system sends 114 emails to remind about this failed job.

Can you give an example of such reminder.

**Comment by sam-suresh** [comment]
![Image 14-01-2020 at 11 34 AM](https://user-images.githubusercontent.com/5198092/72312124-ff6ad180-36c1-11ea-9ef4-77fd64b4f77a.png)


While I understand why email failed- How do I stop this job from retrying?

**Comment by freescout-helpdesk** [comment]
Thanks. We will try to fix.

**Comment by sam-suresh** [comment]
Able to delete the failed job.
But it's still in the queue and keep trying. 

![Screenshot 2020-01-15 at 12 41 08 PM](https://user-images.githubusercontent.com/5198092/72405597-72dd1380-3794-11ea-86ed-f94bc45be163.png)

There is no option to view and remove it.

**Comment by freescout-helpdesk** [comment]
There is not option. Just leave it.
