### ISSUE TITLE
Installing Freescout on Godaddy Shared Hosting

### ISSUE THREAD

**Issue by diondkb** [freescout-helpdesk/freescout#415]
Hi,

Are there any guidelines/tutorials for installing Freescout on Godaddy CPanel Shared Hosting other than this more generic tut https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#7-restarting-services.

Thanks,
Dion

**Comment by sam-suresh** [comment]
I' not using shared hosting but this might work;
1. Download FS https://github.com/freescout-helpdesk/freescout/releases
2. Go to cPanel > File Manager
3. Upload outside `public_html` & Extract
4. Move all contents of the `public` folder to `public_html`
5. Visit your site to continue the installation. https://example.com/install

**Comment by diondkb** [comment]
Hi Sam,

My main wordpress website resides in the public_html folder. I have created a public_html/support folder and added it as a subdomain and extracted the downloaded freescout file here. I then copied the public_html/support/public folder contents to public_html/support, but get a white screen when running support.mydomain.com/install?

Any ideas?

Thanks

**Comment by sam-suresh** [comment]
For security reasons, you should not expose the .env files etc on public_html. 

1. Create subdomain and choose path outside public_html (this is possible with cPanel). So you ll have;

/public_html
/support
/Upload and extract freescout here

2. Move all contents of the public folder(from FS) to /support

3. Visit your site to continue the installation. https://support.example.com/install

**Comment by diondkb** [comment]
Hi Sam. I tried what you suggested and got the same white screen. I removed my previous installation and changed the subdomain doc root to /support. Are there any error messages I can enable and send to you?

Dion

**Comment by freescout-helpdesk** [comment]
Closing for now activity.

**Comment by diondkb** [comment]
What does Closing for now activity mean?

**Comment by diondkb** [comment]
I was waiting for your response to the second white screen?
