### ISSUE TITLE
Workflow Module: Remove Tags

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#416]
I have 2 workflows.

First Workflow Add `Overdue` tag if waiting for 3 days and `active`. 
Second Workflow Remove `Overdue` tag if status `pending`.

What I'm trying to do is FS to tag `overdue` if active and untag it after replied and become `pending`.

With this setup, only first Workflow working. Second one not working. 

Workflow 1:
![Screenshot 2020-01-15 at 12 01 47 PM](https://user-images.githubusercontent.com/5198092/72404011-debc7d80-378e-11ea-8dbb-840ff060f7eb.png)

Workflow 2:
![Screenshot 2020-01-15 at 12 05 11 PM](https://user-images.githubusercontent.com/5198092/72404150-4f639a00-378f-11ea-9e1c-dca9906d1445.png)

![Screenshot 2020-01-15 at 12 39 05 PM](https://user-images.githubusercontent.com/5198092/72405484-0cf08c00-3794-11ea-9256-04cec03b1bda.png)

**Comment by freescout-helpdesk** [comment]
If automatic workflow does not contain any date-condition (Waiting Since, Date Created, Last User Reply, Last Customer Reply), in order to trigger it you need to click "Save & Execute" or some other condition should happen (for example conversation status should change).
