### ISSUE TITLE
Update.sh fail

### ISSUE THREAD

**Issue by laTruffe79** [freescout-helpdesk/freescout#4178]
Hello,

I tried to update with the use of documented update.sh script but it fails with this error : 

[tiredofit/freescout:1.17.78 11:12:14 /] $ sudo www/html/tools/update.sh
Starting updating process: 2024-08-13_11:12:17
Make sure to create a backup of the application before you continue.
Application root: /www/html
sh: dist: unknown operand
Current branch: 
fatal: ambiguous argument '..origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
You already have the latest version of the application, no upgrade needed.

PHP version: 8.2.21
FreeScout version: 1.8.146
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Have you figured it out? What operating system are you using?
