### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#418]
FS 1.4.1

After update sometime Send error happens.

`Array to string conversion (View: /srv/users/XXXXXX/apps/XXXXXX/resources/views/emails/user/notification.blade.php) {"exception":"[object] (ErrorException(code: 0): Array to string conversion (View: /srv/users/XXXXXX/apps/XXXXXX/resources/views/emails/user/notification.blade.php) at /srv/users/XXXXXX/apps/XXXXXX/storage/framework/views/55de9f9a7030ad0fbbcccXXXXXXd51dd7ea18.php:69, ErrorException(code: 0): Array to string conversion at /srv/users/XXXXXX/apps/XXXXXX/storage/framework/views/55de9f9a7030ad0fbbcccc31b1a0e8d51dd7ea18.php:69)
[stacktrace]
#0 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/srv/users/help...', Array)
#2 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get('/srv/users/help...', Array)
#3 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(328): Illuminate\\View\\View->render()
#6 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(301): Illuminate\\Mail\\Mailer->renderView('emails/user/not...', Array)
#7 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(218): Illuminate\\Mail\\Mailer->addContent(Object(Illuminate\\Mail\\Message), 'emails/user/not...', 'emails/user/not...', NULL, Array)
#8 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send('emails/user/not...', Array, Object(Closure))
#9 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#10 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable(Object(App\\Mail\\UserNotification))
#11 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send(Object(App\\Mail\\UserNotification))
#12 /srv/users/XXXXXX/apps/XXXXXX/app/Jobs/SendNotificationToUsers.php(112): Illuminate\\Mail\\PendingMail->send(Object(App\\Mail\\UserNotification))
#13 [internal function]: App\\Jobs\\SendNotificationToUsers->handle()
#14 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#19 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\SendNotificationToUsers))
#20 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\SendNotificationToUsers))
#21 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\SendNotificationToUsers), false)
#23 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#24 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#26 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#27 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#28 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#29 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#30 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#31 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#33 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#34 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#35 /srv/users/XXXXXX/apps/XXXXXX/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#36 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#37 /srv/users/XXXXXX/apps/XXXXXX/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /srv/users/XXXXXX/apps/XXXXXX/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /srv/users/XXXXXX/apps/XXXXXX/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /srv/users/XXXXXX/apps/XXXXXX/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /srv/users/XXXXXX/apps/XXXXXX/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 {main}
"}
`

**Comment by freescout-helpdesk** [comment]
Could you please attach `/srv/users/XXXXXX/apps/XXXXXX/storage/framework/views/55de9f9a7030ad0fbbcccXXXXXXd51dd7ea18.php` file.

**Comment by sam-suresh** [comment]
Sent via email. Thank you.

**Comment by freescout-helpdesk** [comment]
The issue can not be reproduced. Try to clear the cache.

**Comment by sam-suresh** [comment]
After some digging, I found this is coming from the Workflow module.

I set a workflow to send an email to Person A. This is turning into an error and the email is not going out. 

![Screenshot 2020-01-16 at 4 50 58 PM](https://user-images.githubusercontent.com/5198092/72508409-91203d80-3880-11ea-84b0-6d6552b6f8ef.png)

**Comment by freescout-helpdesk** [comment]
Closing for now activity.
