### ISSUE TITLE
[workflow module] error when accessing settings and conversations

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#419]
Hi guys, thanks for the new module, excellent.
We have this running on 2 different projects, on the one it works perfectly on the other when the module is activated and we try to goto

1- the settings
2- view a conversation

We get the error

----

"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? {"userId":1,"email":"XXX@XXXXXXXXX.net","exception":"[object] (ErrorException(code: 0): \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? at /home/XXXXXXXXXXXXXX/public_html/Modules/Workflows/Entities/Workflow.php:732)

----

This error occurs on a CPANEL environment.
Not sure what else you need to troubleshoot this.

Please assist, thanks.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows v1.0.1

**Comment by raramuridesign** [comment]
Thanks, how long does it take to show in the backend for a one-click update?

**Comment by freescout-helpdesk** [comment]
15 min or clear cache

**Comment by raramuridesign** [comment]
Hi - so updated on system which was working no issues.
Cpanel environment throws the following errors
first error is accessing the conversation, second is accessing the workflow settings.
This is the latest version.

------

error | production | 2020-01-15 09:23:25 | "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? (View: /home/xxxxx/public_html/resources/views/conversations/view.blade.php) {"userId":1,"email":"xxxxx@xxxxx.net","exception":"[object] (ErrorException(code: 0): \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? (View: /home/xxxxx/public_html/resources/views/conversations/view.blade.php) at /home/xxxxx/public_html/Modules/Workflows/Entities/Workflow.php:882, ErrorException(code: 0): \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? at /home/xxxxx/public_html/Modules/Workflows/Entities/Workflow.php:882)
-- | -- | -- | --
error | production | 2020-01-15 09:22:20 | "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? {"userId":1,"email":"xxxxx@xxxxx.net","exception":"[object] (ErrorException(code: 0): \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? at /home/xxxxx/public_html/Modules/Workflows/Entities/Workflow.php:882)

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows v1.0.2

**Comment by raramuridesign** [comment]
Thanks, I can confirm that both systems with 1.0.2 are working.
We just need to test a workflow now.

Thanks for the quick response.
Matthew
