### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by nn-ui** [freescout-helpdesk/freescout#421]
Hi folks,
The application is so great.

I would like to request the following features:

workflows:
 - webhook support in conditions and actions in workflows
 - current date, time,datetime support with comparing - for office hours to prevent automated executing tasks like sending email to a customer at midnight.
 - access to custom fields from workflows, including comparing number values (larger than, lower than) of custom fields in workflows
 - access to ticket details like the body, attachments in webhooks 
 - make it possible to read/update customer details like email address using a webhook, for example when the customer has changed the email address, customer_id is set in the custom fields and the webhook endpoint could return new customer contact detail based on the customer_id in an external system
 

custom fields:
- optional lock of selected custom fields in single ticket, so just administrator or workflow could change it.
- datetime, time fields in custom fields
- hidden selected custom fields, for storing some of workflow results, additional parameters or data not accessible by agent, accessible by workflow or administrator

It would be great to have them.

My usage case would be to almost automatically process refund process and I believe they would be also useful for most FS users.

An example flow of it:

POST JSON request to API with some custom fields values and attached files/images or links to it.
```
POST http://example.com/api.php?action=refund&key=12345&agent_id=123
User-Agent: Example UA

```
POST fields would contain some of custom fields.

The JSON would return, for example 
```
{
"status": 1,
"transaction_number":"ABC12345",
"refund_progress": "processing",
"refund_amount: 123.45
}

```
The workflow would check if "status" is 1, then update the custom field "refund_progress" to processing, "transaction_number" to ABC12345, "last_query_date" to current date, and would query another webhook every day in order to check if the "refund_progress" changed to "processed" and then email the client with value of "refund_amount", close the ticket and then use a webhook in actions to contact another API.

The transaction_number or refund_progress would be needed to be locked - only workflow/administrator could change it.

Thanks.

**Comment by freescout-helpdesk** [comment]
No webhooks planned in workflows. Custom fields - maybe later.

**Comment by nn-ui** [comment]
@freescout-helpdesk thanks for reply. Are the webhooks planned somewhere?

**Comment by nn-ui** [comment]
@freescout-helpdesk thanks for reply. Are the webhooks planned somewhere?
They would really be useful with an combination of workflows.
If they would be available as a module, it would be also great.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/430

**Comment by freescout-helpdesk** [comment]
Access to custom fields from workflows implemented. Update to their latest version FreeScout, Custom Fields and Workflows module.

**Comment by freescout-helpdesk** [comment]
> webhook support in conditions and actions in workflows

What do you mean?
