### ISSUE TITLE
Reply box bug

### ISSUE THREAD

**Issue by nn-ui** [freescout-helpdesk/freescout#422]
Dragging a HTML context, for example a part of the user's message into the reply box breaks the page.

**Comment by fulldecent** [comment]
This appears to be fixed. I have just opened a reply box, drag-dropped something HTML from Google News and the page is not broken.

<img width="1733" alt="Screen Shot 2022-10-11 at 12 37 36" src="https://user-images.githubusercontent.com/382183/195150044-2463dddd-05ca-4f25-9e6c-05060b5cc699.png">

**Comment by freescout-helpdesk** [comment]
It probably depends on a dragged content. Anyway it seems to be out of our capacity to fix it.
