### ISSUE TITLE
Sorting User List when Assigning (and in User Table)

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#427]
We are relying on the LDAP module to import our users, and the way that LDAP works is that it sends the first entry regardless of sort order ever returned from LDAP. I'm not entirely sure if this is the case for local logins, but would we be able to sort the user list in an Alphabetical Order in the Assignment Screen and also the userlisting? Our users are getting confused.

**Comment by freescout-helpdesk** [comment]
Assignment Screen - can you give a screenshot

**Comment by tiredofit** [comment]
Reaching out to my user who made the request on the Assignment screen. I'm not seeing the same results.

However here is for Permissions for Mailbox Side:
![image](https://user-images.githubusercontent.com/23528985/72565663-34645900-3867-11ea-98a9-6da4f0edb899.png)

And master user list:

![image](https://user-images.githubusercontent.com/23528985/72565754-65dd2480-3867-11ea-8be9-f2360f641a5e.png)

-- Perhaps they were talking about Assigned via Search:

![image](https://user-images.githubusercontent.com/23528985/72565913-b81e4580-3867-11ea-92d4-04f7d3ba906b.png)

**Comment by tiredofit** [comment]
Many thanks.
