### ISSUE TITLE
No threads in customers inbox in postbox/thunderbird-fork

### ISSUE THREAD

**Issue by patricschwarz** [freescout-helpdesk/freescout#428]
While testing i figured out that the for support asking costomer gets single emails, not threaded emails in the inbox (postbox/thunderbird-fork)

**Comment by patricschwarz** [comment]
1. the "In-Reply-To:" Header is missing in responses
2. there is no option to add a "Re:" Tag to the subject (for auto-reply this option exists)

could you consider these two things for upcoming updates?

**Comment by freescout-helpdesk** [comment]
Adding "In-Reply-To:" will be fixed, this will be enough for grouping emails.
