### ISSUE TITLE
Edit conversation subject

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#43]
todo

**Comment by danielfaulknor** [comment]
I'd be keen to do this one, as I use it quite a lot in ZenDesk

**Comment by freescout-helpdesk** [comment]
Great. So you are welcome to implement it. See how it works in Help Scout.

**Comment by uptimizt** [comment]
does anyone plan to complete this task?

I think a good UX for this task can be copied from GitHub

@freescout-helpdesk 

P.S. if I take this problem, can I solve it using modules? do we have enough hooks?

**Comment by freescout-helpdesk** [comment]
When user clicks on the subject it should be converted into the editable input field.

**Comment by uptimizt** [comment]
> When user clicks on the subject it should be converted into the editable input field.

it is UX from Kayako. ok.

Can I do this through the module? or should I change the core?

**Comment by fvdm** [comment]
It works great! Thanks a lot.

Could you please add a line to the conversation history when the subject is changed?

For example: "Jon renamed conversation from 'Help!' to 'Schedule meet for project X demo'"
