### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by TimoStramann** [freescout-helpdesk/freescout#432]
Getting an error on Installation:  
`[17-Jan-2020 18:21:38 Europe/Berlin] PHP Notice:  Undefined variable: cipher in /home/user/public_html/support/public/install.php on line 34`

**Comment by TimoStramann** [comment]
Thanks. This fixed one issue but now another one appears:  

```
(1/1)   ErrorException   Trying to access array offset on value of type int
--
in ArrayInput.php line 135
at HandleExceptions->handleError(8, 'Trying to access array offset on value of type int', '/home/user/public_html/support/vendor/symfony/console/Input/ArrayInput.php', 135, array('value' => 'freescout:clear-cache', 'key' => 0))in ArrayInput.php line 135
```

**Comment by freescout-helpdesk** [comment]
Use PHP7.0 - PHP7.3 for now

**Comment by fvdm** [comment]
Please update the PHP check in the installer to not allow PHP v7.4 yet. I was battling with this problem and got errors that didn't mention anything useful. Until I found this issue and got to complete the setup.

**Comment by TimoStramann** [comment]
Any chance you'll upgrade the used Laravel version soon so we can use PHP7.4 which is the current standard?

**Comment by freescout-helpdesk** [comment]
Most likely not this year.
