### ISSUE TITLE
403 error after module installation

### ISSUE THREAD

**Issue by TimoStramann** [freescout-helpdesk/freescout#435]
I'm getting a 403 error after installing a module (not activating).  
`Auto Index is disabled for [/home/user/public_html/support/public/modules/], access denied`  
This is what I get on a cPanel standard installation with litespeed. I suppose this error occurs because after installing the module you're redirected to public/modules/ which is an empty directory but for public/modules/list you're getting to the actual modules overview.

**Comment by TimoStramann** [comment]
What I noticed additionally is that when I type `https://example.com/modules` (with no `/` behind modules), there's a redirect to `https://example.com/public/modules`. With that `/` at the end I get a 403 error because of autoindexing is disabled (as described in OP). The redirect should really go to `https://example.com/modules/list` (/modules **/list**).

**Comment by TimoStramann** [comment]
These errors also appear when updating the freesout app.


After upgrading freescout I'm redirected to the system folder (error 404) but get the following error:
![system](https://user-images.githubusercontent.com/21283057/76619847-1f850880-652c-11ea-943e-8cf9e4d0d083.JPG)

And after making changes to a module I'm redirected to modules folder (error 403):
![modules](https://user-images.githubusercontent.com/21283057/76619915-480d0280-652c-11ea-8d12-617215acf98b.JPG)

**Comment by freescout-helpdesk** [comment]
We never were able to reproduce this issue. It must be related to the hosting.
If someone can reproduce the issue please let us know or try to fix.

**Comment by Runoe** [comment]
I'm getting this error on it except I'm getting a 403 error
