### ISSUE TITLE
Workflow: Workflows are running just once for each conversation

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#436]
I found workflows are running once to each conversation. The same workflow is not running again to the applied conversation. I think this is not useful. 

Workflow: 
1. Conversation status is `Active` = assign tag `active` (for custom folder)
2. Conversation is `Viewed` = remove tag `active` and change status `Pending`

This works for the first time. 
When the User replies second time, by default mailbox setting the status is changed to Active but the workflow 1 is not triggering again.  

The workflow should run multiple times on the same conversation as long as the conversation meet the conditions.

**Comment by freescout-helpdesk** [comment]
No plans to make workflows running multiple times for now. Create multiple workflows if needed. Also feel free to adjust the module.

**Comment by nn-ui** [comment]
@sam-suresh I also believe implementing an infinite and a limited one amount of allowed workflow reruns would be useful as less workflows would make less confuse instead of having a lot more of them though.

**Comment by freescout-helpdesk** [comment]
If someone is able to implement running workflows unlimited times per conversation and avoid loops, we will be happy to update the module.

**Comment by sam-suresh** [comment]
I think this is a crucial feature for Workflow. So I hope this issue can stay open so someone else will consider sending a pull request. 

In an ideal situation, the workflow should be triggered by cron jobs. 
As long as the condition is met, the workflow should run always. 
This will not cause any harm as assigning a tag cannot be done multiple times if the tag already assigned. However, if someone removes a tag, next time the cron runs, and the workflow will assign the tag again as intended by the workflow. 
This kind of process will make the workflow highly useful and the integrity of the workflow conditions are always met.

**Comment by nn-ui** [comment]
I believe Sam's approach is quite nice, but digging deeper, there would be also need to decide what to do about when the actions are like forward or send email notification etc. Sending the same email notifications may not be nice though there might be cases when it would be appreciated. I believe there would be need to have an option for each trouble-making action what to do when such events - like sending the same email - has been already been executed in the same workflow, is the email content different or not, or maybe give it some time to rest and let to send it after 30th event change etc. I believe I found a similar approach in another system but sadly I did not recall the name of it.

**Comment by freescout-helpdesk** [comment]
Closing for now activity. If anyone interested, feel free to implement.

**Comment by Sleazified** [comment]
Can you please reconsider this? Maybe create an option to put in a max amout of runs pr conversation?

We bought the workflow module, and can´t use it as our usecase needs the workflows to run multiple times pr conversation.

**Comment by freescout-helpdesk** [comment]
We've added to workflows "Max Executions" parameter allowing to run automatic workflows multiple times per conversation.

**Comment by arjit65** [comment]
It would be nice if FreeScout gives an option in WorkFlow Module to select that 

1 whether trigger a new email to customer [ New Subject Line to be Inputted by user in mail Template

Or

2. To trigger email as reply [ as per existing feature ]

Use Case :  When the ticket is closed, a sperate email thread should appear to Customer in its Inbox.
