### ISSUE TITLE
Feature request: assign limitations

### ISSUE THREAD

**Issue by eric241** [freescout-helpdesk/freescout#445]
Hi

currently it is possible to change the assigned user in already assigned tickets by not only the original assigned user, but also by anyone.
I think the best option would be to add option to limit this to assigned user as currently it could be changed even by mistake by anyone when updating multiple tickets.

Thank you

**Comment by freescout-helpdesk** [comment]
You are probably talking about bulk actions in conversations list.

**Comment by eric241** [comment]
Hi
partially, but not exactly. For some uses it needs to see all the messages, not just a part of it visible in the all conversations list and then when needed change the assigned person or the status. The problem is letting to change the assigned person or statuses by anyone instead of allowing to do this by the assigned user/administratior. As a result when being less focused when there are many tickets some weird actions may be done accidentally and then some mess happens.

Thank you

**Comment by freescout-helpdesk** [comment]
No plans to implement this for now.
