### ISSUE TITLE
Option to send full conversation history to customers

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#447]
todo

**Comment by joris85** [comment]
Great!
I have had multiple customers that asked where i was replying on :-)
Would be a nice feature to have the possibility to send the history.

Getting more and more enthousiastic about Freescout!

**Comment by freescout-helpdesk** [comment]
Before https://github.com/freescout-helpdesk/freescout/releases/tag/1.4.2 release there was an issue with grouping emails for customers (Fixed In-Reply-To header in replies to customers). Most likely after 1.4.2 release your customer won't have this issue anymore.

**Comment by joris85** [comment]
I do not understand the status of this. Is the option coming that the customer is seeing what they asked or the full history of the ticket maybe?

I get daily confused customers asking where my reply was for exactly

**Comment by nextima** [comment]
Same here - our customers are getting super confused after out recent update of Freescout, when they suddenly don't get the full conversation in our replies.
The option for enabling the history in the replies is must have, tiredofit suggested the good solution in  #365 [here](https://github.com/freescout-helpdesk/freescout/issues/365#issuecomment-553916972)

**Comment by freescout-helpdesk** [comment]
"Conversation history" dropdown should be added to the Settings --> Mail Settings (Emails to Customers):

- No history
- Last customer message
- Full history

**Comment by joris85** [comment]
Hi Freescout,
Does help wanted mean that you guys do not work on this?
I really need this function so would like to know if somebody is working on this or not.
Can this be done by a module or does it need to be in the core?

**Comment by freescout-helpdesk** [comment]
`help wanted` label - work which need to be done, by anyone.
This should be in the core.

**Comment by joris85** [comment]
I am no programmer, but i love this feature a lot.
No idea if this is alowed with the freescout and opensource but i am willing to hire my developer to build this and share in the money with who is willing to.
ofcourse afterwards it is core of Freescout.

Is there somebody who wants this and is willing to pay a bit for the development?

Or can i donate to Freescout for this feature?

**Comment by joris85** [comment]
Any news on this?
@freescout-helpdesk do you guys have a way that multiple people can donate for a specific feature and you built it? I will :-)

I understaand it is FREEscout but you guys need to get money for something and i a willing to donate for a feature like this. I just need this as fast as possible. If would never be implemented i need to leave freescout. This is a must for me.

**Comment by fvdm** [comment]
Thanks for adding this feature!

I see the ticket is already closed, but it would still be great to have the middle option `Last customer message`.

**Comment by freescout-helpdesk** [comment]
> I see the ticket is already closed, but it would still be great to have the middle option `Last customer message`.

We are not planning to implement it. If somebody would like they are welcome to submit a pull request.
