### ISSUE TITLE
Feature request: contact groups

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#448]
Hi,

we use Freescout also as an outgoing e-mail system (shared mailbox) and therefore it would be extremely convenient to be able to:

1. manage contacts in an easier way (like list, sort, filter, edit, merge)
2. have mailgroups, like in every email client you can create a group, add contacts and during creation of an email search/select a group.

Keep up the very good work!

Kind regards,

Marcel.

**Comment by joris85** [comment]
Yes both wanted here to!

**Comment by amirkhan7** [comment]
Seconded!

**Comment by freescout-helpdesk** [comment]
There is a possibility to allow to select customers using Customer Fields when creating a new conversation. But in this case a new conversation will be created in FreeScout for each customer-recipient. Will such solution work for you?

**Comment by freescout-helpdesk** [comment]
FreeScout works not only as a mail client but also as a support platform, so creating customer groups and treating them as a single recipient won't be possible.

**Comment by Io-Qo** [comment]
> There is a possibility to allow to select customers using Customer Fields when creating a new conversation. But in this case a new conversation will be created in FreeScout for each customer-recipient. Will such solution work for you?

How does that work? I couldn't find out myself.

**Comment by freescout-helpdesk** [comment]
It's not implemented.

**Comment by Io-Qo** [comment]
Ah! I would love this feature though.
