### ISSUE TITLE
recurring error since today

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#449]
Since today the "system" page most of the times gets an "Whoops, looks like something went wrong."-error

In the app logs it has hundreds of errors:
Client error: `GET https://api.github.com/repos/freescout-helpdesk/freescout/tags` resulted in a `403 Forbidden` response: "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a hig (truncated...)

What could this be?

It occurred with the latest version 1.4.4 but also the previous version.

**Comment by freescout-helpdesk** [comment]
Are you on a shared hosting?

**Comment by imc67** [comment]
Yes, I'm on shared hosting. Probably there are more users on that IP polling that api. However it's a pity that the whole 'system' page is not available because of this.
