### ISSUE TITLE
Plain email template

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#45]
todo

**Comment by freescout-helpdesk** [comment]
If nobody need this feature, then no need to implement

**Comment by Aulig** [comment]
> If nobody need this feature, then no need to implement

Sad to see that this got closed. I'd love to see this feature. I use freescout for most of my e-mails nad for emails other than customer support a plain template would feel more personal.

**Comment by AndreasRiedel95** [comment]
@freescout-helpdesk is there any progress or is it possible to customize somehow the email templates which getting send out for example for notifying a user?
