### ISSUE TITLE
Attache multiple users and there email to a business

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#453]
I do not think this is in Helpscout to but i do not see clear how it works with a certain business with 10 employees.
We have a lot of customers as a business and 10 different names with own email adresses.
That means in Freescout i will get 10 customers. But it is one.
So i mis a way to have one business with 10 persons. 
Even in our situation we have persons that work in 3 different businesses.

**Comment by freescout-helpdesk** [comment]
One email is one customer. There is no solution to for your use case.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/452
