### ISSUE TITLE
Choose icons for in toolbar

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#454]
The trash icon i would like to have more clear.
Why not option to choose if it go's in dropdown or be in toolbar per action.
It would save many clicks if most of them where in the toolbar if you ask me.
https://www.dropbox.com/s/2xzhfczmgdmv25t/Schermafdruk%202020-01-27%2012.20.45.png?dl=0

**Comment by freescout-helpdesk** [comment]
If someone can make Delete button visible on desktop and hidden on mobile, feel free to submit a pull request.
