### ISSUE TITLE
Ability to Hide "Admins" from Mailbox Assign List?

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#456]
Hello, My users are starting to make noise about privacy that there are names in their "Assign" list that shouldn't be for an othewise private inbox. 

Is there a possibility to hide the list of Admins on the Freescout Server from being listed in the Assign page?

As a possible enhancement - The capability of assigning of the users to be an Admin strictly for that mailbox for any feature with the exception of Mailbox Information (IMAP/SMTP settings) would be ideal giving control to the users to create Mailbox side saved replies, and other functionality.

Regards

**Comment by freescout-helpdesk** [comment]
> Is there a possibility to hide the list of Admins on the Freescout Server from being listed in the Assign page?

No for now.

> The capability of assigning of the users to be an Admin strictly for that mailbox

This increases complexity of the whole app, which is not very good.

**Comment by tiredofit** [comment]
I understand, definitely adds complexity to the application and ACL layers. I'll work with what we have so far in this great application and learn to build workarounds.

**Comment by freescout-helpdesk** [comment]
One of the possible solutions - show on Mailbox Permissions page a list of admins with "Hide from Assign List" checkbox next to each admin.

**Comment by tiredofit** [comment]
That would definitely solve the users of the mailboxes freaking out because all sorts of foreign names are there, yet still allow Admins to see the mailbox.

**Comment by santibm** [comment]
Seems related to #410
I can have a look at it

**Comment by ePascalC** [comment]
Strange to close the oldest ticket in favor of a newer one, but if we get to a solution, I would be very happy :-)
Your proposed solution (a 'hide admins' switch) would be great. But of course the names of the admins should be shown so they can be added again to this specific mailbox. We have 3 mailboxes in our system and me (as admin) I DO work on one of those, so for that specific mailbox I need to be able to assign tickets to myself.

**Comment by santibm** [comment]
So that would be admins different to myself when logged as admin no?

**Comment by ePascalC** [comment]
There are multiple ways of 'removing the unwanted admins'. In a smaller organization we probably don't want to differentiate the admin account from the account that can be assigned tickets to. So 1 person would have 1 account for doing both admin tasks and 'normal' tasks.
Let's say with my account I'm admin, but I also need to manage mailbox number 2 of 3
In that case if there is just 1 central switch to remove admins from the assignee list, then that would work fine on mailbox 1 and 3 as my name would not appear. However on mailbox 2, my name would not appear in the list as I'm an admin. 
So hence my remark that somehow I should still be able to add myself in the list of assigned to for mailbox 2.

**Comment by tiredofit** [comment]
Thank you!

**Comment by ePascalC** [comment]
Works perfect! Thanks a lot @santibm

**Comment by santibm** [comment]
Looks great!! Actually it was @ freescout-helpdesk job!! Thanks!!
