### ISSUE TITLE
Signature Variables for User

### ISSUE THREAD

**Issue by statepm** [freescout-helpdesk/freescout#458]
Can anyone let us know if there are variables to enter the user name into the signature. If so, what are they? - Thanks in advance.

**Comment by freescout-helpdesk** [comment]
Use `Insert variable` dropdown.

**Comment by statepm** [comment]
The "Insert Variable" dropdown box only has Mailbox, Conversation and Customer variables but nothing for the user;

![Screen Shot 02-06-20 at 11 01 AM](https://user-images.githubusercontent.com/60494294/73954960-91848500-48d0-11ea-85b6-a6aff02b7400.PNG)

The only variable for a user I could find was in the forums for the user "Job Title";

{%user.jobTitle%}

This variable and other variables for the user are not in the "Insert Variable" drop down menu.

**Comment by freescout-helpdesk** [comment]
User vars will be made available in the mailbox signature.
