### ISSUE TITLE
Some subjects are in code?

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#460]
Some subject are in code instead of readable text, in a 'normal' email client it looks good:

like:

=?utf-8?Q?DigitalOcean=20monitoring=20resolved:=20Bandwidth=20=E2=80=94=20Inbound=20is=20running=20low=20-=20 (... etc.)

or

=?utf-8?Q?=2D=2D=2DPERSBERICHT=2D=2D=2D=20van=20Museum= (.... etc.)

**Comment by freescout-helpdesk** [comment]
Fixed by https://github.com/freescout-helpdesk/freescout/commit/73b8fa039f6989ccb97b4dd41c4ac567b2c1713f
Will be in the next release.
