### ISSUE TITLE
Custom Fields (purchased) - Module not found in modules directory

### ISSUE THREAD

**Issue by benninkcorien** [freescout-helpdesk/freescout#467]
Just bought a few modules, 2 installed fine, the Custom Fields one doesn't.
I get a modal popup saying Module not found in modules directory.
(also contacted the support email, but figured it's a bug too)

**Comment by freescout-helpdesk** [comment]
Try to clear the cache in Manage --> System --> Tools

**Comment by benninkcorien** [comment]
Cleared the cache. Same error.

**Comment by benninkcorien** [comment]
Also your support email seems to not work... 

There was a temporary problem delivering your message to support@freescout.com. Gmail will retry for 45 more hours. You'll be notified if the delivery fails permanently

**Comment by benninkcorien** [comment]
Am an idiot. Accidentally bought Custom Fields, not Folders.

**Comment by freescout-helpdesk** [comment]
Correct email address is support@freescout.net
