### ISSUE TITLE
Fix placeholders in French translation

### ISSUE THREAD

**Issue by FlickTheManual** [freescout-helpdesk/freescout#469]
Hello,

great work for you application.

I got a little issue in front, I got a `:user` and `:customer` or `:etat` instead of the name of the actor or the customer.

![image](https://user-images.githubusercontent.com/2384206/73918004-145e0d80-48da-11ea-894e-2a4b1ae2e4aa.png)

didn't know where this come.

any help, pls? :)

**Comment by freescout-helpdesk** [comment]
French translation need to be fixed.
Placeholders like ':person' should not be translated, bu kept as is.

**Comment by FlickTheManual** [comment]
ho ok, my bad,
I make it in english, and we will see the user name as you say, thanks.

**Comment by fulldecent** [comment]
This is now fixed, as per https://github.com/freescout-helpdesk/freescout/commit/90a34c1295a720078359f7564391fa633ad7f61a . Recommending to close issue.
