### ISSUE TITLE
Cant update FreeScout from Settings

### ISSUE THREAD

**Issue by MartinH0** [freescout-helpdesk/freescout#473]
Everytime I try to update FreeScout I get this error.
I noticed this since v1.3

![FreeScount Cant Update](https://user-images.githubusercontent.com/17692860/74109595-0bdd2f80-4b85-11ea-8427-b1ca48538bdb.png)

Not matter if I overwrite it with the files from GitHub or Update it via `/tools.php`.
The next Update cant update itself. again
It says "permission denied" but passes all the permission tests ..

Updating via `/tools.php` is working btw.

**Comment by freescout-helpdesk** [comment]
OK. We will try to fix in the next release.

**Comment by freescout-helpdesk** [comment]
It does looks like still some folders in `storage/app` have incorrect permissions.

Try to fix permissions:
```
find storage/app -type d -exec chmod 775 {} \;
```

Replace `storage/app` with the full path on your server.

**Comment by MartinH0** [comment]
Ok funny. `storage/app` does not exist. I dont know why. But even if I update with `/tools.php` its not coming back.

I will try to create it or to move it from git to my folderstructure and report back.
So its not wrong permission, but if the folder is missing it does not get recreated by updating.
I never removed anything manually so I dont know when/why this happened.

**Comment by freescout-helpdesk** [comment]
ok
