### ISSUE TITLE
Bug: When images added in mail text is not imported

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#475]
Hi guys,

I have an issue with importing email that has text and images together in an email.

This is the mail in Apple mail:
https://www.dropbox.com/s/peyoqsx26ao3p3w/Schermafdruk%202020-02-10%2015.37.02.png?dl=0

This is the ticket that Freescouts gives me.
https://www.dropbox.com/s/793fba3zsq1z3fi/Schermafdruk%202020-02-10%2015.38.29.png?dl=0

So i ask for more information than the images and customer lets me know he gave that to me.

Let me know if you would like to have that email to test :-)

He is sending from apple mail

**Comment by freescout-helpdesk** [comment]
Yes. Could you please send the email to support@freescout.net

Similar issue has already been fixed: https://github.com/freescout-helpdesk/freescout/issues/381

**Comment by joris85** [comment]
Yes i just did!

**Comment by freescout-helpdesk** [comment]
@joris85 Which version of the FreeScout are you using?

**Comment by freescout-helpdesk** [comment]
Also could you please send content of the **Body** tab of the **Show Original** window.

**Comment by freescout-helpdesk** [comment]
The issue is not confirmed on the latesst version of the FreeScout.

![2020-02-15_21-49-43](https://user-images.githubusercontent.com/40499291/74591121-68d15d80-503d-11ea-9213-2933f915f1fe.png)

**Comment by joris85** [comment]
Hi Guys,

Thanks for checkin in to this issue.
I tested it today and it works.
So the only thing i can imagine is that the import was in the older version and when i checked the version it was the newest because check it almost daily because i love the updates :-)

So sorry for you time in this and thanks for the great support.
I am talking with a developer to develop some new modules for us.
One is a connection to our CRM Teamleader.
I can imagine a connection to Zapier would be an awesome idea.
