### ISSUE TITLE
HTTPS Protocol

### ISSUE THREAD

**Issue by statepm** [freescout-helpdesk/freescout#476]
Our current installation shows that it is recognizing the HTTP protocol however there is the following error message;

![Screen Shot 02-10-20 at 07 00 PM](https://user-images.githubusercontent.com/60494294/74201418-b9108000-4c37-11ea-87e5-38ece1754ccd.PNG)

An ssl certificated has been installed and when you try to access the program using the HTTPS: protocol, the script does not display correctly. Has anyone else encountered the same issue and if so, what steps did you do to fix? Our webhost said it appeared to be a scripting issue because the HTTPS: protocaol is working fine on our installation.

**Comment by freescout-helpdesk** [comment]
Set correct APP_URL in .env file and clear the cache in Manage --> System --> Tools

**Comment by statepm** [comment]
That worked... excellent. Thank you!
