### ISSUE TITLE
Whoops something went wrong (after a amount of time)

### ISSUE THREAD

**Issue by wauwturrr** [freescout-helpdesk/freescout#477]
Hi Freescout,

I'm getting the error below alot in my logs, and sometimes freescout gets the 'Whoops' error. When i then clear the cache with PHP Artisan, it's working again for a bit.

file_put_contents(/var/www/html/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): failed to open stream: Permission denied at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)

I think it might be something with the queue: 

![image](https://user-images.githubusercontent.com/16634704/74234380-f8d57700-4ccc-11ea-8806-82f50188aa61.png)

It's not removing this queue thing for a few days now..

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#10-checking-installation

**Comment by wauwturrr** [comment]
> See https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#10-checking-installation

Did the commands. Is there a way to clean up the try's or something?

**Comment by freescout-helpdesk** [comment]
No
