### ISSUE TITLE
New ticket with combination Helpscout ticket system (their side)

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#479]
Hi guys,

I get complaints that my email is seen as a new email, not coming in the flow of the old ticket. While it is shown in me in the same ticket.
Does Freescout removes Helpscout code, can we have the same ID or anything else that gives a compatibility issue?

Thanks!

**Comment by joris85** [comment]
This is what i get as reply after couple messages :-D

OK. Now, please stop commenting on this ticket because this is the third time I am merging your replies and leaving note to our developers 😀

**Comment by freescout-helpdesk** [comment]
Is it the same issue as https://github.com/freescout-helpdesk/freescout/issues/447 ?
