### ISSUE TITLE
Emails Not Being Sent To All Accounts

### ISSUE THREAD

**Issue by amirkhan7** [freescout-helpdesk/freescout#480]
We currently have an issue where if we have 2 accounts on freescout lets say (test@test.com and test2@test.com) and an email is sent to both addresses then it will only show up in one. the accounts come from 2 separate inboxes. 

The same happens if one of our accounts creates an email and sends it to a 3rd party. and when that 3rd party replies, if he cc's another freescout account that is a seperate inbox, only one account will get it. 

I could be wrong but could the lack of message ID's in the subject header cause this? and if so how can i add them back in the subject header. 

Any help would be greatly appreciated.

**Comment by freescout-helpdesk** [comment]
Most likely this happens because FreeScout checks Message-ID header uniqueness on fetching. Need to be fixed somhow.

**Comment by freescout-helpdesk** [comment]
This seems to non-solvable for now, as if we make Message-ID unique per mailbox and someone moves conversation with the same Message-ID to the mailbox from another mailbox, it will break the system (there will be two messages with the same Message-ID in one mailbox).

**Comment by amirkhan7** [comment]
Couldn't you check for that on condition of it moving (i.e. IF EXISTS SELECT @MessageID From table). and if so throw an error saying they already have the message. or would that be awful for performance?

**Comment by Qrious** [comment]
We're also experiencing this issue, which is a serious problem, so i'm looking at ways we can solve this. 

I'm willing to fix this/open a PR, but seems like a change that might have serious impact, so i'd like to hear your opinion/thoughts first.

> This seems to non-solvable for now, as if we make Message-ID unique per mailbox and someone moves conversation with the same Message-ID to the mailbox from another mailbox, it will break the system (there will be two messages with the same Message-ID in one mailbox).

However, in this case the message was already available in that mailbox, there is no need to actually copy it over? As far as I can judge it is needed to relink/merge the entities that were attached to the thread of which the move was requested, to the already existing one?

Am I missing major issues here?

**Comment by fhirter** [comment]
This is also a major problem for us. It also happens when multiple adresses are subscripted to a mailing list.
We are willing to work on this too.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch. Testing is needed.

**Comment by tiredofit** [comment]
I will test this week and provide results.

**Comment by tiredofit** [comment]
@freescout-helpdesk  Have tested and have found that in our scenarios it is working as intended

**Comment by freescout-helpdesk** [comment]
Thanks
