### ISSUE TITLE
cc address no longer being shown

### ISSUE THREAD

**Issue by amirkhan7** [freescout-helpdesk/freescout#481]
Hi, 

We're currently having an issue after one of the most recent updates where freescout accounts that are cc'd in a email no longer displays as such. See the images below as an example. 

![image](https://user-images.githubusercontent.com/46426497/74443372-f577f200-4e6a-11ea-9c96-84963e323371.png)

![image](https://user-images.githubusercontent.com/46426497/74443438-16404780-4e6b-11ea-8f18-9bd312e08bab.png)

any help would be greatly appreciated. 

Thanks. 
Amir

**Comment by amirkhan7** [comment]
as you can see, in the freescout UI there is no longer a cc address.

**Comment by freescout-helpdesk** [comment]
If CC is the email address of your mail box or it's alias, it will not be visible.

**Comment by amirkhan7** [comment]
i'm assuming if another person was cc'd in that address along with a mail box it would show?

**Comment by freescout-helpdesk** [comment]
yes

**Comment by amirkhan7** [comment]
perfect, thanks!
