### ISSUE TITLE
Allow users to manage custom folders

### ISSUE THREAD

**Issue by amirkhan7** [freescout-helpdesk/freescout#482]
Hi,

We've been using the custom folders module for a while now and were wondering if we could request the ability for users to manage their own custom folders.  Currently they can manage saved replies and add tags, but these tags to do not turn into folders. 

This could be an additional permission setting? 
If theres already a way to do this and i'm just being stupid let me know :) 

Thanks.

**Comment by freescout-helpdesk** [comment]
Not possible for now. Can be implemented in the future.

**Comment by joris85** [comment]
Oh yes!! This would be great!

**Comment by joris85** [comment]
Hi Freescout, 
If i ask my developer to build it, will you implement this in your core module?

**Comment by freescout-helpdesk** [comment]
Sure. It should be implemented similar to the Saved Replies.

**Comment by freescout-helpdesk** [comment]
Added in the latest version of Custom Folders module.
