### ISSUE TITLE
IMAP folder issue

### ISSUE THREAD

**Issue by lgwapnitsky** [freescout-helpdesk/freescout#483]
I'm using IMAP to pull folders from a GMAIL account. I have information filtered into a subcategory, skipping the inbox, but I'm unable to remove the INBOX from the IMAP settings in FreeScout.

![image](https://user-images.githubusercontent.com/647444/74557742-d0e54e00-4f2e-11ea-9ac4-ca7cf6f94068.png)

Every time I do, INBOX comes back when I hit save.

This is causing all emails to come in rather than just the ones i need.

Thank you

**Comment by freescout-helpdesk** [comment]
Todo: allow to remove INBOX from IMAP Folders list.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/547
