### ISSUE TITLE
iOS Mobile App (help wanted)

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#484]
FreeScout iOS mobile app is almost ready. If you have an Apple Developer Account and enrolled as an organization and would like to participate in the provisioning and deployment of the FreeScout iOS mobile app, please email at support@freescout.net

**Comment by bman955** [comment]
Any updates on getting an iOS app out there?

**Comment by freescout-helpdesk** [comment]
https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/180

**Comment by freescout-helpdesk** [comment]
https://github.com/apache/cordova-plugin-wkwebview-engine/issues/178

**Comment by freescout-helpdesk** [comment]
FreeScout iOS app has been released: https://freescout.net/ios-app/
