### ISSUE TITLE
Feature request - Run Workflow on multiple selected emails

### ISSUE THREAD

**Issue by benninkcorien** [freescout-helpdesk/freescout#485]
Would it be possible to add a Workflow option to the top menu, so you can run the same workflow on multiple emails? That way you can assign/change status/add tag for a whole bunch in 1 go.

![multiple select workflow](http://www.corienbennink.nl/imghosted/multiple-select-workflow.jpg)

**Comment by freescout-helpdesk** [comment]
Imlemented in the latest version of the Workflows Module.
