### ISSUE TITLE
Select2 tokenization incorrect when pasting multiple email addresses in to/bcc/cc field.

### ISSUE THREAD

**Issue by Qrious** [freescout-helpdesk/freescout#487]
As depicted in the gif below, currently multiple email addresses are added as a single tag when copy+pasting a string containg multiple email addresses seperated by any of the supported delimiters. For example pasting:
`test1@example.com, test2@example.com, test3@example.com` results in the following situation:
![current](https://user-images.githubusercontent.com/680327/74608258-dcc44200-50df-11ea-990c-f0f424fce1b0.gif)
In this case, multiple tags with a single email address each should be added.

**Comment by freescout-helpdesk** [comment]
Merged.
