### ISSUE TITLE
Mailbox managers

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#490]
Allow to appoint users as mailbox managers in order to allow to administer particular mailboxes.

For example, the user "Test" could be a manager for the mailbox "demo" but he does not have access to other mailboxes.

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/280374

**Comment by brennanmurphy** [comment]
Would like to work on this if no one else is. Aiming to be done by the end of next week. 

Would like some guidance on the following:
- Should mailbox managers be able to edit all settings of the mailbox? I was thinking of blocking them from being able to access connection settings as it seems to me that the point of this would be mostly user/front end settings, not system settings. Would probably also block them from editing the mailbox email and name. 
- Should managers only be able to add users to a mailbox that don't exist in the system?

**Comment by freescout-helpdesk** [comment]
1) Managers should be appointed on the mailbox's Permissions page under `Managers:` section via select2 field (bool `manager` field should be added to `mailbox_user` table). Below select2 field there should be a list of managers (similar to `Administrators:`) with `Hide from Assign list` checkbox.

2) `Connection Settings` page should not be available to managers. On `Edit Mailbox` page Mailbox Name and Email Address fields should be disabled for managers.

3) Only administrators can appoint managers. Managers can not appoint other managers for the mailbox.

4) Managers should have access to the Users page and be able to add new users to the system (only `User` role should be available in the `Create a New User` wizard). Managers should be able to edit, but not delete users. Managers can not change user Role to Administrator.

**Comment by brennanmurphy** [comment]
@freescout-helpdesk done most of the work but I've gotten stuck on integrating with some of the modules. for example, we use the saved replies module, and it would make sense to me that a mailbox manager should be able to edit the saved replies. 

My first thought is creating a function in the User model `isManager($mailbox)` which could then be used to replace the `isAdmin()` checks done in functions like the addAction for adding a link to the mailbox menu. This would require also editing the modules as well. Is this the best way to implement?

**Comment by freescout-helpdesk** [comment]
> My first thought is creating a function in the User model isManager($mailbox)

OK.

**Comment by yamakrane** [comment]
Hi all, is the Mail box manager integrated in freescout yet ? Thanks

**Comment by freescout-helpdesk** [comment]
@brennanmurphy If you have this partially implemented, feel free to submit it as a pull request, we will finish the implementation.

**Comment by injektion** [comment]
@freescout-helpdesk Was looking to take this on as it's something we need a bit urgently... Dragging my feet waiting to see what @brennanmurphy has already in place...

Might also suggest that in addition to the per-mailbox user assignment that there's the ability to define a Mailbox Manager role whereby trusted users could admin any/every mailbox, and also to break out some of the admin options for Managers:

- Email signature
- Auto Reply
- Custom Folders
- Custom Fields
- Saved Replies (Canned Responses)

Use case: We have support staff who we don't want to give admin priv's to (don't want them viewing contents of all mailboxes) but would like them to be able to set out of office replies and update signatures for all mailboxes.

Let me know if this sounds like a good fit... Would love to see what @brennanmurphy has going on, but if he's moved onto other things I'll just start fresh...

**Comment by freescout-helpdesk** [comment]
On Permissions page replace "Administrators:" table with "Access Settings:" table displaying a list of Users (having access to the mailbox) and Administrators with the following checkboxes:

- Edit Mailbox (value: `edit`) [Mailbox Name and Email Address fields should be read-only]
- Permissions (value: `perm`)
- Auto Replies (value: `auto`)
- Custom Folders [will be added via the module]
- Custom Fields [will be added via the module]
- Saved Replies [will be added via the module]
- Hide from Assign list [for this setting use `hide` field of the `mailbox_user` table]

If user is Administrator show only `Hide from Assign list` checkbox and show `(Administrator)` text after user's name.

Access settings should be stored in `mailbox_user` table in the `access` text field casted into JSON.

To allow users Manage Users the following task will need to be implemented: https://github.com/freescout-helpdesk/freescout/issues/741

**Comment by injektion** [comment]
PR submitted to give you what you asked for above - editor update with the JSON array in mailbox_user.access 

Figure the next steps would be to add permission checks and update the Mailbox Settings templates/save functions to only allow editing to what the user has access to.

Not sure if you'd like me to stop there so you can get the permission checking and modules set up just how you want them, but I'm happy to keep on this if you'd like the help!

**Comment by freescout-helpdesk** [comment]
> Figure the next steps would be to add permission checks and update the Mailbox Settings templates/save functions to only allow editing to what the user has access to.

Feel free to implement.

**Comment by injektion** [comment]
I've gone ahead and done that -- submitted a PR with the details.

Couple things:
- user with Permission priv's can edit their own additional priv's.  Didn't know how you'd prefer it handled, but I'd recommend just not allowing that user to edit any of their own priv's (leave it up to admins).
- I moved the signature out of the Edit Mailbox/Main settings page because it seemed like something that a less tech savvy manager might be given permission to edit, but having it alongside the breakable settings didn't seem smart.  I popped it out like the Auto-Reply settings

Let me know if you'd like any additional changes or features.

**Comment by freescout-helpdesk** [comment]
`user with Permission priv's can edit their own additional priv's. Didn't know how you'd prefer it handled, but I'd recommend just not allowing that user to edit any of their own priv's (leave it up to admins).`

Works like this now.

`Email Signature` permission is preserved. "Email Signature" input moved back to "Edit Mailbox" page. If user has `Edit Mailbox`  permission, he can also edit the signature. If use has `Email Signature`  permission without `Edit Mailbox`, he can edit only the signature.

**Comment by freescout-helpdesk** [comment]
Thanks for testing.

**Comment by injektion** [comment]
> `Email Signature` permission is preserved. "Email Signature" input moved back to "Edit Mailbox" page. If user has `Edit Mailbox` permission, he can also edit the signature. If use has `Email Signature` permission without `Edit Mailbox`, he can edit only the signature.

Right on - makes sense... 

Figure the filter and action hooks should be able to update the Mailbox->$USER_ACCESS_PERMISSIONS array nice and easy in the Modules.
