### ISSUE TITLE
Workflow: incomplete - Customer viewed

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#491]
I'm trying to create a workflow that will set status from `active` to `pending` if a customer viewed the conversation reply. 

Condition:
![condition](https://user-images.githubusercontent.com/5198092/74637183-6f2e1980-51a4-11ea-863b-e06db6f16347.png)

Action:
![action](https://user-images.githubusercontent.com/5198092/74637199-75bc9100-51a4-11ea-99f0-ab8515626257.png)

When I save this, I get `incomplete` and the workflow is not running. 

Am I missing?

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows v1.0.6
