### ISSUE TITLE
Request - multi-language replies

### ISSUE THREAD

**Issue by trochaika** [freescout-helpdesk/freescout#495]
Hi!

There are many places where multiple languages are used on daily basis.
Could I ask for supporting creating multi-language in FreeScout mainly saved replies, satisfaction ratings and auto replies?
I will find it very useful.
Instead of 45 saved replies(15 saved replies x 3 languages) I have, there should be a list of 15.

I think additional column with language of ticket or user could work for auto selecting a right set of saved replies.
Maybe it could be optionally auto recognized too?
I looked at the pictures of the 'Ticket Translator' module and it seems it could recognize the language. I do not have purchased it yet, but the description also says it 'Module can automatically detect customer language.'. Maybe it could be useful for this?
Cheers!

**Comment by freescout-helpdesk** [comment]
Maybe will be possible in the future.

**Comment by freescout-helpdesk** [comment]
Categorizing saved replies added in Saved Replies Module v1.0.6: https://freescout.net/module/saved-replies/
