### ISSUE TITLE
Search customer, ticket results shown from not assigned mailboxes

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#496]
Hi guys,

If i have one extra mailbox and i search on a customer.
1. i can see customers that are not in this mailbox (told before)
2. When i click on a customer i can see ticket titles and intro from tickets that are in an other mailbox. When i click on them i get, Whoops something went wrong.

I would love that it is possible to better isolate mailboxes.
I would suggest an option in the mailbox. Isolate mailbox  YES/NO

**Comment by freescout-helpdesk** [comment]
This won't change.
