### ISSUE TITLE
How the customer submit tickets

### ISSUE THREAD

**Issue by victoras** [freescout-helpdesk/freescout#497]
Hi,

I recently started to test the freescout, and looks amazing for me.

How the customers submit tickets, is it any way to submit a form with custom fields. Or the customer has to send just an email?

I didn’t found if is possible to have an account for the customer to browse all tickets and replays.

Thanks

**Comment by freescout-helpdesk** [comment]
Customers create tickets by sending an email to the mailbox's email address.

**Comment by victoras** [comment]
Is it any way for the customer to see the tickets he created?

**Comment by freescout-helpdesk** [comment]
No for now. Maybe there will be a module in the future for this purpose.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/end-user-portal/
