### ISSUE TITLE
Import from Hep Scout

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#5]
Implement importing from Help Scout using Help Scout API: https://developer.helpscout.com/mailbox-api/overview/authentication/

**Comment by freescout-helpdesk** [comment]
Will try to implement this

**Comment by rosinghal** [comment]
@freescout-helpdesk did you end up trying this?

**Comment by freescout-helpdesk** [comment]
Try https://github.com/freescout-helpdesk/freescout/wiki/Migrate-to-FreeScout
