### ISSUE TITLE
Content filtering

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#50]
todo
https://secure.helpscout.net/docs/help/53613edce4b0d3049b645148/

**Comment by fulldecent** [comment]
Here is the relevant HS documentation. Since that page is restricted to login.

<img width="806" alt="Screen Shot 2022-09-12 at 11 58 41" src="https://user-images.githubusercontent.com/382183/189700935-f2e3e34b-31dd-4e71-99ac-f10e864237b1.png">

**Comment by fulldecent** [comment]
Recommending to close this issue.

We currently have spam module which is a big help.

And this issue could be considered again when resources are available or a PR comes along
