### ISSUE TITLE
[root ownership issue] cache folder 5e

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#500]
Hi Support
We have a pending issue with the cache folder permission issue.

The cronjob running is running under the owner of the folder and we have no issues here.
However we have one folder, which is 

/home/ouruser/webapps/project/public/storage/framework/cache/data/5e/

This folder is always created and always has the permissions
root:root

no matter what happens this causes an issue in the logs and sometimes the error appears in Freescout.

What we want to know is if this 5e folder is somehow part of the application cache generation, and if we can somehow remove this permanently.

All other folder are created dynamically and have the correct permissions.
Please note we have followed this guide.
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

Your assistance would be appreciated
Matthew

**Comment by freescout-helpdesk** [comment]
It means that root user somehow is running some freescout command.
