### ISSUE TITLE
Eeasy Filter tickets from college

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#501]
Hi guys,

I would like the option that under assigned it is possible to show the colleges as submenu.
Or when i go to assigned i can click on a name from my college and i see all his tickets.
The same order as the my own tickets or not assigned.

I know i can go to search and then filter on college but that should be faster if you ask me.
It is filtered upside down (in compare with the other list views).

Thanks!

**Comment by freescout-helpdesk** [comment]
No plans for now.
