### ISSUE TITLE
Workflow: Adding an Action, one row is randomly removed after save 

### ISSUE THREAD

**Issue by denistorresan** [freescout-helpdesk/freescout#503]
We found a bug on Workflow module (regularly bought) regarding Actions.
We have more than one "Assign to User" action but notifications (via mail) are not sent. 
So we added another action "Send Email Notification", but after save one of the Assigned user were removed.

We made a video about the problem we found:

https://www.screenpresso.com/=loJic

Is the right way to use that module?
Is there a way to create groups instead single assignment?

thank you

**Comment by freescout-helpdesk** [comment]
Will be fixed.
Groups are not supported.

**Comment by bedoz** [comment]
I've the same issue, seems like it cannot support more than one assignee at a time.
Is my opinion right?

Can the workflow assign more than one member and send notification to all of them?

I mean this is executed when email arrive and workflow launch his job, so with more assignee more mail have to be sent.

Thank you.

I'll wait for a fix.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows 1.0.7

**Comment by denistorresan** [comment]
hello and thank you!
How can I update Workflow module to 1.0.7?
