### ISSUE TITLE
Saved replies

### ISSUE THREAD

**Issue by victoras** [freescout-helpdesk/freescout#504]
I get an unwanted space when I insert the reply.

---

<img width="420" alt="Screenshot 2020-02-26 10 38 14" src="https://user-images.githubusercontent.com/613284/75361042-ad9e9500-5884-11ea-9606-302c2ad6c896.png">
<img width="515" alt="Screenshot 2020-02-26 10 38 33" src="https://user-images.githubusercontent.com/613284/75361046-b0998580-5884-11ea-9016-940fd1cbb728.png">

**Comment by freescout-helpdesk** [comment]
We could not find a solution for this. If anyone can fix it feel free to share your solution.
