### ISSUE TITLE
Customization Module -> unacceptable image quality

### ISSUE THREAD

**Issue by victoras** [freescout-helpdesk/freescout#505]
Can you add an option to add SVG images or at least high resolution images.

If I use a colored Header Logo, on hover it will display a very strange colors.

Thanks!

**Comment by freescout-helpdesk** [comment]
So you need to be able to upload .svg images? Any other extensions?

**Comment by victoras** [comment]
I think .svg and .ico for the favicon will be more than enough.

**Comment by freescout-helpdesk** [comment]
Implemented in Customization Module v1.0.1
