### ISSUE TITLE
Printing Email Threads and Notes

### ISSUE THREAD

**Issue by statepm** [freescout-helpdesk/freescout#507]
Is there a way to print the email thread with the TO, FROM and DATE of the email like other email clients? Currently the only way it appears to be able to print a thread is to print the screen however it does not show the dates, times and details of the email.

This is an important feature, especially when up comes to requiring the dates , times, sender and receiver of the emails for legal etc back up.

**Comment by freescout-helpdesk** [comment]
Added to todo-list.

**Comment by statepm** [comment]
It would also be nice to have these details shown in the email thread in the mailbox as well.

**Comment by Servery** [comment]
Printing is a must have feature! Some incoming emails need to be printed an printing a whole conversation would also be nice.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch. In several days will be released.
