### ISSUE TITLE
Office hours

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#51]
todo

https://docs.helpscout.net/article/503-set-company-office-hours

**Comment by freescout-helpdesk** [comment]
It looks like nobody needs it.

**Comment by diguinho2018** [comment]
I think that this feature will be great if we have chat module, then we could set work hours to the chat be available and outside work hours it would display ticket form.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/office-hours/
