### ISSUE TITLE
Feature Request: teams

### ISSUE THREAD

**Issue by dotce** [freescout-helpdesk/freescout#511]
Hi.

having teams like Help Scout has(https://docs.helpscout.com/article/594-work-with-teams) would be extremely convenient as it is a great feature.

Kind regards.

**Comment by freescout-helpdesk** [comment]
Maybe will be implemented as a module https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/240336

**Comment by freescout-helpdesk** [comment]
Most likely will not be implemented by us. Maybe someone can develop it.
