### ISSUE TITLE
Customization Module

### ISSUE THREAD

**Issue by dotce** [freescout-helpdesk/freescout#512]
Hi.

having fully customizable website footer, email templates and colors of bars, buttons, links would be extremely useful.

I think I have found the most important elements:
- a
- "navbar navbar-default navbar-static-top"
- ".table-conversations thead"
- ".table-conversations th span"
- "conv-toolbar"
- "#folders .active"
- ".btn-primary"
- ".btn-bordered"

Kind regards.

**Comment by freescout-helpdesk** [comment]
No plans for now. Feel free to alter the module according to your needs.

**Comment by DerDanilo** [comment]
Why is this not a thing? It could be done in the customization module to give colour picker options for the important colours. It's nice to be able to add custom css code but this is also problematic in terms of updates etc.. Maybe we can take ideas from other FOSS projects.
