### ISSUE TITLE
Improve autoresponders detection

### ISSUE THREAD

**Issue by holtgrewe** [freescout-helpdesk/freescout#513]
It would be nice to ignore out of office replies. In FreeScout 1.4.11, an out of office reply was triggered when inviting a user.

Here are some pointers on how to do this robustly:

- https://stackoverflow.com/questions/1027395/detecting-outlook-autoreply-out-of-office-emails/14320010#14320010

Thank you for your consideration.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L462

**Comment by freescout-helpdesk** [comment]
Could you please provide headers of the email which has not been detected as autoresponder.

**Comment by holtgrewe** [comment]
The information removed by me has been set to `STRIPPED` below.

```
MIME-Version: 1.0
Received: from S-MX14-HT01.charite.de ([fe80::f915:d7c4:c346:96d2%12]) by
 s-mx14-ht01.charite.de ([fe80::f915:d7c4:c346:96d2%12]) with Microsoft SMTP
 Server id 14.03.0468.000; Tue, 3 Mar 2020 17:25:58 +0100
From: STRIPPED
To: STRIPPED
Subject: Automatische Antwort: Welcome to FreeScout!
Thread-Topic: Welcome to FreeScout!
Thread-Index: AQHV8XhrBwXJ0OAbq0C8gfBThd86Nw==
Date: Tue, 3 Mar 2020 17:25:58 +0100
Message-ID: <9463ba989c394cfc90d12ed622fc69f8@S-MX14-HT01.charite.de>
References: <d2f577e96b44a0ea4b471bc629ec1a0e@_>
In-Reply-To: <d2f577e96b44a0ea4b471bc629ec1a0e@_>
Content-Language: de-DE
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 03
X-MS-Exchange-Organization-AuthSource: s-mx14-ht01.charite.de
X-MS-Has-Attach:
X-Auto-Response-Suppress: All
X-MS-Exchange-Organization-SCL: -1
X-MS-Exchange-Inbox-Rules-Loop: STRIPPED
X-MS-TNEF-Correlator:
Content-Type: text/html; charset="us-ascii"
```

**Comment by freescout-helpdesk** [comment]
We've improved autoresponders detection, but it your case the email message does not contain any headers saying that this is an autoresponder.

**Comment by holtgrewe** [comment]
Thanks. I guess then that's just Exchange from 2010...
