### ISSUE TITLE
Text area in custom fields for ticket

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#514]
Hi there,

I would like to tell my college some information about this ticket. Not in note but on top.
In this case how much time he may spend on this question with some tekst and numbers.
Like:
This customer is picky on time, let you may spend 20 minutes max on this ticket.
If longer first ask customer.

**Comment by freescout-helpdesk** [comment]
Use multiline custom field.

**Comment by joris85** [comment]
I feel stupid, i though it was a checkbox multi select...

**Comment by freescout-helpdesk** [comment]
No problem.
