### ISSUE TITLE
Special caracter in customer name

### ISSUE THREAD

**Issue by fmaytain** [freescout-helpdesk/freescout#516]
Hi,

I'm currentrly testing Freescout and eventually plan to migrate from HelpScout.

I've notice a small bug :
When there is special caracter in customer's name, FreeScout drop it and jump to the next item.
Examples : 
- François Maytain turn into Fran Maytain
- Michèle Dupont turn into Mich Dupont
- Fabrice Müller turn into Fabrice M
- Secrétariat turn into Secr
- Etc.

If I edit the customer with the complete name, it's working. It's just the first time when it's autodiscover by FreeScout.

Keep up the hard work.

F

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. It would be good to know which email client is used to send emails.

**Comment by fmaytain** [comment]
I had the problem with Outlook 2010, with the last version of Outlook with Office 365 E3, and also with the integrated e-mail app in Windows 10.

**Comment by freescout-helpdesk** [comment]
And which email service provider are you using?

**Comment by freescout-helpdesk** [comment]
The issue has been reproduced via live.com

**Comment by freescout-helpdesk** [comment]
https://github.com/Webklex/laravel-imap/pull/286
