### ISSUE TITLE
External Cron Job service

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#517]
I would like to know how to setup an external cron job for fetching mails, such as cron-job.org.

My idea was to create a PHP page that runs the fetch mail function (for all email accounts setup) via a URL (webhook).

I'm not too familiar with Laravel, any direction on this will help a ton! :) Thanks!

**Comment by freescout-helpdesk** [comment]
You may need to find a developer to achieve this.

**Comment by einarmagnus** [comment]
I just made that work. 
https://github.com/einarmagnus/webfork-cronjob

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/1452#issuecomment-933409280
