### ISSUE TITLE
1.5.0 Upgrade 404 to Attachments

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#522]
Hi,

after Upgrading to 1.5 all Attachments only give 404 Errors.
Directory was moved correctly by the upgrade and the corresponding jpg file is in the Directory structure:
/var/www/html/storage/app/attachment

![20200309-085654](https://user-images.githubusercontent.com/4168339/76193391-26d2ac00-61e4-11ea-9d70-6ee528485ff1.png)

Running Nginx, tried after the upgrade, got 404 Error. Tried to Apply the Changes as mentioned in the changelog;

APP_DOWNLOAD_ATTACHMENTS_VIA=nginx >> .env
+ part in the vhost.

Unfortunately still 404.

Nginx Error Log:
`2020/03/09 09:02:25 [error] 112250#112250: *5 open() "/var/www/html/public/storage/attachment/5/7/1/game_Grafik-Vier-von-zehn-Deutschen-kennen-Augmented-Reality.jpg" failed (2: No such file or directory), client: ########, , server: ########, request: "GET /storage/attachment/5/7/1/game_Grafik-Vier-von-zehn-Deutschen-kennen-Augmented-Reality.jpg?id=1842&token=984a1bbcc43ce7935bfab427da8eb060 HTTP/2.0", host: "inbox.planetlan.work", referrer: "https://inbox.planetlan.work/"`

It still tries to read from:
/var/www/html/public/storage/attachment
where /attachment is not existing.

 
![screenshot_20200309-090538](https://user-images.githubusercontent.com/4168339/76193835-2a1a6780-61e5-11ea-8d05-5db748760c72.png)

A Quick Workaround to make it read the Attachements via Nginx again is:
`ln -sd /var/www/html/storage/app/attachment/ /var/www/html/public/storage`

**Comment by freescout-helpdesk** [comment]
Can you provide full nginx config.

**Comment by solariz** [comment]
NGINX Config currently Active:

https://dev.mgz.de/paste/?1c49ba8acbe7319e#7N1hccuKefa64Y3yfwzmgEA2rMHiGiqVRve6zY5wq7jF

**Comment by freescout-helpdesk** [comment]
Nginx config if fine.

> APP_DOWNLOAD_ATTACHMENTS_VIA=nginx >> .env

This is not required. Better remove it from .env until you get attachments working.

**Comment by freescout-helpdesk** [comment]
Make sure that new code actually has been pulled and clear the cache.

**Comment by solariz** [comment]
Removed APP_DOWNLOAD_ATTACHMENTS_VIA from .env >Cleared the Cache again.
System is on  1.5.0 with nginx/1.14.2 PHP 7.3.14-1 

Unfortunately same 404. Currently it's working but only because I added the symbolic link. If I remove it 404 is back.

**Comment by freescout-helpdesk** [comment]
Make sure that `downloadAttachment()` function is being called when accessing an attachment: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/PublicController.php#L142

**Comment by fvdm** [comment]
I had a similar problem where all attachments were empty (0 bytes).

On the shell I ran `php artisan freescout:clear-cache` which solved it for us.

**Comment by solariz** [comment]
Problem is that in Nginx the file as attachment at the end of the conversation seems not to get rewritten and so the webserver tries to open it from the Filesystem instead of passing it though php.

Currently with the symlink it'S working but of course not intended to stay like that, I will have a deeper look into the problem latest wednesday, today I was just to busy.
`https://##########/storage/attachment/3/0/1/Futurepak-with-MMK.PDF?id=12345&token=0dff725b00000REDACTED00000000`

**Comment by freescout-helpdesk** [comment]
After updating to 1.5.0 if you are using Nginx make sure to replace
```
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|svg|woff|woff2|ttf)$ {
        expires 1M;
	access_log off;
	add_header Cache-Control "public";
    }
    location ~* \.(?:css|js)$ {
	expires 2d;
	access_log off;
	add_header Cache-Control "public, must-revalidate";
    }
```
with
```
    location ~* ^/storage/attachment/ {
        expires 1M;
        access_log off;
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~* ^/(?:css|js)/.*\.(?:css|js)$ {
        expires 2d;
        access_log off;
        add_header Cache-Control "public, must-revalidate";
    }
    location ~* ^/(?:css|fonts|img|installer|js|modules|[^\\\]+\..*)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
```

**Comment by solariz** [comment]
Can Confirm, thanks. Indeed the present rules in the NGINX vhost were overwriting the systems php handler. Changed to the suggested one and it works.

-closed

**Comment by fvdm** [comment]
With `APP_DOWNLOAD_ATTACHMENTS_VIA=nginx` and the above nginx config none of the FreeScout images load anymore. I think those settings may be conflicting with other nginx configs higher up the chain on our Plesk server.

For us it works better with `APP_DOWNLOAD_ATTACHMENTS_VIA` commented out and without the nginx config.

**Comment by freescout-helpdesk** [comment]
Opening for others to see this issue.

**Comment by MathijsA** [comment]
I done the things listed above but it steill isn't working.
Does any one have another idea?

**Comment by freescout-helpdesk** [comment]
> I done the things listed above but it still isn't working.
> Does any one have another idea?

Are you updating FreeScout or installing?
Are you using Nginx or Apache?

**Comment by MathijsA** [comment]
We have updated freeScout to 1.5.2.
And we (the docker from [tiredofit](https://github.com/tiredofit/docker-freescout)) are using nginx

**Comment by freescout-helpdesk** [comment]
> We have updated freeScout to 1.5.2.
> And we (the docker from [tiredofit](https://github.com/tiredofit/docker-freescout)) are using nginx

Have you updated Nginx config? https://github.com/freescout-helpdesk/freescout/issues/522#issuecomment-596923374

**Comment by MathijsA** [comment]
yes

**Comment by freescout-helpdesk** [comment]
Does it work with the symlink?

`ln -sd /var/www/html/storage/app/attachment/ /var/www/html/public/storage`

**Comment by MathijsA** [comment]
no unfortunately it doesn't.

**Comment by freescout-helpdesk** [comment]
> no unfortunately it doesn't.

What error are you receiving? Do you actually have files in /var/www/html/storage/app/attachment/ ?

**Comment by MathijsA** [comment]
aha i found it, the docker uses '/data/storage/app/attachment' instead of /var/www/html

**Comment by MathijsA** [comment]
Well our ngnix conf was also wrong. Were the location is defined. fixed that and now it works again.
