### ISSUE TITLE
Error fetching email. Wrong charset

### ISSUE THREAD

**Issue by sp8233218** [freescout-helpdesk/freescout#523]
On the last version, i see in logs a multiple errors for every fetched email.

![46mh0AO 1](https://user-images.githubusercontent.com/61975526/76216132-17258880-6221-11ea-8a0b-216fa8b69e20.png)

Web Server: Apache
PHP: 7.2.28

**Comment by Qrious** [comment]
I encounter this issue as well, after updating to 1.5.0. 

Environment:
Ubuntu 18.04 LTS
Nginx
Remote server:  Office365 via Imap.

```shell
$ php -v
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
```
Modules:
```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by freescout-helpdesk** [comment]
Will be fixed with https://github.com/freescout-helpdesk/freescout/commit/6491fc3ddda9dca157f5d708e9d59319930e3d19
