### ISSUE TITLE
 Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by adrianwnuk** [freescout-helpdesk/freescout#528]
Hello,

Where I can take a look for system logs? In /system/status i have error "Whoops, looks like something went wrong."

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#10-checking-installation

**Comment by adrianwnuk** [comment]
Thanks, this is helped me.

`sudo chgrp -R www-data storage bootstrap/cache public/css/builds public/js/builds
sudo chmod -R ug+rwx storage bootstrap/cache public/css/builds public/js/builds`
