### ISSUE TITLE
Error: iconv(): Wrong charset, conversion from `default' to `UTF-8' is not allowed

### ISSUE THREAD

**Issue by adrianwnuk** [freescout-helpdesk/freescout#529]
Hello,

I have this error in logs: Error: iconv(): Wrong charset, conversion from `default' to `UTF-8' is not allowed; File: /var/www/www_bok_hostninja_pl/overrides/Webklex/IMAP/Message.php (838).

My stack is apache and nginx both in containers nginx handle upstreams to apache webserver.

**Comment by freescout-helpdesk** [comment]
Will be fixed by https://github.com/freescout-helpdesk/freescout/commit/6491fc3ddda9dca157f5d708e9d59319930e3d19
