### ISSUE TITLE
No image below message in mail view

### ISSUE THREAD

**Issue by adrianwnuk** [freescout-helpdesk/freescout#530]
Hello,

I have some issue with mail messages beacuse I have crashed small image below all messages from staff.

<img width="746" alt="Zrzut ekranu 2020-03-11 o 10 06 15" src="https://user-images.githubusercontent.com/54721317/76400534-c5940f80-6380-11ea-91d8-49017732f281.png">

**Comment by freescout-helpdesk** [comment]
Are you using nginx server?

**Comment by adrianwnuk** [comment]
Im using apache on front and nginx as reverse proxy to apache.

**Comment by freescout-helpdesk** [comment]
Have you just installed the FreeScout?

**Comment by adrianwnuk** [comment]
Yes, i',m installed the FreeScout yet.

**Comment by freescout-helpdesk** [comment]
Can you post here nginx config rules?

**Comment by freescout-helpdesk** [comment]
OK. It looks like you have this issue: https://github.com/freescout-helpdesk/freescout/issues/499

**Comment by adrianwnuk** [comment]
Okay, temporary i'm disable this "Open tracking"- I don't need it.
