### ISSUE TITLE
The filename fallback must only contain ASCII characters.

### ISSUE THREAD

**Issue by barreiras** [freescout-helpdesk/freescout#533]
After recent update when acessing atachement with non ascii character on file name i recieve the  InvalidArgumentException

(1/1) InvalidArgumentExceptionThe filename fallback must only contain ASCII characters.
--
in ResponseHeaderBag.php line 280
at ResponseHeaderBag->makeDisposition('attachment', 'Apresentação_Bestpartybooth-14-03-2020-leiria.pdf')in FilesystemAdapter.php line 126
at FilesystemAdapter->response('attachment/1/3/1/Apresentação_Bestpartybooth-14-03-2020-leiria.pdf', 'Apresentação_Bestpartybooth-14-03-2020-leiria.pdf', array(), 'attachment')in FilesystemAdapter.php line 153
at FilesystemAdapter->download('attachment/1/3/1/Apresentação_Bestpartybooth-14-03-2020-leiria.pdf', 'Apresentação_Bestpartybooth-14-03-2020-leiria.pdf')in Attachment.php line 211
at Attachment->download()in PublicController.php line 182
at PublicController->downloadAttachment('1', '3', '1', 'Apresentação_Bestpartybooth-14-03-2020-leiria.pdf', object(Request))
at call_user_func_array(array(object(PublicController), 'downloadAttachment'), array('dir_1' => '1', 'dir_2' => '3', 'dir_3' => '1', 'file_name' => 'Apresentação_Bestpartybooth-14-03-2020-leiria.pdf', object(Request)))in Controller.php line 54
at Controller->callAction('downloadAttachment', array('dir_1' => '1', 'dir_2' => '3', 'dir_3' => '1', 'file_name' => 'Apresentação_Bestpartybooth-14-03-2020-leiria.pdf', object(Request)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(PublicController), 'downloadAttachment')in Route.php line 212

**Comment by freescout-helpdesk** [comment]
Will be fixed.
