### ISSUE TITLE
customization module apple-touch-icon

### ISSUE THREAD

**Issue by TimoStramann** [freescout-helpdesk/freescout#534]
Hello,
right now the apple-touch-icon is showing the freescout logo. Can you add an option to the customization module to use a custom logo here?

**Comment by freescout-helpdesk** [comment]
Maybe it will be possible in the future releases of the module.

**Comment by TimoStramann** [comment]
> Maybe it will be possible in the future releases of the module.

Then, why is this issue closed because as of right now I can't see a PR which addresses this?

**Comment by freescout-helpdesk** [comment]
Modules are developed and published separately from the core.
