### ISSUE TITLE
Need a brief page in the wiki about module development

### ISSUE THREAD

**Issue by ManelyDave** [freescout-helpdesk/freescout#536]
I'm evaluating freescout to see if the company I work for could switch to it and build some custom modules for what we need, but the Modules folder is empty so I have no code to review. If you could add a one page intro on the basic starting point for a module it would be super helpful. Specifically, I think we'll need to add something with it's own set of pages in the main interface in order to then pull customer info from our other backend systems. Is there an existing module that I could buy and get a good idea how to get started? Thanks. Very impressed so far.

**Comment by joris85** [comment]
Search for Laravel modules.
Also for a preview buy one module and see what it does.

We are now building a connection to CRM Teamleader

**Comment by ManelyDave** [comment]
Thanks- based on this? https://nwidart.com/laravel-modules/v6/introduction

Is v6 ok to start with or should I look at a previous version?

**Comment by freescout-helpdesk** [comment]
Yes. This is an instruction: https://nwidart.com/laravel-modules/v6/introduction
