### ISSUE TITLE
Date sorted different on search and tags

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#537]
Hi guys,

in all the situations the last tickets is on top.
Though if i am in my custom folder or search it is upside down...
I would suggest to do like other views the latest on top because that is what i expect.
And why not make it sortable?

**Comment by freescout-helpdesk** [comment]
Update Custom Folders module to the latest version.
The search will be fixed in https://github.com/freescout-helpdesk/freescout/issues/608
