### ISSUE TITLE
Download all attachments as archive

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#54]
Use \Zipper which is already included

todo

**Comment by joris85** [comment]
Anybody who is willing to work on this?

**Comment by stsimb** [comment]
We are willing to donate money to the project or sponsor someone to implement this feature.
Is this possible? Is anyone interested?

**Comment by freescout-helpdesk** [comment]
**[Extended Attachments Module](https://freescout.net/module/extended-attachments/)** has been released.
