### ISSUE TITLE
Change subject of the ticket

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#540]
I like to have the option to change the subject.

In case of my emergency emails i send a text message on every e-mail that has urgent in the subject. If i can't delete urgent when that is gone with every reply i get an sms.
This sms go's to multiple colleges so cost money and triggers more people to do something fast.

I understand this is not a normal situation so would like to know if this will be done or that i need to build that myself.

**Comment by freescout-helpdesk** [comment]
Duplicate https://github.com/freescout-helpdesk/freescout/issues/43
