### ISSUE TITLE
Feature: Move imported messages on IMAP import

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#542]
Similar to #222, it would be great if the imported mails could be automatically moved to a designated folder on the IMAP server and marked as read. This can keep loading the inbox fast and is just cleaner.

**Comment by freescout-helpdesk** [comment]
No plans to add it to the core. Feel free to timplement as a module.

**Comment by Servery** [comment]
I also use the IMAP import. Sooner or later there will be problems with the ever-growing mailboxes. The deletion of the emails in the mailbox when the conversations in FreeScout are deleted in the trash folder must become a core function.

**Comment by sannc** [comment]
I would like to second this feature request. Definitely a must have!
