### ISSUE TITLE
Bug: No notification on reply/note to Anyone

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#543]
When you add a reply or note from FreeScout in a conversation to 'Anyone' I expect a notification to go out to all users who are a member of the mailbox. Instead there are no notifications sent at all.

When a new conversation comes in all members get notified as expected.

**Comment by freescout-helpdesk** [comment]
No plans to add it to the core. Feel free to timplement as a module.

**Comment by fvdm** [comment]
@freescout-helpdesk Why is this not considered a bug?

When a person is assigned they get a notification, but when to assign Anyone (as in 'all') nobody gets notified. To me that is inconsistent behavior.
