### ISSUE TITLE
Bug: Special chars included in auto linked url

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#544]
Auto linked email addresses and urls between special characters include them in the actual url. This happens when adding a reply/note in FreeScout, I haven't tested it with mail replies.

- `'fr@nkl.in'` -> `mailto:'fr@nkl.in'`
- `(https://example.net)` -> `https://example.net)/`

**Comment by freescout-helpdesk** [comment]
Could you please attach a screenshot for mor clarity.

**Comment by fvdm** [comment]
@freescout-helpdesk sure

![AF6E08F5-BB80-4B33-B7A5-D51E9F04C941](https://user-images.githubusercontent.com/93784/77417098-3269c980-6dc5-11ea-80c3-6ead5dfdb72c.jpeg)

**Comment by fulldecent** [comment]
There are Markdown parsers (Pandoc) which have good handling for URLs and email address detection/linking. Maybe we can steal that code.

**Comment by fvdm** [comment]
I think this line is too fuzzy or needs sanitation after the matching:

https://github.com/freescout-helpdesk/freescout/blob/2a077ecf812bcddf619a469b72b7f5d8c3312dcf/app/Misc/Helper.php#L1272
