### ISSUE TITLE
Help Request: Not Automatically Fetching E-Mails (v 1.5.2/Apache on cPanel)

### ISSUE THREAD

**Issue by gopal-thakur** [freescout-helpdesk/freescout#545]
Hi freescout team,

Kindly help with this issue?

I seem to be running into a strange problem resulting in e-mails not being fetched automatically.
In other words, if I manually fetch them (from the Tools page), e-mails come in and tickets are created. 

However, tickets are not being opened up automatically from incoming e-mails into the mailbox's e-mail address.

We're implementing this system for a project involving about 10 agents and about 100 users. Once I can get these tickets opening up automatically, we're definitely looking to buy modules right away to extend functionality immediately, since our need is that urgent.

**Background to my setup**
New installation of freescout version 1.5.2
Via softaculous.com installer on cPanel version 78.0.47
No errors after installation
Cron job setup as per guide and seems to be working fine
One mailbox setup with one admin user

**My settings**
Under Manage-->Settings-->General
1. The time-zone has been set correctly

Under Manage-->Settings-->Mail Settings
1. The system e-mails section is configured and this works
2. Fetching E-mails: set to _Every Minute_

Under Manage-->Settings-->Alerts
1. Fetching Problems: set to _Every 5 minutes_
2. Logs Monitoring: set to _Hourly_
3. An extra recipient has been added (but no alerts are being received of any problems)

Under Manage-->Mailboxes-->Connection Settings
1. Sending e-mails is configured on my own SMTP e-mail and is working
2. Fetching e-mails is configured for my own SMTP (IMAP/993/SSL/No Validate) and is working

**Logs**
1. Outgoing E-mails: no errors, this is working just fine
2. App Logs: no errors

**System Status**
1. This is what I see 
(version 1.5.2/the correct date and time/correct time zone/https/apache/php 7.1.24)
2. PHP Extensions: all ticked off 
3. Permissions: all ticked off

**Cron Commands**
This is what I see
freescout:fetch-emails 
Last successful run: Mar 19, 2020 10:37am (which is the time that I last **forced** it to fetch e-mails from Tools)
queue:work
Last run: ? Last successful run: ? Try to clear cache to force command to start.

**Background Jobs**
11 queued jobs running at the same time as the last successful run above

**Problems & Sympoms**
When I send an e-mail to the mailbox's e-mail address, the e-mail is definitely coming into the actual e-mail account - I can see it come in.
The settings being used for the e-mail account under **Fetching E-mails** are definitely correct, because any other permutation of settings results in a error when Testing the connection
Tickets do get created but **only** when I fetch e-mails manually from Tools
I've tried changing the mailbox's e-mail address to another domain (on the same host) - still the same symptoms

Can anyone please tell me where I'm going wrong here? Is this something wrong with my installation? With my environment? With my settings? With something else??

Thank you and Kind Regards
Gopal

**Comment by freescout-helpdesk** [comment]
Most likely there is some problem with the background cronjob: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

**Comment by gopal-thakur** [comment]
> 
> 
> Most likely there is some problem with the background cronjob: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#9-configuring-cron-jobs

Hi Support team,

Thank you for the response

Attached is a screenshot of my cPanel config for the cron task - (the orange box is my domain name) - does the config look correct?

Also, I don't remember doing anything regarding this:
**crontab -u www-data -e**

How do I add this to my config via cPanel? I'm hosting the site on a HostGator server

I appreciate your assistance and look forward to resolving this

Thanks,

![CronScreenshot](https://user-images.githubusercontent.com/62390255/77137861-fee61280-6a45-11ea-8fe2-7b9386b580e4.jpg)

**Comment by gopal-thakur** [comment]
And here is a screenshot of the cron section under Freescout System Status (Manage --> System)

![CronScreenshot2](https://user-images.githubusercontent.com/62390255/77138101-ede9d100-6a46-11ea-8271-bdceda810f11.jpg)

That time mentioned is about 5 hours ago

Does this mean the cron job is not working properly even though it shows that it is running?

Thanks,

**Comment by gopal-thakur** [comment]
Hi Support
I'm still stumped with this problem of e-mails not being fetched.
Ever since the last time I posted, I've since tried configuring the absolute path to php in cron, changing the version of php running on the web server (which incidentally is hosted on a Reseller hostgator), and still no luck with the cron job running. 
Right now, the only way I can open tickets from e-mail is by clicking on the 'Fetch E-mails' button under FreeScout Tools

Is there a way to resolve and/or get around this?

I am willing to pay for escalated support, assuming FreeScout provides this.

Kindly would you advise?

Thanks

**Comment by freescout-helpdesk** [comment]
> I am willing to pay for escalated support, assuming FreeScout provides this.

No paid support is provided by us. You may need to find a technical assistant.

**Comment by jrajski** [comment]
Hi, I'm facing very similar issue

**Comment by diguinho2018** [comment]
Some hosts request the php cron job to be used like that:
`/usr/local/bin/php /XXXXX/XXXXX/public_html/path/to/cron/script `
or
`/usr/local/bin/ea-php99 /XXXXX/XXXXX/domain_path/path/to/cron/script`

Where ea-php99 is the version of php script running on your server.
Recently I had an issue with cron job not running and I started to use this line:
`/usr/local/bin/ea-php70 /XXXXX/XXXXX/domain_path/path/to/cron/script`
