### ISSUE TITLE
Feature Request: show signature in conversation history

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#549]
Hey there,

I think it would be nice to have a feature that enables the user to show their signature in the conversation history. Currently, it is not displayed and which might be confusing.

Thoughts? Maybe make this an option on a per-user basis.

Thanks in advance,
matsn0w

**Comment by freescout-helpdesk** [comment]
Each mailbox has Email Signature, which is displayed in emails to customers. In Email Signature user name can be added.

**Comment by matsn0w** [comment]
Hi,

Yes, it is. But what I mean is that, when viewing a conversation, only the body of the messages are being showed. I'd like to see my own signature in there as well. 

The signature says 'kind regards', which isn't displayed in the history. This is sometimes confusing.

Cheers

**Comment by freescout-helpdesk** [comment]
In emails to customers it is already displayed.
