### ISSUE TITLE
Conversations bulk actions

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#55]
See how it works in Help Scout.

**Comment by Junker** [comment]
i'm ready to do it..

**Comment by freescout-helpdesk** [comment]
OK. Within this task floating panel will need to be developed:

![2018-11-14_10-55-26](https://user-images.githubusercontent.com/40499291/48468044-dcae0600-e7fb-11e8-8150-9385b4b1be27.png)

It should be universal, there should be possibility to display such floating panel on any page in future.

**Comment by freescout-helpdesk** [comment]
Done
