### ISSUE TITLE
Attachments issue

### ISSUE THREAD

**Issue by jrajski** [freescout-helpdesk/freescout#550]
Hi,
I was testing your demo, sending different attachments. I've discovered that if I send only attachment (from gmail account) without text, attachment is displayed correctly. See screenshot below
![image](https://user-images.githubusercontent.com/62745636/77744365-d186ff00-7019-11ea-8457-26c22b62d24d.png)

So it's ok. But if I enter any text inside email and add the same attachments (to exclude scenario that issue is related to size of attachments), there is no possibility to download attachments.

![image](https://user-images.githubusercontent.com/62745636/77744513-01ce9d80-701a-11ea-85df-adafdeebbb29.png)

But there is still attachment icon on the list
![image](https://user-images.githubusercontent.com/62745636/77744567-1743c780-701a-11ea-90fd-c67bcc4496ba.png)

**Comment by freescout-helpdesk** [comment]
We could not reprodue the issue. Are you sending emails from https://mail.google.com or using some software (Outlook, etc)?

![2020-03-29_11-51-53](https://user-images.githubusercontent.com/40499291/77842585-c1a32280-71b3-11ea-8712-92cdee111cba.png)

**Comment by jrajski** [comment]
I was using website mail.google.com
Now I’m using mobile gmail app and I’m forwarding the same email and in
most cases I’m still able to reproduce this issue. My current idea is it
might be somehow related to special characters in emails’ topic.

The same email sent without polish special characters in topic works fine.

W dniu niedz., 29.03.2020 o 08:08 FreeScout <notifications@github.com>
napisał(a):

**Comment by freescout-helpdesk** [comment]
The issue has been fixed. This was happening due to incorrect directory permissions on the demo.freescout.net
