### ISSUE TITLE
Feature Request: Custom views

### ISSUE THREAD

**Issue by jrajski** [freescout-helpdesk/freescout#551]
Default way of working is to check different mailboxes. You can check quickly if there are any new messages assigned to you looking on dashboard. I'd like to propose different approach where user can define custom view. 

There would be an additional dropdown on main bar 
![image](https://user-images.githubusercontent.com/62745636/77750714-963dfd80-7024-11ea-8841-63da3f0f954b.png)

On the list, there would be a link to settings, where customer could define a new view. 
Each view would need to be configured by providing:
* mailboxes in scope
* ticket statuses
* assignee 
* tags
* custom fields

In this way, User could define a very powerful view, customized for his needs. If user needs to see in one place all emails that are not yet assigned, to quickly assign them to other users - new view. Each User could have a nice view with all emails from different mailboxes in one place. That would have huge impact on productivity.

**Comment by freescout-helpdesk** [comment]
This can be implemented as a module, not in the core. If anybody is willing feel free to implement it as a module and we can share it as a free addon.
