### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [freescout-helpdesk/freescout#552]
It is possible to migrate the personal account to organization?
https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by freescout-helpdesk** [comment]
Nope.

**Comment by Neustradamus** [comment]
@freescout-helpdesk: Why?

It is better for team management, options, ...

**Comment by Neustradamus** [comment]
@freescout-helpdesk: I think that the best solution is (in few minutes):
- Change your username to freescoutaccount (or other): https://github.com/settings/admin
- Create freescout-helpdesk organization: https://github.com/organizations/new

And:
- Transfer freescout into freescout-helpdesk org: https://github.com/NEWACCOUNTUSERNAME/freescout/settings

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams
