### ISSUE TITLE
"Trying to access array offset on value of type null;"

### ISSUE THREAD

**Issue by sp8233218** [freescout-helpdesk/freescout#554]
In the latest version, i got a lot of another errors in the sending logs:

Trying to access array offset on value of type null; ... 

![46O8XQg 1](https://user-images.githubusercontent.com/61975526/78293908-0b806580-7532-11ea-9150-0578eef326f8.png)

**Comment by freescout-helpdesk** [comment]
What is your PHP version?

**Comment by sp8233218** [comment]
PHP: 7.3

**Comment by freescout-helpdesk** [comment]
Let's continue here: https://github.com/freescout-helpdesk/freescout/issues/468

If you can provide us access to your server to check this issue please email at support@freescout.net
