### ISSUE TITLE
Use of undefined constant FT_UID - assumed 'FT_UID

### ISSUE THREAD

**Issue by jrajski** [freescout-helpdesk/freescout#556]
I've completed freescout setup yesterday, I've configured sending mailbox (gmail account) and one mailbox (the same gmail account). I went through enabling less secure app etc. While trying to test connection and send test email, it's working. I'm receiving this test email. However, when trying to send email from this mailbox, it's not working, email never reaches its destination. The same problem is with downloading email. I see in logs this error. There is the same error every minute. Any idea how could it be solved?
PHP 7.0

Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP) {"exception":"[object] (ErrorException(code: 0): Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP) at /var/www/html/freescout/vendor/webklex/laravel-imap/src/config/imap.php:105)
#0 /var/www/html/freescout/vendor/webklex/laravel-imap/src/config/imap.php(105): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Use of undefine...', '/var/www/html/f...', 105, Array)
#1 /var/www/html/freescout/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(66): require('/var/www/html/f...')
#2 /var/www/html/freescout/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#3 /var/www/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#4 /var/www/html/freescout/overrides/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register(Object(Webklex\\IMAP\\Providers\\LaravelServiceProvider))
#5 /var/www/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#6 /var/www/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#7 /var/www/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#8 /var/www/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#9 /var/www/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#10 /var/www/html/freescout/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"}

**Comment by freescout-helpdesk** [comment]
https://github.com/Webklex/laravel-imap/issues/30

**Comment by jrajski** [comment]
Thanks! It helped:
sudo apt-get update -y
sudo apt-get install -y php7.2-imap
