### ISSUE TITLE
Undefined variable: folder

### ISSUE THREAD

**Issue by jrajski** [freescout-helpdesk/freescout#557]
Error message: Undefined variable: folder; File: /var/www/html/freescout/app/Console/Commands/FetchEmails.php (124)

Issue related with downloading email. I've checked similar threads here, but haven't found anything. I have configured one gmail account, I have seleted all available IMAP folders (incoming emails config) I was trying also only with default INBOX, result is the same. 
![image](https://user-images.githubusercontent.com/62745636/78354111-92255900-75ab-11ea-80bc-8adb4063982b.png)

Could you suggest me how could I solve this issue?

**Comment by freescout-helpdesk** [comment]
It will be fixed in the next release.

Here is the patched /app/Console/Commands/FetchEmails.php: [FetchEmails.txt](https://github.com/freescout-helpdesk/freescout/files/4426799/FetchEmails.txt)

**Comment by jrajski** [comment]
After changing FetchEmails.txt as in provided attachment, I have no longer this error in logs. However emails are still not fetched correctly. This is what I see in logs (I currently have only INBOX IMAP folder marked, if other folders are configured as well, then this message is displayed for all folders)


4 | [2020-04-03 13:33:04] Fetching finished
-- | --
**3 | [2020-04-03 13:33:04] Could not get mailbox IMAP folder: INBOX**
2 | [2020-04-03 13:33:03] Mailbox: Allegro: PrintONE_pl
1 | [2020-04-03 13:33:03] Fetching UNREAD emails for the last 3 days.
