### ISSUE TITLE
Gsuite

### ISSUE THREAD

**Issue by oakblue** [freescout-helpdesk/freescout#558]
Hello, I am looking at using freescout.  I use Gsuite as my email provider, is google dropping support to allow freescout to access the incoming mail using imap?

**Comment by freescout-helpdesk** [comment]
We will try to make FreeScout compatible with oAuth IMAP and SMTP: https://github.com/freescout-helpdesk/freescout/issues/390

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/390#issuecomment-631886014
