### ISSUE TITLE
Looking to create a "custom app" as it is in Helpscout

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#560]
I am looking for a **custom app**, same way that Helpscout has. See screenshots for example.

<img width="864" alt="Screenshot 2020-04-05 at 7 19 24 PM" src="https://user-images.githubusercontent.com/3481438/78500148-81730f80-7772-11ea-8622-e7d4f4c80f8a.png">
<img width="859" alt="Screenshot 2020-04-05 at 7 19 32 PM" src="https://user-images.githubusercontent.com/3481438/78500150-83d56980-7772-11ea-9ca8-6e28a79b2412.png">

https://developer.helpscout.com/custom-apps/ for more info.

Has anyone worked or is working on this already?

PS - This place is might not be the best place to ask for this, but I feel this should be part of Freescout, it can even be a paid module.

**Comment by freescout-helpdesk** [comment]
https://nwidart.com/laravel-modules/v2/introduction

**Comment by rosinghal** [comment]
I know about it, but what I am suggesting is it will be nice to have a generic module which can be used for multiple use case.

**Comment by freescout-helpdesk** [comment]
Generic module is almost no use, as each module has specific name is generated via console command.
