### ISSUE TITLE
Ability to hide "Admins" from following list?

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#561]
Hi again,
This is very similar to #456 where we provided the option to hide Admins from being shown the "Assign" lists. I've noticed that Admins are also showing up in the "Following" sidebar which is causing some confusion and concerns by users thinking that people are monitoring their messages. Would this be possible to have the same functionality built for hiding Assignees added to hide specific Followers? Knowing that some Admins will also be legitimate followers.
 
Thanks for all the hard work.

**Comment by freescout-helpdesk** [comment]
Yes. Will be fixed.

**Comment by freescout-helpdesk** [comment]
"hidden" admins will be automatically hidden in the "Following" list.

**Comment by freescout-helpdesk** [comment]
Fixed in Followers Module v1.0.1
