### ISSUE TITLE
Question: Freescout is now on Cloudron, how to migrate from existing hosting?

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#562]
Hi,

since 4 months our volunteers organization is using Freescout, the average age of these users is 70+ and they like it :-)

Since today FreeScout is available at [Cloudron](https://cloudron.io/store/index.html)!!

The big question is: how do we easily migrate settings and emails/attachments from current hosting to the Freescout Cloudron-app?

Wouldn't it be great to have a system option to export all and import all ;-)?

Keep up the good work as we like it very very much!

Kind regards,

MarcelC

**Comment by freescout-helpdesk** [comment]
You need to copy:
- Database
- `/storage/app` folder

**Comment by imc67** [comment]
Is it difficult to add two buttons (backup and restore) to the GUI of Freescout?

**Comment by freescout-helpdesk** [comment]
> Is it difficult to add two buttons (backup and restore) to the GUI of Freescout?

Here is the task: https://github.com/freescout-helpdesk/freescout/issues/564
