### ISSUE TITLE
Lots of errors in Laravel log

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#563]
Since a few days (?) there is a returning error in the Laravel log:

`[Webklex\IMAP\Message] Error: iconv(): Wrong charset, conversion from `default' to `UTF-8' is not allowed; File: /home/*******/domains/********.**/public_html/********/overrides/Webklex/IMAP/Message.php (838)`

What could this be and how can I solve this?

Kind regards,

MarcelC

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of the FreeScout?

**Comment by imc67** [comment]
yes, latest version 1.5.3

**Comment by imc67** [comment]
Probably the update to 1.5.3 (and after that discovering the errors) was already the solution, after almost 24 hours no more errors.
