### ISSUE TITLE
Backup and Restore buttons

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#564]
Add two buttons Backup and Restore to Manage --> System --> Tools

**Comment by diguinho2018** [comment]
That would be great feature to help keep the installation safe and backed up.

**Comment by fulldecent** [comment]
Please link to the new buttons or explain how to get there from here:


<img width="1935" alt="Screen Shot 2021-07-21 at 15 42 16" src="https://user-images.githubusercontent.com/382183/126550035-b286cb27-4cbe-42b0-b7f6-352d6647e9a2.png">

**Comment by freescout-helpdesk** [comment]
Backup and restore should be done using some other tools.
