### ISSUE TITLE
Workflow module: automated emails

### ISSUE THREAD

**Issue by jrajski** [freescout-helpdesk/freescout#565]
I've configured workflow module to trigger automatic reply only in specific scenarios (so standard autoreply won't work here). I have also configured for this inbox signature, where Name and Surname of User who replied is populated. And here comes my problem:

In those emails tirggered by wokrflow, name and surname in signature is "Workflow"
![image](https://user-images.githubusercontent.com/62745636/78888758-95648d00-7a62-11ea-92f5-963da1264fc3.png)

is there any way to have a workaround for this?

**Comment by freescout-helpdesk** [comment]
We will try to fix this.

**Comment by freescout-helpdesk** [comment]
What would you prefer to see as a name and surname in Workflow's messages?

**Comment by jrajski** [comment]
Hi, i ser three options
- name and surname of main user
- configurable name and surname for workflow emails
- skip name and surname for workflow emails

Option 2 and 3 would be preferable, I think



W dniu czw., 28.05.2020 o 08:15 FreeScout <notifications@github.com>
napisał(a):

**Comment by freescout-helpdesk** [comment]
We will not include signature in Workflow emails to customers.

**Comment by freescout-helpdesk** [comment]
Added in Workflows Module v1.0.11
