### ISSUE TITLE
Suggestion for wiki

### ISSUE THREAD

**Issue by danielktaylor** [freescout-helpdesk/freescout#566]
Had to debug connection problems with Gmail that were bothering me all evening.

Would suggest adding information to the [Fetching Emails](https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails) page to help others.

At the bottom of the "Possible Error #1" section, something like this:

> You may also need to do Google's "Captcha Unlock"  (https://accounts.google.com/DisplayUnlockCaptcha) to unblock FreeScout from Gmail if you are getting this error.

> If you keep getting this error over and over, make sure you turn on 2FA in your Google account and set up an "App Specific Password" for FreeScout. Google seems less likely to block FreeScout using this method.

Also, have to say I love this software. We needed something free and robust for a large group of 100s of volunteers that sprung up to help tackling a big problem related to covid-19, and you guys saved our butt. It's been working great so far, and has just the right number of features.

**Comment by freescout-helpdesk** [comment]
Thanks. Wiki updated: https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails
