### ISSUE TITLE
Freescout will generate a new ticket everytime an empoyee responses to an update

### ISSUE THREAD

**Issue by dseegers** [freescout-helpdesk/freescout#567]
We have been using Freescout as a help desk system for some time now and it is great. But we are facing one problem. 

When an employee is responding on a notification mail (with those `Please reply above this line in` it) it will generate a new ticket and not a response on the ticket.
When a customer is relying on an email it is working. 
Both emails are send using Amazon SES.

We are using version 1.5.3 of Freescout
- nginx/1.17.5
- PHP 7.2.24

Is there somewhere I can start debugging? 

It got al the right permissions:

![image](https://user-images.githubusercontent.com/6848396/78989362-b47f1f80-7b33-11ea-8ea4-da10ee064a61.png)

**Comment by freescout-helpdesk** [comment]
You should check https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php

Amazon SES is known to replace Message-ID header with it's own one. So maybe this causes the issue.

**Comment by ChrisRAoW** [comment]
This issue should be fixed with this PR: #568
