### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#57]
todo

**Comment by freescout-helpdesk** [comment]
Anybody needs this?

**Comment by amirkhan7** [comment]
It would be nice to have. Not essential however.

**Comment by lekkerduidelijk** [comment]
This is actually the only thing I'm really missing after switching from HS. 

Having shortcuts makes processing a greater volume of emails way faster.

**Comment by vitaliany** [comment]
+

**Comment by joris85** [comment]
Yes needed!
I would like this list of functions :-D
https://docs.helpscout.com/article/419-keyboard-shortcuts

**Comment by joris85** [comment]
I asked a developer what the start of some important and basic shortcuts will cost.
If anybody is willing to invest together in this we can maybe make most of the shortcuts.

**Comment by PhrantiK** [comment]
+1 from me. I'll check back in a few months to see if there's any progress.

**Comment by jaydio** [comment]
+1 from me as well!

**Comment by jaydio** [comment]
> I asked a developer what the start of some important and basic shortcuts will cost.
> If anybody is willing to invest together in this we can maybe make most of the shortcuts.
> 
> So anybody?

Considering it, how much are we talking?

**Comment by PhrantiK** [comment]
Keen to chip in too, if anyone has some rough costs for developing to speed this up I'm game.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/keyboard-shortcuts/
