### ISSUE TITLE
Reply mails in same mailbox for full threading

### ISSUE THREAD

**Issue by nebulade** [freescout-helpdesk/freescout#574]
Hi,

(sorry if this was already answered somewhere, but I didn't find an answer so far)

we at Cloudron currently use a shared mailbox via mail clients for support and are about to start using FreeScout, for a better support flow. So far we have setup mail clients to place the response mails from our side next to the incoming mails, which allows for nice threading in mail clients, without loosing history in case the mailbox is access directly.
From what I can tell FreeScout does not put sent out reply mails anywhere in the actual mailbox (as far as I can tell not even into `Sent`). I wonder what I miss here with regards to a more centric email flow and what the recommendations are around how to ensure the reply mails end up also in the same mailbox. 

I did try to use the auto-bcc feature to ensure the replies get put into the support mailbox, but that just means the message flow within FreeScout gets confused and lists the double mails there.

Anyone with a similar use-case or ideas how to get this working?

Thanks a lot,
Johannes

**Comment by freescout-helpdesk** [comment]
Actual reply emails can be found in the `Sent` folder of the mail service provider which is used.

**Comment by imc67** [comment]
> Actual reply emails can be found in the `Sent` folder of the mail service provider which is used.

After 4 month of use I now realized that sent mails from Freescout (using SMTP of the same IMAP  mailbox) is not stored in any folder of the email provider. Is that correct?

**Comment by freescout-helpdesk** [comment]
Outgoing emails should be stored in the `Sent` folder of the email provider. If they are not there, check with your email provider why.

**Comment by nebulade** [comment]
I was always under the impression, that the email clients would put message in the sent folder, and thus FreeScout would have place a copy int the sent folder, after a quick grep through the code, I don't seem to find any code for that. Maybe some providers also have server side code to ensure a copy is put into the sent folder?

**Comment by nebulade** [comment]
Yes so all I can find is the information that the email client would put the message into the configured sent folder, usually clients like Thunderbird detect this folder automatically and thus there is no further configuration required. Since FreeScout is the MUA in this case, it is responsible to place a copy of the sent mail somewhere into the mailbox. Ideally it would be possible configure this imap folder, with regular `sent` being the default.
Furthermore it would be really nice, if one could configure to copy the sent mail next to the other mails for threading. Given that FreeScout can already be configured from which imap folder incoming mails are picked, it would also save the reply mails in those folders from where the original inquiry mail was picked from.

If there is any chance of such a change to be integrated, I may be able to look into implementing this, but I probably would need some assistance and pointers where to start and where to put things.

Thanks!

**Comment by freescout-helpdesk** [comment]
Ok. Feel free to implement it.

Checkbox enabling saving replies should be added to `Connection Settings --> Sending Emails` (disabled by default). Select2 below should allow to choose the folder (`Sent` by default).

Replies to customers are being sent in https://github.com/freescout-helpdesk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php

**Comment by freescout-helpdesk** [comment]
FYI. Gmail / G Suite does save outgoing emails in the Sent folder.

**Comment by nebulade** [comment]
I guess this shows that the default setting would be to not copy the reply email to the inbox to avoid duplication and not change the expected behavior. I wonder how gmail works in such a case with the thunderbird defaults and if it is smart enough on the server side to not duplicate messages.

**Comment by nebulade** [comment]
I've update the patchset to make it work. Would be great to get some feedback on this. The dev branch name mentions the "sent" folder however any folder can be configured.

**Comment by nebulade** [comment]
The patch also relies on the rather simplistic `imap_mail_compose` API for the lack of a better method known by me. This means attachments will currently not be handled correctly. Might be nice to fix that, but I am out of ideas doing this with php.
