### ISSUE TITLE
Proper way to run behind Nginx Reverse Proxy

### ISSUE THREAD

**Issue by jarranz2** [freescout-helpdesk/freescout#575]
Hello,

I'm trying to run Freescout behind a nginx reverse proxy. I'm not using Docker.

In .env file I've the following details:

APP_URL: https://mydomain.com
APP_FORCE_HTTPS:true

In Nginx reverse proxy, I have the following configuration:

`server {
        listen 80;
        listen 443 ssl;

        server_name mydomain;

  ssl_certificate /etc/letsencrypt/live/mydomain/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/mydomain/privkey.pem; # managed by Certbot

        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;

        location / {
                    proxy_pass http://the-ip-of-freescout-machine;
  }
}
`

Freescout is not displaying the website and images under ssl. Firefox can not establish a secure connection.

Any help?

Thank you very much and excuse my english, I'm not native speaker.

**Comment by freescout-helpdesk** [comment]
It looks like we can't provide help here.

**Comment by Processeur** [comment]
Hi Jarranz2,

I have exactly the same issue with apache reverse proxy and freescout. Did you found a solution by yourself?

**Comment by jarranz2** [comment]
No

**Comment by Processeur** [comment]
Too bad the tool seems to be promising.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/887
