### ISSUE TITLE
Workflows module not saving properly with "OR" conditions

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#579]
**Description**
Issue started happening with latest release. Whenever I save something in workflow which has multiple OR condition, it gets pushed to next AND block.
Please check below GIF for more details.

**Preview**
![](http://g.recordit.co/2mkUUoVYzj.gif)

Version - 1.5.3

**Comment by freescout-helpdesk** [comment]
Will be fixed

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.11
