### ISSUE TITLE
Error accessing customer history

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#584]
After merging two user email profile (I added e email of the second profile in the first) I get the following error when I enter in client history (for ex. https:/freescout.test.com/customers/2)
Whoops, looks like something went wrong.

This happens for every customer, not only for the one I edited.

I don't know if the problem is caused by the "merge".

This is the logs of the error:

> Trying to get property 'id' of non-object (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) {"userId":1,"email":"test@test.com","exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) at /var/www/freescout/site/Modules/Workflows/Providers/WorkflowsServiceProvider.php:224, ErrorException(code: 0): Trying to get property 'id' of non-object (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) at /var/www/freescout/site/Modules/Workflows/Providers/WorkflowsServiceProvider.php:224, ErrorException(code: 0): Trying to get property 'id' of non-object (View: /var/www/freescout/site/resources/views/conversations/partials/bulk_actions.blade.php) at /var/www/freescout/site/Modules/Workflows/Providers/WorkflowsServiceProvider.php:224, ErrorException(code: 0): Trying to get property 'id' of non-object at /var/www/freescout/site/Modules/Workflows/Providers/WorkflowsServiceProvider.php:224)

**Comment by Filoz** [comment]
Hi,
I've got the same error on your demo: https://demo.freescout.net/customers/9

**Comment by Filoz** [comment]
Ok,
I've found that the error happens when "workflow module" is active

**Comment by Filoz** [comment]
I'm sorry for multiple messages;

The error happens in WorkflowsServiceProvider line 224
            `$workflows = Workflow::where('mailbox_id', $mailbox->id)`
The problem is that $mailbox is null (or empty).

A little (ugly) tmp fix could be:

```
            $workflows = Workflow::where('active', true)
                ->where('type', Workflow::TYPE_MANUAL);
                if (is_object($mailbox)){
                    $workflows->where('mailbox_id', $mailbox->id);

                }
                $workflows = $workflows->orderBy('sort_order')->get();
```

**Comment by Filoz** [comment]
Or, maybe better:

if (!is_object($mailbox)){
    return;
}


Probably is more correct this tmp fix.
What do you think?

**Comment by freescout-helpdesk** [comment]
Thanks. It will bee fixed.

**Comment by joris85** [comment]
Ah! then i understand what happend with my users.
I had the same error as you know.

I think after merging it should be possible to delete the old one.
I jus empty there email field so they kinda disappear :-D

Deleting the old one would be nice feature.
I would say a new page with a customer manager, add delete, merge, search.

**Comment by joris85** [comment]
Hi there,
Stil not fixed in my version, also not after last update this week.
So i wonder if this should be fixed or just not fixed yet.

I want my other colleges to use it but then we go with the whole team in Freescout. 
Seeing full history from a customer is a must.
So if somebody would like to fix it for hour rate let me know.

**Comment by joris85** [comment]
Hi Freescout, 

This is an URGENT matter for us.
Can anybody help me with this fix or do o need to hire a developer.
Can i pay you guys to fix something like this?

If something goes wrong like this i expect some support, i am not expecting to get support for free ;-)

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version of Workflows Module.

**Comment by joris85** [comment]
My bad i did not think it would be in a module. Thank you so much!

**Comment by muhzak** [comment]
I am getting this error again.
