### ISSUE TITLE
Inline images do not display and attachments lead to 404 errors

### ISSUE THREAD

**Issue by SFFLAB** [freescout-helpdesk/freescout#586]
See attached for an example; clicking the attachment leads to a generic 404 error.

<img width="1163" alt="Screen Shot 2020-04-20 at 10 57 09 PM" src="https://user-images.githubusercontent.com/54030421/79820583-98ad2200-835a-11ea-8650-16ec3cc7a107.png">

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/522

**Comment by SFFLAB** [comment]
This doesn't really help. Neither the 'old' nor proposed new location directives are in our configuration file, and we are on the latest release which is well after this issue was identified and closed.

**Comment by SFFLAB** [comment]
Oddly we didn't have the prior location directives configured, but adding the new ones fixed it.
