### ISSUE TITLE
Customer History by mailbox

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#587]
Hi,
referring to #466 and #448 
there is also a bigger problem leaving any user accessing to contact profile: every user (not only admin) can see conversation history of a client  and the conversation history is loaded for all mailboxes.
So every user can see the list of tickets in every mailboxes (going one by one in customer profile)
/customers/1
/customers/2
/customers/3
...

Is easy to  through the list of customers.

**Comment by freescout-helpdesk** [comment]
Thanks. Will be fixed.
