### ISSUE TITLE
A little graphic error

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#588]
![image](https://user-images.githubusercontent.com/5341996/80213947-4c076680-863a-11ea-870d-f97744ba0514.png)

the border should be under custom fields.

It can be solved adding class "clearfix" in fields_view.blade.php in custom fields module:

    @if (!$on_create)
        <div class="conv-top-block clearfix">
            <form class="form-horizontal" method="POST" action="" id="custom-fields-form">
    @else
            <div id="custom-fields-form" class="cf-mode-create">
    @endif

this is the result:
![image](https://user-images.githubusercontent.com/5341996/80214228-c1733700-863a-11ea-9c8f-4549c9dea51a.png)

**Comment by freescout-helpdesk** [comment]
Thanks. It will be fixed.

**Comment by freescout-helpdesk** [comment]
Which browser are you using?

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Fields module v1.0.5
