### ISSUE TITLE
Integration of "Satisfaction Ratings Module" with "Slack Module"

### ISSUE THREAD

**Issue by rosinghal** [freescout-helpdesk/freescout#589]
It will be nice to have Slack integration for **Satisfaction Ratings Module**.

**Comment by freescout-helpdesk** [comment]
Maybe it will be implemented.

**Comment by rosinghal** [comment]
I understand that it might not be planned but do we have roadmap of things defined somewhere?

**Comment by freescout-helpdesk** [comment]
Nope.

**Comment by freescout-helpdesk** [comment]
We will let you know when it will be implemented.
