### ISSUE TITLE
Auto Bcc for mailbox

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#59]
todo

**Comment by guestisp** [comment]
Could you please elaborate more ?
What's the meaning of this and how did you plan to do this ?

**Comment by freescout-helpdesk** [comment]
See Auto BCC at the very bottom here: https://docs.helpscout.net/article/499-update-your-user-profile

**Comment by finalwebsites** [comment]
Your Helpscout link shows a settings page which is connected to the user. I think it would be much better to connect that function to the mailbox. This way I'm able to store my outgoing emails in the original mailbox. (Right now I do the same with Freshdesk and my G Suite account)
Make sense?
And would it be easier/faster to develop to add this autoBcc field to the mailbox form? 
See screenshot
![DT_Selection_046](https://user-images.githubusercontent.com/90638/60961052-96b62d00-a30b-11e9-93bb-9b8a45fdf224.jpg)

**Comment by freescout-helpdesk** [comment]
@finalwebsites The idea seems to be good, but "stored" emails will be fetched into mailbox.

**Comment by finalwebsites** [comment]
Do you say that I don't need a Bcc to get the send email messages in my mailbox as well? (sorry this question doesn't belongs here)

**Comment by foliovision** [comment]
Definitely better to have the BCC set up on a per mailbox basis. Would be very, very simple and would those of us using CRM software keep a record of our Freescout conversations. I'll put a $200 bounty on this if optional BCC can be added next week on a per mailbox basis as Finalwebsites suggested. This is fairly urgent for us.

The workaround of adding BCC by hand for every email will be too much. I suppose we could hardcode it for every outbound email from all boxes but that's a bit awkward and doesn't help anyone else. I'd rather pay the bounty but we'd like it done fast or we'll have to it ourselves.

Thanks, Alec

**Comment by freescout-helpdesk** [comment]
@foliovision https://www.patreon.com/FreeScout

**Comment by foliovision** [comment]
Brilliant! Pledge made.

**Comment by foliovision** [comment]
Thanks again. I'm now using this. I'm very happy to have mailboxes as one of our mailboxes generates a lot of service emails which are better kept out of our CRM.
