### ISSUE TITLE
Cache being created as root?

### ISSUE THREAD

**Issue by shiroi2003** [freescout-helpdesk/freescout#590]
My freescout are crashing everyday but I figured out that cache are being created as root.
How can I change that?

![image](https://user-images.githubusercontent.com/2958083/80292212-3887f880-872b-11ea-8f0d-201f98b88688.png)

**Comment by freescout-helpdesk** [comment]
Make sure you don't run any cron jobs under root user.

**Comment by shiroi2003** [comment]
Solved correcting this. Thank you!
