### ISSUE TITLE
Time tracker doesn't pause

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#592]
Hi,
I've noticed some problem when the counter should pause:

_________________________________________________________

### Option 1
When I set to **"The timer starts when the conversation is assigned to the user."** and I pause the timer, like that (I made a test on your demo):
![image](https://user-images.githubusercontent.com/5341996/80303793-b93e0780-87b2-11ea-9110-5a14aefe3e28.png)

and after some time I reload the page, I get:
![image](https://user-images.githubusercontent.com/5341996/80303810-ce1a9b00-87b2-11ea-996c-d0fd0ff33f71.png)

_________________________________________________________

### Option 2
I've set time tracking with option **"The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation."**.  (I made a test on my installation)
I've noticed that it never pause. 
If I leave the page at 1:00, and I came after some minutes the counter has grown.
(I tried also closing the browser)

![image](https://user-images.githubusercontent.com/5341996/80303708-1a191000-87b2-11ea-92ee-c8939f7d09bc.png)

**Comment by freescout-helpdesk** [comment]
Thanks. We will check it.

**Comment by keenminded** [comment]
I can confirm this is still an issue.

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/issues/726

**Comment by freescout-helpdesk** [comment]
If anyone can give access to the server to check the issue, please send an access details to support@freescout.net

**Comment by freescout-helpdesk** [comment]
Please continue at https://github.com/freescout-helpdesk/freescout/issues/726

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the Time Tracking Module v1.0.4

**Comment by Filoz** [comment]
Hi,
after last update, I can't see timer under the conversation title.

It isn't visibile in conversation page; The module is active anche configured.
![image](https://user-images.githubusercontent.com/5341996/99898964-ff563d80-2ca5-11eb-859d-e832fe1668e6.png)


There aren't error in logs
