### ISSUE TITLE
Custom Folders Module

### ISSUE THREAD

**Issue by vlance11** [freescout-helpdesk/freescout#594]
So we have purchased this Module, but this issue is when working on a ticket and closing it, it moves to the next ticket from the MAIN inbox.  

Also there is no sort option, we always see the closed/oldest tickets first.  So to see the active tickets you have to scroll past hundreds of closed ones before you see the tickets to answer.

Is this misconfigured?

**Comment by freescout-helpdesk** [comment]
We will check it.

**Comment by vlance11** [comment]
Thank you, any luck?  Now that we get 50+ tickets a day its really hard to use this module.  Everyone's just using the main folder since its all there anyways.

**Comment by vlance11** [comment]
@freescout-helpdesk  Any word on this?  The custom folders module is next to useless like this.  Now when trying to find tickets agents need to go 3-4 pages deep to find the newest.

**Comment by freescout-helpdesk** [comment]
It will be fixed soon. We will let you know.

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Folders module v1.0.1.

**Comment by vlance11** [comment]
This shouldn't be closed yet.  Still when answering questions in Custom Folders you are moved to the next ticket OUTSIDE of the custom folder.  It makes the folder near useless unless it can be a work list.
