### ISSUE TITLE
LDAP module get "invalid credentials"

### ISSUE THREAD

**Issue by innov2e** [freescout-helpdesk/freescout#599]
I would autenticate users on my Active Directory and I tried different configurations for LDAP module using:
```
LDAP Host: 10.201.0.200
PORT: 389
ENCRYPTION: none
BASEDN= DC=myorg,DC=it
LDAP FILTER empty
```
I tested more times using as Bind username these:

- myuser
- myuser@myorg.it
- CN=myuser
- CN=myuser,CN=Users

Every timie I get the error message with **Invalid credentials**. So I tried using this php file:
```
<?php
// Set the ldap server
$ldapurl = "10.201.0.201";
$ldapuser = "myuser@myorg.it";
$ldappass = 'mypassword';
// Set the debug flag
$debug = true;
// Set debugging
if ($debug) {
  ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
}
// connect to ldap server
$ldapconn = ldap_connect($ldapurl) or die ("Couldn't connect");
// binding to ldap server
echo "Trying to bind with $ldapuser - $ldappass\n";
$ldapbind = @ldap_bind($ldapconn, $ldapuser, $ldappass);
if (!$ldapbind) {
echo "Unable to bind to server $ldapurl\n";
echo "OpenLdap error message: " . ldap_error($ldapconn) . "\n";
exit;
}
echo "<p>";
echo "Successful bind!!! !";
?>
```
And I get a successful bind.
I tryed also to modify the .env file as suggested in issue [#506](https://github.com/freescout-helpdesk/freescout/issues/506) but with no success.

How I can debug further to get it working? What I am doing wrong? Any help is appreciated..

**Comment by freescout-helpdesk** [comment]
We will check what can be done.

**Comment by freescout-helpdesk** [comment]
Is `myuser` an administrator?

**Comment by innov2e** [comment]
here I am:
1) Yes 10.201.0.201 is available. My Freescout is 10.201.0.154. both on 10.201.0.0/24
2) Yes is the Administrator indeed...

PS I have almost completed the translatio in Italian where I have to post the zip file?

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. Your IT specialist may need to debug `/Modules/Ldap/Overrides/Adldap/Auth/Guard.php`

Translations can be sent from Manage --> Translate page.
