### ISSUE TITLE
Reply from some outlook applications give full email

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#602]
Hi there,

I love that Freescout cleans the older emails.
But some email clients probably whipe the code that freescout can regognize what is old or not.
So how about some Outlook applications. 
I get then the full history from the client, i send my last history of the client so at the end i still get all the old shit double, triple or more :-)

Is this something Freescout could fix or is this as usual a microsoft issue...

**Comment by freescout-helpdesk** [comment]
Duplicates https://github.com/freescout-helpdesk/freescout/issues/461
