### ISSUE TITLE
Ability to train for spam mail 

### ISSUE THREAD

**Issue by nebulade** [freescout-helpdesk/freescout#603]
Hi,

not sure if I just missed the settings somewhere, but since Freescout already has some spam support, I was wondering, how to configure it so when a ticket/mail gets marked manually as spam, it then also gets move to the mailbox spam/junk folder. This way the mail server can train its spam assasin or similar based on this input.

If this does not yet exist, I may be able to create a pull request for this, if there is a chance to get that merged. Also if so, where should such a setting be added?

Best,
Johannes

**Comment by freescout-helpdesk** [comment]
It is provided as a module https://freescout.net/module/spam-filter/

**Comment by nebulade** [comment]
Ah I didn't notice. Purchased it now. Thanks.
