### ISSUE TITLE
Customer History

### ISSUE THREAD

**Issue by vlance11** [freescout-helpdesk/freescout#604]
When trying to view a history of customers messages all we are presented with is  i.e. /customers/342

Whoops, looks like something went wrong.

**Comment by freescout-helpdesk** [comment]
It would be good to have an error message from logs.
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by freescout-helpdesk** [comment]
Update Workflows module to the latest 1.0.9 version.
