### ISSUE TITLE
Allow to cancel queued jobs

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#606]
Hi,

It's the first time I noticed this situation:
![image](https://user-images.githubusercontent.com/5341996/81471962-3d51af80-91f5-11ea-96d7-191e006b3556.png)

It's stuck like that since one hour.
What does it means? I made some test and looks like everything is working..

best regards
Filippo

**Comment by Filoz** [comment]
I've probably found the error:

` Address in mailbox given [[p.test@gmail.com]] does not comply with RFC 2822, 3.6.2. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [[p.test@gmail.com]] does not comply with RFC 2822, 3.6.2. at /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)
[stacktrace]
#0 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(272): Swift_Mime_Headers_MailboxHeader->assertValidAddress('[p.test@gmail...')
#1 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(117): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(74): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(61): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(71): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('Cc', Array)
#5 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(375): Swift_Mime_SimpleHeaderSet->addMailboxHeader('Cc', Array)
#6 /var/www/oracle/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(354): Swift_Mime_SimpleMessage->setCc(Array)
#7 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Message.php(161): Swift_Mime_SimpleMessage->addCc('[p.test@gmail...', NULL)
#8 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Message.php(114): Illuminate\\Mail\\Message->addAddresses('[p.test@gmail...', NULL, 'Cc')
#9 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(278): Illuminate\\Mail\\Message->cc('[p.test@gmail...', NULL)
#10 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(121): Illuminate\\Mail\\Mailable->buildRecipients(Object(Illuminate\\Mail\\Message))
#11 [internal function]: Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}(Object(Illuminate\\Mail\\Message))
#12 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(220): call_user_func(Object(Closure), Object(Illuminate\\Mail\\Message))
#13 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send('emails/customer...', Array, Object(Closure))
#14 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#15 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable(Object(App\\Mail\\ReplyToCustomer))
#16 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send(Object(App\\Mail\\ReplyToCustomer))
#17 /var/www/oracle/site/app/Jobs/SendReplyToCustomer.php(189): Illuminate\\Mail\\PendingMail->send(Object(App\\Mail\\ReplyToCustomer))
#18 [internal function]: App\\Jobs\\SendReplyToCustomer->handle()
#19 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#20 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#22 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#23 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#24 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\SendReplyToCustomer))
#25 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\SendReplyToCustomer))
#26 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\SendReplyToCustomer), false)
#28 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#29 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#30 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#31 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#32 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#33 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#34 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#35 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#36 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#37 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#38 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#39 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#40 /var/www/oracle/site/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#41 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#42 /var/www/oracle/site/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /var/www/oracle/site/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /var/www/oracle/site/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /var/www/oracle/site/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /var/www/oracle/site/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 {main}
"}`


The email address is correct... but it looks like a problem in validation

**Comment by freescout-helpdesk** [comment]
Button allowing to cancel queued jobs should be added.

**Comment by Filoz** [comment]
I've also found the cause:
I don't know why but in a CC, was used
[p.test@gmail.com]
instead of
p.test@gmail.com

Is there a way to "stop" the job? Maybe going in the db?

**Comment by Filoz** [comment]
I've deleted record founded in jobs.
It looks like it's fine now :)

**Comment by raramuridesign** [comment]
@freescout-helpdesk is there a way all qued jobs can be removed apart from removing them from the database.
Or is there another recommended way... in case something was done incorrectly?

**Comment by freescout-helpdesk** [comment]
There should be "Cancel" button next to the queued job.

**Comment by raramuridesign** [comment]
@freescout-helpdesk Looking for a way to remove all jobs in one go. apart from doing this via the database.
