### ISSUE TITLE
Installation ERROR (PHP 7.4 supported?)

### ISSUE THREAD

**Issue by Newboie** [freescout-helpdesk/freescout#607]
Hello

I have a question regarding the installation of FreeScout. We want to use a WebServer which has normally all needed requirements for FreeScout. I created a MySQL DB and FTP Access for the subdomain, just loaded all content of the installation in Htdocs and used a webbrowser to surf my subdomain. It shows directly the web installer - in both steps all requirement checks are marked green, after I inserted the DB data and Admin Login information, I get the message „WHOOPS something went wrong“. When I access the subdomain now, It shows directly the FreeScout Login screen. When use my Admin Login, it shows the „WHOOPS“ Message again :/

Do I have to preconfigure something more to use FreeScout on a hosted webspace? I didn’t alter the *env file. The Server is running PHP 7.4, could that be a problem?

Thank you very much for your help!

**Comment by freescout-helpdesk** [comment]
Not yet: https://github.com/freescout-helpdesk/freescout/issues/432

**Comment by TimoStramann** [comment]
Using PHP7.2 turned out to be the most stable in my use case. I'm running it now on a separate host since all other applications benefit from PHP7.4. Would be well appreciated if you could start upgrading to Laravel 7 maybe before the end of the year (or even next year). ;)
