### ISSUE TITLE
Order of conversations in searchresults are ordered from old to new

### ISSUE THREAD

**Issue by Dirk-Kokx** [freescout-helpdesk/freescout#608]
When you search conversations of a customer you get the conversations list from old to new. Over time you'll need to scroll more and more down to see the latest conversations you had with the customer.

In my believe it's better to change the order of searchresults to the most recent first.
This can easily be done by changing:

    $query_conversations->orderBy('conversations.last_reply_at');

on line 2203 or so of the ConversationsController to:

    $query_conversations->orderBy('conversations.last_reply_at', 'DESC'); 

Could you please consider to modify the core?

**Comment by freescout-helpdesk** [comment]
Fixed in the latest release.
