### ISSUE TITLE
View Attachments In Browser

### ISSUE THREAD

**Issue by amirkhan7** [freescout-helpdesk/freescout#609]
Hi, 

Previous to update 1.5.0, you were able to view attachments in the browser. After this change, this is no longer the case and it just downloads. is it possible to add this functionality back in as we have a lot of complaints from our users (though i understand the need for the update itself - security)

**Comment by amirkhan7** [comment]
or is this an issue with my  nginx web server? if so what changes do i need to make

**Comment by freescout-helpdesk** [comment]
It supposed to work like this. We will check what can be done.

**Comment by amirkhan7** [comment]
Many thanks.

**Comment by freescout-helpdesk** [comment]
The following file type will be viewed in the browser instead of downloading them:
```
'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'apng', 'bmp', 'gif', 'ico', 'cur', 'png', 'svg', 'tif', 'tiff', 'webp', 'pdf', 'txt'
```

**Comment by amirkhan7** [comment]
Thank you very much
