### ISSUE TITLE
How does freescout integrate to social media

### ISSUE THREAD

**Issue by ViscountCX** [freescout-helpdesk/freescout#610]
Hello, 

How does freescout integrate to social media like whatsapp, instagram, telegram etc.

Can DMs from these sites be used as tickets on freescout automatically?

Also, how is reporting handled on freescout?

**Comment by Clausinho** [comment]
Would be extremely cool. Telegram would be the easiest imho, as there is an API available.
It would be a lot of work tho from what I can tell

**Comment by amirkhan7** [comment]
https://freescout.net/module/telegram/

**Comment by Clausinho** [comment]
> https://freescout.net/module/telegram/

Thats not what I think this ticket anticipated.
This module notifies you via Telegram, if you get an E-Mail in FreeScout.
What I anticipated was that an issue gets arised in FreeScout itself, when a certain Telegram account or bot gets a message

**Comment by ViscountCX** [comment]
Thank you

**Comment by freescout-helpdesk** [comment]
Maybe this kinds of modules will appear in the future. No plans for now.

**Comment by freescout-helpdesk** [comment]
Re WhatsApp Integration: https://github.com/freescout-helpdesk/freescout/issues/1072

**Comment by freescout-helpdesk** [comment]
[WhatsApp Integration Module](https://freescout.net/module/whatsapp/) has been released.

**Comment by manuelbieh** [comment]
Sorry for using this old issue but I just found it on Google. Are there any plans to add an Instagram module anytime soon? I'd love to see the Instagram messages I get from my customers in FreeScout 🙂
