### ISSUE TITLE
Vertical scroll for large assignees list

### ISSUE THREAD

**Issue by dsXLII** [freescout-helpdesk/freescout#620]
I'm working with a team that's using Freescout as a shared mailbox, as opposed to a "traditional" help desk. We have about fifty active users.

When we receive a short email, the list of assignees is cut off by the bottom of the Web page. The first 30 or so users, alphabetically, are shown, but users whose names are later in the alphabet cannot have emails assigned to them. This varies with the length of the received email and the size of the browser window, of course, but many of our users simply cannot see the entire staff list, and those later in the alphabet cannot have emails assigned to them.

(If my meaning isn't clear I can put together a couple screenshots or a video, but it's easy enough to reproduce -- just add a lot of users to a mailbox, and eventually your list will be too large to fit.)

Any suggestions for a workaround, for assigning emails to the users at the bottom (alphabetically) of the user list? I can think of a few ways to work around it but none of them are trivial -- modifying Freescout to make the assignment drop-down an auto-complete widget, or using CSS to make the names in that list smaller, maybe?

I'm not sure if this is a help-wanted or a feature request, please tag appropriately.

**Comment by freescout-helpdesk** [comment]
Vertical scroll should be added to the list.

**Comment by stsimb** [comment]
Here is a screenshot showing a large assignee list, but unfortunatelly we can't scroll down ..

![no-scroll](https://user-images.githubusercontent.com/2001023/83944684-15fafc00-a80e-11ea-86df-13683a15da2d.png)
