### ISSUE TITLE
Artisan schedule run from script

### ISSUE THREAD

**Issue by bodnarlajostibor** [freescout-helpdesk/freescout#621]
Hello all! 

I'm trying to make a script named "artisan_schedule_runner.php". 

It would simple do:
`Route::get('/foo', function () {
    Artisan::call('schedule:run >> /dev/null 2>&1');
    //
});`

I can't run CLI commands from cron, just PHP scripts. 
(shared hosting server). 

Can you please help me out, how should I extend my code to get it work? 

Thank you!

**Comment by freescout-helpdesk** [comment]
Try to use https://www.php.net/manual/en/function.shell-exec.php

**Comment by bodnarlajostibor** [comment]
How do I know if it ran successful? 
(I don't think it will work, my host's support replayed that in the service there is no CLI PHP - and I assume that it requires that.)

**Comment by bodnarlajostibor** [comment]
I found a way: 

`$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$input = new Symfony\Component\Console\Input\ArrayInput(['command' => 'schedule:run']);
$output = new Symfony\Component\Console\Output\StreamOutput(fopen('output.log', 'a', false));
$status = $kernel->handle(
    $input,
    $output
);`

Seems it runs now, BUT I got in the output.log file:
`Running scheduled command: '' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1

In Process.php line 147:
The Process class relies on proc_open, which is not available on your PHP installation.
`

**Comment by bodnarlajostibor** [comment]
In Manage / System / Tools 'Fetch emails' all the previously sent email received, they are in the Unassigned folder of the Mailbox! 

But if I run the above script, no mailfetch! :(

**Comment by bodnarlajostibor** [comment]
I found the way to run all the jobs: 
after reading the output of the 'schedule:run' command, now I run all the jobs separately: 
- 'freescout:fetch-monitor'
- 'freescout:check-conv-viewers'
- 'freescout:fetch-emails'
- then 'queue:work' with the parameter '--queue' 'emails,default,5f...'

And it seems now all the jobs running perfectly. 
I hope it helps someone struggling with the same issue.
