### ISSUE TITLE
Impossible to update workflow module

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#625]
Hi,
if I click on "Update now"

this log appear:
"Workflows" module successfully updated!
```
Cache cleared successfully.
Nothing to migrate.
Public symlink already exists
Clearing cache...
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Created: storage/app/public/js/vars.js
```

But module is still as  1.0.10 version
![image](https://user-images.githubusercontent.com/5341996/83169220-fa5b6b80-a112-11ea-9f7c-bc1c515344ad.png)

Is it possible that the module updated correctly but the version number was not changed in the code?

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.12
