### ISSUE TITLE
Feature request : Workflow module date's

### ISSUE THREAD

**Issue by aventmarceau** [freescout-helpdesk/freescout#626]
Hello !
Could you add to workflow action to add xx days or substract from current date ?
There's only option to add fixed date. It's inconvenient to create many conditions with each xx days added to it or subtracted calculated by hand.

Conditions have 'is in the next (days)' and 'was in the last (days)' but actions don't.

Thank you !

**Comment by freescout-helpdesk** [comment]
Could you please send a screenshot of the fixed date.

**Comment by aventmarceau** [comment]
Hello !
I meant in actions there's option to set a date, for instance 2020-01-01 (I call this fixed date), but no option to calculate it each another day, for instance set custom field : «deadline date» to add 10 days from now (Freescout will calculate this each workflow run so when today's date is 2020-01-01, Freescout adds 10 days to it to be 2020-01-11, on 2020-01-02 it will set 2020-01-12 ).

Thank you !

**Comment by freescout-helpdesk** [comment]
Maybe will be implemented in the future.

**Comment by freescout-helpdesk** [comment]
Does not look like a very required feature.
