### ISSUE TITLE
"Forward" functionality in Workflows Module

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#630]
I am trying to use the “Forward” feature of the Workflows module to send a Custom Email to a 3rd Party (A email to SMS provider so I can receive a specially formatted SMS when a SLA is broken)

The 2 problems are:
1.	It has created a new ticket in FreeScout with the Fwd in it.  The Customer is the TO Email Address I used in the Forward
2.	The Email (and therefore the SMS I received) had the “—Please reply above this line –“ message in it

If this is the expected behavior for the “Forward” option in Workflows – can we please have a new option for “Send Custom Email” which does not make any more tickets, and the content of the email (including variables) is only what gets sent out by FreeScout?

Also, regarding Variables – is it possible for you to add “Conversation – Subject” to the options – so the Email (and my SMS) sent out can alert to the particular Ticket still unactioned?

**Comment by freescout-helpdesk** [comment]
No plans to change this functionality for now. Feel free to adjust the module by yourself.

**Comment by joris85** [comment]
I also would like the option to just send a message and use body or attachment in the forward.
Creating a ticket is in my multiple cases not wanted.
1. Send to sms service for urgent matters
2. Send invoices to my administration software

In both situation a more clear email would be more logic.

@freescout-helpdesk 
If i would update the workflow module with the right code, would you add that in the core workflow module?

**Comment by freescout-helpdesk** [comment]
> If i would update the workflow module with the right code, would you add that in the core workflow module?

Yes

**Comment by joris85** [comment]
@luketrip are you capable to program this?
I do not program but can ask my programmer for this feature.
Are you willing to pay something for this feature?
