### ISSUE TITLE
Forwarding mail - multiple addresses in To field

### ISSUE THREAD

**Issue by amirkhan7** [freescout-helpdesk/freescout#632]
Hi, 

Hope you guys are doing okay. 

One of our users noticed a little bug in freescout. Whereupon forwarding a ticket, if you enter multiple recipient addresses in the To field - it will only highlight the first one. 

Is it possible to change this so it imitates the behaviour when you create a new conversation? I.e. (you can select as many addresses as you want to in the "To" field).

Cc and bcc work as normal 

if you need anything else (screenshots) let me know

**Comment by radarsymphony** [comment]
Hi amirkhan7, 
This issue sounds like a similar to #825 
https://github.com/freescout-helpdesk/freescout/issues/825#issuecomment-716343476
Does that match what you are experiencing?

**Comment by freescout-helpdesk** [comment]
It has been fixed in the FreeScout 1.6.3
