### ISSUE TITLE
Prevent password reset for ldap authenticated users

### ISSUE THREAD

**Issue by stsimb** [freescout-helpdesk/freescout#633]
Hello,

Suppose we have a user that has been imported via ldap and "LDAP authentication" is turned on in freescout's settings.

This user can use the "Forgot my password" link in the login page and they will receive an email with a URL that will reset their *local* freescout password. Additionally, right after setting the new password they will be automagically logged in to use freescout, without the need to authenticate again.

If they logout and login again, they will not be able to login using their new password, because it's locally stored in mysql and not in LDAP.

Could we prevent ldap authenticated users from being ablt to use the "Forgot my password" link or we could we display a warning e.g. change password in your ldap/active directory or contact your IT dept ?

Thanks,

**Comment by freescout-helpdesk** [comment]
Will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in the LDAP v1.0.8

**Comment by nerdalertdk** [comment]
Hi when is 1.5.13 out ? 
can't upgrade LDAP before

**Comment by freescout-helpdesk** [comment]
In a few days.
