### ISSUE TITLE
Chain of autoreplies

### ISSUE THREAD

**Issue by imc67** [freescout-helpdesk/freescout#634]
Hi,

if we receive an email with a no-reply address, FreeScout is still sending an autoreply (it doesn't know it's a no-reply address).

However, the mailer-deamon (mailer-daemon@domain.tld) is sending an non-delivery email, and guess, this is seen as a new incoming email. FreeScout is sending an autoreply to the deamon, which results in ... you might guess.

Luckily after 3 loops it stops, but how to prevent this at all?

It seems there are protocols (https://en.wikipedia.org/wiki/Bounce_message) so somehow Freescout could be aware of a bounce and responds corresponding (like add it to the thread).

Kind regards,

Marcel.

**Comment by freescout-helpdesk** [comment]
Could you please provide headers of the mailer-daemon@domain.tld email

**Comment by imc67** [comment]
Hi,

this is the header:

Return-Path: <>
Delivered-To: info@domain.tld
Received: from my.domain.tld ([127.0.0.1])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits))
	by my.domain.tld with LMTP id UIneKWiI4F5iHwAATsuhOw
	for <info@domain.tld>; Wed, 10 Jun 2020 07:14:48 +0000
Received: (Haraka outbound); Wed, 10 Jun 2020 07:14:48 +0000
Received: (Haraka 97 invoked for bounce); Wed, 10 Jun 2020 07:14:48 +0000
Date: Wed, 10 Jun 2020 07:14:48 +0000
From: MAILER-DAEMON@my.domain.tld
To: <>
Subject: Message delivery failure notice
Message-Id: <640A80CE-94A1-459C-A4C2-1955C3DC7799@my.domain.tld>
Content-Type: multipart/report; report-type=delivery-status;
    boundary="boundary_AC22C29A-1DE3-4172-A9C4-6DD2CC76FA70"
References: <autoreply-10308-9efb1a59d7b58e69996cf0e32cb71098@domain.tld>
DKIM-Signature: ***

**Comment by freescout-helpdesk** [comment]
Non-delivery email is missing some special header, for example:
Auto-Submitted: auto-replied

**Comment by imc67** [comment]
@nebulade can you also have a look at this as this is the Cloudron email bounce?

**Comment by gramakri** [comment]
Yes, this is fixed in Haraka (the mail server Cloudron uses) - https://github.com/haraka/Haraka/pull/2782 . This will be part of next Cloudron release.

So, if this header is set will FreeScout be able to pick it up? If so, I guess we can close this issue.

**Comment by freescout-helpdesk** [comment]
> So, if this header is set will FreeScout be able to pick it up?

Yes.
