### ISSUE TITLE
Notification Alert on UI when fails

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#636]
Currently when FS failed to 'artisan' freescout:fetch-emails, 'artisan' queue:work it will log in application and will email to admins as per setting. 

However, all other users not aware of this and keep sending emails from FS assuming everything is normal. 

I suggest display a message globally when the two of the above command failed; 

<img width="1216" alt="Screenshot 2020-06-14 at 1 15 17 PM" src="https://user-images.githubusercontent.com/5198092/84585302-24b26600-ae41-11ea-9011-c823639c00c2.png">

This will be very useful to let all users know that the app is having a serious error and they must do something.

**Comment by freescout-helpdesk** [comment]
No plans to add it to the core. It is not users' job to monitor the system. It will cause too much confusion.
