### ISSUE TITLE
Update failed - 1.3 > 1.5

### ISSUE THREAD

**Issue by foxyfox** [freescout-helpdesk/freescout#638]
Hi,

I tried to do an update from Version 1.3.? to the current one in the backend. It said it failed, and afterwards the whole system broke and I just get "Whoops, looks like something went wrong.“. Tried to remove the .env and .installed file and redo the installation by manually overwriting the old files but it seems that does not help.

Do you have an idea what I can do?
I don't have access to a Terminal. Just using a webspace.

Best,
Foxy

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by foxyfox** [comment]
Thank you. The last part made it work 🙏
