### ISSUE TITLE
"@filter('before_dashboard', '')" was displayed as is after upgrade

### ISSUE THREAD

**Issue by dryabov** [freescout-helpdesk/freescout#64]
https://github.com/freescout-helpdesk/freescout/blob/28ee15ed4128751ad5b84ce4a268fa85dde976f3/resources/views/secure/dashboard.blade.php#L8

Fixed by `php artisan view:clear`, most likely it should be added to upgrade guide/script as well.

**Comment by freescout-helpdesk** [comment]
Thanks. `php artisan cache:clear` did not work?

**Comment by freescout-helpdesk** [comment]
Yes. `php artisan cache:clear` does not remove files in `/storage/framework/views`

Updated [documentation](https://github.com/freescout-helpdesk/freescout/wiki/Upgrading)
