### ISSUE TITLE
Saved Replies module activation issue.

### ISSUE THREAD

**Issue by keenminded** [freescout-helpdesk/freescout#640]
Hello!

Thank you for the hard work on making **FreeScout** into a fantastic product over the years. We have used it for quite some time and just tried to update it from a very old version (1.2.6). We had three modules working with the system: Satisfaction Ratings, Saved Replies and Tags. Upgrade went fine overall, with just a few hiccups which we resolved. Also two out of three modules updated alright. All licenses check out. However, Saved Replies, which we use extensively does not want to cooperate at all. 

Starting with this screen:

![image](https://user-images.githubusercontent.com/4564549/84819744-26656080-afde-11ea-8927-6837293c1832.png)

As soon as 'Activate' button is clicked, the front-end breaks completely and turns into this:

![image](https://user-images.githubusercontent.com/4564549/84820040-983daa00-afde-11ea-9bfd-59921d8f1f01.png)

Deactivating the module restores the front-end.

The artisan freescout:module-build command returns this:

![image](https://user-images.githubusercontent.com/4564549/84819972-7e03cc00-afde-11ea-8ee7-a36b9b17a168.png)

Could the missing view be the culprit?

We are looking to buy several other new modules and to support your efforts, but want to make sure that the module installation works as intended. Since this is a live support website, we do not want to experience outages.

Many thanks in advance and keep up the great work!

**Comment by freescout-helpdesk** [comment]
Check logs in Manage >> Logs >> App Logs

**Comment by keenminded** [comment]
Thank you! Forgot to look there. This ended up being an issue with server security. Had to enable fpassthru and symlink functions in PHP, then reinstalled the modules. Everything is working now. Buying additional modules now.
