### ISSUE TITLE
Ability for Users to create folders?

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#641]
With the paid plugin Custom Folders, it is currently limited to only administrators being able to create folders. Could some provisions be made to allow users to create custom folders as well? It would be devastating to allow the users of a single mailbox to have Admin rights to the entire system.

**Comment by freescout-helpdesk** [comment]
Yes. Corresponding option will be added in the future.

**Comment by joris85** [comment]
Know that i already have created a custom folder with a lot more functions.
My programmer will add it as a pull-request.
https://www.dropbox.com/s/yy2qggddpvkn3vk/Schermafdruk%202020-06-18%2014.11.45.png?dl=0

So you can say that a folder only shows active tickets.
Only ticket that are assigned to that user.
Hide folders for other users.

**Comment by freescout-helpdesk** [comment]
Added in the latest version of Custom Folders module.
