### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#643]
Hi guys,

I have at least a couple times a day this loading icon:
https://www.dropbox.com/s/ditwng3ppr8uu5a/Schermafdruk%202020-06-18%2014.42.49.png?dl=0

My console of my browser is empty

Refresh does solve it though.

Is this normal?

**Comment by fvdm** [comment]
@joris85 Is the console also empty when you enable 'preserve history' or something similar in the browser console?

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
