### ISSUE TITLE
Add Zapier module

### ISSUE THREAD

**Issue by GalacticLion7** [freescout-helpdesk/freescout#644]
Any possibility for a Zapier module?

**Comment by freescout-helpdesk** [comment]
Sure. First API must be implemented: https://github.com/freescout-helpdesk/freescout/issues/148

**Comment by GalacticLion7** [comment]
But how did you make a Slack module?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/780

**Comment by freescout-helpdesk** [comment]
FreeScout is available in Zapier now https://zapier.com/apps/freescout/integrations
For now with one Action allowing to create conversations.
