### ISSUE TITLE
[request] option to increase page count & option to search for keyword and delete on mass

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#646]
Hi Guys
I have 2 requests

1. option to increase the number of items on a page from 50 to 100, 200, 500 etc
This will allow option to mass delete faster

2. option to search for a keyword or email and then have the ability to SELECT ALL and delete these items. This option is similar to Google Mail functionality.

Hope this could be added.
M.

**Comment by colegatron** [comment]
The 2nd point is important since it applies for a lot of other actions; massive search result ticket re-assignation, tag addition, status change and manual workflow executions (which are also affected by #769)

**Comment by fulldecent** [comment]
I recommend against this feature. Having 500 conversations in view and performing a mass operation might cause some application instances to crash. Those will result in support tickets here.

As an alternative, somebody who wants this can implement it by changing this on their local installation:

https://github.com/freescout-helpdesk/freescout/blob/1.8.29/app/Conversation.php#L187

Perhaps after field reports of the performance and which hardware they are running, this might be better suited for adding as a feature. But for now recommending to close issue.

**Comment by raramuridesign** [comment]
@freescout-helpdesk @fulldecent 
Thanks for pointing out where this can be changed for increasing the conversation count.

I have set to these values 100, 200, 500 and the page loads without issues.
I have also performed a mass delete with 500 on a page and I see no performance issues.

Other users may need to test this, but for now I do not see any issue in adding a simple drop down with options to increase the count.

**Comment by fulldecent** [comment]
@raramuridesign Cool, thank you for the experiment. Next, it would be helpful to see about actions. Maybe deleting is easier. But when reassigning, if there is a workflow attached to that... this is something we can test too.

**Comment by raramuridesign** [comment]
@fulldecent our helpdesk has very few conversations to test this, as we keep it very low.
However I have workflows happening all the time - and there does not seem to be any delays or anything like this.

**Comment by freescout-helpdesk** [comment]
> 1. option to increase the number of items on a page from 50 to 100, 200, 500 etc
> This will allow option to mass delete faster

`Deleted` and `Spam` folders now have "Delete All" buttons. Closing this as out of scope.
