### ISSUE TITLE
"Hide from Assign list" in Bulk Actions

### ISSUE THREAD

**Issue by y-viel** [freescout-helpdesk/freescout#648]
Dear all,

While the Administrator can select "Hide from Assign list" for a mailbox, this does not happen in all views.

In the ticket view, tickets cannot be assigned to the admin user.

However, in the queue view, tickets can still be selected, and assigned to the admin user (eg username still visible).
This is independent of the specific queue being viewed (Unassigned, Mine, etc)

App version 1.5.8

Happy to provide any additional info required :) Thank you very much

**Comment by y-viel** [comment]
<img width="267" alt="Screenshot 2020-06-29 at 13 38 46" src="https://user-images.githubusercontent.com/34654079/86000530-f53d5500-ba0d-11ea-8c52-136199c27975.png">
<img width="718" alt="Screenshot 2020-06-29 at 13 37 29" src="https://user-images.githubusercontent.com/34654079/86000534-f5d5eb80-ba0d-11ea-8103-cb8afce6a853.png">

**Comment by y-viel** [comment]
Screenshots:
Top: the ticket view. I can only assign this to Anyone, or Me, the only existing agent.
Bottom: the queue view. Here I can assign this to Me, or to the admin user, who should be hidden from the Assign list as per configuration

**Comment by freescout-helpdesk** [comment]
Fixed by https://github.com/freescout-helpdesk/freescout/pull/650
