### ISSUE TITLE
Ability to rename subject lines?

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#649]
I'm not sure if this is technically possible if the thread scanning is based on the subject line or some internal X-ID. I have been asked by my users to see if there is a possibility of renaming a subject line.

Their case example was simple. They recieve multiple email form submissions with the same subject line "e.g. Form Submitted" and looking at a list of 30 different emails with the same subject has been proven to be confusing. I have recommended they use the Custom Notes feature, however only administrators are able to set that feature up and we naturally don't want to give them all Administrator access.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/43

**Comment by tiredofit** [comment]
My apologies - missed this requested twice. Will close and rely on original issue.
