### ISSUE TITLE
Any hooks I can tap into or any way to perform actions after ticket creation?

### ISSUE THREAD

**Issue by amityweb** [freescout-helpdesk/freescout#65]
I use Asana for tasks and we use Zapier to create new tasks when a ticket is created in Helpscout. 

That won’t be possible with Freescout.

As I’m a developer I can write my own script to create asana tasks but I need a way to call this when new tasks are created in freescout. 

Is there anyway to do this at all without modifying the core?

Thanks

**Comment by freescout-helpdesk** [comment]
Hi. No worries, everything is possible :)

Let's see how to implement it in a better way. We can do the following:
1) Create a Zapier app for FreeScout, which you can use to create tasks in Asana.
2) Create a module for FreeScout which would allow to create new tasks in Asana when a ticket is created in FreeScout.

Which way do you like?

**Comment by freescout-helpdesk** [comment]
Check [this](https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules-Development) out and UserCreatedConversation and CustomerCreatedConversation events.

**Comment by freescout-helpdesk** [comment]
https://zapier.com/apps/asana/integrations/freescout/477018/create-asana-tasks-from-freescout-conversations
