### ISSUE TITLE
[request] Option to SEND EMAIL on CLOSING a support request

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#651]
**REQUEST**
To allow an email to be formatted like the auto responder, but this emails deals with sending an email when the ticket has been closed. A standard reply to notify the customer that this has been done.

It would be great to have a checkbox close to the send button, which would trigger this email.

The email can be formatted under settings area
The screenshot shows a placement, but this can be moved according to UX.

**Screenshot**
![freescout_checkbox](https://user-images.githubusercontent.com/902376/86373031-3ab68800-bc83-11ea-9e98-4d4b4d619c8c.png)

Hope this can be added as a new addition
Thanks
M.

**Comment by Filoz** [comment]
Hi,

I think you can do this with workflows module.

It will send an email when status change in "closed"

**Comment by raramuridesign** [comment]
@Filoz @freescout-helpdesk 
I am not sure that adding the workflow module would be suitable for this. ie to solve one function which could be part of the core. but perhaps this could be considered by the dev team.

**Comment by freescout-helpdesk** [comment]
Feel free to create a feature request at https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/popular

**Comment by raramuridesign** [comment]
Thanks, this has been added.

**Comment by freescout-helpdesk** [comment]
Please use Workflows for now.
