### ISSUE TITLE
Workflow not triggered when mail is moved from another mailbox workflow

### ISSUE THREAD

**Issue by stsimb** [freescout-helpdesk/freescout#652]
Hello, thanks for a great tool!

We have purchased the workflow module, and have the following scenario:

Mailbox1 has an automatic workflow, which is triggered by a specific subject, and it's action is to move the mail to mailbox2.

Mailbox2 has an automatic workflow, which is triggered by the same specific subject, and it's action is to assign the new ticket to a specific user.

When we send an email to mailbox 1, the automatic workflow gets triggered and the email is moved to mailbox2.
We're now expecting the automatic workflow of mailbox2 to be triggered, and assign the new ticket to a specific user that we've configured, but unfortunately, this doesn't happen.

If we send the same email to mailbox2 directly, then the automatic workflow get's triggered, as expected, and it get's assigned to the specific user we've configured.

So, it looks like when the email get's moved into a mailbox from another workflow action, the workflow isn't triggered.

Is this something we can fix?

Thanks for your help!

**Comment by freescout-helpdesk** [comment]
Moving conversations between mailboxes is not equal to the new conversation.
It won't be changed.

**Comment by stsimb** [comment]
This is our expectation too.

When a new conversation is coming into mailbox2, then the automatic workflow in mailbox2 is triggered and it gets assigned to a particular user.

This works when we send the email directly to mailbox2 from a mail client, but it not the case when the email is moved into mailbox2 from another mailbox's workflow.

**Comment by freescout-helpdesk** [comment]
It should have been:

Moving conversations between mailboxes is **not** the same as a new conversation coming to the mailbox.

**Comment by fvdm** [comment]
@freescout-helpdesk Why is this not going to be supported? For the second mailbox it practically is a new incoming conversation. Each support team has their own requirements for processing mails.

**Comment by freescout-helpdesk** [comment]
Workflows Module v1.0.17

By default Workflows are not triggered when conversations are moved. To let the Workflow be triggered when the conversation is moved from another mailbox, you need to have at least one "Conversation moved from another mailbox" item among Conditions.

![helpdesk-ticket-moved-workflow](https://user-images.githubusercontent.com/40499291/102869977-702b7980-444d-11eb-99b6-0e19c5ef51e1.png)
