### ISSUE TITLE
Email Commands for first contact

### ISSUE THREAD

**Issue by webtyphoon** [freescout-helpdesk/freescout#653]
Hi there,

situation - customer sends support request from a form on my site.

Is it possible that I implement "Email Commands" on the form and when form is sent the commands will take action? 

Example - We build a dropdown for "tags" and when customer chooses a tag "billing" this tag will be visible on freescout back-end.

**Comment by luketrip** [comment]
I have achieved this using the Workflows Module and the Custom Tags Module.  In Workflows, you can assign a tag based on keywords in the Subject or Body of the new ticket.  If you look for keyword "Billing" - You could assign that tag and it can be seen in the Backend.

Combine this with the Custom Folders Module and you can easily separate these tagged tickets so they can be organised.  Works great!

The Email Commands module is handy but relies on you manually responding to the email with a Tag command (Ie. @tag billing) - Workflows will do this automatically.

**Comment by webtyphoon** [comment]
Wow, that sounds great and thanks for this comprehensive explanation.
