### ISSUE TITLE
Reply from the email/alias that conversation was originally created from

### ISSUE THREAD

**Issue by alekseyp** [freescout-helpdesk/freescout#656]
My use case, that I'm able to use with other helpdesks, but not with freescout -  is that I have one 'physical' mailbox with multiple aliases going to it. I would like to be able to reply using those aliases.

For example I have an email: user@demo1.com, that has an alias user@demo2.com.
When I create new mailbox in freescout - freescout will import them both into one mailbox (which is perfect), but then, when I reply - it will use main email configured for that mailbox as from address.

Since original email it was sent to is stored in thread table, maybe it's possible to add an option for specific mailbox to reply from multiple emails. For example if it matched the array of "alias" emails - then use alias as from email.
Most SMTP servers will allow authenticating with one address and using different from (if it's an account alias)

**Comment by alekseyp** [comment]
@freescout-helpdesk do you agree that this app functionality should follow how helpscout is managing mailboxes, alias and teams?

https://docs.helpscout.com/article/868-when-to-set-up-new-mailbox#shared

**Comment by nissisb** [comment]
Hello @alekseyp did you find solution ? i have the same issue and no solution from my side......

**Comment by alekseyp** [comment]
Nope, moved to another service

**Comment by nissisb** [comment]
ok fine but which service ? @alekseyp

**Comment by Moongazer** [comment]
What is the current functionality of Postbox > Edit > Aliases? We was hoping that we can use this aliases as FROM address when replying in a conversation. But it seems the sender (FROM) is ALWAYS the postbox mail-address 😢 

Reason: the postbox e.g. is support@domain.com, but for personalized marketing we also having "virtual support members" like joe@domain.com and carry@domain.com. Customers which responding to such marketing mails expect an answer from Joe or Carry, which just can be any of our support staff-member/agent.

It does not make sense to create a postbox for each single "virtual support member", that is usually where aliases are for.

**Comment by freescout-helpdesk** [comment]
We'll try to implement this.

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

![2023-04-17_17-31-02](https://user-images.githubusercontent.com/40499291/232518626-13a7a6e6-93a8-4760-b0ea-49753421e25f.png)

![2023-04-17_17-34-07](https://user-images.githubusercontent.com/40499291/232518647-d049c5fc-83a6-461d-a6bc-c66c8d9def61.png)

**Comment by afawaz2** [comment]
@freescout-helpdesk great feature, can you add the ability for changing the "from" to be one of the aliases when creating a new conversation?

**Comment by freescout-helpdesk** [comment]
> @freescout-helpdesk great feature, can you add the ability to change the "from" to be one of the aliases when creating a new conversation?

This is how it already works.

**Comment by afawaz2** [comment]
@freescout-helpdesk when I create a new conversation I cannot change the "from" only when replying to an existing conversation. See how my new conversation page looks like:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/13179697/233992700-c44177de-46ee-4e06-9738-1bcc0cc79664.png">

**Comment by freescout-helpdesk** [comment]
Selecting mailbox alias in a From field when creating a new conversation has been implemented in the master branch.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2988
