### ISSUE TITLE
Vertical Scroll for Large amounts of Mailboxes

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#657]
Similar to #620 - We are requesting to have vertical scrolling enabled for large mailbox lists. While not as show stopping as the original issue as we can access it from the main dashboard it would be useful to see this enabled for the mailbox list as well.

**Comment by freescout-helpdesk** [comment]
Could you please attach a screenshot.

**Comment by tiredofit** [comment]
Sure thing:
Note I also noticed a Sorting order isssue with the mailboxes at the same time that they are not following A-Z sequence.
![image](https://user-images.githubusercontent.com/23528985/86949607-c442db80-c103-11ea-8e1d-f354f6ed5441.png)

**Comment by freescout-helpdesk** [comment]
Already implemented.
