### ISSUE TITLE
production.ERROR: Class 'Eventy' not found

### ISSUE THREAD

**Issue by mihha** [freescout-helpdesk/freescout#66]
Hi guys!

Today I update my instalaltion to the latest version from GIT and now I can't access the FreeScout login anymore. 

I get the following in the browser:
"Whoops, looks like something went wrong."

In the /storage/logs/laravel.log file I can see the following
[laravel.log](https://github.com/freescout-helpdesk/freescout/files/2440807/laravel.log)

Any chance to shed some light on this issue?

Thank you in advance!

**Comment by mihha** [comment]
Hi,

thank you for pointing me in the right direction. I also needed to run DB migration using

`php artisan migrate`

It is working now

**Comment by freescout-helpdesk** [comment]
Welcome
