### ISSUE TITLE
Stars are not functioning as expected

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#662]
Problem: 
When I attempt to "Star" a message, it appears starred in the message list, however does not update in the left vertical menu of "starred". If I visit the Starred menu option it is blank. When I return to the message list it is now unstarred.

Freescout 1.5.8.

![image](https://user-images.githubusercontent.com/23528985/87104238-2be44e00-c20c-11ea-828f-4f043e9da625.png)
![image](https://user-images.githubusercontent.com/23528985/87104270-45859580-c20c-11ea-8488-41b6ab05730a.png)

**Comment by fvdm** [comment]
The star function doesn't do anything. When you click a star it only changes color, but on reloading the page the star is reset and the Starred list remains empty.

This is quiet annoying, it can be so useful.

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://demo.freescout.net ?

**Comment by fvdm** [comment]
@freescout-helpdesk Yes, exactly the same.

**Comment by fvdm** [comment]
@freescout-helpdesk I did some more testing and found a difference in user types. On our production and test installations, for the admins their stars are correctly remembered, but for other users (including mailbox managers) the stars clear on page reload. On the FS demo the stars are never remembered.

The JSON response always contains `success`.
