### ISSUE TITLE
Custom module lifecycle

### ISSUE THREAD

**Issue by tishma** [freescout-helpdesk/freescout#667]
Hi,

I'm into custom FreeScout module development, and I'd like to hear if there is any recommendation on how to update a module in production?

I was able to see that Installed Modules page offers updating the licensed modules, so I'm unsure (apart from replacing the newer module version code into `/Modules`) - what happens next? Should I perhaps be deactivating and re-activating the new version?

Thank you!

**Comment by freescout-helpdesk** [comment]
You can clear cache:
`php artisan freescout:clear-cache`
