### ISSUE TITLE
setting up freescout as a call center

### ISSUE THREAD

**Issue by nic5ghlh** [freescout-helpdesk/freescout#668]
It says I can set freescout up as a call center but I don't see a module to do this does anyone know what I must do?

**Comment by frommMoritz** [comment]
Hi,

please specify further. What's your definition of being a call center?
Freescout is a multi user mail system. It is not mainly a CRM, can't
handle incomming calls and spread them to agents and so on.

**Comment by nic5ghlh** [comment]
Okay thank you very much
I am looking to have a system that can handle many calls in/out bound

Sent from Mail for Windows 10
