### ISSUE TITLE
Table doesn't exist

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#669]
Saved replies module and Workflow modules are throwing errors after activating:

```
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'freescout.saved_replies' doesn't exist 
```

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'freescout.workflows' doesn't exist 
```

**Comment by freescout-helpdesk** [comment]
Apparently they were not properly installed. Check App Logs.

**Comment by vikasprogrammer** [comment]
Already checked no errors

**Comment by vikasprogrammer** [comment]
Can someone help me here? I sent a support email also, but no response.

**Comment by freescout-helpdesk** [comment]
If you are not a programmer you may need to find a developer who can check it for you.

**Comment by vikasprogrammer** [comment]
I paid for this module and installed it. Without any errors you expect me to solve this? You don't have any support for it? 

Sell this business to me, I will take care of it. :-)

**Comment by vikasprogrammer** [comment]
Sorry for being rude last time, I have found the fix. I am running the docker version of freescout which may be the reason why this didn't work. 

All I did was manually run "Migrate DB" from System screen.
