### ISSUE TITLE
FreeScout returns a 504 Gateway error when sending a message/Locks up in browser after sitting idle for too long

### ISSUE THREAD

**Issue by jacobwilder** [freescout-helpdesk/freescout#675]
Running the Docker container referenced in your documentation with a Traefik reverse proxy provisioning TLS via ACME. On sending a new message, I get a console error of `/js/builds/20930ab83e62f6d3f1e94be59e56cb7122301353272.js:192 GET https://fs.placeholder.com/mailbox/1/2 504` .

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
