### ISSUE TITLE
Workflow problem

### ISSUE THREAD

**Issue by vbandarra** [freescout-helpdesk/freescout#677]
Hello, I recently installed freescout and bought some modules, including the workflow. When I try to create a new workflow, an error page appears. When checking the error logs, it says that the file "/var/www/vhosts/clientes.bitwoci.pt/public_html/suporte2/public/js/flatpickr/l10n/pt-pt.js does not exist" is missing. Has it happened to anyone? How can I solve?
Thank you for your help.

**Comment by freescout-helpdesk** [comment]
It will be fixed. For now you can just switch to the English language.

**Comment by vbandarra** [comment]
Thanks. It's already working :)
