### ISSUE TITLE
Customers management (CRM)

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#678]
Does anybody need a module allowing to view and manage customers, export data, etc?

https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/290418

**Comment by amirkhan7** [comment]
Number 1 requested features by users. Would be greatly appreciated :)

**Comment by freescout-helpdesk** [comment]
Which features are needed?

- viewing and editing customers
- searching by mailbox and other parameters
- export customers data into CSV
- anything else?

**Comment by amirkhan7** [comment]
the ability to merge customers as well. in the event of duplicate contacts lets say for example. and possibly the ability to tag customers into different groups, but that isnt essential to our users.

**Comment by fvdm** [comment]
- cleanup customers who don't have conversations anymore

**Comment by statepm** [comment]
- Being able to add notes for customers
- Being able to add the "status" of a customer

**Comment by hendjam146** [comment]
Actions with 2 way sync via Zapier. I use Teamwave which is available there. Particularly so that there is a connector for Teamwave activity. Any moves adds or changes in Freescout can be seen here as well?

**Comment by Mte90** [comment]
So we have a table with customers but is not possible to add them by ui. We need to add them manually via db?

**Comment by freescout-helpdesk** [comment]
> We need to add them manually via db?
yes, for now.

**Comment by sinister3vil** [comment]
Hi, we're currently evaluating freescout and found the need for this.
Basically some hierarchy like below

- company: freescout
  - user (what is currently considered customer): bob@freescout.com
  - user: alex@freescout.com
- company: helpscout
  - user: nick@helpscout.com
- company: freelancerdev
  - user : freelance.agent@gmail.com
- dummy company : uncategorized
  - user : all other users

Company view should allow you to view users within it and add new users from a (searchable/filtered) drop down list
User view should show you current company and add user to a new one/change existing via a (searchable/filtered) drop down list.
Ability to get a list of conversations per user or company
This should also tie up in search and reporting features, like "total tickets from company helpscout".

Additionally, and a bit overboard, new users/customers could be added to a company based on their e-mail address, so tom@freescout.com, who sends in a ticket for the first time, would automatically be added to company freescout.
A customizable exception fields should be available for this, so adding gmail.com in there would stop any @gmail.com address be added there. Additionally each company should have an inclusion field of different domains, so freescout could have @freescout.com and @freescout.co.uk.

**Comment by diguinho2018** [comment]
Great suggestion.
+1 for this module.

**Comment by adamsewell** [comment]
Agreed

**Comment by freescout-helpdesk** [comment]
> * GDPR export of all customer data

Is it ok if only admin will be able to export customers' data? Or you need also support agents to be able to export data?

**Comment by fvdm** [comment]
@freescout-helpdesk Admin would be fine

**Comment by freescout-helpdesk** [comment]
Module has been released https://freescout.net/module/crm/
More features will be added with time.

**Comment by Mte90** [comment]
It is just missing an import feature, this will simplify the migration to FreeScout.

**Comment by diguinho2018** [comment]
Awesome module, would be great to have an option to delete user.
