### ISSUE TITLE
wrong recepient shown in cc field

### ISSUE THREAD

**Issue by stsimb** [freescout-helpdesk/freescout#679]
Hello,

We have a mailbox setup in our freescout installation, support@

A customer sends an email to support@ and it correctly gets a ticker number.

Then one of our agents uses their gmail client (not freescout) to forward the customer email to a couple of external emails, and adds CC: support@ to their email (but not the customer).

This second email, appears in freescout, with a CC: field that has the customer's email address, although this is not the case, as shown in the "Show original" of this very email in freescount, there is *no* cc: in the email, only to: recepients...

Screenshots attached ...

Is there any explanation for this ?

Thanks!

![view-in-freescout](https://user-images.githubusercontent.com/2001023/87938301-09b9be00-ca9f-11ea-9123-f902575d3ab9.jpg)

![show-original](https://user-images.githubusercontent.com/2001023/87938317-1211f900-ca9f-11ea-92c7-56ca4d9448ca.jpg)

**Comment by freescout-helpdesk** [comment]
Try to update FreeScout to the latest version.
