### ISSUE TITLE
Creating new user issue with SMTP

### ISSUE THREAD

**Issue by twd-ivan** [freescout-helpdesk/freescout#68]
With correct details entered on Mail Settings (Gmail, SSL) we are getting errors on sending new credentials for any user.
This means that any type of user message is not sent.

What could be the problem?

**Comment by twd-ivan** [comment]
![image](https://user-images.githubusercontent.com/44160048/46942639-10b3d100-d06e-11e8-8e5e-225c5f6f8f08.png)


and

![image](https://user-images.githubusercontent.com/44160048/46942714-33de8080-d06e-11e8-9659-7963fced9a68.png)

**Comment by freescout-helpdesk** [comment]
Can you provide your mail settings?

**Comment by twd-ivan** [comment]
![image](https://user-images.githubusercontent.com/44160048/46942958-c8e17980-d06e-11e8-86b8-cc4303946217.png)

Funny thing is happening when I try to save it to SSL, it gets reverted back to none. But I checked in the database, the value is "2" for this field, so I believe it is activated. Maybe it is not?

**Comment by freescout-helpdesk** [comment]
It looks like this is a bug. We will fix it.

Meanwhile just use "PHP's mail() function" for sending system emails. It is more than enough.

**Comment by twd-ivan** [comment]
Ok thanks!
