### ISSUE TITLE
Images don't show in notes

### ISSUE THREAD

**Issue by snazzypants** [freescout-helpdesk/freescout#680]
After pasting an image from the clipboard into a note and saving, the image doesn't show up. If you go to edit the note, the image shows up in the editor, so it appears to be saved.

**Comment by fvdm** [comment]
For me it does appear immediately after pasting in the editor and after saving. Do you have the latest version 1.5.9 installed?

**Comment by snazzypants** [comment]
Messing around with this a little more, I think this is actually due to #694 . I had been deleting one of the duplicate images, and I think the reason the image wasn't showing up was because of the bug in that other issue.
