### ISSUE TITLE
Cannot use since latest update

### ISSUE THREAD

**Issue by statepm** [freescout-helpdesk/freescout#681]
We updated the system to 1.5.10 this morning and now are not able to send messages or log phone tickets? We cannot even enter in the email address into the "To" field?

**Comment by freescout-helpdesk** [comment]
See Manage » Logs » App Logs

**Comment by statepm** [comment]
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'

**Comment by fvdm** [comment]
@statepm Is everything a green OK in Manage > System?

And make sure the settings in the `.env` file that start with `DB_` are correct.

**Comment by statepm** [comment]
We performed the new update this morning to 1.5.11 and it is working again. Thanks!
