### ISSUE TITLE
Report module - current/previous

### ISSUE THREAD

**Issue by innov2e** [freescout-helpdesk/freescout#687]
I just installed the report module. Anyone can explain me the meaning of current/previous numbers?
If I have in a day 203 current and 83 previous what does it means that in that day there was 203 NEW conversations and 83 conversations still active from previous days?

**Comment by freescout-helpdesk** [comment]
Date filter allows you to select a time period for fetching statistics. The "previous period" refers to the period before the selected one. For example if you select a week, the "previous period" will display data for the week before the selected one.
