### ISSUE TITLE
Workflow on different mailbox cannot have the same name

### ISSUE THREAD

**Issue by innov2e** [freescout-helpdesk/freescout#689]
I defined Workflow AAAA in the mail box 111, now I want use the same in another mailbox (i.e. mailbox 222). As workflows are mailbox dependent I am defining a new workflow into mailbox 222 named AAAA, but I get the message "The name has already been taken".

Is this a issue or it work as designed and I have to take care of names?

**Comment by freescout-helpdesk** [comment]
Will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.13
