### ISSUE TITLE
Tags Per Mailbox

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#690]
With the paid Tags plugins, we have a couple dozen shared mailboxes in use. A question has come up to see if the tags can be seperated per mailbox. For example marketing uses quite a bit different tags than operations, and users are finding it difficult to navigate through their list and tag properly.

**Comment by freescout-helpdesk** [comment]
No plans for now. Maybe in the future.

**Comment by mansi-shah-2248** [comment]
We also want this - we have already purchased the Tags Module.

Any plans or ETA for this?
