### ISSUE TITLE
Message ID management

### ISSUE THREAD

**Issue by dsukhin** [freescout-helpdesk/freescout#691]
I am reviewing FreeScout to replace our current ticketing system and so far very impressed and intend to deck things out with a couple of plugins. One of my main requirements is two way mail sync (messages get placed in sent and imported from sent).

I have a few observations/questions:

1. If a message doesn't have a message id, a RANDOM one is generated [here](https://github.com/freescout-helpdesk/freescout/blob/83f14010b1cdbf3d0a7ffe1a62dea5fabbf03d5b/app/Console/Commands/FetchEmails.php#L206). That means the message will be imported over and over again if it is checked multiple times. Why not generate the message id as the hash of the [RFC822](https://tools.ietf.org/html/rfc822) of the message body? Section 4 defines a standard order, such that the message will indeed hash to the same generated id each time. This is more correct. Wanted to flag the reasoning before submitting a PR.

2. Wondering how did item 1 came up... it turns out that while messages sent from the interface generate a message id in the database, the sent messages (which are placed in the sent folder) do NOT have a Message-ID in them, its never added [here](https://github.com/freescout-helpdesk/freescout/blob/badcdf78c1fc2c1f3c32f591495f4e96a9b373e7/app/Jobs/SendReplyToCustomer.php#L257). The one sent on the wire does have it though. This is a problem because the message in the sent folder does not have the very ID that the freescout system relies on for de-duplication and sent messages get imported again. Let me know if I am missing something here but ideally both the database and sent email in the folder and the one actually put out for delivery should contain the same message ID when sending a message from within the app. (cc: @nebulade since it appears you implemented this a few months back)

3. This next item is a mixed bag, but also relating to email import (particularly historical mails). The created date is set to the date of import instead of the date on the email. Now, I am aware this is somewhat moot when the system is running live (and can cause bad SLA escalations if a user mis-dates a mail), but its useful for importing historical conversations especially if importing inbox and sent for a two sided view of history. Any thoughts on adding the created date in the import script? Likewise, a message with a FROM being the mailbox name, should import as a reply made from the system. This is also an easy tweak.

4. I would like an option to leave message state intact... i.e. don't mark messages as seen when importing. This is a simple setting, but wanted to discuss adding this.

If all three things above seem ok, i can submit a PR, but would like to ensure that it will be merged before putting in the effort to polish it for general consumption.

**Comment by freescout-helpdesk** [comment]
1. Feel free to submit a PR.

2. You are right. Feel free to submit a PR.

3. It's ok to set conversation->created_at and thread->created_at to email date. Feel free to submit a PR. Just make sure to take email and Laravel timezones into account. The "message with a FROM being the mailbox name" part skip for now.

4. It is possible, but it will cause FreeScout to retrieve again and again all emails for the last 3 days every minute. They will not be imported, but it will create additional load on FreeScout and mail server.

**Comment by freescout-helpdesk** [comment]
> 1. If a message doesn't have a message id, a RANDOM one is generated here. That means the message will be imported over and over again if it is checked multiple times. Why not generate the message id as the hash of the RFC822 of the message body? Section 4 defines a standard order, such that the message will indeed hash to the same generated id each time. This is more correct. Wanted to flag the reasoning before submitting a PR.

Implemented in `master` branch.

**Comment by freescout-helpdesk** [comment]
> 3. This next item is a mixed bag, but also relating to email import (particularly historical mails). The created date is set to the date of import instead of the date on the email. Now, I am aware this is somewhat moot when the system is running live (and can cause bad SLA escalations if a user mis-dates a mail), but its useful for importing historical conversations especially if importing inbox and sent for a two sided view of history. Any thoughts on adding the created date in the import script? Likewise, a message with a FROM being the mailbox name, should import as a reply made from the system. This is also an easy tweak.

This will lead to timezone conversion issue and potential problems, as date in the email has it's own timezone: `Date: Wed, 28 Oct 2020 09:33:47 +0700`

Over 2 years nobody had issues with dates. So we will leave it as is.

**Comment by nissisb** [comment]
> 4\. It is possible, but it will cause FreeScout to retrieve again and again all emails for the last 3 days every minute. They will not be imported, but it will create additional load on FreeScout and mail server.

Not possible to have function to put unread automatically in email client after fetching and ignore all emails already sync one time into freescout ?

**Comment by fvdm** [comment]
@freescout-helpdesk Regarding point 3:

> Over 2 years nobody had issues with dates. So we will leave it as is.

We just had one. In an ongoing conversation one of the messages arrived in the IMAP spam folder. When I moved the message to the inbox the conversation already had more replies after that mail's timestamp. When FreeScout fetched the mail it was added to the conversation as a reply to the last message, instead of being inserted chronologically in the right position. This makes the conversation less easy to read as I had to insert a note about it.

**Comment by dsukhin** [comment]
I do have a branch that I use locally that fixes this. I can clean it up and re-issue a PR with the above fixes - probably just need to catch up to two years of changes. But in practice, I agree that date issues are more common than one might expect.
