### ISSUE TITLE
Duplicate image in the message body

### ISSUE THREAD

**Issue by fernandolcardoso** [freescout-helpdesk/freescout#694]
Hello everyone, everything good?

So, I'm having trouble putting images in the body of the message.

When I reply with a captured image from memory, the image is being duplicated in the message body.

![image](https://user-images.githubusercontent.com/16019127/89898017-5aac6600-dbb6-11ea-8183-ac3c496558a7.png)

**Comment by fernandolcardoso** [comment]
I noticed a problem receiving messages.

When the image is duplicated and I delete the first image, I get paid normally.

However, when I delete the second image, the image is not displayed.

**Comment by fernandolcardoso** [comment]
![image](https://user-images.githubusercontent.com/16019127/89899210-4d907680-dbb8-11ea-8e9c-ef0c9383c7f3.png)

![image](https://user-images.githubusercontent.com/16019127/89899311-76b10700-dbb8-11ea-88da-5d3ba285cec0.png)

**Comment by freescout-helpdesk** [comment]
Bug confirmed.

**Comment by psuter80** [comment]
this is solved by upgrading to the latest version of summernote. here is what i did on my test installation: 
```
cd /var/www/html/public/js/
mv summernote summernote.old
mkdir summernote
cd summernote 
wget wget https://github.com/summernote/summernote/releases/download/v0.8.18/summernote-0.8.18-dist.zip
unzip summernote-0.8.18-dist.zip
rm summernote-0.8.18-dist.zip
cd ..
chown -R www-data.www-data summernote 
```
problem solved ;)
