### ISSUE TITLE
Move to other Mailbox throws error

### ISSUE THREAD

**Issue by fhirter-vkb** [freescout-helpdesk/freescout#695]
When moving a conversation to a mailbox which the current user is not assigned to a error is shown "Whoops, looks like something went wrong.". But the Conversation is correctly moved.

**Comment by goosalex** [comment]
Problem is that the User does not get redirected after the Move action. If he hasn't got rights in the target mailbox, an error is thrown.

**Comment by freescout-helpdesk** [comment]
Fixed in the Workflows Module v1.0.16
