### ISSUE TITLE
Feature Request: Make it possible to select all mailboxes from move dropdown.

### ISSUE THREAD

**Issue by fhirter-vkb** [freescout-helpdesk/freescout#696]
It would be nice to be able to select all available mailboxes from the dropdown list when moving a conversation.

**Comment by freescout-helpdesk** [comment]
Admin can see all mailboxes, user should see only available to this user mailboxes.

**Comment by fhirter** [comment]
yes, this is how it currently works. but this doesn't fit our workflow. users should be able to easily move conversations to other departments without needing the rights to edit those mailboxes.

**Comment by freescout-helpdesk** [comment]
Feel free to implement as a custom module.
