### ISSUE TITLE
Workflow - only for new conversations/first message

### ISSUE THREAD

**Issue by lovetoast** [freescout-helpdesk/freescout#697]
Hi,

I don't think I can see this, but is it possible to only trigger a workflow when a conversation is created? If not, might this be a good feature? So to run a command for only new conversations. I know you can run it for when a conversation closes but it doesn't appear you can when a conversation is opened?

**Comment by freescout-helpdesk** [comment]
Maybe in the future.

**Comment by freescout-helpdesk** [comment]
"New or Reply" condition added in the Workflows Module 1.0.16
