### ISSUE TITLE
Restrict users to see only tickets assigned to themselves

### ISSUE THREAD

**Issue by Razva** [freescout-helpdesk/freescout#701]
We have a main contact@company.com. This address is monitored by two managers. Managers assign issues to other employees. The employees should **exclusively** see the tickets assigned to them by the managers, and nothing else. Also we should be able to add two employees on the same ticket. So a ticket should be seen by the managers and by all the assigned employees. The other employees should not be able to see tickets on which they are not assigned to.

Is there any way to achieve this with FreeScout? If yes, can you please let me know how? Thank you!

**Comment by freescout-helpdesk** [comment]
No for now.

**Comment by Razva** [comment]
> No for now.

Can we think about a sponsored feature?

**Comment by freescout-helpdesk** [comment]
Maybe someone can implement as a custom module.

**Comment by mahakala** [comment]
Any news here? Would like to support this too. Need exact the same feature.

**Comment by freescout-helpdesk** [comment]
Feel free to submit a feature request: https://freescout.net/request-feature/

**Comment by freescout-helpdesk** [comment]
Technically it's possible. But it will be impossible to show proper counters in mailbox folders for such users. Will it a big issue?

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

Now it's possible to specify users who can see only conversations assigned to themselves via `APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS` parameter in .env file. Specify a comma separated list of user IDs (which can be found in the user profile URL - /users/profile/7) and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache).

```
APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS=7,5,31
```

For such users only Mine folder shows actual number of conversations. This option does not affect admin users.

**Comment by mahakala** [comment]
Great news. Thanks a lot. The count is no problem.

**Comment by termy21** [comment]
I'm on v1.8.122 and have set the environment variable APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS to a single user ID, as fetched from their user profile URL (in this case, APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS=15) and cleared the cache (and also restarted the docker instance).

When that user looks at their Assigned folder they are still seeing tickets assigned to other users.  They are not only seeing their tickets.

I'm a bit confused on this enhancement request though, as "Mine" folder always did only show tickets assigned to that user anyways.  I'm looking at a way to restrict the viewing of tickets not assigned to this user in all folders (Assigned, Draft, Closed, Sent, All).

As a sanity check, I've also set the environment variable "Application Name" to ensure that the application is listening to environment variables defined in this location with my hosting provider.

![image](https://github.com/freescout-helpdesk/freescout/assets/3581126/debd6fe0-b650-4844-804e-dd3d31dd22dd)

**Comment by ilyakonovalenko** [comment]
@freescout-helpdesk can you please consider implementing an ability to also see only conversations with team assignee. So, to let users from APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS only see assigned themselves + teams they are in.

**Comment by freescout-helpdesk** [comment]
> @freescout-helpdesk can you please consider implementing an ability to also see only conversations with team assignee. So, to let users from APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS only see assigned themselves + teams they are in.

Fixed in the `master` branch and will be published in the next release.

**Comment by bash83** [comment]
Is there a way to make this the default behavior for new users? Basically automatically add their IDs here?

Also is there a plan to add a GUI for this configuration?

**Comment by freescout-help** [comment]
> Is there a way to make this the default behavior for new users? Basically automatically add their IDs here?
> 
> Also is there a plan to add a GUI for this configuration?

If anybody is will they can implement these features and submit a pull request.

**Comment by shelkesays** [comment]
> > Is there a way to make this the default behavior for new users? Basically automatically add their IDs here?
> > Also is there a plan to add a GUI for this configuration?
> 
> If anybody is will they can implement these features and submit a pull request.

We have a similar requirement. We are using FreeScout as inter department ticketing solution. Here we have multiple departments accessing the same Inbox. Each department has around 30 - 35 people. We also are using Teams module for Departments. So we would like to have way from UI where we can restrict the user from Seeing tickets only created by him/her and tickets assigned to him/her. In case of Managers it should all tickets within their department. I do not see any way to accomplish this within the current state of FreeScout. 

Hence, I am thinking of developing a module / updating the core to accommodate this. So will be interested in taking this task over and with the help of other collaborators guidance develop this. Let me know how can we proceed for this.

**Comment by leopittoni** [comment]
Is it possible to add this to the GUI? It could just be a checkbox in the role settings of the user...
- can see own tickets (assigned to himself)
- can see all tickets

**Comment by b4oshany** [comment]
> Is it possible to add this to the GUI? It could just be a checkbox in the role settings of the user...
> 
> * can see own tickets (assigned to himself)
> * can see all tickets

It would be good to add this in the UI.

**Comment by freescout-help** [comment]
The option has been moved to the user profile and visible in profiles of non-admin users:

<img width="533" height="97" alt="Image" src="https://github.com/user-attachments/assets/7fc777a6-ce3c-4441-bb75-83c609a72bd7" />
