### ISSUE TITLE
Issue: Previously there were some problems fetching emails. Fetching recovered and functioning now!

### ISSUE THREAD

**Issue by GlenSmale** [freescout-helpdesk/freescout#702]
So I recently started using Freescout, great software, thank you.

I keep getting this message to my email: "Previously there were some problems fetching emails. Fetching recovered and functioning now!"

Is there a reason I keep getting this as my smtp email settings work for send and receive and I have cronjob running.

**My specs are:**
App Version | 1.5.11    Check for updates
-- | --
Aug 19, 2020 08:26
Europe/Paris (GMT+0200)
HTTPS
Apache/2.4.29 (Ubuntu)
PHP 7.4.9

Kind regards,

Glen

**Comment by freescout-helpdesk** [comment]
Check Fetching logs in Manage >> Logs

**Comment by freescout-helpdesk** [comment]
Closing for now activity.
