### ISSUE TITLE
Cc/Bcc repaints reply to email will randomly CC other Cc/Bcc Users

### ISSUE THREAD

**Issue by CruisingwIT** [freescout-helpdesk/freescout#703]
Hi Freescout team,

I have noticed this issue in our production and after some testing, this issue is easily reproducible and consistent.
When an email is sent out from a shared inbox with Bcc users then the Bcc'd users replied to the email. The replied email from the Bcc'd recipients will randomly sent out a Cc to another random user from the Bcc list. Same problem the other way around or a mixture of Cc and Bcc. Random Cc or Bcc users on the list might receive emails. Interestingly, the number of users that will be picked from Bcc or Cc list randomly is not always limited to a single person only.

This behavior can be easily reproduced with the same steps mentioned above:
1. Sent out an email from a shared inbox with some Bcc or Cc recipients
2. Have the recipients to reply to the email coming from the shared inbox
3. Random users from the Bcc and Cc list will receive email(s) from other users

Screenshots for this behavior:
1. With Bcc, single random Cc user.
![image](https://user-images.githubusercontent.com/57601818/90686692-4fd09000-e29e-11ea-8ef4-f5ecf000877b.png)
2. With Cc, single or multiple Cc user
![image](https://user-images.githubusercontent.com/57601818/90689774-2c5c1400-e2a3-11ea-9063-a1f07cda7274.png)
3. Mixture of Cc and Bcc
![image](https://user-images.githubusercontent.com/57601818/90686998-bbb2f880-e29e-11ea-9273-ae6ee586776d.png)
4. Got emails from other users (Edison's inbox).
![image](https://user-images.githubusercontent.com/57601818/90687708-d5a10b00-e29f-11ea-8902-e6b6e76dfe03.png)

**Comment by tiredofit** [comment]
I have tested this commit and ran through 32 different scenarios. Problem seems to be resolved.
