### ISSUE TITLE
"Generic" email addresses always use the original FROM name in other mailboxes.

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#704]
Freescout 1.5.11 -

We have a situation that is developing after bringing lots of users into Freescout to utilize for their daily workflow. 
We have found that generic email addresses (noreply@ or others ie forms@) that are sent to mailboxes always utilize the First Name and Last Name first recieved in the application.

For example. If a message comes in via a form from noreply@example.com with the First, Last Name of "Department 1", and then another message comes into either the same Freescout Inbox or another Freescout Inbox from the same noreply@example.com yet their First, Last Name is "Department 2" from the form, it always appears as "Department 1".  This is especially problematic with Google, and we have also found a similar situation with Mailing Lists.

I would be willing to pay a bounty or other arrangements to have this resolved.

**Comment by fulldecent** [comment]
Recommending to close issue
