### ISSUE TITLE
Some Questions + error on shared hosting

### ISSUE THREAD

**Issue by R1CH101** [freescout-helpdesk/freescout#71]
Hi, 
Love Free Scout so far, just go a few questions, 
is there a plan to email the customer when the status changes? 

Also, the auto-reply only works once with every customer I get it when they have a conversation active or pending, however, once it is closed when they email again, should it send a new auto-reply message?

I kept getting an error on shared hosting about `queue:work` it would never run. there seems to be an error with `withoutOverlapping()`

I edit the `app/Console/Kernel.php` file and changed

```
$schedule->command('queue:work', Config('app.queue_work_params'))
            ->everyMinute()
            ->withoutOverlapping()
            ->sendOutputTo(storage_path().'/logs/queue-jobs.log');
```

to 
```
if (stripos((string) shell_exec('ps xf | grep \'[q]ueue:work\''), 'artisan queue:work') === false) 
        {
            
            $schedule->command('queue:work', Config('app.queue_work_params'))
            ->everyMinute()
            ->sendOutputTo(storage_path().'/logs/queue-jobs.log');
            
        }
```

And now it is working perfectly.

Thanks
Richard

**Comment by freescout-helpdesk** [comment]
Hi,

> is there a plan to email the customer when the status changes?

Yes

> Also, the auto-reply only works once with every customer I get it when they have a conversation active or pending, however, once it is closed when they email again, should it send a new auto-reply message?

Agreed. We will try to implement it too.

> I kept getting an error on shared hosting about queue:work it would never run

How did you receive an error? Via email alert or saw it on System page?

**Comment by R1CH101** [comment]
Hi,
> How did you receive an error? Via email alert or saw it on System page?

On the system page `queue:work` said something like `last successful run: ? Next run: ?` and background jobs were not being executed.

Thanks

**Comment by freescout-helpdesk** [comment]
Jobs mutexes are stored in cache (as file), so most likely you just needed to clear cache (`php artisan cache:clear`): https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

**Comment by R1CH101** [comment]
Hi, Thanks for the reply, I tested the command with original file and it works. just had to give it some time.

Thanks
Richard

**Comment by freescout-helpdesk** [comment]
> is there a plan to email the customer when the status changes?
@R1CH101 which statuses changes would you like to send to customer?
