### ISSUE TITLE
How do customers create their own conversation?

### ISSUE THREAD

**Issue by caselock** [freescout-helpdesk/freescout#713]
Is there any way for customers to create self-made conversations without having to create an account or login?
For example, they can create conversation from a form with email, content, title, ...

**Comment by giovotinh07111996** [comment]
The same issue. Please Support Freescount Team check it as soon as possible. 
Thanks

**Comment by freescout-helpdesk** [comment]
Customers send emails to the mailbox's email.

**Comment by giovotinh07111996** [comment]
I want to create the form like image 
![image](https://user-images.githubusercontent.com/41176876/91289131-1aef9c00-e7bc-11ea-9773-fd6c00b5a1bf.png)

**Comment by caselock** [comment]
> Customers send emails to the mailbox's email.

Where does the customer send it? Or they still have to create an account and log in like this https://prnt.sc/u63riv

**Comment by giovotinh07111996** [comment]
@freescout-helpdesk  hello any news?

**Comment by tiredofit** [comment]
I think what you are looking for is an End User Portal which would bring it more into a Support Desk type of application. It's been requested before. You can add your own requests here for features and vote for ones already proposed: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/popular

**Comment by caselock** [comment]
I see a lot of people voting and needing this feature, but it looks like a long wait

**Comment by freescout-helpdesk** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/popular

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/end-user-portal/
