### ISSUE TITLE
Do not receive email when creating conversation

### ISSUE THREAD

**Issue by caselock** [freescout-helpdesk/freescout#714]
I do not receive an email after creating the conversation or assigning a user, nothing :(
While I successfully configured the email, testing, and creating the user still sent the email successfully.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FAQ#users-do-not-receive-notification-emails

**Comment by caselock** [comment]
> https://github.com/freescout-helpdesk/freescout/wiki/FAQ#users-do-not-receive-notification-emails

@freescout-helpdesk I checked, everything ok, the only conversation does not send an email when create
the email sends test and invites working fine on Outgoing emails
![outgoing](https://user-images.githubusercontent.com/13690711/91399251-db7e8980-e867-11ea-8d3c-a533ce4dfc1a.png)

![notify](https://user-images.githubusercontent.com/13690711/91399396-1da7cb00-e868-11ea-8865-ca447cc802b9.png)
![job](https://user-images.githubusercontent.com/13690711/91399403-1f718e80-e868-11ea-9562-f8a67dcd0b70.png)

**Comment by freescout-helpdesk** [comment]
Do you have more than 1 users?

**Comment by caselock** [comment]
Yes, I currently test 3 users and none of them receive emails

**Comment by freescout-helpdesk** [comment]
Sorry. It looks like we can't help here.
