### ISSUE TITLE
Auto-population of Cc email address on reply

### ISSUE THREAD

**Issue by CruisingwIT** [freescout-helpdesk/freescout#715]
Hi Freescout Team, 

This is an extended issue of a previous one: https://github.com/freescout-helpdesk/freescout/issues/703
Our production found this new bug when the previously received email address is automatically populated to the Cc box on a new reply.

Here are what happened and the steps on how to replicate this (refer to screenshot):
1. Sharedinbox sent out an email with multiple Bcc recipients - four in this case.
2. Bcc recipient A replied and sharedinbox replied back.
3. Bcc recipient B replied; Sharedinbox receives the email from B. 
4. When sharedinbox replies to B you can see the recipient A email address is automatically populated into the reply Cc box.

Screenshot:
![image](https://user-images.githubusercontent.com/57601818/91462424-bb2cea00-e8bc-11ea-97e0-7477c5571726.png)

Thanks for looking into this.

**Comment by freescout-helpdesk** [comment]
This is by design.
