### ISSUE TITLE
Migrate/fetch mail older than 3 days?

### ISSUE THREAD

**Issue by JS3910** [freescout-helpdesk/freescout#717]
I'm changing over our makerspace volunteer mailboxes to use Freescout from just sharing logins to a webmail client and it looks like it will be really practical for us... However, we have thousands of email from several years back, and when I set it up everything is working fine, except it only fetches 3 days back.

In the app log for fetch-emails.log there is:

"[2020-08-30 10:09:02] Fetching UNREAD emails for the last 3 days."

So I'm sure this behavior is intended. But we obviously want all of our historical email migrated into the same place so we don't have to go back and forth to see older stuff. How can I force Freescout to fetch all mails from the IMAP server?

Thanks in advance
    /Johan

**Comment by JS3910** [comment]
Literally 20 seconds after I post this I notice console commands in one of my dozens of open tabs. For anyone else googling for this same question the answer is:

php artisan freescout:fetch-emails --days=<however many you want>

And in case anyone else stumbles figuring out why this doesn't cooperate inside dockerized freescout, you have to run this command from /www/html/.

**Comment by fvdm** [comment]
@JS3910 In Manage > System > Tools you can do manual imports for a custom amount of days.
