### ISSUE TITLE
Sending code snippets in tickets

### ISSUE THREAD

**Issue by pacifier007** [freescout-helpdesk/freescout#718]
Is there a way to share code like using pre tag to send out in tickets/emails? Like in Github we can share code like so:

```
code here
```

**Comment by freescout-helpdesk** [comment]
No

**Comment by rosinghal** [comment]
@freescout-helpdesk Just a feedback. I don't think this is correct way of handling things in any kind of project, there might be some limitation, but certainly would help if you reply accordingly rather than just a "No".

**Comment by fvdm** [comment]
Would be nice if FS had basic Markdown support that is auto converted to HTML.

**Comment by freescout-helpdesk** [comment]
It can be implemented as a module.

**Comment by Mte90** [comment]
It would be nice markdown support so we can use this and also other things.

**Comment by freescout-helpdesk** [comment]
[Extended Editor](https://freescout.net/module/extended-editor/) module released.
