### ISSUE TITLE
Modules not activating

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#719]
I purchased a couple of modules today and tried to install it via the Module installer, I get this error

`Error occured downloading the module. Please download module manually and extract into /www/html/Modules`

When I checked this folder, the module folder was create but somehow its showing this error. I also tried to manually download and unzip the folder the module doesn't appear in the installed module list. 

Can someone help me.

**Comment by freescout-helpdesk** [comment]
1) Check errors in Manage >> Logs >> App Logs.

2) Make sure you have PHP `curl` extension enabled.

3) Make sure that /Modules folder is writable by web server user.

Try to install the module again.

**Comment by freescout-helpdesk** [comment]
Have you managed to solve the issue?
