### ISSUE TITLE
Forwarding Emails

### ISSUE THREAD

**Issue by sicXnull** [freescout-helpdesk/freescout#72]
ETA on completion for this one? This would be a perfect solution if I could forward emails.

**Comment by freescout-helpdesk** [comment]
Hi. Task has been added to the todo list: https://github.com/freescout-helpdesk/freescout/projects/1

**Comment by NdT3Development** [comment]
Hi,

I have updated to version 1.2.2 from (I think) version 1.1.8 and while there is now an option to forward, it doesn't work as it should.

![Screenshot](https://i.imgur.com/hTa0PUK.png)

As shown in screenshot, there is nowhere to enter the email that the conversation should be forwarded to.

How can I fix this as we need forwarding on our company system?

**Comment by NdT3Development** [comment]
Hi again,

Forwarding does work however attachments in the conversation are not forwarded. This is a problem as our business deals with many invoices every day and need to forward some of these invoices.
