### ISSUE TITLE
Open Tracking switch is bugged?

### ISSUE THREAD

**Issue by code4lambo** [freescout-helpdesk/freescout#720]
Hello,

When i receive the messages from Freescout with **disabled** Open Tracking, i still see this addition at the end of every email:

{#FS:cmVwbHktNi0xNjc5MDkxYzVhODgwZmFmNmZiNWU2MDg3ZWIxYjJkY0BtYWlsLWh1Yi5pbw==#}

![48WQQcl 1](https://user-images.githubusercontent.com/70039863/92000331-14c26800-ed46-11ea-87e5-dd535325fcd5.png)

**Comment by freescout-helpdesk** [comment]
This bit of information is related to threads chaining in FreeScout, not to Open Tracking.

**Comment by fvdm** [comment]
@code4lambo The open tracking done with an image url. When you disable it the tracking image tag is not included in the email HTML.
