### ISSUE TITLE
Size of attached files

### ISSUE THREAD

**Issue by ptbranco** [freescout-helpdesk/freescout#721]
I think that the actual filesize limit for each file attached to a message is set to 1Mb. But I need to send larger files.
How can I set other limit?

Thanks for the fantastic tool that you are developing.
Regards.

**Comment by freescout-helpdesk** [comment]
Attachment size is limited by your server configuration.

**Comment by ptbranco** [comment]
Thanks. Solved.

I add this line to ngix.conf: 
`http {`
[...]
	`client_max_body_size 25m;`
[...]
`}`

**Comment by tillmon** [comment]
It would be helpful if the value of `client_max_body_size` is shown under "System State".

**Comment by RienNeVaPlus** [comment]
Setting `client_max_body_size` didn't fully solve this for me.
I had to modify `/etc/php/*.*/fpm/php.ini` as well:

    upload_max_filesize = 10M

Don't forget to:

    /etc/init.d/php7.2-fpm reload
