### ISSUE TITLE
Customer Data Enrichment

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#724]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/240337

We can create a module which would enrich customers data in the background (avatar, contact details from social networks, etc) using https://www.voilanorbert.com/enrich/ enrichment service (this service charges 50 USD for 1000 enrichments per month) or https://en.dropcontact.io/pricing (23 USD for 1000 enrichments per month).

Does anybody need such module?

**Comment by nerdalertdk** [comment]
I just want the ability to set custom fields on customers :)

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/customer-data-enrichment/

**Comment by victoras** [comment]
Is it anyway to check the data for current customers?

**Comment by freescout-helpdesk** [comment]
Not yet. Will need to be implemented.
