### ISSUE TITLE
Email commands on first email

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#727]
It would be great for me that colleges could assign a new e-mail directly to a certain person.
So not a reaction on a notification.

Is that something that could be implemented in the module email commands?

**Comment by freescout-helpdesk** [comment]
It is not quite clear what you need to do.

**Comment by tiredofit** [comment]
It sounds as if you need the Workflow Module if you want auto assignment to occur based on a series of conditions like a Subject Line matching a string.

**Comment by joris85** [comment]
Yes this works to, though i need to create workflows matching email commands.
So i fixed it now with workflows.
