### ISSUE TITLE
Mentions in notes

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#728]
Sometimes i want to keep track of a ticket myself but notify my college about something.
Assigning to him means i need to wait until he assign to me, it is gone in my own tickets.
So the option to notify my college would be handy.

If i could imagine add something like this:

@college Peter johnson
And he will get a notification (email, notification) that there is added a note.
So in notifications another option to receive email when their name is added with @ option.

Or is there another way how freescout can handle this?

**Comment by freescout-helpdesk** [comment]
It can be implemented using @mentions in notes: https://docs.helpscout.com/article/694-using-mentions-in-notes

**Comment by fvdm** [comment]
Isn't the Followers module meant for this?

**Comment by joris85** [comment]
Yes implemented like in helpscout would be great!
I bought the followers module but is not so slick as Helpscout Mentions.
But i can imagine it does the same :-)

**Comment by freescout-helpdesk** [comment]
It looks like this feature is not super needed. Feel free to add here: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#ideas/popular

**Comment by freescout-helpdesk** [comment]
Implemented as a module: https://freescout.net/module/mentions/
