### ISSUE TITLE
FreeScout Cloud Hosting

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#729]
Does anybody need a FreeScout Cloud Hosting for 7 USD / mo with unlimited mailboxes/users?

**Comment by Mte90** [comment]
What modules will be included in the package?

**Comment by freescout-helpdesk** [comment]
No modules. Clean installation.

**Comment by passatgt** [comment]
It would be nice at a higher price(like $10-20), but all extra modules included by default.
