### ISSUE TITLE
Can't fetch mails from Gmail through POP or IMAP

### ISSUE THREAD

**Issue by C0rn3j** [freescout-helpdesk/freescout#73]
Trying to setup Freescout with a Gmail account.

Less secure apps are enabled (It seems that this setting is required for sending. Sending works.) - https://myaccount.google.com/u/4/lesssecureapps

IMAP and POP are both turned on in Gmail settings - https://mail.google.com/mail/u/4/#settings/fwdandpop

Am setting it up according to google docs - https://support.google.com/mail/answer/7126229

It does not matter if I try to use SSL vs TLS Encryption option. 

![image](https://user-images.githubusercontent.com/1641362/47434134-32196900-d7a2-11e8-93f0-ad7d69b04cd7.png)

```
[2018-10-24 15:39:12] Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/tls}. [CLOSED] IMAP connection broken (server response); File: /var/www/html/vendor/webklex/laravel-imap/src/IMAP/Client.php (230)
```

**Comment by freescout-helpdesk** [comment]
Encryption must be SSL. Your "Fetch From" and "Username" must be at Gmail: `your-email@gmail.com`

https://github.com/freescout-helpdesk/freescout/wiki/Fetching-Emails

**Comment by sicXnull** [comment]
Make sure to click "Save Settings" after making each change as well. I was running into a similar issue and thought it would test it if I changed it without clicking save, it will not.

**Comment by C0rn3j** [comment]
@sicXnull Turns out that was my problem.

![image](https://user-images.githubusercontent.com/1641362/47435592-37c47e00-d7a5-11e8-94a8-6f6f202e7899.png)


@freescout-helpdesk it is a gmail address, but it's a company.com address which is why I blurred it out.

Should I open a new issue about the UI or just rename this one?

**Comment by freescout-helpdesk** [comment]
Thanks. No need. We will add a notice.
