### ISSUE TITLE
Customizable reply separator

### ISSUE THREAD

**Issue by gino0631** [freescout-helpdesk/freescout#730]
Even if the option "Email Header" is deactivated in mailbox settings, the default text "-- Please reply above this line --" is added in the plain text version of the message (but not in HTML).
The expected behaviour would be consistently not to add the header if it is not configured to do so.

**Comment by freescout-helpdesk** [comment]
In the plain text version it can't be removed as it works as a "separator" when separating replies.

**Comment by gino0631** [comment]
Viewed as plain text, the messages look like:
```
-- Please reply above this line --
-----------------------------------------------------------
 
(message text)

--
(signature)
-----------------------------------------------------------
## (name), on Sep 12 @ 04:05 (Europe/Bucharest): 
(message text)

--
(signature)
-----------------------------------------------------------
## (name), on Sep 12 @ 03:48 (Europe/Bucharest): 
```
So the text is above the first message, and the messages are separated with `-----`. Is that text really necessary?

**Comment by freescout-helpdesk** [comment]
Using "-----------------------------------------------------------" is not reliable as user or customer message may contain such sequence.

**Comment by gino0631** [comment]
OK, just to understand the idea - you need a reliable separator between a reply and a conversation (and not between messages in the conversation itself), because you use it to find where the reply ends, and discard everything what is below (and you don't do a comparison with what's already in the database to detect older messages in the conversation) - do I understand it right?

**Comment by freescout-helpdesk** [comment]
Yes.

**Comment by gino0631** [comment]
OK, now I see. However, as it is important for the user to understand that text, it would be good to have an option to customize it - to write in two languages, or to change into something seemingly unique ("✄---✄---✄---"), for example, if that's possible.

**Comment by freescout-helpdesk** [comment]
On "Edit Mailbox" page the "Email Header" option should be made editable. Below the input "Add this text to the beginning of each email reply sent to customers" check box should be added.

**Comment by gino0631** [comment]
Just to clarify - "Email Header" option is already editable, and it is possible to add a custom header to email messages, but that would affect HTML messages as well.
The idea is to customize the separator used in plain text messages only, where it is required for technical reasons (to separate a reply from previous messages), without adding anything unnecessary to HTML messages.

**Comment by freescout-helpdesk** [comment]
If "Add this text to the beginning of each email reply sent to customers" checkbox is checked separator is added to HTML and plaintext emails. If this checkbox is unchecked is added to plaintext emails only.

**Comment by gino0631** [comment]
OK, I did the following:
- Checked the checkbox, changed the header text, saved the changes, and sent a reply. The result: I can see the customized header in HTML, but in plain text there is the same "-- Please reply above this line --".
- Unchecked the checkbox, saved the changes. The header text changed back to the original "-- Please reply above this line --".

So the current option works for HTML messages only.

**Comment by toxpal** [comment]
I have exactly the same problem - even after I edit Email Header field, all plain text emails still have default text "-- Please reply above this line --". No problems for HTML emails - freescout uses my custom text for HTML.

Also, my installation has no "Add this text to the beginning of each email reply sent to customers" box - https://i.postimg.cc/0Qkwd2GV/mail.png

**Comment by toxpal** [comment]
I see "help wanted" label was added by dev. @freescout-helpdesk I don't know what type of help you need, but if there's anything else I can do, let me know.

**Comment by toxpal** [comment]
I believe I found what might cause this issue. File /app/Misc/Mail.php contains this text hardcoded as constant:

`const REPLY_SEPARATOR_TEXT = '-- Please reply above this line --';`

Should it really be here?
