### ISSUE TITLE
Customization of "(optional)" placeholder in Satisfaction Ratings

### ISSUE THREAD

**Issue by gino0631** [freescout-helpdesk/freescout#732]
Would it be possible to add an option in "Translate" tab of the "Satisfaction Ratings" plugin to customize the "(optional)" placeholder shown in the comments box?

**Comment by freescout-helpdesk** [comment]
Yes. In the future.

**Comment by gino0631** [comment]
Thanks!
Would you be interested in a patch? Just tried to implement that myself.

**Comment by freescout-helpdesk** [comment]
Sure. You can send the whole updated module to support@freescout.net

**Comment by gino0631** [comment]
Tried to send, but mail server blocked the attachment for some reason, so I'm attaching the patches here, as it's just 3 files. I hope you find this useful. Thanks!
[SatRatings.zip](https://github.com/freescout-helpdesk/freescout/files/5218627/SatRatings.zip)

**Comment by freescout-helpdesk** [comment]
Thanks. We've got it.

**Comment by freescout-helpdesk** [comment]
Added in Satisfaction Rating 1.0.4
