### ISSUE TITLE
Discarding of a message to be fowarded removes conversation attachments

### ISSUE THREAD

**Issue by gino0631** [freescout-helpdesk/freescout#733]
Steps to reproduce:
1. In a conversation that has attachments click Forward.
2. Press Discard.
3. Refresh the page - the customer-submitted attachments are gone.

The expected outcome is that "Discard" affects only the draft - the original conversation should be left intact, including the attachments.

FreeScout is 1.5.14.

**Comment by freescout-helpdesk** [comment]
Fixed.
