### ISSUE TITLE
CC'd/multi recipient conversation only showes up in one inbox

### ISSUE THREAD

**Issue by twentyonepenguins** [freescout-helpdesk/freescout#734]
Hey!
I have a FreeScout install with a couple of different mailboxes. The intention is for these to be accessed by a couple of different people from different teams.

I have noticed, that when I send an email with both of these inboxes as a recipient, it only shows up in one of them, and not the other. 
My guess would be that this has something to do with FreeScout only creating one database entry per email for the entire install, and not per inbox, or is there something else at play?
And is there any solution?

Thanks!

**Comment by freescout-helpdesk** [comment]
There is such an issue already created. Try to search among open issues.

**Comment by marado** [comment]
Looks like it is https://github.com/freescout-helpdesk/freescout/issues/480 .

**Comment by freescout-helpdesk** [comment]
Fixed in `master` branch. Soon will be released.
