### ISSUE TITLE
Need extra checking in subject message [solution]

### ISSUE THREAD

**Issue by vitaliany** [freescout-helpdesk/freescout#735]
Hello. Sometimes we got messages from clients with illegible subjects. It depends by mail program a client. Probably it is actually for cyrillic langs.
![kS2LCz](https://user-images.githubusercontent.com/2734784/93057872-40fbb400-f677-11ea-9b0b-e7b8de291094.png)

**[Solution]**
In app\Console\Commands\FetchEmails.php go to line 417
replace
```php
$subject = $message->getSubject();
```
by follow code:
```php
// Extra checking subject
$str = $message->getSubject();
if (preg_match("/(=\?)(windows-1251|UTF-8|koir-8)(\?B\?)(.*)(\?=)/i",$str,$matches)) {
$decoded = iconv_mime_decode($matches[0], 0, "UTF-8");
$bodytag = str_replace($matches[0], $decoded, $str);
$str = $bodytag;
}
$subject = $str;
```

**Comment by freescout-helpdesk** [comment]
Could you please send one such email to support@freescout.net

**Comment by freescout-helpdesk** [comment]
Merged
