### ISSUE TITLE
Customer photos and countries?

### ISSUE THREAD

**Issue by tcupra** [freescout-helpdesk/freescout#736]
Hi,

I've updated to 1.5.14. I'm looking for how to implement the new features:

- Added function to save customer photo.
- Show address and country in customer profile if any.

I looked in 'Edit profile' for a customer, and I can't see any options for photos or countries, etc.

Thanks! 

![image](https://user-images.githubusercontent.com/71258347/93068450-d1f67d80-f6bf-11ea-84d4-510a48adb7f7.png)

**Comment by freescout-helpdesk** [comment]
For now only via the code, not in the interface.
