### ISSUE TITLE
Emails not succesfully delivered 

### ISSUE THREAD

**Issue by Natee01** [freescout-helpdesk/freescout#739]
I am experiencing a problem with my emails being sent from my mailboxes. When doing email test and user invites emails, the emails are successfully delivered but when sending actual emails through ticketing there is a notification that emails are sent but they are not delivered, not even reach the email receiver.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Sending-Issues

**Comment by Natee01** [comment]
Thanks I am well assisted.
