### ISSUE TITLE
Forwarding with workflows removes mail contents

### ISSUE THREAD

**Issue by lekkerduidelijk** [freescout-helpdesk/freescout#743]
Hi,

When using a manual workflow to forward emails into our accounting software the attachment and message body is stripped. I think maybe I misunderstand how this works. 😃 

The outgoing email only contains:
> Workflow forwarded a conversation # 123 

How can we get both attachments and message body included in the forwarded email? 
Perhaps this can only be done with the new webhooks?

Cheers,
Rutger

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of the Workflows Module?

**Comment by lekkerduidelijk** [comment]
Yes, running `1.0.14` now.

Funny thing is using the regular 'Forward' option works without issues. Just forwarding with a workflow doesn't.

**Comment by freescout-helpdesk** [comment]
Could you please attach screenshots of the Conditions and Actions tabs.

**Comment by lekkerduidelijk** [comment]
My workflow is set to Type Manual. So I have no conditions tab.

<img width="465" alt="Schermafbeelding 2020-09-18 om 15 46 04" src="https://user-images.githubusercontent.com/357924/93604786-26eb0a00-f9c6-11ea-9032-ab22890d68e9.png">

I've set the notifications to 'Not include previous messages' and 'Include the last message'.

<img width="552" alt="Schermafbeelding 2020-09-18 om 15 47 25" src="https://user-images.githubusercontent.com/357924/93604892-5437b800-f9c6-11ea-90ef-07b506c0e82a.png">

Should I include the last message on Emails to Customers?

**Comment by tiredofit** [comment]
I am seeing a similar issue with forwarding multiple recipients, yet not related to the Workflow module, so I apologize if I'm steering this on a different path. When forwarding the message to someone, only the most recent response (either customer or user) is sent. I'm wondering if there could be an option similar to the above two history options to be added strictly for "forwarding" that allows the 3 options (full, last, do not include).

**Comment by lekkerduidelijk** [comment]
Setting the 'Emails to customers' option to 'Include last message' doesn't change anything for the forwarded email with a workflow.

I do see a reference text appended to the mail body where the original message should show. 
For example: `{#FS:bm90a....}`. Maybe that's related?

Will follow progress on #744.

**Comment by lekkerduidelijk** [comment]
Thanks for the fix in release 1.6.0. Great work. The mail body is properly forwarded now.

Unfortunately the attachments aren't. Perhaps this is yet to be added?

**Comment by freescout-helpdesk** [comment]
Yes. Will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module 1.0.15
