### ISSUE TITLE
Conversation History option when forwarding

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#744]
_Originally posted by @tiredofit in https://github.com/freescout-helpdesk/freescout/issues/743#issuecomment-694898395_

I am seeing a similar issue with forwarding multiple recipients, yet not related to the Workflow module, so I apologize if I'm steering this on a different path. When forwarding the message to someone, only the most recent response (either customer or user) is sent. I'm wondering if there could be an option similar to the above two history options to be added strictly for "forwarding" that allows the 3 options (full, last, do not include). This sounds very similar to what OP has posted.

**Comment by freescout-helpdesk** [comment]
Todo:

1) Remove Settings menu item from the conversation toolbar.

2) Add `Conversation History` item to the Send button dropdown menu after "Change default redirect".

3) Store Conversation History option in the `thread` table, remove `email_history` column from `conversations` table.

**Comment by tiredofit** [comment]
Works wonderfully.
