### ISSUE TITLE
Satisfactory module not working

### ISSUE THREAD

**Issue by Natee01** [freescout-helpdesk/freescout#746]
Hi, I kindly need your help with satisfactory module, its currently not functional.

**Comment by Natee01** [comment]
I followed all your troubleshooting process, the issue is not resolved. Please kindly assist urgently.
![screenshot-github com-2020 09 20-04_54_08](https://user-images.githubusercontent.com/71408944/93693237-813ab680-fafd-11ea-8b83-17b924a2298e.png)

**Comment by freescout-helpdesk** [comment]
> not functional

What do it mean?
