### ISSUE TITLE
From header set by FreeScout triggering default rspamd rule

### ISSUE THREAD

**Issue by jarland** [freescout-helpdesk/freescout#747]
While not explicitly an issue with FreeScout, it should be noteworthy to the project that the From header set by FreeScout is triggering a default rule in rspamd. Since the rspamd rule in question is actually a fairly good rule, changing the behavior of FreeScout would be preferable to having rspamd users manually disable it.

The test in question is this: SPOOF_DISPLAY_NAME

The reason is because the From headers look like this:

`From: "{Client Email} {Client Name} via {Ticket System Name}" <{Ticket System SMTP Sender}>`

This is causing my ticket notifications to bounce because I use rspamd to filter outbound email. I imagine more will report the same over time due to rspamd being used to filter their inbound email.

**Comment by jarland** [comment]
The code in question is here:
`/app/Jobs/SendNotificationToUsers.php`

I think it's line 106 (or 112?):

`$from_name = $from_name.' '.__('via').' '.$mailbox->name;`

For example, I believe it would be fixed by changing that to:

`$from_name = $mailbox->name;`

I could submit a PR but I'd rather this be weighed against the intention that led to it being coded that way as perhaps there's a balance between the two that is a bit less than just cutting it out.

**Comment by freescout-helpdesk** [comment]
This can be implemented by adding .env option.

**Comment by fvdm** [comment]
If there is no From name it should be the username part of the email address. Setting the From name to Mailbox name is very confusing in the conversations list.

**Comment by freescout-helpdesk** [comment]
> From: "{Client Email} {Client Name} via {Ticket System Name}" <{Ticket System SMTP Sender}>

We will keep it as is.
