### ISSUE TITLE
Installation fails even though key has been set

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#75]
The installer runs until the end. But then all I get is: Something went wrong.
Debug output is:

 ErrorException (E_ERROR)
Undefined variable: dbMessage (View: /var/www/freescout.xxxxxxxxxxxxx/html/resources/views/vendor/installer/finished.blade.php)

**Comment by nickbe** [comment]
Will try this evening :) Thanks

**Comment by nickbe** [comment]
Ok, the installer worked now :) Thanks for that.
But the css is not loaded at all: 
![grafik](https://user-images.githubusercontent.com/10890765/47821096-d598e980-dd5f-11e8-90ab-4e39eb86bacf.png)

**Comment by freescout-helpdesk** [comment]
Are you using nginx or apache?
Can you check the error message in browser console for css file?

**Comment by freescout-helpdesk** [comment]
It looks like by some reason `/public/storage > /storage/app/public` symlink has not been created.

Run the following console command:
```
php artisan storage:link

```

**Comment by freescout-helpdesk** [comment]
Most likely "App URL" is incorrect. Check APP_URL in your /.env file.

**Comment by nickbe** [comment]
I just found out that this has to do something with the .htaccess cache settings in exaxtly those two folders. It seems that on the first run the two .css and .js files a generated, but then they won't get loaded. As soon as I simply comment out the settings in the .htaccess files it works immediately.

**Comment by freescout-helpdesk** [comment]
Which lines in https://github.com/freescout-helpdesk/freescout/blob/dist/public/.htaccess are you commenting?

**Comment by nickbe** [comment]
The only line in /public/css/builds and /public/js/builds

**Comment by nickbe** [comment]
I tested this on multiple browsers and on two different server installations (one virtual). Same problem on both servers.

**Comment by freescout-helpdesk** [comment]
What error do you see in browser console for CSS and JS in /public/css/builds and /public/js/builds? Is it 404 error?

Do you have files requested on page in `builds` folders?

Are you using CloudFlare or similar systems?

**Comment by freescout-helpdesk** [comment]
Thank you. Replace content of the .htaccess files with (we will add it to the next release):
```
<FilesMatch "\.(css|js)$">
    <IfModule mod_headers.c>
    	Header set Cache-Control "max-age=172800, public, must-revalidate"
    </IfModule>
</FilesMatch>
```

**Comment by nickbe** [comment]
Ok. Now it seems to work. Thanks.
