### ISSUE TITLE
Web Installer -> Database: Maximum password length is 50 characters

### ISSUE THREAD

**Issue by fooness** [freescout-helpdesk/freescout#757]
Hello everyone. I’m currently _trying to_ install freescout on Ubuntu 18.04 via the web installer.

It seems there’s a problem with the database (postgresql) connection, every field/value is highlighted in red. And I really wonder, why the “Maximum password length is 50 characters” … why would you limit password lengths? I fear this is the problem we’re facing, because all other values are correct.

**Comment by freescout-helpdesk** [comment]
In the past there was a problem with this, so the password length has been limited.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/395
