### ISSUE TITLE
Docker compose options?

### ISSUE THREAD

**Issue by dabeeeenster** [freescout-helpdesk/freescout#76]
It would be great to have installation options that included:

- docker
- heroku/dokku

**Comment by freescout-helpdesk** [comment]
Yes. We are planning to do it.

**Comment by tiredofit** [comment]
I would be happy to build a Docker image using one of my bases, I just found out about this project via HackerNews and am eager to see it blossom.

**Comment by freescout-helpdesk** [comment]
@tiredofit Great. Thank you. We will add a https://github.com/tiredofit/docker-freescout link to the project's readme soon.

**Comment by Lewiscowles1986** [comment]
Quick question regarding this. From the freescout side does it require SSL? I Noticed the @tiredofit version is for the web and in example sets up letsencrypt, but I was wondering if from the FreeScout side small businesses could run it over intranet using provider encrypted email so they don't need to bother with TLS?

**Comment by tiredofit** [comment]
I can answer this after walking through the code yesterday. It doesn't require SSL, you could run it unencrypted via Port 80 if you'd like. If you were installing on a machine without Docker, simply following the Installation Guide in the Wiki will get you up and running. If you wanted to assign a SSL Certificate to it to listen on Port 443 would be fairly easy as well. The only SSL setting I could find inside of the application was to accomodate for Reverse SSL Proxies where the service was running on port 80 inside your network, and you wanted it to return (https) urls instead of HTTP.

**Comment by ptman** [comment]
@tiredofit Thank you for the dockerfile and images.

@freescout-helpdesk I would suggest grabbing the freescout -namespace on docker hub and publishing official images there.

**Comment by dabeeeenster** [comment]
Im getting an error with the docker image when trying to retrieve IMAP email in both Gmail and Yandex. 

iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed

Looks like this issue? 

https://github.com/docker-library/php/issues/240

**Comment by tiredofit** [comment]
I'll take a peek at this and have a new release for you by tomorrow. I have seen some iconv issues in the past with PHP and I'll just go ahead and compile it to be sure it's working.

**Comment by Laykou** [comment]
Hi,

I've just installed the new version but still got the error:

```
root@staging2:/data/helpdesk# docker-compose pull
Pulling freescout-app (tiredofit/freescout:latest)...
latest: Pulling from tiredofit/freescout
Digest: sha256:9081218823d778bb66876427897e2634ef03a168d2ac22c8c68ccbb9c7cdc6d4
Status: Image is up to date for tiredofit/freescout:latest
Pulling freescout-db-backup (tiredofit/db-backup:latest)...
latest: Pulling from tiredofit/db-backup
Digest: sha256:2607102fc522eb3acecc8596d3244924a0b3dfbf7f63d90491f17dacdc783a98
Status: Image is up to date for tiredofit/db-backup:latest
Pulling freescout-db (tiredofit/mariadb:latest)...
latest: Pulling from tiredofit/mariadb
Digest: sha256:e5c5e80dae2ae192ce7d42ee73df23a7dbda42e0637f204682fd8cbf381e4c30
Status: Image is up to date for tiredofit/mariadb:latest


root@staging2:/data/helpdesk# docker exec -it helpdesk_freescout-app_1 /bin/bash

bash-4.4# sudo -u nginx php /www/html/artisan schedule:run
Running scheduled command: '/usr/bin/php7' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' freescout:fetch-emails > '/www/html/storage/logs/fetch-emails.log' 2>&1

bash-4.4# cat /www/html/storage/logs/fetch-emails.log
[2018-11-06 16:08:02] Mailbox: SoftPoint Support
[2018-11-06 16:08:02] Folder: INBOX
[2018-11-06 16:08:02] Error: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed; File: /www/html/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php (189)

```

**Comment by tiredofit** [comment]
Thanks for verbose report. I will build an alternate image using debian. Will take a day as I need to juggle my day job.

**Comment by tiredofit** [comment]
Found the problem. I've pushed a new release to my repository and a new build should appear on Docker Hub shortly. This new image is built in a more traditional fashion and introduces log rotation to the freescout logs, along with moving them alongside where the nginx and php-fpm logs exist.

There is also a companion `docker-compose-no-proxy.yml` in the examples folder for those not using a reverse proxy/load balancer.

**Comment by taoeffect** [comment]
I'm encountering this `iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE'` error when attempting to fetch IMAP mail over port 993 with "Encryption" set to SSL... is this the same or something else?

FYI, I'm not using the docker image, but a normal install.
