### ISSUE TITLE
[Feature] Block attachment

### ISSUE THREAD

**Issue by tillmon** [freescout-helpdesk/freescout#762]
A feature to block certain file extension as attachment would be helpful to reduce the risk of receiving malware.

**Comment by fvdm** [comment]
Isn't this more suited in the MTA config? Usually you don't want any of your mail users to send or receive .exe files and the like, not limiting to one application.

**Comment by tillmon** [comment]
Ideally yes, but some email providers do not support it. Some antivirus software can do it.

**Comment by herbutant** [comment]
has this feature been implemented?

**Comment by freescout-helpdesk** [comment]
Can be implemented by someone as a custom module.
