### ISSUE TITLE
Microsoft 365 Exchange Online shared mailbox won't connect

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#764]
Hi there!

It's been a while since I've posted here, but that means that I'm not having many issues ;)
I'm totally in love with the system and the work you do. Thanks!

Now I've been trying to set up a new FreeScout instance for a company, but I'm a bit stuck.

The company is using Microsoft (Office in the past) 365 and is using shared mailboxes like info@contoso.com. 
I found out that you should be able to connect directly into those by using user@contoso.com\shared@contoso.com with the user's password. 

This, however, doesn't work. I'm getting the following error:

> Error: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}. Retrying PLAIN authentication after AUTHENTICATE failed.; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: AUTHENTICATE failed.; File: /home/xxx/domains/xxx/freescout/overrides/Webklex/IMAP/Client.php (230)

I've tried using / and \ with both the same result. Also leaving out the domain doesn't work.

Any ideas?

Thanks in advance!
matsn0w

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/619

**Comment by matsn0w** [comment]
Hi, I'm sorry but I did not read that as I thought this had nothing to do with oAuth.

The suggested solution looks more like a workaround for me... Is it just not possible at all?

**Comment by matsn0w** [comment]
I actually just figured it out..!

https://github.com/freescout-helpdesk/freescout/issues/619#issuecomment-699671735 #619
