### ISSUE TITLE
incorrect detecting of replies composed with Freescout

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#765]
We where talking about an issue with Outlook but today i found an issue with Freescout to freescout.
- So i have 4 mailboxes. 
- If I mail to my College's in design (from web) they get a good email in there Freescout mailbox.
- If they reply in Freescout it is going to the other mailbox web. My email is not stripped from the ticket
Hope this will be fixed in the next release :-)

Screenshot:
https://www.dropbox.com/s/5z762hts345jex2/Schermafbeelding%202020-09-28%20om%2015.58.08.png?dl=0

**Comment by joris85** [comment]
I can imagine this is also difficult for Freescout to manage (same ticketid in freescout but other mailbox).

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue. Apparently the description is not quite correct.
