### ISSUE TITLE
Database growing, what is the limit for fast freescout?

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#766]
Hi Guys,

My database is growing towards 200MB in 6 months.
Now i want to add 4 new mailboxes.
That means that we will be growing at least double the speed.

This means in 3 years couple gigabites.
Is this a problem for MySql or no problem at all?

If this is a problem (also if not) i would suggest to create a certain cleanup ad-don.
Clean all tickets of a customers that you did not interact with, filter them, select and delete all tickets.
For hosting, find attachments that are old and delete them.

Thanks!

**Comment by freescout-helpdesk** [comment]
No problem. DBs are made to grow.
