### ISSUE TITLE
Disable bounce notifications

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#767]
Hi - currently I get email notifications for bounced emails. Since I run an email newsletter (not through freescout) I get a lot of bounce replies. I would like to propose a feature/ setting that disables notifications for bounced/ auto reply emails.

You know when they happen since they are flagged so I wonder if they could be put in a separate folder, or just ignored?

**Comment by DerDanilo** [comment]
Is this going somewhere? It would be great if the system would move bounced mails automatically. Or at least make this message type available in the workflow module.

Thanks!

**Comment by freescout-helpdesk** [comment]
'Is Bounce' condition added in Workflows Module v1.0.21

**Comment by DerDanilo** [comment]
Thanks for resolving this quickly! Already useful in production. :)
