### ISSUE TITLE
Cronjob parameter to fetch all emails

### ISSUE THREAD

**Issue by toxpal** [freescout-helpdesk/freescout#768]
Installed freescout on company's server today. Had minor issues with SSL/TLS email connection, but was able to solve it. However, I have a question: is it possible to pass some parameter to cronjob to fetch all emails? Now, cronjob only fetches unread emails. There's nothing wrong about it, but I'd like cronjob to fetch read emails too.

I know freescout supports this feature because such command (fetch all emails) can be launched via freescout administration dashboard manually. Documentation doesn't say a word about this.

**Comment by freescout-helpdesk** [comment]
freescout:fetch-emails --days=3 --unseen=0

**Comment by toxpal** [comment]
Thanks!
