### ISSUE TITLE
Search - Filter manual workflows not possible

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#769]
Hi Guys,

Search could use some extra attention if you ask me.
Is this in focus to make the search better?

1. This should be per mailbox (the other mailbox can see the tickets, gets an error on clicking)
So more seperation if you ask me (GDPR also an issue i think)
2. Using the Manual Wokflows in search is not possible it looks like (see screenshot)
3. Searching in tags does not give a dropdown/suggestion with tags

<img width="589" alt="Schermafbeelding 2020-09-29 om 14 42 00" src="https://user-images.githubusercontent.com/5088751/94561760-bd3feb00-0264-11eb-8d85-ea57ad4b10a2.png">

**Comment by colegatron** [comment]
Happening in 1.6.13 too.

**Comment by freescout-helpdesk** [comment]
> 2. Using the Manual Wokflows in search is not possible it looks like (see screenshot)

Workflows are configured on a per mailbox basis, in the search conversations from different mailboxes are shows, that is why Workflows are not displayed.

**Comment by colegatron** [comment]
Using the search option 'All from current mailbox' does not allows using workflows (for that mailbox) either.

![image](https://user-images.githubusercontent.com/2078435/111603336-876fce00-87d4-11eb-9d15-9314e44ce4e0.png)

![image](https://user-images.githubusercontent.com/2078435/111603354-8c348200-87d4-11eb-81a6-905efe3e8135.png)

**Comment by freescout-helpdesk** [comment]
Fixed in the master branch.
