### ISSUE TITLE
queue:work cronjob is running, but dashboard doesn't display it

### ISSUE THREAD

**Issue by toxpal** [freescout-helpdesk/freescout#770]
Installed the latest version on cPanel server with PHP 7.4.10. Everything works fine, emails are fetched via cronjob without any errors, but administration dashboard always displays this: 

`queue:work | Last run: ? Last successful run: ? Try to clear cache to force command to start.`

Followed instructions at https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs and queue:work daemon is running. Tried clearing cache 10+ times - no luck. No errors in logs.

I found dozens of issues about queue:work not working, but all of them have very basic suggestions that "your OS might block/kill it" (which is not true in my case) and are closed without any solution (like https://github.com/freescout-helpdesk/freescout/issues/578 for example).

I realize the system is free and devs have limited time resolving issues, but it would be nice if they could take a closer look at a problem which was already reported dozens of times by different users. Which indicates it's not a problem with server.

Otherwise, the system looks promising and even if it lacks some features, I'll still be placing my order for paid plugins later this week to support the development of freescout.

**Comment by toxpal** [comment]
Some update. Like mentioned before, queue:work daemon is running, but it never completes. I use process monitoring software on server, and it flooded me with messages about excessive resource usage:

```
Exceeded:     45626 > 3600 (seconds)
Executable:   /home/virtfs/accountname/opt/cpanel/ea-php74/root/usr/bin/php
Command Line: /opt/cpanel/ea-php74/root/usr/bin/php /home/accountname/public_html/artisan schedule:run
```

I guess it's the main reason why dashboard never displays last successful run of queue:work

Suggestions, please?

**Comment by freescout-helpdesk** [comment]
Any errors in Mange > Logs > App Logs?

**Comment by toxpal** [comment]
No errors. 

fetch-emails.log - only several lines like "Fetching finished"
queue-jobs.log - one line exists, but it's empty - https://i.postimg.cc/T3R8tmsj/logs.png

**Comment by toxpal** [comment]
Not sure if that helps, but this is process output from server:

```
accountname  5174  0.0  0.0 113280  1196 ?        S    11:05   0:00 sh -c '/opt/cpanel/ea-php74/root/usr/bin/php' 'artisan' queue:work --queue='emails,default,some_random_string' --sleep=5 --tries=1 > '/home/accountname/public_html/storage/logs/queue-jobs.log' 2>&1
accountname  5175  0.0  0.4 421612 33012 ?        S    11:05   0:00 /opt/cpanel/ea-php74/root/usr/bin/php artisan queue:work --queue=emails,default,some_random_string --sleep=5 --tries=1
```

**Comment by freescout-helpdesk** [comment]
Try https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#queuework-is-not-running
