### ISSUE TITLE
Daylight saving time

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#772]
> freescout doesn't support daylight saving time, so you will need to re-adjust timezone manually. For example, if you live in GMT+2, you will need to use GMT+3 now because of daylight saving time. Hopefully it will be implemented in future releases.
https://github.com/freescout-helpdesk/freescout/issues/771#issuecomment-701219999

**Comment by fvdm** [comment]
When you set the timezone to a location such as `Europe/Amsterdam`, DST will automatically switch. Provided the PHP server's timezone database is current.

I just tested it on PHP 7.3

```php
<?php
date_default_timezone_set ('Europe/Amsterdam');
echo date ('r');
echo date ('r', time() + 86400*30); 
```

**Comment by fulldecent** [comment]
recommending to close issue
