### ISSUE TITLE
Start new ticket with Note (maybe even without customer)

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#776]
Hi guys,

A lot of times i send my college in the ticket system an email. 
Now that is kinda not possible but would love to notify him trough freescout.
So i would suggest to add at the start of a new ticket next to Call a note as option. 
99% the same as the call and we could fix it with that but i can imagine that with note a customer is not mandatory.

Do you think this could be a core option?

**Comment by freescout-helpdesk** [comment]
It's not clear what is needed.

**Comment by davask** [comment]
Not sure what @joris85 is describing but it would be awesome to create a ticket via a note without assigning a recipient.
Right now we need to send an email to someone to create a new ticket but sometime we just want to create a ticket without sending any email.
Would it be possible ?

**Comment by fulldecent** [comment]
This is currently possible with the calls feature. No email to the customer is sent.

<img width="1733" alt="Screen Shot 2022-10-11 at 15 22 39" src="https://user-images.githubusercontent.com/382183/195180675-08ab197e-1ecf-48ee-9c02-cc164223dd72.png">
