### ISSUE TITLE
Customization of "Send Confirmation" text in Satisfaction Ratings

### ISSUE THREAD

**Issue by gino0631** [freescout-helpdesk/freescout#777]
While it is possible to define a custom "Send Confirmation" text in mailbox settings, the default "Feedback sent" is always used.

For this to be fixed, `thanks()` function in `SatRatingsController` should use the same logic of handling of `$mailbox->ratings_trans` as `record()` does.

**Comment by freescout-helpdesk** [comment]
Will be fixed.

**Comment by freescout-helpdesk** [comment]
Fixed in Satisfaction Rating Module 1.0.5
