### ISSUE TITLE
[REQUEST] Module: Quick login

### ISSUE THREAD

**Issue by Servery** [freescout-helpdesk/freescout#779]
I would like to have a quicker way to login on our reception pc (staff changes every hour). How about an overview with all accounts like this example:
![freescout_quick-login](https://user-images.githubusercontent.com/3184297/94921516-c1644680-04b8-11eb-9413-b0e105f1d5e7.png)
source: https://mdbootstrap.com/snippets/jquery/m-dembna/1154555

If you select one accout bei clicking on it you get a modal to enter a PIN or the password:
![freescout_quick-login2](https://user-images.githubusercontent.com/3184297/94921735-25870a80-04b9-11eb-9f8e-6a4635769f2f.png)
source: https://mdbootstrap.com/docs/jquery/modals/basic/ (Central Modal / SMALL)

To get more security it would be nice to configure "whitelisted" IP and hostnames which get this quick login site instead of the standard login page.

**Comment by tiredofit** [comment]
Servery if you had a reverse proxy/authentication system sitting in front of your Freescout installation you could take advantage of the LDAP module and it's included SSO Functionality. You could make that page you mocked up sit in front of your freescout installation and allow for username/mail to be passed without requiring authentication. I can share how I do it in my org if you want more details.

**Comment by Servery** [comment]
Maybe that will work. But I don't want to set up an LDAP server just for FreeScout. I already tried to get my mocked up site working on my FreeScout inatallation but I failed to get the hidden input field "_token" right, so that my quick login works.

**Comment by fulldecent** [comment]
I created a tool to allow quick customizations like this. Please see:

https://github.com/fulldecent/freescout-dropkick-js

Here is how to use it for your use case: add a javascript snippet that detects if the login page is loaded. If so, import content from a static HTML file you are hosting somewhere. It has the functionality that clicking a photo sets the username. And the password can also be entered.

This addresses the `_token` issue. And the page is loaded from your normal Scout URL.
