### ISSUE TITLE
Customer rating email after close ticket

### ISSUE THREAD

**Issue by elfeffe** [freescout-helpdesk/freescout#78]
Does it send an email after ticket closing to rate the service?
I use that in Zendesk, the weekly reports that tells us the satisfaction of the customers for example.
Is that implemented?

**Comment by elfeffe** [comment]
This is great
Any idea about when you plan to integrate that?
I mean, I know this is an open source project and I can't hurry you, I'm just asking

**Comment by freescout-helpdesk** [comment]
In about a week

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/satisfaction-ratings/

You will need to [update](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout) FreeScout to 1.0.4 to use Satisfaction Ratings.

**Comment by guestisp** [comment]
I don't see the repositories for these modules

**Comment by freescout-helpdesk** [comment]
@guestisp official modules are developed and maintained by FreeScout team.

**Comment by guestisp** [comment]
How to download that ? I've followed the online "purchase" but there isn't any downloadable file...

**Comment by guestisp** [comment]
> official modules are developed and maintained by FreeScout team.

So, this isn't a totally open-source and free project..... There are some modules that (i'm willing to bet) would be encoded or sold.

**Comment by guestisp** [comment]
You can't compare a 6 days project like freescout to multiple years projects like WordPress or redmine..

After 6 days you are already setting some features as external and under registration.... It seems a little bit strange to me.

I've never seen a work in progress project with still tons of todo, having external and not public modules. usually external modules are made when the core project is done or almost done.

It seems that you are looking for developers to fix (for free) the core project when you are making external (and maybe paid) modules.....

If these modules are free, please release them as open source

My two cents..

**Comment by osworx** [comment]
> > official modules are developed and maintained by FreeScout team.
> 
> So, this isn't a totally open-source and free project

Open Source does not mean that the scripts have to be free.
While it does also not mean that they are (automatically) encoded (would violate the License).

Btw: under which License is this project running - cannot  find any line about that!

And mentioning other (big) projects after a few days and a bit of code is not really a way to promote a new project.

As I can see have you labeled many issues with 'help wanted'.
What does that mean?
Help wanted for free and publishing as paid or free module/extension?
Or do you want to increase your team?

**Comment by freescout-helpdesk** [comment]
> Btw: under which License is this project running - cannot find any line about that!

![2018-11-13_11-00-19](https://user-images.githubusercontent.com/40499291/48398952-55955b00-e733-11e8-897d-31e8b147b047.png)

> And mentioning other (big) projects after a few days and a bit of code is not really a way to promote a new project.

Planning has to be done in the beginning to avoid mess in the future. Good project is impossible without good planning.

> As I can see have you labeled many issues with 'help wanted'.
> What does that mean?

Community is invited to participate in developing FreeScout core. 

> Help wanted for free and publishing as paid or free module/extension?

Official modules are developed and maintained only by FreeScout team. Third party modules can be developed by anyone.

**Comment by guestisp** [comment]
@elfeffe Exactly. You wrote in a much better english than mine, what I'm trying to say...

**Comment by osworx** [comment]
Nobody has to expect money for his work if the project is an 'open' project.
But what I do not like is a sentence like that:

> Official modules are developed and maintained only by FreeScout team. Third party modules can be developed by anyone.

Does that mean, when someone else is developing a module, it wil be not official??
Official means agreed by the 'core' team?
Or made by the team and nobody else.

Guess you have to rethink your strategy, I am working since 15 years on OpenSource projects, but such I have never seen before.

What you could do, 'Official' means excepted and approved by the core team.
LIke many other projetcs have in their store.
And if someone develop a module, you could sell in it your store and let the devloper participate.

Just a few thoughts ..

**Comment by guestisp** [comment]
Why not using composer as dependency manager? Installing/Removing modules from web interface doesn't lead to anything good.

I don't think an help desk would be used by users without any knowledge, it's not a CMS or an Ecommerce. It's an IT product and most of the time will be installed by techs able to do a `composer update`

**Comment by freescout-helpdesk** [comment]
> Why not using composer as dependency manager? Installing/Removing modules from web interface doesn't lead to anything good.

The thing is that according to feedbacks from FreeScout users most of them do not want to deal with files, console, composer, etc. Some even have no idea what `SSH console` is and could not install FreeScout until web installer has been [implemented](https://github.com/freescout-helpdesk/freescout/commit/d7f6090f0515f216fce7feb570f95bcbfd108d25). They want everything to be managed from the web interface: installation, updates, adding modules, etc. That is why it is important to have modules architecture easily managed from the web interface.

**Comment by guestisp** [comment]
So, publish all modules on github and allow users to make PR in case of bugs.
Third party modules could be approved by you (like Prestashop does when uploading on their marketplace)

I don't see anything bad. FreeScout marketplace must be moderated like with any project.

**Comment by freescout-helpdesk** [comment]
The other reason to have modular architecture is the size of FreeScout build. It is 17 MB now and if we will add all the possible features into the core, it will become a **monster** (see what happened to another Laravel helpdesk - [FaveoHelpdesk](https://github.com/ladybirdweb/faveo-helpdesk), which grew to 92 MB!). If FreeScout dist will continue growing it will be impossible to use web installer due to memory problems on users's hostings (some already have memory problems when updatings the app).

> So, publish all modules on github and allow users to make PR in case of bugs.

In future some modules selectively will be provided for fixed payment or donation, not clear which ones, time will tell... So if we let community contribute into official modules development, after some module will be converted into paid, this will not be fare towards contributors. Bug reports are always available via [issues](https://github.com/freescout-helpdesk/freescout/issues) anyway.

**Comment by osworx** [comment]
> In this case each third party module uploaded to the directory (and each it's update) will need to be checked by FreeScout team, otherwise at some point someone may inject some malicious code into his/her module and it will go into FreeScout apps. This is one of the problems which WordPress plugins directory is facing.

That is why I do not like WordPress.
Beside this, enabling the download of additional modules via the backend (connected to the store) only, can solve the problem in installing modules from obscure sources (which will happen).

> checking by the FreeScout team

And where is the problem?
Nobody said that additional modules have to be free. 
If you build a robust ecosystem (store) with clear guidelines (who, why, what, etc.), everybody can benefit.

Let the core be as small as possible!
If a User wants to install additional modules, only a view bytes are downloaded - nobody will have a problem with that.

And taking care on those users who have no glue what they are doing, offer a paid service.
AS @guestisp said: noobs wont install a helpdesk.

**Comment by guestisp** [comment]
Honestly, this is going in the wrong direction. Making the canned responses as module (free or not free it doesn't matter) means that many other "mandatory" feature would be under subscription.

There is nothing bad in making some modules under subscription, as long the core/FOSS modules are enough. Canned responses can't be placed as external modules.

If you wan't to be a free alternative to HelpScout/Zendesk (as wrote on your page) you must provide (as free) what helpscout/zendesk are providing under payment.

An example module that could be made under subscription would be any integration with an existing CRM, with Salesforce and so on. Something "additional", not something that is the core-part of any helpdesk software.

It's like making a module for the steering wheel in car. You can make the car radio as module.........

And, as wrote previously, you can't start making external modules (not available in github to everyone) just after a couple of days. Honestly i've lost much of the interested in this project, after 2 days!!

**Comment by elfeffe** [comment]
Yes, I think he same.
Core features (Zendesk default features), must be free and open source.
Then you can charge for extra services, integrations with ecommerce, amazon, ebay.
Ticket sentiment classification (using AI).
Things like that, but canned replies, they must be free and open source.
You can charge for hosting, for extra integrations (Zendesk is plenty of extra plugins, you can charge as they do), but the core (default Zendesk and HelpScout) features, should be free and open source.
That's my opinion, I also collaborate and participate in a lot of Open Source projects, from 10 years ago.

**Comment by guestisp** [comment]
Regarding to this, please release Satisfaction Ratings and Saved Replies as core. They are fundamental for a good helpdesk, they aren't two "optional" modules.

As wrote previously, if you wan't to be a free and open alternative to helpscout and zendesk, you should release what they have in their plans are standard or you'll only be a yet another non free alternative.

I've used and tested HelpScout a couple of days. Their way to think an help desk is **MUCH** better than zendesk. HelpScout has almost everything included even in lower packages.
To really be an alternative, you should release what they have in the Plus package.

Probably, what could be release as module would be: Salesforce, Jira, HubSpot Apps, HIPAA Compliance, SSO/SAML Authentication and something similiar. Very advanced feature.

You can't release canned replies as module.

**Comment by freescout-helpdesk** [comment]
We will see how it goes after several months. No need to spam. First and last warning,

**Comment by elfeffe** [comment]
> We will see how it goes after several months. No need to spam. First and last warning,

Sure, at the end is your project and you do what you want.
I was just trying to give my opinion and in any case you offer a lot of features for free, and what you offer saves a lot of hours working.
I mean, I thank you for what you offer, because it's already a lot.

**Comment by guestisp** [comment]
> We will see how it goes after several months. No need to spam. First and last warning,

Ok, so, please continue the development on your own.
I don't have time to spend (for free) on a project without a clear roadmap and that could became under subscriptin in at any time.

Good luck.

Funny fact: I've **never** ever seen a project to die after a couple of weeks just because the administrator started to create closed source modules in 6 days.

**Comment by abolinhas** [comment]
> @elfeffe Will this work for you or you want ratings to be sent only once when ticket is closed?

Hi
It's possible just send the Ratings after the ticket is closed?
