### ISSUE TITLE
Zapier Integration

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#780]
Does anybody need a Zapier integration? If yes, what exactly you need to integrate via Zapier.

**Comment by tiredofit** [comment]
When you say Zapier, this is more so for Zapier to connect IN to freescout as opposed to outbound, considering your newly released API and Webhook Module should accomodate for outbound. I'm not personally using Zapier, but a big fan of [n8n](https://www.n8n.io) which offers similar functionality, but source available. Just my 2c.

**Comment by adamsewell** [comment]
I'd just like the ability to create tickets from Zapier

**Comment by freescout-helpdesk** [comment]
It looks like Zapier integrations are not much needed.

**Comment by freescout-helpdesk** [comment]
FreeScout is available in Zapier now https://zapier.com/apps/freescout/integrations
For now with one Action allowing to create conversations.

**Comment by CosmikCarrot** [comment]
Excellent - Thanks! @freescout-helpdesk

**Comment by netspear** [comment]
I am trying to connect zapier to freescount, but I keep getting server error while trying to set it up.
Would someone be able to help me?

**Comment by freescout-helpdesk** [comment]
Check logs

**Comment by shanebreckon** [comment]
How do you add tags to the "Create conversation in FreeScout" action in Zapier? Is this possible?

**Comment by shanebreckon** [comment]
> How do you add tags to the "Create conversation in FreeScout" action in Zapier? Is this possible?

Resolved using Zapier Webhooks - https://zapier.com/page/webhooks/
