### ISSUE TITLE
Make mailbox manager permissions table scrollable

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#785]
The new Mailbox Managers permissions table is cut off horizontally when it is wider than the screen. It doesn't scroll so you can't see the other options without rotating the device to landscape.

Mailbox settings > Permissions > Access Settings

On iPhone 8:

![image](https://user-images.githubusercontent.com/93784/95031505-9fd0ae00-06b6-11eb-8a99-de216985c731.jpeg)

**Comment by freescout-helpdesk** [comment]
Fixed by https://github.com/freescout-helpdesk/freescout/pull/788
