### ISSUE TITLE
mailbox name on forwarded mail via freescout

### ISSUE THREAD

**Issue by lakym86** [freescout-helpdesk/freescout#786]
Hi,

I am using this software few days, and it is fantastic! Great job done!

A noticed bug:
Ticket is forwarded to internal email address! When replying to the email, Email account name of Customer is displayed on internal email address, but the email address is ok! See picture below for better understanding! Can you fix this in the next update!

![freescoutissue](https://user-images.githubusercontent.com/36364577/95091510-d8a86b80-0726-11eb-8579-dca08c0d876b.png)

I use the last version. Updated few days ago

**Comment by freescout-helpdesk** [comment]
Could you please write step-by-step instruction to reproduce the issue.

**Comment by lakym86** [comment]
1. Ticket recieved from our customer 
2. Agent forward this email to third party address  eg. our internal email address, for additional information
3. On email reply by our internal staff (not agent at freescout) on email client, email account of the reciever list, is displayed customers account name instead of internal email address account name 

on the picture, step 3, you have the example
instead of Bosh Mayer <dispeceri@expressone.ba>
should be Dispeceri <dispeceri@expressone.ba> or only <dispeceri@expressone.ba>

Bosh Mayer (customer with customer mail eg: boshmayer@gmail.com)

**Comment by lakym86** [comment]
Another example:

Forwarded mail to dispeceri at expressone.ba
but **display name** is the cutomers name which email is forwarded
![New Picture](https://user-images.githubusercontent.com/36364577/95167141-6760cb00-07af-11eb-8812-0850bb5d9042.png)

**Comment by lakym86** [comment]
Hi,

Something new on this topic? We use email/ticket forwarding a lot and this is confusing the receivers (thinking the customer is also in the email of receivers)

Thank you

Br

**Comment by freescout-helpdesk** [comment]
If someone can figure this out and fix please submit a pull request.

**Comment by lakym86** [comment]
Maybe this is not explained clear. I wll try to explain again.

Ticket (email) recieved on freescout:
1. eg sender name "company"  with email address company@test.com  (name in fresscout Company)

2. forward this email  internal to someone eg. to: internal@int.com

3. email recieved with following information 

sent to: company with email address: internal@int.com

display name is "company" display nam of forwarded mail instead of eg. internal or only internal@int.com

reciever is thinking the customer is also in the email of receivers (but only the display name is wrong).


On this picture:
![image](https://user-images.githubusercontent.com/36364577/97156717-6223ea00-1777-11eb-8c4d-41635e58e745.png)

Display name should be Dispeceri (to which the email was forwarded) not the Company name whose email is forwarded.

**Comment by lakym86** [comment]
Forwarded
![New Picture](https://user-images.githubusercontent.com/36364577/97457084-b5de3100-1939-11eb-8d5c-75d5a3366a59.png)

Recieved
![New Picture (1)](https://user-images.githubusercontent.com/36364577/97457139-c2628980-1939-11eb-919a-8193ee2340cc.png)

Please have a look on sender and reciever (selected part)

**Comment by freescout-helpdesk** [comment]
Now it's clear. We will try to fix.
