### ISSUE TITLE
failure to reactivate modules

### ISSUE THREAD

**Issue by vbandarra** [freescout-helpdesk/freescout#791]
Hello everyone. I had a problem with the server and had to do a clean installation of FreeScout. Everything went well. When I wanted to install the modules with the keys I had, I received the message that there were no more licenses available with that key. Does anyone know how to overcome this problem?
Thank you very much.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#is-it-possible-to-transferdisable-the-module-licenses-from-the-old-domain-and-reactivate-them-on-the-new-domain

**Comment by vbandarra** [comment]
Thanks. Problem solved! :)
