### ISSUE TITLE
[Bug] error while udating 1.6.1 -> 1.6.2

### ISSUE THREAD

**Issue by Servery** [freescout-helpdesk/freescout#793]
After clicking on the button to update there showed up an error msg: try again or another update method. But in FreeScout now shows me the new version 1.6.2 and no button to try again.

Error laravel Log:

Illuminate\Routing\Router::loadRoutes(): Failed opening required '/var/www/vhosts/FreeScout/routes/api.php' (include_path='.:/opt/plesk/php/7.3/share/pear') {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Illuminate\\Routing\\Router::loadRoutes(): Failed opening required '/var/www/vhosts/FreeScout/routes/api.php' (include_path='.:/opt/plesk/php/7.3/share/pear') at /var/www/vhosts/FreeScout/vendor/laravel/framework/src/Illuminate/Routing/Router.php:393)

Illuminate\Routing\Router::loadRoutes(): Failed opening required '/var/www/vhosts/FreeScout/routes/api.php' (include_path='.:/opt/plesk/php/7.3/share/pear') {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Illuminate\\Routing\\Router::loadRoutes(): Failed opening required '/var/www/vhosts/ferienpark-ostsee.de/FreeScout/routes/api.php' (include_path='.:/opt/plesk/php/7.3/share/pear') at /var/www/vhosts/FreeScout/vendor/laravel/framework/src/Illuminate/Routing/Router.php:393) 

Is there anything to do or should I just ignore this errors?

**Comment by freescout-helpdesk** [comment]
When updating to the 1.6.2 version the FreeScout may show an error (`Failed opening required '/routes/api.php'` in logs), but show the new version (1.6.2). You can ignore this error, application will function normally.
