### ISSUE TITLE
[REQUEST] Module: WooCommerce integration

### ISSUE THREAD

**Issue by passatgt** [freescout-helpdesk/freescout#794]
Hi!

It would be nice to display the WooCommerce order information related to the conversation, the same way HelpScout works. I put together a proof-of-content, it works, but i have 0 knowledge in Laravel, so its just a hacked together JS based solution. But it does work and might be a good starting point.

Repo of someone wants to play with it: https://github.com/passatgt/freescout-woocommerce

![screenshot](https://user-images.githubusercontent.com/43415/95378300-0090fe00-08e4-11eb-8a64-4a844aa2ece7.png)

**Comment by passatgt** [comment]
Ok so i tried to learn a bit of Laravel and i was able to make this a lot better now. It has a settings screen under Settings / WooCommerce to enter the API keys and domain. It will still store the order data in the browser's LocalStorage, but the API call is on the server side now.

**Comment by diguinho2018** [comment]
Hey @passatgt, I have a woocommerce site and I'll test your module.

**Comment by passatgt** [comment]
> Hey @passatgt, I have a woocommerce site and I'll test your module.
> 
> Edit 01:
> Just installed and I don't see the settings screen you mentioned under Settings/WooCommerce.

Did you activate the module? And make sure the folder name is WooCommerce.

**Comment by diguinho2018** [comment]
I renamed the folder to "WooCommerce" but when I try to activate I have this error and the module isn't activated:
![001](https://user-images.githubusercontent.com/39450586/95800453-c0f45880-0ccd-11eb-8f64-224c7c4f7700.png)
