### ISSUE TITLE
email subject

### ISSUE THREAD

**Issue by vbandarra** [freescout-helpdesk/freescout#795]
Hello guys.

Does anyone know how to automatically change the email subject, so that as soon as it is assigned to a user, it will have the ticket number in the email subject?

Thanks.

**Comment by diguinho2018** [comment]
Hey!
FreeScout already does that by sending the ticket email to the Staff with the ticket id in the subject.
`[#1] TICKET SUBJECT`

**Comment by vbandarra** [comment]
Hi there.
Yes it's true. But when the user replies to the customer, the ticket number does not appear in the subject of the reply email.
That is my question, if there is any automatic way to update the subject of the email.
I know that it is possible in automatic responses.

Thanks for your reply :)

**Comment by vbandarra** [comment]
Hello guys.

Can someone help me with this ticket?

Thank you

**Comment by freescout-helpdesk** [comment]
It's impossible. Maybe someone can implement as a custom module.

**Comment by choletzke** [comment]
> Hello guys.
> 
> Can someone help me with this ticket?
> 
> Thank you

Hi vbandarra,

it is possible with own php script in crobjob:

here my example: 
-------------------------------------------------------------
/opt/subjectCorrect.php
-------------------------------------------------------------
#!/usr/bin/php
<?php
$pdo = new PDO('mysql:host=localhost;dbname=mysqlDatabase', 'mysqlUser', 'mysqlUser');
 
$sql = "SELECT subject,number FROM `conversations` WHERE `subject` NOT LIKE '%[ticket#%' ORDER BY `id` DESC";
$i=0;
foreach ($pdo->query($sql) as $row) {   
   $subjectNew=$pdo->quote("[ticket#".$row['number']."] ".$row['subject']);   
   $updateSql[$i]="UPDATE `conversations` SET `subject`=".$subjectNew." WHERE `number`='".$row['number']."'";
   $i++;
}

-------------------------------------------------------------
create cronjob
-------------------------------------------------------------
# crontab -e
*/1 * * * * /usr/bin/php /opt/subjectCorrect.php >> /dev/null 2>&1

-------------------------------------------------------------
autoreply ....
-------------------------------------------------------------
after this cron php script you can work with workflows with subject contains .... 
and send a reply to your customer.

**Comment by vbandarra** [comment]
Thanks  choletzke. I will try it!

**Comment by choletzke** [comment]
second solution is mysql trigger:

CREATE TRIGGER `before1` BEFORE UPDATE ON `conversations` FOR EACH ROW IF new.subject NOT LIKE '%[TicketYourCompany-%' THEN 
SET new.subject = CONCAT('[TicketYourCompany-',new.number,'] ',new.subject);
END IF
