### ISSUE TITLE
url /polycast/receive request

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#796]
Hi Support
We are wondering if you could provide insight into this url
domain.com/polycast/receive

Basically we getting on average 20k requests on this url every 6 hours, but we see nothing on this link in freescout.
If freescout uses this, what is the purpose of this url?

Some insight would be great
thanks
M.

**Comment by freescout-helpdesk** [comment]
Real-time interface updates https://github.com/leemason/polycast

**Comment by raramuridesign** [comment]
Thanks. So as I understand it, there should be no issues with this... ?

**Comment by freescout-helpdesk** [comment]
Nope

**Comment by raramuridesign** [comment]
Thanks ;-)
