### ISSUE TITLE
Prevent Ticket reopening

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#798]
Hello guys!

Is there a way to prevent user from reopening ticket by replying to the email once this ticket has been marked as closed by staff?

Thank you.

**Comment by freescout-helpdesk** [comment]
No for now.

**Comment by diguinho2018** [comment]
Hey @freescout-helpdesk, thank you for your answer.
That would be a great feature, could have a "lock" option and if the user reply to the thread the system could send an email qith custom message.

**Comment by adamsewell** [comment]
How other ticketing systems handle this is by using Resolved and Closed statuses. Resolved can be reopened until X number of days and Closed tickets can not. Just food for though.

**Comment by fvdm** [comment]
@adamsewell That would be a great solution!

**Comment by diguinho2018** [comment]
> 
> 
> How other ticketing systems handle this is by using Resolved and Closed statuses. Resolved can be reopened until X number of days and Closed tickets can not. Just food for though.

That would be a great solution, also integrated with workflows to set the status automatically.

**Comment by fulldecent** [comment]
Maybe a workaround is to use a workflow:

- If closed: tag as stay_closed
- If tagged as stay_closed and is open: close it

**Comment by fulldecent** [comment]
Recommending to close issue as workaround exists and developer said "not for now"

**Comment by PeopleInside** [comment]
Will be useful lock the customer from adding new comments.
I opened a feature request: [here](https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/440598) who interested can vote it!

**Comment by Jlsmith1001** [comment]
Did this feature get implemented?  Can't find the setting if so, and this is causing me a problem.

**Comment by PeopleInside** [comment]
@Jlsmith1001 unfortunately the function has not yet implemented and we don't know if will be. I'm sorry for the issue caused.
