### ISSUE TITLE
Error sending email to user

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#799]
Hey guys!

I just installed Workflows module and I configured actions like the image bellow.
![001](https://user-images.githubusercontent.com/39450586/95664913-05db8c00-0b22-11eb-8cbb-2ffcc85d1f16.png)

Then I checked the logs and got these errors.
![002](https://user-images.githubusercontent.com/39450586/95664929-29063b80-0b22-11eb-8335-e3de4123a979.png)

It also appears in production log (more than 50 pages with same issue).
![003](https://user-images.githubusercontent.com/39450586/95664962-7a162f80-0b22-11eb-981f-563aac8ced11.png)

Is that something I need to worry about?
Could you guys help please?
Thank you!

**Comment by freescout-helpdesk** [comment]
We will check after some time.

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue.

**Comment by diguinho2018** [comment]
Hey!
I can confirm that this error is not affecting the emails sent to users/customers.
Also after a fresh install it didn't come up again.
