### ISSUE TITLE
Ingest email via something other than IMAP

### ISSUE THREAD

**Issue by ptman** [freescout-helpdesk/freescout#80]
E.g. a webhook so that one could write a really small piece of software to deliver email from the MTA without having to have an IMAP account set up.

**Comment by freescout-helpdesk** [comment]
IMAP is used to fetch emails from the mailbox (not to send).
Can you give an example of the software?

**Comment by dabeeeenster** [comment]
Support for things like Mailgun incoming mail webhooks would be perfect

**Comment by ptman** [comment]
Sure. Say you're running postfix. You can add pipe commands to aliases -files or ~/.forward:

    # /etc/aliases
    mymailinglist: |/usr/local/bin/command-that-processes-mail --mailing-list-name mymailinglist
    # ~/.forward
    |/usr/local/bin/command-that-processes-mail --mailing-list-name myusername

**Comment by mattsims** [comment]
@freescout-helpdesk I'm up for the challenge, can you assign this task to me?

**Comment by freescout-helpdesk** [comment]
You are welcome to implement it.

**Comment by freescout-helpdesk** [comment]
Implementation using https://github.com/beyondcode/laravel-mailbox will add several extra dependencies, so it would be better to implement it as a module.

https://github.com/freescout-helpdesk/freescout/pull/254

**Comment by mattsims** [comment]
No problem. Is there any documentation on creating modules?  Or should I just examine an existing module?

What were your thoughts on a Laravel v5.7 compatible release?  As would still need this even if the new functionality is introduced via a module.

**Comment by freescout-helpdesk** [comment]
Upgrading to Laravel v5.7 is not planned for now. You will need to make chosen package working on Laravel v5.7.

**Comment by iPublicis** [comment]
> No problem. Is there any documentation on creating modules? Or should I just examine an existing module?

Thanks for getting forward on this.

Piping email with Laravel example at https://www.sitepoint.com/piping-emails-laravel-application/
Sample module for FreeScout at https://github.com/freescout-helpdesk/SampleModule

**Comment by iPublicis** [comment]
> No problem. Is there any documentation on creating modules? Or should I just examine an existing module?

Thanks for getting forward on this.

Piping email with Laravel example at https://www.sitepoint.com/piping-emails-laravel-application/
Sample module for FreeScout at https://github.com/freescout-helpdesk/SampleModule


> 
> 
> No problem. Is there any documentation on creating modules? Or should I just examine an existing module?
> 
> What were your thoughts on a Laravel v5.7 compatible release? As would still need this even if the new functionality is introduced via a module.

Hi @mattsims. Any news on this front?

**Comment by iPublicis** [comment]
Hi @mattsims. Any news on this front?

**Comment by freescout-helpdesk** [comment]
Feel free to use https://freescout.net/module/api-webhooks/ or https://freescout.net/zapier/
