### ISSUE TITLE
Workflow don't run in subject

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#800]
Hello guys!

I set workflow as image bellow.
![01](https://user-images.githubusercontent.com/39450586/95665115-8d75ca80-0b23-11eb-9c07-d8fec445ff90.png)

Then sent an email and the system recognizes the new ticket but it never run the workflow based in subject.
![02](https://user-images.githubusercontent.com/39450586/95665046-104a5580-0b23-11eb-8ed9-a5a44a346c0f.png)

But the ticket subjects contains the "[Completo]" as seen in the images.
I have a wordpress website and a form that contains the same subject in all submissions for every user, whats differs is the content that contains the user message.

If I change that to Body, it runs ok.
 
Thank you for your help.

**Comment by diguinho2018** [comment]
Hello guys, any news on this?

**Comment by freescout-helpdesk** [comment]
We'll check after some time.

**Comment by freescout-helpdesk** [comment]
The issue has not been confirmed.

**Comment by diguinho2018** [comment]
It is still not running on subjects in my installation.
Maybe it is something related to characters like: ú, á, é..?
