### ISSUE TITLE
Pasting an Image in Editor pastes twice

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#801]
Freescout 1.6.2 - Has happened in previous releases as well.

When creating/editing a message and pasting in contents of the clipboard, two appear in the editor.
Screenshot, after pasting a snippet of my screen.
![image](https://user-images.githubusercontent.com/23528985/95666558-a5dbea00-0b0f-11eb-8793-7a29c507b66b.png)

When receiving the email, it is referenced both as Base64, and also as an attachment (freescout.example.com/storage/xx/xx/xx/id.jpg) on an external client.

Even stranger, is that when you look at the history within Freescout it only shows one image which is using the file storage option ie: `https://freescout.example.com/storage/attachment/3/2/1/image.png?id=14&token=db8ca42ea4ed48469895a2b0713bacee`

![image](https://user-images.githubusercontent.com/23528985/95666607-18e56080-0b10-11eb-8705-0720de53c5a4.png)

I'd prefer if someone was pasting an image it was sent truly as Base64, but if it could only be using the /storage/ method, that will have to do. Is there a way though to only let one image through?

**Comment by freescout-helpdesk** [comment]
Duplicates https://github.com/freescout-helpdesk/freescout/issues/694
