### ISSUE TITLE
MP3 Attachments

### ISSUE THREAD

**Issue by bman955** [freescout-helpdesk/freescout#803]
Does freescout support MP3 attachments?

I want to have the support voicemail box open tickets, and the voicemails are sent via email. When I have tested this, the email opens a ticket but the mp3 isn’t on freescout. It is on Office365 however.

Thanks

**Comment by freescout-helpdesk** [comment]
Any files can be attached to emails, including MP3.

**Comment by bman955** [comment]
Any idea why it wouldn't be imported into freescout then?

**Comment by Servery** [comment]
[REQUEST] Maybe it could be implemented, that audio attachments like .wav or .mp3 were directly playable in FreeScout, so that is no more needed to download these files and play it with VLC. (I am using a VoiceMailBox, which sends mails with .wav attached.)

**Comment by fvdm** [comment]
@Servery I like that idea, but keep it simple to avoid feature-creep/dependency complication. Only wrap the attachment url in a `<audio>`  and perhaps `<video>` [tag](https://www.w3schools.com/html/html5_audio.asp) based on the file extension. Let the browser handle the rest.

**Comment by freescout-helpdesk** [comment]
> Does freescout support MP3 attachments?

Yes.
