### ISSUE TITLE
Is it possible to connect support@domain.com to freescount ticket

### ISSUE THREAD

**Issue by intered** [freescout-helpdesk/freescout#808]
Hi there,

I am looking for a new ticket system and my eye got caught on Freescout. As it is now, only the email address support@domain.com is connected to another ticket system. All email that is send to this email address, enters the ticket system.  Meaning that users don't first have to register with the Freescout ticketsystem in order to send in a ticket. And when answering the ticket, it is being send directly to the user email address. Is this also possible with Freescout?

And possible to add seperate mailboxes for support@domain1.com - support@domain2.com ?

**Comment by freescout-helpdesk** [comment]
Yes
