### ISSUE TITLE
Installation guide should not overwrite mysql server without informing user

### ISSUE THREAD

**Issue by tareko** [freescout-helpdesk/freescout#81]
The default Ubuntu installation such as 16.04 that I am using in my server uses mysql. I was mindlessly copy/pasting and accidentally overwrote my Mysql which was irritating to fix.

The instructions SHOULD NOT suggest mariadb without informing users that it will automatically remove the mysql-server installation.

tarek : )

**Comment by freescout-helpdesk** [comment]
Are you using docker?

**Comment by tareko** [comment]
No. I followed the instructions here:
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide

**Comment by freescout-helpdesk** [comment]
Thanks. Instruction has been updated: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#2-installing-package-dependencies
