### ISSUE TITLE
more formating options in wysiwyg editor like monospace block

### ISSUE THREAD

**Issue by psuter80** [freescout-helpdesk/freescout#810]
is it possible to add more formatting options to the icon-bar in the text editor for ticket replies and notes? I am especially interested in a code block that allows to post ascii tables etc. in monospace font. 
a workaround is to switch to html view and add a <code></code> block, but that's cumbersome as one needs to switch forth and back all the time during longer messages

**Comment by freescout-helpdesk** [comment]
Duplicates https://github.com/freescout-helpdesk/freescout/issues/718

**Comment by freescout-helpdesk** [comment]
[Extended Editor](https://freescout.net/module/extended-editor/) module released.
