### ISSUE TITLE
Custom field multiple options (checkbox, multiple dropdown)

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#811]
Custom field multiple options (checkbox, multiple dropdown)
Is it easy to add a feature like this?
https://www.dropbox.com/s/qwztqspjmmgu430/Schermafbeelding%202020-10-15%20om%2009.33.16.png?dl=0

So you can kinda add another way to filter on some keywords you have a preset in then tags.

**Comment by freescout-helpdesk** [comment]
No plans for now.
