### ISSUE TITLE
After last update history of FreeScout is not deleted

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#813]
Hi There,

I love the feature that all old bulshit is deleted.
I work a lot together with colleges that use Helpscout.
After last update something went wrong and Freescout does not see where the line is to remove.
I get long long conversations again.

This worked untill 6 oktober perfect.
Then i updated to the latest version with 2 small versions.
So in the last or the one before there is an issue.
Or Helpscout does not like freescout and is interfering to irritate users of freescout.

**Comment by freescout-helpdesk** [comment]
If someone can please fix this.

**Comment by fulldecent** [comment]
Can someone experiencing this issue please reproduce using version 1.8 or later?

**Comment by freescout-helpdesk** [comment]
We'll close this as there were no other such reports.
