### ISSUE TITLE
Workflow module feature request

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#815]
Hey guys!
I was doing some workflow configurations and I came with this feature request.
Would be great to have the possibility to set a per workflow "User Full Name" that would be used to appear while using the variable "User Full Name" in replies, as marked in the images, like that it wouldn't appear as "Workflow" in email from title or in signature.

![2](https://user-images.githubusercontent.com/39450586/96198343-f184fe00-0f2a-11eb-91ed-c6b0f27110f1.jpeg)
![1](https://user-images.githubusercontent.com/39450586/96198347-f2b62b00-0f2a-11eb-8740-47d22daeebcb.jpeg)

Thank you.

**Comment by freescout-helpdesk** [comment]
Implemented in Workflows Module 1.0.15

By default Workflow user’s name is “Workflow”. If you want to change it, add the following parameter to the .env file and clear the cache:

WORKFLOWS_USER_FULL_NAME=”Robot”
