### ISSUE TITLE
Whoops, looks like something went wrong. After last update.

### ISSUE THREAD

**Issue by godepic90** [freescout-helpdesk/freescout#816]
Hi,

I updated my freescout a few minutes ago and i get this message: Whoops, looks like something went wrong.

What can be wrong?

I have checked the log files but there are no error's in the log files.

I hope that there is a fix for this.

And where can i find the key to try the /tools to try to fix the error. App Key (from .env file)

**Comment by SFFLAB** [comment]
The same has happened to us. Very, very bad as our support desk is now down until we get assistance. Please advise @freescout-helpdesk!

**Comment by SFFLAB** [comment]
Update: This occurred for us after attempting to install some modules. I was able to resolve by deleting these modules via SSH, and then clearing the app cache.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/releases/tag/1.6.2

**Comment by SFFLAB** [comment]
I spoke too soon - looks like the app reverts to the error message about an hour after fixing this. Clearing the app cache fixes it but only temporarily.

@freescout-helpdesk I'll create a separate issue for this
