### ISSUE TITLE
Service Level Agreements - SLAs

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#817]
Hey guys,
I don't have the needed knowledge to develop the modules or make changes in code so once I see something interesting I'll post here to make a suggestion and make this software even better.
I saw this feature in another software and found that great and very useful.

Service Level Agreements time-related responses, lets say customers should always get a response from our staff in no more than  24 hour, then the software would send a notification alerting of that violation.

Could be response time between the creation of a ticket and the first reaction of an agent, update time between a customer's request and an agent's reaction and solution time between creation and closing a ticket.

**Comment by freescout-helpdesk** [comment]
You can use Workflows module.

**Comment by diguinho2018** [comment]
Great idea, I just tried that and I managed to configure the "Condition" to "WAiting Since" but when I went to "Actions" the "Send Email Notification" do not allow me to customize the message to the current assignee.
If I use the "Forward" option it will ask me to insert the "To" email but that would be the "Current Assignee" email that is variable, can we use variables in these section, "To", "bcc", "cc"?

**Comment by freescout-helpdesk** [comment]
You can add a note.
