### ISSUE TITLE
Error message when trying to close or reassign emails in FreeScout

### ISSUE THREAD

**Issue by DavidJuicyBike** [freescout-helpdesk/freescout#819]
Hi,

Hoping someone can advise and help me solve what is probably a simple problem, please!
We have started using Freescout as a shared mailbox recently and it has been great, however, in the last few days when I try to change the status of or reassign an email I am getting the following message.
 (Error occurred please check your internet connection and try again)
Also, a colleague has randomly been unable to log in to hi FS and just gets a (whoops something went wrong) To my knowledge we haven't changed any settings so any insight on how to fix this so we can use it as before would be hugely appreciated.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
