### ISSUE TITLE
Fixing queue:work and Last run: ?

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#824]
Hello guys,
I saw a lot of threads about this error, when `queue:work` doesn't work as it should run and show something like this `Last run: ? Last successful run: ? Try to clear cache to force command to start.`

Some Threads that are related to this issue:
#384, #700, #692, #661, #621, #578, #545, #403, #770 

So i did some digging and found a solution, as I'm not a developer I don't know if that is the right one but it works...
The ideal solution is to install `supervisor` and let it do the work, handling stuck jobs and all, but as I'm on a shared hosting I had to solve this issue by another way!

Firstly I tried to set this Cron Job ` /usr/local/bin/ea-php70 /home1/XXXXXX/public_html/helpdesk/artisan queue:work --stop-when-empty >/dev/null 2>&1 ` but that didn't do the trick as it showed an error `The "stop-when-empty" option does not exist.` while running the cron. 

Then after more digging I came with these.
In CPanel I created this Cron Job:
` /usr/local/bin/ea-php70 /home1/XXXXXX/public_html/helpdesk/artisan schedule:run >/dev/null 2>&1 `

Then I created this one:
` /usr/local/bin/ea-php70 /home1/XXXXXX/public_html/helpdesk/artisan queue:work >/dev/null 2>&1 `

And this one to restart the queue hourly:
` /usr/local/bin/ea-php70 /home1/XXXXXX/public_html/helpdesk/artisan queue:restart >/dev/null 2>&1 `

They are running for a about a day and everything is ok.
These Cron Jobs will run sometimes the same task but won't get stuck.

My suggestion as already suggested in another thread is to remove the `queue:work` from schedule and run as a separate one, and update the documentation accordingly.

@freescout-helpdesk, if this solution is not right please correct me and if needed help us in this situation, as this is a central part of FreeScout and a lot of people are having issues.

**Comment by centralplexus** [comment]
This worked for me, thanks!

**Comment by freescout-helpdesk** [comment]
Info added to the Installation Guide: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#queuework-is-not-running
