### ISSUE TITLE
when forwarding to multiple mail adresse it will only send to the last one

### ISSUE THREAD

**Issue by nerdalertdk** [freescout-helpdesk/freescout#825]
Hi

If you forward a case to multiple mail addresses, it will only send to the last mail

![image](https://user-images.githubusercontent.com/3426495/96701811-4ee8d700-1391-11eb-95d5-fd3de4ba4ee2.png)

Only test2@test.com will get the mail 

App Version | 1.6.2

**Comment by lakym86** [comment]
and autocomplete only works on first input

**Comment by freescout-helpdesk** [comment]
For forwarding To field should be limited to one email.

**Comment by tiredofit** [comment]
One field seemed logical to me, until I actually saw 100 users utilize the system, and from what I can see, many people regularly forward to multiple people for notification purposes (yes I know, defeats the purpose of Freescout and shared mailboxes) entirely. We should be able to forward and send to as many as the user has input to accommodate for all use cases. I would try to look into if I could, yet I do not have the skills.

**Comment by nerdalertdk** [comment]
@tiredofit i agree they use it the same way as they use outlook, there you can send to multiple in the to field, but I can see how it would not work here because of the one mail one case design

**Comment by freescout-helpdesk** [comment]
Forwarding to multiple recipients is implemented (in `master` branch).

**Comment by lakym86** [comment]
and mailbox name on forwarded mail #786 - is connected to this topic!  solved or?
