### ISSUE TITLE
issue with connection settings and sending replies

### ISSUE THREAD

**Issue by adamsewell** [freescout-helpdesk/freescout#828]
I'm having some issues with getting the outgoing mail settings set for my mailbox. When I save the settings under "Connection Settings", I get the following error "is not available on port. Make sure that address is correct and that outgoing port on YOUR server is open". I'm trying to use the sendmail option as the server is setup to use a email service. Strangely enough, under Settings -> Mail Settings, everything works fine. 

<img width="925" alt="Image 2020-10-24 at 9 17 26 AM" src="https://user-images.githubusercontent.com/911426/97082815-71216580-15da-11eb-9dd1-96276925ef7f.png">

**Comment by freescout-helpdesk** [comment]
Fixed in master branch.

Copy this file https://raw.githubusercontent.com/freescout-helpdesk/freescout/master/app/Http/Controllers/MailboxesController.php to /app/Http/Controllers/MailboxesController.php

**Comment by adamsewell** [comment]
Seems to have fixed it again. Thanks!
