### ISSUE TITLE
Section 8 of Wiki Installation guide should mention editing the .env file

### ISSUE THREAD

**Issue by tareko** [freescout-helpdesk/freescout#83]
The application does not start and fails with:

`Please copy .env.example file to .env and reload this page.`

To those not familiar with this environment, it's not obvious what to do. There should be explicit instructions to edit the `.env.example` file and rename it to `.env`

**Comment by tareko** [comment]
Just going through the installation script. It appears to be a bug in the programming that it needs the .env to run the installation script, rather than missing documentation.

**Comment by freescout-helpdesk** [comment]
Thanks. Mentioned this in the instruction: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server
