### ISSUE TITLE
Install Freescout on OpenLitespeed

### ISSUE THREAD

**Issue by wauwturrr** [freescout-helpdesk/freescout#830]
Is it possible to use Freescout on a OpenLitespeed server with DirectAdmin?
I can't seem to get it configured right now.

**Comment by freescout-helpdesk** [comment]
We don't know.

**Comment by TimoStramann** [comment]
It works with LiteSpeed on cPanel so I don't see any reason why it should not work with DirectAdmin.

**Comment by wauwturrr** [comment]
And a Apache DirectAdmin enviroment?

**Comment by wauwturrr** [comment]
> It works with LiteSpeed on cPanel so I don't see any reason why it should not work with DirectAdmin.

What steps did you use to make it work? Can you tell?

**Comment by TimoStramann** [comment]
> > It works with LiteSpeed on cPanel so I don't see any reason why it should not work with DirectAdmin.
> 
> What steps did you use to make it work? Can you tell?

I downloaded freescout from freescout.net and uploaded/unzipped it using the web-filemanager. After this navigated to install path and the installation run through without problems.

**Comment by wauwturrr** [comment]
> I downloaded freescout from freescout.net and uploaded/unzipped it using the web-filemanager. After this navigated to install path and the installation run through without problems.

You didn't do any changes within configs etc?

**Comment by TimoStramann** [comment]
The web-installer is doing this for you. Just make sure you have the folder permissions correct as in install instructions.

**Comment by wauwturrr** [comment]
> The web-installer is doing this for you. Just make sure you have the folder permissions correct as in install instructions.

When i do that, it's broken; support.hobbelhost.nl
Do i need a specific thing to change?

**Comment by TimoStramann** [comment]
> When i do that, it's broken; support.hobbelhost.nl
> Do i need a specific thing to change?

What error message do you get in your log when visiting support.hobbelhost.nl/public/ ?

**Comment by wauwturrr** [comment]
Nothing.. the log is empty..

**Comment by wauwturrr** [comment]
On the page itself getting a 500 error, with no further info

**Comment by TimoStramann** [comment]
> On the page itself getting a 500 error, with no further info

Enable error reporting in /config/app.php (APP_DEBUG).

**Comment by wauwturrr** [comment]
It's different now; http://support.hobbelhost.nl/public/

**Comment by TimoStramann** [comment]
Which PHP Version?

**Comment by wauwturrr** [comment]
It's on PHP7.3 with IMAP enabled yes

**Comment by wauwturrr** [comment]
Got it working, THANKS!

**Comment by TimoStramann** [comment]
Let us know what you had to do to solve it so others can benefit too?

**Comment by wauwturrr** [comment]
Well, nothing honestly? Only rebuilded PHP7.3 with IMAP within CustomBuild2.0
