### ISSUE TITLE
Building from Master fails

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#831]
Additionally - tag 1.6.3 - 

It seems that I'm unable to build the [docker image](https://github.com/tiredofit/docker-freescout) with the latest update inside of it. My steps are rather simple, but it seems to be failing at the `composer install` section. Any advice?

````bash
Generating optimized autoload files
Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. Skipping.
Class Faker\Provider\uk_Ua\Payment located in ./vendor/fzaninotto/faker/src/Faker/Provider/uk_UA/Payment.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PackageManifest.php line 120:
                         
  Undefined index: name  
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
````

**Comment by tiredofit** [comment]
Problem is related to composer 2.x series which was released 2 days ago - Anyone attempting to build from master branch must use Composer 1.x (1.10.16 is latest). Will leave open until tree maintainer can see and close at their discretion if they feel like it needs to be noted in install guide.

**Comment by freescout-helpdesk** [comment]
Thanks
