### ISSUE TITLE
FreeScout Beacon

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#832]
Hey guys!

Here I come with a suggestion:
Would be great to see a "FreeScout Beacon" like the one in HelpScout.
https://developer.helpscout.com/beacon-2/

Right now it would, once clicked, show one form (with custom fields) to send e-mail to mailbox, and after the implementation of chat and KB it would display those options too. 

We could have an option to create multiple beacons with custom background, icon and fields. Also we could have an option to configure in what pages (using URL) each beacon should appear, everything via FreeScout helpdesk admin area.

Maybe a separate paid module?

Thanks.

**Comment by freescout-helpdesk** [comment]
Maybe in the future, not nearest.
