### ISSUE TITLE
Customization Module

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#833]
Hello guys!

Here is one suggestion for a feature to be included in the "[Customization Module](https://freescout.net/module/customization/)".
Would be great to see a box called "Custom CSS" where we could add some custom CSS to be applied all over the dashboard.

Thank you.

**Comment by centralplexus** [comment]
+1

**Comment by freescout-helpdesk** [comment]
Maybe it will be added in the future.

**Comment by joris85** [comment]
+1
Or just some location in the ftp with custom.css :-)

**Comment by freescout-helpdesk** [comment]
Custom CSS option has been added in Customization Module v1.0.3

![freescout-help-desk-custom-css](https://user-images.githubusercontent.com/40499291/101012562-12a1bc80-3574-11eb-90d8-f670458a3562.png)

**Comment by centralplexus** [comment]
Works great! Is it possible to have the css also applied on the end user portal?

**Comment by freescout-helpdesk** [comment]
Not yet.

**Comment by freescout-helpdesk** [comment]
> Works great! Is it possible to have the css also applied on the end user portal?

Possible in the End-User Portal Module v1.0.5
