### ISSUE TITLE
Freescout version 1.6.3 'Database Migration Error' issue while installation

### ISSUE THREAD

**Issue by prbt2016** [freescout-helpdesk/freescout#834]
Hello,

I  was trying to install Freescout version 1.6.3 on Centos Linux with PHP 7, MYSQL 5.5, Apache 2.2. 

I face the following issue while doing the same. After entering all the required details the following error is thrown i.e:

Database Migration Error

Error occured migrating database:

`SQLSTATE[HY000]: General error: 1193 Unknown system variable 'sql_require_primary_key' (SQL: SET SESSION sql_require_primary_key=0)` 

![freescout](https://user-images.githubusercontent.com/17871448/97271916-3841f480-1857-11eb-934d-81f6ed733467.jpg)

Could you please fix this issue?

**Comment by freescout-helpdesk** [comment]
We will fix it.

**Comment by prbt2016** [comment]
Okay thanks.

**Comment by freescout-helpdesk** [comment]
Fixed in the latest version of the FreeScout.
