### ISSUE TITLE
Force Modules Update

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#835]
Hello guys!

I noticed that there are modules with new version but they are not appearing in my Modules' Dashboard.
Workflows, Customization didn't show up as new version available, is there any way to force that check?

Thanks

**Comment by freescout-helpdesk** [comment]
It means not everything is ok with background jobs or file permissions.

Try to clear the cache.

**Comment by diguinho2018** [comment]
Yesterday I updated one module successfully, I don't remember which one, but Workflows, Customization didn't show up as new version available.
Also the system updates are ok, they show up and I just updated to 1.6.4.
I manually checked all folder permissions listed in `/system/status` and set to 775, then cleared the cache but the updates didn't show up.

**Comment by freescout-helpdesk** [comment]
Fixed. Should be fine now.

**Comment by diguinho2018** [comment]
Yeah, thank you, everything updated!
