### ISSUE TITLE
Fatal error after update

### ISSUE THREAD

**Issue by centralplexus** [freescout-helpdesk/freescout#836]
Fatal error: Uncaught ReflectionException: Class config does not exist in /x/x/x/tickets.x.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:752

How would I go about restoring that to a working version now? I'm new to this and did not truly expect this to happen tbh.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by centralplexus** [comment]
Hi there, thanks but none of this works for me, not even manual FTP restore on this or the two versions before that.
The web based updater throws an error:

In Loader.php line 262:
                                                                 
  Dotenv values containing spaces must be surrounded by quotes.  
                                                                 

Restoring over FTP did not help either, not this version nor the last two.

**Comment by centralplexus** [comment]
Found the culprit: The footer I entered had a space so it needs double quotes in .env

**Comment by freescout-helpdesk** [comment]
It will be fixed in the next release of FreeScout.
