### ISSUE TITLE
[REQUEST] 2FA Module: Display Secret Key

### ISSUE THREAD

**Issue by centralplexus** [freescout-helpdesk/freescout#837]
Hi there,

I'm using KeepassXC for my 2FA codes and it works but I needed to read the key from the QR code manually and then put it into Keepass. Do you think you could display the key above or below the qr code so one can copy it more easily?

Kind regards,
CPX

**Comment by freescout-helpdesk** [comment]
It should be possible.

**Comment by freescout-helpdesk** [comment]
Implemented in 2FA Module 1.0.1

**Comment by centralplexus** [comment]
Very cool, thanks!
