### ISSUE TITLE
Issues with Nginx Reverse Proxy

### ISSUE THREAD

**Issue by Monklite** [freescout-helpdesk/freescout#838]
I'm using the default Nginx configuration for FreeScout (the one in the install instructions) and I can access it through the IP address; however, when I use my reverse proxy, the login page has a messed up style sheet and the wildcard cert doesn't apply. 

When I login, I get an error saying "This page expired due to inactivity". If it helps, the reverse proxy entry for my instance is below:

```
# freescout subdomain
server {
    server_name                 help.example.com;

    access_log                  /var/log/nginx/help.example.com/access.log;
    error_log                   /var/log/nginx/help.example.com/error.log;

    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass              http://192.168.1.134;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = help.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name                 help.example.com;
    return 404;                 # managed by Certbot
}
```

Here is also an error from the logs.
```
2020/10/27 23:54:50 [error] 29966#29966: *2317 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.86.202, server: help.example.com, request: "GET / HTTP/1.1", upstream:
 "https://192.168.86.134:443/", host: "help.example.com"
```

**Comment by adamsewell** [comment]
According to your error logs, it can't connect to the backend. What's at 192.168.1.134? Also why are you using a reverse proxy when you can just install it on the nginx server?

**Comment by Monklite** [comment]
192.168.86.134 is the FreeScout host. The error log is from the reverse proxy node at 192.168.86.129  

As for why I use it, I use it because I host a variety of services on my domain such as nextcloud, proxmox, dokuwiki, etc and all of them are accessible through subdomains. It allows me to easily manage these subdomains in regards to SSL Certs. To update the wildcard cert, I just run certbot on the reverse proxy host.

**Comment by tiredofit** [comment]
From your proxy server `curl -I http://192.168.1.134` and see what your output is. As @adamsewell wrote, it seems to be a networking issue not a freescout issue.

**Comment by Monklite** [comment]
> From your proxy server `curl -I http://192.168.1.134` and see what your output is. As @adamsewell wrote, it seems to be a networking issue not a freescout issue.

```
HTTP/1.1 302 Found
Server: nginx/1.18.0 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Cache-Control: max-age=0, must-revalidate, no-cache, no-store, private
Date: Mon, 02 Nov 2020 15:54:24 GMT
Location: http://192.168.1.134/login
Pragma: no-cache
Set-Cookie: XSRF-TOKEN=REDACTED; expires=Mon, 02-Nov-2020 17:54:24 GMT; Max-Age=7200; path=/
Set-Cookie: laravel_session=REDACTED; expires=Mon, 02-Nov-2020 17:54:24 GMT; Max-Age=7200; path=/; httponly
```

**Comment by tiredofit** [comment]
Try `APP_FORCE_HTTPS=true` in your .env and then execute `artisan config:clear` in the root of Freescout.

**Comment by Monklite** [comment]
> Try `APP_FORCE_HTTPS=true` in your .env and then execute `artisan config:clear` in the root of Freescout.

Success! I feel so silly :( thank you so much though :+1:
