### ISSUE TITLE
Authorisation Across modules

### ISSUE THREAD

**Issue by cloudties** [freescout-helpdesk/freescout#840]
Do we have the capability to enable autorisation across different modules for users in the system?

**Comment by freescout-helpdesk** [comment]
All module are activated for all users by default.

**Comment by cloudties** [comment]
Hi, 

I have raised a issue asking for this improvement . Thanks for the
details and will you be enabling this capability  in the future? .  

Happy to contibute installation related steps for CentOs in the interest
of the community . Please let me know the forum fot the same  

Saju  

On 2020-10-28 17:19, FreeScout wrote:

> All module are activated for all users by default. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/freescout-helpdesk/freescout/issues/840#issuecomment-717881618
[2]

**Comment by freescout-helpdesk** [comment]
No plans for now.

**Comment by tiredofit** [comment]
@cloudties I'm just trying to understand your request further. Do you mean, that using a paid module (say the Workflow Module or Tags module) you want to be able to limit users who are able to access that option? For example, one user should see the Workflow module yet some others shouldn't? Theoretically it should be possible to do this sort of thing (Right now it is a System wide option for Tags and Folders) per user based on the work that @Injektion submitted for "Manager" level support. It would be up to @freescout-helpdesk to update the paid modules to provide this level of granularity, which doesn't seem well received at this time. 

If I am not understanding your request fully, please let me know.

**Comment by cloudties** [comment]
You got it right . With a permission and privileges if we could enable  the module access and visibility across the system and subsequetly use user roles to  manage them . This shall help in building different modules and assign user roles could access the same . By this we can build independent modules and bring in better modulating

**Comment by tiredofit** [comment]
I follow you @cloudties. I do see it beneficial as well too. For example I wouldn't like to let everyone mess with the Workflow module, only a "manager" or someone that we trust as they could wreck some serious havoc not knowing what they were doing, but also wouldn't want to force an IT department to get in the way of an install that has multiple mailboxes to manage their workflow. I don't know enough about the paid modules in how they work, although you could extend the work that was done in #756 to see if it would fire for your custom module and submit it as a PR.

**Comment by XtomtomX** [comment]
I also agree with @cloudties. We haven in our organization the exactly same problem. We want to enable the shared mailbox "owners" to manage their workflows without contacting the IT for each change (without giving them the admin role).

**Comment by freescout-helpdesk** [comment]
No plans to implement for now.

**Comment by freescout-helpdesk** [comment]
> Allow to set User Permissions per User (in User Profile > Permissions)

https://github.com/freescout-helpdesk/freescout/releases/tag/1.6.11

To some extent allows to manage access to modules.
