### ISSUE TITLE
[ticket emails] email formatting is stripped when viewing in freescout vs show original

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#841]
When an email arrives and we view the original message it shows the tables and other areas formatted with inline CSS
However
When viewing in freescout as a ticket, the formatting is all removed

Is this by design?

It looks like all inline css is removed, ie style=""

**Comment by freescout-helpdesk** [comment]
Yes. You can view original email like this:

![2020-10-28_16-45-10](https://user-images.githubusercontent.com/40499291/97444267-00ad7800-193d-11eb-9069-0d14f0444320.png)

**Comment by raramuridesign** [comment]
I realize this is there, but why is it stripped in the main view?
M

**Comment by freescout-helpdesk** [comment]
Not to break FreeScout layout.

**Comment by raramuridesign** [comment]
Ok, thanks for sharing.

**Comment by sv2kgl** [comment]
Hello. Sorry for reopening the issue. Is there an option available to turn all mails to original permanently?
