### ISSUE TITLE
Advanced search options

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#844]
Hello,

Is it possible to advanced searches using boolean operators etc especially to not include keywords?

i.e.
- tag:important AND NOT tag:sales
- customer:support@company.com AND (tag:sla OR tag:important)

**Comment by freescout-helpdesk** [comment]
No for now.

**Comment by joris85** [comment]
Oh plus one! 
Search would be great to make more flexible!

**Comment by colegatron** [comment]
Is is possible, at least, negate a search? without including other OR/AND,etc 
just search : NOT tag:thistag

**Comment by freescout-helpdesk** [comment]
Closed as out of scope.
