### ISSUE TITLE
How to disable the LDAP module?

### ISSUE THREAD

**Issue by marcusquinn** [freescout-helpdesk/freescout#847]
Hey,

After enabling the LDAP module I can't login.

Tried running `sudo -E -u www-data php artisan module:disable <modulename>` and guessing various names for `<modulename>`, including just `ldap` but all result in `In Repository.php line 481: Module [ldap] does not exist!` errors.

Any ideas what the LDAP module identifier is please?

**Comment by freescout-helpdesk** [comment]
Remove the module from /Modules folder and clear app cache.
