### ISSUE TITLE
[Feature Request] Schedule Replies

### ISSUE THREAD

**Issue by adamsewell** [freescout-helpdesk/freescout#848]
I often reply to tickets on weekends but I don't want clients to think I'm working for them on weekends, in any case, I'd love the ability to schedule a ticket to send out at a specific time. Similar to the way Gmail and Office365 have delayed send.

**Comment by joris85** [comment]
Good idea!

**Comment by davask** [comment]
this has been adressed by the Send later module https://freescout.net/module/send-later/
