### ISSUE TITLE
Installation guide results in empty database and failed installation

### ISSUE THREAD

**Issue by tareko** [freescout-helpdesk/freescout#85]
Hello all,

Running this on a stock Ubuntu 16.04 from DigitalOcean. At the end of the guide, I have the following:

```
QLSTATE[42S02]: Base table or view not found: 1146 Table 'freescout.users' doesn't exist (SQL: select * from `users` where `email` = tareko@fakemail.org limit 1)
```

In checking the Mysql database, there is no database there. Not sure how to properly create the various tables / db and I don't see any SQL files like with old school apps. How do I proceed from here?

tarek : )

**Comment by freescout-helpdesk** [comment]
Ok. It has been mentioned in the instruction: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#6-configuring-web-server
