### ISSUE TITLE
End-User Portal

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#852]
Which features are needed within the End-User Portal?

**Comment by adamsewell** [comment]
The ability for clients to place tickets but also the ability to see their own tickets. It would also be nice if we could designate a person or multiple people to be able to see all tickets from a particular domain. So say ceo@domain.com could see all tickets that are associated with the domain.com domain.

**Comment by fvdm** [comment]
- View, reply and search their own tickets
- Create/reopen tickets
- Manage their profile basics: name, email addresses

**Comment by digipigeon** [comment]
An idea I like would be to have [OPTIONAL] email based security.

We don't need yet another email / password (hash) database do we, just for a small control panel.

How about send an authentication email with a magic link. They can stay logged in for X minutes / days (15 mins - 30 days).

X should be able to be capped by an admin setting or by an option when to login (remember me).

Anything more elaborate could be delivered by an API.

**Comment by diguinho2018** [comment]
Every ticket should have its own link then would be great to have a variable like `{{ticket_link}}` to insert in workflow, emails...

> 
> 
>     * View, reply and search their own tickets
> 
>     * Create, close and reopen their tickets
> 
>     * Manage their profile basics: name, password, 2FA, email addresses

Agreed!

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/end-user-portal/

**Comment by markhn** [comment]
the end-user portal is very simple we need some sort of option to customize it 
Also, the link is way too long we need an option to customize the link as well

**Comment by vikasprogrammer** [comment]
Custom Fields Integration. (like entering purchase code or product name etc).

**Comment by vikasprogrammer** [comment]
Tags Integration, choosing from a list of tags.

**Comment by freescout-helpdesk** [comment]
> Also, the link is way too long we need an option to customize the link as well

The link has been shortened in End-User Portal v1.0.1

**Comment by markhn** [comment]
the link works only for agents

**Comment by freescout-helpdesk** [comment]
> the link works only for agents, I provided the support link to one of my customers, and the page returned with an error message

If you are using Reports module, make sure to update it to the latest version.

**Comment by markhn** [comment]
> > the link works only for agents, I provided the support link to one of my customers, and the page returned with an error message
> 
> If you are using Reports module, make sure to update it to the latest version.

Solved Thank you

**Comment by qsvch** [comment]
It would be nice if the function of the form would also be possible for the website in form of a floating button / form. So finally a code that can be inserted into any website and provides the form there.

**Comment by freescout-helpdesk** [comment]
> It would be nice if the function of the form would also be possible for the website in form of a floating button / form. So finally a code that can be inserted into any website and provides the form there.

Contact form widget is available in the End-User Portal Module v1.0.2 https://freescout.net/module/end-user-portal/

**Comment by qsvch** [comment]
Wow... great! Thank you for the fast implementation! We tested the thing right away and it works fine with all devices and screen sizes!

**Comment by markhn** [comment]
Hello,
I have a few ideas
option to disable and enable attachments
option to select which formats a costumer will be able to attach
the widget is working awesome, it will be great to add the form to the contact page example: https://example.com/contact
i think an iframe code will do it!

**Comment by diguinho2018** [comment]
> 
> 
> > It would be nice if the function of the form would also be possible for the website in form of a floating button / form. So finally a code that can be inserted into any website and provides the form there.
> 
> Contact form widget is available in the End-User Portal Module v1.0.2 https://freescout.net/module/end-user-portal/

Great one @freescout-helpdesk.
Would be great to be able to customize the widget's fields.

**Comment by freescout-helpdesk** [comment]
End-User Portal module will evolve with time.

**Comment by ssthormess** [comment]
It is possible that sometime we can get custom domains for this feature using a CNAME for each Brand?

**Comment by vikasprogrammer** [comment]
We can do it as part of custom development at scoutdevs.com

**Comment by ASTIN-UA** [comment]
Hi/ What about user authentifiction by password? And editor like on agent panel?

**Comment by localmarketingpros** [comment]
Custom Domain per mailbox & End-User Portal for true white-label customization....just like the knwledgebase
