### ISSUE TITLE
Attachments thread_id integer overflow

### ISSUE THREAD

**Issue by digipigeon** [freescout-helpdesk/freescout#853]
Hi,

Whilst migrating from helpscout and I have noticed the following

Thread Table
```
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
```
Foreign Key in Attachment Table
```
  `thread_id` int(11) NULL DEFAULT NULL,
```

Note the lack of `UNSIGNED`. Of course when imported all files over 2147483647 were capped at 2147483647.

I thought that the correct course of action would be to manually adjust the `attachments` table to `UNSIGNED` however the underlying system somehow automatically compensates the overflow and maps this in form of

pseudo
```
attachment.thread_id = table.id-4294967296
```
meaning that *freescout currently prefers negative values for anything that overflows*.

After making the field `UNSIGNED`, importing the data from helpscout, I used the following script to make my data compatible.

```
UPDATE attachments SET thread_id = thread_id - 4294967296 WHERE thread_id > 4294967296;
```

I am documenting all of this as a **hack / workaround**.

I believe that the `thread.id` and `attachments.thread_id` should have the same datatype moving forward to allow good consistency.

Thanks

**Comment by freescout-helpdesk** [comment]
Thanks. We will check it.
And how are you migrating from helpscout? via custom script?

**Comment by digipigeon** [comment]
Hi, Yes custom script written in NodeJS. I am considering publishing this after I have finished with it, however it may be an Incomplete Solution for anyone else wanting to use it, may need some tidying up.
