### ISSUE TITLE
Workflows: forwarding error on "Move to Mailbox"

### ISSUE THREAD

**Issue by XtomtomX** [freescout-helpdesk/freescout#856]
Hi, we encountered an error by setting up the required workflows for our office. It would be nice if you could look into the described issue.

**Setup:**
- System with mailbox A & B
- User X has only access to mailbox A 

Manual workflow created at mailbox A with action "Move to Mailbox": B (workflow is required due to users do not see the other mailboxes on the server at the option "move" if they are not part of the mailboxes).

**Expected behaviour:** User X can execute the manual workflow to move a ticket to mailbox B without getting an error. Due to no permission on the target mailbox the user should stay in his mailbox without getting forwarded (like in the mobile app).

**Actual behaviour:** User X can execute the manual workflow but gets forwarded to an error page ("403 Forbidden").

Regards, Thomas

**Comment by freescout-helpdesk** [comment]
We will check.

Also keep in mind that users can move conversations to any mailbox by entering it's email address in the "Move Conversation" dialog.

**Comment by XtomtomX** [comment]
Thank you very much for checking the routing! 👍 
Thanks a lot in advance!

**Comment by freescout-helpdesk** [comment]
Fixed in the Workflows Module 1.0.16
