### ISSUE TITLE
Woocommerce Module is Great But Should be Per Mailbox

### ISSUE THREAD

**Issue by oxjemly** [freescout-helpdesk/freescout#857]
I love the new Woocommercce Module - it is extremely useful.

But I have a couple of different woocommerce installations and run separate support mailboxes for each domain.

It would be great if the woocommerce Module could be set at the mailbox level, so that I could get integration for all. RIght now I can only use it for one mailbox as it is configred at the master account level.

**Comment by freescout-helpdesk** [comment]
We will check what can be done.

**Comment by freescout-helpdesk** [comment]
If someone is willing feel free to implement a per mailbox configuration.

**Comment by freescout-helpdesk** [comment]
In WooCommerce Module v1.0.1 per mailbox configuration is supported.
