### ISSUE TITLE
system page not being updated with crontab execution (I've read other troubleshooting's solutions )

### ISSUE THREAD

**Issue by colegatron** [freescout-helpdesk/freescout#858]
System status still shows queue:work not working and resquesting clear cache to fix it. Clearing cache don't work.

_Using Docker image the crontab installed under the root user and it is being executed (I get emails on the mailbox)._

No errors on system logs or app logs.
Issue is not related to system, since it is using the docker image in the docker-compose repo's example.

Installed crontab seems ok:
```
# cat /var/spool/cron/crontabs/root 
* * * * * sudo -u nginx LD_PRELOAD=/usr/lib/preloadable_libiconv.so php /www/html/artisan schedule:run >> /dev/null 2>&1
59 23 * * * logrotate -f /etc/logrotate.d/* >/dev/null 2>&1
```

Running the command manually seems to work too:
```
bash-5.0# sudo -u nginx LD_PRELOAD=/usr/lib/preloadable_libiconv.so php /www/html/artisan schedule:run
Running scheduled command: '/usr/bin/php7' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' freescout:fetch-emails > '/www/html/storage/logs/fetch-emails.log' 2>&1
bash-5.0# 
```
Message still showing on system status page:
```
queue:work | Last run: ? Last successful run: ? Try to clear cache to force command to start.
```

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#queuework-is-not-running

**Comment by colegatron** [comment]
Everything seems to work properly, but the queue:work error _"Last run: ? Last successful run: ? Try to clear cache to force command to start."_ stills shows up.

As you can see both commands, the one originally in the container image root's crontab and the troubleshooting's section one: 
```
bash-5.0# cat /var/spool/cron/crontabs/root 
* * * * * sudo -u nginx LD_PRELOAD=/usr/lib/preloadable_libiconv.so php /www/html/artisan schedule:run >> /dev/null 2>&1
* * * * * php /var/www/html/artisan queue:work --queue='emails,default' --sleep=5 --tries=1 >> /dev/null 2>&1
59 23 * * * logrotate -f /etc/logrotate.d/* >/dev/null 2>&1
```
They are under the root's user crontab, since the www-data user does not exists. I've tried with the nginx user crontab, but it still is shown. 
Is there any other place I should look into?

**Comment by colegatron** [comment]
Updated the command from "php /var/www/* to "php /www/*". Inside container the path is different.
Despite that, when I run manually the command it seems to hung. 
Guess it just reading the queue but the message is stille there _"Last run: ? Last successful run: ? Try to clear cache to force command to start."_

**Comment by colegatron** [comment]
Still showing the queue:work not displaying last execution, but everything seems working properly.

@freescout-helpdesk there is anything else I can check?

**Comment by tiredofit** [comment]
@colegatron I'm the maintainer behind the Docker Image and experience the same issues, and have not been able to find a resolution, yet assure you that it does indeed functioning. I can implement an alternative cron function if you would like to execute additional commands. I am considering dropping the cron functionality and turning it into a service so that only one process can execute at a time anyways. Let me know if you'd like to test some of this stuff.

**Comment by colegatron** [comment]
Hi Dave,
I appreciate your answer, I thought it was only me. 
Also checked and you are correct, it is functioning, so I guess there is some error somewhere that prevents to show the right information.
Instead implement alternative workarounds (which can led you to another errors/bugs) I would bet for finding the problem causing the issue. My experience is they are indeed harder to implement and maintain than solve the real problem :-)

It has been long time since I wrote my last php app, never used laravel, and I've no time to dig on the source code, but spent few minutes and found this:

```
- SystemController.php line ~152:
    $option_name = str_replace('freescout_', '', preg_replace('/[^a-zA-Z0-9]/', '_', $command_name));                                                 
and below:    
    $last_run = Option::get($option_name.'_last_run'); 
```

$last_run is empty for command queue:work, meaning the Option::set(freescout_work, value) is not run (or failed) wherever it is expected to be run and in turn that makes the code display the wrong content.

FYI my crontab right now includes:
* * * * * sudo -u nginx LD_PRELOAD=/usr/lib/preloadable_libiconv.so php /www/html/artisan schedule:run >> /dev/null 2>&1
59 23 * * * logrotate -f /etc/logrotate.d/* >/dev/null 2>&1

AFAIU, "schedule:run" runs "queue:work" itself

**Comment by freescout-helpdesk** [comment]
Any progress?

**Comment by colegatron** [comment]
Ey, this was left in my drafts without send time ago...


Hi Dave,
I appreciate your answer, I thought it was only me. Also checked and you
are correct, it is functioning, so I guess there is some error somewhere
that prevents to show the right information.
Instead implement alternative workarounds (which can led you to another
errors/bugs) I would bet for finding the problem causing the issue. My
experience is they are indeed harder to implement and maintain than solve
the real problem :-)

It has been long time since I wrote my last php app, never used laravel,
and I've much time to dig on the source code, but spent few minutes and
found this:
```
- SystemController.php:
            $option_name = str_replace('freescout_', '',
preg_replace('/[^a-zA-Z0-9]/', '_', $command_name));


            [...]
            $last_run = Option::get($option_name.'_last_run');



```
$last_run is empty for command queue:work, meaning the
Option::set(freescout_work, value) is not run (or failed) wherever it is
expected to be run.
That makes the following code display the wrong content.

**Comment by bencgreen** [comment]
Could this be related to S6 / running the cron in the foreground?  I have just switched to use @tiredofit's docker image, and have this issue - yet in the native installation it was fine.  The only difference as far as I can tell, is that on the host machine the cron runs in the background.

**Comment by tiredofit** [comment]
Shouldn't make a difference if its in foreground or background, the commands still function but don't ever seem to finish gracefully. 

I am going to put another image up for those affected `tiredofit/frescout:alt_scheduler` This is Freescout `1.6.11` or a a variant of my `tiredofit/freescout:1.11.2` tag.  It removes the cron dependency and runs `sudo -u nginx LD_PRELOAD=/usr/lib/preloadable_libiconv.so php /www/html/artisan schedule:run` via a hand rolled function. Benefits to this one is that if your schedule takes more than one minute, this alternate command will only allow one to run at any given time.

Please let me know if this makes anything better.

**Comment by bencgreen** [comment]
My thought was whether the S6 supervisor stops the process from ending gracefully?  The problem is clearly not with Freescout itself as that runs perfectly when not inside a container.  For example, when I run `top` inside the container, `schedule:run` is there permanently - which is not the case on the host machine when installed natively.

**Comment by tiredofit** [comment]
The cron tab reads as "run every minute" so I did something similar with the S6 process.. "wait a minute" and then "respawn".

You can see that if you set `CONTAINER_LOG_LEVEL=DEBUG` as an environment variable there is a notice that tells when the scheduler is starting and has ended. 

On your "non Docker installation is it an exact replica of your Docker instalation? Ie amount of mailboxes, usage? I see that our process is running for long periods of time but we are processing 50 mailboxes with a couple hundred users.

**Comment by bencgreen** [comment]
Yes totally identical. Even a copy of the database. 

That's my point really - the S6 respawning. I don't think that's necessary and could be stopping the Freescout scheduler from ending gracefully. What happens if you disable all that and just let the cron / Freescout handle the tasks as they would in a non Docker installation?

**Comment by tiredofit** [comment]
That's what they did originally, really, it was just a one line in the crontab to fire it. They both technically are doing the same thing. I'll revert back to the crontab solution in a few days.

**Comment by fulldecent** [comment]
Recommending to close issue and if needed continue discussion in the other docker project
