### ISSUE TITLE
"Whoops something went wrong" after updating.

### ISSUE THREAD

**Issue by lanc2112b** [freescout-helpdesk/freescout#859]
After updating to the latest version, 'whoops, something went wrong' message appears after login.

Enabling debug shows: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailbox_user.access' in 'field list'

Have tried clearing the cache via SSH

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#troubleshooting

**Comment by lanc2112b** [comment]
Sorted, thx.
