### ISSUE TITLE
When deleting user mark user as deleted instead of deleting from DB

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#86]
todo

**Comment by guestisp** [comment]
A soft delete would be ok ?

**Comment by freescout-helpdesk** [comment]
Yes. Some bool `deleted` flag, which need to be checked when fetchings users. 

- When opening user profile (`/users/profile/1` for example) it should do `abort(404)`.
- Deleted user should not receive email notifications.
- User email need to be changed to `john@gmail.com_deleted20181108` for example, so that if needed user can be registered again.

**Comment by freescout-helpdesk** [comment]
Deleted user must be still visible in the past threads, menu notifications, etc.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/9c19bca5d93255cdf738d9ade84a2f7c101fd944
