### ISSUE TITLE
Change the format for dates

### ISSUE THREAD

**Issue by johanoloflindberg** [freescout-helpdesk/freescout#860]
I want to be able to change the format for dates to the following: 2020-11-10  (YYYY-MM-DD)

**Is it possible?**

**Comment by freescout-helpdesk** [comment]
No for now. It can be implemented by adding .env variable

**Comment by johanoloflindberg** [comment]
How do I add that?

**Comment by freescout-helpdesk** [comment]
Closing as out of scope.
