### ISSUE TITLE
question

### ISSUE THREAD

**Issue by colegatron** [freescout-helpdesk/freescout#861]
Pending is for tickets pending to be replied. And if you have to pass the ticket to another colleage, just add a note, re-assign the task, and it will be shown in the assigned user 'assigned' folder. 
Then you can reply, close or mark as spam, but not sure what is the use case for 'active'.

Thanks

**Comment by XtomtomX** [comment]
When a ticket enters your system, it is always marked as "active". The active status shows how many tickets are waiting to be processed by the agents in the ticket system.

If you as an agent reply to a ticket, it is set to "pending", which means that the agent is now waiting for a reply from the customer.

You can try it out on the demo website to gain some hands-on experience: https://demo.freescout.net/login

**Comment by colegatron** [comment]
Oh, ok, it is pending to read. 
Thanks.
