### ISSUE TITLE
Unable to upload profile photo for shared inboxes

### ISSUE THREAD

**Issue by radarsymphony** [freescout-helpdesk/freescout#862]
Issue: Users are unable to upload a profile photo for mailboxes. 
OS: Windows 10 Pro
Browser: Chrome Version 86.0.4240.183

### Steps to recreate issue:
1. Open a mailbox, click the user's initials in top right corner, Select 'Your Profile.'
2. Click 'Choose File.'
![image](https://user-images.githubusercontent.com/73671474/98722666-30e61500-2346-11eb-9ded-cd8b0d83a887.png)
3. In the File Manager, navigate to new profile image (of an accepted type), click 'Open.'
4. Click 'Save Profile.'
![image](https://user-images.githubusercontent.com/73671474/98724057-0301d000-2348-11eb-8628-a17cc767b720.png)
5. From that mailbox (and updated user), send a test email to another user. 
6. From within the mailbox, inspect the thread of that email by clicking on the email in the "mine" folder on the left side.
The following image shows two locations where the recently uploaded profile would presumably appear: 
![image](https://user-images.githubusercontent.com/73671474/98726485-6fca9980-234b-11eb-9e95-0b2d914a4454.png)

### Additional Comments: 
Also tried waiting, clearing cache, and hard refreshing. Did not resolve issue. 
After saving changes (step 4 above), the image name disappears and the "No file chosen" is displayed again. Even if this is functioning as intended, users might find it helpful to see a persistent record of the name of image they uploaded (as a reference and to verify that the changes took effect).

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by radarsymphony** [comment]
Thank you for your response! 
No, I cannot recreate it on demo.freescout.net. I was able to upload and save a profile on the demo site.

**Comment by radarsymphony** [comment]
This issue has been fixed with the latest release, 1.6.8.
Thanks for all the work you put into this project.
Issue Closed.
