### ISSUE TITLE
Business identity 

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#864]
Hi guys, 

Freescout also does not have it so maybe it never comes. 
I work almost only with business and have sometimes 6 persons and all multiple email adresses for one business where i communicate with. People resign so i forget them.

I would love to choose a business, and even multiple per person. And see all mail of one business. Now i need to filter on 10 different users (one by one) to get all there mail checked if i need one. 

Is this something more people have trouble with?
I am willing to pay for this feature 🙏

**Comment by colegatron** [comment]
Not used yet workflows nor custom folder, but maybe you can categorize them using custom folders and a workflow to make them archived in the right folder (guess a rule per company).

**Comment by XtomtomX** [comment]
Hi, with the custom folders, tags and workflow you can achieve that. Just tag the contacts by their domain and set up custom folders which show only the corresponding tagged conversations.

![grafik](https://user-images.githubusercontent.com/16431559/99552501-5cf43c80-29bd-11eb-8e98-35fcdb4324dd.png)
![grafik](https://user-images.githubusercontent.com/16431559/99552633-83b27300-29bd-11eb-8b97-6039db3ef451.png)
![grafik](https://user-images.githubusercontent.com/16431559/99552830-bceae300-29bd-11eb-8090-971fec4f3064.png)

**Comment by joris85** [comment]
Hi,
Thanks for the reply.
I use workflows and custom folders a lot.
I was thinking of this but is not ideal.
I work 100 active businesses.
Over the years that are more than 1000 so they will grow.

That would be a lot of rules and folders :-P
We use in mail folders (clients with subfolders client1).
And automatically recognizing the client and suggest to move to the specific folder (Mailhub).
With Freescout you can't make subfolders (yet) :-)
So handy fix and maybe use-full if you work with 10 businesses or so.

I suggest to have a custom field with the client (custom fields for clients) where you can add a tag, category that can be used would be great.
I have Basic, Plus, Pro clients so would be also great to give them a tag like that.
Also great for filter on all clients from a certain business or tag (Pro).

If somebody creates a custom client field module for freescout i am willing to pay 300 for a donation right away :-D
1. Tags for clients
2. Category for clients (dropdown with options)
3. Textarea for clients (this client is a pain in the ass, do not spend to much time... :-P)
4. Textfield

**Comment by fulldecent** [comment]
This is here https://freescout.net/module/crm/

Please send donation using https://www.patreon.com/FreeScout

**Comment by fulldecent** [comment]
Yes it is under "Custom Fields".

Recommending to close issue as usable workaround exists
