### ISSUE TITLE
Time Tracking and Workflow Module Issue

### ISSUE THREAD

**Issue by restos-99** [freescout-helpdesk/freescout#865]
Hi,

I think there is a bug with Workflow and time tracking module. If you have a workflow to automatically assign emails to certain user, the time tracking module start counting time when workflow execute this action. 

In time tracking preferences, I've the following preference:

The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation.

But timer starts when Workflow assign the conversation to user.

Version 1.6.7

Thank you.

**Comment by freescout-helpdesk** [comment]
We will check.

**Comment by restos-99** [comment]
Thank you.

**Comment by freescout-helpdesk** [comment]
Fixed in Time Tracking module 1.0.3
