### ISSUE TITLE
Issue Windows Mail (not deleting history)

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#868]
Hi guys,

Now we have fixed the Outlook i see that Windows Mail app (default windows mail) also does not work.
Is there somebody who can fix this?

I hope so :-)

**Comment by joris85** [comment]
I don know if this is Windows mail or Outlook but this client is also still not deleted.
I attached the original code from Freescout.

Our line to check is:
-- graag boven deze regel reageren --

[windowsmail.txt](https://github.com/freescout-helpdesk/freescout/files/5568219/windowsmail.txt)

**Comment by fulldecent** [comment]
Recommending to close issue as unclear
