### ISSUE TITLE
LDAP compatibility with Azure AD Domain Services

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#869]
The ldap module is returning "invalid credentials" when attempting to bind to the ldap of Azure ADDS.

https://docs.microsoft.com/en-us/azure/active-directory-domain-services/overview

I attempted to debug the issue using the php snippet in https://github.com/freescout-helpdesk/freescout/issues/599. That case the bind was successful when the name in the bind request only had the username without the DN and without "cn=username" or "uid=username."

**Comment by freescout-helpdesk** [comment]
Are you using Office 365?

**Comment by stevebauman** [comment]
Hi @afawaz2,

Well need much more information to help you debug this. A start would be your LDAP configuration (with any sensitive details omitted), as well as your Azure ADDS configuration.

I would also suggest testing basic connectivity to ensure your server is reachable from your web server, then debug from there.

**Comment by freescout-helpdesk** [comment]
@afawaz2 Have you enabled Azure AD Domain Services to offer an LDAPS endpoint to connect to? https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-configure-ldaps

**Comment by afawaz2** [comment]
> Are you using Office 365?

Yes.

I used the bind dn as: "ou=AADDC Users,dc=aad,..."


> Hi @afawaz2,
> 
> Well need much more information to help you debug this. A start would be your LDAP configuration (with any sensitive details omitted), as well as your Azure ADDS configuration.
> 
> I would also suggest testing basic connectivity to ensure your server is reachable from your web server, then debug from there.

I can reach the ADDS from the server. What information about the ADDS would you need? I can send those in a private email.


> @afawaz2 Have you enabled Azure AD Domain Services to offer an LDAPS endpoint to connect to? https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-configure-ldaps

LDAPS is enabled, but the module was failing to connect with the TLS option "Can't contact LDAP server."

I switched to plaintext with a 389 port. I can see the traffic between the server and the ldap with tcpdump.

The request is:
`bindRequest(1) "cn=ldap_service,dc=xxxxxxx,dc=com" simple`

The response is:
`bindResponse(1) 1X80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580
`

**Comment by stevebauman** [comment]
That response error code (52e) means:

> Indicates an Active Directory (AD) AcceptSecurityContext error, which is returned when the username is valid but the combination of password and user credential is invalid. This is the AD equivalent of LDAP error code 49.

Try resetting the service accounts password to ensure you’re using the correct one. Also ensure that all account flags are clear (i.e. user account locked out, user must change password on next login, smart card required, etc.)

I don’t think we’ll need to see your configuration since you mentioned you’re getting a response from your server (I see that you mentioned this in your original post, my mistake!).

You could also try binding with a domain admin account just to ensure there’s no permission issued taking place.

Let us know how the troubleshooting goes!

**Comment by afawaz2** [comment]
I am getting the same error. I tested multiple types of users and confirmed that non of them are locked out. Is this module using the https://github.com/Adldap2/Adldap2-Laravel project?

Where can I find the module's source code in my server? The modules folder is empty in /assets/install. I am using the docker container, https://github.com/tiredofit/docker-freescout.

**Comment by freescout-helpdesk** [comment]
> Is this module using the https://github.com/Adldap2/Adldap2-Laravel project?

Yes. 

> Where can I find the module's source code in my server? 

/Modules/Ldap

**Comment by afawaz2** [comment]
Thank you for the link, it turns out that you have two admin prefixes set cn= and uid=, looking at the ADDS documentation for the bind request
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6a5891b8-928e-4b75-a4a5-0e3b77eaca52

AADS expects allows the use of the full DN to do the match so instead of using the username (sAMAccountName) to do the login, I was able to bind use the CN.

For anyone in the future attempting this, install active directory explorer onto a joined machine and find the full DN of the user. The ldap module sets the bindrequest using "CN={bind username},{Bind DN string}"

**Comment by freescout-helpdesk** [comment]
Tanks for the information.

**Comment by afawaz2** [comment]
![image](https://user-images.githubusercontent.com/13179697/100698186-7736fe80-335d-11eb-9710-92e32fb3e9c1.png)
