### ISSUE TITLE
Website bug: Shopping cart prices in USD instead of user's currency

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#875]
https://freescout.net/modules

When you have prices displayed in EUR and add modules to the shopping card, their price is displayed in USD. At first that looks like a discount, but then at checkout the original pricing returns.

![image](https://user-images.githubusercontent.com/93784/99638223-33cbbe80-2a46-11eb-96c7-c66e9d790230.png)

Edit: I now realize the currency changes to USD in the cart, updated issue text.

**Comment by freescout-helpdesk** [comment]
Thanks. We will check.
