### ISSUE TITLE
Request: Workflow conditions for email headers

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#876]
We have contact forms on our websites and inside webapps, that all point to the same support desk (FreeScout). Those mails contain extra headers, for example the app name or the user group name. I would like to assign tags and users based on those mail headers.

For example: `Header` - `X-UserGroup` - `Matches regex pattern` - `^app_[a-z]+_editor`

It would be much like Subject matching, but with a custom header name.

**Comment by EugeneDae** [comment]
Really need this feature!

Our mail is handled by Google Workspace, which can be configured to add X-Gm-Spam and X-Gm-Phishy headers to all incoming messages that Gmail considers spam.

If this was possible, I could create a workflow in FreeScout to identify messages that have `X-Gm-Spam: 1` or `X-Gm-Phishy: 1` headers and move them to spam automatically.

By the way:
- This feature has been implemented in HelpScout around 2018 by my request.
- This feature seems to have been implemented in Zammad: https://github.com/zammad/zammad/issues/376

**Comment by freescout-helpdesk** [comment]
This feature has already been implemented in Workflows Module.
