### ISSUE TITLE
CC addresses remain filled in when forwarding a ticket

### ISSUE THREAD

**Issue by psuter80** [freescout-helpdesk/freescout#877]
when a ticked is forwarded to somebody, whoever was on CC in the original ticket will be pre-filled into the CC field when sending the forwarded ticket. At least I did not expect this to happen, as forwarding an email usually means that none of the original recipients will get it unless they are added. also the main ticket owner is removed from the recipients, but not the CC people.. that does not seem to make sense. 

expected behaviour: leave CC field blank, just like the To field when forwarding a ticket.

**Comment by fulldecent** [comment]
Recommend to close issue as not responsive.
