### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by superduif** [freescout-helpdesk/freescout#879]
Hi,

I am having issues with the time tracking module it does not seem to pause and there are no errors on the system status page...

The cron is setup and running but the time tracking is not working. It does not pause when I exit the conversation as it says on the sales page...

![image](https://user-images.githubusercontent.com/8034643/99800673-63112700-2b3d-11eb-88b2-831fe2c987d5.png)

**Comment by freescout-helpdesk** [comment]
If you can give an access to your server to check the issue please email at support@freescout.net

**Comment by superduif** [comment]
Email has been sent with access to the vm..

**Comment by superduif** [comment]
What I have noticed is that the system page is displaying the incorrect time for the time zone set..

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the Time Tracking Module v1.0.4
