### ISSUE TITLE
SAML Authentication Support

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#88]
Seeing the Todo for LDAP Authentication, I'd also like to add a request for SAML or at the very least HTTP Header based authentication support. This [Onelogin Laravel](https://github.com/aacotroneo/laravel-saml2) module looks like it would be a great addition.

**Comment by tareko** [comment]
One note is that SAML can use an LDAP IDP. Here's [one such example](https://dthlabs.com/configuring-a-saml-idp-with-ldap-as-authentication-source/). If you're using [SimpleSAMLphp](https://simplesamlphp.org/), see [this documentation](https://simplesamlphp.org/docs/stable/ldap:ldap). Not sure if that helps your workflow at all.

tarek : )

**Comment by tiredofit** [comment]
It would make sense that Freescout just act as a SP to an already in place solution such as KeyCloak or LemonLDAP:NG.

There seems to be a community module exisiting already - one thing that can set it apart is to have the functionality to auto create users if they do not already exist.

**Comment by freescout-helpdesk** [comment]
It looks like https://github.com/vladaman/freescout-saml2 is already able to auto create users.

**Comment by tiredofit** [comment]
There we go! Sorry, I had assumed it worked in similar fashion to the Community OIDC plugin.

**Comment by freescout-helpdesk** [comment]
So we are closing this feature request. Further comments can be added in https://github.com/vladaman/freescout-saml2
