### ISSUE TITLE
Add bulk actions to mobile UI

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#880]
On desktop the conversation list has checkboxes for bulk actions. On mobile the checkboxes are missing, so you can't do bulk actions. I found that you can tap and hold the white space of each row to activate bulk mode, but that is not intuitive and doesn't always work.

I rather have an extra button in the top bar next to the Mailbox Settings. A checkbox icon. Tap it to have checkboxes appear on the rows. Select a row to activate the floating bulk actions.

**Comment by freescout-helpdesk** [comment]
It is fine as is.
