### ISSUE TITLE
Link to "connection setting" don't display for non-admin

### ISSUE THREAD

**Issue by Zatalyz** [freescout-helpdesk/freescout#881]
Hello,
As admin, I ticked "manage mailbox" for User1 on the Mailbox1.

User1 can manage mailbox and have right on page "http://courriel.numenaute.org/mailbox/connection-settings/1/incoming" but he don't have link display to this page on "Manage -> Mailboxes ->Mailbox1". He had only "Edit Mailbox". 

Just a problem about display link, so...

**Comment by freescout-helpdesk** [comment]
Mailbox connection setting must be available only for admins.

**Comment by Zatalyz** [comment]
It is strange, because User1 can access via direct link (he is not admin, only user with right to "Edit mailbox"). And it is convenient to allow some users to change the mailbox password.
