### ISSUE TITLE
iPhone App

### ISSUE THREAD

**Issue by qsvch** [freescout-helpdesk/freescout#884]
Thank you for the iPhone app, which serves us very well! The push messages work perfectly with the module. But I still have three suggestions for improvement:

- I use an iPhone 11Pro, which - like almost all iPhones by now - has a notch at the top of the screen. To the left of it the time is displayed and to the right network provider/reception. Unfortunately, the logo (link to the start) often disappears below the time and thus cannot be operated. 

- While writing, the text window often becomes larger and must be zoomed again for better readability. 

- The back and forward buttons at the bottom of the screen are often annoying, because they are sometimes used by mistake. If all links to external pages were opened in the standard browser, this navigation would not be necessary anymore.

**Comment by freescout-helpdesk** [comment]
Thanks. We will check what can be done.
