### ISSUE TITLE
Request: Automatically copy tags to forwarded mail

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#886]
When forwarding a conversation with tags the newly created conversation does not have tags, while they refer to the same situation. It would be nice if the tags are automatically applied to the new forward conversation by default.

**Comment by freescout-helpdesk** [comment]
Won't be implemented by us. If anyone wants to contribute: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs

**Comment by Heavy89** [comment]
Has someone solved this problem? I need the same function and i'll need some help to move the tag along with the conversation when i move a conversation to another mailbox. I've tried to recreate the tag with a workflow on the destination mailbox but it work only if manually applied and not with automatic workflow
