### ISSUE TITLE
Customer deletion

### ISSUE THREAD

**Issue by EoleDev** [freescout-helpdesk/freescout#888]
Hi,
Thanks for your work !!
As we are receiving some spams in our mailbox, for each spam a new customer is created.
We would be really happy to have an option to delete customers when no conversations are assigned to them !
Maybe the deletion could be forbidden when a customer is attached to a conversation to prevent errors !

Thank you !

**Comment by freescout-helpdesk** [comment]
Implemented in CRM Module v1.0.23

![2022-12-21_11-41-28](https://user-images.githubusercontent.com/40499291/208859476-7d503efb-db5f-413c-b8e5-2135a8f6375a.png)
