### ISSUE TITLE
Time tracking not visible

### ISSUE THREAD

**Issue by Filoz** [freescout-helpdesk/freescout#889]
Hi,
after last update, I can't see timer under the conversation title.

It isn't visibile in conversation page; The module is active and configured.
![image](https://user-images.githubusercontent.com/5341996/100475894-8b23fb80-30e4-11eb-9981-26b1b3a84201.png)

**Comment by freescout-helpdesk** [comment]
Unfortunately we can't reproduce the issue.
Anybody else experiencing such issue?

**Comment by Filoz** [comment]
I tried on https://demo.freescout.net/ and the time tracker isn't visibile too

**Comment by freescout-helpdesk** [comment]
Assign conversation to yourself or some other user.

**Comment by Filoz** [comment]
Oh, you are right.
In my config I set "The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation." but the timer wasn't visible.


It can be strange, but adding reports module solved the issue. Now I'm viewing the timer in the top part of the conversation
