### ISSUE TITLE
CRM - Customer Fields

### ISSUE THREAD

**Issue by blacdara** [freescout-helpdesk/freescout#891]
Hello,

Would it be possible to include a customer field in the CRM that you can set up a subdivision. 

Block1
----------------------------------
Customer Fields
Customer Fields
Customer Fields
Customer Fields
----------------------------------

Block2
----------------------------------
Customer Fields
Customer Fields
Customer Fields
Customer Fields
----------------------------------

It would make it clearer.

Sorry for my English 

Thanks :)

**Comment by freescout-helpdesk** [comment]
Hi. No plans for now.
