### ISSUE TITLE
Timetracking should be able to start WITHOUT running

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#892]
Usually you don't start merely by looking at a mail. This is something the user has to decide himself when to start. So it shouldn't automatically start at all. So I suggest a third option for the working clock.

**Comment by freescout-helpdesk** [comment]
If someone wish feel free to implement it in the module.

**Comment by nickbe** [comment]
Well as far as I know there are no GitHub repos availabe for modules... or are there?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs

**Comment by nickbe** [comment]
ok will do!
