### ISSUE TITLE
Delete emails from mail server when deleting conversations

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#893]
When deleting messages (and emptying the trashcan) then the mails are seemingly gone.
Looking at the mailserver though the mails are still there which is wrong - both from a security and privacy protection point of view as well as when considering the mailbox size.

So when deleting a mail and emptying the trash we should be able to rely that the mail is in fact gone.

**Comment by nickbe** [comment]
So we just noticed that the mails are pulled from the server and nothing else. Please give us a simple option to delete mails as soon as they are pulled.

**Comment by freescout-helpdesk** [comment]
The "Also delete from mail server" checkbox should be added to the "Delete Conversations" dialog.

**Comment by nickbe** [comment]
I think It should rather be a basic setting - not for someone who is deleting a conversation.

**Comment by tiredofit** [comment]
If this option was to come it should be a part of the Mailbox Settings component and either have a scheduled timer to delete messages after (x) days, force a manual expunge, or do it upon downloading the message immediately from the server.

**Comment by nickbe** [comment]
That's basically what I suggested above?

**Comment by tiredofit** [comment]
Pretty much the same, yet my take on it was leave it on the mailbox as it is happening right now ,and make the option per mailbox not per freescout instance.

**Comment by nickbe** [comment]
Ah yes sorry, that's also what I meant.

**Comment by joris85** [comment]
Should be an option, not default.
I keep my mailbox filled as archive for if i ever stop with Freescout i still have the emails.

**Comment by flof93** [comment]
This would be a great function, since we are using freescout with a Mailbox that is limited - at the moment we are deleting Mails every month or so manually from the mailbox.

**Comment by alexis3290** [comment]
Is it something that could be implanted anytime soon ? My hosting only provide 5Gb of mail storage, so I delete all the advertising mail or parcel tracking etc…
I also agree with @tiredofit that it should be a Mailbox setting, not a Freescout main settings.

**Comment by freescout-helpdesk** [comment]
Implemented in https://freescout.net/module/gdpr/

**Comment by webdados** [comment]
What was implemented in the GDPR module? I only see an option to delete messages from the mail server when the customer is deleted.

AFAIK, this ticket was about removing messages from the mail server when they're deleted from the Freescout trash, or have the option to delete from the server in POP mode, immediately or after some days.

As we are today, whenever I empty the trash, if the emails still exist on the server, they're pulled again as new conversations, which makes no sense whatsoever.

**Comment by webdados** [comment]
I've just made a quick simple module that will delete messages from the remote server after they're fetched (set as seen).
https://github.com/webdados/DeleteOnFetch

No deletion warnings. Use at your own risk!

**Comment by freescout-helpdesk** [comment]
See https://freescout.net/module/imap-move/
