### ISSUE TITLE
FreeScout Not Loading Fonts, Inline Styles, and Polycast Due to CSP Directive Violations

### ISSUE THREAD

**Issue by anthonyjesmok** [freescout-helpdesk/freescout#894]
Hello!

I recently installed FreeScout on my Debian 10 server using the Ubuntu script, including Nginx, Certbox, etc. The application seems to be working fine, except it is not loading some of the icons from the Font Awesome file and I'm also seeing "Lost Internet Connection" messages. When I go to my Chrome console, I see numerous console errors.

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog='), or a nonce ('nonce-...') is required to enable inline execution.`

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-HKsM7+j1+dHJh8ViT01N670AzZUXJ30d6ZB9z3d9oCQ='), or a nonce ('nonce-...') is required to enable inline execution.`

`Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

`Refused to load manifest from 'https://REMOVEDFORPRIVACY/site.webmanifest' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.`

`Refused to connect to 'https://REMOVEDFORPRIVACY/polycast/connect' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

I have tried to change some of the Nginx site configuration, but no dice. Anyone have any advice on how to get these CSP errors to go away?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting
