### ISSUE TITLE
Make customer messages editable

### ISSUE THREAD

**Issue by psuter80** [freescout-helpdesk/freescout#896]
it would be nice to have the possibility to edit an email in the ticket history just like notes can be edited. this way it would be possible to remove information from the ticket history that is not supposed to be sent forth and back all the time: 

two use-cases where this functionality would be handy: 

1.) a customer opens a new ticket and includes his password in the ticket request. later other parties should be added to the conversation, but the customer's password in the original message should be hidden.. also to avoid sending the credentials forth and back on every email exchange it would be wise to remove it from the history. with the above functionality, the crendentials could be removed from the message and copied into a internal note, so they are still available to the ticket handler but no longer to the people involved in (or listening in on) the conversation. 

2.) a business partner forwards a request he got from this customer for 2nd level support. he wants me to respond directly to his original customer but when forwarding the email to me, he adds a few internal comments which are not meant to be communicated back to his original customer. With an edit function like that such comments could be removed from the ticket or copied into an internal note. 

ideally the original message that is displayed when using the "Show Original" function should not change, only the message shown in the ticket should be changed. like this any ticket manipulations are traceable in case of disputes or anything like that.

**Comment by nickbe** [comment]
I wasn't aware that there's a possibility that messages cannot be edited.
The problem here is that according to the european privacy data protection rules, we are obliged to delete sensible data if we don't need it anymore. This is not something we cannot choose but that we have to do.

So any stored customer data that is not relevant to invoicing/tax or contracts must be deletable or changable so that it is anonymous afterwards. In this case it would be indeed necessary to be able to remove sensible data from tickets.

**Comment by psuter80** [comment]
i am by no means a law expert, but, i can't imagine that what you are saying is truly in this law, because this basically would make it illegal to use any email client, whatsapp, telegram and what not that does not allow to immediately alter messages after they where received.. i don't know of an email client that allows to edit a message after receiving it. Is there a special EU email client? ;)

also in the ticketing system, i would only want to edit the message shown in the ticket history.. the record of the original message which is viewable thorugh the "Show Original" function should still remain original, for the sake of tracking manipulations after the fact.

**Comment by nickbe** [comment]
Doubt it or not. As soon as a customer demands deletion of all private data, not relevant for fiscus/tax purposes, we must comply to this new regulation. Most people in the EU still don't realize what all this means, but no matter how stupid it sounds - it's the law. So all measures which can be taken reasonably have to be taken. 
So the moment you declare all business contacts between us "closed" and demand that I delete your data, I have to:
1. find out which part of your stored information is relevant to ongoing tax/invoice papers - they must be stored for 10 years
2. delete or anonymise all other aspects of the stored data, especially: name, adress, phone number, mail address and everything else which I could use to identify you as a person to protect your privacy.

**Comment by psuter80** [comment]
@freescout-helpdesk thank you so much, you are awesome! I just patched my installation and it works flawlessly. I'm going to close this ticket now.

@nickbe now i agree with you as far as deleting the users data goes. I just can't see where you would go through every email of that person and start editing those messages to remove mentions of that person, this seems unrealistic in practice and too much work.. i'd simply erase all conversations from that person's email adress and you're golden.. anything that needs to be archived as far as taxes etc. goes is hopefully saved somewhere more meaningful and organized than an email client or ticketing system.. so no harm in just deleting all emails of that person.. actually this sounds to me like a perfect use case for a new "GDPR compliance" module which basically takes care of cleaning up all entities belonging to a customer in a single click or in saving all those entities and making it available to the customer should he request to see all this information.

**Comment by nickbe** [comment]
Yes we know the rules are widely regarded as not practical, but the harder companies try the better their stand in case something happens. And anyway. 

GDPR compliance" module - yep. This would be a very interesting. GDPR compliance is a big selling point in the EU right now.
