### ISSUE TITLE
Softaculous 1-click install from c-panel

### ISSUE THREAD

**Issue by pavlenex** [freescout-helpdesk/freescout#90]
I reached out to Softaculous, a company that implements 1-click installations for shared hosting for majority of hosts in c-panel.

They tried to implement FreshDesk, but couldn't do to this:

 > Our developers just checked the details and concluded that freescout requires virtual host entry to install https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#62-apache We have confirmed the same with vendor also on Github. Hence we shall not be able to add this at Softaculous.

Is there any way to re-configure the installation process so that less tech savvy people can deploy easily from their c-panel? That would be a big step towards adoption.

**Comment by freescout-helpdesk** [comment]
Thanks. We will make sure it is possible to install it with cpanel.

**Comment by bitcoinshirt** [comment]
Awesome! Thank you so much. I'll keep the issue opened until it's implemented.
If you wish, let me know and I can ping them since I have an already opened ticket, or you can do it if you prefer.

**Comment by freescout-helpdesk** [comment]
Actually it should be already possible to install FreeScout using cpanel.

**Comment by bitcoinshirt** [comment]
I assume this company does not support ` virtual host `
I believe that's the problem. If there was a way to bypass it I think they can implement it.
If you need more info, just tell me what to ask them.

**Comment by freescout-helpdesk** [comment]
Just check with them what should be done to allow FreeScout installation using Softaculous from cpanel.

**Comment by bitcoinshirt** [comment]
@freescout-helpdesk 

> I did mention that the script needs virtual host entry to install the script. However we at Softaculous shall not have access to make/edit these entries for our users. The script should be able to get installed in sub-directories without the Virtual Host entry. If this is possible, we can go ahead with further testing. Reference link :
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#62-apache

**Comment by freescout-helpdesk** [comment]
FreeScout now can be installed in a subdirectory. Softaculous team is working on integrating FreeScout into their system.

**Comment by freescout-helpdesk** [comment]
FreeScout is available in Softaculous now: http://www.softaculous.com/apps/customersupport/FreeScout

**Comment by pavlenex** [comment]
Fantastic, this should bring lots of newbies to FreeScout.

Thanks.
