### ISSUE TITLE
Customer fields - am I missing something here

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#900]
In the customer fields module there's are the options "Display to Customer" and "Customer can Edit". Am I missing something here? Can the customer somehow login to the system? 

There's the customer portal. but this seems to be only to be a very rudimentary 3 field send message plugin.

So how is the customer part supposed to work?

**Comment by freescout-helpdesk** [comment]
It will be possible in the future in End-user Portal Module.

**Comment by nickbe** [comment]
Ok, thanks. Cool. I've set this module aside until that time.
