### ISSUE TITLE
Name does not vanish from assignment drop down

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#901]
I've just hidden a name from the assign list. For one user the name has vanished from the drop down.
For another it's still there. Both users are "users" not admins.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue.

**Comment by nickbe** [comment]
We've created 6 users to far, 2 of them admins. Somehow it seems that "hiding" the names from the dropdown by using the function is not working, since the users can all see the admins and assign tasks to them. Also users can see each others name even if we hide their names.
I can reproduce this any time - sorry, but it's simply not working.
