### ISSUE TITLE
Visual enhancements for the Tags Module

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#903]
I'd suggest some changes to the Tags Module to make it look much more pleasing
```

conv_tags .tag {
        margin-top: 8px;
	padding: 5px 5px 5px 10px;
	font-size: 15px;
	font-variant: petite-caps;
	font-weight: bold;
	border-radius: 3px;
}

.tag-c-2 {   background-color: #349DE9 !important; }
.tag-c-5 {   background-color: #F0554F !important; }
/* Other colors similar in hue and fitting */

```
 
Before:
![image](https://user-images.githubusercontent.com/10890765/100934021-6ff32a80-34ee-11eb-9e1c-ced01a0f2646.png)

After:
![image](https://user-images.githubusercontent.com/10890765/100935393-56eb7900-34f0-11eb-864b-f8c637367a6c.png)

**Comment by freescout-helpdesk** [comment]
Thanks. We will check it.

**Comment by freescout-helpdesk** [comment]
Styles have been updated a bit in Tags Module v1.0.13

**Comment by nickbe** [comment]
Thanks guys 😃

**Comment by fvdm** [comment]
@freescout-helpdesk In the Tags changelog the version for this change has a typo. Says `1.0.12` and should be `1.0.13`. 😉

**Comment by freescout-helpdesk** [comment]
Thanks. Fixed.

**Comment by distresscode** [comment]
Tags are lowercase for me no matter what I do. Just purchased the module today. Suggestions?
