### ISSUE TITLE
[Feature Request] Option to display a Calendar date instead of "X days ago" for mail in inbox

### ISSUE THREAD

**Issue by radarsymphony** [freescout-helpdesk/freescout#904]
## Overview
Add an option to choose between displaying date as a calendar date or "days ago" for the 'Waiting Since' column. 
(See the image below for more context.)

## Current Functionality
Currently, the 'Waiting Since' date for each email is displayed as "X hours ago" before switching to "X day(s) ago", etc. before switching to displaying a calendar date when the email has been "waiting" more than a week. 
See below for an example showing a few of the possible display dates. The red arrow shows how all dates would appear in this feature request.
![image](https://user-images.githubusercontent.com/73671474/101105942-ba72b680-3583-11eb-9bfc-8573adad57bf.png)

## Proposed Feature
The proposed feature would allow "Waiting Since" dates to always display as a calendar date (see arrow above) as opposed to "X days ago." If the email began waiting within the current calendar date, it would still display "x hours ago" but would switch to display calendar dates if the mail was received before that day. A toggle for this option might live within 'Mailbox Settings' (under 'Edit Mailbox'), or under 'Manage', where global mailbox time format settings already exist (see image below). The first placement implies individual toggles for each mailbox which would allow more ability tailor to the function of the inbox. This is the preferred functionality.

**Comment by freescout-helpdesk** [comment]
Full date can be seen by hovering over the "x ... ago" value. It's not enough?

**Comment by radarsymphony** [comment]
Thanks for your quick reply. Yes, I think that should be enough. (We have a few Luddites in our system that might just have to learn about 'alt text' and the power of hovering...) Much appreciated. Thanks for your time   :)
