### ISSUE TITLE
Make time tracking data available in API

### ISSUE THREAD

**Issue by kurvenschubser** [freescout-helpdesk/freescout#905]
I would like to be able to get the time tracking data for a conversation. Ideally for each mail/note on a conversation. If possible beginning and end of time tracking. If that's not possible then total time spent.

**Comment by kurvenschubser** [comment]
Any chance this will be implemented soon?

**Comment by freescout-helpdesk** [comment]
Not very soon, several months. See also https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs

**Comment by kurvenschubser** [comment]
This is a quick and dirty fix. It's probably not suitable and untested for folks who don't have the time tracking module installed. Do you see any chance of it making it into the master branch?

`root@731edf0b-fa63-4584-ab0e-85525165ce24:/app/code# diff Modules/ApiWebhooks/Providers/ApiWebhooksServiceProvider.php /tmp/ApiWebhooksServiceProvider.php 
17a18
> use Modules\TimeTracking\Entities\Timelog;
252a254,262
>         // Timelog
>       if ($entity instanceof Timelog) {
>             $result = [
>                 'id' => $entity->id,
>                 'created_at' => $entity->created_at,
>                 'time_spent' => $entity->time_spent
>             ];
>         }
> 
258a269,275
>             $timelogs = [];
>             $timelogs_ = Timelog::where('conversation_id', $entity->id)
>                 ->orderBy('id', 'desc')
>                 ->get();
>             foreach ($timelogs_ as $timelog) {
>                 $timelogs[] = self::formatEntity($timelog);
>             }
293c310,311
<                     'threads' => $threads
---
>                     'threads' => $threads,
>                     'timelogs' => $timelogs`

**Comment by johanoloflindberg** [comment]
👍🏻👍🏻👍🏻

**Comment by kurvenschubser** [comment]
Any chance this is going to be implemented?

**Comment by freescout-helpdesk** [comment]
Timelogs can be retrieved in API & Webhooks Module v1.0.20 by passing embed=`threads,timelogs`: https://api-docs.freescout.net/#get-conversation
