### ISSUE TITLE
New visual changes ready

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#906]
Hi guys,

I've made several visual improvement regarding overall dashboard layout, mobile usability and responsiveness:
![image](https://user-images.githubusercontent.com/10890765/101157253-18f27000-362a-11eb-9481-e0810a508454.png)

Can I just send you my style.css?

**Comment by freescout-helpdesk** [comment]
Yes. You can just attach the file.

For complex updates better to submit pull requests into the `master` branch.

**Comment by nickbe** [comment]
I'll finish the changes and attach the file. I'm not really know the git mechanics.

**Comment by tiredofit** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request 

Quite simple to do a PR, that means others can view the changes rather than having to sift through two different copies of a style.css.

**Comment by fvdm** [comment]
Even simpler for beginners:

1. On Github browse to the file you wish to change.
2. In the top-left corner of the content area switch to the **master** branch.
3. On the right, next to `raw` and `blame` buttons, click the **pencil** ✏️ icon.
4. At the bottom fill out the **Propose changes** form.

**Comment by nickbe** [comment]
Thanks for the tip. I've done that a couple of minutes ago.
