### ISSUE TITLE
Pending conversations are too "off the radar"

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#907]
When we create something "Pending" then it's not on the radar. I think especially when you think about many mailboxes there should be a way see to all pending tasks in their own list. Clicking through 15+ Mailboxes just to check if anything's pending doesn't seem practical.

**Comment by nickbe** [comment]
We played around with "internal tickets"  too. Problem is: If I write a standard ticket - using either mail/conversation or note, and even assign the ticket directly to the other user, then the other user has also no way of seeing this new ticket in the dashboard lists. 

I think this problem should be solved somehow. Especially in a IT only environment  we should be able to assign tickets directly  to another internal user (in this case we should be able to use something similar to "note". I also find the name "note" strange when creating tickets in a helpdesk.

In my opinion there should be 3 types: conversation, note (is this meant to be an internal ticket somehow?), and internal conversation/whatever. Or freescout could simply recognize the internal users mail adress and hanel it differently.

To be homest we simply couldn't figure out how to do this right.
Or did we miss something completely here?

**Comment by nickbe** [comment]
We've already figured out how to enhance this behaviour greatly. We will improve this and make a suggestion to review and integrate this issue in a couple of days.

**Comment by freescout-helpdesk** [comment]
Users receive notifications to email, browser or mobile. It's enough.
