### ISSUE TITLE
1.6.9 - Error update TwoFactor

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#908]
After updating to 1.6.9, I got this error;
```
(1/1) FatalThrowableError
Class 'MacroableModels' not found

in TwoFactorAuthServiceProvider.php line 145
at TwoFactorAuthServiceProvider->macros()
in TwoFactorAuthServiceProvider.php line 33
at TwoFactorAuthServiceProvider->boot()
at call_user_func_array(array(object(TwoFactorAuthServiceProvider), 'boot'), array())
in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()
in BoundMethod.php line 87

```

So I removed the TwoFactor module from Modules and the symlink but still unable to access;

```
In Module.php line 327:
                                                                         
  include(/start.php): failed to open stream: No such file or directory
```

Tried uploading via ssh and overwrite the app with a new version and still getting TwoFactor error and migrate db using tools.php still same error. 

Installed 2FA Module Version: 1.0.1
Web Server | Apache/2.4.46 (Unix) OpenSSL/1.1.1
PHP 7.4.12

For now, I have rolled back to 1.6.8.

**Comment by freescout-helpdesk** [comment]
It works fine on https://demo.freescout.net
