### ISSUE TITLE
[Bug] Workflows: Tabs are broken, everything merged into Settings

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#909]
Since the latest FS update, the tabs within Workflows are no longer functional. All the fields from Conditions and Actions are merged on the Settings tab.

Nothing is shown in the browser console and there are no errors in the Logs. I already tried clearing the cache but that didn't help.

FreeScout 1.6.9
Workflows 1.0.2
Firefox 83.0
Safari 14.0.1

**Comment by diguinho2018** [comment]
Hey, I just checked mine and it is working as expected, do you have any ad/script blocker in your browser, maybe that is messing with the settings?

**Comment by fvdm** [comment]
@diguinho2018 When I disable all browser extensions and clear the caches the problem remains.

[Screencap](https://wolk.link/s/0f0R1mSzeU2kV7q)

**Comment by fvdm** [comment]
I also tried disabling and reactivating the Workflow module. On System Status everything is green. I manually checked file and directory permissions and they're all good. Even ran `/tools/update.sh` in a terminal and done the sync to dist and DB migrate.

What else to check?
