### ISSUE TITLE
Send auto-reply on every new conversation

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#91]
Currenlty, auto-replies are sent once per day per customer.
This is not good, one auto-reply should be sent once per conversation to notify customers that their requests are received properly.

Probably, a setting could be added to enable or disable this.

If you are using Freescout as ticketing help desk, when the same user is creating multiple conversations, a receive acknowledge should be sent every time.

**Comment by freescout-helpdesk** [comment]
Thanks. Added to the [todo-list](https://github.com/freescout-helpdesk/freescout/projects/1)

**Comment by guestisp** [comment]
What if I add a setting between `Enable Auto Reply` and `Office Hours` to allow sending one auto-reply per conversation?

**Comment by freescout-helpdesk** [comment]
Yes. It would be good.

Checkbox similar to "Enable Auto Reply": `Send Once in 24 Hours`

**Comment by guestisp** [comment]
Working on it right now.
