### ISSUE TITLE
[Bug] End-User Portal

### ISSUE THREAD

**Issue by diguinho2018** [freescout-helpdesk/freescout#910]
Hey guys!

First I would like to congrat the devs on this project, it is better everyday and you guys listen to our suggestions, that is great.
Today I bought this module and its great, when editing I think I noticed a bug.

If I click the color picker it only displays blue colors.
Firefox, FreeScout 1.6.9, End-User Portal 1.0.3

![001](https://user-images.githubusercontent.com/39450586/101289464-682bd280-37db-11eb-945c-ec6407aa0985.png)

**Comment by freescout-helpdesk** [comment]
Fixed in End-User Portal Module v1.0.4
