### ISSUE TITLE
History view very irritating when working

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#911]
I think the part of the history "who marked and did what to whom" should find a better place or should be hidden and shown on demand. We have a sidebar on the right. Maybe this is a better place for it.

**Comment by freescout-helpdesk** [comment]
Feel free to implement as a custom module. It is possible to adjust anything with custom modules.

**Comment by nickbe** [comment]
This is definetely not something for a module, but should be integral part of the core. 
But that set aside, we are always willing to contribute to a project. Is there a way to contact you via email?

**Comment by fvdm** [comment]
I personally don't mind the current state of history events, it's very clean and informative. But can see how it may clutter the view when you have a lot of meta events happening.

A very nice solution I have seen somewhere else is
- Hide or show them by default depending on user setting.
- When there are meta events a link is shown in a light (unobtrusive) color at the top with how many events are invisible. `Show 35 hidden events`
- Clicking the link expands the messages inside the timeline (javascript).
- When a new hidden event occurs the link lights up to indicate there are new unseen events.

**Comment by nickbe** [comment]
That would be the perfect solution.
