### ISSUE TITLE
Search function returns deleted tickets by default

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#912]
Hello,

We do a lot of merging as our customers have their own ticketing systems that sometimes break conversations. Merged conversations get "deleted".
When I search for a keyword, any merged conversations that match but are "deleted" also appear, spamming the result list.

"Deleted" (and maybe Closed) should be, by default, excluded from search results and need an advanced filter, like "show all" to be checked.
 
Making things worse, is the fact that there's no Status column in the search results, meaning you can't quickly tell if a specific result is what you want or not. The only marking is the trashcan icon on deleted conversations, but that prefixes the Subject field instead of being a separate column.

**Comment by freescout-helpdesk** [comment]
In the latest versions of FreeScout special icons have been added to subjects of deleted and closed conversations.

**Comment by freescout-helpdesk** [comment]
To solve this:

1) "Deleted" should be added to the Status filter.

2) "Status" filter should be applied by default with Active, Pending and Closed selected.
