### ISSUE TITLE
Allow API key to be invalidated

### ISSUE THREAD

**Issue by kurvenschubser** [freescout-helpdesk/freescout#913]
The api key seems to be fixed right now. It would be great if it could be invalidated/re-generated in case it gets leaked.

**Comment by freescout-helpdesk** [comment]
Maybe someone can implement it. 
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs

**Comment by fulldecent** [comment]
Work plan:

- [ ] API key management page
- [ ] Can create a key
- [ ] Can restrict any key to IP addresses
- [ ] Can restrict any key to certain API calls
- [ ] Can delete any key

**Comment by freescout-helpdesk** [comment]
Re-generate API key button will be enough for now. Other can be posted at https://freescout.net/request-feature/

Here is how to contribute to modules: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#5-modifying-modules

**Comment by freescout-helpdesk** [comment]
Does not seem to be very required feature.
