### ISSUE TITLE
If you have permissions issue

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#914]
There's a couple of issues I have, they're not major just creating admin for me.

1. It seems whenever there's an update I get "Whoops there's an error" on the Manage > System page. To remove this error I run the `php artisan freescout:clear-cache` command and that resolves it. I then can get to my system settings page.

2. However, I get a warning about the `storage/framework/cache/data/` needing permissions (every time error 1 happens). I run the `sudo chown -R www-data:www-data /var/www/html` and then it goes to "OK", right up until another update is available then I have to repeat the two steps.

### Error log from App Logs

failed to open stream: No such file or directory {"userId":1,"email":"redacted","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/storage/framework/cache/data/05/9e/059ea079daf978c13b5020b85da476768ea94d82): failed to open stream: No such file or directory at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)

This is on Digital Ocean, running on NGINX.

**Comment by freescout-helpdesk** [comment]
Make sure that `www-data` is the primary group of the `freescout` user:
```
sudo  usermod -g www-data freescout
```

**Comment by andrewlimaza** [comment]
Thanks I've run that script for the user, I'll keep an eye on it.
