### ISSUE TITLE
Feature Request: sort conversations lists

### ISSUE THREAD

**Issue by psuter80** [freescout-helpdesk/freescout#919]
It seems that the listing of conversations in a folder is currently not sorted at all. at least I can't find any logic behind the order how they are displayed. 

it would be nice to be able to click on the message headers in order to order the threads by this column either up or down, bascially like in most email clients :) 

as a quick intermediate solution to bring some degree of order into the lists, I think sorting the messages by last update date would be a feasible default and probably what most people want. 

this would also solve #323 

EDIT: I have to be more precise.. it seems sorted by exactly the column i ment in the "Mine" folder, but other folders like drafts or Closed seem to be in random order.

**Comment by freescout-helpdesk** [comment]
See sorting rules here: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Folder.php#L144

**Comment by freescout-helpdesk** [comment]
Also https://freescout.net/module/inbox/ should help to resolve your confusion.

**Comment by andrewlimaza** [comment]
This filter should be when you return or right before (so developer's can overwrite it) - https://github.com/freescout-helpdesk/freescout/blob/dist/app/Folder.php#L174

It's in the default case, which doesn't run in most cases.

**Comment by MarcoWel** [comment]
Hi,
In the latest version of FreeScout it is still not possible to resort columns by clicking on the column header in the conversations overview. This is supported by all major ticketing systems and an important feature.

Please get this implemented, we would pay for an extension module too, of course! :)

**Comment by MarcoWel** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/372954

**Comment by sideshot** [comment]
> This filter should be when you return or right before (so developer's can overwrite it) - https://github.com/freescout-helpdesk/freescout/blob/dist/app/Folder.php#L174
> 
> It's in the default case, which doesn't run in most cases.

We ended up just modifying the file to sort in reverse.  In our case, it should always be the oldest are seen first.  

```
                #$order_by[] = ['status' => 'asc'];
                $order_by[] = ['last_reply_at' => 'asc'];

```
