### ISSUE TITLE
Error: imap_open(): Couldn't open stream, certificate failiture

### ISSUE THREAD

**Issue by bitcoinshirt** [freescout-helpdesk/freescout#92]
Set up my Freescout on shared hosting. 

Configured  Connection Settings > Sending emails - works
Tried to configure  Connection Settings > Fetching emails- does not work

The error I get is 

`Error: imap_open(): Couldn't open stream {mysite.com:993/imap/ssl}. Certificate failure for mysite.com: Server name does not match certificate: /OU=Domain Control Validated/CN=*.myhost.biz; File:support/vendor/webklex/laravel-imap/src/IMAP/Client.php (230) `
 
1. The imap PHP module is enabled.
2. The SSL certificate is installed properly 
3. Port 993 is open for incoming connections.

My setup:

Fetch From: support@mysite.com
Protocol: imap
Server: mysite.com
Port: 993
Encryption: SSL

Any idea how to fix this?

**Comment by bitcoinshirt** [comment]
It was issue with my hosting, they fixed it.

**Comment by BrianGilbert** [comment]
@pavlenex do you know what they did to resolve it?
