### ISSUE TITLE
User can't delete conversation

### ISSUE THREAD

**Issue by Zatalyz** [freescout-helpdesk/freescout#920]
When we are connected as user, we can't delete conversation.

Exemple for user1, who have this permission on mailboxe Mail1 :

- edit Mailbox
- Permissions
- Email Signature

I had some spam. I can classify them in "spam", but I can't delete this spam when I am connected like "user1", even if spam are in spambox.

**Comment by tillmon** [comment]
Did you try to set "editing" permission for user1 in the mailbox settings (not the user settings)?

**Comment by Zatalyz** [comment]
Yes, if in "mailboxes >permissions", "Edit Mailbox" is checked, it doesn't change anything. User1 can't delete a message.

I am on version, 1.6.7, maybe new version don't have this problem ? I try to update :)

**Comment by tillmon** [comment]
There is another setting in system: _yourdomain.com/app-settings_

**Comment by Zatalyz** [comment]
Ok, it works ! Thanks a lot.

It seems to me that this may be an ergonomic problem. First because I didn't think to search here ;) Then, the rights in this space should not be defined globally, but assigned for user. For example, preventing a "junior" from deleting the mails can be a good thing, whereas experimented people can delete, edit, etc.

**Comment by fulldecent** [comment]
This looks good now. Thank you. Recommending to close issue
