### ISSUE TITLE
Merging a conversation into another should be handled like a "reply added" event

### ISSUE THREAD

**Issue by sinister3vil** [freescout-helpdesk/freescout#921]
Hello,

Due to working with customers that user their own ticketing systems some conversations are broken and we merge replies manually.

There are multiple cases where the original conversation is closed.
Client then reverts that, say, issue persists. We merge this new conversation into the existing one, but it remains closed.
Merging should at least re-open the conversation and in a best case scenario be considered as new replies, triggering whatever events a new reply usually triggers, maybe with the exception of notifications.

**Comment by fulldecent** [comment]
Could you please reproduce with video in the latest 1.8 versions?

**Comment by freescout-helpdesk** [comment]
Just manually change conversation status after merging.
