### ISSUE TITLE
Feature request: Reports

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#926]
The filters in the reporting module are limited. It is important to be able to filter on multiple tags or users. It will be helpful to extend the functionality and use saved search filters to generate reports.

**Comment by freescout-helpdesk** [comment]
Maybe will be added after several months.

**Comment by freescout-helpdesk** [comment]
Most likely will not be implemented by FreeScout Team. If anybody want they can implement it: https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs
