### ISSUE TITLE
Custom folders are missing an important option

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#929]
When showing tickets in a custom folder - For example: "Ideas" - by filtering all "Pending" tickets with a tag "Idea", then there should be an option to "Hide tickets from  other folder".

That way I can virtually move mails  into a custom folder instead of only showing it there.
Depending on what I intend this makes other lists more uncluttered.

This would also solve #932 , but in a different way. Maybe even better and more elegant because it's a module.

**Comment by freescout-helpdesk** [comment]
Most likely will not be implemented. 

See "Can I change module's code according to my needs?"
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#can-i-change-modules-code-according-to-my-needs

**Comment by nickbe** [comment]
Ok let me put it like that: Would you offer to make such modifications if we simply pay for them?
