### ISSUE TITLE
Send history setting in ticket not for future replies

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#930]
A while ago you have added my suggestion (code) that you can choose what history you want to send with a ticket.
You guys have transferred this to the send button to edit the 'conversation history'.
If i set this to 'do not include previous messages' it is only for this reply, not a setting for the ticket in the future.

The biggest reason i need this is because that my reply is not deleted from replies coming from:
Outlook
Windows Mail
Helpscout

To make sure i do not send a lot of duplications the whole time i like to set the setting 'conversation history' to 'do not include previous messages'

**Comment by freescout-helpdesk** [comment]
Can be adjusted in Manage > Settings > Emails to Customers

**Comment by joris85** [comment]
Well, that is in general, thats not what i need.
For all other customers but Outlook, Windows mail, Helpscout i want to send the full history (see other ticket about this  #883) 
So i need to set it in the ticket, not only that specific reply.
That was how it supposed to work (for me) :-)

But again mostly this feature is because of the issue in the other ticket: #883

**Comment by freescout-helpdesk** [comment]
So this need to be fixed: https://github.com/freescout-helpdesk/freescout/issues/883
