### ISSUE TITLE
After closing a ticket - starred mail should also be de-starred.

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#931]
Otherwise we have to remember to remove the star manually afterwards.

**Comment by fvdm** [comment]
I disagree. There are closed mails that contain information useful for other conversations and stuff. Stars make them easy to find.

**Comment by freescout-helpdesk** [comment]
Won't be implemented in to core. Feel free to implement via custom module.

**Comment by nickbe** [comment]
Why not discuss such matters with us? We are actually trying to make this thing better and we put considerable time into testing and thinking about improvements that might be helpful in an everyday scenario. We are willing to pay tribute and/or invest our own time. But I'm not sure that you're really interested in improvements any more. Which would be a pity.

That standard text _"Won't be implemented in to core. Feel free to implement via custom module."_ is not very helpful guys. 😞

**Comment by fvdm** [comment]
@nickbe
> But I'm not sure that you're really interested in improvements any more. 

That's rude. They are maintaining FS in a good way, constantly adding new stuff and integrating our feedback. Sure the communications are a bit short and sometimes tickets are closed a little too soon, but then again there is also a lot of feedback to keep up with. So for a really nice and free open source project with an public community they are doing pretty damn good.

**Comment by nickbe** [comment]
>tickets are closed a little too soon

That's what bothers me. But then don't get me wrong.
I've just implemented another step towards an improvement dashboard view for mobiles screens, a dashboard filter to make it easier when coping with many mailboxes and the "delete mails after fetching" option with 4 different options for mailbox settings. I'll create the pull request over the xmas days.

So I'm willing to invest time and money in freescout. But I want to make sure that there's feedback from the developers.
Right now I thought that you are in fact one of the developers.

**Comment by fvdm** [comment]
> Right now I thought that you are in fact one of the developers.

Ha, no sorry. I'm a volunteer at a non-profit where FreeScout turns out to be a great solution for some of our groups communication needs. I think it can be useful for more of our groups with some improvements here and there. That's why I'm so eager to jump into discussions and submit PRs. There are some really good ideas here and devs who can actually make it happen.

I do agree it would be nice if official replies contain explanations for rejects or at least leaving tickets open for discussion or to allow someone in the community to find a solution. We are not just users, most Github members have an engineering background.

**Comment by nickbe** [comment]
Interesting 😁 But it's good to have someone else here who is eager to improve the system.
Beside myself I've already told one of my programmers to help here too. This might take some weeks, but it will happen.
Myself I don't have that much time for now. But since we've finally decided to stick with freescout, this means that freescout will improve a lot from our side. We have currently 25 mailboxes - for different projects and departments. So the system will be active enough to have a real life experience. I think we will find out what's missing and we will help to add several features.

I've just some pull request for the "delete mails" feature as well as the dashboard filter. Both are working, but especially the different options in  for the "delete mails" feature have to be tested thoroughly.
