### ISSUE TITLE
Missing status "Deferred"

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#932]
Now that I'm actually working with freescout I'm missing one status "deferred" or "on-hold" to withold tickets completely until needed. On the other hand would I prefer that the status "spam" is removed from the dropdown and instead moved to the "..." submenu.

**Comment by freescout-helpdesk** [comment]
Won't be implemented in to core. Feel free to implement via custom module.

**Comment by nickbe** [comment]
As I said, this could be easily solved with some tweaking of the custom folders module. We'll try to modify it for you if you don't have the time. Just tell us if you're interested in improvements.

**Comment by freescout-helpdesk** [comment]
Pull requests are always welcome. Just make sure to describe the implementation before implementing it, otherwise it can be a waist of time. Also see https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#general-guidelines
