### ISSUE TITLE
Suggestion - A combination button between "Me" and "Active"

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#933]
I suggest a third one-click button "grab now" - to immediately assign a ticket to "Me" and to set its status to "Active"

**Comment by fvdm** [comment]
Or create a manual Workflow with both actions. It will appear in the `...` menu > Workflows.

**Comment by freescout-helpdesk** [comment]
Won't be implemented in to core. Feel free to implement via custom module or use Workflow.

**Comment by nickbe** [comment]
@fvdm - So what would actually come on handy would be having direct shortcut buttons for workflows. And probably rights for workflows - some might be suitable for users, others only for admins. Is that possible in a module?
