### ISSUE TITLE
PHP Problem

### ISSUE THREAD

**Issue by djcroman** [freescout-helpdesk/freescout#934]
I install Freescout on a new Server with Plesk
Everything is fine so far.
However, I can not manage a cron for the email retrieval.
Manual retrieval works without any problem.

I have already tried both variants.

php /var/www/vhosts/mydomain/httpdocs/artisan schedule:run >> /dev/null 2>&1
/opt/plesk/php/7.4/bin/php /var/www/vhosts/mydomain/httpdocs/artisan schedule:run >> /dev/null 2>&1

I also do not get an error message
anyone an idea?
thanks

**Comment by fvdm** [comment]
In Plesk it is best to setup scheduled tasks within the domain section where you installed FreeScout. There you choose `PHP 7.4` (or at least the same you use for the FreeScout web interface). Set the first field to `httpdocs/artisan` and the second to `schedule:run`.

Then click Run Now and see if you get any errors. If not, then save the cron job.

**Comment by djcroman** [comment]
> schedule:run

You Great. Thank you so much. Now the Cron runs without any Problems

**Comment by snapptm** [comment]
I am also needing help with this.. This is my first Plesk server, setup in a test environment.  I have installed Freescout, and cannot get  a cron setup to fetch emails. 

this is what i Have. I copied this from the System status page .  What should my cron actually look like ? any help will be greatly appreciated 

/var/www/vhosts/mydomain/httpdocs/freescout1/artisan schedule:run >> /dev/null 2>&1

**Comment by fvdm** [comment]
@snapptm See my comment earlier: https://github.com/freescout-helpdesk/freescout/issues/934#issuecomment-745495573

In your case set the first field to `httpdocs/freescout1/artisan` and the second field to `schedule:run`

Do not include the output redirection `>> /dev/null 2>&1`.

**Comment by freescout-helpdesk** [comment]
![144033340-39f1c5be-e853-4717-a9de-466db4dcc575](https://user-images.githubusercontent.com/40499291/144038028-4c06ba43-c414-4ca5-af39-e5673e14b53d.jpg)

**Comment by erichelch** [comment]
Sorry, but on Plesk I have different entries - all others brought me errors.
Type: Run PHP-Script
Path: /var/www/vhosts/domainname/httpdocs/artisan with arguments: schedule:run
PHP-Version: choose the same as the webserver runs with (here 8.2.20)
run with: Cron-Stile and * * * * *

This runs for me without any error
<img width="948" alt="Bildschirmfoto 2024-07-08 um 16 46 11" src="https://github.com/freescout-help-desk/freescout/assets/33357253/2261a8dd-5a8d-4169-9a2b-813decd86dc3">
