### ISSUE TITLE
[request] full thread forwarding

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#935]
Hi Support
when forwarding an email, can it be possible to forward the entire conversation since the start.
This could be an option, 

forward current conversation
or
forward entire conversation

Please let us know if this is possible
thanks
M.

**Comment by fvdm** [comment]
With the arrow part of the Forward button you can choose how much history you want to include.

**Comment by raramuridesign** [comment]
Ok, brilliant, that was a bit hidden
For reference for anyone else

1. click forward
2. choose the dropdown before you forward and click on conversation history
![image](https://user-images.githubusercontent.com/902376/102266715-1d1b6900-3f19-11eb-930a-27309cee7323.png)
3. Then choose if you want to send full or partial

Thanks @fvdm
