### ISSUE TITLE
Time tracking not working properly because of bug

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#936]
The time tracking was installed, deactivated after some testing and now reactivated to go live.

It's set to:
"The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation."

But when I navigate away from the ticket then the timer just continues to run.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/592#issuecomment-731519361
