### ISSUE TITLE
API feature create conversations

### ISSUE THREAD

**Issue by sebclemens** [freescout-helpdesk/freescout#937]
Hello,

the main reason why I bought the API module was to create conversations. Unfortunally it's not possible, I would like to push this. Is this on the roadmap?

**Comment by freescout-helpdesk** [comment]
All the methods are described here: https://api-docs.freescout.net/

Not very soon.

**Comment by freescout-helpdesk** [comment]
"Create Conversation" and "Create Thread" API methods have been added in the API & Webhooks Module v1.0.6

See docs: https://api-docs.freescout.net/
