### ISSUE TITLE
Conversation closed_at missing

### ISSUE THREAD

**Issue by tillmon** [freescout-helpdesk/freescout#939]
if in mailbox settings status after reply is set to "closed", closed_at is not set of the conversation.

**Comment by tillmon** [comment]
Still not completely resolved. See https://github.com/freescout-helpdesk/freescout/commit/fe694de119b7153917329b86a2252453d8b6922e#comments

**Comment by freescout-helpdesk** [comment]
Works fine for us. `closed_at` is set when creating a new closed conversation:

![2020-12-24_10-20-16](https://user-images.githubusercontent.com/40499291/103070011-ae51a600-45d1-11eb-927d-fa1450a0f144.png)

**Comment by fulldecent** [comment]
Recommending to close as stale and no repreduction
