### ISSUE TITLE
Question about Cronjob

### ISSUE THREAD

**Issue by eickit** [freescout-helpdesk/freescout#942]
Hello, can someone tell me how I have to enter the cronjob in Plesk? Unfortunately, I have little experience.
Which of the 3 task types do I have to select? And what are the correct entries?
Many thanks for a tip! Sven

<img width="814" alt="screenshot_201217081247" src="https://user-images.githubusercontent.com/4112464/102455415-decc9980-403f-11eb-8612-9a9405135c85.png">
<img width="819" alt="screenshot_201217081304" src="https://user-images.githubusercontent.com/4112464/102455427-e12ef380-403f-11eb-931c-9bc52456434c.png">
<img width="956" alt="screenshot_201217081318" src="https://user-images.githubusercontent.com/4112464/102455436-e55b1100-403f-11eb-91e3-21b63d22117f.png">

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/934#issuecomment-745495573
