### ISSUE TITLE
[workflow assignment log] issue with assignment and workflow assignment error

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#943]
Hi Support 
we are getting this error on assignment, can you provide guideance on how to solve this?

![image](https://user-images.githubusercontent.com/902376/102478778-4b569100-405e-11eb-9a20-ee985841686d.png)

Fetch Logs Error
Dec 17, 10:44:02 | Error fetching email | From address service@xxx.com is not the same as user 13 email: service1@xxx.com

What we are not certain is why this is happening.

We also have a workflow setup, it assigns the item, and then triggers the above note and error.

Please let us know how to solve.
Matthew

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here. Check your mail server, etc.
