### ISSUE TITLE
Feature request: Please make workflows directly available from the toolbar

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#950]
It would be much nicer and quicker to access manual workflows directly from a button on the toolbar instead of having to first click the ... (more action), and then click Workflows.

**Comment by fvdm** [comment]
There is little toolbar space left on mobile portrait view. But that can be easily resolved by remove the arrow-parts of the Assign and Status buttons. They have no special value anyway.

**Comment by freescout-helpdesk** [comment]
You can use https://freescout.net/module/keyboard-shortcuts/

**Comment by justajeffy** [comment]
The functionality I'm requesting already exists in the lists of conversations when you select them.

![runworkflow](https://user-images.githubusercontent.com/11652559/103007171-f1901400-4500-11eb-8b7a-9661cfa9bce4.jpg)

I just want to have this same button/dropdown also available directly on the toolbar when viewing a conversation.  That would be much more intuitive for new users than having them learn keyboard shortcuts.

**Comment by fvdm** [comment]
Also keyboard shortcuts are not available with onscreen keyboards, like smartphones and tablets.

**Comment by MarcoWel** [comment]
- Could you make workflows available on the Ticket View as well?
- Could you make workflow actions groupable just like saved replies?

That way, we could define certain replies and reply to tickets with just a single click (or do some other more complicated actions).
