### ISSUE TITLE
Feature request: custom fields in end-user portal

### ISSUE THREAD

**Issue by justajeffy** [freescout-helpdesk/freescout#951]
It would be desirable to have an option to include certain custom fields directly into the end-user portal form so that submitters can help pre-fill data.

**Comment by nickbe** [comment]
In my opinion the end-user portal is not production ready as long as there's not option for customers to log in and review and answer their tickets.

**Comment by amirseafresh** [comment]
> In my opinion the end-user portal is not production ready as long as there's not option for customers to log in and review and answer their tickets.

This was addressed in a recent update I believe. 

Second the ability to add custom fields on the end user portal! would be great

**Comment by fulldecent** [comment]
This is addressed in https://freescout.net/module/custom-fields/

**Comment by fulldecent** [comment]
Recommending to close issue as fixed
