### ISSUE TITLE
Plus addressing

### ISSUE THREAD

**Issue by jtagcat** [freescout-helpdesk/freescout#952]
Plus addressing is this: `mailbox+foo@domain.tld`

Allow assigning a thread to user foo. This way it works like an extension code (if you'd call somewhere).

Foo could also be used for custom folders (don't auto-create them though) or tags.

**Comment by fvdm** [comment]
+1

FreeScout does correctly route VERP addresses but it appears the tag is ignored by the Workflows module. Would be very useful for auto tagging and assignments.

**Comment by freescout-helpdesk** [comment]
Can be implemented via custom module. Not needed in the core.

**Comment by jtagcat** [comment]
Is there an issue tracker somewhere else serving as a custom module wish list?

**Comment by freescout-helpdesk** [comment]
https://freescout.net/request-feature/

**Comment by jtagcat** [comment]
Now at https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/326245

**Comment by jtagcat** [comment]
Also, downstream issue: https://git.k-space.ee/k-space/overnode-cluster/issues/55
