### ISSUE TITLE
Recognize more reply headers sent by customers.

### ISSUE THREAD

**Issue by jtagcat** [freescout-helpdesk/freescout#953]
For example, thunderbird:
```
Customer reply

On {date} {time}, {name} wrote:
> Mail content
> adlkjsadljsadljsad
>
> --
> Freescout helpdesk
--
Customer signature
```

Freescout successfully recognize the mail content, and the customer's signature, but leaves the line with 'On...'. This is shown as the reply:
```
Customer reply

On {date} {time}, {name} wrote:
```

**Comment by freescout-helpdesk** [comment]
If someone can make it 100% reliable please implement.

**Comment by jtagcat** [comment]
Nothing is never 100% reliable.

I think a better way to put this, is 'If somebody can increase reply header detection with high confidence (fail-safe to not detect things 'maybe is reply header') significantly, please implement.

The most confidence can probably be gained by implementing many translations of the more major mail clients.

Data points (what I could think of rn):
 - It seems that most clients quote the whole message.
 - Before quotation, a single line:
   - the date, often the time, when mail by Freescout was sent. There're various date formats, time formats seem to often be in 24h, but whatever is looking for the reply body header, could (not regex, but kind of) look for the 12h HH:MM as well.
   - The line seems to always end with a colon.
   - The lime seems to always start with a capital letter.
   - The line seems to often contain the display name of Freescout.
 - Take all the translations of major mail clients. From memory, these would be (by order) Gmail, Thunderbird, and Apple Mail. It is highly likely, that other mail clients imitate the reply headers of these clients, as such, implementing even a single one of them (even if only English, the default, and as such, the most used) would allow detecting say half of the reply headers with high confidence.

**Comment by fulldecent** [comment]
Are there other larger open source projects that have solved this across languages and clients which we can study?

**Comment by freescout-helpdesk** [comment]
The thing is that there are already a lot of issues with customer replies being truncated: https://github.com/freescout-helpdesk/freescout/issues/3235
So we are a bit hesitant to implement this as most likely it will add issues with customer reply gets incorrectly truncated.
