### ISSUE TITLE
Assign based on name featured in the header.

### ISSUE THREAD

**Issue by jtagcat** [freescout-helpdesk/freescout#954]
There should be 'assign suggestions', what direct the mail to the person, but not definite assignments.

There're many (automated) mails like:
```
Hi, First Last

asdsaaösdkasdölksad
```

(Suggest) assignment to First Last.

**Comment by nickbe** [comment]
Very good idea. This should be quite easy to realize.

**Comment by freescout-helpdesk** [comment]
This may and will have side effects. Not needed in the core.
