### ISSUE TITLE
Missing option to have an "internal" conversation.

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#955]
Currently there's either a convertsation between staff and external mail adresses, OR "notes" which are not really like an internal back and forth conersation at all.

Wouldn't it be easy to let freescout check wether communication was started with an "interal" mail adress and then handle it accordingly. Then we could start a real "internal" conversation by mail.

**Comment by freescout-helpdesk** [comment]
No plans to add it to the core. Can be implemented via a custom module.
