### ISSUE TITLE
Mailbox settings fetch all

### ISSUE THREAD

**Issue by tillmon** [freescout-helpdesk/freescout#956]
It would be helpful if you could configure fetching all / unseen messages in mailbox connection settings. Use case is if mails are fetched from a subfolder where emails are moved into and read status is set.

**Comment by freescout-helpdesk** [comment]
The option is not needed in the app. Can be implemented using hooks.

**Comment by tillmon** [comment]
Can you please explain what you mean by implementing using hooks. Just to clarify I only want to activate "fetch all" for one mailbox and not for all, since I expect it to be very resource hungry.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#actions-and-filters and use them in custom module.

**Comment by tillmon** [comment]
I do not see a way to implement this without changing the app. There is no suitable hook to overwrite the unseen option. I can create a custom module where you can chose if only unseen or all emails are fetched for each mailbox individuell. But I don't know how this can be hooked into the fetch command what is called by the `schedule:run` cron task.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/search?q=Eventy%3A%3Afilter

Also see how to use actions & filters in the [Modules Development Guide](https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development).

**Comment by nickbe** [comment]
I've just made a pulls request with settings for incoming mail handling. I could add a fifth option that simply read ALL unread mails. Then you would only have to set all your mails to unread and you're good to go.

**Comment by tillmon** [comment]
@freescout-helpdesk suggested implementing this feature with a custom module using hooks. I agree with that, since it keeps the app clean. This is better placed in e.g. a MailboxAdvancedSettingsModule. However some hooks are needed, see #959.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/pull/959#event-4146464592
