### ISSUE TITLE
How to send an email answer to a phone-initiated case?

### ISSUE THREAD

**Issue by colegatron** [freescout-helpdesk/freescout#958]
Whenever a colleage opens a new case from a phone-initiated call, usually we need to reply via email to the customer.
I have tried to create a 'new conversation' type 'phone' instead email and this adds a Note which is private and it is OK.
Then, when someone manages the case and wants to answer by email to the customer, there is a 'Forward' in the 'more actions' menu, but it does nothing when I click on it.
I expect to be able to send an anwer to the end user with the solution of the case. The case turns into a 'email type' case, since the customer will be able to reply to our answer.

There is any way to do it?

BTW, The case has an empty 'Waiting since...' column in the issues list for the 'phone cases', so it does not gets sorted properly, making harder to manage it for other people in the support teams.

**Comment by freescout-helpdesk** [comment]
It's not possible for now.
