### ISSUE TITLE
/Install redirects to Login Screen

### ISSUE THREAD

**Issue by astupidmoose** [freescout-helpdesk/freescout#96]
Hello, 

I've tried installing twice, and both instances I get stuck when trying to goto the install wizard. I am simply redirected to a login page, but I have no credentials yet. 

Is this a known issue? 

Using ubuntu 16.04 off a digital ocean base install.

**Comment by freescout-helpdesk** [comment]
Hi,

So you followed [Installation Guide](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide) and on step **8. Installing the Application** you are being redirected to the login page?

**Comment by astupidmoose** [comment]
Yes, correct. 

going to mydomain.com/install simply redirects to mydomain.com/login upon installation. 

DB is MariaDB. Webserver is Nginx.

**Comment by freescout-helpdesk** [comment]
Try to open:
/install.php
/install?nocache=1

**Comment by astupidmoose** [comment]
Both immediately redirect to /login without ever seeing the installer page

**Comment by astupidmoose** [comment]
Not sure if this will help, but i've set debug on and it looks like install is attempted at some point before login: 

![image](https://user-images.githubusercontent.com/3916318/48181053-d6d79280-e2da-11e8-8333-3496044b6320.png)

**Comment by astupidmoose** [comment]
Yes, I had 3 .env files: 

.env
.env.example
.env.travis

I removed all 3 and then was able to visit /install.php where it stated:

> Web installer will need to create .env file in the root folder of your application. Please run the following commands in SSH console to allow the web server to write to the root folder:
> 
> sudo chgrp **_freescout_** /var/www/html
> sudo chmod ug+rwx /var/www/html

This is a bit different from the install instructions: 

> > sudo chgrp **_www-data_** /var/www/html
> sudo chmod ug+rwx /var/www/html

However after running both, I was still seeing the same error. 

I manually created a new .env file based on the example one which brought the following into the installer:

> Please run the following commands in SSH console:
> php artisan key:generate
> php artisan freescout:clear-cache

After running this.. It starts redirections to the login screen again :(

**Comment by freescout-helpdesk** [comment]
2 installation methods have been explained in the guide: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#8-installing-the-application

Web installer is not working because your web server can not create `.env` file in the root folder (most likely due to permissions issue). So if you can not fix this permissions issue, just follow "8.2 Manual installation": https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#82-manual-installation

**Comment by astupidmoose** [comment]
What are the proper permissions? They are being set based on the above however it's still not working. 

Creating a manual user gives the following errors on creation:
In Connection.php line 452:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'freescout.users' doesn't exist

I'm assuming the web installer would be inserting tables into the database and since this has not been completed then there is no table to add to? The installation steps only creates the raw DB and doesn't seem to create tables.

**Comment by freescout-helpdesk** [comment]
Yes. Sorry, one instruction is missing in the manual installation:
```
php artisan migrate
```

**Comment by astupidmoose** [comment]
OK that managed to work. 

Still not sure why I couldn't bring up the installer but past that now. Hopefully if others have the same issue they can see this and do manual install
