### ISSUE TITLE
same origin bug in end user portal

### ISSUE THREAD

**Issue by vikasprogrammer** [freescout-helpdesk/freescout#965]
I am getting following error while embedding the end user widget on a third party website
<img width="415" alt="Screenshot 2020-12-24 at 11 38 15 AM" src="https://user-images.githubusercontent.com/1262327/103065407-8e73af80-45dc-11eb-8828-dfa3b276fcdf.png">

<img width="411" alt="Screenshot 2020-12-24 at 11 38 24 AM" src="https://user-images.githubusercontent.com/1262327/103065400-8a479200-45dc-11eb-8543-359e3a00475b.png">

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of the module?

Are you experiencing this issue with demo.freescout.net widget form?

**Comment by vikasprogrammer** [comment]
1. Yes
2. No, I am using on my own domain.

**Comment by freescout-helpdesk** [comment]
Try to embed the widget from demo.freescout.net and let us know the results.

**Comment by vikasprogrammer** [comment]
The demo widget is working perfectly.

**Comment by vikasprogrammer** [comment]
It was my server's issue, I fixed it thanks for attending.

**Comment by freescout-helpdesk** [comment]
Can you tell what was the reason of the issue?
