### ISSUE TITLE
Extra Keyboard shortcuts 

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#969]
Hi guys,

So happy you guys created this module!
Use freescout now for a year and the last year you guys made it so much more fun to use it.
Wish you great 2021 guys!

Little bug or make it better: 
- 🐛  The add tag (T) does not focus the cursor in the tag field.
I would like to type right away and save it with an enter.
- ⭐  Some shortcuts could be activate in List view 
   - Workflow
   - Status
   - Assign 
   - Delete
   - Move

Suggest shortcuts: 
- Direct delete - ALT + D (the popup is not possible to enter, so this would skip the popup)
- Download attachements - ALT A

Suggestion new features:
- Set a shortcut in a workflow :-)

Thanks!

**Comment by freescout-helpdesk** [comment]
> The add tag (T) does not focus the cursor in the tag field.

This has been fixed.

Regarding the rest - feel free to add feature requests: https://freescout.net/request-feature/
