### ISSUE TITLE
Random ticket number

### ISSUE THREAD

**Issue by guestisp** [freescout-helpdesk/freescout#97]
Ticket number should be created randomly (or with something not easily guessable)

**Comment by freescout-helpdesk** [comment]
Conversation number (as dropdown, it would allow to add other formats if needed):
- Sequential number
- Random number
- Random numbers and letters

Max. 7 digits/numbers, longer ticket numbers may break the design.

`Next Conversation #` - keep it for now, just comment it out. Maybe somebody will need it.

**Comment by guestisp** [comment]
Can we use jQuery or something similiar ?

**Comment by freescout-helpdesk** [comment]
jQuery is already included in the project (see usage in `/public/js/main.js`)

**Comment by guestisp** [comment]
Yes, I seen.
Just a simple question: I have to add a simple javascript to be used in `general.blade.php`.
With a `@section('javascript')` i'm able to do, but it doesn't get minified. Is this an issue or do you have a way to minify javascript when called from a single view ?

**Comment by freescout-helpdesk** [comment]
Add function call to the bottom of the template:
```
@section('javascript')
    @parent
    initGeneralSettings();
@endsection
```

and add `initGeneralSettings()` function to the main.js
