### ISSUE TITLE
Woocommerce multiple shops

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#970]
Hi guys,

I am interested in extending the woocommerce plugin to multiple shops.
For now 2
So in the settings an option to add another shop :-)

Is this coming or should i make that myself and send you guys that update?

**Comment by freescout-helpdesk** [comment]
WooCommerce should be configured per mailbox: https://github.com/freescout-helpdesk/freescout/issues/857
Current implementation settings WooCommerce globally should be preserved.

Feel free to implement.

**Comment by freescout-helpdesk** [comment]
In WooCommerce Module v1.0.1 per mailbox configuration is supported.
