### ISSUE TITLE
API Module – Create Conversation method with Phone only, No Email

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#972]
Firstly – many thanks for recently updating API / Webhooks Module to support Conversation and Customer Creation!

We use FreeScout mainly for Phone Messages and Call Back Requests.  We capture these in a special Webform and would like to push them into Freescout formatted better then pushing in via Email (on Form Submission) at present.

I would like to use API Module to Create Conversation / Create Customers by supplying only a Name and Phone Number (rather than Email Address) – Can the module be updated to support that?  All documentation says Email field is Mandatory so I would like to see either Phone or Email Mandatory, to allow this.

**Comment by freescout-helpdesk** [comment]
You already can pass only phone. We will update the docs.

**Comment by luketrip** [comment]
Thanks for the quick reply!  Can you please provide a example payload as when I try any variation in Postman, I get a 302 Response and it always creates a new Customer ID.  I am not getting the expected 201 (on a new unique entry) and the fact it keeps creating Customer IDs even though the payload is identical is not ideal....

What should happen if I attempt to create a Customer with the same details as a existing one - will Freescout API return the existing Customer ID or return a Error that it already exists?  If it only returns the error, then I am unable to create the conversation as there is no way to know what ID to use for it?

If I use the sample payload form the API Docs, I get the error saying the Email already exists.

This is why I was hoping "Create Conversation" method could be changed so it can will work with only just a Phone Number, so if it is not found/matched the Customer is created, and if it does exist/matches, the conversation gets created against the existing match.

`{
    "firstName": "Mark",
    "lastName": "Morrison",
    "phone": "123",
    "phones": [
        {
            "value": "123",
            "type": "home"
        }
    ]
}`

**Comment by freescout-helpdesk** [comment]
Please provide:
- Method name(s)
- Request JSON
- Response JSON
