### ISSUE TITLE
Allow Users to manage workflows

### ISSUE THREAD

**Issue by avegalco** [freescout-helpdesk/freescout#973]
Dear team.
Just purchased the Workflows module but looks like only administrators can manage workflows, and users should be able to do so as described here:
https://docs.helpscout.com/article/22-get-started-with-workflows
Note: By default, only Administrators and Account Owners can create and manage workflows. If you want all of your Users to manage workflows as well, change that permission from the Company settings page. 
Thank you.

**Comment by fvdm** [comment]
FreeScout is not from the same company as HelpScout

**Comment by avegalco** [comment]
Of couse, I now. Just mentioned that product to show that the request makes sense.

**Comment by tiredofit** [comment]
It's been mentioned a couple of times. I commissioned a PR to create individual permissions for users a while back and couldn't implement the same functionality for the workflow plugin as I didn't want to mess with the code, but I am with you 100% - At least having feature parity with user capabilities similar to the tags/auto responder functionality to be issued on a per user basis would allow a member who is not "Admin" to create advanced workflows, thus reducing dependencies on the systems administrator.

See #840 for a previous discussion. Apparently there was some hope that it was coming in 1.6.11 as shown by developer, but I am not seeing the capabilities to allow certain users to update workflows.

**Comment by freescout-helpdesk** [comment]
We will try to add this feature to the module.

**Comment by freescout-helpdesk** [comment]
Permission to allow users manage workflows added in Workflows Module v1.0.18

**Comment by tiredofit** [comment]
How does an Admin assign the permissions to a user? I can't see from the Mailbox permissions view or directly on the user view.
Perhaps it's still needed to be added into the core software.

**Comment by freescout-helpdesk** [comment]
FreeScout v1.6.11 is enough.

![2021-01-05_20-17-20](https://user-images.githubusercontent.com/40499291/103677232-15d50180-4f93-11eb-8309-6ece2a4cd0dc.png)

**Comment by tiredofit** [comment]
Ahh ok I see it. I thought it was taking advantage of the "Mailbox Managers" functionality. Personally my views of offering it to all the users is dangerous in a large mailbox with many users, and better to be able to dictate "which" users. Regardless, I appreciate the addition at this point.

**Comment by freescout-helpdesk** [comment]
Also can be adjusted on each user's Permissions page.

**Comment by avegalco** [comment]
Module updated to last version, now the option is shown at manage - settings.
Wonderful, thank you!

**Comment by tiredofit** [comment]
Perfect! I see it now! It's a per user not per mailbox. That is good enough for me!
Many thanks.
