### ISSUE TITLE
Api - Expand Get Conversation

### ISSUE THREAD

**Issue by sylvia83** [freescout-helpdesk/freescout#976]
It would be great to be able to use the GET api/conversations with filters for mailboxid and status and get back a list of the conversations matching those criteria. It would also be nice to be able to filter by one or more customer emails and assignee. This could be used to integrate Freescout with other software and allow an easy way to show open tickets according to mailbox, status, or customer(s).

**Comment by freescout-helpdesk** [comment]
List Conversations method added to the API: https://api-docs.freescout.net
