### ISSUE TITLE
Feature request: tag color picker

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#977]
The set of colors available for tags is limited. 

Please implement a basic color picker with the ability to set any color with the hex color code or at least expand the palette.

**Comment by freescout-helpdesk** [comment]
Unfortunately no plans to implement this.

**Comment by afawaz2** [comment]
How can we add feature requests to your backlog? It seems that a lot of feature requests get closed.

**Comment by freescout-helpdesk** [comment]
Here: https://freescout.net/request-feature/
