### ISSUE TITLE
User notification failing after latest workflow update module

### ISSUE THREAD

**Issue by nalafod** [freescout-helpdesk/freescout#979]
We have noticed since issuing the update the bellow error and no user notification is sent.

I am reporting it here because nothing change rather than running the latest workflow update. 

Outgoing email log:

type User notification
Send error. Call to a member function isAdmin() on null (View: /var/www/html/resources/views/emails/user/notification.blade.php).

Send errors log:

Error sending email to user | Call to a member function isAdmin() on null (View: /var/www/html/resources/views/emails/user/notification.blade.php); File: /var/www/html/Modules/Workflows/Entities/Workflow.php (1372)

Email to customers is working

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v.1.0.19

**Comment by nalafod** [comment]
> Fixed in Workflows Module v.1.0.19

Perfect thank you
