### ISSUE TITLE
send.php service.freescout.net

### ISSUE THREAD

**Issue by jesulo** [freescout-helpdesk/freescout#980]
Hi, 
I have bought the push notifications module, I am curious to know how to identify the user when entering the webview application, how do you know that this application corresponds to a specific user so that the correct push message arrives? Cheers

**Comment by freescout-helpdesk** [comment]
See:
https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated
https://firebase.google.com/docs/cloud-messaging

**Comment by jesulo** [comment]
Hi thanks for answer.


I've been seeing how FCM works, I have the following query, how do you assign users by device? I saw in the backend that you use topic per user which you create with md5 (\ Helper :: getAppIdentifier (). $ user-> id);
but how do you subscribe the device to this topic? Does the mobile application take the id of the user and the url of my server? At the application level, how do you subscribe that data? thanks

**Comment by freescout-helpdesk** [comment]
In short it work like this:
1) User logs in in the mobile app.
2) App connects to Google FCM and subscribes the mobile device to notifications.
3) When some event happens in your FreeScout, it connects to service.freescout.net and sends notification to user mobile device via Google FCM.

**Comment by jesulo** [comment]
2. How is identified the user log in with subscribes mobile?

**Comment by jesulo** [comment]
my query is like this link https://stackoverflow.com/questions/54808304/send-player-id-from-onesignal-into-webview-android-studio       


this in freescout backend
 // Add module's JS file to the application layout.
        \Eventy::addAction('javascript', function() {
            $user = auth()->user();
            $topic = '';
            //$token = '';
            if ($user) {
                $topic = self::getUserTopic($user);
                //$token = $user->getAuthToken();
            }
            // inAppSendData('<?php echo $topic; ? >', '<?php echo $token; ? >');
            ?>
                fs_in_app_data['topic'] = '<?php echo $topic; ?>';
            <?php
        });
