### ISSUE TITLE
Question: Ticket visibility

### ISSUE THREAD

**Issue by bjoernhasse** [freescout-helpdesk/freescout#981]
Hello 👋 

is it possible to have a user who can only see tickets assigned to him?
So to hide all other tickets that he is not assigned?

Thank you
Björn

**Comment by freescout-helpdesk** [comment]
It's not possible.

**Comment by infornet1** [comment]
Hi, lt's looks like not possible, any idea how could workaround this issue? Trying to only allow users see owns tickets assigned. Thks

**Comment by freescout-helpdesk** [comment]
Via a custom module. Feel free to add a feature request here https://freescout.net/request-feature/. Maybe someone will create a module.
