### ISSUE TITLE
More actions in conversations listing

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#987]
Hey there,

I noticed a lack of actions when selecting one or multiple conversations in a conversation listing. Currently, you can only assign, flag and delete conversations.

![image](https://user-images.githubusercontent.com/15019582/104048551-ad309380-51e3-11eb-8dde-92f1aff860ae.png)

It would be great if some more actions were added. I am thinking of merging, following and moving conversations. 

Keep up the good work!

**Comment by matsn0w** [comment]
By the way, Laravel is in my next semester so I'm hoping to be abled to add things like this myself soon :)

**Comment by fvdm** [comment]
I think it needs an extras button with drop menu for these actions, because with modules there is not a lot of space left on small screens:

![image](https://user-images.githubusercontent.com/93784/104121677-61dfc780-5340-11eb-8dfa-dfd7b34ce93c.jpeg)

**Comment by joris85** [comment]
Good ideas!

**Comment by fulldecent** [comment]
The extra actions button is here

<img width="834" alt="Screen Shot 2022-10-12 at 10 06 53" src="https://user-images.githubusercontent.com/382183/195365221-37cc5f0d-34d4-4542-ada6-16ccf0a9e8d1.png">

**Comment by freescout-helpdesk** [comment]
Closed as out of scope.
