### ISSUE TITLE
Auto-refreshing emails

### ISSUE THREAD

**Issue by matsn0w** [freescout-helpdesk/freescout#988]
Hey there once again,

When a new message drops, the 'unread' marker is updated automatically without refreshing the page - great!

However, when I'm staring endlessly at my screen to pass the time... It won't show me those new conversations!

Would it be possible to add that functionality? I've read #285. I don't htink this would really impact the performance of the application.

What are your thoughts of this?

Thanks again!

**Comment by fvdm** [comment]
That would be nice, but with a switch to the current style for high traffic mailboxes. Otherwise it may become hard to do bulk tasks while new stuff keeps flowing in.

Maybe auto-sensing based on bulk mode and incoming rate:
- if bulk on: notify
- else if >2 per batch: notify
- else: update message list

**Comment by matsn0w** [comment]
Good point. Maybe just stop updating as soon as the user selects a conversation.

**Comment by freescout-helpdesk** [comment]
Could you please clarify (with a screenshot) where you want to auto-refresh conversations.

**Comment by matsn0w** [comment]
![image](https://user-images.githubusercontent.com/15019582/104131345-10eac600-5376-11eb-9495-320676aa1da4.png)

Here, in the 'inbox'. It's probably not very important in other folders (for me, at least). But this is where the hot stuff comes in.

**Comment by freescout-helpdesk** [comment]
Conversations are already auto-refreshed and not auto-refreshed if there are selected conversation (to apply bulk actions).

**Comment by matsn0w** [comment]
Oh dear, just tested it out and indeed: it's already working! In my memory it only updated the amount of open conversations on the left. 

Lol, good job ;)
