### ISSUE TITLE
End User Portal

### ISSUE THREAD

**Issue by qsvch** [freescout-helpdesk/freescout#989]
I have just installed the End User Portal Update to version 1.07 with pleasure. 

It's brilliant what new features have been opened up for the customer with the login. Only the design (colour, footer and logo) would be nice if it could be adapted!

We would be happy to provide the translation into German!

**Comment by freescout-helpdesk** [comment]
CSS can be adjusted using https://freescout.net/module/customization/

**Comment by qsvch** [comment]
Ahh, ok, thanks!

Could you publish an example for those who don't know CSS, how the code should look like for the adjustments of the colours in the bar and button?
