### ISSUE TITLE
Settings>General - "Spread the Word" turns back on when saved

### ISSUE THREAD

**Issue by astupidmoose** [freescout-helpdesk/freescout#99]
Clicking "Spread the Word" to turn off footer text automatically turns back on when saved.

**Comment by bitcoinshirt** [comment]
I have the same problem.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/fb24ccf50ecaed3b5c9e7018f64e3ff0e6642069
