### ISSUE TITLE
API / Webhook

### ISSUE THREAD

**Issue by solariz** [freescout-helpdesk/freescout#990]
Hey,

is there any maybe not listed requirements or known issues here?
Just installed the Webhook module and can't get it working.

On the webhook side I just do a simple log all to file to see if anything comes through. The hook is fired by freescout but with no POST data on it. In the webhook Configuration I just added all Events. The Status is telling me "OK" but if I click on logs it is just empty even it was triggered several times. If I let my script return a Status 400 it shows as error in the log, but 200 do not show anything. 

Problem is the received webhook call is empty.

For testing I call https://myserver.domain/scripts/webhooktest.php?test=1

the webhooktest.php is simple:
```
<?php
file_put_contents("/tmp/fsapi.log",strftime("%c\n")."POST:".print_r($_POST,true)."\nGET:".print_r($_GET, true), FILE_APPEND);
http_response_code(200);
echo "OK";
```

The temp File contains after call:

```
Mon Jan 11 09:40:07 2021
POST:Array
(
)
GET:Array
(
    [test] => 1
)
```

Thanks for any Ideas.

**Comment by freescout-helpdesk** [comment]
Anything in Manage > Logs > App Logs?

**Comment by solariz** [comment]
Unfortunately not, the emails got fetched correctly and appear in freescout, I also see the webhook firing if I e.g. change the status or reply to a conversation but it is empty.

Laravel Log, webserver log an fetch log doesn't show anything.
I also checked the PHP and FPM Error log on the server, nothing unfortunate.

**Comment by solariz** [comment]
ok, have another clue - the PECL hash isn't available on my system. Need to look into this. 

Is it maybe a fixed requirement? Even I want to send the webhooks to a script running locally without signing?

**Comment by solariz** [comment]
Hello Again,

back to the php hash PECL - it looks like it is deprecated and not maintained for a long time. Is it really a dependency? Can't get it running on a current PHP Version unfortunately.

Thanks

**Comment by freescout-helpdesk** [comment]
PECL is not needed.

**Comment by solariz** [comment]
Thanks, is there any way to enable some kind of debug log for the webhook? Even if I check a TCPDUMP from the outgoing request I see the request is made but with an empty POST Data object.

**Comment by freescout-helpdesk** [comment]
You may need to debug it manually.

**Comment by solariz** [comment]
Ok, solved - somehow.

Because freescout was running on a old debian VM and I want to upgrade it anyway I reinstalled it on a current ubuntu 20 LTS, moved all database and storage over and voila it's working now.
