### ISSUE TITLE
Embed images in reply emails

### ISSUE THREAD

**Issue by afawaz2** [freescout-helpdesk/freescout#991]
The use of static tokens for embedded images in emails is risky because those can be brute forced and those cannot be changed if they get compromised.

It makes sense to embed images using CID tags in reply emails instead of using permanent links.

**Comment by freescout-helpdesk** [comment]
This can be implemented using a custom module.

**Comment by afawaz2** [comment]
Can you please explain?

**Comment by freescout-helpdesk** [comment]
See https://github.com/freescout-helpdesk/freescout/wiki/Modules-Development
