### ISSUE TITLE
Shortcut C is an issue for copy paste.

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#992]
Hi Guys,

Love the shortcuts!
Now i have an issue with the Shortcut C.
When i select some text and click CMD+C i copy the text but a second later i have a new concept.
I Understand that i clicked on C but i use this dozen times a day :-)

Any idea how it can that it does not react on CMD+C but only on C?

**Comment by joris85** [comment]
I have creates already 20 concepts today because of this :-P

**Comment by freescout-helpdesk** [comment]
Maybe you click "C" first and after that click CMD?
Make sure to click CMD first.

**Comment by joris85** [comment]
Nope, Clearly first CMD and then C 
But probably a millisecond later i let go of the c then CMD.
Maybe that is the reason.

Is it an idea to let me change the shortcuts so i can choose another key.
Using a key i use at least 50 times a day in freescout is not so handy :-)

**Comment by freescout-helpdesk** [comment]
Please send output of https://jsfiddle.net/1rp8xfcg/

**Comment by joris85** [comment]
metaKey: false
key: 91

Though also sometimes, and i guess that is the moment i create a new ticket
metaKey: false
key: 67

**Comment by freescout-helpdesk** [comment]
In Keyboard Shortcuts Module v1.0.2 "New Conversation" shortcut has been changed to "Q".
