### ISSUE TITLE
Delete message breaks reply flow

### ISSUE THREAD

**Issue by BinaryMoon** [freescout-helpdesk/freescout#995]
Hi - when I am replying to messages if I delete a message it takes me to the list of messages. When I close a message it takes me to the next message in the list. I would like the delete option to take me to the next message. Otherwise I have to find where I was up to and go back into the messages.

It would also be nice if the close and spam options were on the toolbar as that would reduce the amount of clicks as well. :)

Thanks!

**Comment by freescout-helpdesk** [comment]
Closed as out of scope.
