### ISSUE TITLE
Search breaks when CRM module is activated

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#996]
I can confirm that once the CRM module (V1.0.1) is active and laravel cache is cleared, the search breaks and searching for something returns "Whoops, Looks like something went wrong".

Here's the log:

Class 'CustomField' not found (View: /var/www/html/Modules/Crm/Resources/views/partials/cf_search_filters.blade.php)

**Comment by freescout-helpdesk** [comment]
We will fix.

**Comment by andrewlimaza** [comment]
Thanks for that, will keep an eye out for the update. Please let me know if you need more information from our end.

**Comment by freescout-helpdesk** [comment]
Fixed in CRM Module v1.0.2
