### ISSUE TITLE
Workflow reply and User reply in the same time failed.

### ISSUE THREAD

**Issue by choletzke** [freescout-helpdesk/freescout#998]
Hi,

i have a problem when i reply a message and close the ticket with workflow reply.

1) i have a workflow that inform our customer via mail "your ticket #123 is closed"
2) our customer receive only the workflow message with "your ticket #123 ist closed" two times,
but not Our User reply from Ticket. when i check Outgoing mails, there were "no send attempts yet"

**Comment by choletzke** [comment]
it is solved now. My failure was forget to include "New / Reply / Moved" "User or customer replied" at workflow conditions

**Comment by freescout-helpdesk** [comment]
OK
